= Changelogs for Rudder plugin datasources 7.2.2-2.2.\* versions

== dsc-7.2.2-2.2 (2022-12-06)

=== Changes


==== Misc

* Add scoped variable support to the linter
    (https://issues.rudder.io/issues/22039[#22039])

=== Bug fixes

==== Miscellaneous

* Fixed: Rename technique parameters in rudder-directives.ps1 so that it works with changes from 14371
    (https://issues.rudder.io/issues/22062[#22062])
* Fixed: Plugin should not distribute test files
    (https://issues.rudder.io/issues/21973[#21973])

==== Agent library

* Fixed: rudder_client does not work on powershell 4
    (https://issues.rudder.io/issues/22112[#22112])
* Fixed: Support Powershell 4
    (https://issues.rudder.io/issues/22073[#22073])
* Fixed: Some policies are invalid with Powershell4
    (https://issues.rudder.io/issues/22076[#22076])

==== CLI

* Fixed: Typo in the rudder.ps1 parameter attributes
    (https://issues.rudder.io/issues/22032[#22032])
* Fixed: rudder agent version vanished from the agent in 7.2.0
    (https://issues.rudder.io/issues/21946[#21946])
* Fixed: Postinst does not setup correctly the user path variable
    (https://issues.rudder.io/issues/18852[#18852])

=== Release notes

This is a bug fix release in the 7.2.2-2.2 series and therefore all installations of 7.2.2-2.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.2.2-2.2 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.2 series and therefore all installations of 7.2.2-2.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== notify-7.2.2-2.2 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.2 series and therefore all installations of 7.2.2-2.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-7.2.2-2.2 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.2 series and therefore all installations of 7.2.2-2.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

