= Changelogs for Rudder plugin auth-backends 8.2.\* versions

== auth-backends-8.2.0-2.7 (2024-10-29)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.2.0.rc1-2.7 (2024-10-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.2.0.beta1-2.7 (2024-09-09)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Clarify that we do not support authorizations in OIDC authentification role in documentation
    (https://issues.rudder.io/issues/25280[#25280])
* Fixed: Typo for parameter enableProvisioning in documentation
    (https://issues.rudder.io/issues/25221[#25221])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.2.0.alpha1-2.7 (2024-09-09)

=== Changes


==== Refactoring

* Update scala plugin dependencies
    (https://issues.rudder.io/issues/24771[#24771])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

