= Changelogs for Rudder plugin change-validation 8.2.\* versions

== change-validation-8.2.1-2.4 (2024-11-28)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Change requests bar is no longer clickable
    (https://issues.rudder.io/issues/25741[#25741])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.2.0-2.4 (2024-10-29)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.2.0-2.4 (2024-10-29)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.2.0.rc1-2.4 (2024-10-18)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Remove use of the clipboardjs library
    (https://issues.rudder.io/issues/25660[#25660])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.2.0.beta1-2.4 (2024-09-09)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.2.0.alpha1-2.4 (2024-09-09)

=== Changes


==== Refactoring

* Update scala plugin dependencies
    (https://issues.rudder.io/issues/24771[#24771])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

