= Changelogs for Rudder plugin cve 8.2.\* versions

== cve-8.2.3-2.10 (2024-12-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.2.2-2.10 (2024-11-29)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.2.1-2.10 (2024-11-28)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Error 500 when browsing Vulnerabilities because of SQL error offset must not be negative
    (https://issues.rudder.io/issues/25601[#25601])
* Fixed: Add documentation for 8.2 features (Windows and CVE Groups)
    (https://issues.rudder.io/issues/25467[#25467])
* Fixed: CVE plugin may skip some request
    (https://issues.rudder.io/issues/25736[#25736])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.2.0-2.10 (2024-10-29)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Vulnerable packages table has table issue for colspan 
    (https://issues.rudder.io/issues/25698[#25698])
* Fixed: Lost color code for vulnerable/remediated vulnerabilities on nodes
    (https://issues.rudder.io/issues/25702[#25702])
* Fixed: CVE history is not correct depending on how CVE page is opened
    (https://issues.rudder.io/issues/25699[#25699])
* Fixed: Packages are duplicated when opening node details
    (https://issues.rudder.io/issues/25721[#25721])
* Fixed: Add KB in package name and remove some duplicated entries
    (https://issues.rudder.io/issues/25717[#25717])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.2.0.rc1-2.10 (2024-10-18)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Security benchmarks post-install fails without creating benchmark category.xml
    (https://issues.rudder.io/issues/25674[#25674])
* Fixed: Typo in UI
    (https://issues.rudder.io/issues/25672[#25672])
* Fixed: Amazon Linux is not supported
    (https://issues.rudder.io/issues/25546[#25546])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.2.0.beta1-2.10 (2024-09-09)

=== Changes


=== Bug fixes

==== Web - UI & UX

* Fixed: CVE plugin page could be loading indefinitely
    (https://issues.rudder.io/issues/25347[#25347])

==== Miscellaneous

* Fixed: Broken elm dependency
    (https://issues.rudder.io/issues/25271[#25271])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.2.0.alpha1-2.10 (2024-09-09)

=== Changes


==== Miscellaneous

* Make possible to create groups based on CVE
    (https://issues.rudder.io/issues/25147[#25147])
* Display the list of benchmarks as a datatable
    (https://issues.rudder.io/issues/25041[#25041])
* Log request made to check endpoint
    (https://issues.rudder.io/issues/21058[#21058])
* Log request made to check endpoint
    (https://issues.rudder.io/issues/21058[#21058])
* Make Windows CVE requests
    (https://issues.rudder.io/issues/24987[#24987])
* Update scala dependencies in private plugins
    (https://issues.rudder.io/issues/24774[#24774])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

