= Changelogs for Rudder plugin datasources 8.2.\* versions

== datasources-8.2.0.rc1-2.4 (2024-10-18)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Datasources tests are failling due to race condition
    (https://issues.rudder.io/issues/25497[#25497])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.2.0.beta1-2.4 (2024-09-09)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.2.0.alpha1-2.4 (2024-09-09)

=== Changes


==== Security

* Update js dependencies
    (https://issues.rudder.io/issues/24852[#24852])

=== Bug fixes

==== Miscellaneous

* Fixed: Datasources tests fail on 404
    (https://issues.rudder.io/issues/25085[#25085])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

