= Changelogs for Rudder plugin datasources 8.2.\* versions

== datasources-8.2.7-2.4 (2025-06-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.2.6-2.4 (2025-05-07)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Datasources link from plugin information page is broken
    (https://issues.rudder.io/issues/26764[#26764])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.2.5-2.4 (2025-02-27)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Datasources HTTP tests are failing in 8.2
    (https://issues.rudder.io/issues/26309[#26309])
* Fixed: in datasources, ids are not normalized, thus creating problems at deletion
    (https://issues.rudder.io/issues/26172[#26172])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.2.4-2.4 (2025-01-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.2.3-2.4 (2024-12-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.2.2-2.4 (2024-11-29)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.2.1-2.4 (2024-11-28)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.2.0-2.4 (2024-10-29)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.2.0.rc1-2.4 (2024-10-18)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Datasources tests are failling due to race condition
    (https://issues.rudder.io/issues/25497[#25497])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.2.0.beta1-2.4 (2024-09-09)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.2.0.alpha1-2.4 (2024-09-09)

=== Changes


==== Security

* Update js dependencies
    (https://issues.rudder.io/issues/24852[#24852])

=== Bug fixes

==== Miscellaneous

* Fixed: Datasources tests fail on 404
    (https://issues.rudder.io/issues/25085[#25085])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

