= Changelogs for Rudder plugin dsc 8.2.\* versions

== dsc-8.2.5-2.9 (2025-02-27)

=== Changes


==== Techniques

* Add an option Command to run after changes on this package
    (https://issues.rudder.io/issues/26118[#26118])

=== Bug fixes

==== Packaging

* Fixed: There are still some dev files embedded in the policies
    (https://issues.rudder.io/issues/26382[#26382])
* Fixed: Some build files are shipped in the plugins
    (https://issues.rudder.io/issues/26310[#26310])
* Fixed: Agent fails to compile on new builders
    (https://issues.rudder.io/issues/26419[#26419])
* Fixed: Missing UTF8 bom on the ncf.ps1 generated file
    (https://issues.rudder.io/issues/26383[#26383])

==== CLI

* Fixed: Allow the extraction of zip archive to override existing files
    (https://issues.rudder.io/issues/26400[#26400])
* Fixed: On old Windows, rudder agent update can fail as the New-Item cmdlet uses do not force the file type
    (https://issues.rudder.io/issues/26287[#26287])

==== Techniques

* Fixed: Typo in the windowsSoftware technique metadata in version 2.3
    (https://issues.rudder.io/issues/26395[#26395])
* Fixed: the registry path to the rudder agent in technique windows software in rudder 7.3 is not valid anymore
    (https://issues.rudder.io/issues/22694[#22694])
* Fixed:  Windows software directive skip download check on audit mode 
    (https://issues.rudder.io/issues/26299[#26299])

==== Miscellaneous

* Fixed: Rudder agent update always update the policies, even if they did not change
    (https://issues.rudder.io/issues/26281[#26281])

==== Generic methods

* Fixed: conditions from variable are not usable in other methods on windows
    (https://issues.rudder.io/issues/26245[#26245])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.2.4-2.8 (2025-01-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.2.3-2.8 (2024-12-16)

=== Changes


=== Bug fixes

==== System techniques

* Fixed: Prevent the agent to launch scheduled runs in parallel 
    (https://issues.rudder.io/issues/26029[#26029])

==== Agent library

* Fixed: Update-log failed when parameter message exceed 32766 characters leading to reports not being sent 
    (https://issues.rudder.io/issues/26025[#26025])

==== Generic methods

* Fixed: Service methods are not working anymore since 8.2
    (https://issues.rudder.io/issues/26018[#26018])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.2.3-2.7 (2024-12-03)

=== Changes


==== Inventory

* Redirect inventory logs to rudder output and Rudder event logs
    (https://issues.rudder.io/issues/16282[#16282])

=== Bug fixes

==== CLI

* Fixed: Fusion inventory does not roll out its log file
    (https://issues.rudder.io/issues/25946[#25946])

==== System integration

* Fixed: since Rudder 7.2, there are no more event in the event viewer for Rudder (expect specific errors)
    (https://issues.rudder.io/issues/22751[#22751])

==== Agent library

* Fixed: Rudder agent should not store its own data in fake uninstall registry
    (https://issues.rudder.io/issues/25502[#25502])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.2.2-2.7 (2024-11-29)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: If we have a preexisting Windows node before install the DSC plugin, its policy are not automatically generated
    (https://issues.rudder.io/issues/25344[#25344])

==== Techniques

* Fixed: tooltip for technique windows software is broken because of typo in description
    (https://issues.rudder.io/issues/25591[#25591])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.2.1-2.7 (2024-11-28)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Add the postrm to the package scripts
    (https://issues.rudder.io/issues/25823[#25823])
* Fixed: Removing plugin does not commit removed technique
    (https://issues.rudder.io/issues/11581[#11581])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.2.0-2.7 (2024-10-29)

=== Changes


=== Bug fixes

==== CLI

* Fixed: Missing variable nodeUuid in 8.2 agents using 8.1 policies
    (https://issues.rudder.io/issues/25734[#25734])

==== System techniques

* Fixed:  Fix system conditions on Windows 8.2 policies for older agents
    (https://issues.rudder.io/issues/25700[#25700])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.2.0.rc1-2.7 (2024-10-18)

=== Changes


==== Generic methods

* Add Windows support to the generic method file_report_content_tail
    (https://issues.rudder.io/issues/25587[#25587])

=== Bug fixes

==== Miscellaneous

* Fixed: Security benchmarks post-install fails without creating benchmark category.xml
    (https://issues.rudder.io/issues/25674[#25674])

==== Rudder web app

* Fixed: Generation error about RUDDER_DIRECTIVES_INPUTS
    (https://issues.rudder.io/issues/25603[#25603])

==== Agent library

* Fixed: Fix system conditions on Windows 8.2 agents
    (https://issues.rudder.io/issues/25688[#25688])

==== CLI

* Fixed: The system_classes variable is not defined anymore in 8.2 and it breaks the agent compatibility with older policy server
    (https://issues.rudder.io/issues/25606[#25606])
* Fixed: rudder agent info datetime are not parsed correctly
    (https://issues.rudder.io/issues/25582[#25582])
* Fixed: Rudder agent reset fails
    (https://issues.rudder.io/issues/25550[#25550])
* Fixed: Update error messages are not user friendly enough
    (https://issues.rudder.io/issues/25418[#25418])

==== Security

* Fixed: In rare cases, the agent can delete non Rudder related folders
    (https://issues.rudder.io/issues/25520[#25520])

==== Generic methods

* Fixed: Adapt the dsc_built_in_resource method to 8.2 policies
    (https://issues.rudder.io/issues/25436[#25436])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.2.0.beta1-2.6 (2024-09-09)

=== Changes


==== Rudder web app

* Add a policy-generation-pre-start hook to prevents the usage of deprecated syntax
    (https://issues.rudder.io/issues/25265[#25265])

==== CLI

* Align the rudder agent info command output to the Linux one
    (https://issues.rudder.io/issues/25393[#25393])
* Add support for the rudder agent history CLI
    (https://issues.rudder.io/issues/25224[#25224])

==== Misc

* Cleanup the datastate at the end of the agent run
    (https://issues.rudder.io/issues/25244[#25244])

=== Bug fixes

==== Packaging

* Fixed: prevent-obsolete-syntax-on-windows webapp hook is not executable
    (https://issues.rudder.io/issues/25413[#25413])

==== System techniques

* Fixed: typo in the prerun-check.ps1 file
    (https://issues.rudder.io/issues/25370[#25370])

==== CLI

* Fixed: rudder agent check-scheduled-tasks fails unexpectedly
    (https://issues.rudder.io/issues/25367[#25367])
* Fixed: Internal variables should not be exposed in the policy variables
    (https://issues.rudder.io/issues/25196[#25196])
* Fixed: Windows agent 1st run after policy changes systematically produces error
    (https://issues.rudder.io/issues/25140[#25140])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.2.0.alpha1-2.6 (2024-09-09)

=== Changes


==== Techniques

* Remove the windowsUpdate technique
    (https://issues.rudder.io/issues/25167[#25167])

==== CLI

* Add support for the rudder agent log CLI
    (https://issues.rudder.io/issues/25137[#25137])

==== Agent library

* Migrate the variables to the .NET library
    (https://issues.rudder.io/issues/24109[#24109])

=== Bug fixes

==== System techniques

* Fixed: Some system techniques still use some pre 8.2 global variable syntax
    (https://issues.rudder.io/issues/25163[#25163])

==== CLI

* Fixed: Rudder agent check command does not redefine the nodeId variable when created
    (https://issues.rudder.io/issues/25146[#25146])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

