= Changelogs for Rudder plugin dsc 8.2.\* versions

== dsc-8.2.0.rc1-2.7 (2024-10-18)

=== Changes


==== Generic methods

* Add Windows support to the generic method file_report_content_tail
    (https://issues.rudder.io/issues/25587[#25587])

=== Bug fixes

==== Miscellaneous

* Fixed: Security benchmarks post-install fails without creating benchmark category.xml
    (https://issues.rudder.io/issues/25674[#25674])

==== Rudder web app

* Fixed: Generation error about RUDDER_DIRECTIVES_INPUTS
    (https://issues.rudder.io/issues/25603[#25603])

==== Agent library

* Fixed: Fix system conditions on Windows 8.2 agents
    (https://issues.rudder.io/issues/25688[#25688])

==== CLI

* Fixed: The system_classes variable is not defined anymore in 8.2 and it breaks the agent compatibility with older policy server
    (https://issues.rudder.io/issues/25606[#25606])
* Fixed: rudder agent info datetime are not parsed correctly
    (https://issues.rudder.io/issues/25582[#25582])
* Fixed: Rudder agent reset fails
    (https://issues.rudder.io/issues/25550[#25550])
* Fixed: Update error messages are not user friendly enough
    (https://issues.rudder.io/issues/25418[#25418])

==== Security

* Fixed: In rare cases, the agent can delete non Rudder related folders
    (https://issues.rudder.io/issues/25520[#25520])

==== Generic methods

* Fixed: Adapt the dsc_built_in_resource method to 8.2 policies
    (https://issues.rudder.io/issues/25436[#25436])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.2.0.beta1-2.6 (2024-09-09)

=== Changes


==== Rudder web app

* Add a policy-generation-pre-start hook to prevents the usage of deprecated syntax
    (https://issues.rudder.io/issues/25265[#25265])

==== CLI

* Align the rudder agent info command output to the Linux one
    (https://issues.rudder.io/issues/25393[#25393])
* Add support for the rudder agent history CLI
    (https://issues.rudder.io/issues/25224[#25224])

==== Misc

* Cleanup the datastate at the end of the agent run
    (https://issues.rudder.io/issues/25244[#25244])

=== Bug fixes

==== Packaging

* Fixed: prevent-obsolete-syntax-on-windows webapp hook is not executable
    (https://issues.rudder.io/issues/25413[#25413])

==== System techniques

* Fixed: typo in the prerun-check.ps1 file
    (https://issues.rudder.io/issues/25370[#25370])

==== CLI

* Fixed: rudder agent check-scheduled-tasks fails unexpectedly
    (https://issues.rudder.io/issues/25367[#25367])
* Fixed: Internal variables should not be exposed in the policy variables
    (https://issues.rudder.io/issues/25196[#25196])
* Fixed: Windows agent 1st run after policy changes systematically produces error
    (https://issues.rudder.io/issues/25140[#25140])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.2.0.alpha1-2.6 (2024-09-09)

=== Changes


==== Techniques

* Remove the windowsUpdate technique
    (https://issues.rudder.io/issues/25167[#25167])

==== CLI

* Add support for the rudder agent log CLI
    (https://issues.rudder.io/issues/25137[#25137])

==== Agent library

* Migrate the variables to the .NET library
    (https://issues.rudder.io/issues/24109[#24109])

=== Bug fixes

==== System techniques

* Fixed: Some system techniques still use some pre 8.2 global variable syntax
    (https://issues.rudder.io/issues/25163[#25163])

==== CLI

* Fixed: Rudder agent check command does not redefine the nodeId variable when created
    (https://issues.rudder.io/issues/25146[#25146])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

