= Changelogs for Rudder plugin multi-tenants 8.2.\* versions

== multi-tenants-8.2.0.beta1-1.1 (2024-09-09)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.2.0.alpha1-1.1 (2024-09-09)

=== Changes


=== Bug fixes

==== packaging-common

* Fixed: Plugins don't build since gulpfile update
    (https://issues.rudder.io/issues/25007[#25007])

==== Miscellaneous

* Fixed: API accounts cannot be changed when multi-tenants plugin is enabled
    (https://issues.rudder.io/issues/24980[#24980])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

