= Changelogs for Rudder plugin security-benchmarks 8.2.\* versions

== security-benchmarks-8.2.7-1.1 (2025-06-04)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Benchmark should not contain model, only use an id as reference
    (https://issues.rudder.io/issues/26822[#26822])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.2.6-1.1 (2025-05-07)

=== Changes


==== Miscellaneous

* Adding descriptions to sections and control points
    (https://issues.rudder.io/issues/26454[#26454])
* Section 8.1 : Configure privilege escalation
    (https://issues.rudder.io/issues/26273[#26273])
* Section 9.2 : Local user and group settings
    (https://issues.rudder.io/issues/26435[#26435])

=== Bug fixes

==== Miscellaneous

* Fixed: Missing report in enforce on item 2.1.1 on debian like systems
    (https://issues.rudder.io/issues/26829[#26829])
* Fixed: Compilation errors after #26712
    (https://issues.rudder.io/issues/26820[#26820])
* Fixed: Cannot save a benchmark (rhel9)
    (https://issues.rudder.io/issues/26742[#26742])
* Fixed: Score of benchmark seems to never expire
    (https://issues.rudder.io/issues/26453[#26453])
* Fixed: Fix some typos
    (https://issues.rudder.io/issues/26467[#26467])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.2.5-1.1 (2025-02-27)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Score is not updated when a new score is added
    (https://issues.rudder.io/issues/26393[#26393])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.2.4-1.1 (2025-02-25)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Documentation is always shown and we can't hide it
    (https://issues.rudder.io/issues/26280[#26280])
* Fixed: When we create a new benchmark, the existing rudder_auto_conditions are purged
    (https://issues.rudder.io/issues/26329[#26329])
* Fixed: Missing reporting on applied method
    (https://issues.rudder.io/issues/26073[#26073])
* Fixed: Improve reporting to include more cases
    (https://issues.rudder.io/issues/26295[#26295])
* Fixed: Resolve the rudderc dependency in the Makefile
    (https://issues.rudder.io/issues/26293[#26293])
* Fixed: Missing policy type for rsc01
    (https://issues.rudder.io/issues/26274[#26274])
* Fixed: Improve benchmark documentation display and accessibility
    (https://issues.rudder.io/issues/26038[#26038])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.2.4-1.0 (2025-01-13)

=== Changes


==== Miscellaneous

* Refactor the KCL projects
    (https://issues.rudder.io/issues/26035[#26035])

=== Bug fixes

==== Miscellaneous

* Fixed: Apache2 and nginx packages are removed in audit mode
    (https://issues.rudder.io/issues/26115[#26115])
* Fixed: Fix the packaging of the plugin
    (https://issues.rudder.io/issues/26126[#26126])
* Fixed: Fix several missing reports in rsc01
    (https://issues.rudder.io/issues/26103[#26103])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.2.3-1.0 (2024-12-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.2.2-1.0 (2024-11-29)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Still some improvement on display 
    (https://issues.rudder.io/issues/25895[#25895])
* Fixed: Improve and correct reporting display of benchmarks
    (https://issues.rudder.io/issues/25732[#25732])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.2.1-1.0 (2024-11-28)

=== Changes


==== Miscellaneous

* Notify user that parameters have been saved
    (https://issues.rudder.io/issues/25707[#25707])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.2.0-1.0 (2024-10-29)

=== Changes


==== Miscellaneous

* Make it easier to navigate the parameters
    (https://issues.rudder.io/issues/25683[#25683])

=== Bug fixes

==== Miscellaneous

* Fixed: Properties are not correctly when saving benchmark
    (https://issues.rudder.io/issues/25692[#25692])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.2.0.rc1-1.0 (2024-10-18)

=== Changes


==== Miscellaneous

* Disable plugin when license is invalid
    (https://issues.rudder.io/issues/25608[#25608])
* Delete should clean rules, directives and properties
    (https://issues.rudder.io/issues/25400[#25400])
* Make benchmarks accessible by url
    (https://issues.rudder.io/issues/25442[#25442])
* Show score for node in node details parameter page
    (https://issues.rudder.io/issues/25399[#25399])

=== Bug fixes

==== Miscellaneous

* Fixed: Fix the security postinst script
    (https://issues.rudder.io/issues/25680[#25680])
* Fixed: Correct section names
    (https://issues.rudder.io/issues/25682[#25682])
* Fixed: Security benchmarks post-install fails without creating benchmark category.xml
    (https://issues.rudder.io/issues/25674[#25674])
* Fixed: Improve handling properties in user interface
    (https://issues.rudder.io/issues/25628[#25628])
* Fixed: Make benchmark reporting work again
    (https://issues.rudder.io/issues/25465[#25465])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.2.0.beta1-1.0 (2024-09-09)

=== Changes


==== Miscellaneous

* Display the node's score in the compliance table
    (https://issues.rudder.io/issues/25360[#25360])
* Deploy the benchmark techniques in a dedicated technique category
    (https://issues.rudder.io/issues/25394[#25394])
* Improve scores display in chapters
    (https://issues.rudder.io/issues/25389[#25389])
* Improve display of new/deleted nodes and groups, and make access to their details more intuitive
    (https://issues.rudder.io/issues/25384[#25384])
* Support Score and compliance 
    (https://issues.rudder.io/issues/25295[#25295])
* The item conditions should be based on the rule id to avoid any conflicts between benchmarks
    (https://issues.rudder.io/issues/25286[#25286])
* Improve build steps
    (https://issues.rudder.io/issues/25279[#25279])
* Add delete button 
    (https://issues.rudder.io/issues/25266[#25266])
* Switch from children to items
    (https://issues.rudder.io/issues/25269[#25269])
* Automate the build
    (https://issues.rudder.io/issues/25247[#25247])
* Add an ‘Order by’ selector to the benchmarks list
    (https://issues.rudder.io/issues/25222[#25222])
* Make the name and description of a benchmark editable
    (https://issues.rudder.io/issues/25195[#25195])
* Make documentation accessible and editable
    (https://issues.rudder.io/issues/25194[#25194])
* Improving the display of benchmark chapters
    (https://issues.rudder.io/issues/25178[#25178])
* Add Targets selection interface
    (https://issues.rudder.io/issues/25170[#25170])
* Add benchmark creation interface
    (https://issues.rudder.io/issues/25149[#25149])
* Add edit parameters interface and properties fetch
    (https://issues.rudder.io/issues/25158[#25158])
* Security benchmarks backend and services
    (https://issues.rudder.io/issues/25082[#25082])
* Security benchmarks backend and services
    (https://issues.rudder.io/issues/25082[#25082])
* View and edit benchmark parameters
    (https://issues.rudder.io/issues/25115[#25115])
* Display benchmark details
    (https://issues.rudder.io/issues/25113[#25113])
* Display the list of benchmarks as a datatable
    (https://issues.rudder.io/issues/25041[#25041])
* Create elm application
    (https://issues.rudder.io/issues/25043[#25043])

=== Bug fixes

==== Miscellaneous

* Fixed: Make compliance tables filterable and sortable
    (https://issues.rudder.io/issues/25402[#25402])
* Fixed: Bump KCL to the 0.9.8 version
    (https://issues.rudder.io/issues/25410[#25410])
* Fixed: The build fails due to KCL files not compiling
    (https://issues.rudder.io/issues/25405[#25405])
* Fixed: Group and node compliance tabs should not ne visible while creating a new benchmark
    (https://issues.rudder.io/issues/25355[#25355])
* Fixed: Broken plugin build
    (https://issues.rudder.io/issues/25340[#25340])
* Fixed: Techniques are not placed correctly
    (https://issues.rudder.io/issues/25283[#25283])
* Fixed: Remove temporary sed hack used to modify the tag boolean values
    (https://issues.rudder.io/issues/25278[#25278])
* Fixed: The plugin fails to build if an embedded technique does not have any resource file
    (https://issues.rudder.io/issues/25277[#25277])
* Fixed: Override Parameters per Node/Group 
    (https://issues.rudder.io/issues/25259[#25259])
* Fixed: Show nodes and groups in dedicated tabs
    (https://issues.rudder.io/issues/25249[#25249])
* Fixed: The ‘Select Targets’ tab should not close when leaving the tab.
    (https://issues.rudder.io/issues/25223[#25223])
* Fixed: Allow to configure mode
    (https://issues.rudder.io/issues/25173[#25173])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

