= Changelogs for Rudder plugin system-updates 8.2.\* versions

== system-updates-8.2.6-1.17 (2025-05-07)

=== Changes


==== Miscellaneous

* Add filters to campaign events
    (https://issues.rudder.io/issues/26798[#26798])

=== Bug fixes

==== Miscellaneous

* Fixed: System update python module should fails when workdir does not exists
    (https://issues.rudder.io/issues/26740[#26740])
* Fixed: cannot set the architecture in a software update campaign
    (https://issues.rudder.io/issues/26610[#26610])
* Fixed: Annoying line returns in the form to create update campaign
    (https://issues.rudder.io/issues/26490[#26490])

==== Module - system-updates

* Fixed: Missing timezone setup for one shot campaigns
    (https://issues.rudder.io/issues/26443[#26443])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.2.5-1.17 (2025-02-27)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: impossible to disable a campaign in update campaigns menu
    (https://issues.rudder.io/issues/26208[#26208])
* Fixed: Campaign on SUSE family nodes fail due to unknown flag name on zypper command
    (https://issues.rudder.io/issues/26198[#26198])

==== Module - system-updates

* Fixed: System update campaign targeting Rudder server causes “Missing report” from server
    (https://issues.rudder.io/issues/26189[#26189])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.2.4-1.17 (2025-01-13)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Ambiguous text for package selection in windows
    (https://issues.rudder.io/issues/25949[#25949])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.2.3-1.16 (2024-12-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.2.2-1.16 (2024-11-29)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: system update fails on windows
    (https://issues.rudder.io/issues/25929[#25929])
* Fixed: Timezone information should be more visible in system-updates UI
    (https://issues.rudder.io/issues/25899[#25899])
* Fixed: System update current server time take locale timezone instead of UTC
    (https://issues.rudder.io/issues/25689[#25689])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.2.1-1.16 (2024-11-28)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Windows campaigns do not automatically trigger an inventory when done
    (https://issues.rudder.io/issues/25828[#25828])
* Fixed: Windows campaigns may fail to report their execution if a reboot needed
    (https://issues.rudder.io/issues/25818[#25818])
* Fixed: System campaign in 8.2 fails with windows agent 8.1
    (https://issues.rudder.io/issues/25788[#25788])
* Fixed: Security only checkbox has no margin
    (https://issues.rudder.io/issues/25475[#25475])
* Fixed: Missing icon for windows 2022 in system update page
    (https://issues.rudder.io/issues/25690[#25690])
* Fixed: Missing date in report
    (https://issues.rudder.io/issues/25750[#25750])
* Fixed: Refresh button in node campaign results does not have a utility
    (https://issues.rudder.io/issues/25697[#25697])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.2.0-1.16 (2024-10-29)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: result of campaign is not clearly displayed
    (https://issues.rudder.io/issues/25703[#25703])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.2.0.rc1-1.16 (2024-10-18)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Policy generation crash when creating Software Update campaign
    (https://issues.rudder.io/issues/25684[#25684])
* Fixed: Security benchmarks post-install fails without creating benchmark category.xml
    (https://issues.rudder.io/issues/25674[#25674])
* Fixed: hoover text for all icons is "some nodes did not run the campaign"
    (https://issues.rudder.io/issues/25509[#25509])
* Fixed: Removing date filter in campaign event list is impossible
    (https://issues.rudder.io/issues/24056[#24056])
* Fixed: Indicate campaign time as UTC
    (https://issues.rudder.io/issues/25570[#25570])
* Fixed: recap of system update event with "Security only" option doesn't list the security option
    (https://issues.rudder.io/issues/25511[#25511])
* Fixed: error in agent output in 8.2
    (https://issues.rudder.io/issues/25514[#25514])
* Fixed: System update tab on a node doesn't bring you to the node details
    (https://issues.rudder.io/issues/25446[#25446])
* Fixed: The technique v2 does not look for the rudder module at the right place
    (https://issues.rudder.io/issues/25455[#25455])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.2.0.beta1-1.16 (2024-09-09)

=== Changes


==== Miscellaneous

* Add a parameter to customize reboot behavior
    (https://issues.rudder.io/issues/25341[#25341])
* Add a security-only option to the system campaigns
    (https://issues.rudder.io/issues/25253[#25253])
* Document the Windows system update hooks
    (https://issues.rudder.io/issues/25255[#25255])

=== Bug fixes

==== Miscellaneous

* Fixed: Typo in the windows technique prevents the installation of updates
    (https://issues.rudder.io/issues/25254[#25254])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.2.0.alpha1-1.16 (2024-09-09)

=== Changes


==== Miscellaneous

* Call the new module
    (https://issues.rudder.io/issues/25179[#25179])

=== Bug fixes

==== Miscellaneous

* Fixed: The lint test are not passing in 8.2
    (https://issues.rudder.io/issues/25175[#25175])
* Fixed: Icon in campaign events for success and error status
    (https://issues.rudder.io/issues/24999[#24999])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

