= Changelogs for Rudder plugin system-updates 8.2.\* versions

== system-updates-8.2.0.rc1-1.16 (2024-10-18)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Policy generation crash when creating Software Update campaign
    (https://issues.rudder.io/issues/25684[#25684])
* Fixed: Security benchmarks post-install fails without creating benchmark category.xml
    (https://issues.rudder.io/issues/25674[#25674])
* Fixed: hoover text for all icons is "some nodes did not run the campaign"
    (https://issues.rudder.io/issues/25509[#25509])
* Fixed: Removing date filter in campaign event list is impossible
    (https://issues.rudder.io/issues/24056[#24056])
* Fixed: Indicate campaign time as UTC
    (https://issues.rudder.io/issues/25570[#25570])
* Fixed: recap of system update event with "Security only" option doesn't list the security option
    (https://issues.rudder.io/issues/25511[#25511])
* Fixed: error in agent output in 8.2
    (https://issues.rudder.io/issues/25514[#25514])
* Fixed: System update tab on a node doesn't bring you to the node details
    (https://issues.rudder.io/issues/25446[#25446])
* Fixed: The technique v2 does not look for the rudder module at the right place
    (https://issues.rudder.io/issues/25455[#25455])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.2.0.beta1-1.16 (2024-09-09)

=== Changes


==== Miscellaneous

* Add a parameter to customize reboot behavior
    (https://issues.rudder.io/issues/25341[#25341])
* Add a security-only option to the system campaigns
    (https://issues.rudder.io/issues/25253[#25253])
* Document the Windows system update hooks
    (https://issues.rudder.io/issues/25255[#25255])

=== Bug fixes

==== Miscellaneous

* Fixed: Typo in the windows technique prevents the installation of updates
    (https://issues.rudder.io/issues/25254[#25254])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.2.0.alpha1-1.16 (2024-09-09)

=== Changes


==== Miscellaneous

* Call the new module
    (https://issues.rudder.io/issues/25179[#25179])

=== Bug fixes

==== Miscellaneous

* Fixed: The lint test are not passing in 8.2
    (https://issues.rudder.io/issues/25175[#25175])
* Fixed: Icon in campaign events for success and error status 
    (https://issues.rudder.io/issues/24999[#24999])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

