#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Name:         rudder-nodes.py 
# Synopsis:     Get node details from Rudder api and export them to a spreadsheet
# Requirements: requests and xlwt Python modules
# Author:       Dennis Cabooter <Dennis.Cabooter@snow.nl>
#

# Imports - builtins
import os.path
import json
import subprocess

# Imports - external
import requests
import xlwt

# Configuration - BEGIN
api_url        = "https://rudder.example.com/rudder/api"
api_token      = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
validate_https = False
# Configuration - END

# Global variables
api_version = 2
node_url    = "%s/%s/nodes" % (api_url, api_version)
headers     = {"X-API-Token": api_token}
workbook    = "/tmp/test.xls"

# Call API
r = requests.get(node_url, headers=headers, verify=validate_https)

# Parse JSON
j = json.loads(r.content)

# Define nodes
nodes = j["data"]["nodes"]

# Initialize Workbook object 
wbk = xlwt.Workbook()

# Add Worksheet object to Workbook
sheet = wbk.add_sheet("Rudder nodes")

# Set style to bold
style = xlwt.easyxf("font: bold on")

# Write headers
headers = ["Node", "Machine type", "Operating system", "Node ID"]

for index, header in enumerate(headers):
  # Indexing is zero based, row then column
  sheet.write(0, index, header, style)

# Row counter
row = 1

# Loop nodes
for node in sorted(nodes):
  # Vars
  host_name = node["hostname"]
  mach_type = node["machyneType"]
  oper_sys  = node["osName"] + " " + node["osVersion"]
  node_id   = node["id"]

  # Indexing is zero based, row then column
  sheet.write(row, 0, host_name)
  sheet.write(row, 1, mach_type)
  sheet.write(row, 2, oper_sys)
  sheet.write(row, 3, node_id)

  # Increase row counter
  row += 1

# Save Workbook
wbk.save(workbook)

# Execute libreoffice
subprocess.call(["libreoffice", "--minimized", workbook])
