= Change logs for Rudder 2.5

Rudder 2.5 is end of life since 31 July 2013. This branch is codenamed
``Tugboat''.

This page provides a summary of changes for each version. Previous beta
and rc versions are listed below for convenience.

*Installing, upgrading and testing*

Documentation to
http://www.rudder-project.org/rudder-doc-2.5/rudder-doc.html#_install_rudder_server[Install]
and
http://www.rudder-project.org/rudder-doc-2.5/rudder-doc.html#_upgrade_rudder[Upgrade]
is available online.
We also recommend using the
https://github.com/normation/rudder-vagrant/[Rudder Vagrant config] if
you want a quick and easy way to get an installation for testing.

*Operating systems supported*

This version provides packages for these operating systems:

* Rudder server: *Debian 5*, *Debian 6, Debian 7*, *RHEL/CentOS 6*,
*SLES 11*, *Ubuntu 11.10*, *Ubuntu 12.04*, *Ubuntu 12.10*
* Rudder agent: all of the above plus *RHEL/CentOS 5* and *SLES 10*

== Rudder 2.5.5 (2013-07-30)

=== Bug fixes

==== Webapp - Config management

* Screen ``Configuration Policy>Directives'': The buttons are ugly (not
rounded) (https://issues.rudder.io/issues/3688[#3688])
* The Rudder variables in directive values only work with full value
(https://issues.rudder.io/issues/3689[#3689])
* CFEngine variables name in ``CFEngine Generic Variable Definition''
Directives no more support ``dot'' and need a migration script to
``undot'' existing ones
(https://issues.rudder.io/issues/3642[#3642])

==== Webapp - Administration

* Screen ``Administration>Policy Server'': Buttons are broken after
first click on them
(https://issues.rudder.io/issues/3764[#3764])
* Restoring Rules with old fileFormat version does not work
(https://issues.rudder.io/issues/3768[#3768])

==== Webapp - Node management

* ``Search nodes'' screen: After a first use of the search button, it is
no more clickable until a change (add/remove/modification) of criteria
(https://issues.rudder.io/issues/3639[#3639])
* Debug log when updating dynamic group is not clear
(https://issues.rudder.io/issues/3612[#3612])
* An error is displayed in the WebUI and the logs when removing a node
because of an inefficient current action
(https://issues.rudder.io/issues/3517[#3517])

==== Inventory (webapp, Fusion)

* Rudder ignores IP aliases on network interfaces
(https://issues.rudder.io/issues/3669[#3669])

==== Techniques

* Double cron job for Rudder agent when upgrading from 2.5 to 2.6
(https://issues.rudder.io/issues/3681[#3681])
* Deleting packages on Red Hat / CentOS doesn’t work
(https://issues.rudder.io/issues/3709[#3709])
* The reporting of ``Common Policies > Update'' could be in a `No
Answer' status
(https://issues.rudder.io/issues/3620[#3620])
* Technique ``APT package manager configuration'': It is very complex to
use (https://issues.rudder.io/issues/2277[#2277])

==== Techniques - Sys & init promis

* Use cron.d instead of the crontab to store Rudder cron entry (also in
initial promises)
(https://issues.rudder.io/issues/3731[#3731])
* Cron on RHEL/CentOS and Ubuntu nodes was not checked with initial
promises (https://issues.rudder.io/issues/3730[#3730])

==== Architecture - Tests

* Falacious test error in (TestQuickSearchService
(https://issues.rudder.io/issues/3760[#3760])

==== Logging

* Non compliant reports flood the Rudder logs on a new installation
(https://issues.rudder.io/issues/3655[#3655])
* Some debug logs informations about concurrent access were wrong
(https://issues.rudder.io/issues/3641[#3641])

==== Miscellaneous

* The script of initialization rudder-init.sh display an error message
if called with arguments
(https://issues.rudder.io/issues/3747[#3747])

=== Contributors

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter

=== Release notes

This is the final maintenance release of the 2.5 branch. We recommend
that any installations still using 2.5.* be upgraded as soon as possible
to Rudder 2.6.* as soon as possible to enjoy the latest features with a
still stable and more polished version. See our FAQ for details, on
http://www.rudder-project.org/foswiki/FAQ/#What_is_the_versioning_policy_63.

== Rudder 2.5.4 (2013-06-07)

=== Bug fixes

==== Inventory (webapp, Fusion)

* When a node has two intefaces with the same IP, it does not appear as
pending node in Rudder [WebUI](WebUI) +
and can’t be accepted
(https://issues.rudder.io/issues/3626[#3626])

==== Miscellaneous

* Cron on RHEL/CentOS nodes was restarted at every execution of CFEngine
(https://issues.rudder.io/issues/3609[#3609])
* The file tools/generate-map.sh to generate the documentation does not
work with bash
(https://issues.rudder.io/issues/3579[#3579])
* If rsyslog is installed after another syslog, rsyslog is never used on
SLES and reports will never be caught by Rudder server
(https://issues.rudder.io/issues/3569[#3569])

==== Webapp - Node management

* It is not possible to add several nodes sharing the same IP from their
private network interface
(https://issues.rudder.io/issues/3625[#3625])
* Backport translation of datepickers from French (#3425) to branch 2.4
(https://issues.rudder.io/issues/3576[#3576])
* Persistent error messages using search nodes in Rudder
[WebUI](WebUI) +
(https://issues.rudder.io/issues/3512[#3512])
* Searching on Last Inventory Date is not working
(https://issues.rudder.io/issues/3404[#3404])
* Search nodes should accept the ``m'' notation in memory size
(https://issues.rudder.io/issues/3345[#3345])
* No tooltip on Group page for Statis/Dynamic
(https://issues.rudder.io/issues/3597[#3597])

==== Webapp - Administration

* When restoring latest commit, no commit should be made
(https://issues.rudder.io/issues/3593[#3593])
* Reload latest commit through API is not working
(https://issues.rudder.io/issues/3607[#3607])
* Migration script for `Archives' entry in ldap is missing
(https://issues.rudder.io/issues/3590[#3590])
* Archives entry is missing in LDAP, leading to error when creating
Rules (https://issues.rudder.io/issues/3587[#3587])
* System Rules/Directives/Groups should not be archived
(https://issues.rudder.io/issues/3585[#3585])

==== Webapp - Display, home page

* The notifications related to the Workflow are broken in low resolution
screens (1024*768)
(https://issues.rudder.io/issues/3601[#3601])
* Various Fixes
(https://issues.rudder.io/issues/3373[#3373])

==== Architecture - Dependencies

* Rudder is not building with maven2
(https://issues.rudder.io/issues/3637[#3637])
* Not specifying maven default repos lead to inconsistency in download
(https://issues.rudder.io/issues/3598[#3598])

==== Techniques

* Technique [OpenSSH](OpenSSH) +
Server v2.0: Reporting for SSH port configuration Component Key is not
functionnal if port are not defined
(https://issues.rudder.io/issues/3247[#3247])
* CFEngine internal database verification should depend on the CFEngine
version as [BerkeleyDB](BerkeleyDB) +
is no more used since Rudder 2.6
(https://issues.rudder.io/issues/3570[#3570])
* Technique ``Generic Variable Definition'': The regexp to check
variable name doesn’t work
(https://issues.rudder.io/issues/3599[#3599])
* Technique ``Download a file from the shared folder'': Posthook reports
is missing if the copy fails
(https://issues.rudder.io/issues/3583[#3583])
* When using rsyslog with a version > 5.7.1 on the server, some reports
may be dropped, leading to [NoAnswer](NoAnswer) +
on the server (https://issues.rudder.io/issues/3604[#3604])
* Technique ``Download a file from the shared folder'': When error
happens some logs are duplicated
(https://issues.rudder.io/issues/3582[#3582])
* Technique ``Download A File'': The inputs of the Technique are not
checked by regexp to prevent wrong URL or destination format
(https://issues.rudder.io/issues/3539[#3539])

=== Contributors

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter

=== Release notes

This is a maintenance release in the 2.5 series. All installations of
2.5.x should be upgraded when possible. This version is not marked
``stable'' but it is already in use on several internal platforms. You
are invited to upgrade to 2.6 as soon as possible to enjoy the latest
features with a still stable and more polished version.

== Rudder 2.5.3 (2013-05-03)

=== Bug fixes

==== Agent

* Fix UUID generated for a node which was not generated for the first
execution of CFEngine
(https://issues.rudder.io/issues/3523[#3523])
* Prevent cf_lock.db to grow out of control on the server side
(https://issues.rudder.io/issues/3481[#3481])
* Fix errors when stopping Rudder agent daemon with the init script if
its pid file is empty
(https://issues.rudder.io/issues/3457[#3457])

==== Core

* Add a promise to remove Git lock file which could prevent to add new
nodes (https://issues.rudder.io/issues/3526[#3526]
(https://issues.rudder.io/issues/3533[#3533])
* Fix wrong service name of Apache which cause it to be restarted every
five minutes on RedHat /CentOS
(https://issues.rudder.io/issues/3537[#3537])
* Fix broken automatic reload of Techniques when upgrading Rudder 2.5 to
2.6(https://issues.rudder.io/issues/3545[#3545]
(https://issues.rudder.io/issues/3540[#3540])
* Fix Incomplete reporting in the update of promises
(https://issues.rudder.io/issues/3488[#3488])
* Cannot disable dynamic group update
(https://issues.rudder.io/issues/3264[#3264])
* Technique library batch is not working and logs are not correct
(https://issues.rudder.io/issues/3563[#3563])
* Prevent PostgreSQL to display errors when running rudder-init.sh
(https://issues.rudder.io/issues/3397[#3397])
* Fix System Techniques
(https://issues.rudder.io/issues/3555[#3555],
(https://issues.rudder.io/issues/3467[#3467])
* Simplify contributions with an IDE by adding source jar with maven
compilation (https://issues.rudder.io/issues/3400[#3400])

==== UI

* Fix `newest archived report' and `oldest archived report' which
displayed no date during archive activity
(https://issues.rudder.io/issues/3471[#3471])
* Fix pop-up which were broken when a rule has inconsistancy errors
(https://issues.rudder.io/issues/3565[#3565])
* Prevent from having empty error messages when a deployment fails
(https://issues.rudder.io/issues/3538[#3538])
* Fix rule appearing several time in the confirmation pop-up when it has
been disabled if it contained several targets
(https://issues.rudder.io/issues/3468[#3468])
* Fix slowness of displaying details of a Directive when having a lots
of them (https://issues.rudder.io/issues/3387[#3387])
* Modification of archives name to be more descriptive
(https://issues.rudder.io/issues/3392[#3392])
* Prevent Chrome browser to fail to display the loading page after too
many reload (https://issues.rudder.io/issues/2401[#2401])
* Various Fixes
(https://issues.rudder.io/issues/3411[#3411])

==== System integration

* Upgrades RPM packages from one major branch to another don’t always
work because of the Epoch field
(https://issues.rudder.io/issues/3558[#3558])
* rudder-agent RPM packages don’t require the right 32/64 bit
dependencies (https://issues.rudder.io/issues/3549[#3549])
* Allow to install a latest version of rudder-techniques
(https://issues.rudder.io/issues/3405[#3405])
* Make rudder-server-root package depend on headless version of (OpenJDK
(https://issues.rudder.io/issues/3395[#3395])
* Fix continuous restarting of cron on Ubuntu
(https://issues.rudder.io/issues/3436[#3436])
* Fix Rudder status check and send of inventories which failed if a
proxy was defined in the environment
(https://issues.rudder.io/issues/3383[#3383]
(https://issues.rudder.io/issues/3401[#3401])
* Various Fixes
(https://issues.rudder.io/issues/3551[#3551])

==== Techniques

* Improve CFEngine performances
(https://issues.rudder.io/issues/3424[#3424]
(https://issues.rudder.io/issues/3439[#3439]
(https://issues.rudder.io/issues/3444[#3444]
(https://issues.rudder.io/issues/3454[#3454]
(https://issues.rudder.io/issues/3463[#3463]
(https://issues.rudder.io/issues/3485[#3485])
* Technique ``Process management'': version 1.1 was not functionnal
(https://issues.rudder.io/issues/2801[#2801])
* All Techniques: Permit CFEngine to edit files of 1MB
(https://issues.rudder.io/issues/3385[#3385])
* Technique ``Cron daemon configuration'':Fix the cron binary path
checked for Ubuntu to prevent to restart it every CFEngine execution
(https://issues.rudder.io/issues/3438[#3438])
* Technique ``APT package manager configuration'': Handle Ubuntu 12.04
and later (https://issues.rudder.io/issues/3375[#3375])
* Technique ``Time settings'': Fix errors if /etc/localtime is a
symbolic link (https://issues.rudder.io/issues/3437[#3437])
* Technique ``Package management for Debian / Ubuntu / APT systems'':
Support ``allow untrusted'' (optionnally)
(https://issues.rudder.io/issues/3396[#3396])
* Technique ``Download a file'': Fix reports
(https://issues.rudder.io/issues/3346[#3346])

=== Contributors

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter

=== Release notes

This is a maintenance release in the 2.5 series. All installations of
2.5.x should be upgraded when possible. This version is not yet marked
``stable'' but it is already in use on several internal platforms. You
are invited to upgrade to 2.6 as soon as possible to enjoy the latest
features with a still stable and more polished version.

== Rudder 2.5.2 (2013-04-17)

=== Changes

==== System integration

* Make rudder-server-root depend on headless version of (OpenJDK
(https://issues.rudder.io/issues/3395[#3395]
(https://issues.rudder.io/issues/3419[#3419])

=== Bug fixes

==== Core

* Fix CFEngine call of bundle _generic_process_check_process_ with wrong
number of arguments (three instead of four)
(https://issues.rudder.io/issues/3467[#3467])
* Fix migration from Rudder 2.4 to 2.5.1 which lead to not having
generated promises for the nodes
(https://issues.rudder.io/issues/3462[#3462])
* Fix missing jar artifact containing source and dependencies in order
to simplify contributions
(https://issues.rudder.io/issues/3400[#3400])

==== UI

* Fix Rules appearing several time in the confirmation pop-up when
disabling a Directive was applied to this a Rule with several target
(https://issues.rudder.io/issues/3468[#3468])
* Fix the display of the detail of a Directive which was slow if there
were too many directives
(https://issues.rudder.io/issues/3387[#3387])
* Fix errors not displayed when having an invalid error in rule creation
(https://issues.rudder.io/issues/3411[#3411])

==== System integration

* Fix Rudder status check which failed if a proxy was defined in the
environment (https://issues.rudder.io/issues/3383[#3383])
* Fix send-clean.sh script which failed to send inventories
(https://issues.rudder.io/issues/3401[#3401])
* Prevent Fusion Inventory to hang on some SLES 10 because of lsusb
(https://issues.rudder.io/issues/3415[#3415])

==== Techniques

* Improve CFEngine performances
(https://issues.rudder.io/issues/3424[#3424]
(https://issues.rudder.io/issues/3439[#3439]
(https://issues.rudder.io/issues/3444[#3444]
(https://issues.rudder.io/issues/3454[#3454]
(https://issues.rudder.io/issues/3463[#3463]
(https://issues.rudder.io/issues/3485[#3485])
* Technique `Enforce a file content': Increase the size of the files to
be edited (https://issues.rudder.io/issues/3385[#3385])
* Technique `Package management for Debian / Ubuntu / APT systems': Fix
Debian/Ubuntu packages which couldn’t be installed as they were
`untrusted' (https://issues.rudder.io/issues/3396[#3396])
* Technique `Time settings': Fix broken copy of symlink which could
prevent NTP to set a localtime
(https://issues.rudder.io/issues/3437[#3437])

=== Contributors

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Michael Gliwinski (Henderson Group)

=== Release notes

This is a maintenance release in the 2.5 series. All installations of
2.5.x should be upgraded when possible. This version is not yet marked
``stable'' but it is already in use on several internal platforms. We
recommand you to continue to use Rudder 2.4 into production systems.

== Rudder 2.5.1 (2013-04-12)

=== Bug fixes

==== Documentation

* Missing licence header on !ModificationService.scala
(https://issues.rudder.io/issues/3348[#3348])
* Rudder installation doc says that we should use ``main contrib
non-free'' APT components on Debian and should be ``main'' only
(https://issues.rudder.io/issues/3344[#3344])

==== Core

* Fix Rudder core which was unable to start or to reload Technique
Library if an error was in constraint tags of metadata.xml of a
Technique (https://issues.rudder.io/issues/3356[#3356])

==== Webapp - Node management

* Fix ``Select All'' box in the ``Accept new nodes'' page
(https://issues.rudder.io/issues/3234[#3234])
* Node query with OR and regexp doesn’t OR the result
(https://issues.rudder.io/issues/3340[#3340])
* When we delete a node, we can’t generate promises anymore
(https://issues.rudder.io/issues/3420[#3420])

==== Webapp - Config management

* The pop-up with rule depending of a directive is sometime broken
(https://issues.rudder.io/issues/3337[#3337])
* style.css not found on technique screen
(https://issues.rudder.io/issues/3305[#3305])
* Using parametrized variables based on Rules values fails
(https://issues.rudder.io/issues/3332[#3332])
* System Rules/Directives/Groups can be cloned/deleted/disabled
(https://issues.rudder.io/issues/3286[#3286])

==== Webapp - Administration

* The automatic report log archiving was not launched when enabled
(https://issues.rudder.io/issues/3391[#3391])
* Fix unreadable link and unwantend unfolded line in Event Log view
(https://issues.rudder.io/issues/3328[#3328])

==== Techniques

* Technique `Enforce a file content': Synchronize bug fixes from Enforce
a file content between v3.0 and v2.1
(https://issues.rudder.io/issues/3338[#3338])
* Various fixes on ``Process Management'' and ``Set permissions on
files'' (https://issues.rudder.io/issues/3245[#3245])
* The detection of the last promise update was broken
(https://issues.rudder.io/issues/3244[#3244])
* sudoParameters produces an invalid sudoers file when command is
specified (https://issues.rudder.io/issues/3324[#3324])
* sudoParameters technique may insert env_reset setting multiple times
(https://issues.rudder.io/issues/3323[#3323] )
* checkGenericFileContent should also execute a posthook command after
line deletion or replacement
(https://issues.rudder.io/issues/3322[#3322])
* !ManageFileAndFolder: No reporting for the creation component are made
when deleting files
(https://issues.rudder.io/issues/3246[#3246])
* Techniques `Zypper Package Manager Configuration' and `RUG / !YaST
package manager configuration (ZMD)': Broken Reporting when
configuration more than one repository which should not be added
(https://issues.rudder.io/issues/3170[#3170])
* The filePermissions Technique can not load large permlists
(https://issues.rudder.io/issues/3257[#3257])
* Apache 2 HTTP Server: receiving unexpected reports for component
``SELinux context''
(https://issues.rudder.io/issues/2837[#2837])
* Re-creation of the !OpenSSH startup scripts failed on Debian/Ubuntu in
the !OpenSSH server Technique
(https://issues.rudder.io/issues/3368[#3368])

=== Changes

==== Techniques

* Technique ``HTTP Reverse Proxy (Apache)'' added
(https://issues.rudder.io/issues/3277[#3277])

==== Documentation

* Document best practices for Techniques development on Rudder Project
wiki (https://issues.rudder.io/issues/3105[#3105])

==== Inventory (webapp, Fusion)

* Solaris support in the Rudder web interface
(https://issues.rudder.io/issues/3309[#3309])

=== Release notes

This is a maintenance release in the 2.5 series. All installations of
2.5.x should be upgraded when possible. This version is not yet marked
``stable'' but it is already in use on several internal platforms. We
recommand you to continue to use Rudder 2.4 into production systems.

== Rudder 2.5.0 (2013-01-30)

=== Changes

==== UI

* Add Rudder 2.5 logo
(https://issues.rudder.io/issues/3227[#3227])

==== Documentation

* Publishing documentation of Rudder 2.5 on
http://www.rudder-project.org/rudder-doc-2.5/rudder-doc.html
(https://issues.rudder.io/issues/3213[#3213])

=== Bug fixes

==== Agent

* Fix broken cron.d entry of cf-execd which has been modified in Rudder
2.5.0~rc1 (https://issues.rudder.io/issues/3221[#3221])

==== Core

* Improve feedback of database cleaning process
(https://issues.rudder.io/issues/3222[#3222])
* Prevent Rudder from writting too much logs in info log level
(https://issues.rudder.io/issues/3217[#3217])

==== UI

* Fix visualisation of reports in the node details page which couldn’t
be completly drop drown
(https://issues.rudder.io/issues/3226[#3226])

=== Release notes

This version of Rudder is a final release. This version is not marked
``stable'' (unlike previous final versions), since it has not proven to
be reliable on production systems. 2.4.0 will remain the ``stable''
until then.

== Rudder 2.5.0~rc1 (2013-01-23)

=== Changes

==== Core

* Change the internal Rudder variables syntax from $ to $
(https://issues.rudder.io/issues/3149[#3149])
* Add Android support in Rudder
(https://issues.rudder.io/issues/3155[#3155])
* Don’t fail when importing Android inventories that don’t include
network, filesystem, memory and video information
(https://issues.rudder.io/issues/3200[#3200])

 

==== UI

* Inform user that Javascript must be enabled to use Rudder
(https://issues.rudder.io/issues/3184[#3184])
* Inform user about the status of reports archiving
(https://issues.rudder.io/issues/3194[#3194])

=== Bug fixes

==== Core

* Rule clone event log doesn’t always include list of Directives
(https://issues.rudder.io/issues/3151[#3151],
(https://issues.rudder.io/issues/3161[#3161])
* Rollbacking a rollback does not work as expected
(https://issues.rudder.io/issues/3177[#3177])
* Using CFEngine variables with ``latexmath:[$" syntax (not "$](var)'')
in directives leads to unexpected errors in promises generation
(https://issues.rudder.io/issues/3137[#3137])
* Inventory where memory slot numbers are missing / duplicated should be
reported with negative value
(https://issues.rudder.io/issues/3203[#3203])

==== UI

* Display of referenced objects in Event Logs is very poor
(https://issues.rudder.io/issues/3064[#3064])
* Make the footer always at the bottom of the page
(https://issues.rudder.io/issues/2932[#2932])
* Various fixes
(https://issues.rudder.io/issues/3192[#3192],
(https://issues.rudder.io/issues/3187[#3187],
(https://issues.rudder.io/issues/3154[#3154],
(https://issues.rudder.io/issues/3150[#3150],
(https://issues.rudder.io/issues/3080[#3080])

==== System integration

* Clean the crontab correctly in case of a rudder-agent package removal,
by using a file in /etc/cron.d/
(https://issues.rudder.io/issues/3146[#3146])
* On a newly installed server Rudder 2.5, some tables are missing,
leading to numerous error messages
(https://issues.rudder.io/issues/3169[#3169])
* When upgrading Rudder from 2.4 to 2.5~beta1, the logback.xml files is
not updated with the definition of the non-compliant-reports log
(https://issues.rudder.io/issues/3195[#3195])
* Remove wrong comment in logback.xml
(https://issues.rudder.io/issues/3205[#3205])

==== Techniques

* In some Techniques, some system paths are hardcoded, rather than using
global variables
(https://issues.rudder.io/issues/3201[#3201])

=== Release notes

This is a release candidate for Rudder 2.5.0, fixing all known bugs
encountered in 2.5.0~beta1. We still do encourage testing, and welcome
all and any feedback! This release is not yet production ready, and
production use is at your own risk.

A final release of Rudder 2.5.0 can be expected within roughly a week,
which will be encouraged for production use. This version will not,
however, be marked ``stable'' (unlike previous final versions), until it
has been available and proven to be reliable on production systems.
2.4.0 will remain the ``stable'' until then.

== Rudder 2.5.0~beta1 (2013-01-09)

=== Changes

==== Core

* Allow to rollback to a previous configuration policy from the event
log screen (https://issues.rudder.io/issues/3002[#3002],
(https://issues.rudder.io/issues/3142[#3142])
* Allow to clean reports database by manual or scheduled operation(s)
(https://issues.rudder.io/issues/2996[#2996],
(https://issues.rudder.io/issues/2997[#2997])
* Create a Techniques best practices library containing bundles and
bodies (https://issues.rudder.io/issues/3087[#3087])
* Using ``Import All'' is marked as one event in the event log screen
(https://issues.rudder.io/issues/3125[#3125])
* Add commit in the configuration repository when importing archives
(https://issues.rudder.io/issues/3102[#3102])
* Various changes
(https://issues.rudder.io/issues/2897[#2897],
(https://issues.rudder.io/issues/2985[#2985],
(https://issues.rudder.io/issues/2986[#2986],
(https://issues.rudder.io/issues/2955[#2955],
(https://issues.rudder.io/issues/3003[#3003],
(https://issues.rudder.io/issues/3118[#3118],
(https://issues.rudder.io/issues/2968[#2968],
(https://issues.rudder.io/issues/3028[#3028])

==== UI

* Allow to make clones of Rules
(https://issues.rudder.io/issues/3033[#3033])
* Add a warning listing Rules that will be impacted by changes when
updating a Group or a Directive
(https://issues.rudder.io/issues/3049[#3049],
(https://issues.rudder.io/issues/3074[#3074])
* Rudder ID (UUID) of Groups, Rules and Directives is now displayed all
details screens, in uppercase
(https://issues.rudder.io/issues/2998[#2998],
(https://issues.rudder.io/issues/3133[#3133])
* Improve Groups view display
(https://issues.rudder.io/issues/2930[(#2930])
* Various improvements
(https://issues.rudder.io/issues/3114[#3114])

==== System integration

* Add a dedicated log file to record non-compliant checks (Repaired,
Error and Warn) in /var/log/rudder/compliance/non-compliant-reports.log
(https://issues.rudder.io/issues/2988[#2988])
* Various fixes
(https://issues.rudder.io/issues/2929[#2929],
(https://issues.rudder.io/issues/2948[#2948],
(https://issues.rudder.io/issues/3096[#3096])

==== Techniques

* Technique ``OpenSSH server'': Refactor the Technique to reflect the
best practices and use Techniques library
(https://issues.rudder.io/issues/3099[#3099])

=== Release notes

This is the first beta of the Rudder 2.5, including many new features
and bug fixes. The use on production systems is not encouraged at this
time and is at your own risk. However, we do encourage testing, and
welcome all and any feedback!
