= Change logs for Rudder 8.0

==  Rudder 8.0.8 (2024-04-25)

=== Changes


==== Web - Compliance & node report

* Document stopping process before Postgres restore maintenance to avoid primary key constrain get corrupted
    (https://issues.rudder.io/issues/9752[#9752])

==== Web - Config management

* Have a reset-keys button on the node screen
    (https://issues.rudder.io/issues/12791[#12791])

==== rudderc

* Reformat the rudderc technique Json schema to match the one published in the schemastore repository
    (https://issues.rudder.io/issues/24655[#24655])

==== System techniques

* Make inventory verbose when run in inform mode
    (https://issues.rudder.io/issues/24709[#24709])

==== Agent

* Import new gpg key in agent check
    (https://issues.rudder.io/issues/24216[#24216])

=== Bug fixes

==== Agent

* Fixed: Fusion inventory fails to report software with exotic names
    (https://issues.rudder.io/issues/24321[#24321])

==== Packaging

* Fixed: Add an inconditionnal restart of the slapd service in server postinst
    (https://issues.rudder.io/issues/24662[#24662])

==== Documentation

* Fixed: Add warning for properties not case sensitive on Windows
    (https://issues.rudder.io/issues/24234[#24234])
* Fixed: Typo in ncf 8.0
    (https://issues.rudder.io/issues/24693[#24693])

==== Web - Compliance & node report

* Fixed: Directives applied twice don't show in rule details (they should be skipped)
    (https://issues.rudder.io/issues/22525[#22525])

==== Web - Maintenance

* Fixed: Webapp can fail to start with null sessionid error 
    (https://issues.rudder.io/issues/24017[#24017])

==== Performance and scalability

* Fixed: ExpiredCompliance events are pilling up
    (https://issues.rudder.io/issues/24712[#24712])

==== Miscellaneous

* Fixed: Empty description of technique parameter is not allowed
    (https://issues.rudder.io/issues/24698[#24698])

==== Web - Config management

* Fixed: Missing icon in the rule creation page
    (https://issues.rudder.io/issues/24487[#24487])
* Fixed: File picker is broken in 8.0
    (https://issues.rudder.io/issues/24679[#24679])

==== Security

* Fixed: Disabled provisioned users can still login and use Rudder
    (https://issues.rudder.io/issues/24691[#24691])
* Fixed: Ignore RUSTSEC-2024-0332 
    (https://issues.rudder.io/issues/24678[#24678])

==== Web - UI & UX

* Fixed: Beautify node properties tooltips label badge
    (https://issues.rudder.io/issues/24688[#24688])
* Fixed: Typos in node state description
    (https://issues.rudder.io/issues/24668[#24668])
* Fixed: Broken policy mode badge in rule header
    (https://issues.rudder.io/issues/24643[#24643])

==== Web - Nodes & inventories

* Fixed: When sending inventory with no software update anymore, inventory stored is not updated and keeps previous updates
    (https://issues.rudder.io/issues/24675[#24675])
* Fixed: API authorization error: secure/api/compliance/nodes/{id}/system
    (https://issues.rudder.io/issues/24671[#24671])
* Fixed: Number of nodes in rule badge is not correct with tenants
    (https://issues.rudder.io/issues/24665[#24665])

==== Techniques

* Fixed: The services technique is not compatible with Windows
    (https://issues.rudder.io/issues/24763[#24763])

==== Generic methods

* Fixed: Warning in yum module with python 3.12
    (https://issues.rudder.io/issues/24731[#24731])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.0.7 (2024-04-02)

=== Changes


==== Web - UI & UX

* Plugin information is too empty when there is no plugin
    (https://issues.rudder.io/issues/24352[#24352])

==== Relay server or API

* relayd fail on reports containing non utf-8 characters
    (https://issues.rudder.io/issues/24565[#24565])

==== Architecture - Code maintenance

*  Scala 3 syntax - branch 7.3 - core
    (https://issues.rudder.io/issues/24532[#24532])

==== CI

* Add PoC SBOM tooling
    (https://issues.rudder.io/issues/23356[#23356])

==== rudderc

* Add outcome conditions in rudderc docs
    (https://issues.rudder.io/issues/24302[#24302])

==== Techniques

* Package manager options also work on yum
    (https://issues.rudder.io/issues/24571[#24571])

=== Bug fixes

==== Security

* Fixed: Techniques should not be writable by apache in SELinux
    (https://issues.rudder.io/issues/24618[#24618])
* Fixed: Update dependencies to manage CVE-2024-1597  CVE-2024-22257 and CVE-2024-22243
    (https://issues.rudder.io/issues/24607[#24607])
* Fixed: npm dep security checks are ignored
    (https://issues.rudder.io/issues/24522[#24522])
* Fixed: Ignore angularjs DoS in 7.3
    (https://issues.rudder.io/issues/24517[#24517])

==== Packaging

* Fixed: Adapt rudder-agent packaging for Ubuntu 24.04
    (https://issues.rudder.io/issues/24569[#24569])
* Fixed: Move plugins postupgrade after webapp restart
    (https://issues.rudder.io/issues/24449[#24449])

==== Agent

* Fixed: Typo in rudder-sign openssl 3 signing regex
    (https://issues.rudder.io/issues/24359[#24359])
* Fixed: rudder-sign fails on some machines with openssl 3
    (https://issues.rudder.io/issues/24320[#24320])
* Fixed: Add a warning in "rudder agent info" when cf-execd is stopped
    (https://issues.rudder.io/issues/24620[#24620])

==== Documentation

* Fixed: Documentation on Windows installation misses the dependency on dsc plugin on the rudder server
    (https://issues.rudder.io/issues/24229[#24229])
* Fixed: Import/Export archive feature is no more in beta
    (https://issues.rudder.io/issues/24290[#24290])
* Fixed: Fix typo in file replace lines
    (https://issues.rudder.io/issues/24609[#24609])

==== System integration

* Fixed: SELinux error for downloading files
    (https://issues.rudder.io/issues/24589[#24589])
* Fixed: Missing primary key statement for user sessions table creation when migrating
    (https://issues.rudder.io/issues/24456[#24456])

==== Web - UI & UX

* Fixed: Elm properties app is loaded multiple times
    (https://issues.rudder.io/issues/24416[#24416])
* Fixed: Directive errors section is not consistent and always redirects to first tab
    (https://issues.rudder.io/issues/24590[#24590])
* Fixed: JS error when opening directive form more than once 
    (https://issues.rudder.io/issues/24563[#24563])
* Fixed: Margin is too small on Global compliance details module in dashboard
    (https://issues.rudder.io/issues/24283[#24283])
* Fixed: Errors in event log for deleted techniques
    (https://issues.rudder.io/issues/24277[#24277])
* Fixed: When the documentation of a technique is very long, the user has to scroll a long way before creating a directive from this technique
    (https://issues.rudder.io/issues/23881[#23881])

==== Web - Maintenance

* Fixed: Missing event for Relay Demote preventing demotion
    (https://issues.rudder.io/issues/24596[#24596])

==== Relay server or API

* Fixed: Teach relayd about a new report file name
    (https://issues.rudder.io/issues/24564[#24564])
* Fixed: Vulnerability in mio
    (https://issues.rudder.io/issues/24516[#24516])

==== rudderc

* Fixed: Allow technique id starting with a number
    (https://issues.rudder.io/issues/24592[#24592])
* Fixed: rudderc test should dump the report file path or workdir when a check step fails
    (https://issues.rudder.io/issues/24523[#24523])
* Fixed: Broken detection of incorrect parameter names
    (https://issues.rudder.io/issues/24371[#24371])
* Fixed: Add integration tests to rudderc
    (https://issues.rudder.io/issues/24291[#24291])

==== Web - Nodes & inventories

* Fixed: Wrong error message when no result are found when using a compliance filter
    (https://issues.rudder.io/issues/24499[#24499])
* Fixed: Technical logs are not loaded when visiting the tab
    (https://issues.rudder.io/issues/24502[#24502])

==== Web - Technique editor

* Fixed: Compilation output tab icon in technique is not aligned
    (https://issues.rudder.io/issues/24586[#24586])
* Fixed: We shoud not able to save a technique with no method inside
    (https://issues.rudder.io/issues/24579[#24579])
* Fixed: An errors occurs within technique editor resource manager when we create a folder that has the same name than another parent folder
    (https://issues.rudder.io/issues/24276[#24276])
* Fixed: sysctl value generic method is not reporting
    (https://issues.rudder.io/issues/20853[#20853])

==== API

* Fixed: API export of groups doesn't export the categories as dependencies
    (https://issues.rudder.io/issues/24295[#24295])
* Fixed: Async tests are failing for node certificates
    (https://issues.rudder.io/issues/24520[#24520])
* Fixed: Merge user-management feature branch to 7.3
    (https://issues.rudder.io/issues/24342[#24342])
* Fixed: Empty role in users file is logged as warning
    (https://issues.rudder.io/issues/24285[#24285])

==== Web - Config management

* Fixed: Rudder should finish to migrate all techniques when booting instead of stopping on first error
    (https://issues.rudder.io/issues/24515[#24515])

==== Miscellaneous

* Fixed: Existing deleted user managed by file cannot be reactivated 
    (https://issues.rudder.io/issues/24318[#24318])

==== Architecture - Internal libs

* Fixed: windows Node in tests has invalid  certificate, failing test in plugin windows
    (https://issues.rudder.io/issues/24289[#24289])

==== CI

* Fixed: Adapt Jenkinsfile after warning-ng plugin upgrade
    (https://issues.rudder.io/issues/24301[#24301])

==== System techniques

* Fixed: Add a unique component to inventory and inventory signature file name
    (https://issues.rudder.io/issues/24560[#24560])

==== Generic methods

* Fixed: Regex in file replace line must not match the string used as replacement
    (https://issues.rudder.io/issues/24537[#24537])
* Fixed: Missing constraint for enforce parameter in method File content
    (https://issues.rudder.io/issues/24458[#24458])
* Fixed: The yum module should install local package with yum
    (https://issues.rudder.io/issues/24367[#24367])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.0.6 (2024-02-29)

=== Changes


==== Packaging

* Import new gpg key in rpm postinst
    (https://issues.rudder.io/issues/24070[#24070])

==== Plugin manager cli

* Rudder-package should log the package scripts outputs and errors
    (https://issues.rudder.io/issues/24238[#24238])

==== Architecture - Code maintenance

* Prepare migration to Scala 3 - Version 7.3 part 1
    (https://issues.rudder.io/issues/24171[#24171])

==== Web - UI & UX

* Editing big properties in elm-based properties interface is very inconvenient
    (https://issues.rudder.io/issues/23487[#23487])

=== Bug fixes

==== Packaging

* Fixed: Rudder upgrade may fail on postgres script
    (https://issues.rudder.io/issues/24232[#24232])

==== Documentation

* Fixed: layout of https://docs.rudder.io/reference/8.0/administration/server.html#_importing_configuration is broken
    (https://issues.rudder.io/issues/24190[#24190])

==== Miscellaneous

* Fixed: Incorrect error message about change request creation failure when it is not needed
    (https://issues.rudder.io/issues/24278[#24278])

==== Plugin manager cli

* Fixed: rudder-pkg stops at first install error on the upgrade-all command
    (https://issues.rudder.io/issues/24201[#24201])
* Fixed: Pylint test fails with an exception
    (https://issues.rudder.io/issues/24205[#24205])

==== rudderc

* Fixed: rudderc canonifies already canonified condition expression resulting in loss of logic operators such as ) and |
    (https://issues.rudder.io/issues/24226[#24226])

==== Web - Technique editor

* Fixed: when we have conditions on blocks, the condition text is not correctly positionned when the block is opened
    (https://issues.rudder.io/issues/24150[#24150])
* Fixed: Technique import doesn't refresh the list of method in technique editor
    (https://issues.rudder.io/issues/24123[#24123])
* Fixed: Action dropdown list in technique editor goes under parameters
    (https://issues.rudder.io/issues/24122[#24122])

==== Architecture - Code maintenance

* Fixed: Make spotless only check source of current project
    (https://issues.rudder.io/issues/24177[#24177])

==== Web - Config management

* Fixed: We must not generate policies for nodes without a well formed certificate
    (https://issues.rudder.io/issues/24112[#24112])

==== Web - Maintenance

* Fixed: Archiving allows to read inconsistent active technique category ids 
    (https://issues.rudder.io/issues/24011[#24011])

==== API

* Fixed: Bad description for serialNumber attribute of machine
    (https://issues.rudder.io/issues/24141[#24141])
* Fixed: For delete API for node, add a message for node already deleted
    (https://issues.rudder.io/issues/24129[#24129])

==== Web - UI & UX

* Fixed: Unknown rule targets UI is missing icon and border
    (https://issues.rudder.io/issues/24102[#24102])

==== Agent

* Fixed: rudder agent modified misses some files
    (https://issues.rudder.io/issues/24133[#24133])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.0.5 (2024-02-02)

=== Changes


==== Agent

* We should log an error when a hook timeouts
    (https://issues.rudder.io/issues/23936[#23936])

==== API

* Add manufacturer field in create node API
    (https://issues.rudder.io/issues/24091[#24091])

==== Web - UI & UX

* Display the list of pending change requests related to the selected rule
    (https://issues.rudder.io/issues/21931[#21931])

==== Architecture - Code maintenance

* Remove early return to prepare to Scala3 migration in box sequence/traverse
    (https://issues.rudder.io/issues/23948[#23948])

==== rudderc

* Update the rudderc technique json schema to match the minimal SchemaStore expectation
    (https://issues.rudder.io/issues/23966[#23966])

=== Bug fixes

==== Packaging

* Fixed: add apr-util-db as a dependency for al2023
    (https://issues.rudder.io/issues/24061[#24061])
* Fixed: RHEL9 policies have an incompatible sh shebang
    (https://issues.rudder.io/issues/24057[#24057])
* Fixed: Embed openssl cli on 7.3
    (https://issues.rudder.io/issues/24019[#24019])
* Fixed: Abort server build if rudder.war is less than 1Mb
    (https://issues.rudder.io/issues/23958[#23958])

==== Documentation

* Fixed: Fixed ref in documentation for centralized page
    (https://issues.rudder.io/issues/23917[#23917])
* Fixed: case-sensitivity parameter of rudder-user.xml is not documented
    (https://issues.rudder.io/issues/24024[#24024])

==== Web - Config management

* Fixed: when we import an archive and rules contains non existant targets, the targets can't be removed from the rules
    (https://issues.rudder.io/issues/24007[#24007])
* Fixed: Static group which depends on dynamic subgroup must be forbiden
    (https://issues.rudder.io/issues/18952[#18952])
* Fixed: Rudder agent scheduled runs are not triggered at regular interval
    (https://issues.rudder.io/issues/23956[#23956])

==== Architecture - Code maintenance

* Fixed: Backport test correction for allowed networks
    (https://issues.rudder.io/issues/24093[#24093])

==== Web - Technique editor

* Fixed: 404 not found in technique editor resource manager Ajax query
    (https://issues.rudder.io/issues/24084[#24084])
* Fixed: Technique editor method filters are not aligned correctly
    (https://issues.rudder.io/issues/23885[#23885])

==== Web - Compliance & node report

* Fixed: lost audit/enforce on the node compliance page
    (https://issues.rudder.io/issues/23930[#23930])

==== Web - UI & UX

* Fixed: Fix small ui error in the rules information tab
    (https://issues.rudder.io/issues/24079[#24079])
* Fixed: In quicksearch, query error are not displayed which leads to infinite loading result
    (https://issues.rudder.io/issues/23402[#23402])
* Fixed: New campaigns button does not conform to our graphic charter
    (https://issues.rudder.io/issues/23938[#23938])
* Fixed: A new group display no nodes while all linux are selected
    (https://issues.rudder.io/issues/22170[#22170])
* Fixed: The health check page has an unnecessary "Show check list" button in 8.0
    (https://issues.rudder.io/issues/23916[#23916])
* Fixed: The health check page has an unnecessary "Show check list" button
    (https://issues.rudder.io/issues/23891[#23891])
* Fixed: The "Category" field in the technique editor is displayed as a mandatory field even if it is an unmutable one
    (https://issues.rudder.io/issues/23883[#23883])
* Fixed: Remove the "Edit techniques" button from the directives webpage
    (https://issues.rudder.io/issues/23877[#23877])
* Fixed: Rename the "Create global property" button in "Create"
    (https://issues.rudder.io/issues/23878[#23878])

==== Security

* Fixed: Vulnerability in shlex Rust lib
    (https://issues.rudder.io/issues/24069[#24069])
* Fixed: Ignore cve on ext-js (unused dependency)
    (https://issues.rudder.io/issues/24071[#24071])
* Fixed: DoS vuln in h2 lib in relayd
    (https://issues.rudder.io/issues/24068[#24068])
* Fixed: Ignore CVE-2023-51074 (no impact, score too high)
    (https://issues.rudder.io/issues/24005[#24005])
* Fixed: Unaffected CVE on jgit and logback
    (https://issues.rudder.io/issues/23982[#23982])

==== API

* Fixed: If REST url ends with .com, then the .com is removed from path segments
    (https://issues.rudder.io/issues/24036[#24036])

==== Performance and scalability

* Fixed: Healthcheck on file descriptor should be max 64000
    (https://issues.rudder.io/issues/24006[#24006])

==== Server components

* Fixed: Waning log spam when disabled rudder_compute_changes setting
    (https://issues.rudder.io/issues/23969[#23969])

==== Web - Nodes & inventories

* Fixed: Missing icon for windows 2022
    (https://issues.rudder.io/issues/23972[#23972])
* Fixed: We can accept a node with an existing hostname even if node_accept_duplicated_hostname is false
    (https://issues.rudder.io/issues/22197[#22197])

==== rudderc

* Fixed: Improve rudderc error message when a parameter is missing from a method call
    (https://issues.rudder.io/issues/23953[#23953])
* Fixed: Improve rudderc test error message when no library is passed in the parameters
    (https://issues.rudder.io/issues/23941[#23941])
* Fixed: Parameters are not properly intepreted in method call conditions
    (https://issues.rudder.io/issues/23925[#23925])

==== Architecture - Internal libs

* Fixed: Plugin license implementation is not coherent with interface
    (https://issues.rudder.io/issues/23932[#23932])

==== Miscellaneous

* Fixed: Change request on special:all_nodes_without_role lead to error
    (https://issues.rudder.io/issues/23446[#23446])

==== Techniques

* Fixed: File content directive add 4 spaces at the beginning of the line 
    (https://issues.rudder.io/issues/24022[#24022])
* Fixed: FileTemplate technique fails with an error on the Directory-Create method call
    (https://issues.rudder.io/issues/23954[#23954])

==== Agent

* Fixed: Prompt warning and ask confirmation for factory reset
    (https://issues.rudder.io/issues/23978[#23978])
* Fixed: when a node has capitals in its hostname agent history doesn't show manual runs
    (https://issues.rudder.io/issues/23740[#23740])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Alexis TARUSSIO

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.0.4 (2023-12-14)

=== Changes


==== Packaging

* Upgrade curl to 8.5.0
    (https://issues.rudder.io/issues/23841[#23841])
* Update to jetty 10.0.18
    (https://issues.rudder.io/issues/23710[#23710])
* Update to OpenSSL 3.0 & CFEngine 3.21
    (https://issues.rudder.io/issues/23717[#23717])

==== Performance and scalability

* Add some services available to improve system update performance
    (https://issues.rudder.io/issues/23804[#23804])

==== rudderc

* Improve docs for techniques testing
    (https://issues.rudder.io/issues/23810[#23810])
* Add an env var pointing to reports test file
    (https://issues.rudder.io/issues/23807[#23807])
* Improve techniques tests
    (https://issues.rudder.io/issues/23763[#23763])
* Allow testing Windows techniques
    (https://issues.rudder.io/issues/23721[#23721])

==== Architecture - Code maintenance

* Rewrite Nodes compliance table in Elm
    (https://issues.rudder.io/issues/23656[#23656])

==== Agent

* Add a command to get list of modified files on the agent
    (https://issues.rudder.io/issues/23822[#23822])
* Add next run time in rudder agent info
    (https://issues.rudder.io/issues/23598[#23598])

=== Bug fixes

==== Agent

* Fixed: Backport fix for random process killing
    (https://issues.rudder.io/issues/23713[#23713])
* Fixed: Rudder agent modified fails to list some files and duplicates others
    (https://issues.rudder.io/issues/23849[#23849])

==== Documentation

* Fixed: Debian source list should force architecture
    (https://issues.rudder.io/issues/23731[#23731])

==== Web - Maintenance

* Fixed: Event log migration should not be done every time
    (https://issues.rudder.io/issues/23836[#23836])

==== Web - UI & UX

* Fixed: Adding property on nodes is not possible with role node_all
    (https://issues.rudder.io/issues/23840[#23840])
* Fixed: Change "Name" to something else in the technique editor
    (https://issues.rudder.io/issues/23764[#23764])
* Fixed: Sometimes, tooltips in the directives tree remain displayed
    (https://issues.rudder.io/issues/23819[#23819])
* Fixed: Fix typos in error message in technique editor
    (https://issues.rudder.io/issues/23800[#23800])
* Fixed: In Technique Editor, the quicksearch window still  appears behind the navigation menu
    (https://issues.rudder.io/issues/23588[#23588])
* Fixed: Technique saving is blocked because of localstorage of drafts
    (https://issues.rudder.io/issues/23475[#23475])
* Fixed: Using deprecated chart.js options generates errors in the console
    (https://issues.rudder.io/issues/23747[#23747])

==== rudderc

* Fixed: Fail on more unknown fields
    (https://issues.rudder.io/issues/23851[#23851])
* Fixed: For technique parameter, name, id and doc are mixed up
    (https://issues.rudder.io/issues/23847[#23847])
* Fixed: Serde errors do not point to the correct line number
    (https://issues.rudder.io/issues/23332[#23332])
* Fixed: rudderc should export a technique with ids
    (https://issues.rudder.io/issues/23802[#23802])
* Fixed: rudderc method parsing breaks when method contains several bundles
    (https://issues.rudder.io/issues/23798[#23798])
* Fixed: Fix resources_dir definition on Windows
    (https://issues.rudder.io/issues/23777[#23777])

==== Web - Nodes & inventories

* Fixed: Update the error message for failed inventory signature check
    (https://issues.rudder.io/issues/23827[#23827])

==== Web - Config management

* Fixed:  Import archive for an existing technique delete the previous technique
    (https://issues.rudder.io/issues/23818[#23818])
* Fixed: Copy the certificates directly without calling the agent after generation
    (https://issues.rudder.io/issues/23783[#23783])
* Fixed: Creating files with the file explorer fails when using invalid character
    (https://issues.rudder.io/issues/23606[#23606])

==== Miscellaneous

* Fixed: NA is not properly displayed in node compliance
    (https://issues.rudder.io/issues/23820[#23820])
* Fixed: Compiler warnings should prevent build
    (https://issues.rudder.io/issues/23657[#23657])

==== System integration

* Fixed: Exception when bad input for inventory duration config
    (https://issues.rudder.io/issues/23735[#23735])

==== Web - Technique editor

* Fixed: Content of warning tooltip for unknow method should not overflow
    (https://issues.rudder.io/issues/23801[#23801])

==== Architecture - Code maintenance

* Fixed: Test inventory files for 8.0 are invalid
    (https://issues.rudder.io/issues/23742[#23742])

==== Security

* Fixed: Unescape SQL in eventlog filter
    (https://issues.rudder.io/issues/23724[#23724])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.0.3 (2023-11-09)

=== Changes


==== Packaging

* Update to jetty 10.0.18
    (https://issues.rudder.io/issues/23710[#23710])

=== Bug fixes

==== Agent

* Fixed: Backport fix for random process killing
    (https://issues.rudder.io/issues/23713[#23713])

==== rudderc

* Fixed: Bundle name collision with cloned techniques
    (https://issues.rudder.io/issues/23718[#23718])
* Fixed: Add a cleanup step to techniques tests
    (https://issues.rudder.io/issues/23703[#23703])

==== Architecture - Code maintenance

* Fixed: Software DAO can lead to NoSuchElement exception
    (https://issues.rudder.io/issues/23701[#23701])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.0.2 (2023-11-07)

=== Changes


==== API

* Import archive must refuse yaml technique with mismatch directory and id
    (https://issues.rudder.io/issues/23688[#23688])

==== Agent

* Add next run time in rudder agent info
    (https://issues.rudder.io/issues/23598[#23598])

=== Bug fixes

==== Documentation

* Fixed: Install command with variable $releasever lead to error
    (https://issues.rudder.io/issues/22779[#22779])
* Fixed: Import key section in AIX agent install doc is empty
    (https://issues.rudder.io/issues/23312[#23312])
* Fixed: Remove or reduce technique upgrade docs
    (https://issues.rudder.io/issues/23670[#23670])
* Fixed: 8.0 documentation of supported rudder-server OS is outdated
    (https://issues.rudder.io/issues/23680[#23680])

==== Web - Maintenance

* Fixed: Event log migration takes too long
    (https://issues.rudder.io/issues/23699[#23699])

==== API

* Fixed: Import archive does not support technique upgrade
    (https://issues.rudder.io/issues/23655[#23655])
* Fixed: rudder node api documentation doesn't mention the softwareUpdate
    (https://issues.rudder.io/issues/23441[#23441])

==== rudderc

* Fixed: Fix doc for techniques import
    (https://issues.rudder.io/issues/23689[#23689])
* Fixed: Make the library path passed to CFEngine absolute
    (https://issues.rudder.io/issues/23686[#23686])
* Fixed: When a technique scope variable is used in a component key in a method call, logger fails to define the noop conditions in not_applicable cases
    (https://issues.rudder.io/issues/23683[#23683])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


==  Rudder 8.0.1 (2023-10-30)

=== Changes


==== Web - UI & UX

* The "Required/May be empy" button in the parameters of a technique is not intuitive enough
    (https://issues.rudder.io/issues/23610[#23610])
* Improve deleted directive screen
    (https://issues.rudder.io/issues/23172[#23172])

==== API

* Lint shell code examples
    (https://issues.rudder.io/issues/23653[#23653])

==== Documentation

* Update api doc tooling
    (https://issues.rudder.io/issues/23651[#23651])
* Update contributing doc for Rust projects
    (https://issues.rudder.io/issues/23600[#23600])

==== Architecture - Internal libs

* Add a test on JDK21
    (https://issues.rudder.io/issues/23486[#23486])

=== Bug fixes

==== Packaging

* Fixed: Openssl embedded in too many OSes
    (https://issues.rudder.io/issues/23678[#23678])
* Fixed: Bump to openssl 3.0.12
    (https://issues.rudder.io/issues/23649[#23649])
* Fixed: Revert jetty upgrade to 10.0.17 for now
    (https://issues.rudder.io/issues/23648[#23648])

==== Agent

* Fixed: Agent Pre-established trust not working with Rudder 8.0 agent RHEL 7 on CentOS 7
    (https://issues.rudder.io/issues/23635[#23635])
* Fixed: Agent uses hardcoded /bin/getent
    (https://issues.rudder.io/issues/23623[#23623])

==== System integration

* Fixed: Wrong field used to get software source package and version on debian and ubuntu
    (https://issues.rudder.io/issues/23634[#23634])

==== Security

* Fixed: Several low impact CVE in Jetty 10.0.12
    (https://issues.rudder.io/issues/23608[#23608])
* Fixed: Assessments of several low impact CVE in current 7.3.x reported by contrastsecurity tool 
    (https://issues.rudder.io/issues/23609[#23609])

==== Documentation

* Fixed: Broken links in docs hmepage
    (https://issues.rudder.io/issues/23643[#23643])
* Fixed: remove all "starting with version <old>" from docs
    (https://issues.rudder.io/issues/23628[#23628])

==== rudderc

* Fixed: Incorrect rudderc binary download link in documentation
    (https://issues.rudder.io/issues/23674[#23674])

==== Web - UI & UX

* Fixed: The tooltip in the compliance bar does not appear when the mouse is hovered over it
    (https://issues.rudder.io/issues/23612[#23612])
* Fixed: When we are logged out, the logout button doesn't work
    (https://issues.rudder.io/issues/23010[#23010])
* Fixed: Search bar will not work with filters
    (https://issues.rudder.io/issues/23665[#23665])
* Fixed: In technique editor, the "Name" field appears to be optional, whereas it is not.
    (https://issues.rudder.io/issues/23611[#23611])
* Fixed: Recent changes drop down cannot be read
    (https://issues.rudder.io/issues/22518[#22518])
* Fixed: Do not apply syntax highlighting to string properties
    (https://issues.rudder.io/issues/23639[#23639])
* Fixed: Search bar doesn't work for group properties
    (https://issues.rudder.io/issues/22516[#22516])
* Fixed: When we search by "is defined" in the group search, we get the previous search value displayed
    (https://issues.rudder.io/issues/16094[#16094])
* Fixed: Rename "Parameters" menu entry to "Global properties"
    (https://issues.rudder.io/issues/23618[#23618])
* Fixed: Typo in warning message
    (https://issues.rudder.io/issues/23592[#23592])

==== Web - Technique editor

* Fixed: When a mandatory field in a technique is not defined, we can save a technique and we have a nasty error
    (https://issues.rudder.io/issues/23607[#23607])
* Fixed: user with read_only right has button that allows to create a technique
    (https://issues.rudder.io/issues/17813[#17813])

==== API

* Fixed: Add doc for OpenSCAP plugin API
    (https://issues.rudder.io/issues/23645[#23645])
* Fixed: Feature switch for archive API is still present
    (https://issues.rudder.io/issues/23591[#23591])

==== Web - Nodes & inventories

* Fixed: On the nodes list, the filter does not work on property based column
    (https://issues.rudder.io/issues/23535[#23535])

==== Miscellaneous

* Fixed: Last modified attribute of change request is always "unknown"
    (https://issues.rudder.io/issues/19317[#19317])

==== Web - Config management

* Fixed: Tag are not displayed with a nice diff in eventLog 
    (https://issues.rudder.io/issues/15019[#15019])
* Fixed: Quotes in group name generate JS errors when using GroupId criteria
    (https://issues.rudder.io/issues/23320[#23320])
* Fixed: changing password from script to "Enter password + hash" in MD5 result in clear text
    (https://issues.rudder.io/issues/23488[#23488])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.0.0 (2023-10-18)

=== Changes


==== Documentation

* Upgrade notes for 8.0
    (https://issues.rudder.io/issues/23577[#23577])
* Upgrade notes for 8.0
    (https://issues.rudder.io/issues/23577[#23577])

==== rudderc

* Mark yaml format as 1.0
    (https://issues.rudder.io/issues/23568[#23568])

==== Web - UI & UX

* Compliance filter should be shared between the different tables of a same interface
    (https://issues.rudder.io/issues/23539[#23539])

=== Bug fixes

==== Documentation

* Fixed: Mark 8.0 as final in the docs
    (https://issues.rudder.io/issues/23575[#23575])
* Fixed: Bold appears like normal text in the docs
    (https://issues.rudder.io/issues/23566[#23566])

==== Web - UI & UX

* Fixed: Add checks and validation on parameter name
    (https://issues.rudder.io/issues/23587[#23587])
* Fixed: Missing UI for parameter name and description new format
    (https://issues.rudder.io/issues/23586[#23586])
* Fixed: Always display generic method name
    (https://issues.rudder.io/issues/23564[#23564])

==== rudderc

* Fixed: Broken parsing of some complex expressions
    (https://issues.rudder.io/issues/23583[#23583])
* Fixed: Missing NA report on Windows for methods only compatible with Unix
    (https://issues.rudder.io/issues/23581[#23581])
* Fixed: Broken double quote escaping in Windows policies
    (https://issues.rudder.io/issues/23579[#23579])

==== Architecture - Code maintenance

* Fixed: Rudderc error code interpretation is done at two places inconsistently
    (https://issues.rudder.io/issues/23582[#23582])

==== Security

* Fixed: Ignore CVE 2023-4759 (false positive in jgit 6.7.0.202309050840-r)
    (https://issues.rudder.io/issues/23574[#23574])

==== Web - Technique editor

* Fixed: Add new Windows OS conditions to the technique editor
    (https://issues.rudder.io/issues/23541[#23541])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.0.0.rc2 (2023-10-13)

=== Changes


==== Packaging

* Update curl to 8.4.0
    (https://issues.rudder.io/issues/23559[#23559])

==== Documentation

* Remove 7.2 from docs
    (https://issues.rudder.io/issues/23561[#23561])

=== Bug fixes

==== Web - Config management

* Fixed: Remove technique.json and rudder_reporting.cf when migrating technique to new format
    (https://issues.rudder.io/issues/23547[#23547])
* Fixed: Migration of techniques is failling when there is a resource.
    (https://issues.rudder.io/issues/23546[#23546])

==== rudderc

* Fixed: Broken handling of non-printable characters in techniques
    (https://issues.rudder.io/issues/23551[#23551])
* Fixed: Allow setting conditions in tests
    (https://issues.rudder.io/issues/23557[#23557])
* Fixed: Parameter name in metadata.xml should be its id
    (https://issues.rudder.io/issues/23544[#23544])

==== Web - Nodes & inventories

* Fixed: Override process of properties is very misleading at node level
    (https://issues.rudder.io/issues/23553[#23553])

==== Generic methods

* Fixed: Condition_from_string_match fails to be executed multiple times with same inputs
    (https://issues.rudder.io/issues/23554[#23554])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.0.0.rc1 (2023-10-08)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Ensure different cache when embedded various differences
    (https://issues.rudder.io/issues/23533[#23533])
* Fixed: Missing dependency to perl-Digest-MD5 on 8.0 agents
    (https://issues.rudder.io/issues/23532[#23532])
* Fixed: Allow forcing embedding openssl in RPM packages
    (https://issues.rudder.io/issues/23516[#23516])

==== Web - Config management

* Fixed: Ansi color escape code in captured rudderc output
    (https://issues.rudder.io/issues/23536[#23536])

==== Miscellaneous

* Fixed: PostgreSQL error doobie.util.invariant$UnexpectedEnd$ 
    (https://issues.rudder.io/issues/22527[#22527])

==== Plugins integration

* Fixed: rudder package should not totally fail when parsing index if one entry
    (https://issues.rudder.io/issues/23524[#23524])

==== Web - UI & UX

* Fixed: Compliance filter on node does not work as expected
    (https://issues.rudder.io/issues/23522[#23522])

==== Web - Nodes & inventories

* Fixed: String node poperties are displayed in quotes
    (https://issues.rudder.io/issues/23517[#23517])
* Fixed: Changing group property value displays spurious “renamed” message
    (https://issues.rudder.io/issues/23514[#23514])

==== Agent

* Fixed: Inventory ends in “warning 1 reports were not parsable.”
    (https://issues.rudder.io/issues/23529[#23529])
* Fixed: Don't try to send reports in initial policies
    (https://issues.rudder.io/issues/23531[#23531])

==== Generic methods

* Fixed: schedule_generic breaks the agent run when the periodicity of a job is null
    (https://issues.rudder.io/issues/23540[#23540])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.0.0.beta3 (2023-10-01)

=== Changes


==== Packaging

* Switch to OpenSSL 3.0 LTS instead of 3.1
    (https://issues.rudder.io/issues/23510[#23510])
* Switch back to openssl 1.1 in relayd for now
    (https://issues.rudder.io/issues/23447[#23447])

==== Security

* Update OpenSSL to 3.1.3
    (https://issues.rudder.io/issues/23452[#23452])

==== Web - UI & UX

* Add a compliance filter to directive compliance tables
    (https://issues.rudder.io/issues/23499[#23499])
* Node property webpage does not give any tips on how to use the properties
    (https://issues.rudder.io/issues/23405[#23405])
* Node properties are lacking JSON syntax highlighting
    (https://issues.rudder.io/issues/23404[#23404])
* Add filters on compliance tables to hide some kind of compliance
    (https://issues.rudder.io/issues/8166[#8166])
* After creating a change request, give the user a redirection link to its details
    (https://issues.rudder.io/issues/23443[#23443])
* Add a placeholder description for groups page like for techniques and directives
    (https://issues.rudder.io/issues/23184[#23184])

==== Web - Config management

* Ensure yaml technique id and technique directory path agree
    (https://issues.rudder.io/issues/23474[#23474])

==== Architecture - Code maintenance

* Undocomment/remove parameter rudder.nodes.delete.defaultMode
    (https://issues.rudder.io/issues/23462[#23462])

==== Agent

* Prevent agents <6.0 from running on a 8.X server
    (https://issues.rudder.io/issues/23497[#23497])

=== Bug fixes

==== Packaging

* Fixed: Java version is not detected on sles15sp4
    (https://issues.rudder.io/issues/23500[#23500])
* Fixed: silent error when upgrading Rudder 8.0-nightly to 8.0-nightly on sles15sp4
    (https://issues.rudder.io/issues/23480[#23480])
* Fixed: tar is not an explicit dependency of the Rudder server
    (https://issues.rudder.io/issues/22930[#22930])
* Fixed: Dependency on rudder-api-client should be versioned
    (https://issues.rudder.io/issues/23449[#23449])
* Fixed: Rudder 8.0 cannot be installed on sles15sp4 due to dependency error
    (https://issues.rudder.io/issues/23436[#23436])

==== Agent

* Fixed: Memory corruption when inheriting from bodies containing global variables
    (https://issues.rudder.io/issues/23478[#23478])
* Fixed: Function cache can return incorrect results
    (https://issues.rudder.io/issues/23437[#23437])
* Fixed: rudder agent run -l does not prevent update
    (https://issues.rudder.io/issues/23458[#23458])

==== Documentation

* Fixed: documentation tells to edit /opt/rudder/etc/rudder-pkg/rudder-pkg.conf to set credential
    (https://issues.rudder.io/issues/23398[#23398])

==== Web - Technique editor

* Fixed: Thumbnail are not available for all type of file in resource editor
    (https://issues.rudder.io/issues/23512[#23512])
* Fixed: Disable reporting option is ignored by the technique editor
    (https://issues.rudder.io/issues/23490[#23490])
* Fixed: LanguageTools module can prevent Yaml editor from extending
    (https://issues.rudder.io/issues/23484[#23484])
* Fixed: Unable to save a technique resource through the file manager
    (https://issues.rudder.io/issues/23479[#23479])

==== Web - Nodes & inventories

* Fixed: surprising ordering on values for properties
    (https://issues.rudder.io/issues/23473[#23473])
* Fixed: Editing and renaming a group property results in duplicate property
    (https://issues.rudder.io/issues/23496[#23496])
* Fixed: Error when trying to add a JSON property to node
    (https://issues.rudder.io/issues/23482[#23482])
* Fixed: error when create, modify or delete a properties on group
    (https://issues.rudder.io/issues/23472[#23472])

==== Web - Compliance & node report

* Fixed: Compliance filter is not clear enough when disabling a group of reports
    (https://issues.rudder.io/issues/23492[#23492])
* Fixed: Focus reporting is not working 
    (https://issues.rudder.io/issues/23466[#23466])

==== API

* Fixed: Add an enum for campaign type in post request
    (https://issues.rudder.io/issues/23501[#23501])

==== Web - UI & UX

* Fixed: Calendar in token api creation is broken
    (https://issues.rudder.io/issues/23268[#23268])
* Fixed: import technique doesn't show yaml files
    (https://issues.rudder.io/issues/23483[#23483])
* Fixed: Node property webpage makes it hard to uses JSON based properties
    (https://issues.rudder.io/issues/23401[#23401])
* Fixed: Tables in Rudder UI are sorted alphabetically but should also follow a numerical sort - nodes page
    (https://issues.rudder.io/issues/23427[#23427])

==== Miscellaneous

* Fixed: Update jgit to remove CVE-2023-4759 error message
    (https://issues.rudder.io/issues/23495[#23495])
* Fixed: Make writing node state to fact repos optionnal
    (https://issues.rudder.io/issues/23424[#23424])

==== Techniques

* Fixed: LONG_DESCRIPTION field of techniques seems to be ignored
    (https://issues.rudder.io/issues/23491[#23491])
* Fixed: Outdated warnings in ssh server technique
    (https://issues.rudder.io/issues/23468[#23468])

==== Web - Config management

* Fixed: Cannot override global property in Rudder 8.0 beta 3
    (https://issues.rudder.io/issues/23454[#23454])
* Fixed: adapt policy generation hooks to prevent automatic update of policies for each rudder command
    (https://issues.rudder.io/issues/23464[#23464])

==== System integration

* Fixed: Missing new historical inventory clean-up properties in config file
    (https://issues.rudder.io/issues/23461[#23461])

==== Generic methods

* Fixed: Migrate the report_if_condition method to log v4
    (https://issues.rudder.io/issues/23502[#23502])
* Fixed: Improve variable_string_from_command on 8.0+ agents
    (https://issues.rudder.io/issues/23438[#23438])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.0.0.beta2 (2023-09-15)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Bump to openssl 1.1.1w
    (https://issues.rudder.io/issues/23410[#23410])

==== Architecture - Code maintenance

* Fixed: Clean-up acceptation inventory
    (https://issues.rudder.io/issues/23406[#23406])
* Fixed: Update to zio-json 0.6.2
    (https://issues.rudder.io/issues/23409[#23409])
* Fixed: SQL logger is never called
    (https://issues.rudder.io/issues/23414[#23414])

==== Web - UI & UX

* Fixed: Add a way to set a message if "change audit logs" setting is enabled
    (https://issues.rudder.io/issues/23372[#23372])
* Fixed: Add a way to set a message if "change audit logs" setting is enabled
    (https://issues.rudder.io/issues/23372[#23372])

==== Architecture - Dependencies

* Fixed: Upgrade to scala 2.13.12
    (https://issues.rudder.io/issues/23417[#23417])

==== Web - Config management

* Fixed: Error when updating policies on relays when no files has been shared between nodes
    (https://issues.rudder.io/issues/17143[#17143])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.0.0.beta1 (2023-09-07)

=== Changes


==== Packaging

* Update agent dependencies
    (https://issues.rudder.io/issues/23360[#23360])
* rhel7 server build should depends on python3-pip and python3
    (https://issues.rudder.io/issues/23083[#23083])
* Repair rhel7 agent build
    (https://issues.rudder.io/issues/23080[#23080])
* Update Rust dependencies
    (https://issues.rudder.io/issues/23359[#23359])
* Update frontend dependencies
    (https://issues.rudder.io/issues/23362[#23362])
* Cleanup old files in repo
    (https://issues.rudder.io/issues/23353[#23353])
* Build rust binaries with cargo auditable
    (https://issues.rudder.io/issues/23175[#23175])
* Remove cfe-red-button.sh from sources
    (https://issues.rudder.io/issues/23130[#23130])

==== Agent

* Missing variables in mustache rendering must be an error
    (https://issues.rudder.io/issues/23068[#23068])
* make rudder agent run -u the default
    (https://issues.rudder.io/issues/23328[#23328])
* Remove RUDDER_VERIFY_CERTIFICATES usage in agent
    (https://issues.rudder.io/issues/23329[#23329])
* Remove support for syslog reporting completely from agent
    (https://issues.rudder.io/issues/23317[#23317])
* Add a trust option to rudder agent policy-server
    (https://issues.rudder.io/issues/22629[#22629])

==== Documentation

* Update hardening guide for 8.0
    (https://issues.rudder.io/issues/23333[#23333])
* Add release note for hashed api tokens
    (https://issues.rudder.io/issues/23257[#23257])
* Prepare doc for 8.0
    (https://issues.rudder.io/issues/23204[#23204])
* Document how to script the windows agent install
    (https://issues.rudder.io/issues/23066[#23066])
* Arch doc for policy update
    (https://issues.rudder.io/issues/22589[#22589])

==== Relay server or API

* Update embedded openssl to 3.1 in relayd
    (https://issues.rudder.io/issues/23383[#23383])
* Use the secrecy crates for wrapping passwords
    (https://issues.rudder.io/issues/23159[#23159])

==== Web - Technique editor

* Allow to edit yaml in editor
    (https://issues.rudder.io/issues/23381[#23381])
* Display compilation output  in technique details
    (https://issues.rudder.io/issues/23357[#23357])

==== Web - Compliance & node report

* Remove constraint on component name pattern for matching reports
    (https://issues.rudder.io/issues/23084[#23084])

==== Web - Nodes & inventories

* When I enter the "Create a new item" popup to create a group the default field should be Name
    (https://issues.rudder.io/issues/2677[#2677])

==== Web - UI & UX

* Remove angular leftovers
    (https://issues.rudder.io/issues/23350[#23350])
* Allow to edit files in file manager
    (https://issues.rudder.io/issues/23349[#23349])
* When drag'n drop, the selected method and the targeted drop zone should be more highlighted
    (https://issues.rudder.io/issues/23303[#23303])
* Improve some messages in the interface
    (https://issues.rudder.io/issues/23275[#23275])
* Speed up fadein animation of pages
    (https://issues.rudder.io/issues/23274[#23274])
* Use consistent fonts in Rudder interface
    (https://issues.rudder.io/issues/23265[#23265])
* After deleting a node, the user should be redirected to nodes list page
    (https://issues.rudder.io/issues/7008[#7008])
* Remove angularjs from Rudder
    (https://issues.rudder.io/issues/23072[#23072])
* Rewrite the 'technique-version' app in Elm
    (https://issues.rudder.io/issues/22991[#22991])

==== Web - Config management

* Improve password hash scheme names
    (https://issues.rudder.io/issues/23283[#23283])
* Remove old certificate verification option
    (https://issues.rudder.io/issues/23287[#23287])
* Rename "global parameters" to "global properties"
    (https://issues.rudder.io/issues/22379[#22379])
* Remove the rudderc "linux only" option from webapp
    (https://issues.rudder.io/issues/23118[#23118])

==== Security

* TLS 1.3 everywhere
    (https://issues.rudder.io/issues/23292[#23292])
* Use constant time comparison for system token
    (https://issues.rudder.io/issues/23291[#23291])

==== API

* Add last generation time on regenerate button
    (https://issues.rudder.io/issues/23284[#23284])
* Hash API tokens
    (https://issues.rudder.io/issues/23234[#23234])
* Prepare API doc for 8.0
    (https://issues.rudder.io/issues/23205[#23205])

==== Architecture - Code maintenance

* Rewrite angular app "filters.js" in Elm
    (https://issues.rudder.io/issues/23210[#23210])
* Rewrite angular app "passwordForm" in JavaScript
    (https://issues.rudder.io/issues/23060[#23060])

==== rudderc

* Parse expressions for linting
    (https://issues.rudder.io/issues/23190[#23190])
* Don't stop at first user error but display an many as possible
    (https://issues.rudder.io/issues/23188[#23188])
* Allow JSON output
    (https://issues.rudder.io/issues/23185[#23185])
* Switch to tracing for logging
    (https://issues.rudder.io/issues/23180[#23180])
* Add an option to start the agent in verbose mode
    (https://issues.rudder.io/issues/23135[#23135])
* Document JSON schema
    (https://issues.rudder.io/issues/23134[#23134])
* Improve testing features
    (https://issues.rudder.io/issues/23102[#23102])

==== Performance and scalability

* Make commiting nodes to fact-repo optionnal
    (https://issues.rudder.io/issues/23045[#23045])

==== Generic methods

* Improve variable_string_from_command by using execresult_as_data
    (https://issues.rudder.io/issues/23347[#23347])

=== Bug fixes

==== Packaging

* Fixed: Server install fails with postgresql encoding error
    (https://issues.rudder.io/issues/23388[#23388])
* Fixed: Stop removing the openssl test folder
    (https://issues.rudder.io/issues/23355[#23355])
* Fixed: Don't build openssl tests
    (https://issues.rudder.io/issues/23255[#23255])
* Fixed: Hide postrm script warnings
    (https://issues.rudder.io/issues/23251[#23251])
* Fixed: Rudder Server 7.3.4 doesn't install on SLES 15 SP4
    (https://issues.rudder.io/issues/23186[#23186])
* Fixed: Install failed rudder-slapd does not start
    (https://issues.rudder.io/issues/23165[#23165])
* Fixed: Actually allow uninstalling the agent
    (https://issues.rudder.io/issues/23146[#23146])
* Fixed: Agent uninstall fails on Ubuntu 22.04
    (https://issues.rudder.io/issues/23145[#23145])
* Fixed: rudder-server package can't install on rpm in 8.0
    (https://issues.rudder.io/issues/23144[#23144])
* Fixed: /var/log/rudder/ldap/slapd.log has incorrect permissions
    (https://issues.rudder.io/issues/23142[#23142])
* Fixed: Some cfengine patch don't apply in 8.0 anymore
    (https://issues.rudder.io/issues/23069[#23069])
* Fixed: Some cfengine patch don't apply in 8.0 anymore
    (https://issues.rudder.io/issues/23069[#23069])
* Fixed: relayd build broken
    (https://issues.rudder.io/issues/23247[#23247])
* Fixed: Update spring security
    (https://issues.rudder.io/issues/23221[#23221])
* Fixed: Remove unused Rust dependencies
    (https://issues.rudder.io/issues/23219[#23219])
* Fixed: Update embedded openssl to 1.1.1v - relayd
    (https://issues.rudder.io/issues/23217[#23217])
* Fixed: Install cargo-auditable before building
    (https://issues.rudder.io/issues/23191[#23191])
* Fixed: Package install after uninstall only restores uuid
    (https://issues.rudder.io/issues/23239[#23239])

==== Agent

* Fixed: Wrong source detection on some apt systems
    (https://issues.rudder.io/issues/23387[#23387])
* Fixed: When we uninstall and reinstall an agent, the agent is not correctly activated
    (https://issues.rudder.io/issues/22413[#22413])

==== Security

* Fixed: Update openssl and curl
    (https://issues.rudder.io/issues/23192[#23192])
* Fixed: Prevent API token logging by overriding toString implementation
    (https://issues.rudder.io/issues/23228[#23228])
* Fixed: Use token id in URLs
    (https://issues.rudder.io/issues/23233[#23233])
* Fixed: CVE-2016-1000027 false positive detection
    (https://issues.rudder.io/issues/23231[#23231])
* Fixed: Some internal APIs in the Web application bypass ACLs 
    (https://issues.rudder.io/issues/23227[#23227])
* Fixed: File manager API is vulnerable to malicious input
    (https://issues.rudder.io/issues/23225[#23225])
* Fixed: Path traversal in relayd shared-folder HEAD call
    (https://issues.rudder.io/issues/23226[#23226])
* Fixed: The "shared_file_to_node" method does not verify its policy server's certificate with default configuration
    (https://issues.rudder.io/issues/23290[#23290])

==== Web - Nodes & inventories

* Fixed: Missing information in Oracle linux inventory
    (https://issues.rudder.io/issues/23029[#23029])
* Fixed: 502 - Proxy Error when triggering Rudder agent
    (https://issues.rudder.io/issues/22998[#22998])
* Fixed: Don't accept inventories from agent without a certificate
    (https://issues.rudder.io/issues/23324[#23324])
* Fixed: Change description of "All Linux nodes" group
    (https://issues.rudder.io/issues/23179[#23179])

==== Documentation

* Fixed: Fix version in menu for yaml tehcniques doc
    (https://issues.rudder.io/issues/23259[#23259])
* Fixed: doc for external db is not very clear
    (https://issues.rudder.io/issues/23245[#23245])
* Fixed: Wrong OS for amazon linux 2023 server install 
    (https://issues.rudder.io/issues/23242[#23242])
* Fixed: correct rudder server requirements in doc
    (https://issues.rudder.io/issues/23131[#23131])
* Fixed: Add relevent items from jetty config to the webapp conf section
    (https://issues.rudder.io/issues/23026[#23026])
* Fixed: Document the report mode setting
    (https://issues.rudder.io/issues/13289[#13289])
* Fixed: Windows agent installation : Documentation improvement
    (https://issues.rudder.io/issues/23018[#23018])
* Fixed: Update api doc for new response format for /settings/allowed_networks
    (https://issues.rudder.io/issues/23267[#23267])
* Fixed: Document when a parameter can be a regex
    (https://issues.rudder.io/issues/10713[#10713])

==== Web - UI & UX

* Fixed: Elm webapp build is broken in 8.0
    (https://issues.rudder.io/issues/23394[#23394])
* Fixed: We can choose the format of the value on deletion in global parameter
    (https://issues.rudder.io/issues/23183[#23183])
* Fixed: Tables in Rudder UI are sorted alphabetically but should also follow a numerical sort
    (https://issues.rudder.io/issues/23335[#23335])
* Fixed: Change the display of the new filemanager to match the previous one
    (https://issues.rudder.io/issues/23285[#23285])
* Fixed: Filter display is broken when a tag is added
    (https://issues.rudder.io/issues/23346[#23346])
* Fixed: In the quicksearch window, the link for a result is not applied to the entire line
    (https://issues.rudder.io/issues/23345[#23345])
* Fixed: In Technique Editor, the quicksearch window appears behind the navigation menu. 
    (https://issues.rudder.io/issues/23343[#23343])
* Fixed: In quicksearch window, Warning message "please refine your query" is displayed even if there is less than 10 results
    (https://issues.rudder.io/issues/23342[#23342])
* Fixed: Inconsitency background color in generic method section in technique editor
    (https://issues.rudder.io/issues/23170[#23170])
* Fixed: Node property name is reset to the previous value when editing the value on creation
    (https://issues.rudder.io/issues/23182[#23182])
* Fixed: Inconsistent color of save button in directives
    (https://issues.rudder.io/issues/23196[#23196])
* Fixed: Cannot create group property because of missing UI
    (https://issues.rudder.io/issues/23181[#23181])
* Fixed: Inventory variable that are Json types are listed as plain string types in the UI
    (https://issues.rudder.io/issues/23087[#23087])
* Fixed: Password form in User directives does not works properly
    (https://issues.rudder.io/issues/23200[#23200])
* Fixed: Interface color inconsistency for non compliance display
    (https://issues.rudder.io/issues/23004[#23004])

==== Relay server or API

* Fixed: Allow underscore in file_id in shared-files
    (https://issues.rudder.io/issues/23392[#23392])
* Fixed: Broken log for file_id in shared-files API
    (https://issues.rudder.io/issues/23390[#23390])

==== rudderc

* Fixed: rudderc parses ncf_const.s as const.s
    (https://issues.rudder.io/issues/23377[#23377])
* Fixed: Rudderc silently accept unknown parameter constraints
    (https://issues.rudder.io/issues/23380[#23380])
* Fixed: Broken technique parameter serialization
    (https://issues.rudder.io/issues/23358[#23358])
* Fixed: Rudderc transform some method parameter name in an incorrect manner
    (https://issues.rudder.io/issues/23341[#23341])
* Fixed: Move "technique parameters" section at the beginning
    (https://issues.rudder.io/issues/23334[#23334])
* Fixed: Improve serde deserialization error messages
    (https://issues.rudder.io/issues/23252[#23252])
* Fixed: Rudderc does not escape correctly the double quotes in componentKey in windows techniques
    (https://issues.rudder.io/issues/23246[#23246])
* Fixed: Windows technique generated function name is incoherent with the generated directives
    (https://issues.rudder.io/issues/23240[#23240])
* Fixed: Fix JSON output of the lib command
    (https://issues.rudder.io/issues/23195[#23195])
* Fixed: Warn on deprecated methods
    (https://issues.rudder.io/issues/23194[#23194])
* Fixed: " are not correctly escaped in technique for classes_noop in rudder 8.0
    (https://issues.rudder.io/issues/23178[#23178])
* Fixed: Conditions syntax broken on Windows
    (https://issues.rudder.io/issues/23152[#23152])
* Fixed: Allow booleans for condition fields
    (https://issues.rudder.io/issues/23151[#23151])
* Fixed: Sort bundles in CFEngine output
    (https://issues.rudder.io/issues/23150[#23150])
* Fixed: Broken reports when condition is not defined
    (https://issues.rudder.io/issues/23149[#23149])
* Fixed: Add versions to rudderc binaires
    (https://issues.rudder.io/issues/23138[#23138])
* Fixed: Rudderc fails to render block conditions
    (https://issues.rudder.io/issues/23136[#23136])
* Fixed: Improve technique JSON schema
    (https://issues.rudder.io/issues/23132[#23132])
* Fixed: Embed current version of the lib in rudderc
    (https://issues.rudder.io/issues/23125[#23125])
* Fixed: Add rich form types to yaml techniques
    (https://issues.rudder.io/issues/23039[#23039])

==== Architecture - Code maintenance

* Fixed: Clean-up unsuported old format for expected report and techniques
    (https://issues.rudder.io/issues/23369[#23369])
* Fixed: Add rudder 8.0 inventories to unit tests
    (https://issues.rudder.io/issues/23319[#23319])
* Fixed: Simplify YAML encoding workaround
    (https://issues.rudder.io/issues/23325[#23325])
* Fixed: When custom role permission list is empty, reload lead to stack trace
    (https://issues.rudder.io/issues/23305[#23305])
* Fixed: Rewrite angular app tags.js in Elm
    (https://issues.rudder.io/issues/23201[#23201])
* Fixed: Warning for unused vars in 8.0 compilation
    (https://issues.rudder.io/issues/23093[#23093])

==== Web - Technique editor

* Fixed: Import/Export yaml with technique editor
    (https://issues.rudder.io/issues/23352[#23352])
* Fixed: Technique editor throws errors when using blocks with the weighted default reporting option
    (https://issues.rudder.io/issues/23244[#23244])
* Fixed: Error when we try to save a draft with a missing parameter name in technique editor
    (https://issues.rudder.io/issues/23256[#23256])
* Fixed: in the technique editor, the drop down list for condition is truncated
    (https://issues.rudder.io/issues/23177[#23177])
* Fixed: When changes messages are mandatory and saving a technique we have an error message about missing info but technique is saved
    (https://issues.rudder.io/issues/23000[#23000])

==== Web - Config management

* Fixed: First regenerate methods then migrate to yaml
    (https://issues.rudder.io/issues/23361[#23361])
* Fixed: Regenerate yaml technique and filter generated files in rule archives
    (https://issues.rudder.io/issues/23155[#23155])
* Fixed: Message “Error getting directive compliance” when creating new directive
    (https://issues.rudder.io/issues/22830[#22830])
* Fixed: Temporary workaround for tag creation in rudder 8.0 alpha
    (https://issues.rudder.io/issues/23148[#23148])

==== Architecture - Dependencies

* Fixed: Update scala dependencies before beta
    (https://issues.rudder.io/issues/23364[#23364])

==== Web - Maintenance

* Fixed: Plugin cannot add custom roles or it will be overwritten by boot custom roles 
    (https://issues.rudder.io/issues/23098[#23098])

==== Plugin manager cli

* Fixed: rudder package doesn't upgrade openscap, and it brings a lot of chaos
    (https://issues.rudder.io/issues/23224[#23224])

==== Miscellaneous

* Fixed: Update Rust compiler to 1.71.1 for security fix
    (https://issues.rudder.io/issues/23216[#23216])
* Fixed: Version 2.0.3 of ZIO cause OutOfMemory error and high CPU load
    (https://issues.rudder.io/issues/23147[#23147])
* Fixed: Generation not queued when one already started
    (https://issues.rudder.io/issues/23074[#23074])

==== System integration

* Fixed: Windows agent cannot get immediatly its policies right after being accepted
    (https://issues.rudder.io/issues/23218[#23218])

==== Generic methods

* Fixed: N/A report message when a block expression is not valid is not rendered correctly
    (https://issues.rudder.io/issues/23212[#23212])
* Fixed:  When generic method change a password it doesn't update the date of last change
    (https://issues.rudder.io/issues/23339[#23339])
* Fixed: "Variable string from command" creates empty files in /var/rudder/modified-files
    (https://issues.rudder.io/issues/22584[#22584])

==== CI

* Fixed: Update compatibility test to JVM 20
    (https://issues.rudder.io/issues/23129[#23129])

==== Web - Compliance & node report

* Fixed: Bad report maching when reportid are present
    (https://issues.rudder.io/issues/22388[#22388])
* Fixed: Multiline string in component name or value breaks pattern comparison for expected report
    (https://issues.rudder.io/issues/23090[#23090])

==== Techniques

* Fixed: When the user technique change a password it doesn't update the date of last change
    (https://issues.rudder.io/issues/23338[#23338])
* Fixed: Deprecate some built-in techniques in 8.0
    (https://issues.rudder.io/issues/23044[#23044])

==== System techniques

* Fixed: Broken report in 8.0
    (https://issues.rudder.io/issues/23143[#23143])

==== Server components

* Fixed: Broken "server create-user" command when auth file has different formating
    (https://issues.rudder.io/issues/23203[#23203])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl
* Jonathan CLARKE
* Marc Evans

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


== Rudder 8.0.0.alpha1 (2023-07-18)

=== Changes


==== Packaging

* Remove agent dependency on syslog
    (https://issues.rudder.io/issues/22900[#22900])
* Upgrade agent dependencies for 8.0
    (https://issues.rudder.io/issues/22840[#22840])
* Use openldap 2.6.4 in rudder 8
    (https://issues.rudder.io/issues/22793[#22793])
* Upgrade fusion inventory to 2.6
    (https://issues.rudder.io/issues/22791[#22791])
* Remove transitional packages in Rudder 8.0
    (https://issues.rudder.io/issues/22748[#22748])
* remove python2 support on rudder 8
    (https://issues.rudder.io/issues/22746[#22746])
* Require postgresql 13 on rudder 8
    (https://issues.rudder.io/issues/22745[#22745])
* Update cfengine to 3.21
    (https://issues.rudder.io/issues/22742[#22742])

==== Web - UI & UX

* Switch quicksearch to elm
    (https://issues.rudder.io/issues/23050[#23050])
* Remove old IE 5 & 6 JS compatibility code
    (https://issues.rudder.io/issues/23057[#23057])
* Remove heartbeat configuration from the settings
    (https://issues.rudder.io/issues/22659[#22659])
* Removing deprecated AngularJs applications
    (https://issues.rudder.io/issues/23036[#23036])
* Beautify no permission page when user have no rights
    (https://issues.rudder.io/issues/22626[#22626])
* Rewrite angular app "ComplianceMode" in Elm
    (https://issues.rudder.io/issues/22969[#22969])
* Rewrite angular app "Node properties" in Elm
    (https://issues.rudder.io/issues/22741[#22741])
* Modify the hierarchy of elm applications to make their code shareable between them
    (https://issues.rudder.io/issues/22647[#22647])
* Rewrite the angular app "Policy mode" in Elm
    (https://issues.rudder.io/issues/22427[#22427])
* Rewrite the angular app "Policy mode" in Elm
    (https://issues.rudder.io/issues/22427[#22427])

==== Architecture - Code maintenance

* Rewrite angular app "textForm" in JavaScript
    (https://issues.rudder.io/issues/23041[#23041])
* Remove QueryTrait 
    (https://issues.rudder.io/issues/22678[#22678])

==== API

* Remove "no access" permission in token authorization
    (https://issues.rudder.io/issues/23014[#23014])

==== Web - Technique editor

* Use rudderc in webapp to generate internal techniques
    (https://issues.rudder.io/issues/22815[#22815])

==== rudderc

* Generator for Windows policies
    (https://issues.rudder.io/issues/22849[#22849])
* Update rudderc documentation
    (https://issues.rudder.io/issues/22721[#22721])
* Fallback on /var/rudder/ncf/common for library
    (https://issues.rudder.io/issues/22719[#22719])
* Allow generating runnable techniques
    (https://issues.rudder.io/issues/22573[#22573])
* Improve HTML doc of methods
    (https://issues.rudder.io/issues/22563[#22563])
* Update Rust tooling for 8.0
    (https://issues.rudder.io/issues/22561[#22561])
* Refactor CLI to work on a local directory
    (https://issues.rudder.io/issues/22545[#22545])

==== Relay server or API

* Remove md5 usage in relayd
    (https://issues.rudder.io/issues/22909[#22909])

==== Security

* Use cargo vet to check Rust dependencies
    (https://issues.rudder.io/issues/22816[#22816])

==== Architecture - Dependencies

* Update webapp dependencies 
    (https://issues.rudder.io/issues/22800[#22800])

==== System techniques

* remove syslog configuration and associated restart in the agent
    (https://issues.rudder.io/issues/22902[#22902])
* remove log rotation for slapd logs
    (https://issues.rudder.io/issues/22898[#22898])

==== Generic methods

* Update CFEngine stdlib to 3.21.1
    (https://issues.rudder.io/issues/22818[#22818])
* Add a 'Permissions POSIX ACLs entry parent' method
    (https://issues.rudder.io/issues/22386[#22386])

=== Bug fixes

==== Packaging

* Fixed: slapd cannot write in its log file
    (https://issues.rudder.io/issues/23048[#23048])
* Fixed: remove openssl 1.1.1 build hack un rudder 8.0
    (https://issues.rudder.io/issues/22961[#22961])
* Fixed: accelerate rpm build when perl modules are already present
    (https://issues.rudder.io/issues/22939[#22939])
* Fixed: rpm build may fail on old centos
    (https://issues.rudder.io/issues/22936[#22936])
* Fixed: build fail on amazon linux 2023
    (https://issues.rudder.io/issues/22935[#22935])
* Fixed: there is a hidden dependency on syslog service
    (https://issues.rudder.io/issues/22899[#22899])
* Fixed: Use system openssl for relayd
    (https://issues.rudder.io/issues/22888[#22888])
* Fixed: libxml2 sha256 is wrong
    (https://issues.rudder.io/issues/22855[#22855])
* Fixed: Failing patches of jetty
    (https://issues.rudder.io/issues/22851[#22851])
* Fixed: aix should continue to build 32 bits dependencies as before
    (https://issues.rudder.io/issues/22837[#22837])
* Fixed: old value aix-gcc doesn't work on openssl3
    (https://issues.rudder.io/issues/22835[#22835])
* Fixed: openssl3 configure script is deprecated
    (https://issues.rudder.io/issues/22834[#22834])
* Fixed: openssl3 is not detected at build time by curl
    (https://issues.rudder.io/issues/22833[#22833])
* Fixed: Document missing perl dependencies
    (https://issues.rudder.io/issues/22812[#22812])
* Fixed: 8.0 dependecny check is broken
    (https://issues.rudder.io/issues/22872[#22872])
* Fixed: docopt completion is installed in /usr/local/bin
    (https://issues.rudder.io/issues/22868[#22868])

==== Performance and scalability

* Fixed: use openssl 3 on very old and very recent OS in rudder 8
    (https://issues.rudder.io/issues/22817[#22817])

==== Miscellaneous

* Fixed: Require Java 17
    (https://issues.rudder.io/issues/22732[#22732])

==== Documentation

* Fixed: documentation on how to configure rsync relay synchroinisation is missing
    (https://issues.rudder.io/issues/22891[#22891])
* Fixed: Documentation on how to upgrade Rudder to 7.2 is invalid on zypper
    (https://issues.rudder.io/issues/22621[#22621])

==== Architecture - Code maintenance

* Fixed: Rudderc produces metadata.xml under target directory which breaks webapp
    (https://issues.rudder.io/issues/23053[#23053])
* Fixed: Rewrite file manager to an elm application
    (https://issues.rudder.io/issues/22988[#22988])
* Fixed: Cache most current Version number to save lots of memory
    (https://issues.rudder.io/issues/22978[#22978])
* Fixed: Rudder 8.0 compilation is broken
    (https://issues.rudder.io/issues/22986[#22986])
* Fixed: Snake-yaml dependency in zio-json is subjected to CVE
    (https://issues.rudder.io/issues/22983[#22983])

==== Web - Config management

* Fixed: Wrong command to call rudderc in webapp
    (https://issues.rudder.io/issues/23049[#23049])
* Fixed: Rudderc usage within Rudder webapp
    (https://issues.rudder.io/issues/22845[#22845])
* Fixed: Rudderc usage within Rudder webapp
    (https://issues.rudder.io/issues/22845[#22845])
* Fixed: Rudderc usage within Rudder webapp
    (https://issues.rudder.io/issues/22845[#22845])

==== Web - UI & UX

* Fixed: There is a blank space above almost every Rudder page
    (https://issues.rudder.io/issues/23042[#23042])
* Fixed: Directives tooltips go under navigation menu
    (https://issues.rudder.io/issues/22530[#22530])
* Fixed: Agent schedule and policy mode apps are not initialized anymore
    (https://issues.rudder.io/issues/22853[#22853])
* Fixed: Rewrite angular app "Agent schedule" in Elm
    (https://issues.rudder.io/issues/22510[#22510])

==== Server components

* Fixed: Grammar correction in error message
    (https://issues.rudder.io/issues/23027[#23027])

==== rudderc

* Fixed: Call rudderc with correct parameters
    (https://issues.rudder.io/issues/22973[#22973])
* Fixed: Windows generator generates invalid syntax
    (https://issues.rudder.io/issues/22972[#22972])
* Fixed: Broken test in rudderc
    (https://issues.rudder.io/issues/22726[#22726])
* Fixed: Check focus reporting has an existing id
    (https://issues.rudder.io/issues/22720[#22720])
* Fixed: Put images in src dir
    (https://issues.rudder.io/issues/22572[#22572])
* Fixed: Missing rsync to publish rudderc docs
    (https://issues.rudder.io/issues/22570[#22570])

==== Security

* Fixed: JS vulns in 8.0
    (https://issues.rudder.io/issues/22984[#22984])
* Fixed: Fix our GitHub SECURITY file
    (https://issues.rudder.io/issues/22964[#22964])
* Fixed: Ignore DoS in npm dependencies
    (https://issues.rudder.io/issues/22324[#22324])

==== Architecture - Dependencies

* Fixed: Update elm dependencies
    (https://issues.rudder.io/issues/22881[#22881])

==== API

* Fixed: Change json structure returned for /settings/allowed_networks
    (https://issues.rudder.io/issues/22456[#22456])

==== Techniques

* Fixed: Update user management to manage secondary group of user
    (https://issues.rudder.io/issues/22846[#22846])
* Fixed: Update user management to manage secondary group of user
    (https://issues.rudder.io/issues/22846[#22846])

==== System techniques

* Fixed: there is no all.log anymore, remove log rotation
    (https://issues.rudder.io/issues/22897[#22897])

==== Agent

* Fixed: Hard to understand set-force-audit help
    (https://issues.rudder.io/issues/23008[#23008])

==== Generic methods

* Fixed: Remove reporting heartbeat implementation
    (https://issues.rudder.io/issues/22660[#22660])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.
