== [Private] Rudder 8.0.0.alpha1 (2023-07-18)

=== Changes

[WARNING]
====

This version is only available for extended support subscription

====
    

==== Packaging

* Remove agent dependency on syslog
    (https://issues.rudder.io/issues/22900[#22900])
* Upgrade agent dependencies for 8.0
    (https://issues.rudder.io/issues/22840[#22840])
* Use openldap 2.6.4 in rudder 8
    (https://issues.rudder.io/issues/22793[#22793])
* Upgrade fusion inventory to 2.6
    (https://issues.rudder.io/issues/22791[#22791])
* Remove transitional packages in Rudder 8.0
    (https://issues.rudder.io/issues/22748[#22748])
* remove python2 support on rudder 8
    (https://issues.rudder.io/issues/22746[#22746])
* Require postgresql 13 on rudder 8
    (https://issues.rudder.io/issues/22745[#22745])
* Update cfengine to 3.21
    (https://issues.rudder.io/issues/22742[#22742])

==== Web - UI & UX

* Switch quicksearch to elm
    (https://issues.rudder.io/issues/23050[#23050])
* Remove old IE 5 & 6 JS compatibility code
    (https://issues.rudder.io/issues/23057[#23057])
* Remove heartbeat configuration from the settings
    (https://issues.rudder.io/issues/22659[#22659])
* Removing deprecated AngularJs applications
    (https://issues.rudder.io/issues/23036[#23036])
* Beautify no permission page when user have no rights
    (https://issues.rudder.io/issues/22626[#22626])
* Rewrite angular app "ComplianceMode" in Elm
    (https://issues.rudder.io/issues/22969[#22969])
* Rewrite angular app "Node properties" in Elm
    (https://issues.rudder.io/issues/22741[#22741])
* Modify the hierarchy of elm applications to make their code shareable between them
    (https://issues.rudder.io/issues/22647[#22647])
* Rewrite the angular app "Policy mode" in Elm
    (https://issues.rudder.io/issues/22427[#22427])
* Rewrite the angular app "Policy mode" in Elm
    (https://issues.rudder.io/issues/22427[#22427])

==== Architecture - Code maintenance

* Rewrite angular app "textForm" in JavaScript
    (https://issues.rudder.io/issues/23041[#23041])
* Remove QueryTrait 
    (https://issues.rudder.io/issues/22678[#22678])

==== API

* Remove "no access" permission in token authorization
    (https://issues.rudder.io/issues/23014[#23014])

==== Web - Technique editor

* Use rudderc in webapp to generate internal techniques
    (https://issues.rudder.io/issues/22815[#22815])

==== rudderc

* Generator for Windows policies
    (https://issues.rudder.io/issues/22849[#22849])
* Update rudderc documentation
    (https://issues.rudder.io/issues/22721[#22721])
* Fallback on /var/rudder/ncf/common for library
    (https://issues.rudder.io/issues/22719[#22719])
* Allow generating runnable techniques
    (https://issues.rudder.io/issues/22573[#22573])
* Improve HTML doc of methods
    (https://issues.rudder.io/issues/22563[#22563])
* Update Rust tooling for 8.0
    (https://issues.rudder.io/issues/22561[#22561])
* Refactor CLI to work on a local directory
    (https://issues.rudder.io/issues/22545[#22545])

==== Relay server or API

* Remove md5 usage in relayd
    (https://issues.rudder.io/issues/22909[#22909])

==== Security

* Use cargo vet to check Rust dependencies
    (https://issues.rudder.io/issues/22816[#22816])

==== Architecture - Dependencies

* Update webapp dependencies 
    (https://issues.rudder.io/issues/22800[#22800])

==== System techniques

* remove syslog configuration and associated restart in the agent
    (https://issues.rudder.io/issues/22902[#22902])
* remove log rotation for slapd logs
    (https://issues.rudder.io/issues/22898[#22898])

==== Generic methods

* Update CFEngine stdlib to 3.21.1
    (https://issues.rudder.io/issues/22818[#22818])
* Add a 'Permissions POSIX ACLs entry parent' method
    (https://issues.rudder.io/issues/22386[#22386])

=== Bug fixes

==== Packaging

* Fixed: slapd cannot write in its log file
    (https://issues.rudder.io/issues/23048[#23048])
* Fixed: remove openssl 1.1.1 build hack un rudder 8.0
    (https://issues.rudder.io/issues/22961[#22961])
* Fixed: accelerate rpm build when perl modules are already present
    (https://issues.rudder.io/issues/22939[#22939])
* Fixed: rpm build may fail on old centos
    (https://issues.rudder.io/issues/22936[#22936])
* Fixed: build fail on amazon linux 2023
    (https://issues.rudder.io/issues/22935[#22935])
* Fixed: there is a hidden dependency on syslog service
    (https://issues.rudder.io/issues/22899[#22899])
* Fixed: Use system openssl for relayd
    (https://issues.rudder.io/issues/22888[#22888])
* Fixed: libxml2 sha256 is wrong
    (https://issues.rudder.io/issues/22855[#22855])
* Fixed: Failing patches of jetty
    (https://issues.rudder.io/issues/22851[#22851])
* Fixed: aix should continue to build 32 bits dependencies as before
    (https://issues.rudder.io/issues/22837[#22837])
* Fixed: old value aix-gcc doesn't work on openssl3
    (https://issues.rudder.io/issues/22835[#22835])
* Fixed: openssl3 configure script is deprecated
    (https://issues.rudder.io/issues/22834[#22834])
* Fixed: openssl3 is not detected at build time by curl
    (https://issues.rudder.io/issues/22833[#22833])
* Fixed: Document missing perl dependencies
    (https://issues.rudder.io/issues/22812[#22812])
* Fixed: 8.0 dependecny check is broken
    (https://issues.rudder.io/issues/22872[#22872])
* Fixed: docopt completion is installed in /usr/local/bin
    (https://issues.rudder.io/issues/22868[#22868])

==== Performance and scalability

* Fixed: use openssl 3 on very old and very recent OS in rudder 8
    (https://issues.rudder.io/issues/22817[#22817])

==== Miscellaneous

* Fixed: Require Java 17
    (https://issues.rudder.io/issues/22732[#22732])

==== Documentation

* Fixed: documentation on how to configure rsync relay synchroinisation is missing
    (https://issues.rudder.io/issues/22891[#22891])
* Fixed: Documentation on how to upgrade Rudder to 7.2 is invalid on zypper
    (https://issues.rudder.io/issues/22621[#22621])

==== Architecture - Code maintenance

* Fixed: Rudderc produces metadata.xml under target directory which breaks webapp
    (https://issues.rudder.io/issues/23053[#23053])
* Fixed: Rewrite file manager to an elm application
    (https://issues.rudder.io/issues/22988[#22988])
* Fixed: Cache most current Version number to save lots of memory
    (https://issues.rudder.io/issues/22978[#22978])
* Fixed: Rudder 8.0 compilation is broken
    (https://issues.rudder.io/issues/22986[#22986])
* Fixed: Snake-yaml dependency in zio-json is subjected to CVE
    (https://issues.rudder.io/issues/22983[#22983])

==== Web - Config management

* Fixed: Wrong command to call rudderc in webapp
    (https://issues.rudder.io/issues/23049[#23049])
* Fixed: Rudderc usage within Rudder webapp
    (https://issues.rudder.io/issues/22845[#22845])
* Fixed: Rudderc usage within Rudder webapp
    (https://issues.rudder.io/issues/22845[#22845])
* Fixed: Rudderc usage within Rudder webapp
    (https://issues.rudder.io/issues/22845[#22845])

==== Web - UI & UX

* Fixed: There is a blank space above almost every Rudder page
    (https://issues.rudder.io/issues/23042[#23042])
* Fixed: Directives tooltips go under navigation menu
    (https://issues.rudder.io/issues/22530[#22530])
* Fixed: Agent schedule and policy mode apps are not initialized anymore
    (https://issues.rudder.io/issues/22853[#22853])
* Fixed: Rewrite angular app "Agent schedule" in Elm
    (https://issues.rudder.io/issues/22510[#22510])

==== Server components

* Fixed: Grammar correction in error message
    (https://issues.rudder.io/issues/23027[#23027])

==== rudderc

* Fixed: Call rudderc with correct parameters
    (https://issues.rudder.io/issues/22973[#22973])
* Fixed: Windows generator generates invalid syntax
    (https://issues.rudder.io/issues/22972[#22972])
* Fixed: Broken test in rudderc
    (https://issues.rudder.io/issues/22726[#22726])
* Fixed: Check focus reporting has an existing id
    (https://issues.rudder.io/issues/22720[#22720])
* Fixed: Put images in src dir
    (https://issues.rudder.io/issues/22572[#22572])
* Fixed: Missing rsync to publish rudderc docs
    (https://issues.rudder.io/issues/22570[#22570])

==== Security

* Fixed: JS vulns in 8.0
    (https://issues.rudder.io/issues/22984[#22984])
* Fixed: Fix our GitHub SECURITY file
    (https://issues.rudder.io/issues/22964[#22964])
* Fixed: Ignore DoS in npm dependencies
    (https://issues.rudder.io/issues/22324[#22324])

==== Architecture - Dependencies

* Fixed: Update elm dependencies
    (https://issues.rudder.io/issues/22881[#22881])

==== API

* Fixed: Change json structure returned for /settings/allowed_networks
    (https://issues.rudder.io/issues/22456[#22456])

==== Techniques

* Fixed: Update user management to manage secondary group of user
    (https://issues.rudder.io/issues/22846[#22846])
* Fixed: Update user management to manage secondary group of user
    (https://issues.rudder.io/issues/22846[#22846])

==== System techniques

* Fixed: there is no all.log anymore, remove log rotation
    (https://issues.rudder.io/issues/22897[#22897])

==== Agent

* Fixed: Hard to understand set-force-audit help
    (https://issues.rudder.io/issues/23008[#23008])

==== Generic methods

* Fixed: Remove reporting heartbeat implementation
    (https://issues.rudder.io/issues/22660[#22660])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

= Change logs for Rudder 8.0