= Changelogs for Rudder plugin api-authorizations 7.2.0.beta1-2.1.\* versions

== glpi-7.2.0.beta1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.0.beta1-2.1 series and therefore all installations of 7.2.0.beta1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-7.2.0.beta1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Broken plugins menu interface
    (https://issues.rudder.io/issues/21390[#21390])

==== Refactoring

* Fixed: Update dependencies from #21102
    (https://issues.rudder.io/issues/21115[#21115])

=== Release notes

This is a bug fix release in the 7.2.0.beta1-2.1 series and therefore all installations of 7.2.0.beta1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-7.2.0.beta1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.0.beta1-2.1 series and therefore all installations of 7.2.0.beta1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.2.0.beta1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Broken plugins menu interface
    (https://issues.rudder.io/issues/21390[#21390])
* Fixed: Broken build of maven plugins with elm apps after minification
    (https://issues.rudder.io/issues/21217[#21217])

=== Release notes

This is a bug fix release in the 7.2.0.beta1-2.1 series and therefore all installations of 7.2.0.beta1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== centreon-7.2.0.beta1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.0.beta1-2.1 series and therefore all installations of 7.2.0.beta1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-7.2.0.beta1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Broken plugins menu interface
    (https://issues.rudder.io/issues/21390[#21390])
* Fixed: Broken build of maven plugins with elm apps after minification
    (https://issues.rudder.io/issues/21217[#21217])

=== Release notes

This is a bug fix release in the 7.2.0.beta1-2.1 series and therefore all installations of 7.2.0.beta1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== api-authorizations-7.2.0.beta1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Broken build of maven plugins with elm apps after minification
    (https://issues.rudder.io/issues/21217[#21217])

=== Release notes

This is a bug fix release in the 7.2.0.beta1-2.1 series and therefore all installations of 7.2.0.beta1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

