= Changelogs for Rudder plugin api-authorizations 7.2.1-2.1.\* versions

== vault-7.2.1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.1 series and therefore all installations of 7.2.1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== scale-out-relay-7.2.1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.1 series and therefore all installations of 7.2.1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== openscap-7.2.1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.1 series and therefore all installations of 7.2.1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-7.2.1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.1 series and therefore all installations of 7.2.1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== glpi-7.2.1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.1 series and therefore all installations of 7.2.1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-7.2.1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.1 series and therefore all installations of 7.2.1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cis-7.2.1-2.1 (2022-12-06)

=== Changes


==== Packaging

* Dockerize basic tests for plugins
    (https://issues.rudder.io/issues/21190[#21190])
* Plugins package scripts should always exit on error
    (https://issues.rudder.io/issues/21008[#21008])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.1 series and therefore all installations of 7.2.1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.2.1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.1 series and therefore all installations of 7.2.1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== centreon-7.2.1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.1 series and therefore all installations of 7.2.1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-7.2.1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.1 series and therefore all installations of 7.2.1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== api-authorizations-7.2.1-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.1 series and therefore all installations of 7.2.1-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

