= Changelogs for Rudder plugin dsc 7.1.\* versions

== dsc-7.1.0-2.0 (2022-06-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.1.0.rc1-2.0 (2022-06-02)

=== Changes


=== Bug fixes

==== Generic methods

* Fixed: Re-use the report parameter of GM to handle the "disable reporting" from the technique editor
    (https://issues.rudder.io/issues/20959[#20959])

==== Miscellaneous

* Fixed: Use report instead of loglevel
    (https://issues.rudder.io/issues/20956[#20956])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.1.0.beta2-2.0 (2022-06-02)

=== Changes


==== Generic methods

* Add logs to the file_from_shared_folder method
    (https://issues.rudder.io/issues/20889[#20889])

=== Bug fixes

==== Generic methods

* Fixed: ncf methods changed signature in 7.0 in Rudder, but not in dsc, so we generate techniques with invalid parameters
    (https://issues.rudder.io/issues/20924[#20924])
* Fixed: Add loglevel parameter to each GM
    (https://issues.rudder.io/issues/20900[#20900])

==== Techniques

* Fixed: File download Rudder server technique don't work with Rudder 7.0
    (https://issues.rudder.io/issues/20906[#20906])
* Fixed: windows update technique fails to list updates
    (https://issues.rudder.io/issues/20783[#20783])

==== Misc

* Fixed: Broken tests in 7.0+
    (https://issues.rudder.io/issues/20920[#20920])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.1.0.beta1-2.0 (2022-06-02)

=== Changes


=== Bug fixes

==== System techniques

* Fixed: Make initial policies ignore HTTPS certificate to allow TOFU
    (https://issues.rudder.io/issues/19501[#19501])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

