= Changelogs for Rudder plugin secret-management 7.1.\* versions

== secret-management-7.1.0-1.0 (2022-06-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.1.0.rc1-1.0 (2022-06-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.1.0.beta2-1.0 (2022-06-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.1.0.beta1-1.0 (2022-06-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

