= Changelogs for Rudder plugin auth-backends 7.3.\* versions

== auth-backends-7.3.4-2.6 (2023-07-21)

=== Changes


==== Miscellaneous

* Better debug logs for OIDC provided roles
    (https://issues.rudder.io/issues/23022[#23022])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.0.alpha1-2.6 (2023-07-19)

=== Changes


==== Miscellaneous

* Better debug logs for OIDC provided roles
    (https://issues.rudder.io/issues/23022[#23022])

=== Bug fixes

==== Miscellaneous

* Fixed: Update plugin dependencies for 8.0
    (https://issues.rudder.io/issues/22806[#22806])
* Fixed: Update elm dependencies
    (https://issues.rudder.io/issues/22883[#22883])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.3-2.6 (2023-07-03)

=== Changes


==== Miscellaneous

* OIDC provided custom role list
    (https://issues.rudder.io/issues/22738[#22738])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.2.7-2.6 (2023-05-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.2-2.6 (2023-05-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.2.6-2.6 (2023-05-04)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: LDAP config example advocate for editing rudder-web.properties in place of using a dedicated file
    (https://issues.rudder.io/issues/22513[#22513])
* Fixed: Upgrade nimbus-jose-jwt to last patch release
    (https://issues.rudder.io/issues/22533[#22533])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.1-2.6 (2023-05-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.0-2.6 (2023-04-08)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: LDAP auth backend should deref link to allows finding user in remote directory
    (https://issues.rudder.io/issues/22158[#22158])
* Fixed: LDAP config example advocate for editing rudder-web.properties in place of using a dedicated file
    (https://issues.rudder.io/issues/22513[#22513])
* Fixed: Upgrade nimbus-jose-jwt to last patch release
    (https://issues.rudder.io/issues/22533[#22533])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.0.rc1-2.6 (2023-03-31)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: secrets are leaking at the install of the plugin
    (https://issues.rudder.io/issues/22441[#22441])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.0.beta1-2.6 (2023-03-31)

=== Changes


==== Packaging

* Use npm for building elm
    (https://issues.rudder.io/issues/22205[#22205])
*  Update elm dependencies - plugins
    (https://issues.rudder.io/issues/22052[#22052])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

