= Changelogs for Rudder plugin auth-backends 7.3.\* versions

== auth-backends-7.3.10-2.7 (2023-12-14)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.9-2.7 (2023-11-07)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.7-2.7 (2023-09-19)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.6-2.7 (2023-09-15)

=== Changes


==== Miscellaneous

* Add example log trace for LDAP connection errors
    (https://issues.rudder.io/issues/23321[#23321])
* Add how-to enable debug log for ldap authentication
    (https://issues.rudder.io/issues/23154[#23154])

=== Bug fixes

==== Miscellaneous

* Fixed: Bad doc for known authentication backends
    (https://issues.rudder.io/issues/23419[#23419])
* Fixed: not allowed to access errors because rudder plugins are missing AuthorizationApiMapping 
    (https://issues.rudder.io/issues/23348[#23348])
* Fixed: Add the role-retrieving OIDC feature to OAuth2
    (https://issues.rudder.io/issues/23112[#23112])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.5-2.6 (2023-09-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.4-2.6 (2023-07-22)

=== Changes


==== Miscellaneous

* Better debug logs for OIDC provided roles
    (https://issues.rudder.io/issues/23022[#23022])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.3-2.6 (2023-07-22)

=== Changes


==== Miscellaneous

* OIDC provided custom role list
    (https://issues.rudder.io/issues/22738[#22738])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.2-2.6 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.1-2.6 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.0-2.6 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: LDAP auth backend should deref link to allows finding user in remote directory
    (https://issues.rudder.io/issues/22158[#22158])
* Fixed: LDAP config example advocate for editing rudder-web.properties in place of using a dedicated file
    (https://issues.rudder.io/issues/22513[#22513])
* Fixed: Upgrade nimbus-jose-jwt to last patch release
    (https://issues.rudder.io/issues/22533[#22533])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.0.rc1-2.6 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: secrets are leaking at the install of the plugin
    (https://issues.rudder.io/issues/22441[#22441])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.3.0.beta1-2.6 (2023-07-22)

=== Changes


==== Packaging

* Use npm for building elm
    (https://issues.rudder.io/issues/22205[#22205])
*  Update elm dependencies - plugins
    (https://issues.rudder.io/issues/22052[#22052])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

