= Changelogs for Rudder plugin branding 7.3.\* versions

== branding-7.2.9-2.2 (2023-07-21)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-7.3.4-2.2 (2023-07-21)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-8.0.0.alpha1-2.2 (2023-07-19)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Update elm dependencies
    (https://issues.rudder.io/issues/22883[#22883])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-7.3.3-2.2 (2023-07-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-7.2.7-2.1 (2023-05-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-7.3.2-2.1 (2023-05-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-7.2.6-2.1 (2023-05-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-7.3.1-2.1 (2023-05-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-7.3.0-2.1 (2023-04-08)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Enabling branding plugin top bar causes minor glitches in the interface
    (https://issues.rudder.io/issues/22566[#22566])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-7.3.0.rc1-2.1 (2023-03-31)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: secrets are leaking at the install of the plugin
    (https://issues.rudder.io/issues/22441[#22441])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-7.3.0.beta1-2.1 (2023-03-31)

=== Changes


==== Packaging

* Use npm for building elm
    (https://issues.rudder.io/issues/22205[#22205])
*  Update elm dependencies - plugins
    (https://issues.rudder.io/issues/22052[#22052])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

