= Changelogs for Rudder plugin change-validation 7.3.\* versions

== change-validation-7.3.0-2.1 (2023-04-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.3.0.rc1-2.1 (2023-03-31)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: secrets are leaking at the install of the plugin
    (https://issues.rudder.io/issues/22441[#22441])
* Fixed: Adapt warning message to warn about merge with divergence
    (https://issues.rudder.io/issues/22364[#22364])
* Fixed: Changes made by validated users still need to be validated
    (https://issues.rudder.io/issues/22188[#22188])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.3.0.beta1-2.1 (2023-03-31)

=== Changes


==== Packaging

* Use npm for building elm
    (https://issues.rudder.io/issues/22205[#22205])
*  Update elm dependencies - plugins
    (https://issues.rudder.io/issues/22052[#22052])

=== Bug fixes

==== Miscellaneous

* Fixed: Adapt code to changes from #22206 (custom roles)
    (https://issues.rudder.io/issues/22361[#22361])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

