= Changelogs for Rudder plugin cve 7.3.\* versions

== cve-7.3.16-2.9 (2024-07-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.15-2.9 (2024-06-05)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.14-2.9 (2024-04-25)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Error 500 when looking at a cve detail
    (https://issues.rudder.io/issues/22448[#22448])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.13-2.9 (2024-03-11)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.12-2.9 (2024-02-29)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.11-2.9 (2024-02-02)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Fix small UI & logs problems
    (https://issues.rudder.io/issues/24118[#24118])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.10-2.9 (2023-12-14)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Make log about skipping windows clearer
    (https://issues.rudder.io/issues/23702[#23702])
* Fixed: Hide psql notice message in upgrade output
    (https://issues.rudder.io/issues/23714[#23714])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.9-2.9 (2023-11-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.8-2.9 (2023-12-06)

=== Changes


==== Miscellaneous

* Add link to distrib security trackers, add nvd link
    (https://issues.rudder.io/issues/23672[#23672])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.7-2.9 (2023-09-19)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.6-2.9 (2023-09-15)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Display that our scores are base scores from NVD
    (https://issues.rudder.io/issues/21212[#21212])
* Fixed: Add rights to system update plugin
    (https://issues.rudder.io/issues/23097[#23097])
* Fixed: Unknown CVE with a score of 0 and 0 packages impacted
    (https://issues.rudder.io/issues/22878[#22878])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florent NEYRON

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.5-2.9 (2023-09-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.4-2.9 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.3-2.9 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.2-2.9 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.1-2.9 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.0-2.9 (2023-07-22)

=== Changes


==== Miscellaneous

* Document CVE provided permissions
    (https://issues.rudder.io/issues/22564[#22564])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.0.rc1-2.9 (2023-07-22)

=== Changes


==== Miscellaneous

* Use Html.lazy to optimise html rendering
    (https://issues.rudder.io/issues/22439[#22439])

=== Bug fixes

==== Miscellaneous

* Fixed: Syntax error in cve details request 
    (https://issues.rudder.io/issues/22451[#22451])
* Fixed: Do not load history of previously selected node/cve
    (https://issues.rudder.io/issues/22440[#22440])
* Fixed: The "Security management" link in the navigation menu is not correctly aligned with the other links
    (https://issues.rudder.io/issues/22399[#22399])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.3.0.beta1-2.9 (2023-07-22)

=== Changes


==== Miscellaneous

* Add cve plugin rights
    (https://issues.rudder.io/issues/22199[#22199])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

