= Changelogs for Rudder plugin datasources 7.3.\* versions

== datasources-7.2.7-2.2 (2023-05-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-7.3.2-2.3 (2023-05-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-7.2.6-2.2 (2023-05-04)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Datasources plugin scheduler problems after updating/deleting a datasource
    (https://issues.rudder.io/issues/12752[#12752])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* I C

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-7.3.1-2.3 (2023-05-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-7.3.0-2.3 (2023-04-08)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Datasources plugin scheduler problems after updating/deleting a datasource
    (https://issues.rudder.io/issues/12752[#12752])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* I C

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-7.3.0.rc1-2.3 (2023-03-31)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: secrets are leaking at the install of the plugin
    (https://issues.rudder.io/issues/22441[#22441])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-7.3.0.beta1-2.3 (2023-03-31)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

