= Changelogs for Rudder plugin dsc 7.3.\* versions

== dsc-7.3.0-2.4 (2023-04-27)

=== Changes


==== Packaging

* Update windows submodule for 7.3
    (https://issues.rudder.io/issues/22639[#22639])

=== Bug fixes

==== System techniques

* Fixed: Typo in the system policies
    (https://issues.rudder.io/issues/22638[#22638])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.3.0-2.3 (2023-04-27)

=== Changes


==== Miscellaneous

* Rudder-agent check should create a default agent.conf if it does not exist
    (https://issues.rudder.io/issues/22473[#22473])

=== Bug fixes

==== ci

* Fixed: Conflicting declaration of agentVersion variable
    (https://issues.rudder.io/issues/22603[#22603])
* Fixed: Add NodeId aslegacy variable in the linter
    (https://issues.rudder.io/issues/22600[#22600])

==== Generic methods

* Fixed: Condition from command asks for techniqueName parameter
    (https://issues.rudder.io/issues/22325[#22325])
* Fixed: Missing documentation on generic methods Registry entry *
    (https://issues.rudder.io/issues/22316[#22316])
* Fixed: 7.3 must keep compatibility with the older ncf_lib and system technique functions
    (https://issues.rudder.io/issues/22562[#22562])
* Fixed: File_from_template_mustache fails to render dict variables defined in 7.3
    (https://issues.rudder.io/issues/22557[#22557])

==== System techniques

* Fixed: Refactor part of the schedule task system technique
    (https://issues.rudder.io/issues/22604[#22604])

==== Packaging

* Fixed: Allow the msi to do MajorUpgrade on nightly builds
    (https://issues.rudder.io/issues/22582[#22582])
* Fixed: The name of the Rudder sofware did change, it must not
    (https://issues.rudder.io/issues/22555[#22555])

==== CLI

* Fixed: Rudder agent version does not output anything
    (https://issues.rudder.io/issues/22576[#22576])
* Fixed: Module functions must follow be named following the powershell approved verbs
    (https://issues.rudder.io/issues/22514[#22514])
* Fixed: Fix several issues in system techniques and postinst
    (https://issues.rudder.io/issues/22487[#22487])
* Fixed: Rudder agent check should fallback to initial policy if no policies are found or when forcing a reset
    (https://issues.rudder.io/issues/22483[#22483])
* Fixed: Get-TomlValue must accept empty inputs
    (https://issues.rudder.io/issues/22482[#22482])

==== Techniques

* Fixed: WindowsSoftware technique in 2.1 version is not 7.2+ policy compatible
    (https://issues.rudder.io/issues/22389[#22389])

==== Agent library

* Fixed: LastReportTime, LastStartExecutionTime, LastEndExecutionTime, LastSuccessfulUpdate and LastInventorySent are not stored anymore
    (https://issues.rudder.io/issues/22472[#22472])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.3.0.rc1-2.3 (2023-03-31)

=== Changes


==== Packaging

* Dockerize the agent build
    (https://issues.rudder.io/issues/22343[#22343])
* Refactor the Wix files
    (https://issues.rudder.io/issues/22421[#22421])

=== Bug fixes

==== Packaging

* Fixed: Permissions are not set on the Rudder folder when installing from the msi installer
    (https://issues.rudder.io/issues/22474[#22474])
* Fixed: Fusion patched files are not deployed in the correct folder
    (https://issues.rudder.io/issues/22461[#22461])
* Fixed: Fix postinstall execution
    (https://issues.rudder.io/issues/22460[#22460])
* Fixed: typo in installer builder
    (https://issues.rudder.io/issues/22450[#22450])
* Fixed: When upgrading the agent the msi installer wipes every agent conf files
    (https://issues.rudder.io/issues/22417[#22417])
* Fixed: policy server is not written anymore
    (https://issues.rudder.io/issues/22425[#22425])

==== Agent library

* Fixed: Rename Test-AgentIsDisabled.ps1 as files named using the keyword Test are skipped at build time
    (https://issues.rudder.io/issues/22471[#22471])
* Fixed: Missing Update-Log function from rudderCLi module
    (https://issues.rudder.io/issues/22247[#22247])
* Fixed: Fix the classes.ps1 library and test
    (https://issues.rudder.io/issues/22409[#22409])

==== CLI

* Fixed: Missing rudder agent factory reset on windows agent
    (https://issues.rudder.io/issues/22454[#22454])
* Fixed: when rudder agent is disabled, we can still run it 
    (https://issues.rudder.io/issues/21596[#21596])
* Fixed: rudder agent server-keys-reset does throw errors at execution
    (https://issues.rudder.io/issues/21231[#21231])
* Fixed: Execution time of the agent run is incorrectly computed
    (https://issues.rudder.io/issues/22327[#22327])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.3.0.beta1-2.3 (2023-03-31)

=== Changes


==== Miscellaneous

* Load inputs from system techniques
    (https://issues.rudder.io/issues/22222[#22222])
* Remove the directives.ps1 and system-direcitves.ps1 from the dsc-common bundle
    (https://issues.rudder.io/issues/22238[#22238])

==== Packaging

* Document msi build process
    (https://issues.rudder.io/issues/22337[#22337])
* Use msi compatible version for windows agent
    (https://issues.rudder.io/issues/22273[#22273])
* Build package with wix
    (https://issues.rudder.io/issues/22261[#22261])
* Update dotnet dependencies
    (https://issues.rudder.io/issues/22075[#22075])

==== System techniques

* Update the system techiques to the standard generation format
    (https://issues.rudder.io/issues/22275[#22275])

==== Agent library

* Add a reportJson ResultStatus type
    (https://issues.rudder.io/issues/22212[#22212])

==== CLI

* Refactor the agent to use Powershell modules feature
    (https://issues.rudder.io/issues/21984[#21984])

=== Bug fixes

==== CLI

* Fixed: Missing 'rudder agent policy-server' command
    (https://issues.rudder.io/issues/22335[#22335])
* Fixed: common/resources/RudderCli/Public/Invoke-RudderAgentUpdate.ps1 was not merged correctly
    (https://issues.rudder.io/issues/22269[#22269])

==== Packaging

* Fixed: Update the postinst script to 7.3
    (https://issues.rudder.io/issues/22329[#22329])

==== System techniques

* Fixed: Windows agent does not define the inventory variables
    (https://issues.rudder.io/issues/22284[#22284])
* Fixed: Missing reports in system techniques in 7.2
    (https://issues.rudder.io/issues/21421[#21421])

==== Generic methods

* Fixed: Support powershell 4 (Rudder 7.3 edition)
    (https://issues.rudder.io/issues/22111[#22111])

==== Miscellaneous

* Fixed: typo in powershell_execution method
    (https://issues.rudder.io/issues/21426[#21426])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

