= Changelogs for Rudder plugin dsc 7.3.\* versions

== dsc-7.3.0.beta1-2.3 (2023-07-22)

=== Changes


==== Miscellaneous

* Load inputs from system techniques
    (https://issues.rudder.io/issues/22222[#22222])
* Remove the directives.ps1 and system-direcitves.ps1 from the dsc-common bundle
    (https://issues.rudder.io/issues/22238[#22238])

==== Packaging

* Document msi build process
    (https://issues.rudder.io/issues/22337[#22337])
* Use msi compatible version for windows agent
    (https://issues.rudder.io/issues/22273[#22273])
* Build package with wix
    (https://issues.rudder.io/issues/22261[#22261])
* Update dotnet dependencies
    (https://issues.rudder.io/issues/22075[#22075])

==== System techniques

* Update the system techiques to the standard generation format
    (https://issues.rudder.io/issues/22275[#22275])

==== Agent library

* Add a reportJson ResultStatus type
    (https://issues.rudder.io/issues/22212[#22212])

==== CLI

* Refactor the agent to use Powershell modules feature
    (https://issues.rudder.io/issues/21984[#21984])

=== Bug fixes

==== CLI

* Fixed: Missing 'rudder agent policy-server' command
    (https://issues.rudder.io/issues/22335[#22335])
* Fixed: common/resources/RudderCli/Public/Invoke-RudderAgentUpdate.ps1 was not merged correctly
    (https://issues.rudder.io/issues/22269[#22269])

==== Packaging

* Fixed: Update the postinst script to 7.3
    (https://issues.rudder.io/issues/22329[#22329])

==== System techniques

* Fixed: Windows agent does not define the inventory variables
    (https://issues.rudder.io/issues/22284[#22284])
* Fixed: Missing reports in system techniques in 7.2
    (https://issues.rudder.io/issues/21421[#21421])

==== Generic methods

* Fixed: Support powershell 4 (Rudder 7.3 edition)
    (https://issues.rudder.io/issues/22111[#22111])

==== Miscellaneous

* Fixed: typo in powershell_execution method
    (https://issues.rudder.io/issues/21426[#21426])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

