= Changelogs for Rudder plugin reporting 7.3.\* versions

== reporting-7.3.4-2.1 (2023-07-21)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-8.0.0.alpha1-2.1 (2023-07-19)

=== Changes


==== Miscellaneous

* Adapt cve plugin to changes in 22976
    (https://issues.rudder.io/issues/23063[#23063])

=== Bug fixes

==== Miscellaneous

* Fixed: Update elm dependencies
    (https://issues.rudder.io/issues/22884[#22884])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-7.3.3-2.1 (2023-07-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-7.2.7-2.1 (2023-05-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-7.3.2-2.1 (2023-05-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-7.2.6-2.1 (2023-05-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-7.3.1-2.1 (2023-05-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-7.3.0-2.1 (2023-04-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-7.3.0.rc1-2.1 (2023-03-31)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-7.3.0.beta1-2.1 (2023-03-31)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

