= Changelogs for Rudder plugin secret-management 7.3.\* versions

== secret-management-7.3.2-1.1 (2023-05-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.2.6-1.1 (2023-05-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.3.1-1.1 (2023-05-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.3.0-1.1 (2023-04-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.3.0.rc1-1.1 (2023-03-31)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.3.0.beta1-1.1 (2023-03-31)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

