= Changelogs for Rudder plugin system-updates 7.3.\* versions

== system-updates-7.3.0-1.12 (2023-04-08)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Add linter and fix typos in the windows version of the technique
    (https://issues.rudder.io/issues/22599[#22599])
* Fixed: Nodes target are not displayed on software update campaigns
    (https://issues.rudder.io/issues/22605[#22605])
* Fixed: Error in clean event/objects make rudder fails booting
    (https://issues.rudder.io/issues/22423[#22423])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.0.rc1-1.12 (2023-03-31)

=== Changes


==== Miscellaneous

* Allow rebooting only when necessary
    (https://issues.rudder.io/issues/22365[#22365])

=== Bug fixes

==== Miscellaneous

* Fixed: The "patch management" text in the navigation menu does not respect the same naming convention as the other links
    (https://issues.rudder.io/issues/22398[#22398])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.0.beta1-1.12 (2023-03-31)

=== Changes


==== Miscellaneous

* Allow upgrading specific packages in update campaigns
    (https://issues.rudder.io/issues/22302[#22302])
* Add the windows support
    (https://issues.rudder.io/issues/22152[#22152])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

