= Changelogs for Rudder plugin system-updates 7.3.\* versions

== system-updates-7.3.14-1.14 (2024-04-25)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.13-1.13 (2024-03-11)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.12-1.13 (2024-02-29)

=== Changes


=== Bug fixes

==== Web - UI & UX

* Fixed: We should not be able to access page Update campaigns with role inventory
    (https://issues.rudder.io/issues/24116[#24116])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.11-1.13 (2024-02-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.10-1.12 (2023-12-14)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: system-updates/system-update-schema.sql is listed two times in the files.txz archive
    (https://issues.rudder.io/issues/23843[#23843])
* Fixed: No reports from system update campaign
    (https://issues.rudder.io/issues/23745[#23745])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.9-1.12 (2023-11-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.8-1.12 (2023-12-06)

=== Changes


==== Miscellaneous

* Improve system update hooks
    (https://issues.rudder.io/issues/23465[#23465])

=== Bug fixes

==== Miscellaneous

* Fixed: Patch campaigns are broken with python error
    (https://issues.rudder.io/issues/23636[#23636])
* Fixed: Once we save a system campaign, the display still shows that we can save it
    (https://issues.rudder.io/issues/23295[#23295])
* Fixed: Add a log line in patch output for a node for a node so we know if it rebooted or not
    (https://issues.rudder.io/issues/23408[#23408])
* Fixed: Missing documentation about what rights plugin has
    (https://issues.rudder.io/issues/23428[#23428])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.7-1.12 (2023-09-19)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: System update report is not parseable
    (https://issues.rudder.io/issues/23445[#23445])
* Fixed: Wrong directory for hooks in docs
    (https://issues.rudder.io/issues/23448[#23448])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.6-1.12 (2023-09-15)

=== Changes


==== Miscellaneous

* Document update hooks
    (https://issues.rudder.io/issues/23411[#23411])

=== Bug fixes

==== Miscellaneous

* Fixed: After getting timezone, we refresh all data from plugin, making it reload in continuous when selecting a campaign
    (https://issues.rudder.io/issues/23433[#23433])
* Fixed: Font used for Add Software seems non standard
    (https://issues.rudder.io/issues/22705[#22705])
* Fixed: Doc Windows compat in docs
    (https://issues.rudder.io/issues/23399[#23399])
* Fixed: Add rights to system update plugin
    (https://issues.rudder.io/issues/23097[#23097])
* Fixed: Error 500 when we select an end hour at or before the start date of the campaign
    (https://issues.rudder.io/issues/23222[#23222])
* Fixed: Show campaign and event id in UI
    (https://issues.rudder.io/issues/23304[#23304])
* Fixed: when we create a campaign, the server time displayed is the time when the page was loaded, not when we clicked on new campaign
    (https://issues.rudder.io/issues/23296[#23296])
* Fixed: issue on logging in verbose mode
    (https://issues.rudder.io/issues/23297[#23297])
* Fixed: number of nodes in the list of applicable patch is not valid
    (https://issues.rudder.io/issues/23052[#23052])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.5-1.12 (2023-09-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.4-1.12 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: update campaign fail by asking question
    (https://issues.rudder.io/issues/23024[#23024])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.3-1.12 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: node filter in system update page in case sensitive
    (https://issues.rudder.io/issues/22750[#22750])
* Fixed: Use fnv for calculating update splaytime
    (https://issues.rudder.io/issues/22890[#22890])
* Fixed: The end of the upgrade window computation is wrong, leading to skipping some updates
    (https://issues.rudder.io/issues/22906[#22906])

==== Packaging

* Fixed: add label to rudder-plugin-private docker images
    (https://issues.rudder.io/issues/22921[#22921])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.2-1.12 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.1-1.12 (2023-07-22)

=== Changes


==== Miscellaneous

* Add default local logging on windows
    (https://issues.rudder.io/issues/22631[#22631])

=== Bug fixes

==== Miscellaneous

* Fixed: Windows version of the plugin can not parse input dates when not in UTC
    (https://issues.rudder.io/issues/22700[#22700])
* Fixed: It is not possible to delete or disable software update campaigns
    (https://issues.rudder.io/issues/22670[#22670])
* Fixed: In the select group in the target tab of the campaign there is an unnecessary hamburger button
    (https://issues.rudder.io/issues/22661[#22661])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.0-1.12 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Add linter and fix typos in the windows version of the technique
    (https://issues.rudder.io/issues/22599[#22599])
* Fixed: Nodes target are not displayed on software update campaigns
    (https://issues.rudder.io/issues/22605[#22605])
* Fixed: Error in clean event/objects make rudder fails booting
    (https://issues.rudder.io/issues/22423[#22423])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.0.rc1-1.12 (2023-07-22)

=== Changes


==== Miscellaneous

* Allow rebooting only when necessary
    (https://issues.rudder.io/issues/22365[#22365])

=== Bug fixes

==== Miscellaneous

* Fixed: The "patch management" text in the navigation menu does not respect the same naming convention as the other links
    (https://issues.rudder.io/issues/22398[#22398])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.3.0.beta1-1.12 (2023-07-22)

=== Changes


==== Miscellaneous

* Allow upgrading specific packages in update campaigns
    (https://issues.rudder.io/issues/22302[#22302])
* Add the windows support
    (https://issues.rudder.io/issues/22152[#22152])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

