= Changelogs for Rudder plugin user-management 7.3.\* versions

== user-management-7.3.2-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.3.1-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: save button is "SaveSave"
    (https://issues.rudder.io/issues/22697[#22697])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.3.0-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Plugin writes "roles" in place of "permissions"
    (https://issues.rudder.io/issues/22580[#22580])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.3.0.rc1-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Adapt user-management plugin to parseRight (#22457)
    (https://issues.rudder.io/issues/22458[#22458])
* Fixed: secrets are leaking at the install of the plugin
    (https://issues.rudder.io/issues/22441[#22441])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.3.0.beta1-2.2 (2023-07-22)

=== Changes


==== Packaging

* Use npm for building elm
    (https://issues.rudder.io/issues/22205[#22205])
*  Update elm dependencies - plugins
    (https://issues.rudder.io/issues/22052[#22052])

=== Bug fixes

==== Miscellaneous

* Fixed: Update user plugin to manage update custom roles
    (https://issues.rudder.io/issues/22349[#22349])
* Fixed: Update user plugin to manage update custom roles
    (https://issues.rudder.io/issues/22349[#22349])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

