= Rudder 6.2 release notes

== What's new?

Following our new versioning scheme, 6.2 is a **minor** release that
improves the 6.X branch while avoiding architecture changes
to provide a straightforward upgrade process and ensure reliability.

But make no mistake, it's a minor release that comes with **major user experience improvements**!

=== UI

* *Configurable columns* in node list (yes, that's what you think!). You can display properties values,
  inventory data like any software version, IP addresses,  etc.
* *Directives and Settings* pages are greatly improved.
* The look of most pages has been improved and made more consistent.

=== CVE plugin

* New view by node to visualize the state of known vulnerabilities on individual nodes.
* Tracking and graphing of vulnerability remediation over time.
* More generally, the plugin is now well tested and ready for production use.

=== Health check

Ever wondered how your Rudder server was going or why it started slowing down?
The https://docs.rudder.io/reference/6.2/administration/server.html#_health_check[health check] will make it easy with:

* An *API* endpoint for precise monitoring.
* *Dedicated page* for easy visualization.
* *Notifications* in the menu bar not to miss important stuff.

=== Plugins management

* *Automated plugin upgrade*. No more incompatible or disabled plugins after upgrade! (if your server
  has access to the download server).
* Rudder *instances behind proxies* will now be able to download plugins and use external APIs through
  your proxy.

=== Platforms

==== Windows

* *Windows* agent is now capable of applying DSC configurations directly. You can either use a source file
  that the agent will compile and apply, or directly apply a compiled state (in MOF format). In both cases
  the outcome will be reported in Rudder like any other component.
* The great *Chocolatey* software management tool is now supported, allowing easier software
  management automation.

==== Unix

* *Solaris* support has been added: packaged agent, *ips* package manager, service management, etc.
* *AIX* now supports the *nim* package manager in addition to yum/rpm.
* *Augeas* is now embedded (or installed as a dependency), to allow powerful file editions with a lot
  of pre-defined configuration file formats.

==== Docker/Containers

* A technical preview for *production Rudder relay* running in *read-only unprivileged containers* is now available.
  This is a first step before working on the root server too, we'd love to get feedback if you want to try it!

=== Inventory hooks

New hooks for inventory reception on the server are added, allowing to trigger automated acceptation
process or to notify about a broken inventory.

== Installing, upgrading and testing

* Install docs for https://docs.rudder.io/reference/6.2/installation/server/debian.html[Debian/Ubuntu],
https://docs.rudder.io/reference/6.2/installation/server/rhel.html[RHEL/centOS] and 
https://docs.rudder.io/reference/6.2/installation/server/sles.html[SLES]
* https://docs.rudder.io/reference/6.2/installation/upgrade/notes.html[Upgrade nodes and doc]
* https://docs.rudder.io/reference/6.2/installation/versions.html#_versions[Download links]

== Supported operating systems

This version provides packages for these operating systems:

* Rudder server and Rudder relay: *Debian 9-10, RHEL/CentOS 7-8 (64 bits),
SLES 12-15, Ubuntu 18.04 LTS and 20.04 LTS*
* Rudder agent: all of the above plus *Debian 8, RHEL/CentOS 6, Ubuntu 14.04 LTS, Ubuntu 16.04 LTS*
* Rudder agent (binary packages available with a https://www.rudder.io/en/pricing/subscription/[subscription]) : *Debian 5-7, RHEL/CentOS 3-5,
SLES 10-11, Ubuntu 10.04 LTS-12.04 LTS-13.04-15.10, Windows Server 2008R2-2019, AIX
5-6-7, Solaris 10 & 11, Slackware 14*

Read more about supported operating systems 
https://docs.rudder.io/reference/6.2/installation/operating_systems.html[in the documentation].

