= Change logs for Rudder 6.2

Rudder 6.2 is currently a maintained version of Rudder.

==  Rudder 6.2.9 (2021-07-20)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Or selector for property Name=Value selector returns 0 elements
    (https://issues.rudder.io/issues/19538[#19538])

==== Documentation

* Fixed: Correctly name LICENSES folder in repo
    (https://issues.rudder.io/issues/19535[#19535])

==== Security

* Fixed: CVE in jsonpath dependency
    (https://issues.rudder.io/issues/19530[#19530])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


== Rudder 6.2.8 (2021-07-09)

=== Changes

==== Packaging

* Add debian 11 build flags to 6.2
    (https://issues.rudder.io/issues/19391[#19391])
* Add ci checks for packages
    (https://issues.rudder.io/issues/19362[#19362])
* Improve pylint config and add formatter to rudder-pkg
    (https://issues.rudder.io/issues/19441[#19441])
* rudder-pkg test should use python3
    (https://issues.rudder.io/issues/19405[#19405])
* Backport typos checks to 6.1
    (https://issues.rudder.io/issues/19359[#19359])
* Clean workspace at the end of Rust builds
    (https://issues.rudder.io/issues/19246[#19246])
* Clean workspace at the end of Rust builds
    (https://issues.rudder.io/issues/19246[#19246])
* Add ci check for techniques
    (https://issues.rudder.io/issues/19355[#19355])
* Add ci checks on rudder-agent repo
    (https://issues.rudder.io/issues/19354[#19354])

==== Documentation

* Missing doc about methods ordering
    (https://issues.rudder.io/issues/19462[#19462])
* Add ci check for typos in docs
    (https://issues.rudder.io/issues/19360[#19360])

=== Bug fixes

==== Plugins integration

* Fixed: when upgrading rudder, plugins are upgraded, but are disabled
    (https://issues.rudder.io/issues/19517[#19517])

==== Packaging

* Fixed: No more need for insserv-compat as all our services are systemd units
    (https://issues.rudder.io/issues/19509[#19509])
* Fixed: Broken agent postinst script
    (https://issues.rudder.io/issues/19406[#19406])
* Fixed: Broken short hostname in agent certificate
    (https://issues.rudder.io/issues/19447[#19447])
* Fixed: Api doc publish does not require docs label
    (https://issues.rudder.io/issues/19408[#19408])

==== Agent

* Fixed: rudder-agent-postinst fails in 7.0 while closing fd
    (https://issues.rudder.io/issues/19429[#19429])
* Fixed: Rudder agent check should check if certificate matches private key
    (https://issues.rudder.io/issues/19392[#19392])

==== Documentation

* Fixed: Outdated doc for setting limit of open files for the webapp
    (https://issues.rudder.io/issues/19494[#19494])
* Fixed: Remove wrong doc about services passwords
    (https://issues.rudder.io/issues/19493[#19493])
* Fixed: Fix docs about HTTPS reporting in non-compliant mode
    (https://issues.rudder.io/issues/19437[#19437])
* Fixed: Update Ansible integration link to Rudder inventory script
    (https://issues.rudder.io/issues/19420[#19420])
* Fixed: Document minimum version of JDK (8u92)
    (https://issues.rudder.io/issues/19280[#19280])
* Fixed: Missing 'settings' layer in the allowed_networks API doc
    (https://issues.rudder.io/issues/19502[#19502])
* Fixed: Add name to LDAP pool to help debugging
    (https://issues.rudder.io/issues/19284[#19284])
* Fixed: Improve augeas set method
    (https://issues.rudder.io/issues/19260[#19260])

==== Security

* Fixed: Lack of HTML escaping in nodes list
    (https://issues.rudder.io/issues/19456[#19456])
* Fixed: Vulnerability in spring-security
    (https://issues.rudder.io/issues/19503[#19503])
* Fixed: Enforce stricter restriction on authorized node id and hostname
    (https://issues.rudder.io/issues/19457[#19457])
* Fixed: Command injection in plugins repository file names
    (https://issues.rudder.io/issues/19442[#19442])
* Fixed: CVE in spring dependency
    (https://issues.rudder.io/issues/19407[#19407])
* Fixed: Update snakeyaml dependency for security
    (https://issues.rudder.io/issues/19400[#19400])
* Fixed: rudder.auth.admin.pass should be stored in bcrypt format
    (https://issues.rudder.io/issues/19308[#19308])
* Fixed: Ignore security alert for unused js embeded in scala lib
    (https://issues.rudder.io/issues/19272[#19272])

==== Web - UI & UX

* Fixed: Directive details display is broken if the name of a directive is too long.
    (https://issues.rudder.io/issues/19487[#19487])

==== Performance and scalability

* Fixed: Inefficient comparision of strings in Rudder
    (https://issues.rudder.io/issues/19467[#19467])
* Fixed: Improve NodeInfo cache
    (https://issues.rudder.io/issues/19399[#19399])
* Fixed: Move use of cache outside of semaphore in NodeInfoService
    (https://issues.rudder.io/issues/19396[#19396])
* Fixed: Semaphore on Nodeinfoservice is not working
    (https://issues.rudder.io/issues/19351[#19351])

==== Relay server or API

* Fixed: Prevent parameter option injection in remote run
    (https://issues.rudder.io/issues/19455[#19455])
* Fixed: relayd on relays fails to retry inventories upload
    (https://issues.rudder.io/issues/19375[#19375])

==== System techniques

* Fixed: Missing cleanup of /var/rudder/reports/failed
    (https://issues.rudder.io/issues/19435[#19435])

==== Web - Config management

* Fixed: Inventory with updated properties doesn't always start a policy generation
    (https://issues.rudder.io/issues/19414[#19414])
* Fixed: Semaphore in APIAccountRepository,GitArchiverUtils and maybe PolicyServerManagementService are not semaphoring
    (https://issues.rudder.io/issues/19363[#19363])

==== Web - Nodes & inventories

* Fixed: When a node is totally deleted, cache in NodeInfoService can't know about it
    (https://issues.rudder.io/issues/19394[#19394])
* Fixed: In inventory, if there are two "rudder" tag, uuid are concatenated
    (https://issues.rudder.io/issues/19305[#19305])
* Fixed: Error when processing old inventories with davfs temporary files
    (https://issues.rudder.io/issues/19268[#19268])

==== API

* Fixed: Info API is not documented
    (https://issues.rudder.io/issues/19395[#19395])
* Fixed: API shows only part of the memory information
    (https://issues.rudder.io/issues/19374[#19374])
* Fixed: Remove reference to x-www-form-urlencoded in API commands
    (https://issues.rudder.io/issues/19276[#19276])

==== System integration

* Fixed: Confusing message when we disable non-compliant-report log
    (https://issues.rudder.io/issues/19381[#19381])

==== Techniques

* Fixed: Policy validation at the end of policy generation spends too much time evaluating things
    (https://issues.rudder.io/issues/19477[#19477])
* Fixed: File content always reports repair when "Replace content" is selected
    (https://issues.rudder.io/issues/19445[#19445])
* Fixed: Invalid reporting in file content technique
    (https://issues.rudder.io/issues/19431[#19431])
* Fixed: User technique should show unix option by default
    (https://issues.rudder.io/issues/19403[#19403])
* Fixed: cron management doesn't support multiline entry correctly
    (https://issues.rudder.io/issues/19336[#19336])
* Fixed: When configuring a comment in ssh key in technique ssh key distribution, 6 spaces are added at start of comment line
    (https://issues.rudder.io/issues/19335[#19335])
* Fixed: User Management technique tries to always change user gid when forcing the check of user gid everytime
    (https://issues.rudder.io/issues/19269[#19269])
* Fixed: Group management technique doesn't correctly honor gid option
    (https://issues.rudder.io/issues/19266[#19266])

==== CI

* Fixed: Hardcod the output of the style test TestClassPrefix in success cases
    (https://issues.rudder.io/issues/19404[#19404])
* Fixed:  Add typos check to CI config
    (https://issues.rudder.io/issues/19343[#19343])
* Fixed: Force pylint3 instead of pylint in qa-test
    (https://issues.rudder.io/issues/19390[#19390])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Lars Koenen

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


==  Rudder 6.2.7 (2021-05-18)

=== Changes


==== Packaging

* Improve script linter in rudder repo
    (https://issues.rudder.io/issues/19243[#19243])
* Improve script linter in rudder repo
    (https://issues.rudder.io/issues/19243[#19243])
* Set CVSS limit for failing webapp dependency check
    (https://issues.rudder.io/issues/19214[#19214])
* Add maven deploy task to pipeline
    (https://issues.rudder.io/issues/19197[#19197])
* Add scripts to setup Rust build environements in CI
    (https://issues.rudder.io/issues/19184[#19184])

==== Miscellaneous

* Improve linter and test configuration
    (https://issues.rudder.io/issues/19177[#19177])

=== Bug fixes

==== Generic methods - File Management

* Fixed: The Generic Method "File copy from Rudder shared Folder" ignores Audit policy mode
    (https://issues.rudder.io/issues/19144[#19144])
* Fixed: Condition is ignored after "File from remote template"
    (https://issues.rudder.io/issues/19212[#19212])

==== Packaging

* Fixed: Shared file broken on upgraded servers with SELinux enabled
    (https://issues.rudder.io/issues/19188[#19188])
* Fixed: Update reflections to remove vulnerable guava dependency
    (https://issues.rudder.io/issues/19216[#19216])
* Fixed: Allow building without sccache
    (https://issues.rudder.io/issues/19225[#19225])
* Fixed: postinstall fails on machines with long hostname
    (https://issues.rudder.io/issues/19185[#19185])

==== Web - Config management

* Fixed: Empty /var/rudder/policy-generation-info/node-configuration-hashes.json after a policy generation that changed nothing
    (https://issues.rudder.io/issues/19248[#19248])
* Fixed: AUTHORIZED_NETWORKS system variable must be multivalued
    (https://issues.rudder.io/issues/19217[#19217])

==== Miscellaneous

* Fixed: relay package fails to build on rhel7
    (https://issues.rudder.io/issues/19247[#19247])
* Fixed: API documentation is missleading for properties
    (https://issues.rudder.io/issues/19202[#19202])
* Fixed: Policy generation does change technique resource files when it should not
    (https://issues.rudder.io/issues/19222[#19222])
* Fixed: setting a job with schedule_simple in catchup mode does not honor the schedule
    (https://issues.rudder.io/issues/19227[#19227])

==== API

* Fixed: Undocumented API rudder_verify_certificates
    (https://issues.rudder.io/issues/19235[#19235])
* Fixed: Missing documentation for POST allowedNetwords API
    (https://issues.rudder.io/issues/18506[#18506])

==== Security

* Fixed: Check dependence fails with NPE
    (https://issues.rudder.io/issues/19231[#19231])

==== Web - UI & UX

* Fixed: Date picker in search (last inventory) is broken
    (https://issues.rudder.io/issues/19228[#19228])

==== Performance and scalability

* Fixed: Slow computation of dynamic groups on large system
    (https://issues.rudder.io/issues/18981[#18981])
* Fixed: backup file are not copied correctly when the destination directory is on another FS
    (https://issues.rudder.io/issues/19218[#19218])
* Fixed: Put node cache info into a file in place of LDAP
    (https://issues.rudder.io/issues/19213[#19213])

==== Architecture - Dependencies

* Fixed: Some java dependencies have security warning and should be updated
    (https://issues.rudder.io/issues/19211[#19211])

==== Web - Technique editor

* Fixed: Techniques using a condition containing a variable are not canonified correctly with dsc agent
    (https://issues.rudder.io/issues/19199[#19199])

==== Web - Compliance & node report

* Fixed: Webapp tests fail if repository path contains an '@'
    (https://issues.rudder.io/issues/19186[#19186])

==== Plugins management

* Fixed: Detection of dependencies for plugin can fail if the python lib of another distrib is present
    (https://issues.rudder.io/issues/19187[#19187])

==== Agent

* Fixed: Command "rudder agent policy-server <server ip>" return code = 1 when ok
    (https://issues.rudder.io/issues/19157[#19157])
* Fixed: cannot upgrade directives because curl checks certificates
    (https://issues.rudder.io/issues/19175[#19175])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Jean Cardona
* Axel Bouet
* Lars Koenen

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


==  Rudder 6.2.6 (2021-04-21)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Syntax error in rudder-upgrade
    (https://issues.rudder.io/issues/19172[#19172])

==== Web - Config management

* Fixed: Lots of files are created in /var/rudder/inventories/debug
    (https://issues.rudder.io/issues/19171[#19171])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 6.2.5 (2021-04-21)

=== Changes


==== Security

* Use https repos in maven config
    (https://issues.rudder.io/issues/19164[#19164])

==== Packaging

* Split cargo-deny from qa-test
    (https://issues.rudder.io/issues/19083[#19083])

=== Bug fixes

==== Plugins integration

* Fixed: Error when restoring plugin status on fresh server install
    (https://issues.rudder.io/issues/19125[#19125])

==== Packaging

* Fixed: Update openssl to 1.1.1k
    (https://issues.rudder.io/issues/19090[#19090])
* Fixed: Vulnerability in relayd dependencies diesel and generic-array
    (https://issues.rudder.io/issues/19087[#19087])

==== Documentation

* Fixed: Incorrect option in pg_restore for archive 
    (https://issues.rudder.io/issues/19036[#19036])

==== Plugins management

* Fixed: when we install a plugin, if the dependency (package manager) is not met, it still tries to install it and fails
    (https://issues.rudder.io/issues/18999[#18999])

==== Web - Config management

* Fixed: Cannot load file browser if subfolders of the shared-folder contain dead symlinks
    (https://issues.rudder.io/issues/19158[#19158])
* Fixed: Add empty technique parameter in technique editor (6.2 only)
    (https://issues.rudder.io/issues/19119[#19119])
* Fixed: Allow to put empty value in technique parameters
    (https://issues.rudder.io/issues/19115[#19115])
* Fixed: Inherited node properties are displayed with escape
    (https://issues.rudder.io/issues/19085[#19085])

==== Web - Nodes & inventories

* Fixed: Add an option to invert result of a node query
    (https://issues.rudder.io/issues/19138[#19138])
* Fixed: Search nodes component is not reloaded when reloading page, losing our current request
    (https://issues.rudder.io/issues/19082[#19082])
* Fixed: Inventory named as "Report" in log message
    (https://issues.rudder.io/issues/19072[#19072])

==== API

* Fixed: Clone group via API ask for query
    (https://issues.rudder.io/issues/19129[#19129])
* Fixed: Bad quoting for string value in parameter update from API
    (https://issues.rudder.io/issues/19104[#19104])
* Fixed: Add more tests for API (directives, techniques, parameters)
    (https://issues.rudder.io/issues/19086[#19086])
* Fixed: Missing example for server key reset
    (https://issues.rudder.io/issues/19065[#19065])

==== Web - Compliance & node report

* Fixed: Overridden directives in the same rule are missing (not even "skipped")
    (https://issues.rudder.io/issues/19114[#19114])

==== Web - UI & UX

* Fixed: Syntax helper in the parameter page is outdated
    (https://issues.rudder.io/issues/19108[#19108])

==== Security

* Fixed: Vulnerabilities in relayd hyper dependency
    (https://issues.rudder.io/issues/18903[#18903])

==== Agent

* Fixed: Typo in agent error message
    (https://issues.rudder.io/issues/19130[#19130])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Lars Koenen

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.2.4 (2021-03-19)

=== Changes

=== Bug fixes

==== System integration

* Fixed: Upgrade script fails in system technique update (empty commit)
    (https://issues.rudder.io/issues/19044[#19044])

==== Web - Config management

* Fixed: Cannot load file browser when shared-folder contains dead symlinks
    (https://issues.rudder.io/issues/18200[#18200])

==== Web - UI & UX

* Fixed: Custom bar and logo are not displayed in the login form while option is enabled in the Branding plugin
    (https://issues.rudder.io/issues/19040[#19040])

==== Web - Technique editor

* Fixed: Technique editor error when an class is not correctly defined
    (https://issues.rudder.io/issues/19039[#19039])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Nicolas Ecarnot

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.2.3 (2021-03-18)

=== Release Notes

==== Change of behavior for empty technique parameters

Previously, when adding a new parameter to a technique in the technique editor, all directives based on this technique
were still valid and used an empty value for the new parameter. This leads to unexpected behaviors, and makes adding
parameters to techniques potentially dangerous.

To prevent this type of problems (in the scope of a patch release) we had to totally prevent passing empty parameters to techniques from the technique editor. This makes missing parameters a policy generation error, allowing to safely provide
them to directives after modifying the source technique.

This may break existing directives that rely on an expression which evaluates to an empty value, like a property containing an empty string, or a property value with an empty default.
In this case, you can pass a specific value like
`None` or a space char to indicate an empty value, and modify the technique to handle the special case
as a workaround.

We will work on a better solution in a future version, allowing to make the difference between new parameters and
intentionally blank ones.

(https://issues.rudder.io/issues/18832[#18832])

==== Policy server reload

We fixed a known issue is the way we reload the policy server (the service that distributes policies to Unix systems).

Previously, when adding a node or modifying allowed networks, a configuration reload was triggered, but it was only effective when the service became idle. On loaded Rudder servers or relays, this may totally prevent service reload, and thus
prevent the new nodes from connecting.

We replaced the reload by a graceful restart mechanism which takes effect immediately. This should not
cause any visible changes, except that two `cf-serverd` processes might be running at the same time (on
handling existing connections until completion, one handling the new ones).

(https://issues.rudder.io/issues/18893[#18893])

==== Other important fixes

* We fixed lock issues in Rudder server logic, this should make Rudder safer and faster and thus we recommend all users to update to 6.2.3 (https://issues.rudder.io/issues/18983[#18983])
* In rare cases, the agent inventory processes could pile up, exhausting resources of the machine. This has been fixed, another important reason to update to 6.2.3 (https://issues.rudder.io/issues/18832[#18832])
* OOM exception now stops Rudder correctly with information logs either in rudder-jetty service or in webapp logs, but some JVM, especially old Java 8, still don't log anything (https://issues.rudder.io/issues/18955[#18955]). As a consequence, Rudder now requires at least OpenJDK 1.8.0-92.

=== Changes

==== System integration

* Epoch is not included in rpm package version in inventory
    (https://issues.rudder.io/issues/19000[#19000])

==== Packaging

* Update embedded openssl
    (https://issues.rudder.io/issues/18913[#18913])

==== Documentation

* Add documentation for changing cf-serverd port
    (https://issues.rudder.io/issues/18872[#18872])

==== Web - Config management

* Add a settings to delay start of policy generation
    (https://issues.rudder.io/issues/18845[#18845])

==== Web - UI & UX

* Line break after each ip address
    (https://issues.rudder.io/issues/18883[#18883])

==== Techniques

* Add an "upgrade only" option to the technique packageManagement
    (https://issues.rudder.io/issues/18909[#18909])

==== Generic methods - File Management

* Document usage of sys.ipv4 var in jinja
    (https://issues.rudder.io/issues/18905[#18905])

=== Bug fixes

==== Packaging

* Fixed: Upgrade failed from 5.0.20 to 6.1.9 on SLES
    (https://issues.rudder.io/issues/18891[#18891])

==== System integration

* Fixed: Fatal exception doesn't cause rudder to stop anymore
    (https://issues.rudder.io/issues/18955[#18955])

==== Server components

* Fixed: After the promises generation, cf-serverd config may not be reloaded, preventing new nodes from connecting
    (https://issues.rudder.io/issues/8351[#8351])

==== Agent

* Fixed: Error logs about "Method '...' failed in some repairs" are useless and should be at verbose level instead
    (https://issues.rudder.io/issues/18914[#18914])
* Fixed: Agent run schedule problem
    (https://issues.rudder.io/issues/18846[#18846])
* Fixed: Agent run schedule problem
    (https://issues.rudder.io/issues/18846[#18846])
* Fixed: Rudder Agent consumes complete Memory because of fdisk
    (https://issues.rudder.io/issues/18832[#18832])

==== Documentation

* Fixed: Update some plugin documentation
    (https://issues.rudder.io/issues/18962[#18962])
* Fixed: Add advanced jinja2 template example for main IP address
    (https://issues.rudder.io/issues/18906[#18906])
* Fixed: Missing licence info in pom.xml
    (https://issues.rudder.io/issues/18978[#18978])
* Fixed: rudder api doc doesn't list nodes/pending
    (https://issues.rudder.io/issues/18940[#18940])
* Fixed: Documentation API doesn't build anymore
    (https://issues.rudder.io/issues/18930[#18930])

==== Performance and scalability

* Fixed: We don't know when generation hooks takes more time than expected, massively impacting generation time
    (https://issues.rudder.io/issues/18915[#18915])
* Fixed: A writeLock must never be in a read lock for LDAP repo
    (https://issues.rudder.io/issues/18983[#18983])

==== API

* Fixed: Inherited node properties are not returned in API
    (https://issues.rudder.io/issues/18959[#18959])
* Fixed: nodes API with include managementTechnologyDetails leads to error 500 response
    (https://issues.rudder.io/issues/18926[#18926])
* Fixed: Missing API addition for version 13 in doc
    (https://issues.rudder.io/issues/18923[#18923])

==== Web - Nodes & inventories

* Fixed: FileUploadBaseSizeLimitExceededException with an 10MB inventory
    (https://issues.rudder.io/issues/19004[#19004])
* Fixed: "By agent version" pie chart leads to empty page
    (https://issues.rudder.io/issues/18791[#18791])
* Fixed: purge software batch sometime terminate in error without log message
    (https://issues.rudder.io/issues/18873[#18873])

==== Web - Config management

* Fixed: Missing mandatory directive parameter doesn't fail policy generation
    (https://issues.rudder.io/issues/18995[#18995])
* Fixed: Missing exception details in change request update
    (https://issues.rudder.io/issues/18900[#18900])
* Fixed: Workflow rights are not used for rules
    (https://issues.rudder.io/issues/18876[#18876])

==== Containers

* Fixed: Incorrect permission for relay docker script
    (https://issues.rudder.io/issues/18993[#18993])

==== Web - UI & UX

* Fixed: Double scrollbar in settings page when branding plugin is enabled
    (https://issues.rudder.io/issues/18935[#18935])
* Fixed: Error message when editing properties in the interface
    (https://issues.rudder.io/issues/18902[#18902])
* Fixed: Save button moves when switching of compliance reporting mode
    (https://issues.rudder.io/issues/18849[#18849])

==== Miscellaneous

* Fixed: Error in postCommit pipeline with processor 'post_commit_inventory:pending_node_for_deleted_server'
    (https://issues.rudder.io/issues/18899[#18899])

==== Plugins integration

* Fixed: Do not try to upgrade cis or openscap plugins
    (https://issues.rudder.io/issues/18874[#18874])

==== System techniques

* Fixed: Rsync command for shared-files is incorrect
    (https://issues.rudder.io/issues/18943[#18943])

==== Generic methods - File Management

* Fixed: Value replacement in "File key-value present" and "File keys-values present" methods doesn't work correctly in some cases.
    (https://issues.rudder.io/issues/18944[#18944])
* Fixed: file_check_block_devices test does not work on debian based system
    (https://issues.rudder.io/issues/18924[#18924])

==== Generic methods

* Fixed: ncf unit tests do not generate any log file
    (https://issues.rudder.io/issues/18928[#18928])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Anton Yakimov
* Lars Koenen
* Nicolas Ecarnot
* Andras Miko

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.2.2 (2021-01-28)

=== Changes

==== System techniques

* Allow defining port in policy_server.dat
    (https://issues.rudder.io/issues/18721[#18721])

=== Bug fixes

==== Packaging

* Fixed: Inventories are rejected due to missing dependency on Centos 8
    (https://issues.rudder.io/issues/18862[#18862])

==== System integration

* Fixed: After upgrade between two Rudder 6.2 all plugins are disabled
    (https://issues.rudder.io/issues/18842[#18842])

==== Documentation

* Fixed: Update windows plugin documentation
    (https://issues.rudder.io/issues/18836[#18836])

==== Performance and scalability

* Fixed: Backport new inventory priorisation, software deletion API and log correction in 6.1
    (https://issues.rudder.io/issues/18839[#18839])

==== API

* Fixed: id parameter is ignored in rule category creation API and rule tags are lost on update
    (https://issues.rudder.io/issues/18867[#18867])
* Fixed: Bad URL for doc of purgeSoftware API
    (https://issues.rudder.io/issues/18840[#18840])

==== Web - Config management

* Fixed: Event logs are not written when fields are set to empty (ie short description)
    (https://issues.rudder.io/issues/18856[#18856])

==== Web - UI & UX

* Fixed: Cannot open directive details on Safari 
    (https://issues.rudder.io/issues/18838[#18838])

==== Plugins integration

* Fixed: rudder package upgrade-all does not upgrade each plugin independently
    (https://issues.rudder.io/issues/18841[#18841])
* Fixed: rudder plugin upgrade-all  states that he will disable plugin, but is does not
    (https://issues.rudder.io/issues/18843[#18843])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.2.1 (2021-01-19)

=== Changes

==== Documentation

* Document container/docker support
    (https://issues.rudder.io/issues/18794[#18794])
* Mark 6.2 as final in docs
    (https://issues.rudder.io/issues/18756[#18756])

==== Containers

* Make a single container relay
    (https://issues.rudder.io/issues/18765[#18765])
* Make a single container relay
    (https://issues.rudder.io/issues/18765[#18765])

==== API

* Add API tests for rules
    (https://issues.rudder.io/issues/18770[#18770])

==== Generic methods

* Add solaris specific paths
    (https://issues.rudder.io/issues/18741[#18741])

=== Bug fixes

==== Packaging

* Fixed: package cache ignores architecture
    (https://issues.rudder.io/issues/18759[#18759])

==== Documentation

* Fixed: Add solaris to supported OS in doc
    (https://issues.rudder.io/issues/18807[#18807])
* Fixed: Rudder by example for auto-accept nodes
    (https://issues.rudder.io/issues/18780[#18780])
* Fixed: Lots of methods are missing a documentation
    (https://issues.rudder.io/issues/18724[#18724])

==== Web - Maintenance

* Fixed: Make more clear error message when several rudder.war are present
    (https://issues.rudder.io/issues/18835[#18835])

==== Performance and scalability

* Fixed: In Rudder 6.2.0 inventory processing merge_uuid part get extremely slow on debian
    (https://issues.rudder.io/issues/12937[#12937])

==== API

* Fixed: Broken API doc build
    (https://issues.rudder.io/issues/18823[#18823])
* Fixed: Clone rule API fails with "rule already exists with that id"
    (https://issues.rudder.io/issues/18777[#18777])

==== Relay server or API

* Fixed: Security advisories for relayd dependencies
    (https://issues.rudder.io/issues/18824[#18824])
* Fixed: Security vulnerability in arc-swap
    (https://issues.rudder.io/issues/18766[#18766])

==== Web - Compliance & node report

* Fixed:  Error log about duplicates entries when saving node compliance levels
    (https://issues.rudder.io/issues/18814[#18814])

==== Web - Nodes & inventories

* Fixed: Accepting a node by API or UI doesn't do the same things exactly
    (https://issues.rudder.io/issues/18677[#18677])
* Fixed: bad logger name for inventory processing
    (https://issues.rudder.io/issues/18813[#18813])
* Fixed: Node name not visible in node configuration screen
    (https://issues.rudder.io/issues/18768[#18768])

==== Web - Config management

* Fixed: Global parameters format is not preserved when editing
    (https://issues.rudder.io/issues/18556[#18556])
* Fixed: when directive name is long and there are several tags (like with CIS plugin), display is a bit broken
    (https://issues.rudder.io/issues/18733[#18733])

==== Web - UI & UX

* Fixed: Message on save for group must appear only when button is disabled
    (https://issues.rudder.io/issues/18738[#18738])
* Fixed: Markdown documentation rendering is inconsistent
    (https://issues.rudder.io/issues/18750[#18750])

==== Web - Technique editor

* Fixed: saving imported techniques with unknown GM fails with no error prompt
    (https://issues.rudder.io/issues/18420[#18420])

==== Techniques

* Fixed: Define suse classes on sled
    (https://issues.rudder.io/issues/18775[#18775])

==== System techniques

* Fixed: bootstrap policies report OK if there is no server
    (https://issues.rudder.io/issues/18748[#18748])
* Fixed: Jinja2 UTF-8 rendering Problem
    (https://issues.rudder.io/issues/18552[#18552])

==== Generic methods

* Fixed: head bash command path should be taken from the ncf_paths bundle
    (https://issues.rudder.io/issues/18797[#18797])
* Fixed: Regex constraint must not contain escaped chars
    (https://issues.rudder.io/issues/18764[#18764])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Jeremy CHAMPEL
* I C
* Alexander Brunhirl

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.2.0 (2020-12-10)

=== Changes

==== Documentation

* Add documentation about set-force-audit in audit/enforce chapter
    (https://issues.rudder.io/issues/18707[#18707])

=== Bug fixes

==== Packaging

* Fixed: missing python3-setuptools dependency on relay on sles15 and rhel8
    (https://issues.rudder.io/issues/18747[#18747])
* Fixed: missing python3-setuptools dependency on relay on sles15 and rhel8
    (https://issues.rudder.io/issues/18747[#18747])
* Fixed: Remove plugin notice during upgrade
    (https://issues.rudder.io/issues/18742[#18742])
* Fixed: /var/rudder/config-repo/.gitignore is overridden by packaging
    (https://issues.rudder.io/issues/17995[#17995])

==== Agent

* Fixed: backport fix on background command execution on agent
    (https://issues.rudder.io/issues/18732[#18732])

==== Documentation

* Fixed: Wrong period for health check run in user doc
    (https://issues.rudder.io/issues/18702[#18702])

==== System integration

* Fixed: No newer release compatible versions found for the plugin rudder-plugin-scale-out-relay, disabling it
    (https://issues.rudder.io/issues/18735[#18735])

==== Architecture - Refactoring

* Fixed: Compilation warning (unused variable) in 6.2.0-rc1
    (https://issues.rudder.io/issues/18729[#18729])

==== Web - UI & UX

* Fixed: parent ticket doesn't grey out title on accept new nodes when the popup shows up
    (https://issues.rudder.io/issues/18691[#18691])
* Fixed: Tooltip in node summary goes under sidebar
    (https://issues.rudder.io/issues/18723[#18723])
* Fixed: When there is an error after saving a directive, impossible to scroll down directive details
    (https://issues.rudder.io/issues/18714[#18714])
* Fixed: Create directive button is misplaced
    (https://issues.rudder.io/issues/18700[#18700])

==== Web - Config management

* Fixed: Agent run frequency must not be configurable on policy servers
    (https://issues.rudder.io/issues/18330[#18330])

==== Generic methods - File Management

* Fixed: On sles system augtool requires a terminating break line to run a command passed via pipe
    (https://issues.rudder.io/issues/18719[#18719])
* Fixed: calling file_key_value_present_in_ini_section on a yum repo definition loops
    (https://issues.rudder.io/issues/18705[#18705])

==== Generic methods

* Fixed: ncf uses its own cfengine port instead of rudder defined one
    (https://issues.rudder.io/issues/18704[#18704])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.2.0.rc1 (2020-11-25)

=== Changes

==== Packaging

* Embed augeas in the agent
    (https://issues.rudder.io/issues/17945[#17945])
* Add rudder-agent services to solaris package
    (https://issues.rudder.io/issues/18444[#18444])

==== Documentation

* Update documentation about node properties value inheritance rules 
    (https://issues.rudder.io/issues/18537[#18537])
* Add a link to rudder-by-example in windows doc
    (https://issues.rudder.io/issues/12622[#12622])
* Fix links to different API versions
    (https://issues.rudder.io/issues/18546[#18546])

==== Web - Nodes & inventories

* Add a property column without inherited values in node list
    (https://issues.rudder.io/issues/18641[#18641])
* API to totally erase a node everywhere
    (https://issues.rudder.io/issues/18035[#18035])

==== Web - UI & UX

* Pretty-print json properties in nodes list
    (https://issues.rudder.io/issues/18618[#18618])
* Beautify Nodes page
    (https://issues.rudder.io/issues/18424[#18424])
* Change default columns of nodes tables
    (https://issues.rudder.io/issues/18617[#18617])
* Do not use italics on login page
    (https://issues.rudder.io/issues/18606[#18606])
* Rename Id to "Node ID" in columns name for consistency
    (https://issues.rudder.io/issues/18603[#18603])
* Rename node menu entries for consistency
    (https://issues.rudder.io/issues/18590[#18590])
* Group display: allow to see last inventory field
    (https://issues.rudder.io/issues/7687[#7687])
* Densify the Directives interface
    (https://issues.rudder.io/issues/14841[#14841])
* Add a reset columns button and some guard on localstorage cache
    (https://issues.rudder.io/issues/18495[#18495])
* Store columns used in localstorage in nodes list
    (https://issues.rudder.io/issues/18476[#18476])
* Reduce data send to nodes list and make a faster display
    (https://issues.rudder.io/issues/18473[#18473])

==== Agent

* Rudder server relay install should use the up-to-date commands and not deprecated ones
    (https://issues.rudder.io/issues/18639[#18639])

==== API

* Missing a PATCH API for allowed networks
    (https://issues.rudder.io/issues/18508[#18508])
* Documentation for /nodes/status page
    (https://issues.rudder.io/issues/18483[#18483])
* 6.2 API version is 13
    (https://issues.rudder.io/issues/18481[#18481])

==== Architecture - Internal libs

* Skip performance test
    (https://issues.rudder.io/issues/18563[#18563])

==== Architecture - Refactoring

* Move date formatter service to a more common project 
    (https://issues.rudder.io/issues/15915[#15915])
* Move health check API in /system/
    (https://issues.rudder.io/issues/18482[#18482])

==== Web - Maintenance

* Skip non-standard moint FS for free-space check
    (https://issues.rudder.io/issues/18534[#18534])

==== Techniques

* deprecate the version 2.0 of the technique VariableFromJsonFiles
    (https://issues.rudder.io/issues/14244[#14244])

==== Generic methods

* Augeas methods should prefer the agent provided binary
    (https://issues.rudder.io/issues/18600[#18600])

=== Bug fixes

==== Packaging

* Fixed: We try to replace python shebang in source files instead of destination files
    (https://issues.rudder.io/issues/18675[#18675])
* Fixed: Message about replacing files during upgrade on debian like is not precise enough
    (https://issues.rudder.io/issues/18671[#18671])
* Fixed: Solaris package generation doesn't follows repository tree
    (https://issues.rudder.io/issues/18666[#18666])
* Fixed: solaris versions only support digits
    (https://issues.rudder.io/issues/18640[#18640])
* Fixed: agent fails to build on aix
    (https://issues.rudder.io/issues/18624[#18624])
* Fixed: Solaris fails to build on 6.2
    (https://issues.rudder.io/issues/18614[#18614])
* Fixed: rudder-metrics-reporting doesn't work with 5 000 nodes
    (https://issues.rudder.io/issues/16675[#16675])
* Fixed: Typo in rudder package command on upgrade
    (https://issues.rudder.io/issues/18452[#18452])
* Fixed: Remove useless output from rudder package
    (https://issues.rudder.io/issues/18555[#18555])
* Fixed: Upgrading Rudder 6.2 on centos 7 fails
    (https://issues.rudder.io/issues/18521[#18521])

==== Agent

* Fixed: Fix metrics-reporting script
    (https://issues.rudder.io/issues/18568[#18568])

==== System integration

* Fixed: add software index in ldap
    (https://issues.rudder.io/issues/18475[#18475])
* Fixed: Force reload of generic-method cache when app starts
    (https://issues.rudder.io/issues/18635[#18635])

==== Plugins integration

* Fixed: rudder_synchronize uses the wrong API to retrieve techniques
    (https://issues.rudder.io/issues/18421[#18421])
* Fixed: Upgrading 6.2 nightly to 6.2 nightly with plugins fails
    (https://issues.rudder.io/issues/18645[#18645])
* Fixed: Link to plugins in Rudder interface should point directly to plugins list
    (https://issues.rudder.io/issues/18658[#18658])
* Fixed: rudder package config may not have the new parameters and may fail when reading them
    (https://issues.rudder.io/issues/18453[#18453])

==== Documentation

* Fixed: Improve documentation on disk space requirement
    (https://issues.rudder.io/issues/18532[#18532])
* Fixed: Search window appears behind "dev version warning" bar
    (https://issues.rudder.io/issues/18524[#18524])
* Fixed: Add documentation about proxy in rudder package command
    (https://issues.rudder.io/issues/18454[#18454])
* Fixed: Doc about "Condition from variable existence" is wrong
    (https://issues.rudder.io/issues/18458[#18458])

==== Web - Technique editor

* Fixed: Filter for name for generic methods in technique editor doesn't filter
    (https://issues.rudder.io/issues/18693[#18693])
* Fixed: Code blocks in the technique editor are not rendered correctly
    (https://issues.rudder.io/issues/18547[#18547])

==== Web - Compliance & node report

* Fixed: Reporting error when using twice "	File from local source" with parameter and without parameter in rudder 6.x
    (https://issues.rudder.io/issues/18686[#18686])
* Fixed: it's impossible to see all technical logs in 6.2
    (https://issues.rudder.io/issues/18687[#18687])
* Fixed: Popup error on group page with a readonly user in 6.2
    (https://issues.rudder.io/issues/18626[#18626])

==== Web - Nodes & inventories

* Fixed: Inherited properties always displayed in the column, even if checkbox unchecked
    (https://issues.rudder.io/issues/18681[#18681])
* Fixed: If there is a lot of pending nodes, accept button is not displayed
    (https://issues.rudder.io/issues/18680[#18680])
* Fixed: Typo in example script for auto-accept: POSTT
    (https://issues.rudder.io/issues/18676[#18676])
* Fixed: [object Object] in inherited properties column 
    (https://issues.rudder.io/issues/18668[#18668])
* Fixed: Add a script example for auto-acceptation of nodes by hook
    (https://issues.rudder.io/issues/18634[#18634])
* Fixed: Removing all node list columns remove the whole table
    (https://issues.rudder.io/issues/18597[#18597])
* Fixed: Column name to add are not sorted alphabetically
    (https://issues.rudder.io/issues/18538[#18538])
* Fixed: In added node attribute column, property value is never updated
    (https://issues.rudder.io/issues/18542[#18542])

==== Web - UI & UX

* Fixed: Clicking on "show docs" on a generic method scroll down too much
    (https://issues.rudder.io/issues/18612[#18612])
* Fixed: Many alignement issues on 6.2
    (https://issues.rudder.io/issues/18610[#18610])
* Fixed: In read_only mode, many things are editable
    (https://issues.rudder.io/issues/18627[#18627])
* Fixed: Add line break for partition's list in healthcheck notification
    (https://issues.rudder.io/issues/18662[#18662])
* Fixed: Typo in healthcheck notification title
    (https://issues.rudder.io/issues/18661[#18661])
* Fixed: Disable directive button has incorrect capitalization
    (https://issues.rudder.io/issues/18601[#18601])
* Fixed: Make group tab name capitalization consistent
    (https://issues.rudder.io/issues/18656[#18656])
* Fixed: Small UI features are missing from the new 6.2 interface
    (https://issues.rudder.io/issues/18588[#18588])
* Fixed: Column names in pending and accepted nodes are different
    (https://issues.rudder.io/issues/18609[#18609])
* Fixed: Improve display of partition free space
    (https://issues.rudder.io/issues/18605[#18605])
* Fixed: Make capitalization in directive form tabs consistent
    (https://issues.rudder.io/issues/18604[#18604])
* Fixed: Column label moves slightly when hovering remove button
    (https://issues.rudder.io/issues/18594[#18594])
* Fixed: Rename "Server" node list column to "Policy server"
    (https://issues.rudder.io/issues/18591[#18591])
* Fixed: missing (404) favicon in rudder loading page
    (https://issues.rudder.io/issues/18571[#18571])
* Fixed: Missing lights indicators in healthcheck page
    (https://issues.rudder.io/issues/18582[#18582])
* Fixed: Light in healthcheck notif are not displayed
    (https://issues.rudder.io/issues/18574[#18574])
* Fixed: Wrong timezone format of Date displayed in Recent Changes table
    (https://issues.rudder.io/issues/18543[#18543])
* Fixed: Display message if there are no parameters in Directive details 
    (https://issues.rudder.io/issues/11714[#11714])
* Fixed: In Groups page, the search filter should take up the full width available
    (https://issues.rudder.io/issues/18533[#18533])
* Fixed: after editing columns in the group or serach node page, there's a JS error when doing a search
    (https://issues.rudder.io/issues/18498[#18498])
* Fixed: Missing (404) ajax-loader.gif on node pending page 
    (https://issues.rudder.io/issues/18491[#18491])
* Fixed: Reloading a page with a node table or refreshing breaks hostname links and compliance
    (https://issues.rudder.io/issues/18516[#18516])
* Fixed: spacing is uneven in reports database page
    (https://issues.rudder.io/issues/18503[#18503])
* Fixed: spacing is uneven in the settings page
    (https://issues.rudder.io/issues/18501[#18501])
* Fixed: Improve health check texts
    (https://issues.rudder.io/issues/18477[#18477])
* Fixed: Width of the Directive tree changes according to the selected Directive.
    (https://issues.rudder.io/issues/18474[#18474])
* Fixed: Compliance does not show up if you don't click on refresh
    (https://issues.rudder.io/issues/18462[#18462])
* Fixed: Empty space in Directives header
    (https://issues.rudder.io/issues/18401[#18401])
* Fixed: Warning on plugin icon is huge on left menu
    (https://issues.rudder.io/issues/18460[#18460])
* Fixed: Header of some page hides menu from the left side
    (https://issues.rudder.io/issues/18463[#18463])
* Fixed: Health check page is not displayed
    (https://issues.rudder.io/issues/18461[#18461])

==== Web - Maintenance

* Fixed: category.xml is created in place of activeTechniqueSettings.xml in all config-repos/directives
    (https://issues.rudder.io/issues/18499[#18499])
* Fixed: Healthcheck checks happen to often 
    (https://issues.rudder.io/issues/18540[#18540])
* Fixed: Healthcheck checks happen to often 
    (https://issues.rudder.io/issues/18540[#18540])
* Fixed: Notification healthcheck is not displayed on warning
    (https://issues.rudder.io/issues/18479[#18479])

==== API

* Fixed: API ACL order is lost for users
    (https://issues.rudder.io/issues/18664[#18664])
* Fixed: API message when a node details is not found is extremely misleading
    (https://issues.rudder.io/issues/18654[#18654])
* Fixed: Bad file name in api-doc: set-allowed-networks.yml
    (https://issues.rudder.io/issues/18608[#18608])
* Fixed: Check parition should check the lowest space available first
    (https://issues.rudder.io/issues/18480[#18480])
* Fixed: Typo in API doc
    (https://issues.rudder.io/issues/18457[#18457])

==== Web - Config management

* Fixed: Added column for node property does not show inherited value
    (https://issues.rudder.io/issues/18595[#18595])
* Fixed: Inherited mode is not returned in API
    (https://issues.rudder.io/issues/18578[#18578])
* Fixed: String node properties display quotes
    (https://issues.rudder.io/issues/18580[#18580])
* Fixed: We don't know which hook timeout when it happens
    (https://issues.rudder.io/issues/18530[#18530])
* Fixed: Inherited node prop arrays are replaced not merged contrary to doc
    (https://issues.rudder.io/issues/18466[#18466])
* Fixed: If a second rollback starts when a first is processing, system group/technique may be lost
    (https://issues.rudder.io/issues/17720[#17720])

==== Architecture - Internal libs

* Fixed: semaphore guarding LDAP repos are created each time
    (https://issues.rudder.io/issues/18584[#18584])
* Fixed: If LDAP server does not support subtree deletion, we get error when entry does not exists
    (https://issues.rudder.io/issues/18529[#18529])
* Fixed: ifTrace/Debug/etcIsEnabled on pure logger does nothings
    (https://issues.rudder.io/issues/18528[#18528])

==== Performance and scalability

* Fixed: Batch of new nodes can overflow rudder server with inventories
    (https://issues.rudder.io/issues/16773[#16773])
* Fixed: Loading directive's page is very slow
    (https://issues.rudder.io/issues/18510[#18510])

==== Relay server or API

* Fixed: Too many open files in relayd when disk is full
    (https://issues.rudder.io/issues/18437[#18437])
* Fixed: Broken report parser on some info messages
    (https://issues.rudder.io/issues/18497[#18497])

==== Server components

* Fixed: Error when refusing a node
    (https://issues.rudder.io/issues/16739[#16739])

==== System techniques

* Fixed: ncf_hash_file is created with incorrect group permission by system techniques
    (https://issues.rudder.io/issues/18592[#18592])
* Fixed: file augeas set class parameter should be path rather than lens
    (https://issues.rudder.io/issues/18442[#18442])

==== Techniques

* Fixed: ssh key distribution techniques doesn't accept - in user login
    (https://issues.rudder.io/issues/18449[#18449])

==== Miscellaneous

* Fixed: Update file from remote template doc
    (https://issues.rudder.io/issues/18632[#18632])

==== Generic methods - File Management

* Fixed: Create a file from remote template generic method
    (https://issues.rudder.io/issues/18384[#18384])
* Fixed: Flag the file_augeas_set to stagging since the method does not work as intended
    (https://issues.rudder.io/issues/18570[#18570])
* Fixed: File_augeas_set method does not report as expected
    (https://issues.rudder.io/issues/18536[#18536])
* Fixed: Document the permissions recursive and permissions type recursive methods
    (https://issues.rudder.io/issues/18447[#18447])
* Fixed: Permissions recursive method uses an undefined "recursion" variable in its report string
    (https://issues.rudder.io/issues/18446[#18446])
* Fixed: jinja templating script uses python3 even if jinja2 is not installed in python3 but is in python2
    (https://issues.rudder.io/issues/18416[#18416])

==== Generic methods

* Fixed: variable iterator should accept whitespace as separator
    (https://issues.rudder.io/issues/18562[#18562])
* Fixed: variable from command does not always report an error when the command failed
    (https://issues.rudder.io/issues/18512[#18512])
* Fixed: when sum of length of parameter is larger than 1000 characters, reporting leaks too much from one method to another
    (https://issues.rudder.io/issues/18505[#18505])
* Fixed: techniques in audit don't report correctly for editing values in files
    (https://issues.rudder.io/issues/18451[#18451])
* Fixed: Jinja2 templating fails with python 3 with unicode data
    (https://issues.rudder.io/issues/18441[#18441])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.2.0.beta1 (2020-10-29)

=== Changes

==== Packaging

* Update dependencies for Rudder
    (https://issues.rudder.io/issues/18392[#18392])

==== Documentation

* Document Health Check in user doc
    (https://issues.rudder.io/issues/18350[#18350])

==== Web - Compliance & node report

* Make fields of node list customizable
    (https://issues.rudder.io/issues/7967[#7967])

==== Miscellaneous

* Add check for File Descriptor limit 
    (https://issues.rudder.io/issues/18414[#18414])
* Add check for free space
    (https://issues.rudder.io/issues/18357[#18357])

==== Web - UI & UX

* Beautify Global Parameters page
    (https://issues.rudder.io/issues/18418[#18418])
* Healthcheck notification in navigation bar
    (https://issues.rudder.io/issues/18328[#18328])
* Create Healthcheck webpage
    (https://issues.rudder.io/issues/18314[#18314])
* Beautify API accounts page
    (https://issues.rudder.io/issues/18389[#18389])
* Beautify Reports database page
    (https://issues.rudder.io/issues/18388[#18388])
* Beautify Event logs page
    (https://issues.rudder.io/issues/18366[#18366])
* Update settings UI
    (https://issues.rudder.io/issues/18263[#18263])
* Merge ncf editor into Rudder
    (https://issues.rudder.io/issues/18262[#18262])
* Add a shortcut to create directive with latest technique version from the tree
    (https://issues.rudder.io/issues/18164[#18164])
* Make the filter section of the directives tree foldable
    (https://issues.rudder.io/issues/18157[#18157])
* Use new UI template in Directives page
    (https://issues.rudder.io/issues/18076[#18076])

==== API

* Node status API must not return an error when the node is not here
    (https://issues.rudder.io/issues/17666[#17666])
* Add check name in healthcheck API
    (https://issues.rudder.io/issues/18363[#18363])
* Create healthcheck API 
    (https://issues.rudder.io/issues/18306[#18306])

==== Architecture - Dependencies

* Update dependencies for the webapp
    (https://issues.rudder.io/issues/18395[#18395])

==== Relay server or API

* Update relayd dependencies
    (https://issues.rudder.io/issues/18393[#18393])

==== Techniques

* Implement ips package repositories technique
    (https://issues.rudder.io/issues/18434[#18434])
* Create an "old-school" crontab technique to manage crontab in /var/spool/cron/crontabs
    (https://issues.rudder.io/issues/18228[#18228])

==== Generic methods

* Do not fix component key in generic methods reporting
    (https://issues.rudder.io/issues/18433[#18433])

==== Generic methods - Package Management

* Add solaris package support to ncf
    (https://issues.rudder.io/issues/18243[#18243])

=== Bug fixes

==== Packaging

* Fixed: Version rudder-api-client like Rudder on RPM
    (https://issues.rudder.io/issues/18435[#18435])

==== Plugins integration

* Fixed: All plugins are disabled after a minor upgrade
    (https://issues.rudder.io/issues/17878[#17878])

==== Documentation

* Fixed: Prepare doc for 6.2
    (https://issues.rudder.io/issues/18368[#18368])
* Fixed: Broken ncf doc build
    (https://issues.rudder.io/issues/18369[#18369])

==== Architecture - Refactoring

* Fixed: Fix compilation issues after merge
    (https://issues.rudder.io/issues/18443[#18443])

==== Architecture - Dependencies

* Fixed: Update to scala 2.13.3
    (https://issues.rudder.io/issues/18425[#18425])

==== Miscellaneous

* Fixed: Missing RudderConfig parameter pour healthcheck period 
    (https://issues.rudder.io/issues/18413[#18413])

==== Web - Nodes & inventories

* Fixed: Create hooks for when a node inventory is received
    (https://issues.rudder.io/issues/18379[#18379])
* Fixed: Support source package in Rudder inventory
    (https://issues.rudder.io/issues/18317[#18317])

==== Server components

* Fixed: Group owner of files under configuration-repository are inconsistent
    (https://issues.rudder.io/issues/18347[#18347])
* Fixed: Rudder SSL default configuration should follow the system default one
    (https://issues.rudder.io/issues/18338[#18338])

==== Relay server or API

* Fixed: Handle proxies in rudder package command
    (https://issues.rudder.io/issues/18326[#18326])
* Fixed: Handle proxies in rudder package command
    (https://issues.rudder.io/issues/18326[#18326])
* Fixed: Handle proxies in rudder package command
    (https://issues.rudder.io/issues/18326[#18326])
* Fixed: Handle proxies in rudder package command
    (https://issues.rudder.io/issues/18326[#18326])
* Fixed: Handle proxies in rudder package command
    (https://issues.rudder.io/issues/18326[#18326])

==== Technique editor - API

* Fixed: Technique editor doesn't use context path for API call
    (https://issues.rudder.io/issues/18374[#18374])

==== Web - UI & UX

* Fixed: Beautify Archives page
    (https://issues.rudder.io/issues/18365[#18365])
* Fixed: In the Technique Editor, tooltips no longer appear.
    (https://issues.rudder.io/issues/18334[#18334])
* Fixed: Some page sections blink while the Technique Editor is loading
    (https://issues.rudder.io/issues/18329[#18329])
* Fixed: Replace old notifications by those of Rudder
    (https://issues.rudder.io/issues/18324[#18324])

==== Web - Config management

* Fixed: Stop parsing os/agent from technique metadata
    (https://issues.rudder.io/issues/18340[#18340])

==== Performance and scalability

* Fixed: Unused index on table Ruddersysevents
    (https://issues.rudder.io/issues/18110[#18110])

==== System techniques

* Fixed: Cron for Rudder agent on solaris is invalid
    (https://issues.rudder.io/issues/18231[#18231])

==== Generic methods - Package Management

* Fixed: implement nim package manager 
    (https://issues.rudder.io/issues/18313[#18313])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

This page provides a summary of changes for each version.
