= Change logs for Rudder 6.2

Rudder 6.2 is currently a development version of Rudder.

== Rudder 6.2.0.rc1 (2020-11-25)

=== Changes

==== Packaging

* Embed augeas in the agent
    (https://issues.rudder.io/issues/17945[#17945])
* Add rudder-agent services to solaris package
    (https://issues.rudder.io/issues/18444[#18444])

==== Documentation

* Update documentation about node properties value inheritance rules 
    (https://issues.rudder.io/issues/18537[#18537])
* Add a link to rudder-by-example in windows doc
    (https://issues.rudder.io/issues/12622[#12622])
* Fix links to different API versions
    (https://issues.rudder.io/issues/18546[#18546])

==== Web - Nodes & inventories

* Add a property column without inherited values in node list
    (https://issues.rudder.io/issues/18641[#18641])
* API to totally erase a node everywhere
    (https://issues.rudder.io/issues/18035[#18035])

==== Web - UI & UX

* Pretty-print json properties in nodes list
    (https://issues.rudder.io/issues/18618[#18618])
* Beautify Nodes page
    (https://issues.rudder.io/issues/18424[#18424])
* Change default columns of nodes tables
    (https://issues.rudder.io/issues/18617[#18617])
* Do not use italics on login page
    (https://issues.rudder.io/issues/18606[#18606])
* Rename Id to "Node ID" in columns name for consistency
    (https://issues.rudder.io/issues/18603[#18603])
* Rename node menu entries for consistency
    (https://issues.rudder.io/issues/18590[#18590])
* Group display: allow to see last inventory field
    (https://issues.rudder.io/issues/7687[#7687])
* Densify the Directives interface
    (https://issues.rudder.io/issues/14841[#14841])
* Add a reset columns button and some guard on localstorage cache
    (https://issues.rudder.io/issues/18495[#18495])
* Store columns used in localstorage in nodes list
    (https://issues.rudder.io/issues/18476[#18476])
* Reduce data send to nodes list and make a faster display
    (https://issues.rudder.io/issues/18473[#18473])

==== Agent

* Rudder server relay install should use the up-to-date commands and not deprecated ones
    (https://issues.rudder.io/issues/18639[#18639])

==== API

* Missing a PATCH API for allowed networks
    (https://issues.rudder.io/issues/18508[#18508])
* Documentation for /nodes/status page
    (https://issues.rudder.io/issues/18483[#18483])
* 6.2 API version is 13
    (https://issues.rudder.io/issues/18481[#18481])

==== Architecture - Internal libs

* Skip performance test
    (https://issues.rudder.io/issues/18563[#18563])

==== Architecture - Refactoring

* Move date formatter service to a more common project 
    (https://issues.rudder.io/issues/15915[#15915])
* Move health check API in /system/
    (https://issues.rudder.io/issues/18482[#18482])

==== Web - Maintenance

* Skip non-standard moint FS for free-space check
    (https://issues.rudder.io/issues/18534[#18534])

==== Techniques

* deprecate the version 2.0 of the technique VariableFromJsonFiles
    (https://issues.rudder.io/issues/14244[#14244])

==== Generic methods

* Augeas methods should prefer the agent provided binary
    (https://issues.rudder.io/issues/18600[#18600])

=== Bug fixes

==== Packaging

* Fixed: We try to replace python shebang in source files instead of destination files
    (https://issues.rudder.io/issues/18675[#18675])
* Fixed: Message about replacing files during upgrade on debian like is not precise enough
    (https://issues.rudder.io/issues/18671[#18671])
* Fixed: Solaris package generation doesn't follows repository tree
    (https://issues.rudder.io/issues/18666[#18666])
* Fixed: solaris versions only support digits
    (https://issues.rudder.io/issues/18640[#18640])
* Fixed: agent fails to build on aix
    (https://issues.rudder.io/issues/18624[#18624])
* Fixed: Solaris fails to build on 6.2
    (https://issues.rudder.io/issues/18614[#18614])
* Fixed: rudder-metrics-reporting doesn't work with 5 000 nodes
    (https://issues.rudder.io/issues/16675[#16675])
* Fixed: Typo in rudder package command on upgrade
    (https://issues.rudder.io/issues/18452[#18452])
* Fixed: Remove useless output from rudder package
    (https://issues.rudder.io/issues/18555[#18555])
* Fixed: Upgrading Rudder 6.2 on centos 7 fails
    (https://issues.rudder.io/issues/18521[#18521])

==== Agent

* Fixed: Fix metrics-reporting script
    (https://issues.rudder.io/issues/18568[#18568])

==== System integration

* Fixed: add software index in ldap
    (https://issues.rudder.io/issues/18475[#18475])
* Fixed: Force reload of generic-method cache when app starts
    (https://issues.rudder.io/issues/18635[#18635])

==== Plugins integration

* Fixed: rudder_synchronize uses the wrong API to retrieve techniques
    (https://issues.rudder.io/issues/18421[#18421])
* Fixed: Upgrading 6.2 nightly to 6.2 nightly with plugins fails
    (https://issues.rudder.io/issues/18645[#18645])
* Fixed: Link to plugins in Rudder interface should point directly to plugins list
    (https://issues.rudder.io/issues/18658[#18658])
* Fixed: rudder package config may not have the new parameters and may fail when reading them
    (https://issues.rudder.io/issues/18453[#18453])

==== Documentation

* Fixed: Improve documentation on disk space requirement
    (https://issues.rudder.io/issues/18532[#18532])
* Fixed: Search window appears behind "dev version warning" bar
    (https://issues.rudder.io/issues/18524[#18524])
* Fixed: Add documentation about proxy in rudder package command
    (https://issues.rudder.io/issues/18454[#18454])
* Fixed: Doc about "Condition from variable existence" is wrong
    (https://issues.rudder.io/issues/18458[#18458])

==== Web - Technique editor

* Fixed: Filter for name for generic methods in technique editor doesn't filter
    (https://issues.rudder.io/issues/18693[#18693])
* Fixed: Code blocks in the technique editor are not rendered correctly
    (https://issues.rudder.io/issues/18547[#18547])

==== Web - Compliance & node report

* Fixed: Reporting error when using twice "	File from local source" with parameter and without parameter in rudder 6.x
    (https://issues.rudder.io/issues/18686[#18686])
* Fixed: it's impossible to see all technical logs in 6.2
    (https://issues.rudder.io/issues/18687[#18687])
* Fixed: Popup error on group page with a readonly user in 6.2
    (https://issues.rudder.io/issues/18626[#18626])

==== Web - Nodes & inventories

* Fixed: Inherited properties always displayed in the column, even if checkbox unchecked
    (https://issues.rudder.io/issues/18681[#18681])
* Fixed: If there is a lot of pending nodes, accept button is not displayed
    (https://issues.rudder.io/issues/18680[#18680])
* Fixed: Typo in example script for auto-accept: POSTT
    (https://issues.rudder.io/issues/18676[#18676])
* Fixed: [object Object] in inherited properties column 
    (https://issues.rudder.io/issues/18668[#18668])
* Fixed: Add a script example for auto-acceptation of nodes by hook
    (https://issues.rudder.io/issues/18634[#18634])
* Fixed: Removing all node list columns remove the whole table
    (https://issues.rudder.io/issues/18597[#18597])
* Fixed: Column name to add are not sorted alphabetically
    (https://issues.rudder.io/issues/18538[#18538])
* Fixed: In added node attribute column, property value is never updated
    (https://issues.rudder.io/issues/18542[#18542])

==== Web - UI & UX

* Fixed: Clicking on "show docs" on a generic method scroll down too much
    (https://issues.rudder.io/issues/18612[#18612])
* Fixed: Many alignement issues on 6.2
    (https://issues.rudder.io/issues/18610[#18610])
* Fixed: In read_only mode, many things are editable
    (https://issues.rudder.io/issues/18627[#18627])
* Fixed: Add line break for partition's list in healthcheck notification
    (https://issues.rudder.io/issues/18662[#18662])
* Fixed: Typo in healthcheck notification title
    (https://issues.rudder.io/issues/18661[#18661])
* Fixed: Disable directive button has incorrect capitalization
    (https://issues.rudder.io/issues/18601[#18601])
* Fixed: Make group tab name capitalization consistent
    (https://issues.rudder.io/issues/18656[#18656])
* Fixed: Small UI features are missing from the new 6.2 interface
    (https://issues.rudder.io/issues/18588[#18588])
* Fixed: Column names in pending and accepted nodes are different
    (https://issues.rudder.io/issues/18609[#18609])
* Fixed: Improve display of partition free space
    (https://issues.rudder.io/issues/18605[#18605])
* Fixed: Make capitalization in directive form tabs consistent
    (https://issues.rudder.io/issues/18604[#18604])
* Fixed: Column label moves slightly when hovering remove button
    (https://issues.rudder.io/issues/18594[#18594])
* Fixed: Rename "Server" node list column to "Policy server"
    (https://issues.rudder.io/issues/18591[#18591])
* Fixed: missing (404) favicon in rudder loading page
    (https://issues.rudder.io/issues/18571[#18571])
* Fixed: Missing lights indicators in healthcheck page
    (https://issues.rudder.io/issues/18582[#18582])
* Fixed: Light in healthcheck notif are not displayed
    (https://issues.rudder.io/issues/18574[#18574])
* Fixed: Wrong timezone format of Date displayed in Recent Changes table
    (https://issues.rudder.io/issues/18543[#18543])
* Fixed: Display message if there are no parameters in Directive details 
    (https://issues.rudder.io/issues/11714[#11714])
* Fixed: In Groups page, the search filter should take up the full width available
    (https://issues.rudder.io/issues/18533[#18533])
* Fixed: after editing columns in the group or serach node page, there's a JS error when doing a search
    (https://issues.rudder.io/issues/18498[#18498])
* Fixed: Missing (404) ajax-loader.gif on node pending page 
    (https://issues.rudder.io/issues/18491[#18491])
* Fixed: Reloading a page with a node table or refreshing breaks hostname links and compliance
    (https://issues.rudder.io/issues/18516[#18516])
* Fixed: spacing is uneven in reports database page
    (https://issues.rudder.io/issues/18503[#18503])
* Fixed: spacing is uneven in the settings page
    (https://issues.rudder.io/issues/18501[#18501])
* Fixed: Improve health check texts
    (https://issues.rudder.io/issues/18477[#18477])
* Fixed: Width of the Directive tree changes according to the selected Directive.
    (https://issues.rudder.io/issues/18474[#18474])
* Fixed: Compliance does not show up if you don't click on refresh
    (https://issues.rudder.io/issues/18462[#18462])
* Fixed: Empty space in Directives header
    (https://issues.rudder.io/issues/18401[#18401])
* Fixed: Warning on plugin icon is huge on left menu
    (https://issues.rudder.io/issues/18460[#18460])
* Fixed: Header of some page hides menu from the left side
    (https://issues.rudder.io/issues/18463[#18463])
* Fixed: Health check page is not displayed
    (https://issues.rudder.io/issues/18461[#18461])

==== Web - Maintenance

* Fixed: category.xml is created in place of activeTechniqueSettings.xml in all config-repos/directives
    (https://issues.rudder.io/issues/18499[#18499])
* Fixed: Healthcheck checks happen to often 
    (https://issues.rudder.io/issues/18540[#18540])
* Fixed: Healthcheck checks happen to often 
    (https://issues.rudder.io/issues/18540[#18540])
* Fixed: Notification healthcheck is not displayed on warning
    (https://issues.rudder.io/issues/18479[#18479])

==== API

* Fixed: API ACL order is lost for users
    (https://issues.rudder.io/issues/18664[#18664])
* Fixed: API message when a node details is not found is extremelly misleading
    (https://issues.rudder.io/issues/18654[#18654])
* Fixed: Bad file name in api-doc: set-allowed-networks.yml
    (https://issues.rudder.io/issues/18608[#18608])
* Fixed: Check parition should check the lowest space available first
    (https://issues.rudder.io/issues/18480[#18480])
* Fixed: Typo in API doc
    (https://issues.rudder.io/issues/18457[#18457])

==== Web - Config management

* Fixed: Added column for node property does not show inherited value
    (https://issues.rudder.io/issues/18595[#18595])
* Fixed: Inherited mode is not returned in API
    (https://issues.rudder.io/issues/18578[#18578])
* Fixed: String node properties display quotes
    (https://issues.rudder.io/issues/18580[#18580])
* Fixed: We don't know which hook timeout when it happens
    (https://issues.rudder.io/issues/18530[#18530])
* Fixed: Inherited node prop arrays are replaced not merged contrary to doc
    (https://issues.rudder.io/issues/18466[#18466])
* Fixed: If a second rollback starts when a first is processing, system group/technique may be lost
    (https://issues.rudder.io/issues/17720[#17720])

==== Architecture - Internal libs

* Fixed: semaphore gurading LDAP repos are created each time
    (https://issues.rudder.io/issues/18584[#18584])
* Fixed: If LDAP server does not support subtree deletion, we get error when entry does not exists
    (https://issues.rudder.io/issues/18529[#18529])
* Fixed: ifTrace/Debug/etcIsEnabled on pure logger does nothings
    (https://issues.rudder.io/issues/18528[#18528])

==== Performance and scalability

* Fixed: Batch of new nodes can overflow rudder server with inventories
    (https://issues.rudder.io/issues/16773[#16773])
* Fixed: Loading directive's page is very slow
    (https://issues.rudder.io/issues/18510[#18510])

==== Relay server or API

* Fixed: Too many open files in relayd when disk is full
    (https://issues.rudder.io/issues/18437[#18437])
* Fixed: Broken report parser on some info messages
    (https://issues.rudder.io/issues/18497[#18497])

==== Server components

* Fixed: Error when refusing a node
    (https://issues.rudder.io/issues/16739[#16739])

==== System techniques

* Fixed: ncf_hash_file is created with incorrect group permission by system techniques
    (https://issues.rudder.io/issues/18592[#18592])
* Fixed: file augeas set class parameter should be path rather than lens
    (https://issues.rudder.io/issues/18442[#18442])

==== Techniques

* Fixed: ssh key distribution techniques doesn't accept - in user login
    (https://issues.rudder.io/issues/18449[#18449])

==== Miscellaneous

* Fixed: Update file from remote template doc
    (https://issues.rudder.io/issues/18632[#18632])

==== Generic methods - File Management

* Fixed: Create a file from remote template generic method
    (https://issues.rudder.io/issues/18384[#18384])
* Fixed: Flag the file_augeas_set to stagging since the method does not work as intended
    (https://issues.rudder.io/issues/18570[#18570])
* Fixed: File_augeas_set method does not report as expected
    (https://issues.rudder.io/issues/18536[#18536])
* Fixed: Document the permissions recursive and permissions type recursive methods
    (https://issues.rudder.io/issues/18447[#18447])
* Fixed: Permissions recursive method uses an undefined "recursion" variable in its report string
    (https://issues.rudder.io/issues/18446[#18446])
* Fixed: jinja templating script uses python3 even if jinja2 is not installed in python3 but is in python2
    (https://issues.rudder.io/issues/18416[#18416])

==== Generic methods

* Fixed: variable iterator should accept whitespace as separator
    (https://issues.rudder.io/issues/18562[#18562])
* Fixed: variable from command does not always report an error when the command failed
    (https://issues.rudder.io/issues/18512[#18512])
* Fixed: when sum of length of parameter is larger than 1000 characters, reporting leaks too much from one method to another
    (https://issues.rudder.io/issues/18505[#18505])
* Fixed: techniques in audit don't report correctly for editing values in files
    (https://issues.rudder.io/issues/18451[#18451])
* Fixed: Jinja2 templating fails with python 3 with unicode data
    (https://issues.rudder.io/issues/18441[#18441])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.2.0.beta1 (2020-10-29)

=== Changes

==== Packaging

* Update dependencies for Rudder
    (https://issues.rudder.io/issues/18392[#18392])

==== Documentation

* Document Health Check in user doc
    (https://issues.rudder.io/issues/18350[#18350])

==== Web - Compliance & node report

* Make fields of node list customizable
    (https://issues.rudder.io/issues/7967[#7967])

==== Miscellaneous

* Add check for File Descriptor limit 
    (https://issues.rudder.io/issues/18414[#18414])
* Add check for free space
    (https://issues.rudder.io/issues/18357[#18357])

==== Web - UI & UX

* Beautify Global Parameters page
    (https://issues.rudder.io/issues/18418[#18418])
* Healthcheck notification in navigation bar
    (https://issues.rudder.io/issues/18328[#18328])
* Create Healthcheck webpage
    (https://issues.rudder.io/issues/18314[#18314])
* Beautify API accounts page
    (https://issues.rudder.io/issues/18389[#18389])
* Beautify Reports database page
    (https://issues.rudder.io/issues/18388[#18388])
* Beautify Event logs page
    (https://issues.rudder.io/issues/18366[#18366])
* Update settings UI
    (https://issues.rudder.io/issues/18263[#18263])
* Merge ncf editor into Rudder
    (https://issues.rudder.io/issues/18262[#18262])
* Add a shortcut to create directive with latest technique version from the tree
    (https://issues.rudder.io/issues/18164[#18164])
* Make the filter section of the directives tree foldable
    (https://issues.rudder.io/issues/18157[#18157])
* Use new UI template in Directives page
    (https://issues.rudder.io/issues/18076[#18076])

==== API

* Node status API must not return an error when the node is not here
    (https://issues.rudder.io/issues/17666[#17666])
* Add check name in healthcheck API
    (https://issues.rudder.io/issues/18363[#18363])
* Create healthcheck API 
    (https://issues.rudder.io/issues/18306[#18306])

==== Architecture - Dependencies

* Update dependencies for the webapp
    (https://issues.rudder.io/issues/18395[#18395])

==== Relay server or API

* Update relayd dependencies
    (https://issues.rudder.io/issues/18393[#18393])

==== Techniques

* Implement ips package repositories technique
    (https://issues.rudder.io/issues/18434[#18434])
* Create an "old-school" crontab technique to manage crontab in /var/spool/cron/crontabs
    (https://issues.rudder.io/issues/18228[#18228])

==== Generic methods

* Do not fix component key in generic methods reporting
    (https://issues.rudder.io/issues/18433[#18433])

==== Generic methods - Package Management

* Add solaris package support to ncf
    (https://issues.rudder.io/issues/18243[#18243])

=== Bug fixes

==== Packaging

* Fixed: Version rudder-api-client like Rudder on RPM
    (https://issues.rudder.io/issues/18435[#18435])

==== Plugins integration

* Fixed: All plugins are disabled after a minor upgrade
    (https://issues.rudder.io/issues/17878[#17878])

==== Documentation

* Fixed: Prepare doc for 6.2
    (https://issues.rudder.io/issues/18368[#18368])
* Fixed: Broken ncf doc build
    (https://issues.rudder.io/issues/18369[#18369])

==== Architecture - Refactoring

* Fixed: Fix compilation issues after merge
    (https://issues.rudder.io/issues/18443[#18443])

==== Architecture - Dependencies

* Fixed: Update to scala 2.13.3
    (https://issues.rudder.io/issues/18425[#18425])

==== Miscellaneous

* Fixed: Missing RudderConfig parameter pour healthcheck period 
    (https://issues.rudder.io/issues/18413[#18413])

==== Web - Nodes & inventories

* Fixed: Create hooks for when a node inventory is received
    (https://issues.rudder.io/issues/18379[#18379])
* Fixed: Support source package in Rudder inventory
    (https://issues.rudder.io/issues/18317[#18317])

==== Server components

* Fixed: Group owner of files under configuration-repository are inconsistent
    (https://issues.rudder.io/issues/18347[#18347])
* Fixed: Rudder SSL default configuration should follow the system default one
    (https://issues.rudder.io/issues/18338[#18338])

==== Relay server or API

* Fixed: Handle proxies in rudder package command
    (https://issues.rudder.io/issues/18326[#18326])
* Fixed: Handle proxies in rudder package command
    (https://issues.rudder.io/issues/18326[#18326])
* Fixed: Handle proxies in rudder package command
    (https://issues.rudder.io/issues/18326[#18326])
* Fixed: Handle proxies in rudder package command
    (https://issues.rudder.io/issues/18326[#18326])
* Fixed: Handle proxies in rudder package command
    (https://issues.rudder.io/issues/18326[#18326])

==== Technique editor - API

* Fixed: Technique editor doesn't use context path for API call
    (https://issues.rudder.io/issues/18374[#18374])

==== Web - UI & UX

* Fixed: Beautify Archives page
    (https://issues.rudder.io/issues/18365[#18365])
* Fixed: In the Technique Editor, tooltips no longer appear.
    (https://issues.rudder.io/issues/18334[#18334])
* Fixed: Some page sections blink while the Technique Editor is loading
    (https://issues.rudder.io/issues/18329[#18329])
* Fixed: Replace old notifications by those of Rudder
    (https://issues.rudder.io/issues/18324[#18324])

==== Web - Config management

* Fixed: Stop parsing os/agent from technique metadata
    (https://issues.rudder.io/issues/18340[#18340])

==== Performance and scalability

* Fixed: Unused index on table Ruddersysevents
    (https://issues.rudder.io/issues/18110[#18110])

==== System techniques

* Fixed: Cron for Rudder agent on solaris is invalid
    (https://issues.rudder.io/issues/18231[#18231])

==== Generic methods - Package Management

* Fixed: implement nim package manager 
    (https://issues.rudder.io/issues/18313[#18313])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

This page provides a summary of changes for each version.
