= Changelogs for Rudder plugin aix 5.0.\* versions

== aix-5.0-1.4 (2019-12-09)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Postinstall does not trigger policy generation
    (https://issues.rudder.io/issues/14427[#14427])
* Fixed:  License check must break generation when not OK
    (https://issues.rudder.io/issues/14116[#14116])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== aix-5.0-1.3 (2019-12-09)

=== Changes

==== packaging-common

* Adapt plugin loading to not use spring anymore
    (https://issues.rudder.io/issues/13038[#13038])

=== Bug fixes

==== Miscellaneous

* Fixed: Adapt AIX plugin to 5.0
    (https://issues.rudder.io/issues/13603[#13603])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

