= Change logs for api-authorizations plugin 5.0

== api-authorizations-5.0-1.5 (2019-12-08)

=== Changes

=== Bug fixes

==== Documentation

* Fixed: Compress images in plugins
    (https://issues.rudder.io/issues/15620[#15620])
* Fixed:  Update link in readme to rudder.io and missing smarttag for create-node-api
    (https://issues.rudder.io/issues/15306[#15306])
* Fixed:  Update link in readme to rudder.io and missing smarttag for create-node-api
    (https://issues.rudder.io/issues/15306[#15306])
* Fixed: Fix plugins doc
    (https://issues.rudder.io/issues/13724[#13724])

==== Miscellaneous

* Fixed: Port api-authorization to elm 0.19
    (https://issues.rudder.io/issues/14543[#14543])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== api-authorizations-5.0-1.4 (2018-11-28)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: Plugins with elm don’t get elm (again)
(https://issues.rudder.io/issues/13631[#13631])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== api-authorizations-5.0-1.3 (2018-11-28)

=== Changes

==== Miscellaneous

* Remove spring in plugins
(https://issues.rudder.io/issues/13037[#13037])

=== Bug fixes

==== Miscellaneous

* Fixed: Correction on plugins for parent status check
(https://issues.rudder.io/issues/13087[#13087])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
