= Change logs for auth-backends plugin 5.0

== auth-backends-5.0-1.2 (2019-12-08)

=== Changes

==== Miscellaneous

* Improve Authentication backends plugin UI
    (https://issues.rudder.io/issues/13696[#13696])

=== Bug fixes

==== Miscellaneous

* Fixed: Adapt authentication backend for correct init order
    (https://issues.rudder.io/issues/13709[#13709])
* Fixed: Missing documentation
    (https://issues.rudder.io/issues/13702[#13702])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-5.0-1.2 (2018-11-28)

=== Changes

==== Miscellaneous

* Improve Authentication backends plugin UI
(https://issues.rudder.io/issues/13696[#13696])

=== Bug fixes

==== Miscellaneous

* Fixed: Adapt authentication backend for correct init order
(https://issues.rudder.io/issues/13709[#13709])
* Fixed: Missing documentation
(https://issues.rudder.io/issues/13702[#13702])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== auth-backends-5.0-1.1 (2018-11-28)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: Plugins with elm don’t get elm (again)
(https://issues.rudder.io/issues/13631[#13631])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== auth-backends-5.0-1.0 (2018-11-28)

=== Changes

==== Miscellaneous

* Add an UI to display configured authentication backend
(https://issues.rudder.io/issues/13558[#13558])
* Target groups for the Validation Workflow
(https://issues.rudder.io/issues/12194[#12194])
* Create ``user management'' plugin
(https://issues.rudder.io/issues/13267[#13267])
* Create alternative backend authentication plugin
(https://issues.rudder.io/issues/13024[#13024])

==== UI - UX

* Update menu registering for plugins
(https://issues.rudder.io/issues/13379[#13379])

=== Bug fixes

==== Miscellaneous

* Fixed: Correction on plugins for parent status check
(https://issues.rudder.io/issues/13087[#13087])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre BRIANCEAU

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
