Changelogs for Rudder plugin branding 5.0.* versions
----------------------------------------------------

 Plugin branding - branding-5.0-1.3 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Bug fixes
^^^^^^^^^

Packaging
+++++++++

* Fixed: Plugins with elm don’t get elm (again)
(https://issues.rudder.io/issues/13631[#13631])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin branding - branding-5.0-1.2 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Miscellaneous
+++++++++++++

* Target groups for the Validation Workflow
(https://issues.rudder.io/issues/12194[#12194])
* Remove spring in plugins
(https://issues.rudder.io/issues/13037[#13037])

UI - UX
+++++++

* Update menu registering for plugins
(https://issues.rudder.io/issues/13379[#13379])

Bug fixes
^^^^^^^^^

Packaging
+++++++++

* Fixed: Rename changes-validation to change-validation
(https://issues.rudder.io/issues/13393[#13393])

Miscellaneous
+++++++++++++

* Fixed: Correction on plugins for parent status check
(https://issues.rudder.io/issues/13087[#13087])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre BRIANCEAU

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
