= Change logs for change-validation plugin 5.0

== change-validation-5.0-1.4 (2019-12-08)

=== Changes

==== Miscellaneous

* Manage users infos from API and UI
    (https://issues.rudder.io/issues/15147[#15147])

=== Bug fixes

==== Web - Config management

* Fixed: Changing a Directive from "Inherit Standard" to "Audit only" does not show a diff when changes validation is enabled
    (https://issues.rudder.io/issues/9788[#9788])

==== Miscellaneous

* Fixed: Missing logs in change validation plugin
    (https://issues.rudder.io/issues/15113[#15113])
* Fixed: Change validation does not compile with latest version
    (https://issues.rudder.io/issues/16014[#16014])

==== Documentation

* Fixed: Compress images in plugins
    (https://issues.rudder.io/issues/15620[#15620])
* Fixed:  Update link in readme to rudder.io and missing smarttag for create-node-api
    (https://issues.rudder.io/issues/15306[#15306])
* Fixed:  Update link in readme to rudder.io and missing smarttag for create-node-api
    (https://issues.rudder.io/issues/15306[#15306])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-5.0-1.3 (2019-12-08)

=== Changes

==== Miscellaneous

* Select a group of user concerned by the workflow
    (https://issues.rudder.io/issues/14826[#14826])
* Correct API order in plugins  
    (https://issues.rudder.io/issues/14810[#14810])
* port change-validation plugin to elm 0.19
    (https://issues.rudder.io/issues/14584[#14584])

=== Bug fixes

==== Miscellaneous

* Fixed: Success notification on save goes behind  input group
    (https://issues.rudder.io/issues/14756[#14756])

==== Documentation

* Fixed: Add documentation about rudder <-> plugin version compatibility
    (https://issues.rudder.io/issues/13900[#13900])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-5.0-1.3 (2019-07-10)

=== Changes

==== Miscellaneous

* Select a group of user concerned by the workflow
    (https://issues.rudder.io/issues/14826[#14826])
* Correct API order in plugins  
    (https://issues.rudder.io/issues/14810[#14810])
* port change-validation plugin to elm 0.19
    (https://issues.rudder.io/issues/14584[#14584])

=== Bug fixes

==== Miscellaneous

* Fixed: Success notification on save goes behind  input group
    (https://issues.rudder.io/issues/14756[#14756])

==== Documentation

* Fixed: Add documentation about rudder <-> plugin version compatibility
    (https://issues.rudder.io/issues/13900[#13900])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-5.0-1.2 (2018-11-28)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Directive creation directly linked to a rule are ignored
(https://issues.rudder.io/issues/13895[#13895])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== change-validation-5.0-1.1 (2018-11-28)

=== Changes

==== Miscellaneous

* Improve Change Valdiation plugin UI
(https://issues.rudder.io/issues/13729[#13729])

=== Bug fixes

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== change-validation-5.0-1.0 (2018-11-28)

=== Changes

==== Miscellaneous

* Target groups for the Validation Workflow
(https://issues.rudder.io/issues/12194[#12194])
* Target groups for the Validation Workflow
(https://issues.rudder.io/issues/12194[#12194])

=== Bug fixes

==== Packaging

* Fixed: Plugins with elm don’t get elm (again)
(https://issues.rudder.io/issues/13631[#13631])
* Fixed: Rename changes-validation to change-validation
(https://issues.rudder.io/issues/13393[#13393])

==== Miscellaneous

* Fixed: Bad authorization for Change Validations pages: validator can’t
validate (https://issues.rudder.io/issues/13628[#13628])
* Fixed: Change request must not be saved when no validation is needed
(plugin) (https://issues.rudder.io/issues/13630[#13630])
* Fixed: Check node, not group, for need of change request
(https://issues.rudder.io/issues/13559[#13559])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre BRIANCEAU

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
