= Change logs for change-validation plugin 5.0

== change-validation-5.0-1.2 (2018-11-28)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Directive creation directly linked to a rule are ignored
(https://issues.rudder.io/issues/13895[#13895])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== change-validation-5.0-1.1 (2018-11-28)

=== Changes

==== Miscellaneous

* Improve Change Valdiation plugin UI
(https://issues.rudder.io/issues/13729[#13729])

=== Bug fixes

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== change-validation-5.0-1.0 (2018-11-28)

=== Changes

==== Miscellaneous

* Target groups for the Validation Workflow
(https://issues.rudder.io/issues/12194[#12194])
* Target groups for the Validation Workflow
(https://issues.rudder.io/issues/12194[#12194])

=== Bug fixes

==== Packaging

* Fixed: Plugins with elm don’t get elm (again)
(https://issues.rudder.io/issues/13631[#13631])
* Fixed: Rename changes-validation to change-validation
(https://issues.rudder.io/issues/13393[#13393])

==== Miscellaneous

* Fixed: Bad authorization for Change Validations pages: validator can’t
validate (https://issues.rudder.io/issues/13628[#13628])
* Fixed: Change request must not be saved when no validation is needed
(plugin) (https://issues.rudder.io/issues/13630[#13630])
* Fixed: Check node, not group, for need of change request
(https://issues.rudder.io/issues/13559[#13559])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre BRIANCEAU

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
