= Changelogs for Rudder plugin cve 5.0.\* versions

== cve-5.0-0.2 (2019-12-09)

=== Changes

==== Miscellaneous

* Improve CVEs list
    (https://issues.rudder.io/issues/14823[#14823])

=== Bug fixes

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-5.0-0.1 (2019-05-10)

=== Changes

==== Miscellaneous

* Change how empty cvss (v3 missing) score are stored in databse
    (https://issues.rudder.io/issues/14855[#14855])
* Display details of the selected CVE
    (https://issues.rudder.io/issues/14709[#14709])
* Create the first version of the interface
    (https://issues.rudder.io/issues/14708[#14708])
* Set-up project
    (https://issues.rudder.io/issues/14504[#14504])
* Set-up project
    (https://issues.rudder.io/issues/14504[#14504])

=== Bug fixes

==== Miscellaneous

* Fixed: Move cve parsed file to a new name
    (https://issues.rudder.io/issues/14858[#14858])
* Fixed: Store cve info, store vulners check, create cve api, use api to get data 
    (https://issues.rudder.io/issues/14821[#14821])
* Fixed:  Correct API order in plugins privates
    (https://issues.rudder.io/issues/14811[#14811])
* Fixed: Read cve files from plugin folder and add them to database
    (https://issues.rudder.io/issues/14705[#14705])
* Fixed: Cve elm data model
    (https://issues.rudder.io/issues/14624[#14624])
* Fixed: Get all CVE for all packages by os/version from Vulners
    (https://issues.rudder.io/issues/14519[#14519])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

