= Change logs for datasources plugin 5.0

== datasources-5.0-1.6 (2019-12-09)

=== Changes

==== Miscellaneous

* Correct API order in plugins  
    (https://issues.rudder.io/issues/14810[#14810])
* Make number of parallel connexions configurable
    (https://issues.rudder.io/issues/13782[#13782])

=== Bug fixes

==== Miscellaneous

* Fixed: [breaking] NoSuchMethodError with datasources 4.3-1.4 + Rudder 4.3.7
    (https://issues.rudder.io/issues/13933[#13933])
* Fixed: On small hardware, datasource test timeout
    (https://issues.rudder.io/issues/13733[#13733])
* Fixed: A test is in error in datasources 4.3
    (https://issues.rudder.io/issues/13731[#13731])
* Fixed: Correct attempt.transact -> transact.attempt in SQL request (see #13517)
    (https://issues.rudder.io/issues/13588[#13588])

==== Documentation

* Fixed: Fix plugins doc
    (https://issues.rudder.io/issues/13724[#13724])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-5.0-1.5 (2019-12-09)

=== Changes

==== UI - UX

* Update menu registering for plugins
    (https://issues.rudder.io/issues/13379[#13379])

==== Packaging

* Generate usable docs files from plugins
    (https://issues.rudder.io/issues/13265[#13265])

==== Miscellaneous

* Remove spring in plugins
    (https://issues.rudder.io/issues/13037[#13037])
* Create a plugin for relay servers
    (https://issues.rudder.io/issues/12888[#12888])

=== Bug fixes

==== Packaging

* Fixed: Update build so that licensed binaries don't embed key/license
    (https://issues.rudder.io/issues/13283[#13283])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-5.0-1.5 (2018-11-28)

=== Changes

==== UI - UX

* Update menu registering for plugins
(https://issues.rudder.io/issues/13379[#13379])

==== Packaging

* Generate usable docs files from plugins
(https://issues.rudder.io/issues/13265[#13265])

==== Miscellaneous

* Remove spring in plugins
(https://issues.rudder.io/issues/13037[#13037])
* Create a plugin for relay servers
(https://issues.rudder.io/issues/12888[#12888])

=== Bug fixes

==== Packaging

* Fixed: Update build so that licensed binaries don’t embed key/license
(https://issues.rudder.io/issues/13283[#13283])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
