= Change logs for dsc plugin 5.0

== dsc-5.0-1.17 (2020-07-20)

=== Changes

=== Bug fixes

==== System integration

* Fixed: update is impossible due to tls incompatibility
    (https://issues.rudder.io/issues/16100[#16100])

=== Release notes

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-5.0-1.16 (2019-12-09)

=== Changes

=== Bug fixes

==== System integration

* Fixed: Missing inventory.pm patches to add inventory extension
    (https://issues.rudder.io/issues/16230[#16230])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-5.0-1.15 (2019-11-21)

=== Changes

=== Bug fixes

==== System integration

* Fixed: Make the extended inventory works on windows
    (https://issues.rudder.io/issues/16182[#16182])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-5.0-1.14 (2019-11-04)

=== Changes

=== Bug fixes

==== System integration

* Fixed: Invalid certificate subject: contains '\" du'
    (https://issues.rudder.io/issues/15218[#15218])

==== Packaging

* Fixed: improve text on agent install
    (https://issues.rudder.io/issues/14310[#14310])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-5.0-1.13 (2019-03-20)

=== Changes

==== Techniques

* Windows software technique should be way more flexible in its check methods
    (https://issues.rudder.io/issues/14344[#14344])
* Registry key edition technique should let the user remove a given registry entry
    (https://issues.rudder.io/issues/13919[#13919])

==== ncf

* Add a info level reporting
    (https://issues.rudder.io/issues/13601[#13601])
* Add a generic method to manage NTFS
    (https://issues.rudder.io/issues/13720[#13720])
* Add functions to manipulate classes and contexts
    (https://issues.rudder.io/issues/13607[#13607])

==== Packaging

* Add dll download for the NTFSSecurity module in the Makefile
    (https://issues.rudder.io/issues/13949[#13949])
* Bring the NTFSSecurity powershell module with the agent
    (https://issues.rudder.io/issues/13942[#13942])

=== Bug fixes

==== ncf

* Fixed: wrong method name used in the NTFS generic method
    (https://issues.rudder.io/issues/14441[#14441])
* Fixed: likely broken perl mustache lib
    (https://issues.rudder.io/issues/11380[#11380])
* Fixed: wrong component name on service enabled on windows
    (https://issues.rudder.io/issues/14141[#14141])
* Fixed: NTFS parameters field name is error prone
    (https://issues.rudder.io/issues/13995[#13995])
* Fixed: dsc tests are failing on service restart #2
    (https://issues.rudder.io/issues/13953[#13953])
* Fixed: dsc tests are failing ion service restart
    (https://issues.rudder.io/issues/13940[#13940])

==== Techniques

* Fixed: version comparison in Technique "Install Software" is error prone
    (https://issues.rudder.io/issues/14308[#14308])
* Fixed: error when installing a software with technique "Windows software" if software is in a subdirectory
    (https://issues.rudder.io/issues/14305[#14305])
* Fixed: Windows-Software technique does not handle binaries in a subfolder of the shared file repo
    (https://issues.rudder.io/issues/13907[#13907])

==== Packaging

* Fixed: copyright date on agent install is 2017
    (https://issues.rudder.io/issues/14303[#14303])
* Fixed: The packaging/Files/modules directory shoud be in the repository
    (https://issues.rudder.io/issues/13950[#13950])

==== Rudder web app

* Fixed: Update parent-pom for plugin
    (https://issues.rudder.io/issues/14299[#14299])
* Fixed: add test for policy generation with separated directives
    (https://issues.rudder.io/issues/14045[#14045])

==== Miscellaneous

* Fixed:  License check must break generation when not OK
    (https://issues.rudder.io/issues/14116[#14116])

==== System techniques

* Fixed: end run report execution should not be in info level mode
    (https://issues.rudder.io/issues/13991[#13991])

==== CLI

* Fixed: Wrong module path checking in rudder.ps1
    (https://issues.rudder.io/issues/13948[#13948])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-5.0-1.12 (2018-11-28)

=== Changes

==== Techniques

* Full path details to shared-folders in WebUI for ``File copy from
Rudder Shared Folder'' (https://issues.rudder.io/issues/13818[#13818])

==== CLI

* Add a global variable to check if the verbose mode is active
(https://issues.rudder.io/issues/13600[#13600])

=== Bug fixes

==== System integration

* Fixed: agent is not correctly running
(https://issues.rudder.io/issues/13905[#13905])

==== System techniques

* Fixed: inventory is not generated at install, because of a path issue
to make the signature (https://issues.rudder.io/issues/13904[#13904])
* Fixed: Rudder agent does not manage the inventory task
(https://issues.rudder.io/issues/13617[#13617])
* Fixed: Rudder agent scheduled task is not working due to encoding
problem (https://issues.rudder.io/issues/13616[#13616])

==== CLI

* Fixed: set culture fails on 2008R2
(https://issues.rudder.io/issues/11179[#11179])
* Fixed: Do not display curl output when sending an inventory
(https://issues.rudder.io/issues/11012[#11012])
* Fixed: ``rudder agent run -u'' does not work properly on dsc
(https://issues.rudder.io/issues/13620[#13620])

==== Inventory

* Fixed: Windows VM on Redhat Openstack Nova compute QEMU virtual
machines are seen as physical
(https://issues.rudder.io/issues/11737[#11737])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Ilan COSTA

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== dsc-5.0-1.11 (2018-11-28)

=== Changes

==== Rudder web app

* Adapt DSC plujgin with 5.0 changes
(https://issues.rudder.io/issues/13605[#13605])
* Remove spring usage for plugin definition
(https://issues.rudder.io/issues/13039[#13039])

=== Bug fixes

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
