= Change logs for notify plugin 5.0

== notify-5.0-1.0 (2018-11-30)

=== Changes

==== Miscellaneous

* prepare the plugin for the v1 release
(https://issues.rudder.io/issues/13917[#13917])
* Make a feature to open ticket based on rudder events
(https://issues.rudder.io/issues/13854[#13854])

=== Bug fixes

==== Miscellaneous

* Fixed: When no filters are set, the plugin does not behave like
expected (https://issues.rudder.io/issues/13925[#13925])
* Fixed: Missing dependecy on python-configparser
(https://issues.rudder.io/issues/13922[#13922])
* Fixed: Some plugins overwrite configuration when upgrading
(https://issues.rudder.io/issues/13575[#13575])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
