== reporting-5.0-1.1 (2019-03-20)

=== Changes

==== Miscellaneous

* Add a way to use default/custom data when creating/updating templates
    (https://issues.rudder.io/issues/14493[#14493])
* Add delete button for reports
    (https://issues.rudder.io/issues/14460[#14460])
* Adding new columns to a table
    (https://issues.rudder.io/issues/14448[#14448])

=== Bug fixes

==== Miscellaneous

* Fixed: Align id to template name
    (https://issues.rudder.io/issues/14495[#14495])
* Fixed: Remove empty tooltips
    (https://issues.rudder.io/issues/14494[#14494])
* Fixed: Only load report data when needed
    (https://issues.rudder.io/issues/14466[#14466])
* Fixed: Need to remove system rules from compliance graph when no rule/groups selected
    (https://issues.rudder.io/issues/14457[#14457])
* Fixed: Remove dev templates
    (https://issues.rudder.io/issues/14459[#14459])
* Fixed: Still need to improve data request
    (https://issues.rudder.io/issues/14456[#14456])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

