= Change logs for scale-out-relay plugin 5.0

== scale-out-relay-5.0-1.1 (2018-11-28)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: Plugins with elm don’t get elm (again)
(https://issues.rudder.io/issues/13631[#13631])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== scale-out-relay-5.0-1.0 (2018-11-28)

=== Changes

==== Miscellaneous

* Create a plugin for relay servers
(https://issues.rudder.io/issues/12888[#12888])

=== Bug fixes

==== Miscellaneous

* Fixed: Correction on plugins for parent status check
(https://issues.rudder.io/issues/13087[#13087])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
