Changelogs for Rudder plugin user-management 5.0.* versions
-----------------------------------------------------------

 Plugin user-management - user-management-5.0-1.2 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Miscellaneous
+++++++++++++

* Improve User Management plugin UI
(https://issues.rudder.io/issues/13711[#13711])

Bug fixes
^^^^^^^^^

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin user-management - user-management-5.0-1.1 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Bug fixes
^^^^^^^^^

Packaging
+++++++++

* Fixed: Plugins with elm don’t get elm (again)
(https://issues.rudder.io/issues/13631[#13631])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin user-management - user-management-5.0-1.0 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Miscellaneous
+++++++++++++

* Create ``user management'' plugin
(https://issues.rudder.io/issues/13267[#13267])

Bug fixes
^^^^^^^^^

Miscellaneous
+++++++++++++

* Fixed: Add a ``reload'' button and update CSS
(https://issues.rudder.io/issues/13589[#13589])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
