= Change logs for Rudder 7.0

==  Rudder 7.0.1 (2022-02-18)

=== Changes


==== Packaging

* Update to CFEngine 3.18.1
    (https://issues.rudder.io/issues/20329[#20329])

==== Language

* Add block syntax in the rudder-lang documentation
    (https://issues.rudder.io/issues/20762[#20762])

==== Web - UI & UX

* Add a link on the Directives and Groups to their own page
    (https://issues.rudder.io/issues/20753[#20753])
* cloning a generic method creates the method at the end of the technique
    (https://issues.rudder.io/issues/20703[#20703])
* Improve directives and groups selection in Rules UI
    (https://issues.rudder.io/issues/20625[#20625])

==== Web - Nodes & inventories

* kernel version doesn't show in the node page
    (https://issues.rudder.io/issues/20721[#20721])

==== Documentation

* Replacement of the screenshot in the README
    (https://issues.rudder.io/issues/20708[#20708])

=== Bug fixes

==== Packaging

* Fixed: Missing augeas dependency on rpm
    (https://issues.rudder.io/issues/20687[#20687])
* Fixed: sleep in postinst agent check
    (https://issues.rudder.io/issues/20673[#20673])
* Fixed: Missing fusion patches for windows agent
    (https://issues.rudder.io/issues/20670[#20670])

==== Documentation

* Fixed: Documentation about properties usage on windows node uses an incorrect syntax
    (https://issues.rudder.io/issues/20731[#20731])
* Fixed: Upgrade notes from 6.1|6.2 -> 7.0 title is not clear enough
    (https://issues.rudder.io/issues/20659[#20659])
* Fixed: Missing v14 api description for 7.0
    (https://issues.rudder.io/issues/20654[#20654])

==== Language

* Fixed: In some cases, generate_lib rudder-lang utility does throw exception instead of properly parsing the error
    (https://issues.rudder.io/issues/20761[#20761])
* Fixed: Style fixes in language doc
    (https://issues.rudder.io/issues/20729[#20729])

==== Web - Technique editor

* Fixed: Ressource not found when creating a draft and comming back to it to save it as a technique
    (https://issues.rudder.io/issues/20184[#20184])
* Fixed: Creating a technique with a name normalized to generic method id breaks technique editor
    (https://issues.rudder.io/issues/20710[#20710])
* Fixed: when clicking on "show docs" on a generic method in the middle part of technique editor, it doesn't unfold the right part
    (https://issues.rudder.io/issues/19720[#19720])
* Fixed: Once we decided on which generic method we focus report in a block, it shows the uuid rather than its name
    (https://issues.rudder.io/issues/20738[#20738])
* Fixed: Tooltips remains when we remove a generic method
    (https://issues.rudder.io/issues/20557[#20557])
* Fixed: Draft infos remaining after deletion 
    (https://issues.rudder.io/issues/20631[#20631])

==== API

* Fixed: Factor out trait for api test in yaml
    (https://issues.rudder.io/issues/20759[#20759])
* Fixed: No clear error message when calling api with curl and data are not url-encoded
    (https://issues.rudder.io/issues/10915[#10915])

==== Web - UI & UX

* Fixed: Broken hover when condition is long
    (https://issues.rudder.io/issues/20679[#20679])
* Fixed: when a rule is disabled we cannot see its associated directives
    (https://issues.rudder.io/issues/20713[#20713])
* Fixed: Opening and closing generic method in the technique editor is done in a different place
    (https://issues.rudder.io/issues/20694[#20694])
* Fixed: Tooltip on enforce/audit label in rules tree not working
    (https://issues.rudder.io/issues/20501[#20501])
* Fixed: Categories in the technique editor are flattened
    (https://issues.rudder.io/issues/20453[#20453])
* Fixed: Reccent changes count on rule tab
    (https://issues.rudder.io/issues/20638[#20638])
* Fixed: Selected technique is wrong after cloning
    (https://issues.rudder.io/issues/20454[#20454])
* Fixed: Highlight the rule on the tree when display details
    (https://issues.rudder.io/issues/20630[#20630])

==== Web - Compliance & node report

* Fixed: when there's a disabled directive in a rule, it's really hard to see
    (https://issues.rudder.io/issues/18672[#18672])
* Fixed: when there's a disabled directive in a rule, it's really hard to see
    (https://issues.rudder.io/issues/18672[#18672])

==== Web - Config management

* Fixed: Disable Reporting on a variable String method causes policy update errors
    (https://issues.rudder.io/issues/20700[#20700])

==== Architecture - Dependencies

* Fixed: Update xerces version 
    (https://issues.rudder.io/issues/20676[#20676])

==== Security

* Fixed: Data race in thread-local relayd dependency
    (https://issues.rudder.io/issues/20639[#20639])

==== Miscellaneous

* Fixed: In 6.2.10 the plugin can not uninstall itself in some cases
    (https://issues.rudder.io/issues/20392[#20392])

==== Techniques

* Fixed: SNMP installation uses deprecated package method, and it reports an error even though it works
    (https://issues.rudder.io/issues/16694[#16694])

==== Agent

* Fixed: Excessive Agent restarts (Agent on Debian 11)
    (https://issues.rudder.io/issues/20685[#20685])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* I C
* Nigel Mundy

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.0.2 (2022-04-08)

=== Changes


==== Packaging

* We should detect malformed patch in the packaging to disallow building incorrect packages
    (https://issues.rudder.io/issues/9810[#9810])

==== Documentation

* Windows support should be documented as the other agents
    (https://issues.rudder.io/issues/20835[#20835])
* Add a compatibilty table for agent relay server in the documentation
    (https://issues.rudder.io/issues/20621[#20621])

==== Web - UI & UX

* Glitch in node compliance details
    (https://issues.rudder.io/issues/20693[#20693])

==== Architecture - Internal libs

* Add name for spring security main auth configuration bean to be used by oauth2 
    (https://issues.rudder.io/issues/20886[#20886])

==== Language

* Document the rudder-lang and technique editor incompatibilities
    (https://issues.rudder.io/issues/20766[#20766])

==== Techniques

* Reformat all the statements in userManagement technique
    (https://issues.rudder.io/issues/20878[#20878])

==== Generic methods - File Management

* Improve File from HTTP server method documentation
    (https://issues.rudder.io/issues/20810[#20810])

=== Bug fixes

==== Packaging

* Fixed: rudder-webapp requires rsync to build for RHEL
    (https://issues.rudder.io/issues/20974[#20974])

==== Agent

* Fixed: Lower the log level of the "Skipping adding class [...] as its name is equal or longer than 1024" message
    (https://issues.rudder.io/issues/20960[#20960])
* Fixed: In SLES 15, SP is view as part of version - Rudder 7.0
    (https://issues.rudder.io/issues/20950[#20950])

==== Security

* Fixed: Update embedded openssl to 1.1.1n
    (https://issues.rudder.io/issues/20894[#20894])
* Fixed: Update jdbc postgres driver to 4.2.25 for CVE-2022-21724
    (https://issues.rudder.io/issues/20969[#20969])
* Fixed: Vulnerability in the regex crate
    (https://issues.rudder.io/issues/20872[#20872])

==== Documentation

* Fixed: Broken list of compatible OS in 7.0
    (https://issues.rudder.io/issues/20942[#20942])
* Fixed: Correct doc on windows KB update
    (https://issues.rudder.io/issues/20891[#20891])
* Fixed: backup/restore doc is incomplete
    (https://issues.rudder.io/issues/20888[#20888])

==== Miscellaneous

* Fixed: Show more details in exception when parsing an invalid technique version
    (https://issues.rudder.io/issues/20976[#20976])
* Fixed: Update spring to 5.2.20 to fix CVE-2022-22965
    (https://issues.rudder.io/issues/20972[#20972])
* Fixed: Update spring to 5.2.20 to fix CVE-2022-22965
    (https://issues.rudder.io/issues/20972[#20972])
* Fixed: "Disable reporting" for windows method calls does produce unexpected reports
    (https://issues.rudder.io/issues/20897[#20897])
* Fixed: Compilation warning on branche 6.2
    (https://issues.rudder.io/issues/20874[#20874])

==== Web - Technique editor

* Fixed: Correct minor version condition for Ubuntu in technique editor
    (https://issues.rudder.io/issues/20973[#20973])
* Fixed: When editing files with the technique editor resources manager, newlines at the end of file are trimmed
    (https://issues.rudder.io/issues/19319[#19319])
* Fixed: Suppressed techniques coming back to life forever
    (https://issues.rudder.io/issues/19006[#19006])

==== Web - UI & UX

* Fixed: Hide action buttons if the user does not have write permission on the Rules
    (https://issues.rudder.io/issues/20961[#20961])
* Fixed: Edit mode should be enabled by default when creating a rule
    (https://issues.rudder.io/issues/20954[#20954])
* Fixed: In the technical logs table of a node, mouse cursor should not change when hovering a Status badge
    (https://issues.rudder.io/issues/20953[#20953])
* Fixed: Wrong redirect url for system group in rule page
    (https://issues.rudder.io/issues/20782[#20782])
* Fixed: Applied directive doesn't show up when there is no node
    (https://issues.rudder.io/issues/20856[#20856])
* Fixed: Displays a warning icon for directives that are not used by any rule.
    (https://issues.rudder.io/issues/20692[#20692])
* Fixed: We cannot filter rules by tag anymore
    (https://issues.rudder.io/issues/20848[#20848])
* Fixed: We cannot filter rules by tag anymore
    (https://issues.rudder.io/issues/20848[#20848])

==== Web - Config management

* Fixed: Starting policy generation by hand fails if node-configuration-hashes.json 
    (https://issues.rudder.io/issues/20926[#20926])

==== API

* Fixed: Some api response have an id field but should'nt have one
    (https://issues.rudder.io/issues/20871[#20871])
* Fixed: Broken allowed network curl example
    (https://issues.rudder.io/issues/20844[#20844])

==== Architecture - Internal libs

* Fixed: Duplicate classes RudderUserDetails
    (https://issues.rudder.io/issues/20734[#20734])

==== CI

* Fixed: Don't skip tests in webapp publish
    (https://issues.rudder.io/issues/20812[#20812])
* Fixed: Missing clean in webapp publish
    (https://issues.rudder.io/issues/20772[#20772])

==== Architecture - Refactoring

* Fixed: NodeAndPolicyServerReturnType name is misleading for search that include root server
    (https://issues.rudder.io/issues/20802[#20802])

==== Performance and scalability

* Fixed: Improve dynamic group computation speed and fix inverted searched
    (https://issues.rudder.io/issues/20716[#20716])

==== Web - Nodes & inventories

* Fixed: List of directive for the pending node is invalid
    (https://issues.rudder.io/issues/20736[#20736])

==== Techniques

* Fixed: post hook for copyGitFile on windows don't report
    (https://issues.rudder.io/issues/20909[#20909])
* Fixed: dsc techniques have invalid parameters when calling generic method
    (https://issues.rudder.io/issues/20907[#20907])
* Fixed: Unexpected reporting in userManagement in audit when user is not present
    (https://issues.rudder.io/issues/19427[#19427])
* Fixed: Patch dsc techniques according to #20830
    (https://issues.rudder.io/issues/20832[#20832])
* Fixed: When upgrading from 6.2 to 7.0, the previous rudder logrotate configuration is not removed
    (https://issues.rudder.io/issues/20792[#20792])

==== System integration

* Fixed: Logrotate configuration for relayd is broken
    (https://issues.rudder.io/issues/20791[#20791])

==== Generic methods

* Fixed: Variable string from command fails when command contains control structures
    (https://issues.rudder.io/issues/20128[#20128])
* Fixed: All classes manipulations are ineffeccient because there are repeated 3 times
    (https://issues.rudder.io/issues/20885[#20885])
* Fixed: No report from sysctl generic method
    (https://issues.rudder.io/issues/20612[#20612])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Alexis TARUSSIO

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.0.3 (2022-05-31)

=== Changes


==== Web - UI & UX

* Update css related to the change validation plugin
    (https://issues.rudder.io/issues/21052[#21052])

==== Server components

* allow a user to pass a password to server create-user command
    (https://issues.rudder.io/issues/20675[#20675])

=== Bug fixes

==== Documentation

* Fixed: Documentation about certificate handling during uprade is not great
    (https://issues.rudder.io/issues/21129[#21129])
* Fixed: Fix the relayd logging documentation
    (https://issues.rudder.io/issues/20985[#20985])

==== Miscellaneous

* Fixed: Document that port 5309 can be disable in node configuration
    (https://issues.rudder.io/issues/20982[#20982])

==== Relay server or API

* Fixed: Huge broken logs in relayd
    (https://issues.rudder.io/issues/21157[#21157])

==== Security

* Fixed: security checks fails because of request to sonatype oss index
    (https://issues.rudder.io/issues/21179[#21179])
* Fixed: Fix some cve in dependencies 
    (https://issues.rudder.io/issues/21169[#21169])
* Fixed: Ignore some CVE that cannot be fixed in 6.1 branch
    (https://issues.rudder.io/issues/21103[#21103])
* Fixed: Ignore some CVE that cannot be fixed in 6.1 branch
    (https://issues.rudder.io/issues/21103[#21103])
* Fixed: Don't display oauth/oidc client secret in logs
    (https://issues.rudder.io/issues/21077[#21077])
* Fixed: Ignore CVEs for spring-ldap-core
    (https://issues.rudder.io/issues/21027[#21027])
* Fixed: Update spring and logback version because of new CVE
    (https://issues.rudder.io/issues/21022[#21022])

==== System integration

* Fixed: Root log explain_compliance is in debug by default
    (https://issues.rudder.io/issues/21166[#21166])
* Fixed: rudder package does not sort plugin version correctly
    (https://issues.rudder.io/issues/21121[#21121])

==== Web - Nodes & inventories

* Fixed: Criteria not working when filter on IP adress and GoupID in group page
    (https://issues.rudder.io/issues/21144[#21144])
* Fixed: Sometime inventory processing is not done when inventory is receveived
    (https://issues.rudder.io/issues/19585[#19585])
* Fixed: List of nodes by version does not include windows nodes
    (https://issues.rudder.io/issues/17728[#17728])
* Fixed: Two same envvar modulo a space at begining of name leads to LDAP error when saving inventory
    (https://issues.rudder.io/issues/20984[#20984])

==== Web - Technique editor

* Fixed: Filter on agent type on technique editor is not correctly shown
    (https://issues.rudder.io/issues/21160[#21160])
* Fixed: The display of the DSC icon is broken in the technical editor
    (https://issues.rudder.io/issues/21016[#21016])
* Fixed: Unable to open a block within a block when it has just been drop from the list 
    (https://issues.rudder.io/issues/20787[#20787])
* Fixed: When cloning a block with two identical methods, only one is cloned
    (https://issues.rudder.io/issues/21001[#21001])

==== API

* Fixed: Directive and rule revision is not parsed in API
    (https://issues.rudder.io/issues/21150[#21150])
* Fixed: Rudder incorectly parse URL with a '+' in the path into spaces
    (https://issues.rudder.io/issues/20943[#20943])
* Fixed: Deleting a rule's category leeds to an error
    (https://issues.rudder.io/issues/21080[#21080])
* Fixed: Update api doc tool chain
    (https://issues.rudder.io/issues/21073[#21073])
* Fixed: Generation not started when modifying authorized network via API
    (https://issues.rudder.io/issues/20979[#20979])

==== Packaging

* Fixed: Backup ca.cert like other cert files
    (https://issues.rudder.io/issues/21143[#21143])

==== Web - Config management

* Fixed: condition from windows node does not take condition from blocks
    (https://issues.rudder.io/issues/21108[#21108])
* Fixed: Revision are taken into account during generation
    (https://issues.rudder.io/issues/20929[#20929])

==== Architecture - Refactoring

* Fixed: Scala does not really supports [_:P] syntax
    (https://issues.rudder.io/issues/21107[#21107])
* Fixed: Update TechniqueVersion to conform to method visibility
    (https://issues.rudder.io/issues/21106[#21106])

==== Web - Compliance & node report

* Fixed: Compliance percentage computation in ComplianceLevel is not correct, and performance is not correct
    (https://issues.rudder.io/issues/20998[#20998])
* Fixed: Compliance percentage computation in ComplianceLevel is not correct, and performance is not correct
    (https://issues.rudder.io/issues/20998[#20998])
* Fixed: Techniques with no component define have no reporting
    (https://issues.rudder.io/issues/21007[#21007])

==== Web - UI & UX

* Fixed: Fold and unfold all categories button not working in rules page
    (https://issues.rudder.io/issues/21079[#21079])
* Fixed: In Nodes table, the "Edit columns" button should be renamed when activated
    (https://issues.rudder.io/issues/21013[#21013])
* Fixed: Sort by status does not work on rules table
    (https://issues.rudder.io/issues/21010[#21010])

==== Performance and scalability

* Fixed: The way groups are fetched when responding to API compliance is inefficient
    (https://issues.rudder.io/issues/21028[#21028])

==== Web - Maintenance

* Fixed: Download as zip in archives page returns a 404
    (https://issues.rudder.io/issues/20903[#20903])

==== System techniques

* Fixed: Error in relay policies when disabling file sharing in policies
    (https://issues.rudder.io/issues/21125[#21125])
* Fixed: Rudder server 7.X generates invalid configuration for 6.X relayd
    (https://issues.rudder.io/issues/21122[#21122])
* Fixed: When updating allowed networks of a relay, rudder-cf-serverd service does not seem to be restarted
    (https://issues.rudder.io/issues/20993[#20993])
* Fixed: when database is not on the root server, policy generation fails
    (https://issues.rudder.io/issues/20986[#20986])

==== Techniques

* Fixed: wrong spelling of wily in apt package manager settings
    (https://issues.rudder.io/issues/21113[#21113])

==== CI

* Fixed: Ci does not properly clean its test files
    (https://issues.rudder.io/issues/21178[#21178])
* Fixed: Improve cleanup of root-owned files in tests
    (https://issues.rudder.io/issues/21130[#21130])

==== Generic methods

* Fixed: report_if_condition method does not support expressions in its input
    (https://issues.rudder.io/issues/21011[#21011])
* Fixed: multiple calls to file_from_template_jinja2 in audit fails
    (https://issues.rudder.io/issues/20913[#20913])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.0.0 (2022-01-26)

=== Changes

=== Bug fixes

==== Server components

* Fixed: rudder_synchronize fails to import technique
(https://issues.rudder.io/issues/20645[#20645])

==== Documentation

* Fixed: Agent logs section is missing in doc
(https://issues.rudder.io/issues/20627[#20627])
* Fixed:  Mark 7.0 as final - docs
(https://issues.rudder.io/issues/20626[#20626])
* Fixed: Some screenshots in documentation are too old
(https://issues.rudder.io/issues/20611[#20611])
* Fixed: Debian emits a warning if we follow the documentation way of adding the private repository
(https://issues.rudder.io/issues/20543[#20543])
* Fixed: API : URL ending with / are seen like /[empty string parameter]
(https://issues.rudder.io/issues/3881[#3881])

==== Plugins integration

* Fixed: rudder-pkg can not parse nightly version
(https://issues.rudder.io/issues/20649[#20649])

==== Web - UI & UX

* Fixed: Change the buttons color in the setup wizard
(https://issues.rudder.io/issues/20616[#20616])

==== Web - Technique editor

* Fixed: generic method doc in technique editor in 7.0 doesn't look great
(https://issues.rudder.io/issues/20608[#20608])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.0.0.rc3 (2022-01-20)

=== Changes

==== Documentation

* Add a note about recent  changes in upgrade notes
    (https://issues.rudder.io/issues/20507[#20507])
* Document how to automatically synchronize technique resources from an external repository
    (https://issues.rudder.io/issues/20495[#20495])
* Add upgrade notes for 7.0
    (https://issues.rudder.io/issues/20388[#20388])
* Display images in release notes
    (https://issues.rudder.io/issues/20464[#20464])
* Update screenshot in api doc
    (https://issues.rudder.io/issues/20586[#20586])
* Update api-doc tooling
    (https://issues.rudder.io/issues/20584[#20584])

==== Web - Technique editor

* Speed up technique editor
    (https://issues.rudder.io/issues/20552[#20552])

==== Web - Config management

* Disable rudderc compilation of technique editor technique
    (https://issues.rudder.io/issues/20529[#20529])
* Delay policy generation until rudder app is fully boot
    (https://issues.rudder.io/issues/20462[#20462])

==== Web - UI & UX

* Add a warning in plugin page if a version mismatches rudder patch one
    (https://issues.rudder.io/issues/20261[#20261])
* Add a warning in plugin page if a version mismatches rudder patch one
    (https://issues.rudder.io/issues/20261[#20261])
* Bring back recent changes to life.
    (https://issues.rudder.io/issues/20440[#20440])

==== CI

* Dockerize technique tests
    (https://issues.rudder.io/issues/20386[#20386])

==== Agent

* Allow rudder agent check to stop at any step
    (https://issues.rudder.io/issues/20569[#20569])

=== Bug fixes

==== Packaging

* Fixed: webapp preinst should run rudder agent check
    (https://issues.rudder.io/issues/20539[#20539])
* Fixed: webapp installation produces a warning about initial branch name
    (https://issues.rudder.io/issues/20537[#20537])
* Fixed: rudder-agent-postinst doesn't close file descriptors anymore
    (https://issues.rudder.io/issues/20522[#20522])
* Fixed: /etc/cron.d/rudder-agent is a conffile
    (https://issues.rudder.io/issues/20268[#20268])
* Fixed: Separate openldap cache between nightly and release builds - 6.2
    (https://issues.rudder.io/issues/20450[#20450])
* Fixed: Update openssl to 1.1.1m
    (https://issues.rudder.io/issues/20428[#20428])
* Fixed: rpm python API incompatible in python3
    (https://issues.rudder.io/issues/20602[#20602])

==== Agent

* Fixed: Improve agent-side messages when download is refused
    (https://issues.rudder.io/issues/20521[#20521])
* Fixed: when rudder agent check changes something it should resend an inventory
    (https://issues.rudder.io/issues/20538[#20538])

==== Documentation

* Fixed: Add a note about relay upgrade order
    (https://issues.rudder.io/issues/20505[#20505])
* Fixed: apt-key is deprecated
    (https://issues.rudder.io/issues/20518[#20518])
* Fixed: Add a complex example of node search API request
    (https://issues.rudder.io/issues/20577[#20577])
* Fixed: documentation of method schedule_ is broken
    (https://issues.rudder.io/issues/20605[#20605])

==== Web - Technique editor

* Fixed: Expand/Hide in technique editor tree not working
    (https://issues.rudder.io/issues/20492[#20492])
* Fixed: It's not possible to select a condition with the dropdownlist on technique editor in rudder 7
    (https://issues.rudder.io/issues/20420[#20420])
* Fixed: block still disapear in technique editor when we put a method in it
    (https://issues.rudder.io/issues/20551[#20551])
* Fixed: Add loading effect for technique editor tree 
    (https://issues.rudder.io/issues/20493[#20493])
* Fixed: The technique editor allows saving methods with missing parameters
    (https://issues.rudder.io/issues/20415[#20415])
* Fixed: Error message in technique editor doesn't help
    (https://issues.rudder.io/issues/20491[#20491])
* Fixed: Technique editor allows id with only case difference, do an error, but still save technique
    (https://issues.rudder.io/issues/20133[#20133])
* Fixed: when trying to put a generic method within a block, it can replace the whole block
    (https://issues.rudder.io/issues/20306[#20306])
* Fixed: Resources in drafts are not displayed and saved
    (https://issues.rudder.io/issues/20486[#20486])
* Fixed: When we move a technique in editor, resources are not moved
    (https://issues.rudder.io/issues/20445[#20445])
* Fixed: When we move a technique in editor, resources are not moved
    (https://issues.rudder.io/issues/20445[#20445])
* Fixed: Broken technique resources in drafts
    (https://issues.rudder.io/issues/20414[#20414])
* Fixed: Error when writing techniques via the technique editor
    (https://issues.rudder.io/issues/20437[#20437])

==== API

* Fixed: Missing api rights 
    (https://issues.rudder.io/issues/20609[#20609])
* Fixed: State is missing from node api
    (https://issues.rudder.io/issues/20582[#20582])

==== Architecture - Refactoring

* Fixed: Remove warning messages
    (https://issues.rudder.io/issues/20606[#20606])

==== Web - UI & UX

* Fixed: Loading effect on rules tree
    (https://issues.rudder.io/issues/20595[#20595])
* Fixed: Underlining of links is cut in firefox
    (https://issues.rudder.io/issues/20596[#20596])
* Fixed: Redesign the login page with the new graphic charter
    (https://issues.rudder.io/issues/20581[#20581])
* Fixed: Compliance of rules should not be rounded to the nearest hundredth
    (https://issues.rudder.io/issues/20573[#20573])
* Fixed: Compliance by nodes in the Rules page shows the node id rather than it's name
    (https://issues.rudder.io/issues/20490[#20490])
* Fixed: Sub categories have too many "|-" displaed in select box
    (https://issues.rudder.io/issues/20559[#20559])
* Fixed: Tables look weird when empty in Rules UI
    (https://issues.rudder.io/issues/20467[#20467])
* Fixed: In a directive the technique documentation button is not visibled enough
    (https://issues.rudder.io/issues/20436[#20436])
* Fixed: we can save a rule without a name
    (https://issues.rudder.io/issues/19789[#19789])
* Fixed: Missing rounding of rules compliance percentage
    (https://issues.rudder.io/issues/20532[#20532])
* Fixed: We can save a technique with a missing component name for a nested block
    (https://issues.rudder.io/issues/20497[#20497])
* Fixed: metrics are still present in wizard, and wizard doesn't end
    (https://issues.rudder.io/issues/20478[#20478])
* Fixed: Cancel button is missing when deleting a technique
    (https://issues.rudder.io/issues/20487[#20487])
* Fixed: Wrong technique name displayed in deletion message 
    (https://issues.rudder.io/issues/20488[#20488])
* Fixed: The left menu is under the menu bar's shadow
    (https://issues.rudder.io/issues/20030[#20030])
* Fixed: It's hard to know how to edit a block/method in editor
    (https://issues.rudder.io/issues/20344[#20344])
* Fixed: icons on login page are not centered
    (https://issues.rudder.io/issues/19887[#19887])
* Fixed: when we hit enter key on rule category creation,page is reloaded
    (https://issues.rudder.io/issues/20365[#20365])
* Fixed: buttons on rule creation page don't have the same width
    (https://issues.rudder.io/issues/20364[#20364])

==== Web - Config management

* Fixed: No na reporting generated by webapp
    (https://issues.rudder.io/issues/20591[#20591])
* Fixed: Missing rule Id in rule details
    (https://issues.rudder.io/issues/19876[#19876])
* Fixed: If a rule is in a category that no longer exists, it can't be accessed in rule tree
    (https://issues.rudder.io/issues/20095[#20095])
* Fixed: Sometimes the webapp fails to generate the reporting file of new techniques
    (https://issues.rudder.io/issues/20513[#20513])
* Fixed: error in webapp log at start, and group allPolicyServers not showing up in group tree
    (https://issues.rudder.io/issues/20479[#20479])
* Fixed: Missing special target in group selection for rules
    (https://issues.rudder.io/issues/20348[#20348])
* Fixed: Invalid attribute 'special:all_servers_with_role' (or special:all_nodes_without_role) for entry ruleTarget
    (https://issues.rudder.io/issues/20460[#20460])
* Fixed: Value 'focus:48137400-7f48-48bd-a888-9522167b5b81' is not a valid reporting composition rule
    (https://issues.rudder.io/issues/20459[#20459])

==== Web - Compliance & node report

* Fixed: Unexpected reports when using nested blocks
    (https://issues.rudder.io/issues/20540[#20540])
* Fixed: First node name is used for all nodes in rule compliance details "by node"
    (https://issues.rudder.io/issues/20585[#20585])
* Fixed: Compliance bar of a node with no policy applied is red / error 100%
    (https://issues.rudder.io/issues/20558[#20558])
* Fixed: compliance from API doesn't always adds up to 100%
    (https://issues.rudder.io/issues/20373[#20373])
* Fixed: Compliance issue in 7.0 because of invalid expected reports
    (https://issues.rudder.io/issues/20498[#20498])
* Fixed: error on system status tabs when there are missing reports
    (https://issues.rudder.io/issues/20474[#20474])
* Fixed: webapp doesn't start after upgrade from 6.2 to 7.0
    (https://issues.rudder.io/issues/20390[#20390])

==== Security

* Fixed: Update spring-core
    (https://issues.rudder.io/issues/20571[#20571])
* Fixed: Use a proper CSPRNG to generate API tokens
    (https://issues.rudder.io/issues/20512[#20512])

==== Relay server or API

* Fixed: It is impossible to read group properties with a read-only account
    (https://issues.rudder.io/issues/20567[#20567])
* Fixed: Don't insert partial runs as run logs
    (https://issues.rudder.io/issues/20446[#20446])

==== Performance and scalability

* Fixed: We are recreating ldap object while we could duplicate them, leading to suboptimal perf
    (https://issues.rudder.io/issues/20535[#20535])

==== Miscellaneous

* Fixed: Compliance api miss audit state
    (https://issues.rudder.io/issues/20531[#20531])

==== Language

* Fixed: generate_lib outputs a debug line
    (https://issues.rudder.io/issues/20471[#20471])

==== Techniques

* Fixed: Confusing log message in cron technique hook
    (https://issues.rudder.io/issues/20515[#20515])
* Fixed: deprecate techniques in 7.0
    (https://issues.rudder.io/issues/20277[#20277])

==== System techniques

* Fixed: Skipping inventory run when another one is already running should not throw an error
    (https://issues.rudder.io/issues/20511[#20511])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.0.0.rc2 (2021-12-17)

=== Changes

==== Documentation

* Add debian 11 server support to documentation
    (https://issues.rudder.io/issues/20379[#20379])
* Better documentation of the windows update technique
    (https://issues.rudder.io/issues/20360[#20360])

==== CI

* Discard old builds
    (https://issues.rudder.io/issues/20408[#20408])
* Test ncf in docker
    (https://issues.rudder.io/issues/20374[#20374])

==== Web - Technique editor

* Add a worst-case, weighted sum for block compliance mode
    (https://issues.rudder.io/issues/20342[#20342])
* Add a worst-case, weighted sum for block compliance mode
    (https://issues.rudder.io/issues/20342[#20342])

==== Relay server or API

* Add relayd man page build to Jenkinsfile
    (https://issues.rudder.io/issues/20327[#20327])

=== Bug fixes

==== Security

* Fixed: Do not display the jetty version number
    (https://issues.rudder.io/issues/19163[#19163])
* Fixed: Upgrade logback version for LOGBACK-1591 / JNDI
    (https://issues.rudder.io/issues/20421[#20421])

==== Packaging

* Fixed: rudder-webapp 6.2 on debian11 generate a dbgsym package
    (https://issues.rudder.io/issues/20376[#20376])
* Fixed: When upgrading from 6.2 -> 7.0 on centos8, old system technique are still present, and break policy generation
    (https://issues.rudder.io/issues/20356[#20356])
* Fixed: System techniques upgrade is broken
    (https://issues.rudder.io/issues/20337[#20337])
* Fixed: Database connection test is broken since the rules table has been removed
    (https://issues.rudder.io/issues/20335[#20335])
* Fixed: rudder-webapp on debian11 generate a dbgsym package
    (https://issues.rudder.io/issues/20319[#20319])
* Fixed: System technique migration fails on old server
    (https://issues.rudder.io/issues/20351[#20351])
* Fixed: Refactor apache configuration for easy separation between agent and web flows
    (https://issues.rudder.io/issues/20349[#20349])

==== Documentation

* Fixed: Clean rudder-packages README
    (https://issues.rudder.io/issues/20330[#20330])
* Fixed: 7.0 install documentation installs a 6.2 version
    (https://issues.rudder.io/issues/20402[#20402])
* Fixed: Improve windows patch management technique doc
    (https://issues.rudder.io/issues/20369[#20369])

==== Web - UI & UX

* Fixed: css of generation status is dubious in 7.0
    (https://issues.rudder.io/issues/20395[#20395])
* Fixed: Upgrade jquery to 3.6.0
    (https://issues.rudder.io/issues/20430[#20430])
* Fixed: Block and component compliance display in Rules page
    (https://issues.rudder.io/issues/20302[#20302])
* Fixed: Remove metrics section from wizard
    (https://issues.rudder.io/issues/20394[#20394])
* Fixed: User name invisible
    (https://issues.rudder.io/issues/20384[#20384])
* Fixed: Loading and first connection pages don't use new rudder 7.0 theme
    (https://issues.rudder.io/issues/20231[#20231])

==== Relay server or API

* Fixed: Query seems to be ignored for pendings nodes
    (https://issues.rudder.io/issues/20281[#20281])
* Fixed: Test that the distributed config files are valid
    (https://issues.rudder.io/issues/20416[#20416])

==== Plugins integration

* Fixed: Plugins upgrade broken in 7.0 rc
    (https://issues.rudder.io/issues/20385[#20385])

==== Architecture - Dependencies

* Fixed: Rudder build when skipping tests
    (https://issues.rudder.io/issues/20410[#20410])

==== Web - Technique editor

* Fixed: when we edit the content of a generic method in 7.0, there is no way to know which method it is
    (https://issues.rudder.io/issues/20308[#20308])

==== Web - Config management

* Fixed: Non system technique appears in "System status tab"
    (https://issues.rudder.io/issues/20383[#20383])
* Fixed: multiple save buttons on rule page
    (https://issues.rudder.io/issues/20286[#20286])

==== Performance and scalability

* Fixed: Improve performance of getUserAndSystemNodeStatusReports by exploring only once cache
    (https://issues.rudder.io/issues/20318[#20318])
* Fixed: Improve performance of getUserAndSystemNodeStatusReports by exploring only once cache
    (https://issues.rudder.io/issues/20318[#20318])
* Fixed: Method getByRulesCompliance used by API is highly inefficient
    (https://issues.rudder.io/issues/20310[#20310])
* Fixed: Method getByRulesCompliance used by API is highly inefficient
    (https://issues.rudder.io/issues/20310[#20310])
* Fixed: Method getByRulesCompliance used by API is highly inefficient
    (https://issues.rudder.io/issues/20310[#20310])
* Fixed: Method getByRulesCompliance used by API is highly inefficient
    (https://issues.rudder.io/issues/20310[#20310])

==== Miscellaneous

* Fixed: Mount elm tmp dir in tmpfs to avoid lock failure on concurrent builds
    (https://issues.rudder.io/issues/20361[#20361])

==== CI

* Fixed: Rudder-pkg tests timeout sometimes
    (https://issues.rudder.io/issues/20354[#20354])
* Fixed: Broken 7.0 tests due to missing user_id variable in Jenkinsfile
    (https://issues.rudder.io/issues/20339[#20339])
* Fixed: Only run compatibility tests during the night
    (https://issues.rudder.io/issues/20323[#20323])
* Fixed: Split test and build tasks in Jenkins file
    (https://issues.rudder.io/issues/20320[#20320])

==== System integration

* Fixed: gitgc is always run at start whatever its schedule is and run every 3~4 min
    (https://issues.rudder.io/issues/20350[#20350])
* Fixed: Bad logs for migration error when technique is missing
    (https://issues.rudder.io/issues/20336[#20336])

==== Architecture - Refactoring

* Fixed: Empty value for certificate should not kill rudder
    (https://issues.rudder.io/issues/20341[#20341])

==== API

* Fixed: Wrong deprecation information in technique
    (https://issues.rudder.io/issues/20333[#20333])

==== Web - Nodes & inventories

* Fixed: group page is not scrollable, so we can't see the full list of nodes in 7.0
    (https://issues.rudder.io/issues/20293[#20293])

==== System techniques

* Fixed: .pgpass file cannot use remote postgresql
    (https://issues.rudder.io/issues/19659[#19659])
* Fixed: unexpected report after upgrading Rudder from 6.2 to 7.0
    (https://issues.rudder.io/issues/20381[#20381])
* Fixed: rudder is restarted in first agent run after upgrade from 6.2 to 7.0
    (https://issues.rudder.io/issues/20382[#20382])
* Fixed: rsyslog.d/rudder.conf left after 7.0 upgrade
    (https://issues.rudder.io/issues/20340[#20340])

==== Agent

* Fixed: Don't use a passphrase anymore in agent check
    (https://issues.rudder.io/issues/20331[#20331])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.0.0.rc1 (2021-11-29)

=== Changes

==== Documentation

* Update supported platform list in documentation
    (https://issues.rudder.io/issues/20125[#20125])
* Document windows update technique
    (https://issues.rudder.io/issues/20265[#20265])
* Dockerify api-doc test, build and publication
    (https://issues.rudder.io/issues/20272[#20272])

==== Web - UI & UX

* Make the rows of the compliance tables foldable to show more levels of compliance in Rules UI
    (https://issues.rudder.io/issues/20236[#20236])
* Allow to customize in which menu plugins are set
    (https://issues.rudder.io/issues/20264[#20264])

==== System techniques

* It's not possible to make the agent listen on a specific port
    (https://issues.rudder.io/issues/20113[#20113])

=== Bug fixes

==== Packaging

* Fixed: Separate openldap cache between nightly and release builds
    (https://issues.rudder.io/issues/20315[#20315])
* Fixed: error in rudder-agent cron file in packaging
    (https://issues.rudder.io/issues/20267[#20267])

==== Web - UI & UX

* Fixed: wrong write for rule page 
    (https://issues.rudder.io/issues/20299[#20299])
* Fixed: Redirection does not work on rule page
    (https://issues.rudder.io/issues/20298[#20298])

==== Web - Nodes & inventories

* Fixed: by default, group condition should not be displayed
    (https://issues.rudder.io/issues/20297[#20297])
* Fixed: Alma Linux is detected as CentOS
    (https://issues.rudder.io/issues/20237[#20237])

==== CI

* Fixed: Add redirect to latest API doc version to Jenkinsfile
    (https://issues.rudder.io/issues/20291[#20291])
* Fixed: Language docs publication does not work
    (https://issues.rudder.io/issues/20285[#20285])
* Fixed: Missing elm 0.19.1 in 7.0 tests
    (https://issues.rudder.io/issues/20283[#20283])
* Fixed: Dockerify tests
    (https://issues.rudder.io/issues/20275[#20275])

==== System integration

* Fixed: Can't use rudder with openjdk17: cannot access class sun.net.util.IPAddressUtil
    (https://issues.rudder.io/issues/20289[#20289])

==== Miscellaneous

* Fixed: Move to a new Url Technique api so anyone can create technique like the editor through api
    (https://issues.rudder.io/issues/20242[#20242])
* Fixed: Rudder agent factory-reset don't regenerate inventory
    (https://issues.rudder.io/issues/20282[#20282])

==== Web - Config management

* Fixed: Error when creating a rule in 7.0
    (https://issues.rudder.io/issues/20278[#20278])
* Fixed: Rule editor does not use webapp context path value
    (https://issues.rudder.io/issues/19879[#19879])

==== Performance and scalability

* Fixed: spurious "connection_read(9): no connection!" in /var/log/rudder/ldap/slapd.log
    (https://issues.rudder.io/issues/19980[#19980])
* Fixed: dashboard only shows the compliance of the nodes that really answer when logging on the test platform in 7.0
    (https://issues.rudder.io/issues/20273[#20273])

==== Web - Technique editor

* Fixed: 404 error when opening a technique in the technique editor
    (https://issues.rudder.io/issues/20183[#20183])

==== Relay server or API

* Fixed: Vulnerability in tokio
    (https://issues.rudder.io/issues/20269[#20269])

==== Documentation

* Fixed: Missing documentation for relay to node demote API
    (https://issues.rudder.io/issues/20262[#20262])

==== Architecture - Internal libs

* Fixed: Add mock in test lib for secrets eventlogs 
    (https://issues.rudder.io/issues/20256[#20256])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

Rudder 7.0 is currently the next version of Rudder.


== Rudder 7.0.0.beta3 (2021-11-18)

=== Changes

==== Documentation

* Add support for Alma and Rocky Linux
    (https://issues.rudder.io/issues/20220[#20220])
* Document HTTP port change
    (https://issues.rudder.io/issues/20132[#20132])

==== Web - Config management

* Remove SKIPIDENTIFY system variable
    (https://issues.rudder.io/issues/19782[#19782])
* Don't historize names of nodes, rules & groups in the database
    (https://issues.rudder.io/issues/20229[#20229])
* Make consistant id+revision format accross rule, directive, techniques in API
    (https://issues.rudder.io/issues/20190[#20190])

==== Web - UI & UX

* Display Groups list in the 'Compliance by nodes' tab
    (https://issues.rudder.io/issues/20243[#20243])

==== Web - Technique editor

* Update OS conditions in the technique editor
    (https://issues.rudder.io/issues/20223[#20223])

==== Miscellaneous

* Missing data for Rule page
    (https://issues.rudder.io/issues/20127[#20127])

=== Bug fixes

==== Miscellaneous

* Fixed: There is no cfengine-systemd patch anymore thus making package build faild
    (https://issues.rudder.io/issues/20255[#20255])

==== System integration

* Fixed: Git warning about branch name in install logs
    (https://issues.rudder.io/issues/20232[#20232])

==== Packaging

* Fixed: upgrade jetty dependency
    (https://issues.rudder.io/issues/20222[#20222])
* Fixed: Upgrade to openldap 2.4.59 for rudder 7.0
    (https://issues.rudder.io/issues/20221[#20221])
* Fixed: some build generate _dbgsym packages
    (https://issues.rudder.io/issues/20193[#20193])
* Fixed: error in logs at install about policy-server.pem
    (https://issues.rudder.io/issues/19737[#19737])
* Fixed: error at upgrade of rudder to 7.0
    (https://issues.rudder.io/issues/20031[#20031])

==== Documentation

* Fixed: Documentation about collection access in jinja2 template is incorect
    (https://issues.rudder.io/issues/20234[#20234])
* Fixed: Document that HTTP port is not configurable with SELinux policies
    (https://issues.rudder.io/issues/20200[#20200])
* Fixed: Remove old logo from Rudder docs
    (https://issues.rudder.io/issues/20189[#20189])
* Fixed: Complete documentation on how to set up dev environment for 7.0
    (https://issues.rudder.io/issues/20195[#20195])

==== Performance and scalability

* Fixed: Do a `git gc` periodically
    (https://issues.rudder.io/issues/17767[#17767])
* Fixed: Improve compliance computation efficiency
    (https://issues.rudder.io/issues/20254[#20254])
* Fixed: improve compliance computation efficiency
    (https://issues.rudder.io/issues/20253[#20253])

==== Web - UI & UX

* Fixed: Improve compliance bars display in Rules UI
    (https://issues.rudder.io/issues/20197[#20197])
* Fixed: source map missing in 7.0
    (https://issues.rudder.io/issues/19935[#19935])
* Fixed: Fix a css issue in the Technique Editor tree
    (https://issues.rudder.io/issues/20214[#20214])
* Fixed: "Save changes" button on the policy mode form is broken.
    (https://issues.rudder.io/issues/20210[#20210])
* Fixed: Status displayed in the rules table is incorrect
    (https://issues.rudder.io/issues/20202[#20202])
* Fixed: Can't get over page "Getting Started"
    (https://issues.rudder.io/issues/20207[#20207])
* Fixed: Rule table scroll the whole page and not the rule table section when there is too much Rule
    (https://issues.rudder.io/issues/20201[#20201])
* Fixed: Display policy mode in Rule lists
    (https://issues.rudder.io/issues/20140[#20140])
* Fixed: Edit mode should be enabled by default when creating a new rule
    (https://issues.rudder.io/issues/20194[#20194])
* Fixed: When creating a rule, the Select Directives and Select Groups buttons do not work
    (https://issues.rudder.io/issues/20188[#20188])

==== Language

* Fixed: technique cannot be compile if name contains \\"x 
    (https://issues.rudder.io/issues/19888[#19888])
* Fixed: rudderc doesn't support multiline text
    (https://issues.rudder.io/issues/19900[#19900])

==== Web - Nodes & inventories

* Fixed: Rocky Linux is not recognized
    (https://issues.rudder.io/issues/20239[#20239])

==== Web - Technique editor

* Fixed: Technique draft should be deleted on save
    (https://issues.rudder.io/issues/20241[#20241])
* Fixed: it's not possible to reorder method in a block in technique editor
    (https://issues.rudder.io/issues/19954[#19954])
* Fixed: it's not possible to reorder method in a block in technique editor
    (https://issues.rudder.io/issues/19954[#19954])
* Fixed: Cannot save a technique with a block with reporting focused on one method
    (https://issues.rudder.io/issues/19769[#19769])

==== Plugins integration

* Fixed: when upgrading from 6.2 to 7.0 with the dsc plugin, webapp doesn't work
    (https://issues.rudder.io/issues/20204[#20204])

==== System techniques

* Fixed: /root/.pgpass and /opt/rudder/etc/rudder-web.properties have rudder_parameters.rudder_file_edit_header on Rudder 7.0
    (https://issues.rudder.io/issues/19929[#19929])

==== Generic methods

* Fixed: Document that "package_verify" is deprecated
    (https://issues.rudder.io/issues/20151[#20151])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

Rudder 7.0 is currently the next version of Rudder.
== Rudder 7.0.0.beta2 (2021-10-23)

=== Changes

==== Documentation

* Apply the new graphic charter to the documentation
    (https://issues.rudder.io/issues/20145[#20145])
* Update the doc for external database setup
    (https://issues.rudder.io/issues/19849[#19849])
* Use the new favicon for docs.rudder.io
    (https://issues.rudder.io/issues/19914[#19914])
* Make a nice index page for logos
    (https://issues.rudder.io/issues/20036[#20036])

==== System integration

* Add a feature switch for rudderc use during generation
    (https://issues.rudder.io/issues/20099[#20099])

==== Plugins integration

* Rudder package should try to install nightly plugins when Rudder is installed as a nightly version
    (https://issues.rudder.io/issues/20134[#20134])

==== Language

* rudder language generate_lib should use the existing ncf python library instead of implement itself the ncf methods parsing
    (https://issues.rudder.io/issues/20130[#20130])
* Support reporting logic metadata in language
    (https://issues.rudder.io/issues/19926[#19926])

==== Web - UI & UX

* Display the 'Compliance by Nodes' table
    (https://issues.rudder.io/issues/19880[#19880])
* Display directive tags in rule details
    (https://issues.rudder.io/issues/20111[#20111])
* Add filters on Groups in rule details
    (https://issues.rudder.io/issues/20024[#20024])

==== Miscellaneous

* Missing API and data for Rule page: special targets and node compliance
    (https://issues.rudder.io/issues/20112[#20112])

==== Web - Compliance & node report

* Add revision to rule 
    (https://issues.rudder.io/issues/20081[#20081])

==== Web - Technique editor

* Introduce technique drafts
    (https://issues.rudder.io/issues/19995[#19995])
* Make the technique editor more integrated and accessible
    (https://issues.rudder.io/issues/19985[#19985])

==== Web - Config management

* Improve rudder package output
    (https://issues.rudder.io/issues/19967[#19967])

==== Web - Nodes & inventories

* Remove all.log setting
    (https://issues.rudder.io/issues/19951[#19951])

==== Architecture - Refactoring

* Remove exception classes
    (https://issues.rudder.io/issues/19946[#19946])

==== Packaging

* Improve rust build times
    (https://issues.rudder.io/issues/19915[#19915])

==== CI

* Change the slack notification form the ncf tests
    (https://issues.rudder.io/issues/20143[#20143])

==== Generic methods

* We should be able to return an arbitrary report from the technique editor
    (https://issues.rudder.io/issues/20007[#20007])
* Improve parameter naming
    (https://issues.rudder.io/issues/18868[#18868])

=== Bug fixes

==== Packaging

* Fixed: ubuntu 13 doesn't support tlsv1.2 
    (https://issues.rudder.io/issues/20122[#20122])
* Fixed: Some package still download sources from rudder-project
    (https://issues.rudder.io/issues/20072[#20072])
* Fixed: File /tmp/rudder-plugins-upgrade is never cleaned during an upgrade, so running again rudder-upgrade causes trouble on plugins
    (https://issues.rudder.io/issues/20069[#20069])
* Fixed: old distro build fail to get source
    (https://issues.rudder.io/issues/20063[#20063])
* Fixed: techniques distributePolicy and server-roles are not removed from /var/rudder/configuration-repository/techniques/system when upgrading from 6.2 to 7.0
    (https://issues.rudder.io/issues/20060[#20060])
* Fixed: create migration script for database change in 7.0
    (https://issues.rudder.io/issues/20021[#20021])
* Fixed: SELinux error when upgrading from 6.2 to 7.0 on centos8
    (https://issues.rudder.io/issues/20035[#20035])
* Fixed: Agent key does not work for HTTP on migrations
    (https://issues.rudder.io/issues/20070[#20070])

==== Plugins integration

* Fixed: Rudder patch upgrade fails on plugin upgrade
    (https://issues.rudder.io/issues/20098[#20098])
* Fixed: Don't allow directory traversal through plugin URL
    (https://issues.rudder.io/issues/19969[#19969])

==== Web - Maintenance

* Fixed: don't show wizard after an upgrade
    (https://issues.rudder.io/issues/20094[#20094])
* Fixed: Error when unserializing ChangeRequest modifying Directives based on Techniques  that have been deleted
    (https://issues.rudder.io/issues/3783[#3783])

==== Documentation

* Fixed: Properly use lato in docs
    (https://issues.rudder.io/issues/20166[#20166])
* Fixed: Improve search bar visibility and appearance
    (https://issues.rudder.io/issues/20168[#20168])
* Fixed: Convert text to vector paths in the Rudder documentation logo
    (https://issues.rudder.io/issues/20167[#20167])
* Fixed: Fix lato usage in api docs
    (https://issues.rudder.io/issues/20171[#20171])
* Fixed: Use standard formatting for GPLv3
    (https://issues.rudder.io/issues/20061[#20061])

==== Web - Config management

* Fixed: cannot create or modify a rule
    (https://issues.rudder.io/issues/20186[#20186])
* Fixed: Add a way to load/unload rule revision in LDAP
    (https://issues.rudder.io/issues/20097[#20097])
* Fixed: Rules can't be accessed directly by url, all redirection broken
    (https://issues.rudder.io/issues/19872[#19872])
* Fixed: rules sorting does not work and they are not sorted by default
    (https://issues.rudder.io/issues/19871[#19871])
* Fixed: Typo in log "deletedbut"
    (https://issues.rudder.io/issues/19956[#19956])

==== Web - UI & UX

* Fixed: Hide Technical logs tab
    (https://issues.rudder.io/issues/20139[#20139])
* Fixed: Make the tree categories foldable
    (https://issues.rudder.io/issues/20164[#20164])
* Fixed: Display tags in rule lists
    (https://issues.rudder.io/issues/20149[#20149])
* Fixed: Display directive tags inside Compliance table In Rule details
    (https://issues.rudder.io/issues/20148[#20148])
* Fixed: Getting started setup fails to send metrics
    (https://issues.rudder.io/issues/20042[#20042])
* Fixed: Allow categories to be moved in the Rules tree
    (https://issues.rudder.io/issues/20116[#20116])
* Fixed: Improve user experience when selecting Directives and Groups
    (https://issues.rudder.io/issues/20090[#20090])
* Fixed: Add filter to the directive lists in Rule details
    (https://issues.rudder.io/issues/19987[#19987])
* Fixed: Make the search bar of the Rules list work
    (https://issues.rudder.io/issues/19971[#19971])
* Fixed: Display the name of the groups of a rule instead of their id
    (https://issues.rudder.io/issues/19981[#19981])
* Fixed: Tags of a rule cannot be deleted
    (https://issues.rudder.io/issues/19977[#19977])
* Fixed: launch set-up wizard on first connection
    (https://issues.rudder.io/issues/19898[#19898])
* Fixed: Display the name of the groups of a rule instead of their id
    (https://issues.rudder.io/issues/19981[#19981])

==== Web - Compliance & node report

* Fixed: Duplicated expected reports leads to bad compliance for technique with blocks
    (https://issues.rudder.io/issues/20124[#20124])
* Fixed: No reporting on a fresh 7.0~beta2 install
    (https://issues.rudder.io/issues/20104[#20104])
* Fixed: Technique editor blocks do not report as expected
    (https://issues.rudder.io/issues/19990[#19990])
* Fixed: When 2 changes are close in time,  expected report on the compliance page don't show the new config
    (https://issues.rudder.io/issues/19740[#19740])

==== Language

* Fixed: DSC policies are generated without the conditions
    (https://issues.rudder.io/issues/20083[#20083])
* Fixed: disable variable methods that don't work with language until we find a proper solution
    (https://issues.rudder.io/issues/20146[#20146])
* Fixed: Update generate lib to match new generic method parameters
    (https://issues.rudder.io/issues/20062[#20062])
* Fixed: Improve rudder language states documentation
    (https://issues.rudder.io/issues/20107[#20107])
* Fixed: Error on missing resource is not explicit
    (https://issues.rudder.io/issues/20103[#20103])
* Fixed: After migrating from 6.2 to 7.0, techniques that were totally valid may become invalid because of name collision in rudderc
    (https://issues.rudder.io/issues/20065[#20065])
* Fixed: disable reporting in the technique editor does nothing in rudderc
    (https://issues.rudder.io/issues/20015[#20015])
* Fixed: rudder-lang in 7.0 should use ncf 7.0
    (https://issues.rudder.io/issues/20041[#20041])

==== Relay server or API

* Fixed: Add an exception to relayd license to allow linking statically with openssl
    (https://issues.rudder.io/issues/20161[#20161])
* Fixed: Vulnerability in chrono
    (https://issues.rudder.io/issues/20160[#20160])
* Fixed: Vulnerability in time crate
    (https://issues.rudder.io/issues/20141[#20141])
* Fixed: Make HTTP keep alive configurable in relayd
    (https://issues.rudder.io/issues/20115[#20115])

==== Web - Technique editor

* Fixed: Technique draft can't be deleted
    (https://issues.rudder.io/issues/20137[#20137])
* Fixed: Migrate existing techniques to new naming of method  parameters
    (https://issues.rudder.io/issues/20019[#20019])
* Fixed: error in technique editor in rudder 7 when copying class result from within a block
    (https://issues.rudder.io/issues/19953[#19953])
* Fixed: cannot remove a method within a block
    (https://issues.rudder.io/issues/19959[#19959])

==== Web - Nodes & inventories

* Fixed: confusing search option for Node: "Policy Node ID"
    (https://issues.rudder.io/issues/20093[#20093])
* Fixed: Number of CPU is wrongly reported
    (https://issues.rudder.io/issues/19988[#19988])
* Fixed: Persist revisions of node inventories in fact-repository
    (https://issues.rudder.io/issues/19869[#19869])

==== API

* Fixed: Missing rights/role mapping for 7.0 endpoints
    (https://issues.rudder.io/issues/20051[#20051])

==== Performance and scalability

* Fixed: Store processes of an inventory after storing the inventory
    (https://issues.rudder.io/issues/20006[#20006])

==== Architecture - Internal libs

* Fixed: In CI, technique migration test sometimes throw an NPE
    (https://issues.rudder.io/issues/20009[#20009])

==== System integration

* Fixed: Need a migration script about changes in system directives, groups and rules
    (https://issues.rudder.io/issues/19650[#19650])
* Fixed: Remove useless bootchecks in rudder 7.0
    (https://issues.rudder.io/issues/19960[#19960])
* Fixed: Jetty is restarted 3 times during install
    (https://issues.rudder.io/issues/19852[#19852])

==== Architecture - Refactoring

* Fixed: Change format to call engines in properties 
    (https://issues.rudder.io/issues/19943[#19943])

==== Miscellaneous

* Fixed: Copy to clipboard button for user creation command in login page
    (https://issues.rudder.io/issues/19938[#19938])

==== Security

* Fixed: there aren't any authorizations on the rules pages
    (https://issues.rudder.io/issues/19775[#19775])

==== System techniques

* Fixed: Missing report for inventory
    (https://issues.rudder.io/issues/20154[#20154])
* Fixed: Broken reporting for webdav password when changing http port
    (https://issues.rudder.io/issues/20153[#20153])
* Fixed: Homogenize suse classes in system techniques
    (https://issues.rudder.io/issues/20155[#20155])
* Fixed: boostrap bundle should not be present on relays
    (https://issues.rudder.io/issues/20136[#20136])
* Fixed: Apache is not reloaded when the generated /var/rudder/lib/ssl/nodescerts.pem changes
    (https://issues.rudder.io/issues/20096[#20096])
* Fixed: slow policy generation in Rudder 7.0
    (https://issues.rudder.io/issues/19771[#19771])

==== Techniques

* Fixed: sshKeyDistribution doesn't correctly reports on missing home folder
    (https://issues.rudder.io/issues/19944[#19944])

==== Agent

* Fixed: rudder agent info should display port information
    (https://issues.rudder.io/issues/20158[#20158])

==== Server components

* Fixed: grep error in install logs
    (https://issues.rudder.io/issues/20150[#20150])

==== Generic methods

* Fixed: sharedfile methods don't have consistent class parameter
    (https://issues.rudder.io/issues/20126[#20126])
* Fixed: Pass the zypper_pattern test in staging
    (https://issues.rudder.io/issues/20108[#20108])
* Fixed: Rename report_if to report_if_condition
    (https://issues.rudder.io/issues/20038[#20038])
* Fixed: generic method parameter name must not change between 6.2 and 7.0
    (https://issues.rudder.io/issues/20017[#20017])
* Fixed: Fix augeas methods documentation
    (https://issues.rudder.io/issues/19883[#19883])
* Fixed: testinfra based tests should pass via the python executable and not py.test
    (https://issues.rudder.io/issues/20001[#20001])
* Fixed: error in file_key_value_present_in_ini_section
    (https://issues.rudder.io/issues/19992[#19992])
* Fixed: Strict mode of file_key_value_present_option does not introduce unwanted escpaing characters
    (https://issues.rudder.io/issues/19908[#19908])

==== CI

* Fixed: Remove ubuntu20 from the Jenkinsfile test since thehost is unstable atm
    (https://issues.rudder.io/issues/20056[#20056])
* Fixed: Cover all supported server OS in the PR automated tests.
    (https://issues.rudder.io/issues/19979[#19979])
* Fixed: Add ncf tests to the repo Jenkinsfile
    (https://issues.rudder.io/issues/19970[#19970])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


== Rudder 7.0.0.beta1 (2021-09-08)

=== Changes

==== Packaging

* Package db initialisation script with webapp
    (https://issues.rudder.io/issues/19845[#19845])
* Remove rudder-init.sh link
    (https://issues.rudder.io/issues/19847[#19847])
* Remove check-rudder-agent
    (https://issues.rudder.io/issues/19811[#19811])
* Remove slapd pre-systemd migration logic
    (https://issues.rudder.io/issues/19754[#19754])
* Remove useless log messages from packages scripts
    (https://issues.rudder.io/issues/19749[#19749])
* Harden LDAP hardening compiler options
    (https://issues.rudder.io/issues/19647[#19647])
* CFEngine 3.18 LTS on 7.0
    (https://issues.rudder.io/issues/19483[#19483])
* Add debian 11 support
    (https://issues.rudder.io/issues/19332[#19332])
* Remove C client build
    (https://issues.rudder.io/issues/19289[#19289])
* Remove unused relay dependencies
    (https://issues.rudder.io/issues/19106[#19106])
* Add cross compile option to agent build
    (https://issues.rudder.io/issues/19098[#19098])
* Add rudder-api-client as a dependency on rudder server
    (https://issues.rudder.io/issues/19060[#19060])
* Package network client on Unix agent
    (https://issues.rudder.io/issues/18974[#18974])
* Embed rudder version into packages
    (https://issues.rudder.io/issues/18932[#18932])
* Remove upgrade path from 5.0 and before
    (https://issues.rudder.io/issues/18917[#18917])
* Remove rsyslog dependency from 7.0
    (https://issues.rudder.io/issues/18144[#18144])
* Embed augeas in the agent 7.0 and later
    (https://issues.rudder.io/issues/18615[#18615])
* Require at least postgresql 9.6 in 7.0
    (https://issues.rudder.io/issues/18145[#18145])
* Makefile should fail if no rudder version is provided
    (https://issues.rudder.io/issues/18007[#18007])
* Use rpm %{make} instead of make
    (https://issues.rudder.io/issues/17984[#17984])
* Create a configure to make the agent package
    (https://issues.rudder.io/issues/17941[#17941])
* rudder package makefile should not install things on the system
    (https://issues.rudder.io/issues/17291[#17291])
* Move SELinux policy application into postinst script
    (https://issues.rudder.io/issues/19746[#19746])
* Redirect everything to https
    (https://issues.rudder.io/issues/19733[#19733])
* Update elm to 0.19.1
    (https://issues.rudder.io/issues/19658[#19658])
* Update Rust to 1.54.0
    (https://issues.rudder.io/issues/19626[#19626])
* Use Rust 1.51.0
    (https://issues.rudder.io/issues/19080[#19080])
* Add windows support to http client build
    (https://issues.rudder.io/issues/19046[#19046])
* Build client everywhere
    (https://issues.rudder.io/issues/19007[#19007])
* update rust to stable (1.47)
    (https://issues.rudder.io/issues/18455[#18455])

==== System integration

* Graceful restart should not wait for 10s
    (https://issues.rudder.io/issues/19035[#19035])
* Remove server roles in webapp and add support for remote postgres
    (https://issues.rudder.io/issues/19625[#19625])

==== Security

* Improve hardening flags for our C dependencies
    (https://issues.rudder.io/issues/13812[#13812])
* Force TLS 1.2+ in cf-serverd config
    (https://issues.rudder.io/issues/19780[#19780])

==== Documentation

* Prepare doc for 7.0
    (https://issues.rudder.io/issues/19842[#19842])
* Add a link to rudder-lang doc in reference manual
    (https://issues.rudder.io/issues/18992[#18992])
* Add lato font to the docs
    (https://issues.rudder.io/issues/19796[#19796])
* Make 7.0 doc build properly
    (https://issues.rudder.io/issues/19791[#19791])
* Add new rudder agent output to release notes
    (https://issues.rudder.io/issues/19475[#19475])
* Update build documentation for 7.0
    (https://issues.rudder.io/issues/19347[#19347])
* Add a rudder-by-example for post-provisionning reboot
    (https://issues.rudder.io/issues/18074[#18074])
* Build 6.2 embedded doc
    (https://issues.rudder.io/issues/17962[#17962])
* Update doc for new versioning policy
    (https://issues.rudder.io/issues/17147[#17147])
* Rename master branch doc to 6.2
    (https://issues.rudder.io/issues/17210[#17210])
* New logo for 7.0
    (https://issues.rudder.io/issues/19837[#19837])
* API documentation for secret variable feature
    (https://issues.rudder.io/issues/19730[#19730])
* New style for language doc
    (https://issues.rudder.io/issues/19805[#19805])
* New style for API docs
    (https://issues.rudder.io/issues/19794[#19794])
* 7.0 has API version 14
    (https://issues.rudder.io/issues/19793[#19793])
* Add typos check to CI config
    (https://issues.rudder.io/issues/19328[#19328])
* Add an arch doc for certificate changes in 7.0
    (https://issues.rudder.io/issues/19126[#19126])
* Add rudder-lang publication to Jenkinsfile
    (https://issues.rudder.io/issues/19195[#19195])

==== Web - UI & UX

* Display number of techniques in the editor
    (https://issues.rudder.io/issues/19913[#19913])
* Update the favicon with the new logo
    (https://issues.rudder.io/issues/19838[#19838])
* Replace the main colours of the interface with those of the new graphic charter
    (https://issues.rudder.io/issues/19809[#19809])
* Update Rules UI
    (https://issues.rudder.io/issues/18264[#18264])
* Make an onboarding wizard in Elm
    (https://issues.rudder.io/issues/18853[#18853])
* Port technique editor in elm
    (https://issues.rudder.io/issues/18953[#18953])
* Upgrade js dependencies to latest version
    (https://issues.rudder.io/issues/18720[#18720])

==== Plugins integration

* Secrets variables event log
    (https://issues.rudder.io/issues/19646[#19646])
* Make rudder package command use version files
    (https://issues.rudder.io/issues/19476[#19476])
* Adapt rudder package to support new versionning scheme
    (https://issues.rudder.io/issues/18557[#18557])

==== Relay server or API

* Improve relayd compilation time by 30-40%
    (https://issues.rudder.io/issues/19834[#19834])
* nom 7.0
    (https://issues.rudder.io/issues/19832[#19832])
* Warn in check config when relayd has an insecure configuration
    (https://issues.rudder.io/issues/19784[#19784])
* Store hashes as bytes
    (https://issues.rudder.io/issues/19528[#19528])
* Update relayd to tokio 1.0
    (https://issues.rudder.io/issues/18818[#18818])
* Replace stats API by a prometheus endpoint
    (https://issues.rudder.io/issues/18781[#18781])
* Update relayd to tokio 0.2
    (https://issues.rudder.io/issues/16477[#16477])

==== Web - Maintenance

* Update certificate validation setting for 7.0
    (https://issues.rudder.io/issues/19652[#19652])

==== Architecture - Dependencies

* Update all java dependencies to latests version for Rudder 7.0
    (https://issues.rudder.io/issues/19612[#19612])
* Upgrade to ZIO 1.0.1
    (https://issues.rudder.io/issues/18149[#18149])

==== Web - Config management

* Add a way to disable/enable reporting of a method in technique editor
    (https://issues.rudder.io/issues/19558[#19558])
* Be able to group reporting and methods so that we have clearer techniques and a better reporting
    (https://issues.rudder.io/issues/19323[#19323])
* Move allowed network data to settings 
    (https://issues.rudder.io/issues/18730[#18730])
* Use rudderc to compile technique from the editor instead of rudder logic
    (https://issues.rudder.io/issues/19061[#19061])
* Add HTTPS_POLICY_DISTRIBUTION_PORT system variable 
    (https://issues.rudder.io/issues/19259[#19259])
* Directly generate policies with correct rights
    (https://issues.rudder.io/issues/18375[#18375])

==== Language

* Fix language documentation
    (https://issues.rudder.io/issues/19472[#19472])
* Add a lint option to rudderc
    (https://issues.rudder.io/issues/19471[#19471])
* Rename rudder language and extension
    (https://issues.rudder.io/issues/19468[#19468])
* Enable language tests
    (https://issues.rudder.io/issues/19207[#19207])
* replace library metadata by is_dependency based on cli parameters
    (https://issues.rudder.io/issues/19048[#19048])
* add a metadata to generated lib to link deprecated gms to rebranded ones
    (https://issues.rudder.io/issues/18782[#18782])
* DSC: implement diff checker and fix generator
    (https://issues.rudder.io/issues/18566[#18566])
* handle resources that do not have particular state
    (https://issues.rudder.io/issues/18670[#18670])
* impl exception for condition resource conditions
    (https://issues.rudder.io/issues/18450[#18450])
* update backtrace with better performance in parser
    (https://issues.rudder.io/issues/18484[#18484])
* add backtrace to parser
    (https://issues.rudder.io/issues/18478[#18478])
* upgrade testing loop to match new actions and dsc integration
    (https://issues.rudder.io/issues/18300[#18300])
* refactoring DSC generator
    (https://issues.rudder.io/issues/18119[#18119])
* internally use a more secured version type for techniques version
    (https://issues.rudder.io/issues/18275[#18275])
* Split Number in Integer and Float
    (https://issues.rudder.io/issues/18138[#18138])
* command line rework
    (https://issues.rudder.io/issues/18168[#18168])
* Add tests to ir
    (https://issues.rudder.io/issues/18161[#18161])
* Rename ast to IR ans split it
    (https://issues.rudder.io/issues/18152[#18152])
* Implement resource level variables
    (https://issues.rudder.io/issues/18136[#18136])
* Implement case within variable declaration
    (https://issues.rudder.io/issues/18105[#18105])
* Order states in rl doc
    (https://issues.rudder.io/issues/18135[#18135])
* Improve stdlib doc generation
    (https://issues.rudder.io/issues/18129[#18129])
* cargo fmt
    (https://issues.rudder.io/issues/18121[#18121])
* Technique from AST
    (https://issues.rudder.io/issues/18096[#18096])
* remove cf-monitord variables
    (https://issues.rudder.io/issues/18116[#18116])
* update json tests and doc to match new format 
    (https://issues.rudder.io/issues/18095[#18095])
* impl serialized Technique struct
    (https://issues.rudder.io/issues/18067[#18067])
* Generate documentation for the stdlib
    (https://issues.rudder.io/issues/18088[#18088])
* move toml data into rudderlang stdlib
    (https://issues.rudder.io/issues/18081[#18081])
* Switch rudder-lang metadata format to toml
    (https://issues.rudder.io/issues/18075[#18075])
* Minor rudder-lang doc fixup
    (https://issues.rudder.io/issues/18071[#18071])
* Parse log_* keywords
    (https://issues.rudder.io/issues/18069[#18069])
* Add source information in enum expression
    (https://issues.rudder.io/issues/18068[#18068])
* Add proper generation for log and fail methods in CFEngine
    (https://issues.rudder.io/issues/18066[#18066])
* add a backtrace option for error handling
    (https://issues.rudder.io/issues/17994[#17994])
* Fix warnings and update dependencies
    (https://issues.rudder.io/issues/18064[#18064])
* Display rudder-lang source in cfengine comments
    (https://issues.rudder.io/issues/18063[#18063])
* Add a source context to statements
    (https://issues.rudder.io/issues/18062[#18062])
* Add na reporting to CFEngine generator
    (https://issues.rudder.io/issues/17955[#17955])
* Switch to nom_locate 2
    (https://issues.rudder.io/issues/18051[#18051])
* tests clean 2
    (https://issues.rudder.io/issues/18047[#18047])
* make use of conditional and flow statements for dsc
    (https://issues.rudder.io/issues/17904[#17904])
* clean tests
    (https://issues.rudder.io/issues/18042[#18042])
* differenciate classic and dsc generic methods
    (https://issues.rudder.io/issues/17821[#17821])
* differenciate classic and dsc generic methods
    (https://issues.rudder.io/issues/17821[#17821])
* Improve CFEngine code generation
    (https://issues.rudder.io/issues/17925[#17925])
* Improve CFEngine code generation
    (https://issues.rudder.io/issues/17925[#17925])
* dsc integration
    (https://issues.rudder.io/issues/17585[#17585])
* fix fmt and warnings
    (https://issues.rudder.io/issues/17796[#17796])

==== API

* Directive  tree API
    (https://issues.rudder.io/issues/19440[#19440])
* Remove unused API setting  use_reverse_dns
    (https://issues.rudder.io/issues/19236[#19236])

==== Architecture - Refactoring

* Test zio-json in place of lift-json
    (https://issues.rudder.io/issues/18879[#18879])

==== System techniques

* Remove CFEngine enterprise specific policies
    (https://issues.rudder.io/issues/19827[#19827])
* Only reload relayd when a restart is not needed
    (https://issues.rudder.io/issues/19704[#19704])
* Force TLS 1.2 in all CFEngine communication
    (https://issues.rudder.io/issues/19634[#19634])
* Remove automatic roles management
    (https://issues.rudder.io/issues/19541[#19541])
* Use agent certificate in place of rudder.crt
    (https://issues.rudder.io/issues/19496[#19496])
* Call common client to speak http with the server
    (https://issues.rudder.io/issues/19179[#19179])
* Remove most absolute hardcoded path in the bundle common g
    (https://issues.rudder.io/issues/19050[#19050])
* homogenize class parameters names and descriptions for each resource
    (https://issues.rudder.io/issues/18439[#18439])

==== Techniques

* Read nodecerts.pem on simple relayd
    (https://issues.rudder.io/issues/19681[#19681])

==== Miscellaneous

* Refactor the system techniques by component
    (https://issues.rudder.io/issues/19037[#19037])

==== Agent

* Improve agent commands output
    (https://issues.rudder.io/issues/19778[#19778])
* Add certificate pinning information to rudder agent info output
    (https://issues.rudder.io/issues/19623[#19623])
* Add proxy and port change support to rudder agent
    (https://issues.rudder.io/issues/19205[#19205])
* Add proxy and port configuration to https client
    (https://issues.rudder.io/issues/19515[#19515])
* Rudder agent log and history are missing options
    (https://issues.rudder.io/issues/19423[#19423])
* Add rudder http client to rudder agent
    (https://issues.rudder.io/issues/19178[#19178])
* Use embedded version file in rudder agent version
    (https://issues.rudder.io/issues/19155[#19155])
* Add a CN to our agent certificate
    (https://issues.rudder.io/issues/18808[#18808])

==== Generic methods

* Sync masterfiles with 3.18.0 upstream
    (https://issues.rudder.io/issues/19484[#19484])

=== Bug fixes

==== Agent

* Fixed: Error in agent about empty file backup
    (https://issues.rudder.io/issues/19830[#19830])
* Fixed: rudder-agent-postinst fails in 7.0 while closing fd
    (https://issues.rudder.io/issues/19429[#19429])
* Fixed: run inventory should not include /etc/profile
    (https://issues.rudder.io/issues/18026[#18026])
* Fixed: rudder packages refuses to install -SNAPSHOT plugins
    (https://issues.rudder.io/issues/19690[#19690])
* Fixed: Client fails to validate certs on some systems
    (https://issues.rudder.io/issues/19101[#19101])
* Fixed: Add tests for Rudder client
    (https://issues.rudder.io/issues/18998[#18998])
* Fixed: Implement missing calls in network client
    (https://issues.rudder.io/issues/18976[#18976])
* Fixed: Add a curl/openssl wrapper for sending file to policy server without validating host
    (https://issues.rudder.io/issues/18844[#18844])
* Fixed: rudder-agent check sleep and process pile-up
    (https://issues.rudder.io/issues/16859[#16859])
* Fixed: Stop using removed system API
    (https://issues.rudder.io/issues/19825[#19825])
* Fixed: server key reste should also remove HTTP pin
    (https://issues.rudder.io/issues/19783[#19783])
* Fixed: Wrong variable name for server key hash
    (https://issues.rudder.io/issues/19619[#19619])
* Fixed: Inventory fails because rudder-client fails because it needs /opt/rudder/etc/agent.conf
    (https://issues.rudder.io/issues/19583[#19583])
* Fixed: /opt/rudder/share/lib/common.sh fails when the api-token file does not exist
    (https://issues.rudder.io/issues/19563[#19563])

==== Packaging

* Fixed: Remove rudder-root-rename from webapp package
    (https://issues.rudder.io/issues/19812[#19812])
* Fixed: default cron contains a mustache variable
    (https://issues.rudder.io/issues/19668[#19668])
* Fixed: Add /var/rudder/lib/ssl to agent package
    (https://issues.rudder.io/issues/19638[#19638])
* Fixed: webapp package depends on rust
    (https://issues.rudder.io/issues/19393[#19393])
* Fixed: rsync is a build dependency
    (https://issues.rudder.io/issues/19387[#19387])
* Fixed: Remove build of tomlc99
    (https://issues.rudder.io/issues/19373[#19373])
* Fixed: rpm-build is a build dependency on sles 12
    (https://issues.rudder.io/issues/19325[#19325])
* Fixed: Fusion rudder agent certificate patch fails on windows
    (https://issues.rudder.io/issues/19309[#19309])
* Fixed: Rudder 7.0 fails to build when not run from build-task script
    (https://issues.rudder.io/issues/19291[#19291])
* Fixed: embedded version file is not complete
    (https://issues.rudder.io/issues/19154[#19154])
* Fixed: versions file doesn't contain any commit
    (https://issues.rudder.io/issues/19055[#19055])
* Fixed: init script present on systemd systems
    (https://issues.rudder.io/issues/19054[#19054])
* Fixed: rpmvercmp is missing in 7.0 package
    (https://issues.rudder.io/issues/19053[#19053])
* Fixed: Wrong dependency on augeas
    (https://issues.rudder.io/issues/19052[#19052])
* Fixed: Rudder 7.0 fails to build
    (https://issues.rudder.io/issues/19002[#19002])
* Fixed: %make macro doesn't exist in rpmbuild
    (https://issues.rudder.io/issues/18996[#18996])
* Fixed: Regenerate Makefile for new dependency
    (https://issues.rudder.io/issues/18949[#18949])
* Fixed: create migration script to remove index on keyvalue
    (https://issues.rudder.io/issues/18111[#18111])
* Fixed: syntax error in solaris package script for 6.2
    (https://issues.rudder.io/issues/18005[#18005])
* Fixed: Update openssl embedded in relayd to 1.1.1l
    (https://issues.rudder.io/issues/19856[#19856])
* Fixed: Refactor apache configs
    (https://issues.rudder.io/issues/19821[#19821])
* Fixed: Missing changes in SELinux configuration
    (https://issues.rudder.io/issues/19736[#19736])
* Fixed: Missing nodescerts.pem during postinst
    (https://issues.rudder.io/issues/19710[#19710])
* Fixed: warning when upgrading from 7.0 nightly to 7.0 nightly
    (https://issues.rudder.io/issues/19649[#19649])
* Fixed: Fix certificate configuration for httpd
    (https://issues.rudder.io/issues/19504[#19504])
* Fixed: Missing folder exclusion in shell tests
    (https://issues.rudder.io/issues/19265[#19265])
* Fixed: Do not pass xFLAGS as environment
    (https://issues.rudder.io/issues/19012[#19012])

==== System integration

* Fixed: Fusion inventory cannot read text files that contain BOM 
    (https://issues.rudder.io/issues/19315[#19315])
* Fixed: Missing default value for HTTPS port
    (https://issues.rudder.io/issues/19416[#19416])
* Fixed: Warning: Nashorn engine is planned to be removed from a future JDK release 
    (https://issues.rudder.io/issues/14753[#14753])
* Fixed: Warning: Nashorn engine is planned to be removed from a future JDK release 
    (https://issues.rudder.io/issues/14753[#14753])
* Fixed: rudder agent run does not actually send the inventory
    (https://issues.rudder.io/issues/19594[#19594])

==== Documentation

* Fixed: Error when building dev site
    (https://issues.rudder.io/issues/18373[#18373])
* Fixed: Rudderify doc rudder-lang doc theme
    (https://issues.rudder.io/issues/18991[#18991])
* Fixed: Symlink to rudder-api-client is not documented to use rtf
    (https://issues.rudder.io/issues/18947[#18947])
* Fixed: Fix doc title level
    (https://issues.rudder.io/issues/19473[#19473])

==== Miscellaneous

* Fixed: wrong option name in rudder package command
    (https://issues.rudder.io/issues/19923[#19923])
* Fixed: Filter on generic methods name should not be case sensitive
    (https://issues.rudder.io/issues/19565[#19565])
* Fixed: Specify relayd as user agent
    (https://issues.rudder.io/issues/19232[#19232])

==== Web - UI & UX

* Fixed: Saving groups in the rules UI is broken
    (https://issues.rudder.io/issues/19881[#19881])
* Fixed: Refresh the list of Rules after saving
    (https://issues.rudder.io/issues/19743[#19743])
* Fixed: there is no indication on column sorting in nodes table in rudder 7.0
    (https://issues.rudder.io/issues/19666[#19666])
* Fixed: Display of configuration of nodes table column is not great in 7.0
    (https://issues.rudder.io/issues/19665[#19665])
* Fixed: typo in onboarding program for metrics
    (https://issues.rudder.io/issues/19682[#19682])
* Fixed: JS error while initializing Elm app since we upgrade elm to 0.19.1
    (https://issues.rudder.io/issues/19662[#19662])
* Fixed: Broken group properties
    (https://issues.rudder.io/issues/19654[#19654])
* Fixed: Multiples UI error on 7.0
    (https://issues.rudder.io/issues/19562[#19562])
* Fixed: all small icons are broken in 7.0
    (https://issues.rudder.io/issues/19620[#19620])
* Fixed: Rename settings menu to administration
    (https://issues.rudder.io/issues/19617[#19617])
* Fixed: Display of DataTables' pagination buttons  is broken.
    (https://issues.rudder.io/issues/18881[#18881])
* Fixed: Upgrade font awesome to latest version 
    (https://issues.rudder.io/issues/18728[#18728])
* Fixed: Group property inherited tooltip is not visible
    (https://issues.rudder.io/issues/17546[#17546])

==== Web - Technique editor

* Fixed: disable reporting option is not saved in technique editor
    (https://issues.rudder.io/issues/19719[#19719])
* Fixed: Technique editor allows empty technique name
    (https://issues.rudder.io/issues/19865[#19865])
* Fixed: documentation of generic methods is broken in 7.0 - and t cannot be selected / copy/pasted
    (https://issues.rudder.io/issues/19717[#19717])
* Fixed: minor & major versions for conditions don't work in technique editor in rudder 7
    (https://issues.rudder.io/issues/19718[#19718])
* Fixed: On technique editor, the Categories section doesnt look great
    (https://issues.rudder.io/issues/19714[#19714])
* Fixed: The information pointer on generic method doesn't display information
    (https://issues.rudder.io/issues/19819[#19819])
* Fixed: generic method group link has the wrong cursor
    (https://issues.rudder.io/issues/19818[#19818])
* Fixed: result condition are canonifying variables
    (https://issues.rudder.io/issues/19776[#19776])
* Fixed: Saving a technique fails when a resource was unchanged (should be untouched)
    (https://issues.rudder.io/issues/19802[#19802])
* Fixed: copy to clipboard button of resource in Technique editor doesn't copy to clipboard
    (https://issues.rudder.io/issues/19801[#19801])
* Fixed: result condition in the technique editor are wrong
    (https://issues.rudder.io/issues/19773[#19773])
* Fixed: generated bundle name of technique is invalid, as it is postfixed by _technique
    (https://issues.rudder.io/issues/19739[#19739])
* Fixed: Add timing logger to technique editor
    (https://issues.rudder.io/issues/19748[#19748])
* Fixed: technique editor  uses .rl extension instead of .rd
    (https://issues.rudder.io/issues/19697[#19697])
* Fixed: technique editor uses too many quotes to calls rudderc
    (https://issues.rudder.io/issues/19694[#19694])
* Fixed: "reporting based on" is duplicated on component
    (https://issues.rudder.io/issues/19605[#19605])
* Fixed: error getting techniques when coming back on technique page
    (https://issues.rudder.io/issues/19600[#19600])

==== Plugins integration

* Fixed: Rudder package should accept plugins with same minor version, not just patch version
    (https://issues.rudder.io/issues/19868[#19868])
* Fixed: rudder-pkg version parsing does not support version numbers containing a git hash
    (https://issues.rudder.io/issues/19413[#19413])
* Fixed: rudder package should now look for rpkg.index in the dedicated plugin repository instead of its root
    (https://issues.rudder.io/issues/18829[#18829])

==== Web - Config management

* Fixed: When we delete a directive, it's not removed from the rules
    (https://issues.rudder.io/issues/19786[#19786])
* Fixed: importing directives from rudder 6.2 breaks everything in 7.0
    (https://issues.rudder.io/issues/19892[#19892])
* Fixed: Saving a rule with deleted directives/groups does not correct it
    (https://issues.rudder.io/issues/19873[#19873])
* Fixed: When we save a rule, the directives are not saved
    (https://issues.rudder.io/issues/19744[#19744])
* Fixed: node properties writen in policies is invalid
    (https://issues.rudder.io/issues/19723[#19723])
* Fixed: versionning is too technical on the directive tree
    (https://issues.rudder.io/issues/19609[#19609])
* Fixed: Broken pom after merge
    (https://issues.rudder.io/issues/19180[#19180])
* Fixed: Add empty technique parameter in technique editor (7.0)
    (https://issues.rudder.io/issues/19123[#19123])

==== Performance and scalability

* Fixed: debug_timing debug log is polluted by cache last run hashmap
    (https://issues.rudder.io/issues/19894[#19894])

==== Language

* Fixed: rudderc fails to read blocks in techniques
    (https://issues.rudder.io/issues/19858[#19858])
* Fixed: language cannot use resource parameter
    (https://issues.rudder.io/issues/19855[#19855])
* Fixed: cli tests are ignored in rudderc
    (https://issues.rudder.io/issues/19725[#19725])
* Fixed: rudderc adds .rd to every files it generates
    (https://issues.rudder.io/issues/19724[#19724])
* Fixed: rudderc cannot save technique editor data
    (https://issues.rudder.io/issues/19695[#19695])
* Fixed: language tests fail
    (https://issues.rudder.io/issues/19692[#19692])
* Fixed: Language tests ignore method unique id
    (https://issues.rudder.io/issues/19691[#19691])
* Fixed: Missing lint section in rudderc config file
    (https://issues.rudder.io/issues/19588[#19588])
* Fixed: cis technique compiler fixes
    (https://issues.rudder.io/issues/19009[#19009])
* Fixed: Properly locate entity errors if the source has metadatas attached
    (https://issues.rudder.io/issues/18669[#18669])
* Fixed: ensure state definitions include specific metadatas
    (https://issues.rudder.io/issues/19043[#19043])
* Fixed: ensure state definitions include specific metadatas
    (https://issues.rudder.io/issues/19043[#19043])
* Fixed: Rudder-lang doc misses a mkdir
    (https://issues.rudder.io/issues/18990[#18990])
* Fixed: condition_from fix
    (https://issues.rudder.io/issues/18895[#18895])
* Fixed: handle external variables in conditions
    (https://issues.rudder.io/issues/18827[#18827])
* Fixed: accept enum aliases when checking CF diff
    (https://issues.rudder.io/issues/18816[#18816])
* Fixed: lib generation does not handle gm parameters order properly
    (https://issues.rudder.io/issues/18866[#18866])
* Fixed: fix invalid escape in parameter strings
    (https://issues.rudder.io/issues/18800[#18800])
* Fixed: addd sled to rudderlang supported os list
    (https://issues.rudder.io/issues/18799[#18799])
* Fixed: fix doc generation
    (https://issues.rudder.io/issues/18798[#18798])
* Fixed: generation should work whatever order gm parameters are received
    (https://issues.rudder.io/issues/18696[#18696])
* Fixed: fix makefile
    (https://issues.rudder.io/issues/18649[#18649])
* Fixed: fix ci tests
    (https://issues.rudder.io/issues/18581[#18581])
* Fixed: interpolated variable in conditions should not treat dots as AND operators 
    (https://issues.rudder.io/issues/18486[#18486])
* Fixed: add NA logs to cfengine generation
    (https://issues.rudder.io/issues/18440[#18440])
* Fixed: fix makefile test
    (https://issues.rudder.io/issues/18468[#18468])
* Fixed: Rudder-lang doc build broken by ncf parameter
    (https://issues.rudder.io/issues/18371[#18371])
* Fixed: delete tmp file added by mistake
    (https://issues.rudder.io/issues/18342[#18342])
* Fixed: fix version for serde and rudderlang techniques
    (https://issues.rudder.io/issues/18193[#18193])
* Fixed: rudder-lang fails to test its documentation examples
    (https://issues.rudder.io/issues/18169[#18169])
* Fixed: Sort the generated lib
    (https://issues.rudder.io/issues/18128[#18128])
* Fixed: rudder-lang tests fail on system with python2
    (https://issues.rudder.io/issues/18126[#18126])
* Fixed: Broken generate_lib with python 2
    (https://issues.rudder.io/issues/18114[#18114])

==== Architecture - Internal libs

* Fixed: Move elm test in the webapp step to avoid concurrent builds
    (https://issues.rudder.io/issues/19829[#19829])

==== Relay server or API

* Fixed: File watchers on inventories do not work
    (https://issues.rudder.io/issues/19813[#19813])
* Fixed: Rudder-server-relay postinstall script fails to modify the certificate paths in the apache configuration
    (https://issues.rudder.io/issues/19550[#19550])
* Fixed: Memory corruption in tokio
    (https://issues.rudder.io/issues/19520[#19520])
* Fixed: relayd fails to start because of incorrect default logging config handling
    (https://issues.rudder.io/issues/19497[#19497])
* Fixed: Broken reports watcher in 7.0
    (https://issues.rudder.io/issues/19479[#19479])
* Fixed: Missing catchup limit in 7.0
    (https://issues.rudder.io/issues/19478[#19478])
* Fixed: Cargo update is needed
    (https://issues.rudder.io/issues/19292[#19292])
* Fixed: Allow verifying upstream server certificate when forwarding files
    (https://issues.rudder.io/issues/18851[#18851])
* Fixed: Update relayd after reporting changes in webapp
    (https://issues.rudder.io/issues/18412[#18412])
* Fixed: Do not fail on missing config id
    (https://issues.rudder.io/issues/18189[#18189])
* Fixed: Add ReportsExecution insertion in relayd
    (https://issues.rudder.io/issues/18124[#18124])
* Fixed:  Use cargo-deny to replace cargo-audit
    (https://issues.rudder.io/issues/18123[#18123])
* Fixed: Shared-files correction in postinst must be recursive
    (https://issues.rudder.io/issues/17882[#17882])
* Fixed: Configure relayd to check certificates
    (https://issues.rudder.io/issues/19622[#19622])

==== System techniques

* Fixed: Allowed networks are not saved for the Relay
    (https://issues.rudder.io/issues/19779[#19779])
* Fixed: relayd is not reloaded when a node is added under a relay
    (https://issues.rudder.io/issues/19826[#19826])
* Fixed: on relay, policies complains about missing /opt/rudder/etc/rudder-passwords.conf that is not on relay
    (https://issues.rudder.io/issues/19788[#19788])
* Fixed: Inventories are not accepted by relays. Need to restart apache2 to make them accept it
    (https://issues.rudder.io/issues/19787[#19787])
* Fixed: Relayd does not start on relays due to missing db config
    (https://issues.rudder.io/issues/19781[#19781])
* Fixed: Invalid /root/.pgpass file in rudder 7
    (https://issues.rudder.io/issues/19655[#19655])
* Fixed: unexpected reports in rudder-service-relayd
    (https://issues.rudder.io/issues/19606[#19606])
* Fixed: no reports are inserted in database in rudder 7.0
    (https://issues.rudder.io/issues/19603[#19603])
* Fixed: when the password are updated by the policies, rudder-jetty and rudder-slapd are not restarted
    (https://issues.rudder.io/issues/19584[#19584])
* Fixed: Typo in inventory technique file
    (https://issues.rudder.io/issues/19433[#19433])

==== Security

* Fixed: Don't fill system variable with sensitive info on non  root server
    (https://issues.rudder.io/issues/19680[#19680])

==== Web - Compliance & node report

* Fixed: Compliance problem in 7.0
    (https://issues.rudder.io/issues/19615[#19615])
* Fixed: Broken rules list in directive form
    (https://issues.rudder.io/issues/19651[#19651])

==== Web - Nodes & inventories

* Fixed: Remove server roles in node details
    (https://issues.rudder.io/issues/19614[#19614])
* Fixed: Properties tab is broken in rudder 7.0
    (https://issues.rudder.io/issues/19597[#19597])

==== API

* Fixed: Remove API v1 endpoints
    (https://issues.rudder.io/issues/18511[#18511])

==== Architecture - Refactoring

* Fixed: webapp build broken in 7.0
    (https://issues.rudder.io/issues/18825[#18825])
* Fixed: AgentRunsTest and ReportsTest not passing on master
    (https://issues.rudder.io/issues/18151[#18151])

==== Techniques

* Fixed: delete all deprecated techniques for 7.0
    (https://issues.rudder.io/issues/19610[#19610])
* Fixed: HTTP download technique should not try to use minicurl
    (https://issues.rudder.io/issues/17261[#17261])

==== Server components

* Fixed: Rudder server reload-techniques does not work in 7.0
    (https://issues.rudder.io/issues/19448[#19448])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Marek Haluska
* Gatan POBLON

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

