= Change logs for Rudder 6.0

Rudder 6.0 is currently a maintained version of Rudder.

This page provides a summary of changes for each version. Previous beta
and rc versions are listed below for convenience.

== Rudder 6.0.10 (2020-10-28)

=== Changes

=== Bug fixes

==== Documentation

* Fixed: Advise to not desinstall rudder server if possible
    (https://issues.rudder.io/issues/17803[#17803])

==== API

* Fixed: Format of lastRunDate/lastInventoryDate has changed in api response in 6.0.0
    (https://issues.rudder.io/issues/18337[#18337])

==== Security

* Fixed: Webdav allows get on inventory and reports
    (https://issues.rudder.io/issues/18325[#18325])
* Fixed: Agents fail to check their policy server's identity
    (https://issues.rudder.io/issues/18286[#18286])

==== Web - Config management

* Fixed: Missing system variable "POLICY_SERVER_KEY"
    (https://issues.rudder.io/issues/18289[#18289])

==== Techniques

* Fixed: apt configuration issue - add apost-check to validate generated line
    (https://issues.rudder.io/issues/13741[#13741])
* Fixed: userManagement produces missing reports when used in "check only" mode
    (https://issues.rudder.io/issues/16837[#16837])

==== Agent

* Fixed: commands from error message are launched due to backticks
    (https://issues.rudder.io/issues/18174[#18174])
* Fixed: rudder-agent check sleep and process pile-up in 6.0
    (https://issues.rudder.io/issues/18339[#18339])

==== Technique editor - API

* Fixed: Method with empty curly braces are not recognized as valid
    (https://issues.rudder.io/issues/18268[#18268])

==== Generic methods - Package Management

* Fixed: Zypper module does not work on python2
    (https://issues.rudder.io/issues/18143[#18143])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.0.9 (2020-09-16)

=== Changes

=== Bug fixes

==== Web - Config management

* Fixed: Groups are not committed in configuration-repository on modification
    (https://issues.rudder.io/issues/18207[#18207])

==== System integration

* Fixed: Logs from all nodes are always reported in all.log
    (https://issues.rudder.io/issues/18205[#18205])

==== Techniques

* Fixed: Technique resources should not be committed on server upgrade
    (https://issues.rudder.io/issues/18213[#18213])

=== Release notes

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.0.8 (2020-09-16)

=== Changes

==== Documentation

* CVE plugin api documentation
    (https://issues.rudder.io/issues/17940[#17940])
* Improve docs consistency
    (https://issues.rudder.io/issues/18109[#18109])

=== Bug fixes

==== Packaging

* Fixed: if configuration files are replaced during upgrade, rudder-upgrade fails on both postgresql checks and plugins disabling
    (https://issues.rudder.io/issues/18139[#18139])

==== Security

* Fixed: Rudder app and docs should not be indexable by search engines
    (https://issues.rudder.io/issues/18019[#18019])

==== Web - Nodes & inventories

* Fixed: In SLES 15, SP is view as part of rudder agent version
    (https://issues.rudder.io/issues/17736[#17736])
* Fixed: Group query with OR composition and searching for Node properties return all nodes in place of none
    (https://issues.rudder.io/issues/18172[#18172])
* Fixed: Group query with OR composition and searching for Node properties return less results than expected
    (https://issues.rudder.io/issues/18133[#18133])
* Fixed: Number of groups on the dashboard in incorrect
    (https://issues.rudder.io/issues/17202[#17202])

==== Relay server or API

* Fixed: SELinux perms on relay forbid to retrieve files from shared-folder (Windows DSC)
    (https://issues.rudder.io/issues/17770[#17770])

==== Documentation

* Fixed: Update links to ansible inventory plugin
    (https://issues.rudder.io/issues/18080[#18080])
* Fixed: http in place of https in install doc for zypper subscription repo
    (https://issues.rudder.io/issues/18055[#18055])
* Fixed: Fix doc build after nodejs upgrade
    (https://issues.rudder.io/issues/18056[#18056])
* Fixed: The documentation should mention more obviously that upgrades from 4.3 to 6.0 are not supported
    (https://issues.rudder.io/issues/17982[#17982])
* Fixed: Documentation is wrong about default values for data retention
    (https://issues.rudder.io/issues/17935[#17935])

==== API

* Fixed: "id" setting is silently ignored for new group created through the REST API.
    (https://issues.rudder.io/issues/10216[#10216])
* Fixed: Rudder directive API seem to take key-value order into account in json POST request 
    (https://issues.rudder.io/issues/14934[#14934])
* Fixed: Fix swagger warnings in api doc
    (https://issues.rudder.io/issues/18020[#18020])

==== Miscellaneous

* Fixed: orchestrateur-5 (root) inventory are send to demo/snapshot/dev server, breaking their inventory preventing to use them
    (https://issues.rudder.io/issues/18130[#18130])
* Fixed: Error displayed when switching from full access to read only
    (https://issues.rudder.io/issues/18052[#18052])

==== Web - Config management

* Fixed: SUSE is spelled SuSE in the webapp
    (https://issues.rudder.io/issues/16319[#16319])
* Fixed: Techniques with conditions on tasks with very long parameters report "missing" parts on the dashboard
    (https://issues.rudder.io/issues/18100[#18100])
* Fixed: "error: Only functions returning scalars can be used as arguments" in verbose output
    (https://issues.rudder.io/issues/18101[#18101])
* Fixed: Missing interpolator in error message for allowed networks
    (https://issues.rudder.io/issues/17967[#17967])
* Fixed: Incorrect error message when a resource is not found
    (https://issues.rudder.io/issues/17944[#17944])

==== Performance and scalability

* Fixed: duplicate parsing for hostname in inventory processing
    (https://issues.rudder.io/issues/18097[#18097])

==== System integration

* Fixed: Test fails because takes too long
    (https://issues.rudder.io/issues/18050[#18050])
* Fixed: directive list tells you to upgrade the server if it didn't yet connect.
    (https://issues.rudder.io/issues/16663[#16663])
* Fixed: When rudder agent health stops all service because there aren't any space left, if should state it in the log (and which fs)
    (https://issues.rudder.io/issues/17472[#17472])

==== Web - Technique editor

* Fixed: Remove technique from technique tree when deleting technique in the technique editor
    (https://issues.rudder.io/issues/18015[#18015])

==== Web - UI & UX

* Fixed: Cannot set Compliance reporting mode on "Non compliant only" in settings tab
    (https://issues.rudder.io/issues/16402[#16402])
* Fixed: Error when trying to enable a disabled Technique in the technique tree
    (https://issues.rudder.io/issues/17906[#17906])

==== Techniques

* Fixed: Technique shared folder on WIndows use invalid md5 hash instead of sha256
    (https://issues.rudder.io/issues/18176[#18176])
* Fixed: No flush key report on sshKeyDistribution when there is not yet an ssh key configured
    (https://issues.rudder.io/issues/16516[#16516])

==== System techniques

* Fixed: If gzip is not installed the inventory is not sent
    (https://issues.rudder.io/issues/17891[#17891])

==== Agent

* Fixed: hostname command may not exist
    (https://issues.rudder.io/issues/18018[#18018])
* Fixed: When a node is in bootstrap mode there is no understandable way to unlock it from this state
    (https://issues.rudder.io/issues/16825[#16825])
* Fixed: rudder agent health fails on aix
    (https://issues.rudder.io/issues/17933[#17933])

==== Generic methods

* Fixed: Method shared folder should not state that you can use md5 as hash method
    (https://issues.rudder.io/issues/18177[#18177])
* Fixed: File from local source with check: diff error
    (https://issues.rudder.io/issues/17303[#17303])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Bas B
* Frédéric COSTANT
* Alexander Brunhirl
* Florian Heigl
* Dmitry Svyatogorov
* PB LO

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.0.7 (2020-07-03)

=== Changes

==== Documentation

* Missing uninstall doc for agent
    (https://issues.rudder.io/issues/17790[#17790])

==== Miscellaneous

* Add a 'Rudder by example' best practice use case
    (https://issues.rudder.io/issues/17715[#17715])
* Add a 'Rudder by example' best practice use case
    (https://issues.rudder.io/issues/17715[#17715])
* Add a 'Rudder by example' best practice use case
    (https://issues.rudder.io/issues/17715[#17715])
* Add a 'Rudder by example' best practice use case
    (https://issues.rudder.io/issues/17715[#17715])

==== Plugins integration

* Rudder package list should display plugin status
    (https://issues.rudder.io/issues/16793[#16793])

=== Bug fixes

==== Packaging

* Fixed: Rudder-agent needs libxml-treepp-perl dependency to work on minimal Debian
    (https://issues.rudder.io/issues/17699[#17699])
* Fixed: /opt/rudder/etc/rudder-pkg comes with the wrong permissions
    (https://issues.rudder.io/issues/17695[#17695])
* Fixed: Agent uses "cmp" command but it is not a dependency
    (https://issues.rudder.io/issues/17606[#17606])
* Fixed: shared-files acls are incorrect on relays, preventing the windows nodes from downloading them
    (https://issues.rudder.io/issues/17802[#17802])
* Fixed: ruder package command fails to run in automated setup
    (https://issues.rudder.io/issues/17645[#17645])
* Fixed: ruder package command fails to run in automated setup
    (https://issues.rudder.io/issues/17645[#17645])

==== Documentation

* Fixed: remove pg_repack from documentation
    (https://issues.rudder.io/issues/17839[#17839])
* Fixed: Missing doc about root-relay communication flows
    (https://issues.rudder.io/issues/17837[#17837])
* Fixed: Documentation should state that SSD is recommended for more than 50 nodes
    (https://issues.rudder.io/issues/17761[#17761])
* Fixed: Missing documentation for overriding jetty system properties in start.ini
    (https://issues.rudder.io/issues/17719[#17719])
* Fixed: Inconsistent commands for service management
    (https://issues.rudder.io/issues/17529[#17529])
* Fixed: Images from private plugins are not visible
    (https://issues.rudder.io/issues/17498[#17498])

==== Relay server or API

* Fixed: Shared-files correction in postinst must be recursive
    (https://issues.rudder.io/issues/17882[#17882])
* Fixed: Ignore invalid hash in nodeslist
    (https://issues.rudder.io/issues/17458[#17458])

==== Web - Config management

* Fixed: Wrong error message when policy server of a Node is not found during generation 
    (https://issues.rudder.io/issues/17851[#17851])
* Fixed: Upgrading from rudder 5.0 to 6.0 leads to `distributePolicy not available` error
    (https://issues.rudder.io/issues/17836[#17836])
* Fixed: Duplicate category name error when saving a new user technique
    (https://issues.rudder.io/issues/17774[#17774])
* Fixed: Auto-archive gitRepo.git failure warning is not actionnable, should be info or debug
    (https://issues.rudder.io/issues/17777[#17777])
* Fixed: Ignored node lead to an error log during generation
    (https://issues.rudder.io/issues/17441[#17441])

==== API

* Fixed: 'policyMode' vs. 'policy' in node settings API
    (https://issues.rudder.io/issues/17817[#17817])
* Fixed: API documentation on Rules is missing explanation on how to update rule category
    (https://issues.rudder.io/issues/17409[#17409])
* Fixed: Bad JSON answer for api PUT /rules
    (https://issues.rudder.io/issues/17388[#17388])

==== Performance and scalability

* Fixed: table nodes contains on entry per node per generation, which is too much
    (https://issues.rudder.io/issues/17778[#17778])
* Fixed: table nodes contains on entry per node per generation, which is too much
    (https://issues.rudder.io/issues/17778[#17778])
* Fixed: when running cf-promises, list-compatible-inputs is ran 8 times
    (https://issues.rudder.io/issues/17481[#17481])

==== System integration

* Fixed: Cannot download licenses if there is a trailing slash in rudder package config url
    (https://issues.rudder.io/issues/17673[#17673])
* Fixed: rudder package command fails when not run from a terminal
    (https://issues.rudder.io/issues/17453[#17453])

==== Plugins integration

* Fixed: Improve rudder package error message when an update is needed
    (https://issues.rudder.io/issues/17626[#17626])
* Fixed: rudder package logs are inconsistent
    (https://issues.rudder.io/issues/17600[#17600])

==== Security

* Fixed: Markdown descriptions in directives and groups are evaluated, resulting in Javascript execution
    (https://issues.rudder.io/issues/17641[#17641])

==== Web - Compliance & node report

* Fixed: policy generation fails if we put a " in the directive name
    (https://issues.rudder.io/issues/17628[#17628])

==== Web - Nodes & inventories

* Fixed: compilation error in 6.0 because of absence of typo in Inconsistency
    (https://issues.rudder.io/issues/17605[#17605])
* Fixed: Purge of unreferenced software may still fail on very large system
    (https://issues.rudder.io/issues/17176[#17176])

==== Web - UI & UX

* Fixed: When adding tags, if anything is wrong in the directive form, all unsaved tags are wiped out
    (https://issues.rudder.io/issues/15557[#15557])
* Fixed: OS logo is missing in summary node
    (https://issues.rudder.io/issues/16454[#16454])
* Fixed: Ignored (disabled) nodes are show as enabled in details
    (https://issues.rudder.io/issues/17440[#17440])

==== Techniques

* Fixed: clockConfiguration is not compatible with systemd-based systems
    (https://issues.rudder.io/issues/6772[#6772])
* Fixed: Rsync commands for shared files are broken
    (https://issues.rudder.io/issues/17468[#17468])

==== System techniques

* Fixed: Rudder 6 check postgresql process failes
    (https://issues.rudder.io/issues/17145[#17145])
* Fixed: Error when setting classes for agent capabilities
    (https://issues.rudder.io/issues/17480[#17480])

==== Generic methods

* Fixed: Syntax error in shared_file_to_node
    (https://issues.rudder.io/issues/17667[#17667])
* Fixed: no reports from sharedfile to node if file is already there
    (https://issues.rudder.io/issues/17661[#17661])

==== Web - Technique editor

* Fixed: The technique editor struggles to display long line as component
    (https://issues.rudder.io/issues/17392[#17392])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Alexander Brunhirl

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.0.6 (2020-05-19)

=== Changes

==== Documentation

* Document that Rudder servers should not be exposed on the Internet
    (https://issues.rudder.io/issues/17316[#17316])
* Improve doc related to plugins/subscriptions
    (https://issues.rudder.io/issues/17144[#17144])

==== Packaging

* Use cargo-deny to replace cargo-audit
    (https://issues.rudder.io/issues/17308[#17308])

==== Agent

* Add a command to set policy server on agents
    (https://issues.rudder.io/issues/16529[#16529])

==== Technique editor - UI/UX

* Keep the original name of a Generic Method displayed
    (https://issues.rudder.io/issues/16937[#16937])

=== Bug fixes

==== Packaging

* Fixed: SELinux policy for technique editor is not applied anymore after upgrade on RHEL/Centos server
    (https://issues.rudder.io/issues/17395[#17395])
* Fixed: "strip" calls fail during AIX agent build
    (https://issues.rudder.io/issues/17365[#17365])
* Fixed: Reduce size of rpm build logs
    (https://issues.rudder.io/issues/17360[#17360])
* Fixed: Missing dependency on iproute2 making rudder-init fails on minimal install
    (https://issues.rudder.io/issues/17356[#17356])
* Fixed: Agent package cache is updated at each run
    (https://issues.rudder.io/issues/17337[#17337])
* Fixed: Our agent package contains CFEngine systemd units
    (https://issues.rudder.io/issues/16790[#16790])

==== Agent

* Fixed: Debug script is broken in 6.0
    (https://issues.rudder.io/issues/17380[#17380])
* Fixed: Update embedded openssl version to 1.1.1g
    (https://issues.rudder.io/issues/17178[#17178])
* Fixed: Add doc about return codes to agent man page
    (https://issues.rudder.io/issues/17281[#17281])
* Fixed: Agent run exit code should be 0 when agent runs properly (no breaking/fatal errors) 
    (https://issues.rudder.io/issues/17268[#17268])

==== Performance and scalability

* Fixed: Agent consuming lots of IO and resources at each run
    (https://issues.rudder.io/issues/17371[#17371])

==== Documentation

* Fixed: Doc about missing uuid.hive at upgrade was not upmerged
    (https://issues.rudder.io/issues/17299[#17299])
* Fixed: Add a link to upgrade notes at the beginning of each upgrade doc page
    (https://issues.rudder.io/issues/17219[#17219])
* Fixed: Plugins menu in the documentation should be in alphabetical order
    (https://issues.rudder.io/issues/16808[#16808])
* Fixed: API documentation is lacking of a Json based update of rule/directive
    (https://issues.rudder.io/issues/17292[#17292])

==== Relay server or API

* Fixed: Inventories from new nodes should be sent using the "rudder" password and not generated one
    (https://issues.rudder.io/issues/17416[#17416])

==== Architecture - Internal libs

* Fixed: Stacktrace in test introduce in #17341
    (https://issues.rudder.io/issues/17411[#17411])

==== Web - Config management

* Fixed: Compliance data for reporting plugin are not generated anymore
    (https://issues.rudder.io/issues/17341[#17341])
* Fixed: TechniqueVersion ordering algorithm is incorrect
    (https://issues.rudder.io/issues/17157[#17157])

==== API

* Fixed: API documentation omits the policymode parameter of directives
    (https://issues.rudder.io/issues/17301[#17301])

==== Web - UI & UX

* Fixed: Page for node not found is too minimalist
    (https://issues.rudder.io/issues/16515[#16515])
* Fixed: Rule ID is not trimmed when copied from the web interface
    (https://issues.rudder.io/issues/17290[#17290])

==== Security

* Fixed: exception in ldap search are not correctly caught
    (https://issues.rudder.io/issues/17267[#17267])

==== Web - Nodes & inventories

* Fixed: When a node is removed from a dynamic group, it log "adding nothing, removing nothing"
    (https://issues.rudder.io/issues/17220[#17220])
* Fixed: Concurrent access to node info cache cause exception to be thrown when accessing cache content
    (https://issues.rudder.io/issues/17172[#17172])

==== System techniques

* Fixed: Runlog catchup does not work on linux
    (https://issues.rudder.io/issues/17192[#17192])

==== Technique editor - API

* Fixed: techniques files are parsed twice
    (https://issues.rudder.io/issues/17425[#17425])

==== Web - Technique editor

* Fixed: Technique diverge popup when coming back to a techniques because of a change of category
    (https://issues.rudder.io/issues/17400[#17400])

==== Technique editor - UI/UX

* Fixed: Text &  Boxes jump when displaying missing inputs
    (https://issues.rudder.io/issues/16235[#16235])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl
* Victor Héry

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.0.5 (2020-04-23)

=== Changes

==== Documentation

* Add a page about pre-releases
    (https://issues.rudder.io/issues/17091[#17091])
* Change path for plugin images
    (https://issues.rudder.io/issues/16990[#16990])
* Redirect video page from the doc to the youtube playlists
    (https://issues.rudder.io/issues/17002[#17002])
* Move upgrade notes into "upgrade rudder"
    (https://issues.rudder.io/issues/16947[#16947])
* Add new API docs to the main doc menu
    (https://issues.rudder.io/issues/16865[#16865])
* Explains how to change requestHeaderSize in Rudder 5.0
    (https://issues.rudder.io/issues/16677[#16677])
* Publish arch-doc for http reporting/relayd in the repo
    (https://issues.rudder.io/issues/16623[#16623])

==== Web - UI & UX

* Folded categories in the Directive tree should be kept between sessions
    (https://issues.rudder.io/issues/16258[#16258])

==== Packaging

* Add a rust-toolchain file in relayd
    (https://issues.rudder.io/issues/16957[#16957])

==== Web - Compliance & node report

* Better tracking of last seen state
    (https://issues.rudder.io/issues/8069[#8069])

=== Bug fixes

==== Agent

* Fixed: Align Unix agent certificate configuration on the one used by Windows agents
    (https://issues.rudder.io/issues/17043[#17043])
* Fixed: Upgrade to CFEngine 3.12.4
    (https://issues.rudder.io/issues/16978[#16978])
* Fixed: Agent check splaytime is not actually random
    (https://issues.rudder.io/issues/17082[#17082])
* Fixed: "rudder agent factory-reset" restores old uuid instead of changing it
    (https://issues.rudder.io/issues/16900[#16900])
* Fixed: rudder agent reset does not ensure that ncf is up to date on the server
    (https://issues.rudder.io/issues/16826[#16826])

==== Packaging

* Fixed: When installing rudder-server-root on RPM-based systems, it asks about running rudder-node-to-relay
    (https://issues.rudder.io/issues/14600[#14600])
* Fixed: shared-files are not writable by relayd on upgraded servers
    (https://issues.rudder.io/issues/16923[#16923])
* Fixed: Slow permissions change of /var/rudder/share during upgrade
    (https://issues.rudder.io/issues/16907[#16907])
* Fixed: Inconsistent path for nodeslist.pem
    (https://issues.rudder.io/issues/16762[#16762])

==== Web - Nodes & inventories

* Fixed: In SLES 15, SP is view as part of version
    (https://issues.rudder.io/issues/16803[#16803])

==== Plugins integration

* Fixed: Remove old rudder-plugin script
    (https://issues.rudder.io/issues/16755[#16755])

==== Documentation

* Fixed: Add documentation on generic methods writing
    (https://issues.rudder.io/issues/16988[#16988])
* Fixed: Add better documentation on how to access technique parameter within a technique
    (https://issues.rudder.io/issues/17034[#17034])
* Fixed: Precise in the documentation that the Windows agent does not currently support HTTPS report mode
    (https://issues.rudder.io/issues/17018[#17018])
* Fixed: Add a reference documentation about methods writing
    (https://issues.rudder.io/issues/16999[#16999])
* Fixed: Remove debian 5 from the list of supported os
    (https://issues.rudder.io/issues/17005[#17005])
* Fixed: Add a logs documentation page
    (https://issues.rudder.io/issues/16602[#16602])
* Fixed: Broken formatting of network requirements
    (https://issues.rudder.io/issues/16970[#16970])
* Fixed: Documentation for variables is "splitted" in two
    (https://issues.rudder.io/issues/16933[#16933])
* Fixed: Typo in Variable doc: hsotname
    (https://issues.rudder.io/issues/16918[#16918])
* Fixed: Document /var/rudder/policy-generation-info
    (https://issues.rudder.io/issues/16903[#16903])
* Fixed: Add an example on how to apply condition_from_variable_match_regex to a technique parameter
    (https://issues.rudder.io/issues/17035[#17035])

==== Miscellaneous

* Fixed: Add DSC inventory hook documentation
    (https://issues.rudder.io/issues/16940[#16940])

==== Technique editor - UI/UX

* Fixed: When we add a multiline description in a technique, it breaks policy generation and technique loadingg
    (https://issues.rudder.io/issues/17141[#17141])
* Fixed: "Technique diverges" bug still persists
    (https://issues.rudder.io/issues/16691[#16691])

==== Web - Maintenance

* Fixed: When deletion of reports fails, we don't get meaningful message, and it fails when ComplianceLevels are disabled
    (https://issues.rudder.io/issues/17129[#17129])
* Fixed: Purge of unreferenced software may fail on very large system
    (https://issues.rudder.io/issues/16636[#16636])

==== Web - UI & UX

* Fixed: Some alignement issues in the interface
    (https://issues.rudder.io/issues/16430[#16430])
* Fixed: Generation status color must not be grey
    (https://issues.rudder.io/issues/17104[#17104])
* Fixed: Users with readonly rights should be able to view the node properties and their value
    (https://issues.rudder.io/issues/16854[#16854])
* Fixed: Menu scroll is broken
    (https://issues.rudder.io/issues/17056[#17056])
* Fixed: Hide remote run button for Windows agent
    (https://issues.rudder.io/issues/16898[#16898])

==== Relay server or API

* Fixed: Systemd hardening generates error message on remote-run
    (https://issues.rudder.io/issues/17107[#17107])
* Fixed: Windows agents are unable to access shared-folder
    (https://issues.rudder.io/issues/17041[#17041])
* Fixed: Vulnerability in a dependency of relayd benchmarking tool
    (https://issues.rudder.io/issues/16975[#16975])
* Fixed: Broken parsing of openscap technique report
    (https://issues.rudder.io/issues/16961[#16961])

==== System integration

* Fixed: Test files are not correctly clean
    (https://issues.rudder.io/issues/17079[#17079])
* Fixed: Trace log in policy generation is displaying the same value for two differents entries
    (https://issues.rudder.io/issues/16916[#16916])

==== Web - Config management

* Fixed: Policy generation must fail when report is HTTPS only and old agent are present
    (https://issues.rudder.io/issues/17019[#17019])
* Fixed: Agent 6.0 can't update policies from Rudder 5.0
    (https://issues.rudder.io/issues/17081[#17081])
* Fixed: Technique resources are not provided to Windows agent
    (https://issues.rudder.io/issues/17062[#17062])

==== Techniques

* Fixed: Webdav password is ignored and access is granted for all nodes in allowed networks
    (https://issues.rudder.io/issues/16552[#16552])
* Fixed: duplicate RudderUniqueID on one entry on UserManagement v9
    (https://issues.rudder.io/issues/16881[#16881])
* Fixed: When using twice directive packageManagement 1.2, once to ensure presence of a package, and second one to upgrade the package, reporting and posthook is wrong on the second one
    (https://issues.rudder.io/issues/16849[#16849])

==== Architecture - Dependencies

* Fixed: Upgrade Bouncy Castle GPG to latest minor version
    (https://issues.rudder.io/issues/17006[#17006])

==== Performance and scalability

* Fixed: Infinite loop in `for` may leak memory
    (https://issues.rudder.io/issues/16946[#16946])
* Fixed: Git configuration-repository object is created at each evaluation, impacting performance
    (https://issues.rudder.io/issues/16929[#16929])
* Fixed: Inneficient computation of RuleStatusReports and NodeStatusReports
    (https://issues.rudder.io/issues/16661[#16661])

==== API

* Fixed: Add openapi 11 version of the API doc
    (https://issues.rudder.io/issues/16852[#16852])

==== Generic methods - Package Management

* Fixed: Update package modules to 3.12.4
    (https://issues.rudder.io/issues/17111[#17111])
* Fixed: package_state_options doesn't properly defines outcome classes when called twice with same package name
    (https://issues.rudder.io/issues/16850[#16850])

==== Generic methods

* Fixed: Use a valid URL to test http methods
    (https://issues.rudder.io/issues/17098[#17098])
* Fixed: Broken tests for user group
    (https://issues.rudder.io/issues/17008[#17008])
* Fixed: Permissions dirs recursive doesn't allow to set only owner, or group, or mode
    (https://issues.rudder.io/issues/16917[#16917])
* Fixed: Generic method  sysctl_value
    (https://issues.rudder.io/issues/16882[#16882])

==== Web - Technique editor

* Fixed: Can't insert method to end of method list in technique editor
    (https://issues.rudder.io/issues/16993[#16993])
* Fixed: Technique editor does not prevent user from cloning a technique with an already existing id
    (https://issues.rudder.io/issues/17030[#17030])
* Fixed: When editing the content of a ressource, the "save" button is lowercase
    (https://issues.rudder.io/issues/16722[#16722])

==== Generic methods - User Management

* Fixed: There is no method to handle secondary groups of a user in the technique editor
    (https://issues.rudder.io/issues/16325[#16325])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Tim Taler
* Florian Heigl

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.0.4 (2020-03-03)

=== Changes

==== Documentation

* Add upgrade notice to 6.0.3
    (https://issues.rudder.io/issues/16832[#16832])

=== Bug fixes

==== Packaging

* Fixed: Policy generation fails with many nodes in 6.0 after an upgrade
    (https://issues.rudder.io/issues/16845[#16845])

==== Web - Maintenance

* Fixed: LDAP connection pool error are not correctly reported 
    (https://issues.rudder.io/issues/16847[#16847])
* Fixed: when we import groups, categories are not imported, and groups are not imported either
    (https://issues.rudder.io/issues/16835[#16835])

==== API

* Fixed: It is impossible to use the /nodes/applyPolicy endpoint
    (https://issues.rudder.io/issues/16848[#16848])

==== Web - Compliance & node report

* Fixed: Changing one node policy mode change the policy mode for all nodes
    (https://issues.rudder.io/issues/16844[#16844])

==== Web - Config management

* Fixed: Restoring directive archive timeout and break LDAP
    (https://issues.rudder.io/issues/16839[#16839])

==== Web - Technique editor

* Fixed: Impossible to scroll through technique list in the technique editor
    (https://issues.rudder.io/issues/16840[#16840])

==== Technique editor - API

* Fixed: Technique with non ascii characters breaks migration from 5.0 to 6.0
    (https://issues.rudder.io/issues/16838[#16838])

==== Generic methods - File Management

* Fixed: Add log reporting for jinja templating
    (https://issues.rudder.io/issues/16748[#16748])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.0.3 (2020-02-27)

=== Changes

==== Documentation

* Update security doc after 6.0
    (https://issues.rudder.io/issues/16572[#16572])

==== Web - UI & UX

* Make some changes to facilitate the integration of plugins
    (https://issues.rudder.io/issues/16781[#16781])

==== Web - Nodes & inventories

* Remove agent type from node details
    (https://issues.rudder.io/issues/16627[#16627])

==== Packaging

* Add github status for rudder-language build
    (https://issues.rudder.io/issues/16617[#16617])

==== Rudder language

* rl logger
    (https://issues.rudder.io/issues/16583[#16583])
* Replace file headers to shorter spdx license identifier
    (https://issues.rudder.io/issues/16593[#16593])
* rl integration tests cleaned
    (https://issues.rudder.io/issues/16580[#16580])
* rl integration tests
    (https://issues.rudder.io/issues/16484[#16484])
* RL error handling - non blocking errors tool and error context capture
    (https://issues.rudder.io/issues/16483[#16483])

==== Web - Config management

* Add basic support for categories in techniques from technique editor
    (https://issues.rudder.io/issues/16598[#16598])

=== Bug fixes

==== Packaging

* Fixed: After upgrading from 5.0.16 to 6.0.3 on centos7 with plugins, jetty is stopped
    (https://issues.rudder.io/issues/16797[#16797])
* Fixed: Avoid moving ncf-api-venv config on SLES
    (https://issues.rudder.io/issues/16796[#16796])
* Fixed: When upgrading to 6.0.3 the packaging should disable all installed plugins
    (https://issues.rudder.io/issues/16792[#16792])
* Fixed: Error on plugins compatibility on upgrade cause the technique to not be updated
    (https://issues.rudder.io/issues/16782[#16782])
* Fixed: Missing restorecon in relay postinst for relayd file
    (https://issues.rudder.io/issues/16766[#16766])
* Fixed: rudder-upgrade refers to /opt/rudder/bin/rudder-pkg which doesn't exists in 6.0
    (https://issues.rudder.io/issues/16761[#16761])
* Fixed: When upgrading from 5.0 to 6.0 (on centos7), incompatible plugins are not disabled
    (https://issues.rudder.io/issues/16735[#16735])
* Fixed: After upgrade from 5.0 to 6.0 on centos7, rudder-slapd is not started
    (https://issues.rudder.io/issues/16707[#16707])
* Fixed: Getfacl warning at upgrade time
    (https://issues.rudder.io/issues/16698[#16698])
* Fixed: During upgrade, jetty doesn't seems to always restart correctly 
    (https://issues.rudder.io/issues/12911[#12911])
* Fixed: rudder-init fails when there are only IPv6 addresses
    (https://issues.rudder.io/issues/16680[#16680])
* Fixed: Restart rudder-jetty at the end of rudder-webapp postinst
    (https://issues.rudder.io/issues/16642[#16642])
* Fixed: Webapp postinst script in upgrade can fail with an agent error
    (https://issues.rudder.io/issues/16631[#16631])
* Fixed: In some upgrade paths, the Rudder config in /etc/ld.so.conf.d/ stays present
    (https://issues.rudder.io/issues/16596[#16596])
* Fixed: Typo in the rudder-server-relay rule file
    (https://issues.rudder.io/issues/16571[#16571])
* Fixed: At upgrade apache restart fail since webapp files are already unpacked
    (https://issues.rudder.io/issues/16560[#16560])
* Fixed: Missing failed folder for inventories on relays
    (https://issues.rudder.io/issues/16550[#16550])
* Fixed: Install logs of rudder-webapp are overwritten at the last install step
    (https://issues.rudder.io/issues/16528[#16528])
* Fixed: rudder reports installation fails on CentOS 7.7 because /var/log/rudder/install directory does not exist
    (https://issues.rudder.io/issues/16519[#16519])
* Fixed: Missing SELinux context on relayd config
    (https://issues.rudder.io/issues/16771[#16771])
* Fixed: We should not display logs about password creation by htpasswd in relay postinst
    (https://issues.rudder.io/issues/16765[#16765])
* Fixed: Use HTTPS repository URLs in maven configuration
    (https://issues.rudder.io/issues/16651[#16651])
* Fixed: Debian9 install fails due to rudder-init
    (https://issues.rudder.io/issues/16561[#16561])
* Fixed: Rudder agent 5.x package not compatible with Centos8
    (https://issues.rudder.io/issues/16521[#16521])
* Fixed: Restore SELinux context for cert and nodeslist in reload script
    (https://issues.rudder.io/issues/16769[#16769])

==== Server components

* Fixed: 6.0 agents are unable to download their policies from a 5.0 server
    (https://issues.rudder.io/issues/16576[#16576])
* Fixed: Can not apply directives based on technique built only for non Linux systems if they do not contains conditions
    (https://issues.rudder.io/issues/16810[#16810])
* Fixed: Add an "upgrade-all" command to rudder-pkg
    (https://issues.rudder.io/issues/16569[#16569])

==== Agent

* Fixed: At install rudder-agent does not prompt the necessary steps to configure the agent
    (https://issues.rudder.io/issues/16533[#16533])
* Fixed: Method "exist_or_restore" in rudder agent check outputs an error message if the backup doesn't exist
    (https://issues.rudder.io/issues/16703[#16703])
* Fixed: rudder agent health does not work on agent bootstrap nor on server before first run
    (https://issues.rudder.io/issues/16588[#16588])

==== Documentation

* Fixed: Update install/upgrade docs for 6.0.3
    (https://issues.rudder.io/issues/16779[#16779])
* Fixed: Inventory workflow schema is not up to date in 6.0
    (https://issues.rudder.io/issues/16708[#16708])
* Fixed: Plugins architecture documentation is hard to find
    (https://issues.rudder.io/issues/16639[#16639])
* Fixed: Inventory workflow documentation outdated for Rudder 5.0
    (https://issues.rudder.io/issues/16679[#16679])
* Fixed: Install command for plugin is wrong in the doc
    (https://issues.rudder.io/issues/16545[#16545])
* Fixed: Do not advise to run "rudder agent start" after installation
    (https://issues.rudder.io/issues/16544[#16544])

==== Web - Technique editor

* Fixed: HereString are not generated properly
    (https://issues.rudder.io/issues/16817[#16817])

==== Web - Maintenance

* Fixed: Error when restoring an archive in 6.0
    (https://issues.rudder.io/issues/16816[#16816])
* Fixed: In zip archive, all files have size 0
    (https://issues.rudder.io/issues/16805[#16805])

==== Web - Nodes & inventories

* Fixed: Add 6.0 inventories in rudder fusion test folder
    (https://issues.rudder.io/issues/16804[#16804])
* Fixed: If an inventory has no signature, the error message in log is thousands of line long
    (https://issues.rudder.io/issues/16783[#16783])
* Fixed: Missing log when inventory signature check fails
    (https://issues.rudder.io/issues/16624[#16624])

==== Web - UI & UX

* Fixed: Missing timezone in reports caption header
    (https://issues.rudder.io/issues/16777[#16777])
* Fixed: Updating some settings leads to an eventlog with empty  "Value" field
    (https://issues.rudder.io/issues/16354[#16354])

==== Relay server or API

* Fixed: Remote run always timeout for nodes behing relays
    (https://issues.rudder.io/issues/16760[#16760])
* Fixed: Parsing error of agent output when it contains warn of info logs
    (https://issues.rudder.io/issues/16644[#16644])
* Fixed: On centos8 relay, service relayd is not started after installation
    (https://issues.rudder.io/issues/16509[#16509])
* Fixed: Default relayd config should have disabled reporting output
    (https://issues.rudder.io/issues/16511[#16511])

==== Architecture - Refactoring

* Fixed: Compilation warning for unused variable in WriteTechniquesTest.scala
    (https://issues.rudder.io/issues/16759[#16759])

==== Web - Compliance & node report

* Fixed: Trigger remote run in node details says it timeouts
    (https://issues.rudder.io/issues/16448[#16448])
* Fixed: Set HTTPS mode to pure HTTPS for install, rather than HTTPS+syslogcompat
    (https://issues.rudder.io/issues/16527[#16527])

==== System integration

* Fixed: We still talk about cmdb-endpoint in rudder 6.0 properties
    (https://issues.rudder.io/issues/16715[#16715])

==== Web - Config management

* Fixed: Garbled generated policies in 6.0
    (https://issues.rudder.io/issues/16700[#16700])
* Fixed: Archive of techniques miss some files needed for a the technique editor
    (https://issues.rudder.io/issues/16582[#16582])

==== API

* Fixed: Add authorized network configuration in settings api
    (https://issues.rudder.io/issues/16667[#16667])
* Fixed: Error when creating a directive with a given id from the API
    (https://issues.rudder.io/issues/16592[#16592])
* Fixed: Technique editor fails with internal error
    (https://issues.rudder.io/issues/16701[#16701])

==== Performance and scalability

* Fixed: NullPointerException with hundreds of inventories at once
    (https://issues.rudder.io/issues/14991[#14991])
* Fixed: Unnecessary compliance computations when historization of Node Compliance is disabled
    (https://issues.rudder.io/issues/16643[#16643])
* Fixed: Unnecessary compliance computations when historization of Node Compliance is disabled
    (https://issues.rudder.io/issues/16643[#16643])
* Fixed: CachedFindRuleNodeStatusReports is a huge source of contention
    (https://issues.rudder.io/issues/16557[#16557])
* Fixed: Unnecessary call to trim on empty string when creating executionBatch
    (https://issues.rudder.io/issues/16522[#16522])
* Fixed: Node never updated because of nonEmpty in place of isEmpty
    (https://issues.rudder.io/issues/16537[#16537])
* Fixed: we should not use .size to check if a collection is empty
    (https://issues.rudder.io/issues/16524[#16524])
* Fixed: JVM GC cannot clean objects in scope in a for { } yield {} even if they are not referenced anymore
    (https://issues.rudder.io/issues/16513[#16513])
* Fixed: StatusReportTest leads to inconsistent results
    (https://issues.rudder.io/issues/16496[#16496])

==== Miscellaneous

* Fixed: Improve performance of policy generation writer
    (https://issues.rudder.io/issues/16382[#16382])
* Fixed: Message indicating plugin is incompatible at the end of every plugin install from the repo
    (https://issues.rudder.io/issues/16630[#16630])
* Fixed: Timeout for `NuCommand` test is too short
    (https://issues.rudder.io/issues/16622[#16622])
* Fixed: Merge error in #16606
    (https://issues.rudder.io/issues/16607[#16607])

==== Architecture - Dependencies

* Fixed: Port Rudder to Scala 2.13
    (https://issues.rudder.io/issues/16491[#16491])

==== Security

* Fixed: 5.0.15 and lower agents can not update when managed by a 6.0+ server or relay
    (https://issues.rudder.io/issues/16716[#16716])

==== System techniques

* Fixed: Relays in 5.0 managed by a 6.0 root server are unable to send their reports
    (https://issues.rudder.io/issues/16744[#16744])
* Fixed: In HTTPS + syslog mode, agents without the http support (like 5.0) don't have their syslog configured
    (https://issues.rudder.io/issues/16710[#16710])
* Fixed: After first relay configuration, allowed networks are not taken into account
    (https://issues.rudder.io/issues/16553[#16553])
* Fixed: Shared files are broken in relayd
    (https://issues.rudder.io/issues/16549[#16549])
* Fixed: Unexpected reports on postgresql when changing allowed network in 6.0
    (https://issues.rudder.io/issues/16530[#16530])
* Fixed: Missing report on "Synchronize files" on simple relays when shared-files are empty
    (https://issues.rudder.io/issues/16518[#16518])

==== Techniques

* Fixed: Technique SNMP installation doesn't work on non-debian like system
    (https://issues.rudder.io/issues/16689[#16689])

==== Generic methods

* Fixed: New parameter_type option for GM are not detected
    (https://issues.rudder.io/issues/16812[#16812])
* Fixed: Command parameter should not be called "Command name"
    (https://issues.rudder.io/issues/16645[#16645])
* Fixed: Make error in no-reporting mode info instead of warns
    (https://issues.rudder.io/issues/16608[#16608])

==== Technique editor - UI/UX

* Fixed: Technique resource modifications do not activate the save button
    (https://issues.rudder.io/issues/16573[#16573])

==== Generic methods - File Management

* Fixed: Jinja2 templating script is always run with /usr/bin/python
    (https://issues.rudder.io/issues/16120[#16120])

==== Generic methods - Package Management

* Fixed:  Package modules shebangs do not work when python3 is not installed in 6.0
    (https://issues.rudder.io/issues/16542[#16542])
* Fixed: Package modules shebangs do not work when python3 is not installed
    (https://issues.rudder.io/issues/16541[#16541])
* Fixed: yum package module is not compatible with systems having only python2
    (https://issues.rudder.io/issues/16534[#16534])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Romain Brucker

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.0.2 (2020-01-10)

=== Changes

==== Documentation

* Document Amazon Linux support state
    (https://issues.rudder.io/issues/16487[#16487])

==== Relay server or API

* Add default values for relayd configs whenever possible
    (https://issues.rudder.io/issues/16480[#16480])
* Add a cleanup job for old reports and inventories in relayd
    (https://issues.rudder.io/issues/16479[#16479])

==== Web - UI & UX

* Display compliance bar in Node details
    (https://issues.rudder.io/issues/16326[#16326])
* Improve display of status in technical logs table
    (https://issues.rudder.io/issues/15964[#15964])

==== Rudder language

* Prettify output of rudder-lang compiler
    (https://issues.rudder.io/issues/16461[#16461])
* fuzzy matching to help with error messages
    (https://issues.rudder.io/issues/16449[#16449])

==== Performance and scalability

* Backport test on Hooks to 5.0
    (https://issues.rudder.io/issues/16438[#16438])

==== Web - Config management

* Markdown numbered list description are not correctly rendered
    (https://issues.rudder.io/issues/16303[#16303])

==== Agent

* Add a cleanup job for old reports that have not been sent
    (https://issues.rudder.io/issues/16242[#16242])

=== Bug fixes

==== Packaging

* Fixed: Upgrade from 5.0.x to 6.0.x on debian fail because of conflicting file
    (https://issues.rudder.io/issues/16500[#16500])
* Fixed: Missing recursive option when removing old ncf hooks at rudder-upgrade
    (https://issues.rudder.io/issues/16482[#16482])
* Fixed: Remove unused webapp postinst parameters
    (https://issues.rudder.io/issues/16471[#16471])
* Fixed: Use binaries from /opt/rudder/bin in systemd services
    (https://issues.rudder.io/issues/16459[#16459])
* Fixed: We mention HTTP/S instead of HTTPS in install logs
    (https://issues.rudder.io/issues/16485[#16485])
* Fixed: Add Amazon Linux support to ncf and techniques
    (https://issues.rudder.io/issues/12990[#12990])

==== Agent

* Fixed: Inventory fails with errors on CentOS/RHEL 8
    (https://issues.rudder.io/issues/16457[#16457])

==== System integration

* Fixed: Error about /var/rudder/reports/ready/ on CentOS when migrating from Rudder 5.0 to 6.0
    (https://issues.rudder.io/issues/16443[#16443])
* Fixed: Webapp can't connect to postgres before first agent run
    (https://issues.rudder.io/issues/16450[#16450])

==== Server components

* Fixed: Policy generation impossible after fresh install on Ubuntu 16.04 (due to ubuntu's Java 9 package)
    (https://issues.rudder.io/issues/16466[#16466])
* Fixed: Output redirection of rudder-init is broken
    (https://issues.rudder.io/issues/16472[#16472])
* Fixed: Upgrade fails because we try to insert an LDAP property that is already there
    (https://issues.rudder.io/issues/16464[#16464])

==== Documentation

* Fixed: Server install doc still mentions SLES 11 which is not supported anymore
    (https://issues.rudder.io/issues/16469[#16469])
* Fixed: Warn user about know bug in 6.0.1 and installation workaround
    (https://issues.rudder.io/issues/16451[#16451])

==== Architecture - Refactoring

* Fixed: We use not the correct InputStream at several place
    (https://issues.rudder.io/issues/16492[#16492])

==== Web - Config management

* Fixed: Missing stored git commit leads to fatal exception
    (https://issues.rudder.io/issues/16493[#16493])
* Fixed: Set HTTPS mode by default for new install, keep syslog for upgrade
    (https://issues.rudder.io/issues/16458[#16458])
* Fixed: Cannot import technique with missing component in 6.0
    (https://issues.rudder.io/issues/16383[#16383])
* Fixed: Cannot add a parameter to an existing technique
    (https://issues.rudder.io/issues/16453[#16453])

==== Web - Nodes & inventories

* Fixed: Amazon Linux appears as "Other Linux 2" in nodes list
    (https://issues.rudder.io/issues/16486[#16486])

==== Performance and scalability

* Fixed: Computation of ComplianceLevel generates too many objects
    (https://issues.rudder.io/issues/16468[#16468])
* Fixed: A lot of data is computed and stored in Policy object, that is either never used, or used only once
    (https://issues.rudder.io/issues/16467[#16467])

==== API

* Fixed: HTTPS reporting setting not working
    (https://issues.rudder.io/issues/16465[#16465])

==== Web - UI & UX

* Fixed: Title are too big in doc blocks of the settings page
    (https://issues.rudder.io/issues/16113[#16113])
* Fixed: Technique editor truncates the text in the generic method, even if the space is still available
    (https://issues.rudder.io/issues/16101[#16101])

==== Rudder language

* Fixed: Make paths configurable in the rudder-lang tester script
    (https://issues.rudder.io/issues/16334[#16334])

==== System techniques

* Fixed: Postinst scripts do not set the postgres password
    (https://issues.rudder.io/issues/16475[#16475])
* Fixed: Postgresql service name is not detected properly on SLES 12 
    (https://issues.rudder.io/issues/16470[#16470])
* Fixed: When syslog reporting is disabled, we should also remove remove_limits.conf from rsyslog config
    (https://issues.rudder.io/issues/16116[#16116])

==== Techniques

* Fixed: Syntax error in clockConfiguration.cf line 99
    (https://issues.rudder.io/issues/16462[#16462])

==== Generic methods - Package Management

* Fixed: zypper_pattern module does not work in python3
    (https://issues.rudder.io/issues/16278[#16278])

==== Technique editor - UI/UX

* Fixed: "Technique diverges" popup is broken
    (https://issues.rudder.io/issues/15558[#15558])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Laurent Santoul
* Marius Rieck
* Mike Kingsbury

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.0.1 (2019-12-20)

=== Changes

==== Packaging

* Upgrade agent to CFEngine 3.12.3
    (https://issues.rudder.io/issues/16369[#16369])

==== Agent

* Add a test for CFEngine errors in relayd parser
    (https://issues.rudder.io/issues/16302[#16302])

=== Bug fixes

==== Packaging

* Fixed: try stopping jetty and slapd with init script before enabling then through systemd
    (https://issues.rudder.io/issues/16426[#16426])
* Fixed: rudder-server-relay has a non-existing dependency on RHEL8
    (https://issues.rudder.io/issues/16415[#16415])
* Fixed: Upgrade script fails when some properties are missing from the inventory conf file
    (https://issues.rudder.io/issues/16388[#16388])
* Fixed: Rudder-agent postinst fails on non-systemd OS
    (https://issues.rudder.io/issues/16387[#16387])

==== Web - Technique editor

* Fixed: Technique are lost when a new one is created because of selinux (centos 7 and 8)
    (https://issues.rudder.io/issues/16393[#16393])
* Fixed: Technique editor access authorization seems incorrect 
    (https://issues.rudder.io/issues/16386[#16386])

==== Documentation

* Fixed: Warn people that for now, upgrade of Rudder from 5.0 is broken
    (https://issues.rudder.io/issues/16431[#16431])
* Fixed: Update rudder-setup doc
    (https://issues.rudder.io/issues/16373[#16373])
* Fixed: Update release policy
    (https://issues.rudder.io/issues/16358[#16358])

==== Techniques

* Fixed: Technique resource are not copied to the correct path
    (https://issues.rudder.io/issues/16446[#16446])
* Fixed: Missing report for "Installation" conponent in ssh technique
    (https://issues.rudder.io/issues/16385[#16385])

==== Web - UI & UX

* Fixed: Missing timezone in generation "started at" 
    (https://issues.rudder.io/issues/16392[#16392])
* Fixed:  scroll-issue after policy-rebuild on the GUI
    (https://issues.rudder.io/issues/16434[#16434])
* Fixed: Wrong vertical alignement of numerous items
    (https://issues.rudder.io/issues/16406[#16406])
* Fixed: Incorrect hour display in node list's last seen column
    (https://issues.rudder.io/issues/16389[#16389])
* Fixed: Title are too big in doc blocks of the settings page
    (https://issues.rudder.io/issues/16113[#16113])
* Fixed: "Reload techniques" button has a slightly different color
    (https://issues.rudder.io/issues/16320[#16320])

==== Web - Compliance & node report

* Fixed: Not report compliance because of scala.UninitializedFieldError
    (https://issues.rudder.io/issues/16439[#16439])

==== Plugins integration

* Fixed: Rudder-pkg fails to parse new plugin nightly version
    (https://issues.rudder.io/issues/16422[#16422])
* Fixed: Rudder-pkg fails to show installed plugins when they are not available in the configurated repo if any
    (https://issues.rudder.io/issues/16398[#16398])

==== Server components

* Fixed: Rudder package list command should not list plugins that are not available for the user
    (https://issues.rudder.io/issues/16391[#16391])

==== Web - Config management

* Fixed: Invalid value in class prefix when there is a double quote in parameter
    (https://issues.rudder.io/issues/16384[#16384])

==== System techniques

* Fixed: System techniques still refer to an historical file
    (https://issues.rudder.io/issues/16436[#16436])

==== Agent

* Fixed: syntax error in rudder server-disable-policy-distribution
    (https://issues.rudder.io/issues/16444[#16444])

==== Technique editor - API

* Fixed: Technique does not appear anymore if some ressources are defined
    (https://issues.rudder.io/issues/16425[#16425])

==== Technique editor - UI/UX

* Fixed: Make Result condition fields more readable
    (https://issues.rudder.io/issues/16330[#16330])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Nigel Mundy
* Marius Rieck
* Romain Brucker

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.0.0 (2019-12-09)

=== Changes

==== Packaging

* Reduplicate cfengine binaries
    (https://issues.rudder.io/issues/16344[#16344])
* Use system curl and openssl on RHEL8
    (https://issues.rudder.io/issues/16080[#16080])
* Automatically restart relayd in case of crash
    (https://issues.rudder.io/issues/16081[#16081])
* Stop listenning for inventories on port 80
    (https://issues.rudder.io/issues/16122[#16122])

==== Documentation

* 6.0 release in docs
    (https://issues.rudder.io/issues/16375[#16375])
* Render release notes in the changelog
    (https://issues.rudder.io/issues/16300[#16300])
* relayd admin guide
    (https://issues.rudder.io/issues/16217[#16217])
* Remove multiserver install procedure
    (https://issues.rudder.io/issues/16209[#16209])
* Document new reporting protocol
    (https://issues.rudder.io/issues/16202[#16202])
* Document inventory variables
    (https://issues.rudder.io/issues/15596[#15596])
* Update URL of our GPG key
    (https://issues.rudder.io/issues/16329[#16329])
* Update Rust environment setup instructions
    (https://issues.rudder.io/issues/16196[#16196])
* Update ncf README after merge into Rudder
    (https://issues.rudder.io/issues/16097[#16097])
* Fix link to external doc in technique editor
    (https://issues.rudder.io/issues/16098[#16098])

==== Rudder language

* Add license information to rudder-lang
    (https://issues.rudder.io/issues/16305[#16305])
* Improve rendering of rudder-lang readme
    (https://issues.rudder.io/issues/16304[#16304])

==== Web - Config management

* Add rollback to event log pagination
    (https://issues.rudder.io/issues/15733[#15733])
* Unsigned inventories must not be accepted anymore in 6.0
    (https://issues.rudder.io/issues/16260[#16260])
* Display 'long' description  as markdown
    (https://issues.rudder.io/issues/16216[#16216])

==== Web - UI & UX

* Regroup tabs from "Hardware" to "Virtual Machines" into one
    (https://issues.rudder.io/issues/16223[#16223])
* Make the "Add node property" form more visible
    (https://issues.rudder.io/issues/16194[#16194])
* Remove unnecessary borders and padding around the Technique Editor
    (https://issues.rudder.io/issues/16188[#16188])
* Improve current node details UI
    (https://issues.rudder.io/issues/16087[#16087])
* Update URLs to our websites
    (https://issues.rudder.io/issues/16121[#16121])

==== Architecture - Dependencies

* Upgrade to ZIO 1.0-RC17
    (https://issues.rudder.io/issues/16206[#16206])

==== System techniques

* OpenSUSE should be detected as "suse" os family
    (https://issues.rudder.io/issues/16249[#16249])

==== Technique editor - API

* Type for parameters of methods in technique editor
    (https://issues.rudder.io/issues/16314[#16314])
* Make ncf.py usable by rudder-lang
    (https://issues.rudder.io/issues/15933[#15933])

==== Generic methods

* Add verbosity level in the rudder logger
    (https://issues.rudder.io/issues/15126[#15126])

==== Technique editor - UI/UX

* Improve display of parameter name in technique editor
    (https://issues.rudder.io/issues/16277[#16277])

==== Generic methods - Package Management

* Improve zypper pattern error log
    (https://issues.rudder.io/issues/15447[#15447])

=== Bug fixes

==== Packaging

* Fixed: Debian 10 doesn't know how to install java if it's not already installed
    (https://issues.rudder.io/issues/16366[#16366])
* Fixed: service rudder-jetty is not activated after upgrade from 5.0 to 6.0 on centos7
    (https://issues.rudder.io/issues/16364[#16364])
* Fixed: Upgrade script fails on unknown git branch
    (https://issues.rudder.io/issues/16363[#16363])
* Fixed: Empty maxsize parameter in ldap conf after update to 6.0
    (https://issues.rudder.io/issues/16350[#16350])
* Fixed: rudder-webapp should obsolete rudder-inventory-endpoint
    (https://issues.rudder.io/issues/16343[#16343])
* Fixed: Add a dependency on semanage for relay on RHEL
    (https://issues.rudder.io/issues/16335[#16335])
* Fixed: LDAP error during upgrade
    (https://issues.rudder.io/issues/15533[#15533])
* Fixed: Missing dependency on systemd for recent Ubuntu/Debian systems
    (https://issues.rudder.io/issues/14653[#14653])
* Fixed: Postrm script want to use systemd on Ubuntu 14.04
    (https://issues.rudder.io/issues/14139[#14139])
* Fixed: Inventory should not require the presence of /etc/profile
    (https://issues.rudder.io/issues/16162[#16162])
* Fixed: Upgrading Rudder 5.0.12 to 5.1-nightly on Debian9 fails
    (https://issues.rudder.io/issues/15569[#15569])
* Fixed: Metrics reporting is broken on CentOS 7
    (https://issues.rudder.io/issues/14798[#14798])
* Fixed: Remove unused 'argparse' dependency in rudder-pkg
    (https://issues.rudder.io/issues/11150[#11150])
* Fixed: rudder-api-client is missing basic dh rule in its rule file
    (https://issues.rudder.io/issues/16150[#16150])
* Fixed: rudder-init reports that it is a distributed setup when its not with rudder 6.0
    (https://issues.rudder.io/issues/15987[#15987])
* Fixed: On error, rudder-upgrade stops without error message
    (https://issues.rudder.io/issues/14560[#14560])
* Fixed: Broken relay shared-files cleanup cron
    (https://issues.rudder.io/issues/16149[#16149])
* Fixed: relay postinst fails on SLES15
    (https://issues.rudder.io/issues/16108[#16108])
* Fixed: Systemd sandboxing options prevent remote-run from executing
    (https://issues.rudder.io/issues/16148[#16148])

==== Agent

* Fixed: At  install agents are not printing anymore the mandatory configuration to do
    (https://issues.rudder.io/issues/16318[#16318])
* Fixed: Recommend bash-completion package with rudder-agent
    (https://issues.rudder.io/issues/16239[#16239])
* Fixed: Add http reporting agent capability
    (https://issues.rudder.io/issues/16173[#16173])
* Fixed: Allow disabling the agent without stopping cf-serverd
    (https://issues.rudder.io/issues/15188[#15188])
* Fixed: Remove wsgi from relay dependencies
    (https://issues.rudder.io/issues/16157[#16157])
* Fixed: Running /opt/rudder/bin/rudder-debug-info outside of /opt/rudder/bin fails 
    (https://issues.rudder.io/issues/14830[#14830])
* Fixed: Rudder-metrics-report does not work in python3
    (https://issues.rudder.io/issues/16140[#16140])
* Fixed: File content directive - Audit mode is not correctly supported
    (https://issues.rudder.io/issues/11086[#11086])
* Fixed: File content directive - Audit mode is not correctly supported
    (https://issues.rudder.io/issues/11086[#11086])
* Fixed: Add capabilities as base conditions
    (https://issues.rudder.io/issues/15032[#15032])
* Fixed: In https reporting mode, the agent outputs html raw text at the end of output
    (https://issues.rudder.io/issues/16355[#16355])
* Fixed: rudder agent script should reset locale to C
    (https://issues.rudder.io/issues/16333[#16333])
* Fixed: Rudder autocompletion does not complete automatically the inputs
    (https://issues.rudder.io/issues/16250[#16250])
* Fixed: Typo in rudder agent health output
    (https://issues.rudder.io/issues/16229[#16229])
* Fixed: Command rudder agent start shoud list activated/deactivated services
    (https://issues.rudder.io/issues/16145[#16145])
* Fixed: Cleanup disable server flag
    (https://issues.rudder.io/issues/16170[#16170])
* Fixed: "rudder server trigger-policy-generation/reload-groups" output a curl error if apache is stopped
    (https://issues.rudder.io/issues/15535[#15535])
* Fixed: We should not start agent daemons outside of the service
    (https://issues.rudder.io/issues/16128[#16128])
* Fixed: factory-reset does not work on AIX
    (https://issues.rudder.io/issues/14574[#14574])
* Fixed: Negative execution time on AIX
    (https://issues.rudder.io/issues/12996[#12996])
* Fixed: "rudder agent check" should not require /etc/profile presence
    (https://issues.rudder.io/issues/16160[#16160])
* Fixed: rudder relay start syntax error
    (https://issues.rudder.io/issues/16159[#16159])
* Fixed: Even when rudder agent is disabled, it runs cf-promises every 5 minutes
    (https://issues.rudder.io/issues/15854[#15854])

==== Performance and scalability

* Fixed: When the number of file descriptor openable at the same time is too low, we can get a confusing error at policy generation
    (https://issues.rudder.io/issues/15630[#15630])
* Fixed: On a loaded system, the compliance computation is fairly expensive
    (https://issues.rudder.io/issues/16208[#16208])
* Fixed: Log metrics about configuration object at start of generation
    (https://issues.rudder.io/issues/16213[#16213])
* Fixed: Inefficient computing of compliance on home page
    (https://issues.rudder.io/issues/16201[#16201])
* Fixed: Missing timing info in logs for Home Page
    (https://issues.rudder.io/issues/16199[#16199])
* Fixed: Big memory usage when fetching/writing node configuration and expected reports
    (https://issues.rudder.io/issues/16083[#16083])
* Fixed: Improve documentation in rudder-web.properties about backup folder
    (https://issues.rudder.io/issues/16072[#16072])
* Fixed: Rationalize the handling of variables during policy generation
    (https://issues.rudder.io/issues/15798[#15798])
* Fixed: Improve performance of logs parsing by rsyslog
    (https://issues.rudder.io/issues/16255[#16255])

==== Relay server or API

* Fixed: On relays /var/rudder/share files are not executable for group
    (https://issues.rudder.io/issues/16136[#16136])
* Fixed: Missing SELinux/systemd context for relayd on shared-files folder
    (https://issues.rudder.io/issues/16227[#16227])

==== Documentation

* Fixed: Document reporting protocol options
    (https://issues.rudder.io/issues/16284[#16284])
* Fixed: Missing documentation on openssl incompatibilities between 4.x and 5.0
    (https://issues.rudder.io/issues/16224[#16224])
* Fixed: Troubleshooting agent-server communication issues section in the doc is empty
    (https://issues.rudder.io/issues/16268[#16268])
* Fixed: Docs recommend using multiserver setup while its benefit may be dubious
    (https://issues.rudder.io/issues/16207[#16207])
* Fixed: Backup procedure documentation is incorrect
    (https://issues.rudder.io/issues/15271[#15271])
* Fixed: Debian/Ubuntu install doc fails if lsb_release is not installed
    (https://issues.rudder.io/issues/14632[#14632])
* Fixed: Document that a plugin is required for user roles and LDAP authentification
    (https://issues.rudder.io/issues/14812[#14812])
* Fixed: Document the usage of environment variables during installation
    (https://issues.rudder.io/issues/10015[#10015])
* Fixed: Typo in link to mustache method
    (https://issues.rudder.io/issues/14633[#14633])
* Fixed: Display 6.0 as 6.0-beta in doc menu
    (https://issues.rudder.io/issues/16156[#16156])
* Fixed: Missing link to the beginning of the guide in getting strated home page
    (https://issues.rudder.io/issues/15408[#15408])
* Fixed: Document that a full policy regeneration is necessary after a backup restoration
    (https://issues.rudder.io/issues/15984[#15984])
* Fixed: Use MB instead of mB for megabytes in the doc
    (https://issues.rudder.io/issues/14161[#14161])
* Fixed: Document specific purging configuration for log_* reports
    (https://issues.rudder.io/issues/15974[#15974])
* Fixed: Document the hook that triggers an agent run on update
    (https://issues.rudder.io/issues/14332[#14332])
* Fixed: How to setup a development's environment doc
    (https://issues.rudder.io/issues/16141[#16141])
* Fixed: Document that variable_dict_from_file_type#csv needs CRLF
    (https://issues.rudder.io/issues/15657[#15657])
* Fixed: Fix internal doc links in generic methods
    (https://issues.rudder.io/issues/16092[#16092])

==== Web - Config management

* Fixed: Race condition in technique variable filling
    (https://issues.rudder.io/issues/16374[#16374])
* Fixed: policy generation logs still mention promises
    (https://issues.rudder.io/issues/16307[#16307])
* Fixed: The "migrate" field should not be displayed on directive creation
    (https://issues.rudder.io/issues/14859[#14859])
* Fixed: Audit/Enforce button in directive page should be similar to node page
    (https://issues.rudder.io/issues/13531[#13531])
* Fixed: Mark configuration-repository git repo options deprecated 
    (https://issues.rudder.io/issues/13870[#13870])
* Fixed: Dubious duplicate log message about hook
    (https://issues.rudder.io/issues/16091[#16091])

==== Web - Compliance & node report

* Fixed: error when searching by date on Technical Logs
    (https://issues.rudder.io/issues/16353[#16353])
* Fixed: Deadlock on compliance computing
    (https://issues.rudder.io/issues/16256[#16256])
* Fixed: Error when retrieving reports at application start
    (https://issues.rudder.io/issues/16189[#16189])
* Fixed: Directive appear in "mixed" mode in a rule applied on only one node
    (https://issues.rudder.io/issues/14379[#14379])
* Fixed: Rule tag is "Enforce" whereas it has both enforce and audit nodes
    (https://issues.rudder.io/issues/15124[#15124])
* Fixed: Deleted directives are not always removed from rule (and are then not actionnable)
    (https://issues.rudder.io/issues/14790[#14790])
* Fixed: No compliance from a Rule with only one Directive (from a technique created in the editor) when the Directive is also applied in another Rule
    (https://issues.rudder.io/issues/11917[#11917])

==== Web - Technique editor

* Fixed: Default values of parameters in methods cannot be used in technique editor
    (https://issues.rudder.io/issues/16316[#16316])
* Fixed: Close button in Generic Method tab is not working
    (https://issues.rudder.io/issues/16019[#16019])
* Fixed: We can save a technique with empty name when we add a resource
    (https://issues.rudder.io/issues/16135[#16135])

==== Web - Nodes & inventories

* Fixed: UI settings for new certificate validation system variable
    (https://issues.rudder.io/issues/16306[#16306])
* Fixed: Exception "fiberFailed" when running agent from UI
    (https://issues.rudder.io/issues/16222[#16222])
* Fixed: Error in group page when searching "Last inventory date" + "is defined"
    (https://issues.rudder.io/issues/14267[#14267])
* Fixed: In node details, clicking on policy server id redirect to original node
    (https://issues.rudder.io/issues/15953[#15953])

==== System integration

* Fixed: Set HTTP reporting protocol by default on new rudder 6.0 installation
    (https://issues.rudder.io/issues/16294[#16294])
* Fixed: Nova license path in log is misleading for plugin licenses
    (https://issues.rudder.io/issues/15989[#15989])
* Fixed:  Remove deprecated rudder property configuration options
    (https://issues.rudder.io/issues/16166[#16166])
* Fixed: We still have an LDAP entry "ou=Nodes Configuration,..." which is not used anymore
    (https://issues.rudder.io/issues/15878[#15878])
* Fixed: os.makedirs 'exist_ok' parameter does not exist in python 2.7
    (https://issues.rudder.io/issues/16161[#16161])
* Fixed: Not all rudder-related reports are sent to /var/log/rudder/reports/all.log
    (https://issues.rudder.io/issues/16214[#16214])
* Fixed: On centos7 fresh install, generation fails because relayd is not started
    (https://issues.rudder.io/issues/16104[#16104])

==== Rudder language

* Fixed: Fix warnings in rudder-language
    (https://issues.rudder.io/issues/16308[#16308])

==== Web - Maintenance

* Fixed: Filtering on eventlogs doesn't filter
    (https://issues.rudder.io/issues/15944[#15944])
* Fixed: JS Error when setting the "Send anonymous usage statistics " value
    (https://issues.rudder.io/issues/13508[#13508])

==== Architecture - Internal libs

* Fixed: Deadlock when application starts
    (https://issues.rudder.io/issues/16291[#16291])

==== API

* Fixed: Could not get Group tree details through API
    (https://issues.rudder.io/issues/16269[#16269])
* Fixed: We cannot get the rules categories with the API
    (https://issues.rudder.io/issues/16164[#16164])

==== Plugins integration

* Fixed: Rudder package fails on a python error
    (https://issues.rudder.io/issues/16261[#16261])
* Fixed: Plugin id on plugin page should be more human-friendly
    (https://issues.rudder.io/issues/11101[#11101])

==== Web - UI & UX

* Fixed: Inconsistent capitalization in menu items
    (https://issues.rudder.io/issues/16210[#16210])
* Fixed: In Node settings, "override global value" fields should have the same display 
    (https://issues.rudder.io/issues/16191[#16191])
* Fixed: Accepted inventory without matching rudder node appears in quicksearch
    (https://issues.rudder.io/issues/14431[#14431])
* Fixed: OS version sort in nodes list is broken
    (https://issues.rudder.io/issues/14433[#14433])
* Fixed: Folded subsections in directive forms are not visible enough
    (https://issues.rudder.io/issues/15107[#15107])
* Fixed: If an LDAP attribute is missing the related LDAP errors are not reported in UI (silent fail)
    (https://issues.rudder.io/issues/10067[#10067])
* Fixed: Improve Rules tabs visibility
    (https://issues.rudder.io/issues/11644[#11644])

==== Server components

* Fixed: If a relay is deleted (via node->delete), its system rule remains
    (https://issues.rudder.io/issues/14464[#14464])
* Fixed: Remote run does not try to use the system token
    (https://issues.rudder.io/issues/13825[#13825])

==== Miscellaneous

* Fixed: When the api authorization plugin is disabled tokens become read only
    (https://issues.rudder.io/issues/12440[#12440])

==== System techniques

* Fixed: We need to restart rudder-jetty when ldap password is updated
    (https://issues.rudder.io/issues/16332[#16332])
* Fixed: Agent policy loading is done in the wrong order
    (https://issues.rudder.io/issues/16288[#16288])
* Fixed: Agent is not correctly aborted when repaired is happening in audit mode
    (https://issues.rudder.io/issues/16178[#16178])
* Fixed: system technique to update ldap passwords fails
    (https://issues.rudder.io/issues/16107[#16107])

==== Techniques

* Fixed: Creating a user without home directory fails
    (https://issues.rudder.io/issues/11013[#11013])
* Fixed: The file from Rudder server technique may change permission of the destination parent directory instead of the file
    (https://issues.rudder.io/issues/13612[#13612])

==== Generic methods

* Fixed: condition_from_commands is not running any command in audit mode
    (https://issues.rudder.io/issues/16359[#16359])
* Fixed: Add a generic method to escape regex chars in a string
    (https://issues.rudder.io/issues/16275[#16275])
* Fixed: Using ${match.x} in generic method causes an error message in the agent output, and prevents multiple reporting based on this generic method
    (https://issues.rudder.io/issues/14286[#14286])
* Fixed: Missing edit_lines promises in dry-run lib
    (https://issues.rudder.io/issues/16181[#16181])
* Fixed: http_request_content_headers test tries to get content from a removed site
    (https://issues.rudder.io/issues/16082[#16082])
* Fixed: Fix unexpected report in osquery method
    (https://issues.rudder.io/issues/15658[#15658])

==== Technique editor - UI/UX

* Fixed: Clicking twice on "New technique" in the editor breaks the method drag and drop
    (https://issues.rudder.io/issues/16118[#16118])
* Fixed: Technique editor is broken due to a js error
    (https://issues.rudder.io/issues/16187[#16187])
* Fixed: Deleting a technique in the technique editor just after its creation fails
    (https://issues.rudder.io/issues/15178[#15178])

==== Technique editor - API

* Fixed: Custom methods don't appear in technique editor anymore
    (https://issues.rudder.io/issues/16336[#16336])
* Fixed: Wrong condition on component used when importing technique
    (https://issues.rudder.io/issues/16323[#16323])
* Fixed: Prevent setting an empty report component
    (https://issues.rudder.io/issues/15509[#15509])

==== Generic methods - File Management

* Fixed: ACLS methods are not working in recurse mode
    (https://issues.rudder.io/issues/16220[#16220])
* Fixed: Copying a file to a directory using the "file_from_shared_folder" method results in a success report even if nothing is done
    (https://issues.rudder.io/issues/16267[#16267])
* Fixed: Do not store response when response code is an error in file_fom_http_server
    (https://issues.rudder.io/issues/12780[#12780])

==== Generic methods - Service Management

* Fixed: Service reload tests are failing in 6.0 on debian like systems
    (https://issues.rudder.io/issues/16271[#16271])
* Fixed: Ensure service (re)started does now work if systemd hit "start-limit"
    (https://issues.rudder.io/issues/11587[#11587])

==== Generic methods - Package Management

* Fixed: Missing report in "Package check installed" generic methods
    (https://issues.rudder.io/issues/16137[#16137])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Tobias Ell
* Janos Mattyasovszky
* P C
* Hamlyn Mootoo
* Jean Cardona
* Jérémy HOCDÉ
* Mikaël Mantel
* Didier METRAL
* Nigel Mundy
* Alexandre BRIANCEAU
* Florian Heigl

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.0.0.beta1 (2019-11-04)

=== Changes

==== Packaging

* Cleanup rudder-upgrade
    (https://issues.rudder.io/issues/15875[#15875])
* Cleanup roles in packaging
    (https://issues.rudder.io/issues/15829[#15829])
* Add trace parameters to make calls during build
    (https://issues.rudder.io/issues/15729[#15729])
* Increase default password size for db passwords
    (https://issues.rudder.io/issues/15683[#15683])
* Cleanup packages postinstall 
    (https://issues.rudder.io/issues/15388[#15388])
* Cleanup webapp postinstall
    (https://issues.rudder.io/issues/15379[#15379])
* Cleanup rudder-init
    (https://issues.rudder.io/issues/15338[#15338])
* Merge rudder-ldap with rudder-webapp
    (https://issues.rudder.io/issues/14989[#14989])
* Remove maven dependency at package time
    (https://issues.rudder.io/issues/14973[#14973])
* Remove automatic provides generation from rpm packages
    (https://issues.rudder.io/issues/14982[#14982])
* change rudder-webapp to be arch dependant
    (https://issues.rudder.io/issues/14950[#14950])
* Deduplicate cfengine binaries
    (https://issues.rudder.io/issues/14872[#14872])
* Not all ncf source should be included in rudder-webapp
    (https://issues.rudder.io/issues/14913[#14913])
* Move away from python 2 to python 3
    (https://issues.rudder.io/issues/14881[#14881])
* Remove cf-monitored to save space
    (https://issues.rudder.io/issues/14837[#14837])
* Cleanup rudder agent postinst
    (https://issues.rudder.io/issues/14836[#14836])
* Beautify pg_hba.conf 
    (https://issues.rudder.io/issues/14780[#14780])
* Remove initial promises from rudder agent package
    (https://issues.rudder.io/issues/14182[#14182])
* Remove initial promises from rudder agent package
    (https://issues.rudder.io/issues/14182[#14182])
* Remove jdk installation on debian8 builder
    (https://issues.rudder.io/issues/14761[#14761])
* Cleanup rudder-packages
    (https://issues.rudder.io/issues/14749[#14749])
* Declare rpm dependencies is SPECS directory
    (https://issues.rudder.io/issues/14711[#14711])
* Upgrade FusionInventory to 2.4.3
    (https://issues.rudder.io/issues/14424[#14424])
* Try faster builds with parallel make
    (https://issues.rudder.io/issues/14108[#14108])
* Rename rudder-inventory-ldap to rudder-ldap
    (https://issues.rudder.io/issues/14071[#14071])
*  Move rudder-jetty service to a systemd unit
    (https://issues.rudder.io/issues/14021[#14021])
* Upgrade embedded openldap to 2.4.47
    (https://issues.rudder.io/issues/14016[#14016])
* Move rudder-slapd to a systemd unit
    (https://issues.rudder.io/issues/14006[#14006])
* Update rudder packages to match modern packaging recommendation
    (https://issues.rudder.io/issues/14001[#14001])
* Merge packages into one
    (https://issues.rudder.io/issues/13852[#13852])
* There are some remaining rudder-agent-thin references in packaging
    (https://issues.rudder.io/issues/13980[#13980])
* Confine relayd with SELinux
    (https://issues.rudder.io/issues/15500[#15500])
* Disable lto for relayd release builds
    (https://issues.rudder.io/issues/15909[#15909])
* Cache relayd builds
    (https://issues.rudder.io/issues/15880[#15880])
* Add hardening config in relayd systemd unit
    (https://issues.rudder.io/issues/15521[#15521])
* Remove relayd tests from qa-test
    (https://issues.rudder.io/issues/15254[#15254])
* Add shellcheck linting to shell scripts in the rudder repo
    (https://issues.rudder.io/issues/14685[#14685])
* Remove local doc build when installing ncf
    (https://issues.rudder.io/issues/14990[#14990])
* package modules must autodetect python version 
    (https://issues.rudder.io/issues/14912[#14912])

==== Miscellaneous

* Cleanup rudder-webapp install scripts
    (https://issues.rudder.io/issues/15677[#15677])

==== Support info script

* Detect any .rpmnew files in rudder-support-info
    (https://issues.rudder.io/issues/10512[#10512])
* Add a check for refusal message in syslog
    (https://issues.rudder.io/issues/8567[#8567])
* Test agent runtime for runs > 5min
    (https://issues.rudder.io/issues/8596[#8596])
* Only check recent failed inventories on the server
    (https://issues.rudder.io/issues/8582[#8582])
* Low free space on disk should be a warning and not an error
    (https://issues.rudder.io/issues/8579[#8579])

==== Agent

* Remove our patch that send agent errors to stderr
    (https://issues.rudder.io/issues/14863[#14863])
* Add autocompletion to rudder-pkg
    (https://issues.rudder.io/issues/15502[#15502])
* Make certificate verification in HTTP calls configurable
    (https://issues.rudder.io/issues/15513[#15513])
* Fix command used to reload relay config
    (https://issues.rudder.io/issues/15940[#15940])
* Improve rudder remote run command
    (https://issues.rudder.io/issues/15816[#15816])
* Execute a single directive on the agent
    (https://issues.rudder.io/issues/15223[#15223])
* Execute a single directive on the agent
    (https://issues.rudder.io/issues/15223[#15223])
* Add a command to show agent auth info
    (https://issues.rudder.io/issues/8552[#8552])
* Add rudder relay commands
    (https://issues.rudder.io/issues/15330[#15330])
* Main rudder agent command should bootstrap if promises are empty
    (https://issues.rudder.io/issues/15299[#15299])
* We should stop rudder agent check if the agent is disabled
    (https://issues.rudder.io/issues/15300[#15300])
* Replace cfengine bootstrap by rudder bootstrap
    (https://issues.rudder.io/issues/15266[#15266])
* Use rudder agent check at postinst and factory reset to avoid duplicating code
    (https://issues.rudder.io/issues/14833[#14833])
* Clean up rudder agent check
    (https://issues.rudder.io/issues/14831[#14831])
* Remove deprecated agent-reinit command
    (https://issues.rudder.io/issues/14063[#14063])

==== Documentation

* Add a link to the backup doc at the beginning of upgrade procedure
    (https://issues.rudder.io/issues/16073[#16073])
* Improve generic method docs
    (https://issues.rudder.io/issues/16034[#16034])
* Add rudder-pkg notes to the 6.0 rudder doc
    (https://issues.rudder.io/issues/15950[#15950])
* Document that 6.0 upgrade is only possible from 5.0
    (https://issues.rudder.io/issues/15972[#15972])
* Add relay API to doc menu
    (https://issues.rudder.io/issues/15889[#15889])
* Adapt doc for 6.0
    (https://issues.rudder.io/issues/15845[#15845])
* Update doc for 5.1
    (https://issues.rudder.io/issues/15452[#15452])
* Add upgrade note about the change of behaviour of condition_from_command starting 5.1
    (https://issues.rudder.io/issues/15193[#15193])
* Add the security vulnerability reporting policy to the rudder repo
    (https://issues.rudder.io/issues/15026[#15026])
* Add a contribution guide to the Rudder repo
    (https://issues.rudder.io/issues/14878[#14878])
* Improve Rudder README in the repo
    (https://issues.rudder.io/issues/14283[#14283])
* Remove ncf.io site
    (https://issues.rudder.io/issues/16067[#16067])

==== Relay server or API

* Improve relayd tests
    (https://issues.rudder.io/issues/16066[#16066])
* Enable backtrace in relayd
    (https://issues.rudder.io/issues/16063[#16063])
* Don't fail on nodeslist or certificate file absence
    (https://issues.rudder.io/issues/15992[#15992])
* Simplify error type definitions
    (https://issues.rudder.io/issues/15949[#15949])
* Refector api code in relayd
    (https://issues.rudder.io/issues/15883[#15883])
* Improve status API
    (https://issues.rudder.io/issues/15866[#15866])
* Remove avoidable dependencies
    (https://issues.rudder.io/issues/15664[#15664])
* Update structopt
    (https://issues.rudder.io/issues/15610[#15610])
* Add inventory forwarding on relays in relayd
    (https://issues.rudder.io/issues/15497[#15497])
* Split API tests and fix tracing depency versions
    (https://issues.rudder.io/issues/15489[#15489])
* Move rudder-pkg to rudder repo
    (https://issues.rudder.io/issues/14943[#14943])
* Forward reports to upper relays in relayd
    (https://issues.rudder.io/issues/15435[#15435])
* Make the  remote run agent parameters configurable
    (https://issues.rudder.io/issues/15196[#15196])
* Make the  remote run agent parameters configurable
    (https://issues.rudder.io/issues/15196[#15196])
* Implementing agents effectively in remote-run API
    (https://issues.rudder.io/issues/15056[#15056])
* Implementing agents effectively in remote-run API
    (https://issues.rudder.io/issues/15056[#15056])
* Split logging configuration
    (https://issues.rudder.io/issues/15077[#15077])

==== Web - UI & UX

* Show log information next to reports and full compliance report
    (https://issues.rudder.io/issues/15713[#15713])
* Add technique ID in UI
    (https://issues.rudder.io/issues/15672[#15672])
* Display key info in node details
    (https://issues.rudder.io/issues/15358[#15358])
* Change introduction and description fields look in Rudder web interface
    (https://issues.rudder.io/issues/15587[#15587])
* Add a Button to trigger an agent run through the UI
    (https://issues.rudder.io/issues/14647[#14647])

==== Web - Config management

* Add search/pagination to eventlogs UI
    (https://issues.rudder.io/issues/15148[#15148])
* Add managed/technique private files for technique editor
    (https://issues.rudder.io/issues/14657[#14657])
* Add managed/technique private files for technique editor
    (https://issues.rudder.io/issues/14657[#14657])

==== Web - Nodes & inventories

* Merge inventory endpoint and rudder webapps
    (https://issues.rudder.io/issues/15752[#15752])

==== Architecture - Refactoring

* Keep directive and rule name in Policy data structure
    (https://issues.rudder.io/issues/15255[#15255])
* Correct scala compilation warnings
    (https://issues.rudder.io/issues/15574[#15574])
* Clean-up cfengine enterprise code in webapp
    (https://issues.rudder.io/issues/15257[#15257])
* Use ZIO for effect management in Rudder
    (https://issues.rudder.io/issues/14870[#14870])
* Change Scala project structure so that parent-pom is a real parent project
    (https://issues.rudder.io/issues/14359[#14359])

==== API

* Updating Apache's reverse proxy configuration to handle HTTPS requests on remote-run API
    (https://issues.rudder.io/issues/15536[#15536])
* Deprecate API up to 10
    (https://issues.rudder.io/issues/15353[#15353])
* Migrate ncf write technique api to Rudder
    (https://issues.rudder.io/issues/15134[#15134])

==== System integration

* List all plugin in plugin status page
    (https://issues.rudder.io/issues/15556[#15556])

==== Plugins integration

* Display warning when plugin license is near expiration date 
    (https://issues.rudder.io/issues/15568[#15568])
* Take care of number of nodes in plugin license check
    (https://issues.rudder.io/issues/15275[#15275])

==== Architecture - Dependencies

* Update silencer plugin to version 1.4
    (https://issues.rudder.io/issues/15302[#15302])
* Upgrade to ZIO rc5
    (https://issues.rudder.io/issues/15040[#15040])
* Upgrade to Doobie .0.6.0 and related dependencies
    (https://issues.rudder.io/issues/14598[#14598])

==== Performance and scalability

* Don't archive reports anymore on Rudder 5.1
    (https://issues.rudder.io/issues/14862[#14862])

==== Web - Compliance & node report

* Remove red button code from rudder
    (https://issues.rudder.io/issues/14054[#14054])

==== System techniques

* Remove ununsed nodeslist.json in /opt/rudder/etc
    (https://issues.rudder.io/issues/16015[#16015])
* Cleanup roles in system techniques
    (https://issues.rudder.io/issues/15757[#15757])
* Use ncf abort handler when agent is disable
    (https://issues.rudder.io/issues/15160[#15160])
* Remove nova-specific cron job from system techniques
    (https://issues.rudder.io/issues/15258[#15258])
* Remove unencrypted body files
    (https://issues.rudder.io/issues/14353[#14353])
* Remove ncf.conf usage
    (https://issues.rudder.io/issues/14193[#14193])
* Abort when running 5.1 policies on old agent
    (https://issues.rudder.io/issues/14135[#14135])
* Remove rudder-lib from techniques
    (https://issues.rudder.io/issues/14124[#14124])
* Cleanup reporting from rudder-techniques
    (https://issues.rudder.io/issues/13999[#13999])
* Cleanup rudder promises generated
    (https://issues.rudder.io/issues/13992[#13992])
* Remove template in system techniques
    (https://issues.rudder.io/issues/13983[#13983])
* Remove minicurl references in rudder techniques
    (https://issues.rudder.io/issues/13973[#13973])
* Replave the NOVA system variable with a simple condition
    (https://issues.rudder.io/issues/13979[#13979])
* Remove ncf.conf
    (https://issues.rudder.io/issues/14191[#14191])
* Remove ncf.conf
    (https://issues.rudder.io/issues/14191[#14191])

==== Techniques

* Remove license header in techniques
    (https://issues.rudder.io/issues/15704[#15704])
* Add the User techniques category to the technique packaging
    (https://issues.rudder.io/issues/15380[#15380])
* Migrate rudder_common_classes bundle to classes_generic
    (https://issues.rudder.io/issues/14993[#14993])
* Cleanup old OS classes in techniques
    (https://issues.rudder.io/issues/14874[#14874])
* Deprecated techniques before 5.1
    (https://issues.rudder.io/issues/13988[#13988])
* Remove technique tools in Rudder 5.1
    (https://issues.rudder.io/issues/13974[#13974])
* Remove windows reference in rudder techniques
    (https://issues.rudder.io/issues/13971[#13971])
* Drop support of the module check_zypper_version
    (https://issues.rudder.io/issues/13976[#13976])
* Remove deprecated techniques un 5.1
    (https://issues.rudder.io/issues/13972[#13972])

==== Security

* Force TLS1.2 communication between agent and server
    (https://issues.rudder.io/issues/14786[#14786])

==== Technique editor - UI/UX

* Replace "Technique restored from current session" message by notification
    (https://issues.rudder.io/issues/16023[#16023])
* Make it possible to edit several methods in parallel
    (https://issues.rudder.io/issues/15145[#15145])
* Improve parameters' UI in Technique editor
    (https://issues.rudder.io/issues/15136[#15136])
* Make a new Technique Editor interface
    (https://issues.rudder.io/issues/15336[#15336])

==== Generic methods

* Synchronize package modules from masterfiles
    (https://issues.rudder.io/issues/14915[#14915])
* Remove 60_services and dispatcher from ncf
    (https://issues.rudder.io/issues/14192[#14192])
* Split ncf_lib like cfengine lib
    (https://issues.rudder.io/issues/14128[#14128])
* Split ncf_lib like cfengine lib
    (https://issues.rudder.io/issues/14128[#14128])
* Move stuff from rudder-lib into ncf
    (https://issues.rudder.io/issues/14125[#14125])
* Move generic stuff from techniques into ncf
    (https://issues.rudder.io/issues/14000[#14000])
* Remove windows reference in ncf
    (https://issues.rudder.io/issues/13970[#13970])

=== Bug fixes

==== Packaging

* Fixed: Packaging files for rudder-api-client in 5.0 are not correct
    (https://issues.rudder.io/issues/16057[#16057])
* Fixed: Remove debug pprint from rudder-pkg
    (https://issues.rudder.io/issues/15985[#15985])
* Fixed: Unwanted systemctl output in rudder-reports postinst
    (https://issues.rudder.io/issues/15979[#15979])
* Fixed: rudder-api-client should not depend of python2 on redhat8
    (https://issues.rudder.io/issues/15936[#15936])
* Fixed: cache may ignore some change within dependencies patches
    (https://issues.rudder.io/issues/15881[#15881])
* Fixed: Missing python build dependencies for rudder-api-client on debian builds
    (https://issues.rudder.io/issues/15922[#15922])
* Fixed: build-caching cache the same thing twice
    (https://issues.rudder.io/issues/15911[#15911])
* Fixed: ldap build should not use --debug
    (https://issues.rudder.io/issues/15879[#15879])
* Fixed: curl doesnt fail on 404 during packaging
    (https://issues.rudder.io/issues/15865[#15865])
* Fixed: Remove rudder-api-client/SOURCES/Makefile in 6.0
    (https://issues.rudder.io/issues/15861[#15861])
* Fixed: /var/rudder/reports/failed is not created at install
    (https://issues.rudder.io/issues/15825[#15825])
* Fixed: inventory-web.properties is list as conf file but we removed it
    (https://issues.rudder.io/issues/15805[#15805])
* Fixed: Wrong path for inventory.schema in Makefile
    (https://issues.rudder.io/issues/15803[#15803])
* Fixed: Apache modules needed by rudder-webapp are listed in a file which is not included in the apache conf file
    (https://issues.rudder.io/issues/15753[#15753])
* Fixed: packages fail to build on rpm
    (https://issues.rudder.io/issues/15726[#15726])
* Fixed: Wrong python version used in rudder-server-relay build
    (https://issues.rudder.io/issues/15720[#15720])
* Fixed: server 5.1 take too long to install
    (https://issues.rudder.io/issues/15721[#15721])
* Fixed: rudder-api-client packaging fails to execute make clean
    (https://issues.rudder.io/issues/15716[#15716])
* Fixed: Rudder api client expect python3 which is not available by default on rhel7
    (https://issues.rudder.io/issues/15711[#15711])
* Fixed: rudder-api-client fails to build on rpm
    (https://issues.rudder.io/issues/15709[#15709])
* Fixed: Missing build dependencies on rpm based distros for rudder-api-client
    (https://issues.rudder.io/issues/15701[#15701])
* Fixed: rudder-init does duplicate things with postinst
    (https://issues.rudder.io/issues/15700[#15700])
* Fixed: Rudder-api-client packaging fails on rpm based system
    (https://issues.rudder.io/issues/15695[#15695])
* Fixed: apache fails to start
    (https://issues.rudder.io/issues/15693[#15693])
* Fixed: mod_proxy is not enabled in a relay
    (https://issues.rudder.io/issues/15690[#15690])
* Fixed: Wrong Makefile in rudder-api-client
    (https://issues.rudder.io/issues/15671[#15671])
* Fixed: Rudder-api-client changelog points to rudder-server-root
    (https://issues.rudder.io/issues/15669[#15669])
* Fixed: Missing SOURCES directory in rudder-packages/rudder-api-client
    (https://issues.rudder.io/issues/15624[#15624])
* Fixed: At installation Rudder-webapp only creates rudder-slapd and ncf-api-venv users but do not force group creation
    (https://issues.rudder.io/issues/15649[#15649])
* Fixed: add a prerm script to rudder-server-relay
    (https://issues.rudder.io/issues/15566[#15566])
* Fixed: Warning about systemd script during upgrade of rudder-agent 5.1 on centos7
    (https://issues.rudder.io/issues/15532[#15532])
* Fixed: Rights of ncf-api-venv home are not correct (at least on debian 9) preventing usage of technique editor
    (https://issues.rudder.io/issues/15508[#15508])
* Fixed: Python deps for rudder-pkg are listed in build-depends instead of depends
    (https://issues.rudder.io/issues/15495[#15495])
* Fixed: error during upgrade of rudder 5.1 nightly on a centos 7
    (https://issues.rudder.io/issues/15455[#15455])
* Fixed: Rudder init is not done in post install
    (https://issues.rudder.io/issues/15409[#15409])
* Fixed: timestamp script is not executable
    (https://issues.rudder.io/issues/15402[#15402])
* Fixed: upgrade from 5.0 to 5.1 fails
    (https://issues.rudder.io/issues/15391[#15391])
* Fixed: /var/rudder/configuration-repository/ncf should not be checked anymore by rudder-fix-repository-permissions
    (https://issues.rudder.io/issues/15373[#15373])
* Fixed: Rudder fails to build on 5.1
    (https://issues.rudder.io/issues/15347[#15347])
* Fixed: Agent doesn't know when it is installed on a root server on rpm distro
    (https://issues.rudder.io/issues/15335[#15335])
* Fixed: Selinux policy application fails in rudder-webapp postinst 
    (https://issues.rudder.io/issues/14794[#14794])
* Fixed: ncf api fails to run on python 3
    (https://issues.rudder.io/issues/15304[#15304])
* Fixed: Rudder 5.1 fails to build because of #15142
    (https://issues.rudder.io/issues/15175[#15175])
* Fixed: Add back java dependency on SLES12 for 5.1
    (https://issues.rudder.io/issues/15072[#15072])
* Fixed: Technique editor apache conf is misplaced on RHEL
    (https://issues.rudder.io/issues/15071[#15071])
* Fixed: rudder-server-webapp depends on jdk >= 1.8 on sles15 but the package is no longer distributed
    (https://issues.rudder.io/issues/15068[#15068])
* Fixed: Server install on 5.1 depends of libpq which does not exist on debian based distros 
    (https://issues.rudder.io/issues/15066[#15066])
* Fixed: Agent 5.1 fails to build on rhel6 and aix 
    (https://issues.rudder.io/issues/15059[#15059])
* Fixed: Add a placeholder in SOURCES dir for relay package 
    (https://issues.rudder.io/issues/15043[#15043])
* Fixed: Extract sources before fixing python version inscripts
    (https://issues.rudder.io/issues/15030[#15030])
* Fixed: midding build dependencies for rhel8 
    (https://issues.rudder.io/issues/14901[#14901])
* Fixed: Add dev dependencies for virtualenv 
    (https://issues.rudder.io/issues/14899[#14899])
* Fixed: Broken install script in 5.1 rpm agent 
    (https://issues.rudder.io/issues/14865[#14865])
* Fixed: Packaging fails at test step 
    (https://issues.rudder.io/issues/14769[#14769])
* Fixed: debian server 5.1 packages won't build  
    (https://issues.rudder.io/issues/14759[#14759])
* Fixed: Postgresql misconfigured when not the default distrib package (ex: Centos 6 with Postgresql 9.3 from pgfoundry.org)
    (https://issues.rudder.io/issues/14744[#14744])
* Fixed: Package for slackware doesn't build
    (https://issues.rudder.io/issues/14745[#14745])
* Fixed: Remove localdepends target in packages.makfile 
    (https://issues.rudder.io/issues/14674[#14674])
* Fixed: Remove http1.1 parameter from curl
    (https://issues.rudder.io/issues/14671[#14671])
* Fixed: linker error during agent build
    (https://issues.rudder.io/issues/14639[#14639])
* Fixed: Force http 1.1 when downloading curl
    (https://issues.rudder.io/issues/14158[#14158])
* Fixed: rudder-reports postinstall fails on redhat
    (https://issues.rudder.io/issues/14133[#14133])
* Fixed: rpm build error
    (https://issues.rudder.io/issues/14118[#14118])
* Fixed: Postinstall 5.1 fails
    (https://issues.rudder.io/issues/14113[#14113])
* Fixed: debian rudder-webapp fails to install
    (https://issues.rudder.io/issues/14101[#14101])
* Fixed: rudder-server-relay fail to build
    (https://issues.rudder.io/issues/14085[#14085])
* Fixed: rudder-server-relay fail to build
    (https://issues.rudder.io/issues/14084[#14084])
* Fixed: Curl is not a rudder-server-root dependency
    (https://issues.rudder.io/issues/14070[#14070])
* Fixed: rudder-server-relay fail to build
    (https://issues.rudder.io/issues/14081[#14081])
* Fixed: rudder inventory ldap build fail
    (https://issues.rudder.io/issues/14079[#14079])
* Fixed: specfile syntax error
    (https://issues.rudder.io/issues/14078[#14078])
* Fixed: debian packages fail to build
    (https://issues.rudder.io/issues/14076[#14076])
* Fixed: Error when building rudder-server-relay
    (https://issues.rudder.io/issues/14075[#14075])
* Fixed: bad syntax during rpm build
    (https://issues.rudder.io/issues/14074[#14074])
* Fixed: remove rudder-slapd-configure from installation
    (https://issues.rudder.io/issues/14072[#14072])
* Fixed: builds fail to get repository.rudder.io
    (https://issues.rudder.io/issues/14068[#14068])
* Fixed: Missing cd sourcedir in specfiles
    (https://issues.rudder.io/issues/14067[#14067])
* Fixed: 5.1 fails to build for rpm
    (https://issues.rudder.io/issues/14066[#14066])
* Fixed: Missing /var/rudder/lib/relay dir in packaging
    (https://issues.rudder.io/issues/16052[#16052])
* Fixed: New techniques are not added to directive tree
    (https://issues.rudder.io/issues/14354[#14354])
* Fixed: Incorrect permission on /var/rudder/reports
    (https://issues.rudder.io/issues/15810[#15810])
* Fixed: add a prerm script to rudder-server-relay
    (https://issues.rudder.io/issues/15566[#15566])
* Fixed: Missing directories in relay install target
    (https://issues.rudder.io/issues/15555[#15555])
* Fixed: Typo in rudder Makefile
    (https://issues.rudder.io/issues/15480[#15480])
* Fixed: relay api doesn't support python2 and python 3
    (https://issues.rudder.io/issues/15399[#15399])
* Fixed: rudder-server-relay fails during postinstall
    (https://issues.rudder.io/issues/15374[#15374])
* Fixed: Invalid cron file put by packaging
    (https://issues.rudder.io/issues/14559[#14559])
* Fixed: slapd conf file owner is not correct 
    (https://issues.rudder.io/issues/15047[#15047])
* Fixed: Wrong check of response in rudder relay reload
    (https://issues.rudder.io/issues/16058[#16058])

==== Agent

* Fixed: Postinst of rudder-agent on centos6 tries to use systemd
    (https://issues.rudder.io/issues/15937[#15937])
* Fixed: agent reset keys won't work anymore on 5.1
    (https://issues.rudder.io/issues/15339[#15339])
* Fixed: Agent inventory are refused by the webapp since they do not contains the agent certificate
    (https://issues.rudder.io/issues/15325[#15325])
* Fixed: Rudder commands complain because of a missing rudder.json
    (https://issues.rudder.io/issues/15282[#15282])
* Fixed: Initial promises are failing to execute since some bundles are not included
    (https://issues.rudder.io/issues/15323[#15323])
* Fixed: agents in 5.1 fail to download ncf from the server
    (https://issues.rudder.io/issues/15322[#15322])
* Fixed: agents in 5.1 fail to download ncf from the server
    (https://issues.rudder.io/issues/15320[#15320])
* Fixed: HTTPS reporting is not done at first run if agent runs with -u
    (https://issues.rudder.io/issues/15997[#15997])
* Fixed: Error at /opt/rudder/bin/rudder relay reload -p
    (https://issues.rudder.io/issues/15995[#15995])
* Fixed: Ununderstandable error messages when server is not up and agent is installed
    (https://issues.rudder.io/issues/15901[#15901])
* Fixed: Factory-reset does not reset uuid and certificates
    (https://issues.rudder.io/issues/15401[#15401])
* Fixed: Explain in the doc that no reports are sent in verbose or debug mode
    (https://issues.rudder.io/issues/15474[#15474])
* Fixed: Rudder agent disable command has a -s option, that is not parsed
    (https://issues.rudder.io/issues/15460[#15460])
* Fixed: reload relay command should use POST
    (https://issues.rudder.io/issues/15426[#15426])
* Fixed: "rudder agent check" should check certificate subject, and update it if it is wrong
    (https://issues.rudder.io/issues/15332[#15332])
* Fixed: Syntax error in rudder agent check
    (https://issues.rudder.io/issues/15329[#15329])
* Fixed: Broken curl command in agent
    (https://issues.rudder.io/issues/15231[#15231])
* Fixed: reset and check commands break server in some cases 
    (https://issues.rudder.io/issues/15031[#15031])

==== Relay server or API

* Fixed: Rudder-pkg setup conf files in the wrong places
    (https://issues.rudder.io/issues/15470[#15470])
* Fixed: relayd should stop when a thread panics
    (https://issues.rudder.io/issues/16076[#16076])
* Fixed: HTTP errors when forwarding reports or inventories should generally be considered as transient
    (https://issues.rudder.io/issues/16065[#16065])
* Fixed: Remote-run sometimes returns empty outpout or output with missing newlines
    (https://issues.rudder.io/issues/16047[#16047])
* Fixed: Remote-run starts commands with no host name
    (https://issues.rudder.io/issues/16044[#16044])
* Fixed: Passwords can appear in relayd logs
    (https://issues.rudder.io/issues/16040[#16040])
* Fixed: Add logging contexts
    (https://issues.rudder.io/issues/16001[#16001])
* Fixed: Add benchmarks for big nodes lists
    (https://issues.rudder.io/issues/16013[#16013])
* Fixed: Receiving a report for an unknown node crashes the watcher
    (https://issues.rudder.io/issues/15999[#15999])
* Fixed: Remote-run returns empty output
    (https://issues.rudder.io/issues/15990[#15990])
* Fixed: Fix async & keep_output behavior
    (https://issues.rudder.io/issues/15836[#15836])
* Fixed: relayd should accept empty condition field in remote-run
    (https://issues.rudder.io/issues/15832[#15832])
* Fixed: Incorrect remote run command when used with sudo
    (https://issues.rudder.io/issues/15814[#15814])
* Fixed: Fix synchronous remote run
    (https://issues.rudder.io/issues/15808[#15808])
* Fixed: Fix PUT in shared-files API
    (https://issues.rudder.io/issues/15668[#15668])
* Fixed: Update relayd dependencies to fix RUSTSEC-2019-0013
    (https://issues.rudder.io/issues/15597[#15597])
* Fixed: Make clean doesn't remove all python files downloaded and generated on rudder-relay
    (https://issues.rudder.io/issues/15490[#15490])
* Fixed: rudder-pkg python lib are missplaced on the server
    (https://issues.rudder.io/issues/15483[#15483])
* Fixed: Report PUT is missing the file name
    (https://issues.rudder.io/issues/15482[#15482])
* Fixed: rudder-pkg does not install properly
    (https://issues.rudder.io/issues/15476[#15476])
* Fixed: Remove \r in reports in relayd
    (https://issues.rudder.io/issues/15467[#15467])
* Fixed: postinstall of rudder-server-relay may fail if httpd is too slow to shut down
    (https://issues.rudder.io/issues/15444[#15444])
* Fixed: relayd watcher does not catch moved files
    (https://issues.rudder.io/issues/15427[#15427])
* Fixed: relayd should only control run date consistency inside the runlog
    (https://issues.rudder.io/issues/15425[#15425])
* Fixed: Only treat file with report extension in relayd
    (https://issues.rudder.io/issues/15405[#15405])
* Fixed: Add logs to Relay API
    (https://issues.rudder.io/issues/14947[#14947])
* Fixed: Add logs to Relay API
    (https://issues.rudder.io/issues/14947[#14947])
* Fixed: Relay packages uses python3 to build virtualenv
    (https://issues.rudder.io/issues/14897[#14897])
* Fixed: Modify urllib3 import to disable useless pylint warning 
    (https://issues.rudder.io/issues/14684[#14684])
* Fixed: relayd fails to start on centos7 du to invalid permissions on nodeslist.json
    (https://issues.rudder.io/issues/16059[#16059])

==== Support info script

* Fixed: script debug info
    (https://issues.rudder.io/issues/15366[#15366])
* Fixed: Add a check for refusal message in syslog
    (https://issues.rudder.io/issues/15367[#15367])
* Fixed: support-info script don't list installed plugin
    (https://issues.rudder.io/issues/12805[#12805])

==== Documentation

* Fixed: User manual doesn't mention Debian wheezy support
    (https://issues.rudder.io/issues/4124[#4124])
* Fixed: Use systemctl for rudder services management in docs
    (https://issues.rudder.io/issues/15968[#15968])
* Fixed: Add a link to old docs
    (https://issues.rudder.io/issues/15928[#15928])
* Fixed: Fix dead links in the doc
    (https://issues.rudder.io/issues/15884[#15884])
* Fixed: Doc links in home should point to 5.0 and not 6.0
    (https://issues.rudder.io/issues/15855[#15855])
* Fixed: Missing 5.0 changelog in docs
    (https://issues.rudder.io/issues/15618[#15618])
* Fixed: Prepare 5.1 doc
    (https://issues.rudder.io/issues/15612[#15612])
* Fixed: Fix title levels in docs
    (https://issues.rudder.io/issues/16036[#16036])
* Fixed: ncf site does not build
    (https://issues.rudder.io/issues/14105[#14105])

==== System techniques

* Fixed: Agent bootstraping does not work on root server
    (https://issues.rudder.io/issues/14788[#14788])
* Fixed: Typo in the system technique PropagatePromises
    (https://issues.rudder.io/issues/16064[#16064])
* Fixed: Initial policies on root server broken with missing postgres-check.cf file
    (https://issues.rudder.io/issues/16028[#16028])
* Fixed: In a separate database setup, an unexpected N/A report about "Postgresql component check" pops up
    (https://issues.rudder.io/issues/15993[#15993])
* Fixed: Error in agent run about missing variable
    (https://issues.rudder.io/issues/15464[#15464])
* Fixed: postgres-check.cf doesn't exist anymore but is still loaded
    (https://issues.rudder.io/issues/15899[#15899])
* Fixed: Duplicate report in distributePolicy/1.0/propagatePromises.cf
    (https://issues.rudder.io/issues/15830[#15830])
* Fixed: Missing template for relayd conf in the initial promises
    (https://issues.rudder.io/issues/15821[#15821])
* Fixed: Bootstrap policies should listen on 5309
    (https://issues.rudder.io/issues/15818[#15818])
* Fixed: Allow local cfruncommand on root server
    (https://issues.rudder.io/issues/15820[#15820])
* Fixed: Initial promises contain an empty allowed network
    (https://issues.rudder.io/issues/15779[#15779])
* Fixed: More typos in system techniques
    (https://issues.rudder.io/issues/15750[#15750])
* Fixed: typo in server-roles/1.0/password-check.cf
    (https://issues.rudder.io/issues/15748[#15748])
* Fixed: Anomalous ending during agent inventory
    (https://issues.rudder.io/issues/15694[#15694])
* Fixed: RUDDER_WEBDAV_PASSWORD from /opt/rudder/etc/rudder-passwords.conf is ignored
    (https://issues.rudder.io/issues/15682[#15682])
* Fixed: missing report about  	Send inventories to Rudder server
    (https://issues.rudder.io/issues/15496[#15496])
* Fixed: duplicate report form component "Log system for reports" when report protocol is https 
    (https://issues.rudder.io/issues/15485[#15485])
* Fixed: When HTTPS reporting is selected, rsyslog is still active and so reports are duplicated on the server
    (https://issues.rudder.io/issues/15446[#15446])
* Fixed: Syntax error in promises.cf
    (https://issues.rudder.io/issues/15415[#15415])
* Fixed: Broken reports forwaring policy
    (https://issues.rudder.io/issues/15404[#15404])
* Fixed: In 5.1 common policies always return a missing reports on the server
    (https://issues.rudder.io/issues/15334[#15334])
* Fixed: Don't set root owner on slapd config
    (https://issues.rudder.io/issues/15326[#15326])
* Fixed: Wrong variable name when downloading initial promises from the server
    (https://issues.rudder.io/issues/15316[#15316])
* Fixed: at install on the server on centos7, rudder-system-directives.cf is empty, and so, there are missing bundles when running the agent
    (https://issues.rudder.io/issues/15309[#15309])
* Fixed: Fix broken 5.1 techniques 
    (https://issues.rudder.io/issues/15044[#15044])
* Fixed: No reports from nodes in Rudder 5.1 due to bad location of check_rsyslog_version
    (https://issues.rudder.io/issues/14352[#14352])
* Fixed: missing reports in rudder 5.1 because of undefined distribute_policy_common.directiveId
    (https://issues.rudder.io/issues/14350[#14350])
* Fixed: Syntax error in policy generation in 5.1
    (https://issues.rudder.io/issues/14242[#14242])
* Fixed: cf-agent aborted on defined class 'should_not_continue'
    (https://issues.rudder.io/issues/14157[#14157])
* Fixed: server install fail on agent check
    (https://issues.rudder.io/issues/14123[#14123])
* Fixed: System techniques are invalid in 5.1
    (https://issues.rudder.io/issues/14114[#14114])
* Fixed: Deleted stdlib files are still loaded in initial policies
    (https://issues.rudder.io/issues/14102[#14102])
* Fixed: Making initial promises from rudder-techniques fails
    (https://issues.rudder.io/issues/14069[#14069])

==== Web - UI & UX

* Fixed: Date handling in API Token Creation is broken
    (https://issues.rudder.io/issues/15943[#15943])
* Fixed: Login page on Rudder 6.0 shows version 5.1
    (https://issues.rudder.io/issues/15941[#15941])
* Fixed: Missing notification for archive page
    (https://issues.rudder.io/issues/15315[#15315])
* Fixed: Generation status is empty and grey at every connection
    (https://issues.rudder.io/issues/15307[#15307])
* Fixed: Fix rudder-elm notifications init
    (https://issues.rudder.io/issues/15438[#15438])

==== Server components

* Fixed: Rudder-pkg fails to build since subprocess.DEVNULL is undefined before python 3.3
    (https://issues.rudder.io/issues/16077[#16077])
* Fixed: Cannot start relayd
    (https://issues.rudder.io/issues/15434[#15434])
* Fixed: Error while fixing 15748
    (https://issues.rudder.io/issues/15774[#15774])
* Fixed: Rudde server debug in 5.1 has a typo in it
    (https://issues.rudder.io/issues/15318[#15318])

==== Plugins integration

* Fixed: Rudder package does not work when there are no plugin compatible with the current version of Rudder
    (https://issues.rudder.io/issues/15952[#15952])
* Fixed: Rudder-pkg try to copy a folder with install command instead of using a recursive cp
    (https://issues.rudder.io/issues/15481[#15481])
* Fixed: Remove tabulate python lib from rudder pkg
    (https://issues.rudder.io/issues/15463[#15463])

==== Technique editor - Techniques

* Fixed: Policy generation is broken when using condition on generic methds
    (https://issues.rudder.io/issues/16069[#16069])
* Fixed: ressources are not correctly referenced in technique
    (https://issues.rudder.io/issues/16039[#16039])
* Fixed: Resources in technique are not put in the correct folder
    (https://issues.rudder.io/issues/16033[#16033])

==== Web - Technique editor

* Fixed: Error message in technique editor when using wrong syntax for node properties is REALLY not clear enough 
    (https://issues.rudder.io/issues/15048[#15048])
* Fixed: Policy generation fails when we have technique ressources
    (https://issues.rudder.io/issues/16008[#16008])
* Fixed: In rudder 5.1 we can no more put multiple lines in technique editor fields
    (https://issues.rudder.io/issues/15314[#15314])
* Fixed: Cannot delete file and folder in file editor
    (https://issues.rudder.io/issues/16029[#16029])
* Fixed: Drag'N Drop not working for generic method
    (https://issues.rudder.io/issues/16037[#16037])
* Fixed: Import file button is still active when the panel is hide
    (https://issues.rudder.io/issues/16035[#16035])
* Fixed: Show/Hides docs in technique editor doesn't do anything
    (https://issues.rudder.io/issues/16016[#16016])

==== Web - Config management

* Fixed: nodeslist.json can take up to 5 minutes to be updated after accepting a node
    (https://issues.rudder.io/issues/16017[#16017])
* Fixed: Generation fails with: RejectedExecutionException'. Perhaps the thread pool was stopped?
    (https://issues.rudder.io/issues/15981[#15981])
* Fixed: MANAGED_NODES_NAME is still needed for CFE nodes
    (https://issues.rudder.io/issues/15355[#15355])
* Fixed: Webapp stops at ncf boot check
    (https://issues.rudder.io/issues/15159[#15159])

==== Miscellaneous

* Fixed: Dynamic group based on another dynamic group don't work correctly in 6.0
    (https://issues.rudder.io/issues/16010[#16010])
* Fixed: Unexpected crash of webapp on 6.0
    (https://issues.rudder.io/issues/16004[#16004])

==== Web - Nodes & inventories

* Fixed: add a test on group of groups
    (https://issues.rudder.io/issues/16030[#16030])
* Fixed: Empty keyhashes in nodeslist.json on Linux nodes
    (https://issues.rudder.io/issues/15547[#15547])
* Fixed: Wrong name for all nodes certificates files
    (https://issues.rudder.io/issues/15403[#15403])
* Fixed: When receiving pleinty of inventories at the same time, the web interface starts to parse them all at once 
    (https://issues.rudder.io/issues/15012[#15012])
* Fixed: Broken certificate handling in Unix nodes
    (https://issues.rudder.io/issues/15331[#15331])
* Fixed: DecoderException: unable to decode base64 string: invalid characters encountered in base64 data 
    (https://issues.rudder.io/issues/15034[#15034])

==== Performance and scalability

* Fixed: Webapp does not start when only one proc is available (deadlock)
    (https://issues.rudder.io/issues/15982[#15982])
* Fixed: Use `extends AnyVal` and remove HashCodeCaching for classes with one parameter
    (https://issues.rudder.io/issues/15797[#15797])
* Fixed: Computing dynamic groups is very memory intensive, and can lead to FGC or OOM
    (https://issues.rudder.io/issues/15858[#15858])
* Fixed: Use a queue for "changes" cache update
    (https://issues.rudder.io/issues/15117[#15117])

==== System integration

* Fixed: Missing some logger documentation in logback.xml
    (https://issues.rudder.io/issues/15916[#15916])
* Fixed: Webapp fails to boot (several time)
    (https://issues.rudder.io/issues/15324[#15324])
* Fixed: Test in 5.1 for webapp are broken
    (https://issues.rudder.io/issues/15364[#15364])
* Fixed: Policy generation error is not clear in log anymore
    (https://issues.rudder.io/issues/15313[#15313])
* Fixed: Remove unused property "base_url"  
    (https://issues.rudder.io/issues/14932[#14932])
* Fixed: When switching to HTTPS reporting, the compliance of root server is broken because it receives both https and syslog
    (https://issues.rudder.io/issues/16002[#16002])

==== Architecture - Refactoring

* Fixed: Normalize datetime format to ISO8601/rfc3339
    (https://issues.rudder.io/issues/15896[#15896])
* Fixed: Missing a fork for clean report info batch
    (https://issues.rudder.io/issues/15849[#15849])
* Fixed: Port string template processing to zio
    (https://issues.rudder.io/issues/15260[#15260])
* Fixed: Upgrade to ZIO new namespace
    (https://issues.rudder.io/issues/15100[#15100])

==== Architecture - Dependencies

* Fixed: Update libraries to last minor versions
    (https://issues.rudder.io/issues/15740[#15740])

==== API

* Fixed: Wrong path in shared-files API
    (https://issues.rudder.io/issues/15552[#15552])
* Fixed: Unknown option in remote-run command
    (https://issues.rudder.io/issues/15501[#15501])
* Fixed: Verifying signatures correctly in shared-files API
    (https://issues.rudder.io/issues/15469[#15469])
* Fixed: Handle ttl parameter correctly in shared-files API
    (https://issues.rudder.io/issues/15456[#15456])
* Fixed: upgrade API settings to v12 to include default report protocol and syslog protocol disabled 
    (https://issues.rudder.io/issues/15472[#15472])
* Fixed: Running remote-run as sudo during runtime
    (https://issues.rudder.io/issues/15390[#15390])
* Fixed: Adding Windows shared folder feature to shared-file API
    (https://issues.rudder.io/issues/15360[#15360])
* Fixed: API for node key management
    (https://issues.rudder.io/issues/15344[#15344])
* Fixed: Sending & Receiving files with the shared-files API
    (https://issues.rudder.io/issues/15253[#15253])
* Fixed: Validating signatures in shared-files API
    (https://issues.rudder.io/issues/15247[#15247])
* Fixed: Limiting conditions length to 1024 characters
    (https://issues.rudder.io/issues/15245[#15245])
* Fixed: public key and key-hash comparison not consistent in Rust's version of shared-file API
    (https://issues.rudder.io/issues/15233[#15233])
* Fixed: public key and key-hash comparison not consistent in Rust's version of shared-file API
    (https://issues.rudder.io/issues/15233[#15233])
* Fixed: public key and key-hash comparison not consistent in Rust's version of shared-file API
    (https://issues.rudder.io/issues/15233[#15233])
* Fixed: Handling keept_output and asynchronous parameters in the remote-run API
    (https://issues.rudder.io/issues/15206[#15206])
* Fixed: Logging the remote-run API with warp
    (https://issues.rudder.io/issues/15202[#15202])
* Fixed: support "classes" and "conditions" as parameters in the remote-run API
    (https://issues.rudder.io/issues/15201[#15201])

==== Security

* Fixed: Guard against non-audit mode on node
    (https://issues.rudder.io/issues/15431[#15431])
* Fixed: Relayd configuration is world-readable
    (https://issues.rudder.io/issues/15523[#15523])

==== Techniques

* Fixed: Missing reports on system techniques in 6.0 for postgresql component check
    (https://issues.rudder.io/issues/15994[#15994])
* Fixed: Use "rudder agent run" instead of cf-agent 
    (https://issues.rudder.io/issues/14873[#14873])
* Fixed: Use new package methods in techniques
    (https://issues.rudder.io/issues/13998[#13998])

==== Technique editor - UI/UX

* Fixed: Cannot create Technique with resources
    (https://issues.rudder.io/issues/15598[#15598])
* Fixed: We cannot delete parameters
    (https://issues.rudder.io/issues/16027[#16027])
* Fixed: Fix file manager navbar's display
    (https://issues.rudder.io/issues/15604[#15604])
* Fixed: Fix Technique Editor loading message
    (https://issues.rudder.io/issues/15600[#15600])
* Fixed: Popups display is broken
    (https://issues.rudder.io/issues/15445[#15445])
* Fixed: Improve the Generic methods list of the new interface
    (https://issues.rudder.io/issues/15396[#15396])

==== Generic methods - File Management

* Fixed: file_from_shared_folder generic methods fails to report
    (https://issues.rudder.io/issues/15983[#15983])

==== Generic methods

* Fixed: variable_string_match tests are failing on old systems
    (https://issues.rudder.io/issues/15971[#15971])
* Fixed: Reformat some cfengine classes bodies in ncf_lib.ncf in 5.1
    (https://issues.rudder.io/issues/15311[#15311])
* Fixed: condition_from_command does not do anything in audit mode
    (https://issues.rudder.io/issues/15189[#15189])
* Fixed: in 5.1 the bundle ncf_configuration_basedir does not exists anymore 
    (https://issues.rudder.io/issues/14911[#14911])
* Fixed: ncf_lib should not exist in 5.1 anymore
    (https://issues.rudder.io/issues/14787[#14787])
* Fixed: Unwanted "methods" promise in log_rudder.cf
    (https://issues.rudder.io/issues/14198[#14198])

==== Generic methods - Service Management

* Fixed: Service having both an init script and a real systemd unit are managed through the init script
    (https://issues.rudder.io/issues/13740[#13740])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Jonathan CLARKE
* Thomas CAILHE

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


