= Change logs for Rudder 5.0

Rudder 5.0 is currently a maintained version of Rudder.

This page provides a summary of changes for each version. Previous beta
and rc versions are listed below for convenience.

*Warning*: The following features are now provided as plugins and no
more available as part of default Rudder installation starting from 5.0:

* LDAP-based authentication
* Relay servers
* Changes validation workflow (change requests)

If you were using them, upgrade will disable them and you will have to
install the plugin. Read the http://rudder.io/plugins[plugins page on
our website] for more information.

The initial RUDDER model consisting of a single software block which
includes all features, thus imposing a greater and greater complexity on
all of our users, has reached its limits. We have now reached a
sufficient understanding of the domain, its challenges, and the way
RUDDER is used, to make us realize that this all-in-one model is not, or
is no longer, the best suited.

_New plugin ecosystem_: Version 5.0 introduces a plugin ecosystem that
gathers RUDDER’s most specific features. This way, only essential
features have to be installed by default and advanced features can be
used on a case by case basis. So what is essential and what is not? The
basic rule is that the essential experience must contain the features
used by 80% or more of users, whatever the scale of use. In other words,
we keep as core features everything that delivers on RUDDER’s initial
promise: enabling users to continuously audit and enforce configurations
with an easy to use webapp providing visual reporting. The remaining 20%
solve needs that are no less important, only less common (PDF compliance
reports, UI branding, scale-out relay servers, validation workflow…). To
know everything about the impact of this evolution, you can read the
detailed dedicated article:

https://www.rudder.io/en/blog/2018/09/26/rudder-5-new-modular-version-thanks-ecosystem-plugins/[RUDDER 5 – a new modular version, thanks to an ecosystem of plugins]

_Integration_: We provide integration with third party tools as plugins,
making RUDDER more integrated with tools like Ansible, Centreon, Zabbix,
GLPI or Vault. Except for a few (ie. managing AIX and Windows host),
plugins are open source and source code is available in the 
https://github.com/normation/rudder-plugins/[rudder-plugins repository].

_New documentation_: Welcome to our brand new documentation website
https://docs.rudder.io[docs.rudder.io]! Beyond its fresh look (both on
the online website and in the embedded version), this new documentation
includes updated content and new resources, like a ``getting started''
guide and examples of use-cases.

_System API_: We built a new REST API that allows to manage some
advanced settings and perform maintenance operations in RUDDER, like
triggering policy generations, updating dynamic groups and managing
report archives. This was previously available in the now deprecated
https://docs.rudder.io/history/4.3/rest-api.html#rest-api[V1 API] which
will be removed in the next major version (5.1).

_Debugging information script_: We created a script to gather basic
information about a RUDDER setup when you want to debug or understand
RUDDER’s behavior. This script fetches log files and executes various
commands, either to get information from databases or directly from the
system (package versions, etc)

_Automatic Technique upgrade_: Techniques provided with RUDDER can now
be automatically upgraded when you update RUDDER. This process used to
be manual because you might have modified the base Technique Library and
we thought you may want to have more control about the content of your
Technique Library. But it appears that this process was forgotten by a
majority of our users and so many bug fixes and new versions were not
available after an upgrade. By default this feature is enabled on new
RUDDER 5.0 installations but is disabled on upgrades from older
versions, to prevent any accidental damage.

_Support policy_: Our general policy is to maintain major releases until
3 months after the next major version is released to give some time for
upgrading. The ESR tag was previously given to major releases that were
maintained 6 months after the next ESR version was announced. Rudder 4.1
is the last ESR release. For a slower major upgrade pace, Rudder
subscription provides long-term maintenance up to 24 months after
release (depending on the subscription level) for Rudder versions. Read
the 
https://docs.rudder.io/reference/5.0/installation/versions.html[dedicated page]
for more informtion.

_Packaging_: _Relay server support is now part of an open-source
plugin_, pre-compiled packages are available as part of the Rudder
subscription.

The agent package is now more modular: instead of embedding all
dependencies, we are using system libraries on maintained operating
systems, to allow for a better system integration. As a consequence, the
experimental rudder-agent-thin (which had this exact goal) package is
not built anymore.

_New repositories_: https://repository.rudder.io/ We are using new
repositories for versions starting from 5.0. We also provide all
previous releases in these new repos. We improved our build system,
files hierarchy, and added more gpg signatures on distributed files
(Rudder sources, etc.)

*Installing, upgrading and testing*

* Install docs:
** https://docs.rudder.io/reference/5.0/installation/server/debian.html[Debian/Ubuntu]
** https://docs.rudder.io/reference/5.0/installation/server/rhel.html[RHEL/centOS]
** https://docs.rudder.io/reference/5.0/installation/server/sles.html[SLES]
* https://docs.rudder.io/reference/5.0/installation/upgrade.html[Upgrade docs]
* https://docs.rudder.io/reference/5.0/installation/versions.html#_versions[Download links]

We also recommend using the
https://github.com/Normation/rudder-vagrant[Rudder Vagrant] config if
you want a quick and easy way to get an installation for testing.

*Supported operating systems*

This version provides packages for these operating systems:

* Rudder server and Rudder relay: *Debian 8-9, RHEL/CentOS 7 (64 bits),
SLES 12-15, Ubuntu 16.04 LTS-18.04 LTS*
* Rudder agent: all of the above plus *RHEL/CentOS 6, Ubuntu 14.04 LTS*
* Rudder agent (binary packages available with a https://www.rudder.io/en/pricing/subscription/[subscription]) : *Debian 5-7, RHEL/CentOS 3-5,
SLES 10-11, Ubuntu 10.04 LTS-12.04 LTS-13.04-15.10, Windows Server 2008R2-2016, AIX
5-6-7, Slackware 14*

Read more about supported operating systems 
https://docs.rudder.io/reference/5.0/installation/operating_systems.html[in the documentation].

== Known issues in Rudder 5.0.0 to 5.0.2

=== Communication between agents built with 1.1.0 vs. 1.0.x openssl versions

We have found a communication problem between some versions of rudder
agent and server due to a bug in OpenSSL library.

The problem occurs when a client (resp. server) using OpenSSL 1.0 tries
to communicate with a server (resp. client) using OpenSSL 1.1.0. It is
https://github.com/openssl/openssl/issues/7134[corrected] in newly
released OpenSSL 1.1.1. The Rudder corresponding bug is
https://www.rudder-project.org/redmine/issues/13690[traced on Rudder bug
tracker].

Rudder versions from 5.0.0 to 5.0.2 on Ubuntu 18.04, Debian 9, and SLES
15 use OpenSSL 1.1.0. Any previous version of Rudder on these OS or any
version of Rudder in any other OS use OpenSSL 1.0. If you have in your
environment a Rudder server in one group and agents in the other group,
these agents won’t be able to communicate with the server any more.

The most likely case where it could happen is if you upgrade a Rudder
server on Ubuntu 18.04 or on Debian 9 from version 4.3 to 5.0. In such a
case, a partial workaround is to also upgrade Debian 9/Ubuntu 18.04
agents to Rudder 5.0, but agents in other OS will still be impacted by
the communication problem. A safer and simpler solution, if available,
is to delay such on upgrade until a patch is available.

We are working on the patch to replace the buggy OpenSSL 1.1.0 and we
will release a new version of Rudder 5.0 with it as soon as possible.

We are sorry for any inconvenience resulting from this problem. If you
need more information or help, please don’t hesitate to contact us by
email or other means of communication like
https://gitter.im/normation/rudder[gitter] or irc (#rudder on freenode).

== Rudder 5.0.12 (2019-07-08)

=== Changes

==== Packaging

* Soften Rudder version requirements in dependencies of nightly builds to allow easier testing
    (https://issues.rudder.io/issues/15079[#15079])
* Better caching of already built binaries to speed-up builds
    (https://issues.rudder.io/issues/14955[#14955])
* Update CFEngine to 3.12.2
    (https://issues.rudder.io/issues/14921[#14921])
* Update embedded openssl version to 1.1.1b/1.0.2r
    (https://issues.rudder.io/issues/14933[#14933])

==== Documentation

* Add a "Rudder by example" to add CPU vulnerabilities status to inventory
    (https://issues.rudder.io/issues/15008[#15008])

==== Architecture - Internal libs

* Using move into non existing branch failed but delete the source
    (https://issues.rudder.io/issues/3591[#3591])

==== Web - UI & UX

* Allow to filter by technique name or tag in when managing directives in rule details
    (https://issues.rudder.io/issues/14803[#14803])

==== Agent

* Add support for rudder commands without subcommands
    (https://issues.rudder.io/issues/14944[#14944])
* Add disable date to rudder agent info
    (https://issues.rudder.io/issues/14929[#14929])

==== Web - Technique editor

* Add visual indication to methods modified since last save
    (https://issues.rudder.io/issues/14518[#14518])

=== Bug fixes

==== Packaging

* Fixed: Libraries sometime fail to load on AIX
    (https://issues.rudder.io/issues/15133[#15133])
* Fixed: Error after upgrade from 4.1 to 5.0 on RPM because slapd is not restarted: apiAuthorizationKind: attribute type undefined
    (https://issues.rudder.io/issues/15120[#15120])
* Fixed:  Rudder agent fails to build on aix due to unkown cp option
    (https://issues.rudder.io/issues/15088[#15088])
* Fixed: Rudder agent fails to build on rhel6 due to missing zlib and bzip2 build dependencies
    (https://issues.rudder.io/issues/15086[#15086])
* Fixed: The sourcedir parameter in dh_install needs to be lowercase for debian 10 compatibility
    (https://issues.rudder.io/issues/15013[#15013])
* Fixed: Disable shebang mangling in rhel8 to keep generic python shebangs
    (https://issues.rudder.io/issues/14958[#14958])

==== Performance and scalability

* Fixed: Allow overriding gc options for the webapp JVM to better deal with high volumes
    (https://issues.rudder.io/issues/15075[#15075])
* Fixed: Error at the end of a policy generation with too many nodes 
    (https://issues.rudder.io/issues/15011[#15011])
* Fixed: Rule changes SQL request and data structure use too much memory 
    (https://issues.rudder.io/issues/15042[#15042])
* Fixed: Compute change hook need to be on a dedicated threadpool
    (https://issues.rudder.io/issues/15096[#15096])
* Fixed: Hooks need to run on an dedicated thread pool
    (https://issues.rudder.io/issues/15095[#15095])
* Fixed: Add switch to disable some compliance and change tracking features for performance
    (https://issues.rudder.io/issues/15073[#15073])
* Fixed: Allow only catching up with recent runs in agent report processing batch
    (https://issues.rudder.io/issues/15062[#15062])
* Fixed: Make the size of the LDAP connection pool configurable
    (https://issues.rudder.io/issues/15060[#15060])
* Fixed: The computation of changes by rules, at start of web interface, is quite slow 
    (https://issues.rudder.io/issues/15041[#15041])
* Fixed: Avoid fetching nodeconfigurations twice when when runs processed
    (https://issues.rudder.io/issues/15035[#15035])
* Fixed: Deleted node should be periodically fully erased in LDAP (after some ttl)
    (https://issues.rudder.io/issues/9609[#9609])
* Fixed: Missing timing logs in ldap queries (especially for dynamic groups) 
    (https://issues.rudder.io/issues/14922[#14922])
* Fixed: Improve rsyslog performance by simplifying parsing of reports
    (https://issues.rudder.io/issues/15028[#15028])

==== Security

* Fixed: Arbitrary command execution in rudder relay API due to missing parameter sanitization
    (https://issues.rudder.io/issues/14974[#14974])

==== Documentation

* Fixed: Update backup and restore documentation 
    (https://issues.rudder.io/issues/15033[#15033])
* Fixed: Update backup and restore documentation 
    (https://issues.rudder.io/issues/15033[#15033])
* Fixed: Specify that we need more cpu cores  for Rudder server when managing a lot of nodes 
    (https://issues.rudder.io/issues/14940[#14940])
* Fixed: Add a note in the file content methods' docs to indicate they only work in full compliance mode
    (https://issues.rudder.io/issues/15090[#15090])

==== Web - UI & UX

* Fixed: Missing "disabled"  status information in rules table
    (https://issues.rudder.io/issues/15101[#15101])
* Fixed: Menu items can overflow menu width
    (https://issues.rudder.io/issues/15106[#15106])
* Fixed: Loading animation on 404 page is broken
    (https://issues.rudder.io/issues/15105[#15105])
* Fixed: Make node properties editable on the GUI
    (https://issues.rudder.io/issues/10612[#10612])
* Fixed: Font in "recent changes" tooltip on rules page is too big
    (https://issues.rudder.io/issues/14562[#14562])
* Fixed: Rule table search filter is broken after creating or deleting a rule
    (https://issues.rudder.io/issues/15070[#15070])
* Fixed: Start generation date in status is incorrect (it should not be page load date)
    (https://issues.rudder.io/issues/14941[#14941])
* Fixed: Group clone popup does not refresh group list, does not close, and an error when clicking a second time on clone
    (https://issues.rudder.io/issues/15039[#15039])
* Fixed: Webapp tries to load a missing angularjs map file
    (https://issues.rudder.io/issues/14935[#14935])

==== Web - Config management

* Fixed: Clicking on a group in rule configuration does not lead to the group
    (https://issues.rudder.io/issues/15099[#15099])
* Fixed: Generation fails with "Task FutureTask rejected from ThreadPoolExecutor" due to timeout in JS computation
    (https://issues.rudder.io/issues/14465[#14465])
* Fixed: Generation wronly warns with"non stable policy on node" when the same directive is used in two rules
    (https://issues.rudder.io/issues/15022[#15022])

==== Web - Compliance & node report

* Fixed: Directive with at least 3 times the same parameterized generic method leads to missing reports
    (https://issues.rudder.io/issues/15007[#15007])

==== System integration

* Fixed: rudder.auth.admin.password appears in clear text in the logs 
    (https://issues.rudder.io/issues/14946[#14946])

==== API

* Fixed: Missing rule name in compliance API
    (https://issues.rudder.io/issues/14241[#14241])

==== Techniques

* Fixed: Use umask defined in /etc/login.defs in Technique "SSH authorized keys"  for creating missing home dir 
    (https://issues.rudder.io/issues/14916[#14916])
* Fixed: Unexpected reports in Variable from JSON file(dict) when the json file is not present
    (https://issues.rudder.io/issues/14605[#14605])
* Fixed: File download technique generates error report on permissions 
    (https://issues.rudder.io/issues/14992[#14992])

==== Agent

* Fixed: Agent should trim policy_server.dat content 
    (https://issues.rudder.io/issues/14930[#14930])

==== Generic methods

* Fixed: We should test sles and suse classes in ncf tests  
    (https://issues.rudder.io/issues/15110[#15110])
* Fixed: Style test fails because it parses .pyc files 
    (https://issues.rudder.io/issues/15061[#15061])
* Fixed: Syntax error in file_report_content tests on 4.3
    (https://issues.rudder.io/issues/15053[#15053])
* Fixed: Normal ordering is not respected in some policies in 4.3 
    (https://issues.rudder.io/issues/15051[#15051])

==== Generic methods - File Management

* Fixed: permissions_acl_*_absent generic methods report success if no acls binaries are found on the system 
    (https://issues.rudder.io/issues/15121[#15121])
* Fixed: On sles15 there is no games user nor games group and we are using it in some acl tests   
    (https://issues.rudder.io/issues/15112[#15112])

==== Generic methods - Package Management

* Fixed: Improve package management error reporting to suggest avoiding virtual packages
    (https://issues.rudder.io/issues/14582[#14582])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.11 (2019-05-21)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: rudder agent dependencies are missing for rhel8 
    (https://issues.rudder.io/issues/14914[#14914])

==== Web - Nodes & inventories

* Fixed: Inventory may never finish if there is a disk issue or invalid mountpoint
    (https://issues.rudder.io/issues/14190[#14190])

==== Web - Config management

* Fixed: "Dynamic group update time-outed (waited for 10 secondes to finish)" 
    (https://issues.rudder.io/issues/14918[#14918])

==== System techniques

* Fixed: Unexpected status when sending inventory with non default schedule 
    (https://issues.rudder.io/issues/14909[#14909])

==== Techniques

* Fixed: Broken ubuntu version detection in apt settings technique with 5.0+ agents
    (https://issues.rudder.io/issues/14888[#14888])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.10 (2019-05-14)

=== Changes

==== Packaging

* Beautify pg_hba.conf
    (https://issues.rudder.io/issues/8901[#8901])
* Remove version replacement in packages and cleanup RUDDER_VERSION_TO_PACKAGE
    (https://issues.rudder.io/issues/14659[#14659])

==== Performance and scalability

* Document using pg_repack to prevent large disk usage
    (https://issues.rudder.io/issues/14450[#14450])

==== Documentation

* Add a debugging guide page to the doc
    (https://issues.rudder.io/issues/14785[#14785])

==== Web - UI & UX

* Make the Directive and Group sections foldable
    (https://issues.rudder.io/issues/14783[#14783])

==== Techniques

* Port MOTD Technique to DSC
    (https://issues.rudder.io/issues/14313[#14313])

==== Generic methods - File Management

* Add acl dedicated body in ncf_lib
    (https://issues.rudder.io/issues/14815[#14815])
* Add support for audit mode in "apply_gm" for the ncf tests
    (https://issues.rudder.io/issues/14635[#14635])

==== Generic methods

* Change all serverspec ncf tests in testinfra ones
    (https://issues.rudder.io/issues/14799[#14799])

==== Technique editor - UI/UX

* Merge the info and depreciation icon in technique editor
    (https://issues.rudder.io/issues/14665[#14665])

==== Miscellaneous

* Better Technique editor loading message
    (https://issues.rudder.io/issues/14622[#14622])

=== Bug fixes

==== Packaging

* Fixed: Postgresql is not started properly at postinstall on sles12 
    (https://issues.rudder.io/issues/14832[#14832])
* Fixed: Error when upgrading to Rudder 5.0.10 using centos7  with custom postgresql
    (https://issues.rudder.io/issues/14827[#14827])
* Fixed: ncf-api-virtualenv does not have a group created
    (https://issues.rudder.io/issues/11126[#11126])
* Fixed: Debian 8 server fail to install jdk during build
    (https://issues.rudder.io/issues/14765[#14765])
* Fixed: Debian 8 packages fail to build  
    (https://issues.rudder.io/issues/14754[#14754])
* Fixed: build-caching fails on builder with python 2.6 
    (https://issues.rudder.io/issues/14676[#14676])
* Fixed: Import relay sources into rudder repo
    (https://issues.rudder.io/issues/14660[#14660])

==== System integration

* Fixed: Postgresql misconfigured when not the default distrib package (ex: Centos 6 with Postgresql 9.3 from pgfoundry.org)
    (https://issues.rudder.io/issues/6403[#6403])

==== Agent

* Fixed: Script rudder-support-info does not mask credentials
    (https://issues.rudder.io/issues/13657[#13657])
* Fixed: Rudder remote run accept an invalid option -b 
    (https://issues.rudder.io/issues/14852[#14852])
* Fixed: Rudder commands should use rudder provided binaries when available 
    (https://issues.rudder.io/issues/14847[#14847])
* Fixed: When policy cannot be updated, agent says ok: Rudder agent promises were updated. 
    (https://issues.rudder.io/issues/14824[#14824])
* Fixed: Rudder agent check cannot restore saved uuid on AIX 
    (https://issues.rudder.io/issues/14763[#14763])
* Fixed: Rudder agent check does not repair policies if they are broken 
    (https://issues.rudder.io/issues/14692[#14692])

==== Documentation

* Fixed: Disk usage in documentation is insuficiently precise 
    (https://issues.rudder.io/issues/14842[#14842])
* Fixed: Add 2019 CfgMgmgtCamp videos to the docs 
    (https://issues.rudder.io/issues/14731[#14731])
* Fixed: Document that resource file of Techniques are shared to nodes with UTF-8 Encoding *only* (breaks for other encoding)
    (https://issues.rudder.io/issues/13619[#13619])

==== Performance and scalability

* Fixed: Correct disk usage in rudder configuration file 
    (https://issues.rudder.io/issues/14844[#14844])
* Fixed: Default archive retention is too large, which cause very large disk usage 
    (https://issues.rudder.io/issues/14834[#14834])

==== Web - Config management

* Fixed: A technique can have two agent section for the same kind of agent 
    (https://issues.rudder.io/issues/14797[#14797])
* Fixed: Accepting a change request on dynamic group, make the group empty leads an invalid policy generation 
    (https://issues.rudder.io/issues/14758[#14758])
* Fixed: When restoring archive (full or groups) dynamic groups are created empty
    (https://issues.rudder.io/issues/4480[#4480])
* Fixed: In node compliance, the rule name for root server is "distributePolicy", it should be at least "distribute policy"
    (https://issues.rudder.io/issues/14689[#14689])

==== Web - Maintenance

* Fixed: Postgres fills up and can't be vaccumed
    (https://issues.rudder.io/issues/14789[#14789])
* Fixed: Invalid comparision of String and Option[String] in HistorizationService 
    (https://issues.rudder.io/issues/14770[#14770])

==== API

* Fixed: API info does not list endpoints in their sorted order 
    (https://issues.rudder.io/issues/14807[#14807])
* Fixed: Api ordering and tests are broken  
    (https://issues.rudder.io/issues/14652[#14652])

==== System techniques

* Fixed: Sometimes, root server shows up with "No machine inventory" after install
    (https://issues.rudder.io/issues/14627[#14627])
* Fixed: Syntax error in techniques/system/server-roles/1.0/component-check.st
    (https://issues.rudder.io/issues/14808[#14808])
* Fixed: If postgresql is down, agent tried to fix password before checking that its up an running
    (https://issues.rudder.io/issues/14750[#14750])
* Fixed: rudder-directives.cf is included twice in policies 
    (https://issues.rudder.io/issues/14687[#14687])

==== Techniques

* Fixed: Technique "SSH authorized keys" creates home directory with perms root:root when it does not exists yet 
    (https://issues.rudder.io/issues/14732[#14732])

==== Generic methods

* Fixed: Fix badly translated files for ncf services tests 
    (https://issues.rudder.io/issues/14804[#14804])
* Fixed: Missing '_not_kept' state in method outcome 
    (https://issues.rudder.io/issues/14649[#14649])

==== Technique editor - UI/UX

* Fixed: Having a long Technique name breaks display of title  
    (https://issues.rudder.io/issues/14663[#14663])
* Fixed: The deprecated tooltip doesn't say why it is deprecated
    (https://issues.rudder.io/issues/13031[#13031])
* Fixed: Improve display of technique list in technique editor
    (https://issues.rudder.io/issues/14282[#14282])

==== Web - Compliance & node report

* Fixed: Reporting missing if several generic methods with same class_prefix and different condition applied 
    (https://issues.rudder.io/issues/9130[#9130])
* Fixed: Reporting missing if several generic methods with same class_prefix and different condition applied 
    (https://issues.rudder.io/issues/9130[#9130])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* emb3dd3d server
* Tobias Ell
* Florian Heigl
* Janos Mattyasovszky

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.9 (2019-04-15)

=== Changes

==== Packaging

* Remove psl dependency on curl
    (https://issues.rudder.io/issues/14500[#14500])
* Repair and adapt AIX agent to work with 5.0 changes 
    (https://issues.rudder.io/issues/14467[#14467])
* Reduce the size of the agent by removing cf-monitord
    (https://issues.rudder.io/issues/14406[#14406])

==== Documentation

* Add Windows known issues and improve install Windows software how-to
    (https://issues.rudder.io/issues/14446[#14446])
* Update antora theme/tools to 2.0.0
    (https://issues.rudder.io/issues/14385[#14385])

==== Web - UI & UX

* Add a "Copy to clipboard" button for Node properties and show its type
    (https://issues.rudder.io/issues/14593[#14593])
* Add a "Copy to clipboard" button for Node properties and show its type
    (https://issues.rudder.io/issues/14593[#14593])
* New display of Directives and Groups in Rule details
    (https://issues.rudder.io/issues/14536[#14536])
* New modern look for all tables
    (https://issues.rudder.io/issues/9557[#9557])

==== Web - Config management

* New tab in group details: display Rules applied to the group
    (https://issues.rudder.io/issues/11911[#11911])

==== API

* Add "Last seen" to Node API 
    (https://issues.rudder.io/issues/7922[#7922])

==== Web - Nodes & inventories

* Add Linux Mint support in inventories
    (https://issues.rudder.io/issues/10812[#10812])

==== Techniques

* Support separated policy generation for technique "Variable from JSON file (dict)"
    (https://issues.rudder.io/issues/14160[#14160])
* Support separated policy generation for technique "Variable from JSON file (dict)"
    (https://issues.rudder.io/issues/14160[#14160])

==== Generic methods

* Add a generic method call to test generic method
    (https://issues.rudder.io/issues/14563[#14563])
* Add bundle dedicated to the ncf tests
    (https://issues.rudder.io/issues/14311[#14311])
* Add systemd commands to the library of standard system command paths
    (https://issues.rudder.io/issues/14401[#14401])
* Improve service_{start/stop} tests
    (https://issues.rudder.io/issues/14323[#14323])

==== Technique editor - UI/UX

* We don't know where to click on a generic method to edit it
    (https://issues.rudder.io/issues/14317[#14317])

=== Bug fixes

==== Packaging

* Fixed: When installing rudder-agent, there's a long wait of run interval/2, so up to several hours
    (https://issues.rudder.io/issues/14644[#14644])
* Fixed: During installation of the agent, when staring "rudder agent" service, there is numerous error about missing '/opt/rudder/etc/uuid.hive' file
    (https://issues.rudder.io/issues/14616[#14616])
* Fixed: Debian 8 backports repository does not exist anymore, breaking our builds
    (https://issues.rudder.io/issues/14608[#14608])
* Fixed: Error message when installing or upgrading Rudder server about missing pid file
    (https://issues.rudder.io/issues/13767[#13767])
* Fixed: Build openssl for Slackware, so the agent can update promises
    (https://issues.rudder.io/issues/14570[#14570])
* Fixed: Error message when installing rudder-agent  on rpm based systems due to missing directory '/var/rudder/inventories'
    (https://issues.rudder.io/issues/14348[#14348])

==== System integration

* Fixed: Agent stderr shows up in /var/log/apache2/error.log
    (https://issues.rudder.io/issues/14602[#14602])
* Fixed: Allow changing cf-serverd loglevel and set info as default
    (https://issues.rudder.io/issues/8529[#8529])
* Fixed: Only one Node below a Rudder server can be run through remote run API
    (https://issues.rudder.io/issues/14391[#14391])
* Fixed: Manage rudder webapp shutdown correctly in case of fatal exception at startup
    (https://issues.rudder.io/issues/14281[#14281])
* Fixed: Windows 10 inventory is not fully supported
    (https://issues.rudder.io/issues/14295[#14295])
* Fixed: Error about invalid variable in httpd at Rudder install on centos 7
    (https://issues.rudder.io/issues/14592[#14592])

==== Agent

* Fixed: Slackware agent depends on mysql
    (https://issues.rudder.io/issues/14472[#14472])

==== System techniques

* Fixed: Agent connection cache does not work, and does not improve performance as expected
    (https://issues.rudder.io/issues/14342[#14342])
* Fixed: Bad reporting mode for "Monitoring; No Rudder monitoring information to share with the server"
    (https://issues.rudder.io/issues/14532[#14532])
* Fixed: Remove cf-monitord check on component "Binaries update"  
    (https://issues.rudder.io/issues/14561[#14561])
* Fixed: Missing "update" reports on node
    (https://issues.rudder.io/issues/12137[#12137])

==== Plugins integration

* Fixed: Typo in rudder-pkg when package version is incompatible
    (https://issues.rudder.io/issues/14408[#14408])

==== Documentation

* Fixed: uuid.hive is not present afet an install or an upgradie ofrudder agent to latest 4.1.x, 4.3.x and 5.0.x on rpm system purges the uuid.hive
    (https://issues.rudder.io/issues/14264[#14264])
* Fixed: Command to upgrade server from old 4.1/4.2/4.3 to 5.0  does not upgrade rudder-agent, breaking everything
    (https://issues.rudder.io/issues/14415[#14415])
* Fixed: Command to upgrade server from old 4.1/4.2/4.3 to 5.0  does not upgrade rudder-agent, breaking everything
    (https://issues.rudder.io/issues/14415[#14415])
* Fixed: Update mustache templating method documentation to detail the windows syntax
    (https://issues.rudder.io/issues/14451[#14451])

==== Architecture - Internal libs

* Fixed: Rudder postgres unit test are broken
    (https://issues.rudder.io/issues/14599[#14599])

==== Web - Config management

* Fixed: Policies generated for Rudder server have wrong permissions
    (https://issues.rudder.io/issues/14594[#14594])
* Fixed: UI "settings" for management of hooks works inconsistently
    (https://issues.rudder.io/issues/14386[#14386])

==== Web - UI & UX

* Fixed: There is no visual indication of sort in node table
    (https://issues.rudder.io/issues/14434[#14434])
* Fixed: JS error in rule pages, and Directives don't show in the list of directives
    (https://issues.rudder.io/issues/14573[#14573])
* Fixed: Fix some CSS issues following the style change of the Datatables
    (https://issues.rudder.io/issues/14463[#14463])
* Fixed: Typo in error message when aix plugin is not there
    (https://issues.rudder.io/issues/14426[#14426])

==== Web - Compliance & node report

* Fixed: Improve message on Node compliance details when  reports are outdated
    (https://issues.rudder.io/issues/14380[#14380])
* Fixed: Missing report on generic method "command exec" with $()
    (https://issues.rudder.io/issues/14390[#14390])

==== Security

* Fixed: Missing eventlogs for technique editor action and technique update
    (https://issues.rudder.io/issues/14312[#14312])

==== Web - Nodes & inventories

* Fixed: Incoherent state when accepting a Node, where node is accepted but now available in UI (error when creating Node entry)
    (https://issues.rudder.io/issues/14430[#14430])
* Fixed: System groups should be treated like normal groups and display their list of nodes 
    (https://issues.rudder.io/issues/11796[#11796])
* Fixed: Error about failed  move of machine inventory doesn't give sufficient context information
    (https://issues.rudder.io/issues/14522[#14522])

==== Performance and scalability

* Fixed: If a rule targets too many groups, policy generation fails
    (https://issues.rudder.io/issues/14392[#14392])
* Fixed: Improve 'rsyslog' to manage larger load of reports
    (https://issues.rudder.io/issues/14506[#14506])
* Fixed: Cron job checking rudder agent health, is ran every  5 minutes exactly, causing resource usage spike
    (https://issues.rudder.io/issues/14258[#14258])

==== Techniques

* Fixed: SNMP technique on windows wrongly parse the authorized sources
    (https://issues.rudder.io/issues/14368[#14368])

==== Technique editor - UI/UX

* Fixed: Padding in technique editor inputs makes you think there is a space before the value
    (https://issues.rudder.io/issues/14340[#14340])
* Fixed: Error in technique editor when there is  "$()" in  a parameter of a method
    (https://issues.rudder.io/issues/14549[#14549])

==== Generic methods

* Fixed: _classes_sanitize should be strict on the classes cancelled
    (https://issues.rudder.io/issues/14578[#14578])
* Fixed: Policy generation fails after upgrade  to 4.3: Undefined bundle lines_present
    (https://issues.rudder.io/issues/14548[#14548])
* Fixed: Expected repaired class in ncf tests are not correctly defined
    (https://issues.rudder.io/issues/14538[#14538])
* Fixed: Reporting when executing severspec is not correct in ncf tests
    (https://issues.rudder.io/issues/14537[#14537])
* Fixed: monitoring.csv accumulate temporary files that can blow up the filesystem
    (https://issues.rudder.io/issues/13716[#13716])

==== Generic methods - Package Management

* Fixed: Broken yum usage with old package promises on CentOS
    (https://issues.rudder.io/issues/14546[#14546])

==== Web - Technique editor

* Fixed: Technique editor duplicate techniques for each change
    (https://issues.rudder.io/issues/14370[#14370])
* Fixed: Reporting fails on NCF when service start/stop is guarded by a class
    (https://issues.rudder.io/issues/14404[#14404])

==== Generic methods - Service Management

* Fixed: ncf_services does not work on slackware
    (https://issues.rudder.io/issues/14471[#14471])

==== Generic methods - File Management

* Fixed: Improve method 'file copy from shared files'  parameters documentation
    (https://issues.rudder.io/issues/14361[#14361])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Aspid ASM
* Maxime Longuet
* Janos Mattyasovszky

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.8 (2019-02-28)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: Upgrade to 5.0.7 fails because rudder-upgrade script returns 1
    (https://issues.rudder.io/issues/14400[#14400])

==== Generic methods

* Fixed: Fix normal ordering in file report {tail/head}
    (https://issues.rudder.io/issues/14396[#14396])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.7 (2019-02-28)

=== Changes

==== Architecture - Internal libs

* Remove deprecated (and not use) code causing warning
    (https://issues.rudder.io/issues/14291[#14291])

==== Agent

* Add config id to rudder agent info
    (https://issues.rudder.io/issues/14306[#14306])

==== Generic methods - File Management

* Add a generic method that displays selected lines from a file in reports
    (https://issues.rudder.io/issues/14357[#14357])

==== Generic methods

* Add serverspec tests to the ncf ones
    (https://issues.rudder.io/issues/14314[#14314])

=== Bug fixes

==== System integration

* Fixed: Patch cf-serverd to change loglevel on agent refusal
    (https://issues.rudder.io/issues/8529[#8529])
* Fixed: Rudder database grows with time because of defaults values for  autovacuum that don't fit our needs
    (https://issues.rudder.io/issues/14336[#14336])
* Fixed: qa-test break because of repository layout change
    (https://issues.rudder.io/issues/14289[#14289])

==== Packaging

* Fixed: Never modify policy_server.dat on upgrade
    (https://issues.rudder.io/issues/14337[#14337])
* Fixed: "/var/rudder/inventories: no such dir" error message on first run
    (https://issues.rudder.io/issues/14257[#14257])

==== Documentation

* Fixed: Typo in "Replacement" in doc
    (https://issues.rudder.io/issues/14137[#14137])
* Fixed: Root of webapp docs changed
    (https://issues.rudder.io/issues/14284[#14284])
* Fixed: variable_dict_from_file: Path of file is unclear if relative or absolute
    (https://issues.rudder.io/issues/14117[#14117])

==== Web - Config management

* Fixed: Add an optional hook to trigger node update on nodes with new policies
    (https://issues.rudder.io/issues/14331[#14331])
* Fixed: Add an optional hook to trigger node update on nodes with new policies
    (https://issues.rudder.io/issues/14331[#14331])
* Fixed: Directive parameter values are mixed between directives
    (https://issues.rudder.io/issues/14322[#14322])

==== Web - Nodes & inventories

* Fixed: Windows 2019 doesn't show up correctly in node list
    (https://issues.rudder.io/issues/14362[#14362])
* Fixed: Mandatory fields for new inventories are not correctly checked 
    (https://issues.rudder.io/issues/13962[#13962])

==== Architecture - Refactoring

* Fixed: We are comparing Option[String] and String
    (https://issues.rudder.io/issues/14346[#14346])

==== Web - UI & UX

* Fixed: Fix compliance bars text color
    (https://issues.rudder.io/issues/14294[#14294])
* Fixed: Drag and drop of a generic method displays a phantom method
    (https://issues.rudder.io/issues/14321[#14321])

==== Architecture - Dependencies

* Fixed: Compilation fails with Java 11
    (https://issues.rudder.io/issues/14290[#14290])

==== Techniques

* Fixed: unexpected reports in zypper repo management technique
    (https://issues.rudder.io/issues/14347[#14347])
* Fixed: sshConfiguration technique should not authorize ssh password authent by default
    (https://issues.rudder.io/issues/14316[#14316])

==== System techniques

* Fixed: Technique uses /root as an hardcoded value for the home of user root
    (https://issues.rudder.io/issues/6412[#6412])

==== Generic methods - File Management

* Fixed: File lines absent generic method doesn't report anything when the file doesn't exist
    (https://issues.rudder.io/issues/14246[#14246])

==== Generic methods

* Fixed: ncf 4.1 is not compatible anymore with agent 3.1
    (https://issues.rudder.io/issues/14293[#14293])
* Fixed: "monitoring" technique is broken since we removed def.policy_server
    (https://issues.rudder.io/issues/14285[#14285])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky
* Tobias Ell

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.6 (2019-02-04)

=== Changes

=== Bug fixes

==== Web - Nodes & inventories

* Fixed: RHEL 7.6 appears as "Other Linux"
    (https://issues.rudder.io/issues/14200[#14200])

==== Documentation

* Fixed: Remove "repository" from Rudder repository name
    (https://issues.rudder.io/issues/14262[#14262])

==== System integration

* Fixed: Bad rights for hooks
    (https://issues.rudder.io/issues/14273[#14273])

==== Web - UI & UX

* Fixed: JS in directive name is executed on rule table if the directive is disabled
    (https://issues.rudder.io/issues/14271[#14271])
* Fixed: Rounding error in compliance bar
    (https://issues.rudder.io/issues/10773[#10773])

==== Architecture - Dependencies

* Fixed: Update very old maven-assembly version used for template-cli
    (https://issues.rudder.io/issues/14247[#14247])
* Fixed: Duplicate dependency "jsr305" in rudder-core/pom.xml
    (https://issues.rudder.io/issues/14248[#14248])
* Fixed: Update very old maven-assembly version used for template-cli
    (https://issues.rudder.io/issues/14247[#14247])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.5 (2019-01-30)

=== Changes

==== System integration

* Impossible to change keys of a Node using rudder-keys cli
    (https://issues.rudder.io/issues/14207[#14207])

==== Documentation

* Update links in doc to rudder.io
    (https://issues.rudder.io/issues/14203[#14203])
* Add some known issues in the known issue of the DSC doc
    (https://issues.rudder.io/issues/14150[#14150])
* Add some known issues in the known issue of the DSC doc
    (https://issues.rudder.io/issues/14150[#14150])

==== Web - Maintenance

* Update links in Rudder interface to use rudder.io
    (https://issues.rudder.io/issues/14205[#14205])

==== Web - Config management

* Configure report value of technique from technique editor
    (https://issues.rudder.io/issues/14091[#14091])

==== Techniques

* Port techniques downloadFile & cronManagement to separated policy generation 
    (https://issues.rudder.io/issues/14002[#14002])

==== Technique editor - UI/UX

* In the technique editor, scrolling through the GM should not mask the filter
    (https://issues.rudder.io/issues/14178[#14178])
* Manage caching of technique editor resources (css/js) with Rudder version
    (https://issues.rudder.io/issues/14194[#14194])
* Display documentation of ncf methods directly in the editor
    (https://issues.rudder.io/issues/14172[#14172])

==== Generic methods

* Update to 3.12.1 CFEngine stdlib
    (https://issues.rudder.io/issues/14129[#14129])

=== Bug fixes

==== Packaging

* Fixed: "rudder-init" script does not allow the "auto" option
    (https://issues.rudder.io/issues/14134[#14134])

==== Documentation

* Fixed: Missing documentation for "state" and "policymode" parameter expansion
    (https://issues.rudder.io/issues/13915[#13915])
* Fixed: Jinja templating iteration example in the doc is invalid
    (https://issues.rudder.io/issues/14179[#14179])

==== Web - UI & UX

* Fixed: Error when creating a rule
    (https://issues.rudder.io/issues/14245[#14245])
* Fixed: Rudder node id is confused with machine id and not selectable by triple-click
    (https://issues.rudder.io/issues/14243[#14243])
* Fixed: API token expiration date form appears behind the popup
    (https://issues.rudder.io/issues/14199[#14199])
* Fixed: Enable/Disable button text should be capitalized
    (https://issues.rudder.io/issues/14185[#14185])

==== Web - Compliance & node report

* Fixed: we can inject html & javascript in Rudder tables
    (https://issues.rudder.io/issues/14221[#14221])

==== Web - Maintenance

* Fixed: Constraints on table nodecompliancelevels are not valid
    (https://issues.rudder.io/issues/14218[#14218])

==== Performance and scalability

* Fixed: Index nodeid_idx is not used and consumes a lot of disk space for nothing
    (https://issues.rudder.io/issues/14149[#14149])

==== Web - Config management

* Fixed: When hooks are exiting with an error we can have stackoverflow error if there are many of them
    (https://issues.rudder.io/issues/10973[#10973])
* Fixed: When refreshing a rule details, the current tab is not memorized
    (https://issues.rudder.io/issues/4904[#4904])

==== API

* Fixed: Logs full of WARN  Attribute 'apiAuthorizationKind' or 'expirationTimestamp' is defined for API account but it will be ignored
    (https://issues.rudder.io/issues/13913[#13913])

==== Techniques

* Fixed: Technique "file content from remote template" does not work on the Rudder server when using remote file
    (https://issues.rudder.io/issues/14211[#14211])
* Fixed: "File content from remote template" technique ads tabs in the output file
    (https://issues.rudder.io/issues/14188[#14188])

==== System techniques

* Fixed: improve error message when the node cannot get the uuid from the server
    (https://issues.rudder.io/issues/14176[#14176])
* Fixed: psql should not freeze the agent
    (https://issues.rudder.io/issues/14156[#14156])
* Fixed: "classes promises do not support promise locking" warning message when running the agent
    (https://issues.rudder.io/issues/14132[#14132])
* Fixed: Add compatibility sles classes in failsafe
    (https://issues.rudder.io/issues/13975[#13975])
* Fixed: Missing report on File key-value parameter in list
    (https://issues.rudder.io/issues/14164[#14164])

==== Plugins integration

* Fixed: Separated policy generation does not work correctly with Rudder DSC agent
    (https://issues.rudder.io/issues/14038[#14038])

==== Web - Nodes & inventories

* Fixed: Inventory watcher is too quick and does not wait for file close
    (https://issues.rudder.io/issues/14237[#14237])

==== Agent

* Fixed: rudder agent inventory wrongly states that we are not in full compliance mode
    (https://issues.rudder.io/issues/13882[#13882])
* Fixed: Create a rudder server trigger_policy_generation command
    (https://issues.rudder.io/issues/14052[#14052])

==== System integration

* Fixed: Every agent check for postgresql and ldap partition size, resulting in possible overzealous shutting down of Rudder on node
    (https://issues.rudder.io/issues/14162[#14162])

==== Server components

* Fixed: cf-serverd may listen on port 8080 preventing rudder-jetty from running
    (https://issues.rudder.io/issues/13982[#13982])

==== Generic methods

* Fixed: Avoid  checking for exit_on_lock option on newer yum
    (https://issues.rudder.io/issues/14235[#14235])
* Fixed: Enable 4h cache on available upgrades list in old package bodies
    (https://issues.rudder.io/issues/14225[#14225])
* Fixed: Error in inform mode about undefined @args in rudder agent output
    (https://issues.rudder.io/issues/14214[#14214])
* Fixed: file_from_string_mustache GM unwanted behaviour when the mustache template use non-printable elements
    (https://issues.rudder.io/issues/14215[#14215])
* Fixed: Generic method in 4.3 should not use the class has_promiser_stack
    (https://issues.rudder.io/issues/14167[#14167])

==== Technique editor - UI/UX

* Fixed: Filter in generic method should not be case sensitive
    (https://issues.rudder.io/issues/14216[#14216])
* Fixed: Categories in Technique Editor do not work in IE 11.26.70
    (https://issues.rudder.io/issues/14181[#14181])

==== Generic methods - File Management

* Fixed: Jinja templating method does not correctly clean up temporary files in audit mode
    (https://issues.rudder.io/issues/13666[#13666])
* Fixed: Generic Method "File key-value present with option " treats the option as one of the value
    (https://issues.rudder.io/issues/14186[#14186])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Valentin Lelong

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.4 (2019-01-10)

=== Changes

==== Packaging

* Cleanup rudder promises generated
    (https://issues.rudder.io/issues/13996[#13996])
* Update CFEngine to 3.12.1
    (https://issues.rudder.io/issues/13927[#13927])

==== Documentation

* Add a page with an array for all versions info
    (https://issues.rudder.io/issues/13956[#13956])
* Add a page for videos about Rudder
    (https://issues.rudder.io/issues/14029[#14029])
* Update rudder-setup url in docs
    (https://issues.rudder.io/issues/14034[#14034])
* Render changelogs in Rudder doc
    (https://issues.rudder.io/issues/13928[#13928])
* Document some node-level system variables
    (https://issues.rudder.io/issues/13945[#13945])

==== System integration

* Missing flag file to trigger a policy generation
    (https://issues.rudder.io/issues/14050[#14050])

==== Web - UI & UX

* Remove jquery-ui related css libraries
    (https://issues.rudder.io/issues/13920[#13920])

==== Techniques

* Download files needed to build rudder-techniques package from repository.rudder.io
    (https://issues.rudder.io/issues/14036[#14036])
* Add a technique to manage basic SNMP configuration
    (https://issues.rudder.io/issues/13602[#13602])
* Technique File download (Rudder server) has a borken posthook and should incorporate a windows and a linux section
    (https://issues.rudder.io/issues/13918[#13918])

==== Technique editor - UI/UX

* Add a filter on generic method tree to find methods faster
    (https://issues.rudder.io/issues/14013[#14013])
* Allow to clone Generic methods in a technique in the editor
    (https://issues.rudder.io/issues/11676[#11676])
* Make conditions visible in the Technique editor
    (https://issues.rudder.io/issues/12740[#12740])

=== Bug fixes

==== Packaging

* Fixed: uuid.hive file should not be a rudder-agent package conf file
    (https://issues.rudder.io/issues/14062[#14062])
* Fixed: Force http 1.1 when downloading curl
    (https://issues.rudder.io/issues/14059[#14059])
* Fixed: When installing a rudder root server (on debian), it asks to run rudder-node-to-relay
    (https://issues.rudder.io/issues/11630[#11630])
* Fixed: Change packaging to allow openjdk > 8 
    (https://issues.rudder.io/issues/13896[#13896])
* Fixed: When we stop rudder-jetty, it says it stops Jetty 7 (we are using Jetty 9 ...)
    (https://issues.rudder.io/issues/13929[#13929])

==== Agent

* Fixed: Agent run errors are not outputed on stderr anymore
    (https://issues.rudder.io/issues/14061[#14061])
* Fixed: Os name for sles 12 is not correct in 5.0 inventories
    (https://issues.rudder.io/issues/13964[#13964])

==== Miscellaneous

* Fixed: Rudder-jetty depends on jdk8 but always try to install jdk9 as dependency
    (https://issues.rudder.io/issues/14024[#14024])

==== Documentation

* Fixed: Use B instead of b for bytes in the doc
    (https://issues.rudder.io/issues/14126[#14126])
* Fixed: Add documentation about rudder <-> plugin version compatibility in docs
    (https://issues.rudder.io/issues/14099[#14099])
* Fixed: Broken 4.1/4.3 doc build
    (https://issues.rudder.io/issues/14048[#14048])
* Fixed: Broken current redirect in docs
    (https://issues.rudder.io/issues/14047[#14047])

==== Web - Config management

* Fixed: Cannot modify groups when workflow are enabled
    (https://issues.rudder.io/issues/14056[#14056])

==== Plugins integration

* Fixed: indexes on nodecompliancelevels table are not valid and table ArchivedReportsExecution is never used
    (https://issues.rudder.io/issues/14007[#14007])

==== Performance and scalability

* Fixed: A lot of space is wasted on table nodecompliance and nodeconfigurations due to pretty jsonification
    (https://issues.rudder.io/issues/14014[#14014])
* Fixed: Massive performance penalty in policy generation due to invalid usage of StringTemplate
    (https://issues.rudder.io/issues/13987[#13987])
* Fixed: Load all ncf files in one go (or two)
    (https://issues.rudder.io/issues/13859[#13859])

==== Web - Maintenance

* Fixed: Impossible to log in with root admin 
    (https://issues.rudder.io/issues/13910[#13910])

==== Web - UI & UX

* Fixed: In the node details, clicking on the link to the policy server doesn't redirect to the policy server
    (https://issues.rudder.io/issues/13834[#13834])
* Fixed: Alignement of radio button on Settings page is still imperfect
    (https://issues.rudder.io/issues/13889[#13889])

==== Techniques

* Fixed: "Job Scheduler" Technique miss runs when using a non-default agent execution frequency
    (https://issues.rudder.io/issues/4840[#4840])

==== System techniques

* Fixed: Inventory fails since the files are not copied on the right location
    (https://issues.rudder.io/issues/13966[#13966])
* Fixed: "File from shared folder" technique in very old version does not work anymore since a common variable has been removed
    (https://issues.rudder.io/issues/13932[#13932])

==== Web - Nodes & inventories

* Fixed: Huge latency between inventory sent and inventory appears in Rudder
    (https://issues.rudder.io/issues/14080[#14080])

==== Generic methods

* Fixed: Error in the info (rudder agent run -i) output of the agent at first run
    (https://issues.rudder.io/issues/13951[#13951])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.3 (2018-11-26)

=== Changes

==== API

* Add rudder server version to the Rest API (system/info endpoint)
(https://issues.rudder.io/issues/13654[#13654])

==== System techniques

* Remove default server value from system techniques
(https://issues.rudder.io/issues/13819[#13819])

==== Techniques

* Provide a rudder.json file with initial policies
(https://issues.rudder.io/issues/13805[#13805])

==== Documentation

* Cleanup the ncf repo (https://issues.rudder.io/issues/13651[#13651])

=== Bug fixes

==== Plugins integration

* Fixed: Improve error messsage when path to install a plugin package is
not correct (https://issues.rudder.io/issues/13891[#13891])

==== Packaging

* Fixed: Rudder agent 4.3 needs libxml-treepp-perl on debian
(https://issues.rudder.io/issues/12599[#12599])
* Fixed: Slackware agent is not started at boot
(https://issues.rudder.io/issues/13850[#13850])
* Fixed: Error when uninstalling rudder-webapp and ncf-api-virtualenv
(https://issues.rudder.io/issues/11206[#11206])
* Fixed: Don’t create crontab entry at Rudder agent install but during
first run (https://issues.rudder.io/issues/13846[#13846])
* Fixed: Remove unnecessary conflict dependency with openjdk 9 on debian
(https://issues.rudder.io/issues/12664[#12664])
* Fixed: Missing _ in slackware package name
(https://issues.rudder.io/issues/13839[#13839])
* Fixed: Download Rudder sources from the new repository
(https://issues.rudder.io/issues/13838[#13838])
* Fixed: Agent should depend on a logging system on SUSE
(https://issues.rudder.io/issues/13788[#13788])
* Fixed: On rudder-webapp upgrade, ncf.conf file is not commited
(https://issues.rudder.io/issues/13679[#13679])

==== Agent

* Fixed: Upgrade CFEngine to 3.10.5
(https://issues.rudder.io/issues/13851[#13851])
* Fixed: ``rudder-keys change-key'' does not check for key file
existence (https://issues.rudder.io/issues/12496[#12496])
* Fixed: When ``policy-server.dat'' is missing, generated inventory is
not legit (https://issues.rudder.io/issues/11715[#11715])
* Fixed: /var/log/rudder/agent-check/check.log should contains only
error level messages (https://issues.rudder.io/issues/12230[#12230])
* Fixed: rudder remote run error, and unable to pass -i option
(https://issues.rudder.io/issues/11318[#11318])
* Fixed: Command ``rudder remote run -a'' does not warn about missing
token (https://issues.rudder.io/issues/11417[#11417])
* Fixed: Add a warn message when agent run is incomplete
(https://issues.rudder.io/issues/10751[#10751])
* Fixed: Command ``rudder agent reset'' sets incorrect permission in
/var/rudder/cfengine-community/inputs
(https://issues.rudder.io/issues/12410[#12410])
* Fixed: ``rudder agent info'' returns invalid report mode for not yet
accepted nodes (https://issues.rudder.io/issues/12992[#12992])
* Fixed: Missing spaces between key and message on rudder agent run
report when using -w option
(https://issues.rudder.io/issues/13663[#13663])

==== Performance and scalability

* Fixed: There are still tables expectedreports & expectesreportsnodes
on upgraded Rudder 4.x and 5.x,
(https://issues.rudder.io/issues/13770[#13770])
* Fixed: After a node is deleted, a policy generation is started every 5
secondes (https://issues.rudder.io/issues/13845[#13845])
* Fixed: Invalid value reported for Node expected reports saved in base
in Rudder log (https://issues.rudder.io/issues/13418[#13418])

==== Security

* Fixed: Impossible to update promises when using a debian9 or Ubuntu 18
server and older distributions as Nodes (incompatible openssl version)
(https://issues.rudder.io/issues/13690[#13690])

==== System integration

* Fixed: ``rudder-pkg enable-all'' command fails when a plugin has no
jar (https://issues.rudder.io/issues/13785[#13785])
* Fixed: Bad log level during generation
(https://issues.rudder.io/issues/9512[#9512])
* Fixed: Init check on group All classic Nodes known by Rudder (Using a
CFEngine based agent) always tries to rewrite the group
(https://issues.rudder.io/issues/13792[#13792])

==== Documentation

* Fixed: Windows doc has disappeared
(https://issues.rudder.io/issues/13880[#13880])
* Fixed: Document syslog port 5514 if Rudder server is an ubuntu < 14
(https://issues.rudder.io/issues/11016[#11016])
* Fixed: No favicon for Rudder doc on embeded doc
(https://issues.rudder.io/issues/13520[#13520])
* Fixed: Fix path to jinja2_custom.py in jinja2 templating doc
(https://issues.rudder.io/issues/13784[#13784])

==== Web - Config management

* Fixed: The password field allows storing a password without any
selected hash (https://issues.rudder.io/issues/12198[#12198])
* Fixed: Spinning compliance in nodes list on a disabled node
(https://issues.rudder.io/issues/12649[#12649])
* Fixed: Spinning compliance in nodes list on a disabled node
(https://issues.rudder.io/issues/12649[#12649])
* Fixed: ``Not copying missing license file into'' in webapp log
(https://issues.rudder.io/issues/10917[#10917])
* Fixed: Missing node state variable expansion in directive
(https://issues.rudder.io/issues/13671[#13671])
* Fixed: Add full path to shared-folder in description of ``Download
file from shared folder'' Technique
(https://issues.rudder.io/issues/13530[#13530])

==== Web - UI & UX

* Fixed: Wrong text color in table header in Rule page
(https://issues.rudder.io/issues/13835[#13835])
* Fixed: Quotes in reports are displayed as " in the web interface
(https://issues.rudder.io/issues/13349[#13349])
* Fixed: Upgrade loading wheel with a new look
(https://issues.rudder.io/issues/8622[#8622])
* Fixed: On Dashboard, when we have 100% of something, the pie is
including a confusing white line
(https://issues.rudder.io/issues/12233[#12233])
* Fixed: Imperfect alignement of radio button
(https://issues.rudder.io/issues/13512[#13512])
* Fixed: No color difference on hover on the user menu
(https://issues.rudder.io/issues/12926[#12926])
* Fixed: ``Configure the default state'' is lacking explanations
(https://issues.rudder.io/issues/12462[#12462])
* Fixed: Bad display of radio button on the Reports Database page in
Rudder 5.0 (https://issues.rudder.io/issues/13476[#13476])
* Fixed: Remove static ids in Password section
(https://issues.rudder.io/issues/13457[#13457])
* Fixed: Button to enable a technique in Directive Screen is not
working, should be a link to the Technique
(https://issues.rudder.io/issues/13779[#13779])
* Fixed: In directive page, tooltip is not correctly aligned with text
(https://issues.rudder.io/issues/13511[#13511])
* Fixed: The ``hardware'' tab is not displayed in accept new nodes
screen (https://issues.rudder.io/issues/13688[#13688])

==== Web - Nodes & inventories

* Fixed: When a node is deleted, its generated promises are not removed
(https://issues.rudder.io/issues/4709[#4709])
* Fixed: Inventory keeps its key certified when node is deleted
(https://issues.rudder.io/issues/9149[#9149])
* Fixed: Missing gateway, network in network interface details
(https://issues.rudder.io/issues/13804[#13804])
* Fixed: Network group criteria not working
(https://issues.rudder.io/issues/13772[#13772])
* Fixed: Node details shows Operating System Type: MSWin for Windows
node rather than Windows (https://issues.rudder.io/issues/6019[#6019])
* Fixed: The error message for bad inventory signature is unclear
(https://issues.rudder.io/issues/9192[#9192])
* Fixed: Network, mask and gateway not correctly parsed from inventory
(https://issues.rudder.io/issues/13803[#13803])

==== Web - Compliance & node report

* Fixed: Compliance error (missing) when a directive is applied by two
rules on a node (https://issues.rudder.io/issues/13674[#13674])

==== API

* Fixed: Remove old ``machyne type'' api Rest typo since it should not
be called anymore (https://issues.rudder.io/issues/13795[#13795])
* Fixed: Tags in rules are ignored in POST API
(https://issues.rudder.io/issues/13374[#13374])

==== Techniques

* Fixed: Option description for ``File download (Rudder server)''
technique is misleading (https://issues.rudder.io/issues/13887[#13887])
* Fixed: Technique ``Cron job v3.0'' does not use the ``user'' setting
with predefined scheduled (https://issues.rudder.io/issues/8004[#8004])
* Fixed: Missing reports on password component on ``User management''
Technique in audit mode (https://issues.rudder.io/issues/9474[#9474])
* Fixed: Enforce checkbox tooltip in ``Group management'' Technique is
misleading (https://issues.rudder.io/issues/13489[#13489])
* Fixed: Missing report with `File and directory basics' Technique in
audit mode when checking perms on non existing file
(https://issues.rudder.io/issues/11653[#11653])
* Fixed: Broken reporting when copying a directory from the Rudder
server without specifying the trailing / in the destination
(https://issues.rudder.io/issues/13290[#13290])
* Fixed: Missing report for post-modification hook in Technique ``File
download (Rudder server)''
(https://issues.rudder.io/issues/13717[#13717])
* Fixed: Details of usage of technique ``Variable from command output
(string)'' is not clear (https://issues.rudder.io/issues/12058[#12058])
* Fixed: Some files in the techniques repository do not present any
licence header (https://issues.rudder.io/issues/13633[#13633])
* Fixed: Technique ``cron job'' refuses task user name if it contains
hyphen (https://issues.rudder.io/issues/12960[#12960])
* Fixed: Missing report for component ``Post-modification hook'' when
cleaning files with ``File and directory basics'' Technique version 4.1
(https://issues.rudder.io/issues/13786[#13786])

==== System techniques

* Fixed: Mustache templates are not processed at all (including
cron.d/rudder-agent file)
(https://issues.rudder.io/issues/13885[#13885])
* Fixed: Slackware agent cron.d is broken in system technique
(https://issues.rudder.io/issues/13848[#13848])

==== Server components

* Fixed: server command based on jq should exit when jq is not installed
and explain to install it
(https://issues.rudder.io/issues/13682[#13682])

==== Generic methods

* Fixed: Typo in ``File content'' generic method description
(https://issues.rudder.io/issues/13883[#13883])
* Fixed: Generic method ``File_remove'' can delete empty directories
(https://issues.rudder.io/issues/12857[#12857])
* Fixed: Scheduler classes have incomplete labels
(https://issues.rudder.io/issues/8008[#8008])

==== Web - Technique editor

* Fixed: In technique editor, on save, we get ``success'' but some
errors are shallowed (https://issues.rudder.io/issues/12210[#12210])

==== Generic methods - File Management

* Fixed: Generic Method ``permission dirs'' incorrect reporting when
target path is a file (https://issues.rudder.io/issues/10689[#10689])
* Fixed: ``File key-value present'' Generic Method and ``Manage
keys-values in file'' Technique does not support | as separator
(https://issues.rudder.io/issues/13562[#13562])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Thomas CAILHE
* Ilan COSTA
* vlycop Doo
* Florian Heigl
* Renaud Manus
* Janos Mattyasovszky
* Romain Quinaud
* David Svejda

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 5.0.2 (2018-11-06)

=== Changes

==== Generic methods

* Add condition_once and execute_once generic methods
(https://www.rudder-project.org/redmine/issues/13667[#13667])

==== Documentation

* Document zypper pattern usage in the ``Package state'' generic method
documentation
(https://www.rudder-project.org/redmine/issues/13725[#13725])

=== Bug fixes

==== Web - UI & UX

* Fixed: We have no way to know that a Technique is disabled when
editing a Directive
(https://www.rudder-project.org/redmine/issues/12829[#12829])
* Fixed: Broken display of popup to delete node property in Rudder 5.0.1
(https://www.rudder-project.org/redmine/issues/13694[#13694])

==== Generic methods

* Fixed: Generic method ``Sharedfile to node'' always return repaired
status (https://www.rudder-project.org/redmine/issues/13753[#13753])
* Fixed: Unit tests for generic method ``File from a Jinja2 template''
fail on Ubuntu12 on Rudder 4.1
(https://www.rudder-project.org/redmine/issues/13747[#13747])
* Fixed: Time lib may not work when the first non-loopback interface has
no ip adress
(https://www.rudder-project.org/redmine/issues/13744[#13744])
* Fixed: Remove comment about classes_generic_two being deprecated
(https://www.rudder-project.org/redmine/issues/13286[#13286])
* Fixed: Style test nbsp_is_not_allowed.sh always fails, missing 4.1
version of 13637
(https://www.rudder-project.org/redmine/issues/13722[#13722])
* Fixed: Missing report when using default value in Generic method
parameters (https://www.rudder-project.org/redmine/issues/13704[#13704])
* Fixed: Add more tests for the schedule lib in ncf
(https://www.rudder-project.org/redmine/issues/13668[#13668])
* Fixed: Zypper patterns tests should not be executed on non sles os
(https://www.rudder-project.org/redmine/issues/13638[#13638])

==== Web - Nodes & inventories

* Fixed: Group of group is empty if we use the AND combinator
(https://www.rudder-project.org/redmine/issues/13424[#13424])

==== Plugins integration

* Fixed: Authentication providers are not loaded before authentication
is initialized
(https://www.rudder-project.org/redmine/issues/13695[#13695])

==== Generic methods - File Management

* Fixed: Change the detection of curl path in ncf to use rudder_curl if
available (https://www.rudder-project.org/redmine/issues/13745[#13745])
* Fixed: Missing report in ``Manage keys-values in file'' technique
(https://www.rudder-project.org/redmine/issues/13715[#13715])
* Fixed: Missing reporting in ``Permisisons recurse'' method
(https://www.rudder-project.org/redmine/issues/13683[#13683])
* Fixed: Generic Method ``File copy from remote source'' does not report
when copying a directory
(https://www.rudder-project.org/redmine/issues/13634[#13634])
* Fixed: Missing status when I use ``File copy from Rudder shared
folder'' Technique
(https://www.rudder-project.org/redmine/issues/13669[#13669])

==== Web - Config management

* Fixed: In directive, change input for parameter from technique editor
from text to textarea
(https://www.rudder-project.org/redmine/issues/12824[#12824])

==== Generic methods - Package Management

* Fixed: Missing report when using the ``Package state'' generic method
with default value for the ``state'' parameter
(https://www.rudder-project.org/redmine/issues/13703[#13703])

==== Agent

* Fixed: Redhat Openstack Nova compute QEMU virtual machines are seen as
physical (https://www.rudder-project.org/redmine/issues/10265[#10265])
* Fixed: Mustache templating in audit mode always considers destination
compliant once it exists
(https://www.rudder-project.org/redmine/issues/13664[#13664])

==== Packaging

* Fixed: rudder-cf-execd and rudder-cf-serverd are not enabled nor
running after a server install on debian 8
(https://www.rudder-project.org/redmine/issues/13774[#13774])
* Fixed: Rudder agent uninstall may fail to to systemd unit
(https://www.rudder-project.org/redmine/issues/13762[#13762])
* Fixed: can’t upgrade debian package if /bin/systemd exist but sysv is
used (https://www.rudder-project.org/redmine/issues/13174[#13174])
* Fixed: rudder.conf is not removed from /etc/ld.so.conf.d
(https://www.rudder-project.org/redmine/issues/12554[#12554])
* Fixed: Fusioninventory error about unitialized value $FQDN
(https://www.rudder-project.org/redmine/issues/13739[#13739])
* Fixed: Embedded openssl does not build on Ubuntu 15.10
(https://www.rudder-project.org/redmine/issues/13712[#13712])
* Fixed: ``type: systemctl : not found'' appears in rudder-agent
installation logs
(https://www.rudder-project.org/redmine/issues/13693[#13693])
* Fixed: Script rudder-support-info is too chatty when looking for time
(branch 5.0)
(https://www.rudder-project.org/redmine/issues/13670[#13670])
* Fixed: Rudder syslog port is reset after upgrade on Ubuntu (< 14)
Servers (https://www.rudder-project.org/redmine/issues/12714[#12714])

==== Generic methods - Service Management

* Fixed: Broken variable in ``Service restart'' method report
(https://www.rudder-project.org/redmine/issues/13713[#13713])

==== Documentation

* Fixed: Broken doc build
(https://www.rudder-project.org/redmine/issues/13734[#13734])

==== System techniques

* Fixed: Use embedded curl when available
(https://www.rudder-project.org/redmine/issues/13687[#13687])

==== Performance and scalability

* Fixed: LDAP IO error on generation with a lot of nodes
(https://www.rudder-project.org/redmine/issues/13256[#13256])

==== Techniques

* Fixed: Sharing files with ``root'' does not work
(https://www.rudder-project.org/redmine/issues/10605[#10605])
* Fixed: Add option for Zypper Patterns in Technique ``Packages''
(https://www.rudder-project.org/redmine/issues/13721[#13721])
* Fixed: Add a bigger warning about full path in ``Download a file''
technique (https://www.rudder-project.org/redmine/issues/13647[#13647])
* Fixed: Add a bigger warning about full path in ``Download a file''
technique (https://www.rudder-project.org/redmine/issues/13646[#13646])
* Fixed: Fix some typo in ``rudder server directive upgrade'' help
output (https://www.rudder-project.org/redmine/issues/13765[#13765])
* Fixed: ``directive-upgrade'' rudder command does not work
(https://www.rudder-project.org/redmine/issues/13681[#13681])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* tim c
* Matthew Frost
* Ilan COSTA
* Jérémy HOCDÉ
* Janos Mattyasovszky
* Thomas CAILHE

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 5.0.1 (2018-10-19)

=== Changes

==== Packaging

* Embed dependencies on ubuntu 15
(https://www.rudder-project.org/redmine/issues/13677[#13677])

==== Generic methods

* Add a flag library
(https://www.rudder-project.org/redmine/issues/13622[#13622])
* Add a flag library
(https://www.rudder-project.org/redmine/issues/13622[#13622])

==== Generic methods - Package Management

* Add a package provider for zypper patterns
(https://www.rudder-project.org/redmine/issues/12164[#12164])

=== Bug fixes

==== Generic methods

* Fixed: Allow to report on same reporting parameters
(https://www.rudder-project.org/redmine/issues/13632[#13632])
* Fixed: style test nbsp_is_not_allowed.sh always fails
(https://www.rudder-project.org/redmine/issues/13637[#13637])
* Fixed: rudder agent log files content in user facility
(https://www.rudder-project.org/redmine/issues/13175[#13175])
* Fixed: 4.3+ version of 12164
(https://www.rudder-project.org/redmine/issues/13621[#13621])
* Fixed: still some typos in package tests
(https://www.rudder-project.org/redmine/issues/13591[#13591])
* Fixed: some ncf test are failing on SLES because they are trying to
deal with packages that are not available
(https://www.rudder-project.org/redmine/issues/13573[#13573])

==== Web - Nodes & inventories

* Fixed: Node group with `OR' multi criteria fails
(https://www.rudder-project.org/redmine/issues/13649[#13649])

==== Web - Config management

* Fixed: Change request must not be saved when no validation is needed
(https://www.rudder-project.org/redmine/issues/13609[#13609])

==== Documentation

* Fixed: rudder-doc embedeed doesn’t work anymore
(https://www.rudder-project.org/redmine/issues/13659[#13659])
* Fixed: Document Amazon Linux compatibility
(https://www.rudder-project.org/redmine/issues/13624[#13624])
* Fixed: Add sles 15 in 5.0 supported OS
(https://www.rudder-project.org/redmine/issues/13533[#13533])
* Fixed: Bad explanation for generic variable overide priority cause
people making the opposite of what is needed
(https://www.rudder-project.org/redmine/issues/13615[#13615])

==== Technique editor - UI/UX

* Fixed: Rename ``bundle name'' in the technique details
(https://www.rudder-project.org/redmine/issues/12847[#12847])

==== Agent

* Fixed: rudder server command states that ``Warning: Long arguments are
not supported, you probably tried to use one!'' - but it does support it
(https://www.rudder-project.org/redmine/issues/13505[#13505])

==== Packaging

* Fixed: Ubuntu 13.04 package tries to use systemd
(https://www.rudder-project.org/redmine/issues/13676[#13676])
* Fixed: Debian package cannot build in 4.1 because of docs.rudder.io
(https://www.rudder-project.org/redmine/issues/13594[#13594])
* Fixed: cebtos7 install_package_existant should be skipped
(https://www.rudder-project.org/redmine/issues/13596[#13596])

==== Security

* Fixed: StackOverflowError during policy generation in JavascriptEngine
- debian 9.5 with jdk 1.8.0_181
(https://www.rudder-project.org/redmine/issues/13014[#13014])
* Fixed: In Rudder 5.0, user password encoding is broken for some
passwords. (https://www.rudder-project.org/redmine/issues/13643[#13643])
* Fixed: Api User Account doesn’t have User role
(https://www.rudder-project.org/redmine/issues/13629[#13629])
* Fixed: file enforce content log file content which can have private
info (https://www.rudder-project.org/redmine/issues/13608[#13608])

==== Performance and scalability

* Fixed: Hikari pool autocomit configuration is incorrect, which can
impact performance
(https://www.rudder-project.org/redmine/issues/13582[#13582])
* Fixed: Policy generation fails definitively when postgresql is shut
down during policy generation
(https://www.rudder-project.org/redmine/issues/13517[#13517])

==== Techniques

* Fixed: SudoParameter technique version 3.2 returns a report that is
not parsable by the CLI
(https://www.rudder-project.org/redmine/issues/13350[#13350])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Jeremy CHAMPEL
* tim c
* Marco Kirchhoff

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 5.0.0 (2018-09-27)

=== Changes

==== Packaging

* Require Postgresql 9.2 for rudder server
(https://www.rudder-project.org/redmine/issues/13545[#13545])
* rename ``support info'' script to ``debug info'' script and change
store debug info in a standard path
(https://www.rudder-project.org/redmine/issues/13443[#13443])

==== Documentation

* Finish initial version of get-started guide
(https://issues.rudder.io/issues/13177[#13177,
https://issues.rudder.io/issues/13448[#13448])
* Rudder by example cleanup
(https://www.rudder-project.org/redmine/issues/13452[#13452])
* Add a rudder-by-example to replace line in a file
(https://www.rudder-project.org/redmine/issues/13404[#13404])

=== Bug fixes

==== Web - UI & UX

* Fixed: Blue text color in node details tabs
(https://www.rudder-project.org/redmine/issues/13168[#13168])
* Fixed: fields are not correctly aligned in group page
(https://www.rudder-project.org/redmine/issues/13417[#13417])
* Fixed: Dual scrolling bars on the right of group details in Rudder 5
(https://www.rudder-project.org/redmine/issues/13428[#13428])
* Fixed: Tooltip on the source of property is not dislpayed in Rudder
5.0 (https://www.rudder-project.org/redmine/issues/13456[#13456])
* Fixed: JS error when loading Rules pages
(https://www.rudder-project.org/redmine/issues/13469[#13469])
* Fixed: In Rudder 5.0, Password fields in directive is empty
(https://www.rudder-project.org/redmine/issues/13446[#13446])
* Fixed: Rudder web login page shows 5 instead of 5.0 in the right
bottom corner
(https://www.rudder-project.org/redmine/issues/13472[#13472])

==== Generic methods

* Fixed: Some old tests are failing on centos
(https://www.rudder-project.org/redmine/issues/13535[#13535])
* Fixed: there is still a trailing new line in the jinja result test
file (https://www.rudder-project.org/redmine/issues/13529[#13529])
* Fixed: variable_string and variable_string_default GM are failing in
rudder 5.0 (https://www.rudder-project.org/redmine/issues/13523[#13523])
* Fixed: Some tests are failing on ubuntu distros
(https://www.rudder-project.org/redmine/issues/13514[#13514])
* Fixed: add a method to set reportiing_context from within a technique
(https://www.rudder-project.org/redmine/issues/13351[#13351])

==== Generic methods - File Management

* Fixed: Missing report on Permissions (non recursive)
(https://www.rudder-project.org/redmine/issues/13536[#13536])

==== Documentation

* Fixed: Update download link in documentation
(https://www.rudder-project.org/redmine/issues/13534[#13534])
* Fixed: Fix appearance of titles
(https://www.rudder-project.org/redmine/issues/13502[#13502])

==== Packaging

* Fixed: rudder-jetty cannot extract java version on sles15
(https://www.rudder-project.org/redmine/issues/13552[#13552])
* Fixed: rudder-agent service is not removed when removing rudder-agent
(https://www.rudder-project.org/redmine/issues/13549[#13549])
* Fixed: add insserv-compat dependency on SLES15 packages
(https://www.rudder-project.org/redmine/issues/13550[#13550])
* Fixed: Use openjdk 10 on sles 15
(https://www.rudder-project.org/redmine/issues/13543[#13543])
* Fixed: Use new man page URL after doc URL redirect
(https://www.rudder-project.org/redmine/issues/13537[#13537])
* Fixed: Error at install of Rudder Server Root 5.0 on Sles 12
(https://www.rudder-project.org/redmine/issues/13527[#13527])
* Fixed: rudder-agent 4.1 install hangs on Debian 7
(https://www.rudder-project.org/redmine/issues/13525[#13525])
* Fixed: Doc download in webapp package does not work anymore
(https://www.rudder-project.org/redmine/issues/13499[#13499])
* Fixed: rudder server upgrade-techniques –autoupdate-technique-library
fails when run during Rudder upgrade
(https://www.rudder-project.org/redmine/issues/13458[#13458])

==== API

* Fixed: Harmonize URLs of system API
(https://www.rudder-project.org/redmine/issues/13471[#13471])

==== Techniques

* Fixed: deprecate old version of techniques for Rudder 5.0
(https://www.rudder-project.org/redmine/issues/13487[#13487])
* Fixed: Package management technique fails to check if a package is
absent in the ``latest'' version
(https://www.rudder-project.org/redmine/issues/12939[#12939])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 5.0.0.rc1 (2018-09-12)

=== Changes

==== Architecture - Internal libs

* We need to be able to decide what workflow to use based on the change
request (https://www.rudder-project.org/redmine/issues/13396[#13396])

=== Bug fixes

==== API

* Fixed: POST/PUT/DELETE API requests gives 403
(https://www.rudder-project.org/redmine/issues/13426[#13426])
* Fixed: Rudder system api token only have RO access
(https://www.rudder-project.org/redmine/issues/13416[#13416])

==== Generic methods

* Fixed: " error: List or container parameter `args' not found while
constructing scope `log_rudder' - use @(scope.variable) in calling
reference" when running Rudder 4.3
(https://www.rudder-project.org/redmine/issues/13430[#13430])

==== Performance and scalability

* Fixed: On error on nodecompliance SQL, logs are huge
(https://www.rudder-project.org/redmine/issues/13427[#13427])

==== Architecture - Refactoring

* Fixed: Git merge issue between Rudder 4.3 and Rudder 5.0
(https://www.rudder-project.org/redmine/issues/13432[#13432])

==== Agent

* Fixed: remove unessecary patch that remove truncation of line in
inventory (https://www.rudder-project.org/redmine/issues/13403[#13403])
* Fixed: Upgrade perl to latest minor version in 5.0 for fusion
inventory (https://www.rudder-project.org/redmine/issues/13402[#13402])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 5.0.0.beta2 (2018-09-06)

=== Changes

==== Packaging

* Remove rudder agent thin in 5.0
(https://www.rudder-project.org/redmine/issues/13377[#13377])
* Upgrade python related dependencies
(https://www.rudder-project.org/redmine/issues/13371[#13371])
* Remove apache 2.2 support
(https://www.rudder-project.org/redmine/issues/13325[#13325])
* keep only systemd on server packages
(https://www.rudder-project.org/redmine/issues/13320[#13320])
* Upgrade jetty to 9.4.11
(https://www.rudder-project.org/redmine/issues/13323[#13323])
* Remove support for old system on rudder server builds
(https://www.rudder-project.org/redmine/issues/13315[#13315])
* Update agent dependencies
(https://www.rudder-project.org/redmine/issues/13314[#13314])
* Upgrade openssl
(https://www.rudder-project.org/redmine/issues/13316[#13316])
* Upgrade python related dependencies
(https://www.rudder-project.org/redmine/issues/13373[#13373])

==== Web - UI & UX

* Update main menu: plugin at top level, techique editor in
configuration policy
(https://www.rudder-project.org/redmine/issues/13067[#13067])

==== Documentation

* Use repository.rudder.io in 5.0 doc
(https://www.rudder-project.org/redmine/issues/13382[#13382])

==== Plugins integration

* Make user/role management a plugin
(https://www.rudder-project.org/redmine/issues/13030[#13030])

==== Architecture - Dependencies

* Update all rudder dependencies
(https://www.rudder-project.org/redmine/issues/13313[#13313])

=== Bug fixes

==== Web - UI & UX

* Fixed: Fonts changed in Rudder 5.0
(https://www.rudder-project.org/redmine/issues/13364[#13364])
* Fixed: Save button in group page is not readable in Rudder 5.0
(https://www.rudder-project.org/redmine/issues/13368[#13368])
* Fixed: In directives pages, Text selector and input field are not
correctly allligned in Rudder 5.0
(https://www.rudder-project.org/redmine/issues/13372[#13372])
* Fixed: Clicking on Status/Details leads to a disabled screen in Rudder
5.0 (https://www.rudder-project.org/redmine/issues/13362[#13362])

==== Generic methods

* Fixed: user_primary_group tests are failing on suse
(https://www.rudder-project.org/redmine/issues/13282[#13282])
* Fixed: Some ncf tests are too old and fails on many distributions
(https://www.rudder-project.org/redmine/issues/13249[#13249])

==== Architecture - Internal libs

* Fixed: Spring Security error - leading to random unlogging in Rudder 5
(https://www.rudder-project.org/redmine/issues/13365[#13365])

==== Technique editor - API

* Fixed: Error message is not correctly treated when an exception occurs
in when authenticating to Rudder authentication API
(https://www.rudder-project.org/redmine/issues/13219[#13219])

==== Packaging

* Fixed: libxml 2.9.8 doesn’t compile on aix
(https://www.rudder-project.org/redmine/issues/13363[#13363])
* Fixed: libxml fails to build with old compiler
(https://www.rudder-project.org/redmine/issues/13337[#13337])
* Fixed: Use correct version when building Slackware packages
(https://www.rudder-project.org/redmine/issues/13329[#13329])
* Fixed: Use https everywhere to download server sources
(https://www.rudder-project.org/redmine/issues/13324[#13324])
* Fixed: parallel build on rpmbuild hides build error
(https://www.rudder-project.org/redmine/issues/13300[#13300])

==== Generic methods - Service Management

* Fixed: Service test do not use any service to test on suse
(https://www.rudder-project.org/redmine/issues/13278[#13278])
* Fixed: 4.3+ version of 13278
(https://www.rudder-project.org/redmine/issues/13279[#13279])
* Fixed: services GM are not working anymore due to typo
(https://www.rudder-project.org/redmine/issues/13258[#13258])

==== Security

* Fixed: ``//'' in rudder-web/secure/api//settings/global_policy_mode
cause browser/spring error
(https://www.rudder-project.org/redmine/issues/13356[#13356])
* Fixed: Bad mime type for our js files: application/js
(https://www.rudder-project.org/redmine/issues/13334[#13334])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 5.0.0.beta1 (2018-08-29)

=== Changes

==== API

* Create system Rest API to replace V1 API
(https://www.rudder-project.org/redmine/issues/12516[#12516])

==== Generic methods

* Add a generic method to test variable existence
(https://www.rudder-project.org/redmine/issues/12986[#12986])

==== Plugins integration

* Remove the need for Spring in plugin
(https://www.rudder-project.org/redmine/issues/13036[#13036])

==== Documentation

* Add a search field
(https://issues.rudder.io/issues/13093[#13093])
* Change version of documentation on rudder-doc
(https://www.rudder-project.org/redmine/issues/13019[#13019])
* Build a centralized place for doc: docs.rudder.io
(https://www.rudder-project.org/redmine/issues/12907[#12907])
* Use a rudder-specific theme
(https://www.rudder-project.org/redmine/issues/12875[#12875])
* Add DSC content to Rudder by example
(https://www.rudder-project.org/redmine/issues/12584[#12584])
* Add a ``Rudder by example'' guide to the documentation
(https://www.rudder-project.org/redmine/issues/12383[#12383])

==== Technique editor - API

* Remove expected reports.csv logic
(https://www.rudder-project.org/redmine/issues/11915[#11915])

==== Agent

* Use CFEngine 3.12 in Rudder agent
(https://www.rudder-project.org/redmine/issues/12856[#12856])
* Add a package techniques migration script
(https://www.rudder-project.org/redmine/issues/12710[#12710])
* Update technique migration technique with 12614 review
(https://www.rudder-project.org/redmine/issues/12676[#12676])

==== Packaging

* Add sles 15 support to rudder-packages
(https://www.rudder-project.org/redmine/issues/13295[#13295])
* Disable HTTPs for sources download on old OSes
(https://www.rudder-project.org/redmine/issues/13197[#13197])
* Download sources from repository.rudder.io instead of
www.normation.com
(https://www.rudder-project.org/redmine/issues/13172[#13172])
* Download man on docs.rudder.io
(https://www.rudder-project.org/redmine/issues/13170[#13170])

==== Generic methods - Service Management

* Remove unused _service_check_running_smf and
_service_check_running_src in branch 5.0
(https://www.rudder-project.org/redmine/issues/13245[#13245])

==== System integration

* Bundle support info script into Rudder
(https://www.rudder-project.org/redmine/issues/13213[#13213])

==== Architecture - Refactoring

* Make scale-out (relay) server a plugin
(https://www.rudder-project.org/redmine/issues/12885[#12885])
* Make third-party authentication a plugin
(https://www.rudder-project.org/redmine/issues/12906[#12906])
* Make validation workflow a plugin
(https://www.rudder-project.org/redmine/issues/12904[#12904])

==== Generic methods - Package Management

* Use the new class_prefix for package methods
(https://www.rudder-project.org/redmine/issues/12427[#12427])

=== Bug fixes

==== Web - UI & UX

* Fixed: Remove the ``tw-bs'' css hack
(https://www.rudder-project.org/redmine/issues/13022[#13022])

==== Generic methods

* Fixed: Incomplete management of disabled/reenable reporting
(https://www.rudder-project.org/redmine/issues/13209[#13209])
* Fixed: file_check_special tests are failing on debian
(https://www.rudder-project.org/redmine/issues/13243[#13243])
* Fixed: Huge agent logs when we define an new class_prefix that is
longer than 1024 chars
(https://www.rudder-project.org/redmine/issues/13155[#13155])

==== Plugins integration

* Fixed: Missing real-time check of license capabilities for api and
others plugins
(https://www.rudder-project.org/redmine/issues/13073[#13073])

==== Generic methods - File Management

* Fixed: Error when using 2 or more File from a jinja2 template
(https://www.rudder-project.org/redmine/issues/13183[#13183])

==== Documentation

* Fixed: Git repository not initialised in plugin directory
(https://issues.rudder.io/issues/13306[13306])
* Fixed: Wrong version displayed on the login page for plugin branding
(https://www.rudder-project.org/redmine/issues/13274[#13274])
* Fixed: Update screenshot for Rudder Branding
(https://www.rudder-project.org/redmine/issues/13270[#13270])
* Fixed: Make plugin doc build with 5.0 doc
(https://issues.rudder.io/issues/13137[13137])
* Fixed: Typos in rudder-by-example
(https://www.rudder-project.org/redmine/issues/12611[#12611])
* Fixed: Add a favicon for Rudder by example
(https://www.rudder-project.org/redmine/issues/12490[#12490])
* Fixed: Build rudder man page using asciidoctor
(https://www.rudder-project.org/redmine/issues/12977[#12977])

==== Miscellaneous

* Fixed: Removing workflow comet leads to missing user information and
session is destroyed
(https://www.rudder-project.org/redmine/issues/13026[#13026])

==== Agent

* Fixed: Broken agent build on linux platforms
(https://www.rudder-project.org/redmine/issues/13311[#13311])
* Fixed: rudder technique-migrate is not documented nor properly named
(https://www.rudder-project.org/redmine/issues/13146[#13146])

==== Packaging

* Fixed: Purge of rudder-webapp should not fail
(https://www.rudder-project.org/redmine/issues/13210[#13210])
* Fixed: Fix bdb download link from repository.rudder.io
(https://www.rudder-project.org/redmine/issues/13198[#13198])
* Fixed: slackware should not build its package into /tmp
(https://www.rudder-project.org/redmine/issues/13194[#13194])
* Fixed: Download rudder.8 for new man page url
(https://www.rudder-project.org/redmine/issues/12982[#12982])
* Fixed: Add back missing migration script in 5.0
(https://www.rudder-project.org/redmine/issues/13084[#13084])
* Fixed: Makefile fails if a symbolink link /usr/bin/ncf already exists
(https://www.rudder-project.org/redmine/issues/13277[#13277])

==== Generic methods - Service Management

* Fixed: service_started_start.cf test fails on redhat
(https://www.rudder-project.org/redmine/issues/13257[#13257])
* Fixed: service_started_path.cf does not generate classes anymore since
13220 (https://www.rudder-project.org/redmine/issues/13254[#13254])

==== API

* Fixed: Compilation warnings in master
(https://www.rudder-project.org/redmine/issues/13028[#13028])

==== Generic methods - Package Management

* Fixed: old packages generic methods are failing on old debian
(https://www.rudder-project.org/redmine/issues/13305[#13305])

==== Techniques

* Fixed: Package repository keys Technique in Audit Mode : Missing
Reports (https://www.rudder-project.org/redmine/issues/13065[#13065])
* Fixed: Package repository keys Technique in Audit Mode : Missing
Reports (https://www.rudder-project.org/redmine/issues/13065[#13065])
* Fixed: Rudder SNMP technique has a component failing on first run
(https://www.rudder-project.org/redmine/issues/13159[#13159])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Mikaël Mantel
* Pierre HAY
* Guillaume Terrier

This software is in beta status and contains several new features but we
have tested it and believe it to be free of any critical bugs. The use
on production systems is not encouraged at this time and is at your own
risk. However, we do encourage testing, and welcome all and any
feedback!
