= Change logs for Rudder 5.0

Rudder 5.0 is currently a maintained version of Rudder.

This page provides a summary of changes for each version. Previous beta
and rc versions are listed below for convenience.

*Warning*: The following features are now provided as plugins and no
more available as part of default Rudder installation starting from 5.0:

* LDAP-based authentication
* Relay servers
* Changes validation workflow (change requests)

If you were using them, upgrade will disable them and you will have to
install the plugin. Read the http://rudder.io/plugins[plugins page on
our website] for more information.

The initial RUDDER model consisting of a single software block which
includes all features, thus imposing a greater and greater complexity on
all of our users, has reached its limits. We have now reached a
sufficient understanding of the domain, its challenges, and the way
RUDDER is used, to make us realize that this all-in-one model is not, or
is no longer, the best suited.

_New plugin ecosystem_: Version 5.0 introduces a plugin ecosystem that
gathers RUDDER’s most specific features. This way, only essential
features have to be installed by default and advanced features can be
used on a case by case basis. So what is essential and what is not? The
basic rule is that the essential experience must contain the features
used by 80% or more of users, whatever the scale of use. In other words,
we keep as core features everything that delivers on RUDDER’s initial
promise: enabling users to continuously audit and enforce configurations
with an easy to use webapp providing visual reporting. The remaining 20%
solve needs that are no less important, only less common (PDF compliance
reports, UI branding, scale-out relay servers, validation workflow…). To
know everything about the impact of this evolution, you can read the
detailed dedicated article:

https://www.rudder.io/en/blog/2018/09/26/rudder-5-new-modular-version-thanks-ecosystem-plugins/[RUDDER 5 – a new modular version, thanks to an ecosystem of plugins]

_Integration_: We provide integration with third party tools as plugins,
making RUDDER more integrated with tools like Ansible, Centreon, Zabbix,
GLPI or Vault. Except for a few (ie. managing AIX and Windows host),
plugins are open source and source code is available in the 
https://github.com/normation/rudder-plugins/[rudder-plugins repository].

_New documentation_: Welcome to our brand new documentation website
https://docs.rudder.io[docs.rudder.io]! Beyond its fresh look (both on
the online website and in the embedded version), this new documentation
includes updated content and new resources, like a ``getting started''
guide and examples of use-cases.

_System API_: We built a new REST API that allows to manage some
advanced settings and perform maintenance operations in RUDDER, like
triggering policy generations, updating dynamic groups and managing
report archives. This was previously available in the now deprecated
https://docs.rudder.io/history/4.3/rest-api.html#rest-api[V1 API] which
will be removed in the next major version (5.1).

_Debugging information script_: We created a script to gather basic
information about a RUDDER setup when you want to debug or understand
RUDDER’s behavior. This script fetches log files and executes various
commands, either to get information from databases or directly from the
system (package versions, etc)

_Automatic Technique upgrade_: Techniques provided with RUDDER can now
be automatically upgraded when you update RUDDER. This process used to
be manual because you might have modified the base Technique Library and
we thought you may want to have more control about the content of your
Technique Library. But it appears that this process was forgotten by a
majority of our users and so many bug fixes and new versions were not
available after an upgrade. By default this feature is enabled on new
RUDDER 5.0 installations but is disabled on upgrades from older
versions, to prevent any accidental damage.

_Support policy_: Our general policy is to maintain major releases until
3 months after the next major version is released to give some time for
upgrading. The ESR tag was previously given to major releases that were
maintained 6 months after the next ESR version was announced. Rudder 4.1
is the last ESR release. For a slower major upgrade pace, Rudder
subscription provides long-term maintenance up to 24 months after
release (depending on the subscription level) for Rudder versions. Read
the 
https://docs.rudder.io/reference/5.0/installation/versions.html[dedicated page]
for more information.

_Packaging_: _Relay server support is now part of an open-source
plugin_, pre-compiled packages are available as part of the Rudder
subscription.

The agent package is now more modular: instead of embedding all
dependencies, we are using system libraries on maintained operating
systems, to allow for a better system integration. As a consequence, the
experimental rudder-agent-thin (which had this exact goal) package is
not built anymore.

_New repositories_: https://repository.rudder.io/ We are using new
repositories for versions starting from 5.0. We also provide all
previous releases in these new repos. We improved our build system,
files hierarchy, and added more gpg signatures on distributed files
(Rudder sources, etc.)

*Installing, upgrading and testing*

* Install docs:
** https://docs.rudder.io/reference/5.0/installation/server/debian.html[Debian/Ubuntu]
** https://docs.rudder.io/reference/5.0/installation/server/rhel.html[RHEL/centOS]
** https://docs.rudder.io/reference/5.0/installation/server/sles.html[SLES]
* https://docs.rudder.io/reference/5.0/installation/upgrade.html[Upgrade docs]
* https://docs.rudder.io/reference/5.0/installation/versions.html#_versions[Download links]

We also recommend using the
https://github.com/Normation/rudder-vagrant[Rudder Vagrant] config if
you want a quick and easy way to get an installation for testing.

*Supported operating systems*

This version provides packages for these operating systems:

* Rudder server and Rudder relay: *Debian 8-9, RHEL/CentOS 7 (64 bits),
SLES 12-15, Ubuntu 16.04 LTS-18.04 LTS*
* Rudder agent: all of the above plus *RHEL/CentOS 6, Ubuntu 14.04 LTS*
* Rudder agent (binary packages available with a https://www.rudder.io/en/pricing/subscription/[subscription]) : *Debian 5-7, RHEL/CentOS 3-5,
SLES 10-11, Ubuntu 10.04 LTS-12.04 LTS-13.04-15.10, Windows Server 2008R2-2016, AIX
5-6-7, Slackware 14*

Read more about supported operating systems 
https://docs.rudder.io/reference/5.0/installation/operating_systems.html[in the documentation].

== Known issues in Rudder 5.0.0 to 5.0.2

=== Communication between agents built with 1.1.0 vs. 1.0.x openssl versions

We have found a communication problem between some versions of rudder
agent and server due to a bug in OpenSSL library.

The problem occurs when a client (resp. server) using OpenSSL 1.0 tries
to communicate with a server (resp. client) using OpenSSL 1.1.0. It is
https://github.com/openssl/openssl/issues/7134[corrected] in newly
released OpenSSL 1.1.1. The Rudder corresponding bug is
https://www.rudder-project.org/redmine/issues/13690[traced on Rudder bug
tracker].

Rudder versions from 5.0.0 to 5.0.2 on Ubuntu 18.04, Debian 9, and SLES
15 use OpenSSL 1.1.0. Any previous version of Rudder on these OS or any
version of Rudder in any other OS use OpenSSL 1.0. If you have in your
environment a Rudder server in one group and agents in the other group,
these agents won’t be able to communicate with the server any more.

The most likely case where it could happen is if you upgrade a Rudder
server on Ubuntu 18.04 or on Debian 9 from version 4.3 to 5.0. In such a
case, a partial workaround is to also upgrade Debian 9/Ubuntu 18.04
agents to Rudder 5.0, but agents in other OS will still be impacted by
the communication problem. A safer and simpler solution, if available,
is to delay such on upgrade until a patch is available.

We are working on the patch to replace the buggy OpenSSL 1.1.0 and we
will release a new version of Rudder 5.0 with it as soon as possible.

We are sorry for any inconvenience resulting from this problem. If you
need more information or help, please don’t hesitate to contact us by
email or other means of communication like
https://gitter.im/normation/rudder[gitter] or irc (#rudder on freenode).

== Rudder 5.0.20 (2020-10-28)

=== Changes

=== Bug fixes

==== Documentation

* Fixed: Advise to not desinstall rudder server if possible
    (https://issues.rudder.io/issues/17803[#17803])

==== Web - Config management

* Fixed: Missing system variable "POLICY_SERVER_KEY"
    (https://issues.rudder.io/issues/18289[#18289])

==== Security

* Fixed: Agents fail to check their policy server's identity
    (https://issues.rudder.io/issues/18286[#18286])

==== Techniques

* Fixed: apt configuration issue - add apost-check to validate generated line
    (https://issues.rudder.io/issues/13741[#13741])

==== Technique editor - API

* Fixed: Method with empty curly braces are not recognized as valid
    (https://issues.rudder.io/issues/18268[#18268])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.19 (2020-09-16)

=== Changes

=== Bug fixes

==== Web - Nodes & inventories

* Fixed: Group query with OR composition and searching for Node properties return all nodes in place of none
    (https://issues.rudder.io/issues/18172[#18172])
* Fixed: Group query with OR composition and searching for Node properties return less results than expected
    (https://issues.rudder.io/issues/18133[#18133])

==== API

* Fixed: "id" setting is silently ignored for new group created through the REST API.
    (https://issues.rudder.io/issues/10216[#10216])
* Fixed: Rudder directive API seem to take key-value order into account in json POST request 
    (https://issues.rudder.io/issues/14934[#14934])

==== Web - Config management

* Fixed: SUSE is spelled SuSE in the webapp
    (https://issues.rudder.io/issues/16319[#16319])

==== Miscellaneous

* Fixed: Error displayed when switching from full access to read only
    (https://issues.rudder.io/issues/18052[#18052])

==== Techniques

* Fixed: No flush key report on sshKeyDistribution when there is not yet an ssh key configured
    (https://issues.rudder.io/issues/16516[#16516])

==== Generic methods

* Fixed: File from local source with check: diff error
    (https://issues.rudder.io/issues/17303[#17303])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Dmitry Svyatogorov
* Alexander Brunhirl

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.18 (2020-07-24)

=== Changes

==== Documentation

* Missing uninstall doc for agent
    (https://issues.rudder.io/issues/17790[#17790])

=== Bug fixes

==== Web - Nodes & inventories

* Fixed: In SLES 15, SP is view as part of rudder agent version
    (https://issues.rudder.io/issues/17736[#17736])
* Fixed: Purge of unreferenced software may still fail on very large system
    (https://issues.rudder.io/issues/17176[#17176])
* Fixed: When a node is removed from a dynamic group, it log "adding nothing, removing nothing"
    (https://issues.rudder.io/issues/17220[#17220])

==== Packaging

* Fixed: Rudder-agent needs libxml-treepp-perl dependency to work on minimal Debian
    (https://issues.rudder.io/issues/17699[#17699])

==== Agent

* Fixed: Update embedded openssl version to 1.1.1g
    (https://issues.rudder.io/issues/17178[#17178])

==== Documentation

* Fixed: remove pg_repack from documentation
    (https://issues.rudder.io/issues/17839[#17839])
* Fixed: Documentation should state that SSD is recommended for more than 50 nodes
    (https://issues.rudder.io/issues/17761[#17761])
* Fixed: Missing documentation for overriding jetty system properties in start.ini
    (https://issues.rudder.io/issues/17719[#17719])
* Fixed: Doc about missing uuid.hive at upgrade was not upmerged
    (https://issues.rudder.io/issues/17299[#17299])

==== API

* Fixed: 'policyMode' vs. 'policy' in node settings API
    (https://issues.rudder.io/issues/17817[#17817])
* Fixed: API documentation on Rules is missing explanation on how to update rule category
    (https://issues.rudder.io/issues/17409[#17409])
* Fixed: Bad JSON answer for api PUT /rules
    (https://issues.rudder.io/issues/17388[#17388])

==== Performance and scalability

* Fixed: table nodes contains on entry per node per generation, which is too much
    (https://issues.rudder.io/issues/17778[#17778])
* Fixed: table nodes contains on entry per node per generation, which is too much
    (https://issues.rudder.io/issues/17778[#17778])
* Fixed: when running cf-promises, list-compatible-inputs is ran 8 times
    (https://issues.rudder.io/issues/17481[#17481])

==== Web - Config management

* Fixed: Duplicate category name error when saving a new user technique
    (https://issues.rudder.io/issues/17774[#17774])
* Fixed: Auto-archive gitRepo.git failure warning is not actionnable, should be info or debug
    (https://issues.rudder.io/issues/17777[#17777])
* Fixed: Ignored node lead to an error log during generation
    (https://issues.rudder.io/issues/17441[#17441])
* Fixed: TechniqueVersion ordering algorithm is incorrect
    (https://issues.rudder.io/issues/17157[#17157])

==== Web - UI & UX

* Fixed: When adding tags, if anything is wrong in the directive form, all unsaved tags are wiped out
    (https://issues.rudder.io/issues/15557[#15557])

==== Security

* Fixed: exception in ldap search are not correctly caught
    (https://issues.rudder.io/issues/17267[#17267])

==== System integration

* Fixed: When rudder agent health stops all service because there aren't any space left, if should state it in the log (and which fs)
    (https://issues.rudder.io/issues/17472[#17472])

==== Generic methods

* Fixed: Syntax error in shared_file_to_node
    (https://issues.rudder.io/issues/17667[#17667])
* Fixed: no reports from sharedfile to node if file is already there
    (https://issues.rudder.io/issues/17661[#17661])

==== Technique editor - UI/UX

* Fixed: Text &  Boxes jump when displaying missing inputs
    (https://issues.rudder.io/issues/16235[#16235])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.17 (2020-04-23)

=== Changes

==== Documentation

* Change path for plugin images
    (https://issues.rudder.io/issues/16990[#16990])
* Redirect video page from the doc to the youtube playlists
    (https://issues.rudder.io/issues/17002[#17002])
* Explains how to change requestHeaderSize in Rudder 5.0
    (https://issues.rudder.io/issues/16677[#16677])

==== Web - UI & UX

* Folded categories in the Directive tree should be kept between sessions
    (https://issues.rudder.io/issues/16258[#16258])

=== Bug fixes

==== Agent

* Fixed: Upgrade to CFEngine 3.12.4
    (https://issues.rudder.io/issues/16978[#16978])
* Fixed: Agent check splaytime is not actually random
    (https://issues.rudder.io/issues/17082[#17082])

==== Packaging

* Fixed: When installing rudder-server-root on RPM-based systems, it asks about running rudder-node-to-relay
    (https://issues.rudder.io/issues/14600[#14600])
* Fixed: Rudder agent 5.x package not compatible with Centos8
    (https://issues.rudder.io/issues/16521[#16521])

==== Web - Nodes & inventories

* Fixed: In SLES 15, SP is view as part of version
    (https://issues.rudder.io/issues/16803[#16803])

==== Plugins integration

* Fixed: Remove old rudder-plugin script
    (https://issues.rudder.io/issues/16755[#16755])

==== Documentation

* Fixed: Typo in Variable doc: hsotname
    (https://issues.rudder.io/issues/16918[#16918])
* Fixed: Document /var/rudder/policy-generation-info
    (https://issues.rudder.io/issues/16903[#16903])

==== Web - Maintenance

* Fixed: When deletion of reports fails, we don't get meaningful message, and it fails when ComplianceLevels are disabled
    (https://issues.rudder.io/issues/17129[#17129])
* Fixed: Purge of unreferenced software may fail on very large system
    (https://issues.rudder.io/issues/16636[#16636])

==== Web - UI & UX

* Fixed: Generation status color must not be grey
    (https://issues.rudder.io/issues/17104[#17104])
* Fixed: Users with readonly rights should be able to view the node properties and their value
    (https://issues.rudder.io/issues/16854[#16854])
* Fixed: Missing timezone in reports caption header
    (https://issues.rudder.io/issues/16777[#16777])

==== System integration

* Fixed: Test files are not correctly clean
    (https://issues.rudder.io/issues/17079[#17079])

==== Web - Config management

* Fixed: Agent 6.0 can't update policies from Rudder 5.0
    (https://issues.rudder.io/issues/17081[#17081])

==== Performance and scalability

* Fixed: Inneficient computation of RuleStatusReports and NodeStatusReports
    (https://issues.rudder.io/issues/16661[#16661])

==== API

* Fixed: Add openapi 11 version of the API doc
    (https://issues.rudder.io/issues/16852[#16852])

==== Techniques

* Fixed: duplicate RudderUniqueID on one entry on UserManagement v9
    (https://issues.rudder.io/issues/16881[#16881])
* Fixed: When using twice directive packageManagement 1.2, once to ensure presence of a package, and second one to upgrade the package, reporting and posthook is wrong on the second one
    (https://issues.rudder.io/issues/16849[#16849])

==== Generic methods - Package Management

* Fixed: Update package modules to 3.12.4
    (https://issues.rudder.io/issues/17111[#17111])
* Fixed: package_state_options doesn't properly defines outcome classes when called twice with same package name
    (https://issues.rudder.io/issues/16850[#16850])

==== Generic methods

* Fixed: Use a valid URL to test http methods
    (https://issues.rudder.io/issues/17098[#17098])
* Fixed: Broken tests for user group
    (https://issues.rudder.io/issues/17008[#17008])
* Fixed: Permissions dirs recursive doesn't allow to set only owner, or group, or mode
    (https://issues.rudder.io/issues/16917[#16917])
* Fixed: Generic method  sysctl_value
    (https://issues.rudder.io/issues/16882[#16882])

==== Generic methods - User Management

* Fixed: There is no method to handle secondary groups of a user in the technique editor
    (https://issues.rudder.io/issues/16325[#16325])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Romain Brucker

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.16 (2020-02-17)

=== Changes

==== Packaging

* Upgrade agent to CFEngine 3.12.3
    (https://issues.rudder.io/issues/16369[#16369])

==== Performance and scalability

* Backport test on Hooks to 5.0
    (https://issues.rudder.io/issues/16438[#16438])

=== Bug fixes

==== Packaging

* Fixed: During upgrade, jetty doesn't seems to always restart correctly 
    (https://issues.rudder.io/issues/12911[#12911])
* Fixed: rudder-init fails when there are only IPv6 addresses
    (https://issues.rudder.io/issues/16680[#16680])
* Fixed: Debian 10 doesn't know how to install java if it's not already installed
    (https://issues.rudder.io/issues/16366[#16366])
* Fixed: Use HTTPS repository URLs in maven configuration
    (https://issues.rudder.io/issues/16651[#16651])
* Fixed: Add Amazon Linux support to ncf and techniques
    (https://issues.rudder.io/issues/12990[#12990])

==== Documentation

* Fixed: Inventory workflow documentation outdated for Rudder 5.0
    (https://issues.rudder.io/issues/16679[#16679])
* Fixed: Update rudder-setup doc
    (https://issues.rudder.io/issues/16373[#16373])
* Fixed: Update release policy documentation
    (https://issues.rudder.io/issues/16358[#16358])

==== API

* Fixed: Add authorized network configuration in settings api
    (https://issues.rudder.io/issues/16667[#16667])
* Fixed: Technique editor fails with internal error
    (https://issues.rudder.io/issues/16701[#16701])

==== Performance and scalability

* Fixed: NullPointerException with hundreds of inventories at once
    (https://issues.rudder.io/issues/14991[#14991])
* Fixed: Unnecessary compliance computations when historization of Node Compliance is disabled
    (https://issues.rudder.io/issues/16643[#16643])
* Fixed: Unnecessary compliance computations when historization of Node Compliance is disabled
    (https://issues.rudder.io/issues/16643[#16643])
* Fixed: Unnecessary call to trim on empty string when creating executionBatch
    (https://issues.rudder.io/issues/16522[#16522])
* Fixed: we should not use .size to check if a collection is empty
    (https://issues.rudder.io/issues/16524[#16524])
* Fixed: JVM GC cannot clean objects in scope in a for { } yield {} even if they are not referenced anymore
    (https://issues.rudder.io/issues/16513[#16513])
* Fixed: StatusReportTest leads to inconsistent results
    (https://issues.rudder.io/issues/16496[#16496])
* Fixed: Computation of ComplianceLevel generates too many objects
    (https://issues.rudder.io/issues/16468[#16468])
* Fixed: A lot of data is computed and stored in Policy object, that is either never used, or used only once
    (https://issues.rudder.io/issues/16467[#16467])

==== Web - Config management

* Fixed: Archive of techniques miss some files needed for a the technique editor
    (https://issues.rudder.io/issues/16582[#16582])

==== Web - Nodes & inventories

* Fixed: Amazon Linux appears as "Other Linux 2" in nodes list
    (https://issues.rudder.io/issues/16486[#16486])

==== Web - UI & UX

* Fixed: Missing timezone in generation "started at" 
    (https://issues.rudder.io/issues/16392[#16392])
* Fixed: Scroll issue after policy rebuild
    (https://issues.rudder.io/issues/16434[#16434])
* Fixed: "Reload techniques" button has a slightly different color
    (https://issues.rudder.io/issues/16320[#16320])

==== Web - Compliance & node report

* Fixed: Not report compliance because of scala.UninitializedFieldError
    (https://issues.rudder.io/issues/16439[#16439])

==== Web - Technique editor

* Fixed: Technique edit authorizations don't allow technique editor use 
    (https://issues.rudder.io/issues/16386[#16386])

==== Techniques

* Fixed: Technique SNMP installation doesn't work on non-debian like system
    (https://issues.rudder.io/issues/16689[#16689])

==== Agent

* Fixed: rudder agent health does not work on agent bootstrap nor on server before first run
    (https://issues.rudder.io/issues/16588[#16588])
* Fixed: syntax error in rudder server-disable-policy-distribution
    (https://issues.rudder.io/issues/16444[#16444])

==== Generic methods

* Fixed: Make error in no-reporting mode info instead of warns
    (https://issues.rudder.io/issues/16608[#16608])
* Fixed: condition_from_commands is not running any command in audit mode
    (https://issues.rudder.io/issues/16359[#16359])

==== Generic methods - Package Management

* Fixed: Package modules shebangs do not work when python3 is not installed
    (https://issues.rudder.io/issues/16541[#16541])
* Fixed: yum package module is not compatible with systems having only python2
    (https://issues.rudder.io/issues/16534[#16534])

==== Technique editor - UI/UX

* Fixed: "Technique diverges" appears when it shouldn't
    (https://issues.rudder.io/issues/15558[#15558])

==== Technique editor - API

* Fixed: Wrong condition on component used when importing technique
    (https://issues.rudder.io/issues/16323[#16323])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Mike Kingsbury

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.15 (2019-12-05)

=== Changes

==== Documentation

* Remove multiserver install procedure
    (https://issues.rudder.io/issues/16209[#16209])
* Document inventory variables
    (https://issues.rudder.io/issues/15596[#15596])
* Improve generic method docs in the manual
    (https://issues.rudder.io/issues/16034[#16034])
* Update ncf README after merge into Rudder
    (https://issues.rudder.io/issues/16097[#16097])
* Fix link to external doc in technique editor
    (https://issues.rudder.io/issues/16098[#16098])

==== Web - UI & UX

* Make the "Add node property" form more visible
    (https://issues.rudder.io/issues/16194[#16194])

==== System techniques

* OpenSUSE should be detected as "suse" os family
    (https://issues.rudder.io/issues/16249[#16249])

=== Bug fixes

==== Agent

* Fixed: Recommend bash-completion package with rudder-agent
    (https://issues.rudder.io/issues/16239[#16239])
* Fixed: Running /opt/rudder/bin/rudder-debug-info outside of /opt/rudder/bin fails 
    (https://issues.rudder.io/issues/14830[#14830])
* Fixed: File content directive - Audit mode is not correctly supported
    (https://issues.rudder.io/issues/11086[#11086])
* Fixed: File content directive - Audit mode is not correctly supported
    (https://issues.rudder.io/issues/11086[#11086])
* Fixed: Typo in rudder agent health output
    (https://issues.rudder.io/issues/16229[#16229])
* Fixed: Command rudder agent start shoud list activated/deactivated services
    (https://issues.rudder.io/issues/16145[#16145])
* Fixed: "rudder server trigger-policy-generation/reload-groups" output a curl error if apache is stopped
    (https://issues.rudder.io/issues/15535[#15535])
* Fixed: We should not start agent daemons outside of the service
    (https://issues.rudder.io/issues/16128[#16128])
* Fixed: factory-reset does not work on AIX
    (https://issues.rudder.io/issues/14574[#14574])
* Fixed: Negative execution time on AIX
    (https://issues.rudder.io/issues/12996[#12996])
* Fixed: "rudder agent check" should not require /etc/profile presence
    (https://issues.rudder.io/issues/16160[#16160])
* Fixed: Even when rudder agent is disabled, it runs cf-promises every 5 minutes
    (https://issues.rudder.io/issues/15854[#15854])

==== Packaging

* Fixed: Missing dependency on systemd for recent Ubuntu/Debian systems
    (https://issues.rudder.io/issues/14653[#14653])
* Fixed: Postrm script want to use systemd on Ubuntu 14.04
    (https://issues.rudder.io/issues/14139[#14139])
* Fixed: Inventory should not require the presence of /etc/profile
    (https://issues.rudder.io/issues/16162[#16162])
* Fixed: Remove unused 'argparse' dependency in rudder-pkg
    (https://issues.rudder.io/issues/11150[#11150])
* Fixed: Packaging files for rudder-api-client in 5.0 are not correct
    (https://issues.rudder.io/issues/16057[#16057])
* Fixed: Remove debug pprint from rudder-pkg
    (https://issues.rudder.io/issues/15985[#15985])
* Fixed: Unwanted systemctl output in rudder-reports postinst
    (https://issues.rudder.io/issues/15979[#15979])
* Fixed: rudder-api-client should not depend of python2 on redhat8
    (https://issues.rudder.io/issues/15936[#15936])
* Fixed: Build cache may ignore some changes within dependencies patches
    (https://issues.rudder.io/issues/15881[#15881])
* Fixed: On error, rudder-upgrade stops without error message
    (https://issues.rudder.io/issues/14560[#14560])
* Fixed: Invalid cron file put by packaging
    (https://issues.rudder.io/issues/14559[#14559])

==== Relay server or API

* Fixed: On relays /var/rudder/share files are not executable for group
    (https://issues.rudder.io/issues/16136[#16136])

==== Documentation

* Fixed: Missing documentation on openssl incompatibilities between 4.x and 5.0
    (https://issues.rudder.io/issues/16224[#16224])
* Fixed: Troubleshooting agent-server communication issues section in the doc is empty
    (https://issues.rudder.io/issues/16268[#16268])
* Fixed: Docs recommend using multiserver setup while its benefit may be dubious
    (https://issues.rudder.io/issues/16207[#16207])
* Fixed: Backup procedure documentation is incorrect
    (https://issues.rudder.io/issues/15271[#15271])
* Fixed: Debian/Ubuntu install doc fails if lsb_release is not installed
    (https://issues.rudder.io/issues/14632[#14632])
* Fixed: Document that a plugin is required for user roles and LDAP authentification
    (https://issues.rudder.io/issues/14812[#14812])
* Fixed: Document the usage of environment variables during installation
    (https://issues.rudder.io/issues/10015[#10015])
* Fixed: Typo in link to mustache method
    (https://issues.rudder.io/issues/14633[#14633])
* Fixed: Missing link to the beginning of the guide in getting strated home page
    (https://issues.rudder.io/issues/15408[#15408])
* Fixed: Document that a full policy regeneration is necessary after a backup restoration
    (https://issues.rudder.io/issues/15984[#15984])
* Fixed: Use MB instead of mB for megabytes in the doc
    (https://issues.rudder.io/issues/14161[#14161])
* Fixed: Document specific purging configuration for log_* reports
    (https://issues.rudder.io/issues/15974[#15974])
* Fixed: Document the hook that triggers an agent run on update
    (https://issues.rudder.io/issues/14332[#14332])
* Fixed: Document that variable_dict_from_file_type#csv needs CRLF
    (https://issues.rudder.io/issues/15657[#15657])
* Fixed: Fix internal doc links in generic methods
    (https://issues.rudder.io/issues/16092[#16092])
* Fixed: Fix title levels in generic methods docs
    (https://issues.rudder.io/issues/16036[#16036])

==== Web - Config management

* Fixed: policy generation logs still mention promises
    (https://issues.rudder.io/issues/16307[#16307])
* Fixed: The "migrate" field should not be displayed on directive creation
    (https://issues.rudder.io/issues/14859[#14859])
* Fixed: Audit/Enforce button in directive page should be similar to node page
    (https://issues.rudder.io/issues/13531[#13531])
* Fixed: Mark configuration-repository git repo options deprecated 
    (https://issues.rudder.io/issues/13870[#13870])
* Fixed: Dubious duplicate log message about hook
    (https://issues.rudder.io/issues/16091[#16091])

==== Web - Compliance & node report

* Fixed: Deadlock on compliance computing
    (https://issues.rudder.io/issues/16256[#16256])
* Fixed: Error when retrieving reports at application start
    (https://issues.rudder.io/issues/16189[#16189])
* Fixed: Directive appear in "mixed" mode in a rule applied on only one node
    (https://issues.rudder.io/issues/14379[#14379])
* Fixed: Rule tag is "Enforce" whereas it has both enforce and audit nodes
    (https://issues.rudder.io/issues/15124[#15124])
* Fixed: Deleted directives are not always removed from rule (and are then not actionnable)
    (https://issues.rudder.io/issues/14790[#14790])
* Fixed: No compliance from a Rule with only one Directive (from a technique created in the editor) when the Directive is also applied in another Rule
    (https://issues.rudder.io/issues/11917[#11917])

==== System integration

* Fixed: Nova license path in log is misleading for plugin licenses
    (https://issues.rudder.io/issues/15989[#15989])
* Fixed: We still have an LDAP entry "ou=Nodes Configuration,..." which is not used anymore
    (https://issues.rudder.io/issues/15878[#15878])
* Fixed: Missing some logger documentation in logback.xml
    (https://issues.rudder.io/issues/15916[#15916])
* Fixed: Not all rudder-related reports are sent to /var/log/rudder/reports/all.log
    (https://issues.rudder.io/issues/16214[#16214])

==== API

* Fixed: Could not get Group tree details through API
    (https://issues.rudder.io/issues/16269[#16269])
* Fixed: We cannot get the rules categories with the API
    (https://issues.rudder.io/issues/16164[#16164])

==== Performance and scalability

* Fixed: On a loaded system, the compliance computation is fairly expensive
    (https://issues.rudder.io/issues/16208[#16208])
* Fixed: Log metrics about configuration object at start of generation
    (https://issues.rudder.io/issues/16213[#16213])
* Fixed: Inefficient computing of compliance on home page
    (https://issues.rudder.io/issues/16201[#16201])
* Fixed: Missing timing info in logs for Home Page
    (https://issues.rudder.io/issues/16199[#16199])
* Fixed: Big memory usage when fetching/writing node configuration and expected reports
    (https://issues.rudder.io/issues/16083[#16083])
* Fixed: Improve documentation in rudder-web.properties about backup folder
    (https://issues.rudder.io/issues/16072[#16072])
* Fixed: Use `extends AnyVal` and remove HashCodeCaching for classes with one parameter
    (https://issues.rudder.io/issues/15797[#15797])
* Fixed: Computing dynamic groups is very memory intensive, and can lead to FGC or OOM
    (https://issues.rudder.io/issues/15858[#15858])
* Fixed: Rationalize the handling of variables during policy generation
    (https://issues.rudder.io/issues/15798[#15798])
* Fixed: Improve performance of logs parsing by rsyslog
    (https://issues.rudder.io/issues/16255[#16255])

==== Web - UI & UX

* Fixed: Inconsistent capitalization in menu items
    (https://issues.rudder.io/issues/16210[#16210])
* Fixed: In Node settings, "override global value" fields should have the same display 
    (https://issues.rudder.io/issues/16191[#16191])
* Fixed: Accepted inventory without matching rudder node appears in quicksearch
    (https://issues.rudder.io/issues/14431[#14431])
* Fixed: OS version sort in nodes list is broken
    (https://issues.rudder.io/issues/14433[#14433])
* Fixed: Folded subsections in directive forms are not visible enough
    (https://issues.rudder.io/issues/15107[#15107])
* Fixed: If an LDAP attribute is missing the related LDAP errors are not reported in UI (silent fail)
    (https://issues.rudder.io/issues/10067[#10067])
* Fixed: Improve Rules tabs visibility
    (https://issues.rudder.io/issues/11644[#11644])

==== Server components

* Fixed: If a relay is deleted (via node->delete), its system rule remains
    (https://issues.rudder.io/issues/14464[#14464])
* Fixed: Remote run does not try to use the system token
    (https://issues.rudder.io/issues/13825[#13825])

==== Web - Maintenance

* Fixed: JS Error when setting the "Send anonymous usage statistics " value
    (https://issues.rudder.io/issues/13508[#13508])

==== Plugins integration

* Fixed: Plugin id on plugin page should be more human-friendly
    (https://issues.rudder.io/issues/11101[#11101])

==== Web - Nodes & inventories

* Fixed: Error in group page when searching "Last inventory date" + "is defined"
    (https://issues.rudder.io/issues/14267[#14267])
* Fixed: In node details, clicking on policy server id redirect to original node
    (https://issues.rudder.io/issues/15953[#15953])
* Fixed: Add a test on group of groups
    (https://issues.rudder.io/issues/16030[#16030])

==== Miscellaneous

* Fixed: When the api authorization plugin is disabled tokens become read only
    (https://issues.rudder.io/issues/12440[#12440])

==== Web - Technique editor

* Fixed: Error message in technique editor when using wrong syntax for node properties is REALLY not clear enough 
    (https://issues.rudder.io/issues/15048[#15048])

==== Architecture - Refactoring

* Fixed: Trying to make LdapEntry immutable broke rudder - reverting
    (https://issues.rudder.io/issues/15965[#15965])

==== Techniques

* Fixed: Creating a user without home directory fails
    (https://issues.rudder.io/issues/11013[#11013])
* Fixed: The file from Rudder server technique may change permission of the destination parent directory instead of the file
    (https://issues.rudder.io/issues/13612[#13612])

==== System techniques

* Fixed: Agent is not correctly aborted when repaired is happening in audit mode
    (https://issues.rudder.io/issues/16178[#16178])
* Fixed: Rsync option for relay policy sync does not work
    (https://issues.rudder.io/issues/16064[#16064])
* Fixed: Initial policies on root server broken with missing postgres-check.cf file
    (https://issues.rudder.io/issues/16028[#16028])
* Fixed: In a separate database setup, an unexpected N/A report about "Postgresql component check" pops up
    (https://issues.rudder.io/issues/15993[#15993])

==== Generic methods

* Fixed: Add a generic method to escape regex chars in a string
    (https://issues.rudder.io/issues/16275[#16275])
* Fixed: Using ${match.x} in generic method causes an error message in the agent output, and prevents multiple reporting based on this generic method
    (https://issues.rudder.io/issues/14286[#14286])
* Fixed: http_request_content_headers test tries to get content from a removed site
    (https://issues.rudder.io/issues/16082[#16082])
* Fixed: Fix unexpected report in osquery method
    (https://issues.rudder.io/issues/15658[#15658])
* Fixed: variable_string_match tests are failing on old systems
    (https://issues.rudder.io/issues/15971[#15971])

==== Generic methods - File Management

* Fixed: ACLS methods are not working in recurse mode
    (https://issues.rudder.io/issues/16220[#16220])
* Fixed: Copying a file to a directory using the "file_from_shared_folder" method results in a success report even if nothing is done
    (https://issues.rudder.io/issues/16267[#16267])
* Fixed: Do not store response when response code is an error in file_fom_http_server
    (https://issues.rudder.io/issues/12780[#12780])
* Fixed: file_from_shared_folder generic methods fails to report
    (https://issues.rudder.io/issues/15983[#15983])

==== Technique editor - UI/UX

* Fixed: Deleting a technique in the technique editor just after its creation fails
    (https://issues.rudder.io/issues/15178[#15178])

==== Technique editor - API

* Fixed: Prevent setting an empty report component
    (https://issues.rudder.io/issues/15509[#15509])

==== Generic methods - Package Management

* Fixed: Missing report in "Package check installed" generic methods
    (https://issues.rudder.io/issues/16137[#16137])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky
* P C
* Mikaël Mantel
* Tobias Ell
* Jérémy HOCDÉ
* Jean Cardona
* Hamlyn Mootoo
* Alexandre BRIANCEAU
* Florian Heigl
* Didier METRAL

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.14 (2019-10-10)

=== Changes

==== Packaging

* Prepare the future build of rudder-api-client in 5.0
    (https://issues.rudder.io/issues/15815[#15815])

==== Architecture - Dependencies

* Update scala to 2.12.10
    (https://issues.rudder.io/issues/15741[#15741])

==== System integration

* Add test inventories for each major Rudder version
    (https://issues.rudder.io/issues/15705[#15705])

==== Agent

* Add a "rudder server health" command
    (https://issues.rudder.io/issues/15715[#15715])

==== Generic methods

* Add a check_variable_match method
    (https://issues.rudder.io/issues/15200[#15200])

==== Documentation

* Precise the documentation of user_present about user primary group
    (https://issues.rudder.io/issues/15764[#15764])

=== Bug fixes

==== Packaging

* Fixed: On sles12 the webapp gives "access denied" error after fresh install
    (https://issues.rudder.io/issues/15914[#15914])
* Fixed: Better sources clean in rudder-agent makefile
    (https://issues.rudder.io/issues/15787[#15787])
* Fixed: Create /opt/rudder/etc/plugins/licenses at server install
    (https://issues.rudder.io/issues/15763[#15763])
* Fixed: Add -XX:+UseStringDeduplication in G1GC optionnal config
    (https://issues.rudder.io/issues/15758[#15758])
* Fixed: rhel5 fails to get sources
    (https://issues.rudder.io/issues/15754[#15754])
* Fixed: Agent fail to build on slackware 14.1
    (https://issues.rudder.io/issues/15736[#15736])
* Fixed: Prerm does not backup ppkeys
    (https://issues.rudder.io/issues/15703[#15703])

==== Web - Nodes & inventories

* Fixed: Invalid json in Rudder inventory hooks fails to log the problem 
    (https://issues.rudder.io/issues/13866[#13866])
* Fixed: Job to clean unreference software may delete software for pending nodes
    (https://issues.rudder.io/issues/15827[#15827])
* Fixed: Virtuozzo Virtual machine reported as "Unknown type"
    (https://issues.rudder.io/issues/15488[#15488])
* Fixed: Impossible to reset the status of a Node using rudder-keys cli
    (https://issues.rudder.io/issues/14209[#14209])

==== Documentation

* Fixed: In the embedded docs the link to changelogs is broken
    (https://issues.rudder.io/issues/14222[#14222])
* Fixed: Port 5310 is only used internally, no need to open it on the server
    (https://issues.rudder.io/issues/14159[#14159])
* Fixed: Add a section in plugin documentation about plugin licenses installation
    (https://issues.rudder.io/issues/15793[#15793])
* Fixed: Display a warning in relay server documentatin that it needs a plugin to work
    (https://issues.rudder.io/issues/15751[#15751])
* Fixed: improve documentation on memory requirement
    (https://issues.rudder.io/issues/15702[#15702])

==== Architecture - Refactoring

* Fixed: Fix "Non exhaustive pattern match" warning
    (https://issues.rudder.io/issues/15893[#15893])

==== Performance and scalability

* Fixed: Clean up reports with log_* types more than once a day
    (https://issues.rudder.io/issues/15802[#15802])
* Fixed: When writing policies, we replace the RudderUniqueId with replaceAll which is twice as slow as StringUtils.replace
    (https://issues.rudder.io/issues/15792[#15792])
* Fixed: 'Nodes Configurations' ldap entry is too big
    (https://issues.rudder.io/issues/15609[#15609])
* Fixed: When computing system variables for each node, we compute the full "nodes<->policy server" mapping
    (https://issues.rudder.io/issues/15786[#15786])
* Fixed: When receiving plenty of inventories at the same time, the web interface starts to parse them all at once (branch 5.0)
    (https://issues.rudder.io/issues/15747[#15747])
* Fixed: Make inventory processing less memory consuming
    (https://issues.rudder.io/issues/15768[#15768])
* Fixed: Use less memory in PreUnmarshallCheckConsistency
    (https://issues.rudder.io/issues/15749[#15749])

==== Web - UI & UX

* Fixed: Rules are shown in "Applied rules" on groups where they are not applied
    (https://issues.rudder.io/issues/15599[#15599])
* Fixed: if screen height is too small, it's impossible to access settings in the rudder menu
    (https://issues.rudder.io/issues/15795[#15795])

==== Security

* Fixed: A user with read only access can global parameters
    (https://issues.rudder.io/issues/15104[#15104])

==== Web - Config management

* Fixed: Webapp does not wait long enough for technique editor API response, which can break startup
    (https://issues.rudder.io/issues/15809[#15809])
* Fixed: Webapp does not wait long enough for technique editor API response, which can break startup
    (https://issues.rudder.io/issues/15809[#15809])
* Fixed: Missing generation failure hook
    (https://issues.rudder.io/issues/15791[#15791])

==== API

* Fixed: Cannot get Rule tree with the API
    (https://issues.rudder.io/issues/15171[#15171])
* Fixed: Rudder authentication api refuse api account even if they have correct access rights set
    (https://issues.rudder.io/issues/15790[#15790])

==== Web - Maintenance

* Fixed: Batch to purge deleted inventories starts 10 minutes after startup, rather than the defined interval after startup
    (https://issues.rudder.io/issues/15710[#15710])

==== Techniques

* Fixed: Broken indentation in fileManagement posthook
    (https://issues.rudder.io/issues/15841[#15841])
* Fixed: fileManagement can not remove files with last modification date in the future
    (https://issues.rudder.io/issues/15840[#15840])
* Fixed: Rename services techniques to make the difference clearer
    (https://issues.rudder.io/issues/15839[#15839])
* Fixed: sshKeyDistribution breaks root perms when target user has no home defined
    (https://issues.rudder.io/issues/15738[#15738])

==== System techniques

* Fixed: Rudder agent cannot copy the certificate if the user defined one that is a link to a file in a different mount point
    (https://issues.rudder.io/issues/15801[#15801])
* Fixed: rudder-vars.json is read but absent in initial promises
    (https://issues.rudder.io/issues/15692[#15692])
* Fixed: System technique try to edit pg_hba file only on SUSE, but packaging takes care of this part
    (https://issues.rudder.io/issues/14296[#14296])

==== Agent

* Fixed: Command not found when running "rudder agent enable -s"
    (https://issues.rudder.io/issues/15697[#15697])

==== Generic methods

* Fixed: Missing usermod path in stdlib on redhat-based distros
    (https://issues.rudder.io/issues/15804[#15804])

==== Generic methods - File Management

* Fixed: jinja templating does not clean up the temp files properly
    (https://issues.rudder.io/issues/15800[#15800])

==== Technique editor - API

* Fixed: Technique editor does not handle errors from rudder authentication api correctly
    (https://issues.rudder.io/issues/15789[#15789])

==== Technique editor - UI/UX

* Fixed: Cannot create 'or' condition in technique editor (using | character)
    (https://issues.rudder.io/issues/15770[#15770])

==== Generic methods - User Management

* Fixed: user_primary_group tests method does not properly clean up all potentially created groups
    (https://issues.rudder.io/issues/15780[#15780])
* Fixed: user_primary_group test fails on sles11
    (https://issues.rudder.io/issues/15769[#15769])

==== System integration

* Fixed: InsecureRequestWarning pollute technique editor's logs
    (https://issues.rudder.io/issues/15777[#15777])

==== Generic methods - Service Management

* Fixed: Test for service_check_running_ps fails on centos6
    (https://issues.rudder.io/issues/15771[#15771])
* Fixed: Wrong service path used in method test
    (https://issues.rudder.io/issues/15760[#15760])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Victor Héry
* Philip Seeger

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.13 (2019-09-12)

=== Changes

==== Documentation

* Update list of supported OS
    (https://issues.rudder.io/issues/15443[#15443])
* Add a variable documentation page
    (https://issues.rudder.io/issues/15115[#15115])

==== Web - Config management

* Allow to get informations from the node inventory to use them in Directives and ncf techniques
    (https://issues.rudder.io/issues/3112[#3112])

==== Generic methods

* Add a GM to ensure that a kernel module is enable at boot
    (https://issues.rudder.io/issues/15220[#15220])
* Add a generic method to ensure that a kernel module is not loaded
    (https://issues.rudder.io/issues/15222[#15222])
* Add a generic method to ensure that a kernel module is not loaded
    (https://issues.rudder.io/issues/15222[#15222])
* Add a generic method to ensure that a kernel module is loaded
    (https://issues.rudder.io/issues/15216[#15216])
* Add a generic method to ensure that a kernel module is loaded
    (https://issues.rudder.io/issues/15216[#15216])
* Add a Generic Method to ensure that a kernel module modprobe configuration is correct
    (https://issues.rudder.io/issues/15430[#15430])
* Add automatic class_prefix and old_class_prefix for all methods in 30_generic_methods
    (https://issues.rudder.io/issues/15161[#15161])
* Improve and correct tests for command_execution GM
    (https://issues.rudder.io/issues/15166[#15166])
* Improve and correct tests for command_execution_result GM
    (https://issues.rudder.io/issues/15179[#15179])
* Improve and correct tests for condition_from_command.cf GM
    (https://issues.rudder.io/issues/15184[#15184])
* Extend variable_dict_from_file to allow reading yaml and csv files
    (https://issues.rudder.io/issues/10142[#10142])
* Extend variable_dict_from_file to allow reading yaml and csv files
    (https://issues.rudder.io/issues/10142[#10142])
* Add methods to define variables from osquery queries
    (https://issues.rudder.io/issues/15155[#15155])

==== Technique editor - UI/UX

* Make the focus on the generic method we just added 
    (https://issues.rudder.io/issues/15139[#15139])

=== Bug fixes

==== Packaging

* Fixed: Hooks content/permissions are changed during Rudder upgrade (for ex  /opt/rudder/etc/hooks.d/policy-generation-node-ready/10-cf-promise-check is replaced)
    (https://issues.rudder.io/issues/10623[#10623])
* Fixed: Perl dependency in the agent package is not in dependencies directory
    (https://issues.rudder.io/issues/15662[#15662])
* Fixed: Fixes to allow building the agent on Fedora 30
    (https://issues.rudder.io/issues/15454[#15454])
* Fixed: Add set -e in the qa-test of rudder-packages
    (https://issues.rudder.io/issues/15250[#15250])
* Fixed: qa test are failing in rudder-packages
    (https://issues.rudder.io/issues/15256[#15256])
* Fixed: qa tests in ncf does not fail if there is an error in the tests
    (https://issues.rudder.io/issues/15248[#15248])

==== Agent

* Fixed: Uuid generation fails on AIX 7.2
    (https://issues.rudder.io/issues/15586[#15586])
* Fixed: Double logs when running the agent in "-r"
    (https://issues.rudder.io/issues/15471[#15471])
* Fixed: Rudder agent disable command has a -s option, that is not parsed
    (https://issues.rudder.io/issues/15460[#15460])

==== System integration

* Fixed: Remove warning: "Nashorn engine is planned to be removed from a future JDK release " 
    (https://issues.rudder.io/issues/14822[#14822])
* Fixed: Autovacuum may never finish, or take more than one day, on busy Rudder instance, because of resources attrition
    (https://issues.rudder.io/issues/15413[#15413])
* Fixed: Clean-up Jetty abort on boot
    (https://issues.rudder.io/issues/15387[#15387])

==== Server components

* Fixed: support-info script doesn't correctly detect jetty process with Rudder 4.3+
    (https://issues.rudder.io/issues/13072[#13072])

==== Documentation

* Fixed: Correct archives procedure to include a 'technique reload'
    (https://issues.rudder.io/issues/15180[#15180])
* Fixed: Update link in readme to rudder.io
    (https://issues.rudder.io/issues/15305[#15305])

==== Performance and scalability

* Fixed: Reduce number of Loggable class instance
    (https://issues.rudder.io/issues/15665[#15665])
* Fixed: Huge quantity of memory not released after generation
    (https://issues.rudder.io/issues/15646[#15646])
* Fixed: Missing logs on NodeCompliance archive/deletion
    (https://issues.rudder.io/issues/15372[#15372])

==== Relay server or API

* Fixed: When creating a rule via the API the id parameter is only read from url parameters, and not from json
    (https://issues.rudder.io/issues/15608[#15608])

==== Web - UI & UX

* Fixed: Tags are not properly set when changing only value field before new insertion
    (https://issues.rudder.io/issues/15419[#15419])
* Fixed: Filtering tags with more than one tag with same "key" did not return correct results
    (https://issues.rudder.io/issues/15423[#15423])
* Fixed: Navigation menu is broken when it is folded
    (https://issues.rudder.io/issues/15328[#15328])
* Fixed: When we have a branding header, an annoying scrollbar appears on the technique editor page
    (https://issues.rudder.io/issues/15158[#15158])
* Fixed: "node management" and "config policy" menus should always be open
    (https://issues.rudder.io/issues/15203[#15203])
* Fixed: Quicksearch bar is misplaced when branding plugin is enabled
    (https://issues.rudder.io/issues/15165[#15165])

==== Web - Config management

* Fixed: Problem when updating a category name for Technique Management in /var/rudder
    (https://issues.rudder.io/issues/2613[#2613])
* Fixed: Avoid duplicating technique category when changing category name
    (https://issues.rudder.io/issues/15575[#15575])

==== Web - Maintenance

* Fixed: If we filter event logs with only a start or end date, we get a super ugly error
    (https://issues.rudder.io/issues/9445[#9445])

==== Web - Nodes & inventories

* Fixed: It is possible to download policies from any Windows node knowing its id by getting a forged inventory accepted 
    (https://issues.rudder.io/issues/14866[#14866])

==== Web - Compliance & node report

* Fixed: Error when modifying a Directive when having the Change Request plugin
    (https://issues.rudder.io/issues/15207[#15207])

==== Miscellaneous

* Fixed: Parameters of a directive are not correctly checked by change requests
    (https://issues.rudder.io/issues/15187[#15187])

==== Architecture - Dependencies

* Fixed: Duplicate dependency "jsr305" in rudder-core/pom.xml
    (https://issues.rudder.io/issues/14389[#14389])

==== System techniques

* Fixed: Wrong exclusion of folder in update.cf for common ncf
    (https://issues.rudder.io/issues/15428[#15428])

==== Techniques

* Fixed: It's not possible to use $(match.o) anymore in directives/techniques 
    (https://issues.rudder.io/issues/15029[#15029])
* Fixed: Invalid detection of empty strings for edition in Techniques
    (https://issues.rudder.io/issues/15167[#15167])
* Fixed: Rudder directives posthook can not support multilines command execution
    (https://issues.rudder.io/issues/15174[#15174])
* Fixed: Multi-line command in post-modification hooks works incorrectly
    (https://issues.rudder.io/issues/8933[#8933])
* Fixed: Rudder technique User management 6.0 ends with status repaired if user's comment field contains a comma ","
    (https://issues.rudder.io/issues/10156[#10156])
* Fixed: User Management doesn't report when we request a change of user home directory and it fails to change its home
    (https://issues.rudder.io/issues/15163[#15163])

==== Technique editor - Techniques

* Fixed: typo in "Variable dict from file'  method description
    (https://issues.rudder.io/issues/15654[#15654])
* Fixed: Reporting context is not re-evaluated when using multiple directives of the same technique
    (https://issues.rudder.io/issues/15572[#15572])

==== Technique editor - UI/UX

* Fixed: Missing components when exporting technique from the technique editor
    (https://issues.rudder.io/issues/15606[#15606])
* Fixed: Technique Editor accept invalid character (-) in condition
    (https://issues.rudder.io/issues/15504[#15504])

==== Generic methods - Package Management

* Fixed: Make zypper_pattern compatible with python2.6
    (https://issues.rudder.io/issues/15524[#15524])
* Fixed: zypper_pattern module does not work in python3
    (https://issues.rudder.io/issues/15522[#15522])
* Fixed: Fix zypper pattern module tests
    (https://issues.rudder.io/issues/15457[#15457])
* Fixed: package management reporting broken when trying to use latest version and absent state  
    (https://issues.rudder.io/issues/15149[#15149])

==== Generic methods

* Fixed: broken command execution tests in 5.1
    (https://issues.rudder.io/issues/15312[#15312])
* Fixed: Improve and correct tests for condition_from_variable_existence GM
    (https://issues.rudder.io/issues/15198[#15198])
* Fixed: Improve and correct tests for condition_from_expression GM
    (https://issues.rudder.io/issues/15197[#15197])
* Fixed: Modify ncf tests bundles to better handle the dry run stack
    (https://issues.rudder.io/issues/15192[#15192])
* Fixed: Reformat some classes bodies in ncf_lib.ncf
    (https://issues.rudder.io/issues/15169[#15169])
* Fixed: Improve and correct tests for condition_from_variable_match GM
    (https://issues.rudder.io/issues/15157[#15157])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Dmitry Svyatogorov
* Nicolas PERRON
* Ferenc Ulrich
* Jean VILVER
* Alexander Brunhirl
* Ilan COSTA

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.12 (2019-07-08)

=== Changes

==== Packaging

* Soften Rudder version requirements in dependencies of nightly builds to allow easier testing
    (https://issues.rudder.io/issues/15079[#15079])
* Better caching of already built binaries to speed-up builds
    (https://issues.rudder.io/issues/14955[#14955])
* Update CFEngine to 3.12.2
    (https://issues.rudder.io/issues/14921[#14921])
* Update embedded openssl version to 1.1.1b/1.0.2r
    (https://issues.rudder.io/issues/14933[#14933])

==== Documentation

* Add a "Rudder by example" to add CPU vulnerabilities status to inventory
    (https://issues.rudder.io/issues/15008[#15008])

==== Architecture - Internal libs

* Using move into non existing branch failed but delete the source
    (https://issues.rudder.io/issues/3591[#3591])

==== Web - UI & UX

* Allow to filter by technique name or tag in when managing directives in rule details
    (https://issues.rudder.io/issues/14803[#14803])

==== Agent

* Add support for rudder commands without subcommands
    (https://issues.rudder.io/issues/14944[#14944])
* Add disable date to rudder agent info
    (https://issues.rudder.io/issues/14929[#14929])

==== Web - Technique editor

* Add visual indication to methods modified since last save
    (https://issues.rudder.io/issues/14518[#14518])

=== Bug fixes

==== Packaging

* Fixed: Libraries sometime fail to load on AIX
    (https://issues.rudder.io/issues/15133[#15133])
* Fixed: Error after upgrade from 4.1 to 5.0 on RPM because slapd is not restarted: apiAuthorizationKind: attribute type undefined
    (https://issues.rudder.io/issues/15120[#15120])
* Fixed:  Rudder agent fails to build on aix due to unknown cp option
    (https://issues.rudder.io/issues/15088[#15088])
* Fixed: Rudder agent fails to build on rhel6 due to missing zlib and bzip2 build dependencies
    (https://issues.rudder.io/issues/15086[#15086])
* Fixed: The sourcedir parameter in dh_install needs to be lowercase for debian 10 compatibility
    (https://issues.rudder.io/issues/15013[#15013])
* Fixed: Disable shebang mangling in rhel8 to keep generic python shebangs
    (https://issues.rudder.io/issues/14958[#14958])

==== Performance and scalability

* Fixed: Allow overriding gc options for the webapp JVM to better deal with high volumes
    (https://issues.rudder.io/issues/15075[#15075])
* Fixed: Error at the end of a policy generation with too many nodes 
    (https://issues.rudder.io/issues/15011[#15011])
* Fixed: Rule changes SQL request and data structure use too much memory 
    (https://issues.rudder.io/issues/15042[#15042])
* Fixed: Compute change hook need to be on a dedicated threadpool
    (https://issues.rudder.io/issues/15096[#15096])
* Fixed: Hooks need to run on an dedicated thread pool
    (https://issues.rudder.io/issues/15095[#15095])
* Fixed: Add switch to disable some compliance and change tracking features for performance
    (https://issues.rudder.io/issues/15073[#15073])
* Fixed: Allow only catching up with recent runs in agent report processing batch
    (https://issues.rudder.io/issues/15062[#15062])
* Fixed: Make the size of the LDAP connection pool configurable
    (https://issues.rudder.io/issues/15060[#15060])
* Fixed: The computation of changes by rules, at start of web interface, is quite slow 
    (https://issues.rudder.io/issues/15041[#15041])
* Fixed: Avoid fetching nodeconfigurations twice when when runs processed
    (https://issues.rudder.io/issues/15035[#15035])
* Fixed: Deleted node should be periodically fully erased in LDAP (after some ttl)
    (https://issues.rudder.io/issues/9609[#9609])
* Fixed: Missing timing logs in ldap queries (especially for dynamic groups) 
    (https://issues.rudder.io/issues/14922[#14922])
* Fixed: Improve rsyslog performance by simplifying parsing of reports
    (https://issues.rudder.io/issues/15028[#15028])

==== Security

* Fixed: Arbitrary command execution in rudder relay API due to missing parameter sanitization
    (https://issues.rudder.io/issues/14974[#14974])

==== Documentation

* Fixed: Update backup and restore documentation 
    (https://issues.rudder.io/issues/15033[#15033])
* Fixed: Update backup and restore documentation 
    (https://issues.rudder.io/issues/15033[#15033])
* Fixed: Specify that we need more cpu cores  for Rudder server when managing a lot of nodes 
    (https://issues.rudder.io/issues/14940[#14940])
* Fixed: Add a note in the file content methods' docs to indicate they only work in full compliance mode
    (https://issues.rudder.io/issues/15090[#15090])

==== Web - UI & UX

* Fixed: Missing "disabled"  status information in rules table
    (https://issues.rudder.io/issues/15101[#15101])
* Fixed: Menu items can overflow menu width
    (https://issues.rudder.io/issues/15106[#15106])
* Fixed: Loading animation on 404 page is broken
    (https://issues.rudder.io/issues/15105[#15105])
* Fixed: Make node properties editable on the GUI
    (https://issues.rudder.io/issues/10612[#10612])
* Fixed: Font in "recent changes" tooltip on rules page is too big
    (https://issues.rudder.io/issues/14562[#14562])
* Fixed: Rule table search filter is broken after creating or deleting a rule
    (https://issues.rudder.io/issues/15070[#15070])
* Fixed: Start generation date in status is incorrect (it should not be page load date)
    (https://issues.rudder.io/issues/14941[#14941])
* Fixed: Group clone popup does not refresh group list, does not close, and an error when clicking a second time on clone
    (https://issues.rudder.io/issues/15039[#15039])
* Fixed: Webapp tries to load a missing angularjs map file
    (https://issues.rudder.io/issues/14935[#14935])

==== Web - Config management

* Fixed: Clicking on a group in rule configuration does not lead to the group
    (https://issues.rudder.io/issues/15099[#15099])
* Fixed: Generation fails with "Task FutureTask rejected from ThreadPoolExecutor" due to timeout in JS computation
    (https://issues.rudder.io/issues/14465[#14465])
* Fixed: Generation wronly warns with"non stable policy on node" when the same directive is used in two rules
    (https://issues.rudder.io/issues/15022[#15022])

==== Web - Compliance & node report

* Fixed: Directive with at least 3 times the same parameterized generic method leads to missing reports
    (https://issues.rudder.io/issues/15007[#15007])

==== System integration

* Fixed: rudder.auth.admin.password appears in clear text in the logs 
    (https://issues.rudder.io/issues/14946[#14946])

==== API

* Fixed: Missing rule name in compliance API
    (https://issues.rudder.io/issues/14241[#14241])

==== Techniques

* Fixed: Use umask defined in /etc/login.defs in Technique "SSH authorized keys"  for creating missing home dir 
    (https://issues.rudder.io/issues/14916[#14916])
* Fixed: Unexpected reports in Variable from JSON file(dict) when the json file is not present
    (https://issues.rudder.io/issues/14605[#14605])
* Fixed: File download technique generates error report on permissions 
    (https://issues.rudder.io/issues/14992[#14992])

==== Agent

* Fixed: Agent should trim policy_server.dat content 
    (https://issues.rudder.io/issues/14930[#14930])

==== Generic methods

* Fixed: We should test sles and suse classes in ncf tests  
    (https://issues.rudder.io/issues/15110[#15110])
* Fixed: Style test fails because it parses .pyc files 
    (https://issues.rudder.io/issues/15061[#15061])
* Fixed: Syntax error in file_report_content tests on 4.3
    (https://issues.rudder.io/issues/15053[#15053])
* Fixed: Normal ordering is not respected in some policies in 4.3 
    (https://issues.rudder.io/issues/15051[#15051])

==== Generic methods - File Management

* Fixed: permissions_acl_*_absent generic methods report success if no acls binaries are found on the system 
    (https://issues.rudder.io/issues/15121[#15121])
* Fixed: On sles15 there is no games user nor games group and we are using it in some acl tests   
    (https://issues.rudder.io/issues/15112[#15112])

==== Generic methods - Package Management

* Fixed: Improve package management error reporting to suggest avoiding virtual packages
    (https://issues.rudder.io/issues/14582[#14582])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.11 (2019-05-21)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: rudder agent dependencies are missing for rhel8 
    (https://issues.rudder.io/issues/14914[#14914])

==== Web - Nodes & inventories

* Fixed: Inventory may never finish if there is a disk issue or invalid mountpoint
    (https://issues.rudder.io/issues/14190[#14190])

==== Web - Config management

* Fixed: "Dynamic group update time-outed (waited for 10 secondes to finish)" 
    (https://issues.rudder.io/issues/14918[#14918])

==== System techniques

* Fixed: Unexpected status when sending inventory with non default schedule 
    (https://issues.rudder.io/issues/14909[#14909])

==== Techniques

* Fixed: Broken ubuntu version detection in apt settings technique with 5.0+ agents
    (https://issues.rudder.io/issues/14888[#14888])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.10 (2019-05-14)

=== Changes

==== Packaging

* Beautify pg_hba.conf
    (https://issues.rudder.io/issues/8901[#8901])
* Remove version replacement in packages and cleanup RUDDER_VERSION_TO_PACKAGE
    (https://issues.rudder.io/issues/14659[#14659])

==== Performance and scalability

* Document using pg_repack to prevent large disk usage
    (https://issues.rudder.io/issues/14450[#14450])

==== Documentation

* Add a debugging guide page to the doc
    (https://issues.rudder.io/issues/14785[#14785])

==== Web - UI & UX

* Make the Directive and Group sections foldable
    (https://issues.rudder.io/issues/14783[#14783])

==== Techniques

* Port MOTD Technique to DSC
    (https://issues.rudder.io/issues/14313[#14313])

==== Generic methods - File Management

* Add acl dedicated body in ncf_lib
    (https://issues.rudder.io/issues/14815[#14815])
* Add support for audit mode in "apply_gm" for the ncf tests
    (https://issues.rudder.io/issues/14635[#14635])

==== Generic methods

* Change all serverspec ncf tests in testinfra ones
    (https://issues.rudder.io/issues/14799[#14799])

==== Technique editor - UI/UX

* Merge the info and depreciation icon in technique editor
    (https://issues.rudder.io/issues/14665[#14665])

==== Miscellaneous

* Better Technique editor loading message
    (https://issues.rudder.io/issues/14622[#14622])

=== Bug fixes

==== Packaging

* Fixed: Postgresql is not started properly at postinstall on sles12 
    (https://issues.rudder.io/issues/14832[#14832])
* Fixed: Error when upgrading to Rudder 5.0.10 using centos7  with custom postgresql
    (https://issues.rudder.io/issues/14827[#14827])
* Fixed: ncf-api-virtualenv does not have a group created
    (https://issues.rudder.io/issues/11126[#11126])
* Fixed: Debian 8 server fail to install jdk during build
    (https://issues.rudder.io/issues/14765[#14765])
* Fixed: Debian 8 packages fail to build  
    (https://issues.rudder.io/issues/14754[#14754])
* Fixed: build-caching fails on builder with python 2.6 
    (https://issues.rudder.io/issues/14676[#14676])
* Fixed: Import relay sources into rudder repo
    (https://issues.rudder.io/issues/14660[#14660])

==== System integration

* Fixed: Postgresql misconfigured when not the default distrib package (ex: Centos 6 with Postgresql 9.3 from pgfoundry.org)
    (https://issues.rudder.io/issues/6403[#6403])

==== Agent

* Fixed: Script rudder-support-info does not mask credentials
    (https://issues.rudder.io/issues/13657[#13657])
* Fixed: Rudder remote run accept an invalid option -b 
    (https://issues.rudder.io/issues/14852[#14852])
* Fixed: Rudder commands should use rudder provided binaries when available 
    (https://issues.rudder.io/issues/14847[#14847])
* Fixed: When policy cannot be updated, agent says ok: Rudder agent promises were updated. 
    (https://issues.rudder.io/issues/14824[#14824])
* Fixed: Rudder agent check cannot restore saved uuid on AIX 
    (https://issues.rudder.io/issues/14763[#14763])
* Fixed: Rudder agent check does not repair policies if they are broken 
    (https://issues.rudder.io/issues/14692[#14692])

==== Documentation

* Fixed: Disk usage in documentation is insuficiently precise 
    (https://issues.rudder.io/issues/14842[#14842])
* Fixed: Add 2019 CfgMgmgtCamp videos to the docs 
    (https://issues.rudder.io/issues/14731[#14731])
* Fixed: Document that resource file of Techniques are shared to nodes with UTF-8 Encoding *only* (breaks for other encoding)
    (https://issues.rudder.io/issues/13619[#13619])

==== Performance and scalability

* Fixed: Correct disk usage in rudder configuration file 
    (https://issues.rudder.io/issues/14844[#14844])
* Fixed: Default archive retention is too large, which cause very large disk usage 
    (https://issues.rudder.io/issues/14834[#14834])

==== Web - Config management

* Fixed: A technique can have two agent section for the same kind of agent 
    (https://issues.rudder.io/issues/14797[#14797])
* Fixed: Accepting a change request on dynamic group, make the group empty leads an invalid policy generation 
    (https://issues.rudder.io/issues/14758[#14758])
* Fixed: When restoring archive (full or groups) dynamic groups are created empty
    (https://issues.rudder.io/issues/4480[#4480])
* Fixed: In node compliance, the rule name for root server is "distributePolicy", it should be at least "distribute policy"
    (https://issues.rudder.io/issues/14689[#14689])

==== Web - Maintenance

* Fixed: Postgres fills up and can't be vaccumed
    (https://issues.rudder.io/issues/14789[#14789])
* Fixed: Invalid comparison of String and Option[String] in HistorizationService 
    (https://issues.rudder.io/issues/14770[#14770])

==== API

* Fixed: API info does not list endpoints in their sorted order 
    (https://issues.rudder.io/issues/14807[#14807])
* Fixed: Api ordering and tests are broken  
    (https://issues.rudder.io/issues/14652[#14652])

==== System techniques

* Fixed: Sometimes, root server shows up with "No machine inventory" after install
    (https://issues.rudder.io/issues/14627[#14627])
* Fixed: Syntax error in techniques/system/server-roles/1.0/component-check.st
    (https://issues.rudder.io/issues/14808[#14808])
* Fixed: If postgresql is down, agent tried to fix password before checking that its up an running
    (https://issues.rudder.io/issues/14750[#14750])
* Fixed: rudder-directives.cf is included twice in policies 
    (https://issues.rudder.io/issues/14687[#14687])

==== Techniques

* Fixed: Technique "SSH authorized keys" creates home directory with perms root:root when it does not exists yet 
    (https://issues.rudder.io/issues/14732[#14732])

==== Generic methods

* Fixed: Fix badly translated files for ncf services tests 
    (https://issues.rudder.io/issues/14804[#14804])
* Fixed: Missing '_not_kept' state in method outcome 
    (https://issues.rudder.io/issues/14649[#14649])

==== Technique editor - UI/UX

* Fixed: Having a long Technique name breaks display of title  
    (https://issues.rudder.io/issues/14663[#14663])
* Fixed: The deprecated tooltip doesn't say why it is deprecated
    (https://issues.rudder.io/issues/13031[#13031])
* Fixed: Improve display of technique list in technique editor
    (https://issues.rudder.io/issues/14282[#14282])

==== Web - Compliance & node report

* Fixed: Reporting missing if several generic methods with same class_prefix and different condition applied 
    (https://issues.rudder.io/issues/9130[#9130])
* Fixed: Reporting missing if several generic methods with same class_prefix and different condition applied 
    (https://issues.rudder.io/issues/9130[#9130])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* emb3dd3d server
* Tobias Ell
* Florian Heigl
* Janos Mattyasovszky

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.9 (2019-04-15)

=== Changes

==== Packaging

* Remove psl dependency on curl
    (https://issues.rudder.io/issues/14500[#14500])
* Repair and adapt AIX agent to work with 5.0 changes 
    (https://issues.rudder.io/issues/14467[#14467])
* Reduce the size of the agent by removing cf-monitored
    (https://issues.rudder.io/issues/14406[#14406])

==== Documentation

* Add Windows known issues and improve install Windows software how-to
    (https://issues.rudder.io/issues/14446[#14446])
* Update antora theme/tools to 2.0.0
    (https://issues.rudder.io/issues/14385[#14385])

==== Web - UI & UX

* Add a "Copy to clipboard" button for Node properties and show its type
    (https://issues.rudder.io/issues/14593[#14593])
* Add a "Copy to clipboard" button for Node properties and show its type
    (https://issues.rudder.io/issues/14593[#14593])
* New display of Directives and Groups in Rule details
    (https://issues.rudder.io/issues/14536[#14536])
* New modern look for all tables
    (https://issues.rudder.io/issues/9557[#9557])

==== Web - Config management

* New tab in group details: display Rules applied to the group
    (https://issues.rudder.io/issues/11911[#11911])

==== API

* Add "Last seen" to Node API 
    (https://issues.rudder.io/issues/7922[#7922])

==== Web - Nodes & inventories

* Add Linux Mint support in inventories
    (https://issues.rudder.io/issues/10812[#10812])

==== Techniques

* Support separated policy generation for technique "Variable from JSON file (dict)"
    (https://issues.rudder.io/issues/14160[#14160])
* Support separated policy generation for technique "Variable from JSON file (dict)"
    (https://issues.rudder.io/issues/14160[#14160])

==== Generic methods

* Add a generic method call to test generic method
    (https://issues.rudder.io/issues/14563[#14563])
* Add bundle dedicated to the ncf tests
    (https://issues.rudder.io/issues/14311[#14311])
* Add systemd commands to the library of standard system command paths
    (https://issues.rudder.io/issues/14401[#14401])
* Improve service_{start/stop} tests
    (https://issues.rudder.io/issues/14323[#14323])

==== Technique editor - UI/UX

* We don't know where to click on a generic method to edit it
    (https://issues.rudder.io/issues/14317[#14317])

=== Bug fixes

==== Packaging

* Fixed: When installing rudder-agent, there's a long wait of run interval/2, so up to several hours
    (https://issues.rudder.io/issues/14644[#14644])
* Fixed: During installation of the agent, when staring "rudder agent" service, there is numerous error about missing '/opt/rudder/etc/uuid.hive' file
    (https://issues.rudder.io/issues/14616[#14616])
* Fixed: Debian 8 backports repository does not exist anymore, breaking our builds
    (https://issues.rudder.io/issues/14608[#14608])
* Fixed: Error message when installing or upgrading Rudder server about missing pid file
    (https://issues.rudder.io/issues/13767[#13767])
* Fixed: Build openssl for Slackware, so the agent can update promises
    (https://issues.rudder.io/issues/14570[#14570])
* Fixed: Error message when installing rudder-agent  on rpm based systems due to missing directory '/var/rudder/inventories'
    (https://issues.rudder.io/issues/14348[#14348])

==== System integration

* Fixed: Agent stderr shows up in /var/log/apache2/error.log
    (https://issues.rudder.io/issues/14602[#14602])
* Fixed: Allow changing cf-serverd loglevel and set info as default
    (https://issues.rudder.io/issues/8529[#8529])
* Fixed: Only one Node below a Rudder server can be run through remote run API
    (https://issues.rudder.io/issues/14391[#14391])
* Fixed: Manage rudder webapp shutdown correctly in case of fatal exception at startup
    (https://issues.rudder.io/issues/14281[#14281])
* Fixed: Windows 10 inventory is not fully supported
    (https://issues.rudder.io/issues/14295[#14295])
* Fixed: Error about invalid variable in httpd at Rudder install on centos 7
    (https://issues.rudder.io/issues/14592[#14592])

==== Agent

* Fixed: Slackware agent depends on mysql
    (https://issues.rudder.io/issues/14472[#14472])

==== System techniques

* Fixed: Agent connection cache does not work, and does not improve performance as expected
    (https://issues.rudder.io/issues/14342[#14342])
* Fixed: Bad reporting mode for "Monitoring; No Rudder monitoring information to share with the server"
    (https://issues.rudder.io/issues/14532[#14532])
* Fixed: Remove cf-monitored check on component "Binaries update"  
    (https://issues.rudder.io/issues/14561[#14561])
* Fixed: Missing "update" reports on node
    (https://issues.rudder.io/issues/12137[#12137])

==== Plugins integration

* Fixed: Typo in rudder-pkg when package version is incompatible
    (https://issues.rudder.io/issues/14408[#14408])

==== Documentation

* Fixed: uuid.hive is not present afet an install or an upgradie ofrudder agent to latest 4.1.x, 4.3.x and 5.0.x on rpm system purges the uuid.hive
    (https://issues.rudder.io/issues/14264[#14264])
* Fixed: Command to upgrade server from old 4.1/4.2/4.3 to 5.0  does not upgrade rudder-agent, breaking everything
    (https://issues.rudder.io/issues/14415[#14415])
* Fixed: Command to upgrade server from old 4.1/4.2/4.3 to 5.0  does not upgrade rudder-agent, breaking everything
    (https://issues.rudder.io/issues/14415[#14415])
* Fixed: Update mustache templating method documentation to detail the windows syntax
    (https://issues.rudder.io/issues/14451[#14451])

==== Architecture - Internal libs

* Fixed: Rudder postgres unit test are broken
    (https://issues.rudder.io/issues/14599[#14599])

==== Web - Config management

* Fixed: Policies generated for Rudder server have wrong permissions
    (https://issues.rudder.io/issues/14594[#14594])
* Fixed: UI "settings" for management of hooks works inconsistently
    (https://issues.rudder.io/issues/14386[#14386])

==== Web - UI & UX

* Fixed: There is no visual indication of sort in node table
    (https://issues.rudder.io/issues/14434[#14434])
* Fixed: JS error in rule pages, and Directives don't show in the list of directives
    (https://issues.rudder.io/issues/14573[#14573])
* Fixed: Fix some CSS issues following the style change of the Datatables
    (https://issues.rudder.io/issues/14463[#14463])
* Fixed: Typo in error message when aix plugin is not there
    (https://issues.rudder.io/issues/14426[#14426])

==== Web - Compliance & node report

* Fixed: Improve message on Node compliance details when  reports are outdated
    (https://issues.rudder.io/issues/14380[#14380])
* Fixed: Missing report on generic method "command exec" with $()
    (https://issues.rudder.io/issues/14390[#14390])

==== Security

* Fixed: Missing eventlogs for technique editor action and technique update
    (https://issues.rudder.io/issues/14312[#14312])

==== Web - Nodes & inventories

* Fixed: Incoherent state when accepting a Node, where node is accepted but now available in UI (error when creating Node entry)
    (https://issues.rudder.io/issues/14430[#14430])
* Fixed: System groups should be treated like normal groups and display their list of nodes 
    (https://issues.rudder.io/issues/11796[#11796])
* Fixed: Error about failed  move of machine inventory doesn't give sufficient context information
    (https://issues.rudder.io/issues/14522[#14522])

==== Performance and scalability

* Fixed: If a rule targets too many groups, policy generation fails
    (https://issues.rudder.io/issues/14392[#14392])
* Fixed: Improve 'rsyslog' to manage larger load of reports
    (https://issues.rudder.io/issues/14506[#14506])
* Fixed: Cron job checking rudder agent health, is ran every  5 minutes exactly, causing resource usage spike
    (https://issues.rudder.io/issues/14258[#14258])

==== Techniques

* Fixed: SNMP technique on windows wrongly parse the authorized sources
    (https://issues.rudder.io/issues/14368[#14368])

==== Technique editor - UI/UX

* Fixed: Padding in technique editor inputs makes you think there is a space before the value
    (https://issues.rudder.io/issues/14340[#14340])
* Fixed: Error in technique editor when there is  "$()" in  a parameter of a method
    (https://issues.rudder.io/issues/14549[#14549])

==== Generic methods

* Fixed: _classes_sanitize should be strict on the classes cancelled
    (https://issues.rudder.io/issues/14578[#14578])
* Fixed: Policy generation fails after upgrade  to 4.3: Undefined bundle lines_present
    (https://issues.rudder.io/issues/14548[#14548])
* Fixed: Expected repaired class in ncf tests are not correctly defined
    (https://issues.rudder.io/issues/14538[#14538])
* Fixed: Reporting when executing severspec is not correct in ncf tests
    (https://issues.rudder.io/issues/14537[#14537])
* Fixed: monitoring.csv accumulate temporary files that can blow up the filesystem
    (https://issues.rudder.io/issues/13716[#13716])

==== Generic methods - Package Management

* Fixed: Broken yum usage with old package promises on CentOS
    (https://issues.rudder.io/issues/14546[#14546])

==== Web - Technique editor

* Fixed: Technique editor duplicate techniques for each change
    (https://issues.rudder.io/issues/14370[#14370])
* Fixed: Reporting fails on NCF when service start/stop is guarded by a class
    (https://issues.rudder.io/issues/14404[#14404])

==== Generic methods - Service Management

* Fixed: ncf_services does not work on slackware
    (https://issues.rudder.io/issues/14471[#14471])

==== Generic methods - File Management

* Fixed: Improve method 'file copy from shared files'  parameters documentation
    (https://issues.rudder.io/issues/14361[#14361])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Aspid ASM
* Maxime Longuet
* Janos Mattyasovszky

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.8 (2019-02-28)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: Upgrade to 5.0.7 fails because rudder-upgrade script returns 1
    (https://issues.rudder.io/issues/14400[#14400])

==== Generic methods

* Fixed: Fix normal ordering in file report {tail/head}
    (https://issues.rudder.io/issues/14396[#14396])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.7 (2019-02-28)

=== Changes

==== Architecture - Internal libs

* Remove deprecated (and not use) code causing warning
    (https://issues.rudder.io/issues/14291[#14291])

==== Agent

* Add config id to rudder agent info
    (https://issues.rudder.io/issues/14306[#14306])

==== Generic methods - File Management

* Add a generic method that displays selected lines from a file in reports
    (https://issues.rudder.io/issues/14357[#14357])

==== Generic methods

* Add serverspec tests to the ncf ones
    (https://issues.rudder.io/issues/14314[#14314])

=== Bug fixes

==== System integration

* Fixed: Patch cf-serverd to change loglevel on agent refusal
    (https://issues.rudder.io/issues/8529[#8529])
* Fixed: Rudder database grows with time because of defaults values for  autovacuum that don't fit our needs
    (https://issues.rudder.io/issues/14336[#14336])
* Fixed: qa-test break because of repository layout change
    (https://issues.rudder.io/issues/14289[#14289])

==== Packaging

* Fixed: Never modify policy_server.dat on upgrade
    (https://issues.rudder.io/issues/14337[#14337])
* Fixed: "/var/rudder/inventories: no such dir" error message on first run
    (https://issues.rudder.io/issues/14257[#14257])

==== Documentation

* Fixed: Typo in "Replacement" in doc
    (https://issues.rudder.io/issues/14137[#14137])
* Fixed: Root of webapp docs changed
    (https://issues.rudder.io/issues/14284[#14284])
* Fixed: variable_dict_from_file: Path of file is unclear if relative or absolute
    (https://issues.rudder.io/issues/14117[#14117])

==== Web - Config management

* Fixed: Add an optional hook to trigger node update on nodes with new policies
    (https://issues.rudder.io/issues/14331[#14331])
* Fixed: Add an optional hook to trigger node update on nodes with new policies
    (https://issues.rudder.io/issues/14331[#14331])
* Fixed: Directive parameter values are mixed between directives
    (https://issues.rudder.io/issues/14322[#14322])

==== Web - Nodes & inventories

* Fixed: Windows 2019 doesn't show up correctly in node list
    (https://issues.rudder.io/issues/14362[#14362])
* Fixed: Mandatory fields for new inventories are not correctly checked 
    (https://issues.rudder.io/issues/13962[#13962])

==== Architecture - Refactoring

* Fixed: We are comparing Option[String] and String
    (https://issues.rudder.io/issues/14346[#14346])

==== Web - UI & UX

* Fixed: Fix compliance bars text color
    (https://issues.rudder.io/issues/14294[#14294])
* Fixed: Drag and drop of a generic method displays a phantom method
    (https://issues.rudder.io/issues/14321[#14321])

==== Architecture - Dependencies

* Fixed: Compilation fails with Java 11
    (https://issues.rudder.io/issues/14290[#14290])

==== Techniques

* Fixed: unexpected reports in zypper repo management technique
    (https://issues.rudder.io/issues/14347[#14347])
* Fixed: sshConfiguration technique should not authorize ssh password authent by default
    (https://issues.rudder.io/issues/14316[#14316])

==== System techniques

* Fixed: Technique uses /root as an hardcoded value for the home of user root
    (https://issues.rudder.io/issues/6412[#6412])

==== Generic methods - File Management

* Fixed: File lines absent generic method doesn't report anything when the file doesn't exist
    (https://issues.rudder.io/issues/14246[#14246])

==== Generic methods

* Fixed: ncf 4.1 is not compatible anymore with agent 3.1
    (https://issues.rudder.io/issues/14293[#14293])
* Fixed: "monitoring" technique is broken since we removed def.policy_server
    (https://issues.rudder.io/issues/14285[#14285])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky
* Tobias Ell

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.6 (2019-02-04)

=== Changes

=== Bug fixes

==== Web - Nodes & inventories

* Fixed: RHEL 7.6 appears as "Other Linux"
    (https://issues.rudder.io/issues/14200[#14200])

==== Documentation

* Fixed: Remove "repository" from Rudder repository name
    (https://issues.rudder.io/issues/14262[#14262])

==== System integration

* Fixed: Bad rights for hooks
    (https://issues.rudder.io/issues/14273[#14273])

==== Web - UI & UX

* Fixed: JS in directive name is executed on rule table if the directive is disabled
    (https://issues.rudder.io/issues/14271[#14271])
* Fixed: Rounding error in compliance bar
    (https://issues.rudder.io/issues/10773[#10773])

==== Architecture - Dependencies

* Fixed: Update very old maven-assembly version used for template-cli
    (https://issues.rudder.io/issues/14247[#14247])
* Fixed: Duplicate dependency "jsr305" in rudder-core/pom.xml
    (https://issues.rudder.io/issues/14248[#14248])
* Fixed: Update very old maven-assembly version used for template-cli
    (https://issues.rudder.io/issues/14247[#14247])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.5 (2019-01-30)

=== Changes

==== System integration

* Impossible to change keys of a Node using rudder-keys cli
    (https://issues.rudder.io/issues/14207[#14207])

==== Documentation

* Update links in doc to rudder.io
    (https://issues.rudder.io/issues/14203[#14203])
* Add some known issues in the known issue of the DSC doc
    (https://issues.rudder.io/issues/14150[#14150])
* Add some known issues in the known issue of the DSC doc
    (https://issues.rudder.io/issues/14150[#14150])

==== Web - Maintenance

* Update links in Rudder interface to use rudder.io
    (https://issues.rudder.io/issues/14205[#14205])

==== Web - Config management

* Configure report value of technique from technique editor
    (https://issues.rudder.io/issues/14091[#14091])

==== Techniques

* Port techniques downloadFile & cronManagement to separated policy generation 
    (https://issues.rudder.io/issues/14002[#14002])

==== Technique editor - UI/UX

* In the technique editor, scrolling through the GM should not mask the filter
    (https://issues.rudder.io/issues/14178[#14178])
* Manage caching of technique editor resources (css/js) with Rudder version
    (https://issues.rudder.io/issues/14194[#14194])
* Display documentation of ncf methods directly in the editor
    (https://issues.rudder.io/issues/14172[#14172])

==== Generic methods

* Update to 3.12.1 CFEngine stdlib
    (https://issues.rudder.io/issues/14129[#14129])

=== Bug fixes

==== Packaging

* Fixed: "rudder-init" script does not allow the "auto" option
    (https://issues.rudder.io/issues/14134[#14134])

==== Documentation

* Fixed: Missing documentation for "state" and "policymode" parameter expansion
    (https://issues.rudder.io/issues/13915[#13915])
* Fixed: Jinja templating iteration example in the doc is invalid
    (https://issues.rudder.io/issues/14179[#14179])

==== Web - UI & UX

* Fixed: Error when creating a rule
    (https://issues.rudder.io/issues/14245[#14245])
* Fixed: Rudder node id is confused with machine id and not selectable by triple-click
    (https://issues.rudder.io/issues/14243[#14243])
* Fixed: API token expiration date form appears behind the popup
    (https://issues.rudder.io/issues/14199[#14199])
* Fixed: Enable/Disable button text should be capitalized
    (https://issues.rudder.io/issues/14185[#14185])

==== Web - Compliance & node report

* Fixed: we can inject html & javascript in Rudder tables
    (https://issues.rudder.io/issues/14221[#14221])

==== Web - Maintenance

* Fixed: Constraints on table nodecompliancelevels are not valid
    (https://issues.rudder.io/issues/14218[#14218])

==== Performance and scalability

* Fixed: Index nodeid_idx is not used and consumes a lot of disk space for nothing
    (https://issues.rudder.io/issues/14149[#14149])

==== Web - Config management

* Fixed: When hooks are exiting with an error we can have stackoverflow error if there are many of them
    (https://issues.rudder.io/issues/10973[#10973])
* Fixed: When refreshing a rule details, the current tab is not memorized
    (https://issues.rudder.io/issues/4904[#4904])

==== API

* Fixed: Logs full of WARN  Attribute 'apiAuthorizationKind' or 'expirationTimestamp' is defined for API account but it will be ignored
    (https://issues.rudder.io/issues/13913[#13913])

==== Techniques

* Fixed: Technique "file content from remote template" does not work on the Rudder server when using remote file
    (https://issues.rudder.io/issues/14211[#14211])
* Fixed: "File content from remote template" technique ads tabs in the output file
    (https://issues.rudder.io/issues/14188[#14188])

==== System techniques

* Fixed: improve error message when the node cannot get the uuid from the server
    (https://issues.rudder.io/issues/14176[#14176])
* Fixed: psql should not freeze the agent
    (https://issues.rudder.io/issues/14156[#14156])
* Fixed: "classes promises do not support promise locking" warning message when running the agent
    (https://issues.rudder.io/issues/14132[#14132])
* Fixed: Add compatibility sles classes in failsafe
    (https://issues.rudder.io/issues/13975[#13975])
* Fixed: Missing report on File key-value parameter in list
    (https://issues.rudder.io/issues/14164[#14164])

==== Plugins integration

* Fixed: Separated policy generation does not work correctly with Rudder DSC agent
    (https://issues.rudder.io/issues/14038[#14038])

==== Web - Nodes & inventories

* Fixed: Inventory watcher is too quick and does not wait for file close
    (https://issues.rudder.io/issues/14237[#14237])

==== Agent

* Fixed: rudder agent inventory wrongly states that we are not in full compliance mode
    (https://issues.rudder.io/issues/13882[#13882])
* Fixed: Create a rudder server trigger_policy_generation command
    (https://issues.rudder.io/issues/14052[#14052])

==== System integration

* Fixed: Every agent check for postgresql and ldap partition size, resulting in possible overzealous shutting down of Rudder on node
    (https://issues.rudder.io/issues/14162[#14162])

==== Server components

* Fixed: cf-serverd may listen on port 8080 preventing rudder-jetty from running
    (https://issues.rudder.io/issues/13982[#13982])

==== Generic methods

* Fixed: Avoid  checking for exit_on_lock option on newer yum
    (https://issues.rudder.io/issues/14235[#14235])
* Fixed: Enable 4h cache on available upgrades list in old package bodies
    (https://issues.rudder.io/issues/14225[#14225])
* Fixed: Error in inform mode about undefined @args in rudder agent output
    (https://issues.rudder.io/issues/14214[#14214])
* Fixed: file_from_string_mustache GM unwanted behaviour when the mustache template use non-printable elements
    (https://issues.rudder.io/issues/14215[#14215])
* Fixed: Generic method in 4.3 should not use the class has_promiser_stack
    (https://issues.rudder.io/issues/14167[#14167])

==== Technique editor - UI/UX

* Fixed: Filter in generic method should not be case sensitive
    (https://issues.rudder.io/issues/14216[#14216])
* Fixed: Categories in Technique Editor do not work in IE 11.26.70
    (https://issues.rudder.io/issues/14181[#14181])

==== Generic methods - File Management

* Fixed: Jinja templating method does not correctly clean up temporary files in audit mode
    (https://issues.rudder.io/issues/13666[#13666])
* Fixed: Generic Method "File key-value present with option " treats the option as one of the value
    (https://issues.rudder.io/issues/14186[#14186])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Valentin Lelong

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.4 (2019-01-10)

=== Changes

==== Packaging

* Cleanup rudder promises generated
    (https://issues.rudder.io/issues/13996[#13996])
* Update CFEngine to 3.12.1
    (https://issues.rudder.io/issues/13927[#13927])

==== Documentation

* Add a page with an array for all versions info
    (https://issues.rudder.io/issues/13956[#13956])
* Add a page for videos about Rudder
    (https://issues.rudder.io/issues/14029[#14029])
* Update rudder-setup url in docs
    (https://issues.rudder.io/issues/14034[#14034])
* Render changelogs in Rudder doc
    (https://issues.rudder.io/issues/13928[#13928])
* Document some node-level system variables
    (https://issues.rudder.io/issues/13945[#13945])

==== System integration

* Missing flag file to trigger a policy generation
    (https://issues.rudder.io/issues/14050[#14050])

==== Web - UI & UX

* Remove jquery-ui related css libraries
    (https://issues.rudder.io/issues/13920[#13920])

==== Techniques

* Download files needed to build rudder-techniques package from repository.rudder.io
    (https://issues.rudder.io/issues/14036[#14036])
* Add a technique to manage basic SNMP configuration
    (https://issues.rudder.io/issues/13602[#13602])
* Technique File download (Rudder server) has a borken posthook and should incorporate a windows and a linux section
    (https://issues.rudder.io/issues/13918[#13918])

==== Technique editor - UI/UX

* Add a filter on generic method tree to find methods faster
    (https://issues.rudder.io/issues/14013[#14013])
* Allow to clone Generic methods in a technique in the editor
    (https://issues.rudder.io/issues/11676[#11676])
* Make conditions visible in the Technique editor
    (https://issues.rudder.io/issues/12740[#12740])

=== Bug fixes

==== Packaging

* Fixed: uuid.hive file should not be a rudder-agent package conf file
    (https://issues.rudder.io/issues/14062[#14062])
* Fixed: Force http 1.1 when downloading curl
    (https://issues.rudder.io/issues/14059[#14059])
* Fixed: When installing a rudder root server (on debian), it asks to run rudder-node-to-relay
    (https://issues.rudder.io/issues/11630[#11630])
* Fixed: Change packaging to allow openjdk > 8 
    (https://issues.rudder.io/issues/13896[#13896])
* Fixed: When we stop rudder-jetty, it says it stops Jetty 7 (we are using Jetty 9 ...)
    (https://issues.rudder.io/issues/13929[#13929])

==== Agent

* Fixed: Agent run errors are not outputted on stderr anymore
    (https://issues.rudder.io/issues/14061[#14061])
* Fixed: Os name for sles 12 is not correct in 5.0 inventories
    (https://issues.rudder.io/issues/13964[#13964])

==== Miscellaneous

* Fixed: Rudder-jetty depends on jdk8 but always try to install jdk9 as dependency
    (https://issues.rudder.io/issues/14024[#14024])

==== Documentation

* Fixed: Use B instead of b for bytes in the doc
    (https://issues.rudder.io/issues/14126[#14126])
* Fixed: Add documentation about rudder <-> plugin version compatibility in docs
    (https://issues.rudder.io/issues/14099[#14099])
* Fixed: Broken 4.1/4.3 doc build
    (https://issues.rudder.io/issues/14048[#14048])
* Fixed: Broken current redirect in docs
    (https://issues.rudder.io/issues/14047[#14047])

==== Web - Config management

* Fixed: Cannot modify groups when workflow are enabled
    (https://issues.rudder.io/issues/14056[#14056])

==== Plugins integration

* Fixed: indexes on nodecompliancelevels table are not valid and table ArchivedReportsExecution is never used
    (https://issues.rudder.io/issues/14007[#14007])

==== Performance and scalability

* Fixed: A lot of space is wasted on table nodecompliance and nodeconfigurations due to pretty jsonification
    (https://issues.rudder.io/issues/14014[#14014])
* Fixed: Massive performance penalty in policy generation due to invalid usage of StringTemplate
    (https://issues.rudder.io/issues/13987[#13987])
* Fixed: Load all ncf files in one go (or two)
    (https://issues.rudder.io/issues/13859[#13859])

==== Web - Maintenance

* Fixed: Impossible to log in with root admin 
    (https://issues.rudder.io/issues/13910[#13910])

==== Web - UI & UX

* Fixed: In the node details, clicking on the link to the policy server doesn't redirect to the policy server
    (https://issues.rudder.io/issues/13834[#13834])
* Fixed: Alignement of radio button on Settings page is still imperfect
    (https://issues.rudder.io/issues/13889[#13889])

==== Techniques

* Fixed: "Job Scheduler" Technique miss runs when using a non-default agent execution frequency
    (https://issues.rudder.io/issues/4840[#4840])

==== System techniques

* Fixed: Inventory fails since the files are not copied on the right location
    (https://issues.rudder.io/issues/13966[#13966])
* Fixed: "File from shared folder" technique in very old version does not work anymore since a common variable has been removed
    (https://issues.rudder.io/issues/13932[#13932])

==== Web - Nodes & inventories

* Fixed: Huge latency between inventory sent and inventory appears in Rudder
    (https://issues.rudder.io/issues/14080[#14080])

==== Generic methods

* Fixed: Error in the info (rudder agent run -i) output of the agent at first run
    (https://issues.rudder.io/issues/13951[#13951])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 5.0 series and therefore all installations of 5.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 5.0.3 (2018-11-26)

=== Changes

==== API

* Add rudder server version to the Rest API (system/info endpoint)
(https://issues.rudder.io/issues/13654[#13654])

==== System techniques

* Remove default server value from system techniques
(https://issues.rudder.io/issues/13819[#13819])

==== Techniques

* Provide a rudder.json file with initial policies
(https://issues.rudder.io/issues/13805[#13805])

==== Documentation

* Cleanup the ncf repo (https://issues.rudder.io/issues/13651[#13651])

=== Bug fixes

==== Plugins integration

* Fixed: Improve error messsage when path to install a plugin package is
not correct (https://issues.rudder.io/issues/13891[#13891])

==== Packaging

* Fixed: Rudder agent 4.3 needs libxml-treepp-perl on debian
(https://issues.rudder.io/issues/12599[#12599])
* Fixed: Slackware agent is not started at boot
(https://issues.rudder.io/issues/13850[#13850])
* Fixed: Error when uninstalling rudder-webapp and ncf-api-virtualenv
(https://issues.rudder.io/issues/11206[#11206])
* Fixed: Don’t create crontab entry at Rudder agent install but during
first run (https://issues.rudder.io/issues/13846[#13846])
* Fixed: Remove unnecessary conflict dependency with openjdk 9 on debian
(https://issues.rudder.io/issues/12664[#12664])
* Fixed: Missing _ in slackware package name
(https://issues.rudder.io/issues/13839[#13839])
* Fixed: Download Rudder sources from the new repository
(https://issues.rudder.io/issues/13838[#13838])
* Fixed: Agent should depend on a logging system on SUSE
(https://issues.rudder.io/issues/13788[#13788])
* Fixed: On rudder-webapp upgrade, ncf.conf file is not committed
(https://issues.rudder.io/issues/13679[#13679])

==== Agent

* Fixed: Upgrade CFEngine to 3.10.5
(https://issues.rudder.io/issues/13851[#13851])
* Fixed: ``rudder-keys change-key'' does not check for key file
existence (https://issues.rudder.io/issues/12496[#12496])
* Fixed: When ``policy-server.dat'' is missing, generated inventory is
not legit (https://issues.rudder.io/issues/11715[#11715])
* Fixed: /var/log/rudder/agent-check/check.log should contains only
error level messages (https://issues.rudder.io/issues/12230[#12230])
* Fixed: rudder remote run error, and unable to pass -i option
(https://issues.rudder.io/issues/11318[#11318])
* Fixed: Command ``rudder remote run -a'' does not warn about missing
token (https://issues.rudder.io/issues/11417[#11417])
* Fixed: Add a warn message when agent run is incomplete
(https://issues.rudder.io/issues/10751[#10751])
* Fixed: Command ``rudder agent reset'' sets incorrect permission in
/var/rudder/cfengine-community/inputs
(https://issues.rudder.io/issues/12410[#12410])
* Fixed: ``rudder agent info'' returns invalid report mode for not yet
accepted nodes (https://issues.rudder.io/issues/12992[#12992])
* Fixed: Missing spaces between key and message on rudder agent run
report when using -w option
(https://issues.rudder.io/issues/13663[#13663])

==== Performance and scalability

* Fixed: There are still tables expectedreports & expectesreportsnodes
on upgraded Rudder 4.x and 5.x,
(https://issues.rudder.io/issues/13770[#13770])
* Fixed: After a node is deleted, a policy generation is started every 5
secondes (https://issues.rudder.io/issues/13845[#13845])
* Fixed: Invalid value reported for Node expected reports saved in base
in Rudder log (https://issues.rudder.io/issues/13418[#13418])

==== Security

* Fixed: Impossible to update promises when using a debian9 or Ubuntu 18
server and older distributions as Nodes (incompatible openssl version)
(https://issues.rudder.io/issues/13690[#13690])

==== System integration

* Fixed: ``rudder-pkg enable-all'' command fails when a plugin has no
jar (https://issues.rudder.io/issues/13785[#13785])
* Fixed: Bad log level during generation
(https://issues.rudder.io/issues/9512[#9512])
* Fixed: Init check on group All classic Nodes known by Rudder (Using a
CFEngine based agent) always tries to rewrite the group
(https://issues.rudder.io/issues/13792[#13792])

==== Documentation

* Fixed: Windows doc has disappeared
(https://issues.rudder.io/issues/13880[#13880])
* Fixed: Document syslog port 5514 if Rudder server is an ubuntu < 14
(https://issues.rudder.io/issues/11016[#11016])
* Fixed: No favicon for Rudder doc on embedded doc
(https://issues.rudder.io/issues/13520[#13520])
* Fixed: Fix path to jinja2_custom.py in jinja2 templating doc
(https://issues.rudder.io/issues/13784[#13784])

==== Web - Config management

* Fixed: The password field allows storing a password without any
selected hash (https://issues.rudder.io/issues/12198[#12198])
* Fixed: Spinning compliance in nodes list on a disabled node
(https://issues.rudder.io/issues/12649[#12649])
* Fixed: Spinning compliance in nodes list on a disabled node
(https://issues.rudder.io/issues/12649[#12649])
* Fixed: ``Not copying missing license file into'' in webapp log
(https://issues.rudder.io/issues/10917[#10917])
* Fixed: Missing node state variable expansion in directive
(https://issues.rudder.io/issues/13671[#13671])
* Fixed: Add full path to shared-folder in description of ``Download
file from shared folder'' Technique
(https://issues.rudder.io/issues/13530[#13530])

==== Web - UI & UX

* Fixed: Wrong text color in table header in Rule page
(https://issues.rudder.io/issues/13835[#13835])
* Fixed: Quotes in reports are displayed as " in the web interface
(https://issues.rudder.io/issues/13349[#13349])
* Fixed: Upgrade loading wheel with a new look
(https://issues.rudder.io/issues/8622[#8622])
* Fixed: On Dashboard, when we have 100% of something, the pie is
including a confusing white line
(https://issues.rudder.io/issues/12233[#12233])
* Fixed: Imperfect alignement of radio button
(https://issues.rudder.io/issues/13512[#13512])
* Fixed: No color difference on hover on the user menu
(https://issues.rudder.io/issues/12926[#12926])
* Fixed: ``Configure the default state'' is lacking explanations
(https://issues.rudder.io/issues/12462[#12462])
* Fixed: Bad display of radio button on the Reports Database page in
Rudder 5.0 (https://issues.rudder.io/issues/13476[#13476])
* Fixed: Remove static ids in Password section
(https://issues.rudder.io/issues/13457[#13457])
* Fixed: Button to enable a technique in Directive Screen is not
working, should be a link to the Technique
(https://issues.rudder.io/issues/13779[#13779])
* Fixed: In directive page, tooltip is not correctly aligned with text
(https://issues.rudder.io/issues/13511[#13511])
* Fixed: The ``hardware'' tab is not displayed in accept new nodes
screen (https://issues.rudder.io/issues/13688[#13688])

==== Web - Nodes & inventories

* Fixed: When a node is deleted, its generated promises are not removed
(https://issues.rudder.io/issues/4709[#4709])
* Fixed: Inventory keeps its key certified when node is deleted
(https://issues.rudder.io/issues/9149[#9149])
* Fixed: Missing gateway, network in network interface details
(https://issues.rudder.io/issues/13804[#13804])
* Fixed: Network group criteria not working
(https://issues.rudder.io/issues/13772[#13772])
* Fixed: Node details shows Operating System Type: MSWin for Windows
node rather than Windows (https://issues.rudder.io/issues/6019[#6019])
* Fixed: The error message for bad inventory signature is unclear
(https://issues.rudder.io/issues/9192[#9192])
* Fixed: Network, mask and gateway not correctly parsed from inventory
(https://issues.rudder.io/issues/13803[#13803])

==== Web - Compliance & node report

* Fixed: Compliance error (missing) when a directive is applied by two
rules on a node (https://issues.rudder.io/issues/13674[#13674])

==== API

* Fixed: Remove old ``machyne type'' api Rest typo since it should not
be called anymore (https://issues.rudder.io/issues/13795[#13795])
* Fixed: Tags in rules are ignored in POST API
(https://issues.rudder.io/issues/13374[#13374])

==== Techniques

* Fixed: Option description for ``File download (Rudder server)''
technique is misleading (https://issues.rudder.io/issues/13887[#13887])
* Fixed: Technique ``Cron job v3.0'' does not use the ``user'' setting
with predefined scheduled (https://issues.rudder.io/issues/8004[#8004])
* Fixed: Missing reports on password component on ``User management''
Technique in audit mode (https://issues.rudder.io/issues/9474[#9474])
* Fixed: Enforce checkbox tooltip in ``Group management'' Technique is
misleading (https://issues.rudder.io/issues/13489[#13489])
* Fixed: Missing report with `File and directory basics' Technique in
audit mode when checking perms on non existing file
(https://issues.rudder.io/issues/11653[#11653])
* Fixed: Broken reporting when copying a directory from the Rudder
server without specifying the trailing / in the destination
(https://issues.rudder.io/issues/13290[#13290])
* Fixed: Missing report for post-modification hook in Technique ``File
download (Rudder server)''
(https://issues.rudder.io/issues/13717[#13717])
* Fixed: Details of usage of technique ``Variable from command output
(string)'' is not clear (https://issues.rudder.io/issues/12058[#12058])
* Fixed: Some files in the techniques repository do not present any
licence header (https://issues.rudder.io/issues/13633[#13633])
* Fixed: Technique ``cron job'' refuses task user name if it contains
hyphen (https://issues.rudder.io/issues/12960[#12960])
* Fixed: Missing report for component ``Post-modification hook'' when
cleaning files with ``File and directory basics'' Technique version 4.1
(https://issues.rudder.io/issues/13786[#13786])

==== System techniques

* Fixed: Mustache templates are not processed at all (including
cron.d/rudder-agent file)
(https://issues.rudder.io/issues/13885[#13885])
* Fixed: Slackware agent cron.d is broken in system technique
(https://issues.rudder.io/issues/13848[#13848])

==== Server components

* Fixed: server command based on jq should exit when jq is not installed
and explain to install it
(https://issues.rudder.io/issues/13682[#13682])

==== Generic methods

* Fixed: Typo in ``File content'' generic method description
(https://issues.rudder.io/issues/13883[#13883])
* Fixed: Generic method ``File_remove'' can delete empty directories
(https://issues.rudder.io/issues/12857[#12857])
* Fixed: Scheduler classes have incomplete labels
(https://issues.rudder.io/issues/8008[#8008])

==== Web - Technique editor

* Fixed: In technique editor, on save, we get ``success'' but some
errors are shallowed (https://issues.rudder.io/issues/12210[#12210])

==== Generic methods - File Management

* Fixed: Generic Method ``permission dirs'' incorrect reporting when
target path is a file (https://issues.rudder.io/issues/10689[#10689])
* Fixed: ``File key-value present'' Generic Method and ``Manage
keys-values in file'' Technique does not support | as separator
(https://issues.rudder.io/issues/13562[#13562])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Thomas CAILHE
* Ilan COSTA
* vlycop Doo
* Florian Heigl
* Renaud Manus
* Janos Mattyasovszky
* Romain Quinaud
* David Svejda

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 5.0.2 (2018-11-06)

=== Changes

==== Generic methods

* Add condition_once and execute_once generic methods
(https://www.rudder-project.org/redmine/issues/13667[#13667])

==== Documentation

* Document zypper pattern usage in the ``Package state'' generic method
documentation
(https://www.rudder-project.org/redmine/issues/13725[#13725])

=== Bug fixes

==== Web - UI & UX

* Fixed: We have no way to know that a Technique is disabled when
editing a Directive
(https://www.rudder-project.org/redmine/issues/12829[#12829])
* Fixed: Broken display of popup to delete node property in Rudder 5.0.1
(https://www.rudder-project.org/redmine/issues/13694[#13694])

==== Generic methods

* Fixed: Generic method ``Sharedfile to node'' always return repaired
status (https://www.rudder-project.org/redmine/issues/13753[#13753])
* Fixed: Unit tests for generic method ``File from a Jinja2 template''
fail on Ubuntu12 on Rudder 4.1
(https://www.rudder-project.org/redmine/issues/13747[#13747])
* Fixed: Time lib may not work when the first non-loopback interface has
no ip address
(https://www.rudder-project.org/redmine/issues/13744[#13744])
* Fixed: Remove comment about classes_generic_two being deprecated
(https://www.rudder-project.org/redmine/issues/13286[#13286])
* Fixed: Style test nbsp_is_not_allowed.sh always fails, missing 4.1
version of 13637
(https://www.rudder-project.org/redmine/issues/13722[#13722])
* Fixed: Missing report when using default value in Generic method
parameters (https://www.rudder-project.org/redmine/issues/13704[#13704])
* Fixed: Add more tests for the schedule lib in ncf
(https://www.rudder-project.org/redmine/issues/13668[#13668])
* Fixed: Zypper patterns tests should not be executed on non sles os
(https://www.rudder-project.org/redmine/issues/13638[#13638])

==== Web - Nodes & inventories

* Fixed: Group of group is empty if we use the AND combinator
(https://www.rudder-project.org/redmine/issues/13424[#13424])

==== Plugins integration

* Fixed: Authentication providers are not loaded before authentication
is initialized
(https://www.rudder-project.org/redmine/issues/13695[#13695])

==== Generic methods - File Management

* Fixed: Change the detection of curl path in ncf to use rudder_curl if
available (https://www.rudder-project.org/redmine/issues/13745[#13745])
* Fixed: Missing report in ``Manage keys-values in file'' technique
(https://www.rudder-project.org/redmine/issues/13715[#13715])
* Fixed: Missing reporting in ``Permissions recurse'' method
(https://www.rudder-project.org/redmine/issues/13683[#13683])
* Fixed: Generic Method ``File copy from remote source'' does not report
when copying a directory
(https://www.rudder-project.org/redmine/issues/13634[#13634])
* Fixed: Missing status when I use ``File copy from Rudder shared
folder'' Technique
(https://www.rudder-project.org/redmine/issues/13669[#13669])

==== Web - Config management

* Fixed: In directive, change input for parameter from technique editor
from text to textarea
(https://www.rudder-project.org/redmine/issues/12824[#12824])

==== Generic methods - Package Management

* Fixed: Missing report when using the ``Package state'' generic method
with default value for the ``state'' parameter
(https://www.rudder-project.org/redmine/issues/13703[#13703])

==== Agent

* Fixed: Redhat Openstack Nova compute QEMU virtual machines are seen as
physical (https://www.rudder-project.org/redmine/issues/10265[#10265])
* Fixed: Mustache templating in audit mode always considers destination
compliant once it exists
(https://www.rudder-project.org/redmine/issues/13664[#13664])

==== Packaging

* Fixed: rudder-cf-execd and rudder-cf-serverd are not enabled nor
running after a server install on debian 8
(https://www.rudder-project.org/redmine/issues/13774[#13774])
* Fixed: Rudder agent uninstall may fail to to systemd unit
(https://www.rudder-project.org/redmine/issues/13762[#13762])
* Fixed: can’t upgrade debian package if /bin/systemd exist but sysv is
used (https://www.rudder-project.org/redmine/issues/13174[#13174])
* Fixed: rudder.conf is not removed from /etc/ld.so.conf.d
(https://www.rudder-project.org/redmine/issues/12554[#12554])
* Fixed: Fusioninventory error about unitialized value $FQDN
(https://www.rudder-project.org/redmine/issues/13739[#13739])
* Fixed: Embedded openssl does not build on Ubuntu 15.10
(https://www.rudder-project.org/redmine/issues/13712[#13712])
* Fixed: ``type: systemctl : not found'' appears in rudder-agent
installation logs
(https://www.rudder-project.org/redmine/issues/13693[#13693])
* Fixed: Script rudder-support-info is too chatty when looking for time
(branch 5.0)
(https://www.rudder-project.org/redmine/issues/13670[#13670])
* Fixed: Rudder syslog port is reset after upgrade on Ubuntu (< 14)
Servers (https://www.rudder-project.org/redmine/issues/12714[#12714])

==== Generic methods - Service Management

* Fixed: Broken variable in ``Service restart'' method report
(https://www.rudder-project.org/redmine/issues/13713[#13713])

==== Documentation

* Fixed: Broken doc build
(https://www.rudder-project.org/redmine/issues/13734[#13734])

==== System techniques

* Fixed: Use embedded curl when available
(https://www.rudder-project.org/redmine/issues/13687[#13687])

==== Performance and scalability

* Fixed: LDAP IO error on generation with a lot of nodes
(https://www.rudder-project.org/redmine/issues/13256[#13256])

==== Techniques

* Fixed: Sharing files with ``root'' does not work
(https://www.rudder-project.org/redmine/issues/10605[#10605])
* Fixed: Add option for Zypper Patterns in Technique ``Packages''
(https://www.rudder-project.org/redmine/issues/13721[#13721])
* Fixed: Add a bigger warning about full path in ``Download a file''
technique (https://www.rudder-project.org/redmine/issues/13647[#13647])
* Fixed: Add a bigger warning about full path in ``Download a file''
technique (https://www.rudder-project.org/redmine/issues/13646[#13646])
* Fixed: Fix some typo in ``rudder server directive upgrade'' help
output (https://www.rudder-project.org/redmine/issues/13765[#13765])
* Fixed: ``directive-upgrade'' rudder command does not work
(https://www.rudder-project.org/redmine/issues/13681[#13681])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* tim c
* Matthew Frost
* Ilan COSTA
* Jérémy HOCDÉ
* Janos Mattyasovszky
* Thomas CAILHE

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 5.0.1 (2018-10-19)

=== Changes

==== Packaging

* Embed dependencies on ubuntu 15
(https://www.rudder-project.org/redmine/issues/13677[#13677])

==== Generic methods

* Add a flag library
(https://www.rudder-project.org/redmine/issues/13622[#13622])
* Add a flag library
(https://www.rudder-project.org/redmine/issues/13622[#13622])

==== Generic methods - Package Management

* Add a package provider for zypper patterns
(https://www.rudder-project.org/redmine/issues/12164[#12164])

=== Bug fixes

==== Generic methods

* Fixed: Allow to report on same reporting parameters
(https://www.rudder-project.org/redmine/issues/13632[#13632])
* Fixed: style test nbsp_is_not_allowed.sh always fails
(https://www.rudder-project.org/redmine/issues/13637[#13637])
* Fixed: rudder agent log files content in user facility
(https://www.rudder-project.org/redmine/issues/13175[#13175])
* Fixed: 4.3+ version of 12164
(https://www.rudder-project.org/redmine/issues/13621[#13621])
* Fixed: still some typos in package tests
(https://www.rudder-project.org/redmine/issues/13591[#13591])
* Fixed: some ncf test are failing on SLES because they are trying to
deal with packages that are not available
(https://www.rudder-project.org/redmine/issues/13573[#13573])

==== Web - Nodes & inventories

* Fixed: Node group with `OR' multi criteria fails
(https://www.rudder-project.org/redmine/issues/13649[#13649])

==== Web - Config management

* Fixed: Change request must not be saved when no validation is needed
(https://www.rudder-project.org/redmine/issues/13609[#13609])

==== Documentation

* Fixed: rudder-doc embedeed doesn’t work anymore
(https://www.rudder-project.org/redmine/issues/13659[#13659])
* Fixed: Document Amazon Linux compatibility
(https://www.rudder-project.org/redmine/issues/13624[#13624])
* Fixed: Add sles 15 in 5.0 supported OS
(https://www.rudder-project.org/redmine/issues/13533[#13533])
* Fixed: Bad explanation for generic variable overide priority cause
people making the opposite of what is needed
(https://www.rudder-project.org/redmine/issues/13615[#13615])

==== Technique editor - UI/UX

* Fixed: Rename ``bundle name'' in the technique details
(https://www.rudder-project.org/redmine/issues/12847[#12847])

==== Agent

* Fixed: rudder server command states that ``Warning: Long arguments are
not supported, you probably tried to use one!'' - but it does support it
(https://www.rudder-project.org/redmine/issues/13505[#13505])

==== Packaging

* Fixed: Ubuntu 13.04 package tries to use systemd
(https://www.rudder-project.org/redmine/issues/13676[#13676])
* Fixed: Debian package cannot build in 4.1 because of docs.rudder.io
(https://www.rudder-project.org/redmine/issues/13594[#13594])
* Fixed: cebtos7 install_package_existent should be skipped
(https://www.rudder-project.org/redmine/issues/13596[#13596])

==== Security

* Fixed: StackOverflowError during policy generation in JavascriptEngine
- debian 9.5 with jdk 1.8.0_181
(https://www.rudder-project.org/redmine/issues/13014[#13014])
* Fixed: In Rudder 5.0, user password encoding is broken for some
passwords. (https://www.rudder-project.org/redmine/issues/13643[#13643])
* Fixed: Api User Account doesn’t have User role
(https://www.rudder-project.org/redmine/issues/13629[#13629])
* Fixed: file enforce content log file content which can have private
info (https://www.rudder-project.org/redmine/issues/13608[#13608])

==== Performance and scalability

* Fixed: Hikari pool autocomit configuration is incorrect, which can
impact performance
(https://www.rudder-project.org/redmine/issues/13582[#13582])
* Fixed: Policy generation fails definitively when postgresql is shut
down during policy generation
(https://www.rudder-project.org/redmine/issues/13517[#13517])

==== Techniques

* Fixed: SudoParameter technique version 3.2 returns a report that is
not parsable by the CLI
(https://www.rudder-project.org/redmine/issues/13350[#13350])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Jeremy CHAMPEL
* tim c
* Marco Kirchhoff

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 5.0.0 (2018-09-27)

=== Changes

==== Packaging

* Require Postgresql 9.2 for rudder server
(https://www.rudder-project.org/redmine/issues/13545[#13545])
* rename ``support info'' script to ``debug info'' script and change
store debug info in a standard path
(https://www.rudder-project.org/redmine/issues/13443[#13443])

==== Documentation

* Finish initial version of get-started guide
(https://issues.rudder.io/issues/13177[#13177,
https://issues.rudder.io/issues/13448[#13448])
* Rudder by example cleanup
(https://www.rudder-project.org/redmine/issues/13452[#13452])
* Add a rudder-by-example to replace line in a file
(https://www.rudder-project.org/redmine/issues/13404[#13404])

=== Bug fixes

==== Web - UI & UX

* Fixed: Blue text color in node details tabs
(https://www.rudder-project.org/redmine/issues/13168[#13168])
* Fixed: fields are not correctly aligned in group page
(https://www.rudder-project.org/redmine/issues/13417[#13417])
* Fixed: Dual scrolling bars on the right of group details in Rudder 5
(https://www.rudder-project.org/redmine/issues/13428[#13428])
* Fixed: Tooltip on the source of property is not dislpayed in Rudder
5.0 (https://www.rudder-project.org/redmine/issues/13456[#13456])
* Fixed: JS error when loading Rules pages
(https://www.rudder-project.org/redmine/issues/13469[#13469])
* Fixed: In Rudder 5.0, Password fields in directive is empty
(https://www.rudder-project.org/redmine/issues/13446[#13446])
* Fixed: Rudder web login page shows 5 instead of 5.0 in the right
bottom corner
(https://www.rudder-project.org/redmine/issues/13472[#13472])

==== Generic methods

* Fixed: Some old tests are failing on centos
(https://www.rudder-project.org/redmine/issues/13535[#13535])
* Fixed: there is still a trailing new line in the jinja result test
file (https://www.rudder-project.org/redmine/issues/13529[#13529])
* Fixed: variable_string and variable_string_default GM are failing in
rudder 5.0 (https://www.rudder-project.org/redmine/issues/13523[#13523])
* Fixed: Some tests are failing on ubuntu distros
(https://www.rudder-project.org/redmine/issues/13514[#13514])
* Fixed: add a method to set reportiing_context from within a technique
(https://www.rudder-project.org/redmine/issues/13351[#13351])

==== Generic methods - File Management

* Fixed: Missing report on Permissions (non recursive)
(https://www.rudder-project.org/redmine/issues/13536[#13536])

==== Documentation

* Fixed: Update download link in documentation
(https://www.rudder-project.org/redmine/issues/13534[#13534])
* Fixed: Fix appearance of titles
(https://www.rudder-project.org/redmine/issues/13502[#13502])

==== Packaging

* Fixed: rudder-jetty cannot extract java version on sles15
(https://www.rudder-project.org/redmine/issues/13552[#13552])
* Fixed: rudder-agent service is not removed when removing rudder-agent
(https://www.rudder-project.org/redmine/issues/13549[#13549])
* Fixed: add insserv-compat dependency on SLES15 packages
(https://www.rudder-project.org/redmine/issues/13550[#13550])
* Fixed: Use openjdk 10 on sles 15
(https://www.rudder-project.org/redmine/issues/13543[#13543])
* Fixed: Use new man page URL after doc URL redirect
(https://www.rudder-project.org/redmine/issues/13537[#13537])
* Fixed: Error at install of Rudder Server Root 5.0 on Sles 12
(https://www.rudder-project.org/redmine/issues/13527[#13527])
* Fixed: rudder-agent 4.1 install hangs on Debian 7
(https://www.rudder-project.org/redmine/issues/13525[#13525])
* Fixed: Doc download in webapp package does not work anymore
(https://www.rudder-project.org/redmine/issues/13499[#13499])
* Fixed: rudder server upgrade-techniques –autoupdate-technique-library
fails when run during Rudder upgrade
(https://www.rudder-project.org/redmine/issues/13458[#13458])

==== API

* Fixed: Harmonize URLs of system API
(https://www.rudder-project.org/redmine/issues/13471[#13471])

==== Techniques

* Fixed: deprecate old version of techniques for Rudder 5.0
(https://www.rudder-project.org/redmine/issues/13487[#13487])
* Fixed: Package management technique fails to check if a package is
absent in the ``latest'' version
(https://www.rudder-project.org/redmine/issues/12939[#12939])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 5.0.0.rc1 (2018-09-12)

=== Changes

==== Architecture - Internal libs

* We need to be able to decide what workflow to use based on the change
request (https://www.rudder-project.org/redmine/issues/13396[#13396])

=== Bug fixes

==== API

* Fixed: POST/PUT/DELETE API requests gives 403
(https://www.rudder-project.org/redmine/issues/13426[#13426])
* Fixed: Rudder system api token only have RO access
(https://www.rudder-project.org/redmine/issues/13416[#13416])

==== Generic methods

* Fixed: " error: List or container parameter `args' not found while
constructing scope `log_rudder' - use @(scope.variable) in calling
reference" when running Rudder 4.3
(https://www.rudder-project.org/redmine/issues/13430[#13430])

==== Performance and scalability

* Fixed: On error on nodecompliance SQL, logs are huge
(https://www.rudder-project.org/redmine/issues/13427[#13427])

==== Architecture - Refactoring

* Fixed: Git merge issue between Rudder 4.3 and Rudder 5.0
(https://www.rudder-project.org/redmine/issues/13432[#13432])

==== Agent

* Fixed: remove unessecary patch that remove truncation of line in
inventory (https://www.rudder-project.org/redmine/issues/13403[#13403])
* Fixed: Upgrade perl to latest minor version in 5.0 for fusion
inventory (https://www.rudder-project.org/redmine/issues/13402[#13402])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 5.0.0.beta2 (2018-09-06)

=== Changes

==== Packaging

* Remove rudder agent thin in 5.0
(https://www.rudder-project.org/redmine/issues/13377[#13377])
* Upgrade python related dependencies
(https://www.rudder-project.org/redmine/issues/13371[#13371])
* Remove apache 2.2 support
(https://www.rudder-project.org/redmine/issues/13325[#13325])
* keep only systemd on server packages
(https://www.rudder-project.org/redmine/issues/13320[#13320])
* Upgrade jetty to 9.4.11
(https://www.rudder-project.org/redmine/issues/13323[#13323])
* Remove support for old system on rudder server builds
(https://www.rudder-project.org/redmine/issues/13315[#13315])
* Update agent dependencies
(https://www.rudder-project.org/redmine/issues/13314[#13314])
* Upgrade openssl
(https://www.rudder-project.org/redmine/issues/13316[#13316])
* Upgrade python related dependencies
(https://www.rudder-project.org/redmine/issues/13373[#13373])

==== Web - UI & UX

* Update main menu: plugin at top level, techique editor in
configuration policy
(https://www.rudder-project.org/redmine/issues/13067[#13067])

==== Documentation

* Use repository.rudder.io in 5.0 doc
(https://www.rudder-project.org/redmine/issues/13382[#13382])

==== Plugins integration

* Make user/role management a plugin
(https://www.rudder-project.org/redmine/issues/13030[#13030])

==== Architecture - Dependencies

* Update all rudder dependencies
(https://www.rudder-project.org/redmine/issues/13313[#13313])

=== Bug fixes

==== Web - UI & UX

* Fixed: Fonts changed in Rudder 5.0
(https://www.rudder-project.org/redmine/issues/13364[#13364])
* Fixed: Save button in group page is not readable in Rudder 5.0
(https://www.rudder-project.org/redmine/issues/13368[#13368])
* Fixed: In directives pages, Text selector and input field are not
correctly allligned in Rudder 5.0
(https://www.rudder-project.org/redmine/issues/13372[#13372])
* Fixed: Clicking on Status/Details leads to a disabled screen in Rudder
5.0 (https://www.rudder-project.org/redmine/issues/13362[#13362])

==== Generic methods

* Fixed: user_primary_group tests are failing on suse
(https://www.rudder-project.org/redmine/issues/13282[#13282])
* Fixed: Some ncf tests are too old and fails on many distributions
(https://www.rudder-project.org/redmine/issues/13249[#13249])

==== Architecture - Internal libs

* Fixed: Spring Security error - leading to random unlogging in Rudder 5
(https://www.rudder-project.org/redmine/issues/13365[#13365])

==== Technique editor - API

* Fixed: Error message is not correctly treated when an exception occurs
in when authenticating to Rudder authentication API
(https://www.rudder-project.org/redmine/issues/13219[#13219])

==== Packaging

* Fixed: libxml 2.9.8 doesn’t compile on aix
(https://www.rudder-project.org/redmine/issues/13363[#13363])
* Fixed: libxml fails to build with old compiler
(https://www.rudder-project.org/redmine/issues/13337[#13337])
* Fixed: Use correct version when building Slackware packages
(https://www.rudder-project.org/redmine/issues/13329[#13329])
* Fixed: Use https everywhere to download server sources
(https://www.rudder-project.org/redmine/issues/13324[#13324])
* Fixed: parallel build on rpmbuild hides build error
(https://www.rudder-project.org/redmine/issues/13300[#13300])

==== Generic methods - Service Management

* Fixed: Service test do not use any service to test on suse
(https://www.rudder-project.org/redmine/issues/13278[#13278])
* Fixed: 4.3+ version of 13278
(https://www.rudder-project.org/redmine/issues/13279[#13279])
* Fixed: services GM are not working anymore due to typo
(https://www.rudder-project.org/redmine/issues/13258[#13258])

==== Security

* Fixed: ``//'' in rudder-web/secure/api//settings/global_policy_mode
cause browser/spring error
(https://www.rudder-project.org/redmine/issues/13356[#13356])
* Fixed: Bad mime type for our js files: application/js
(https://www.rudder-project.org/redmine/issues/13334[#13334])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 5.0 series and therefore all
installations of 5.0.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 5.0.0.beta1 (2018-08-29)

=== Changes

==== API

* Create system Rest API to replace V1 API
(https://www.rudder-project.org/redmine/issues/12516[#12516])

==== Generic methods

* Add a generic method to test variable existence
(https://www.rudder-project.org/redmine/issues/12986[#12986])

==== Plugins integration

* Remove the need for Spring in plugin
(https://www.rudder-project.org/redmine/issues/13036[#13036])

==== Documentation

* Add a search field
(https://issues.rudder.io/issues/13093[#13093])
* Change version of documentation on rudder-doc
(https://www.rudder-project.org/redmine/issues/13019[#13019])
* Build a centralized place for doc: docs.rudder.io
(https://www.rudder-project.org/redmine/issues/12907[#12907])
* Use a rudder-specific theme
(https://www.rudder-project.org/redmine/issues/12875[#12875])
* Add DSC content to Rudder by example
(https://www.rudder-project.org/redmine/issues/12584[#12584])
* Add a ``Rudder by example'' guide to the documentation
(https://www.rudder-project.org/redmine/issues/12383[#12383])

==== Technique editor - API

* Remove expected reports.csv logic
(https://www.rudder-project.org/redmine/issues/11915[#11915])

==== Agent

* Use CFEngine 3.12 in Rudder agent
(https://www.rudder-project.org/redmine/issues/12856[#12856])
* Add a package techniques migration script
(https://www.rudder-project.org/redmine/issues/12710[#12710])
* Update technique migration technique with 12614 review
(https://www.rudder-project.org/redmine/issues/12676[#12676])

==== Packaging

* Add sles 15 support to rudder-packages
(https://www.rudder-project.org/redmine/issues/13295[#13295])
* Disable HTTPs for sources download on old OSes
(https://www.rudder-project.org/redmine/issues/13197[#13197])
* Download sources from repository.rudder.io instead of
www.normation.com
(https://www.rudder-project.org/redmine/issues/13172[#13172])
* Download man on docs.rudder.io
(https://www.rudder-project.org/redmine/issues/13170[#13170])

==== Generic methods - Service Management

* Remove unused _service_check_running_smf and
_service_check_running_src in branch 5.0
(https://www.rudder-project.org/redmine/issues/13245[#13245])

==== System integration

* Bundle support info script into Rudder
(https://www.rudder-project.org/redmine/issues/13213[#13213])

==== Architecture - Refactoring

* Make scale-out (relay) server a plugin
(https://www.rudder-project.org/redmine/issues/12885[#12885])
* Make third-party authentication a plugin
(https://www.rudder-project.org/redmine/issues/12906[#12906])
* Make validation workflow a plugin
(https://www.rudder-project.org/redmine/issues/12904[#12904])

==== Generic methods - Package Management

* Use the new class_prefix for package methods
(https://www.rudder-project.org/redmine/issues/12427[#12427])

=== Bug fixes

==== Web - UI & UX

* Fixed: Remove the ``tw-bs'' css hack
(https://www.rudder-project.org/redmine/issues/13022[#13022])

==== Generic methods

* Fixed: Incomplete management of disabled/reenable reporting
(https://www.rudder-project.org/redmine/issues/13209[#13209])
* Fixed: file_check_special tests are failing on debian
(https://www.rudder-project.org/redmine/issues/13243[#13243])
* Fixed: Huge agent logs when we define an new class_prefix that is
longer than 1024 chars
(https://www.rudder-project.org/redmine/issues/13155[#13155])

==== Plugins integration

* Fixed: Missing real-time check of license capabilities for api and
others plugins
(https://www.rudder-project.org/redmine/issues/13073[#13073])

==== Generic methods - File Management

* Fixed: Error when using 2 or more File from a jinja2 template
(https://www.rudder-project.org/redmine/issues/13183[#13183])

==== Documentation

* Fixed: Git repository not initialised in plugin directory
(https://issues.rudder.io/issues/13306[13306])
* Fixed: Wrong version displayed on the login page for plugin branding
(https://www.rudder-project.org/redmine/issues/13274[#13274])
* Fixed: Update screenshot for Rudder Branding
(https://www.rudder-project.org/redmine/issues/13270[#13270])
* Fixed: Make plugin doc build with 5.0 doc
(https://issues.rudder.io/issues/13137[13137])
* Fixed: Typos in rudder-by-example
(https://www.rudder-project.org/redmine/issues/12611[#12611])
* Fixed: Add a favicon for Rudder by example
(https://www.rudder-project.org/redmine/issues/12490[#12490])
* Fixed: Build rudder man page using asciidoctor
(https://www.rudder-project.org/redmine/issues/12977[#12977])

==== Miscellaneous

* Fixed: Removing workflow comet leads to missing user information and
session is destroyed
(https://www.rudder-project.org/redmine/issues/13026[#13026])

==== Agent

* Fixed: Broken agent build on linux platforms
(https://www.rudder-project.org/redmine/issues/13311[#13311])
* Fixed: rudder technique-migrate is not documented nor properly named
(https://www.rudder-project.org/redmine/issues/13146[#13146])

==== Packaging

* Fixed: Purge of rudder-webapp should not fail
(https://www.rudder-project.org/redmine/issues/13210[#13210])
* Fixed: Fix bdb download link from repository.rudder.io
(https://www.rudder-project.org/redmine/issues/13198[#13198])
* Fixed: slackware should not build its package into /tmp
(https://www.rudder-project.org/redmine/issues/13194[#13194])
* Fixed: Download rudder.8 for new man page url
(https://www.rudder-project.org/redmine/issues/12982[#12982])
* Fixed: Add back missing migration script in 5.0
(https://www.rudder-project.org/redmine/issues/13084[#13084])
* Fixed: Makefile fails if a symbolink link /usr/bin/ncf already exists
(https://www.rudder-project.org/redmine/issues/13277[#13277])

==== Generic methods - Service Management

* Fixed: service_started_start.cf test fails on redhat
(https://www.rudder-project.org/redmine/issues/13257[#13257])
* Fixed: service_started_path.cf does not generate classes anymore since
13220 (https://www.rudder-project.org/redmine/issues/13254[#13254])

==== API

* Fixed: Compilation warnings in master
(https://www.rudder-project.org/redmine/issues/13028[#13028])

==== Generic methods - Package Management

* Fixed: old packages generic methods are failing on old debian
(https://www.rudder-project.org/redmine/issues/13305[#13305])

==== Techniques

* Fixed: Package repository keys Technique in Audit Mode : Missing
Reports (https://www.rudder-project.org/redmine/issues/13065[#13065])
* Fixed: Package repository keys Technique in Audit Mode : Missing
Reports (https://www.rudder-project.org/redmine/issues/13065[#13065])
* Fixed: Rudder SNMP technique has a component failing on first run
(https://www.rudder-project.org/redmine/issues/13159[#13159])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Mikaël Mantel
* Pierre HAY
* Guillaume Terrier

This software is in beta status and contains several new features but we
have tested it and believe it to be free of any critical bugs. The use
on production systems is not encouraged at this time and is at your own
risk. However, we do encourage testing, and welcome all and any
feedback!
