= Changelogs for Rudder plugin benchmark-cis-ubuntu-24-04 9.1.\* versions

== benchmark-cis-ubuntu-24-04-9.1.1-0.10 (2026-05-04)

=== Changes


==== Miscellaneous

* CIS Windows Server 2022 - section 17
    (https://issues.rudder.io/issues/28696[#28696])

=== Bug fixes

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-ubuntu-24-04-9.1.0-0.10 (2026-04-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-ubuntu-24-04-9.1.0.rc1-0.10 (2026-04-10)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Missing Ubuntu 24.04 benchmark from tests
    (https://issues.rudder.io/issues/28544[#28544])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-ubuntu-24-04-9.1.0.beta1-0.10 (2026-03-10)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

