= Changelogs for Rudder plugin benchmark-cis-windows-2022 9.1.\* versions

== benchmark-cis-windows-2022-9.1.0.rc1-0.10 (2026-04-10)

=== Changes


==== Miscellaneous

* CIS Windows Server 2022 - all sections without secedit and auditpool
    (https://issues.rudder.io/issues/28482[#28482])

=== Bug fixes

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-windows-2022-9.1.0.beta1-0.10 (2026-03-10)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-windows-2022-9.1.0.alpha1-0.10 (2026-01-26)

=== Changes


==== Miscellaneous

* Init Windows Server 2022 CIS directory project
    (https://issues.rudder.io/issues/28065[#28065])

=== Bug fixes

==== Miscellaneous

* Fixed: Double colone in title breaks parsing for metadata.json
    (https://issues.rudder.io/issues/28220[#28220])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

