= Changelogs for Rudder plugin change-validation 9.1.\* versions

== change-validation-9.1.0.rc1-2.4 (2026-04-10)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: In the changes tab of a change request's changes table, the display of the entire component breaks if some diff lines are too long
    (https://issues.rudder.io/issues/28605[#28605])
* Fixed: Change request history table does not render as a table
    (https://issues.rudder.io/issues/28547[#28547])
* Fixed: Change requests table empty when accessed with specific URL
    (https://issues.rudder.io/issues/28264[#28264])
* Fixed: Directive change request shows whole sectionval diff
    (https://issues.rudder.io/issues/28502[#28502])
* Fixed: Change request loading page is an error message
    (https://issues.rudder.io/issues/28328[#28328])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-9.1.0.beta1-2.4 (2026-03-10)

=== Changes


==== Plugins management

* License should check instance id if defined 
    (https://issues.rudder.io/issues/28273[#28273])

==== Miscellaneous

* Bump rudder-elm-library version to 0.2.4
    (https://issues.rudder.io/issues/28240[#28240])

=== Bug fixes

==== Plugins management

* Fixed: Update templating-maven-plugin since 1.0 API doesn't work with recent maven anymore (public)
    (https://issues.rudder.io/issues/28279[#28279])

==== Miscellaneous

* Fixed: The change requests management table is initially empty
    (https://issues.rudder.io/issues/28242[#28242])
* Fixed: Error "Workflow API is not available" upon trying to view any change request page 
    (https://issues.rudder.io/issues/28138[#28138])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-9.1.0.alpha1-2.4 (2026-01-26)

=== Changes


==== Miscellaneous

* Update Scala dependencies - 9.1 
    (https://issues.rudder.io/issues/27842[#27842])

=== Bug fixes

==== Miscellaneous

* Fixed: Change requests table status filter is missing + button
    (https://issues.rudder.io/issues/27772[#27772])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

