= Changelogs for Rudder plugin cve 9.1.\* versions

== cve-9.1.3-2.12 (2026-07-11)

=== Changes


==== Miscellaneous

* Update http5client to fix cve in dependencies
    (https://issues.rudder.io/issues/29199[#29199])

=== Bug fixes

==== Miscellaneous

* Fixed: Some CVEs may have conflicting information for their score, which causes display inconsistencies (might be releatd to CVSSv4 and CVSSv3 difference in score)
    (https://issues.rudder.io/issues/27939[#27939])
* Fixed: Correct source package management for debian requests
    (https://issues.rudder.io/issues/29085[#29085])
* Fixed: The write_rights boolean of the CVE Elm app takes the value of the rule_write user authorization
    (https://issues.rudder.io/issues/28927[#28927])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-9.1.2-2.12 (2026-06-11)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Filters should be case insensitive
    (https://issues.rudder.io/issues/28635[#28635])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-9.1.1-2.12 (2026-05-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-9.1.0-2.12 (2026-04-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-9.1.0.rc1-2.12 (2026-04-10)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-9.1.0.beta1-2.12 (2026-03-10)

=== Changes


==== Miscellaneous

* Plugin license check should check instance id
    (https://issues.rudder.io/issues/28274[#28274])
* In the CVE plugin there is a remove group button but not a remove campaign button
    (https://issues.rudder.io/issues/27694[#27694])

=== Bug fixes

==== Miscellaneous

* Fixed: Revert 26924 since checkbox is broken
    (https://issues.rudder.io/issues/28330[#28330])
* Fixed: Remediated CVE don't show up in the list if they are not found inthe node details first
    (https://issues.rudder.io/issues/26924[#26924])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-9.1.0.alpha1-2.12 (2026-01-26)

=== Changes


==== Miscellaneous

* Update dependencies scala - 9.1
    (https://issues.rudder.io/issues/27843[#27843])

=== Bug fixes

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

