= Changelogs for Rudder plugin secret-management 9.1.\* versions

== secret-management-9.1.0-1.1 (2026-04-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-9.1.0.rc1-1.1 (2026-04-10)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Table filter in secrets page does not look like a bootstrap input
    (https://issues.rudder.io/issues/28520[#28520])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-9.1.0.beta1-1.1 (2026-03-10)

=== Changes


==== Miscellaneous

* Plugin license check should check instance id
    (https://issues.rudder.io/issues/28274[#28274])

=== Bug fixes

==== Plugins integration

* Fixed: Fix imports of QueryContext
    (https://issues.rudder.io/issues/28441[#28441])

==== Miscellaneous

* Fixed: Change log about secret added should be saved admin
    (https://issues.rudder.io/issues/28424[#28424])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-9.1.0.alpha1-1.1 (2026-01-26)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

