= Changelogs for Rudder plugin security-benchmarks 9.1.\* versions

== security-benchmarks-9.1.0.rc1-1.2 (2026-04-10)

=== Changes


==== Miscellaneous

* Export of benchmark parameters to CSV items scopes should be side by side
    (https://issues.rudder.io/issues/28607[#28607])

=== Bug fixes

==== Miscellaneous

* Fixed: Scrollbar in Item details column doesn't reach the bottom
    (https://issues.rudder.io/issues/28530[#28530])
* Fixed: Cleaning benchmarks should be "at best"
    (https://issues.rudder.io/issues/27900[#27900])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-9.1.0.beta1-1.2 (2026-03-10)

=== Changes


==== Miscellaneous

* Export of benchmark parameters to CSV should include disabled items
    (https://issues.rudder.io/issues/28371[#28371])
* Export benchmark parameters to CSV
    (https://issues.rudder.io/issues/28051[#28051])
* Plugin license check should check instance id
    (https://issues.rudder.io/issues/28274[#28274])
* Show property override and inheritance
    (https://issues.rudder.io/issues/27995[#27995])

=== Bug fixes

==== Miscellaneous

* Fixed: Button to export parameters to CSV should look different
    (https://issues.rudder.io/issues/28372[#28372])
* Fixed: Error with multiple saves of benchmark
    (https://issues.rudder.io/issues/28204[#28204])
* Fixed: Creating new benchmark leads to an error about missing score
    (https://issues.rudder.io/issues/28180[#28180])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-9.1.0.alpha1-1.2 (2026-01-26)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Double colone in title breaks parsing for metadata.json
    (https://issues.rudder.io/issues/28220[#28220])
* Fixed: CIS : rudder_syctl_file is not defined for the benchmark
    (https://issues.rudder.io/issues/28192[#28192])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

