= Changelogs for Rudder plugin system-updates 9.1.\* versions

== system-updates-9.1.2-1.18 (2026-06-11)

=== Changes


==== Miscellaneous

* Add ui test cases on search bar in update campaigns in result tab
    (https://issues.rudder.io/issues/28963[#28963])
* Add a new log file to log the Windows module calls
    (https://issues.rudder.io/issues/28921[#28921])
* Add ui tests on filter result tab of a campaign event  
    (https://issues.rudder.io/issues/28886[#28886])
* Add ui tests on filter result tab of a campaign event  
    (https://issues.rudder.io/issues/28886[#28886])

=== Bug fixes

==== Miscellaneous

* Fixed: Search bar in campaign nodes does not work
    (https://issues.rudder.io/issues/28974[#28974])
* Fixed: Search bar in software campaign nodes does not work
    (https://issues.rudder.io/issues/29006[#29006])
* Fixed: The Windows technique does not try to send the JSON report if the module returns nor success nor repaired
    (https://issues.rudder.io/issues/28952[#28952])
* Fixed: Fix upmerge of 28886
    (https://issues.rudder.io/issues/28894[#28894])
* Fixed: The filter on campaign status don't work if we don't click on "load more"
    (https://issues.rudder.io/issues/28858[#28858])
* Fixed: Search bar in update campaigns doesn't work
    (https://issues.rudder.io/issues/28093[#28093])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-9.1.1-1.18 (2026-05-04)

=== Changes


==== Miscellaneous

* The campaign configuration page should display the estimated duration of the campaign in a realtime
    (https://issues.rudder.io/issues/28287[#28287])

=== Bug fixes

==== Miscellaneous

* Fixed: don't use MD5 for computation of hashes in system update campaign time computation
    (https://issues.rudder.io/issues/23236[#23236])
* Fixed: Sorting does not work on the packages tab of software update campaigns
    (https://issues.rudder.io/issues/28454[#28454])
* Fixed: When we select a timezone in a campaign, the timezone is not used in the schedule summary
    (https://issues.rudder.io/issues/27698[#27698])
* Fixed: The "arch" attribute of software/system package updates cannot be modified from the interface
    (https://issues.rudder.io/issues/28472[#28472])
* Fixed: Fix capitalization
    (https://issues.rudder.io/issues/28630[#28630])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-9.1.0-1.18 (2026-04-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-9.1.0.rc1-1.18 (2026-04-10)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: error when accessing system updates page when we don't have admin right
    (https://issues.rudder.io/issues/28648[#28648])
* Fixed: When viewing the list of package updates on a given node after an update campaign, the "Export to CSV" button doesn't work
    (https://issues.rudder.io/issues/28534[#28534])
* Fixed: Is is not possible to change end time of a patch campaign beyond the timezone delay
    (https://issues.rudder.io/issues/28136[#28136])
* Fixed: Typo in the path of the new excludes file
    (https://issues.rudder.io/issues/28539[#28539])
* Fixed: Package excludes on incompatible versions fail to report an error
    (https://issues.rudder.io/issues/28537[#28537])
* Fixed: It is possible to add software packages with empty name
    (https://issues.rudder.io/issues/28423[#28423])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-9.1.0.beta1-1.18 (2026-03-10)

=== Changes


==== Miscellaneous

* Remove the python fallback
    (https://issues.rudder.io/issues/28495[#28495])
* Add exclusion support to Linux system updates technique
    (https://issues.rudder.io/issues/28492[#28492])
* Add a new "Packages to exclude" tab in every campaign (software or system) configuration page
    (https://issues.rudder.io/issues/28286[#28286])
* Export benchmark parameters to CSV
    (https://issues.rudder.io/issues/28051[#28051])
* Plugin license check should check instance id
    (https://issues.rudder.io/issues/28274[#28274])
* Bump rudder-elm-library version to 0.2.3
    (https://issues.rudder.io/issues/28221[#28221])

=== Bug fixes

==== Miscellaneous

* Fixed: Add the "excludes" feature to the Windows technique
    (https://issues.rudder.io/issues/28335[#28335])
* Fixed: Campaign filter do not applies filter for events in failure state
    (https://issues.rudder.io/issues/27527[#27527])
* Fixed: The campaign event result page per node is missing the node UUID
    (https://issues.rudder.io/issues/28284[#28284])
* Fixed: Deletion of campaign popup has a cropped popup
    (https://issues.rudder.io/issues/28349[#28349])
* Fixed: Make the windows technique use the 9.1 module instead of legacy powershell code if available
    (https://issues.rudder.io/issues/28267[#28267])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-9.1.0.alpha1-1.18 (2026-01-26)

=== Changes


==== Miscellaneous

* Export packages of campaign result on a node to CSV
    (https://issues.rudder.io/issues/27903[#27903])

==== Web - UI & UX

* Add filter for groups in system updates page
    (https://issues.rudder.io/issues/27985[#27985])

=== Bug fixes

==== Miscellaneous

* Fixed: Campaigns in failure state still show that no nodes are impacted
    (https://issues.rudder.io/issues/27769[#27769])

==== Refactoring

* Fixed: Missing spotless on scala 3 extension method
    (https://issues.rudder.io/issues/28092[#28092])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

