= Changelogs for Rudder plugin system-updates 9.1.\* versions

== system-updates-9.1.0.beta1-1.18 (2026-03-10)

=== Changes


==== Miscellaneous

* Remove the python fallback
    (https://issues.rudder.io/issues/28495[#28495])
* Add exclusion support to Linux system updates technique
    (https://issues.rudder.io/issues/28492[#28492])
* Add a new "Packages to exclude" tab in every campaign (software or system) configuration page
    (https://issues.rudder.io/issues/28286[#28286])
* Export benchmark parameters to CSV
    (https://issues.rudder.io/issues/28051[#28051])
* Plugin license check should check instance id
    (https://issues.rudder.io/issues/28274[#28274])
* Bump rudder-elm-library version to 0.2.3
    (https://issues.rudder.io/issues/28221[#28221])

=== Bug fixes

==== Miscellaneous

* Fixed: Add the "excludes" feature to the Windows technique
    (https://issues.rudder.io/issues/28335[#28335])
* Fixed: Campaign filter do not applies filter for events in failure state
    (https://issues.rudder.io/issues/27527[#27527])
* Fixed: The campaign event result page per node is missing the node UUID
    (https://issues.rudder.io/issues/28284[#28284])
* Fixed: Deletion of campaign popup has a cropped popup
    (https://issues.rudder.io/issues/28349[#28349])
* Fixed: Make the windows technique use the 9.1 module instead of legacy powershell code if available
    (https://issues.rudder.io/issues/28267[#28267])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-9.1.0.alpha1-1.18 (2026-01-26)

=== Changes


==== Miscellaneous

* Export packages of campaign result on a node to CSV
    (https://issues.rudder.io/issues/27903[#27903])

==== Web - UI & UX

* Add filter for groups in system updates page
    (https://issues.rudder.io/issues/27985[#27985])

=== Bug fixes

==== Miscellaneous

* Fixed: Campaigns in failure state still show that no nodes are impacted
    (https://issues.rudder.io/issues/27769[#27769])

==== Refactoring

* Fixed: Missing spotless on scala 3 extension method
    (https://issues.rudder.io/issues/28092[#28092])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

