= Change logs for Rudder 7.3

==  Rudder 7.3.1 (2023-05-04)

=== Changes


==== Documentation

* Add documentation about optional anonymous data collection
    (https://issues.rudder.io/issues/22673[#22673])
* Add install docs for Amazon Linux 2023
    (https://issues.rudder.io/issues/22628[#22628])

==== CI

* Notify different channel for security dependency check
    (https://issues.rudder.io/issues/22687[#22687])

==== Web - Nodes & inventories

* Display sha256 key hash in node details
    (https://issues.rudder.io/issues/22633[#22633])

=== Bug fixes

==== Packaging

* Fixed: Rudder agent force a lot of dependencies on RHEL9 
    (https://issues.rudder.io/issues/22610[#22610])

==== Miscellaneous

* Fixed: Ignore CVE 2023-20860 
    (https://issues.rudder.io/issues/22708[#22708])
* Fixed: Missing "latest" in archive API tests leads to error with upmerge
    (https://issues.rudder.io/issues/22636[#22636])

==== Security

* Fixed: Vulnerability in decode-uri-component
    (https://issues.rudder.io/issues/22707[#22707])
* Fixed: Ignore RUSTSEC-2023-0034 in relayd
    (https://issues.rudder.io/issues/22706[#22706])
* Fixed: upgrade postgresql drive for CVE CVE-2022-41946
    (https://issues.rudder.io/issues/22637[#22637])
* Fixed: Stackoverflow if {} used in place of [] for properties in node create api
    (https://issues.rudder.io/issues/22617[#22617])

==== Web - Campaigns

* Fixed: We should initialize campaign service after plugin were added or else current events will be skipped (before being added again)
    (https://issues.rudder.io/issues/22646[#22646])

==== Architecture - Internal libs

* Fixed: A deadlock can occur at boot (also a cause of slow initialization)
    (https://issues.rudder.io/issues/22645[#22645])

==== Web - UI & UX

* Fixed: It's hard to understand which authentication backend failed when a fallback happens
    (https://issues.rudder.io/issues/20396[#20396])
* Fixed: There are unused css classes due to wrong css class name
    (https://issues.rudder.io/issues/22669[#22669])
* Fixed:  Pending nodes History Tab shows duplicate entries
    (https://issues.rudder.io/issues/19258[#19258])
* Fixed: Remove AdminLTE script from login page
    (https://issues.rudder.io/issues/22644[#22644])
* Fixed:  Tooltip on enforce/audit label in rules title not working
    (https://issues.rudder.io/issues/20788[#20788])
* Fixed: rules/directives/cancel button doesn't work
    (https://issues.rudder.io/issues/22517[#22517])

==== Documentation

* Fixed: Fix typos in system-updates api doc
    (https://issues.rudder.io/issues/22667[#22667])
* Fixed: Relay API documentation is quite hard to find
    (https://issues.rudder.io/issues/22648[#22648])
* Fixed: Update screenshot of the dashboard
    (https://issues.rudder.io/issues/22634[#22634])

==== Web - Maintenance

* Fixed: JGitInternalError on HistorizeNodeCountService
    (https://issues.rudder.io/issues/22616[#22616])

==== Architecture - Dependencies

* Fixed: Update spring to 5.3.27 and spring-security 5.7.8
    (https://issues.rudder.io/issues/22668[#22668])

==== Relay server or API

* Fixed: Broken shared-files cleanup when file id contains a dot
    (https://issues.rudder.io/issues/22652[#22652])

==== System integration

* Fixed: Log in hook should got to /var/log and not /tmp
    (https://issues.rudder.io/issues/22649[#22649])

==== Web - Config management

* Fixed: Error log at boot: Can not find active technique with id 'test_import_export_archive}'
    (https://issues.rudder.io/issues/22614[#22614])

==== Web - Technique editor

* Fixed: In technique editor, technique with missing generic method need a warning icon
    (https://issues.rudder.io/issues/12282[#12282])

==== System techniques

* Fixed: Always send start/end reports even in changes-only mode
    (https://issues.rudder.io/issues/22655[#22655])

==== Agent

* Fixed: Allow skipping reporting when it is disabled
    (https://issues.rudder.io/issues/22653[#22653])

==== Generic methods

* Fixed: Augeas set method does not correctly handle successive calls
    (https://issues.rudder.io/issues/22677[#22677])
* Fixed: report_if_condition report contain twice "was correct"
    (https://issues.rudder.io/issues/22665[#22665])
* Fixed: Missleading use of parameter variable_name in method condition_from_variable_match
    (https://issues.rudder.io/issues/22620[#22620])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Lars Koenen

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.0 (2023-04-07)

=== Changes


==== Packaging

* Add amazon linux to support to specfiles
    (https://issues.rudder.io/issues/22578[#22578])

==== Documentation

* Document 7.3 windows specific changes
    (https://issues.rudder.io/issues/22613[#22613])
* Arch doc for frontend security
    (https://issues.rudder.io/issues/22512[#22512])
* Update network security arch doc for 7.3 and migration cases
    (https://issues.rudder.io/issues/22505[#22505])
* Update network security arch doc for 7.3 and migration cases
    (https://issues.rudder.io/issues/22505[#22505])
* Update network security arch doc for 7.3 and migration cases
    (https://issues.rudder.io/issues/22505[#22505])

==== Web - Nodes & inventories

* Add tests for linux inventory signature with certificate
    (https://issues.rudder.io/issues/22528[#22528])

==== rudderc

* Render methods docs as html
    (https://issues.rudder.io/issues/22538[#22538])
* Add a JSON schema validation
    (https://issues.rudder.io/issues/22489[#22489])

==== Web - Config management

* Persisted rule should have sorted groups/directives
    (https://issues.rudder.io/issues/18215[#18215])

==== Techniques

* Deprecate System update technique
    (https://issues.rudder.io/issues/22611[#22611])

==== Generic methods

* Explain flag mechanisme for "once" method
    (https://issues.rudder.io/issues/22596[#22596])

=== Bug fixes

==== Packaging

* Fixed: missing dependencies on amazon linux server
    (https://issues.rudder.io/issues/22615[#22615])
* Fixed: rudder-init replaces rudder-db password at postinst
    (https://issues.rudder.io/issues/22608[#22608])
* Fixed: Amazon linux doesn't provide postgresql-server
    (https://issues.rudder.io/issues/22593[#22593])
* Fixed: rudder-server-postinst fails to update rudder-web.properties
    (https://issues.rudder.io/issues/22495[#22495])
* Fixed: Error when installing Rudder 6.2.13 on almalinux 8
    (https://issues.rudder.io/issues/21252[#21252])

==== Agent

* Fixed: rudder-sign says "hostname: command not found"
    (https://issues.rudder.io/issues/22452[#22452])
* Fixed: Connection timeout to server are too long
    (https://issues.rudder.io/issues/22540[#22540])

==== Server components

* Fixed: "reportid" missing in PostgreSQL database after upgrade from v6.2.12 to v7.2.3
    (https://issues.rudder.io/issues/22315[#22315])

==== Documentation

* Fixed: Update doc for 7.3
    (https://issues.rudder.io/issues/22607[#22607])
* Fixed: Add rudder agent verbose command in windows install 
    (https://issues.rudder.io/issues/22598[#22598])
* Fixed: Typo in windows msiexec command in documentation
    (https://issues.rudder.io/issues/22554[#22554])
* Fixed: Problem in Server backup and migration documentation
    (https://issues.rudder.io/issues/22313[#22313])
* Fixed: Typo in windows install documentation
    (https://issues.rudder.io/issues/22558[#22558])
* Fixed: Provide info to user about java-openjdk11-headless alternatives for AL2
    (https://issues.rudder.io/issues/22499[#22499])
* Fixed: Broken doc build after plugins doc change
    (https://issues.rudder.io/issues/22490[#22490])
* Fixed: document in the getting started that virtualbox needs a list of authorized IP
    (https://issues.rudder.io/issues/21485[#21485])
* Fixed: API Documentation errors for trigger agent run
    (https://issues.rudder.io/issues/22565[#22565])
* Fixed: Improve introduction of relay arch docs
    (https://issues.rudder.io/issues/22509[#22509])

==== Web - UI & UX

* Fixed: when we save a rule category, the button save never stops saving
    (https://issues.rudder.io/issues/22524[#22524])
* Fixed: there is a space before all texts in the node details page, so copy and paste include it
    (https://issues.rudder.io/issues/21417[#21417])
* Fixed: System group preview description are not displayed
    (https://issues.rudder.io/issues/18583[#18583])
* Fixed: Rule list doesn't appear anymore in a rule category
    (https://issues.rudder.io/issues/22103[#22103])
* Fixed: When shared folder file list is too long the selector fail
    (https://issues.rudder.io/issues/22110[#22110])
* Fixed: Change name parameter "Rudder ID" for group id
    (https://issues.rudder.io/issues/22581[#22581])
* Fixed: Technique ID and group ID are juste listed as "ID" in the UI when other IDs are listed with their long name
    (https://issues.rudder.io/issues/21369[#21369])
* Fixed: Rule is in mixed mode even though she has only one directive in audit
    (https://issues.rudder.io/issues/21731[#21731])
* Fixed: Shadow overlapping on first menu entry
    (https://issues.rudder.io/issues/21683[#21683])
* Fixed: Missing tooltip on unused directives icon
    (https://issues.rudder.io/issues/22428[#22428])

==== Web - Maintenance

* Fixed: password=LDAP produces error logs in webapp
    (https://issues.rudder.io/issues/21978[#21978])

==== Web - Compliance & node report

* Fixed: General improvements on Directive compliance API
    (https://issues.rudder.io/issues/22552[#22552])
* Fixed: HTML tag in compliance hover
    (https://issues.rudder.io/issues/22560[#22560])
* Fixed: Sorting by Compliance doesn't sort in the rule details
    (https://issues.rudder.io/issues/21182[#21182])

==== API

* Fixed: List Managed Nodes API with any of the fields listed in the "full" never answer
    (https://issues.rudder.io/issues/22534[#22534])

==== Security

* Fixed: Update spring-core to 5.3.26
    (https://issues.rudder.io/issues/22586[#22586])
* Fixed: Allow iframes from the same origin
    (https://issues.rudder.io/issues/22522[#22522])
* Fixed: Update openssl crate to fix several vulnerabilities
    (https://issues.rudder.io/issues/22532[#22532])

==== Techniques

* Fixed: Mustache template is not capable to render technique parameters
    (https://issues.rudder.io/issues/22535[#22535])

==== rudderc

* Fixed: Allow BSD-2-Clause licences
    (https://issues.rudder.io/issues/22543[#22543])
* Fixed: Fix escaping in rudderc
    (https://issues.rudder.io/issues/22468[#22468])

==== Web - Config management

* Fixed: Policy generation broken when defining a group with invert result of inclusion of another group
    (https://issues.rudder.io/issues/21924[#21924])
* Fixed: Directive detail is really slow to load in 7.3
    (https://issues.rudder.io/issues/22392[#22392])

==== Web - Technique editor

* Fixed: There is one more minus in deleted resources counter within technique editor
    (https://issues.rudder.io/issues/22475[#22475])

==== Web - Nodes & inventories

* Fixed: On "Node search" page, we can click on "Create node group from this query" even if there were no query
    (https://issues.rudder.io/issues/19986[#19986])

==== System integration

* Fixed: server-create-user uses old role attribte in place of new permissions one
    (https://issues.rudder.io/issues/22498[#22498])
* Fixed: Parent fix does not work: Fusioninventory is not tracked by check-rudder-health
    (https://issues.rudder.io/issues/11102[#11102])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Lars Koenen

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.0.rc1 (2023-03-17)

=== Changes


==== Agent

* Remove the fallback on "rudder" host when no policy server is configued
    (https://issues.rudder.io/issues/22407[#22407])

==== Documentation

* Add bcrypt param doc in main doc
    (https://issues.rudder.io/issues/22429[#22429])
* Prepare 7.3 doc
    (https://issues.rudder.io/issues/22368[#22368])
* Prepare 7.3 doc
    (https://issues.rudder.io/issues/22368[#22368])
* Prepare 7.3 doc
    (https://issues.rudder.io/issues/22368[#22368])
* Add missing documentation for CVE API
    (https://issues.rudder.io/issues/22446[#22446])
* Add missing documentation for CVE API
    (https://issues.rudder.io/issues/22446[#22446])

==== Web - UI & UX

* Edit properties is not intuitive
    (https://issues.rudder.io/issues/21918[#21918])
* Missing a loading info when a technique it is being saved
    (https://issues.rudder.io/issues/21929[#21929])

==== API

* Remove usage of redoc-cli which is deprecated
    (https://issues.rudder.io/issues/22447[#22447])

==== System integration

* Make specs2 test console output more detailed
    (https://issues.rudder.io/issues/22419[#22419])

==== Architecture - Internal libs

* Fix version maven-resources-plugin to 3.1.0, instead of relying on maven default version
    (https://issues.rudder.io/issues/22403[#22403])

==== Performance and scalability

* Make parsing "process" in inventory optional
    (https://issues.rudder.io/issues/22359[#22359])

==== Web - Config management

* Avoid sync group when importing a rule archive
    (https://issues.rudder.io/issues/22333[#22333])

==== Security

* Allow iframes from the same origin
    (https://issues.rudder.io/issues/22374[#22374])

=== Bug fixes

==== System integration

* Fixed: Rudder-jetty timeout is the systemd default one and may be short
    (https://issues.rudder.io/issues/22377[#22377])

==== Packaging

* Fixed: Cleanup prerm scripts
    (https://issues.rudder.io/issues/22203[#22203])

==== Documentation

* Fixed: Bad documentation leads to package build failing when building for armhf
    (https://issues.rudder.io/issues/17868[#17868])
* Fixed: doc about configuring repositories on debian is confusing for the rudder server
    (https://issues.rudder.io/issues/22396[#22396])
* Fixed: Remove outdated stuff about the technique editor
    (https://issues.rudder.io/issues/22420[#22420])
* Fixed: Broken link to rudder-announce ML
    (https://issues.rudder.io/issues/22416[#22416])
* Fixed: versions in Rudder doc are invalid
    (https://issues.rudder.io/issues/21750[#21750])
* Fixed: List of authentication backend is invalid in the documentation (includes Radius)
    (https://issues.rudder.io/issues/22406[#22406])
* Fixed: Backport hardening guide to 7.2
    (https://issues.rudder.io/issues/22405[#22405])
* Fixed: Hardening guide for Rudder
    (https://issues.rudder.io/issues/21877[#21877])
* Fixed: documentation about default login/password is invalid
    (https://issues.rudder.io/issues/22367[#22367])
* Fixed: documentation about default login/password is invalid
    (https://issues.rudder.io/issues/22367[#22367])
* Fixed: network requirement in documentation are invalid
    (https://issues.rudder.io/issues/22366[#22366])
* Fixed: Inconsistency in API doc for allowed network
    (https://issues.rudder.io/issues/22467[#22467])

==== Web - UI & UX

* Fixed: typo about licensed plugin
    (https://issues.rudder.io/issues/22463[#22463])
* Fixed: Empty dashboard doesn't look good
    (https://issues.rudder.io/issues/21255[#21255])
* Fixed: Add an animation when the rules table loads
    (https://issues.rudder.io/issues/22449[#22449])
* Fixed: Show all in technical details table doesn't work
    (https://issues.rudder.io/issues/22107[#22107])
* Fixed: Plugins-repository URL from plugins pages redirect to home page
    (https://issues.rudder.io/issues/21346[#21346])

==== Web - Maintenance

* Fixed: Update rudder-user.xml to use permissions in place of roles attribute
    (https://issues.rudder.io/issues/22457[#22457])

==== API

* Fixed: Invalid openapi definition
    (https://issues.rudder.io/issues/20629[#20629])
* Fixed: Directive compliance API version is 10 in place of 17
    (https://issues.rudder.io/issues/22435[#22435])

==== Web - Nodes & inventories

* Fixed: Inventory error when missing tag POLICY_SERVER_UUID talk about POLICY_SERVER
    (https://issues.rudder.io/issues/22453[#22453])
* Fixed: Add Raspbian to the list of recognized OS
    (https://issues.rudder.io/issues/22345[#22345])

==== Security

* Fixed: RUSTSEC-2023-0018  in remove_dir_all
    (https://issues.rudder.io/issues/22432[#22432])
* Fixed: RUSTSEC-2023-0018  in remove_dir_all
    (https://issues.rudder.io/issues/22432[#22432])
* Fixed: RUSTSEC-2023-0018  in remove_dir_all
    (https://issues.rudder.io/issues/22432[#22432])
* Fixed: RUSTSEC-2023-0018  in remove_dir_all
    (https://issues.rudder.io/issues/22432[#22432])

==== Miscellaneous

* Fixed: Update commons fileupload dependency to prevent CVE-2023-24998
    (https://issues.rudder.io/issues/22433[#22433])
* Fixed: Healthcheck on file descriptor should be max 64000
    (https://issues.rudder.io/issues/22430[#22430])

==== Architecture - Refactoring

* Fixed: Remove pattern matching warning 
    (https://issues.rudder.io/issues/22424[#22424])

==== Web - Compliance & node report

* Fixed: missing report in change only
    (https://issues.rudder.io/issues/22371[#22371])
* Fixed: Nodes not answering are seen in "missing" rather than in "no reports"
    (https://issues.rudder.io/issues/22375[#22375])
* Fixed: Refactor Directive compliance to handle blocks
    (https://issues.rudder.io/issues/22376[#22376])

==== Web - Config management

* Fixed: Generate policies for campaigns before it starts officially, delete them after it stops (1 hour delay each)
    (https://issues.rudder.io/issues/22378[#22378])
* Fixed: User should be able to accept change request even with divergences
    (https://issues.rudder.io/issues/22363[#22363])

==== Relay server or API

* Fixed: File from shared folder method does not support special characters in the source path
    (https://issues.rudder.io/issues/20834[#20834])

==== System techniques

* Fixed: A 6.2 relay cannot talk to a 7.2 server through HTTPS
    (https://issues.rudder.io/issues/22402[#22402])
* Fixed: Changes only does not support campaign reports 
    (https://issues.rudder.io/issues/22240[#22240])

==== Generic methods

* Fixed: file key value parameter in list accepts entries without separator
    (https://issues.rudder.io/issues/22322[#22322])
* Fixed: Descriptin of permissions dirs recursive is misleading
    (https://issues.rudder.io/issues/17122[#17122])

==== Agent

* Fixed: "Using the default value 'true' for attribute rxdirs" waning in agent run output
    (https://issues.rudder.io/issues/22393[#22393])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Nicolas Ecarnot
* Alexis TARUSSIO

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.0.beta1 (2023-02-09)

=== Changes


==== Packaging

* Remove useless configure flags from openldap
    (https://issues.rudder.io/issues/22265[#22265])
* Remove readline library from aix package
    (https://issues.rudder.io/issues/22234[#22234])
* Add zip as a server dependency
    (https://issues.rudder.io/issues/22116[#22116])
* Update server dependencies for 7.3
    (https://issues.rudder.io/issues/22070[#22070])
* Update agent dependencies
    (https://issues.rudder.io/issues/22071[#22071])
* Update to CFEngine 3.18.3
    (https://issues.rudder.io/issues/22068[#22068])
* Update the toml crate to 0.6
    (https://issues.rudder.io/issues/22300[#22300])
* Build frontend files with gulp
    (https://issues.rudder.io/issues/22094[#22094])
* Use a lock file for api doc build dependencies
    (https://issues.rudder.io/issues/22136[#22136])
* Use npm for managing js dependencies
    (https://issues.rudder.io/issues/22081[#22081])

==== Documentation

* Update windows agent installation documentation
    (https://issues.rudder.io/issues/22330[#22330])
* Remove 6.2 and 7.0 from doc menu
    (https://issues.rudder.io/issues/22031[#22031])
* Use docsearch v3 for search integration
    (https://issues.rudder.io/issues/21989[#21989])
* Start docs for new technique yaml format
    (https://issues.rudder.io/issues/21961[#21961])

==== System integration

* Allow user to define custom roles in rudder-user.xml
    (https://issues.rudder.io/issues/22206[#22206])

==== Security

* Update to Rust 1.66.1
    (https://issues.rudder.io/issues/22293[#22293])
* Improve npm audit
    (https://issues.rudder.io/issues/22217[#22217])
* Add security headers in Lift config
    (https://issues.rudder.io/issues/21795[#21795])

==== rudderc

* Windows policy generation
    (https://issues.rudder.io/issues/22239[#22239])
* Add a first hardening technique draft
    (https://issues.rudder.io/issues/22268[#22268])
* Make rudderc techniques work in edge cases
    (https://issues.rudder.io/issues/22179[#22179])
* Tags entry in yaml technique
    (https://issues.rudder.io/issues/22156[#22156])
* Don't require resources to be listed in yaml technique
    (https://issues.rudder.io/issues/22147[#22147])
* Rename resources in rudderc
    (https://issues.rudder.io/issues/22142[#22142])
* Generate a proper metadata.xml
    (https://issues.rudder.io/issues/22054[#22054])
* Remove rudder-lang code
    (https://issues.rudder.io/issues/22040[#22040])
*  Use resource type information in rudderc
    (https://issues.rudder.io/issues/21308[#21308])

==== Web - UI & UX

* Use npm to maintain jqueryui
    (https://issues.rudder.io/issues/22244[#22244])
* Update elm dependencies
    (https://issues.rudder.io/issues/22051[#22051])

==== API

* API for directive compliance
    (https://issues.rudder.io/issues/22150[#22150])

==== Miscellaneous

* Make authorization and rights pluggable
    (https://issues.rudder.io/issues/22198[#22198])

==== Architecture - Dependencies

* Update scala dependencies to latest version
    (https://issues.rudder.io/issues/22049[#22049])
* Port code to ZIO2
    (https://issues.rudder.io/issues/21825[#21825])

==== CI

* Update Rust for 7.3
    (https://issues.rudder.io/issues/21875[#21875])

==== Web - Maintenance

* Cleanup rudder-lang settings
    (https://issues.rudder.io/issues/21866[#21866])

==== System techniques

* Disable agent syslog logging by default
    (https://issues.rudder.io/issues/21970[#21970])

==== Agent

* Cleanup remote run command for relay
    (https://issues.rudder.io/issues/22231[#22231])

==== Generic methods

* Add agent support metadata
    (https://issues.rudder.io/issues/21939[#21939])

=== Bug fixes

==== Packaging

* Fixed: Remove git from build dependencies of rudder-server
    (https://issues.rudder.io/issues/22356[#22356])
* Fixed: patch fusioninventory to detect correctly rockylinux
    (https://issues.rudder.io/issues/22334[#22334])
* Fixed: Remove message of cfengine trying to load enterprise module
    (https://issues.rudder.io/issues/22236[#22236])
* Fixed: readline fails to build on aix
    (https://issues.rudder.io/issues/22228[#22228])
* Fixed: Dev version of perl used
    (https://issues.rudder.io/issues/22215[#22215])
* Fixed: Add content in rudder's robots.txt
    (https://issues.rudder.io/issues/21798[#21798])

==== Web - UI & UX

* Fixed: Redirect / to /rudder/secure to avoid login form if already connected
    (https://issues.rudder.io/issues/21807[#21807])
* Fixed: Remove useless headers
    (https://issues.rudder.io/issues/21797[#21797])
* Fixed: Update outdated npm packages
    (https://issues.rudder.io/issues/22336[#22336])
* Fixed: Directive creation process is counter intuitive in 7.3.0~alpha
    (https://issues.rudder.io/issues/22254[#22254])
* Fixed: Display of Target Rules is broken
    (https://issues.rudder.io/issues/22305[#22305])
* Fixed: Use npm to maintain gauge.js
    (https://issues.rudder.io/issues/22270[#22270])
* Fixed: Use npm to maintain angularJS
    (https://issues.rudder.io/issues/22252[#22252])
* Fixed: Top menu bar display is broken
    (https://issues.rudder.io/issues/22245[#22245])
* Fixed: Remove AdminLTE theme
    (https://issues.rudder.io/issues/22204[#22204])
* Fixed: Transform tabs of the directives into real tabs
    (https://issues.rudder.io/issues/22086[#22086])
* Fixed: Dont redirect other tabs to login form when session cookie is replaced
    (https://issues.rudder.io/issues/21808[#21808])
* Fixed: Impossible to move groups
    (https://issues.rudder.io/issues/21755[#21755])

==== Documentation

* Fixed: Wrong Table name inside documentation
    (https://issues.rudder.io/issues/22128[#22128])
* Fixed: Remove beta header from 7.2 docs
    (https://issues.rudder.io/issues/21879[#21879])

==== Security

* Fixed: Ignore CVE-2023-22895 in relayd
    (https://issues.rudder.io/issues/22354[#22354])
* Fixed: Update the embedded openssl to 1.1.1t
    (https://issues.rudder.io/issues/22351[#22351])
* Fixed: Ignore DoS in npm dependencies
    (https://issues.rudder.io/issues/22324[#22324])
* Fixed: Ignore RUSTSEC-2022-0082
    (https://issues.rudder.io/issues/22328[#22328])
* Fixed: Fix npm security alerts
    (https://issues.rudder.io/issues/22307[#22307])
* Fixed: Rudder sessions never expire when the browser stays connected
    (https://issues.rudder.io/issues/21806[#21806])
* Fixed: Stop using UUIDs as system token
    (https://issues.rudder.io/issues/21669[#21669])

==== Web - Campaigns

* Fixed: New filters on campaign queries to get several campaign types in one request
    (https://issues.rudder.io/issues/22346[#22346])

==== Web - Nodes & inventories

* Fixed: some nodes are called "localhost" since #8022
    (https://issues.rudder.io/issues/22326[#22326])

==== Web - Config management

* Fixed: Hook timeout may not have the good value
    (https://issues.rudder.io/issues/22339[#22339])

==== API

* Fixed: Cannot list directives with API
    (https://issues.rudder.io/issues/22314[#22314])

==== rudderc

* Fixed: Various metadata.xml fixes
    (https://issues.rudder.io/issues/22153[#22153])

==== CI

* Fixed: Add authorized license Unicode-DFS-2016 in relayd
    (https://issues.rudder.io/issues/21914[#21914])

==== Server components

* Fixed: All rudder commands using the API don't detect the port of the webapp when we configure a virtualhost with a different port
    (https://issues.rudder.io/issues/21216[#21216])

==== Generic methods

* Fixed: Remove ncf scripts
    (https://issues.rudder.io/issues/21950[#21950])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Alexis TARUSSIO

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

