= Change logs for Rudder 7.3

==  Rudder 7.3.13 (2024-03-11)

=== Changes


=== Bug fixes

==== Documentation

* Fixed: Documentation on Windows installation misses the dependency on dsc plugin on the rudder server
    (https://issues.rudder.io/issues/24229[#24229])

==== Architecture - Internal libs

* Fixed: windows Node in tests has invalid  certificate, failing test in plugin windows
    (https://issues.rudder.io/issues/24289[#24289])

==== API

* Fixed: Merge user-management feature branch to 7.3
    (https://issues.rudder.io/issues/24342[#24342])
* Fixed: Empty role in users file is logged as warning
    (https://issues.rudder.io/issues/24285[#24285])

==== CI

* Fixed: Adapt Jenkinsfile after warning-ng plugin upgrade
    (https://issues.rudder.io/issues/24301[#24301])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.12 (2024-02-29)

=== Changes


==== Architecture - Code maintenance

* Prepare migration to Scala 3 - Version 7.3 part 1
    (https://issues.rudder.io/issues/24171[#24171])

=== Bug fixes

==== Packaging

* Fixed: Rudder upgrade may fail on postgres script
    (https://issues.rudder.io/issues/24232[#24232])

==== Miscellaneous

* Fixed: Incorrect error message about change request creation failure when it is not needed
    (https://issues.rudder.io/issues/24278[#24278])

==== Plugin manager cli

* Fixed: Pylint test fails with an exception
    (https://issues.rudder.io/issues/24205[#24205])

==== Architecture - Code maintenance

* Fixed: Make spotless only check source of current project
    (https://issues.rudder.io/issues/24177[#24177])

==== Web - Config management

* Fixed: We must not generate policies for nodes without a well formed certificate
    (https://issues.rudder.io/issues/24112[#24112])

==== Web - Maintenance

* Fixed: Archiving allows to read inconsistent active technique category ids 
    (https://issues.rudder.io/issues/24011[#24011])

==== API

* Fixed: Bad description for serialNumber attribute of machine
    (https://issues.rudder.io/issues/24141[#24141])
* Fixed: For delete API for node, add a message for node already deleted
    (https://issues.rudder.io/issues/24129[#24129])

==== Web - Technique editor

* Fixed: Action dropdown list in technique editor goes under parameters
    (https://issues.rudder.io/issues/24122[#24122])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.11 (2024-02-02)

=== Changes


==== Agent

* We should log an error when a hook timeouts
    (https://issues.rudder.io/issues/23936[#23936])

==== API

* Add manufacturer field in create node API
    (https://issues.rudder.io/issues/24091[#24091])

==== Web - UI & UX

* Display the list of pending change requests related to the selected rule
    (https://issues.rudder.io/issues/21931[#21931])

==== Architecture - Code maintenance

* Remove early return to prepare to Scala3 migration in box sequence/traverse
    (https://issues.rudder.io/issues/23948[#23948])

=== Bug fixes

==== Packaging

* Fixed: RHEL9 policies have an incompatible sh shebang
    (https://issues.rudder.io/issues/24057[#24057])
* Fixed: Embed openssl cli on 7.3
    (https://issues.rudder.io/issues/24019[#24019])
* Fixed: Abort server build if rudder.war is less than 1Mb
    (https://issues.rudder.io/issues/23958[#23958])

==== Documentation

* Fixed: Fixed ref in documentation for centralized page
    (https://issues.rudder.io/issues/23917[#23917])
* Fixed: Debian source list should force architecture
    (https://issues.rudder.io/issues/23731[#23731])
* Fixed: case-sensitivity parameter of rudder-user.xml is not documented
    (https://issues.rudder.io/issues/24024[#24024])

==== Web - UI & UX

* Fixed: Fix small ui error in the rules information tab
    (https://issues.rudder.io/issues/24079[#24079])
* Fixed: New campaigns button does not conform to our graphic charter
    (https://issues.rudder.io/issues/23938[#23938])
* Fixed: A new group display no nodes while all linux are selected
    (https://issues.rudder.io/issues/22170[#22170])
* Fixed: The health check page has an unnecessary "Show check list" button
    (https://issues.rudder.io/issues/23891[#23891])
* Fixed: The "Category" field in the technique editor is displayed as a mandatory field even if it is an unmutable one
    (https://issues.rudder.io/issues/23883[#23883])
* Fixed: Rename the "Create global property" button in "Create"
    (https://issues.rudder.io/issues/23878[#23878])

==== Security

* Fixed: Ignore cve on ext-js (unused dependency)
    (https://issues.rudder.io/issues/24071[#24071])
* Fixed: DoS vuln in h2 lib in relayd
    (https://issues.rudder.io/issues/24068[#24068])
* Fixed: Unaffected CVE on jgit and logback
    (https://issues.rudder.io/issues/23982[#23982])

==== API

* Fixed: If REST url ends with .com, then the .com is removed from path segments
    (https://issues.rudder.io/issues/24036[#24036])

==== Performance and scalability

* Fixed: Healthcheck on file descriptor should be max 64000
    (https://issues.rudder.io/issues/24006[#24006])

==== Web - Config management

* Fixed: Static group which depends on dynamic subgroup must be forbiden
    (https://issues.rudder.io/issues/18952[#18952])
* Fixed: Rudder agent scheduled runs are not triggered at regular interval
    (https://issues.rudder.io/issues/23956[#23956])

==== Server components

* Fixed: Waning log spam when disabled rudder_compute_changes setting
    (https://issues.rudder.io/issues/23969[#23969])

==== Web - Nodes & inventories

* Fixed: Missing icon for windows 2022
    (https://issues.rudder.io/issues/23972[#23972])
* Fixed: We can accept a node with an existing hostname even if node_accept_duplicated_hostname is false
    (https://issues.rudder.io/issues/22197[#22197])

==== Architecture - Internal libs

* Fixed: Plugin license implementation is not coherent with interface
    (https://issues.rudder.io/issues/23932[#23932])

==== Miscellaneous

* Fixed: Change request on special:all_nodes_without_role lead to error
    (https://issues.rudder.io/issues/23446[#23446])

==== Techniques

* Fixed: File content directive add 4 spaces at the beginning of the line 
    (https://issues.rudder.io/issues/24022[#24022])
* Fixed: FileTemplate technique fails with an error on the Directory-Create method call
    (https://issues.rudder.io/issues/23954[#23954])

==== Agent

* Fixed: Prompt warning and ask confirmation for factory reset
    (https://issues.rudder.io/issues/23978[#23978])
* Fixed: when a node has capitals in its hostname agent history doesn't show manual runs
    (https://issues.rudder.io/issues/23740[#23740])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Alexis TARUSSIO

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.10 (2023-12-14)

=== Changes


==== Packaging

* Upgrade curl to 8.5.0
    (https://issues.rudder.io/issues/23841[#23841])
* Update to OpenSSL 3.0 & CFEngine 3.21
    (https://issues.rudder.io/issues/23717[#23717])

=== Bug fixes

==== Agent

* Fixed: Backport fix for random process killing
    (https://issues.rudder.io/issues/23713[#23713])
* Fixed: Backport fix for random process killing
    (https://issues.rudder.io/issues/23713[#23713])

==== Web - Maintenance

* Fixed: Event log migration should not be done every time
    (https://issues.rudder.io/issues/23836[#23836])

==== Web - Nodes & inventories

* Fixed: Update the error message for failed inventory signature check
    (https://issues.rudder.io/issues/23827[#23827])

==== Web - UI & UX

* Fixed: Sometimes, tooltips in the directives tree remain displayed
    (https://issues.rudder.io/issues/23819[#23819])
* Fixed: Fix typos in error message in technique editor
    (https://issues.rudder.io/issues/23800[#23800])
* Fixed: In Technique Editor, the quicksearch window still  appears behind the navigation menu
    (https://issues.rudder.io/issues/23588[#23588])
* Fixed: Technique saving is blocked because of localstorage of drafts
    (https://issues.rudder.io/issues/23475[#23475])
* Fixed: Using deprecated chart.js options generates errors in the console
    (https://issues.rudder.io/issues/23747[#23747])

==== Web - Technique editor

* Fixed: Content of warning tooltip for unknow method should not overflow
    (https://issues.rudder.io/issues/23801[#23801])

==== rudderc

* Fixed: rudderc method parsing breaks when method contains several bundles
    (https://issues.rudder.io/issues/23798[#23798])

==== Web - Config management

* Fixed: Copy the certificates directly without calling the agent after generation
    (https://issues.rudder.io/issues/23783[#23783])

==== Miscellaneous

* Fixed: Compiler warnings should prevent build
    (https://issues.rudder.io/issues/23657[#23657])

==== Security

* Fixed: Unescape SQL in eventlog filter
    (https://issues.rudder.io/issues/23724[#23724])

==== Architecture - Code maintenance

* Fixed: Software DAO can lead to NoSuchElement exception
    (https://issues.rudder.io/issues/23701[#23701])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.9 (2023-11-07)

=== Changes


=== Bug fixes

==== Documentation

* Fixed: Install command with variable $releasever lead to error
    (https://issues.rudder.io/issues/22779[#22779])
* Fixed: Import key section in AIX agent install doc is empty
    (https://issues.rudder.io/issues/23312[#23312])

==== Web - Maintenance

* Fixed: Event log migration takes too long
    (https://issues.rudder.io/issues/23699[#23699])

==== API

* Fixed: rudder node api documentation doesn't mention the softwareUpdate
    (https://issues.rudder.io/issues/23441[#23441])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.8 (2023-10-30)

=== Changes


==== Packaging

* Update curl to 8.4.0
    (https://issues.rudder.io/issues/23559[#23559])

==== Web - UI & UX

* The "Required/May be empy" button in the parameters of a technique is not intuitive enough
    (https://issues.rudder.io/issues/23610[#23610])
* After creating a change request, give the user a redirection link to its details
    (https://issues.rudder.io/issues/23443[#23443])

==== API

* Lint shell code examples
    (https://issues.rudder.io/issues/23653[#23653])

==== Architecture - Internal libs

* Add a test on JDK21
    (https://issues.rudder.io/issues/23486[#23486])

=== Bug fixes

==== Packaging

* Fixed: Openssl embedded in too many OSes
    (https://issues.rudder.io/issues/23678[#23678])
* Fixed: Revert jetty upgrade to 10.0.17 for now
    (https://issues.rudder.io/issues/23648[#23648])
* Fixed: Ensure different cache when embedded various differences
    (https://issues.rudder.io/issues/23533[#23533])
* Fixed: Allow forcing embedding openssl in RPM packages
    (https://issues.rudder.io/issues/23516[#23516])
* Fixed: silent error when upgrading Rudder 8.0-nightly to 8.0-nightly on sles15sp4
    (https://issues.rudder.io/issues/23480[#23480])
* Fixed: tar is not an explicit dependency of the Rudder server
    (https://issues.rudder.io/issues/22930[#22930])
* Fixed: Dependency on rudder-api-client should be versioned
    (https://issues.rudder.io/issues/23449[#23449])

==== Agent

* Fixed: Agent uses hardcoded /bin/getent
    (https://issues.rudder.io/issues/23623[#23623])
* Fixed: Memory corruption when inheriting from bodies containing global variables
    (https://issues.rudder.io/issues/23478[#23478])
* Fixed: Function cache can return incorrect results
    (https://issues.rudder.io/issues/23437[#23437])
* Fixed: Don't try to send reports in initial policies
    (https://issues.rudder.io/issues/23531[#23531])

==== Security

* Fixed: Several low impact CVE in Jetty 10.0.12
    (https://issues.rudder.io/issues/23608[#23608])
* Fixed: Assessments of several low impact CVE in current 7.3.x reported by contrastsecurity tool 
    (https://issues.rudder.io/issues/23609[#23609])

==== Documentation

* Fixed: Broken links in docs hmepage
    (https://issues.rudder.io/issues/23643[#23643])
* Fixed: remove all "starting with version <old>" from docs
    (https://issues.rudder.io/issues/23628[#23628])
* Fixed: documentation tells to edit /opt/rudder/etc/rudder-pkg/rudder-pkg.conf to set credential
    (https://issues.rudder.io/issues/23398[#23398])

==== Web - UI & UX

* Fixed: The tooltip in the compliance bar does not appear when the mouse is hovered over it
    (https://issues.rudder.io/issues/23612[#23612])
* Fixed: When we are logged out, the logout button doesn't work
    (https://issues.rudder.io/issues/23010[#23010])
* Fixed: Search bar will not work with filters
    (https://issues.rudder.io/issues/23665[#23665])
* Fixed: In technique editor, the "Name" field appears to be optional, whereas it is not.
    (https://issues.rudder.io/issues/23611[#23611])
* Fixed: Recent changes drop down cannot be read
    (https://issues.rudder.io/issues/22518[#22518])
* Fixed: Search bar doesn't work for group properties
    (https://issues.rudder.io/issues/22516[#22516])
* Fixed: When we search by "is defined" in the group search, we get the previous search value displayed
    (https://issues.rudder.io/issues/16094[#16094])
* Fixed: Typo in warning message
    (https://issues.rudder.io/issues/23592[#23592])
* Fixed: Always display generic method name
    (https://issues.rudder.io/issues/23564[#23564])

==== Web - Nodes & inventories

* Fixed: On the nodes list, the filter does not work on property based column
    (https://issues.rudder.io/issues/23535[#23535])

==== Miscellaneous

* Fixed: Last modified attribute of change request is always "unknown"
    (https://issues.rudder.io/issues/19317[#19317])
* Fixed: PostgreSQL error doobie.util.invariant$UnexpectedEnd$ 
    (https://issues.rudder.io/issues/22527[#22527])

==== Web - Config management

* Fixed: Tag are not displayed with a nice diff in eventLog 
    (https://issues.rudder.io/issues/15019[#15019])
* Fixed: Quotes in group name generate JS errors when using GroupId criteria
    (https://issues.rudder.io/issues/23320[#23320])

==== Web - Technique editor

* Fixed: user with read_only right has button that allows to create a technique
    (https://issues.rudder.io/issues/17813[#17813])

==== Plugins integration

* Fixed: rudder package should not totally fail when parsing index if one entry
    (https://issues.rudder.io/issues/23524[#23524])

==== API

* Fixed: Add an enum for campaign type in post request doc
    (https://issues.rudder.io/issues/23501[#23501])

==== Web - Compliance & node report

* Fixed: Focus reporting is not working 
    (https://issues.rudder.io/issues/23466[#23466])

==== Generic methods

* Fixed: Condition_from_string_match fails to be executed multiple times with same inputs
    (https://issues.rudder.io/issues/23554[#23554])
* Fixed: schedule_generic breaks the agent run when the periodicity of a job is null
    (https://issues.rudder.io/issues/23540[#23540])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.7 (2023-09-19)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.6 (2023-09-15)

=== Changes


==== Web - UI & UX

* Add a placeholder description for groups page like for techniques and directives
    (https://issues.rudder.io/issues/23184[#23184])
* When drag'n drop, the selected method and the targeted drop zone should be more highlighted
    (https://issues.rudder.io/issues/23303[#23303])

==== Relay server or API

* Update embedded openssl to 3.1 in relayd
    (https://issues.rudder.io/issues/23383[#23383])

==== Web - Nodes & inventories

* When I enter the "Create a new item" popup to create a group the default field should be Name
    (https://issues.rudder.io/issues/2677[#2677])

==== Documentation

* Arch doc for policy update
    (https://issues.rudder.io/issues/22589[#22589])

=== Bug fixes

==== Packaging

* Fixed: Bump to openssl 1.1.1w
    (https://issues.rudder.io/issues/23410[#23410])
* Fixed: Server install fails with postgresql encoding error
    (https://issues.rudder.io/issues/23388[#23388])
* Fixed: Stop removing the openssl test folder
    (https://issues.rudder.io/issues/23355[#23355])
* Fixed: Don't build openssl tests
    (https://issues.rudder.io/issues/23255[#23255])

==== Agent

* Fixed: Wrong source detection on some apt systems
    (https://issues.rudder.io/issues/23387[#23387])

==== Miscellaneous

* Fixed: Make writing node state to fact repos optionnal
    (https://issues.rudder.io/issues/23424[#23424])

==== Web - UI & UX

* Fixed: Tables in Rudder UI are sorted alphabetically but should also follow a numerical sort - nodes page
    (https://issues.rudder.io/issues/23427[#23427])
* Fixed: Add a way to set a message if "change audit logs" setting is enabled
    (https://issues.rudder.io/issues/23372[#23372])
* Fixed: Add a way to set a message if "change audit logs" setting is enabled
    (https://issues.rudder.io/issues/23372[#23372])
* Fixed: We can choose the format of the value on deletion in global parameter
    (https://issues.rudder.io/issues/23183[#23183])
* Fixed: Tables in Rudder UI are sorted alphabetically but should also follow a numerical sort
    (https://issues.rudder.io/issues/23335[#23335])
* Fixed: Inconsitency background color in generic method section in technique editor
    (https://issues.rudder.io/issues/23170[#23170])
* Fixed: Inconsistent color of save button in directives
    (https://issues.rudder.io/issues/23196[#23196])

==== Relay server or API

* Fixed: Allow underscore in file_id in shared-files
    (https://issues.rudder.io/issues/23392[#23392])
* Fixed: Broken log for file_id in shared-files API
    (https://issues.rudder.io/issues/23390[#23390])

==== Web - Maintenance

* Fixed: Plugin cannot add custom roles or it will be overwritten by boot custom roles 
    (https://issues.rudder.io/issues/23098[#23098])

==== Architecture - Code maintenance

* Fixed: When custom role permission list is empty, reload lead to stack trace
    (https://issues.rudder.io/issues/23305[#23305])

==== Web - Technique editor

* Fixed: Error when we try to save a draft with a missing parameter name in technique editor
    (https://issues.rudder.io/issues/23256[#23256])

==== Web - Config management

* Fixed: Error when updating policies on relays when no files has been shared between nodes
    (https://issues.rudder.io/issues/17143[#17143])

==== Techniques

* Fixed: When the user technique change a password it doesn't update the date of last change
    (https://issues.rudder.io/issues/23338[#23338])

==== Security

* Fixed: The "shared_file_to_node" method does not verify its policy server's certificate with default configuration
    (https://issues.rudder.io/issues/23290[#23290])

==== Generic methods

* Fixed:  When generic method change a password it doesn't update the date of last change
    (https://issues.rudder.io/issues/23339[#23339])
* Fixed: "Variable string from command" creates empty files in /var/rudder/modified-files
    (https://issues.rudder.io/issues/22584[#22584])

==== Documentation

* Fixed: Document when a parameter can be a regex
    (https://issues.rudder.io/issues/10713[#10713])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Marc Evans
* Jonathan CLARKE

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.5 (2023-08-11)

=== Changes


==== Web - UI & UX

* After deleting a node, the user should be redirected to nodes list page
    (https://issues.rudder.io/issues/7008[#7008])

=== Bug fixes

==== Packaging

* Fixed: Hide postrm script warnings
    (https://issues.rudder.io/issues/23251[#23251])
* Fixed: Rudder Server 7.3.4 doesn't install on SLES 15 SP4
    (https://issues.rudder.io/issues/23186[#23186])
* Fixed: Actually allow uninstalling the agent
    (https://issues.rudder.io/issues/23146[#23146])
* Fixed: Agent uninstall fails on Ubuntu 22.04
    (https://issues.rudder.io/issues/23145[#23145])
* Fixed: relayd build broken
    (https://issues.rudder.io/issues/23247[#23247])
* Fixed: Update spring security
    (https://issues.rudder.io/issues/23221[#23221])
* Fixed: Update embedded openssl to 1.1.1v - relayd
    (https://issues.rudder.io/issues/23217[#23217])
* Fixed: Package install after uninstall only restores uuid
    (https://issues.rudder.io/issues/23239[#23239])

==== Agent

* Fixed: When we uninstall and reinstall an agent, the agent is not correctly activated
    (https://issues.rudder.io/issues/22413[#22413])

==== Security

* Fixed: Update openssl and curl
    (https://issues.rudder.io/issues/23192[#23192])
* Fixed: CVE-2016-1000027 false positive detection
    (https://issues.rudder.io/issues/23231[#23231])

==== Documentation

* Fixed: doc for external db is not very clear
    (https://issues.rudder.io/issues/23245[#23245])
* Fixed: Wrong OS for amazon linux 2023 server install 
    (https://issues.rudder.io/issues/23242[#23242])
* Fixed: correct rudder server requirements in doc
    (https://issues.rudder.io/issues/23131[#23131])

==== Plugin manager cli

* Fixed: rudder package doesn't upgrade openscap, and it brings a lot of chaos
    (https://issues.rudder.io/issues/23224[#23224])

==== Miscellaneous

* Fixed: Update Rust compiler to 1.71.1 for security fix
    (https://issues.rudder.io/issues/23216[#23216])
* Fixed: Version 2.0.3 of ZIO cause OutOfMemory error and high CPU load
    (https://issues.rudder.io/issues/23147[#23147])

==== System integration

* Fixed: Windows agent cannot get immediatly its policies right after being accepted
    (https://issues.rudder.io/issues/23218[#23218])

==== Web - Config management

* Fixed: Message “Error getting directive compliance” when creating new directive
    (https://issues.rudder.io/issues/22830[#22830])

==== Generic methods

* Fixed: N/A report message when a block expression is not valid is not rendered correctly
    (https://issues.rudder.io/issues/23212[#23212])

==== Web - Technique editor

* Fixed: in the technique editor, the drop down list for condition is truncated
    (https://issues.rudder.io/issues/23177[#23177])

==== Web - UI & UX

* Fixed: Inventory variable that are Json types are listed as plain string types in the UI
    (https://issues.rudder.io/issues/23087[#23087])
* Fixed: Interface color inconsistency for non compliance display
    (https://issues.rudder.io/issues/23004[#23004])

==== Server components

* Fixed: Broken "server create-user" command when auth file has different formating
    (https://issues.rudder.io/issues/23203[#23203])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.4 (2023-07-21)

=== Changes


==== Packaging

* rhel7 server build should depends on python3-pip and python3
    (https://issues.rudder.io/issues/23083[#23083])
* Repair rhel7 agent build
    (https://issues.rudder.io/issues/23080[#23080])

==== Documentation

* Document how to script the windows agent install
    (https://issues.rudder.io/issues/23066[#23066])

==== Performance and scalability

* Make commiting nodes to fact-repo optionnal
    (https://issues.rudder.io/issues/23045[#23045])

==== Web - UI & UX

* Remove heartbeat configuration from the settings
    (https://issues.rudder.io/issues/22659[#22659])
* Beautify no permission page when user have no rights
    (https://issues.rudder.io/issues/22626[#22626])

==== API

* Remove "no access" permission in token authorization
    (https://issues.rudder.io/issues/23014[#23014])

==== Agent

* Add a trust option to rudder agent policy-server
    (https://issues.rudder.io/issues/22629[#22629])

=== Bug fixes

==== Web - Nodes & inventories

* Fixed: Missing information in Oracle linux inventory
    (https://issues.rudder.io/issues/23029[#23029])
* Fixed: 502 - Proxy Error when triggering Rudder agent
    (https://issues.rudder.io/issues/22998[#22998])

==== Documentation

* Fixed: Add relevent items from jetty config to the webapp conf section
    (https://issues.rudder.io/issues/23026[#23026])
* Fixed: Document the report mode setting
    (https://issues.rudder.io/issues/13289[#13289])
* Fixed: Windows agent installation : Documentation improvement
    (https://issues.rudder.io/issues/23018[#23018])
* Fixed: documentation on how to configure rsync relay synchroinisation is missing
    (https://issues.rudder.io/issues/22891[#22891])
* Fixed: Documentation on how to upgrade Rudder to 7.2 is invalid on zypper
    (https://issues.rudder.io/issues/22621[#22621])

==== Web - Compliance & node report

* Fixed: Bad report maching when reportid are present
    (https://issues.rudder.io/issues/22388[#22388])
* Fixed: Multiline string in component name or value breaks pattern comparison for expected report
    (https://issues.rudder.io/issues/23090[#23090])

==== Miscellaneous

* Fixed: Generation not queued when one already started
    (https://issues.rudder.io/issues/23074[#23074])

==== Web - Technique editor

* Fixed: When changes messages are mandatory and saving a technique we have an error message about missing info but technique is saved
    (https://issues.rudder.io/issues/23000[#23000])

==== Web - UI & UX

* Fixed: There is a blank space above almost every Rudder page
    (https://issues.rudder.io/issues/23042[#23042])
* Fixed: Directives tooltips go under navigation menu
    (https://issues.rudder.io/issues/22530[#22530])

==== Architecture - Code maintenance

* Fixed: Cache most current Version number to save lots of memory
    (https://issues.rudder.io/issues/22978[#22978])

==== Server components

* Fixed: Grammar correction in error message
    (https://issues.rudder.io/issues/23027[#23027])

==== Techniques

* Fixed: Update user management to manage secondary group of user
    (https://issues.rudder.io/issues/22846[#22846])
* Fixed: Update user management to manage secondary group of user
    (https://issues.rudder.io/issues/22846[#22846])

==== Agent

* Fixed: Hard to understand set-force-audit help
    (https://issues.rudder.io/issues/23008[#23008])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.3 (2023-07-03)

=== Changes


==== Web - Config management

* Display inventory variables and values in node details
    (https://issues.rudder.io/issues/22864[#22864])

==== Web - Technique editor

* Improving the display of Generic Methods in the Technique Editor for a better UX
    (https://issues.rudder.io/issues/22896[#22896])

==== Web - Nodes & inventories

* OS and hardware inventory information are not discoverable
    (https://issues.rudder.io/issues/22807[#22807])

==== Generic methods

* Add a methd to force the secondary groups of a user
    (https://issues.rudder.io/issues/22722[#22722])

=== Bug fixes

==== Packaging

* Fixed: slackware postinst fails because library links are made too late
    (https://issues.rudder.io/issues/22974[#22974])
* Fixed: slackware doesn't install initscript
    (https://issues.rudder.io/issues/22962[#22962])
* Fixed: openssl 1.1.1 fails to build on debian 12 armhf
    (https://issues.rudder.io/issues/22954[#22954])
* Fixed: Update embedded openssl to 1.1.1u
    (https://issues.rudder.io/issues/22886[#22886])
* Fixed: build-cache share cache between different rudder versions
    (https://issues.rudder.io/issues/22850[#22850])
* Fixed: Disable http2 in embedded curl
    (https://issues.rudder.io/issues/22809[#22809])
* Fixed: Missing python3 on AL2 leads to missing generic methods in technique editor and big red error
    (https://issues.rudder.io/issues/22551[#22551])
* Fixed: Useless python sed for rhel7 agent package
    (https://issues.rudder.io/issues/22804[#22804])
* Fixed: git is a build dependency for rudder-server package
    (https://issues.rudder.io/issues/22782[#22782])
* Fixed: perl dependencies are missing on AL 2023
    (https://issues.rudder.io/issues/22765[#22765])
* Fixed: docopt completion is installed in /usr/local/bin
    (https://issues.rudder.io/issues/22868[#22868])
* Fixed: Typos-cli does not build anymore
    (https://issues.rudder.io/issues/22924[#22924])

==== Agent

* Fixed: Use dist-upgrade on apt systems to see list of pending upgrades
    (https://issues.rudder.io/issues/22839[#22839])

==== Performance and scalability

* Fixed: resources sent to the browser are not compressed when using a custom cetificate
    (https://issues.rudder.io/issues/22749[#22749])
* Fixed: When we arrive on the node search page with a query pre-filed, the query is done twice
    (https://issues.rudder.io/issues/21236[#21236])

==== Documentation

* Fixed: Inventory variable doc is wrong about evaluation process
    (https://issues.rudder.io/issues/22956[#22956])
* Fixed: Remove AL2023 from menu doc for server install
    (https://issues.rudder.io/issues/22955[#22955])
* Fixed: Missing postgres version in requirement
    (https://issues.rudder.io/issues/22901[#22901])
* Fixed: Documentation for windows node inventory variable is false
    (https://issues.rudder.io/issues/22865[#22865])
* Fixed: Documentation for windows node inventory variable is false
    (https://issues.rudder.io/issues/22865[#22865])
* Fixed: Missing documentation for AmazonLinux 2023 install for the agent
    (https://issues.rudder.io/issues/22778[#22778])
* Fixed: API doc loads files from cdn.redoc.ly
    (https://issues.rudder.io/issues/22843[#22843])
* Fixed: missing parameters in ruledetails api response
    (https://issues.rudder.io/issues/22783[#22783])

==== Architecture - Code maintenance

* Fixed: Spurious test error about length of generated password
    (https://issues.rudder.io/issues/22967[#22967])
* Fixed: error in node variable parser for policy server
    (https://issues.rudder.io/issues/22958[#22958])
* Fixed: Exception in page when the user rights list is empty
    (https://issues.rudder.io/issues/22908[#22908])
* Fixed: API are not logged anymore
    (https://issues.rudder.io/issues/22877[#22877])

==== CI

* Fixed: add label to rudder docker images
    (https://issues.rudder.io/issues/22914[#22914])
* Fixed: add label to rudder-techniques docker images
    (https://issues.rudder.io/issues/22922[#22922])
* Fixed: add label to ncf docker images
    (https://issues.rudder.io/issues/22913[#22913])

==== Web - Maintenance

* Fixed: NodeProperties value are not correctly serialized in event log
    (https://issues.rudder.io/issues/22946[#22946])
* Fixed: Too many "Policy Update Started" in event logs
    (https://issues.rudder.io/issues/22879[#22879])

==== Server components

* Fixed: Disable post-generation remote-run by default
    (https://issues.rudder.io/issues/22871[#22871])
* Fixed: Use 8080 port to talk with the webapp in hooks
    (https://issues.rudder.io/issues/22870[#22870])

==== Web - UI & UX

* Fixed: diff on node properties in event log (at least) is broken
    (https://issues.rudder.io/issues/22933[#22933])
* Fixed: Long change request diff is unusable
    (https://issues.rudder.io/issues/22919[#22919])
* Fixed: JS diff library stop working
    (https://issues.rudder.io/issues/22911[#22911])
* Fixed: TODOs in the UI
    (https://issues.rudder.io/issues/22880[#22880])
* Fixed: Button to add/remove more entries indirectives are inside entries
    (https://issues.rudder.io/issues/22654[#22654])

==== Miscellaneous

* Fixed: Update relayd rust-openssl dependency due to RUSTSEC-2023-0044
    (https://issues.rudder.io/issues/22943[#22943])

==== Web - Nodes & inventories

* Fixed: When we clone a group in Rudder 7.2, newly added properties are not cloned
    (https://issues.rudder.io/issues/22702[#22702])
* Fixed: NPE gz inventory file is corrupted
    (https://issues.rudder.io/issues/22874[#22874])

==== Security

* Fixed: Directive CSV compliance is not correctly quote-escaped
    (https://issues.rudder.io/issues/22801[#22801])

==== Techniques

* Fixed: Method calls using a condition are not properly generated when a variable is used in the condition expression
    (https://issues.rudder.io/issues/22785[#22785])

==== Generic methods

* Fixed: Add a full class prefix in user_secondary_group
    (https://issues.rudder.io/issues/22866[#22866])

=== Release notes

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.2 (2023-05-18)

=== Changes


==== Packaging

* Add debian12 support to agent package
    (https://issues.rudder.io/issues/22747[#22747])

==== Architecture - Internal libs

* Backport scala 2.13 change for scala 3.0 migration
    (https://issues.rudder.io/issues/22723[#22723])

==== Web - Nodes & inventories

* VM type is missing in group criteria
    (https://issues.rudder.io/issues/19803[#19803])

=== Bug fixes

==== Server components

* Fixed: silent rudder-upgrade failure / plugins were not upgraded when upgrading from 7.2.5 to 7.3.1~nightly
    (https://issues.rudder.io/issues/22689[#22689])

==== Agent

* Fixed: Errors with Rudder agent on unprivileged containers (LXC)
    (https://issues.rudder.io/issues/15636[#15636])
* Fixed: A node update in bootstrap/initial policies should not fail
    (https://issues.rudder.io/issues/20996[#20996])

==== System integration

* Fixed: Postgresql is not created with the UTF8 encoding
    (https://issues.rudder.io/issues/20937[#20937])

==== Packaging

* Fixed: Missing dependency on ps command on RHEL8+
    (https://issues.rudder.io/issues/22727[#22727])
* Fixed: pip3 refuses to install modules in a system with packages python modules
    (https://issues.rudder.io/issues/22763[#22763])

==== Documentation

* Fixed: proxy documentation is lost in rudder 7.3 documentation
    (https://issues.rudder.io/issues/22767[#22767])
* Fixed: Backup/restore documentation is missing some important folder backups when using plugins
    (https://issues.rudder.io/issues/22756[#22756])
* Fixed: Installation documentation should use ' instead of " to avoid unwanted bash string interpretation
    (https://issues.rudder.io/issues/22737[#22737])

==== Web - Nodes & inventories

* Fixed: No local account shown on windows
    (https://issues.rudder.io/issues/22387[#22387])

==== Security

* Fixed: Error when trying to save a property using xml tags but property actually saved
    (https://issues.rudder.io/issues/19519[#19519])
* Fixed: Healthcheck notification is displayed when a user have no right
    (https://issues.rudder.io/issues/22625[#22625])

==== Web - UI & UX

* Fixed: Inconsistent colors in hover on the dashboard
    (https://issues.rudder.io/issues/22671[#22671])
* Fixed: Inconsistent colors in hover on the dashboard
    (https://issues.rudder.io/issues/22671[#22671])

==== Web - Compliance & node report

* Fixed: Warn sign in nodes list for disabled nodes
    (https://issues.rudder.io/issues/19545[#19545])

==== Generic methods

* Fixed: Reporting error when using a dash for SSH authorized keys method
    (https://issues.rudder.io/issues/22724[#22724])
* Fixed: condition from variable match does not work with node properties
    (https://issues.rudder.io/issues/21026[#21026])
* Fixed: file augeas set doesn't when value have space
    (https://issues.rudder.io/issues/22725[#22725])
* Fixed: Method File augeas set does not clean augnew files
    (https://issues.rudder.io/issues/22718[#22718])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Stefan Schmitt

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.1 (2023-05-04)

=== Changes


==== Documentation

* Add documentation about optional anonymous data collection
    (https://issues.rudder.io/issues/22673[#22673])
* Add install docs for Amazon Linux 2023
    (https://issues.rudder.io/issues/22628[#22628])

==== CI

* Notify different channel for security dependency check
    (https://issues.rudder.io/issues/22687[#22687])

==== Web - Nodes & inventories

* Display sha256 key hash in node details
    (https://issues.rudder.io/issues/22633[#22633])

=== Bug fixes

==== Packaging

* Fixed: Rudder agent force a lot of dependencies on RHEL9 
    (https://issues.rudder.io/issues/22610[#22610])

==== Miscellaneous

* Fixed: Ignore CVE 2023-20860 
    (https://issues.rudder.io/issues/22708[#22708])
* Fixed: Missing "latest" in archive API tests leads to error with upmerge
    (https://issues.rudder.io/issues/22636[#22636])

==== Security

* Fixed: Vulnerability in decode-uri-component
    (https://issues.rudder.io/issues/22707[#22707])
* Fixed: Ignore RUSTSEC-2023-0034 in relayd
    (https://issues.rudder.io/issues/22706[#22706])
* Fixed: upgrade postgresql drive for CVE CVE-2022-41946
    (https://issues.rudder.io/issues/22637[#22637])
* Fixed: Stackoverflow if {} used in place of [] for properties in node create api
    (https://issues.rudder.io/issues/22617[#22617])

==== Web - Campaigns

* Fixed: We should initialize campaign service after plugin were added or else current events will be skipped (before being added again)
    (https://issues.rudder.io/issues/22646[#22646])

==== Architecture - Internal libs

* Fixed: A deadlock can occur at boot (also a cause of slow initialization)
    (https://issues.rudder.io/issues/22645[#22645])

==== Web - UI & UX

* Fixed: It's hard to understand which authentication backend failed when a fallback happens
    (https://issues.rudder.io/issues/20396[#20396])
* Fixed: There are unused css classes due to wrong css class name
    (https://issues.rudder.io/issues/22669[#22669])
* Fixed:  Pending nodes History Tab shows duplicate entries
    (https://issues.rudder.io/issues/19258[#19258])
* Fixed: Remove AdminLTE script from login page
    (https://issues.rudder.io/issues/22644[#22644])
* Fixed:  Tooltip on enforce/audit label in rules title not working
    (https://issues.rudder.io/issues/20788[#20788])
* Fixed: rules/directives/cancel button doesn't work
    (https://issues.rudder.io/issues/22517[#22517])

==== Documentation

* Fixed: Fix typos in system-updates api doc
    (https://issues.rudder.io/issues/22667[#22667])
* Fixed: Relay API documentation is quite hard to find
    (https://issues.rudder.io/issues/22648[#22648])
* Fixed: Update screenshot of the dashboard
    (https://issues.rudder.io/issues/22634[#22634])

==== Web - Maintenance

* Fixed: JGitInternalError on HistorizeNodeCountService
    (https://issues.rudder.io/issues/22616[#22616])

==== Architecture - Dependencies

* Fixed: Update spring to 5.3.27 and spring-security 5.7.8
    (https://issues.rudder.io/issues/22668[#22668])

==== Relay server or API

* Fixed: Broken shared-files cleanup when file id contains a dot
    (https://issues.rudder.io/issues/22652[#22652])

==== System integration

* Fixed: Log in hook should got to /var/log and not /tmp
    (https://issues.rudder.io/issues/22649[#22649])

==== Web - Config management

* Fixed: Error log at boot: Can not find active technique with id 'test_import_export_archive}'
    (https://issues.rudder.io/issues/22614[#22614])

==== Web - Technique editor

* Fixed: In technique editor, technique with missing generic method need a warning icon
    (https://issues.rudder.io/issues/12282[#12282])

==== System techniques

* Fixed: Always send start/end reports even in changes-only mode
    (https://issues.rudder.io/issues/22655[#22655])

==== Agent

* Fixed: Allow skipping reporting when it is disabled
    (https://issues.rudder.io/issues/22653[#22653])

==== Generic methods

* Fixed: Augeas set method does not correctly handle successive calls
    (https://issues.rudder.io/issues/22677[#22677])
* Fixed: report_if_condition report contain twice "was correct"
    (https://issues.rudder.io/issues/22665[#22665])
* Fixed: Missleading use of parameter variable_name in method condition_from_variable_match
    (https://issues.rudder.io/issues/22620[#22620])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Lars Koenen

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.0 (2023-04-07)

=== Changes


==== Packaging

* Add amazon linux to support to specfiles
    (https://issues.rudder.io/issues/22578[#22578])

==== Documentation

* Document 7.3 windows specific changes
    (https://issues.rudder.io/issues/22613[#22613])
* Arch doc for frontend security
    (https://issues.rudder.io/issues/22512[#22512])
* Update network security arch doc for 7.3 and migration cases
    (https://issues.rudder.io/issues/22505[#22505])
* Update network security arch doc for 7.3 and migration cases
    (https://issues.rudder.io/issues/22505[#22505])
* Update network security arch doc for 7.3 and migration cases
    (https://issues.rudder.io/issues/22505[#22505])

==== Web - Nodes & inventories

* Add tests for linux inventory signature with certificate
    (https://issues.rudder.io/issues/22528[#22528])

==== rudderc

* Render methods docs as html
    (https://issues.rudder.io/issues/22538[#22538])
* Add a JSON schema validation
    (https://issues.rudder.io/issues/22489[#22489])

==== Web - Config management

* Persisted rule should have sorted groups/directives
    (https://issues.rudder.io/issues/18215[#18215])

==== Techniques

* Deprecate System update technique
    (https://issues.rudder.io/issues/22611[#22611])

==== Generic methods

* Explain flag mechanisme for "once" method
    (https://issues.rudder.io/issues/22596[#22596])

=== Bug fixes

==== Packaging

* Fixed: missing dependencies on amazon linux server
    (https://issues.rudder.io/issues/22615[#22615])
* Fixed: rudder-init replaces rudder-db password at postinst
    (https://issues.rudder.io/issues/22608[#22608])
* Fixed: Amazon linux doesn't provide postgresql-server
    (https://issues.rudder.io/issues/22593[#22593])
* Fixed: rudder-server-postinst fails to update rudder-web.properties
    (https://issues.rudder.io/issues/22495[#22495])
* Fixed: Error when installing Rudder 6.2.13 on almalinux 8
    (https://issues.rudder.io/issues/21252[#21252])

==== Agent

* Fixed: rudder-sign says "hostname: command not found"
    (https://issues.rudder.io/issues/22452[#22452])
* Fixed: Connection timeout to server are too long
    (https://issues.rudder.io/issues/22540[#22540])

==== Server components

* Fixed: "reportid" missing in PostgreSQL database after upgrade from v6.2.12 to v7.2.3
    (https://issues.rudder.io/issues/22315[#22315])

==== Documentation

* Fixed: Update doc for 7.3
    (https://issues.rudder.io/issues/22607[#22607])
* Fixed: Add rudder agent verbose command in windows install 
    (https://issues.rudder.io/issues/22598[#22598])
* Fixed: Typo in windows msiexec command in documentation
    (https://issues.rudder.io/issues/22554[#22554])
* Fixed: Problem in Server backup and migration documentation
    (https://issues.rudder.io/issues/22313[#22313])
* Fixed: Typo in windows install documentation
    (https://issues.rudder.io/issues/22558[#22558])
* Fixed: Provide info to user about java-openjdk11-headless alternatives for AL2
    (https://issues.rudder.io/issues/22499[#22499])
* Fixed: Broken doc build after plugins doc change
    (https://issues.rudder.io/issues/22490[#22490])
* Fixed: document in the getting started that virtualbox needs a list of authorized IP
    (https://issues.rudder.io/issues/21485[#21485])
* Fixed: API Documentation errors for trigger agent run
    (https://issues.rudder.io/issues/22565[#22565])
* Fixed: Improve introduction of relay arch docs
    (https://issues.rudder.io/issues/22509[#22509])

==== Web - UI & UX

* Fixed: when we save a rule category, the button save never stops saving
    (https://issues.rudder.io/issues/22524[#22524])
* Fixed: there is a space before all texts in the node details page, so copy and paste include it
    (https://issues.rudder.io/issues/21417[#21417])
* Fixed: System group preview description are not displayed
    (https://issues.rudder.io/issues/18583[#18583])
* Fixed: Rule list doesn't appear anymore in a rule category
    (https://issues.rudder.io/issues/22103[#22103])
* Fixed: When shared folder file list is too long the selector fail
    (https://issues.rudder.io/issues/22110[#22110])
* Fixed: Change name parameter "Rudder ID" for group id
    (https://issues.rudder.io/issues/22581[#22581])
* Fixed: Technique ID and group ID are juste listed as "ID" in the UI when other IDs are listed with their long name
    (https://issues.rudder.io/issues/21369[#21369])
* Fixed: Rule is in mixed mode even though she has only one directive in audit
    (https://issues.rudder.io/issues/21731[#21731])
* Fixed: Shadow overlapping on first menu entry
    (https://issues.rudder.io/issues/21683[#21683])
* Fixed: Missing tooltip on unused directives icon
    (https://issues.rudder.io/issues/22428[#22428])

==== Web - Maintenance

* Fixed: password=LDAP produces error logs in webapp
    (https://issues.rudder.io/issues/21978[#21978])

==== Web - Compliance & node report

* Fixed: General improvements on Directive compliance API
    (https://issues.rudder.io/issues/22552[#22552])
* Fixed: HTML tag in compliance hover
    (https://issues.rudder.io/issues/22560[#22560])
* Fixed: Sorting by Compliance doesn't sort in the rule details
    (https://issues.rudder.io/issues/21182[#21182])

==== API

* Fixed: List Managed Nodes API with any of the fields listed in the "full" never answer
    (https://issues.rudder.io/issues/22534[#22534])

==== Security

* Fixed: Update spring-core to 5.3.26
    (https://issues.rudder.io/issues/22586[#22586])
* Fixed: Allow iframes from the same origin
    (https://issues.rudder.io/issues/22522[#22522])
* Fixed: Update openssl crate to fix several vulnerabilities
    (https://issues.rudder.io/issues/22532[#22532])

==== Techniques

* Fixed: Mustache template is not capable to render technique parameters
    (https://issues.rudder.io/issues/22535[#22535])

==== rudderc

* Fixed: Allow BSD-2-Clause licences
    (https://issues.rudder.io/issues/22543[#22543])
* Fixed: Fix escaping in rudderc
    (https://issues.rudder.io/issues/22468[#22468])

==== Web - Config management

* Fixed: Policy generation broken when defining a group with invert result of inclusion of another group
    (https://issues.rudder.io/issues/21924[#21924])
* Fixed: Directive detail is really slow to load in 7.3
    (https://issues.rudder.io/issues/22392[#22392])

==== Web - Technique editor

* Fixed: There is one more minus in deleted resources counter within technique editor
    (https://issues.rudder.io/issues/22475[#22475])

==== Web - Nodes & inventories

* Fixed: On "Node search" page, we can click on "Create node group from this query" even if there were no query
    (https://issues.rudder.io/issues/19986[#19986])

==== System integration

* Fixed: server-create-user uses old role attribte in place of new permissions one
    (https://issues.rudder.io/issues/22498[#22498])
* Fixed: Parent fix does not work: Fusioninventory is not tracked by check-rudder-health
    (https://issues.rudder.io/issues/11102[#11102])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Lars Koenen

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.0.rc1 (2023-03-17)

=== Changes


==== Agent

* Remove the fallback on "rudder" host when no policy server is configued
    (https://issues.rudder.io/issues/22407[#22407])

==== Documentation

* Add bcrypt param doc in main doc
    (https://issues.rudder.io/issues/22429[#22429])
* Prepare 7.3 doc
    (https://issues.rudder.io/issues/22368[#22368])
* Prepare 7.3 doc
    (https://issues.rudder.io/issues/22368[#22368])
* Prepare 7.3 doc
    (https://issues.rudder.io/issues/22368[#22368])
* Add missing documentation for CVE API
    (https://issues.rudder.io/issues/22446[#22446])
* Add missing documentation for CVE API
    (https://issues.rudder.io/issues/22446[#22446])

==== Web - UI & UX

* Edit properties is not intuitive
    (https://issues.rudder.io/issues/21918[#21918])
* Missing a loading info when a technique it is being saved
    (https://issues.rudder.io/issues/21929[#21929])

==== API

* Remove usage of redoc-cli which is deprecated
    (https://issues.rudder.io/issues/22447[#22447])

==== System integration

* Make specs2 test console output more detailed
    (https://issues.rudder.io/issues/22419[#22419])

==== Architecture - Internal libs

* Fix version maven-resources-plugin to 3.1.0, instead of relying on maven default version
    (https://issues.rudder.io/issues/22403[#22403])

==== Performance and scalability

* Make parsing "process" in inventory optional
    (https://issues.rudder.io/issues/22359[#22359])

==== Web - Config management

* Avoid sync group when importing a rule archive
    (https://issues.rudder.io/issues/22333[#22333])

==== Security

* Allow iframes from the same origin
    (https://issues.rudder.io/issues/22374[#22374])

=== Bug fixes

==== System integration

* Fixed: Rudder-jetty timeout is the systemd default one and may be short
    (https://issues.rudder.io/issues/22377[#22377])

==== Packaging

* Fixed: Cleanup prerm scripts
    (https://issues.rudder.io/issues/22203[#22203])

==== Documentation

* Fixed: Bad documentation leads to package build failing when building for armhf
    (https://issues.rudder.io/issues/17868[#17868])
* Fixed: doc about configuring repositories on debian is confusing for the rudder server
    (https://issues.rudder.io/issues/22396[#22396])
* Fixed: Remove outdated stuff about the technique editor
    (https://issues.rudder.io/issues/22420[#22420])
* Fixed: Broken link to rudder-announce ML
    (https://issues.rudder.io/issues/22416[#22416])
* Fixed: versions in Rudder doc are invalid
    (https://issues.rudder.io/issues/21750[#21750])
* Fixed: List of authentication backend is invalid in the documentation (includes Radius)
    (https://issues.rudder.io/issues/22406[#22406])
* Fixed: Backport hardening guide to 7.2
    (https://issues.rudder.io/issues/22405[#22405])
* Fixed: Hardening guide for Rudder
    (https://issues.rudder.io/issues/21877[#21877])
* Fixed: documentation about default login/password is invalid
    (https://issues.rudder.io/issues/22367[#22367])
* Fixed: documentation about default login/password is invalid
    (https://issues.rudder.io/issues/22367[#22367])
* Fixed: network requirement in documentation are invalid
    (https://issues.rudder.io/issues/22366[#22366])
* Fixed: Inconsistency in API doc for allowed network
    (https://issues.rudder.io/issues/22467[#22467])

==== Web - UI & UX

* Fixed: typo about licensed plugin
    (https://issues.rudder.io/issues/22463[#22463])
* Fixed: Empty dashboard doesn't look good
    (https://issues.rudder.io/issues/21255[#21255])
* Fixed: Add an animation when the rules table loads
    (https://issues.rudder.io/issues/22449[#22449])
* Fixed: Show all in technical details table doesn't work
    (https://issues.rudder.io/issues/22107[#22107])
* Fixed: Plugins-repository URL from plugins pages redirect to home page
    (https://issues.rudder.io/issues/21346[#21346])

==== Web - Maintenance

* Fixed: Update rudder-user.xml to use permissions in place of roles attribute
    (https://issues.rudder.io/issues/22457[#22457])

==== API

* Fixed: Invalid openapi definition
    (https://issues.rudder.io/issues/20629[#20629])
* Fixed: Directive compliance API version is 10 in place of 17
    (https://issues.rudder.io/issues/22435[#22435])

==== Web - Nodes & inventories

* Fixed: Inventory error when missing tag POLICY_SERVER_UUID talk about POLICY_SERVER
    (https://issues.rudder.io/issues/22453[#22453])
* Fixed: Add Raspbian to the list of recognized OS
    (https://issues.rudder.io/issues/22345[#22345])

==== Security

* Fixed: RUSTSEC-2023-0018  in remove_dir_all
    (https://issues.rudder.io/issues/22432[#22432])
* Fixed: RUSTSEC-2023-0018  in remove_dir_all
    (https://issues.rudder.io/issues/22432[#22432])
* Fixed: RUSTSEC-2023-0018  in remove_dir_all
    (https://issues.rudder.io/issues/22432[#22432])
* Fixed: RUSTSEC-2023-0018  in remove_dir_all
    (https://issues.rudder.io/issues/22432[#22432])

==== Miscellaneous

* Fixed: Update commons fileupload dependency to prevent CVE-2023-24998
    (https://issues.rudder.io/issues/22433[#22433])
* Fixed: Healthcheck on file descriptor should be max 64000
    (https://issues.rudder.io/issues/22430[#22430])

==== Architecture - Refactoring

* Fixed: Remove pattern matching warning 
    (https://issues.rudder.io/issues/22424[#22424])

==== Web - Compliance & node report

* Fixed: missing report in change only
    (https://issues.rudder.io/issues/22371[#22371])
* Fixed: Nodes not answering are seen in "missing" rather than in "no reports"
    (https://issues.rudder.io/issues/22375[#22375])
* Fixed: Refactor Directive compliance to handle blocks
    (https://issues.rudder.io/issues/22376[#22376])

==== Web - Config management

* Fixed: Generate policies for campaigns before it starts officially, delete them after it stops (1 hour delay each)
    (https://issues.rudder.io/issues/22378[#22378])
* Fixed: User should be able to accept change request even with divergences
    (https://issues.rudder.io/issues/22363[#22363])

==== Relay server or API

* Fixed: File from shared folder method does not support special characters in the source path
    (https://issues.rudder.io/issues/20834[#20834])

==== System techniques

* Fixed: A 6.2 relay cannot talk to a 7.2 server through HTTPS
    (https://issues.rudder.io/issues/22402[#22402])
* Fixed: Changes only does not support campaign reports 
    (https://issues.rudder.io/issues/22240[#22240])

==== Generic methods

* Fixed: file key value parameter in list accepts entries without separator
    (https://issues.rudder.io/issues/22322[#22322])
* Fixed: Descriptin of permissions dirs recursive is misleading
    (https://issues.rudder.io/issues/17122[#17122])

==== Agent

* Fixed: "Using the default value 'true' for attribute rxdirs" waning in agent run output
    (https://issues.rudder.io/issues/22393[#22393])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Nicolas Ecarnot
* Alexis TARUSSIO

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.3.0.beta1 (2023-02-09)

=== Changes


==== Packaging

* Remove useless configure flags from openldap
    (https://issues.rudder.io/issues/22265[#22265])
* Remove readline library from aix package
    (https://issues.rudder.io/issues/22234[#22234])
* Add zip as a server dependency
    (https://issues.rudder.io/issues/22116[#22116])
* Update server dependencies for 7.3
    (https://issues.rudder.io/issues/22070[#22070])
* Update agent dependencies
    (https://issues.rudder.io/issues/22071[#22071])
* Update to CFEngine 3.18.3
    (https://issues.rudder.io/issues/22068[#22068])
* Update the toml crate to 0.6
    (https://issues.rudder.io/issues/22300[#22300])
* Build frontend files with gulp
    (https://issues.rudder.io/issues/22094[#22094])
* Use a lock file for api doc build dependencies
    (https://issues.rudder.io/issues/22136[#22136])
* Use npm for managing js dependencies
    (https://issues.rudder.io/issues/22081[#22081])

==== Documentation

* Update windows agent installation documentation
    (https://issues.rudder.io/issues/22330[#22330])
* Remove 6.2 and 7.0 from doc menu
    (https://issues.rudder.io/issues/22031[#22031])
* Use docsearch v3 for search integration
    (https://issues.rudder.io/issues/21989[#21989])
* Start docs for new technique yaml format
    (https://issues.rudder.io/issues/21961[#21961])

==== System integration

* Allow user to define custom roles in rudder-user.xml
    (https://issues.rudder.io/issues/22206[#22206])

==== Security

* Update to Rust 1.66.1
    (https://issues.rudder.io/issues/22293[#22293])
* Improve npm audit
    (https://issues.rudder.io/issues/22217[#22217])
* Add security headers in Lift config
    (https://issues.rudder.io/issues/21795[#21795])

==== rudderc

* Windows policy generation
    (https://issues.rudder.io/issues/22239[#22239])
* Add a first hardening technique draft
    (https://issues.rudder.io/issues/22268[#22268])
* Make rudderc techniques work in edge cases
    (https://issues.rudder.io/issues/22179[#22179])
* Tags entry in yaml technique
    (https://issues.rudder.io/issues/22156[#22156])
* Don't require resources to be listed in yaml technique
    (https://issues.rudder.io/issues/22147[#22147])
* Rename resources in rudderc
    (https://issues.rudder.io/issues/22142[#22142])
* Generate a proper metadata.xml
    (https://issues.rudder.io/issues/22054[#22054])
* Remove rudder-lang code
    (https://issues.rudder.io/issues/22040[#22040])
*  Use resource type information in rudderc
    (https://issues.rudder.io/issues/21308[#21308])

==== Web - UI & UX

* Use npm to maintain jqueryui
    (https://issues.rudder.io/issues/22244[#22244])
* Update elm dependencies
    (https://issues.rudder.io/issues/22051[#22051])

==== API

* API for directive compliance
    (https://issues.rudder.io/issues/22150[#22150])

==== Miscellaneous

* Make authorization and rights pluggable
    (https://issues.rudder.io/issues/22198[#22198])

==== Architecture - Dependencies

* Update scala dependencies to latest version
    (https://issues.rudder.io/issues/22049[#22049])
* Port code to ZIO2
    (https://issues.rudder.io/issues/21825[#21825])

==== CI

* Update Rust for 7.3
    (https://issues.rudder.io/issues/21875[#21875])

==== Web - Maintenance

* Cleanup rudder-lang settings
    (https://issues.rudder.io/issues/21866[#21866])

==== System techniques

* Disable agent syslog logging by default
    (https://issues.rudder.io/issues/21970[#21970])

==== Agent

* Cleanup remote run command for relay
    (https://issues.rudder.io/issues/22231[#22231])

==== Generic methods

* Add agent support metadata
    (https://issues.rudder.io/issues/21939[#21939])

=== Bug fixes

==== Packaging

* Fixed: Remove git from build dependencies of rudder-server
    (https://issues.rudder.io/issues/22356[#22356])
* Fixed: patch fusioninventory to detect correctly rockylinux
    (https://issues.rudder.io/issues/22334[#22334])
* Fixed: Remove message of cfengine trying to load enterprise module
    (https://issues.rudder.io/issues/22236[#22236])
* Fixed: readline fails to build on aix
    (https://issues.rudder.io/issues/22228[#22228])
* Fixed: Dev version of perl used
    (https://issues.rudder.io/issues/22215[#22215])
* Fixed: Add content in rudder's robots.txt
    (https://issues.rudder.io/issues/21798[#21798])

==== Web - UI & UX

* Fixed: Redirect / to /rudder/secure to avoid login form if already connected
    (https://issues.rudder.io/issues/21807[#21807])
* Fixed: Remove useless headers
    (https://issues.rudder.io/issues/21797[#21797])
* Fixed: Update outdated npm packages
    (https://issues.rudder.io/issues/22336[#22336])
* Fixed: Directive creation process is counter intuitive in 7.3.0~alpha
    (https://issues.rudder.io/issues/22254[#22254])
* Fixed: Display of Target Rules is broken
    (https://issues.rudder.io/issues/22305[#22305])
* Fixed: Use npm to maintain gauge.js
    (https://issues.rudder.io/issues/22270[#22270])
* Fixed: Use npm to maintain angularJS
    (https://issues.rudder.io/issues/22252[#22252])
* Fixed: Top menu bar display is broken
    (https://issues.rudder.io/issues/22245[#22245])
* Fixed: Remove AdminLTE theme
    (https://issues.rudder.io/issues/22204[#22204])
* Fixed: Transform tabs of the directives into real tabs
    (https://issues.rudder.io/issues/22086[#22086])
* Fixed: Dont redirect other tabs to login form when session cookie is replaced
    (https://issues.rudder.io/issues/21808[#21808])
* Fixed: Impossible to move groups
    (https://issues.rudder.io/issues/21755[#21755])

==== Documentation

* Fixed: Wrong Table name inside documentation
    (https://issues.rudder.io/issues/22128[#22128])
* Fixed: Remove beta header from 7.2 docs
    (https://issues.rudder.io/issues/21879[#21879])

==== Security

* Fixed: Ignore CVE-2023-22895 in relayd
    (https://issues.rudder.io/issues/22354[#22354])
* Fixed: Update the embedded openssl to 1.1.1t
    (https://issues.rudder.io/issues/22351[#22351])
* Fixed: Ignore DoS in npm dependencies
    (https://issues.rudder.io/issues/22324[#22324])
* Fixed: Ignore RUSTSEC-2022-0082
    (https://issues.rudder.io/issues/22328[#22328])
* Fixed: Fix npm security alerts
    (https://issues.rudder.io/issues/22307[#22307])
* Fixed: Rudder sessions never expire when the browser stays connected
    (https://issues.rudder.io/issues/21806[#21806])
* Fixed: Stop using UUIDs as system token
    (https://issues.rudder.io/issues/21669[#21669])

==== Web - Campaigns

* Fixed: New filters on campaign queries to get several campaign types in one request
    (https://issues.rudder.io/issues/22346[#22346])

==== Web - Nodes & inventories

* Fixed: some nodes are called "localhost" since #8022
    (https://issues.rudder.io/issues/22326[#22326])

==== Web - Config management

* Fixed: Hook timeout may not have the good value
    (https://issues.rudder.io/issues/22339[#22339])

==== API

* Fixed: Cannot list directives with API
    (https://issues.rudder.io/issues/22314[#22314])

==== rudderc

* Fixed: Various metadata.xml fixes
    (https://issues.rudder.io/issues/22153[#22153])

==== CI

* Fixed: Add authorized license Unicode-DFS-2016 in relayd
    (https://issues.rudder.io/issues/21914[#21914])

==== Server components

* Fixed: All rudder commands using the API don't detect the port of the webapp when we configure a virtualhost with a different port
    (https://issues.rudder.io/issues/21216[#21216])

==== Generic methods

* Fixed: Remove ncf scripts
    (https://issues.rudder.io/issues/21950[#21950])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Alexis TARUSSIO

This is a bug fix release in the 7.3 series and therefore all installations of 7.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

