= Change logs for Rudder 9.1

==  Rudder 9.1.0 (2026-04-13)

=== Changes


=== Bug fixes

==== Documentation

* Fixed: Documentation mention .exe installer
    (https://issues.rudder.io/issues/28684[#28684])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 9.1.0.rc1 (2026-04-02)

=== Changes


==== Web - UI & UX

* Improve dashboard display on small screens
    (https://issues.rudder.io/issues/28566[#28566])

==== Web - Maintenance

* Be able to represent API account that was never authenticated
    (https://issues.rudder.io/issues/28580[#28580])

==== Documentation

* Update rudder documentation webapp.md adding fix to setup dev environment
    (https://issues.rudder.io/issues/28367[#28367])
* ADR for restart handling
    (https://issues.rudder.io/issues/28559[#28559])

==== Architecture - Code maintenance

* Simplify derivation in RudderJsonResponse
    (https://issues.rudder.io/issues/28538[#28538])

==== Module - system-updates

* Add exclusions in system-updates - apt
    (https://issues.rudder.io/issues/28336[#28336])

==== Architecture - ADR

* Add an ADR for usage of elm/time as main frontend library for display of dates
    (https://issues.rudder.io/issues/28524[#28524])
* Add an ADR for java-time usage
    (https://issues.rudder.io/issues/28515[#28515])

==== Architecture - Test

* Unit tests to cover missing cases in node agent cache
    (https://issues.rudder.io/issues/28514[#28514])

==== Security

* Logger for secure dispatch snippet should be application.authentication logger 
    (https://issues.rudder.io/issues/28505[#28505])

=== Bug fixes

==== Packaging

* Fixed: rudder-server Java dependencies on SLES15SP6+ are incorrect
    (https://issues.rudder.io/issues/28620[#28620])

==== Documentation

* Fixed: Broken link in user documentation to manage windows registry
    (https://issues.rudder.io/issues/28554[#28554])
* Fixed: Take into account RHEL like OS for the backup process
    (https://issues.rudder.io/issues/28252[#28252])

==== Web - Nodes & inventories

* Fixed: Cannot get inventory from pending node or history
    (https://issues.rudder.io/issues/28668[#28668])
* Fixed: Double table header when we change the columns in the node list
    (https://issues.rudder.io/issues/28664[#28664])
* Fixed: Cannot access to group criteria on Rudder 9.1 with a lot of nodes
    (https://issues.rudder.io/issues/28625[#28625])
* Fixed: tabs from nodes to System Updates & CVEs are not there in 9.1
    (https://issues.rudder.io/issues/28590[#28590])
* Fixed: Node settings cannot be updated from UI when audit log message are mandatory
    (https://issues.rudder.io/issues/28435[#28435])

==== Web - UI & UX

* Fixed: When user is not admin, there is an error when accessing the dashboard
    (https://issues.rudder.io/issues/28647[#28647])
* Fixed: Rewrite 'Parameter ... start or end with whitespace characters' message
    (https://issues.rudder.io/issues/28565[#28565])
* Fixed: On tables showing Compliance, some lines don't return to next line. It moves the compliance score out of the screen.
    (https://issues.rudder.io/issues/28591[#28591])
* Fixed: When we click on a gorup with a long description, the description popup remains
    (https://issues.rudder.io/issues/27787[#27787])
* Fixed: Rules page title is wrapped in medium screen width because of too many buttons
    (https://issues.rudder.io/issues/28523[#28523])
* Fixed: Spinner icon broken on Trigger agent inventory and Trigger agent buttons
    (https://issues.rudder.io/issues/28417[#28417])
* Fixed: When we click on a gorup with a long description, the description popup remains
    (https://issues.rudder.io/issues/27787[#27787])
* Fixed: Node property edition line has cell that are misaligned and have wrong colspan 
    (https://issues.rudder.io/issues/28522[#28522])
* Fixed: Rule's compliance tabs should not be empty if directives or nodes are applied but there is no compliance.
    (https://issues.rudder.io/issues/28481[#28481])
* Fixed: ChartJS tooltips do not disappear
    (https://issues.rudder.io/issues/28521[#28521])
* Fixed: Plugins selection causes header of page to grow
    (https://issues.rudder.io/issues/28512[#28512])
* Fixed: lack of space preservation in compliance value menu
    (https://issues.rudder.io/issues/28428[#28428])
* Fixed: The about page displays license dates with way too much precision
    (https://issues.rudder.io/issues/28433[#28433])

==== Module - system-updates

* Fixed: Missing log for system reboot
    (https://issues.rudder.io/issues/28653[#28653])
* Fixed: Service restart is broken on yum/zypper
    (https://issues.rudder.io/issues/28652[#28652])
* Fixed: Run system updates tests on Windows
    (https://issues.rudder.io/issues/28629[#28629])
* Fixed: Frequent common errors with service restarts on APT systems
    (https://issues.rudder.io/issues/28385[#28385])
* Fixed: Missing yum command run in logs
    (https://issues.rudder.io/issues/28536[#28536])

==== Web - Compliance & node report

* Fixed: Duplicate header for Technical Logs in Rudder 9.1
    (https://issues.rudder.io/issues/28587[#28587])

==== Module - augeas

* Fixed: add documentation for augeas GM
    (https://issues.rudder.io/issues/28594[#28594])

==== Web - Config management

* Fixed: Change logs pagination number of total entries is wrong
    (https://issues.rudder.io/issues/28579[#28579])

==== Miscellaneous

* Fixed: Missing values in security benchmark node parameters CSV export 
    (https://issues.rudder.io/issues/28596[#28596])
* Fixed: More build error for windows
    (https://issues.rudder.io/issues/28585[#28585])
* Fixed: The module fails to build on Windows due do a warning of unused import
    (https://issues.rudder.io/issues/28578[#28578])
* Fixed: Add reboot support for windows nodes using the new rust module
    (https://issues.rudder.io/issues/28568[#28568])
* Fixed: Incorrect filter on the "excluded" updates on Windows
    (https://issues.rudder.io/issues/28558[#28558])
* Fixed:  Directive change log shows whole sectionval diff
    (https://issues.rudder.io/issues/28526[#28526])

==== API

* Fixed: Clicking a change log element to view its details may create a ZonedDateTime-related error notification
    (https://issues.rudder.io/issues/28572[#28572])

==== Web - Maintenance

* Fixed: Viewing rollback event details in the change logs page creates an error log
    (https://issues.rudder.io/issues/28506[#28506])
* Fixed: Manual reports cleaning message has wrong path for webapp logs
    (https://issues.rudder.io/issues/28436[#28436])

==== Module - secedit

* Fixed: add documentation for secedit GM
    (https://issues.rudder.io/issues/28583[#28583])
* Fixed: rename secedit method
    (https://issues.rudder.io/issues/28510[#28510])

==== Plugin manager cli

* Fixed: Update the tar version used by rudder-packages
    (https://issues.rudder.io/issues/28577[#28577])

==== Web - Technique editor

* Fixed: Method block has truncated view of tabs
    (https://issues.rudder.io/issues/28551[#28551])

==== Architecture - Internal libs

* Fixed: Stacktrace when an empty group is created while a change request deleted it
    (https://issues.rudder.io/issues/28147[#28147])

==== Plugins integration

* Fixed: When license status change, the security benchmarks menu is not always updated
    (https://issues.rudder.io/issues/28246[#28246])

==== Generic methods

* Fixed: Agent 9.0.4 fails with Rudder server 8.3
    (https://issues.rudder.io/issues/28555[#28555])

==== Security

* Fixed: ADR for proper initialization of query context in Lift snippets
    (https://issues.rudder.io/issues/28452[#28452])

==== Architecture - Evolution

* Fixed: Add an ADR for dates formats and timezones in Rudder
    (https://issues.rudder.io/issues/28227[#28227])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 9.1.0.beta1 (2026-03-09)

=== Changes


==== Packaging

* Agent is missing a dependency on bzip2
    (https://issues.rudder.io/issues/28251[#28251])

==== Documentation

* Adapt doc for Rudder 9.1
    (https://issues.rudder.io/issues/28490[#28490])
* ADR for modules compatibility
    (https://issues.rudder.io/issues/28369[#28369])
* Render the ADRs
    (https://issues.rudder.io/issues/28361[#28361])
* Publish Rust API doc for our workspace
    (https://issues.rudder.io/issues/28355[#28355])

==== Miscellaneous

* Add API version 23 to API documentation
    (https://issues.rudder.io/issues/28498[#28498])
* Update webapp dependencies 
    (https://issues.rudder.io/issues/28280[#28280])
* Finalize groups & rules migration to rudder-elm-library
    (https://issues.rudder.io/issues/28236[#28236])

==== Architecture - Code maintenance

* Some simple zio-json removal
    (https://issues.rudder.io/issues/28480[#28480])
* Remove pre-8.0 deprecated system variable RUDDER_VERIFY_CERTIFICATES
    (https://issues.rudder.io/issues/28363[#28363])

==== Web - Technique editor

* People use the name field of methods as the first param of the method and hate it
    (https://issues.rudder.io/issues/27700[#27700])

==== Web - Nodes & inventories

* Refactor OS modelisation so that adding an OS is done at only one place
    (https://issues.rudder.io/issues/28443[#28443])

==== rudderc

*  Add the report_data internal variable to windows policies
    (https://issues.rudder.io/issues/28416[#28416])
* Revert the addition of the directiveId in the windows technique parameters
    (https://issues.rudder.io/issues/28316[#28316])

==== Web - UI & UX

* Remove text from DSC icon
    (https://issues.rudder.io/issues/28429[#28429])
* Improve display of Pending nodes table
    (https://issues.rudder.io/issues/28426[#28426])
* Move Elm utility functions to specific modules
    (https://issues.rudder.io/issues/28406[#28406])
* Add a filter to hide techniques without any directives in directives page
    (https://issues.rudder.io/issues/28142[#28142])
* Generate a graphic charter from comments in SCSS source files
    (https://issues.rudder.io/issues/28024[#28024])
* We should be able to fetch token ID and rights from the API token
    (https://issues.rudder.io/issues/27481[#27481])

==== Module - secedit

* add ghost GM for rudder-module-secedit
    (https://issues.rudder.io/issues/28420[#28420])
* add rudder-module-secedit
    (https://issues.rudder.io/issues/27978[#27978])

==== CI

* Run modules tests on ARM
    (https://issues.rudder.io/issues/28395[#28395])
* Use latest nodejs LTS
    (https://issues.rudder.io/issues/28358[#28358])

==== Web - Maintenance

* Improve display of technique event logs
    (https://issues.rudder.io/issues/28383[#28383])
* Add event logs for techniques from the technique editor
    (https://issues.rudder.io/issues/28106[#28106])

==== Web - Config management

* Logs with actor equal to Rudder must be hidden by default
    (https://issues.rudder.io/issues/28114[#28114])
* Allow to disable a node even if its internal state is inconsistent
    (https://issues.rudder.io/issues/28340[#28340])

==== Module - system-updates

* Add exclusions in system-updates
    (https://issues.rudder.io/issues/28334[#28334])

==== Security

* Improve the "reset status to be able to accept a different key" node feature
    (https://issues.rudder.io/issues/26653[#26653])

==== Module - common

* Add useful info CLI in modules
    (https://issues.rudder.io/issues/28326[#28326])

==== Agent

* update Makefile with rudder-module-secedit
    (https://issues.rudder.io/issues/28327[#28327])

==== API

* Update API doc tooling
    (https://issues.rudder.io/issues/28290[#28290])
* Rudder server Instance ID does not show up in the node API
    (https://issues.rudder.io/issues/28131[#28131])

==== Build & Deps - Rust

* Update to Rust 1.93.0
    (https://issues.rudder.io/issues/28230[#28230])

==== Architecture - Evolution

* Add tenant information to configuration objects
    (https://issues.rudder.io/issues/28035[#28035])

=== Bug fixes

==== Miscellaneous

* Fixed: Embedded jq fails with missing library
    (https://issues.rudder.io/issues/28412[#28412])
* Fixed: libxml2 does not exist as dependency in Ubuntu26, but libxml2-16 instead
    (https://issues.rudder.io/issues/28347[#28347])
* Fixed: Add support for Ubuntu 26.04
    (https://issues.rudder.io/issues/28317[#28317])
* Fixed: The module is unable to build when targeting windows release
    (https://issues.rudder.io/issues/28477[#28477])
* Fixed: The groups' "Export to CSV" button downloads an empty file when the user navigates directly to any given group's page
    (https://issues.rudder.io/issues/28241[#28241])
* Fixed:  	Add the "excludes" feature to the Windows Update Agent module
    (https://issues.rudder.io/issues/28350[#28350])
* Fixed: Add a run-module command to the rudder-moddule-system-update CLI 
    (https://issues.rudder.io/issues/28266[#28266])
* Fixed: Error when unserializing change request
    (https://issues.rudder.io/issues/27974[#27974])
* Fixed: CI fails in multiple webapp tests due to implicit timezone
    (https://issues.rudder.io/issues/28311[#28311])
* Fixed: Rust dependency update
    (https://issues.rudder.io/issues/28278[#28278])
* Fixed: Rust dependency update
    (https://issues.rudder.io/issues/28278[#28278])
* Fixed: Rust dependency update
    (https://issues.rudder.io/issues/28278[#28278])

==== Packaging

* Fixed: Incorrect rudder-server package openjdk dependency on SLES15 sp6+
    (https://issues.rudder.io/issues/28409[#28409])
* Fixed: Missing dependency on bzip2
    (https://issues.rudder.io/issues/28388[#28388])
* Fixed: SLES16 has broken dependency on pcre2
    (https://issues.rudder.io/issues/28257[#28257])

==== Security

* Fixed: Bump embedded openssl
    (https://issues.rudder.io/issues/28375[#28375])
* Fixed: Some npm build vulnerabilities in sass and gulp-svgmin
    (https://issues.rudder.io/issues/28487[#28487])
* Fixed: Ignore build vulnerabilities in 9.1 from sassdoc
    (https://issues.rudder.io/issues/28483[#28483])
* Fixed: CurrentUser can have unknown actor and query context in snippets
    (https://issues.rudder.io/issues/28404[#28404])
* Fixed: Change log for manual policy generation event has unknown actor
    (https://issues.rudder.io/issues/28462[#28462])

==== Module - augeas

* Fixed: Agent segfault on ARMv7 + Debian 13
    (https://issues.rudder.io/issues/27924[#27924])
* Fixed: Add a global operator for reversing the check outcome
    (https://issues.rudder.io/issues/28149[#28149])

==== Documentation

* Fixed: Doc on Rudder versionning is invalid
    (https://issues.rudder.io/issues/28366[#28366])
* Fixed: We should add the notion of tier in supported OS
    (https://issues.rudder.io/issues/28269[#28269])
* Fixed: Documentation still mention policy instance
    (https://issues.rudder.io/issues/28126[#28126])
* Fixed: Remove images in API doc
    (https://issues.rudder.io/issues/28289[#28289])

==== Module - secedit

* Fixed: add documentation for rudder-module-secedit
    (https://issues.rudder.io/issues/28408[#28408])
* Fixed: fix broken diff for rudder-module-secedit
    (https://issues.rudder.io/issues/28466[#28466])
* Fixed: fix windows path splitting in rudder-module-secedit
    (https://issues.rudder.io/issues/28376[#28376])

==== Generic methods

* Fixed: Add module features detection bundle
    (https://issues.rudder.io/issues/28493[#28493])
* Fixed: permissions_posix_acls_absent can crash the rudder agent when applied to a single file
    (https://issues.rudder.io/issues/28309[#28309])

==== Web - UI & UX

* Fixed: Make the display of a Group description consistent with the description of other items.
    (https://issues.rudder.io/issues/28474[#28474])
* Fixed: Rename "Short description" and "Description" fields in Rule details
    (https://issues.rudder.io/issues/28469[#28469])
* Fixed: Rename "Short description" and "Description" fields in Directive details
    (https://issues.rudder.io/issues/28458[#28458])
* Fixed: Statistics numbers are not aligned on small screens
    (https://issues.rudder.io/issues/28457[#28457])
* Fixed: HTML in tooltips is no longer rendered
    (https://issues.rudder.io/issues/28453[#28453])
* Fixed: The foreach interface if broken when there are more than 3 keys
    (https://issues.rudder.io/issues/28174[#28174])
* Fixed: Remove unnecessary scrollbars from the Plugins page
    (https://issues.rudder.io/issues/28431[#28431])
* Fixed: Adjust spacing in the directives page structure
    (https://issues.rudder.io/issues/28425[#28425])
* Fixed: No line breaks in the lines of node inventory tables
    (https://issues.rudder.io/issues/28410[#28410])
* Fixed: Timezone in change/event logs timepicker is not the same as in table
    (https://issues.rudder.io/issues/28198[#28198])
* Fixed: Add an ‘Activity’ section to the dashboard
    (https://issues.rudder.io/issues/28308[#28308])
* Fixed: Datatable error on localeCompare
    (https://issues.rudder.io/issues/28362[#28362])
* Fixed: Adding software column on node list doesn't refresh is it contains a space
    (https://issues.rudder.io/issues/28050[#28050])
* Fixed: Make compliance text in dashboard correct
    (https://issues.rudder.io/issues/28295[#28295])
* Fixed: Remove useless graphs
    (https://issues.rudder.io/issues/28036[#28036])

==== Web - Config management

* Fixed: Change logs automatically created should be filtered
    (https://issues.rudder.io/issues/28422[#28422])
* Fixed: Changes logs user service should filter on "Rudder system account" by default too
    (https://issues.rudder.io/issues/28403[#28403])

==== Architecture - Dependencies

* Fixed: False positive npm vulnerability on minimatch and glob
    (https://issues.rudder.io/issues/28463[#28463])
* Fixed: GaugeJS library is no longer used
    (https://issues.rudder.io/issues/28460[#28460])
* Fixed: Some npm dependencies should be in devDependencies 
    (https://issues.rudder.io/issues/28459[#28459])

==== Module - common

* Fixed: Add a schedule module
    (https://issues.rudder.io/issues/27927[#27927])

==== Web - Technique editor

* Fixed: When the webapp fails to compile a technique, it does not notify the user anywhere outside the webapp log file
    (https://issues.rudder.io/issues/28060[#28060])
* Fixed: ‘Technique is invalid’ message is insufficient
    (https://issues.rudder.io/issues/27877[#27877])

==== Web - Nodes & inventories

* Fixed: After restart, windows 11 group is empty and os name is os.name.Windows in place of Windows 11
    (https://issues.rudder.io/issues/28419[#28419])
* Fixed: Policy Server ID appears twice in the Node Inventory 
    (https://issues.rudder.io/issues/28069[#28069])

==== API

* Fixed: EventLogAPI has info log for a debug value 
    (https://issues.rudder.io/issues/28401[#28401])
* Fixed: API endpoint to query API accounts from token is not needed
    (https://issues.rudder.io/issues/28353[#28353])

==== Plugin manager cli

* Fixed: Confusing message by rudder package when no credential is set
    (https://issues.rudder.io/issues/27783[#27783])
* Fixed: Lower the log level if no credentials
    (https://issues.rudder.io/issues/28299[#28299])

==== CI

* Fixed: Broken API doc redirect
    (https://issues.rudder.io/issues/28368[#28368])
* Fixed: Add automatic Windows methods testing using the new framework in CI
    (https://issues.rudder.io/issues/28357[#28357])
* Fixed: Enable color for maven & js in CI
    (https://issues.rudder.io/issues/28321[#28321])
* Fixed: Timeout of TestJsEngine occurs with 1 second configuration
    (https://issues.rudder.io/issues/28253[#28253])
* Fixed: CI tests fail due to misconfigured date format in TestMigrateNodeAcceptationInventories
    (https://issues.rudder.io/issues/28244[#28244])

==== rudderc

* Fixed: Add more local debug logs when an exception is thrown inside a windows technique
    (https://issues.rudder.io/issues/28329[#28329])

==== Agent

* Fixed: Rust dependency update
    (https://issues.rudder.io/issues/28325[#28325])
* Fixed: fix warning for RUSTSEC-2026-0009 
    (https://issues.rudder.io/issues/28305[#28305])
* Fixed: Rust dependency update
    (https://issues.rudder.io/issues/28304[#28304])
* Fixed: Rename the internal agent_state consts module to constants
    (https://issues.rudder.io/issues/28282[#28282])
* Fixed: Generate openssl salt as hexa
    (https://issues.rudder.io/issues/28470[#28470])
* Fixed: rudder agent reset -p : typo
    (https://issues.rudder.io/issues/28213[#28213])

==== Containers

* Fixed: Force setuptools to be older than version 82 until avocado fixes the import in python 3.13
    (https://issues.rudder.io/issues/28319[#28319])

==== Architecture - Code maintenance

* Fixed: Deadlock on JGitInternalException : Garbage collection failed.
    (https://issues.rudder.io/issues/28291[#28291])
* Fixed: Missing header and junit marker in tests
    (https://issues.rudder.io/issues/28292[#28292])

==== Module - system-updates

* Fixed: Server ignore inventory of factory reset nodes - new inventory processing stopped
    (https://issues.rudder.io/issues/28277[#28277])

==== Web - Maintenance

* Fixed: Scheduled job log info renders non human readable duration
    (https://issues.rudder.io/issues/28202[#28202])
* Fixed: Group category can no longer be created
    (https://issues.rudder.io/issues/28250[#28250])

==== Techniques

* Fixed: Wrong name for ed25519-sk key type
    (https://issues.rudder.io/issues/28400[#28400])
* Fixed: Technique Package sources and settings (APT) doesn't manage HTTPS proxy
    (https://issues.rudder.io/issues/28185[#28185])
* Fixed: Outcome collisions in Linux packages built-in techniques
    (https://issues.rudder.io/issues/28228[#28228])

==== System techniques

* Fixed: Relay « Cannot propagate shared files »
    (https://issues.rudder.io/issues/26597[#26597])
* Fixed: Broken reload of apache service when updating nodescerts.pem
    (https://issues.rudder.io/issues/28389[#28389])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 9.1.0.alpha1 (2026-01-26)

=== Changes


==== Packaging

* Bump to CFEngine 3.24.3
    (https://issues.rudder.io/issues/28103[#28103])
* Upgrade curl
    (https://issues.rudder.io/issues/28096[#28096])
* Update to Jetty 12
    (https://issues.rudder.io/issues/27925[#27925])
* Update C dependencies
    (https://issues.rudder.io/issues/27807[#27807])
* First rust toolchain and deps update
    (https://issues.rudder.io/issues/27800[#27800])

==== Security

* Add information about last access for API accounts 
    (https://issues.rudder.io/issues/28179[#28179])

==== Miscellaneous

* Export Rules table to CSV
    (https://issues.rudder.io/issues/28133[#28133])
* Test equality between the json encoding of zio-json and lift-json to validate the migration
    (https://issues.rudder.io/issues/27741[#27741])

==== Web - UI & UX

*  Export groups dashboard table to CSV
    (https://issues.rudder.io/issues/27960[#27960])
* Replace main color codes with SCSS variables
    (https://issues.rudder.io/issues/27834[#27834])

==== Architecture - Code maintenance

* Changing inheritMode on a property should start generation
    (https://issues.rudder.io/issues/28189[#28189])
* Improve Rust & system build scripts
    (https://issues.rudder.io/issues/27944[#27944])
* Remove heartbeat and port to zio-json corresponding API
    (https://issues.rudder.io/issues/27981[#27981])

==== Architecture - Evolution

* Add an adr for zio-json migration
    (https://issues.rudder.io/issues/28137[#28137])

==== CI

* Update the target test JVMs
    (https://issues.rudder.io/issues/28134[#28134])

==== Documentation

* Add an ADR template to the repo
    (https://issues.rudder.io/issues/28123[#28123])
* Update Rudder webapp documentation 
    (https://issues.rudder.io/issues/27858[#27858])

==== Generic methods

* New logger without suffix
    (https://issues.rudder.io/issues/28116[#28116])

==== System integration

* Allow to override server certiicate even if cert_validation is not enabled
    (https://issues.rudder.io/issues/28107[#28107])

==== Build & Deps - Rust

* Update to Rust 1.92.0
    (https://issues.rudder.io/issues/28031[#28031])
* Bump to Rust 1.91.0
    (https://issues.rudder.io/issues/27825[#27825])

==== Architecture - Dependencies

* Update front-end dependencies
    (https://issues.rudder.io/issues/27817[#27817])
* Update scala dependencies - 9.1
    (https://issues.rudder.io/issues/27808[#27808])

=== Bug fixes

==== Agent

* Fixed: Linux agent breaks on Y2038
    (https://issues.rudder.io/issues/28030[#28030])
* Fixed: misspell in documentation $ rudder agent restore --help
    (https://issues.rudder.io/issues/28124[#28124])

==== Packaging

* Fixed: Add support for SLES 16
    (https://issues.rudder.io/issues/28153[#28153])
* Fixed: Incorrect arm32 detection in openssl builds
    (https://issues.rudder.io/issues/28099[#28099])
* Fixed: Redirect module output to install log
    (https://issues.rudder.io/issues/28023[#28023])

==== Documentation

* Fixed: Document the new HTTPS protocol
    (https://issues.rudder.io/issues/28097[#28097])
* Fixed: Correct documentation about user disabling/deletion
    (https://issues.rudder.io/issues/28075[#28075])
* Fixed: Reference manual on installation should explain what Relay are used for
    (https://issues.rudder.io/issues/28032[#28032])
* Fixed: Add an adr for new logger
    (https://issues.rudder.io/issues/28125[#28125])
* Fixed: Expliclty write that method template from file option only support UTF-8 format
    (https://issues.rudder.io/issues/27652[#27652])

==== Web - Technique editor

* Fixed: Condition generated by foreach iterations are not canonified
    (https://issues.rudder.io/issues/28177[#28177])

==== Web - Compliance & node report

* Fixed: Directive present in 2 different rules applied on same node show up as grey “No data available” in compliance
    (https://issues.rudder.io/issues/27762[#27762])

==== Architecture - Code maintenance

* Fixed: Typo in named parameter
    (https://issues.rudder.io/issues/28182[#28182])
* Fixed: Scala 9.1 needs more information about errors
    (https://issues.rudder.io/issues/27970[#27970])

==== Module - common

* Fixed: Remove error log in case of error report
    (https://issues.rudder.io/issues/28143[#28143])

==== Module - augeas

* Fixed: Augeas report gets duplicated in second instance
    (https://issues.rudder.io/issues/27918[#27918])
* Fixed: Missing escaping in raugeas dsl
    (https://issues.rudder.io/issues/28108[#28108])

==== CI

* Fixed: Try to use colors in CI builds
    (https://issues.rudder.io/issues/28105[#28105])
* Fixed: Set version of typos-cli
    (https://issues.rudder.io/issues/28091[#28091])
* Fixed: Update cargo-deny
    (https://issues.rudder.io/issues/28087[#28087])

==== Web - Maintenance

* Fixed: Cannot create technique category in active tree
    (https://issues.rudder.io/issues/28070[#28070])

==== Web - Nodes & inventories

* Fixed: Count inconsistency between pending nodes, dashboard, and LDAP content
    (https://issues.rudder.io/issues/28076[#28076])

==== Module - system-updates

* Fixed: Add Windows Update Agent support to the system-updates module
    (https://issues.rudder.io/issues/28054[#28054])

==== Generic methods

* Fixed: Generic method “File copy from rudder shared folder” produces bogus error.
    (https://issues.rudder.io/issues/28053[#28053])
* Fixed: Add windows support to the library tests
    (https://issues.rudder.io/issues/27760[#27760])

==== System techniques

* Fixed: Errors in system techniques
    (https://issues.rudder.io/issues/27660[#27660])

==== Techniques

* Fixed: manageKeyValueFile can't be applied twice 
    (https://issues.rudder.io/issues/28156[#28156])
* Fixed: sshKeyDistribution technique doesn't support ed25519-sk key type
    (https://issues.rudder.io/issues/28068[#28068])
* Fixed: “Users” standard technique produces “unexpected” reports when secondary group specified
    (https://issues.rudder.io/issues/27920[#27920])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

