= Change logs for Rudder 9.1==  Rudder 9.1.0.alpha1 (2026-01-26)

=== Changes


==== Packaging

* Bump to CFEngine 3.24.3
    (https://issues.rudder.io/issues/28103[#28103])
* Upgrade curl
    (https://issues.rudder.io/issues/28096[#28096])
* Update to Jetty 12
    (https://issues.rudder.io/issues/27925[#27925])
* Update C dependencies
    (https://issues.rudder.io/issues/27807[#27807])
* First rust toolchain and deps update
    (https://issues.rudder.io/issues/27800[#27800])

==== Security

* Add information about last access for API accounts 
    (https://issues.rudder.io/issues/28179[#28179])

==== Miscellaneous

* Export Rules table to CSV
    (https://issues.rudder.io/issues/28133[#28133])
* Test equality between the json encoding of zio-json and lift-json to validate the migration
    (https://issues.rudder.io/issues/27741[#27741])

==== Web - UI & UX

*  Export groups dashboard table to CSV
    (https://issues.rudder.io/issues/27960[#27960])
* Replace main color codes with SCSS variables
    (https://issues.rudder.io/issues/27834[#27834])

==== Architecture - Code maintenance

* Changing inheritMode on a property should start generation
    (https://issues.rudder.io/issues/28189[#28189])
* Improve Rust & system build scripts
    (https://issues.rudder.io/issues/27944[#27944])
* Remove heartbeat and port to zio-json corresponding API
    (https://issues.rudder.io/issues/27981[#27981])

==== Architecture - Evolution

* Add an adr for zio-json migration
    (https://issues.rudder.io/issues/28137[#28137])

==== CI

* Update the target test JVMs
    (https://issues.rudder.io/issues/28134[#28134])

==== Documentation

* Add an ADR template to the repo
    (https://issues.rudder.io/issues/28123[#28123])
* Update Rudder webapp documentation 
    (https://issues.rudder.io/issues/27858[#27858])

==== Generic methods

* New logger without suffix
    (https://issues.rudder.io/issues/28116[#28116])

==== System integration

* Allow to override server certiicate even if cert_validation is not enabled
    (https://issues.rudder.io/issues/28107[#28107])

==== Build & Deps - Rust

* Update to Rust 1.92.0
    (https://issues.rudder.io/issues/28031[#28031])
* Bump to Rust 1.91.0
    (https://issues.rudder.io/issues/27825[#27825])

==== Architecture - Dependencies

* Update front-end dependencies
    (https://issues.rudder.io/issues/27817[#27817])
* Update scala dependencies - 9.1
    (https://issues.rudder.io/issues/27808[#27808])

=== Bug fixes

==== Agent

* Fixed: Linux agent breaks on Y2038
    (https://issues.rudder.io/issues/28030[#28030])
* Fixed: misspell in documentation $ rudder agent restore --help
    (https://issues.rudder.io/issues/28124[#28124])

==== Packaging

* Fixed: Add support for SLES 16
    (https://issues.rudder.io/issues/28153[#28153])
* Fixed: Incorrect arm32 detection in openssl builds
    (https://issues.rudder.io/issues/28099[#28099])
* Fixed: Redirect module output to install log
    (https://issues.rudder.io/issues/28023[#28023])

==== Documentation

* Fixed: Document the new HTTPS protocol
    (https://issues.rudder.io/issues/28097[#28097])
* Fixed: Correct documentation about user disabling/deletion
    (https://issues.rudder.io/issues/28075[#28075])
* Fixed: Reference manual on installation should explain what Relay are used for
    (https://issues.rudder.io/issues/28032[#28032])
* Fixed: Add an adr for new logger
    (https://issues.rudder.io/issues/28125[#28125])
* Fixed: Expliclty write that method template from file option only support UTF-8 format
    (https://issues.rudder.io/issues/27652[#27652])

==== Web - Technique editor

* Fixed: Condition generated by foreach iterations are not canonified
    (https://issues.rudder.io/issues/28177[#28177])

==== Web - Compliance & node report

* Fixed: Directive present in 2 different rules applied on same node show up as grey “No data available” in compliance
    (https://issues.rudder.io/issues/27762[#27762])

==== Architecture - Code maintenance

* Fixed: Typo in named parameter
    (https://issues.rudder.io/issues/28182[#28182])
* Fixed: Scala 9.1 needs more information about errors
    (https://issues.rudder.io/issues/27970[#27970])

==== Module - common

* Fixed: Remove error log in case of error report
    (https://issues.rudder.io/issues/28143[#28143])

==== Module - augeas

* Fixed: Augeas report gets duplicated in second instance
    (https://issues.rudder.io/issues/27918[#27918])
* Fixed: Missing escaping in raugeas dsl
    (https://issues.rudder.io/issues/28108[#28108])

==== CI

* Fixed: Try to use colors in CI builds
    (https://issues.rudder.io/issues/28105[#28105])
* Fixed: Set version of typos-cli
    (https://issues.rudder.io/issues/28091[#28091])
* Fixed: Update cargo-deny
    (https://issues.rudder.io/issues/28087[#28087])

==== Web - Maintenance

* Fixed: Cannot create technique category in active tree
    (https://issues.rudder.io/issues/28070[#28070])

==== Web - Nodes & inventories

* Fixed: Count inconsistency between pending nodes, dashboard, and LDAP content
    (https://issues.rudder.io/issues/28076[#28076])

==== Module - system-updates

* Fixed: Add Windows Update Agent support to the system-updates module
    (https://issues.rudder.io/issues/28054[#28054])

==== Generic methods

* Fixed: Generic method “File copy from rudder shared folder” produces bogus error.
    (https://issues.rudder.io/issues/28053[#28053])
* Fixed: Add windows support to the library tests
    (https://issues.rudder.io/issues/27760[#27760])

==== System techniques

* Fixed: Errors in system techniques
    (https://issues.rudder.io/issues/27660[#27660])

==== Techniques

* Fixed: manageKeyValueFile can't be applied twice 
    (https://issues.rudder.io/issues/28156[#28156])
* Fixed: sshKeyDistribution technique doesn't support ed25519-sk key type
    (https://issues.rudder.io/issues/28068[#28068])
* Fixed: “Users” standard technique produces “unexpected” reports when secondary group specified
    (https://issues.rudder.io/issues/27920[#27920])

=== Release notes

This is a bug fix release in the 9.1 series and therefore all installations of 9.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

