= Gathering EC2 information

== Goal

This inventory hook allows gathering information about available data on the EC2 instance, using the following url to view all categories of instance metadata from within a running instance: 

----
http://169.254.169.254/latest/
----

== Property

This hook provides three properties named `AWS-metadata` `AWS-dynamic` `AWS-user-data` which gets a value of some of the metadata itemswith JSON format.

=== AWS-metadata 
* It shows a collection of network and instance related values and it is in here where things get a bit more interesting.

----
"AWS-meta-data": {
    "services": {
      "domain": "amazonaws.com",
      "partition": "aws"
    },
    "instance-type": "t2.small",
    "instance-id": "i-04b26d4a8993e4c54",
    "local-hostname": "ip-10-0-1-86.eu-west-1.compute.internal",
    "network": {
      "interfaces": {
        "macs": {
          "02:1e:c8:e2:67:14": {
            "public-hostname": "ec2-63-35-216-174.eu-west-1.compute.amazonaws.com",
            "vpc-ipv4-cidr-blocks": "10.0.0.0/16"
          }
        }
      }
    }
----

=== AWS-dynamic
* With dynamic data, the options still useful to retrievr a resume like document, in a JSON format.

----
"AWS-dynamic": {
    "instance-identity": {
      "document": {
        "devpayProductCodes": null,
        "availabilityZone": "eu-west-1a",
        "instanceId": "i-04b26d4a8993e4c54",
        "region": "eu-west-1",
        "marketplaceProductCodes": null,
        "privateIp": "10.0.1.86",
        "version": "2017-09-30",
        "architecture": "x86_64",
        "billingProducts": null,
        "kernelId": null
      }
    }
  }
----

=== AWS-user-data
* In this data, you can access to specific parameters or script configuration that is needed for your EC2 instances.

----
 "AWS-user-data": {
    "sudo ./rudder-setup setup-server latest": "#!/bin/bash\nsudo wget https://repository.rudder.io/tools/rudder-setup\nsudo chmod +x rudder-setup\nsudo ./rudder-setup setup-server latest\n"
}
----
 

