= Change logs for Rudder 4.3

Rudder 4.3 has reached public End of Life the 11th January 2019.
It is currently maintained as part of extended support included in
https://www.normation.com/en/rudder/subscription/[Rudder subscription].

This page provides a summary of changes for each version. Previous beta
and rc versions are listed below for convenience.

*Main new features in Rudder 4.3:*

* *Technique Parameters:* You can now add parameters to your Techniques
created with the Technique editor. The value of theses parameters will
be set in Directives, making your Techniques much more versatile and
expressive and giving you access to feature that were only available to
classic Techniques.
* *Multi version/mode Directives:* You can now apply Directives with
different versions and different policy mode _on the same node_. This
allow easy migration (to a new version, from Audit to Enforce) that was
previously impossible.
* *Authorization system for API accounts:* Choose between read-only or
full access. A plugin will be available soon in order to allow you more
finely grained authorization.
* *Node properties from inventory:* Node properties can be automatically
provided by the inventory data from the node.
* *Node lifecycle:* You can define a state for each Node managed by
Rudder (provisioning, pending removal, disabled etc.). This can be used
to build groups and apply configuration according to the Node current
state. Also disabled Nodes are not counted in compliance reports, so you
are not bothered by offline Nodes when checking compliance.
* *Group based on Groups*: You can now define that a Group should
contain the Nodes of another Group, making it easier to manage a complex
set of Nodes.
* *Graphs on the dashboard are now clickable*: You can access the list
of nodes in a category by clicking on parts of the graphs.
* *Import/Export of techniques in the Technique Editor*: There is now a
button to export or import a technique in the Technique Editor, allowing
sharing techniques easily. Be careful, this import/export only works
between servers running the same Rudder version.
* *IPv6 support by default:* Rudder is now completely compatible with
IPv6 on the agent side as well as server side.
* *Hooks on Techniques:* When you write a Technique by hand, you can add
pre- and post- hooks in it that will be executed once per Technique,
even if you applied it in several directives.
* *Use system Perl:* On recent systems, rudder-agent does not embed Perl
anymore, so it uses an up to date version of Perl more integrated to
your system. All the needed dependencies are either declared (for the
common ones) or still embedded. On a side note, it makes it easier to
build a rudder-agent package (which size goes down from 12MB to 4MB!).
* *Rudder agent services based on systemd:* On systemd based os, we
switched from SysV init system to systemd, to make rudder-agent more
integrated to your system.
* *Time all actions made by the agent:* A new option (-T) added to
``rudder agent'' command line, to display how long an action took and
find what makes a run slow.
* *Renaming of all generic methods:* We changed for a clearer and more
logic name scheme in all our generic methods in the Technique editor.
* *Simplified logger for Techniques:* We changed the way we do reporting
for Techniques from Technique editor with a much simpler way, which
should be faster and also fix some reporting issues (ie: when you use
variables in your reports).
* *Plenty of library updates / cleaning / architecture changes*: Either
on web app or in rudder-agent we upgraded some dependencies, refactored
some code, to provide you a more secure, maintainable and faster Rudder.

*Installing, upgrading and testing*

* Install docs:
https://www.rudder-project.org/doc-4.3/_installation.html
* Upgrade docs:
https://www.rudder-project.org/doc-4.3/_upgrade_rudder.html
* Download links:
https://www.rudder-project.org/site/get-rudder/downloads/

We also recommend using the
https://github.com/Normation/rudder-vagrant[Rudder Vagrant] config if
you want a quick and easy way to get an installation for testing.

*Operating systems supported*

This version provides packages for these operating systems:

* Rudder server and Rudder relay: *Debian 8, Debian 9, RHEL/CentOS 6,
RHEL/CentOS 7 (64 bits), SLES 11, SLES 12, Ubuntu 14.04, Ubuntu 16.04*
* Rudder agent: all of the above plus *Debian 5, Debian 6, Debian 7
RHEL/CentOS 3, RHEL/CentOS 5, CentOS 7 (32 bits), SLES 10, SLES 12,
Ubuntu 10.04, Ubuntu 12.04, Ubuntu 18.04*
* Rudder agent (binary packages available from
(http://www.normation.com[Normation]): *Windows Server 2008R2-2016, AIX
5-6-7*

*Note*: As of Rudder 4.3, the rudder agent packages are no longer
available on Fedora 18 and Ubuntu 12.10.

*Special thanks*

* Thanks to Maxime Longuet from https://www.itika.net/[Itika] for
sponsoring the _node lifecycle_ feature!

== Rudder 4.3.12 (2019-05-14)

=== Changes

==== Techniques

* Port MOTD Technique to DSC
    (https://issues.rudder.io/issues/14313[#14313])

=== Bug fixes

==== Packaging

* Fixed: ncf-api-virtualenv does not have a group created
    (https://issues.rudder.io/issues/11126[#11126])
* Fixed: Debian 8 packages fail to build  
    (https://issues.rudder.io/issues/14754[#14754])

==== Performance and scalability

* Fixed: Correct disk usage in rudder configuration file 
    (https://issues.rudder.io/issues/14844[#14844])
* Fixed: Default archive retention is too large, which cause very large disk usage 
    (https://issues.rudder.io/issues/14834[#14834])

==== Web - Config management

* Fixed: Accepting a change request on dynamic group, make the group empty leads an invalid policy generation 
    (https://issues.rudder.io/issues/14758[#14758])
* Fixed: When restoring archive (full or groups) dynamic groups are created empty
    (https://issues.rudder.io/issues/4480[#4480])

==== Web - Maintenance

* Fixed: Invalid comparision of String and Option[String] in HistorizationService 
    (https://issues.rudder.io/issues/14770[#14770])

==== Techniques

* Fixed: Technique "SSH authorized keys" creates home directory with perms root:root when it does not exists yet 
    (https://issues.rudder.io/issues/14732[#14732])

==== Agent

* Fixed: Rudder agent check cannot restore saved uuid on AIX 
    (https://issues.rudder.io/issues/14763[#14763])
* Fixed: Rudder agent check does not repair policies if they are broken 
    (https://issues.rudder.io/issues/14692[#14692])

==== Technique editor - UI/UX

* Fixed: The deprecated tooltip doesn't say why it is deprecated
    (https://issues.rudder.io/issues/13031[#13031])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 4.3 series and therefore all installations of 4.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 4.3.11 (2019-04-15)

=== Changes

==== Techniques

* Support separated policy generation for technique "Variable from JSON file (dict)"
    (https://issues.rudder.io/issues/14160[#14160])
* Support separated policy generation for technique "Variable from JSON file (dict)"
    (https://issues.rudder.io/issues/14160[#14160])

==== Generic methods

* Add bundle dedicated to the ncf tests
    (https://issues.rudder.io/issues/14311[#14311])
* Add systemd commands to the library of standard system command paths
    (https://issues.rudder.io/issues/14401[#14401])
* Improve service_{start/stop} tests
    (https://issues.rudder.io/issues/14323[#14323])

=== Bug fixes

==== Packaging

* Fixed: When installing rudder-agent, there's a long wait of run interval/2, so up to several hours
    (https://issues.rudder.io/issues/14644[#14644])
* Fixed: During installation of the agent, when staring "rudder agent" service, there is numerous error about missing '/opt/rudder/etc/uuid.hive' file
    (https://issues.rudder.io/issues/14616[#14616])
* Fixed: Debian 8 backports repository does not exist anymore, breaking our builds
    (https://issues.rudder.io/issues/14608[#14608])
* Fixed: Error message when installing or upgrading Rudder server about missing pid file
    (https://issues.rudder.io/issues/13767[#13767])
* Fixed: Error message when installing rudder-agent  on rpm based systems due to missing directory '/var/rudder/inventories'
    (https://issues.rudder.io/issues/14348[#14348])

==== Agent

* Fixed: Slackware agent depends on mysql
    (https://issues.rudder.io/issues/14472[#14472])

==== System techniques

* Fixed: Agent connection cache does not work, and does not improve performance as expected
    (https://issues.rudder.io/issues/14342[#14342])
* Fixed: Bad reporting mode for "Monitoring; No Rudder monitoring information to share with the server"
    (https://issues.rudder.io/issues/14532[#14532])
* Fixed: Missing "update" reports on node
    (https://issues.rudder.io/issues/12137[#12137])

==== System integration

* Fixed: Allow changing cf-serverd loglevel and set info as default
    (https://issues.rudder.io/issues/8529[#8529])
* Fixed: Only one Node below a Rudder server can be run through remote run API
    (https://issues.rudder.io/issues/14391[#14391])
* Fixed: Windows 10 inventory is not fully supported
    (https://issues.rudder.io/issues/14295[#14295])

==== Plugins integration

* Fixed: Typo in rudder-pkg when package version is incompatible
    (https://issues.rudder.io/issues/14408[#14408])

==== Documentation

* Fixed: uuid.hive is not present afet an install or an upgradie ofrudder agent to latest 4.1.x, 4.3.x and 5.0.x on rpm system purges the uuid.hive
    (https://issues.rudder.io/issues/14264[#14264])

==== Web - Config management

* Fixed: Policies generated for Rudder server have wrong permissions
    (https://issues.rudder.io/issues/14594[#14594])

==== Web - Compliance & node report

* Fixed: Improve message on Node compliance details when  reports are outdated
    (https://issues.rudder.io/issues/14380[#14380])
* Fixed: Missing report on generic method "command exec" with $()
    (https://issues.rudder.io/issues/14390[#14390])

==== Web - Nodes & inventories

* Fixed: Incoherent state when accepting a Node, where node is accepted but now available in UI (error when creating Node entry)
    (https://issues.rudder.io/issues/14430[#14430])
* Fixed: Error about failed  move of machine inventory doesn't give sufficient context information
    (https://issues.rudder.io/issues/14522[#14522])

==== Performance and scalability

* Fixed: If a rule targets too many groups, policy generation fails
    (https://issues.rudder.io/issues/14392[#14392])
* Fixed: Cron job checking rudder agent health, is ran every  5 minutes exactly, causing resource usage spike
    (https://issues.rudder.io/issues/14258[#14258])

==== Technique editor - UI/UX

* Fixed: Error in technique editor when there is  "$()" in  a parameter of a method
    (https://issues.rudder.io/issues/14549[#14549])

==== Generic methods

* Fixed: Policy generation fails after upgrade  to 4.3: Undefined bundle lines_present
    (https://issues.rudder.io/issues/14548[#14548])
* Fixed: Expected repaired class in ncf tests are not correctly defined
    (https://issues.rudder.io/issues/14538[#14538])
* Fixed: Reporting when executing severspec is not correct in ncf tests
    (https://issues.rudder.io/issues/14537[#14537])
* Fixed: monitoring.csv accumulate temporary files that can blow up the filesystem
    (https://issues.rudder.io/issues/13716[#13716])

==== Generic methods - Package Management

* Fixed: Broken yum usage with old package promises on CentOS
    (https://issues.rudder.io/issues/14546[#14546])

==== Web - Technique editor

* Fixed: Reporting fails on NCF when service start/stop is guarded by a class
    (https://issues.rudder.io/issues/14404[#14404])

==== Generic methods - File Management

* Fixed: Improve method 'file copy from shared files'  parameters documentation
    (https://issues.rudder.io/issues/14361[#14361])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 4.3 series and therefore all installations of 4.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 4.3.10 (2019-02-28)

=== Changes

==== Architecture - Internal libs

* Remove deprecated (and not use) code causing warning
    (https://issues.rudder.io/issues/14291[#14291])

==== Generic methods - File Management

* Add a generic method that displays selected lines from a file in reports
    (https://issues.rudder.io/issues/14357[#14357])

==== Generic methods

* Add serverspec tests to the ncf ones
    (https://issues.rudder.io/issues/14314[#14314])

=== Bug fixes

==== System integration

* Fixed: Patch cf-serverd to change loglevel on agent refusal
    (https://issues.rudder.io/issues/8529[#8529])
* Fixed: qa-test break because of repository layout change
    (https://issues.rudder.io/issues/14289[#14289])

==== Packaging

* Fixed: Never modify policy_server.dat on upgrade
    (https://issues.rudder.io/issues/14337[#14337])
* Fixed: "/var/rudder/inventories: no such dir" error message on first run
    (https://issues.rudder.io/issues/14257[#14257])

==== Documentation

* Fixed: Typo in "Replacement" in doc
    (https://issues.rudder.io/issues/14137[#14137])
* Fixed: Root of webapp docs changed
    (https://issues.rudder.io/issues/14284[#14284])
* Fixed: variable_dict_from_file: Path of file is unclear if relative or absolute
    (https://issues.rudder.io/issues/14117[#14117])

==== Web - Nodes & inventories

* Fixed: Windows 2019 doesn't show up correctly in node list
    (https://issues.rudder.io/issues/14362[#14362])
* Fixed: Mandatory fields for new inventories are not correctly checked 
    (https://issues.rudder.io/issues/13962[#13962])

==== Web - Config management

* Fixed: Directive parameter values are mixed between directives
    (https://issues.rudder.io/issues/14322[#14322])

==== Architecture - Refactoring

* Fixed: We are comparing Option[String] and String
    (https://issues.rudder.io/issues/14346[#14346])

==== Architecture - Dependencies

* Fixed: Compilation fails with Java 11
    (https://issues.rudder.io/issues/14290[#14290])

==== Techniques

* Fixed: unexpected reports in zypper repo management technique
    (https://issues.rudder.io/issues/14347[#14347])
* Fixed: sshConfiguration technique should not authorize ssh password authent by default
    (https://issues.rudder.io/issues/14316[#14316])

==== System techniques

* Fixed: Technique uses /root as an hardcoded value for the home of user root
    (https://issues.rudder.io/issues/6412[#6412])

==== Generic methods - File Management

* Fixed: File lines absent generic method doesn't report anything when the file doesn't exist
    (https://issues.rudder.io/issues/14246[#14246])

==== Generic methods

* Fixed: ncf 4.1 is not compatible anymore with agent 3.1
    (https://issues.rudder.io/issues/14293[#14293])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Tobias Ell
* Janos Mattyasovszky

This is a bug fix release in the 4.3 series and therefore all installations of 4.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 4.3.9 (2019-01-30)

=== Changes

==== System integration

* Impossible to change keys of a Node using rudder-keys cli
    (https://issues.rudder.io/issues/14207[#14207])

==== Documentation

* Add some known issues in the known issue of the DSC doc
    (https://issues.rudder.io/issues/14150[#14150])
* Add some known issues in the known issue of the DSC doc
    (https://issues.rudder.io/issues/14150[#14150])

==== Web - Maintenance

* Update links in Rudder interface to use rudder.io
    (https://issues.rudder.io/issues/14205[#14205])

==== Web - Config management

* Configure report value of technique from technique editor
    (https://issues.rudder.io/issues/14091[#14091])

==== Techniques

* Port techniques downloadFile & cronManagement to separated policy generation 
    (https://issues.rudder.io/issues/14002[#14002])

==== Technique editor - UI/UX

* In the technique editor, scrolling through the GM should not mask the filter
    (https://issues.rudder.io/issues/14178[#14178])
* Manage caching of technique editor resources (css/js) with Rudder version
    (https://issues.rudder.io/issues/14194[#14194])
* Display documentation of ncf methods directly in the editor
    (https://issues.rudder.io/issues/14172[#14172])

=== Bug fixes

==== Packaging

* Fixed: "rudder-init" script does not allow the "auto" option
    (https://issues.rudder.io/issues/14134[#14134])

==== Web - UI & UX

* Fixed: Rudder node id is confused with machine id and not selectable by triple-click
    (https://issues.rudder.io/issues/14243[#14243])

==== Web - Compliance & node report

* Fixed: we can inject html & javascript in Rudder tables
    (https://issues.rudder.io/issues/14221[#14221])

==== Web - Maintenance

* Fixed: Constraints on table nodecompliancelevels are not valid
    (https://issues.rudder.io/issues/14218[#14218])

==== Performance and scalability

* Fixed: Index nodeid_idx is not used and consumes a lot of disk space for nothing
    (https://issues.rudder.io/issues/14149[#14149])

==== Web - Config management

* Fixed: When hooks are exiting with an error we can have stackoverflow error if there are many of them
    (https://issues.rudder.io/issues/10973[#10973])
* Fixed: When refreshing a rule details, the current tab is not memorized
    (https://issues.rudder.io/issues/4904[#4904])

==== API

* Fixed: Logs full of WARN  Attribute 'apiAuthorizationKind' or 'expirationTimestamp' is defined for API account but it will be ignored
    (https://issues.rudder.io/issues/13913[#13913])

==== Techniques

* Fixed: Technique "file content from remote template" does not work on the Rudder server when using remote file
    (https://issues.rudder.io/issues/14211[#14211])
* Fixed: "File content from remote template" technique ads tabs in the output file
    (https://issues.rudder.io/issues/14188[#14188])

==== System techniques

* Fixed: improve error message when the node cannot get the uuid from the server
    (https://issues.rudder.io/issues/14176[#14176])
* Fixed: "classes promises do not support promise locking" warning message when running the agent
    (https://issues.rudder.io/issues/14132[#14132])
* Fixed: Add compatibility sles classes in failsafe
    (https://issues.rudder.io/issues/13975[#13975])
* Fixed: Missing report on File key-value parameter in list
    (https://issues.rudder.io/issues/14164[#14164])

==== Plugins integration

* Fixed: Separated policy generation does not work correctly with Rudder DSC agent
    (https://issues.rudder.io/issues/14038[#14038])

==== Agent

* Fixed: rudder agent inventory wrongly states that we are not in full compliance mode
    (https://issues.rudder.io/issues/13882[#13882])

==== System integration

* Fixed: Every agent check for postgresql and ldap partition size, resulting in possible overzealous shutting down of Rudder on node
    (https://issues.rudder.io/issues/14162[#14162])

==== Server components

* Fixed: cf-serverd may listen on port 8080 preventing rudder-jetty from running
    (https://issues.rudder.io/issues/13982[#13982])

==== Generic methods

* Fixed: Avoid  checking for exit_on_lock option on newer yum
    (https://issues.rudder.io/issues/14235[#14235])
* Fixed: Enable 4h cache on available upgrades list in old package bodies
    (https://issues.rudder.io/issues/14225[#14225])
* Fixed: Error in inform mode about undefined @args in rudder agent output
    (https://issues.rudder.io/issues/14214[#14214])
* Fixed: file_from_string_mustache GM unwanted behaviour when the mustache template use non-printable elements
    (https://issues.rudder.io/issues/14215[#14215])
* Fixed: Generic method in 4.3 should not use the class has_promiser_stack
    (https://issues.rudder.io/issues/14167[#14167])

==== Technique editor - UI/UX

* Fixed: Filter in generic method should not be case sensitive
    (https://issues.rudder.io/issues/14216[#14216])

==== Documentation

* Fixed: Jinja templating iteration example in the doc is invalid
    (https://issues.rudder.io/issues/14179[#14179])

==== Generic methods - File Management

* Fixed: Jinja templating method does not correctly clean up temporary files in audit mode
    (https://issues.rudder.io/issues/13666[#13666])
* Fixed: Generic Method "File key-value present with option " treats the option as one of the value
    (https://issues.rudder.io/issues/14186[#14186])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Valentin Lelong

This is a bug fix release in the 4.3 series and therefore all installations of 4.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 4.3.8 (2019-01-10)

=== Changes

==== System integration

* Missing flag file to trigger a policy generation
    (https://issues.rudder.io/issues/14050[#14050])

==== Techniques

* Download files needed to build rudder-techniques package from repository.rudder.io
    (https://issues.rudder.io/issues/14036[#14036])
* Add a technique to manage basic SNMP configuration
    (https://issues.rudder.io/issues/13602[#13602])
* Technique File download (Rudder server) has a borken posthook and should incorporate a windows and a linux section
    (https://issues.rudder.io/issues/13918[#13918])

==== Technique editor - UI/UX

* Add a filter on generic method tree to find methods faster
    (https://issues.rudder.io/issues/14013[#14013])
* Allow to clone Generic methods in a technique in the editor
    (https://issues.rudder.io/issues/11676[#11676])
* Make conditions visible in the Technique editor
    (https://issues.rudder.io/issues/12740[#12740])

=== Bug fixes

==== Packaging

* Fixed: uuid.hive file should not be a rudder-agent package conf file
    (https://issues.rudder.io/issues/14062[#14062])
* Fixed: Force http 1.1 when downloading curl
    (https://issues.rudder.io/issues/14059[#14059])
* Fixed: When installing a rudder root server (on debian), it asks to run rudder-node-to-relay
    (https://issues.rudder.io/issues/11630[#11630])
* Fixed: Change packaging to allow openjdk > 8 
    (https://issues.rudder.io/issues/13896[#13896])
* Fixed: When we stop rudder-jetty, it says it stops Jetty 7 (we are using Jetty 9 ...)
    (https://issues.rudder.io/issues/13929[#13929])

==== Agent

* Fixed: Agent run errors are not outputed on stderr anymore
    (https://issues.rudder.io/issues/14061[#14061])

==== Miscellaneous

* Fixed: Rudder-jetty depends on jdk8 but always try to install jdk9 as dependency
    (https://issues.rudder.io/issues/14024[#14024])

==== Documentation

* Fixed: Broken 4.1/4.3 doc build
    (https://issues.rudder.io/issues/14048[#14048])

==== Web - Config management

* Fixed: Cannot modify groups when workflow are enabled
    (https://issues.rudder.io/issues/14056[#14056])

==== Plugins integration

* Fixed: indexes on nodecompliancelevels table are not valid and table ArchivedReportsExecution is never used
    (https://issues.rudder.io/issues/14007[#14007])

==== Performance and scalability

* Fixed: A lot of space is wasted on table nodecompliance and nodeconfigurations due to pretty jsonification
    (https://issues.rudder.io/issues/14014[#14014])
* Fixed: Massive performance penalty in policy generation due to invalid usage of StringTemplate
    (https://issues.rudder.io/issues/13987[#13987])
* Fixed: Load all ncf files in one go (or two)
    (https://issues.rudder.io/issues/13859[#13859])

==== Web - UI & UX

* Fixed: In the node details, clicking on the link to the policy server doesn't redirect to the policy server
    (https://issues.rudder.io/issues/13834[#13834])

==== Techniques

* Fixed: "Job Scheduler" Technique miss runs when using a non-default agent execution frequency
    (https://issues.rudder.io/issues/4840[#4840])

==== Generic methods

* Fixed: Error in the info (rudder agent run -i) output of the agent at first run
    (https://issues.rudder.io/issues/13951[#13951])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 4.3 series and therefore all installations of 4.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 4.3.7 (2018-11-26)

=== Changes

==== API

* Add rudder server version to the Rest API (system/info endpoint)
(https://issues.rudder.io/issues/13654[#13654])

==== Techniques

* Provide a rudder.json file with initial policies
(https://issues.rudder.io/issues/13805[#13805])

==== Documentation

* Cleanup the ncf repo (https://issues.rudder.io/issues/13651[#13651])

=== Bug fixes

==== Plugins integration

* Fixed: Improve error messsage when path to install a plugin package is
not correct (https://issues.rudder.io/issues/13891[#13891])

==== Packaging

* Fixed: Rudder agent 4.3 needs libxml-treepp-perl on debian
(https://issues.rudder.io/issues/12599[#12599])
* Fixed: Slackware agent is not started at boot
(https://issues.rudder.io/issues/13850[#13850])
* Fixed: Don’t create crontab entry at Rudder agent install but during
first run (https://issues.rudder.io/issues/13846[#13846])
* Fixed: Remove unnecessary conflict dependency with openjdk 9 on debian
(https://issues.rudder.io/issues/12664[#12664])
* Fixed: Missing _ in slackware package name
(https://issues.rudder.io/issues/13839[#13839])
* Fixed: Agent should depend on a logging system on SUSE
(https://issues.rudder.io/issues/13788[#13788])
* Fixed: On rudder-webapp upgrade, ncf.conf file is not commited
(https://issues.rudder.io/issues/13679[#13679])

==== Agent

* Fixed: Upgrade CFEngine to 3.10.5
(https://issues.rudder.io/issues/13851[#13851])
* Fixed: ``rudder-keys change-key'' does not check for key file
existence (https://issues.rudder.io/issues/12496[#12496])
* Fixed: When ``policy-server.dat'' is missing, generated inventory is
not legit (https://issues.rudder.io/issues/11715[#11715])
* Fixed: /var/log/rudder/agent-check/check.log should contains only
error level messages (https://issues.rudder.io/issues/12230[#12230])
* Fixed: rudder remote run error, and unable to pass -i option
(https://issues.rudder.io/issues/11318[#11318])
* Fixed: Command ``rudder remote run -a'' does not warn about missing
token (https://issues.rudder.io/issues/11417[#11417])
* Fixed: Add a warn message when agent run is incomplete
(https://issues.rudder.io/issues/10751[#10751])
* Fixed: Command ``rudder agent reset'' sets incorrect permission in
/var/rudder/cfengine-community/inputs
(https://issues.rudder.io/issues/12410[#12410])
* Fixed: ``rudder agent info'' returns invalid report mode for not yet
accepted nodes (https://issues.rudder.io/issues/12992[#12992])
* Fixed: Missing spaces between key and message on rudder agent run
report when using -w option
(https://issues.rudder.io/issues/13663[#13663])

==== Performance and scalability

* Fixed: There are still tables expectedreports & expectesreportsnodes
on upgraded Rudder 4.x and 5.x,
(https://issues.rudder.io/issues/13770[#13770])
* Fixed: After a node is deleted, a policy generation is started every 5
secondes (https://issues.rudder.io/issues/13845[#13845])
* Fixed: Invalid value reported for Node expected reports saved in base
in Rudder log (https://issues.rudder.io/issues/13418[#13418])

==== System integration

* Fixed: ``rudder-pkg enable-all'' command fails when a plugin has no
jar (https://issues.rudder.io/issues/13785[#13785])
* Fixed: Bad log level during generation
(https://issues.rudder.io/issues/9512[#9512])
* Fixed: Init check on group All classic Nodes known by Rudder (Using a
CFEngine based agent) always tries to rewrite the group
(https://issues.rudder.io/issues/13792[#13792])

==== Web - Config management

* Fixed: The password field allows storing a password without any
selected hash (https://issues.rudder.io/issues/12198[#12198])
* Fixed: Spinning compliance in nodes list on a disabled node
(https://issues.rudder.io/issues/12649[#12649])
* Fixed: Spinning compliance in nodes list on a disabled node
(https://issues.rudder.io/issues/12649[#12649])
* Fixed: ``Not copying missing license file into'' in webapp log
(https://issues.rudder.io/issues/10917[#10917])
* Fixed: Missing node state variable expansion in directive
(https://issues.rudder.io/issues/13671[#13671])
* Fixed: Add full path to shared-folder in description of ``Download
file from shared folder'' Technique
(https://issues.rudder.io/issues/13530[#13530])

==== Web - UI & UX

* Fixed: Wrong text color in table header in Rule page
(https://issues.rudder.io/issues/13835[#13835])
* Fixed: Quotes in reports are displayed as " in the web interface
(https://issues.rudder.io/issues/13349[#13349])
* Fixed: Upgrade loading wheel with a new look
(https://issues.rudder.io/issues/8622[#8622])
* Fixed: On Dashboard, when we have 100% of something, the pie is
including a confusing white line
(https://issues.rudder.io/issues/12233[#12233])
* Fixed: No color difference on hover on the user menu
(https://issues.rudder.io/issues/12926[#12926])
* Fixed: ``Configure the default state'' is lacking explanations
(https://issues.rudder.io/issues/12462[#12462])
* Fixed: Remove static ids in Password section
(https://issues.rudder.io/issues/13457[#13457])
* Fixed: Button to enable a technique in Directive Screen is not
working, should be a link to the Technique
(https://issues.rudder.io/issues/13779[#13779])
* Fixed: In directive page, tooltip is not correctly aligned with text
(https://issues.rudder.io/issues/13511[#13511])
* Fixed: The ``hardware'' tab is not displayed in accept new nodes
screen (https://issues.rudder.io/issues/13688[#13688])

==== Web - Nodes & inventories

* Fixed: When a node is deleted, its generated promises are not removed
(https://issues.rudder.io/issues/4709[#4709])
* Fixed: Inventory keeps its key certified when node is deleted
(https://issues.rudder.io/issues/9149[#9149])
* Fixed: Missing gateway, network in network interface details
(https://issues.rudder.io/issues/13804[#13804])
* Fixed: Network group criteria not working
(https://issues.rudder.io/issues/13772[#13772])
* Fixed: Node details shows Operating System Type: MSWin for Windows
node rather than Windows (https://issues.rudder.io/issues/6019[#6019])
* Fixed: The error message for bad inventory signature is unclear
(https://issues.rudder.io/issues/9192[#9192])
* Fixed: Network, mask and gateway not correctly parsed from inventory
(https://issues.rudder.io/issues/13803[#13803])

==== Web - Compliance & node report

* Fixed: Compliance error (missing) when a directive is applied by two
rules on a node (https://issues.rudder.io/issues/13674[#13674])

==== API

* Fixed: Remove old ``machyne type'' api Rest typo since it should not
be called anymore (https://issues.rudder.io/issues/13795[#13795])
* Fixed: Tags in rules are ignored in POST API
(https://issues.rudder.io/issues/13374[#13374])

==== Techniques

* Fixed: Option description for ``File download (Rudder server)''
technique is misleading (https://issues.rudder.io/issues/13887[#13887])
* Fixed: Technique ``Cron job v3.0'' does not use the ``user'' setting
with predefined scheduled (https://issues.rudder.io/issues/8004[#8004])
* Fixed: Missing reports on password component on ``User management''
Technique in audit mode (https://issues.rudder.io/issues/9474[#9474])
* Fixed: Enforce checkbox tooltip in ``Group management'' Technique is
misleading (https://issues.rudder.io/issues/13489[#13489])
* Fixed: Missing report with `File and directory basics' Technique in
audit mode when checking perms on non existing file
(https://issues.rudder.io/issues/11653[#11653])
* Fixed: Broken reporting when copying a directory from the Rudder
server without specifying the trailing / in the destination
(https://issues.rudder.io/issues/13290[#13290])
* Fixed: Missing report for post-modification hook in Technique ``File
download (Rudder server)''
(https://issues.rudder.io/issues/13717[#13717])
* Fixed: Details of usage of technique ``Variable from command output
(string)'' is not clear (https://issues.rudder.io/issues/12058[#12058])
* Fixed: Some files in the techniques repository do not present any
licence header (https://issues.rudder.io/issues/13633[#13633])
* Fixed: Technique ``cron job'' refuses task user name if it contains
hyphen (https://issues.rudder.io/issues/12960[#12960])
* Fixed: Missing report for component ``Post-modification hook'' when
cleaning files with ``File and directory basics'' Technique version 4.1
(https://issues.rudder.io/issues/13786[#13786])

==== System techniques

* Fixed: Mustache templates are not processed at all (including
cron.d/rudder-agent file)
(https://issues.rudder.io/issues/13885[#13885])
* Fixed: Slackware agent cron.d is broken in system technique
(https://issues.rudder.io/issues/13848[#13848])

==== Server components

* Fixed: server command based on jq should exit when jq is not installed
and explain to install it
(https://issues.rudder.io/issues/13682[#13682])

==== Generic methods

* Fixed: Typo in ``File content'' generic method description
(https://issues.rudder.io/issues/13883[#13883])
* Fixed: Generic method ``File_remove'' can delete empty directories
(https://issues.rudder.io/issues/12857[#12857])
* Fixed: Scheduler classes have incomplete labels
(https://issues.rudder.io/issues/8008[#8008])

==== Web - Technique editor

* Fixed: In technique editor, on save, we get ``success'' but some
errors are shallowed (https://issues.rudder.io/issues/12210[#12210])

==== Generic methods - File Management

* Fixed: Generic Method ``permission dirs'' incorrect reporting when
target path is a file (https://issues.rudder.io/issues/10689[#10689])
* Fixed: ``File key-value present'' Generic Method and ``Manage
keys-values in file'' Technique does not support | as separator
(https://issues.rudder.io/issues/13562[#13562])

==== Documentation

* Fixed: Fix path to jinja2_custom.py in jinja2 templating doc
(https://issues.rudder.io/issues/13784[#13784])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Thomas CAILHE
* Ilan COSTA
* vlycop Doo
* Florian Heigl
* Renaud Manus
* Janos Mattyasovszky
* Romain Quinaud
* David Svejda

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 4.3.6 (2018-11-06)

=== Changes

==== Generic methods

* Add condition_once and execute_once generic methods
(https://www.rudder-project.org/redmine/issues/13667[#13667])
* Add a flag library to store persistent context on the agents
(https://www.rudder-project.org/redmine/issues/13622[#13622])
* Add a flag library to store persistent context on the agents
(https://www.rudder-project.org/redmine/issues/13622[#13622])

==== Documentation

* Document zypper pattern usage in the ``Package state'' generic method
documentation
(https://www.rudder-project.org/redmine/issues/13725[#13725])

=== Bug fixes

==== Web - UI & UX

* Fixed: We have no way to know that a Technique is disabled when
editing a Directive
(https://www.rudder-project.org/redmine/issues/12829[#12829])

==== Generic methods

* Fixed: Generic method ``Sharedfile to node'' always return repaired
status (https://www.rudder-project.org/redmine/issues/13753[#13753])
* Fixed: Unit tests for generic method ``File from a Jinja2 template''
fail on Ubuntu12 on Rudder 4.1
(https://www.rudder-project.org/redmine/issues/13747[#13747])
* Fixed: Time lib may not work when the first non-loopback interface has
no ip adress
(https://www.rudder-project.org/redmine/issues/13744[#13744])
* Fixed: Remove comment about classes_generic_two being deprecated
(https://www.rudder-project.org/redmine/issues/13286[#13286])
* Fixed: Style test nbsp_is_not_allowed.sh always fails, missing 4.1
version of 13637
(https://www.rudder-project.org/redmine/issues/13722[#13722])
* Fixed: Missing report when using default value in Generic method
parameters (https://www.rudder-project.org/redmine/issues/13704[#13704])
* Fixed: Add more tests for the schedule lib in ncf
(https://www.rudder-project.org/redmine/issues/13668[#13668])
* Fixed: Zypper patterns tests should not be executed on non sles os
(https://www.rudder-project.org/redmine/issues/13638[#13638])

==== Web - Nodes & inventories

* Fixed: Group of group is empty if we use the AND combinator
(https://www.rudder-project.org/redmine/issues/13424[#13424])

==== Generic methods - Package Management

* Fixed: Missing report when using the ``Package state'' generic method
with default value for the ``state'' parameter
(https://www.rudder-project.org/redmine/issues/13703[#13703])

==== Generic methods - File Management

* Fixed: Change the detection of curl path in ncf to use rudder_curl if
available (https://www.rudder-project.org/redmine/issues/13745[#13745])
* Fixed: Missing report in ``Manage keys-values in file'' technique
(https://www.rudder-project.org/redmine/issues/13715[#13715])
* Fixed: Missing reporting in ``Permisisons recurse'' method
(https://www.rudder-project.org/redmine/issues/13683[#13683])
* Fixed: Generic Method ``File copy from remote source'' does not report
when copying a directory
(https://www.rudder-project.org/redmine/issues/13634[#13634])
* Fixed: Missing status when I use ``File copy from Rudder shared
folder'' Technique
(https://www.rudder-project.org/redmine/issues/13669[#13669])

==== Web - Config management

* Fixed: In directive, change input for parameter from technique editor
from text to textarea
(https://www.rudder-project.org/redmine/issues/12824[#12824])

==== Agent

* Fixed: Redhat Openstack Nova compute QEMU virtual machines are seen as
physical (https://www.rudder-project.org/redmine/issues/10265[#10265])
* Fixed: Mustache templating in audit mode always considers destination
compliant once it exists
(https://www.rudder-project.org/redmine/issues/13664[#13664])

==== Packaging

* Fixed: rudder-cf-execd and rudder-cf-serverd are not enabled nor
running after a server install on debian 8
(https://www.rudder-project.org/redmine/issues/13774[#13774])
* Fixed: Rudder agent uninstall may fail to to systemd unit
(https://www.rudder-project.org/redmine/issues/13762[#13762])
* Fixed: can’t upgrade debian package if /bin/systemd exist but sysv is
used (https://www.rudder-project.org/redmine/issues/13174[#13174])
* Fixed: rudder.conf is not removed from /etc/ld.so.conf.d
(https://www.rudder-project.org/redmine/issues/12554[#12554])
* Fixed: Fusioninventory error about unitialized value $FQDN
(https://www.rudder-project.org/redmine/issues/13739[#13739])
* Fixed: ``type: systemctl : not found'' appears in rudder-agent
installation logs
(https://www.rudder-project.org/redmine/issues/13693[#13693])
* Fixed: Rudder syslog port is reset after upgrade on Ubuntu (< 14)
Servers (https://www.rudder-project.org/redmine/issues/12714[#12714])

==== Generic methods - Service Management

* Fixed: Broken variable in ``Service restart'' method report
(https://www.rudder-project.org/redmine/issues/13713[#13713])

==== Documentation

* Fixed: Broken doc build
(https://www.rudder-project.org/redmine/issues/13734[#13734])

==== System techniques

* Fixed: Use embedded curl when available
(https://www.rudder-project.org/redmine/issues/13687[#13687])

==== Performance and scalability

* Fixed: LDAP IO error on generation with a lot of nodes
(https://www.rudder-project.org/redmine/issues/13256[#13256])

==== Techniques

* Fixed: Sharing files with ``root'' does not work
(https://www.rudder-project.org/redmine/issues/10605[#10605])
* Fixed: Add option for Zypper Patterns in Technique ``Packages''
(https://www.rudder-project.org/redmine/issues/13721[#13721])
* Fixed: Add a bigger warning about full path in ``Download a file''
technique (https://www.rudder-project.org/redmine/issues/13647[#13647])
* Fixed: Add a bigger warning about full path in ``Download a file''
technique (https://www.rudder-project.org/redmine/issues/13646[#13646])
* Fixed: Fix some typo in ``rudder server directive upgrade'' help
output (https://www.rudder-project.org/redmine/issues/13765[#13765])
* Fixed: ``directive-upgrade'' rudder command does not work
(https://www.rudder-project.org/redmine/issues/13681[#13681])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* tim c
* Matthew Frost
* Ilan COSTA
* Jérémy HOCDÉ
* Janos Mattyasovszky
* Thomas CAILHE

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 4.3.5 (2018-10-19)

=== Changes

==== Packaging

* Upgrade openssl
(https://www.rudder-project.org/redmine/issues/13316[#13316])
* Add sles 15 support to rudder-packages
(https://www.rudder-project.org/redmine/issues/13295[#13295])
* Disable HTTPs for sources download on old OSes
(https://www.rudder-project.org/redmine/issues/13197[#13197])
* Download sources from repository.rudder.io instead of
www.normation.com
(https://www.rudder-project.org/redmine/issues/13172[#13172])

==== Generic methods

* Add a generic method to test variable existence
(https://www.rudder-project.org/redmine/issues/12986[#12986])

==== Generic methods - Package Management

* Use the new class_prefix for package methods
(https://www.rudder-project.org/redmine/issues/12427[#12427])
* Add a package provider for zypper patterns
(https://www.rudder-project.org/redmine/issues/12164[#12164])

==== Agent

* Add a package techniques migration script
(https://www.rudder-project.org/redmine/issues/12710[#12710])
* Update technique migration script with 12614 review
(https://www.rudder-project.org/redmine/issues/12676[#12676])

=== Bug fixes

==== Web - UI & UX

* Fixed: Blue text color in node details tabs
(https://www.rudder-project.org/redmine/issues/13168[#13168])

==== Generic methods

* Fixed: Allow to report on same reporting parameters
(https://www.rudder-project.org/redmine/issues/13632[#13632])
* Fixed: style test nbsp_is_not_allowed.sh always fails
(https://www.rudder-project.org/redmine/issues/13637[#13637])
* Fixed: rudder agent log files content in user facility
(https://www.rudder-project.org/redmine/issues/13175[#13175])
* Fixed: 4.3+ version of 12164
(https://www.rudder-project.org/redmine/issues/13621[#13621])
* Fixed: still some typos in package tests
(https://www.rudder-project.org/redmine/issues/13591[#13591])
* Fixed: some ncf test are failing on SLES because they are trying to
deal with packages that are not available
(https://www.rudder-project.org/redmine/issues/13573[#13573])
* Fixed: Some old tests are failing on centos
(https://www.rudder-project.org/redmine/issues/13535[#13535])
* Fixed: there is still a trailing new line in the jinja result test
file (https://www.rudder-project.org/redmine/issues/13529[#13529])
* Fixed: Tests on variable_string and variable_string_default GM are
failing (https://www.rudder-project.org/redmine/issues/13523[#13523])
* Fixed: Some tests are failing on ubuntu distros
(https://www.rudder-project.org/redmine/issues/13514[#13514])
* Fixed: " error: List or container parameter `args' not found while
constructing scope `log_rudder' - use @(scope.variable) in calling
reference" when running Rudder 4.3
(https://www.rudder-project.org/redmine/issues/13430[#13430])
* Fixed: add a method to set reportiing_context from within a technique
(https://www.rudder-project.org/redmine/issues/13351[#13351])
* Fixed: user_primary_group tests are failing on suse
(https://www.rudder-project.org/redmine/issues/13282[#13282])
* Fixed: Some ncf tests are too old and fails on many distributions
(https://www.rudder-project.org/redmine/issues/13249[#13249])
* Fixed: Incomplete management of disabled/reenable reporting
(https://www.rudder-project.org/redmine/issues/13209[#13209])
* Fixed: file_check_special tests are failing on debian
(https://www.rudder-project.org/redmine/issues/13243[#13243])
* Fixed: Huge agent logs when we define an new class_prefix that is
longer than 1024 chars
(https://www.rudder-project.org/redmine/issues/13155[#13155])

==== Web - Nodes & inventories

* Fixed: Node group with `OR' multi criteria fails
(https://www.rudder-project.org/redmine/issues/13649[#13649])

==== Generic methods - Package Management

* Fixed: old packages generic methods are failing on old debian
(https://www.rudder-project.org/redmine/issues/13305[#13305])

==== Generic methods - File Management

* Fixed: Missing report on Permissions (non recursive)
(https://www.rudder-project.org/redmine/issues/13536[#13536])
* Fixed: Error when using 2 or more File from a jinja2 template
(https://www.rudder-project.org/redmine/issues/13183[#13183])

==== Documentation

* Fixed: rudder-doc embedeed doesn’t work anymore
(https://www.rudder-project.org/redmine/issues/13659[#13659])
* Fixed: Document Amazon Linux compatibility
(https://www.rudder-project.org/redmine/issues/13624[#13624])
* Fixed: Wrong version displayed on the login page for plugin branding
(https://www.rudder-project.org/redmine/issues/13274[#13274])
* Fixed: Update screenshot for Rudder Branding
(https://www.rudder-project.org/redmine/issues/13270[#13270])
* Fixed: Bad explanation for generic variable overide priority cause
people making the opposite of what is needed
(https://www.rudder-project.org/redmine/issues/13615[#13615])

==== Technique editor - API

* Fixed: Error message is not correctly treated when an exception occurs
in when authenticating to Rudder authentication API
(https://www.rudder-project.org/redmine/issues/13219[#13219])

==== Agent

* Fixed: remove unessecary patch that remove truncation of line in
inventory (https://www.rudder-project.org/redmine/issues/13403[#13403])
* Fixed: rudder server command states that ``Warning: Long arguments are
not supported, you probably tried to use one!'' - but it does support it
(https://www.rudder-project.org/redmine/issues/13505[#13505])
* Fixed: rudder technique-migrate is not documented nor properly named
(https://www.rudder-project.org/redmine/issues/13146[#13146])

==== Packaging

* Fixed: Debian package cannot build in 4.1 because of docs.rudder.io
(https://www.rudder-project.org/redmine/issues/13594[#13594])
* Fixed: rudder-agent service is not removed when removing rudder-agent
(https://www.rudder-project.org/redmine/issues/13549[#13549])
* Fixed: Use new man page URL after doc URL redirect
(https://www.rudder-project.org/redmine/issues/13537[#13537])
* Fixed: rudder-agent 4.1 install hangs on Debian 7
(https://www.rudder-project.org/redmine/issues/13525[#13525])
* Fixed: Doc download in webapp package does not work anymore
(https://www.rudder-project.org/redmine/issues/13499[#13499])
* Fixed: Use correct version when building Slackware packages
(https://www.rudder-project.org/redmine/issues/13329[#13329])
* Fixed: parallel build on rpmbuild hides build error
(https://www.rudder-project.org/redmine/issues/13300[#13300])
* Fixed: Purge of rudder-webapp should not fail
(https://www.rudder-project.org/redmine/issues/13210[#13210])
* Fixed: Fix bdb download link from repository.rudder.io
(https://www.rudder-project.org/redmine/issues/13198[#13198])
* Fixed: slackware should not build its package into /tmp
(https://www.rudder-project.org/redmine/issues/13194[#13194])
* Fixed: rudder server upgrade-techniques –autoupdate-technique-library
fails when run during Rudder upgrade
(https://www.rudder-project.org/redmine/issues/13458[#13458])
* Fixed: cebtos7 install_package_existant should be skipped
(https://www.rudder-project.org/redmine/issues/13596[#13596])
* Fixed: Makefile fails if a symbolink link /usr/bin/ncf already exists
(https://www.rudder-project.org/redmine/issues/13277[#13277])

==== Generic methods - Service Management

* Fixed: Service test do not use any service to test on suse
(https://www.rudder-project.org/redmine/issues/13278[#13278])
* Fixed: services GM are not working anymore due to typo
(https://www.rudder-project.org/redmine/issues/13258[#13258])
* Fixed: service_started_start.cf test fails on redhat
(https://www.rudder-project.org/redmine/issues/13257[#13257])
* Fixed: service_started_path.cf does not generate classes anymore since
13220 (https://www.rudder-project.org/redmine/issues/13254[#13254])

==== API

* Fixed: Rudder system api token only have RO access
(https://www.rudder-project.org/redmine/issues/13416[#13416])

==== Security

* Fixed: StackOverflowError during policy generation in JavascriptEngine
- debian 9.5 with jdk 1.8.0_181
(https://www.rudder-project.org/redmine/issues/13014[#13014])
* Fixed: Api User Account doesn’t have User role
(https://www.rudder-project.org/redmine/issues/13629[#13629])
* Fixed: ``//'' in rudder-web/secure/api//settings/global_policy_mode
cause browser/spring error
(https://www.rudder-project.org/redmine/issues/13356[#13356])
* Fixed: Bad mime type for our js files: application/js
(https://www.rudder-project.org/redmine/issues/13334[#13334])
* Fixed: file enforce content log file content which can have private
info (https://www.rudder-project.org/redmine/issues/13608[#13608])

==== Performance and scalability

* Fixed: Hikari pool autocomit configuration is incorrect, which can
impact performance
(https://www.rudder-project.org/redmine/issues/13582[#13582])
* Fixed: Policy generation fails definitively when postgresql is shut
down during policy generation
(https://www.rudder-project.org/redmine/issues/13517[#13517])
* Fixed: On error on nodecompliance SQL, logs are huge
(https://www.rudder-project.org/redmine/issues/13427[#13427])

==== Techniques

* Fixed: SudoParameter technique version 3.2 returns a report that is
not parsable by the CLI
(https://www.rudder-project.org/redmine/issues/13350[#13350])
* Fixed: Package repository keys Technique in Audit Mode : Missing
Reports (https://www.rudder-project.org/redmine/issues/13065[#13065])
* Fixed: Package repository keys Technique in Audit Mode : Missing
Reports (https://www.rudder-project.org/redmine/issues/13065[#13065])
* Fixed: Rudder SNMP technique has a component failing on first run
(https://www.rudder-project.org/redmine/issues/13159[#13159])
* Fixed: Package management technique fails to check if a package is
absent in the ``latest'' version
(https://www.rudder-project.org/redmine/issues/12939[#12939])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Jeremy CHAMPEL
* Mikaël Mantel
* tim c
* Marco Kirchhoff
* Guillaume Terrier

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 4.3.4 (2018-08-08)

=== Changes

==== Packaging

* Add the slackware target to packages.makefile
(https://www.rudder-project.org/redmine/issues/13070[#13070])

==== Web - UI & UX

* Remove the ``Update policy'' button
(https://www.rudder-project.org/redmine/issues/12668[#12668])

=== Bug fixes

==== Web - UI & UX

* Fixed: Strange behavior of the generation status icon background
(https://www.rudder-project.org/redmine/issues/12816[#12816])
* Fixed: Display Rudder Machine ID color scheme is surprising
(https://www.rudder-project.org/redmine/issues/12923[#12923])
* Fixed: Style to define behaviour regarding duplicated reports in 4.3
is not consistent with the rest of the option
(https://www.rudder-project.org/redmine/issues/12987[#12987])

==== Generic methods

* Fixed: Generic method File present is called Presence of a file, and
that’s really confusing
(https://www.rudder-project.org/redmine/issues/13003[#13003])

==== Web - Config management

* Fixed: ``SocketException(message=`Socket closed''' error at the end of
generation with 500 nodes
(https://www.rudder-project.org/redmine/issues/10646[#10646])
* Fixed: Wrong tag used in metadata.xml to define if a technique should
use ncf method reporting or not
(https://www.rudder-project.org/redmine/issues/13035[#13035])

==== Architecture - Internal libs

* Fixed: nuProcess 1.2.0 crashes on JDK 10
(https://www.rudder-project.org/redmine/issues/12832[#12832])

==== Documentation

* Fixed: Script execution must be allowed to install and use Rudder on
Windows nodes
(https://www.rudder-project.org/redmine/issues/12772[#12772])

==== Agent

* Fixed: Broken -g option in rudder remote run
(https://www.rudder-project.org/redmine/issues/13017[#13017])

==== Packaging

* Fixed: cfengine fails to build with embedded libxml on rhel3
(https://www.rudder-project.org/redmine/issues/13096[#13096])
* Fixed: agent postinstall fails on OS without /proc/self
(https://www.rudder-project.org/redmine/issues/13066[#13066])
* Fixed: libxml depends on zlib but we don’t pass it the configure flag
(https://www.rudder-project.org/redmine/issues/13060[#13060])
* Fixed: Libgcc is missing on aix
(https://www.rudder-project.org/redmine/issues/13046[#13046])
* Fixed: static-libgcc is ignored by some build
(https://www.rudder-project.org/redmine/issues/13042[#13042])
* Fixed: echo -n doewn’t work on aix
(https://www.rudder-project.org/redmine/issues/13005[#13005])
* Fixed: Missing lib path in AIX cfengine executables
(https://www.rudder-project.org/redmine/issues/12994[#12994])
* Fixed: Silent install does not work
(https://www.rudder-project.org/redmine/issues/12929[#12929])
* Fixed: Tests broken after #12953
(https://www.rudder-project.org/redmine/issues/13001[#13001])

==== Relay server or API

* Fixed: Relay API does not correctly work on relay, as RewriteEngine is
not enabled
(https://www.rudder-project.org/redmine/issues/13063[#13063])

==== System techniques

* Fixed: Missing report on File key-value present
(https://www.rudder-project.org/redmine/issues/12998[#12998])

==== Web - Maintenance

* Fixed: rudder-metrics-reporting fail to report reports on
directive/expected reports in 4.3, as the database schema changed
(https://www.rudder-project.org/redmine/issues/13041[#13041])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Martin Zbozien

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 4.3.3 (2018-07-18)

=== Changes

==== Generic methods

* Do not modify variables in existing bundles
(https://www.rudder-project.org/redmine/issues/12597[#12597])
* Add support for BSD-style init scripts services (rc.d) (slackware)
(https://www.rudder-project.org/redmine/issues/12593[#12593])

==== Generic methods - Package Management

* Synchronize the `slackpkg' cfengine package module shipped with ncf
with the official one
(https://www.rudder-project.org/redmine/issues/12811[#12811])
* Synchronize package modules from masterfiles
(https://www.rudder-project.org/redmine/issues/10907[#10907])
* Backport options for yum package provider
(https://www.rudder-project.org/redmine/issues/12127[#12127])

==== Documentation

* Document rudder branding plugin
(https://www.rudder-project.org/redmine/issues/12852[#12852])
* Document plugin node-external-reports
(https://www.rudder-project.org/redmine/issues/12864[#12864])
* Add binary dependency to rpkg format documentation
(https://www.rudder-project.org/redmine/issues/12810[#12810])
* Change the documentation to tell the user to use the gpg key from the
root path (https://www.rudder-project.org/redmine/issues/12802[#12802])

==== Agent

* Patch the agent Makefile in rudder-packages in order to build it on
Slackware (https://www.rudder-project.org/redmine/issues/12775[#12775])
* The agent cannot find its version on Slackware
(https://www.rudder-project.org/redmine/issues/12766[#12766])
* Add a command line option to run the agent in full compliance mode
(https://www.rudder-project.org/redmine/issues/12681[#12681])

==== Packaging

* Accept external options to rpmbuild calls
(https://www.rudder-project.org/redmine/issues/12973[#12973])
* Remove documentation from the install of rudder-agent dependencies in
rudder-packages
(https://www.rudder-project.org/redmine/issues/12831[#12831])
* Add slackware support to rudder-packages
(https://www.rudder-project.org/redmine/issues/12789[#12789])

==== Plugins

* Integrate plugin-common Trait into rudder
(https://www.rudder-project.org/redmine/issues/12908[#12908])
* Integrate plugin-common Trait into rudder
(https://www.rudder-project.org/redmine/issues/12908[#12908])

==== System techniques

* Make the agent resend the inventory if sending failed
(https://www.rudder-project.org/redmine/issues/7490[#7490])

==== Techniques

* Add testing on sshKeyDistribution
(https://www.rudder-project.org/redmine/issues/12822[#12822])

=== Bug fixes

==== Technique editor - UI/UX

* Fixed: dsc filter in technique editor does not seem to work
(https://www.rudder-project.org/redmine/issues/12468[#12468])

==== Web - UI & UX

* Fixed: The red cross in case of generation problem is not visible
enough (https://www.rudder-project.org/redmine/issues/11889[#11889])

==== Technique editor - API

* Fixed: On debian 9.4, ncf views.py can not access
http://localhost/rudder (but can https://..)
(https://www.rudder-project.org/redmine/issues/12957[#12957])

==== Web - Nodes & inventories

* Fixed: NodeInfoCache is precise to the second but we need it to be
precise to the millisecond
(https://www.rudder-project.org/redmine/issues/12988[#12988])
* Fixed: root node disapeared while upgrading from 4.1 to 4.3 on debian
9 (https://www.rudder-project.org/redmine/issues/12474[#12474])
* Fixed: In inventory, ``motherboardid'' is not the mother board id but
the machine id
(https://www.rudder-project.org/redmine/issues/12893[#12893])
* Fixed: It’s difficult to know if the node property added is valid json
(https://www.rudder-project.org/redmine/issues/12360[#12360])

==== Generic methods - Package Management

* Fixed: Force using epoch when installing a package with zypper
(https://www.rudder-project.org/redmine/issues/12799[#12799])
* Fixed: zypper module arch and version specification for zypper
commands is not correct
(https://www.rudder-project.org/redmine/issues/12798[#12798])

==== Web - Technique editor

* Fixed: Broken technique editor if a technique is in the browser cache,
but has been removed from the FS
(https://www.rudder-project.org/redmine/issues/12970[#12970])

==== Rudder web app

* Fixed: wrong text encoding in technique editor
(https://www.rudder-project.org/redmine/issues/12471[#12471])

==== Web - Config management

* Fixed: When we add a section in the directive editor, it clears the
content of the previous section
(https://www.rudder-project.org/redmine/issues/12916[#12916])

==== Documentation

* Fixed: Invalid ordering of elements in node external reports plugin
(https://www.rudder-project.org/redmine/issues/12901[#12901])
* Fixed: Update screenshot of branding plugin
(https://www.rudder-project.org/redmine/issues/12897[#12897])
* Fixed: Move DSC documentation inside the plugins section of Rudder doc
(https://www.rudder-project.org/redmine/issues/12895[#12895])
* Fixed: Missing support of Ubuntu 18.04 agent in documentation
(https://www.rudder-project.org/redmine/issues/12854[#12854])
* Fixed: Rudder doc 4.3 fails to list the supported SLES for the nodes
(https://www.rudder-project.org/redmine/issues/12756[#12756])
* Fixed: Documentation for dsc ncf GM does not appear in the user manual
(https://www.rudder-project.org/redmine/issues/12750[#12750])

==== Generic methods

* Fixed: In some cases, reporting context calls can be the same for
different methods, and hence ignored
(https://www.rudder-project.org/redmine/issues/12953[#12953])
* Fixed: Wrong bundle name passed in 12154
(https://www.rudder-project.org/redmine/issues/12921[#12921])
* Fixed: Broken reporting when class_prefix contains an unexpanded
variable (https://www.rudder-project.org/redmine/issues/12819[#12819])
* Fixed: Description of the ``user primary group'' method is wrong
(https://www.rudder-project.org/redmine/issues/12785[#12785])
* Fixed: Broken logger_rudder test in 4.3
(https://www.rudder-project.org/redmine/issues/12777[#12777])
* Fixed: Create a generic method to define environment variable
(https://www.rudder-project.org/redmine/issues/12154[#12154])

==== Web - Compliance & node report

* Fixed: During an upgrade of Rudder, if a new generic method appears in
ncf, that is also on local method, all is broken
(https://www.rudder-project.org/redmine/issues/12930[#12930])
* Fixed: Some reports are duplicated between agent and postgres leading
to ``unexpected'' compliance
(https://www.rudder-project.org/redmine/issues/12719[#12719])

==== Packaging

* Fixed: Broken windows plugin install in 4.3
(https://www.rudder-project.org/redmine/issues/12922[#12922])
* Fixed: Rudder-agent provides rudder-agent without a version
(https://www.rudder-project.org/redmine/issues/7777[#7777])
* Fixed: rudder-agent 4.3 install hangs on Debian 7
(https://www.rudder-project.org/redmine/issues/12698[#12698])
* Fixed: Error in Plugin section for Node external reports
(https://www.rudder-project.org/redmine/issues/12898[#12898])
* Fixed: Warn during inventory if sending through http not https
(https://www.rudder-project.org/redmine/issues/11284[#11284])

==== Plugin - API ACL

* Fixed: Rudder 4.3 missing important features for plugins, especially
ACL one (https://www.rudder-project.org/redmine/issues/12808[#12808])

==== Generic methods - Service Management

* Fixed: fail to restart certain services on Ubuntu because of
incomplete detection of systemd/upstart
(https://www.rudder-project.org/redmine/issues/12887[#12887])

==== API

* Fixed: JS error when changing the status of an api token
(https://www.rudder-project.org/redmine/issues/12947[#12947])
* Fixed: Can not create token
(https://www.rudder-project.org/redmine/issues/12940[#12940])
* Fixed: Tags in directives are ignored in POST API
(https://www.rudder-project.org/redmine/issues/12355[#12355])

==== Agent

* Fixed: Can not install rudder agent on AIX: libyaml.a could not be
loaded (https://www.rudder-project.org/redmine/issues/12966[#12966])

==== Plugins

* Fixed: rudder-pkg must disable plugin during major version Rudder
update (https://www.rudder-project.org/redmine/issues/12331[#12331])
* Fixed: rudder-pkg should fail installation is a dependency is missing
(https://www.rudder-project.org/redmine/issues/12749[#12749])
* Fixed: Declared plugin APIs not correctly regirstered in Rudder
(https://www.rudder-project.org/redmine/issues/12919[#12919])

==== System techniques

* Fixed: cron is always restarted since #12615
(https://www.rudder-project.org/redmine/issues/12886[#12886])
* Fixed: When a technique reports several time the exact same text,
there is only one report generated
(https://www.rudder-project.org/redmine/issues/6343[#6343])
* Fixed: Detection of minicurl and https is done in conflicting ways
(https://www.rudder-project.org/redmine/issues/12155[#12155])
* Fixed: Rudder agent needs 2 updates to work properly
(https://www.rudder-project.org/redmine/issues/12793[#12793])

==== Performance and scalability

* Fixed: Method copyResourceFile is quite inefficient
(https://www.rudder-project.org/redmine/issues/12702[#12702])

==== Techniques

* Fixed: double quoted introduced as a typo of parent ticket
(https://www.rudder-project.org/redmine/issues/12943[#12943])
* Fixed: Technique userManagement does not change shell
(https://www.rudder-project.org/redmine/issues/6395[#6395])
* Fixed: Missing support for ubuntu 18_04 in technique
aptPackageManagerSettings
(https://www.rudder-project.org/redmine/issues/12884[#12884])
* Fixed: Clean up the tests for sshKeyDistribution
(https://www.rudder-project.org/redmine/issues/12863[#12863])
* Fixed: fileTemplate technique does not correctly work in
multiversionned format in Rudder 4.3
(https://www.rudder-project.org/redmine/issues/12784[#12784])
* Fixed: Sudoers technique does not abide by the no password parameter
in technique version 3.2
(https://www.rudder-project.org/redmine/issues/12782[#12782])

==== System integration

* Fixed: Replace the log debug DEBUG
com.normation.rudder.services.policies.PromiseGenerationServiceImpl
which contains the timing summary to the policy.generation logger, in
INFO (https://www.rudder-project.org/redmine/issues/12731[#12731])
* Fixed: Generation gets stuck when cf-serverd is not running
(https://www.rudder-project.org/redmine/issues/12604[#12604])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky
* Dmitry Svyatogorov
* Florian Heigl

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 4.3.2 (2018-06-12)

=== Changes

==== Packaging

* Add agent support for Ubuntu 18.04 LTS ``Bionic Beaver''
(https://www.rudder-project.org/redmine/issues/12683[#12683])

==== Generic methods

* Add the possibility to customize filters and tests for jinja2
templating (https://www.rudder-project.org/redmine/issues/12761[#12761])
* Add a generic method to test variable content
(https://www.rudder-project.org/redmine/issues/12596[#12596])

==== Web - Nodes & inventories

* It’s not possible to search Nodes by their node lifecycle
(https://www.rudder-project.org/redmine/issues/12564[#12564])

==== Generic methods - Package Management

* Add a package module for cfengine supporting slackware
(https://www.rudder-project.org/redmine/issues/12684[#12684])

==== Architecture - Internal libs

* Enforce stricter checks by scala compiler with Xlint flags
(https://www.rudder-project.org/redmine/issues/12558[#12558])

==== Documentation

* Add a doc about generic method naming conventions
(https://www.rudder-project.org/redmine/issues/12594[#12594])
* Node lifecycle: documentation
(https://www.rudder-project.org/redmine/issues/12592[#12592])
* Add docs about Windows agent logging
(https://www.rudder-project.org/redmine/issues/12393[#12393])

==== Web - Compliance & node report

* Overriden directives are not listed in reports information
(https://www.rudder-project.org/redmine/issues/7616[#7616])

==== Packaging

* Strip binaries in rpm packages
(https://www.rudder-project.org/redmine/issues/12452[#12452])

==== Agent

* Upgrade to CFEngine 3.10.4 LTS
(https://www.rudder-project.org/redmine/issues/12576[#12576])

==== System techniques

* Add a way to override report mode in system techniques
(https://www.rudder-project.org/redmine/issues/12680[#12680])
* rudder-lib.st in the ``common'' system technique does not identify
crond as running when the ps is /usr/sbin/crond -l notice
(https://www.rudder-project.org/redmine/issues/12615[#12615])
* Remove big red button code from techniques
(https://www.rudder-project.org/redmine/issues/12525[#12525])

==== Performance and scalability

* Explore alternative format for compliance table
(https://www.rudder-project.org/redmine/issues/12621[#12621])

==== Techniques

* Make the `common' system technique identify crond on a slackware agent
(https://www.rudder-project.org/redmine/issues/12610[#12610])
* Add scripts to help migrate techniques to rudder server command
(https://www.rudder-project.org/redmine/issues/12614[#12614])

=== Bug fixes

==== API

* Fixed: Archive API always tells ``group'' even for other objects
(https://www.rudder-project.org/redmine/issues/12705[#12705])
* Fixed: NumberFormatException in NodeAPI 8 (runResponse)
(https://www.rudder-project.org/redmine/issues/12556[#12556])
* Fixed: Custom acl are not parsed by api account API
(https://www.rudder-project.org/redmine/issues/12585[#12585])

==== Web - UI & UX

* Fixed: Custom node properties from inventory are not found in group
search (https://www.rudder-project.org/redmine/issues/12572[#12572])
* Fixed: loading page and 404 page does not use correct style when
redirected by apache
(https://www.rudder-project.org/redmine/issues/12736[#12736])
* Fixed: Windows node show an empty Certificate Hash field in node
details (https://www.rudder-project.org/redmine/issues/11347[#11347])
* Fixed: GUI problem with long strings in reporting
(https://www.rudder-project.org/redmine/issues/12283[#12283])
* Fixed: When deleting an API account the removed row is not the good
one (https://www.rudder-project.org/redmine/issues/12638[#12638])
* Fixed: Compliance bar appears partially white in some graphes
(https://www.rudder-project.org/redmine/issues/12643[#12643])
* Fixed: Directive and Rule tree filter are very slow
(https://www.rudder-project.org/redmine/issues/12650[#12650])
* Fixed: While adding network in General settings CIDR notation
validation fails in special cases
(https://www.rudder-project.org/redmine/issues/12629[#12629])
* Fixed: Delete directive confirmation popup should display the action
to confirm (https://www.rudder-project.org/redmine/issues/12552[#12552])
* Fixed: In technique editor, mouse cursor on top of technique parameter
``use with'' should be a carret
(https://www.rudder-project.org/redmine/issues/12266[#12266])

==== Generic methods

* Fixed: Reporting context is not set correctly when using an iterator
somewhere (https://www.rudder-project.org/redmine/issues/12693[#12693])

==== Web - Nodes & inventories

* Fixed: Extend groups search capabilities for complex JSON Properties /
JsonPath (https://www.rudder-project.org/redmine/issues/9299[#9299])
* Fixed: cannot add two node properties at the same time from inventory
(https://www.rudder-project.org/redmine/issues/12760[#12760])
* Fixed: Slackware is not known by Rudder
(https://www.rudder-project.org/redmine/issues/12707[#12707])
* Fixed: Log with cause for a missing node is swallowed
(https://www.rudder-project.org/redmine/issues/12724[#12724])

==== Web - Maintenance

* Fixed: Java 9 / Java 10 compatibility: security exception for JS VM
(https://www.rudder-project.org/redmine/issues/12548[#12548])
* Fixed: Java 9 / Java 10 compatibility: javax/xml/bind removed
(https://www.rudder-project.org/redmine/issues/12557[#12557])

==== Web - Technique editor

* Fixed: Always get ``Technique diverges'' pop-up when coming back to
technique editor
(https://www.rudder-project.org/redmine/issues/12207[#12207])

==== Architecture - Internal libs

* Fixed: Missing ipv6 constraint regex test
(https://www.rudder-project.org/redmine/issues/12666[#12666])

==== Web - Config management

* Fixed: No reports on dsc only techniques on a Linux Node
(https://www.rudder-project.org/redmine/issues/12754[#12754])
* Fixed: Id of the ncf technique parameter used when generating Rudder
technique parameter instead of it’s name
(https://www.rudder-project.org/redmine/issues/12743[#12743])
* Fixed: When policies have wrong permissions (660), agent cannot be
executed, and reload server fails, it breaks the generation, and prevent
correcting the permission
(https://www.rudder-project.org/redmine/issues/12732[#12732])
* Fixed: Policies regeneration error when using a parameters with " char
(https://www.rudder-project.org/redmine/issues/12674[#12674])
* Fixed: ``Safelly'' typo in logs
(https://www.rudder-project.org/redmine/issues/12635[#12635])

==== Technique editor - API

* Fixed: Technique Editor may ignores some error when authenticating,
leading to unauthorized access
(https://www.rudder-project.org/redmine/issues/12720[#12720])

==== Web - Compliance & node report

* Fixed: $\{const.dollar} in generic method parameter leads to missing
report (https://www.rudder-project.org/redmine/issues/12616[#12616])

==== Packaging

* Fixed: .pyc file are not cleand up during postinst
(https://www.rudder-project.org/redmine/issues/12634[#12634])
* Fixed: Build fail because on non existent man3 directory
(https://www.rudder-project.org/redmine/issues/12632[#12632])
* Fixed: Error during postinst on upgrade to 4.3
(https://www.rudder-project.org/redmine/issues/12583[#12583])
* Fixed: Cleanup agent makefile
(https://www.rudder-project.org/redmine/issues/12449[#12449])
* Fixed: ncf script traceback error
(https://www.rudder-project.org/redmine/issues/12633[#12633])

==== System integration

* Fixed: apache overwrites error response from Rudder
(https://www.rudder-project.org/redmine/issues/12747[#12747])
* Fixed: Webapp log file have been renamed from stderrout.log to
jetty.log (https://www.rudder-project.org/redmine/issues/12607[#12607])

==== Agent

* Fixed: jobScheduler does not work when the first non-loopback
interface has no ip address
(https://www.rudder-project.org/redmine/issues/12262[#12262])

==== Documentation

* Fixed: Documentaiton should use full path to rudder-pkg for command
examples (https://www.rudder-project.org/redmine/issues/12771[#12771])
* Fixed: Adding missings informations for Windows plugin installation
(https://www.rudder-project.org/redmine/issues/12748[#12748])
* Fixed: Restricted java security policy breaks Rudder (class configured
for Cipher(provider: BC)cannot be found)
(https://www.rudder-project.org/redmine/issues/12606[#12606])
* Fixed: Fix various typos in ncf doc
(https://www.rudder-project.org/redmine/issues/12570[#12570])

==== Technique editor - UI/UX

* Fixed: Broken css when technique name is long
(https://www.rudder-project.org/redmine/issues/12545[#12545])

==== System techniques

* Fixed: System Techniques must not be added by reload technique, only
updated, else they are duplicated
(https://www.rudder-project.org/redmine/issues/12765[#12765])

==== Security

* Fixed: JS sandbox permission must be defined in a file
(https://www.rudder-project.org/redmine/issues/12450[#12450])
* Fixed: Remove max concurrent session limit to avoid denial of services
(https://www.rudder-project.org/redmine/issues/12581[#12581])

==== Performance and scalability

* Fixed: Unused formatter in policy generation spend a bit of time in
policy generation
(https://www.rudder-project.org/redmine/issues/12735[#12735])
* Fixed: Moving policies to their final position (last step of policies
writing) could be improved
(https://www.rudder-project.org/redmine/issues/12730[#12730])
* Fixed: We are missing a lot of timing measurement in policy generation
(https://www.rudder-project.org/redmine/issues/12725[#12725])

==== Techniques

* Fixed: Load modules from local ncf in Rudder policies
(https://www.rudder-project.org/redmine/issues/12774[#12774])
* Fixed: Process management: stopped sends multiple reports.
(https://www.rudder-project.org/redmine/issues/11683[#11683])
* Fixed: SSH Configuration Technique on AIX does not reload correctly
sshd service when there’s been a change
(https://www.rudder-project.org/redmine/issues/12745[#12745])
* Fixed: Misleading error message in Services technique when range of
number of process could not be repaired
(https://www.rudder-project.org/redmine/issues/12713[#12713])
* Fixed: Wrong reporting in ``ManagekeyValue'' technique
(https://www.rudder-project.org/redmine/issues/12603[#12603])
* Fixed: Enforce checkbox tooltip in groupmanagement technique is
misleading (https://www.rudder-project.org/redmine/issues/12670[#12670])
* Fixed: Missing report if two mountounts with the same target
(https://www.rudder-project.org/redmine/issues/12647[#12647])
* Fixed: Add zypper pattern option in package Technique. _please note
that it does not work yet and will be available in next release 4.3.3_
(https://www.rudder-project.org/redmine/issues/12700[#12700])
* Fixed: Missing report when we cannot change home directory in users
technique (https://www.rudder-project.org/redmine/issues/12555[#12555])
* Fixed: Typo in generic method File content
(https://www.rudder-project.org/redmine/issues/12507[#12507])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Daniel Fuleki
* Janos Mattyasovszky
* Ilan COSTA
* Vincent DAVY

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 4.3.1 (2018-05-04)

=== Changes

==== Web - UI & UX

* Make the compliance graph clickable
(https://www.rudder-project.org/redmine/issues/12429[#12429])

==== Generic methods

* Add generic methods to assign monitoring templates and parameters to
nodes (https://www.rudder-project.org/redmine/issues/12517[#12517])

==== Documentation

* Document the behavior of inventory hooks
(https://www.rudder-project.org/redmine/issues/8335[#8335])

==== Miscellaneous

* Add tests for sshKeyDistribution technique
(https://www.rudder-project.org/redmine/issues/12455[#12455])

==== Techniques

* New rudder technique : SNMP configuration to monitor the rudder agent
health (https://www.rudder-project.org/redmine/issues/12501[#12501])
* Add a system technique handling monitoring files sharing
(https://www.rudder-project.org/redmine/issues/12519[#12519])

=== Bug fixes

==== Technique editor - UI/UX

* Fixed: The filter field in the technique editor should not be
monospace (https://www.rudder-project.org/redmine/issues/12081[#12081])

==== Web - UI & UX

* Fixed: Missing border in Default policy mode setting
(https://www.rudder-project.org/redmine/issues/12236[#12236])
* Fixed: Inconsistent font for status of rule in accept new node page,
when looking at the Rules to be applied
(https://www.rudder-project.org/redmine/issues/12364[#12364])
* Fixed: Switch’s css is broken on the Api accounts page
(https://www.rudder-project.org/redmine/issues/12518[#12518])
* Fixed: Add space between filter and Event logs table
(https://www.rudder-project.org/redmine/issues/12515[#12515])
* Fixed: CSS of txt/json inputs is broken
(https://www.rudder-project.org/redmine/issues/12514[#12514])
* Fixed: Add margin between selects and button groups in Archives page
(https://www.rudder-project.org/redmine/issues/12513[#12513])
* Fixed: Buttons don’t follow a straight design
(https://www.rudder-project.org/redmine/issues/12512[#12512])

==== Generic methods

* Fixed: service restart uses an undefined variable
(https://www.rudder-project.org/redmine/issues/12553[#12553])

==== Web - Config management

* Fixed: Wrong parameter used to create dsc ncf techniques
(https://www.rudder-project.org/redmine/issues/12533[#12533])

==== Documentation

* Fixed: Wrong service name in agent install instruction in 4.3
(https://www.rudder-project.org/redmine/issues/12569[#12569])
* Fixed: Typo beeing -> being in rudder manual
(https://www.rudder-project.org/redmine/issues/12506[#12506])
* Fixed: Add a favicon for Rudder by example
(https://www.rudder-project.org/redmine/issues/12490[#12490])

==== Miscellaneous

* Fixed: wrong import in ssh-key-distribution tests
(https://www.rudder-project.org/redmine/issues/12511[#12511])

==== Packaging

* Fixed: Fix flask version during build
(https://www.rudder-project.org/redmine/issues/12541[#12541])
* Fixed: rudder-pkg python3 issue
(https://www.rudder-project.org/redmine/issues/12504[#12504])

==== Technique editor - API

* Fixed: Broken reporting for non-applicable generic methods
(https://www.rudder-project.org/redmine/issues/12542[#12542])

==== System integration

* Fixed: apache_acl file is remplaced, even on relay with no http
(https://www.rudder-project.org/redmine/issues/12530[#12530])

==== System techniques

* Fixed: monitoring_hook do no exist in initial promises
(https://www.rudder-project.org/redmine/issues/12563[#12563])
* Fixed: Don’t stop agent execution when uuid is missing on non
community agent
(https://www.rudder-project.org/redmine/issues/12529[#12529])
* Fixed: Access rules on Rudder servers/relays prevent in most case the
server from downloading/connecting on itself
(https://www.rudder-project.org/redmine/issues/12521[#12521])

==== Techniques

* Fixed: A rudder relay or server, with no nodes behind it, does not
share ncf (https://www.rudder-project.org/redmine/issues/12465[#12465])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 4.3.0 (2018-04-19)

=== Changes

==== Web - UI & UX

* Modify the mouse cursor when hovering the chart
(https://www.rudder-project.org/redmine/issues/12438[#12438])
* Allow to search on machine type in search nodes request
(https://www.rudder-project.org/redmine/issues/12380[#12380])
* NodeGroupId picker for subgroup selection
(https://www.rudder-project.org/redmine/issues/12311[#12311])
* Make dashboard graphs clickable
(https://www.rudder-project.org/redmine/issues/12358[#12358])

==== Generic methods

* Make reporting work when targeting several time the same item with
several generic method
(https://www.rudder-project.org/redmine/issues/12414[#12414])
* Synchronize ncf stdlib with cfengine 3.10.3 stdlib
(https://www.rudder-project.org/redmine/issues/12384[#12384])

==== Technique editor - Techniques

* Add import/export buttons to the technique editor
(https://www.rudder-project.org/redmine/issues/12280[#12280])

==== Documentation

* Add a ``Rudder by example'' guide to the documentation
(https://www.rudder-project.org/redmine/issues/12383[#12383])

==== Agent

* Add libacl to Rudder agent
(https://www.rudder-project.org/redmine/issues/12270[#12270])

==== Packaging

* Oracle jdk url has changed but not in ppa
(https://www.rudder-project.org/redmine/issues/12479[#12479])
* Disable default logger in ncf
(https://www.rudder-project.org/redmine/issues/12425[#12425])

==== Relay server or API

* Make Groups and Rules API accessible for internal use
(https://www.rudder-project.org/redmine/issues/12419[#12419])

=== Bug fixes

==== Web - UI & UX

* Fixed: Lifecycle UI elements (dropdown menu & display) looks bad
(https://www.rudder-project.org/redmine/issues/12048[#12048])
* Fixed: Node agent schedule cannot be changed due to a JS Error
(https://www.rudder-project.org/redmine/issues/12388[#12388])

==== Generic methods

* Fixed: Permissions dirs recursive has a wrong rename tag
(https://www.rudder-project.org/redmine/issues/12437[#12437])
* Fixed: service_restart_if has two deprecation tags
(https://www.rudder-project.org/redmine/issues/12435[#12435])

==== Technique editor - Techniques

* Fixed: Technique editor returning an error when saving
(https://www.rudder-project.org/redmine/issues/12464[#12464])

==== plugin-cfe-enterprise

* Fixed: Compute SHA key, and change key identification for enterprise
node (https://www.rudder-project.org/redmine/issues/12458[#12458])

==== Web - Config management

* Fixed: (breaking change) In Windows Agent, a ’' in a directive
parameter value is escaped but it should not
(https://www.rudder-project.org/redmine/issues/12390[#12390])

==== Miscellaneous

* Fixed: broken reporting for ssh key distribution technique
(https://www.rudder-project.org/redmine/issues/12444[#12444])
* Fixed: Report missing if no password given in User technique
(https://www.rudder-project.org/redmine/issues/12422[#12422])
* Fixed: wrong xenstore-read path on (at least) ubuntu
(https://www.rudder-project.org/redmine/issues/12376[#12376])

==== Packaging

* Fixed: rpm fails to build on aix
(https://www.rudder-project.org/redmine/issues/12480[#12480])
* Fixed: Problem: nothing provides libyaml needed by
rudder-agent-1398866025:4.3.0.rc3-1.SLES.12.x86_64
(https://www.rudder-project.org/redmine/issues/12461[#12461])

==== Plugins

* Fixed: rudder-pkg does not allow to install/update/remove several
plugin at once
(https://www.rudder-project.org/redmine/issues/12330[#12330])

==== Security

* Fixed: Failed generation with ``Could not initialize class
javax.crypto.JceSecurity''
(https://www.rudder-project.org/redmine/issues/12448[#12448])

==== Server components

* Fixed: Root server can be disable with node lifecycle ``ignore'' ``set
empty policies''
(https://www.rudder-project.org/redmine/issues/12324[#12324])

==== Techniques

* Fixed: When upgrading from 4.1 to 4.3, reports from Rudder Techniques
break reporting
(https://www.rudder-project.org/redmine/issues/12398[#12398])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 4.3.0.rc3 (2018-04-10)

=== Changes

==== Web - UI & UX

* Make API account page pluggable
(https://www.rudder-project.org/redmine/issues/12375[#12375])

==== Generic methods

* Create hook ncf methods that can be used in pre-/post-run hooks
(https://www.rudder-project.org/redmine/issues/11857[#11857])

==== Documentation

* Update doc for 4.3
(https://www.rudder-project.org/redmine/issues/12347[#12347])

==== Miscellaneous

* Update the techniques tests
(https://www.rudder-project.org/redmine/issues/12346[#12346])

=== Bug fixes

==== Generic methods

* Fixed: Canonify job-id in classes for scheduler methods
(https://www.rudder-project.org/redmine/issues/12382[#12382])
* Fixed: Job cheduler methods whith mode are broken
(https://www.rudder-project.org/redmine/issues/12378[#12378])
* Fixed: Unexpected report on several methods due to non-executed
bundles (https://www.rudder-project.org/redmine/issues/12368[#12368])
* Fixed: Missing report for ``Shared file to node''
(https://www.rudder-project.org/redmine/issues/12377[#12377])
* Fixed: Some methods which let another one do the reporting are broken
in 4.3 (https://www.rudder-project.org/redmine/issues/12371[#12371])

==== Web - Config management

* Fixed: Cannot generate policies when there is a loop in policy server
hierharchy (stackoverflow)
(https://www.rudder-project.org/redmine/issues/12359[#12359])

==== Web - Nodes & inventories

* Fixed: LDAP query checker must succeed when criteria is empty
(https://www.rudder-project.org/redmine/issues/12343[#12343])
* Fixed: ``Error when trying to find dependencies for that group'' when
accepting a node
(https://www.rudder-project.org/redmine/issues/12338[#12338])

==== Generic methods - File Management

* Fixed: Jinja2 templating: Shows error in output even when successful
(https://www.rudder-project.org/redmine/issues/12379[#12379])
* Fixed: Missing report in Manage keys-values in file because of invalid
conditions in ensure_key_value_option
(https://www.rudder-project.org/redmine/issues/12345[#12345])

==== Documentation

* Fixed: Remove references to foswiki in the doc
(https://www.rudder-project.org/redmine/issues/12363[#12363])

==== Packaging

* Fixed: rudder-agent fails to build on debian 7/ubuntu 12.04
(https://www.rudder-project.org/redmine/issues/12362[#12362])
* Fixed: Rudder agent fails to build on some os
(https://www.rudder-project.org/redmine/issues/12353[#12353])

==== Initial promises & sys tech

* Fixed: Error at policy generation when using sudoParameter technique
with Rudder 4.3
(https://www.rudder-project.org/redmine/issues/12339[#12339])

==== System integration

* Fixed: Temp folders of jetty are piling up in /var/rudder/tmp/jetty
(https://www.rudder-project.org/redmine/issues/11987[#11987])

==== Security

* Fixed: Bad session counting block user login after three session
created (https://www.rudder-project.org/redmine/issues/12367[#12367])

==== Server components

* Fixed: sysconfig/apache2 modifications get removed
(https://www.rudder-project.org/redmine/issues/11153[#11153])

==== Techniques

* Fixed: RudderUniqueId is not replaced when using OUTPATH in metadata,
causing no report in File Permissions
(https://www.rudder-project.org/redmine/issues/12344[#12344])
* Fixed: Time settings directive configuration not accessible to
non-root users
(https://www.rudder-project.org/redmine/issues/12303[#12303])
* Fixed: Correct path to permlist file in File Permissions in 4.3
(https://www.rudder-project.org/redmine/issues/12348[#12348])
* Fixed: Unsupported key types are silently ignored in ssh key
management technique
(https://www.rudder-project.org/redmine/issues/8618[#8618])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky
* Florian Heigl
* Rob Pomeroy

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 4.3.0.rc2 (2018-04-03)

=== Changes

==== Technique editor - UI/UX

* Rename class to condition in the interface
(https://www.rudder-project.org/redmine/issues/11766[#11766])

==== Web - UI & UX

* Missing information/bad UX in API authorization UI
(https://www.rudder-project.org/redmine/issues/12202[#12202])

==== Technique editor - API

* typo in name of method used in write_all_techniques
(https://www.rudder-project.org/redmine/issues/12335[#12335])

==== Web - Nodes & inventories

* Remove modifications made to the inventory by the agent
(https://www.rudder-project.org/redmine/issues/8919[#8919])

==== Web - Config management

* Add name of the parameter to bundle parameter when generation bundle
sequence (https://www.rudder-project.org/redmine/issues/12310[#12310])
* Generate dsc technique parameter
(https://www.rudder-project.org/redmine/issues/12289[#12289])
* Identify in technique metadata if techniques should enable or disable
ncf reporting
(https://www.rudder-project.org/redmine/issues/12291[#12291])

==== Generic methods

* Migrate generic methods towards new loging system
(https://www.rudder-project.org/redmine/issues/12227[#12227])

==== Agent

* Backport key size option for cf-key
(https://www.rudder-project.org/redmine/issues/12241[#12241])

==== Packaging

* Change defaults for embedding xml and yaml
(https://www.rudder-project.org/redmine/issues/12285[#12285])
* Cleanup build options and build results
(https://www.rudder-project.org/redmine/issues/12278[#12278])
* Add strict version dependency on ncf-api-virtualenv to rudder-webapp
(https://www.rudder-project.org/redmine/issues/12273[#12273])
* embed libyaml and libxml in cfengine
(https://www.rudder-project.org/redmine/issues/12187[#12187])
* Epoch should be fixed in packaging
(https://www.rudder-project.org/redmine/issues/12239[#12239])
* Embed curl in the agent
(https://www.rudder-project.org/redmine/issues/12186[#12186])

==== Initial promises & sys tech

* An agent run with initial promises should send its inventory more
often (https://www.rudder-project.org/redmine/issues/9676[#9676])

=== Bug fixes

==== Web - UI & UX

* Fixed: JS error when starting Rudder 4.3 with jetty 9
(https://www.rudder-project.org/redmine/issues/12002[#12002])

==== Generic methods

* Fixed: Broken file_enforce_content generic method in 4.3 due to
upmerge (https://www.rudder-project.org/redmine/issues/12226[#12226])

==== Web - Config management

* Fixed: Incomplete ``Rules to be applied'' summary when accepting a new
nodes when using groups of groups
(https://www.rudder-project.org/redmine/issues/12060[#12060])
* Fixed: Typo in agent build error ``reource''"
(https://www.rudder-project.org/redmine/issues/12314[#12314])

==== Technique editor - API

* Fixed: @action tag appears in method description in the editor
(https://www.rudder-project.org/redmine/issues/12080[#12080])

==== Web - Technique editor

* Fixed: Escaping issue in Users Technique Parameter
(https://www.rudder-project.org/redmine/issues/12101[#12101])

==== Plugin - API ACL

* Fixed: API failing on root node
(https://www.rudder-project.org/redmine/issues/12229[#12229])

==== Documentation

* Fixed: Missing configuration instructions at the end of node install
documentation
(https://www.rudder-project.org/redmine/issues/11927[#11927])
* Fixed: Remove doc of class_prefix variable
(https://www.rudder-project.org/redmine/issues/12176[#12176])
* Fixed: condition_from_expression documentation does not clearly state
how to use it
(https://www.rudder-project.org/redmine/issues/12157[#12157])

==== Miscellaneous

* Fixed: Wrong regex in FileTemplate technique
(https://www.rudder-project.org/redmine/issues/12263[#12263])

==== Agent

* Fixed: Add capabilities for Rudder agent 4.3
(https://www.rudder-project.org/redmine/issues/12322[#12322])
* Fixed: if we have syntax error in policies on the Rudder server,
rudder agent check says that all is fine
(https://www.rudder-project.org/redmine/issues/12220[#12220])
* Fixed: agent-health should not require reverse resolution
(https://www.rudder-project.org/redmine/issues/12218[#12218])

==== Packaging

* Fixed: Missing or invalid migration for techniques generated by
technique editor from 4.2 to 4.3
(https://www.rudder-project.org/redmine/issues/12232[#12232])
* Fixed: rudder-jetty should depend on headless jre on centos7
(https://www.rudder-project.org/redmine/issues/12328[#12328])
* Fixed: Remove useless files in agent package
(https://www.rudder-project.org/redmine/issues/12320[#12320])
* Fixed: agent-capabilities file should not be executable
(https://www.rudder-project.org/redmine/issues/12318[#12318])
* Fixed: Remove invalid comment in rudder-agent spec file
(https://www.rudder-project.org/redmine/issues/12312[#12312])
* Fixed: Rudder agent service not started in 4.3 after a reboot on
Centos7 (https://www.rudder-project.org/redmine/issues/12302[#12302])
* Fixed: Warning when upgrading from 4.2 to 4.3: No such file or
directory (https://www.rudder-project.org/redmine/issues/12222[#12222])
* Fixed: rudder-init fails ruding initial policy setup
(https://www.rudder-project.org/redmine/issues/12247[#12247])
* Fixed: AIX should not depend on curl
(https://www.rudder-project.org/redmine/issues/12245[#12245])
* Fixed: Wrong dependencies in agent rpm in 4.3
(https://www.rudder-project.org/redmine/issues/12184[#12184])

==== Initial promises & sys tech

* Fixed: Authorize reports: in techniques/system/common/1.0/hooks.st in
qa-test (https://www.rudder-project.org/redmine/issues/12244[#12244])

==== Server components

* Fixed: Agent components should not try to load failsafe.cf when
policies are broken
(https://www.rudder-project.org/redmine/issues/12243[#12243])
* Fixed: reload-cf-serverd fails if cf-serverd not running and /sbin not
in PATH (https://www.rudder-project.org/redmine/issues/11824[#11824])

==== Techniques

* Fixed: Missing report for component ``Post-modification hook'' when
cleaning files
(https://www.rudder-project.org/redmine/issues/12297[#12297])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Ilan COSTA
* Janos Mattyasovszky

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 4.3.0.rc1 (2018-03-15)

=== Changes

==== API

* The compliance API is missing a global compliance target
(https://www.rudder-project.org/redmine/issues/8584[#8584])

==== Web - UI & UX

* Rename class to condition in the interface
(https://www.rudder-project.org/redmine/issues/12174[#12174])
* Make Rudder UI pluggable (login + common layout)
(https://www.rudder-project.org/redmine/issues/12093[#12093])

==== Generic methods

* file_copy_with_check
(https://www.rudder-project.org/redmine/issues/11610[#11610])

==== Web - Nodes & inventories

* Allows inventories to be augmented by the user with custom properties
(https://www.rudder-project.org/redmine/issues/4670[#4670])
* Add more information about the inventory in the inventory process
reporting (https://www.rudder-project.org/redmine/issues/10084[#10084])

==== Documentation

* Remove bibliography from the doc
(https://www.rudder-project.org/redmine/issues/7733[#7733])
* Document scheduler generic method
(https://www.rudder-project.org/redmine/issues/6946[#6946])

==== Miscellaneous

* Make node post-acceptation properties configurable
(https://www.rudder-project.org/redmine/issues/11811[#11811])

==== Agent

* Backport complete variable table performance patch
(https://www.rudder-project.org/redmine/issues/12130[#12130])
* Update CFEngine to 3.10.3
(https://www.rudder-project.org/redmine/issues/12090[#12090])
* Add a ``rudder agent history'' command
(https://www.rudder-project.org/redmine/issues/12053[#12053])

==== Packaging

* remove ld.so.conf
(https://www.rudder-project.org/redmine/issues/8969[#8969])
* Stop providing rudder-policy-templates
(https://www.rudder-project.org/redmine/issues/12120[#12120])
* Use debconf to configure rudder-agent on debian
(https://www.rudder-project.org/redmine/issues/5919[#5919])
* Changelog on Rudder rpm hasn’t been updated since 2011
(https://www.rudder-project.org/redmine/issues/8609[#8609])

==== Initial promises & sys tech

* Keep N last inventories generated on the node
(https://www.rudder-project.org/redmine/issues/7908[#7908])
* Keep N last inventories generated on the node
(https://www.rudder-project.org/redmine/issues/7908[#7908])
* Implement disable-flag for policy server policy copy for nodes
(https://www.rudder-project.org/redmine/issues/11631[#11631])
* rename cf-served file and cfserved variable
(https://www.rudder-project.org/redmine/issues/12119[#12119])
* Create a global variable for ``shared-files'' path
(https://www.rudder-project.org/redmine/issues/6324[#6324])

==== System integration

* link policy server config to Rudder’s config dir
(https://www.rudder-project.org/redmine/issues/10847[#10847])

==== Architecture - Refactoring

* Remove ListTag workaround when JGit version > 1.2
(https://www.rudder-project.org/redmine/issues/2278[#2278])

==== Techniques

* Add post-hook to the manage key-value file techniques
(https://www.rudder-project.org/redmine/issues/12124[#12124])

=== Bug fixes

==== Technique editor - UI/UX

* Fixed: Parameters menu arrow does not work as expected
(https://www.rudder-project.org/redmine/issues/12082[#12082])

==== Web - UI & UX

* Fixed: Update / Delete buttons on group Category modification should
be separated
(https://www.rudder-project.org/redmine/issues/11782[#11782])

==== Generic methods

* Fixed: ncf 4.3 now requires CFEngine >= 3.10
(https://www.rudder-project.org/redmine/issues/12161[#12161])
* Fixed: command_execution_result does not report anything
(https://www.rudder-project.org/redmine/issues/12087[#12087])

==== Web - Nodes & inventories

* Fixed: Node details ``properties'' page broken: js not loading
(https://www.rudder-project.org/redmine/issues/12206[#12206])
* Fixed: No Machine Inventory in nodes list while the details are
complete (https://www.rudder-project.org/redmine/issues/12041[#12041])

==== Web - Technique editor

* Fixed: metadata.xml not generated when saving a technique from editor
(https://www.rudder-project.org/redmine/issues/12209[#12209])
* Fixed: Broken variable expression when using node properties in the
technique editor
(https://www.rudder-project.org/redmine/issues/10304[#10304])

==== Technique editor - API

* Fixed: Result class containing \{} are not properly canonized
(https://www.rudder-project.org/redmine/issues/11600[#11600])

==== Generic methods - File Management

* Fixed: We cannot use file_enforce_content with a list and enforce=true
(https://www.rudder-project.org/redmine/issues/12147[#12147])

==== Documentation

* Fixed: Please, legitimate ``Priority'' usage in multi-instance
directives (https://www.rudder-project.org/redmine/issues/11963[#11963])

==== Miscellaneous

* Fixed: On a fresh Rudder 4.3 centos6 install, error about ncf API in
logs (https://www.rudder-project.org/redmine/issues/12034[#12034])

==== Agent

* Fixed: Broken ``rudder agent check'' in 4.3
(https://www.rudder-project.org/redmine/issues/12178[#12178])
* Fixed: Broken ``rudder agent history'' in 4.3
(https://www.rudder-project.org/redmine/issues/12177[#12177])
* Fixed: Agent script argument parsing failure when using non-default
locale (https://www.rudder-project.org/redmine/issues/12131[#12131])
* Fixed: rudder remote run cuts down IP of remote host
(https://www.rudder-project.org/redmine/issues/11418[#11418])
* Fixed: With ``rudder agent run'', nothing is logged in
/var/rudder/cfengine-community/outputs/
(https://www.rudder-project.org/redmine/issues/10801[#10801])

==== Packaging

* Fixed: Broken rudder-agent 4.1->4.3 upgrade in debian 9
(https://www.rudder-project.org/redmine/issues/12182[#12182])
* Fixed: Remove suggestion to install cfengine in ncf package
(https://www.rudder-project.org/redmine/issues/12183[#12183])
* Fixed: On debian, with systemd rudder-agent services are not enabled
during postinst
(https://www.rudder-project.org/redmine/issues/12083[#12083])
* Fixed: On debian, installation is broken
(https://www.rudder-project.org/redmine/issues/12162[#12162])
* Fixed: rudder-webapp upgrade doesn’t commit updates to ncf hooks
(https://www.rudder-project.org/redmine/issues/6758[#6758])
* Fixed: rudder-inventory-ldap package provides openldap libraries
(https://www.rudder-project.org/redmine/issues/3377[#3377])

==== Initial promises & sys tech

* Fixed: We have broken reports on a root server in 4.3 beta1
(https://www.rudder-project.org/redmine/issues/12086[#12086])
* Fixed: If we a have generic method command_execution with parameter
/bin/true, we get an error on reporting for syslog restart on non-aix
nor solaris sytem
(https://www.rudder-project.org/redmine/issues/12139[#12139])

==== API

* Fixed: Unathenticated API v1 are not accessible anymore
(https://www.rudder-project.org/redmine/issues/12216[#12216])
* Fixed: Api does not fail on bad JSON
(https://www.rudder-project.org/redmine/issues/5931[#5931])

==== Techniques

* Fixed: Missing report in Group Management
(https://www.rudder-project.org/redmine/issues/12214[#12214])
* Fixed: Invalid call in descriptor of Technique File download (Rudder
server) , version 2.2 in branch 4.2 and 4.3
(https://www.rudder-project.org/redmine/issues/12213[#12213])
* Fixed: Typo in templating technique
(https://www.rudder-project.org/redmine/issues/12126[#12126])
* Fixed: Typo in tooltip of File content (from remote template) for path
of file (https://www.rudder-project.org/redmine/issues/12123[#12123])
* Fixed: sharedfile_to_node reports repaired even if it fails
(https://www.rudder-project.org/redmine/issues/11836[#11836])

==== Server components

* Fixed: Clarify support for SLES12 SP2 as Root Server
(https://www.rudder-project.org/redmine/issues/11854[#11854])
* Fixed: rudder server refusing nodes after an error in
check-rudder-agent
(https://www.rudder-project.org/redmine/issues/11309[#11309])

==== System integration

* Fixed: Stopping slapd fails if pid file is empty
(https://www.rudder-project.org/redmine/issues/10498[#10498])
* Fixed: service rudder-* outputs on stderror
(https://www.rudder-project.org/redmine/issues/6429[#6429])
* Fixed: Cannot run rudder server reload-techniques on RedHat 6.6
(https://www.rudder-project.org/redmine/issues/11907[#11907])
* Fixed: Promises shared with apache are group executable
(https://www.rudder-project.org/redmine/issues/12169[#12169])
* Fixed: send-clean.sh blocks on inventory parsing error
(https://www.rudder-project.org/redmine/issues/10019[#10019])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Michael Gliwinski
* Avit Sidis
* Dmitry Svyatogorov
* d i
* Janos Mattyasovszky
* The Ranger
* Jean Cardona
* Alexandre BRIANCEAU
* Alexander Brunhirl
* Florian Heigl

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 4.3.0.beta1 (2018-02-06)

=== Changes

==== Technique editor - UI/UX

* Change max field length from 2k to 16k
(https://www.rudder-project.org/redmine/issues/11859[#11859])

==== Web - UI & UX

* add margin to the magnifying glass icon in the Nodes table
(https://www.rudder-project.org/redmine/issues/11849[#11849])

==== Technique editor - API

* Use a fixed size font in the Technique editor parameters
(https://www.rudder-project.org/redmine/issues/11895[#11895])
* no reporting if value to report contains a variable
(https://www.rudder-project.org/redmine/issues/11913[#11913])
* Add support to parameters in ncf Techniques written with ncf builder
(https://www.rudder-project.org/redmine/issues/5673[#5673])

==== Web - Nodes & inventories

* Be able to create a groups containing Nodes list from an other group
(https://www.rudder-project.org/redmine/issues/6982[#6982])
* Remove the skipidentify variable and settings page entry
(https://www.rudder-project.org/redmine/issues/10719[#10719])
* Node lifecycle: add a node state
(https://www.rudder-project.org/redmine/issues/11748[#11748])

==== Web - Config management

* Add common pre- and post- agent run action triggered by Technique
logic (https://www.rudder-project.org/redmine/issues/11858[#11858])
* Don’t merge directive from same Technique on generation
(https://www.rudder-project.org/redmine/issues/10625[#10625])

==== Generic methods - File Management

* Use built-in function and remove dumpdatastate usage in ncf
(https://www.rudder-project.org/redmine/issues/11816[#11816])

==== Documentation

* Update doc for 4.3
(https://www.rudder-project.org/redmine/issues/12049[#12049])

==== Generic methods

* Add a method to unset all the classes of a prefix
(https://www.rudder-project.org/redmine/issues/11903[#11903])
* Implement a push / pop mechanism for audit mode
(https://www.rudder-project.org/redmine/issues/11732[#11732])
* Standardize generic methods name
(https://www.rudder-project.org/redmine/issues/11812[#11812])
* Synchronize stdlib from masterfiles
(https://www.rudder-project.org/redmine/issues/11716[#11716])

==== Agent

* Use system Perl instead of embedding into rudder-agent if possible
(https://www.rudder-project.org/redmine/issues/11741[#11741])
* Remove multiline output option from ``rudder agent'' command
(https://www.rudder-project.org/redmine/issues/11897[#11897])
* Add an option to add timing information to the agent run
(https://www.rudder-project.org/redmine/issues/9163[#9163])
* Only rudder version needs to be displayed in ``rudder agent info''
(https://www.rudder-project.org/redmine/issues/10706[#10706])
* Cleanup agent check
(https://www.rudder-project.org/redmine/issues/11723[#11723])

==== Packaging

* Upgrade openssl to 1.0.2n
(https://www.rudder-project.org/redmine/issues/11967[#11967])
* Replace rudder-agent init script by systemd units on compatible OSes
(https://www.rudder-project.org/redmine/issues/11684[#11684])
* Automatically package fusion dependencies
(https://www.rudder-project.org/redmine/issues/11855[#11855])
* Remove our syslog name patch in 4.3
(https://www.rudder-project.org/redmine/issues/11807[#11807])
* Add a subjectaltname to server certificate
(https://www.rudder-project.org/redmine/issues/11790[#11790])
* Add a curl dependency in the agent
(https://www.rudder-project.org/redmine/issues/11752[#11752])
* Add checksum verification of the agent sources
(https://www.rudder-project.org/redmine/issues/11742[#11742])
* Upgrade lmdb to 0.9.21 in the agent
(https://www.rudder-project.org/redmine/issues/11736[#11736])
* Upgrade openldap to 2.4.45
(https://www.rudder-project.org/redmine/issues/11733[#11733])
* Upgrade to Jetty9
(https://www.rudder-project.org/redmine/issues/11647[#11647])
* Create a rudder server upgrade-techniques commands
(https://www.rudder-project.org/redmine/issues/11059[#11059])

==== Initial promises & sys tech

* Remove old package promises from system Techniques
(https://www.rudder-project.org/redmine/issues/11717[#11717])
* Enable IPv6 for cf-serverd
(https://www.rudder-project.org/redmine/issues/9693[#9693])
* Drop old protocol and acl for agents
(https://www.rudder-project.org/redmine/issues/9502[#9502])

==== API

* Readonly API or otherwise restrictable API Accounts
(https://www.rudder-project.org/redmine/issues/5627[#5627])
* Add logic to generate ncf Technique files into Rudder
(https://www.rudder-project.org/redmine/issues/11783[#11783])

==== Architecture - Refactoring

* Remove most scala compilation warning
(https://www.rudder-project.org/redmine/issues/11955[#11955])
* Use scheduledJob logger for scheduledJob
(https://www.rudder-project.org/redmine/issues/11800[#11800])
* Clean-up trivial warnings
(https://www.rudder-project.org/redmine/issues/11786[#11786])
* Move all API v1 into their own package
(https://www.rudder-project.org/redmine/issues/11760[#11760])
* Remove dead code in AuthorizationType
(https://www.rudder-project.org/redmine/issues/11756[#11756])
* Remove remaining use of spring-jdbc
(https://www.rudder-project.org/redmine/issues/11667[#11667])
* Extract Rest API from Rudder-web project into a new Scala project
(https://www.rudder-project.org/redmine/issues/11677[#11677])
* Switch to cats ecosystem
(https://www.rudder-project.org/redmine/issues/11763[#11763])
* Autumn cleaning before 4.3 (parent-pom)
(https://www.rudder-project.org/redmine/issues/11637[#11637])

==== Techniques

* Add multiversion support to some Techniques
(https://www.rudder-project.org/redmine/issues/11687[#11687])

=== Bug fixes

==== Web - UI & UX

* Fixed: Javascript error on every pages, preventing usage of file
explorer (https://www.rudder-project.org/redmine/issues/11991[#11991])
* Fixed: Directives tree is not filtered after saving changes
(https://www.rudder-project.org/redmine/issues/11670[#11670])
* Fixed: Input text for repository in apt repository management is too
small (https://www.rudder-project.org/redmine/issues/11841[#11841])
* Fixed: ``Agent policy mode'' should be ``Node policy mode''
(https://www.rudder-project.org/redmine/issues/11837[#11837])

==== Technique editor - API

* Fixed: If change message is mandatory, we cannot update Technique with
Technique editor
(https://www.rudder-project.org/redmine/issues/12008[#12008])
* Fixed: Saving a Technique in the Technique editor in IE11 fails
(https://www.rudder-project.org/redmine/issues/11894[#11894])

==== Web - Config management

* Fixed: Audit mode flag is not correctly set on DSC Techniques
(https://www.rudder-project.org/redmine/issues/10974[#10974])
* Fixed: Unhelpful error message when applying a tehcnique with invalid
agent type to a node
(https://www.rudder-project.org/redmine/issues/10969[#10969])

==== Technique editor - Techniques

* Fixed: rudder_reporting file is invalid on nodes if it contains `&&'
in one of its parameter
(https://www.rudder-project.org/redmine/issues/11870[#11870])

==== Generic methods - Package Management

* Fixed: Wrong detection of package provider on debian for package_*
method (https://www.rudder-project.org/redmine/issues/11999[#11999])
* Fixed: Zypper hangs on dialogs / issues due to open tty
(https://www.rudder-project.org/redmine/issues/6291[#6291])

==== Web - Technique editor

* Fixed: Set flag to reload ncf Technique through Rudder during update
(https://www.rudder-project.org/redmine/issues/12005[#12005])

==== Web - Nodes & inventories

* Fixed: When a network interface is deleted from a node, it is not
removed on the Rudder server
(https://www.rudder-project.org/redmine/issues/12026[#12026])
* Fixed: Incorrect detection of architecture on Ubuntu 14.04 32 bits
(https://www.rudder-project.org/redmine/issues/11918[#11918])

==== Documentation

* Fixed: Missing documentation about InputTCPMaxSessions and when to
change its value in rsyslog
(https://www.rudder-project.org/redmine/issues/8613[#8613])
* Fixed: Merge ``Migration'' and ``Server migration'' subsections in the
doc (https://www.rudder-project.org/redmine/issues/11062[#11062])
* Fixed: Restore backup documentation is not correct
(https://www.rudder-project.org/redmine/issues/11177[#11177])
* Fixed: Redirect FAQ to faq.rudder-project.org
(https://www.rudder-project.org/redmine/issues/11905[#11905])

==== Generic methods

* Fixed: yum is run at each cf-promises, having a massive perf cost, on
redhat-like system
(https://www.rudder-project.org/redmine/issues/11937[#11937])
* Fixed: Add a comment about quotes in file_ensure_key_value parameters
documentation
(https://www.rudder-project.org/redmine/issues/11896[#11896])
* Fixed: Wrong result class in file_enforce_content
(https://www.rudder-project.org/redmine/issues/11880[#11880])
* Fixed: Abort bundle does not work in dry-run mode
(https://www.rudder-project.org/redmine/issues/11867[#11867])
* Fixed: ``Shared file to node'' method does not send file to node if
file to send was created during run
(https://www.rudder-project.org/redmine/issues/11869[#11869])

==== Agent

* Fixed: Autocompletion for rudder commands doesn’t work on RHEL and
SLES (https://www.rudder-project.org/redmine/issues/11885[#11885])
* Fixed: Errors are not diplayed when running agent without -i
(https://www.rudder-project.org/redmine/issues/9181[#9181])
* Fixed: The agent moves obstructions regardless of policy mode
(https://www.rudder-project.org/redmine/issues/11866[#11866])
* Fixed: When rudder agent disable fails it prints a success message
(https://www.rudder-project.org/redmine/issues/11936[#11936])
* Fixed: Agent process detection is wrong in rudder agent check on AIX
(https://www.rudder-project.org/redmine/issues/11921[#11921])
* Fixed: Escaping variable in a method call fails
(https://www.rudder-project.org/redmine/issues/11795[#11795])

==== Packaging

* Fixed: rudder-pkg 4.3 belives it is rudder 4.2
(https://www.rudder-project.org/redmine/issues/12074[#12074])
* Fixed: typo in rudder-server relay package install output
(https://www.rudder-project.org/redmine/issues/12064[#12064])
* Fixed: Reload of Techniques after update throught Technique editor
should only be done by Rudder, remove reload.sh hook
(https://www.rudder-project.org/redmine/issues/12010[#12010])
* Fixed: Upgrade Java version used when building webapp on old debian
versions, since oracle jvm links has changed
(https://www.rudder-project.org/redmine/issues/11981[#11981])
* Fixed: Rudder root on SLES12 shows LDAP error during installation
(https://www.rudder-project.org/redmine/issues/10454[#10454])
* Fixed: Impossible to share policies to DSC Nodes with a SLES11 Server
(https://www.rudder-project.org/redmine/issues/11856[#11856])
* Fixed: Remove old migration scripts
(https://www.rudder-project.org/redmine/issues/11743[#11743])

==== Initial promises & sys tech

* Fixed: Rudder server installation fails if apache cannot resolve
server hostname
(https://www.rudder-project.org/redmine/issues/11983[#11983])
* Fixed: Use rudder agent check in aix crontab
(https://www.rudder-project.org/redmine/issues/11920[#11920])
* Fixed: Inventory from a node on Xen dom0 is missing UUID and is
invalid (https://www.rudder-project.org/redmine/issues/11902[#11902])
* Fixed: remote execution is cut at 30 secondes
(https://www.rudder-project.org/redmine/issues/11416[#11416])

==== System integration

* Fixed: Configuration file of Rudder mention that we may change ``LDAP
DIT configuration'', which is wrong
(https://www.rudder-project.org/redmine/issues/10664[#10664])

==== Web - Compliance & node report

* Fixed: Compliance keeps on loading while expected reports are not
available for a node or a rule
(https://www.rudder-project.org/redmine/issues/7281[#7281])
* Fixed: Runaway quotation mark at Node report
(https://www.rudder-project.org/redmine/issues/11834[#11834])

==== Architecture - Dependencies

* Fixed: ERROR: canceling statement due to user request
(https://www.rudder-project.org/redmine/issues/11973[#11973])
* Fixed: Update to monix 2.3.3: critical bug corrected
(https://www.rudder-project.org/redmine/issues/12024[#12024])

==== Architecture - Refactoring

* Fixed: Remove scripts folder from rudder repo
(https://www.rudder-project.org/redmine/issues/12047[#12047])

==== Server components

* Fixed: There is a /var/cfengine/inputs on a Rudder server
(https://www.rudder-project.org/redmine/issues/8625[#8625])

==== Techniques

* Fixed: The Technique file copy from shared folder reports file source
instead of file destination
(https://www.rudder-project.org/redmine/issues/6564[#6564])
* Fixed: Group management Technique silently changes the group gid
(https://www.rudder-project.org/redmine/issues/11863[#11863])
* Fixed: Typo in services Technique preventing persisting post-hook
(https://www.rudder-project.org/redmine/issues/11861[#11861])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky
* Alexander Brunhirl
* Florian Heigl
* Dennis Cabooter

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
