= Changelogs for Rudder plugin auth-backends 7.2.\* versions

== auth-backends-7.2.2-2.6 (2023-03-31)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: New CVE in Jackson-Databind 2.13.4
    (https://issues.rudder.io/issues/21992[#21992])
* Fixed: Document oauth2 common error case
    (https://issues.rudder.io/issues/21987[#21987])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.2.1-2.5 (2023-03-31)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Jackson-databind used in oauth has CVE
    (https://issues.rudder.io/issues/21927[#21927])
* Fixed: Remaingin OAUTH secret in log in trace level
    (https://issues.rudder.io/issues/21896[#21896])

==== Documentation

* Fixed: OIDC doc contains a merge diff resolution comment
    (https://issues.rudder.io/issues/21897[#21897])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.2.0-2.5 (2023-03-31)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.2.0.rc1-2.5 (2023-03-31)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.2.0.beta1-2.5 (2023-03-31)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Broken plugins menu interface
    (https://issues.rudder.io/issues/21390[#21390])
* Fixed: Broken build of maven plugins with elm apps after minification
    (https://issues.rudder.io/issues/21217[#21217])

==== Documentation

* Fixed: Add case-sentitivity parameter in user file example
    (https://issues.rudder.io/issues/21250[#21250])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

