= Changelogs for Rudder plugin cve 7.2.\* versions

== cve-7.2.4-2.10 (2023-07-22)

=== Changes


==== Miscellaneous

* Use Html.lazy to optimise html rendering
    (https://issues.rudder.io/issues/22439[#22439])

=== Bug fixes

==== Miscellaneous

* Fixed: Syntax error in cve details request 
    (https://issues.rudder.io/issues/22451[#22451])
* Fixed: Do not load history of previously selected node/cve
    (https://issues.rudder.io/issues/22440[#22440])
* Fixed: The "Security management" link in the navigation menu is not correctly aligned with the other links
    (https://issues.rudder.io/issues/22399[#22399])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.4-2.9 (2023-07-22)

=== Changes


==== Miscellaneous

* API to get CVE by score/publishedDate
    (https://issues.rudder.io/issues/22189[#22189])
* Add a way to filter CVE check by cve id, node id and packages
    (https://issues.rudder.io/issues/22182[#22182])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.4-2.8 (2023-07-22)

=== Changes


==== Miscellaneous

* Some little optimisation on CVE plugin web application
    (https://issues.rudder.io/issues/22163[#22163])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.3-2.7 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.2-2.7 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.1-2.7 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Nodes with no cve are not displayed
    (https://issues.rudder.io/issues/22003[#22003])
* Fixed: Pass almalinux and rockylinux as redhat
    (https://issues.rudder.io/issues/21993[#21993])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.1-2.6 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.0-2.6 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.0.rc1-2.6 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Correct map to SoftwareUuid following 7.1.3 / 7.0.6
    (https://issues.rudder.io/issues/21479[#21479])
* Fixed: Augment timeout and make it configurable
    (https://issues.rudder.io/issues/21439[#21439])
* Fixed: I'm getting an error when running a CVE check
    (https://issues.rudder.io/issues/21174[#21174])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florent NEYRON

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.0.beta1-2.3 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

