= Changelogs for Rudder plugin cve 7.2.\* versions

== cve-7.2.1-2.7 (2022-12-06)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Nodes with no cve are not displayed
    (https://issues.rudder.io/issues/22003[#22003])
* Fixed: Pass almalinux and rockylinux as redhat
    (https://issues.rudder.io/issues/21993[#21993])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.1-2.6 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.0-2.6 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.0.rc1-2.6 (2022-12-06)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Correct map to SoftwareUuid following 7.1.3 / 7.0.6
    (https://issues.rudder.io/issues/21479[#21479])
* Fixed: Augment timeout and make it configurable
    (https://issues.rudder.io/issues/21439[#21439])
* Fixed: I'm getting an error when running a CVE check
    (https://issues.rudder.io/issues/21174[#21174])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.2.0.beta1-2.3 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

