= Changelogs for Rudder plugin dsc 7.2.\* versions

== dsc-7.2.9-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== CLI

* Fixed: error with directive that contains a ' in its name
    (https://issues.rudder.io/issues/22380[#22380])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.8-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Use fnv for calculating update splaytime
    (https://issues.rudder.io/issues/22890[#22890])

==== Security

* Fixed: Powershell injection from rudder properties
    (https://issues.rudder.io/issues/22412[#22412])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.7-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.6-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.5-2.2 (2023-07-22)

=== Changes


==== Miscellaneous

* API to get CVE by score/publishedDate
    (https://issues.rudder.io/issues/22189[#22189])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.4-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.3-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.2-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Rename technique parameters in rudder-directives.ps1 so that it works with changes from 14371
    (https://issues.rudder.io/issues/22062[#22062])
* Fixed: Plugin should not distribute test files
    (https://issues.rudder.io/issues/21973[#21973])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.1-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.0-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Add the UI to delete a campaign event
    (https://issues.rudder.io/issues/21776[#21776])

==== Packaging

* Fixed: Test files should not be packaged in the policies
    (https://issues.rudder.io/issues/21751[#21751])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.0.rc1-2.2 (2023-07-22)

=== Changes


==== Rudder web app

* Resurect DSC policy generation test for rudder 7.1
    (https://issues.rudder.io/issues/21483[#21483])

==== Miscellaneous

* Provide an interface to manage System update campaigns
    (https://issues.rudder.io/issues/21310[#21310])

=== Bug fixes

==== Rudder web app

* Fixed: Incorrect permissions for dsc generated policies
    (https://issues.rudder.io/issues/21567[#21567])
* Fixed: Adapt policy generation to DSC agent 7.2
    (https://issues.rudder.io/issues/21552[#21552])

==== Packaging

* Fixed: Update plugin makefile to build the F# rudderLib
    (https://issues.rudder.io/issues/21419[#21419])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.0.beta1-2.2 (2023-07-22)

=== Changes


==== Agent library

* Add logging and Rudder report writter to the rudderLib
    (https://issues.rudder.io/issues/21294[#21294])
* Add a code formatter for F#
    (https://issues.rudder.io/issues/21273[#21273])

==== Techniques

* Add WSUS support to the WindowsUpdate technique
    (https://issues.rudder.io/issues/21075[#21075])

==== Packaging

* Add base configuration for F# agent library
    (https://issues.rudder.io/issues/21251[#21251])
* Add base configuration for F# agent library
    (https://issues.rudder.io/issues/21251[#21251])

=== Bug fixes

==== Miscellaneous

* Fixed: Add backend to support system update campaign
    (https://issues.rudder.io/issues/21385[#21385])
* Fixed: Add F# linter to the rudderLib project and ci
    (https://issues.rudder.io/issues/21268[#21268])

==== Generic methods

* Fixed: Create a generic method to execute powershell command
    (https://issues.rudder.io/issues/21332[#21332])
* Fixed: Create a generic method to execute powershell command
    (https://issues.rudder.io/issues/21332[#21332])
* Fixed: Port ncf to the new rudderLib
    (https://issues.rudder.io/issues/21306[#21306])

==== Techniques

* Fixed: Windows update technique does not display the correct next scheduled date of execution
    (https://issues.rudder.io/issues/21354[#21354])
* Fixed: correct reporting in windowsUpdate technique
    (https://issues.rudder.io/issues/21277[#21277])

==== Packaging

* Fixed: Integrate the rudderLib to the agent and plugin build
    (https://issues.rudder.io/issues/21334[#21334])

==== Agent library

* Fixed: Add reports and console output to the rudderLib
    (https://issues.rudder.io/issues/21289[#21289])

==== CLI

* Fixed: 7.1.0 agent fails to run inventory
    (https://issues.rudder.io/issues/21066[#21066])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

