= Changelogs for Rudder plugin dsc 7.2.\* versions

== dsc-7.2.8-2.2 (2023-07-22)

=== Changes


==== ci

* make the dotnet dockerfile less cache consumming
    (https://issues.rudder.io/issues/22822[#22822])

=== Bug fixes

==== Miscellaneous

* Fixed: Use fnv for calculating update splaytime
    (https://issues.rudder.io/issues/22890[#22890])

==== Security

* Fixed: Powershell injection from rudder properties
    (https://issues.rudder.io/issues/22412[#22412])

==== ci

* Fixed: add label to rudder-agent-windows docker images
    (https://issues.rudder.io/issues/22915[#22915])

==== Generic methods

* Fixed: Powershell_execution documentation does not document the regex options used
    (https://issues.rudder.io/issues/22863[#22863])
* Fixed: Audit from Powershell execution documentation is truncated in the technique editor
    (https://issues.rudder.io/issues/22858[#22858])
* Fixed: File_lines_present fails to identify missings lines when they are a sub string of an already written line in the target path
    (https://issues.rudder.io/issues/22799[#22799])

==== Agent library

* Fixed: naming of agent run logs use hour on 12 hours rather than 24 hours
    (https://issues.rudder.io/issues/22752[#22752])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.7-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.6-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Generic methods

* Fixed: Missing documentation on generic methods Registry entry *
    (https://issues.rudder.io/issues/22316[#22316])

==== Techniques

* Fixed: WindowsSoftware technique in 2.1 version is not 7.2+ policy compatible
    (https://issues.rudder.io/issues/22389[#22389])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.5-2.2 (2023-07-22)

=== Changes


==== Miscellaneous

* API to get CVE by score/publishedDate
    (https://issues.rudder.io/issues/22189[#22189])

=== Bug fixes

==== Agent library

* Fixed: Fix the classes.ps1 library and test
    (https://issues.rudder.io/issues/22409[#22409])

==== CLI

* Fixed: when rudder agent is disabled, we can still run it 
    (https://issues.rudder.io/issues/21596[#21596])
* Fixed: rudder agent server-keys-reset does throw errors at execution
    (https://issues.rudder.io/issues/21231[#21231])
* Fixed: Execution time of the agent run is incorrectly computed
    (https://issues.rudder.io/issues/22327[#22327])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.4-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Generic methods

* Fixed: File Content always reports repaired on powershell 4.0
    (https://issues.rudder.io/issues/22223[#22223])

==== CLI

* Fixed: Fix typo in update.ps1
    (https://issues.rudder.io/issues/22145[#22145])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.3-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Security

* Fixed: Security update for Newtonsoft.Json
    (https://issues.rudder.io/issues/22181[#22181])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.2-2.2 (2023-07-22)

=== Changes


==== Misc

* Add scoped variable support to the linter
    (https://issues.rudder.io/issues/22039[#22039])

=== Bug fixes

==== Miscellaneous

* Fixed: Rename technique parameters in rudder-directives.ps1 so that it works with changes from 14371
    (https://issues.rudder.io/issues/22062[#22062])
* Fixed: Plugin should not distribute test files
    (https://issues.rudder.io/issues/21973[#21973])

==== Agent library

* Fixed: rudder_client does not work on powershell 4
    (https://issues.rudder.io/issues/22112[#22112])
* Fixed: Support Powershell 4
    (https://issues.rudder.io/issues/22073[#22073])
* Fixed: Some policies are invalid with Powershell4
    (https://issues.rudder.io/issues/22076[#22076])

==== CLI

* Fixed: Typo in the rudder.ps1 parameter attributes
    (https://issues.rudder.io/issues/22032[#22032])
* Fixed: rudder agent version vanished from the agent in 7.2.0
    (https://issues.rudder.io/issues/21946[#21946])
* Fixed: Postinst does not setup correctly the user path variable
    (https://issues.rudder.io/issues/18852[#18852])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.1-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: When upgrading to 7.2, displayVersion of earlier rudder versions are not properly cleaned out
    (https://issues.rudder.io/issues/21885[#21885])

==== CLI

* Fixed: Missing function Rudder-Control-Report when running a 7.2+ windows agent with a server <7.2
    (https://issues.rudder.io/issues/21884[#21884])

==== Misc

* Fixed: improve doc on testing
    (https://issues.rudder.io/issues/21862[#21862])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.0-2.2 (2023-07-22)

=== Changes


==== Security

* Add vulnerability check on dependencies
    (https://issues.rudder.io/issues/21843[#21843])

==== Generic methods

* Remove class_prefix tests as they are no longer managed by the methods
    (https://issues.rudder.io/issues/21818[#21818])
* Add tests to the condition from command method
    (https://issues.rudder.io/issues/21687[#21687])
* Add logs to the permissions_ntfs method
    (https://issues.rudder.io/issues/21799[#21799])
* Add an Audit-From-Powershell-Execution method
    (https://issues.rudder.io/issues/21764[#21764])
* Improve condition_from_* reporting
    (https://issues.rudder.io/issues/21743[#21743])
* Add tests for Condition_from_variable_match method
    (https://issues.rudder.io/issues/21692[#21692])
* Add tests for the File-From-Template method
    (https://issues.rudder.io/issues/21715[#21715])
* Add tests for condition_from_variable_existence
    (https://issues.rudder.io/issues/21689[#21689])
* Add tests for the file_content method
    (https://issues.rudder.io/issues/21696[#21696])
* Add tests for the file_lines_absent method
    (https://issues.rudder.io/issues/21716[#21716])
* Add tests for the file_lines_present method
    (https://issues.rudder.io/issues/21719[#21719])
* Add tests for file_from_http_server method
    (https://issues.rudder.io/issues/21712[#21712])
* Add tests for file_from_local_source method
    (https://issues.rudder.io/issues/21713[#21713])

==== Packaging

* Drop 6.1 compatibility for windows agents
    (https://issues.rudder.io/issues/21753[#21753])

==== CLI

* Add a message after agent update to warn that a shell respawn is most likely needed
    (https://issues.rudder.io/issues/21733[#21733])

==== Techniques

* Deprecate version 1.0 of the technique windowsUpdate 
    (https://issues.rudder.io/issues/21706[#21706])
* Deprecate the registry_edition old technique versions
    (https://issues.rudder.io/issues/21710[#21710])

==== System techniques

* Add simple test of node property loading and usage
    (https://issues.rudder.io/issues/20732[#20732])

=== Bug fixes

==== Miscellaneous

* Fixed: Add the UI to delete a campaign event
    (https://issues.rudder.io/issues/21776[#21776])

==== Packaging

* Fixed: Test files should not be packaged in the policies
    (https://issues.rudder.io/issues/21751[#21751])
* Fixed: rudder agent architecture is i586
    (https://issues.rudder.io/issues/21670[#21670])

==== Generic methods

* Fixed: Display-Report does not work in the > 7.2 tests as agentVersion variable is not defined
    (https://issues.rudder.io/issues/21863[#21863])
* Fixed: Directory_absent method throws non terminating exception when applied on an empty directory
    (https://issues.rudder.io/issues/20980[#20980])
* Fixed: LASTEXITCODE should always be reset before being checked
    (https://issues.rudder.io/issues/21739[#21739])
* Fixed: improve documentation of powershell_execution
    (https://issues.rudder.io/issues/21682[#21682])
* Fixed: File from_copy_from_rudder_shared_folder fails to retrieve the file when the parent destination folder exists but is not a proper folder
    (https://issues.rudder.io/issues/21780[#21780])
* Fixed: successRegex and repairedRegex should not be both mandatory
    (https://issues.rudder.io/issues/21770[#21770])
* Fixed: Incorrect parameters type for package_state_windows method
    (https://issues.rudder.io/issues/21745[#21745])
* Fixed: Fix dsc_apply method
    (https://issues.rudder.io/issues/21759[#21759])
* Fixed: Incorrect audit handling by check_compliance internal method
    (https://issues.rudder.io/issues/21746[#21746])
* Fixed: NCF sanity tests are written but not automatically run by the ci
    (https://issues.rudder.io/issues/20908[#20908])

==== ci

* Fixed: Missing powershell command on the python docker to run the sanity tests
    (https://issues.rudder.io/issues/21815[#21815])

==== Techniques

* Fixed: Translate windowsSoftware technique to the 7.2 syntax
    (https://issues.rudder.io/issues/21628[#21628])
* Fixed: Port the windowsUpdate technique to the new 7.2 syntax
    (https://issues.rudder.io/issues/21650[#21650])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.0.rc1-2.2 (2023-07-22)

=== Changes


==== Rudder web app

* Resurect DSC policy generation test for rudder 7.1
    (https://issues.rudder.io/issues/21483[#21483])

==== Miscellaneous

* Provide an interface to manage System update campaigns
    (https://issues.rudder.io/issues/21310[#21310])

==== Techniques

* Deprecate old windows technique versions
    (https://issues.rudder.io/issues/21704[#21704])

==== Generic methods

* Add tests for file_asbent method
    (https://issues.rudder.io/issues/21694[#21694])
* Add tests for directory_present method
    (https://issues.rudder.io/issues/21693[#21693])
* Add logging functions for techniques and directives
    (https://issues.rudder.io/issues/21559[#21559])
* Translate file_from_shared_folder and file_from_template_mustache to the new 7.2 syntax
    (https://issues.rudder.io/issues/21507[#21507])
* Migrate the registry* methods to 7.2 syntax
    (https://issues.rudder.io/issues/21481[#21481])

==== CLI

* Add reporting compliance mode support to the 7.2 agents
    (https://issues.rudder.io/issues/21598[#21598])
* Rudder runs should be stored on DSC agents
    (https://issues.rudder.io/issues/21562[#21562])
* Add displayName to method reporting context
    (https://issues.rudder.io/issues/21549[#21549])

==== Agent library

* Make agents 7.2 compatible with older policies
    (https://issues.rudder.io/issues/21400[#21400])

=== Bug fixes

==== Rudder web app

* Fixed: Incorrect permissions for dsc generated policies
    (https://issues.rudder.io/issues/21567[#21567])
* Fixed: Adapt policy generation to DSC agent 7.2
    (https://issues.rudder.io/issues/21552[#21552])

==== Packaging

* Fixed: Update plugin makefile to build the F# rudderLib
    (https://issues.rudder.io/issues/21419[#21419])
* Fixed: Postinst fails to find the utils.ps1 file
    (https://issues.rudder.io/issues/21591[#21591])
* Fixed: Packaging should not package test assets
    (https://issues.rudder.io/issues/21566[#21566])
* Fixed: Error in rudderLib loading in postinst
    (https://issues.rudder.io/issues/21557[#21557])

==== Agent library

* Fixed: Fix MethodStatus order to have the Error as most weighted and Control as the least weighted
    (https://issues.rudder.io/issues/21679[#21679])
* Fixed: Allow custom messages for report na
    (https://issues.rudder.io/issues/21610[#21610])
* Fixed: The 7.2 rudderLib does not support optional reporting
    (https://issues.rudder.io/issues/21550[#21550])
* Fixed: Context uuid are changed when merged
    (https://issues.rudder.io/issues/21547[#21547])
* Fixed: "result_na" reporting status is set as "resultNA" which is unknown by the webapp
    (https://issues.rudder.io/issues/21545[#21545])
* Fixed: Agent version format is not nuget compatible
    (https://issues.rudder.io/issues/21530[#21530])
* Fixed: Add AssemblyVersion to the rudderLib 
    (https://issues.rudder.io/issues/21464[#21464])

==== Techniques

* Fixed: Port the registryManagement technique to the nex 7.2 syntax
    (https://issues.rudder.io/issues/21639[#21639])
* Fixed: windowsUpdate text improvement
    (https://issues.rudder.io/issues/21384[#21384])

==== Generic methods

* Fixed: Error with permissions-NTFS generic method
    (https://issues.rudder.io/issues/21593[#21593])
* Fixed: error with condition from command
    (https://issues.rudder.io/issues/21595[#21595])
* Fixed: file from shared folder report an error
    (https://issues.rudder.io/issues/21589[#21589])
* Fixed: Make the 7.2 plugin compatible with 7.1 or older agents
    (https://issues.rudder.io/issues/21574[#21574])
* Fixed: File_from_local_source method fails when the target file is located in the root folder of a disk
    (https://issues.rudder.io/issues/21568[#21568])
* Fixed: Translate windows* methods to the 7.2 syntax
    (https://issues.rudder.io/issues/21518[#21518])
* Fixed: Translate permissions_ntfs and package_state_windows to the 7.2 syntax
    (https://issues.rudder.io/issues/21521[#21521])
* Fixed: Translate user* methods to the 7.2 syntax
    (https://issues.rudder.io/issues/21516[#21516])
* Fixed: Translate the variable* methods to the 7.2 syntax
    (https://issues.rudder.io/issues/21505[#21505])
* Fixed: Translate service* methods to the 7.2 syntax
    (https://issues.rudder.io/issues/21501[#21501])
* Fixed: Variable from command method does not execute itself in audit mode
    (https://issues.rudder.io/issues/21404[#21404])
* Fixed: Typos in File-Lines-* methods preventing correct encoding
    (https://issues.rudder.io/issues/21391[#21391])

==== CLI

* Fixed: Add log rotatation to the agent history logs
    (https://issues.rudder.io/issues/21597[#21597])
* Fixed: Remove any reference to the persistent lib
    (https://issues.rudder.io/issues/21573[#21573])
* Fixed: Incorrect filename for run logs
    (https://issues.rudder.io/issues/21535[#21535])
* Fixed: Typo in file loading
    (https://issues.rudder.io/issues/21415[#21415])

==== System techniques

* Fixed: Missing reports in system techniques in 7.2
    (https://issues.rudder.io/issues/21421[#21421])

==== Miscellaneous

* Fixed: typo in powershell_execution method
    (https://issues.rudder.io/issues/21426[#21426])

==== Misc

* Fixed: fix tests
    (https://issues.rudder.io/issues/21398[#21398])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.2.0.beta1-2.2 (2023-07-22)

=== Changes


==== Agent library

* Add logging and Rudder report writter to the rudderLib
    (https://issues.rudder.io/issues/21294[#21294])
* Add a code formatter for F#
    (https://issues.rudder.io/issues/21273[#21273])

==== Techniques

* Add WSUS support to the WindowsUpdate technique
    (https://issues.rudder.io/issues/21075[#21075])

==== Packaging

* Add base configuration for F# agent library
    (https://issues.rudder.io/issues/21251[#21251])
* Add base configuration for F# agent library
    (https://issues.rudder.io/issues/21251[#21251])

=== Bug fixes

==== Miscellaneous

* Fixed: Add backend to support system update campaign
    (https://issues.rudder.io/issues/21385[#21385])
* Fixed: Add F# linter to the rudderLib project and ci
    (https://issues.rudder.io/issues/21268[#21268])

==== Generic methods

* Fixed: Create a generic method to execute powershell command
    (https://issues.rudder.io/issues/21332[#21332])
* Fixed: Create a generic method to execute powershell command
    (https://issues.rudder.io/issues/21332[#21332])
* Fixed: Port ncf to the new rudderLib
    (https://issues.rudder.io/issues/21306[#21306])

==== Techniques

* Fixed: Windows update technique does not display the correct next scheduled date of execution
    (https://issues.rudder.io/issues/21354[#21354])
* Fixed: correct reporting in windowsUpdate technique
    (https://issues.rudder.io/issues/21277[#21277])

==== Packaging

* Fixed: Integrate the rudderLib to the agent and plugin build
    (https://issues.rudder.io/issues/21334[#21334])

==== Agent library

* Fixed: Add reports and console output to the rudderLib
    (https://issues.rudder.io/issues/21289[#21289])

==== CLI

* Fixed: 7.1.0 agent fails to run inventory
    (https://issues.rudder.io/issues/21066[#21066])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

