= Changelogs for Rudder plugin system-updates 7.2.\* versions

== system-updates-7.2.0-1.5 (2023-03-31)

=== Changes


==== Miscellaneous

* Reload events when saving a campaign
    (https://issues.rudder.io/issues/21848[#21848])
* Display error output
    (https://issues.rudder.io/issues/21847[#21847])

=== Bug fixes

==== Miscellaneous

* Fixed: errors and output of results should be optionnal
    (https://issues.rudder.io/issues/21876[#21876])
* Fixed: Campaign events are duplicated when swtiching between events and campaign tab  and back to events again
    (https://issues.rudder.io/issues/21870[#21870])
* Fixed: Improve the appearance of the "execution schedule" form
    (https://issues.rudder.io/issues/21860[#21860])
* Fixed: Campaign events should not all be loaded directly within the UI
    (https://issues.rudder.io/issues/21850[#21850])
* Fixed: Add version support to system update campaign
    (https://issues.rudder.io/issues/21813[#21813])
* Fixed: Improve the display of the command output in the details of a node
    (https://issues.rudder.io/issues/21769[#21769])
* Fixed: Add the UI to delete a campaign event
    (https://issues.rudder.io/issues/21776[#21776])
* Fixed: Adapt plugin to new schedule model
    (https://issues.rudder.io/issues/21812[#21812])
* Fixed: The "Reason" popover does not close automatically.
    (https://issues.rudder.io/issues/21800[#21800])
* Fixed: Make the selection of Targets more accessible when creating a campaign
    (https://issues.rudder.io/issues/21747[#21747])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.2.0.rc1-1.5 (2023-03-31)

=== Changes


==== Miscellaneous

* Make system directives and rules created by a system update campaign 
    (https://issues.rudder.io/issues/21700[#21700])

=== Bug fixes

==== Miscellaneous

* Fixed: Improve campaign info display in event details
    (https://issues.rudder.io/issues/21735[#21735])
* Fixed: Mark the difference between ongoing events and planned and skipped events
    (https://issues.rudder.io/issues/21717[#21717])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.2.0.rc1-1.4 (2023-03-31)

=== Changes


==== Miscellaneous

* Scheduled campaign should be skipped when plugin is disabled 
    (https://issues.rudder.io/issues/21663[#21663])
* Handle Server time zone in UI 
    (https://issues.rudder.io/issues/21620[#21620])
* Display the list of impacted nodes and their packages in the Result tab of a campaign event
    (https://issues.rudder.io/issues/21519[#21519])
* Provide an interface to manage System update campaigns
    (https://issues.rudder.io/issues/21310[#21310])
* Provide an interface to manage System update campaigns
    (https://issues.rudder.io/issues/21310[#21310])
* Handle windows update in plugin
    (https://issues.rudder.io/issues/21165[#21165])

=== Bug fixes

==== Miscellaneous

* Fixed: Allow to skip campaign events
    (https://issues.rudder.io/issues/21699[#21699])
* Fixed: fix some issues in the campaigns view
    (https://issues.rudder.io/issues/21688[#21688])
* Fixed: fix some issues in the campaigns view
    (https://issues.rudder.io/issues/21688[#21688])
* Fixed: Elm app path are produced in a directory and are not kept by plugin packging
    (https://issues.rudder.io/issues/21646[#21646])
* Fixed: Improve the display of the list of past events
    (https://issues.rudder.io/issues/21633[#21633])
* Fixed: Make datatables filterable and sortable
    (https://issues.rudder.io/issues/21614[#21614])
* Fixed: Display the list of past events of a campaign
    (https://issues.rudder.io/issues/21563[#21563])
* Fixed: Fix plugin in various places to display result
    (https://issues.rudder.io/issues/21613[#21613])
* Fixed: Add test data api server side for dev iteration
    (https://issues.rudder.io/issues/21564[#21564])
* Fixed: Make the filters work on the list of campaign events
    (https://issues.rudder.io/issues/21494[#21494])
* Fixed: Create the interface for selecting the groups of a campaign
    (https://issues.rudder.io/issues/21466[#21466])
* Fixed: Create the interface for selecting the groups of a campaign
    (https://issues.rudder.io/issues/21466[#21466])
* Fixed: Handling dates
    (https://issues.rudder.io/issues/21472[#21472])
* Fixed: Improve the display of nodes OS icon
    (https://issues.rudder.io/issues/21070[#21070])
* Fixed: build.conf is not packaged in correct directory
    (https://issues.rudder.io/issues/21032[#21032])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.2.0.beta1-1.2 (2023-03-31)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Add backend to support system update campaign
    (https://issues.rudder.io/issues/21385[#21385])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

