= Changelogs for Rudder plugin system-updates 7.2.\* versions

== system-updates-7.2.2-1.9 (2023-03-31)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Campaign directive name may be duplicated if two campaign have the same name at different moments
    (https://issues.rudder.io/issues/22149[#22149])
* Fixed: Campaign name must be not empty and reboot message is not clear
    (https://issues.rudder.io/issues/22140[#22140])
* Fixed: Adapt plugin to changes in #22041
    (https://issues.rudder.io/issues/22066[#22066])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.2.2-1.8 (2023-03-31)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Adapt plugin to changes in #22041
    (https://issues.rudder.io/issues/22066[#22066])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.2.1-1.9 (2023-03-31)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.2.1-1.8 (2023-03-31)

=== Changes


==== Miscellaneous

* Make System update campaing plugin api public
    (https://issues.rudder.io/issues/22082[#22082])
* Add skip reason in event information tab
    (https://issues.rudder.io/issues/21871[#21871])
* Display campaign description as markdown
    (https://issues.rudder.io/issues/22033[#22033])
* Display list of all nodes impacted by a campaign event, not just the one that have responded
    (https://issues.rudder.io/issues/22030[#22030])
* Add links to campaign and events
    (https://issues.rudder.io/issues/22056[#22056])
* Add filter by date for event lists
    (https://issues.rudder.io/issues/21966[#21966])

=== Bug fixes

==== Miscellaneous

* Fixed: Keep the duration of a campaign when changing its start date
    (https://issues.rudder.io/issues/22042[#22042])
* Fixed: error when trying to skip a campaign
    (https://issues.rudder.io/issues/22079[#22079])
* Fixed: Document behavior of system update for audit-only nodes
    (https://issues.rudder.io/issues/21969[#21969])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.2.1-1.7 (2023-03-31)

=== Changes


==== Miscellaneous

* Add a datepicker for date selection in one-shot campaigns
    (https://issues.rudder.io/issues/21928[#21928])

=== Bug fixes

==== Miscellaneous

* Fixed: Facilitate the selection of the day and time for the start and end of a campaign
    (https://issues.rudder.io/issues/21948[#21948])
* Fixed: When 2 system update campaign apply to a unique node, only one is applied
    (https://issues.rudder.io/issues/21985[#21985])
* Fixed: Rename version table headers in Node result
    (https://issues.rudder.io/issues/21951[#21951])
* Fixed: Minute duration of campaign is wrong
    (https://issues.rudder.io/issues/21949[#21949])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.2.1-1.6 (2023-03-31)

=== Changes


==== Miscellaneous

* Add system-update technique tests back
    (https://issues.rudder.io/issues/21922[#21922])
* Package system update campaign technique within the plugin
    (https://issues.rudder.io/issues/21909[#21909])

==== Documentation

* Add patch management documentation
    (https://issues.rudder.io/issues/21868[#21868])

=== Bug fixes

==== Miscellaneous

* Fixed: Missing report from the system update technique
    (https://issues.rudder.io/issues/21921[#21921])
* Fixed: Make campaigns deactivatable
    (https://issues.rudder.io/issues/21874[#21874])
* Fixed: Missing latest changes on Monthly schedule
    (https://issues.rudder.io/issues/21882[#21882])
* Fixed: Display server date and show future schedule event date
    (https://issues.rudder.io/issues/21881[#21881])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.2.0-1.5 (2023-03-31)

=== Changes


==== Miscellaneous

* Reload events when saving a campaign
    (https://issues.rudder.io/issues/21848[#21848])
* Display error output
    (https://issues.rudder.io/issues/21847[#21847])

=== Bug fixes

==== Miscellaneous

* Fixed: errors and output of results should be optionnal
    (https://issues.rudder.io/issues/21876[#21876])
* Fixed: Campaign events are duplicated when swtiching between events and campaign tab  and back to events again
    (https://issues.rudder.io/issues/21870[#21870])
* Fixed: Improve the appearance of the "execution schedule" form
    (https://issues.rudder.io/issues/21860[#21860])
* Fixed: Campaign events should not all be loaded directly within the UI
    (https://issues.rudder.io/issues/21850[#21850])
* Fixed: Add version support to system update campaign
    (https://issues.rudder.io/issues/21813[#21813])
* Fixed: Improve the display of the command output in the details of a node
    (https://issues.rudder.io/issues/21769[#21769])
* Fixed: Add the UI to delete a campaign event
    (https://issues.rudder.io/issues/21776[#21776])
* Fixed: Adapt plugin to new schedule model
    (https://issues.rudder.io/issues/21812[#21812])
* Fixed: The "Reason" popover does not close automatically.
    (https://issues.rudder.io/issues/21800[#21800])
* Fixed: Make the selection of Targets more accessible when creating a campaign
    (https://issues.rudder.io/issues/21747[#21747])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.2.0.rc1-1.5 (2023-03-31)

=== Changes


==== Miscellaneous

* Make system directives and rules created by a system update campaign 
    (https://issues.rudder.io/issues/21700[#21700])

=== Bug fixes

==== Miscellaneous

* Fixed: Improve campaign info display in event details
    (https://issues.rudder.io/issues/21735[#21735])
* Fixed: Mark the difference between ongoing events and planned and skipped events
    (https://issues.rudder.io/issues/21717[#21717])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.2.0.rc1-1.4 (2023-03-31)

=== Changes


==== Miscellaneous

* Scheduled campaign should be skipped when plugin is disabled 
    (https://issues.rudder.io/issues/21663[#21663])
* Handle Server time zone in UI 
    (https://issues.rudder.io/issues/21620[#21620])
* Display the list of impacted nodes and their packages in the Result tab of a campaign event
    (https://issues.rudder.io/issues/21519[#21519])
* Provide an interface to manage System update campaigns
    (https://issues.rudder.io/issues/21310[#21310])
* Provide an interface to manage System update campaigns
    (https://issues.rudder.io/issues/21310[#21310])
* Handle windows update in plugin
    (https://issues.rudder.io/issues/21165[#21165])

=== Bug fixes

==== Miscellaneous

* Fixed: Allow to skip campaign events
    (https://issues.rudder.io/issues/21699[#21699])
* Fixed: fix some issues in the campaigns view
    (https://issues.rudder.io/issues/21688[#21688])
* Fixed: fix some issues in the campaigns view
    (https://issues.rudder.io/issues/21688[#21688])
* Fixed: Elm app path are produced in a directory and are not kept by plugin packging
    (https://issues.rudder.io/issues/21646[#21646])
* Fixed: Improve the display of the list of past events
    (https://issues.rudder.io/issues/21633[#21633])
* Fixed: Make datatables filterable and sortable
    (https://issues.rudder.io/issues/21614[#21614])
* Fixed: Display the list of past events of a campaign
    (https://issues.rudder.io/issues/21563[#21563])
* Fixed: Fix plugin in various places to display result
    (https://issues.rudder.io/issues/21613[#21613])
* Fixed: Add test data api server side for dev iteration
    (https://issues.rudder.io/issues/21564[#21564])
* Fixed: Make the filters work on the list of campaign events
    (https://issues.rudder.io/issues/21494[#21494])
* Fixed: Create the interface for selecting the groups of a campaign
    (https://issues.rudder.io/issues/21466[#21466])
* Fixed: Create the interface for selecting the groups of a campaign
    (https://issues.rudder.io/issues/21466[#21466])
* Fixed: Handling dates
    (https://issues.rudder.io/issues/21472[#21472])
* Fixed: Improve the display of nodes OS icon
    (https://issues.rudder.io/issues/21070[#21070])
* Fixed: build.conf is not packaged in correct directory
    (https://issues.rudder.io/issues/21032[#21032])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-7.2.0.beta1-1.2 (2023-03-31)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Add backend to support system update campaign
    (https://issues.rudder.io/issues/21385[#21385])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

