= Changelogs for Rudder plugin user-management 7.2.\* versions

== user-management-7.2.6-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.2.5-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: secrets are leaking at the install of the plugin
    (https://issues.rudder.io/issues/22441[#22441])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.2.4-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.2.3-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.2.2-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.2.1-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.2.0-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.2.0.rc1-2.2 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-7.2.0.beta1-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Broken plugins menu interface
    (https://issues.rudder.io/issues/21390[#21390])
* Fixed: Broken build of maven plugins with elm apps after minification
    (https://issues.rudder.io/issues/21217[#21217])

==== Documentation

* Fixed: Add case-sentitivity parameter in user file example
    (https://issues.rudder.io/issues/21250[#21250])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

