= Change logs for Rudder 6.1

Rudder 6.1 is currently a maintained version of Rudder.

This page provides a summary of changes for each version. Previous beta

== [Private] Rudder 6.1.17 (2021-11-19)

=== Changes

[WARNING]
====

This version is only available for extended support subscription

====
    

==== CI

* Change the slack notification form the ncf tests
    (https://issues.rudder.io/issues/20143[#20143])

=== Bug fixes

==== Packaging

* Fixed: ubuntu 13 doesn't support tlsv1.2 
    (https://issues.rudder.io/issues/20122[#20122])
* Fixed: old distro build fail to get source
    (https://issues.rudder.io/issues/20063[#20063])

==== Documentation

* Fixed: Documentation about collection access in jinja2 template is incorect
    (https://issues.rudder.io/issues/20234[#20234])

==== Performance and scalability

* Fixed: Improve compliance computation efficiency
    (https://issues.rudder.io/issues/20254[#20254])
* Fixed: Store processes of an inventory after storing the inventory
    (https://issues.rudder.io/issues/20006[#20006])

==== Relay server or API

* Fixed: Vulnerability in chrono
    (https://issues.rudder.io/issues/20160[#20160])
* Fixed: Vulnerability in time crate
    (https://issues.rudder.io/issues/20141[#20141])

==== Web - Maintenance

* Fixed: Error when unserializing ChangeRequest modifying Directives based on Techniques  that have been deleted
    (https://issues.rudder.io/issues/3783[#3783])

==== Web - Nodes & inventories

* Fixed: confusing search option for Node: "Policy Node ID"
    (https://issues.rudder.io/issues/20093[#20093])
* Fixed: Number of CPU is wrongly reported
    (https://issues.rudder.io/issues/19988[#19988])

==== Techniques

* Fixed: sshKeyDistribution doesn't correctly reports on missing home folder
    (https://issues.rudder.io/issues/19944[#19944])

==== Generic methods

* Fixed: Pass the zypper_pattern test in staging
    (https://issues.rudder.io/issues/20108[#20108])
* Fixed: testinfra based tests should pass via the python executable and not py.test
    (https://issues.rudder.io/issues/20001[#20001])
* Fixed: Strict mode of file_key_value_present_option does not introduce unwanted escpaing characters
    (https://issues.rudder.io/issues/19908[#19908])

==== CI

* Fixed: Remove ubuntu20 from the Jenkinsfile test since thehost is unstable atm
    (https://issues.rudder.io/issues/20056[#20056])
* Fixed: Cover all supported server OS in the PR automated tests.
    (https://issues.rudder.io/issues/19979[#19979])
* Fixed: Add ncf tests to the repo Jenkinsfile
    (https://issues.rudder.io/issues/19970[#19970])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.



== [Private] Rudder 6.1.16 (2021-09-03)

=== Changes

[WARNING]
====

This version is only available for extended support subscription

====
    

==== Packaging

* Optimize ldap binaries with -O2
    (https://issues.rudder.io/issues/19648[#19648])

=== Bug fixes

==== Packaging

* Fixed: Update openssl to 1.1.1l
    (https://issues.rudder.io/issues/19854[#19854])
* Fixed: Fail on elm build error
    (https://issues.rudder.io/issues/19689[#19689])

==== Documentation

* Fixed: Document that a "rudder agent server-keys-reset" is necessary to move a node to another policy server
    (https://issues.rudder.io/issues/19761[#19761])
* Fixed: Wrong procedure for import of configuration
    (https://issues.rudder.io/issues/19712[#19712])

==== System integration

* Fixed: Git error when deleting a node or archiving everything, and very slow git
    (https://issues.rudder.io/issues/19398[#19398])
* Fixed: Rudder fails to stop on boot error
    (https://issues.rudder.io/issues/19567[#19567])

==== Miscellaneous

* Fixed: Error about cfengine key when deleting a node
    (https://issues.rudder.io/issues/19571[#19571])
* Fixed: NoSuchFileException: /var/rudder/policy-generation-info/node-configuration-hashes.json
    (https://issues.rudder.io/issues/19589[#19589])

==== Relay server or API

* Fixed: Data race in crossbeam-deque
    (https://issues.rudder.io/issues/19833[#19833])
* Fixed: Relayd deadlocks when trying to forward a shared-file
    (https://issues.rudder.io/issues/19547[#19547])
* Fixed: Prevent race condition in relayd tests
    (https://issues.rudder.io/issues/19569[#19569])

==== Architecture - Internal libs

* Fixed: RunNuCommandTest fails with timeout on CI
    (https://issues.rudder.io/issues/19828[#19828])

==== Security

* Fixed: Two vulnerabilities in hyper
    (https://issues.rudder.io/issues/19731[#19731])

==== Web - Nodes & inventories

* Fixed: Incorrect pattern matching leads to error in inventory parsing
    (https://issues.rudder.io/issues/19632[#19632])

==== Web - Config management

* Fixed: It is impossible to read properties with a read-only account
    (https://issues.rudder.io/issues/19631[#19631])
* Fixed: Can't access filesystem type from group criteria
    (https://issues.rudder.io/issues/19559[#19559])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Gaëtan Chagneau

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.



== [Private] Rudder 6.1.15 (2021-07-20)

=== Changes

[WARNING]
====

This version is only available for extended support subscription

====
    

=== Bug fixes

==== Miscellaneous

* Fixed: Or selector for property Name=Value selector returns 0 elements
    (https://issues.rudder.io/issues/19538[#19538])

==== Documentation

* Fixed: Correctly name LICENSES folder in repo
    (https://issues.rudder.io/issues/19535[#19535])

==== Security

* Fixed: CVE in jsonpath dependency
    (https://issues.rudder.io/issues/19530[#19530])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.



== [Private] Rudder 6.1.14 (2021-07-09)

=== Changes

[WARNING]
====

This version is only available for extended support subscription

====
    

==== Packaging

* Add ci checks for packages
    (https://issues.rudder.io/issues/19362[#19362])
* Improve pylint config and add formatter to rudder-pkg
    (https://issues.rudder.io/issues/19441[#19441])
* rudder-pkg test should use python3
    (https://issues.rudder.io/issues/19405[#19405])
* Backport typos checks to 6.1
    (https://issues.rudder.io/issues/19359[#19359])
* Clean workspace at the end of Rust builds
    (https://issues.rudder.io/issues/19246[#19246])
* Clean workspace at the end of Rust builds
    (https://issues.rudder.io/issues/19246[#19246])
* Add ci check for techniques
    (https://issues.rudder.io/issues/19355[#19355])
* Add ci checks on rudder-agent repo
    (https://issues.rudder.io/issues/19354[#19354])

==== Documentation

* Add ci check for typos in docs
    (https://issues.rudder.io/issues/19360[#19360])

=== Bug fixes

==== Agent

* Fixed: rudder-agent-postinst fails in 7.0 while closing fd
    (https://issues.rudder.io/issues/19429[#19429])
* Fixed: Rudder agent check should check if certificate matches private key
    (https://issues.rudder.io/issues/19392[#19392])

==== Packaging

* Fixed: Broken agent postinst script
    (https://issues.rudder.io/issues/19406[#19406])
* Fixed: Broken short hostname in agent certificate
    (https://issues.rudder.io/issues/19447[#19447])
* Fixed: Api doc publish does not require docs label
    (https://issues.rudder.io/issues/19408[#19408])

==== Documentation

* Fixed: Remove wrong doc about services passwords
    (https://issues.rudder.io/issues/19493[#19493])
* Fixed: Fix docs about HTTPS reporting in non-compliant mode
    (https://issues.rudder.io/issues/19437[#19437])
* Fixed: Update Ansible integration link to Rudder inventory script
    (https://issues.rudder.io/issues/19420[#19420])
* Fixed: Document minimum version of JDK (8u92)
    (https://issues.rudder.io/issues/19280[#19280])
* Fixed: Missing 'settings' layer in the allowed_networks API doc
    (https://issues.rudder.io/issues/19502[#19502])
* Fixed: Add name to LDAP pool to help debugging
    (https://issues.rudder.io/issues/19284[#19284])

==== Security

* Fixed: Lack of HTML escaping in nodes list
    (https://issues.rudder.io/issues/19456[#19456])
* Fixed: Vulnerability in spring-security
    (https://issues.rudder.io/issues/19503[#19503])
* Fixed: Enforce stricter restriction on authorized node id and hostname
    (https://issues.rudder.io/issues/19457[#19457])
* Fixed: Command injection in plugins repository file names
    (https://issues.rudder.io/issues/19442[#19442])
* Fixed: CVE in spring dependency
    (https://issues.rudder.io/issues/19407[#19407])
* Fixed: Update snakeyaml dependency for security
    (https://issues.rudder.io/issues/19400[#19400])
* Fixed: rudder.auth.admin.pass should be stored in bcrypt format
    (https://issues.rudder.io/issues/19308[#19308])
* Fixed: Ignore security alert for unused js embeded in scala lib
    (https://issues.rudder.io/issues/19272[#19272])

==== Performance and scalability

* Fixed: Inefficient comparision of strings in Rudder
    (https://issues.rudder.io/issues/19467[#19467])
* Fixed: Improve NodeInfo cache
    (https://issues.rudder.io/issues/19399[#19399])
* Fixed: Move use of cache outside of semaphore in NodeInfoService
    (https://issues.rudder.io/issues/19396[#19396])
* Fixed: Semaphore on Nodeinfoservice is not working
    (https://issues.rudder.io/issues/19351[#19351])

==== Relay server or API

* Fixed: Prevent parameter option injection in remote run
    (https://issues.rudder.io/issues/19455[#19455])
* Fixed: relayd on relays fails to retry inventories upload
    (https://issues.rudder.io/issues/19375[#19375])

==== System techniques

* Fixed: Missing cleanup of /var/rudder/reports/failed
    (https://issues.rudder.io/issues/19435[#19435])

==== Web - Config management

* Fixed: Inventory with updated properties doesn't always start a policy generation
    (https://issues.rudder.io/issues/19414[#19414])
* Fixed: Semaphore in APIAccountRepository,GitArchiverUtils and maybe PolicyServerManagementService are not semaphoring
    (https://issues.rudder.io/issues/19363[#19363])

==== Web - Nodes & inventories

* Fixed: When a node is totally deleted, cache in NodeInfoService can't know about it
    (https://issues.rudder.io/issues/19394[#19394])
* Fixed: In inventory, if there are two "rudder" tag, uuid are concatenated
    (https://issues.rudder.io/issues/19305[#19305])
* Fixed: Error when processing old inventories with davfs temporary files
    (https://issues.rudder.io/issues/19268[#19268])

==== API

* Fixed: Info API is not documented
    (https://issues.rudder.io/issues/19395[#19395])
* Fixed: API shows only part of the memory information
    (https://issues.rudder.io/issues/19374[#19374])
* Fixed: Remove reference to x-www-form-urlencoded in API commands
    (https://issues.rudder.io/issues/19276[#19276])

==== System integration

* Fixed: Confusing message when we disable non-compliant-report log
    (https://issues.rudder.io/issues/19381[#19381])

==== Techniques

* Fixed: Policy validation at the end of policy generation spends too much time evaluating things
    (https://issues.rudder.io/issues/19477[#19477])
* Fixed: File content always reports repair when "Replace content" is selected
    (https://issues.rudder.io/issues/19445[#19445])
* Fixed: Invalid reporting in file content technique
    (https://issues.rudder.io/issues/19431[#19431])
* Fixed: cron management doesn't support multiline entry correctly
    (https://issues.rudder.io/issues/19336[#19336])
* Fixed: When configuring a comment in ssh key in technique ssh key distribution, 6 spaces are added at start of comment line
    (https://issues.rudder.io/issues/19335[#19335])
* Fixed: User Management technique tries to always change user gid when forcing the check of user gid everytime
    (https://issues.rudder.io/issues/19269[#19269])
* Fixed: Group management technique doesn't correctly honor gid option
    (https://issues.rudder.io/issues/19266[#19266])

==== CI

* Fixed: Hardcod the output of the style test TestClassPrefix in success cases
    (https://issues.rudder.io/issues/19404[#19404])
* Fixed:  Add typos check to CI config
    (https://issues.rudder.io/issues/19343[#19343])
* Fixed: Force pylint3 instead of pylint in qa-test
    (https://issues.rudder.io/issues/19390[#19390])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Lars Koenen

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== [Private] Rudder 6.1.18 (2021-12-17)

=== Changes

[WARNING]
====

This version is only available for extended support subscription

====
    

==== CI

* Discard old builds
    (https://issues.rudder.io/issues/20408[#20408])
* Test ncf in docker
    (https://issues.rudder.io/issues/20374[#20374])

==== Relay server or API

* Add relayd man page build to Jenkinsfile
    (https://issues.rudder.io/issues/20327[#20327])

==== Documentation

* Dockerify api-doc test, build and publication
    (https://issues.rudder.io/issues/20272[#20272])

=== Bug fixes

==== Security

* Fixed: Upgrade logback version for LOGBACK-1591 / JNDI
    (https://issues.rudder.io/issues/20421[#20421])

==== Architecture - Dependencies

* Fixed: Rudder build when skipping tests
    (https://issues.rudder.io/issues/20410[#20410])

==== Web - Config management

* Fixed: Non system technique appears in "System status tab"
    (https://issues.rudder.io/issues/20383[#20383])

==== Performance and scalability

* Fixed: Method getByRulesCompliance used by API is highly inefficient
    (https://issues.rudder.io/issues/20310[#20310])
* Fixed: Method getByRulesCompliance used by API is highly inefficient
    (https://issues.rudder.io/issues/20310[#20310])
* Fixed: Method getByRulesCompliance used by API is highly inefficient
    (https://issues.rudder.io/issues/20310[#20310])
* Fixed: Method getByRulesCompliance used by API is highly inefficient
    (https://issues.rudder.io/issues/20310[#20310])
* Fixed: spurious "connection_read(9): no connection!" in /var/log/rudder/ldap/slapd.log
    (https://issues.rudder.io/issues/19980[#19980])

==== Miscellaneous

* Fixed: Mount elm tmp dir in tmpfs to avoid lock failure on concurrent builds
    (https://issues.rudder.io/issues/20361[#20361])
* Fixed: Rudder agent factory-reset don't regenerate inventory
    (https://issues.rudder.io/issues/20282[#20282])

==== CI

* Fixed: Rudder-pkg tests timeout sometimes
    (https://issues.rudder.io/issues/20354[#20354])
* Fixed: Only run compatibility tests during the night
    (https://issues.rudder.io/issues/20323[#20323])
* Fixed: Split test and build tasks in Jenkins file
    (https://issues.rudder.io/issues/20320[#20320])
* Fixed: Dockerify tests
    (https://issues.rudder.io/issues/20275[#20275])

==== Relay server or API

* Fixed: Vulnerability in tokio
    (https://issues.rudder.io/issues/20269[#20269])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.13 (2021-05-18)

=== Changes
    
==== Packaging

* Improve script linter in rudder repo
    (https://issues.rudder.io/issues/19243[#19243])
* Improve script linter in rudder repo
    (https://issues.rudder.io/issues/19243[#19243])
* Set CVSS limit for failing webapp dependency check
    (https://issues.rudder.io/issues/19214[#19214])
* Add maven deploy task to pipeline
    (https://issues.rudder.io/issues/19197[#19197])
* Add scripts to setup Rust build environements in CI
    (https://issues.rudder.io/issues/19184[#19184])

==== Miscellaneous

* Improve linter and test configuration
    (https://issues.rudder.io/issues/19177[#19177])

==== Security

* Use https repos in maven config
    (https://issues.rudder.io/issues/19164[#19164])

=== Bug fixes

==== Generic methods - File Management

* Fixed: The Generic Method "File copy from Rudder shared Folder" ignores Audit policy mode
    (https://issues.rudder.io/issues/19144[#19144])
* Fixed: Condition is ignored after "File from remote template"
    (https://issues.rudder.io/issues/19212[#19212])

==== Packaging

* Fixed: Shared file broken on upgraded servers with SELinux enabled
    (https://issues.rudder.io/issues/19188[#19188])
* Fixed: Update reflections to remove vulnerable guava dependency
    (https://issues.rudder.io/issues/19216[#19216])
* Fixed: Allow building without sccache
    (https://issues.rudder.io/issues/19225[#19225])
* Fixed: postinstall fails on machines with long hostname
    (https://issues.rudder.io/issues/19185[#19185])

==== Web - Config management

* Fixed: Empty /var/rudder/policy-generation-info/node-configuration-hashes.json after a policy generation that changed nothing
    (https://issues.rudder.io/issues/19248[#19248])
* Fixed: AUTHORIZED_NETWORKS system variable must be multivalued
    (https://issues.rudder.io/issues/19217[#19217])
* Fixed: Lots of files are created in /var/rudder/inventories/debug
    (https://issues.rudder.io/issues/19171[#19171])
* Fixed: Cannot load file browser if subfolders of the shared-folder contain dead symlinks
    (https://issues.rudder.io/issues/19158[#19158])

==== Miscellaneous

* Fixed: relay package fails to build on rhel7
    (https://issues.rudder.io/issues/19247[#19247])
* Fixed: API documentation is missleading for properties
    (https://issues.rudder.io/issues/19202[#19202])
* Fixed: Policy generation does change technique resource files when it should not
    (https://issues.rudder.io/issues/19222[#19222])
* Fixed: setting a job with schedule_simple in catchup mode does not honor the schedule
    (https://issues.rudder.io/issues/19227[#19227])

==== API

* Fixed: Undocumented API rudder_verify_certificates
    (https://issues.rudder.io/issues/19235[#19235])
* Fixed: Missing documentation for POST allowedNetwords API
    (https://issues.rudder.io/issues/18506[#18506])

==== Security

* Fixed: Check dependence fails with NPE
    (https://issues.rudder.io/issues/19231[#19231])

==== Web - UI & UX

* Fixed: Date picker in search (last inventory) is broken
    (https://issues.rudder.io/issues/19228[#19228])

==== Performance and scalability

* Fixed: Slow computation of dynamic groups on large system
    (https://issues.rudder.io/issues/18981[#18981])
* Fixed: backup file are not copied correctly when the destination directory is on another FS
    (https://issues.rudder.io/issues/19218[#19218])
* Fixed: Put node cache info into a file in place of LDAP
    (https://issues.rudder.io/issues/19213[#19213])

==== Architecture - Dependencies

* Fixed: Some java dependencies have security warning and should be updated
    (https://issues.rudder.io/issues/19211[#19211])

==== Web - Technique editor

* Fixed: Techniques using a condition containing a variable are not canonified correctly with dsc agent
    (https://issues.rudder.io/issues/19199[#19199])

==== Web - Compliance & node report

* Fixed: Webapp tests fail if repository path contains an '@'
    (https://issues.rudder.io/issues/19186[#19186])

==== Plugins management

* Fixed: Detection of dependencies for plugin can fail if the python lib of another distrib is present
    (https://issues.rudder.io/issues/19187[#19187])
* Fixed: when we install a plugin, if the dependency (package manager) is not met, it still tries to install it and fails
    (https://issues.rudder.io/issues/18999[#18999])

==== Agent

* Fixed: Command "rudder agent policy-server <server ip>" return code = 1 when ok
    (https://issues.rudder.io/issues/19157[#19157])
* Fixed: cannot upgrade directives because curl checks certificates
    (https://issues.rudder.io/issues/19175[#19175])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Jean Cardona
* Lars Koenen
* Axel Bouet

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


==  Rudder 6.1.12 (2021-04-15)

=== Changes


==== Packaging

* Split cargo-deny from qa-test
    (https://issues.rudder.io/issues/19083[#19083])

=== Bug fixes

==== Packaging

* Fixed: Update openssl to 1.1.1k
    (https://issues.rudder.io/issues/19090[#19090])
* Fixed: Vulnerability in relayd dependencies diesel and generic-array
    (https://issues.rudder.io/issues/19087[#19087])

==== Documentation

* Fixed: Incorrect option in pg_restore for archive 
    (https://issues.rudder.io/issues/19036[#19036])

==== Web - Config management

* Fixed: Allow to put empty value in technique parameters
    (https://issues.rudder.io/issues/19115[#19115])

==== Web - UI & UX

* Fixed: Syntax helper in the parameter page is outdated
    (https://issues.rudder.io/issues/19108[#19108])

==== API

* Fixed: Add more tests for API (directives, techniques, parameters)
    (https://issues.rudder.io/issues/19086[#19086])
* Fixed: Missing example for server key reset
    (https://issues.rudder.io/issues/19065[#19065])

==== Security

* Fixed: Vulnerabilities in relayd hyper dependency
    (https://issues.rudder.io/issues/18903[#18903])

==== Agent

* Fixed: Typo in agent error message
    (https://issues.rudder.io/issues/19130[#19130])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Lars Koenen

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.11 (2021-03-19)

=== Changes

=== Bug fixes

==== System integration

* Fixed: Upgrade script fails in system technique update (empty commit)
    (https://issues.rudder.io/issues/19044[#19044])

==== Web - Config management

* Fixed: Cannot load file browser when shared-folder contains dead symlinks
    (https://issues.rudder.io/issues/18200[#18200])

==== Web - UI & UX

* Fixed: Custom bar and logo are not displayed in the login form while option is enabled in the Branding plugin
    (https://issues.rudder.io/issues/19040[#19040])

==== Web - Technique editor

* Fixed: Technique editor error when an class is not correctly defined
    (https://issues.rudder.io/issues/19039[#19039])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Nicolas Ecarnot

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.10 (2021-03-18)

=== Release Notes

==== Change of behavior for empty technique parameters

Previously, when adding a new parameter to a technique in the technique editor, all directives based on this technique
were still valid and used an empty value for the new parameter. This leads to unexpected behaviors, and makes adding
parameters to techniques potentially dangerous.

To prevent this type of problems (in the scope of a patch release) we had to totally prevent passing empty parameters to techniques from the technique editor. This makes missing parameters a policy generation error, allowing to safely provide
them to directives after modifying the source technique.

This may break existing directives that rely on an expression which evaluates to an empty value, like a property containing an empty string, or a property value with an empty default.
In this case, you can pass a specific value like
`None` or a space char to indicate an empty value, and modify the technique to handle the special case
as a workaround.

We will work on a better solution in a future version, allowing to make the difference between new parameters and
intentionally blank ones.

(https://issues.rudder.io/issues/18832[#18832])

==== Policy server reload

We fixed a known issue is the way we reload the policy server (the service that distributes policies to Unix systems).

Previously, when adding a node or modifying allowed networks, a configuration reload was triggered, but it was only effective when the service became idle. On loaded Rudder servers or relays, this may totally prevent service reload, and thus
prevent the new nodes from connecting.

We replaced the reload by a graceful restart mechanism which takes effect immediately. This should not
cause any visible changes, except that two `cf-serverd` processes might be running at the same time (on
handling existing connections until completion, one handling the new ones).

(https://issues.rudder.io/issues/18893[#18893])

==== Other important fixes

* We fixed lock issues in Rudder server logic, this should make Rudder safer and faster and thus we recommend all users to update to 6.2.3 (https://issues.rudder.io/issues/18983[#18983])
* In rare cases, the agent inventory processes could pile up, exhausting resources of the machine. This has been fixed, another important reason to update to 6.2.3 (https://issues.rudder.io/issues/18832[#18832])
* OOM exception now stops Rudder correctly with information logs either in rudder-jetty service or in webapp logs, but some JVM, especially old Java 8, still don't log anything (https://issues.rudder.io/issues/18955[#18955]). As a consequence, Rudder now requires at least OpenJDK 1.8.0-92.

=== Changes

==== Packaging

* Update embedded openssl
    (https://issues.rudder.io/issues/18913[#18913])

==== Web - Config management

* Add a settings to delay start of policy generation
    (https://issues.rudder.io/issues/18845[#18845])

==== Techniques

* Add an "upgrade only" option to the technique packageManagement
    (https://issues.rudder.io/issues/18909[#18909])

==== Generic methods - File Management

* Document usage of sys.ipv4 var in jinja
    (https://issues.rudder.io/issues/18905[#18905])

=== Bug fixes

==== Packaging

* Fixed: Upgrade failed from 5.0.20 to 6.1.9 on SLES
    (https://issues.rudder.io/issues/18891[#18891])

==== System integration

* Fixed: Fatal exception doesn't cause rudder to stop anymore
    (https://issues.rudder.io/issues/18955[#18955])

==== Server components

* Fixed: After the promises generation, cf-serverd config may not be reloaded, preventing new nodes from connecting
    (https://issues.rudder.io/issues/8351[#8351])

==== Agent

* Fixed: Error logs about "Method '...' failed in some repairs" are useless and should be at verbose level instead
    (https://issues.rudder.io/issues/18914[#18914])
* Fixed: Agent run schedule problem
    (https://issues.rudder.io/issues/18846[#18846])
* Fixed: Agent run schedule problem
    (https://issues.rudder.io/issues/18846[#18846])
* Fixed: Rudder Agent consumes complete Memory because of fdisk
    (https://issues.rudder.io/issues/18832[#18832])

==== Documentation

* Fixed: Update some plugin documentation
    (https://issues.rudder.io/issues/18962[#18962])
* Fixed: Missing licence info in pom.xml
    (https://issues.rudder.io/issues/18978[#18978])
* Fixed: rudder api doc doesn't list nodes/pending
    (https://issues.rudder.io/issues/18940[#18940])

==== Performance and scalability

* Fixed: We don't know when generation hooks takes more time than expected, massively impacting generation time
    (https://issues.rudder.io/issues/18915[#18915])
* Fixed: A writeLock must never be in a read lock for LDAP repo
    (https://issues.rudder.io/issues/18983[#18983])

==== API

* Fixed: Inherited node properties are not returned in API
    (https://issues.rudder.io/issues/18959[#18959])
* Fixed: nodes API with include managementTechnologyDetails leads to error 500 response
    (https://issues.rudder.io/issues/18926[#18926])

==== Web - Nodes & inventories

* Fixed: FileUploadBaseSizeLimitExceededException with an 10MB inventory
    (https://issues.rudder.io/issues/19004[#19004])
* Fixed: purge software batch sometime terminate in error without log message
    (https://issues.rudder.io/issues/18873[#18873])

==== Web - Config management

* Fixed: Missing mandatory directive parameter doesn't fail policy generation
    (https://issues.rudder.io/issues/18995[#18995])
* Fixed: Missing exception details in change request update
    (https://issues.rudder.io/issues/18900[#18900])
* Fixed: Workflow rights are not used for rules
    (https://issues.rudder.io/issues/18876[#18876])

==== Web - UI & UX

* Fixed: Error message when editing properties in the interface
    (https://issues.rudder.io/issues/18902[#18902])
* Fixed: Save button moves when switching of compliance reporting mode
    (https://issues.rudder.io/issues/18849[#18849])

==== Miscellaneous

* Fixed: Error in postCommit pipeline with processor 'post_commit_inventory:pending_node_for_deleted_server'
    (https://issues.rudder.io/issues/18899[#18899])

==== System techniques

* Fixed: Rsync command for shared-files is incorrect
    (https://issues.rudder.io/issues/18943[#18943])

==== Generic methods - File Management

* Fixed: Value replacement in "File key-value present" and "File keys-values present" methods doesn't work correctly in some cases.
    (https://issues.rudder.io/issues/18944[#18944])

==== Generic methods

* Fixed: ncf unit tests do not generate any log file
    (https://issues.rudder.io/issues/18928[#18928])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Andras Miko
* Anton Yakimov
* Lars Koenen

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.9 (2021-01-28)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: Inventories are rejected due to missing dependency on Centos 8
    (https://issues.rudder.io/issues/18862[#18862])

==== Documentation

* Fixed: Update windows plugin documentation
    (https://issues.rudder.io/issues/18836[#18836])

==== Performance and scalability

* Fixed: Backport new inventory priorisation, software deletion API and log correction in 6.1
    (https://issues.rudder.io/issues/18839[#18839])

==== API

* Fixed: id parameter is ignored in rule category creation API and rule tags are lost on update
    (https://issues.rudder.io/issues/18867[#18867])

==== Web - Config management

* Fixed: Event logs are not written when fields are set to empty (ie short description)
    (https://issues.rudder.io/issues/18856[#18856])

==== Plugins integration

* Fixed: rudder package upgrade-all does not upgrade each plugin independently
    (https://issues.rudder.io/issues/18841[#18841])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.8 (2021-01-19)

=== Changes

==== API

* Add API tests for rules
    (https://issues.rudder.io/issues/18770[#18770])

=== Bug fixes

==== Web - Maintenance

* Fixed: Make more clear error message when several rudder.war are present
    (https://issues.rudder.io/issues/18835[#18835])

==== API

* Fixed: Broken API doc build
    (https://issues.rudder.io/issues/18823[#18823])
* Fixed: Clone rule API fails with "rule already exists with that id"
    (https://issues.rudder.io/issues/18777[#18777])

==== Relay server or API

* Fixed: Security advisories for relayd dependencies
    (https://issues.rudder.io/issues/18824[#18824])

==== Web - Compliance & node report

* Fixed:  Error log about duplicates entries when saving node compliance levels
    (https://issues.rudder.io/issues/18814[#18814])

==== Web - Nodes & inventories

* Fixed: Accepting a node by API or UI doesn't do the same things exactly
    (https://issues.rudder.io/issues/18677[#18677])

==== Web - Config management

* Fixed: Global parameters format is not preserved when editing
    (https://issues.rudder.io/issues/18556[#18556])

==== Web - UI & UX

* Fixed: Message on save for group must appear only when button is disabled
    (https://issues.rudder.io/issues/18738[#18738])
* Fixed: Markdown documentation rendering is inconsistent
    (https://issues.rudder.io/issues/18750[#18750])

==== Techniques

* Fixed: Define suse classes on sled
    (https://issues.rudder.io/issues/18775[#18775])

==== Documentation

* Fixed: Lots of methods are missing a documentation
    (https://issues.rudder.io/issues/18724[#18724])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* I C

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.7 (2020-12-18)

=== Changes

==== Documentation

* Add documentation about set-force-audit in audit/enforce chapter
    (https://issues.rudder.io/issues/18707[#18707])
* Add a link to rudder-by-example in windows doc
    (https://issues.rudder.io/issues/12622[#12622])

==== Agent

* Rudder server relay install should use the up-to-date commands and not deprecated ones
    (https://issues.rudder.io/issues/18639[#18639])

==== Web - Nodes & inventories

* API to totally erase a node everywhere
    (https://issues.rudder.io/issues/18035[#18035])

==== API

* Missing a PATCH API for allowed networks
    (https://issues.rudder.io/issues/18508[#18508])

==== Architecture - Internal libs

* Skip performance test
    (https://issues.rudder.io/issues/18563[#18563])

=== Bug fixes

==== Packaging

* Fixed: package cache ignores architecture
    (https://issues.rudder.io/issues/18759[#18759])
* Fixed: missing python3-setuptools dependency on relay on sles15 and rhel8
    (https://issues.rudder.io/issues/18747[#18747])
* Fixed: agent fails to build on aix
    (https://issues.rudder.io/issues/18624[#18624])
* Fixed: rudder-metrics-reporting doesn't work with 5 000 nodes
    (https://issues.rudder.io/issues/16675[#16675])

==== Agent

* Fixed: backport fix on background command execution on agent
    (https://issues.rudder.io/issues/18732[#18732])
* Fixed: Fix metrics-reporting script
    (https://issues.rudder.io/issues/18568[#18568])

==== Plugins integration

* Fixed: rudder_synchronize uses the wrong API to retrieve techniques
    (https://issues.rudder.io/issues/18421[#18421])
* Fixed: Link to plugins in Rudder interface should point directly to plugins list
    (https://issues.rudder.io/issues/18658[#18658])

==== Documentation

* Fixed: Improve documentation on disk space requirement
    (https://issues.rudder.io/issues/18532[#18532])
* Fixed: Correct documentation about arrray merge for node properties
    (https://issues.rudder.io/issues/18467[#18467])
* Fixed: Search window appears behind "dev version warning" bar
    (https://issues.rudder.io/issues/18524[#18524])
* Fixed: Update file from remote template doc
    (https://issues.rudder.io/issues/18632[#18632])
* Fixed: Doc about "Condition from variable existence" is wrong
    (https://issues.rudder.io/issues/18458[#18458])

==== Relay server or API

* Fixed: Security vulnerability in arc-swap
    (https://issues.rudder.io/issues/18766[#18766])
* Fixed: Too many open files in relayd when disk is full
    (https://issues.rudder.io/issues/18437[#18437])
* Fixed: Broken report parser on some info messages
    (https://issues.rudder.io/issues/18497[#18497])

==== Web - Config management

* Fixed: Agent run frequency must not be configurable on policy servers
    (https://issues.rudder.io/issues/18330[#18330])
* Fixed: We don't know which hook timeout when it happens
    (https://issues.rudder.io/issues/18530[#18530])
* Fixed: If a second rollback starts when a first is processing, system group/technique may be lost
    (https://issues.rudder.io/issues/17720[#17720])

==== Web - Compliance & node report

* Fixed: Reporting error when using twice "	File from local source" with parameter and without parameter in rudder 6.x
    (https://issues.rudder.io/issues/18686[#18686])

==== API

* Fixed: API ACL order is lost for users
    (https://issues.rudder.io/issues/18664[#18664])
* Fixed: API message when a node details is not found is extremely misleading
    (https://issues.rudder.io/issues/18654[#18654])
* Fixed: Bad file name in api-doc: some more errors
    (https://issues.rudder.io/issues/18622[#18622])
* Fixed: Typo in API doc
    (https://issues.rudder.io/issues/18457[#18457])

==== Architecture - Internal libs

* Fixed: semaphore guarding LDAP repos are created each time
    (https://issues.rudder.io/issues/18584[#18584])
* Fixed: If LDAP server does not support subtree deletion, we get error when entry does not exists
    (https://issues.rudder.io/issues/18529[#18529])
* Fixed: ifTrace/Debug/etcIsEnabled on pure logger does nothings
    (https://issues.rudder.io/issues/18528[#18528])

==== Performance and scalability

* Fixed: Batch of new nodes can overflow rudder server with inventories
    (https://issues.rudder.io/issues/16773[#16773])

==== Server components

* Fixed: Error when refusing a node
    (https://issues.rudder.io/issues/16739[#16739])

==== System techniques

* Fixed: bootstrap policies report OK if there is no server
    (https://issues.rudder.io/issues/18748[#18748])
* Fixed: Jinja2 UTF-8 rendering Problem
    (https://issues.rudder.io/issues/18552[#18552])
* Fixed: file augeas set class parameter should be path rather than lens
    (https://issues.rudder.io/issues/18442[#18442])

==== Techniques

* Fixed: ssh key distribution techniques doesn't accept - in user login
    (https://issues.rudder.io/issues/18449[#18449])

==== Generic methods

* Fixed: Regex constraint must not contain escaped chars
    (https://issues.rudder.io/issues/18764[#18764])
* Fixed: ncf uses its own cfengine port instead of rudder defined one
    (https://issues.rudder.io/issues/18704[#18704])
* Fixed: variable iterator should accept whitespace as separator
    (https://issues.rudder.io/issues/18562[#18562])
* Fixed: variable from command does not always report an error when the command failed
    (https://issues.rudder.io/issues/18512[#18512])
* Fixed: when sum of length of parameter is larger than 1000 characters, reporting leaks too much from one method to another
    (https://issues.rudder.io/issues/18505[#18505])
* Fixed: techniques in audit don't report correctly for editing values in files
    (https://issues.rudder.io/issues/18451[#18451])
* Fixed: Jinja2 templating fails with python 3 with unicode data
    (https://issues.rudder.io/issues/18441[#18441])

==== Generic methods - File Management

* Fixed: On sles system augtool requires a terminating break line to run a command passed via pipe
    (https://issues.rudder.io/issues/18719[#18719])
* Fixed: calling file_key_value_present_in_ini_section on a yum repo definition loops
    (https://issues.rudder.io/issues/18705[#18705])
* Fixed: Create a file from remote template generic method
    (https://issues.rudder.io/issues/18384[#18384])
* Fixed: Flag the file_augeas_set to stagging since the method does not work as intended
    (https://issues.rudder.io/issues/18570[#18570])
* Fixed: File_augeas_set method does not report as expected
    (https://issues.rudder.io/issues/18536[#18536])
* Fixed: Document the permissions recursive and permissions type recursive methods
    (https://issues.rudder.io/issues/18447[#18447])
* Fixed: Permissions recursive method uses an undefined "recursion" variable in its report string
    (https://issues.rudder.io/issues/18446[#18446])
* Fixed: jinja templating script uses python3 even if jinja2 is not installed in python3 but is in python2
    (https://issues.rudder.io/issues/18416[#18416])

==== Web - Technique editor

* Fixed: Code blocks in the technique editor are not rendered correctly
    (https://issues.rudder.io/issues/18547[#18547])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Alexander Brunhirl

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.6 (2020-10-28)

=== Changes

==== Containers

* Reorganize dockerfiles and start documentation
    (https://issues.rudder.io/issues/17752[#17752])

=== Bug fixes

==== System integration

* Fixed: systemctl restart rudder-server does nothing
    (https://issues.rudder.io/issues/18404[#18404])
* Fixed: Intermittent failure test on certificate inventory
    (https://issues.rudder.io/issues/18353[#18353])

==== Packaging

* Fixed: Replace apache config in /opt/rudder/etc on upgrade
    (https://issues.rudder.io/issues/18333[#18333])

==== Documentation

* Fixed: USEMETHODREPORTING is missing in metadata documentation
    (https://issues.rudder.io/issues/18427[#18427])
* Fixed: Advise to not desinstall rudder server if possible
    (https://issues.rudder.io/issues/17803[#17803])
* Fixed: Add a documentation page on how to manually distribute plugin licenses
    (https://issues.rudder.io/issues/18391[#18391])
* Fixed: Add agent-server troubleshooting section
    (https://issues.rudder.io/issues/18190[#18190])
* Fixed: Broken API doc build
    (https://issues.rudder.io/issues/18383[#18383])

==== Web - UI & UX

* Fixed: Group description button should not be clickable in read_only
    (https://issues.rudder.io/issues/17634[#17634])
* Fixed: Broken display of error icon in menu when there is a plugin error
    (https://issues.rudder.io/issues/18265[#18265])

==== Architecture - Refactoring

* Fixed: Duplicated code from a merge #16513
    (https://issues.rudder.io/issues/18377[#18377])

==== Web - Technique editor

* Fixed: Technique parameter description is not valid in technique.cf file
    (https://issues.rudder.io/issues/18370[#18370])

==== Server components

* Fixed: Make the group option to include the Rudder server or not in the group clearer
    (https://issues.rudder.io/issues/18346[#18346])

==== API

* Fixed: Format of lastRunDate/lastInventoryDate has changed in api response in 6.0.0
    (https://issues.rudder.io/issues/18337[#18337])
* Fixed: Improve documentation on how to change a key for a node by stating that \n is mandatory around begin and end
    (https://issues.rudder.io/issues/18336[#18336])

==== Security

* Fixed: Webdav allows get on inventory and reports
    (https://issues.rudder.io/issues/18325[#18325])
* Fixed: Agents fail to check their policy server's identity
    (https://issues.rudder.io/issues/18286[#18286])

==== Web - Config management

* Fixed: Missing system variable "POLICY_SERVER_KEY"
    (https://issues.rudder.io/issues/18289[#18289])
* Fixed: Error log about duplicates entries when saving node compliance levels
    (https://issues.rudder.io/issues/18188[#18188])

==== Plugins integration

* Fixed: rudder package throws exceptions when the connection timeouts
    (https://issues.rudder.io/issues/18308[#18308])

==== Relay server or API

* Fixed: Calling the relay-api to trigger a remote run on all nodes do an infinite loop on root server, killing it
    (https://issues.rudder.io/issues/18303[#18303])
* Fixed: null value in status API on simple relay
    (https://issues.rudder.io/issues/18282[#18282])

==== Techniques

* Fixed: Selecting "latest" version for package installation in techniques Packages only checks for existence
    (https://issues.rudder.io/issues/18260[#18260])
* Fixed: apt configuration issue - add apost-check to validate generated line
    (https://issues.rudder.io/issues/13741[#13741])

==== System techniques

* Fixed: Incorrect configuration when the database is not hosted on the rudder server itself
    (https://issues.rudder.io/issues/18279[#18279])

==== Agent

* Fixed: commands from error message are launched due to backticks
    (https://issues.rudder.io/issues/18174[#18174])
* Fixed: rudder-agent check sleep and process pile-up in 6.0
    (https://issues.rudder.io/issues/18339[#18339])

==== Technique editor - UI/UX

* Fixed: Alert user if they named a technique with a name that already exists in provided techniques
    (https://issues.rudder.io/issues/18098[#18098])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.5 (2020-10-07)

=== Changes

==== Documentation

* Add a page for technical stack doc
    (https://issues.rudder.io/issues/18223[#18223])
* Add svg logos to the repo
    (https://issues.rudder.io/issues/18232[#18232])

=== Bug fixes

==== Documentation

* Fixed: Document that JDK 15 is not supported because of nashorn removing
    (https://issues.rudder.io/issues/18214[#18214])
* Fixed: Missing menu link to "contribute"
    (https://issues.rudder.io/issues/18173[#18173])
* Fixed: compatible OS typo
    (https://issues.rudder.io/issues/18171[#18171])

==== Web - Config management

* Fixed: Array as root json are seens as string
    (https://issues.rudder.io/issues/18285[#18285])
* Fixed: Uncommitted rudder_reporting.cf  when creating a technique with a condition
    (https://issues.rudder.io/issues/18266[#18266])

==== Relay server or API

* Fixed: Broken url for local api in relay api doc
    (https://issues.rudder.io/issues/18283[#18283])
* Fixed: relayd should accept to listen on an hostname and not only an IP
    (https://issues.rudder.io/issues/18269[#18269])

==== System techniques

* Fixed: Webapp does not regerate policies when webdav password is changed, breaking inventories after 5.0 -> 6.0 upgrade
    (https://issues.rudder.io/issues/17250[#17250])
* Fixed: In HTTPS+Syslog, syslog config is not removed if agent supports https
    (https://issues.rudder.io/issues/18222[#18222])

==== Web - Nodes & inventories

* Fixed: Optionally accept node with same hostname as an already accepted one 
    (https://issues.rudder.io/issues/18272[#18272])

==== API

* Fixed: Resources API error for subcategories
    (https://issues.rudder.io/issues/18259[#18259])

==== Web - Technique editor

* Fixed: It should be forbidden to create a user technique with the same name as n existing technique
    (https://issues.rudder.io/issues/15024[#15024])

==== Performance and scalability

* Fixed: Possible deadlock when connection pool is full
    (https://issues.rudder.io/issues/18224[#18224])

==== System integration

* Fixed: Fiber error when postgres is unavaible breaks generation forever
    (https://issues.rudder.io/issues/18227[#18227])

==== Technique editor - API

* Fixed: Method with empty curly braces are not recognized as valid
    (https://issues.rudder.io/issues/18268[#18268])

==== Generic methods - Package Management

* Fixed: Zypper module does not work on python2
    (https://issues.rudder.io/issues/18143[#18143])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Victor Héry

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.4 (2020-09-16)

=== Changes

==== Documentation

* Migrate general questions from the faq into the doc
    (https://issues.rudder.io/issues/18117[#18117])
* Improve docs consistency
    (https://issues.rudder.io/issues/18109[#18109])

=== Bug fixes

==== System integration

* Fixed: LDAP index inconsistency on update cause error with allowed networks
    (https://issues.rudder.io/issues/17998[#17998])
* Fixed: Logs from all nodes are always reported in all.log
    (https://issues.rudder.io/issues/18205[#18205])
* Fixed: directive list tells you to upgrade the server if it didn't yet connect.
    (https://issues.rudder.io/issues/16663[#16663])

==== Packaging

* Fixed: if configuration files are replaced during upgrade, rudder-upgrade fails on both postgresql checks and plugins disabling
    (https://issues.rudder.io/issues/18139[#18139])

==== Documentation

* Fixed: Unclear upgrade nodes about 5.0.16+
    (https://issues.rudder.io/issues/18212[#18212])
* Fixed: Improve policy ordering doc
    (https://issues.rudder.io/issues/17903[#17903])
* Fixed: Move cf-serverd verbosity config into an appropriate section
    (https://issues.rudder.io/issues/18104[#18104])
* Fixed: The documentation should mention more obviously that upgrades from 4.3 to 6.0 are not supported
    (https://issues.rudder.io/issues/17982[#17982])

==== Web - Config management

* Fixed: Groups are not committed in configuration-repository on modification
    (https://issues.rudder.io/issues/18207[#18207])
* Fixed: SUSE is spelled SuSE in the webapp
    (https://issues.rudder.io/issues/16319[#16319])
* Fixed: Techniques with conditions on tasks with very long parameters report "missing" parts on the dashboard
    (https://issues.rudder.io/issues/18100[#18100])
* Fixed: "error: Only functions returning scalars can be used as arguments" in verbose output
    (https://issues.rudder.io/issues/18101[#18101])

==== Web - Technique editor

* Fixed: Resources are lost during an upgrade from 6.0 to 6.1
    (https://issues.rudder.io/issues/18192[#18192])

==== Web - Nodes & inventories

* Fixed: Group query with OR composition and searching for Node properties return all nodes in place of none
    (https://issues.rudder.io/issues/18172[#18172])
* Fixed: Group query with OR composition and searching for Node properties return less results than expected
    (https://issues.rudder.io/issues/18133[#18133])

==== API

* Fixed: "id" setting is silently ignored for new group created through the REST API.
    (https://issues.rudder.io/issues/10216[#10216])
* Fixed: Rudder directive API seem to take key-value order into account in json POST request 
    (https://issues.rudder.io/issues/14934[#14934])

==== Miscellaneous

* Fixed: orchestrateur-5 (root) inventory are send to demo/snapshot/dev server, breaking their inventory preventing to use them
    (https://issues.rudder.io/issues/18130[#18130])
* Fixed: Error displayed when switching from full access to read only
    (https://issues.rudder.io/issues/18052[#18052])

==== Performance and scalability

* Fixed: duplicate parsing for hostname in inventory processing
    (https://issues.rudder.io/issues/18097[#18097])

==== Techniques

* Fixed: Technique shared folder on WIndows use invalid md5 hash instead of sha256
    (https://issues.rudder.io/issues/18176[#18176])
* Fixed: No flush key report on sshKeyDistribution when there is not yet an ssh key configured
    (https://issues.rudder.io/issues/16516[#16516])
* Fixed: Technique resources should not be committed on server upgrade
    (https://issues.rudder.io/issues/18213[#18213])

==== Agent

* Fixed: Unparsable techniques when there are error in cf-promises (cf-promises outputs error in stdout)
    (https://issues.rudder.io/issues/18178[#18178])

==== Generic methods

* Fixed: Method shared folder should not state that you can use md5 as hash method
    (https://issues.rudder.io/issues/18177[#18177])
* Fixed: File from local source with check: diff error
    (https://issues.rudder.io/issues/17303[#17303])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl
* Alexander Brunhirl
* Dmitry Svyatogorov
* PB LO

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.3 (2020-08-04)

=== Changes

=== Bug fixes

==== Web - Config management

* Fixed: Broken technique resources in 6.1.2
    (https://issues.rudder.io/issues/18085[#18085])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.2 (2020-07-31)

=== Changes

==== Packaging

* Solaris package script should take a version as an argument
    (https://issues.rudder.io/issues/17988[#17988])
* Preliminary support for macosx
    (https://issues.rudder.io/issues/17847[#17847])

==== Documentation

* Add a rudder by example for group properties
    (https://issues.rudder.io/issues/18061[#18061])
* Optimize images in the doc
    (https://issues.rudder.io/issues/18024[#18024])
* CVE plugin api documentation
    (https://issues.rudder.io/issues/17940[#17940])

==== API

* Add request examples to API doc
    (https://issues.rudder.io/issues/18021[#18021])

==== Rudder language

* replace var keyword by let
    (https://issues.rudder.io/issues/17937[#17937])

==== Agent

* Add debug information when sending reports 
    (https://issues.rudder.io/issues/17981[#17981])
* Add an option to exit with an error code if here was an application error
    (https://issues.rudder.io/issues/17689[#17689])

==== Generic methods

* Add a method for osquery-based audit
    (https://issues.rudder.io/issues/17651[#17651])

=== Bug fixes

==== Packaging

* Fixed: Broken relay postinst due to missing shared-folder
    (https://issues.rudder.io/issues/18070[#18070])
* Fixed: When rudder-webapp postinstall fails, everything fails
    (https://issues.rudder.io/issues/18045[#18045])
* Fixed: rudder-reports-postinst errors during upgrade from 6.1.0 to 6.1.1
    (https://issues.rudder.io/issues/18014[#18014])
* Fixed: solaris package always downloads 6.0
    (https://issues.rudder.io/issues/18004[#18004])
* Fixed: All package scripts should be set -e
    (https://issues.rudder.io/issues/17687[#17687])

==== Security

* Fixed: Rudder app and docs should not be indexable by search engines
    (https://issues.rudder.io/issues/18019[#18019])

==== Web - Nodes & inventories

* Fixed: In SLES 15, SP is view as part of rudder agent version
    (https://issues.rudder.io/issues/17736[#17736])
* Fixed:  Historization of node count reports inverts pending and accepted
    (https://issues.rudder.io/issues/17856[#17856])
* Fixed: Number of groups on the dashboard in incorrect
    (https://issues.rudder.io/issues/17202[#17202])

==== Relay server or API

* Fixed: SELinux perms on relay forbid to retrieve files from shared-folder (Windows DSC)
    (https://issues.rudder.io/issues/17770[#17770])

==== Documentation

* Fixed: Update links to ansible inventory plugin
    (https://issues.rudder.io/issues/18080[#18080])
* Fixed: Add DSC based node in the network flow schema in the documentation
    (https://issues.rudder.io/issues/18041[#18041])
* Fixed: http in place of https in install doc for zypper subscription repo
    (https://issues.rudder.io/issues/18055[#18055])
* Fixed: Fix doc build after nodejs upgrade
    (https://issues.rudder.io/issues/18056[#18056])
* Fixed: Documentation is wrong about default values for data retention
    (https://issues.rudder.io/issues/17935[#17935])
* Fixed: Broken formatting in methods doc
    (https://issues.rudder.io/issues/17999[#17999])

==== API

* Fixed: Generic method are not sorted by alpha-num order
    (https://issues.rudder.io/issues/18044[#18044])
* Fixed: Fix swagger warnings in api doc
    (https://issues.rudder.io/issues/18020[#18020])

==== System integration

* Fixed: Test fails because takes too long
    (https://issues.rudder.io/issues/18050[#18050])
* Fixed: When rudder agent health stops all service because there aren't any space left, if should state it in the log (and which fs)
    (https://issues.rudder.io/issues/17472[#17472])

==== Web - Config management

* Fixed: Use node properties as path for node properties
    (https://issues.rudder.io/issues/18025[#18025])
* Fixed: na reports for Windows techniques on Linux generate broken condition
    (https://issues.rudder.io/issues/18027[#18027])
* Fixed: Missing interpolator in error message for allowed networks
    (https://issues.rudder.io/issues/17967[#17967])
* Fixed: Incorrect error message when a resource is not found
    (https://issues.rudder.io/issues/17944[#17944])

==== Rudder language

* Fixed: compiler error is not helpful in certain cases
    (https://issues.rudder.io/issues/17992[#17992])
* Fixed: testing loop should report an error when rudderc does
    (https://issues.rudder.io/issues/17950[#17950])
* Fixed: Error during translate in CIS techniques
    (https://issues.rudder.io/issues/17910[#17910])
* Fixed: rudderc is way too slow
    (https://issues.rudder.io/issues/17912[#17912])

==== Web - Technique editor

* Fixed: Remove technique from technique tree when deleting technique in the technique editor
    (https://issues.rudder.io/issues/18015[#18015])
* Fixed: Resource automatically added on newly created technique - since 6.1 upgrade
    (https://issues.rudder.io/issues/17977[#17977])
* Fixed: Long error message are not displayed in technique editor
    (https://issues.rudder.io/issues/18046[#18046])
* Fixed: Keep resource information from api when saving technique
    (https://issues.rudder.io/issues/17881[#17881])

==== Web - UI & UX

* Fixed: Cannot set Compliance reporting mode on "Non compliant only" in settings tab
    (https://issues.rudder.io/issues/16402[#16402])
* Fixed: Error when trying to enable a disabled Technique in the technique tree
    (https://issues.rudder.io/issues/17906[#17906])

==== Techniques

* Fixed: Description of Technique is partially garbled because of markdown rendering
    (https://issues.rudder.io/issues/17942[#17942])

==== System techniques

* Fixed: If gzip is not installed the inventory is not sent
    (https://issues.rudder.io/issues/17891[#17891])
* Fixed: On debian, package with new dependencies is not upgraded to latest available version
    (https://issues.rudder.io/issues/17917[#17917])

==== Agent

* Fixed: hostname command may not exist
    (https://issues.rudder.io/issues/18018[#18018])
* Fixed: grep -E doesn't work on solaris
    (https://issues.rudder.io/issues/17932[#17932])
* Fixed: When a node is in bootstrap mode there is no understandable way to unlock it from this state
    (https://issues.rudder.io/issues/16825[#16825])
* Fixed: rudder agent health fails on aix
    (https://issues.rudder.io/issues/17933[#17933])
* Fixed: rudder agent factory reset fails on solaris
    (https://issues.rudder.io/issues/17930[#17930])
* Fixed: "rudder agent check" always raises errors
    (https://issues.rudder.io/issues/17928[#17928])
* Fixed: rudder agent check fails on macosx
    (https://issues.rudder.io/issues/17894[#17894])

==== Technique editor - UI/UX

* Fixed: Change cursor to pointer when we choose an action
    (https://issues.rudder.io/issues/17707[#17707])
* Fixed: Add left margin to DSC icon in generic method name
    (https://issues.rudder.io/issues/17706[#17706])
* Fixed: Add margin for OS input condition in generic method
    (https://issues.rudder.io/issues/17756[#17756])
* Fixed: CSS problem on OS condition for generic methods
    (https://issues.rudder.io/issues/17877[#17877])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Nicolas Ecarnot
* Frédéric COSTANT
* Bas B

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.1 (2020-07-03)

=== Changes

==== Documentation

* Add a Rudder by example for using Rudder server/relays as file mirror (for repos)
    (https://issues.rudder.io/issues/17858[#17858])
* Add docs about configuration-repository, how to sync it and what can be modified or not from outside
    (https://issues.rudder.io/issues/17865[#17865])
* Add doc about network resiliency
    (https://issues.rudder.io/issues/17880[#17880])
* Improve documentation about communication security
    (https://issues.rudder.io/issues/17834[#17834])
* Add a rudder-by-example for git sync in shared-files
    (https://issues.rudder.io/issues/17840[#17840])
* Document how to use custom certificates
    (https://issues.rudder.io/issues/14206[#14206])
* Document how to use custom certificates
    (https://issues.rudder.io/issues/14206[#14206])
* Missing uninstall doc for agent
    (https://issues.rudder.io/issues/17790[#17790])
* Add screenshots for technique editor with annotation in get started documentation
    (https://issues.rudder.io/issues/17781[#17781])

==== Web - UI & UX

* Inconsistent fonts in technical logs
    (https://issues.rudder.io/issues/16032[#16032])

==== Rudder language

* add doc about logs and generated techniques 
    (https://issues.rudder.io/issues/17738[#17738])

==== Techniques

* Firewall technique
    (https://issues.rudder.io/issues/16915[#16915])

=== Bug fixes

==== Web - Technique editor

* Fixed: Can't access on technique editor
    (https://issues.rudder.io/issues/17883[#17883])
* Fixed: "unsaved changed" technique editor pop-up appears when not needed
    (https://issues.rudder.io/issues/17750[#17750])
* Fixed: Resource path of a technique with a category different thant default category are wrong
    (https://issues.rudder.io/issues/17747[#17747])
* Fixed: When removing and adding a new method, the save button is disabled
    (https://issues.rudder.io/issues/17776[#17776])

==== Packaging

* Fixed: SLES12 upgrade error 6.0 to 6.1
    (https://issues.rudder.io/issues/17873[#17873])
* Fixed: some errors when upgrading from 5.0.18nightly to 6.1-nightly on debian9 and 10
    (https://issues.rudder.io/issues/17644[#17644])
* Fixed: Optimize elm application
    (https://issues.rudder.io/issues/17888[#17888])
* Fixed: shared-files acls are incorrect on relays, preventing the windows nodes from downloading them
    (https://issues.rudder.io/issues/17802[#17802])

==== Documentation

* Fixed: Add support of Ubuntu 20 in doc
    (https://issues.rudder.io/issues/17874[#17874])
* Fixed: Typo in network resiliency documentation
    (https://issues.rudder.io/issues/17892[#17892])
* Fixed: Add trigger agent run feature from UI in get started 
    (https://issues.rudder.io/issues/17855[#17855])
* Fixed: remove pg_repack from documentation
    (https://issues.rudder.io/issues/17839[#17839])
* Fixed: Update screenshots in usage doc section 
    (https://issues.rudder.io/issues/17843[#17843])
* Fixed: Missing doc about root-relay communication flows
    (https://issues.rudder.io/issues/17837[#17837])
* Fixed: Missing ressources feature in technique editor doc
    (https://issues.rudder.io/issues/17787[#17787])
* Fixed: Broken link in apply advanced configuration get started doc
    (https://issues.rudder.io/issues/17792[#17792])
* Fixed: Missing markdown support for description in technique editor doc
    (https://issues.rudder.io/issues/17788[#17788])
* Fixed: Missing parameters feature in technique editor doc
    (https://issues.rudder.io/issues/17786[#17786])
* Fixed: Add link to further information in get started section
    (https://issues.rudder.io/issues/17771[#17771])
* Fixed: Replace deprecated generic methods in technique editor documentation usage
    (https://issues.rudder.io/issues/17768[#17768])
* Fixed: Documentation should state that SSD is recommended for more than 50 nodes
    (https://issues.rudder.io/issues/17761[#17761])
* Fixed: Refresh screenshots for technique editor
    (https://issues.rudder.io/issues/17746[#17746])

==== Miscellaneous

* Fixed: Typos in directive documentation
    (https://issues.rudder.io/issues/17762[#17762])
* Fixed: Typos in technique editor documentation
    (https://issues.rudder.io/issues/17760[#17760])

==== Relay server or API

* Fixed: Shared-files correction in postinst must be recursive
    (https://issues.rudder.io/issues/17882[#17882])

==== Rudder language

* Fixed: make use of parameters instead of args
    (https://issues.rudder.io/issues/17885[#17885])
* Fixed: fix nasty random generation failure
    (https://issues.rudder.io/issues/17811[#17811])
* Fixed: handle techniques location path properly
    (https://issues.rudder.io/issues/17737[#17737])
* Fixed: error about rudder-lang in logs
    (https://issues.rudder.io/issues/17724[#17724])

==== Web - Config management

* Fixed: Wrong error message when policy server of a Node is not found during generation 
    (https://issues.rudder.io/issues/17851[#17851])
* Fixed: Trying to add a group property with change request plugin enabled lead to blank property
    (https://issues.rudder.io/issues/17804[#17804])
* Fixed: Upgrading from rudder 5.0 to 6.0 leads to `distributePolicy not available` error
    (https://issues.rudder.io/issues/17836[#17836])
* Fixed: Updating property merge them in place of replacing them
    (https://issues.rudder.io/issues/17830[#17830])
* Fixed: When there is a serialisation error for parameter, their edit screen is unavaible
    (https://issues.rudder.io/issues/17702[#17702])
* Fixed: Duplicate category name error when saving a new user technique
    (https://issues.rudder.io/issues/17774[#17774])
* Fixed: Uncommitted generic_methods.json in configuration repo
    (https://issues.rudder.io/issues/17775[#17775])
* Fixed: Auto-archive gitRepo.git failure warning is not actionnable, should be info or debug
    (https://issues.rudder.io/issues/17777[#17777])
* Fixed: description of global parameter "rudder" is misleading
    (https://issues.rudder.io/issues/17700[#17700])

==== API

* Fixed: Missing doc for group properties and json global parameters
    (https://issues.rudder.io/issues/17818[#17818])
* Fixed: Group API compatibility broken as it now always expects "properties"
    (https://issues.rudder.io/issues/17815[#17815])
* Fixed: 'policyMode' vs. 'policy' in node settings API
    (https://issues.rudder.io/issues/17817[#17817])

==== Web - Compliance & node report

* Fixed: Node details summary compliance contains system rules
    (https://issues.rudder.io/issues/17660[#17660])

==== Web - UI & UX

* Fixed: user with read_only right has button that allows write actions 
    (https://issues.rudder.io/issues/17725[#17725])
* Fixed: Select node state in settings is confusiing for read_only user 
    (https://issues.rudder.io/issues/17627[#17627])
* Fixed: when we create a group, we should go directly to the criteria page
    (https://issues.rudder.io/issues/17678[#17678])
* Fixed: Content in header of plugin page overflows when custom from branding is activate
    (https://issues.rudder.io/issues/17731[#17731])

==== Performance and scalability

* Fixed: table nodes contains on entry per node per generation, which is too much
    (https://issues.rudder.io/issues/17778[#17778])
* Fixed: table nodes contains on entry per node per generation, which is too much
    (https://issues.rudder.io/issues/17778[#17778])

==== Techniques

* Fixed: clockConfiguration is not compatible with systemd-based systems
    (https://issues.rudder.io/issues/6772[#6772])

==== System techniques

* Fixed: Rudder 6 check postgresql process failes
    (https://issues.rudder.io/issues/17145[#17145])
* Fixed: error when installing rudder server root on debian 9 - 6.1
    (https://issues.rudder.io/issues/17765[#17765])
* Fixed: Initial promises warning during agent setup
    (https://issues.rudder.io/issues/17722[#17722])

==== Technique editor - UI/UX

* Fixed: Save button is disable when a technique is imported
    (https://issues.rudder.io/issues/17897[#17897])
* Fixed: Gear icon in save button always displayed
    (https://issues.rudder.io/issues/17745[#17745])

==== Technique editor - Techniques

* Fixed: Importing technique leads to a blocked editor
    (https://issues.rudder.io/issues/17793[#17793])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Tristan Le Chanony
* Alexander Brunhirl

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0 (2020-06-17)

=== Changes

==== Miscellaneous

* Add a 'Rudder by example' best practice use case
    (https://issues.rudder.io/issues/17715[#17715])
* Add a 'Rudder by example' best practice use case
    (https://issues.rudder.io/issues/17715[#17715])
* Add a 'Rudder by example' best practice use case
    (https://issues.rudder.io/issues/17715[#17715])
* Add a 'Rudder by example' best practice use case
    (https://issues.rudder.io/issues/17715[#17715])

==== Documentation

* Prepare doc for final 6.1 release
    (https://issues.rudder.io/issues/17648[#17648])

==== Containers

* Dockerize Rudder Relay Server
    (https://issues.rudder.io/issues/17732[#17732])
* Dockerize Rudder Relay Server
    (https://issues.rudder.io/issues/17732[#17732])

=== Bug fixes

==== Packaging

* Fixed: systemd detection fails when init has parameters
    (https://issues.rudder.io/issues/17717[#17717])

==== Documentation

* Fixed: broken doc build because of spaces in file name
    (https://issues.rudder.io/issues/17751[#17751])
* Fixed: Broken links in rudder-by-example
    (https://issues.rudder.io/issues/17735[#17735])
* Fixed: Missing documentation for overriding jetty system properties in start.ini
    (https://issues.rudder.io/issues/17719[#17719])
* Fixed: Document access to `ipv4[eth0]` system variable
    (https://issues.rudder.io/issues/17705[#17705])
* Fixed: Add a `rudder-by-example` for rudder-agent package update
    (https://issues.rudder.io/issues/17686[#17686])

==== Technique editor - UI/UX

* Fixed: Filter on agent type also filter generic methods in technique
    (https://issues.rudder.io/issues/17749[#17749])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.rc4 (2020-06-11)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: Rudder-agent needs libxml-treepp-perl dependency to work on minimal Debian
    (https://issues.rudder.io/issues/17699[#17699])
* Fixed: /opt/rudder/etc/rudder-pkg comes with the wrong permissions
    (https://issues.rudder.io/issues/17695[#17695])
* Fixed: All package script should be set -e
    (https://issues.rudder.io/issues/17687[#17687])
* Fixed: Upgrade to 6.1 fails on httpd start beacause of old ncf conf is still present on rpm
    (https://issues.rudder.io/issues/17681[#17681])
* Fixed: gpg import error in rudder-pkg
    (https://issues.rudder.io/issues/17692[#17692])
* Fixed: package key is not trusted by rudder-pkg
    (https://issues.rudder.io/issues/17675[#17675])
* Fixed: Error in technique editor just after install: No such file or directory: '/var/rudder/configuration-repository/ncf/generic_methods.json'
    (https://issues.rudder.io/issues/17573[#17573])

==== System integration

* Fixed: An error in during upgrade to 6.1 breaks rudder upgrade and everything
    (https://issues.rudder.io/issues/17659[#17659])
* Fixed: Bad init value for param rudder_file_edit_header
    (https://issues.rudder.io/issues/17701[#17701])
* Fixed: Cannot download licenses if there is a trailing slash in rudder package config url
    (https://issues.rudder.io/issues/17673[#17673])

==== Web - Config management

* Fixed: Error in technique editor "could not get generic method metadata" after upgrade from 6.0
    (https://issues.rudder.io/issues/17683[#17683])

==== Web - Compliance & node report

* Fixed: Global parameter "string" doesn't escape json
    (https://issues.rudder.io/issues/17674[#17674])

==== API

* Fixed: API doc build silently fails
    (https://issues.rudder.io/issues/17656[#17656])

==== Plugins integration

* Fixed: Improve rudder package error message when an update is needed
    (https://issues.rudder.io/issues/17626[#17626])

==== Technique editor - UI/UX

* Fixed: Deprecated method filter is broken
    (https://issues.rudder.io/issues/17647[#17647])
* Fixed: Still some technique diverge popup after you added a new method
    (https://issues.rudder.io/issues/17654[#17654])

==== Generic methods

* Fixed: Syntax error in shared_file_to_node
    (https://issues.rudder.io/issues/17667[#17667])
* Fixed: no reports from sharedfile to node if file is already there
    (https://issues.rudder.io/issues/17661[#17661])

==== Web - Technique editor

* Fixed: The technique editor struggles to display long line as component
    (https://issues.rudder.io/issues/17392[#17392])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.rc3 (2020-06-08)

=== Changes

==== Miscellaneous

* Dockerizing Rudder agent 
    (https://issues.rudder.io/issues/17604[#17604])
* Dockerizing Rudder agent 
    (https://issues.rudder.io/issues/17604[#17604])
* Dockerizing Rudder agent 
    (https://issues.rudder.io/issues/17604[#17604])
* Dockerizing Rudder agent 
    (https://issues.rudder.io/issues/17604[#17604])
* Dockerizing Rudder agent 
    (https://issues.rudder.io/issues/17604[#17604])

==== Rudder language

* Improve rudder-lang doc
    (https://issues.rudder.io/issues/16944[#16944])

=== Bug fixes

==== Packaging

* Fixed: error at install of rudder 6.1 on debian9
    (https://issues.rudder.io/issues/17636[#17636])
* Fixed: AIX builds fails on invalid or condition
    (https://issues.rudder.io/issues/17635[#17635])
* Fixed: Agent uses "cmp" command but it is not a dependency
    (https://issues.rudder.io/issues/17606[#17606])
* Fixed: The webapp is unable to start after a fresh install
    (https://issues.rudder.io/issues/17591[#17591])
* Fixed: ruder package command fails to run in automated setup
    (https://issues.rudder.io/issues/17645[#17645])
* Fixed: ruder package command fails to run in automated setup
    (https://issues.rudder.io/issues/17645[#17645])

==== Documentation

* Fixed: Update documentation about variable (condition)
    (https://issues.rudder.io/issues/17629[#17629])

==== Web - UI & UX

* Fixed: Clicking on the warning icon is node list should lead to system status page
    (https://issues.rudder.io/issues/17646[#17646])
* Fixed: Group value should only display value for that element in main table
    (https://issues.rudder.io/issues/17625[#17625])
* Fixed: Plugin expiration warning misalignement problem
    (https://issues.rudder.io/issues/17619[#17619])
* Fixed: Overridden pop-up top is missing
    (https://issues.rudder.io/issues/17623[#17623])
* Fixed: tooltip for node properties does not show
    (https://issues.rudder.io/issues/17550[#17550])
* Fixed: when searching nodes, on the search page, the checkbox "Include Rudder server components" if briefly checked and unchecked
    (https://issues.rudder.io/issues/17575[#17575])
* Fixed: Rudder logo appears in remote-run error message
    (https://issues.rudder.io/issues/17556[#17556])

==== Security

* Fixed: description in directives and groups are evaluated, and we can inject whatever we want
    (https://issues.rudder.io/issues/17641[#17641])

==== Rudder language

* Fixed: doc conflicting with tests
    (https://issues.rudder.io/issues/17649[#17649])
* Fixed: fix doc configuration files
    (https://issues.rudder.io/issues/17614[#17614])

==== Web - Compliance & node report

* Fixed: text explaining hierarchy of groups always shows up for system group
    (https://issues.rudder.io/issues/17638[#17638])
* Fixed: policy generation fails if we put a " in the directive name
    (https://issues.rudder.io/issues/17628[#17628])

==== Plugins integration

* Fixed: rudder package logs are inconsistent
    (https://issues.rudder.io/issues/17600[#17600])

==== Web - Nodes & inventories

* Fixed: compilation error in 6.0 because of absence of typo in Inconsistency
    (https://issues.rudder.io/issues/17605[#17605])
* Fixed: no policy generation after accepting many nodes in 6.1
    (https://issues.rudder.io/issues/17594[#17594])

==== Web - Maintenance

* Fixed: NPE when agent key is malformed
    (https://issues.rudder.io/issues/17597[#17597])

==== Web - Config management

* Fixed: when a policy generation is triggered by a dynamic group update, it states in event logs "Manually update policies"
    (https://issues.rudder.io/issues/17595[#17595])

==== Web - Technique editor

* Fixed: User with some to access technique editor api
    (https://issues.rudder.io/issues/17596[#17596])

==== System techniques

* Fixed: system techniques start rudder-relayd before setting postgresql passwords
    (https://issues.rudder.io/issues/17612[#17612])
* Fixed: inventory should be copied to /var/rudder/inventories/accepted-nodes-updates rather than uploaded on root server
    (https://issues.rudder.io/issues/17616[#17616])

==== Agent

* Fixed: error at install of rudder 6.1 server on debian 9
    (https://issues.rudder.io/issues/17637[#17637])
* Fixed: Warning message in relayd logs when reloading
    (https://issues.rudder.io/issues/17630[#17630])
* Fixed: rudder server root tries to set initial promises while they are not installed
    (https://issues.rudder.io/issues/17611[#17611])
* Fixed: possible use of undefined variable in lib/common.sh
    (https://issues.rudder.io/issues/17610[#17610])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.rc2 (2020-06-04)

=== Changes

==== Rudder language

* refactoring io usage and configuration
    (https://issues.rudder.io/issues/17403[#17403])

==== Plugins integration

* Rudder package list should display plugin status
    (https://issues.rudder.io/issues/16793[#16793])

=== Bug fixes

==== Packaging

* Fixed: Apache reload error during root server setup
    (https://issues.rudder.io/issues/17565[#17565])
* Fixed:  apache acl are still empty after installation
    (https://issues.rudder.io/issues/17564[#17564])
* Fixed: rudder init syntax error
    (https://issues.rudder.io/issues/17560[#17560])
* Fixed: postgresl client in relayd tries to read krb conf
    (https://issues.rudder.io/issues/17518[#17518])
* Fixed: First inventory fails when installing root server
    (https://issues.rudder.io/issues/17567[#17567])

==== Relay server or API

* Fixed: old rudder-node-to-relay fails to redirect to new one
    (https://issues.rudder.io/issues/17566[#17566])

==== Web - Config management

* Fixed: Multiple problems with inherited (group, node) properties
    (https://issues.rudder.io/issues/17547[#17547])
* Fixed: Property error message for group with parent group
    (https://issues.rudder.io/issues/17549[#17549])
* Fixed: error in webapp log after upgrade to 6.1-rc1
    (https://issues.rudder.io/issues/17555[#17555])

==== Web - Technique editor

* Fixed: Allow to regenerate generic methods when there is a new one
    (https://issues.rudder.io/issues/17568[#17568])
* Fixed: No techniques in technique editor after upgrade from 5.0.18 to 6.1-rc1 on debian9
    (https://issues.rudder.io/issues/17572[#17572])
* Fixed: GM documentation is not rendered anymore
    (https://issues.rudder.io/issues/17563[#17563])

==== Rudder language

* Fixed: documentation quick update
    (https://issues.rudder.io/issues/17583[#17583])

==== Web - UI & UX

* Fixed: Plugin names are not displayed
    (https://issues.rudder.io/issues/17544[#17544])
* Fixed: Broken appearance of hover details in node details
    (https://issues.rudder.io/issues/17553[#17553])
* Fixed: Group property inherited tooltip is not visible
    (https://issues.rudder.io/issues/17546[#17546])

==== System techniques

* Fixed: rudder agent reset fails on root server
    (https://issues.rudder.io/issues/17580[#17580])

==== Agent

* Fixed: rudder agent run should not always return ok when there is no log
    (https://issues.rudder.io/issues/17571[#17571])
* Fixed: rudder agent stop displays the list of service event when quiet is required
    (https://issues.rudder.io/issues/17561[#17561])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.rc1 (2020-05-28)

=== Changes

==== Documentation

* Add a banner on the docs of non-released/deprecated versions
    (https://issues.rudder.io/issues/17485[#17485])
* Small fixes in variables page
    (https://issues.rudder.io/issues/17353[#17353])
* Add Branding endpoints in API documentation
    (https://issues.rudder.io/issues/17437[#17437])

==== Packaging

* Strip rust release binaries
    (https://issues.rudder.io/issues/14697[#14697])
* Use cargo-deny to replace cargo-audit
    (https://issues.rudder.io/issues/17308[#17308])

==== Architecture - Internal libs

* Add a feature switch for rudder-lang test loop
    (https://issues.rudder.io/issues/17412[#17412])

==== Rudder language

* improve documentation coverage
    (https://issues.rudder.io/issues/17148[#17148])
* update reserved keywords list
    (https://issues.rudder.io/issues/17355[#17355])
* add contributing documentation
    (https://issues.rudder.io/issues/17289[#17289])

==== Relay server or API

* Update relayd dependencies to remove unmaintained "spin" crate
    (https://issues.rudder.io/issues/17384[#17384])

==== Web - UI & UX

* Improve notification display in Rudder
    (https://issues.rudder.io/issues/17383[#17383])

==== API

* Missing info about if a node is a relay in API and capabilities need to to in management technologie
    (https://issues.rudder.io/issues/17367[#17367])

==== Generic methods

* move all abort bundle in a dedicated lib file under 20_cfe_basics
    (https://issues.rudder.io/issues/17519[#17519])
* Allow forcing a "None" component in reporting
    (https://issues.rudder.io/issues/17095[#17095])

==== Generic methods - File Management

* Improve Augeas generic methods documentation
    (https://issues.rudder.io/issues/17464[#17464])
* Improve Augeas generic methods documentation
    (https://issues.rudder.io/issues/17464[#17464])

==== Technique editor - UI/UX

* Keep the original name of a Generic Method displayed
    (https://issues.rudder.io/issues/16937[#16937])

=== Bug fixes

==== Packaging

* Fixed: when upgrading to 6.1, ldap indexing should be normal and not quick
    (https://issues.rudder.io/issues/17532[#17532])
* Fixed: Missing context on relayd binary on CentOS7
    (https://issues.rudder.io/issues/17522[#17522])
* Fixed: Apache must be restarted after acl change in rudder-init
    (https://issues.rudder.io/issues/17515[#17515])
* Fixed: apache acl are empty after installation
    (https://issues.rudder.io/issues/17495[#17495])
* Fixed: #17395 should not be in 6.1
    (https://issues.rudder.io/issues/17474[#17474])
* Fixed: Warn users if scale-out-relay plugin is not installed when promoting node through script
    (https://issues.rudder.io/issues/17429[#17429])
* Fixed: cf-agent writes a lot of times to cf_lock db
    (https://issues.rudder.io/issues/17336[#17336])
* Fixed: Python scripts on rhel7 are set to use python3 which is not available
    (https://issues.rudder.io/issues/17433[#17433])
* Fixed: Missing dependencies between server services
    (https://issues.rudder.io/issues/17402[#17402])
* Fixed: Error while upgrading rudder from 6.0.5 to 6.1 nightly on debian
    (https://issues.rudder.io/issues/17397[#17397])
* Fixed: SELinux policy for technique editor is not applied anymore after upgrade on RHEL/Centos server
    (https://issues.rudder.io/issues/17395[#17395])
* Fixed: We use the "service" command (on CentOS7) do not not depend on the package providing it
    (https://issues.rudder.io/issues/17386[#17386])
* Fixed: Missing dependency on iproute2 making rudder-init fails on minimal install
    (https://issues.rudder.io/issues/17356[#17356])
* Fixed: Remote-run does not work anymore with SELinux
    (https://issues.rudder.io/issues/17516[#17516])
* Fixed: remove progressive output from postinstall
    (https://issues.rudder.io/issues/17525[#17525])
* Fixed: Upgrading Rudder from 5.0.18 to 6.1-nightly does not update techniques
    (https://issues.rudder.io/issues/17313[#17313])
* Fixed: Allow httpd to serve policy files for windows
    (https://issues.rudder.io/issues/17488[#17488])

==== Plugins integration

* Fixed: add rudder-synchonize within Rudder
    (https://issues.rudder.io/issues/17345[#17345])

==== Agent

* Fixed: Debug script is broken in 6.0
    (https://issues.rudder.io/issues/17380[#17380])
* Fixed: remove progressive output from agent check
    (https://issues.rudder.io/issues/17526[#17526])
* Fixed: Add doc about return codes to agent man page
    (https://issues.rudder.io/issues/17281[#17281])

==== Performance and scalability

* Fixed: Agent consuming lots of IO and resources at each run
    (https://issues.rudder.io/issues/17371[#17371])
* Fixed: when running cf-promises, list-compatible-inputs is ran 8 times
    (https://issues.rudder.io/issues/17481[#17481])

==== Documentation

* Fixed: Inconsistent commands for service management
    (https://issues.rudder.io/issues/17529[#17529])
* Fixed: Images from private plugins are not visible
    (https://issues.rudder.io/issues/17498[#17498])
* Fixed: wrong url to download.rudder.io on 6.1
    (https://issues.rudder.io/issues/17484[#17484])
* Fixed: Broken links in docs
    (https://issues.rudder.io/issues/17389[#17389])
* Fixed: Add explanation to setup technique editor in development environement in 6.1
    (https://issues.rudder.io/issues/17502[#17502])
* Fixed: Missing validated user endpoints in change validation api doc
    (https://issues.rudder.io/issues/17434[#17434])

==== Web - Config management

* Fixed: error when a technique with a directive attached change in 6.1 blocks all technique updates
    (https://issues.rudder.io/issues/17523[#17523])
* Fixed: A repaired in system policies should not be seen as a problem for warning display in nodes list
    (https://issues.rudder.io/issues/17521[#17521])
* Fixed: Inherited properties don't appear anymore
    (https://issues.rudder.io/issues/17496[#17496])
* Fixed: Global parameter which are a comment string are ignored
    (https://issues.rudder.io/issues/17491[#17491])
* Fixed: Ignored node lead to an error log during generation
    (https://issues.rudder.io/issues/17441[#17441])
* Fixed: Ignored node lead to an error log during generation
    (https://issues.rudder.io/issues/17441[#17441])
* Fixed: We can't choose between string and json for global parameters
    (https://issues.rudder.io/issues/17325[#17325])
* Fixed: err17: can not update attribute in parameter
    (https://issues.rudder.io/issues/17396[#17396])

==== Miscellaneous

* Fixed: When no User rules are defined on a node, compliance tab on node details shows an error 
    (https://issues.rudder.io/issues/17527[#17527])
* Fixed: add debug to makefile
    (https://issues.rudder.io/issues/17191[#17191])
* Fixed: Fail password confirmation in BCrypt lead to an user with empty password in file
    (https://issues.rudder.io/issues/17424[#17424])

==== Web - Nodes & inventories

* Fixed: inventory watcher should ignore uuid.hive file
    (https://issues.rudder.io/issues/17507[#17507])
* Fixed: Change message in case of udefined certificate for a node
    (https://issues.rudder.io/issues/17487[#17487])
* Fixed: Purge of unreferenced software may still fail on very large system
    (https://issues.rudder.io/issues/17176[#17176])
* Fixed: Add log about node group update failure because of inconsistency
    (https://issues.rudder.io/issues/17421[#17421])
* Fixed: Group property UX is unclear regarding saving
    (https://issues.rudder.io/issues/17312[#17312])
* Fixed: Some inventories are not correctly noticed by inotify file watcher
    (https://issues.rudder.io/issues/15422[#15422])
* Fixed: Inventory upload is not distributed uniformly
    (https://issues.rudder.io/issues/7290[#7290])

==== Web - Maintenance

* Fixed: Nashorn deprecation should be "info" level
    (https://issues.rudder.io/issues/17524[#17524])
* Fixed: Parameters are not restored from archive
    (https://issues.rudder.io/issues/17457[#17457])
* Fixed: Webapp block at start on inventory processing
    (https://issues.rudder.io/issues/17482[#17482])
* Fixed: Historization of node count reports wrong value for pending nodes
    (https://issues.rudder.io/issues/17372[#17372])

==== Web - UI & UX

* Fixed: When adding tags, if anything is wrong in the directive form, all unsaved tags are wiped out
    (https://issues.rudder.io/issues/15557[#15557])
* Fixed: OS logo is missing in summary node
    (https://issues.rudder.io/issues/16454[#16454])
* Fixed: Move "System status" tab before technical logs
    (https://issues.rudder.io/issues/17486[#17486])
* Fixed: Technique doc is not formatted when clicking on technique in tree
    (https://issues.rudder.io/issues/17413[#17413])
* Fixed: Ignored (disabled) nodes are show as enabled in details
    (https://issues.rudder.io/issues/17440[#17440])
* Fixed: Separate system rules from user-defined rules in node compliance display
    (https://issues.rudder.io/issues/17427[#17427])
* Fixed: Missing information that markdown is supported for technique documentation
    (https://issues.rudder.io/issues/17415[#17415])

==== Architecture - Refactoring

* Fixed: Build broke in 6.1 due to faulty merge
    (https://issues.rudder.io/issues/17490[#17490])

==== Web - Compliance & node report

* Fixed: Error log about duplicates entries when saving node compliance levels
    (https://issues.rudder.io/issues/17410[#17410])

==== Relay server or API

* Fixed: Ignore invalid hash in nodeslist
    (https://issues.rudder.io/issues/17458[#17458])
* Fixed: Inventories from new nodes should be sent using the "rudder" password and not generated one
    (https://issues.rudder.io/issues/17416[#17416])

==== System integration

* Fixed: rudder package command fails when not run from a terminal
    (https://issues.rudder.io/issues/17453[#17453])

==== API

* Fixed: API documentation on Rules is missing explanation on how to update rule category
    (https://issues.rudder.io/issues/17409[#17409])
* Fixed: Bad JSON answer for api PUT /rules
    (https://issues.rudder.io/issues/17388[#17388])

==== Architecture - Internal libs

* Fixed: Stacktrace in test introduce in #17341
    (https://issues.rudder.io/issues/17411[#17411])

==== Rudder language

* Fixed: translate should not use hardcoded path for libraries
    (https://issues.rudder.io/issues/17252[#17252])
* Fixed: fix compilation failure
    (https://issues.rudder.io/issues/17405[#17405])

==== System techniques

* Fixed: Error when setting classes for agent capabilities
    (https://issues.rudder.io/issues/17480[#17480])
* Fixed: properties loading needs to be done in a common bundle
    (https://issues.rudder.io/issues/17478[#17478])

==== Techniques

* Fixed: Rsync commands for shared files are broken
    (https://issues.rudder.io/issues/17468[#17468])

==== Web - Technique editor

* Fixed: Modifying a method parameter does not trigger the save button
    (https://issues.rudder.io/issues/17494[#17494])
* Fixed: Technique description is displayed two times in the technique editor
    (https://issues.rudder.io/issues/17393[#17393])
* Fixed: Category for new technique are not sorted
    (https://issues.rudder.io/issues/17414[#17414])
* Fixed: Technique diverge popup when coming back to a techniques because of a change of category
    (https://issues.rudder.io/issues/17400[#17400])
* Fixed: Popup saying that technique change still happens in 6.1
    (https://issues.rudder.io/issues/17319[#17319])

==== Technique editor - Techniques

* Fixed: Move Markdown message in icon tooltip
    (https://issues.rudder.io/issues/17503[#17503])

==== Generic methods

* Fixed: ncf_def should be bundle common
    (https://issues.rudder.io/issues/17477[#17477])
* Fixed: remove non-rudder logger from ncf
    (https://issues.rudder.io/issues/17354[#17354])

==== Technique editor - API

* Fixed: techniques files are parsed twice
    (https://issues.rudder.io/issues/17425[#17425])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.beta3 (2020-05-11)

=== Changes

==== Documentation

* Documentation for group properties
    (https://issues.rudder.io/issues/17282[#17282])

==== Web - Config management

* Prevent removal of 'system' global and group properties
    (https://issues.rudder.io/issues/17227[#17227])

==== Packaging

* Add auto reload of welcome page
    (https://issues.rudder.io/issues/17317[#17317])

=== Bug fixes

==== Packaging

* Fixed: strip calls fail on aix
    (https://issues.rudder.io/issues/17365[#17365])
* Fixed: rpm build logs are huge
    (https://issues.rudder.io/issues/17360[#17360])
* Fixed: 6.1 fails to build on aix
    (https://issues.rudder.io/issues/17357[#17357])
* Fixed: create migration script for LDAP indexes
    (https://issues.rudder.io/issues/17215[#17215])
* Fixed: create migration script for LDAP indexes
    (https://issues.rudder.io/issues/17215[#17215])
* Fixed: rudder fails to build in 6.0
    (https://issues.rudder.io/issues/17339[#17339])
* Fixed: Package cache is updated at each run
    (https://issues.rudder.io/issues/17337[#17337])
* Fixed: cf-agent writes a lot of times to performance db
    (https://issues.rudder.io/issues/17335[#17335])
* Fixed: At relay install time, if the domain is not defined the server certificate can not be issued
    (https://issues.rudder.io/issues/17332[#17332])

==== Documentation

* Fixed: Move variables doc into "usge" category
    (https://issues.rudder.io/issues/17368[#17368])
* Fixed: improve documentation on "default" for variable to state that it should be quoted
    (https://issues.rudder.io/issues/17352[#17352])
* Fixed: Doc about missing uuid.hive at upgrade was not upmerged
    (https://issues.rudder.io/issues/17299[#17299])

==== Web - Compliance & node report

* Fixed: Inconsistent syntax for global parameter in directive incompatible with JSON values
    (https://issues.rudder.io/issues/17350[#17350])
* Fixed: JSON global parameter are inherited as string
    (https://issues.rudder.io/issues/17326[#17326])

==== Technique editor - API

* Fixed: When defining a category for a new technique, the files are not placed on the correct path in the git repo
    (https://issues.rudder.io/issues/17338[#17338])

==== Web - UI & UX

* Fixed: The generic methods documentation is no longer accessible from the technique editor
    (https://issues.rudder.io/issues/17321[#17321])
* Fixed: main parameter of a method is not displayed anymore, and result classes are not ok anymore
    (https://issues.rudder.io/issues/17329[#17329])

==== API

* Fixed: when importing a technique with  /api/internal/techniques, the order of parameters is not respected
    (https://issues.rudder.io/issues/17348[#17348])

==== Web - Config management

* Fixed: Data for reporting plugin are not generated anymore
    (https://issues.rudder.io/issues/17341[#17341])
* Fixed: Property name aren't limited to ascii
    (https://issues.rudder.io/issues/17334[#17334])
* Fixed: Group properties inheritance error when it should not
    (https://issues.rudder.io/issues/17324[#17324])

==== System techniques

* Fixed: Disable sending old reports from relayd
    (https://issues.rudder.io/issues/17349[#17349])

==== Web - Technique editor

* Fixed: Resource manager should talk about saved/unsaved and not committed/not committed
    (https://issues.rudder.io/issues/17328[#17328])

==== Technique editor - UI/UX

* Fixed: Tooltips not showing up
    (https://issues.rudder.io/issues/17333[#17333])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.beta2 (2020-05-04)

=== Changes

==== Documentation

* Document that Rudder servers should not be exposed on the Internet
    (https://issues.rudder.io/issues/17316[#17316])

==== Rudder language

* rename stdlib to resourcelib
    (https://issues.rudder.io/issues/17254[#17254])
* rename stdlib to resourcelib
    (https://issues.rudder.io/issues/17254[#17254])

=== Bug fixes

==== Packaging

* Fixed: jq is not available in the base repositories on SLES15 and should be embedded with the agent package
    (https://issues.rudder.io/issues/17318[#17318])
* Fixed: installing rudder server 6.1.0~beta1 on debian 9 fails
    (https://issues.rudder.io/issues/17280[#17280])
* Fixed: openssl fails to build on aix
    (https://issues.rudder.io/issues/17262[#17262])

==== API

* Fixed: API documentation omits the policymode parameter of directives
    (https://issues.rudder.io/issues/17301[#17301])

==== Web - UI & UX

* Fixed: Page for node not found is too minimalist
    (https://issues.rudder.io/issues/16515[#16515])
* Fixed: RuleID is not trimmed when copied from the GUI
    (https://issues.rudder.io/issues/17290[#17290])

==== Security

* Fixed: exception in ldap search are not correctly caught
    (https://issues.rudder.io/issues/17267[#17267])

==== Documentation

* Fixed: API documentation is lacking of a Json based update of rule/directive
    (https://issues.rudder.io/issues/17292[#17292])

==== Agent

* Fixed: rudder agent run returns exit code 1 when everything is ok
    (https://issues.rudder.io/issues/17268[#17268])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Victor Héry

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.beta1 (2020-04-28)

=== Changes

==== Packaging

* Embed openssl 1.1.1 on every OS
    (https://issues.rudder.io/issues/17233[#17233])
* Do not embed openssl and curl on distribution with a recent openssl
    (https://issues.rudder.io/issues/17231[#17231])
* Replace node-to-relay script from rudder-package
    (https://issues.rudder.io/issues/17217[#17217])
* Replace node-to-relay script from rudder-package
    (https://issues.rudder.io/issues/17217[#17217])
* add jq to rudder agent
    (https://issues.rudder.io/issues/17139[#17139])
* Add systemd hardening config for slapd
    (https://issues.rudder.io/issues/17055[#17055])
* Upgrade Jetty to latest version
    (https://issues.rudder.io/issues/16905[#16905])
* It should be impossible to connect with "admin" password with default config
    (https://issues.rudder.io/issues/16732[#16732])
* Display Rust tooling version in build
    (https://issues.rudder.io/issues/16969[#16969])
* Use SPDX headers in relay
    (https://issues.rudder.io/issues/16834[#16834])

==== Performance and scalability

* review index for LDAP
    (https://issues.rudder.io/issues/17128[#17128])
* Do not compute dynamic groups if nothing changed in LDAP
    (https://issues.rudder.io/issues/17237[#17237])
* By default we should not archive reports
    (https://issues.rudder.io/issues/16931[#16931])
* Don't replace RudderUniqueId in generated policies with a replace, but with StringTemplate
    (https://issues.rudder.io/issues/16856[#16856])

==== Agent

* Make agents preserve perm on copy to keep previous behavior (patch for CFEngine 3.15)
    (https://issues.rudder.io/issues/17124[#17124])
* Update agent to CFEngine 3.15.1
    (https://issues.rudder.io/issues/16734[#16734])
* Add a command to set policy server on agents
    (https://issues.rudder.io/issues/16529[#16529])
* Add support for HTTP reporting in changes-only mode
    (https://issues.rudder.io/issues/17153[#17153])

==== Documentation

* Improve doc related to plugins/subscriptions
    (https://issues.rudder.io/issues/17144[#17144])
* Update doc for initial user account
    (https://issues.rudder.io/issues/17174[#17174])
* Prepare doc for 6.1
    (https://issues.rudder.io/issues/17130[#17130])
* Update content of docs menus
    (https://issues.rudder.io/issues/17033[#17033])
* Improve accessibility of documentation site's menu
    (https://issues.rudder.io/issues/16984[#16984])
* Update get-started for 6.0
    (https://issues.rudder.io/issues/16986[#16986])
* Update screenshots in "Install relay server" section
    (https://issues.rudder.io/issues/16945[#16945])
* Update screenshot in the documentation
    (https://issues.rudder.io/issues/16752[#16752])
* Add upgrade note to document how to switch from previous hash function to BCrypt
    (https://issues.rudder.io/issues/16729[#16729])
* Add Bcrypt support informations 
    (https://issues.rudder.io/issues/16724[#16724])
* Adapt doc for 6.1
    (https://issues.rudder.io/issues/15846[#15846])
* Add promote to relay endpoint in API documentation
    (https://issues.rudder.io/issues/17162[#17162])
* Clarify webapp contributing documentation
    (https://issues.rudder.io/issues/16914[#16914])
* Add spdx licenses for api doc
    (https://issues.rudder.io/issues/16883[#16883])
* Documentation is outdated for development
    (https://issues.rudder.io/issues/16932[#16932])

==== Web - Config management

* Initialize `rudder` global parameter to default value at boot
    (https://issues.rudder.io/issues/17251[#17251])
* Display node properties inherited from group/global
    (https://issues.rudder.io/issues/17173[#17173])
* Display technique description in directive form as markdown
    (https://issues.rudder.io/issues/17238[#17238])
* Rudder should be able to read techniques by itself and not rely on legacy ncf rest api
    (https://issues.rudder.io/issues/17133[#17133])
* Add JSON support for global parameters
    (https://issues.rudder.io/issues/16301[#16301])
* Group properties
    (https://issues.rudder.io/issues/16347[#16347])

==== Architecture - Refactoring

* Update some libraries for 6.1
    (https://issues.rudder.io/issues/17224[#17224])
* Dead code: com.normation.rudder.domain.system
    (https://issues.rudder.io/issues/17189[#17189])
* Clarify code of rollback events parsing
    (https://issues.rudder.io/issues/16603[#16603])

==== Web - UI & UX

* Update links in login page
    (https://issues.rudder.io/issues/17218[#17218])
* Beautify banner warning for expired plugin
    (https://issues.rudder.io/issues/16910[#16910])
* Display a warning in place of login form if no user are defined
    (https://issues.rudder.io/issues/17070[#17070])
* Display directive tags inside Compliance tables
    (https://issues.rudder.io/issues/16869[#16869])
* Display tags when listing directives
    (https://issues.rudder.io/issues/16346[#16346])
* Adapt user configuration file to remove default admin credentials
    (https://issues.rudder.io/issues/16731[#16731])
* Update users configuration file to add BCrypt support
    (https://issues.rudder.io/issues/16730[#16730])
* Update UI for group page to new template
    (https://issues.rudder.io/issues/16473[#16473])

==== API

* Add Usermanagement endpoints in API documentation
    (https://issues.rudder.io/issues/17164[#17164])
* Be able to save in LDAP a Policy Server Target
    (https://issues.rudder.io/issues/16906[#16906])
* Be able to save in LDAP a Policy Server Target
    (https://issues.rudder.io/issues/16906[#16906])

==== System integration

* Historize node count information
    (https://issues.rudder.io/issues/17161[#17161])

==== Miscellaneous

* Missing LDAP write operations to promote a node to relay
    (https://issues.rudder.io/issues/17112[#17112])
* Missing LDAP write operations to promote a node to relay
    (https://issues.rudder.io/issues/17112[#17112])

==== Plugins integration

* Add "technical preview" status for plugins
    (https://issues.rudder.io/issues/17093[#17093])

==== Rudder language

* make translate methods use stdlib rather than regexes
    (https://issues.rudder.io/issues/17115[#17115])
* logging adjustments for integration test loop
    (https://issues.rudder.io/issues/17114[#17114])
* test loop integration
    (https://issues.rudder.io/issues/16902[#16902])
* Full review of rudder-lang suported systems
    (https://issues.rudder.io/issues/16974[#16974])
* Rework os class translation into rudder-lang
    (https://issues.rudder.io/issues/17052[#17052])
* Implement metadata for enums
    (https://issues.rudder.io/issues/17049[#17049])
* Load all files from stdlib automatically
    (https://issues.rudder.io/issues/17047[#17047])
* Replace SourceList with a typed arena
    (https://issues.rudder.io/issues/17046[#17046])
* Cleanup rudder-lang tester
    (https://issues.rudder.io/issues/17010[#17010])
* non global items can have duplicate names
    (https://issues.rudder.io/issues/16992[#16992])
* Add enum aliases in rudder lang
    (https://issues.rudder.io/issues/16972[#16972])
* Add range to enum expressions
    (https://issues.rudder.io/issues/16928[#16928])
* rudder-lang packaging changes
    (https://issues.rudder.io/issues/16967[#16967])
* rudder-lang packaging update
    (https://issues.rudder.io/issues/16886[#16886])
* Fix clippy warnings in rudder-lang
    (https://issues.rudder.io/issues/16943[#16943])
* Improve compiler options
    (https://issues.rudder.io/issues/16938[#16938])
* Prepare documentation layout for rudder-lang
    (https://issues.rudder.io/issues/16934[#16934])
* Prepare documentation layout for rudder-lang
    (https://issues.rudder.io/issues/16934[#16934])
* Reimplement enums
    (https://issues.rudder.io/issues/16924[#16924])
* tests changes to prepare rudder-lang integration
    (https://issues.rudder.io/issues/16846[#16846])
* rl add cfengine_core to libs, which declares global variables
    (https://issues.rudder.io/issues/16807[#16807])
* rl add an optional path for compilation and translation
    (https://issues.rudder.io/issues/16775[#16775])
* rl allow splitted global variables declaration
    (https://issues.rudder.io/issues/16774[#16774])
* rl enchance variables handling 
    (https://issues.rudder.io/issues/16728[#16728])
* rl enchance variables handling 
    (https://issues.rudder.io/issues/16728[#16728])
* rl generate enum mappings from os tree
    (https://issues.rudder.io/issues/16717[#16717])
* rl improve output fidelity of generated cf files
    (https://issues.rudder.io/issues/16658[#16658])
* rl add non terminating errors and related integration tests
    (https://issues.rudder.io/issues/16616[#16616])
* format entire rudderlang code according to style guidelines 
    (https://issues.rudder.io/issues/16614[#16614])

==== Web - Nodes & inventories

* Agent capabilities in inventory are not parsed
    (https://issues.rudder.io/issues/12109[#12109])

==== Relay server or API

* Add support for parsing HTTP logs from Windows
    (https://issues.rudder.io/issues/17073[#17073])

==== Security

* Allow content to be shown in iframe
    (https://issues.rudder.io/issues/17072[#17072])
* We should use BCrypt by default for storing user's local password
    (https://issues.rudder.io/issues/16674[#16674])
* Add a command to generate user accounts after installation
    (https://issues.rudder.io/issues/16620[#16620])

==== Architecture - Internal libs

* Upgrade to ZIO RC18
    (https://issues.rudder.io/issues/16892[#16892])

==== Techniques

* Delete deprecated techniques, and deprecate techniques in 6.1
    (https://issues.rudder.io/issues/17159[#17159])

==== Generic methods - Package Management

* Make the package_module bodies configurable
    (https://issues.rudder.io/issues/9110[#9110])

==== Technique editor - UI/UX

* Define the category of a technique
    (https://issues.rudder.io/issues/16345[#16345])
* Add description of technique parameters
    (https://issues.rudder.io/issues/17239[#17239])
* Improve UX for technique resource files
    (https://issues.rudder.io/issues/17078[#17078])

==== Generic methods

* Sync stdlib with 3.15.1
    (https://issues.rudder.io/issues/17229[#17229])
* Add verbosity level in the rudder logger
    (https://issues.rudder.io/issues/15126[#15126])

==== Web - Technique editor

* Add fully qualified name of technique parameter
    (https://issues.rudder.io/issues/17029[#17029])

=== Bug fixes

==== Packaging

* Fixed: Our agent package contains CFEngine systemd units
    (https://issues.rudder.io/issues/16790[#16790])
* Fixed: We need to stop apache before removing ncf-api-venv user
    (https://issues.rudder.io/issues/17198[#17198])
* Fixed: rudderlang makefile integration
    (https://issues.rudder.io/issues/17187[#17187])
* Fixed: package fails to build jq
    (https://issues.rudder.io/issues/17175[#17175])
* Fixed: jq fails to build on old distro
    (https://issues.rudder.io/issues/17169[#17169])
* Fixed: make clean should not remove source in rudder-packages
    (https://issues.rudder.io/issues/17140[#17140])
* Fixed: rudder-webapp fails to build on 6.1
    (https://issues.rudder.io/issues/17125[#17125])
* Fixed: After server install, the "no user" login page link to a 404 documentation page
    (https://issues.rudder.io/issues/17163[#17163])
* Fixed: After server install, the "no user" login page link to a 404 documentation page
    (https://issues.rudder.io/issues/17163[#17163])

==== Agent

* Fixed: Update embedded openssl version to 1.1.1g
    (https://issues.rudder.io/issues/17178[#17178])
* Fixed: When in changes-only and nothing needs to be sent an empty invalid report is sent
    (https://issues.rudder.io/issues/17193[#17193])
* Fixed: Restart the webapp after creating a user
    (https://issues.rudder.io/issues/17190[#17190])
* Fixed: HTTP report PUT prints useless messages at the end of the run
    (https://issues.rudder.io/issues/16112[#16112])

==== Documentation

* Fixed: Add a link to upgrade notes at the beginning of each upgrade doc page
    (https://issues.rudder.io/issues/17219[#17219])
* Fixed: Fix 6.1 doc build
    (https://issues.rudder.io/issues/17207[#17207])
* Fixed: Fix links in 6.1 homepage
    (https://issues.rudder.io/issues/17200[#17200])
* Fixed: Plugins menu in the documentation should be in alphabetical order
    (https://issues.rudder.io/issues/16808[#16808])
* Fixed: Add Create Node endpoint in API documentation
    (https://issues.rudder.io/issues/17183[#17183])

==== Web - Maintenance

* Fixed: Rudder 6.1 does not start anymore
    (https://issues.rudder.io/issues/17228[#17228])
* Fixed: Rudder 6.1 does not start anymore
    (https://issues.rudder.io/issues/17228[#17228])

==== Web - Nodes & inventories

* Fixed: when a node is removed from a dynamc group, it log "adding nothing, removing nothing"
    (https://issues.rudder.io/issues/17220[#17220])
* Fixed: Concurrent access to node info cache cause exception to be thrown when accessing cache content
    (https://issues.rudder.io/issues/17172[#17172])
* Fixed: Search does not work in group criteria
    (https://issues.rudder.io/issues/17203[#17203])

==== Web - Config management

* Fixed: TechniqueVersion ordering algorithm is incorrect
    (https://issues.rudder.io/issues/17157[#17157])
* Fixed: cannot add directives to a rules
    (https://issues.rudder.io/issues/17099[#17099])
* Fixed: Don't fail generation for HTTPS only reports with  DSC/6.1
    (https://issues.rudder.io/issues/17085[#17085])

==== Performance and scalability

* Fixed: chmod at the end of policy generation is painfully slow
    (https://issues.rudder.io/issues/17214[#17214])

==== Web - UI & UX

* Fixed: rudder version is wrong in the login page
    (https://issues.rudder.io/issues/17201[#17201])
* Fixed: Not all tags have the same appearance
    (https://issues.rudder.io/issues/16897[#16897])

==== Architecture - Refactoring

* Fixed: Remove warning and "Inconsistency" typo compilation error
    (https://issues.rudder.io/issues/17156[#17156])
* Fixed: Inconsistency error is misspelled
    (https://issues.rudder.io/issues/17110[#17110])

==== Security

* Fixed: cannot login in Rudder 6.1
    (https://issues.rudder.io/issues/17108[#17108])

==== Rudder language

* Fixed: Compilation output file is not generated when input file is a path
    (https://issues.rudder.io/issues/17094[#17094])
* Fixed: translation into rudder-lang doesn't handle any class
    (https://issues.rudder.io/issues/17075[#17075])
* Fixed: Use Pin tu fix source code address
    (https://issues.rudder.io/issues/16998[#16998])
* Fixed: fix generation of parameters and conditions from cfengine files
    (https://issues.rudder.io/issues/16878[#16878])
* Fixed: rl compile fix enum logical expressions
    (https://issues.rudder.io/issues/16713[#16713])
* Fixed: rl translate add exception for kernel_module resource parsing
    (https://issues.rudder.io/issues/16711[#16711])

==== System techniques

* Fixed: Runlog catchup does not work on linux
    (https://issues.rudder.io/issues/17192[#17192])

==== Technique editor - UI/UX

* Fixed: Text &  Boxes jump when displaying missing inputs
    (https://issues.rudder.io/issues/16235[#16235])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

and rc versions are listed below for convenience.
