= Change logs for Rudder 6.1

Rudder 6.1 is currently a maintained version of Rudder.

This page provides a summary of changes for each version. Previous beta

== Rudder 6.1.1 (2020-07-03)

=== Changes

==== Documentation

* Add a Rudder by example for using Rudder server/relays as file mirror (for repos)
    (https://issues.rudder.io/issues/17858[#17858])
* Add docs about configuration-repository, how to sync it and what can be modified or not from outside
    (https://issues.rudder.io/issues/17865[#17865])
* Add doc about network resiliency
    (https://issues.rudder.io/issues/17880[#17880])
* Improve documentation about communication security
    (https://issues.rudder.io/issues/17834[#17834])
* Add a rudder-by-example for git sync in shared-files
    (https://issues.rudder.io/issues/17840[#17840])
* Document how to use custom certificates
    (https://issues.rudder.io/issues/14206[#14206])
* Document how to use custom certificates
    (https://issues.rudder.io/issues/14206[#14206])
* Missing uninstall doc for agent
    (https://issues.rudder.io/issues/17790[#17790])
* Add screenshots for technique editor with annotation in get started documentation
    (https://issues.rudder.io/issues/17781[#17781])

==== Web - UI & UX

* Inconsistent fonts in technical logs
    (https://issues.rudder.io/issues/16032[#16032])

==== Rudder language

* add doc about logs and generated techniques 
    (https://issues.rudder.io/issues/17738[#17738])

==== Techniques

* Firewall technique
    (https://issues.rudder.io/issues/16915[#16915])

=== Bug fixes

==== Web - Technique editor

* Fixed: Can't access on technique editor
    (https://issues.rudder.io/issues/17883[#17883])
* Fixed: "unsaved changed" technique editor pop-up appears when not needed
    (https://issues.rudder.io/issues/17750[#17750])
* Fixed: Resource path of a technique with a category different thant default category are wrong
    (https://issues.rudder.io/issues/17747[#17747])
* Fixed: When removing and adding a new method, the save button is disabled
    (https://issues.rudder.io/issues/17776[#17776])

==== Packaging

* Fixed: SLES12 upgrade error 6.0 to 6.1
    (https://issues.rudder.io/issues/17873[#17873])
* Fixed: some errors when upgrading from 5.0.18nightly to 6.1-nightly on debian9 and 10
    (https://issues.rudder.io/issues/17644[#17644])
* Fixed: Optimize elm application
    (https://issues.rudder.io/issues/17888[#17888])
* Fixed: shared-files acls are incorrect on relays, preventing the windows nodes from downloading them
    (https://issues.rudder.io/issues/17802[#17802])

==== Documentation

* Fixed: Add support of Ubuntu 20 in doc
    (https://issues.rudder.io/issues/17874[#17874])
* Fixed: Typo in network resiliency documentation
    (https://issues.rudder.io/issues/17892[#17892])
* Fixed: Add trigger agent run feature from UI in get started 
    (https://issues.rudder.io/issues/17855[#17855])
* Fixed: remove pg_repack from documentation
    (https://issues.rudder.io/issues/17839[#17839])
* Fixed: Update screenshots in usage doc section 
    (https://issues.rudder.io/issues/17843[#17843])
* Fixed: Missing doc about root-relay communication flows
    (https://issues.rudder.io/issues/17837[#17837])
* Fixed: Missing ressources feature in technique editor doc
    (https://issues.rudder.io/issues/17787[#17787])
* Fixed: Broken link in apply advanced configuration get started doc
    (https://issues.rudder.io/issues/17792[#17792])
* Fixed: Missing markdown support for description in technique editor doc
    (https://issues.rudder.io/issues/17788[#17788])
* Fixed: Missing parameters feature in technique editor doc
    (https://issues.rudder.io/issues/17786[#17786])
* Fixed: Add link to further information in get started section
    (https://issues.rudder.io/issues/17771[#17771])
* Fixed: Replace deprecated generic methods in technique editor documentation usage
    (https://issues.rudder.io/issues/17768[#17768])
* Fixed: Documentation should state that SSD is recommended for more than 50 nodes
    (https://issues.rudder.io/issues/17761[#17761])
* Fixed: Refresh screenshots for technique editor
    (https://issues.rudder.io/issues/17746[#17746])

==== Miscellaneous

* Fixed: Typos in directive documentation
    (https://issues.rudder.io/issues/17762[#17762])
* Fixed: Typos in technique editor documentation
    (https://issues.rudder.io/issues/17760[#17760])

==== Relay server or API

* Fixed: Shared-files correction in postinst must be recursive
    (https://issues.rudder.io/issues/17882[#17882])

==== Rudder language

* Fixed: make use of parameters instead of args
    (https://issues.rudder.io/issues/17885[#17885])
* Fixed: fix nasty random generation failure
    (https://issues.rudder.io/issues/17811[#17811])
* Fixed: handle techniques location path properly
    (https://issues.rudder.io/issues/17737[#17737])
* Fixed: error about rudder-lang in logs
    (https://issues.rudder.io/issues/17724[#17724])

==== Web - Config management

* Fixed: Wrong error message when policy server of a Node is not found during generation 
    (https://issues.rudder.io/issues/17851[#17851])
* Fixed: Trying to add a group property with change request plugin enabled lead to blank property
    (https://issues.rudder.io/issues/17804[#17804])
* Fixed: Upgrading from rudder 5.0 to 6.0 leads to `distributePolicy not available` error
    (https://issues.rudder.io/issues/17836[#17836])
* Fixed: Updating property merge them in place of replacing them
    (https://issues.rudder.io/issues/17830[#17830])
* Fixed: When there is a serialisation error for parameter, their edit screen is unavaible
    (https://issues.rudder.io/issues/17702[#17702])
* Fixed: Duplicate category name error when saving a new user technique
    (https://issues.rudder.io/issues/17774[#17774])
* Fixed: Uncommited generic_methods.json in configuration repo
    (https://issues.rudder.io/issues/17775[#17775])
* Fixed: Auto-archive gitRepo.git failure warning is not actionnable, should be info or debug
    (https://issues.rudder.io/issues/17777[#17777])
* Fixed: description of global parameter "rudder" is misleading
    (https://issues.rudder.io/issues/17700[#17700])

==== API

* Fixed: Missing doc for group properties and json global parameters
    (https://issues.rudder.io/issues/17818[#17818])
* Fixed: Group API compatibility broken as it now always expects "properties"
    (https://issues.rudder.io/issues/17815[#17815])
* Fixed: 'policyMode' vs. 'policy' in node settings API
    (https://issues.rudder.io/issues/17817[#17817])

==== Web - Compliance & node report

* Fixed: Node details summary compliance contains system rules
    (https://issues.rudder.io/issues/17660[#17660])

==== Web - UI & UX

* Fixed: user with read_only right has button that allows write actions 
    (https://issues.rudder.io/issues/17725[#17725])
* Fixed: Select node state in settings is confusiing for read_only user 
    (https://issues.rudder.io/issues/17627[#17627])
* Fixed: when we create a group, we should go directly to the criteria page
    (https://issues.rudder.io/issues/17678[#17678])
* Fixed: Content in header of plugin page overflows when custom from branding is activate
    (https://issues.rudder.io/issues/17731[#17731])

==== Performance and scalability

* Fixed: table nodes contains on entry per node per generation, which is too much
    (https://issues.rudder.io/issues/17778[#17778])
* Fixed: table nodes contains on entry per node per generation, which is too much
    (https://issues.rudder.io/issues/17778[#17778])

==== Techniques

* Fixed: clockConfiguration is not compatible with systemd-based systems
    (https://issues.rudder.io/issues/6772[#6772])

==== System techniques

* Fixed: Rudder 6 check postgresql process failes
    (https://issues.rudder.io/issues/17145[#17145])
* Fixed: error when installing rudder server root on debian 9 - 6.1
    (https://issues.rudder.io/issues/17765[#17765])
* Fixed: Initial promises warning during agent setup
    (https://issues.rudder.io/issues/17722[#17722])

==== Technique editor - UI/UX

* Fixed: Save button is disable when a technique is imported
    (https://issues.rudder.io/issues/17897[#17897])
* Fixed: Gear icon in save button always displayed
    (https://issues.rudder.io/issues/17745[#17745])

==== Technique editor - Techniques

* Fixed: Importing technique leads to a blocked editor
    (https://issues.rudder.io/issues/17793[#17793])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Tristan Le Chanony
* Alexander Brunhirl

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0 (2020-06-17)

=== Changes

==== Miscellaneous

* Add a 'Rudder by example' best practice use case
    (https://issues.rudder.io/issues/17715[#17715])
* Add a 'Rudder by example' best practice use case
    (https://issues.rudder.io/issues/17715[#17715])
* Add a 'Rudder by example' best practice use case
    (https://issues.rudder.io/issues/17715[#17715])
* Add a 'Rudder by example' best practice use case
    (https://issues.rudder.io/issues/17715[#17715])

==== Documentation

* Prepare doc for final 6.1 release
    (https://issues.rudder.io/issues/17648[#17648])

==== Containers

* Dockerize Rudder Relay Server
    (https://issues.rudder.io/issues/17732[#17732])
* Dockerize Rudder Relay Server
    (https://issues.rudder.io/issues/17732[#17732])

=== Bug fixes

==== Packaging

* Fixed: systemd detection fails when init has parameters
    (https://issues.rudder.io/issues/17717[#17717])

==== Documentation

* Fixed: broken doc build because of spaces in file name
    (https://issues.rudder.io/issues/17751[#17751])
* Fixed: Broken links in rudder-by-example
    (https://issues.rudder.io/issues/17735[#17735])
* Fixed: Missing documentation for overriding jetty system properties in start.ini
    (https://issues.rudder.io/issues/17719[#17719])
* Fixed: Document access to `ipv4[eth0]` system variable
    (https://issues.rudder.io/issues/17705[#17705])
* Fixed: Add a `rudder-by-example` for rudder-agent package update
    (https://issues.rudder.io/issues/17686[#17686])

==== Technique editor - UI/UX

* Fixed: Filter on agent type also filter generic methods in technique
    (https://issues.rudder.io/issues/17749[#17749])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.rc4 (2020-06-11)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: Rudder-agent needs libxml-treepp-perl dependency to work on minimal Debian
    (https://issues.rudder.io/issues/17699[#17699])
* Fixed: /opt/rudder/etc/rudder-pkg comes with the wrong permissions
    (https://issues.rudder.io/issues/17695[#17695])
* Fixed: All package script should be set -e
    (https://issues.rudder.io/issues/17687[#17687])
* Fixed: Upgrade to 6.1 fails on httpd start beacause of old ncf conf is still present on rpm
    (https://issues.rudder.io/issues/17681[#17681])
* Fixed: gpg import error in rudder-pkg
    (https://issues.rudder.io/issues/17692[#17692])
* Fixed: package key is not trusted by rudder-pkg
    (https://issues.rudder.io/issues/17675[#17675])
* Fixed: Error in technique editor just after install: No such file or directory: '/var/rudder/configuration-repository/ncf/generic_methods.json'
    (https://issues.rudder.io/issues/17573[#17573])

==== System integration

* Fixed: An error in during upgrade to 6.1 breaks rudder upgrade and everything
    (https://issues.rudder.io/issues/17659[#17659])
* Fixed: Bad init value for param rudder_file_edit_header
    (https://issues.rudder.io/issues/17701[#17701])
* Fixed: Cannot download licenses if there is a trailing slash in rudder package config url
    (https://issues.rudder.io/issues/17673[#17673])

==== Web - Config management

* Fixed: Error in technique editor "could not get generic method metadata" after upgrade from 6.0
    (https://issues.rudder.io/issues/17683[#17683])

==== Web - Compliance & node report

* Fixed: Global parameter "string" doesn't escape json
    (https://issues.rudder.io/issues/17674[#17674])

==== API

* Fixed: API doc build silently fails
    (https://issues.rudder.io/issues/17656[#17656])

==== Plugins integration

* Fixed: Improve rudder package error message when an update is needed
    (https://issues.rudder.io/issues/17626[#17626])

==== Technique editor - UI/UX

* Fixed: Deprecated method filter is broken
    (https://issues.rudder.io/issues/17647[#17647])
* Fixed: Still some technique diverge popup after you added a new method
    (https://issues.rudder.io/issues/17654[#17654])

==== Generic methods

* Fixed: Syntax error in shared_file_to_node
    (https://issues.rudder.io/issues/17667[#17667])
* Fixed: no reports from sharedfile to node if file is already there
    (https://issues.rudder.io/issues/17661[#17661])

==== Web - Technique editor

* Fixed: The technique editor struggles to display long line as component
    (https://issues.rudder.io/issues/17392[#17392])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.rc3 (2020-06-08)

=== Changes

==== Miscellaneous

* Dockerizing Rudder agent 
    (https://issues.rudder.io/issues/17604[#17604])
* Dockerizing Rudder agent 
    (https://issues.rudder.io/issues/17604[#17604])
* Dockerizing Rudder agent 
    (https://issues.rudder.io/issues/17604[#17604])
* Dockerizing Rudder agent 
    (https://issues.rudder.io/issues/17604[#17604])
* Dockerizing Rudder agent 
    (https://issues.rudder.io/issues/17604[#17604])

==== Rudder language

* Improve rudder-lang doc
    (https://issues.rudder.io/issues/16944[#16944])

=== Bug fixes

==== Packaging

* Fixed: error at install of rudder 6.1 on debian9
    (https://issues.rudder.io/issues/17636[#17636])
* Fixed: AIX builds fails on invalid or condition
    (https://issues.rudder.io/issues/17635[#17635])
* Fixed: Agent uses "cmp" command but it is not a dependency
    (https://issues.rudder.io/issues/17606[#17606])
* Fixed: The webapp is unable to start after a fresh install
    (https://issues.rudder.io/issues/17591[#17591])
* Fixed: ruder package command fails to run in automated setup
    (https://issues.rudder.io/issues/17645[#17645])
* Fixed: ruder package command fails to run in automated setup
    (https://issues.rudder.io/issues/17645[#17645])

==== Documentation

* Fixed: Update documentation about variable (condition)
    (https://issues.rudder.io/issues/17629[#17629])

==== Web - UI & UX

* Fixed: Clicking on the warning icon is node list should lead to system status page
    (https://issues.rudder.io/issues/17646[#17646])
* Fixed: Group value should only display value for that element in main table
    (https://issues.rudder.io/issues/17625[#17625])
* Fixed: Plugin expiration warning misalignement problem
    (https://issues.rudder.io/issues/17619[#17619])
* Fixed: Overriden pop-up top is missing
    (https://issues.rudder.io/issues/17623[#17623])
* Fixed: tooltip for node properties does not show
    (https://issues.rudder.io/issues/17550[#17550])
* Fixed: when searching nodes, on the search page, the checkbox "Include Rudder server components" if briefly checked and unchecked
    (https://issues.rudder.io/issues/17575[#17575])
* Fixed: Rudder logo appears in remote-run error message
    (https://issues.rudder.io/issues/17556[#17556])

==== Security

* Fixed: description in directives and groups are evaluated, and we can inject whatever we want
    (https://issues.rudder.io/issues/17641[#17641])

==== Rudder language

* Fixed: doc conflicting with tests
    (https://issues.rudder.io/issues/17649[#17649])
* Fixed: fix doc configuration files
    (https://issues.rudder.io/issues/17614[#17614])

==== Web - Compliance & node report

* Fixed: text explaining hierarchy of groups always shows up for system group
    (https://issues.rudder.io/issues/17638[#17638])
* Fixed: policy generation fails if we put a " in the directive name
    (https://issues.rudder.io/issues/17628[#17628])

==== Plugins integration

* Fixed: rudder package logs are inconsistent
    (https://issues.rudder.io/issues/17600[#17600])

==== Web - Nodes & inventories

* Fixed: compilation error in 6.0 because of absence of typo in Inconsistency
    (https://issues.rudder.io/issues/17605[#17605])
* Fixed: no policy generation after accepting many nodes in 6.1
    (https://issues.rudder.io/issues/17594[#17594])

==== Web - Maintenance

* Fixed: NPE when agent key is malformed
    (https://issues.rudder.io/issues/17597[#17597])

==== Web - Config management

* Fixed: when a policy generation is triggered by a dynamic group update, it states in event logs "Manually update policies"
    (https://issues.rudder.io/issues/17595[#17595])

==== Web - Technique editor

* Fixed: User with some to access technique editor api
    (https://issues.rudder.io/issues/17596[#17596])

==== System techniques

* Fixed: system techniques start rudder-relayd before setting postgresql passwords
    (https://issues.rudder.io/issues/17612[#17612])
* Fixed: inventory should be copied to /var/rudder/inventories/accepted-nodes-updates rather than uploaded on root server
    (https://issues.rudder.io/issues/17616[#17616])

==== Agent

* Fixed: error at install of rudder 6.1 server on debian 9
    (https://issues.rudder.io/issues/17637[#17637])
* Fixed: Warning message in relayd logs when reloading
    (https://issues.rudder.io/issues/17630[#17630])
* Fixed: rudder server root tries to set initial promises while they are not installed
    (https://issues.rudder.io/issues/17611[#17611])
* Fixed: possible use of undefined variable in lib/common.sh
    (https://issues.rudder.io/issues/17610[#17610])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.rc2 (2020-06-04)

=== Changes

==== Rudder language

* refactoring io usage and configuration
    (https://issues.rudder.io/issues/17403[#17403])

==== Plugins integration

* Rudder package list should display plugin status
    (https://issues.rudder.io/issues/16793[#16793])

=== Bug fixes

==== Packaging

* Fixed: Apache reload error during root server setup
    (https://issues.rudder.io/issues/17565[#17565])
* Fixed:  apache acl are still empty after installation
    (https://issues.rudder.io/issues/17564[#17564])
* Fixed: rudder init syntax error
    (https://issues.rudder.io/issues/17560[#17560])
* Fixed: postgresl client in relayd tries to read krb conf
    (https://issues.rudder.io/issues/17518[#17518])
* Fixed: First inventory fails when installing root server
    (https://issues.rudder.io/issues/17567[#17567])

==== Relay server or API

* Fixed: old rudder-node-to-relay fails to redirect to new one
    (https://issues.rudder.io/issues/17566[#17566])

==== Web - Config management

* Fixed: Multiple problems with inherited (group, node) properties
    (https://issues.rudder.io/issues/17547[#17547])
* Fixed: Property error message for group with parent group
    (https://issues.rudder.io/issues/17549[#17549])
* Fixed: error in webapp log after upgrade to 6.1-rc1
    (https://issues.rudder.io/issues/17555[#17555])

==== Web - Technique editor

* Fixed: Allow to regenerate generic methods when there is a new one
    (https://issues.rudder.io/issues/17568[#17568])
* Fixed: No techniques in technique editor after upgrade from 5.0.18 to 6.1-rc1 on debian9
    (https://issues.rudder.io/issues/17572[#17572])
* Fixed: GM documentation is not rendered anymore
    (https://issues.rudder.io/issues/17563[#17563])

==== Rudder language

* Fixed: documentation quick update
    (https://issues.rudder.io/issues/17583[#17583])

==== Web - UI & UX

* Fixed: Plugin names are not displayed
    (https://issues.rudder.io/issues/17544[#17544])
* Fixed: Broken appearance of hover details in node details
    (https://issues.rudder.io/issues/17553[#17553])
* Fixed: Group property inherited tooltip is not visible
    (https://issues.rudder.io/issues/17546[#17546])

==== System techniques

* Fixed: rudder agent reset fails on root server
    (https://issues.rudder.io/issues/17580[#17580])

==== Agent

* Fixed: rudder agent run should not always return ok when there is no log
    (https://issues.rudder.io/issues/17571[#17571])
* Fixed: rudder agent stop displays the list of service event when quiet is required
    (https://issues.rudder.io/issues/17561[#17561])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.rc1 (2020-05-28)

=== Changes

==== Documentation

* Add a banner on the docs of non-released/deprecated versions
    (https://issues.rudder.io/issues/17485[#17485])
* Small fixes in variables page
    (https://issues.rudder.io/issues/17353[#17353])
* Add Branding endpoints in API documentation
    (https://issues.rudder.io/issues/17437[#17437])

==== Packaging

* Strip rust release binaries
    (https://issues.rudder.io/issues/14697[#14697])
* Use cargo-deny to replace cargo-audit
    (https://issues.rudder.io/issues/17308[#17308])

==== Architecture - Internal libs

* Add a feature switch for rudder-lang test loop
    (https://issues.rudder.io/issues/17412[#17412])

==== Rudder language

* improve documentation coverage
    (https://issues.rudder.io/issues/17148[#17148])
* update reserved keywords list
    (https://issues.rudder.io/issues/17355[#17355])
* add contributing documentation
    (https://issues.rudder.io/issues/17289[#17289])

==== Relay server or API

* Update relayd dependencies to remove unmaintained "spin" crate
    (https://issues.rudder.io/issues/17384[#17384])

==== Web - UI & UX

* Improve notification display in Rudder
    (https://issues.rudder.io/issues/17383[#17383])

==== API

* Missing info about if a node is a relay in API and capabilities need to to in management technologie
    (https://issues.rudder.io/issues/17367[#17367])

==== Generic methods

* move all abort bundle in a dedicated lib file under 20_cfe_basics
    (https://issues.rudder.io/issues/17519[#17519])
* Allow forcing a "None" component in reporting
    (https://issues.rudder.io/issues/17095[#17095])

==== Generic methods - File Management

* Improve Augeas generic methods documentation
    (https://issues.rudder.io/issues/17464[#17464])
* Improve Augeas generic methods documentation
    (https://issues.rudder.io/issues/17464[#17464])

==== Technique editor - UI/UX

* Keep the original name of a Generic Method displayed
    (https://issues.rudder.io/issues/16937[#16937])

=== Bug fixes

==== Packaging

* Fixed: when upgrading to 6.1, ldap indexing should be normal and not quick
    (https://issues.rudder.io/issues/17532[#17532])
* Fixed: Missing context on relayd binary on CentOS7
    (https://issues.rudder.io/issues/17522[#17522])
* Fixed: Apache must be restarted after acl change in rudder-init
    (https://issues.rudder.io/issues/17515[#17515])
* Fixed: apache acl are empty after installation
    (https://issues.rudder.io/issues/17495[#17495])
* Fixed: #17395 should not be in 6.1
    (https://issues.rudder.io/issues/17474[#17474])
* Fixed: Warn users if scale-out-relay plugin is not installed when promoting node through script
    (https://issues.rudder.io/issues/17429[#17429])
* Fixed: cf-agent writes a lot of times to cf_lock db
    (https://issues.rudder.io/issues/17336[#17336])
* Fixed: Python scripts on rhel7 are set to use python3 which is not available
    (https://issues.rudder.io/issues/17433[#17433])
* Fixed: Missing dependencies between server services
    (https://issues.rudder.io/issues/17402[#17402])
* Fixed: Error while upgrading rudder from 6.0.5 to 6.1 nightly on debian
    (https://issues.rudder.io/issues/17397[#17397])
* Fixed: SELinux policy for technique editor is not applied anymore after upgrade on RHEL/Centos server
    (https://issues.rudder.io/issues/17395[#17395])
* Fixed: We use the "service" command (on CentOS7) do not not depend on the package providing it
    (https://issues.rudder.io/issues/17386[#17386])
* Fixed: Missing dependency on iproute2 making rudder-init fails on minimal install
    (https://issues.rudder.io/issues/17356[#17356])
* Fixed: Remote-run does not work anymore with SELinux
    (https://issues.rudder.io/issues/17516[#17516])
* Fixed: remove progressive output from postinstall
    (https://issues.rudder.io/issues/17525[#17525])
* Fixed: Upgrading Rudder from 5.0.18 to 6.1-nightly does not update techniques
    (https://issues.rudder.io/issues/17313[#17313])
* Fixed: Allow httpd to serve policy files for windows
    (https://issues.rudder.io/issues/17488[#17488])

==== Plugins integration

* Fixed: add rudder-synchonize within Rudder
    (https://issues.rudder.io/issues/17345[#17345])

==== Agent

* Fixed: Debug script is broken in 6.0
    (https://issues.rudder.io/issues/17380[#17380])
* Fixed: remove progressive output from agent check
    (https://issues.rudder.io/issues/17526[#17526])
* Fixed: Add doc about return codes to agent man page
    (https://issues.rudder.io/issues/17281[#17281])

==== Performance and scalability

* Fixed: Agent consuming lots of IO and resources at each run
    (https://issues.rudder.io/issues/17371[#17371])
* Fixed: when running cf-promises, list-compatible-inputs is ran 8 times
    (https://issues.rudder.io/issues/17481[#17481])

==== Documentation

* Fixed: Inconsistent commands for service management
    (https://issues.rudder.io/issues/17529[#17529])
* Fixed: Images from private plugins are not visible
    (https://issues.rudder.io/issues/17498[#17498])
* Fixed: wrong url to download.rudder.io on 6.1
    (https://issues.rudder.io/issues/17484[#17484])
* Fixed: Broken links in docs
    (https://issues.rudder.io/issues/17389[#17389])
* Fixed: Add explanation to setup technique editor in development environement in 6.1
    (https://issues.rudder.io/issues/17502[#17502])
* Fixed: Missing validated user endpoints in change validation api doc
    (https://issues.rudder.io/issues/17434[#17434])

==== Web - Config management

* Fixed: error when a technique with a directive attached change in 6.1 blocks all technique updates
    (https://issues.rudder.io/issues/17523[#17523])
* Fixed: A repaired in system policies should not be seen as a problem for warning display in nodes list
    (https://issues.rudder.io/issues/17521[#17521])
* Fixed: Inherited properties don't appear anymore
    (https://issues.rudder.io/issues/17496[#17496])
* Fixed: Global parameter which are a comment string are ignored
    (https://issues.rudder.io/issues/17491[#17491])
* Fixed: Ignored node lead to an error log during generation
    (https://issues.rudder.io/issues/17441[#17441])
* Fixed: Ignored node lead to an error log during generation
    (https://issues.rudder.io/issues/17441[#17441])
* Fixed: We can't choose between string and json for global parameters
    (https://issues.rudder.io/issues/17325[#17325])
* Fixed: err17: can not update attribute in parameter
    (https://issues.rudder.io/issues/17396[#17396])

==== Miscellaneous

* Fixed: When no User rules are defined on a node, compliance tab on node details shows an error 
    (https://issues.rudder.io/issues/17527[#17527])
* Fixed: add debug to makefile
    (https://issues.rudder.io/issues/17191[#17191])
* Fixed: Fail password confirmation in BCrypt lead to an user with empty password in file
    (https://issues.rudder.io/issues/17424[#17424])

==== Web - Nodes & inventories

* Fixed: inventory watcher should ignore uuid.hive file
    (https://issues.rudder.io/issues/17507[#17507])
* Fixed: Change message in case of udefined certificate for a node
    (https://issues.rudder.io/issues/17487[#17487])
* Fixed: Purge of unreferenced software may still fail on very large system
    (https://issues.rudder.io/issues/17176[#17176])
* Fixed: Add log about node group update failure because of inconsistency
    (https://issues.rudder.io/issues/17421[#17421])
* Fixed: Group property UX is unclear regarding saving
    (https://issues.rudder.io/issues/17312[#17312])
* Fixed: Some inventories are not correctly noticed by inotify file watcher
    (https://issues.rudder.io/issues/15422[#15422])
* Fixed: Inventory upload is not distributed uniformly
    (https://issues.rudder.io/issues/7290[#7290])

==== Web - Maintenance

* Fixed: Nashorn deprecation should be "info" level
    (https://issues.rudder.io/issues/17524[#17524])
* Fixed: Parameters are not restored from archive
    (https://issues.rudder.io/issues/17457[#17457])
* Fixed: Webapp block at start on inventory processing
    (https://issues.rudder.io/issues/17482[#17482])
* Fixed: Historization of node count reports wrong value for pending nodes
    (https://issues.rudder.io/issues/17372[#17372])

==== Web - UI & UX

* Fixed: When adding tags, if anything is wrong in the directive form, all unsaved tags are wiped out
    (https://issues.rudder.io/issues/15557[#15557])
* Fixed: OS logo is missing in summary node
    (https://issues.rudder.io/issues/16454[#16454])
* Fixed: Move "System status" tab before technical logs
    (https://issues.rudder.io/issues/17486[#17486])
* Fixed: Technique doc is not formatted when clicking on technique in tree
    (https://issues.rudder.io/issues/17413[#17413])
* Fixed: Ignored (disabled) nodes are show as enabled in details
    (https://issues.rudder.io/issues/17440[#17440])
* Fixed: Separate system rules from user-defined rules in node compliance display
    (https://issues.rudder.io/issues/17427[#17427])
* Fixed: Missing information that markdown is supported for technique documentation
    (https://issues.rudder.io/issues/17415[#17415])

==== Architecture - Refactoring

* Fixed: Build broke in 6.1 due to faulty merge
    (https://issues.rudder.io/issues/17490[#17490])

==== Web - Compliance & node report

* Fixed: Error log about duplicates entries when saving node compliance levels
    (https://issues.rudder.io/issues/17410[#17410])

==== Relay server or API

* Fixed: Ignore invalid hash in nodeslist
    (https://issues.rudder.io/issues/17458[#17458])
* Fixed: Inventories from new nodes should be sent using the "rudder" password and not generated one
    (https://issues.rudder.io/issues/17416[#17416])

==== System integration

* Fixed: rudder package command fails when not run from a terminal
    (https://issues.rudder.io/issues/17453[#17453])

==== API

* Fixed: API documentation on Rules is missing explaination on how to update rule category
    (https://issues.rudder.io/issues/17409[#17409])
* Fixed: Bad JSON answer for api PUT /rules
    (https://issues.rudder.io/issues/17388[#17388])

==== Architecture - Internal libs

* Fixed: Stacktrace in test introduce in #17341
    (https://issues.rudder.io/issues/17411[#17411])

==== Rudder language

* Fixed: translate should not use hardcoded path for libraries
    (https://issues.rudder.io/issues/17252[#17252])
* Fixed: fix compilation failure
    (https://issues.rudder.io/issues/17405[#17405])

==== System techniques

* Fixed: Error when setting classes for agent capabilities
    (https://issues.rudder.io/issues/17480[#17480])
* Fixed: properties loading needs to be done in a common bundle
    (https://issues.rudder.io/issues/17478[#17478])

==== Techniques

* Fixed: Rsync commands for shared files are broken
    (https://issues.rudder.io/issues/17468[#17468])

==== Web - Technique editor

* Fixed: Modifying a method parameter does not trigger the save button
    (https://issues.rudder.io/issues/17494[#17494])
* Fixed: Technique description is displayed two times in the technique editor
    (https://issues.rudder.io/issues/17393[#17393])
* Fixed: Category for new technique are not sorted
    (https://issues.rudder.io/issues/17414[#17414])
* Fixed: Technique diverge popup when comming back to a techniques because of a change of category
    (https://issues.rudder.io/issues/17400[#17400])
* Fixed: Popup saying that technique change still happens in 6.1
    (https://issues.rudder.io/issues/17319[#17319])

==== Technique editor - Techniques

* Fixed: Move Markdown message in icon tooltip
    (https://issues.rudder.io/issues/17503[#17503])

==== Generic methods

* Fixed: ncf_def should be bundle common
    (https://issues.rudder.io/issues/17477[#17477])
* Fixed: remove non-rudder logger from ncf
    (https://issues.rudder.io/issues/17354[#17354])

==== Technique editor - API

* Fixed: techniques files are parsed twice
    (https://issues.rudder.io/issues/17425[#17425])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.beta3 (2020-05-11)

=== Changes

==== Documentation

* Documentation for group properties
    (https://issues.rudder.io/issues/17282[#17282])

==== Web - Config management

* Prevent removal of 'system' global and group properties
    (https://issues.rudder.io/issues/17227[#17227])

==== Packaging

* Add auto reload of welcome page
    (https://issues.rudder.io/issues/17317[#17317])

=== Bug fixes

==== Packaging

* Fixed: strip calls fail on aix
    (https://issues.rudder.io/issues/17365[#17365])
* Fixed: rpm build logs are huge
    (https://issues.rudder.io/issues/17360[#17360])
* Fixed: 6.1 fails to build on aix
    (https://issues.rudder.io/issues/17357[#17357])
* Fixed: create migration script for LDAP indexes
    (https://issues.rudder.io/issues/17215[#17215])
* Fixed: create migration script for LDAP indexes
    (https://issues.rudder.io/issues/17215[#17215])
* Fixed: rudder fails to build in 6.0
    (https://issues.rudder.io/issues/17339[#17339])
* Fixed: Package cache is updated at each run
    (https://issues.rudder.io/issues/17337[#17337])
* Fixed: cf-agent writes a lot of times to performance db
    (https://issues.rudder.io/issues/17335[#17335])
* Fixed: At relay install time, if the domain is not defined the server certificate can not be issued
    (https://issues.rudder.io/issues/17332[#17332])

==== Documentation

* Fixed: Move variables doc into "usge" category
    (https://issues.rudder.io/issues/17368[#17368])
* Fixed: improve documentation on "default" for variable to state that it should be quoted
    (https://issues.rudder.io/issues/17352[#17352])
* Fixed: Doc about missing uuid.hive at upgrade was not upmerged
    (https://issues.rudder.io/issues/17299[#17299])

==== Web - Compliance & node report

* Fixed: Inconsistant syntax for global parameter in directive incompatible with JSON values
    (https://issues.rudder.io/issues/17350[#17350])
* Fixed: JSON global parameter are inherited as string
    (https://issues.rudder.io/issues/17326[#17326])

==== Technique editor - API

* Fixed: When defining a category for a new technique, the files are not placed on the correct path in the git repo
    (https://issues.rudder.io/issues/17338[#17338])

==== Web - UI & UX

* Fixed: The generic methods documentation is no longer accessible from the technique editor
    (https://issues.rudder.io/issues/17321[#17321])
* Fixed: main parameter of a method is not displayed anymore, and result classes are not ok anymore
    (https://issues.rudder.io/issues/17329[#17329])

==== API

* Fixed: when importing a technique with  /api/internal/techniques, the order of parameters is not respected
    (https://issues.rudder.io/issues/17348[#17348])

==== Web - Config management

* Fixed: Data for reporting plugin are not generated anymore
    (https://issues.rudder.io/issues/17341[#17341])
* Fixed: Property name aren't limited to ascii
    (https://issues.rudder.io/issues/17334[#17334])
* Fixed: Group properties inheritance error when it should not
    (https://issues.rudder.io/issues/17324[#17324])

==== System techniques

* Fixed: Disable sending old reports from relayd
    (https://issues.rudder.io/issues/17349[#17349])

==== Web - Technique editor

* Fixed: Resource manager should talk about saved/unsaved and not commited/not commited
    (https://issues.rudder.io/issues/17328[#17328])

==== Technique editor - UI/UX

* Fixed: Tooltips not showing up
    (https://issues.rudder.io/issues/17333[#17333])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.beta2 (2020-05-04)

=== Changes

==== Documentation

* Document that Rudder servers should not be exposed on the Internet
    (https://issues.rudder.io/issues/17316[#17316])

==== Rudder language

* rename stdlib to resourcelib
    (https://issues.rudder.io/issues/17254[#17254])
* rename stdlib to resourcelib
    (https://issues.rudder.io/issues/17254[#17254])

=== Bug fixes

==== Packaging

* Fixed: jq is not available in the base repositories on SLES15 and should be embedded with the agent package
    (https://issues.rudder.io/issues/17318[#17318])
* Fixed: installing rudder server 6.1.0~beta1 on debian 9 fails
    (https://issues.rudder.io/issues/17280[#17280])
* Fixed: openssl fails to build on aix
    (https://issues.rudder.io/issues/17262[#17262])

==== API

* Fixed: API documentation omits the policymode parameter of directives
    (https://issues.rudder.io/issues/17301[#17301])

==== Web - UI & UX

* Fixed: Page for node not found is too minimalist
    (https://issues.rudder.io/issues/16515[#16515])
* Fixed: RuleID is not trimmed when copied from the GUI
    (https://issues.rudder.io/issues/17290[#17290])

==== Security

* Fixed: exception in ldap search are not correctly caught
    (https://issues.rudder.io/issues/17267[#17267])

==== Documentation

* Fixed: API documentation is lacking of a Json based update of rule/directive
    (https://issues.rudder.io/issues/17292[#17292])

==== Agent

* Fixed: rudder agent run returns exit code 1 when everything is ok
    (https://issues.rudder.io/issues/17268[#17268])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Victor Héry

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 6.1.0.beta1 (2020-04-28)

=== Changes

==== Packaging

* Embed openssl 1.1.1 on every OS
    (https://issues.rudder.io/issues/17233[#17233])
* Do not embed openssl and curl on distribution with a recent openssl
    (https://issues.rudder.io/issues/17231[#17231])
* Replace node-to-relay script from rudder-package
    (https://issues.rudder.io/issues/17217[#17217])
* Replace node-to-relay script from rudder-package
    (https://issues.rudder.io/issues/17217[#17217])
* add jq to rudder agent
    (https://issues.rudder.io/issues/17139[#17139])
* Add systemd hardening config for slapd
    (https://issues.rudder.io/issues/17055[#17055])
* Upgrade Jetty to latest version
    (https://issues.rudder.io/issues/16905[#16905])
* It should be impossible to connect with "admin" password with default config
    (https://issues.rudder.io/issues/16732[#16732])
* Display Rust tooling version in build
    (https://issues.rudder.io/issues/16969[#16969])
* Use SPDX headers in relay
    (https://issues.rudder.io/issues/16834[#16834])

==== Performance and scalability

* review index for LDAP
    (https://issues.rudder.io/issues/17128[#17128])
* Do not compute dynamic groups if nothing changed in LDAP
    (https://issues.rudder.io/issues/17237[#17237])
* By default we should not archive reports
    (https://issues.rudder.io/issues/16931[#16931])
* Don't replace RudderUniqueId in generated policies with a replace, but with StringTemplate
    (https://issues.rudder.io/issues/16856[#16856])

==== Agent

* Make agents preserve perm on copy to keep previous behavior (patch for CFEngine 3.15)
    (https://issues.rudder.io/issues/17124[#17124])
* Update agent to CFEngine 3.15.1
    (https://issues.rudder.io/issues/16734[#16734])
* Add a command to set policy server on agents
    (https://issues.rudder.io/issues/16529[#16529])
* Add support for HTTP reporting in changes-only mode
    (https://issues.rudder.io/issues/17153[#17153])

==== Documentation

* Improve doc related to plugins/subscriptions
    (https://issues.rudder.io/issues/17144[#17144])
* Update doc for initial user account
    (https://issues.rudder.io/issues/17174[#17174])
* Prepare doc for 6.1
    (https://issues.rudder.io/issues/17130[#17130])
* Update content of docs menus
    (https://issues.rudder.io/issues/17033[#17033])
* Improve accessibility of documentation site's menu
    (https://issues.rudder.io/issues/16984[#16984])
* Update get-started for 6.0
    (https://issues.rudder.io/issues/16986[#16986])
* Update screenshots in "Install relay server" section
    (https://issues.rudder.io/issues/16945[#16945])
* Update screenshot in the documentation
    (https://issues.rudder.io/issues/16752[#16752])
* Add upgrade note to document how to switch from previous hash function to BCrypt
    (https://issues.rudder.io/issues/16729[#16729])
* Add Bcrypt support informations 
    (https://issues.rudder.io/issues/16724[#16724])
* Adapt doc for 6.1
    (https://issues.rudder.io/issues/15846[#15846])
* Add promote to relay endpoint in API documentation
    (https://issues.rudder.io/issues/17162[#17162])
* Clarify webapp contributing documentation
    (https://issues.rudder.io/issues/16914[#16914])
* Add spdx licenses for api doc
    (https://issues.rudder.io/issues/16883[#16883])
* Documentation is outdated for development
    (https://issues.rudder.io/issues/16932[#16932])

==== Web - Config management

* Initialize `rudder` global parameter to default value at boot
    (https://issues.rudder.io/issues/17251[#17251])
* Display node properties inherited from group/global
    (https://issues.rudder.io/issues/17173[#17173])
* Display technique description in directive form as markdown
    (https://issues.rudder.io/issues/17238[#17238])
* Rudder should be able to read techniques by itself and not rely on legacy ncf rest api
    (https://issues.rudder.io/issues/17133[#17133])
* Add JSON support for global parameters
    (https://issues.rudder.io/issues/16301[#16301])
* Group properties
    (https://issues.rudder.io/issues/16347[#16347])

==== Architecture - Refactoring

* Update some libraries for 6.1
    (https://issues.rudder.io/issues/17224[#17224])
* Dead code: com.normation.rudder.domain.system
    (https://issues.rudder.io/issues/17189[#17189])
* Clarify code of rollback events parsing
    (https://issues.rudder.io/issues/16603[#16603])

==== Web - UI & UX

* Update links in login page
    (https://issues.rudder.io/issues/17218[#17218])
* Beautify banner warning for expired plugin
    (https://issues.rudder.io/issues/16910[#16910])
* Display a warning in place of login form if no user are defined
    (https://issues.rudder.io/issues/17070[#17070])
* Display directive tags inside Compliance tables
    (https://issues.rudder.io/issues/16869[#16869])
* Display tags when listing directives
    (https://issues.rudder.io/issues/16346[#16346])
* Adapt user configuration file to remove default admin credentials
    (https://issues.rudder.io/issues/16731[#16731])
* Update users configuration file to add BCrypt support
    (https://issues.rudder.io/issues/16730[#16730])
* Update UI for group page to new template
    (https://issues.rudder.io/issues/16473[#16473])

==== API

* Add Usermanagement endpoints in API documentation
    (https://issues.rudder.io/issues/17164[#17164])
* Be able to save in LDAP a Policy Server Target
    (https://issues.rudder.io/issues/16906[#16906])
* Be able to save in LDAP a Policy Server Target
    (https://issues.rudder.io/issues/16906[#16906])

==== System integration

* Historize node count information
    (https://issues.rudder.io/issues/17161[#17161])

==== Miscellaneous

* Missing LDAP write operations to promote a node to relay
    (https://issues.rudder.io/issues/17112[#17112])
* Missing LDAP write operations to promote a node to relay
    (https://issues.rudder.io/issues/17112[#17112])

==== Plugins integration

* Add "technical preview" status for plugins
    (https://issues.rudder.io/issues/17093[#17093])

==== Rudder language

* make translate methods use stdlib rather than regexes
    (https://issues.rudder.io/issues/17115[#17115])
* logging adjustments for integration test loop
    (https://issues.rudder.io/issues/17114[#17114])
* test loop integration
    (https://issues.rudder.io/issues/16902[#16902])
* Full review of rudder-lang suported systems
    (https://issues.rudder.io/issues/16974[#16974])
* Rework os class translation into rudder-lang
    (https://issues.rudder.io/issues/17052[#17052])
* Implement metadata for enums
    (https://issues.rudder.io/issues/17049[#17049])
* Load all files from stdlib automatically
    (https://issues.rudder.io/issues/17047[#17047])
* Replace SourceList with a typed arena
    (https://issues.rudder.io/issues/17046[#17046])
* Cleanup rudder-lang tester
    (https://issues.rudder.io/issues/17010[#17010])
* non global items can have duplicate names
    (https://issues.rudder.io/issues/16992[#16992])
* Add enum aliases in rudder lang
    (https://issues.rudder.io/issues/16972[#16972])
* Add range to enum expressions
    (https://issues.rudder.io/issues/16928[#16928])
* rudder-lang packaging changes
    (https://issues.rudder.io/issues/16967[#16967])
* rudder-lang packaging update
    (https://issues.rudder.io/issues/16886[#16886])
* Fix clippy warnings in rudder-lang
    (https://issues.rudder.io/issues/16943[#16943])
* Improve compiler options
    (https://issues.rudder.io/issues/16938[#16938])
* Prepare documentation layout for rudder-lang
    (https://issues.rudder.io/issues/16934[#16934])
* Prepare documentation layout for rudder-lang
    (https://issues.rudder.io/issues/16934[#16934])
* Reimplement enums
    (https://issues.rudder.io/issues/16924[#16924])
* tests changes to prepare rudder-lang integration
    (https://issues.rudder.io/issues/16846[#16846])
* rl add cfengine_core to libs, which declares global variables
    (https://issues.rudder.io/issues/16807[#16807])
* rl add an optional path for compilation and translation
    (https://issues.rudder.io/issues/16775[#16775])
* rl allow splitted global variables declaration
    (https://issues.rudder.io/issues/16774[#16774])
* rl enchance variables handling 
    (https://issues.rudder.io/issues/16728[#16728])
* rl enchance variables handling 
    (https://issues.rudder.io/issues/16728[#16728])
* rl generate enum mappings from os tree
    (https://issues.rudder.io/issues/16717[#16717])
* rl improve output fidelity of generated cf files
    (https://issues.rudder.io/issues/16658[#16658])
* rl add non terminating errors and related integration tests
    (https://issues.rudder.io/issues/16616[#16616])
* format entire rudderlang code according to style guidelines 
    (https://issues.rudder.io/issues/16614[#16614])

==== Web - Nodes & inventories

* Agent capabilities in inventory are not parsed
    (https://issues.rudder.io/issues/12109[#12109])

==== Relay server or API

* Add support for parsing HTTP logs from Windows
    (https://issues.rudder.io/issues/17073[#17073])

==== Security

* Allow content to be shown in iframe
    (https://issues.rudder.io/issues/17072[#17072])
* We should use BCrypt by default for storing user's local password
    (https://issues.rudder.io/issues/16674[#16674])
* Add a command to generate user accounts after installation
    (https://issues.rudder.io/issues/16620[#16620])

==== Architecture - Internal libs

* Upgrade to ZIO RC18
    (https://issues.rudder.io/issues/16892[#16892])

==== Techniques

* Delete deprecated techniques, and deprecate techniques in 6.1
    (https://issues.rudder.io/issues/17159[#17159])

==== Generic methods - Package Management

* Make the package_module bodies configurable
    (https://issues.rudder.io/issues/9110[#9110])

==== Technique editor - UI/UX

* Define the category of a technique
    (https://issues.rudder.io/issues/16345[#16345])
* Add description of technique parameters
    (https://issues.rudder.io/issues/17239[#17239])
* Improve UX for technique resource files
    (https://issues.rudder.io/issues/17078[#17078])

==== Generic methods

* Sync stdlib with 3.15.1
    (https://issues.rudder.io/issues/17229[#17229])
* Add verbosity level in the rudder logger
    (https://issues.rudder.io/issues/15126[#15126])

==== Web - Technique editor

* Add fully qualified name of technique parameter
    (https://issues.rudder.io/issues/17029[#17029])

=== Bug fixes

==== Packaging

* Fixed: Our agent package contains CFEngine systemd units
    (https://issues.rudder.io/issues/16790[#16790])
* Fixed: We need to stop apache before removing ncf-api-venv user
    (https://issues.rudder.io/issues/17198[#17198])
* Fixed: rudderlang makefile integration
    (https://issues.rudder.io/issues/17187[#17187])
* Fixed: package fails to build jq
    (https://issues.rudder.io/issues/17175[#17175])
* Fixed: jq fails to build on old distro
    (https://issues.rudder.io/issues/17169[#17169])
* Fixed: make clean should not remove source in rudder-packages
    (https://issues.rudder.io/issues/17140[#17140])
* Fixed: rudder-webapp fails to build on 6.1
    (https://issues.rudder.io/issues/17125[#17125])
* Fixed: After server install, the "no user" login page link to a 404 documentation page
    (https://issues.rudder.io/issues/17163[#17163])
* Fixed: After server install, the "no user" login page link to a 404 documentation page
    (https://issues.rudder.io/issues/17163[#17163])

==== Agent

* Fixed: Update embedded openssl version to 1.1.1g
    (https://issues.rudder.io/issues/17178[#17178])
* Fixed: When in changes-only and nothing needs to be sent an empty invalid report is sent
    (https://issues.rudder.io/issues/17193[#17193])
* Fixed: Restart the webapp after creating a user
    (https://issues.rudder.io/issues/17190[#17190])
* Fixed: HTTP report PUT prints useless messages at the end of the run
    (https://issues.rudder.io/issues/16112[#16112])

==== Documentation

* Fixed: Add a link to upgrade notes at the beginning of each upgrade doc page
    (https://issues.rudder.io/issues/17219[#17219])
* Fixed: Fix 6.1 doc build
    (https://issues.rudder.io/issues/17207[#17207])
* Fixed: Fix links in 6.1 homepage
    (https://issues.rudder.io/issues/17200[#17200])
* Fixed: Plugins menu in the documentation should be in alphabetical order
    (https://issues.rudder.io/issues/16808[#16808])
* Fixed: Add Create Node endpoint in API documentation
    (https://issues.rudder.io/issues/17183[#17183])

==== Web - Maintenance

* Fixed: Rudder 6.1 does not start anymore
    (https://issues.rudder.io/issues/17228[#17228])
* Fixed: Rudder 6.1 does not start anymore
    (https://issues.rudder.io/issues/17228[#17228])

==== Web - Nodes & inventories

* Fixed: when a node is removed from a dynamc group, it log "adding nothing, removing nothing"
    (https://issues.rudder.io/issues/17220[#17220])
* Fixed: Concurrent access to node info cache cause exception to be thrown when accessing cache content
    (https://issues.rudder.io/issues/17172[#17172])
* Fixed: Search does not work in group criteria
    (https://issues.rudder.io/issues/17203[#17203])

==== Web - Config management

* Fixed: TechniqueVersion ordering algorithm is incorrect
    (https://issues.rudder.io/issues/17157[#17157])
* Fixed: cannot add directives to a rules
    (https://issues.rudder.io/issues/17099[#17099])
* Fixed: Don't fail generation for HTTPS only reports with  DSC/6.1
    (https://issues.rudder.io/issues/17085[#17085])

==== Performance and scalability

* Fixed: chmod at the end of policy generation is painfully slow
    (https://issues.rudder.io/issues/17214[#17214])

==== Web - UI & UX

* Fixed: rudder version is wrong in the login page
    (https://issues.rudder.io/issues/17201[#17201])
* Fixed: Not all tags have the same appearance
    (https://issues.rudder.io/issues/16897[#16897])

==== Architecture - Refactoring

* Fixed: Remove warning and "Inconsistance" typo compilation error
    (https://issues.rudder.io/issues/17156[#17156])
* Fixed: Inconsistency error is mispelled
    (https://issues.rudder.io/issues/17110[#17110])

==== Security

* Fixed: cannot login in Rudder 6.1
    (https://issues.rudder.io/issues/17108[#17108])

==== Rudder language

* Fixed: Compilation output file is not generated when input file is a path
    (https://issues.rudder.io/issues/17094[#17094])
* Fixed: translation into rudder-lang doesn't handle any class
    (https://issues.rudder.io/issues/17075[#17075])
* Fixed: Use Pin tu fix source code address
    (https://issues.rudder.io/issues/16998[#16998])
* Fixed: fix generation of parameters and conditions from cfengine files
    (https://issues.rudder.io/issues/16878[#16878])
* Fixed: rl compile fix enum logical expressions
    (https://issues.rudder.io/issues/16713[#16713])
* Fixed: rl translate add exception for kernel_module resource parsing
    (https://issues.rudder.io/issues/16711[#16711])

==== System techniques

* Fixed: Runlog catchup does not work on linux
    (https://issues.rudder.io/issues/17192[#17192])

==== Technique editor - UI/UX

* Fixed: Text &  Boxes jump when displaying missing inputs
    (https://issues.rudder.io/issues/16235[#16235])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

and rc versions are listed below for convenience.
