= Change logs for Rudder 8.3==  Rudder 8.3.0.alpha1 (2025-01-23)

==  Rudder 8.3.3 (2025-07-17)

=== Changes


==== Documentation

* Documentation for passwords should be explicit about password hashes compatibility
    (https://issues.rudder.io/issues/27235[#27235])

==== Generic methods

* Add a generic method to retrieve more than one file shared by other nodes
    (https://issues.rudder.io/issues/25877[#25877])

==== Web - UI & UX

* License setup should update the list of plugins
    (https://issues.rudder.io/issues/27005[#27005])

==== Miscellaneous

* Change request count badge needs more contrast on hover
    (https://issues.rudder.io/issues/27027[#27027])

==== Agent

* Add a new agent command to reset package cache
    (https://issues.rudder.io/issues/26874[#26874])

=== Bug fixes

==== Packaging

* Fixed: Incorrect java dependency on AL2023
    (https://issues.rudder.io/issues/27277[#27277])
* Fixed: Update curl version to 8.14.1 & openssl to 3.0.16
    (https://issues.rudder.io/issues/27072[#27072])
* Fixed: libpq may be missing on rudder-relay on alma8
    (https://issues.rudder.io/issues/26654[#26654])

==== Agent

* Fixed: Define the "suse" system condition on SLED systems
    (https://issues.rudder.io/issues/27082[#27082])
* Fixed: rudder agent check complains “egrep: warning: egrep is obsolescent; using grep -E”
    (https://issues.rudder.io/issues/26810[#26810])
* Fixed: rudder agent check doesn't reenable cf-execd
    (https://issues.rudder.io/issues/27108[#27108])

==== Web - Config management

* Fixed: Score service does not really clean unmanaged score, it only removes them from cache but keeps in database
    (https://issues.rudder.io/issues/26900[#26900])
* Fixed: Misleading comments about RUDDER_POLICIES_DIRECTORY in hook template
    (https://issues.rudder.io/issues/27232[#27232])
* Fixed: Many diffs no longer display in event logs 
    (https://issues.rudder.io/issues/27114[#27114])

==== Web - UI & UX

* Fixed: "Directive" should not be displayed in each directive title, it is redundant
    (https://issues.rudder.io/issues/23870[#23870])
* Fixed: Redundant "Compliance" title in the "Compliance" tab inside a group detail
    (https://issues.rudder.io/issues/24507[#24507])
* Fixed: Add a global warning and alert banner in user management with unsafe hashes
    (https://issues.rudder.io/issues/27200[#27200])
* Fixed: When editing a long textarea browser scrolls to top
    (https://issues.rudder.io/issues/22355[#22355])
* Fixed: Iterator items that have exactly the same values are considered to be a single object
    (https://issues.rudder.io/issues/27131[#27131])
* Fixed: Fix auth method display in user management page
    (https://issues.rudder.io/issues/27123[#27123])
* Fixed: Technical logs date pickers are misaligned in UI
    (https://issues.rudder.io/issues/27050[#27050])
* Fixed: User with only  “Inventory” rights has a notification error when changing tab
    (https://issues.rudder.io/issues/26952[#26952])
* Fixed: Sometimes, property values that are too long push the action buttons out of the window
    (https://issues.rudder.io/issues/26991[#26991])

==== Plugins management

* Fixed: Plugins get silently disabled when number of licensed nodes is exceeded
    (https://issues.rudder.io/issues/27175[#27175])

==== Web - Compliance & node report

* Fixed: Node compliance persistence fails when all reports from sysevents are cleaned
    (https://issues.rudder.io/issues/27180[#27180])
* Fixed: Rule detail compliance has no indication that it is loading
    (https://issues.rudder.io/issues/26711[#26711])

==== Generic methods

* Fixed:  Add windows support to the Audit from osquery generic method
    (https://issues.rudder.io/issues/27228[#27228])
* Fixed: When the component value of a method is too long, the reporting can be missing
    (https://issues.rudder.io/issues/27167[#27167])
* Fixed: Add Windows support to the Audit from osquery generic method
    (https://issues.rudder.io/issues/27227[#27227])

==== Miscellaneous

* Fixed: Deleting a running Update Campaign does not remove associated system policies
    (https://issues.rudder.io/issues/27184[#27184])
* Fixed: History API ignores 'before' and 'order' keywords
    (https://issues.rudder.io/issues/23507[#23507])
* Fixed: Hundreds of “n/a” when iterator used in a simple package installation technique
    (https://issues.rudder.io/issues/26814[#26814])
* Fixed: Event logs rollback does not work anymore
    (https://issues.rudder.io/issues/27051[#27051])

==== Web - Technique editor

* Fixed: Remove old OSes from technique editor conditions
    (https://issues.rudder.io/issues/27192[#27192])
* Fixed: Technique editor Operating System condition RHEL generates wrong “redhat” condition
    (https://issues.rudder.io/issues/27144[#27144])
* Fixed: Technique editor conditions do not differentiate between Alma/Rocky and CentOS
    (https://issues.rudder.io/issues/26983[#26983])

==== Security

* Fixed: Security update of webapp dependencies 
    (https://issues.rudder.io/issues/27199[#27199])
* Fixed: Bad logger used for authentication error
    (https://issues.rudder.io/issues/27090[#27090])
* Fixed: Inventory role allows to get system status detailed logs and technical logs 
    (https://issues.rudder.io/issues/27040[#27040])

==== Server components

* Fixed: Do not send CA list on client authentication
    (https://issues.rudder.io/issues/27156[#27156])

==== Architecture - Code maintenance

* Fixed: Bad package for TestCheckUsersFile
    (https://issues.rudder.io/issues/27152[#27152])
* Fixed: ReportType json serialization in base is incorrect
    (https://issues.rudder.io/issues/27035[#27035])

==== Module - augeas

* Fixed: Improve error messages and reporting in augeas module
    (https://issues.rudder.io/issues/27028[#27028])

==== Web - Maintenance

* Fixed: Rudder webapp migration create table ScoreDetails with message constraint
    (https://issues.rudder.io/issues/26976[#26976])

==== Documentation

* Fixed: Incorrect HTTP method documentation for the usermanagement/users/reload endpoint
    (https://issues.rudder.io/issues/26948[#26948])
* Fixed: OpenAPI doc for plugin infos endpoint has a warning on details field
    (https://issues.rudder.io/issues/27001[#27001])

==== Architecture - Dependencies

* Fixed: Postgresql has (non impacting) CVE-2025-49146
    (https://issues.rudder.io/issues/27079[#27079])

==== Web - Nodes & inventories

* Fixed: Error when parsing date for last user loggin awaited format is EEE MMM dd HH:mm
    (https://issues.rudder.io/issues/27067[#27067])

==== Techniques

* Fixed: Creating a technique with resources in folders can break the technique library
    (https://issues.rudder.io/issues/26912[#26912])
* Fixed: Merge the powershell files of built-in techniques together
    (https://issues.rudder.io/issues/27170[#27170])
* Fixed: “SSH server” technique proposes deprecated “Use privilege separation” option
    (https://issues.rudder.io/issues/26938[#26938])

==== System techniques

* Fixed: Overwrite the /var/rudder/lib/ssl/policy_server.pem when it is a symlink
    (https://issues.rudder.io/issues/27267[#27267])

==== Performance and scalability

* Fixed: rudder agent update is really slow
    (https://issues.rudder.io/issues/26384[#26384])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Nicolas Pawlak

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.3.2 (2025-06-04)

=== Changes


==== Packaging

* RHEL 10 Rudder server should depend on java 21
    (https://issues.rudder.io/issues/27025[#27025])
* Add packages dependencies for RHEL10
    (https://issues.rudder.io/issues/26995[#26995])

==== Miscellaneous

* Remove apr-util-bdb from relay dependencies on RHEL10
    (https://issues.rudder.io/issues/27017[#27017])

==== Module - augeas

* Document the augeas module
    (https://issues.rudder.io/issues/26919[#26919])

==== Web - Nodes & inventories

* Store agent-version as a dedicated field
    (https://issues.rudder.io/issues/26918[#26918])

==== Architecture - Code maintenance

* Add a logger for rudderc gm lib command
    (https://issues.rudder.io/issues/26922[#26922])
* Prepare EventActor serialization for scala3
    (https://issues.rudder.io/issues/26898[#26898])

==== Web - UI & UX

* Adjust the bootstrap theme dark color used for checkbox buttons
    (https://issues.rudder.io/issues/26826[#26826])

=== Bug fixes

==== Packaging

* Fixed: "Already on 'master'" in postinst logs
    (https://issues.rudder.io/issues/26966[#26966])
* Fixed: rudder server reload-techniques should work even if webapp is stopped
    (https://issues.rudder.io/issues/26897[#26897])

==== System integration

* Fixed: When using an external database, special characters are breaking the password detection
    (https://issues.rudder.io/issues/26432[#26432])

==== Web - Technique editor

* Fixed: Workspace directory is missing when saving a technique
    (https://issues.rudder.io/issues/27026[#27026])

==== Security

* Fixed: Potential XSS vulnerability in radio button in event logs
    (https://issues.rudder.io/issues/27010[#27010])
* Fixed: Nodes page parses URL without escaping which allows XSS
    (https://issues.rudder.io/issues/26997[#26997])
* Fixed: Ensure zip extraction doesn't slip out of its directory
    (https://issues.rudder.io/issues/26954[#26954])
* Fixed: Rollback event log endpoint has the wrong HTTP method
    (https://issues.rudder.io/issues/26973[#26973])
* Fixed: Path traversal in technique categories
    (https://issues.rudder.io/issues/26957[#26957])
* Fixed: Check for path traversal in inventory api
    (https://issues.rudder.io/issues/26944[#26944])
* Fixed: Metadata parsing must use a safe SaxParser to avoid XXE
    (https://issues.rudder.io/issues/26936[#26936])
* Fixed: User management API endpoints require admin privileges
    (https://issues.rudder.io/issues/26925[#26925])

==== API

* Fixed: Update api doc tooling
    (https://issues.rudder.io/issues/26999[#26999])
* Fixed: Debug script API must be a POST with admin write rights
    (https://issues.rudder.io/issues/26945[#26945])

==== Miscellaneous

* Fixed: API account form should not display tenants when full access is selected 
    (https://issues.rudder.io/issues/26980[#26980])

==== Web - UI & UX

* Fixed: When there is too many nodes in groups, we can't change criteria anymore
    (https://issues.rudder.io/issues/26972[#26972])
* Fixed: Number of “nodes in audit mode” wrong on "About" page
    (https://issues.rudder.io/issues/26747[#26747])
* Fixed: User management UI does not display when a user info is a complex JSON object
    (https://issues.rudder.io/issues/26939[#26939])
* Fixed: Plugin successful install can display an error because of service restart
    (https://issues.rudder.io/issues/26940[#26940])
* Fixed: Technique details on built-in technique are wrong
    (https://issues.rudder.io/issues/26860[#26860])
* Fixed: Archive “download as zip” creates backup with wrong name (but right contents)
    (https://issues.rudder.io/issues/26779[#26779])
* Fixed: Groups with special target has clone button but cannot be cloned
    (https://issues.rudder.io/issues/26832[#26832])
* Fixed: User management page no longer displays individual authorizations
    (https://issues.rudder.io/issues/26842[#26842])

==== Web - Nodes & inventories

* Fixed: Remove default root description 
    (https://issues.rudder.io/issues/26878[#26878])

==== Architecture - Code maintenance

* Fixed: Missing visibility change for parameter
    (https://issues.rudder.io/issues/26889[#26889])

==== Web - Maintenance

* Fixed: XML unserialization of ACL is incorrect
    (https://issues.rudder.io/issues/26888[#26888])

==== Techniques

* Fixed: “Users” standard technique : Fails setting secondary groups when already correct.
    (https://issues.rudder.io/issues/26823[#26823])
* Fixed: “Users” standard technique causes “Missing report” on Windows
    (https://issues.rudder.io/issues/26935[#26935])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.3.1 (2025-05-07)

=== Changes


==== Agent

* Add agent version to inventory - windows version
    (https://issues.rudder.io/issues/26835[#26835])
* Add agent version to inventory
    (https://issues.rudder.io/issues/26818[#26818])

==== Documentation

* Set 8.3 docs to final
    (https://issues.rudder.io/issues/26778[#26778])
* "How score are computed" documentation
    (https://issues.rudder.io/issues/26720[#26720])

==== Web - Config management

* Add a "all" keyword for archives export
    (https://issues.rudder.io/issues/26801[#26801])

==== Miscellaneous

* Completly ignore source target of rules when importing an archive
    (https://issues.rudder.io/issues/23998[#23998])

=== Bug fixes

==== Packaging

* Fixed: Agent fails to build without embedded augeas
    (https://issues.rudder.io/issues/26809[#26809])
* Fixed: Backup apache config file put in /
    (https://issues.rudder.io/issues/26678[#26678])

==== Documentation

* Fixed: rudder doc doesn't explain how to change the https port on windows
    (https://issues.rudder.io/issues/26875[#26875])
* Fixed: Remove the generic methods docs fro the reference manual
    (https://issues.rudder.io/issues/26821[#26821])
* Fixed: Correct documentation about Postgresql maintenance
    (https://issues.rudder.io/issues/26699[#26699])

==== Web - UI & UX

* Fixed: Replace Normation in menu by Rudder
    (https://issues.rudder.io/issues/26880[#26880])
* Fixed: Techniques count in dashboard leads to 404 page
    (https://issues.rudder.io/issues/26844[#26844])
* Fixed: User with 'user' role cannot get token status
    (https://issues.rudder.io/issues/26843[#26843])
* Fixed: Number of techniques shows 0 when I have several techniques. They have been imported.
    (https://issues.rudder.io/issues/26061[#26061])
* Fixed: System group description is editable in the UI but cannot be saved
    (https://issues.rudder.io/issues/25374[#25374])
* Fixed: We cannot scroll to the bottom page of all Settings pages
    (https://issues.rudder.io/issues/26648[#26648])
* Fixed: Headers does not scale on table size on search node tab
    (https://issues.rudder.io/issues/26571[#26571])
* Fixed: Sometimes when we click on an element (technique or rule), the whole page reloads
    (https://issues.rudder.io/issues/26106[#26106])

==== Web - Maintenance

* Fixed: Logs filled with similar errors : SQL : la relation « nodelastcompliance » n'existe pas.
    (https://issues.rudder.io/issues/26869[#26869])

==== API

* Fixed: Rest API Error 500 when not authorized
    (https://issues.rudder.io/issues/26852[#26852])

==== Architecture - Code maintenance

* Fixed: Clean up reporting node compliance tables
    (https://issues.rudder.io/issues/26774[#26774])

==== Web - Campaigns

* Fixed: Commit campaign definition in the configuration repository
    (https://issues.rudder.io/issues/22675[#22675])

==== Web - Compliance & node report

* Fixed: When directives are skipped, they are multiplied in the directive tab of the rule
    (https://issues.rudder.io/issues/26712[#26712])
* Fixed: There is no indication that the rule page is loading compliance
    (https://issues.rudder.io/issues/26710[#26710])

==== Relay server or API

* Fixed: Randomize port used in relayd test
    (https://issues.rudder.io/issues/26768[#26768])

==== Security

* Fixed: Compliance right should not give access to techniques and global parameters
    (https://issues.rudder.io/issues/26642[#26642])
* Fixed: Upgrade spring security dependency to correct CVE-2025-22228
    (https://issues.rudder.io/issues/26707[#26707])

==== Miscellaneous

* Fixed: Do not store nodecompliancelevels by default
    (https://issues.rudder.io/issues/26773[#26773])
* Fixed: Services restart fails on RedHat 9 after successful update campaign
    (https://issues.rudder.io/issues/26681[#26681])

==== Web - Technique editor

* Fixed: Can't save technique when modifying a resource file
    (https://issues.rudder.io/issues/26685[#26685])

==== Techniques

* Fixed: aptPackageManagerSettings always produce a warning when run
    (https://issues.rudder.io/issues/26782[#26782])
* Fixed: apt package source technique doesn't support ubuntu24
    (https://issues.rudder.io/issues/26766[#26766])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Nicolas Ecarnot

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.3.0 (2025-04-22)

=== Changes


=== Bug fixes

==== Web - Compliance & node report

* Fixed: User with limited rights gets Ajax error
    (https://issues.rudder.io/issues/26690[#26690])

==== Generic methods

* Fixed: Fix code formatting
    (https://issues.rudder.io/issues/26755[#26755])

==== Security

* Fixed: Vulnerabilities in Rust dependencies
    (https://issues.rudder.io/issues/26753[#26753])

==== Web - Technique editor

* Fixed: Technique loop copy box pastes wrong value
    (https://issues.rudder.io/issues/26650[#26650])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.3.0.rc1 (2025-04-10)

=== Changes


==== Packaging

* Embed augeas everywhere
    (https://issues.rudder.io/issues/26668[#26668])

==== Documentation

* Documentation to manage plugins should mention the new plugins page
    (https://issues.rudder.io/issues/26606[#26606])

==== Module - augeas

* Implement file editions in augeas module
    (https://issues.rudder.io/issues/26619[#26619])
* Add a new generic method for the augeas module
    (https://issues.rudder.io/issues/26430[#26430])

==== Plugins integration

* License error in plugins should link to settings at licence tab
    (https://issues.rudder.io/issues/26633[#26633])

==== Web - UI & UX

* Initial page after Rudder installation should be the license tab at welcome step
    (https://issues.rudder.io/issues/26688[#26688])
* Renaming tab and parameter for licence info in setup page
    (https://issues.rudder.io/issues/26620[#26620])
* Make tabs accessible by URL
    (https://issues.rudder.io/issues/26590[#26590])
* Make tabs accessible by URL
    (https://issues.rudder.io/issues/26590[#26590])
* Make tabs accessible by URL
    (https://issues.rudder.io/issues/26590[#26590])
* Name the old event logs page "change logs"
    (https://issues.rudder.io/issues/26579[#26579])
* Improve the About page interface
    (https://issues.rudder.io/issues/26536[#26536])

==== Architecture - evolution

* Expose techniqueArchiver in RudderConfig and Mock objects
    (https://issues.rudder.io/issues/26644[#26644])
* Add a function to clean a type of score for a node
    (https://issues.rudder.io/issues/26596[#26596])

==== Architecture - Code maintenance

* JVM platform limit requires splitting services in RudderConfig
    (https://issues.rudder.io/issues/26416[#26416])

==== Web - Config management

* Add a hook during policy generation
    (https://issues.rudder.io/issues/26595[#26595])
* Node criteria for instance ID search should be named "root server instance ID"
    (https://issues.rudder.io/issues/26524[#26524])

==== Generic methods

* Port condition_from methods to log v4+
    (https://issues.rudder.io/issues/25936[#25936])

==== API

* API documentation for API account rest API
    (https://issues.rudder.io/issues/26503[#26503])

==== Web - Nodes & inventories

* CSV export of server list (simple)
    (https://issues.rudder.io/issues/467[#467])

=== Bug fixes

==== Packaging

* Fixed: Remove reporting plugin in 8.3
    (https://issues.rudder.io/issues/26697[#26697])
* Fixed: Apply the patch for augeas preview
    (https://issues.rudder.io/issues/26693[#26693])
* Fixed: Rudder agent 8.3 beta2 nightly breaks on Alma 9
    (https://issues.rudder.io/issues/26547[#26547])

==== Miscellaneous

* Fixed: Can't install Rudder 8.3 Beta 2 on SLES 15 SP4
    (https://issues.rudder.io/issues/26592[#26592])
* Fixed: Confusing warning header on the plugin webpage
    (https://issues.rudder.io/issues/26671[#26671])
* Fixed: Error in documentation /api/changeRequests response data
    (https://issues.rudder.io/issues/26675[#26675])
* Fixed: Ubuntu 22.04 agent cannot be accepted on the server
    (https://issues.rudder.io/issues/26625[#26625])
* Fixed: Error when trying to add a node property when “Change audit logs” are mandatory
    (https://issues.rudder.io/issues/26483[#26483])
* Fixed: Character in method name reports an error while agent run
    (https://issues.rudder.io/issues/26558[#26558])
* Fixed: Missing api account account creation diff element
    (https://issues.rudder.io/issues/26515[#26515])
* Fixed: Missing api account account creation diff element
    (https://issues.rudder.io/issues/26515[#26515])
* Fixed: rudderc generate invalid method call when using methods that are not compatible with Linux 
    (https://issues.rudder.io/issues/26512[#26512])

==== Documentation

* Fixed: Adapt doc for 8.3
    (https://issues.rudder.io/issues/26627[#26627])
* Fixed: Fix links in docs homepage
    (https://issues.rudder.io/issues/26601[#26601])
* Fixed: Rudder package install-file command is no longer relevant in documentation
    (https://issues.rudder.io/issues/26482[#26482])

==== Web - UI & UX

* Fixed: When the menu is collapsed, category titles have a transparent background.
    (https://issues.rudder.io/issues/26680[#26680])
* Fixed: Global properties are unfolded in weird way 
    (https://issues.rudder.io/issues/26639[#26639])
* Fixed: Some settings buttons are grey
    (https://issues.rudder.io/issues/26587[#26587])
* Fixed: SearchNodes page in Rudder : Error 404
    (https://issues.rudder.io/issues/26544[#26544])
* Fixed: License information not displayed on “About” page
    (https://issues.rudder.io/issues/26584[#26584])
* Fixed: Missing API account UI info/actions for token
    (https://issues.rudder.io/issues/26538[#26538])
* Fixed: Missing Score pie charts on dashboard
    (https://issues.rudder.io/issues/26599[#26599])
* Fixed: Menu color leads to unclarity of meaning
    (https://issues.rudder.io/issues/26532[#26532])
* Fixed: Change validation and global settings navigation menu got merged
    (https://issues.rudder.io/issues/26514[#26514])
* Fixed: Error message in plugin page is not visible at all
    (https://issues.rudder.io/issues/26575[#26575])
* Fixed: Links in plugins page should redirect to the local doc
    (https://issues.rudder.io/issues/26565[#26565])
* Fixed: Naming inconsistencies for archive/snapshot page
    (https://issues.rudder.io/issues/26531[#26531])
* Fixed: The refresh button from the nodes webpage change the list of nodes in the other tab
    (https://issues.rudder.io/issues/26264[#26264])
* Fixed: The "Edit columns" button in the nodes webpage is displayed three times
    (https://issues.rudder.io/issues/26260[#26260])
* Fixed: Global properties generated by security benchmarks are displayed on Global Properties GUI
    (https://issues.rudder.io/issues/26487[#26487])

==== Architecture - Dependencies

* Fixed: Unused justinmimbs/date Elm dependency
    (https://issues.rudder.io/issues/26694[#26694])

==== Generic methods

* Fixed: Inventory trigger method broken on Linux
    (https://issues.rudder.io/issues/26684[#26684])
* Fixed: Fix several typos
    (https://issues.rudder.io/issues/26660[#26660])
* Fixed: user_secondary_groups reporting can conflict with itself when used in foreach loop
    (https://issues.rudder.io/issues/26497[#26497])
* Fixed: Fix the Service-Disabled method on Windows
    (https://issues.rudder.io/issues/26520[#26520])
* Fixed: Sharefile to node method doesn't work in audit mode
    (https://issues.rudder.io/issues/26418[#26418])

==== Web - Config management

* Fixed: Changing the system group category hierarchy breaks Rudder
    (https://issues.rudder.io/issues/26429[#26429])
* Fixed: Score are not cleaned correctly at startup
    (https://issues.rudder.io/issues/26504[#26504])

==== Web - Compliance & node report

* Fixed: Compliance repeated when using the new “foreach” loops
    (https://issues.rudder.io/issues/26652[#26652])
* Fixed: No compliance on dashboard in Rudder 8.3
    (https://issues.rudder.io/issues/26545[#26545])
* Fixed: Stackoverflow in NodeStatusReports event computing
    (https://issues.rudder.io/issues/26464[#26464])

==== Web - Nodes & inventories

* Fixed: User with "compliance" perm get error on group, directive pages
    (https://issues.rudder.io/issues/26602[#26602])
* Fixed: Timeout on directive save
    (https://issues.rudder.io/issues/26348[#26348])
* Fixed: Missing Windows 11 OS Name
    (https://issues.rudder.io/issues/26557[#26557])
* Fixed: Errors in callback 'trigger-score-update' in the logs when a node is deleted
    (https://issues.rudder.io/issues/26458[#26458])

==== Techniques

* Fixed: Windows Server 2025 not present in technique editor conditions
    (https://issues.rudder.io/issues/26628[#26628])
* Fixed: The powershell linter does not lint the userManagement technique in version 10
    (https://issues.rudder.io/issues/26722[#26722])
* Fixed: UserManagement technique never report about the password
    (https://issues.rudder.io/issues/26552[#26552])
* Fixed: Standard Rudder technique “SSH server (OpenSSH)” breaks SSH server if Match blocks exists in sshd_config
    (https://issues.rudder.io/issues/26499[#26499])
* Fixed: Broken reporting when using userManagement technique with multiple usesr and secondary group
    (https://issues.rudder.io/issues/26510[#26510])

==== Web - Technique editor

* Fixed: Dubius vertical alignement in generic method
    (https://issues.rudder.io/issues/26630[#26630])
* Fixed: Rudder 8.3 Beta 2 : Result conditions duplicated in technique editor
    (https://issues.rudder.io/issues/26560[#26560])

==== rudderc

* Fixed: Broken policies test in 8.2
    (https://issues.rudder.io/issues/26618[#26618])
* Fixed: Fix the rudderc tests in 8.3
    (https://issues.rudder.io/issues/26589[#26589])
* Fixed: Add a technique test case on unsupported methods
    (https://issues.rudder.io/issues/26556[#26556])
* Fixed:  Re-canonify the expression before evualting them for in windows techniques
    (https://issues.rudder.io/issues/26540[#26540])

==== Architecture - Code maintenance

* Fixed: CurrentUser.queryContext is null when used in a ZIO for
    (https://issues.rudder.io/issues/26605[#26605])

==== Plugin manager cli

* Fixed: rudder package update never test nor use the crendentials
    (https://issues.rudder.io/issues/26493[#26493])

==== Inventory

* Fixed: Rejected inventory with `dummy-node-id` when version missing version section in SOFTWARE/RUDDER
    (https://issues.rudder.io/issues/26465[#26465])

==== API

* Fixed: prettify parameter is ignored in API calls
    (https://issues.rudder.io/issues/26535[#26535])

==== Performance and scalability

* Fixed: rudder agent update is really slow
    (https://issues.rudder.io/issues/26384[#26384])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Jonathan CLARKE
* Intero Admin

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.3.0.beta1 (2025-03-06)

=== Changes


==== Packaging

* Clean rudder package calls
    (https://issues.rudder.io/issues/26423[#26423])
* Cleanup server package for 8.3
    (https://issues.rudder.io/issues/26331[#26331])
* Upgrade to CFEngine 3.24.1
    (https://issues.rudder.io/issues/26321[#26321])
* Embed pcre2 on Slackware 14
    (https://issues.rudder.io/issues/26311[#26311])
* Disable augeas build on Slackware
    (https://issues.rudder.io/issues/26304[#26304])

==== Agent

* We should not be able to install package on wrong OS
    (https://issues.rudder.io/issues/26090[#26090])

==== CI

* Integrate the methods tests to the CI
    (https://issues.rudder.io/issues/26485[#26485])
* Publish step for CI runs the tests when they already have previously run
    (https://issues.rudder.io/issues/26411[#26411])
* Make rudder jenkins task work with ns-remap
    (https://issues.rudder.io/issues/26370[#26370])
* Make rudder-techniques jenkins task work with ns-remap
    (https://issues.rudder.io/issues/26368[#26368])
* Add docker based tests in rudder-agent
    (https://issues.rudder.io/issues/26379[#26379])

==== Architecture - evolution

* Changes for scala 3 migration - branch 8.3
    (https://issues.rudder.io/issues/26455[#26455])

==== API

* Rework api authorization models
    (https://issues.rudder.io/issues/24872[#24872])
* Port RestApiAccount api endpoint to zio-json
    (https://issues.rudder.io/issues/26335[#26335])
* Allow to choose api account ID on creation
    (https://issues.rudder.io/issues/26292[#26292])

==== Plugin manager cli

* Allow skipping the postinst
    (https://issues.rudder.io/issues/26451[#26451])

==== Architecture - Code maintenance

* Update to Rust 1.85.0 and Rust 2024 edition
    (https://issues.rudder.io/issues/26421[#26421])
* Some more changes needed for scala 3 migrations
    (https://issues.rudder.io/issues/26328[#26328])

==== Web - UI & UX

* Add foreach on blocks
    (https://issues.rudder.io/issues/26278[#26278])
* Prettify About page
    (https://issues.rudder.io/issues/26338[#26338])
* Improve license errors handling in webapp
    (https://issues.rudder.io/issues/26243[#26243])
* Pop up validation for restoring archive
    (https://issues.rudder.io/issues/26265[#26265])
* There is no "refresh" on the compliance in directive page and group page
    (https://issues.rudder.io/issues/26062[#26062])
* Make it possible to edit the values of items in a foreach
    (https://issues.rudder.io/issues/26213[#26213])
* Make it possible to edit the values of items in a foreach
    (https://issues.rudder.io/issues/26213[#26213])

==== Module - augeas

* Implement checks in augeas
    (https://issues.rudder.io/issues/26238[#26238])

==== Generic methods

* Write a new test framework for the Rudder methods
    (https://issues.rudder.io/issues/26340[#26340])

==== Architecture - Test

* Ignore policies tests scripts in shellcheck
    (https://issues.rudder.io/issues/26403[#26403])

==== Web - Maintenance

* Migrate logback.xml to new fixed logfile
    (https://issues.rudder.io/issues/26303[#26303])

==== Architecture - Dependencies

* Update zio and zio-json to take benefits of perf improvements
    (https://issues.rudder.io/issues/26297[#26297])

==== rudderc

* Add policy type in rudderc
    (https://issues.rudder.io/issues/26270[#26270])

==== Web - Config management

* Allow to enable/disable technique from the directive tree screen
    (https://issues.rudder.io/issues/26161[#26161])

=== Bug fixes

==== Packaging

* Fixed: Fix typos in ruddder-packages
    (https://issues.rudder.io/issues/26409[#26409])
* Fixed: Builds fail to cleanup
    (https://issues.rudder.io/issues/26308[#26308])
* Fixed: Agent fails to build on old systems
    (https://issues.rudder.io/issues/26306[#26306])
* Fixed: rudder server package writes in different log files ...
    (https://issues.rudder.io/issues/26137[#26137])
* Fixed: Upmerge of 8.1.11 into 8.3 has spotless issue
    (https://issues.rudder.io/issues/26247[#26247])

==== Documentation

* Fixed: Typos in docs
    (https://issues.rudder.io/issues/26410[#26410])
* Fixed: Fixup rudder-doc test task
    (https://issues.rudder.io/issues/26369[#26369])
* Fixed: Change path to webapp log file in doc
    (https://issues.rudder.io/issues/26312[#26312])
* Fixed: Add 8.3 api doc and 8.2 api deprecation
    (https://issues.rudder.io/issues/26481[#26481])
* Fixed: Create a doc for Rust agent support
    (https://issues.rudder.io/issues/26323[#26323])

==== Miscellaneous

* Fixed: Bad "OnSuccess" delay in log
    (https://issues.rudder.io/issues/26479[#26479])

==== Web - Compliance & node report

* Fixed: Inconsistent compliance computation between Directive compliance per Node and Node compliance (directive compliance page is probably wrong)
    (https://issues.rudder.io/issues/26330[#26330])

==== Web - Maintenance

* Fixed: Policy backup and plugins pages should not be available as read-only admin
    (https://issues.rudder.io/issues/26447[#26447])

==== Web - UI & UX

* Fixed: Keep line breaks in reports
    (https://issues.rudder.io/issues/26417[#26417])
* Fixed: Adding a property column to nodes list causes lines to double height thus screen shows 2 times less nodes
    (https://issues.rudder.io/issues/26354[#26354])
* Fixed: Hooks documentation link redirects to non-existing page
    (https://issues.rudder.io/issues/26399[#26399])
* Fixed: Compliance : Directive displayed as Enforce when running in Audit mode
    (https://issues.rudder.io/issues/26232[#26232])
* Fixed: Fix display problems related to menu changes in 8.3
    (https://issues.rudder.io/issues/26359[#26359])
* Fixed: Fix display problems related to menu changes in 8.3
    (https://issues.rudder.io/issues/26359[#26359])
* Fixed: Fix display problems related to menu changes in 8.3
    (https://issues.rudder.io/issues/26359[#26359])
* Fixed: When several plugins are using the same menu, only the last one is displayed
    (https://issues.rudder.io/issues/26322[#26322])
* Fixed: The "Save" button disappears from the group webpage if the group name is too long
    (https://issues.rudder.io/issues/26261[#26261])
* Fixed: Technique can be created with technique ID starting with a forbidden character
    (https://issues.rudder.io/issues/26249[#26249])
* Fixed: Directive will not be displayed when clicking on a technique then on directive in tree
    (https://issues.rudder.io/issues/26206[#26206])
* Fixed: Persistent tooltips on rules page
    (https://issues.rudder.io/issues/25586[#25586])

==== Module - system-updates

* Fixed: Sometimes the error output sent to the server only contain only empty lines
    (https://issues.rudder.io/issues/26441[#26441])
* Fixed: Pretty print the json in the show cmd output
    (https://issues.rudder.io/issues/26437[#26437])
* Fixed: Patch management campaigns on CentOS 7 end in error
    (https://issues.rudder.io/issues/26194[#26194])

==== Plugin manager cli

* Fixed: rudder-pkg reports a success when installing a plugin even if the postinst plugin script was in error
    (https://issues.rudder.io/issues/26428[#26428])
* Fixed: “rudder package upgrade” alone does not upgrade any plugin
    (https://issues.rudder.io/issues/26175[#26175])
* Fixed: rudder-package should create the license folder when not already there
    (https://issues.rudder.io/issues/26317[#26317])

==== Web - Config management

* Fixed: Authorize global parameter names that are not alpha numeric only
    (https://issues.rudder.io/issues/25962[#25962])

==== Web - Nodes & inventories

* Fixed: Resolved properties conflicts still appear as errors in status
    (https://issues.rudder.io/issues/26325[#26325])

==== CI

* Fixed: Cache is not shared anymode
    (https://issues.rudder.io/issues/26414[#26414])
* Fixed: Test for hooks is failing in Docker CI
    (https://issues.rudder.io/issues/26406[#26406])
* Fixed: Test for instance ID is failing on Docker CI
    (https://issues.rudder.io/issues/26396[#26396])
* Fixed: Add a NVD API key to the Jenkins-security jobs
    (https://issues.rudder.io/issues/26385[#26385])

==== Architecture - Test

* Fixed: Roles parsing for custom plugin role may fail in tests
    (https://issues.rudder.io/issues/26342[#26342])

==== Web - Campaigns

* Fixed: Get campaign is creating an empty file when campaign does not exist
    (https://issues.rudder.io/issues/26337[#26337])

==== Agent

* Fixed: The relayd reports parser can break on multiline fields in logs
    (https://issues.rudder.io/issues/26290[#26290])
* Fixed: rudder agent modified may not detect some dates
    (https://issues.rudder.io/issues/26476[#26476])

==== Architecture - Code maintenance

* Fixed: InstanceId check must be in early bootstrap checks
    (https://issues.rudder.io/issues/26286[#26286])
* Fixed: Error at rudder start after an upgrade
    (https://issues.rudder.io/issues/26200[#26200])

==== Security

* Fixed: Update the openssl crate
    (https://issues.rudder.io/issues/26305[#26305])

==== rudderc

* Fixed: Undefined variables can lead to unwanted policy overrides
    (https://issues.rudder.io/issues/26138[#26138])
* Fixed: UTF-8 chars are HTML escaped when used in policy variables
    (https://issues.rudder.io/issues/26151[#26151])

==== Web - Technique editor

* Fixed: Unable to download technique resources
    (https://issues.rudder.io/issues/26159[#26159])

==== System techniques

* Fixed: Fix more typos in system techniques
    (https://issues.rudder.io/issues/26408[#26408])
* Fixed: Fix some typos in system techniques
    (https://issues.rudder.io/issues/26407[#26407])

==== Techniques

* Fixed: ssh key distribution reports The user <username> does not have a defined home dir when username has a dash in it
    (https://issues.rudder.io/issues/26351[#26351])
* Fixed: Reporting on user management technique is broken when multiple users are defined in a directive
    (https://issues.rudder.io/issues/26255[#26255])

==== Generic methods

* Fixed: Fix the abort_default acceptance test
    (https://issues.rudder.io/issues/26372[#26372])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

=== Changes


==== Packaging

* Build the augeas module
    (https://issues.rudder.io/issues/26183[#26183])
* Add nettle as a rudder-package dependency
    (https://issues.rudder.io/issues/26084[#26084])
* Use ncf from the rudder repo
    (https://issues.rudder.io/issues/26080[#26080])
* Update compiled dependencies for Rudder 8.3
    (https://issues.rudder.io/issues/25931[#25931])
* Remove rudder-synchronize and rudder-api-client dependency
    (https://issues.rudder.io/issues/25890[#25890])
* Update to CFEngine 3.24.0 LTS
    (https://issues.rudder.io/issues/25791[#25791])
* Update to Rust 1.84.0
    (https://issues.rudder.io/issues/26186[#26186])
* Create an instance id on each root server
    (https://issues.rudder.io/issues/25841[#25841])
* Allow LGPL license in crates
    (https://issues.rudder.io/issues/26086[#26086])
* Test cleanup after ncf merge into Rudder
    (https://issues.rudder.io/issues/26076[#26076])
* Update to Rust 1.83.0
    (https://issues.rudder.io/issues/25975[#25975])
* Update Rust dependencies
    (https://issues.rudder.io/issues/25843[#25843])

==== System integration

* Add a command to help splitting virtualhosts
    (https://issues.rudder.io/issues/25144[#25144])
* Instance ID should be added as a variable for nodes
    (https://issues.rudder.io/issues/26135[#26135])

==== Documentation

* Add the 8.2 version of the techniques doc
    (https://issues.rudder.io/issues/26187[#26187])
* Update documentation for new rpm key in 8.3
    (https://issues.rudder.io/issues/26006[#26006])

==== Web - UI & UX

* Add a user interface for managing method/block loops in the techniques editor
    (https://issues.rudder.io/issues/26153[#26153])
* Create a new ‘About’ page for easy access to technical information
    (https://issues.rudder.io/issues/26059[#26059])
* Change rudder 8.3 main menu
    (https://issues.rudder.io/issues/26055[#26055])
* Make fold-out menu css accessible everywhere in Rudder
    (https://issues.rudder.io/issues/26028[#26028])
* Remove rudder.css file
    (https://issues.rudder.io/issues/25898[#25898])

==== Module - augeas

* Implement augeas module
    (https://issues.rudder.io/issues/26089[#26089])

==== Plugins integration

* Allow to install plugins from user interface
    (https://issues.rudder.io/issues/26144[#26144])

==== Miscellaneous

* Update api doc tooling
    (https://issues.rudder.io/issues/26188[#26188])
* Improve SVG image handling in the repo
    (https://issues.rudder.io/issues/25225[#25225])

==== Web - Nodes & inventories

* Add windows 2025 data info in Rudder server
    (https://issues.rudder.io/issues/26173[#26173])
* Add description/doc field to node settable by API
    (https://issues.rudder.io/issues/25984[#25984])

==== Web - Maintenance

* Update front-end dependencies
    (https://issues.rudder.io/issues/26042[#26042])
* Have a stable webapp log file
    (https://issues.rudder.io/issues/26039[#26039])

==== API

* Make API authentication pluggable
    (https://issues.rudder.io/issues/26167[#26167])
* Remove unused and duplicate rest extractor lift-json methods
    (https://issues.rudder.io/issues/25960[#25960])
* Add and Remove/deprecate API for Rudder 8.3
    (https://issues.rudder.io/issues/25945[#25945])

==== Architecture - Code maintenance

* Migrate compliance status from lift-json to zio-json
    (https://issues.rudder.io/issues/26046[#26046])
* Migrate from lift-json to zio-json in LDAPEntityMapper
    (https://issues.rudder.io/issues/25887[#25887])
* Migrate Environment variable from lift-json to zio-json
    (https://issues.rudder.io/issues/25886[#25886])
* Migrate CustomProperties form lift-json to zio-json
    (https://issues.rudder.io/issues/25885[#25885])
* Migrate SecurityToken ldap json serialisation to ZIO
    (https://issues.rudder.io/issues/25884[#25884])
* Clean-up support for rsa key for inventory signature
    (https://issues.rudder.io/issues/25780[#25780])
* Migrate CmdbQuery to zio-json
    (https://issues.rudder.io/issues/25894[#25894])
* Remove all occurrence of cfengine enterprise
    (https://issues.rudder.io/issues/25779[#25779])

==== Web - Config management

* Add instance ID in group search criteria
    (https://issues.rudder.io/issues/26136[#26136])
* Remove AIX password hash support
    (https://issues.rudder.io/issues/25836[#25836])

==== Plugin manager cli

* Handle the plugin metadata for license requirement
    (https://issues.rudder.io/issues/26149[#26149])
* Use sequoia in rudder-package
    (https://issues.rudder.io/issues/26082[#26082])

==== Module - system-updates

* Create the augeas module
    (https://issues.rudder.io/issues/25942[#25942])

==== rudderc

* Make compilation resolved loops over Blocks/Methods in techniques possible
    (https://issues.rudder.io/issues/25970[#25970])

==== Security

* Deny iframes in Rudder
    (https://issues.rudder.io/issues/26068[#26068])
* Remove support for clear-text API tokens
    (https://issues.rudder.io/issues/25902[#25902])

==== Relay server or API

* Add rsync configuration datastructure to relayd
    (https://issues.rudder.io/issues/24997[#24997])

==== Generic methods

* Deprecated audit methods that have a non audit only alternative
    (https://issues.rudder.io/issues/25939[#25939])
*  Add Windows support to the generic method file_report_content_tail
    (https://issues.rudder.io/issues/25588[#25588])
* Deprecated audit methods that have a non audit only alternative
    (https://issues.rudder.io/issues/25939[#25939])

==== Architecture - Dependencies

* Upgrade to ZIO 2.1.12
    (https://issues.rudder.io/issues/24968[#24968])

==== Techniques

* Remove the zmd management technique
    (https://issues.rudder.io/issues/26140[#26140])

==== System techniques

* Remove the metrics technique
    (https://issues.rudder.io/issues/25920[#25920])

==== Agent

* Hide na reports by default
    (https://issues.rudder.io/issues/25910[#25910])

=== Bug fixes

==== Packaging

* Fixed: Broken agent build on RHEL8
    (https://issues.rudder.io/issues/26209[#26209])
* Fixed: Use the fallback system-updates on Ubuntu 16.04 and Debian 9
    (https://issues.rudder.io/issues/25655[#25655])
* Fixed: Missing dependency on gpgv on RPM systems
    (https://issues.rudder.io/issues/25494[#25494])
* Fixed: raugeas does not build on arm
    (https://issues.rudder.io/issues/26227[#26227])
* Fixed: Allow unicode license
    (https://issues.rudder.io/issues/25872[#25872])
* Fixed: Don't configure a broken Rudder account by default
    (https://issues.rudder.io/issues/25868[#25868])
* Fixed: Update Rust for typos check
    (https://issues.rudder.io/issues/25790[#25790])

==== Agent

* Fixed: Pass an argument to CFEngine custom promise type binaries
    (https://issues.rudder.io/issues/25145[#25145])

==== Documentation

* Fixed: Troubleshooting ESET software modifying certificates by replacing issuers
    (https://issues.rudder.io/issues/26234[#26234])
* Fixed: Fix the logo in the README
    (https://issues.rudder.io/issues/25755[#25755])

==== Architecture - Code maintenance

* Fixed: Add tests and clean-up JsDataLine structures
    (https://issues.rudder.io/issues/26070[#26070])
* Fixed: Remove NodeInfoService and other related proxy service
    (https://issues.rudder.io/issues/25781[#25781])

==== Architecture - Test

* Fixed: Fix API yaml tests on groups and remove restriction to event log
    (https://issues.rudder.io/issues/26078[#26078])

==== Web - UI & UX

* Fixed: Node search page looks empty
    (https://issues.rudder.io/issues/26058[#26058])

==== Web - Nodes & inventories

* Fixed: Refuse inventory too far from "now"
    (https://issues.rudder.io/issues/25996[#25996])

==== rudderc

* Fixed: Broken policies test
    (https://issues.rudder.io/issues/25998[#25998])
* Fixed: Create a global method call counter to help provide more unicity
    (https://issues.rudder.io/issues/25776[#25776])
* Fixed: We have no 8.3 build for now
    (https://issues.rudder.io/issues/25346[#25346])

==== API

* Fixed: Migrate info api to zio-json
    (https://issues.rudder.io/issues/25969[#25969])

==== Generic methods

* Fixed: Add a new type constraint to the variable_dict generic method
    (https://issues.rudder.io/issues/25924[#25924])
* Fixed: Broken jinja2 templating on Ubuntu 24.04
    (https://issues.rudder.io/issues/25324[#25324])

==== Architecture - Dependencies

* Fixed: Update Scala dependencies
    (https://issues.rudder.io/issues/25758[#25758])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

