= Change logs for Rudder 8.3==  Rudder 8.3.0.alpha1 (2025-01-23)

==  Rudder 8.3.0.beta1 (2025-03-06)

=== Changes


==== Packaging

* Clean rudder package calls
    (https://issues.rudder.io/issues/26423[#26423])
* Cleanup server package for 8.3
    (https://issues.rudder.io/issues/26331[#26331])
* Upgrade to CFEngine 3.24.1
    (https://issues.rudder.io/issues/26321[#26321])
* Embed pcre2 on Slackware 14
    (https://issues.rudder.io/issues/26311[#26311])
* Disable augeas build on Slackware
    (https://issues.rudder.io/issues/26304[#26304])

==== Agent

* We should not be able to install package on wrong OS
    (https://issues.rudder.io/issues/26090[#26090])

==== CI

* Integrate the methods tests to the CI
    (https://issues.rudder.io/issues/26485[#26485])
* Publish step for CI runs the tests when they already have previously run
    (https://issues.rudder.io/issues/26411[#26411])
* Make rudder jenkins task work with ns-remap
    (https://issues.rudder.io/issues/26370[#26370])
* Make rudder-techniques jenkins task work with ns-remap
    (https://issues.rudder.io/issues/26368[#26368])
* Add docker based tests in rudder-agent
    (https://issues.rudder.io/issues/26379[#26379])

==== Architecture - evolution

* Changes for scala 3 migration - branch 8.3
    (https://issues.rudder.io/issues/26455[#26455])

==== API

* Rework api authorization models
    (https://issues.rudder.io/issues/24872[#24872])
* Port RestApiAccount api endpoint to zio-json
    (https://issues.rudder.io/issues/26335[#26335])
* Allow to choose api account ID on creation
    (https://issues.rudder.io/issues/26292[#26292])

==== Plugin manager cli

* Allow skipping the postinst
    (https://issues.rudder.io/issues/26451[#26451])

==== Architecture - Code maintenance

* Update to Rust 1.85.0 and Rust 2024 edition
    (https://issues.rudder.io/issues/26421[#26421])
* Some more changes needed for scala 3 migrations
    (https://issues.rudder.io/issues/26328[#26328])

==== Web - UI & UX

* Add foreach on blocks
    (https://issues.rudder.io/issues/26278[#26278])
* Prettify About page
    (https://issues.rudder.io/issues/26338[#26338])
* Improve license errors handling in webapp
    (https://issues.rudder.io/issues/26243[#26243])
* Pop up validation for restoring archive
    (https://issues.rudder.io/issues/26265[#26265])
* There is no "refresh" on the compliance in directive page and group page
    (https://issues.rudder.io/issues/26062[#26062])
* Make it possible to edit the values of items in a foreach
    (https://issues.rudder.io/issues/26213[#26213])
* Make it possible to edit the values of items in a foreach
    (https://issues.rudder.io/issues/26213[#26213])

==== Module - augeas

* Implement checks in augeas
    (https://issues.rudder.io/issues/26238[#26238])

==== Generic methods

* Write a new test framework for the Rudder methods
    (https://issues.rudder.io/issues/26340[#26340])

==== Architecture - Test

* Ignore policies tests scripts in shellcheck
    (https://issues.rudder.io/issues/26403[#26403])

==== Web - Maintenance

* Migrate logback.xml to new fixed logfile
    (https://issues.rudder.io/issues/26303[#26303])

==== Architecture - Dependencies

* Update zio and zio-json to take benefits of perf improvements
    (https://issues.rudder.io/issues/26297[#26297])

==== rudderc

* Add policy type in rudderc
    (https://issues.rudder.io/issues/26270[#26270])

==== Web - Config management

* Allow to enable/disable technique from the directive tree screen
    (https://issues.rudder.io/issues/26161[#26161])

=== Bug fixes

==== Packaging

* Fixed: Fix typos in ruddder-packages
    (https://issues.rudder.io/issues/26409[#26409])
* Fixed: Builds fail to cleanup
    (https://issues.rudder.io/issues/26308[#26308])
* Fixed: Agent fails to build on old systems
    (https://issues.rudder.io/issues/26306[#26306])
* Fixed: rudder server package writes in different log files ...
    (https://issues.rudder.io/issues/26137[#26137])
* Fixed: Upmerge of 8.1.11 into 8.3 has spotless issue
    (https://issues.rudder.io/issues/26247[#26247])

==== Documentation

* Fixed: Typos in docs
    (https://issues.rudder.io/issues/26410[#26410])
* Fixed: Fixup rudder-doc test task
    (https://issues.rudder.io/issues/26369[#26369])
* Fixed: Change path to webapp log file in doc
    (https://issues.rudder.io/issues/26312[#26312])
* Fixed: Add 8.3 api doc and 8.2 api deprecation
    (https://issues.rudder.io/issues/26481[#26481])
* Fixed: Create a doc for Rust agent support
    (https://issues.rudder.io/issues/26323[#26323])

==== Miscellaneous

* Fixed: Bad "OnSuccess" delay in log
    (https://issues.rudder.io/issues/26479[#26479])

==== Web - Compliance & node report

* Fixed: Inconsistent compliance computation between Directive compliance per Node and Node compliance (directive compliance page is probably wrong)
    (https://issues.rudder.io/issues/26330[#26330])

==== Web - Maintenance

* Fixed: Policy backup and plugins pages should not be available as read-only admin
    (https://issues.rudder.io/issues/26447[#26447])

==== Web - UI & UX

* Fixed: Keep line breaks in reports
    (https://issues.rudder.io/issues/26417[#26417])
* Fixed: Adding a property column to nodes list causes lines to double height thus screen shows 2 times less nodes
    (https://issues.rudder.io/issues/26354[#26354])
* Fixed: Hooks documentation link redirects to non-existing page
    (https://issues.rudder.io/issues/26399[#26399])
* Fixed: Compliance : Directive displayed as Enforce when running in Audit mode
    (https://issues.rudder.io/issues/26232[#26232])
* Fixed: Fix display problems related to menu changes in 8.3
    (https://issues.rudder.io/issues/26359[#26359])
* Fixed: Fix display problems related to menu changes in 8.3
    (https://issues.rudder.io/issues/26359[#26359])
* Fixed: Fix display problems related to menu changes in 8.3
    (https://issues.rudder.io/issues/26359[#26359])
* Fixed: When several plugins are using the same menu, only the last one is displayed
    (https://issues.rudder.io/issues/26322[#26322])
* Fixed: The "Save" button disappears from the group webpage if the group name is too long
    (https://issues.rudder.io/issues/26261[#26261])
* Fixed: Technique can be created with technique ID starting with a forbidden character
    (https://issues.rudder.io/issues/26249[#26249])
* Fixed: Directive will not be displayed when clicking on a technique then on directive in tree
    (https://issues.rudder.io/issues/26206[#26206])
* Fixed: Persistent tooltips on rules page
    (https://issues.rudder.io/issues/25586[#25586])

==== Module - system-updates

* Fixed: Sometimes the error output sent to the server only contain only empty lines
    (https://issues.rudder.io/issues/26441[#26441])
* Fixed: Pretty print the json in the show cmd output
    (https://issues.rudder.io/issues/26437[#26437])
* Fixed: Patch management campaigns on CentOS 7 end in error
    (https://issues.rudder.io/issues/26194[#26194])

==== Plugin manager cli

* Fixed: rudder-pkg reports a success when installing a plugin even if the postinst plugin script was in error
    (https://issues.rudder.io/issues/26428[#26428])
* Fixed: “rudder package upgrade” alone does not upgrade any plugin
    (https://issues.rudder.io/issues/26175[#26175])
* Fixed: rudder-package should create the license folder when not already there
    (https://issues.rudder.io/issues/26317[#26317])

==== Web - Config management

* Fixed: Authorize global parameter names that are not alpha numeric only
    (https://issues.rudder.io/issues/25962[#25962])

==== Web - Nodes & inventories

* Fixed: Resolved properties conflicts still appear as errors in status
    (https://issues.rudder.io/issues/26325[#26325])

==== CI

* Fixed: Cache is not shared anymode
    (https://issues.rudder.io/issues/26414[#26414])
* Fixed: Test for hooks is failing in Docker CI
    (https://issues.rudder.io/issues/26406[#26406])
* Fixed: Test for instance ID is failing on Docker CI
    (https://issues.rudder.io/issues/26396[#26396])
* Fixed: Add a NVD API key to the Jenkins-security jobs
    (https://issues.rudder.io/issues/26385[#26385])

==== Architecture - Test

* Fixed: Roles parsing for custom plugin role may fail in tests
    (https://issues.rudder.io/issues/26342[#26342])

==== Web - Campaigns

* Fixed: Get campaign is creating an empty file when campaign does not exist
    (https://issues.rudder.io/issues/26337[#26337])

==== Agent

* Fixed: The relayd reports parser can break on multiline fields in logs
    (https://issues.rudder.io/issues/26290[#26290])
* Fixed: rudder agent modified may not detect some dates
    (https://issues.rudder.io/issues/26476[#26476])

==== Architecture - Code maintenance

* Fixed: InstanceId check must be in early bootstrap checks
    (https://issues.rudder.io/issues/26286[#26286])
* Fixed: Error at rudder start after an upgrade
    (https://issues.rudder.io/issues/26200[#26200])

==== Security

* Fixed: Update the openssl crate
    (https://issues.rudder.io/issues/26305[#26305])

==== rudderc

* Fixed: Undefined variables can lead to unwanted policy overrides
    (https://issues.rudder.io/issues/26138[#26138])
* Fixed: UTF-8 chars are HTML escaped when used in policy variables
    (https://issues.rudder.io/issues/26151[#26151])

==== Web - Technique editor

* Fixed: Unable to download technique resources
    (https://issues.rudder.io/issues/26159[#26159])

==== System techniques

* Fixed: Fix more typos in system techniques
    (https://issues.rudder.io/issues/26408[#26408])
* Fixed: Fix some typos in system techniques
    (https://issues.rudder.io/issues/26407[#26407])

==== Techniques

* Fixed: ssh key distribution reports The user <username> does not have a defined home dir when username has a dash in it
    (https://issues.rudder.io/issues/26351[#26351])
* Fixed: Reporting on user management technique is broken when multiple users are defined in a directive
    (https://issues.rudder.io/issues/26255[#26255])

==== Generic methods

* Fixed: Fix the abort_default acceptance test
    (https://issues.rudder.io/issues/26372[#26372])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

=== Changes


==== Packaging

* Build the augeas module
    (https://issues.rudder.io/issues/26183[#26183])
* Add nettle as a rudder-package dependency
    (https://issues.rudder.io/issues/26084[#26084])
* Use ncf from the rudder repo
    (https://issues.rudder.io/issues/26080[#26080])
* Update compiled dependencies for Rudder 8.3
    (https://issues.rudder.io/issues/25931[#25931])
* Remove rudder-synchronize and rudder-api-client dependency
    (https://issues.rudder.io/issues/25890[#25890])
* Update to CFEngine 3.24.0 LTS
    (https://issues.rudder.io/issues/25791[#25791])
* Update to Rust 1.84.0
    (https://issues.rudder.io/issues/26186[#26186])
* Create an instance id on each root server
    (https://issues.rudder.io/issues/25841[#25841])
* Allow LGPL license in crates
    (https://issues.rudder.io/issues/26086[#26086])
* Test cleanup after ncf merge into Rudder
    (https://issues.rudder.io/issues/26076[#26076])
* Update to Rust 1.83.0
    (https://issues.rudder.io/issues/25975[#25975])
* Update Rust dependencies
    (https://issues.rudder.io/issues/25843[#25843])

==== System integration

* Add a command to help splitting virtualhosts
    (https://issues.rudder.io/issues/25144[#25144])
* Instance ID should be added as a variable for nodes
    (https://issues.rudder.io/issues/26135[#26135])

==== Documentation

* Add the 8.2 version of the techniques doc
    (https://issues.rudder.io/issues/26187[#26187])
* Update documentation for new rpm key in 8.3
    (https://issues.rudder.io/issues/26006[#26006])

==== Web - UI & UX

* Add a user interface for managing method/block loops in the techniques editor
    (https://issues.rudder.io/issues/26153[#26153])
* Create a new ‘About’ page for easy access to technical information
    (https://issues.rudder.io/issues/26059[#26059])
* Change rudder 8.3 main menu
    (https://issues.rudder.io/issues/26055[#26055])
* Make fold-out menu css accessible everywhere in Rudder
    (https://issues.rudder.io/issues/26028[#26028])
* Remove rudder.css file
    (https://issues.rudder.io/issues/25898[#25898])

==== Module - augeas

* Implement augeas module
    (https://issues.rudder.io/issues/26089[#26089])

==== Plugins integration

* Allow to install plugins from user interface
    (https://issues.rudder.io/issues/26144[#26144])

==== Miscellaneous

* Update api doc tooling
    (https://issues.rudder.io/issues/26188[#26188])
* Improve SVG image handling in the repo
    (https://issues.rudder.io/issues/25225[#25225])

==== Web - Nodes & inventories

* Add windows 2025 data info in Rudder server
    (https://issues.rudder.io/issues/26173[#26173])
* Add description/doc field to node settable by API
    (https://issues.rudder.io/issues/25984[#25984])

==== Web - Maintenance

* Update front-end dependencies
    (https://issues.rudder.io/issues/26042[#26042])
* Have a stable webapp log file
    (https://issues.rudder.io/issues/26039[#26039])

==== API

* Make API authentication pluggable
    (https://issues.rudder.io/issues/26167[#26167])
* Remove unused and duplicate rest extractor lift-json methods
    (https://issues.rudder.io/issues/25960[#25960])
* Add and Remove/deprecate API for Rudder 8.3
    (https://issues.rudder.io/issues/25945[#25945])

==== Architecture - Code maintenance

* Migrate compliance status from lift-json to zio-json
    (https://issues.rudder.io/issues/26046[#26046])
* Migrate from lift-json to zio-json in LDAPEntityMapper
    (https://issues.rudder.io/issues/25887[#25887])
* Migrate Environment variable from lift-json to zio-json
    (https://issues.rudder.io/issues/25886[#25886])
* Migrate CustomProperties form lift-json to zio-json
    (https://issues.rudder.io/issues/25885[#25885])
* Migrate SecurityToken ldap json serialisation to ZIO
    (https://issues.rudder.io/issues/25884[#25884])
* Clean-up support for rsa key for inventory signature
    (https://issues.rudder.io/issues/25780[#25780])
* Migrate CmdbQuery to zio-json
    (https://issues.rudder.io/issues/25894[#25894])
* Remove all occurrence of cfengine enterprise
    (https://issues.rudder.io/issues/25779[#25779])

==== Web - Config management

* Add instance ID in group search criteria
    (https://issues.rudder.io/issues/26136[#26136])
* Remove AIX password hash support
    (https://issues.rudder.io/issues/25836[#25836])

==== Plugin manager cli

* Handle the plugin metadata for license requirement
    (https://issues.rudder.io/issues/26149[#26149])
* Use sequoia in rudder-package
    (https://issues.rudder.io/issues/26082[#26082])

==== Module - system-updates

* Create the augeas module
    (https://issues.rudder.io/issues/25942[#25942])

==== rudderc

* Make compilation resolved loops over Blocks/Methods in techniques possible
    (https://issues.rudder.io/issues/25970[#25970])

==== Security

* Deny iframes in Rudder
    (https://issues.rudder.io/issues/26068[#26068])
* Remove support for clear-text API tokens
    (https://issues.rudder.io/issues/25902[#25902])

==== Relay server or API

* Add rsync configuration datastructure to relayd
    (https://issues.rudder.io/issues/24997[#24997])

==== Generic methods

* Deprecated audit methods that have a non audit only alternative
    (https://issues.rudder.io/issues/25939[#25939])
*  Add Windows support to the generic method file_report_content_tail
    (https://issues.rudder.io/issues/25588[#25588])
* Deprecated audit methods that have a non audit only alternative
    (https://issues.rudder.io/issues/25939[#25939])

==== Architecture - Dependencies

* Upgrade to ZIO 2.1.12
    (https://issues.rudder.io/issues/24968[#24968])

==== Techniques

* Remove the zmd management technique
    (https://issues.rudder.io/issues/26140[#26140])

==== System techniques

* Remove the metrics technique
    (https://issues.rudder.io/issues/25920[#25920])

==== Agent

* Hide na reports by default
    (https://issues.rudder.io/issues/25910[#25910])

=== Bug fixes

==== Packaging

* Fixed: Broken agent build on RHEL8
    (https://issues.rudder.io/issues/26209[#26209])
* Fixed: Use the fallback system-updates on Ubuntu 16.04 and Debian 9
    (https://issues.rudder.io/issues/25655[#25655])
* Fixed: Missing dependency on gpgv on RPM systems
    (https://issues.rudder.io/issues/25494[#25494])
* Fixed: raugeas does not build on arm
    (https://issues.rudder.io/issues/26227[#26227])
* Fixed: Allow unicode license
    (https://issues.rudder.io/issues/25872[#25872])
* Fixed: Don't configure a broken Rudder account by default
    (https://issues.rudder.io/issues/25868[#25868])
* Fixed: Update Rust for typos check
    (https://issues.rudder.io/issues/25790[#25790])

==== Agent

* Fixed: Pass an argument to CFEngine custom promise type binaries
    (https://issues.rudder.io/issues/25145[#25145])

==== Documentation

* Fixed: Troubleshooting ESET software modifying certificates by replacing issuers
    (https://issues.rudder.io/issues/26234[#26234])
* Fixed: Fix the logo in the README
    (https://issues.rudder.io/issues/25755[#25755])

==== Architecture - Code maintenance

* Fixed: Add tests and clean-up JsDataLine structures
    (https://issues.rudder.io/issues/26070[#26070])
* Fixed: Remove NodeInfoService and other related proxy service
    (https://issues.rudder.io/issues/25781[#25781])

==== Architecture - Test

* Fixed: Fix API yaml tests on groups and remove restriction to event log
    (https://issues.rudder.io/issues/26078[#26078])

==== Web - UI & UX

* Fixed: Node search page looks empty
    (https://issues.rudder.io/issues/26058[#26058])

==== Web - Nodes & inventories

* Fixed: Refuse inventory too far from "now"
    (https://issues.rudder.io/issues/25996[#25996])

==== rudderc

* Fixed: Broken policies test
    (https://issues.rudder.io/issues/25998[#25998])
* Fixed: Create a global method call counter to help provide more unicity
    (https://issues.rudder.io/issues/25776[#25776])
* Fixed: We have no 8.3 build for now
    (https://issues.rudder.io/issues/25346[#25346])

==== API

* Fixed: Migrate info api to zio-json
    (https://issues.rudder.io/issues/25969[#25969])

==== Generic methods

* Fixed: Add a new type constraint to the variable_dict generic method
    (https://issues.rudder.io/issues/25924[#25924])
* Fixed: Broken jinja2 templating on Ubuntu 24.04
    (https://issues.rudder.io/issues/25324[#25324])

==== Architecture - Dependencies

* Fixed: Update Scala dependencies
    (https://issues.rudder.io/issues/25758[#25758])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

