= Changelogs for Rudder plugin dsc 7.3.5.\* versions

== dsc-7.3.5-2.4 (2023-08-11)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: If the installer is run multiple times consecutively, the FusionInventory patches are removed from the system
    (https://issues.rudder.io/issues/23232[#23232])
* Fixed: Windows agent is built with corrupted version number when built from the CI with a timestamp close to a minute end
    (https://issues.rudder.io/issues/23124[#23124])

==== Agent library

* Fixed: The false condition should not be definable in a context rudderc expect "false" to always evaluate to a false boolean
    (https://issues.rudder.io/issues/23162[#23162])

==== Generic methods

* Fixed: File_from_share_folder fails with unexpected error since upgrade in 7.3.4
    (https://issues.rudder.io/issues/23126[#23126])

==== CLI

* Fixed: RudderVariables module throw warning logs when some registry entries are not yet defined
    (https://issues.rudder.io/issues/23115[#23115])
* Fixed: 7.3 rudder agent version displays the agent version in its old format
    (https://issues.rudder.io/issues/23114[#23114])

=== Release notes

This is a bug fix release in the 7.3.5 series and therefore all installations of 7.3.5.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

