= Change logs for Rudder 7.1

==  Rudder 7.1.2 (2022-06-22)

=== Changes


==== Documentation

* Add documentation to install Rudder server on Amazon linux 2
    (https://issues.rudder.io/issues/21183[#21183])
* Update api doc tooling
    (https://issues.rudder.io/issues/21232[#21232])

=== Bug fixes

==== Relay server or API

* Fixed: relayd can't connect to postgresql on Ubuntu 22.04 server
    (https://issues.rudder.io/issues/21219[#21219])
* Fixed: Missing SELinux rules for httpd on RockyLinux
    (https://issues.rudder.io/issues/20263[#20263])
* Fixed: relayd error messages about config files are lacking path information
    (https://issues.rudder.io/issues/21279[#21279])
* Fixed: Allow .ocs files as inventory
    (https://issues.rudder.io/issues/21270[#21270])
* Fixed: Missing encoding of postgresql password
    (https://issues.rudder.io/issues/21203[#21203])
* Fixed: Query seems to be ignored for pendings nodes
    (https://issues.rudder.io/issues/20281[#20281])

==== Packaging

* Fixed: parsing of system fusioninventory is invalid
    (https://issues.rudder.io/issues/21211[#21211])

==== Documentation

* Fixed: Typo in documentation to change ports used by rudder
    (https://issues.rudder.io/issues/21210[#21210])
* Fixed: Missing API documentation for technique
    (https://issues.rudder.io/issues/21254[#21254])

==== Techniques

* Fixed: When upgrading to 7.1, techniques are not upgraded to the new format and reporting issue occur
    (https://issues.rudder.io/issues/21220[#21220])
* Fixed: systemUpdate technique parameters should accept properties as input
    (https://issues.rudder.io/issues/21291[#21291])

==== Security

* Fixed: Ignore CVE  CVE-2022-22978 that will not be fixed in 6.1/6.2 dependencies
    (https://issues.rudder.io/issues/21263[#21263])
* Fixed: Upgrade spring-security to 5.5.8 to fix CVE 2022-22978
    (https://issues.rudder.io/issues/21237[#21237])

==== Web - Config management

* Fixed: GetMetadataContent does not correctly retrieve content when a revision is given
    (https://issues.rudder.io/issues/21260[#21260])

==== Architecture - Internal libs

* Fixed: Query string is not correctly parsed in test API framework
    (https://issues.rudder.io/issues/21253[#21253])

==== Web - Technique editor

* Fixed: When a technique is not in the active techique tree, it can't be deleted in editor
    (https://issues.rudder.io/issues/21119[#21119])

==== Web - UI & UX

* Fixed: Missing icon in technical logs for error messages
    (https://issues.rudder.io/issues/18918[#18918])

==== Performance and scalability

* Fixed: Improve performance of display for agent version on homepage
    (https://issues.rudder.io/issues/21230[#21230])

==== rudderc

* Fixed: During upgrade of techniques, rudderc is used even if disabled
    (https://issues.rudder.io/issues/21229[#21229])

==== CI

* Fixed: Race condition between elm builds
    (https://issues.rudder.io/issues/21156[#21156])

==== Generic methods

* Fixed: The mustache template examples in our documentation do not respect the mustache standard
    (https://issues.rudder.io/issues/21286[#21286])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


==  Rudder 7.1.1 (2022-05-31)

=== Changes


==== Plugins integration

* Add windows support to the inventory software update section
    (https://issues.rudder.io/issues/21067[#21067])

==== Web - UI & UX

* Provide a version of the OS icons without text
    (https://issues.rudder.io/issues/21071[#21071])
* Update css related to the change validation plugin
    (https://issues.rudder.io/issues/21052[#21052])

==== Server components

* allow a user to pass a password to server create-user command
    (https://issues.rudder.io/issues/20675[#20675])

=== Bug fixes

==== Packaging

* Fixed: Embed openssl on ubuntu 22.04
    (https://issues.rudder.io/issues/21040[#21040])
* Fixed: ubuntu22 build options are missing
    (https://issues.rudder.io/issues/21036[#21036])
* Fixed: Ubuntu 22 needs python3 as build dependency for rudder-agent
    (https://issues.rudder.io/issues/21035[#21035])
* Fixed: Backup ca.cert like other cert files
    (https://issues.rudder.io/issues/21143[#21143])

==== Documentation

* Fixed: Documentation about certificate handling during uprade is not great
    (https://issues.rudder.io/issues/21129[#21129])
* Fixed: Mark 7.1 as released in the docs
    (https://issues.rudder.io/issues/21030[#21030])

==== Performance and scalability

* Fixed: Adapt rule details to have the list of directives/nodes that appear faster
    (https://issues.rudder.io/issues/21081[#21081])
* Fixed: The way groups are fetched when responding to API compliance is inefficient
    (https://issues.rudder.io/issues/21028[#21028])

==== Relay server or API

* Fixed: Huge broken logs in relayd
    (https://issues.rudder.io/issues/21157[#21157])

==== Security

* Fixed: security checks fails because of request to sonatype oss index
    (https://issues.rudder.io/issues/21179[#21179])
* Fixed: Fix some cve in dependencies 
    (https://issues.rudder.io/issues/21169[#21169])
* Fixed: Ignore some CVE that cannot be fixed in 6.1 branch
    (https://issues.rudder.io/issues/21103[#21103])
* Fixed: Ignore some CVE that cannot be fixed in 6.1 branch
    (https://issues.rudder.io/issues/21103[#21103])
* Fixed: Don't display oauth/oidc client secret in logs
    (https://issues.rudder.io/issues/21077[#21077])
* Fixed: Ignore CVEs for spring-ldap-core
    (https://issues.rudder.io/issues/21027[#21027])
* Fixed: Update spring and logback version because of new CVE
    (https://issues.rudder.io/issues/21022[#21022])

==== System integration

* Fixed: Root log explain_compliance is in debug by default
    (https://issues.rudder.io/issues/21166[#21166])
* Fixed: rudder package does not sort plugin version correctly
    (https://issues.rudder.io/issues/21121[#21121])

==== Web - Nodes & inventories

* Fixed: Criteria not working when filter on IP adress and GoupID in group page
    (https://issues.rudder.io/issues/21144[#21144])
* Fixed: Sometime inventory processing is not done when inventory is receveived
    (https://issues.rudder.io/issues/19585[#19585])
* Fixed: List of nodes by version does not include windows nodes
    (https://issues.rudder.io/issues/17728[#17728])

==== Web - Technique editor

* Fixed: Filter on agent type on technique editor is not correctly shown
    (https://issues.rudder.io/issues/21160[#21160])

==== API

* Fixed: Directive and rule revision is not parsed in API
    (https://issues.rudder.io/issues/21150[#21150])
* Fixed: Rudder incorectly parse URL with a '+' in the path into spaces
    (https://issues.rudder.io/issues/20943[#20943])
* Fixed: Deleting a rule's category leeds to an error
    (https://issues.rudder.io/issues/21080[#21080])
* Fixed: Update api doc tool chain
    (https://issues.rudder.io/issues/21073[#21073])
* Fixed: Generation not started when modifying authorized network via API
    (https://issues.rudder.io/issues/20979[#20979])

==== Web - Config management

* Fixed: condition from windows node does not take condition from blocks
    (https://issues.rudder.io/issues/21108[#21108])
* Fixed: Revision are taken into account during generation
    (https://issues.rudder.io/issues/20929[#20929])

==== Architecture - Refactoring

* Fixed: Scala does not really supports [_:P] syntax
    (https://issues.rudder.io/issues/21107[#21107])
* Fixed: Update TechniqueVersion to conform to method visibility
    (https://issues.rudder.io/issues/21106[#21106])

==== Web - Compliance & node report

* Fixed: Compliance percentage computation in ComplianceLevel is not correct, and performance is not correct
    (https://issues.rudder.io/issues/20998[#20998])
* Fixed: Compliance percentage computation in ComplianceLevel is not correct, and performance is not correct
    (https://issues.rudder.io/issues/20998[#20998])

==== Web - UI & UX

* Fixed: Fold and unfold all categories button not working in rules page
    (https://issues.rudder.io/issues/21079[#21079])
* Fixed: In Nodes table, the "Edit columns" button should be renamed when activated
    (https://issues.rudder.io/issues/21013[#21013])
* Fixed: Sort by status does not work on rules table
    (https://issues.rudder.io/issues/21010[#21010])

==== System techniques

* Fixed: Error in relay policies when disabling file sharing in policies
    (https://issues.rudder.io/issues/21125[#21125])
* Fixed: Rudder server 7.X generates invalid configuration for 6.X relayd
    (https://issues.rudder.io/issues/21122[#21122])
* Fixed: When updating allowed networks of a relay, rudder-cf-serverd service does not seem to be restarted
    (https://issues.rudder.io/issues/20993[#20993])

==== Techniques

* Fixed: wrong spelling of wily in apt package manager settings
    (https://issues.rudder.io/issues/21113[#21113])

==== Generic methods

* Fixed: Reporting issues when using multiple directives of the same technique on a node
    (https://issues.rudder.io/issues/21088[#21088])
* Fixed: multiple calls to file_from_template_jinja2 in audit fails
    (https://issues.rudder.io/issues/20913[#20913])

==== CI

* Fixed: Ci does not properly clean its test files
    (https://issues.rudder.io/issues/21178[#21178])
* Fixed: Improve cleanup of root-owned files in tests
    (https://issues.rudder.io/issues/21130[#21130])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.1.0 (2022-04-25)

=== Changes

==== Techniques

* Add a system-update technique for classic agents
    (https://issues.rudder.io/issues/20988[#20988])

=== Bug fixes

==== Documentation

* Fixed: Fix the relayd logging documentation
    (https://issues.rudder.io/issues/20985[#20985])

==== Miscellaneous

* Fixed: Document that port 5309 can be disable in node configuration
    (https://issues.rudder.io/issues/20982[#20982])

==== Web - Technique editor

* Fixed: The display of the DSC icon is broken in the technical editor
    (https://issues.rudder.io/issues/21016[#21016])
* Fixed: Unable to open a block within a block when it has just been drop from the list
    (https://issues.rudder.io/issues/20787[#20787])
* Fixed: When cloning a block with two identical methods, only one is cloned
    (https://issues.rudder.io/issues/21001[#21001])

==== Web - Compliance & node report

* Fixed: Techniques with no component define have no reporting
    (https://issues.rudder.io/issues/21007[#21007])
* Fixed: Techniques with no component define have no reporting
    (https://issues.rudder.io/issues/21007[#21007])
* Fixed: Bad number of component for 2 block with same name same content
    (https://issues.rudder.io/issues/21000[#21000])

==== Web - Maintenance

* Fixed: Download as zip in archives page returns a 404
    (https://issues.rudder.io/issues/20903[#20903])

==== Web - Nodes & inventories

* Fixed: Two same envvar modulo a space at begining of name leads to LDAP error when saving inventory
    (https://issues.rudder.io/issues/20984[#20984])

==== System techniques

* Fixed: when database is not on the root server, policy generation fails
    (https://issues.rudder.io/issues/20986[#20986])

==== Generic methods

* Fixed: report_if_condition method does not support expressions in its input
    (https://issues.rudder.io/issues/21011[#21011])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.1.0.rc1 (2022-04-08)

=== Changes

==== Packaging

* We should detect malformed patch in the packaging to disallow building incorrect packages
    (https://issues.rudder.io/issues/9810[#9810])

==== Documentation

* Prepare doc for 7.1
    (https://issues.rudder.io/issues/20945[#20945])

==== Generic methods

* Allow managing other types of systemd units
    (https://issues.rudder.io/issues/18553[#18553])

=== Bug fixes

==== Packaging

* Fixed: rudder-webapp requires rsync to build for RHEL
    (https://issues.rudder.io/issues/20974[#20974])

==== Agent

* Fixed: Lower the log level of the "Skipping adding class [...] as its name is equal or longer than 1024" message
    (https://issues.rudder.io/issues/20960[#20960])
* Fixed: In SLES 15, SP is view as part of version - Rudder 7.0
    (https://issues.rudder.io/issues/20950[#20950])

==== Documentation

* Fixed: Broken list of compatible OS in 7.0
    (https://issues.rudder.io/issues/20942[#20942])

==== Miscellaneous

* Fixed: Show more details in exception when parsing an invalid technique version
    (https://issues.rudder.io/issues/20976[#20976])
* Fixed: Update spring to 5.2.20 to fix CVE-2022-22965
    (https://issues.rudder.io/issues/20972[#20972])
* Fixed: Update spring to 5.2.20 to fix CVE-2022-22965
    (https://issues.rudder.io/issues/20972[#20972])
* Fixed: Add support for report id reporting with Windows agent
    (https://issues.rudder.io/issues/20963[#20963])
* Fixed: "Disable reporting" for windows method calls does produce unexpected reports
    (https://issues.rudder.io/issues/20897[#20897])

==== Web - Technique editor

* Fixed: Correct minor version condition for Ubuntu in technique editor
    (https://issues.rudder.io/issues/20973[#20973])

==== Security

* Fixed: Update jdbc postgres driver to 4.2.25 for CVE-2022-21724
    (https://issues.rudder.io/issues/20969[#20969])

==== Web - Compliance & node report

* Fixed: Removed report in compliance when calling several times the command_execution with same value
    (https://issues.rudder.io/issues/20880[#20880])

==== Web - UI & UX

* Fixed: Hide action buttons if the user does not have write permission on the Rules
    (https://issues.rudder.io/issues/20961[#20961])
* Fixed: Edit mode should be enabled by default when creating a rule
    (https://issues.rudder.io/issues/20954[#20954])
* Fixed: In the technical logs table of a node, mouse cursor should not change when hovering a Status badge
    (https://issues.rudder.io/issues/20953[#20953])
* Fixed: Remove the transparent div that covers the Properties tab and prevents interaction with it.
    (https://issues.rudder.io/issues/20951[#20951])
* Fixed: Displays a warning icon for directives that are not used by any rule.
    (https://issues.rudder.io/issues/20692[#20692])

==== API

* Fixed: Add new software update fields to API doc
    (https://issues.rudder.io/issues/20947[#20947])

==== System techniques

* Fixed: Increase default value of maxconnections
    (https://issues.rudder.io/issues/20946[#20946])

==== Generic methods

* Fixed: Broken reporting for double nested method calls
    (https://issues.rudder.io/issues/20944[#20944])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.1.0.beta2 (2022-03-25)

=== Changes

==== Web - UI & UX

* Glitch in node compliance details
    (https://issues.rudder.io/issues/20693[#20693])

==== Architecture - Internal libs

* Add name for spring security main auth configuration bean to be used by oauth2
    (https://issues.rudder.io/issues/20886[#20886])

==== Generic methods

* Generic method to raise a reinventory
    (https://issues.rudder.io/issues/5684[#5684])

=== Bug fixes

==== Security

* Fixed: Update embedded openssl to 1.1.1n
    (https://issues.rudder.io/issues/20894[#20894])

==== Documentation

* Fixed: Correct doc on windows KB update
    (https://issues.rudder.io/issues/20891[#20891])
* Fixed: backup/restore doc is incomplete
    (https://issues.rudder.io/issues/20888[#20888])

==== Web - Config management

* Fixed: Starting policy generation by hand fails if node-configuration-hashes.json
    (https://issues.rudder.io/issues/20926[#20926])
* Fixed: Built in Techniques using generic methods have no reports with new report id
    (https://issues.rudder.io/issues/20883[#20883])

==== Web - UI & UX

* Fixed: Remove the AngularJs application from the API accounts page
    (https://issues.rudder.io/issues/20901[#20901])
* Fixed: Wrong redirect url for system group in rule page
    (https://issues.rudder.io/issues/20782[#20782])
* Fixed: Applied directive doesn't show up when there is no node
    (https://issues.rudder.io/issues/20856[#20856])
* Fixed: We cannot filter rules by tag anymore
    (https://issues.rudder.io/issues/20848[#20848])
* Fixed: We cannot filter rules by tag anymore
    (https://issues.rudder.io/issues/20848[#20848])

==== Web - Technique editor

* Fixed: When editing files with the technique editor resources manager, newlines at the end of file are trimmed
    (https://issues.rudder.io/issues/19319[#19319])

==== Miscellaneous

* Fixed: Compilation warning on branche 6.2
    (https://issues.rudder.io/issues/20874[#20874])

==== System techniques

* Fixed: Set a report id for all method called within new 7.1 system techniques
    (https://issues.rudder.io/issues/20919[#20919])

==== Techniques

* Fixed: post hook for copyGitFile on windows don't report
    (https://issues.rudder.io/issues/20909[#20909])
* Fixed: dsc techniques have invalid parameters when calling generic method
    (https://issues.rudder.io/issues/20907[#20907])
* Fixed: Use report_data.component_key instead of value passed as parameter
    (https://issues.rudder.io/issues/20918[#20918])

==== Generic methods

* Fixed: Variable string from command fails when command contains control structures
    (https://issues.rudder.io/issues/20128[#20128])
* Fixed: Adapt new rudder report to work with techniques
    (https://issues.rudder.io/issues/20882[#20882])
* Fixed: All classes manipulations are ineffeccient because there are repeated 3 times
    (https://issues.rudder.io/issues/20885[#20885])
* Fixed: Broken reporting for double nested method calls
    (https://issues.rudder.io/issues/20863[#20863])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl
* Alexis TARUSSIO

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.1.0.beta1 (2022-03-17)

=== Changes

==== Web - Nodes & inventories

* Add available software updates in inventory
    (https://issues.rudder.io/issues/20663[#20663])

==== Packaging

* Remove the old technique editor
    (https://issues.rudder.io/issues/20578[#20578])
* Remove old migration logic from packaging
    (https://issues.rudder.io/issues/19766[#19766])
* Update rust to 1.58.0
    (https://issues.rudder.io/issues/20572[#20572])

==== Documentation

* Windows support should be documented as the other agents
    (https://issues.rudder.io/issues/20835[#20835])
* Add a compatibilty table for agent relay server in the documentation
    (https://issues.rudder.io/issues/20621[#20621])
* Prepare 7.1 API doc
    (https://issues.rudder.io/issues/20737[#20737])

==== Performance and scalability

* Serialization of NodeConfigurations is fairly expensive
    (https://issues.rudder.io/issues/16197[#16197])

==== Web - Compliance & node report

* Use a unique id to identify reports
    (https://issues.rudder.io/issues/20747[#20747])
* Use a unique id to identify reports
    (https://issues.rudder.io/issues/20747[#20747])

==== Language

* Document the rudder-lang and technique editor incompatibilities
    (https://issues.rudder.io/issues/20766[#20766])

==== Relay server or API

* Update relayd dependencies
    (https://issues.rudder.io/issues/20473[#20473])
* Use gumdrop instead of structopt
    (https://issues.rudder.io/issues/19790[#19790])

==== Techniques

* Reformat all the statements in userManagement technique
    (https://issues.rudder.io/issues/20878[#20878])

==== Generic methods - File Management

* Improve File from HTTP server method documentation
    (https://issues.rudder.io/issues/20810[#20810])

=== Bug fixes

==== Packaging

* Fixed: broken rudder-upgrade in 7.1
    (https://issues.rudder.io/issues/20862[#20862])
* Fixed: Delete virtualenv from webapp dependencies
    (https://issues.rudder.io/issues/20733[#20733])

==== Security

* Fixed: Vulnerability in the regex crate
    (https://issues.rudder.io/issues/20872[#20872])

==== API

* Fixed: Some api response have an id field but should'nt have one
    (https://issues.rudder.io/issues/20871[#20871])
* Fixed: Broken allowed network curl example
    (https://issues.rudder.io/issues/20844[#20844])

==== Web - UI & UX

* Fixed: Do not allow the creation of an account with an empty name or with the same name as another account
    (https://issues.rudder.io/issues/20857[#20857])
* Fixed: Rewrite the API account page in Elm
    (https://issues.rudder.io/issues/20683[#20683])

==== Architecture - Internal libs

* Fixed: Duplicate classes RudderUserDetails
    (https://issues.rudder.io/issues/20734[#20734])

==== CI

* Fixed: Don't skip tests in webapp publish
    (https://issues.rudder.io/issues/20812[#20812])
* Fixed: Missing clean in webapp publish
    (https://issues.rudder.io/issues/20772[#20772])

==== Web - Technique editor

* Fixed: Suppressed techniques coming back to life forever
    (https://issues.rudder.io/issues/19006[#19006])

==== Architecture - Refactoring

* Fixed: NodeAndPolicyServerReturnType name is misleading for search that include root server
    (https://issues.rudder.io/issues/20802[#20802])

==== Performance and scalability

* Fixed: Improve dynamic group computation speed and fix inverted searched
    (https://issues.rudder.io/issues/20716[#20716])

==== Web - Nodes & inventories

* Fixed: List of directive for the pending node is invalid
    (https://issues.rudder.io/issues/20736[#20736])

==== Architecture - Dependencies

* Fixed: Maven needs <version> tag even if version is in <dependency-management>
    (https://issues.rudder.io/issues/20727[#20727])

==== Techniques

* Fixed: Unexpected reporting in userManagement in audit when user is not present
    (https://issues.rudder.io/issues/19427[#19427])
* Fixed: Patch dsc techniques according to #20830
    (https://issues.rudder.io/issues/20832[#20832])
* Fixed: When upgrading from 6.2 to 7.0, the previous rudder logrotate configuration is not removed
    (https://issues.rudder.io/issues/20792[#20792])

==== System integration

* Fixed: Logrotate configuration for relayd is broken
    (https://issues.rudder.io/issues/20791[#20791])

==== Generic methods

* Fixed: use report_id for command_execution generic method
    (https://issues.rudder.io/issues/20864[#20864])
* Fixed: No report from sysctl generic method
    (https://issues.rudder.io/issues/20612[#20612])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

