= Change logs for Rudder 7.1

==  Rudder 7.1.10 (2023-01-25)

=== Changes


==== CI

* Improve ci notification on repaired and error
    (https://issues.rudder.io/issues/22250[#22250])

=== Bug fixes

==== Packaging

* Fixed: On rhel postinst uses yum creating a deadlock
    (https://issues.rudder.io/issues/22267[#22267])
* Fixed: Ignore RUSTSEC-2023-0001 in relayd
    (https://issues.rudder.io/issues/22249[#22249])

==== Web - Nodes & inventories

* Fixed: Inventory are rejected due to missing dependencies on the server
    (https://issues.rudder.io/issues/22257[#22257])
* Fixed: Do not trigger a group reload if last check is younger than 100 ms
    (https://issues.rudder.io/issues/22210[#22210])

==== Security

* Fixed: Workaround for CVE-2022-46176 in cargo
    (https://issues.rudder.io/issues/22294[#22294])

==== Web - UI & UX

* Fixed: Today button doesn't work in datepicker in report database page
    (https://issues.rudder.io/issues/22291[#22291])

==== Documentation

* Fixed: Documentation for Modify Settings example missing parameter
    (https://issues.rudder.io/issues/22225[#22225])

==== Relay server or API

* Fixed: Broken policies update with rsync method
    (https://issues.rudder.io/issues/22207[#22207])

==== Generic methods

* Fixed: Missing cf-promises binary to run the ncf 'quick' tests
    (https://issues.rudder.io/issues/22243[#22243])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.1.8 (2022-11-30)

=== Changes


==== Documentation

* Documentation for FQDN overriding
    (https://issues.rudder.io/issues/21952[#21952])

==== API

* Log all API errors
    (https://issues.rudder.io/issues/22124[#22124])

==== Architecture - Refactoring

* Auto-format scala code
    (https://issues.rudder.io/issues/21741[#21741])

==== Web - Maintenance

* logback.xml should contains examples of specific plugins loggers
    (https://issues.rudder.io/issues/21945[#21945])

=== Bug fixes

==== Agent

* Fixed: rudder-signature check fail to start
    (https://issues.rudder.io/issues/22097[#22097])

==== Packaging

* Fixed: Step is not correctly set in rudder upgrade script
    (https://issues.rudder.io/issues/22050[#22050])

==== Documentation

* Fixed: Windows agent exe link in install doc does not point to the right folder
    (https://issues.rudder.io/issues/22046[#22046])

==== Web - UI & UX

* Fixed: Click on graph node with "applying" compliance lead to JS error 
    (https://issues.rudder.io/issues/22134[#22134])
* Fixed: Deleting custom column in based on a property in nodes list fails
    (https://issues.rudder.io/issues/22092[#22092])
* Fixed: Missing use of contextPath in some js files
    (https://issues.rudder.io/issues/21944[#21944])

==== Miscellaneous

* Fixed: Windows generic method parameters are always written "mandatory=true" even when "mayBeEmpty" 
    (https://issues.rudder.io/issues/22126[#22126])
* Fixed: Missing epoch string in search node query from pie chart
    (https://issues.rudder.io/issues/22015[#22015])

==== Web - Technique editor

* Fixed: Errors of script that write technique.json during upgrade should be ignored
    (https://issues.rudder.io/issues/21957[#21957])
* Fixed: Focus change on the first character in input box for method's condition
    (https://issues.rudder.io/issues/21323[#21323])
* Fixed: At least on windows, technique editor parameters can not handle "_" char
    (https://issues.rudder.io/issues/14371[#14371])

==== Web - Config management

* Fixed: Creating a global parameter doesn't trigger a policy generation in Rudder 6.2, 7.1 and 7.2
    (https://issues.rudder.io/issues/22106[#22106])
* Fixed: When reading methods, if generic_methods.json does not exists, rudder should generate it
    (https://issues.rudder.io/issues/22100[#22100])

==== CI

* Fixed: Fix various builds errors after build containers update
    (https://issues.rudder.io/issues/22084[#22084])

==== Relay server or API

* Fixed: rudder_relayd filling /var/log/daemon.log (Invalid report)
    (https://issues.rudder.io/issues/22029[#22029])

==== API

* Fixed: Error ir create node API example in docs
    (https://issues.rudder.io/issues/22017[#22017])

==== Techniques

* Fixed: Update technique with / in name lead to error
    (https://issues.rudder.io/issues/21964[#21964])
* Fixed: disable other repositories in apt source technique doesn't work
    (https://issues.rudder.io/issues/21960[#21960])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Alexis TARUSSIO
* Nicolas Ecarnot

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.1.7 (2022-10-12)

=== Changes


==== Agent

* Add in the agent a feature to express that it support not sending syslog message
    (https://issues.rudder.io/issues/21771[#21771])
* Allow users to specify node hostname (FQDN)
    (https://issues.rudder.io/issues/8022[#8022])

==== System integration

* add an option to select where to log in syslog
    (https://issues.rudder.io/issues/21778[#21778])

==== Generic methods

* Add documentation for package_present update cache
    (https://issues.rudder.io/issues/21412[#21412])

=== Bug fixes

==== Security

* Fixed: CVE in Jetty 9.4.32 Rudder 6.2
    (https://issues.rudder.io/issues/21888[#21888])
* Fixed: CVE in nuprocess 2.03 and below
    (https://issues.rudder.io/issues/21893[#21893])

==== Agent

* Fixed: When cf-serverd starts it can kill an unrelated process
    (https://issues.rudder.io/issues/21100[#21100])
* Fixed: Curl build for windows agents must support schannel backend
    (https://issues.rudder.io/issues/21760[#21760])
* Fixed: Epoch is displayed in agent version in webapp
    (https://issues.rudder.io/issues/21411[#21411])
* Fixed: Broken report parsing when the key value contains line breaks
    (https://issues.rudder.io/issues/21736[#21736])
* Fixed: rudder agent check may not restart cf-execd if an agent is frozen
    (https://issues.rudder.io/issues/21774[#21774])

==== Documentation

* Fixed: Missing ubuntu 22.04 LTS supported OS for relay and server
    (https://issues.rudder.io/issues/21835[#21835])
* Fixed: Missing ubuntu 22.04 support in documentation
    (https://issues.rudder.io/issues/21721[#21721])
* Fixed: Format of target group is wrong in API doc
    (https://issues.rudder.io/issues/21935[#21935])
* Fixed: Wrong method for reload technique in API doc
    (https://issues.rudder.io/issues/21762[#21762])

==== Web - UI & UX

* Fixed: User technique should be on top in directive tree
    (https://issues.rudder.io/issues/21917[#21917])
* Fixed: Unable to sort on property in list of nodes tab
    (https://issues.rudder.io/issues/21503[#21503])
* Fixed: Input Text disapear in technic editor when entering a space with Grammarly/LanguageTool extension
    (https://issues.rudder.io/issues/21172[#21172])

==== Miscellaneous

* Fixed: Quick search does not return node name when looking for properties but node id instead
    (https://issues.rudder.io/issues/21901[#21901])

==== Web - Config management

* Fixed: Links in {directive|rule|group|technique} "tree" can not be open in a new tab
    (https://issues.rudder.io/issues/21373[#21373])
* Fixed: on a fresh 7.1 install, the number of group displayed for "Global configuration of all nodes" is invalid
    (https://issues.rudder.io/issues/21730[#21730])
* Fixed: No link to directives in a rule if the rule is not applied to some nodes
    (https://issues.rudder.io/issues/21371[#21371])

==== Architecture - Dependencies

* Fixed: Update scala-lib version due to CVE2022-36944
    (https://issues.rudder.io/issues/21869[#21869])

==== API

* Fixed: API version was not updated to API 15 for addition of node updates
    (https://issues.rudder.io/issues/21793[#21793])

==== Web - Technique editor

* Fixed: Cannot save a technique after removing a block
    (https://issues.rudder.io/issues/21768[#21768])
* Fixed: Report if condition and Environement_variable_present by default cause missing report
    (https://issues.rudder.io/issues/21752[#21752])
* Fixed: Methods markdown documentation in the technique editor are not properly rendered
    (https://issues.rudder.io/issues/21368[#21368])

==== Architecture - Internal libs

* Fixed: Syntax errors in scala files
    (https://issues.rudder.io/issues/21748[#21748])

==== System techniques

* Fixed: relayd error in logs in 7.2
    (https://issues.rudder.io/issues/21777[#21777])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


==  Rudder 7.1.6 (2022-09-05)

=== Changes


=== Bug fixes

==== Documentation

* Fixed: Installation documentation for Server has a section about sles12 but we only support sles15 as of 7.0
    (https://issues.rudder.io/issues/21420[#21420])

==== Web - Config management

* Fixed: missing list of inpacted rules when creating a directive and applying it to a rule
    (https://issues.rudder.io/issues/21671[#21671])
* Fixed: generated policies are invalid when using a generic method that doesn't exist on linux
    (https://issues.rudder.io/issues/21686[#21686])

==== API

* Fixed: API documentation on how to query node is invalid
    (https://issues.rudder.io/issues/21690[#21690])

==== Web - UI & UX

* Fixed: rollback button in even log can be clicked several time in a row and error are stacked in other screens
    (https://issues.rudder.io/issues/21429[#21429])
* Fixed: Node certificate expiration date does not follow the same format than the others dates in the UI
    (https://issues.rudder.io/issues/21367[#21367])

==== Agent

* Fixed: rudder package command fails on amazon linux
    (https://issues.rudder.io/issues/21654[#21654])

==== Techniques

* Fixed: extra & at the end of systemUpdate technique
    (https://issues.rudder.io/issues/21703[#21703])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.1.5 (2022-08-31)

=== Changes


=== Bug fixes

==== Web - UI & UX

* Fixed: Delete group category popup and directive creation popup are not closing
    (https://issues.rudder.io/issues/21666[#21666])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.1.4 (2022-08-25)

=== Changes


==== Agent

* Add a disable syslog option to cfengine
    (https://issues.rudder.io/issues/20449[#20449])

==== Security

* Skip CVE-2022-31197 in checks
    (https://issues.rudder.io/issues/21602[#21602])

==== Architecture - Internal libs

* Port policy writting test to rudder 7.1
    (https://issues.rudder.io/issues/21477[#21477])

==== Techniques

* Update techniques conditions for rhel9
    (https://issues.rudder.io/issues/21588[#21588])

=== Bug fixes

==== Packaging

* Fixed: Postinst message on AIX about hostname rudder not found
    (https://issues.rudder.io/issues/21626[#21626])

==== Web - UI & UX

* Fixed: when validating change in directive, a popup appear, but the background is only half grayed out
    (https://issues.rudder.io/issues/18575[#18575])
* Fixed: when validating change in directive, a popup appear, but the background is only half grayed out
    (https://issues.rudder.io/issues/18575[#18575])
* Fixed: once we setup the Rudder server, we have an option to go to the getting started... which doesn't work
    (https://issues.rudder.io/issues/21488[#21488])
* Fixed: Filter in URL doest work on tab list of nodes
    (https://issues.rudder.io/issues/21558[#21558])

==== Web - Nodes & inventories

* Fixed: Cannot edit/detele an empty group category
    (https://issues.rudder.io/issues/21599[#21599])

==== Web - Technique editor

* Fixed: When we change the status of a technique parameter from required to may be empty, it returns to required after saving
    (https://issues.rudder.io/issues/21560[#21560])
* Fixed: result condition are not correct in the technique editor when using properties or variables
    (https://issues.rudder.io/issues/21515[#21515])
* Fixed: Cannot delete technique in the technique editor if it contains a space in its name
    (https://issues.rudder.io/issues/21491[#21491])

==== Relay server or API

* Fixed: Unsoundness in "owning_ref"
    (https://issues.rudder.io/issues/21538[#21538])

==== Architecture - Internal libs

* Fixed: Some tests not run because of bad class name
    (https://issues.rudder.io/issues/21534[#21534])
* Fixed: Path.of is not available in java8/rudder 7.1
    (https://issues.rudder.io/issues/21524[#21524])

==== Performance and scalability

* Fixed: Improve group node computation
    (https://issues.rudder.io/issues/20758[#20758])

==== System integration

* Fixed: Correct BOM file in ps1.st used in test
    (https://issues.rudder.io/issues/21498[#21498])

==== Web - Config management

* Fixed: Concurrent delete of policy backup directory can lead to useless error
    (https://issues.rudder.io/issues/21482[#21482])

==== Documentation

* Fixed: improve contributing doc to state how to generate inventories
    (https://issues.rudder.io/issues/21476[#21476])

==== System techniques

* Fixed: Permissions are not preserved in shared-files on the relays
    (https://issues.rudder.io/issues/21617[#21617])
* Fixed: Broken reload command in apache logrotate configuration
    (https://issues.rudder.io/issues/21612[#21612])

==== Techniques

* Fixed: cron configuration restarts cron every 5 minutes on ubuntu22
    (https://issues.rudder.io/issues/21600[#21600])

==== Miscellaneous

* Fixed: Improve handling of certificates not matching the key
    (https://issues.rudder.io/issues/21616[#21616])

==== Agent

* Fixed: Properly display report_json reports in agent output
    (https://issues.rudder.io/issues/21622[#21622])

==== Generic methods

* Fixed: Broken jinja2 templating on ubuntu 22.04
    (https://issues.rudder.io/issues/21606[#21606])
* Fixed: rudder agent run man git-stash
    (https://issues.rudder.io/issues/21525[#21525])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


==  Rudder 7.1.3 (2022-07-26)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Missing dependency on gpg breaks "rudder package" command fails on minimal installs
    (https://issues.rudder.io/issues/21061[#21061])

==== Security

* Fixed: Update embedded openssl to 1.1.1q
    (https://issues.rudder.io/issues/21360[#21360])
* Fixed: URL with "%3B" (ie ';') leads to a stacktrace
    (https://issues.rudder.io/issues/21463[#21463])
* Fixed: JSESSIONID cookie should have a SameSite policy
    (https://issues.rudder.io/issues/21445[#21445])
* Fixed: Add HSTS config (commented for now)
    (https://issues.rudder.io/issues/21438[#21438])

==== Web - Nodes & inventories

* Fixed: 502 - Proxy Error when triggering Rudder agent
    (https://issues.rudder.io/issues/21170[#21170])
* Fixed: Using '{' in node property lead to error
    (https://issues.rudder.io/issues/21322[#21322])

==== Performance and scalability

* Fixed: API to fetch nodes + software times out on large instance
    (https://issues.rudder.io/issues/21241[#21241])

==== Web - UI & UX

* Fixed: Refresh Button in Rules menu under Directives Tab is not working
    (https://issues.rudder.io/issues/21264[#21264])
* Fixed: Impossible to put a Rule in a subcategory
    (https://issues.rudder.io/issues/21175[#21175])
* Fixed: Cancel button not showed within disable rule menu 
    (https://issues.rudder.io/issues/21171[#21171])

==== Web - Config management

* Fixed: Links to rules inside a directive webpage redirect to the general rule webpage
    (https://issues.rudder.io/issues/21372[#21372])

==== CI

* Fixed: Ignore rudder-lang repos in script checks
    (https://issues.rudder.io/issues/21364[#21364])

==== Miscellaneous

* Fixed: Remove unused variable newCall in JRTechniqueElem
    (https://issues.rudder.io/issues/21355[#21355])

==== Web - Compliance & node report

* Fixed: In HTTPS mode, we may have errors in logs about duplicate messages that are totally legit
    (https://issues.rudder.io/issues/21352[#21352])

==== Architecture - Refactoring

* Fixed: Tests fail due to policy mode definition in MockServices
    (https://issues.rudder.io/issues/21336[#21336])

==== Web - Technique editor

* Fixed: Prevent adding carriage return in the condition in technique editor
    (https://issues.rudder.io/issues/21126[#21126])

==== Documentation

* Fixed: Some reponses are missing in technique api doc
    (https://issues.rudder.io/issues/21304[#21304])

==== Agent

* Fixed: Deprecation warning with package methods on Ubuntu 22.04 LTS
    (https://issues.rudder.io/issues/21206[#21206])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


==  Rudder 7.1.2 (2022-06-22)

=== Changes


==== Documentation

* Add documentation to install Rudder server on Amazon linux 2
    (https://issues.rudder.io/issues/21183[#21183])
* Update api doc tooling
    (https://issues.rudder.io/issues/21232[#21232])

=== Bug fixes

==== Relay server or API

* Fixed: relayd can't connect to postgresql on Ubuntu 22.04 server
    (https://issues.rudder.io/issues/21219[#21219])
* Fixed: Missing SELinux rules for httpd on RockyLinux
    (https://issues.rudder.io/issues/20263[#20263])
* Fixed: relayd error messages about config files are lacking path information
    (https://issues.rudder.io/issues/21279[#21279])
* Fixed: Allow .ocs files as inventory
    (https://issues.rudder.io/issues/21270[#21270])
* Fixed: Missing encoding of postgresql password
    (https://issues.rudder.io/issues/21203[#21203])
* Fixed: Query seems to be ignored for pendings nodes
    (https://issues.rudder.io/issues/20281[#20281])

==== Packaging

* Fixed: parsing of system fusioninventory is invalid
    (https://issues.rudder.io/issues/21211[#21211])

==== Documentation

* Fixed: Typo in documentation to change ports used by rudder
    (https://issues.rudder.io/issues/21210[#21210])
* Fixed: Missing API documentation for technique
    (https://issues.rudder.io/issues/21254[#21254])

==== Techniques

* Fixed: When upgrading to 7.1, techniques are not upgraded to the new format and reporting issue occur
    (https://issues.rudder.io/issues/21220[#21220])
* Fixed: systemUpdate technique parameters should accept properties as input
    (https://issues.rudder.io/issues/21291[#21291])

==== Security

* Fixed: Ignore CVE  CVE-2022-22978 that will not be fixed in 6.1/6.2 dependencies
    (https://issues.rudder.io/issues/21263[#21263])
* Fixed: Upgrade spring-security to 5.5.8 to fix CVE 2022-22978
    (https://issues.rudder.io/issues/21237[#21237])

==== Web - Config management

* Fixed: GetMetadataContent does not correctly retrieve content when a revision is given
    (https://issues.rudder.io/issues/21260[#21260])

==== Architecture - Internal libs

* Fixed: Query string is not correctly parsed in test API framework
    (https://issues.rudder.io/issues/21253[#21253])

==== Web - Technique editor

* Fixed: When a technique is not in the active techique tree, it can't be deleted in editor
    (https://issues.rudder.io/issues/21119[#21119])

==== Web - UI & UX

* Fixed: Missing icon in technical logs for error messages
    (https://issues.rudder.io/issues/18918[#18918])

==== Performance and scalability

* Fixed: Improve performance of display for agent version on homepage
    (https://issues.rudder.io/issues/21230[#21230])

==== rudderc

* Fixed: During upgrade of techniques, rudderc is used even if disabled
    (https://issues.rudder.io/issues/21229[#21229])

==== CI

* Fixed: Race condition between elm builds
    (https://issues.rudder.io/issues/21156[#21156])

==== Generic methods

* Fixed: The mustache template examples in our documentation do not respect the mustache standard
    (https://issues.rudder.io/issues/21286[#21286])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


==  Rudder 7.1.1 (2022-05-31)

=== Changes


==== Plugins integration

* Add windows support to the inventory software update section
    (https://issues.rudder.io/issues/21067[#21067])

==== Web - UI & UX

* Provide a version of the OS icons without text
    (https://issues.rudder.io/issues/21071[#21071])
* Update css related to the change validation plugin
    (https://issues.rudder.io/issues/21052[#21052])

==== Server components

* allow a user to pass a password to server create-user command
    (https://issues.rudder.io/issues/20675[#20675])

=== Bug fixes

==== Packaging

* Fixed: Embed openssl on ubuntu 22.04
    (https://issues.rudder.io/issues/21040[#21040])
* Fixed: ubuntu22 build options are missing
    (https://issues.rudder.io/issues/21036[#21036])
* Fixed: Ubuntu 22 needs python3 as build dependency for rudder-agent
    (https://issues.rudder.io/issues/21035[#21035])
* Fixed: Backup ca.cert like other cert files
    (https://issues.rudder.io/issues/21143[#21143])

==== Documentation

* Fixed: Documentation about certificate handling during uprade is not great
    (https://issues.rudder.io/issues/21129[#21129])
* Fixed: Mark 7.1 as released in the docs
    (https://issues.rudder.io/issues/21030[#21030])

==== Performance and scalability

* Fixed: Adapt rule details to have the list of directives/nodes that appear faster
    (https://issues.rudder.io/issues/21081[#21081])
* Fixed: The way groups are fetched when responding to API compliance is inefficient
    (https://issues.rudder.io/issues/21028[#21028])

==== Relay server or API

* Fixed: Huge broken logs in relayd
    (https://issues.rudder.io/issues/21157[#21157])

==== Security

* Fixed: security checks fails because of request to sonatype oss index
    (https://issues.rudder.io/issues/21179[#21179])
* Fixed: Fix some cve in dependencies 
    (https://issues.rudder.io/issues/21169[#21169])
* Fixed: Ignore some CVE that cannot be fixed in 6.1 branch
    (https://issues.rudder.io/issues/21103[#21103])
* Fixed: Ignore some CVE that cannot be fixed in 6.1 branch
    (https://issues.rudder.io/issues/21103[#21103])
* Fixed: Don't display oauth/oidc client secret in logs
    (https://issues.rudder.io/issues/21077[#21077])
* Fixed: Ignore CVEs for spring-ldap-core
    (https://issues.rudder.io/issues/21027[#21027])
* Fixed: Update spring and logback version because of new CVE
    (https://issues.rudder.io/issues/21022[#21022])

==== System integration

* Fixed: Root log explain_compliance is in debug by default
    (https://issues.rudder.io/issues/21166[#21166])
* Fixed: rudder package does not sort plugin version correctly
    (https://issues.rudder.io/issues/21121[#21121])

==== Web - Nodes & inventories

* Fixed: Criteria not working when filter on IP adress and GoupID in group page
    (https://issues.rudder.io/issues/21144[#21144])
* Fixed: Sometime inventory processing is not done when inventory is receveived
    (https://issues.rudder.io/issues/19585[#19585])
* Fixed: List of nodes by version does not include windows nodes
    (https://issues.rudder.io/issues/17728[#17728])

==== Web - Technique editor

* Fixed: Filter on agent type on technique editor is not correctly shown
    (https://issues.rudder.io/issues/21160[#21160])

==== API

* Fixed: Directive and rule revision is not parsed in API
    (https://issues.rudder.io/issues/21150[#21150])
* Fixed: Rudder incorectly parse URL with a '+' in the path into spaces
    (https://issues.rudder.io/issues/20943[#20943])
* Fixed: Deleting a rule's category leeds to an error
    (https://issues.rudder.io/issues/21080[#21080])
* Fixed: Update api doc tool chain
    (https://issues.rudder.io/issues/21073[#21073])
* Fixed: Generation not started when modifying authorized network via API
    (https://issues.rudder.io/issues/20979[#20979])

==== Web - Config management

* Fixed: condition from windows node does not take condition from blocks
    (https://issues.rudder.io/issues/21108[#21108])
* Fixed: Revision are taken into account during generation
    (https://issues.rudder.io/issues/20929[#20929])

==== Architecture - Refactoring

* Fixed: Scala does not really supports [_:P] syntax
    (https://issues.rudder.io/issues/21107[#21107])
* Fixed: Update TechniqueVersion to conform to method visibility
    (https://issues.rudder.io/issues/21106[#21106])

==== Web - Compliance & node report

* Fixed: Compliance percentage computation in ComplianceLevel is not correct, and performance is not correct
    (https://issues.rudder.io/issues/20998[#20998])
* Fixed: Compliance percentage computation in ComplianceLevel is not correct, and performance is not correct
    (https://issues.rudder.io/issues/20998[#20998])

==== Web - UI & UX

* Fixed: Fold and unfold all categories button not working in rules page
    (https://issues.rudder.io/issues/21079[#21079])
* Fixed: In Nodes table, the "Edit columns" button should be renamed when activated
    (https://issues.rudder.io/issues/21013[#21013])
* Fixed: Sort by status does not work on rules table
    (https://issues.rudder.io/issues/21010[#21010])

==== System techniques

* Fixed: Error in relay policies when disabling file sharing in policies
    (https://issues.rudder.io/issues/21125[#21125])
* Fixed: Rudder server 7.X generates invalid configuration for 6.X relayd
    (https://issues.rudder.io/issues/21122[#21122])
* Fixed: When updating allowed networks of a relay, rudder-cf-serverd service does not seem to be restarted
    (https://issues.rudder.io/issues/20993[#20993])

==== Techniques

* Fixed: wrong spelling of wily in apt package manager settings
    (https://issues.rudder.io/issues/21113[#21113])

==== Generic methods

* Fixed: Reporting issues when using multiple directives of the same technique on a node
    (https://issues.rudder.io/issues/21088[#21088])
* Fixed: multiple calls to file_from_template_jinja2 in audit fails
    (https://issues.rudder.io/issues/20913[#20913])

==== CI

* Fixed: Ci does not properly clean its test files
    (https://issues.rudder.io/issues/21178[#21178])
* Fixed: Improve cleanup of root-owned files in tests
    (https://issues.rudder.io/issues/21130[#21130])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.1.9 (2022-12-19)

=== Changes


==== Generic methods

* Add support for Snap package manager to package methods
    (https://issues.rudder.io/issues/22055[#22055])

=== Bug fixes

==== Packaging

* Fixed: AIX agent postinst doesn't install a crontab for "rudder agent check"
    (https://issues.rudder.io/issues/22167[#22167])

==== Web - Nodes & inventories

* Fixed: Authorize "_" (underscore) in hostname / fqdn
    (https://issues.rudder.io/issues/22186[#22186])

==== Web - Config management

* Fixed: Cannot deploy changes on a group where properties are defined with a validated user
    (https://issues.rudder.io/issues/22178[#22178])

==== Server components

* Fixed: Command seq not found in crontab on AIX
    (https://issues.rudder.io/issues/21858[#21858])

==== System techniques

* Fixed: crontab edition is ignored on AIX
    (https://issues.rudder.io/issues/22168[#22168])

==== Agent

* Fixed: "rudder agent check -q" always exits with 1
    (https://issues.rudder.io/issues/22166[#22166])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.1.0 (2022-04-25)

=== Changes

==== Techniques

* Add a system-update technique for classic agents
    (https://issues.rudder.io/issues/20988[#20988])

=== Bug fixes

==== Documentation

* Fixed: Fix the relayd logging documentation
    (https://issues.rudder.io/issues/20985[#20985])

==== Miscellaneous

* Fixed: Document that port 5309 can be disable in node configuration
    (https://issues.rudder.io/issues/20982[#20982])

==== Web - Technique editor

* Fixed: The display of the DSC icon is broken in the technical editor
    (https://issues.rudder.io/issues/21016[#21016])
* Fixed: Unable to open a block within a block when it has just been drop from the list
    (https://issues.rudder.io/issues/20787[#20787])
* Fixed: When cloning a block with two identical methods, only one is cloned
    (https://issues.rudder.io/issues/21001[#21001])

==== Web - Compliance & node report

* Fixed: Techniques with no component define have no reporting
    (https://issues.rudder.io/issues/21007[#21007])
* Fixed: Techniques with no component define have no reporting
    (https://issues.rudder.io/issues/21007[#21007])
* Fixed: Bad number of component for 2 block with same name same content
    (https://issues.rudder.io/issues/21000[#21000])

==== Web - Maintenance

* Fixed: Download as zip in archives page returns a 404
    (https://issues.rudder.io/issues/20903[#20903])

==== Web - Nodes & inventories

* Fixed: Two same envvar modulo a space at begining of name leads to LDAP error when saving inventory
    (https://issues.rudder.io/issues/20984[#20984])

==== System techniques

* Fixed: when database is not on the root server, policy generation fails
    (https://issues.rudder.io/issues/20986[#20986])

==== Generic methods

* Fixed: report_if_condition method does not support expressions in its input
    (https://issues.rudder.io/issues/21011[#21011])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.1.0.rc1 (2022-04-08)

=== Changes

==== Packaging

* We should detect malformed patch in the packaging to disallow building incorrect packages
    (https://issues.rudder.io/issues/9810[#9810])

==== Documentation

* Prepare doc for 7.1
    (https://issues.rudder.io/issues/20945[#20945])

==== Generic methods

* Allow managing other types of systemd units
    (https://issues.rudder.io/issues/18553[#18553])

=== Bug fixes

==== Packaging

* Fixed: rudder-webapp requires rsync to build for RHEL
    (https://issues.rudder.io/issues/20974[#20974])

==== Agent

* Fixed: Lower the log level of the "Skipping adding class [...] as its name is equal or longer than 1024" message
    (https://issues.rudder.io/issues/20960[#20960])
* Fixed: In SLES 15, SP is view as part of version - Rudder 7.0
    (https://issues.rudder.io/issues/20950[#20950])

==== Documentation

* Fixed: Broken list of compatible OS in 7.0
    (https://issues.rudder.io/issues/20942[#20942])

==== Miscellaneous

* Fixed: Show more details in exception when parsing an invalid technique version
    (https://issues.rudder.io/issues/20976[#20976])
* Fixed: Update spring to 5.2.20 to fix CVE-2022-22965
    (https://issues.rudder.io/issues/20972[#20972])
* Fixed: Update spring to 5.2.20 to fix CVE-2022-22965
    (https://issues.rudder.io/issues/20972[#20972])
* Fixed: Add support for report id reporting with Windows agent
    (https://issues.rudder.io/issues/20963[#20963])
* Fixed: "Disable reporting" for windows method calls does produce unexpected reports
    (https://issues.rudder.io/issues/20897[#20897])

==== Web - Technique editor

* Fixed: Correct minor version condition for Ubuntu in technique editor
    (https://issues.rudder.io/issues/20973[#20973])

==== Security

* Fixed: Update jdbc postgres driver to 4.2.25 for CVE-2022-21724
    (https://issues.rudder.io/issues/20969[#20969])

==== Web - Compliance & node report

* Fixed: Removed report in compliance when calling several times the command_execution with same value
    (https://issues.rudder.io/issues/20880[#20880])

==== Web - UI & UX

* Fixed: Hide action buttons if the user does not have write permission on the Rules
    (https://issues.rudder.io/issues/20961[#20961])
* Fixed: Edit mode should be enabled by default when creating a rule
    (https://issues.rudder.io/issues/20954[#20954])
* Fixed: In the technical logs table of a node, mouse cursor should not change when hovering a Status badge
    (https://issues.rudder.io/issues/20953[#20953])
* Fixed: Remove the transparent div that covers the Properties tab and prevents interaction with it.
    (https://issues.rudder.io/issues/20951[#20951])
* Fixed: Displays a warning icon for directives that are not used by any rule.
    (https://issues.rudder.io/issues/20692[#20692])

==== API

* Fixed: Add new software update fields to API doc
    (https://issues.rudder.io/issues/20947[#20947])

==== System techniques

* Fixed: Increase default value of maxconnections
    (https://issues.rudder.io/issues/20946[#20946])

==== Generic methods

* Fixed: Broken reporting for double nested method calls
    (https://issues.rudder.io/issues/20944[#20944])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.1.0.beta2 (2022-03-25)

=== Changes

==== Web - UI & UX

* Glitch in node compliance details
    (https://issues.rudder.io/issues/20693[#20693])

==== Architecture - Internal libs

* Add name for spring security main auth configuration bean to be used by oauth2
    (https://issues.rudder.io/issues/20886[#20886])

==== Generic methods

* Generic method to raise a reinventory
    (https://issues.rudder.io/issues/5684[#5684])

=== Bug fixes

==== Security

* Fixed: Update embedded openssl to 1.1.1n
    (https://issues.rudder.io/issues/20894[#20894])

==== Documentation

* Fixed: Correct doc on windows KB update
    (https://issues.rudder.io/issues/20891[#20891])
* Fixed: backup/restore doc is incomplete
    (https://issues.rudder.io/issues/20888[#20888])

==== Web - Config management

* Fixed: Starting policy generation by hand fails if node-configuration-hashes.json
    (https://issues.rudder.io/issues/20926[#20926])
* Fixed: Built in Techniques using generic methods have no reports with new report id
    (https://issues.rudder.io/issues/20883[#20883])

==== Web - UI & UX

* Fixed: Remove the AngularJs application from the API accounts page
    (https://issues.rudder.io/issues/20901[#20901])
* Fixed: Wrong redirect url for system group in rule page
    (https://issues.rudder.io/issues/20782[#20782])
* Fixed: Applied directive doesn't show up when there is no node
    (https://issues.rudder.io/issues/20856[#20856])
* Fixed: We cannot filter rules by tag anymore
    (https://issues.rudder.io/issues/20848[#20848])
* Fixed: We cannot filter rules by tag anymore
    (https://issues.rudder.io/issues/20848[#20848])

==== Web - Technique editor

* Fixed: When editing files with the technique editor resources manager, newlines at the end of file are trimmed
    (https://issues.rudder.io/issues/19319[#19319])

==== Miscellaneous

* Fixed: Compilation warning on branche 6.2
    (https://issues.rudder.io/issues/20874[#20874])

==== System techniques

* Fixed: Set a report id for all method called within new 7.1 system techniques
    (https://issues.rudder.io/issues/20919[#20919])

==== Techniques

* Fixed: post hook for copyGitFile on windows don't report
    (https://issues.rudder.io/issues/20909[#20909])
* Fixed: dsc techniques have invalid parameters when calling generic method
    (https://issues.rudder.io/issues/20907[#20907])
* Fixed: Use report_data.component_key instead of value passed as parameter
    (https://issues.rudder.io/issues/20918[#20918])

==== Generic methods

* Fixed: Variable string from command fails when command contains control structures
    (https://issues.rudder.io/issues/20128[#20128])
* Fixed: Adapt new rudder report to work with techniques
    (https://issues.rudder.io/issues/20882[#20882])
* Fixed: All classes manipulations are ineffeccient because there are repeated 3 times
    (https://issues.rudder.io/issues/20885[#20885])
* Fixed: Broken reporting for double nested method calls
    (https://issues.rudder.io/issues/20863[#20863])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florian Heigl
* Alexis TARUSSIO

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.1.0.beta1 (2022-03-17)

=== Changes

==== Web - Nodes & inventories

* Add available software updates in inventory
    (https://issues.rudder.io/issues/20663[#20663])

==== Packaging

* Remove the old technique editor
    (https://issues.rudder.io/issues/20578[#20578])
* Remove old migration logic from packaging
    (https://issues.rudder.io/issues/19766[#19766])
* Update rust to 1.58.0
    (https://issues.rudder.io/issues/20572[#20572])

==== Documentation

* Windows support should be documented as the other agents
    (https://issues.rudder.io/issues/20835[#20835])
* Add a compatibilty table for agent relay server in the documentation
    (https://issues.rudder.io/issues/20621[#20621])
* Prepare 7.1 API doc
    (https://issues.rudder.io/issues/20737[#20737])

==== Performance and scalability

* Serialization of NodeConfigurations is fairly expensive
    (https://issues.rudder.io/issues/16197[#16197])

==== Web - Compliance & node report

* Use a unique id to identify reports
    (https://issues.rudder.io/issues/20747[#20747])
* Use a unique id to identify reports
    (https://issues.rudder.io/issues/20747[#20747])

==== Language

* Document the rudder-lang and technique editor incompatibilities
    (https://issues.rudder.io/issues/20766[#20766])

==== Relay server or API

* Update relayd dependencies
    (https://issues.rudder.io/issues/20473[#20473])
* Use gumdrop instead of structopt
    (https://issues.rudder.io/issues/19790[#19790])

==== Techniques

* Reformat all the statements in userManagement technique
    (https://issues.rudder.io/issues/20878[#20878])

==== Generic methods - File Management

* Improve File from HTTP server method documentation
    (https://issues.rudder.io/issues/20810[#20810])

=== Bug fixes

==== Packaging

* Fixed: broken rudder-upgrade in 7.1
    (https://issues.rudder.io/issues/20862[#20862])
* Fixed: Delete virtualenv from webapp dependencies
    (https://issues.rudder.io/issues/20733[#20733])

==== Security

* Fixed: Vulnerability in the regex crate
    (https://issues.rudder.io/issues/20872[#20872])

==== API

* Fixed: Some api response have an id field but should'nt have one
    (https://issues.rudder.io/issues/20871[#20871])
* Fixed: Broken allowed network curl example
    (https://issues.rudder.io/issues/20844[#20844])

==== Web - UI & UX

* Fixed: Do not allow the creation of an account with an empty name or with the same name as another account
    (https://issues.rudder.io/issues/20857[#20857])
* Fixed: Rewrite the API account page in Elm
    (https://issues.rudder.io/issues/20683[#20683])

==== Architecture - Internal libs

* Fixed: Duplicate classes RudderUserDetails
    (https://issues.rudder.io/issues/20734[#20734])

==== CI

* Fixed: Don't skip tests in webapp publish
    (https://issues.rudder.io/issues/20812[#20812])
* Fixed: Missing clean in webapp publish
    (https://issues.rudder.io/issues/20772[#20772])

==== Web - Technique editor

* Fixed: Suppressed techniques coming back to life forever
    (https://issues.rudder.io/issues/19006[#19006])

==== Architecture - Refactoring

* Fixed: NodeAndPolicyServerReturnType name is misleading for search that include root server
    (https://issues.rudder.io/issues/20802[#20802])

==== Performance and scalability

* Fixed: Improve dynamic group computation speed and fix inverted searched
    (https://issues.rudder.io/issues/20716[#20716])

==== Web - Nodes & inventories

* Fixed: List of directive for the pending node is invalid
    (https://issues.rudder.io/issues/20736[#20736])

==== Architecture - Dependencies

* Fixed: Maven needs <version> tag even if version is in <dependency-management>
    (https://issues.rudder.io/issues/20727[#20727])

==== Techniques

* Fixed: Unexpected reporting in userManagement in audit when user is not present
    (https://issues.rudder.io/issues/19427[#19427])
* Fixed: Patch dsc techniques according to #20830
    (https://issues.rudder.io/issues/20832[#20832])
* Fixed: When upgrading from 6.2 to 7.0, the previous rudder logrotate configuration is not removed
    (https://issues.rudder.io/issues/20792[#20792])

==== System integration

* Fixed: Logrotate configuration for relayd is broken
    (https://issues.rudder.io/issues/20791[#20791])

==== Generic methods

* Fixed: use report_id for command_execution generic method
    (https://issues.rudder.io/issues/20864[#20864])
* Fixed: No report from sysctl generic method
    (https://issues.rudder.io/issues/20612[#20612])

=== Release notes

This is a bug fix release in the 7.1 series and therefore all installations of 7.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

