= Changelogs for Rudder plugin api-authorizations 6.0.\* versions

== api-authorizations-6.0-1.6 (2020-02-27)

=== Changes

=== Bug fixes

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== api-authorizations-6.0-1.5 (2019-12-09)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: Take care of number of nodes in plugin license check
    (https://issues.rudder.io/issues/15273[#15273])

==== Miscellaneous

* Fixed: Correction on plugins for parent status check 
    (https://issues.rudder.io/issues/13087[#13087])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

