= Changelogs for Rudder plugin branding 6.0.\* versions

== branding-6.0-1.7 (2020-07-20)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Empty footer in sidebar 
    (https://issues.rudder.io/issues/17436[#17436])

=== Release notes

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-6.0-1.6 (2020-04-23)

=== Changes

==== Miscellaneous

* Customize logo
    (https://issues.rudder.io/issues/16671[#16671])

=== Bug fixes

==== Documentation

* Fixed: Ansible plugin doc has incorrect title
    (https://issues.rudder.io/issues/16985[#16985])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-6.0-1.5 (2020-02-27)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Transparency leads to broken display
    (https://issues.rudder.io/issues/12949[#12949])

==== Refactoring

* Fixed: Port public plugins to scala 2.13
    (https://issues.rudder.io/issues/16562[#16562])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-6.0-1.4 (2019-12-09)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: Release plugin for 6.0
    (https://issues.rudder.io/issues/16370[#16370])
* Fixed: Wrong README extension for branding  scale-out-relay user-management
    (https://issues.rudder.io/issues/15394[#15394])
* Fixed: Take care of number of nodes in plugin license check
    (https://issues.rudder.io/issues/15273[#15273])

==== Documentation

* Fixed:  Update link in readme to rudder.io and missing smarttag for create-node-api
    (https://issues.rudder.io/issues/15306[#15306])
* Fixed:  Update link in readme to rudder.io and missing smarttag for create-node-api
    (https://issues.rudder.io/issues/15306[#15306])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

