= Changelogs for Rudder plugin centreon 6.0.\* versions

== centreon-6.0-1.2 (2019-12-09)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Plugin depends on python libs that are not listed in the packaging nor in the doc
    (https://issues.rudder.io/issues/16090[#16090])

==== Documentation

* Fixed:  Update link in readme to rudder.io and missing smarttag for create-node-api
    (https://issues.rudder.io/issues/15306[#15306])
* Fixed:  Update link in readme to rudder.io and missing smarttag for create-node-api
    (https://issues.rudder.io/issues/15306[#15306])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

