= Changelogs for Rudder plugin change-validation 6.0.\* versions

== change-validation-6.0-1.5 (2020-02-27)

=== Changes

=== Bug fixes

==== Refactoring

* Fixed: Port public plugins to scala 2.13
    (https://issues.rudder.io/issues/16562[#16562])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-6.0-1.4 (2019-12-09)

=== Changes

==== Refactoring

* Plugins don't compile anymore
    (https://issues.rudder.io/issues/16351[#16351])

=== Bug fixes

==== Packaging

* Fixed: Update change validation and hello world to Rudder 6.0
    (https://issues.rudder.io/issues/16132[#16132])
* Fixed: Take care of number of nodes in plugin license check
    (https://issues.rudder.io/issues/15273[#15273])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

