= Changelogs for Rudder plugin consul 6.0.\* versions

== consul-6.0-1.0 (2020-04-23)

=== Changes

=== Bug fixes

==== Packaging

* Fixed: Plugins should not use a hardcoded path for curl
    (https://issues.rudder.io/issues/17042[#17042])
* Fixed: Plugins should not use a hardcoded path for curl
    (https://issues.rudder.io/issues/17042[#17042])

==== Miscellaneous

* Fixed: Add documentation to Consul plugin integration with Rudder
    (https://issues.rudder.io/issues/17092[#17092])
* Fixed: Add documentation to Consul plugin integration with Rudder
    (https://issues.rudder.io/issues/17092[#17092])
* Fixed: Add documentation to Consul plugin integration with Rudder
    (https://issues.rudder.io/issues/17092[#17092])
* Fixed: Add documentation to Consul plugin integration with Rudder
    (https://issues.rudder.io/issues/17092[#17092])
* Fixed: Add documentation to Consul plugin integration with Rudder
    (https://issues.rudder.io/issues/17092[#17092])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

