= Changelogs for Rudder plugin create-node-api 6.0.\* versions

== create-node-api-6.0-1.2 (2020-02-27)

=== Changes

=== Bug fixes

==== Refactoring

* Fixed: Port public plugins to scala 2.13
    (https://issues.rudder.io/issues/16562[#16562])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== create-node-api-6.0-1.1 (2019-12-09)

=== Changes

=== Bug fixes

==== Documentation

* Fixed: Typo in doc example of node-create-api plugin
    (https://issues.rudder.io/issues/16165[#16165])

==== Miscellaneous

* Fixed: Invalid name for certificate value in JSON
    (https://issues.rudder.io/issues/15395[#15395])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

