= Changelogs for Rudder plugin cve 6.0.\* versions

== cve-6.0-1.0 (2020-06-19)

=== Changes

==== Miscellaneous

* Add introduction to cve page and minor improvements
    (https://issues.rudder.io/issues/17449[#17449])
* Remove all mentions to Vulners in code and log
    (https://issues.rudder.io/issues/17327[#17327])
* Add notification to CVE plugin
    (https://issues.rudder.io/issues/17014[#17014])
* Configure Vulners within the UI
    (https://issues.rudder.io/issues/16982[#16982])
* Update cve by downloading CVE definition file
    (https://issues.rudder.io/issues/16901[#16901])

=== Bug fixes

==== Miscellaneous

* Fixed: Trigger cve check on node update / new node acceptation
    (https://issues.rudder.io/issues/17076[#17076])
* Fixed: Use vulners API key and adapt to nvd new json format
    (https://issues.rudder.io/issues/16893[#16893])
* Fixed: Display hostname first before node id in cve lists
    (https://issues.rudder.io/issues/16894[#16894])

=== Release notes

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-6.0-0.3 (2020-02-27)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Port private plugins to scala 2.13
    (https://issues.rudder.io/issues/16564[#16564])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-6.0-0.2 (2019-12-09)

=== Changes

=== Bug fixes

==== Packaging

* Fixed:  Update change validation and hello world to Rudder 6.0 (private plugins)
    (https://issues.rudder.io/issues/16134[#16134])
* Fixed:  Take care of number of nodes in plugin license check (private plugins)
    (https://issues.rudder.io/issues/15288[#15288])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

