= Changelogs for Rudder plugin datasources 6.0.\* versions

== datasources-6.0-1.7 (2020-02-27)

=== Changes

=== Bug fixes

==== Refactoring

* Fixed: Port public plugins to scala 2.13
    (https://issues.rudder.io/issues/16562[#16562])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-6.0-1.6 (2019-12-09)

=== Changes

==== Refactoring

* Plugins don't compile anymore
    (https://issues.rudder.io/issues/16351[#16351])

=== Bug fixes

==== Packaging

* Fixed: Release plugin for 6.0
    (https://issues.rudder.io/issues/16370[#16370])
* Fixed: Fix tests in plugins for branch 5.1
    (https://issues.rudder.io/issues/15468[#15468])
* Fixed: Take care of number of nodes in plugin license check
    (https://issues.rudder.io/issues/15273[#15273])

==== Miscellaneous

* Fixed: Datasources is not compatible with Rudder 6.0
    (https://issues.rudder.io/issues/16131[#16131])

==== Documentation

* Fixed: Compress images in plugins
    (https://issues.rudder.io/issues/15620[#15620])
* Fixed:  Update link in readme to rudder.io and missing smarttag for create-node-api
    (https://issues.rudder.io/issues/15306[#15306])
* Fixed:  Update link in readme to rudder.io and missing smarttag for create-node-api
    (https://issues.rudder.io/issues/15306[#15306])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

