= Changelogs for Rudder plugin dsc 6.0.\* versions

== dsc-6.0-1.19 (2020-09-09)

=== Changes

=== Bug fixes

==== ncf

* Fixed: handle default values and add sha 512 to file from shared folder generic method
    (https://issues.rudder.io/issues/18179[#18179])
* Fixed: Make the "rudder agent test" command able to call for a specific test
    (https://issues.rudder.io/issues/18148[#18148])
* Fixed: Add a package management GM for windows
    (https://issues.rudder.io/issues/17142[#17142])
* Fixed: Rename the DSC_report method to DSC_internal_report
    (https://issues.rudder.io/issues/17158[#17158])
* Fixed: DSC_ressource method should handle exception since it is very prone to raising some
    (https://issues.rudder.io/issues/17137[#17137])
* Fixed: Refactor _rudder_common_report and enable nested logs
    (https://issues.rudder.io/issues/16822[#16822])
* Fixed: Add a File-ensure-line-absent GM
    (https://issues.rudder.io/issues/17090[#17090])
* Fixed: DSC_report method is missing its HereString parameter type
    (https://issues.rudder.io/issues/17068[#17068])
* Fixed: Condition_from_command method does not execute in audit mode
    (https://issues.rudder.io/issues/17058[#17058])
* Fixed: backport DSC_report method
    (https://issues.rudder.io/issues/17054[#17054])

==== Packaging

* Fixed: Fresh install only modifies Systel env variables and not the current process one
    (https://issues.rudder.io/issues/18146[#18146])
* Fixed: At install time, agent installer asks the user for a component name
    (https://issues.rudder.io/issues/17136[#17136])

==== CLI

* Fixed: When an inventory is send, the agent also send an end execution report which should be sent
    (https://issues.rudder.io/issues/18031[#18031])
* Fixed: Add health command to the agent
    (https://issues.rudder.io/issues/17915[#17915])

==== Miscellaneous

* Fixed: Parameters value in the technique editor are changed if they contain a "_" char
    (https://issues.rudder.io/issues/18022[#18022])

==== System integration

* Fixed: Global const variables are not defined on the windows agent
    (https://issues.rudder.io/issues/17370[#17370])
* Fixed: update is impossible due to tls incompatibility
    (https://issues.rudder.io/issues/16100[#16100])

=== Release notes

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-6.0-1.18 (2020-07-20)

=== Changes

=== Bug fixes

==== ncf

* Fixed: Rename the DSC_report method to DSC_internal_report
    (https://issues.rudder.io/issues/17158[#17158])
* Fixed: DSC_ressource method should handle exception since it is very prone to raising some
    (https://issues.rudder.io/issues/17137[#17137])
* Fixed: Refactor _rudder_common_report and enable nested logs
    (https://issues.rudder.io/issues/16822[#16822])
* Fixed: Add a File-ensure-line-absent GM
    (https://issues.rudder.io/issues/17090[#17090])
* Fixed: DSC_report method is missing its HereString parameter type
    (https://issues.rudder.io/issues/17068[#17068])
* Fixed: Condition_from_command method does not execute in audit mode
    (https://issues.rudder.io/issues/17058[#17058])
* Fixed: backport DSC_report method
    (https://issues.rudder.io/issues/17054[#17054])

==== Packaging

* Fixed: At install time, agent installer asks the user for a component name
    (https://issues.rudder.io/issues/17136[#17136])

==== System integration

* Fixed: update is impossible due to tls incompatibility
    (https://issues.rudder.io/issues/16100[#16100])

=== Release notes

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-6.0-1.17 (2020-02-27)

=== Changes

=== Bug fixes

==== Rudder web app

* Fixed: broken test on dsc webapp
    (https://issues.rudder.io/issues/16770[#16770])
* Fixed: New plugin release does not generated correctly the policies for 6.0
    (https://issues.rudder.io/issues/16625[#16625])

==== Packaging

* Fixed: Windows postinst fails to run properly
    (https://issues.rudder.io/issues/16626[#16626])
* Fixed: Port DSC plugin to scala 2.13
    (https://issues.rudder.io/issues/16563[#16563])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

