= Changelogs for Rudder plugin vault 6.0.\* versions

== vault-6.0-1.3 (2020-07-20)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Typo in vault documentation
    (https://issues.rudder.io/issues/17714[#17714])

==== Documentation

* Fixed: Clean pugin install docs
    (https://issues.rudder.io/issues/17276[#17276])

=== Release notes

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== vault-6.0-1.2 (2020-04-23)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Variable from vault file must contains two [data] levels in mergedata
    (https://issues.rudder.io/issues/17103[#17103])
* Fixed: Improve Vault Doc
    (https://issues.rudder.io/issues/17096[#17096])
* Fixed: Improve Vault Doc
    (https://issues.rudder.io/issues/17096[#17096])
* Fixed: Improve Vault Doc
    (https://issues.rudder.io/issues/17096[#17096])
* Fixed: Make the generic method usable with self-signed TLS
    (https://issues.rudder.io/issues/17083[#17083])
* Fixed: Make the generic method usable with self-signed TLS
    (https://issues.rudder.io/issues/17083[#17083])
* Fixed: Make the generic method usable with self-signed TLS
    (https://issues.rudder.io/issues/17083[#17083])
* Fixed: Make the generic method usable with self-signed TLS
    (https://issues.rudder.io/issues/17083[#17083])
* Fixed: Make the generic method usable with self-signed TLS
    (https://issues.rudder.io/issues/17083[#17083])
* Fixed: Make the generic method usable with self-signed TLS
    (https://issues.rudder.io/issues/17083[#17083])
* Fixed: Make the generic method usable with self-signed TLS
    (https://issues.rudder.io/issues/17083[#17083])
* Fixed: Make the generic method usable with self-signed TLS
    (https://issues.rudder.io/issues/17083[#17083])
* Fixed: Make the generic method usable with self-signed TLS
    (https://issues.rudder.io/issues/17083[#17083])
* Fixed: Make the generic method usable with self-signed TLS
    (https://issues.rudder.io/issues/17083[#17083])
* Fixed: Generic method path parameter description change
    (https://issues.rudder.io/issues/17011[#17011])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Improving Vault documentation
    (https://issues.rudder.io/issues/16981[#16981])
* Fixed: Always repaired state while executing agent 
    (https://issues.rudder.io/issues/16973[#16973])
* Fixed: Always repaired state while executing agent 
    (https://issues.rudder.io/issues/16973[#16973])
* Fixed: Server unreachable error while executing agent on node
    (https://issues.rudder.io/issues/16951[#16951])

==== Packaging

* Fixed: Plugins should not use a hardcoded path for curl
    (https://issues.rudder.io/issues/17042[#17042])

==== Documentation

* Fixed: Make images displayable in plugin doc on github
    (https://issues.rudder.io/issues/16989[#16989])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:


This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== vault-6.0-1.1 (2019-12-09)

=== Changes

==== Miscellaneous

* Add TLS cert/key auth to the Vault plugin
    (https://issues.rudder.io/issues/12978[#12978])

=== Bug fixes

==== Documentation

* Fixed:  Update link in readme to rudder.io and missing smarttag for create-node-api
    (https://issues.rudder.io/issues/15306[#15306])
* Fixed:  Update link in readme to rudder.io and missing smarttag for create-node-api
    (https://issues.rudder.io/issues/15306[#15306])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Victor QUERETTE

This is a bug fix release in the 6.0 series and therefore all installations of 6.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

