
= Change logs for Rudder 8.2
==  Rudder 8.2.0.alpha1 (2024-09-09)

=== Changes


==== Packaging

* Remove unsupported distro from rudder-package
    (https://issues.rudder.io/issues/25130[#25130])
* Remove AIX plugin on upgrade
    (https://issues.rudder.io/issues/25133[#25133])
* Update CFEngine to 3.21.5
    (https://issues.rudder.io/issues/25058[#25058])
* Upgrade dependencies for 8.2
    (https://issues.rudder.io/issues/24765[#24765])
* Remove rudder-pkg Python implementation
    (https://issues.rudder.io/issues/24965[#24965])

==== Documentation

* Prepare documentation for repository key change
    (https://issues.rudder.io/issues/24077[#24077])
* Update api doc tooling
    (https://issues.rudder.io/issues/25103[#25103])

==== Agent

* Create a system-updates module in Rust
    (https://issues.rudder.io/issues/24977[#24977])

==== Web - Nodes & inventories

* API to find usage of a node property in Directives
    (https://issues.rudder.io/issues/24634[#24634])
* API to find usage of a node property in Directives
    (https://issues.rudder.io/issues/24634[#24634])

==== Web - UI & UX

* Add parameter to change maximum limit on a quicksearch
    (https://issues.rudder.io/issues/25116[#25116])
* Add parameter to change maximum limit on a quicksearch
    (https://issues.rudder.io/issues/25116[#25116])
* Display the list of users in table form
    (https://issues.rudder.io/issues/24881[#24881])

==== rudderc

* Add error control on Windows techniques
    (https://issues.rudder.io/issues/25152[#25152])
* Add description and documentation fields to methods and blocks
    (https://issues.rudder.io/issues/24962[#24962])
* Allow Boost Software License in Rust crates
    (https://issues.rudder.io/issues/24895[#24895])
* Update to Rust 1.78
    (https://issues.rudder.io/issues/24830[#24830])
* Update Rust dependencies
    (https://issues.rudder.io/issues/24764[#24764])

==== System integration

* Make apache configuration easier to automatically split
    (https://issues.rudder.io/issues/25143[#25143])

==== Miscellaneous

* Some services are not available to build plugins
    (https://issues.rudder.io/issues/25125[#25125])

==== Web - Config management

* Add pre generation hook
    (https://issues.rudder.io/issues/24944[#24944])

==== Web - Compliance & node report

* Add a compliance-by-feature logic and save compliance in base
    (https://issues.rudder.io/issues/24876[#24876])
* Add a compliance-by-feature logic and save compliance in base
    (https://issues.rudder.io/issues/24876[#24876])

==== Architecture - Code maintenance

* Refactoring Elm code related to datatables
    (https://issues.rudder.io/issues/24769[#24769])
* Remove unused tables about compliance and eventlogs
    (https://issues.rudder.io/issues/24964[#24964])

==== Security

* Allow using a different password hash algorithm for each local user
    (https://issues.rudder.io/issues/24729[#24729])
* Implement the custom header CSRF mitigation for XHR requests
    (https://issues.rudder.io/issues/24897[#24897])

==== Architecture - Dependencies

*  Update Scala dependencies
    (https://issues.rudder.io/issues/24768[#24768])

==== System techniques

* Remove AIX support in system techniques
    (https://issues.rudder.io/issues/25131[#25131])

=== Bug fixes

==== Packaging

* Fixed: Remove AIX specific code in agent
    (https://issues.rudder.io/issues/25129[#25129])
* Fixed: Remove the outdated migration scripts from the packaging
    (https://issues.rudder.io/issues/25000[#25000])
* Fixed: copy of doc should ignore version
    (https://issues.rudder.io/issues/24890[#24890])
* Fixed: Remove outdated CFEngine patches
    (https://issues.rudder.io/issues/24773[#24773])
* Fixed: relayd man page build is broken
    (https://issues.rudder.io/issues/24984[#24984])

==== Documentation

* Fixed: Broken doc build
    (https://issues.rudder.io/issues/24151[#24151])

==== API

* Fixed: Missing header XMLHttpRequest for quicksearch call in find property usage
    (https://issues.rudder.io/issues/25184[#25184])
* Fixed: Missing header XMLHttpRequest for quicksearch call in find property usage
    (https://issues.rudder.io/issues/25184[#25184])

==== Web - Nodes & inventories

* Fixed: When agent version is missing in inventory, we get a security token error
    (https://issues.rudder.io/issues/25164[#25164])
* Fixed: XML Entity injection in inventory parsing
    (https://issues.rudder.io/issues/25157[#25157])

==== Web - UI & UX

* Fixed: Small improvements of Targets selection interface
    (https://issues.rudder.io/issues/25176[#25176])
* Fixed: Small improvements of Targets selection interface
    (https://issues.rudder.io/issues/25176[#25176])
* Fixed: User management should display tenants, last and previous session
    (https://issues.rudder.io/issues/24865[#24865])

==== Web - Maintenance

* Fixed: The webapp does not build on jdk22
    (https://issues.rudder.io/issues/25168[#25168])
* Fixed: API tests could fail because yaml files execute concurrently
    (https://issues.rudder.io/issues/24992[#24992])
* Fixed: Move user-management plugin to rudder
    (https://issues.rudder.io/issues/24799[#24799])

==== rudderc

* Fixed: Rudderc fails to render "plain" variables on Windows
    (https://issues.rudder.io/issues/25148[#25148])

==== Security

* Fixed: Generate template variables for Windows policies in directives sequence
    (https://issues.rudder.io/issues/25111[#25111])
* Fixed:  Use Content-Security-Policy strict headers in utilities pages
    (https://issues.rudder.io/issues/25032[#25032])
* Fixed: Generate runtime evaluated variables in windows policies as templates instead of Powershell expansion
    (https://issues.rudder.io/issues/23973[#23973])

==== Architecture - Test

* Fixed: TraitTestApiFromYamlFiles must allow to customize liftRules
    (https://issues.rudder.io/issues/25017[#25017])

==== Architecture - Code maintenance

* Fixed: On a fresh install of Rudder 8.2 nightly, bootcheck error for table deletion
    (https://issues.rudder.io/issues/25016[#25016])

==== Architecture - Dependencies

* Fixed: Update gulp related js dependencies
    (https://issues.rudder.io/issues/24722[#24722])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


Rudder 8.2 is currently the developement version of Rudder.
You can test it using development builds, but not use it in production.

This page provides a summary of changes for each version. Previous beta
and rc versions are listed below for convenience.


*Main new features in Rudder 8.2:*

*Installing, upgrading and testing*

* Install docs:
** Debian/Ubuntu: https://docs.rudder.io/reference/8.2/installation/server/debian.html
** RHEL/CentOS: https://docs.rudder.io/reference/8.2/installation/server/rhel.html
** SLES: https://docs.rudder.io/reference/8.2/installation/server/sles.html
* Upgrade docs: https://docs.rudder.io/reference/8.2/installation/upgrade.html
* Download links: https://www.rudder-project.org/site/get-rudder/downloads/

We also recommend using the https://github.com/Normation/rudder-vagrant[Rudder
Vagrant] config if you want
a quick and easy way to get an installation for testing.

*Operating systems supported*

This version provides packages for these operating systems:

* Rudder server and Rudder relay: *Debian 8-9, RHEL/CentOS 7 (64 bits),
SLES 12-15, Ubuntu 16.04 LTS-18.04 LTS*
* Rudder agent: all of the above plus *RHEL/CentOS 6, Ubuntu 14.04 LTS*
* Rudder agent (binary packages available from
(http://www.normation.com[Normation]): *Debian 5-7, RHEL/CentOS 5,
SLES 11, Ubuntu 10.04 LTS-12.04 LTS-13.04-15.10, Windows Server 2008R2-2016, AIX
5-6-7, Slackware 14*

== Rudder 8.2.0~alpha1

=== Changes

=== Release notes

