
= Change logs for Rudder 8.2

==  Rudder 8.2.2 (2024-11-28)

=== Changes


==== Packaging

* Update openssl and curl
    (https://issues.rudder.io/issues/25932[#25932])

==== Documentation

* Remove deprecated examples from rudder-by-example
    (https://issues.rudder.io/issues/25909[#25909])
* Document the 8.2 windows variable changes
    (https://issues.rudder.io/issues/25445[#25445])

==== Web - UI & UX

* Add padding to trees to prevent the last element from being hidden when a link is hovered
    (https://issues.rudder.io/issues/25923[#25923])

==== rudderc

* Allow validating JSON parameters in methods
    (https://issues.rudder.io/issues/25871[#25871])

==== Architecture - Code maintenance

* Better log for bad node key
    (https://issues.rudder.io/issues/25870[#25870])

=== Bug fixes

==== Documentation

* Fixed: Documention should advice to trigger agent run after promote a node to relay
    (https://issues.rudder.io/issues/25967[#25967])
* Fixed: Update example to keep up to date rudder-agent package
    (https://issues.rudder.io/issues/25905[#25905])
* Fixed: Remove references to syslog in the docs
    (https://issues.rudder.io/issues/25865[#25865])
* Fixed: Backup/Restore/Migrate documentation are missing essential bits
    (https://issues.rudder.io/issues/25676[#25676])
* Fixed: Documented repository  Rudder public key url is incorrect
    (https://issues.rudder.io/issues/25845[#25845])

==== Web - Nodes & inventories

* Fixed: Error when accepting 2 or more nodes
    (https://issues.rudder.io/issues/25892[#25892])

==== Architecture - Test

* Fixed: Spurious failing test for inherited properties rest API
    (https://issues.rudder.io/issues/25941[#25941])

==== Module - system-updates

* Fixed: Wrong error message when upgrading a non-existent package
    (https://issues.rudder.io/issues/25940[#25940])
* Fixed: Dont output package lists in report
    (https://issues.rudder.io/issues/25926[#25926])
* Fixed: Broken system-updates module build
    (https://issues.rudder.io/issues/25889[#25889])
* Fixed: Error in update campaign
    (https://issues.rudder.io/issues/25867[#25867])

==== Security

* Fixed: Migrate to unsafe-hashes only from a known unsalted algorithm
    (https://issues.rudder.io/issues/25935[#25935])
* Fixed: Vulnerability in diesel
    (https://issues.rudder.io/issues/25888[#25888])

==== Architecture - Dependencies

* Fixed: Remove security check on a js dev dependency 
    (https://issues.rudder.io/issues/25937[#25937])

==== Web - UI & UX

* Fixed: The setup initial page should not be displayed if rudder-pkg.conf has been modified
    (https://issues.rudder.io/issues/25847[#25847])
* Fixed: Add timezone and refresh seconds in deployment status
    (https://issues.rudder.io/issues/25733[#25733])

==== Web - Config management

* Fixed: Locale issue: date picker should be in yyyy/MM/dd in group criteria
    (https://issues.rudder.io/issues/25727[#25727])
* Fixed: After restart, nodes that were set back to default policy mode return to their previous overriden mode
    (https://issues.rudder.io/issues/25866[#25866])

==== Architecture - Code maintenance

* Fixed: Test for inherited properties is failing in 8.2
    (https://issues.rudder.io/issues/25659[#25659])

==== Web - Compliance & node report

* Fixed: a node with no rules applied has a score of F
    (https://issues.rudder.io/issues/25813[#25813])

==== Plugin manager cli

* Fixed: Use secrecy to store the password
    (https://issues.rudder.io/issues/25873[#25873])

==== Techniques

* Fixed: File content from remote template technique should allow selecting a file from shared folder
    (https://issues.rudder.io/issues/25851[#25851])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.2.1 (2024-11-08)

=== Changes


==== Documentation

* Publish the audit report in the docs
    (https://issues.rudder.io/issues/25803[#25803])

==== Agent

* Add a new CLI tool to converts raw Rudder reports to Json
    (https://issues.rudder.io/issues/25757[#25757])

==== Generic methods

*  Add Windows support to the generic method file_report_content_tail
    (https://issues.rudder.io/issues/25588[#25588])

=== Bug fixes

==== Packaging

* Fixed: Start jetty script in debug mode
    (https://issues.rudder.io/issues/25735[#25735])
* Fixed: rudder package log error when trying to update licence on a relay
    (https://issues.rudder.io/issues/25821[#25821])
* Fixed: Update Rust for typos check
    (https://issues.rudder.io/issues/25790[#25790])

==== Documentation

* Fixed: Update docs for 8.2
    (https://issues.rudder.io/issues/25826[#25826])
* Fixed: Mark 8.2 doc as stable
    (https://issues.rudder.io/issues/25773[#25773])
* Fixed: Missing documentation on rudder.users.cleanup.account.disableAfterLastLogin
    (https://issues.rudder.io/issues/25623[#25623])
* Fixed: Property name case collision is not longer a thing on Windows node since 8.2
    (https://issues.rudder.io/issues/25726[#25726])
* Fixed: Update and fix the API doc tooling
    (https://issues.rudder.io/issues/25809[#25809])

==== Web - UI & UX

* Fixed: Status bar can only be opened by clicking twice
    (https://issues.rudder.io/issues/25834[#25834])
* Fixed: Sometimes too long properties values move out actions buttons from window
    (https://issues.rudder.io/issues/25762[#25762])
* Fixed: Improve config log wording
    (https://issues.rudder.io/issues/25829[#25829])
* Fixed: Properties on newly created group are not initialized until policy generation or other group properties update
    (https://issues.rudder.io/issues/25822[#25822])
* Fixed: Tooltips in nodes compliance are not displayed
    (https://issues.rudder.io/issues/25663[#25663])

==== rudderc

* Fixed: Override audit/enforce mode does not work with iterator
    (https://issues.rudder.io/issues/25770[#25770])
* Fixed: Missing annotation on a rudderc test case
    (https://issues.rudder.io/issues/25775[#25775])
* Fixed: Broken parsing of node inventory variable
    (https://issues.rudder.io/issues/25771[#25771])

==== Web - Nodes & inventories

* Fixed: On new groups, adding a prop leads to "No query defined for group" error
    (https://issues.rudder.io/issues/25820[#25820])
* Fixed: Lost manufacturer & serial for BIOS  between 7.3 and 8.0
    (https://issues.rudder.io/issues/25589[#25589])

==== Web - Compliance & node report

* Fixed: ReportsExecution doesn't have timezone on all fields
    (https://issues.rudder.io/issues/25713[#25713])

==== API

* Fixed: API version for 8.2 is 20
    (https://issues.rudder.io/issues/25800[#25800])
* Fixed: Full archive export does not work anymore
    (https://issues.rudder.io/issues/25691[#25691])

==== Web - Config management

* Fixed: Search on RAM fails in node groups
    (https://issues.rudder.io/issues/25701[#25701])
* Fixed: When removing files from a technique, it might get disabled unexpectedly
    (https://issues.rudder.io/issues/23959[#23959])
* Fixed: switching policy mode on a node from "Enforce" to anything else produce event log about properties
    (https://issues.rudder.io/issues/25667[#25667])

==== Web - Maintenance

* Fixed: OIDC users are marked as deleted after a new user is provisionned
    (https://issues.rudder.io/issues/25681[#25681])
* Fixed: Bad postgresql time conversion for event log cleaning
    (https://issues.rudder.io/issues/25782[#25782])
* Fixed: Technical and event logs get log from browser timezone instead of server timezone
    (https://issues.rudder.io/issues/25720[#25720])

==== Server components

* Fixed: Default settings for new nodes are not applied on a accepted node
    (https://issues.rudder.io/issues/25652[#25652])

==== Relay server or API

* Fixed: Stacktrace in relayd on invalid run time file name
    (https://issues.rudder.io/issues/25754[#25754])

==== Security

* Fixed: CSP violations from status tab in utilities pages
    (https://issues.rudder.io/issues/25712[#25712])

==== Architecture - Code maintenance

* Fixed: Avoid Content-Security-Policy-Report-Only headers in dev mode
    (https://issues.rudder.io/issues/25715[#25715])

==== Agent

* Fixed: rudder agent factory-reset -f doesn't do anything
    (https://issues.rudder.io/issues/25607[#25607])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.2.0 (2024-10-29)

=== Changes


=== Bug fixes

==== Agent

* Fixed: APT update output mis-handles interactive output
    (https://issues.rudder.io/issues/25751[#25751])
* Fixed: Update schedule is not sen anymore
    (https://issues.rudder.io/issues/25747[#25747])
* Fixed: db error about pid column
    (https://issues.rudder.io/issues/25745[#25745])

==== Miscellaneous

* Fixed: Software update campaign does not work on Debian 10 Buster
    (https://issues.rudder.io/issues/25695[#25695])
* Fixed: Software update campaign does not work on SLES 15
    (https://issues.rudder.io/issues/25693[#25693])

==== Documentation

* Fixed: OpenAPI documentation is invalid with duplicate /nodes/pending endpoints
    (https://issues.rudder.io/issues/25709[#25709])

==== rudderc

* Fixed: Windows techniques fail to catch the Nustache.Core.RaiseExceptionOnEmptyStringValue errors
    (https://issues.rudder.io/issues/25708[#25708])

==== System techniques

* Fixed: rudder-cf-serverd is not restarted properly after a change in authorized network on a relay
    (https://issues.rudder.io/issues/25639[#25639])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.2.0.rc1 (2024-10-18)

=== Changes


==== Packaging

* Reenable system-updates module build
    (https://issues.rudder.io/issues/25651[#25651])

==== Documentation

* Document how to install plugins on Amazon 2023
    (https://issues.rudder.io/issues/25678[#25678])
* Add Ubuntu 24.04 as server in documentation
    (https://issues.rudder.io/issues/25468[#25468])
* Update users management doc in 8.2
    (https://issues.rudder.io/issues/25401[#25401])

==== Web - Compliance & node report

* Node with kept compliance should have the clock icon in node list
    (https://issues.rudder.io/issues/25649[#25649])
* We need an icon and recognizable message style for node with expired maintained compliance
    (https://issues.rudder.io/issues/25572[#25572])
* Worst report takes the worst component instead of block
    (https://issues.rudder.io/issues/25383[#25383])

==== Web - Nodes & inventories

* IP search field with slash notation
    (https://issues.rudder.io/issues/3615[#3615])

==== Architecture - evolution

* Add missing service for plugins
    (https://issues.rudder.io/issues/25609[#25609])
* Remove webapp technique compilation fallback
    (https://issues.rudder.io/issues/25504[#25504])
* Normalize authentication logs
    (https://issues.rudder.io/issues/25478[#25478])
* Normalize authentication logs
    (https://issues.rudder.io/issues/25478[#25478])

==== Web - UI & UX

* Add notifications on copy to clipboard 
    (https://issues.rudder.io/issues/25602[#25602])

==== Architecture - Code maintenance

* Limit number of  rust jobs in build jobs
    (https://issues.rudder.io/issues/25524[#25524])

==== Techniques

* Add linting to the powershell techniques
    (https://issues.rudder.io/issues/25551[#25551])

=== Bug fixes

==== Packaging

* Fixed: Disable apt feature on Slackware
    (https://issues.rudder.io/issues/25629[#25629])
* Fixed: Error buiding system-updates on debian 12
    (https://issues.rudder.io/issues/25615[#25615])
* Fixed: Missing apt feature in system updates module
    (https://issues.rudder.io/issues/25613[#25613])
* Fixed: Pass an argument to CFEngine custom promise type binaries - 8.2
    (https://issues.rudder.io/issues/25571[#25571])
* Fixed: Take cargo fetures without the option
    (https://issues.rudder.io/issues/25616[#25616])
* Fixed: Set build limit to 2 jobs for Rust programs
    (https://issues.rudder.io/issues/25541[#25541])

==== Agent

* Fixed: Skip libapt build on breaking systems
    (https://issues.rudder.io/issues/25627[#25627])
* Fixed: Skip libapt build on breaking systems
    (https://issues.rudder.io/issues/25627[#25627])
* Fixed: Skip libapt build on breaking systems
    (https://issues.rudder.io/issues/25627[#25627])
* Fixed: Backport scheduling fixes for cf-execd
    (https://issues.rudder.io/issues/25505[#25505])
* Fixed: System updates module expects snake case
    (https://issues.rudder.io/issues/25686[#25686])
* Fixed: Report more errors to the server
    (https://issues.rudder.io/issues/25677[#25677])
* Fixed: Fix system-updates schedule
    (https://issues.rudder.io/issues/25661[#25661])
* Fixed: Fix the package manager detection
    (https://issues.rudder.io/issues/25653[#25653])
* Fixed: Use the fixed rust-apt
    (https://issues.rudder.io/issues/25640[#25640])
* Fixed: Fix system-updates module technique compatibility
    (https://issues.rudder.io/issues/25575[#25575])
* Fixed: Fix the system-updates module
    (https://issues.rudder.io/issues/25364[#25364])

==== Inventory

* Fixed: Inventory fails because rudder-agent has no version in inventory
    (https://issues.rudder.io/issues/25496[#25496])

==== Documentation

* Fixed: Change of template.png in docs.rudder.io
    (https://issues.rudder.io/issues/25646[#25646])
* Fixed: Revert to using the old RPM key in the docs
    (https://issues.rudder.io/issues/25543[#25543])
* Fixed: User password change no longer needs restart in doc
    (https://issues.rudder.io/issues/25444[#25444])
* Fixed: Adapt doc for 8.2 build
    (https://issues.rudder.io/issues/25431[#25431])
* Fixed: Anchor link to Rudder Core doent work in the README
    (https://issues.rudder.io/issues/25642[#25642])
* Fixed: New README for Rudder
    (https://issues.rudder.io/issues/25636[#25636])
* Fixed: API documentation for user-management is missing some endpoints
    (https://issues.rudder.io/issues/25459[#25459])
* Fixed: API documentation for user management in 8.2
    (https://issues.rudder.io/issues/25293[#25293])

==== Relay server or API

* Fixed: Add 127.0.0.1 as ServerAlias for multi-vhost  server configuration
    (https://issues.rudder.io/issues/25675[#25675])

==== Web - UI & UX

* Fixed: System rules are now always shown in group compliance
    (https://issues.rudder.io/issues/25673[#25673])
* Fixed: Remove the Clipboard js library as it is no longer required
    (https://issues.rudder.io/issues/25658[#25658])
* Fixed: Node search query doesn't find any Windows node
    (https://issues.rudder.io/issues/25638[#25638])
* Fixed: When changing node properties the old table is sometimes still displayed
    (https://issues.rudder.io/issues/25332[#25332])
* Fixed: Display for checkbox "Show inherited properties" when adding a property column on node pages is broken
    (https://issues.rudder.io/issues/25536[#25536])
* Fixed: When accepting a node with a duplicate hostname, there's no error displayed
    (https://issues.rudder.io/issues/25453[#25453])
* Fixed: It's "AlmaLinux" and not "Alma Linux"
    (https://issues.rudder.io/issues/25553[#25553])
* Fixed: Typo in agent schedule selector
    (https://issues.rudder.io/issues/25500[#25500])
* Fixed: Event log table default period of two hours is too short
    (https://issues.rudder.io/issues/25499[#25499])
* Fixed: Score badge background image should not be repeated
    (https://issues.rudder.io/issues/25391[#25391])

==== Web - Config management

* Fixed: "Started since" time in status zone is not correct
    (https://issues.rudder.io/issues/25670[#25670])
* Fixed: Hooks are not executed anymore from their directory
    (https://issues.rudder.io/issues/25498[#25498])

==== Miscellaneous

* Fixed: Debug information download is broken by anti-CSRF header
    (https://issues.rudder.io/issues/25534[#25534])
* Fixed: Group properties wrongly appear empty when group has no member nodes
    (https://issues.rudder.io/issues/25530[#25530])
* Fixed: Target selection has a weird vertical text
    (https://issues.rudder.io/issues/25507[#25507])
* Fixed: Group position on dashboard statistics  make no sens
    (https://issues.rudder.io/issues/25448[#25448])

==== API

* Fixed: Related rules return an authorization error in UI for non-admin users
    (https://issues.rudder.io/issues/25645[#25645])
* Fixed: System rules are now always shown in directives compliance
    (https://issues.rudder.io/issues/25517[#25517])
* Fixed: The severity ERROR for Node with ID ‘xxx’ was not found in Rudder’ is too strict
    (https://issues.rudder.io/issues/25438[#25438])
* Fixed: Archive API for import/export doesn't know about technique
    (https://issues.rudder.io/issues/24789[#24789])

==== Architecture - Code maintenance

* Fixed: Add tests for the case where there is conflicts in group properties
    (https://issues.rudder.io/issues/25419[#25419])
* Fixed: Chunk appending when resolving node ids from union target can be optimized
    (https://issues.rudder.io/issues/25635[#25635])
* Fixed: NuProcessHandler.onStart NPE log message
    (https://issues.rudder.io/issues/25306[#25306])

==== Web - Compliance & node report

* Fixed: Node in with no reports, pending and keep compliance lead to computation loop
    (https://issues.rudder.io/issues/25650[#25650])
* Fixed: No system status in 8.2
    (https://issues.rudder.io/issues/25508[#25508])
* Fixed: worst report by percentage seems to be non fonctionnal
    (https://issues.rudder.io/issues/25513[#25513])
* Fixed: Technical logs are not loaded when visiting the tab - rudder 8.1
    (https://issues.rudder.io/issues/24332[#24332])

==== Architecture - Test

* Fixed: Sometimes tests with lift actor fails
    (https://issues.rudder.io/issues/25637[#25637])

==== Web - Nodes & inventories

* Fixed: SQL error in the logs when deleting a node
    (https://issues.rudder.io/issues/25633[#25633])
* Fixed: Add support for Tuxedo OS
    (https://issues.rudder.io/issues/25519[#25519])
* Fixed: API don't include acceptedSince information
    (https://issues.rudder.io/issues/25476[#25476])

==== Plugin manager cli

* Fixed: Detect local install tentative in rudder package
    (https://issues.rudder.io/issues/25538[#25538])

==== Security

* Fixed: Unknown API tokens get logged in plain
    (https://issues.rudder.io/issues/25555[#25555])
* Fixed: Ignore RUSTSEC-2024-0365 as we are not vulnerable
    (https://issues.rudder.io/issues/25456[#25456])
* Fixed: User password and permission change should invalidate sessions
    (https://issues.rudder.io/issues/25407[#25407])
* Fixed: Invalidated user sessions need to have an endcause and user should be notified 
    (https://issues.rudder.io/issues/25443[#25443])

==== Techniques

* Fixed: Techniques no longer compile with error in rudderc arguments
    (https://issues.rudder.io/issues/25545[#25545])

==== Web - Maintenance

* Fixed: Users cleanup configuration is too strict on disabled users
    (https://issues.rudder.io/issues/25479[#25479])

==== rudderc

* Fixed: Static rudderc builds are failing due to missing tracing import
    (https://issues.rudder.io/issues/25439[#25439])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Fabrice FLORE-THÉBAULT

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.2.0.beta1 (2024-09-09)

=== Changes


==== Packaging

* Build the system-updates module
    (https://issues.rudder.io/issues/25305[#25305])
* Remove python-dev as a builld dependency on rudder-server
    (https://issues.rudder.io/issues/25317[#25317])
* Add rust build to packaging
    (https://issues.rudder.io/issues/25197[#25197])

==== Documentation

* Adapt the variables documentation to the 8.2 syntax
    (https://issues.rudder.io/issues/25262[#25262])
* Undocument global parameters
    (https://issues.rudder.io/issues/25261[#25261])

==== Web - Nodes & inventories

* Add an optional visibility attribute on node property 
    (https://issues.rudder.io/issues/25369[#25369])

==== Agent

* Improve system-updates module
    (https://issues.rudder.io/issues/25188[#25188])

==== Architecture - evolution

* Some services needed for plugins
    (https://issues.rudder.io/issues/25315[#25315])

==== Architecture - Dependencies

* Update Scala dependencies
    (https://issues.rudder.io/issues/25186[#25186])

=== Bug fixes

==== Packaging

* Fixed: Add the new completion file to RPM package
    (https://issues.rudder.io/issues/25309[#25309])
* Fixed: build-caching fails for agent rust builds
    (https://issues.rudder.io/issues/25257[#25257])
* Fixed: rust build-caching breaks hosts without rust
    (https://issues.rudder.io/issues/25206[#25206])
* Fixed: do not build rust items on sustems that do not support it
    (https://issues.rudder.io/issues/25205[#25205])
* Fixed: Changes for modules packaging
    (https://issues.rudder.io/issues/25342[#25342])
* Fixed: Changes for modules packaging
    (https://issues.rudder.io/issues/25342[#25342])
* Fixed: rudder-package completion build breaks
    (https://issues.rudder.io/issues/25308[#25308])

==== Server components

* Fixed: rudder-cf-serverd was stopped on the server, and nothing restarted it
    (https://issues.rudder.io/issues/25252[#25252])
* Fixed: Node inventory hooks are are not working properly
    (https://issues.rudder.io/issues/25161[#25161])

==== Plugin manager cli

* Fixed: Rudder-pkg tests fail since distutils package has been removed in python 3.12
    (https://issues.rudder.io/issues/25417[#25417])
* Fixed: Postinst script are not run during upgrades
    (https://issues.rudder.io/issues/25282[#25282])
* Fixed: Make plugin install log less verbose
    (https://issues.rudder.io/issues/25275[#25275])

==== Web - UI & UX

* Fixed: User identity does not show up in bar when user has last login
    (https://issues.rudder.io/issues/25409[#25409])
* Fixed: Incorrect display of compliance in newly created rules
    (https://issues.rudder.io/issues/25371[#25371])
* Fixed: Event logs details look broken in 8.1
    (https://issues.rudder.io/issues/25071[#25071])
* Fixed: Nodes table sorting is not obvious and we need to guess the sort column and direction 
    (https://issues.rudder.io/issues/25136[#25136])
* Fixed: Some minor UI issues in node property usage search
    (https://issues.rudder.io/issues/25333[#25333])
* Fixed: Make tooltips non-transparent
    (https://issues.rudder.io/issues/25326[#25326])
* Fixed: User management 'providers' column is still missing when there are multiple values
    (https://issues.rudder.io/issues/25299[#25299])
* Fixed: Only remaining user managed by file cannot be deleted 
    (https://issues.rudder.io/issues/25300[#25300])
* Fixed: User management table always shows additional 'no_rights' authorization
    (https://issues.rudder.io/issues/25296[#25296])
* Fixed: User management table has the wrong count of entries with deleted users
    (https://issues.rudder.io/issues/25301[#25301])
* Fixed: Tenants column in user-management should depend on plugin activation
    (https://issues.rudder.io/issues/24976[#24976])
* Fixed: Message « This node has no properties » on group
    (https://issues.rudder.io/issues/25171[#25171])
* Fixed: tooltips in the rules page persist when switching content
    (https://issues.rudder.io/issues/21668[#21668])
* Fixed: Dashboard information are not updated when deleting a node
    (https://issues.rudder.io/issues/25095[#25095])

==== Architecture - Dependencies

* Fixed: Allow MPL-2.0 license in cargo checks
    (https://issues.rudder.io/issues/25404[#25404])

==== rudderc

* Fixed: Static builds are failing due to missing lib
    (https://issues.rudder.io/issues/25390[#25390])
* Fixed: Typo in the windows technique generation template
    (https://issues.rudder.io/issues/25382[#25382])
* Fixed: rudderc CLI errors are not user friendly enough when the workdir is incorrectly set
    (https://issues.rudder.io/issues/25375[#25375])
* Fixed: rudderc is generating 0 bytes resources when output directory is the same as the input
    (https://issues.rudder.io/issues/25238[#25238])
* Fixed: Improve the error handling in the Windows techniques
    (https://issues.rudder.io/issues/25190[#25190])

==== API

* Fixed: Node property usage search seems to be limited to 10 elements
    (https://issues.rudder.io/issues/25334[#25334])
* Fixed: Deleting CVE group is possible even if it is a system group
    (https://issues.rudder.io/issues/25348[#25348])
* Fixed: Apply policy returns a json error when clicking on trigger agent
    (https://issues.rudder.io/issues/25368[#25368])
* Fixed: Event log rollback action is prevented from CSP headers
    (https://issues.rudder.io/issues/25352[#25352])
* Fixed: The pending nodes API now returns array of arrays of nodes instead of an array of nodes
    (https://issues.rudder.io/issues/25203[#25203])
* Fixed: Unauthorized access to API should not be logged as error
    (https://issues.rudder.io/issues/25246[#25246])

==== Architecture - Code maintenance

* Fixed: Add log for error in JSON campaigns on FS
    (https://issues.rudder.io/issues/25388[#25388])
* Fixed: Scheduled processes could stop on error in ZIO
    (https://issues.rudder.io/issues/25365[#25365])

==== Web - Nodes & inventories

* Fixed: Windows KB don't show up in the inventory anymore
    (https://issues.rudder.io/issues/25351[#25351])

==== Web - Technique editor

* Fixed: Resources upload over 8 MB show error in log and not in UI
    (https://issues.rudder.io/issues/25155[#25155])

==== Web - Campaigns

* Fixed: no reports in campaign page even if the node sent the data
    (https://issues.rudder.io/issues/25350[#25350])

==== System integration

* Fixed: One user is created each case change even if case sensivity if false
    (https://issues.rudder.io/issues/24955[#24955])

==== Security

* Fixed: Authentication happens twice with same session id
    (https://issues.rudder.io/issues/25123[#25123])
* Fixed: Disabled and deleted user can still use Rudder until session expires
    (https://issues.rudder.io/issues/25307[#25307])
* Fixed:  Implement missing CSRF mitigation headers for Rules XHR
    (https://issues.rudder.io/issues/25310[#25310])
* Fixed: RUSTSEC-2024-0357  vulnerability in openssl lib
    (https://issues.rudder.io/issues/25189[#25189])

==== Architecture - Test

* Fixed: Database tests have non temporary DDL that prevents running them twice
    (https://issues.rudder.io/issues/25303[#25303])

==== Documentation

* Fixed: API documentation examples are not valid bash scripts
    (https://issues.rudder.io/issues/25302[#25302])
* Fixed: API documentation for user management has no user info and providers fields
    (https://issues.rudder.io/issues/25291[#25291])
* Fixed: API documentation for pending nodes is missing an endpoint and fields
    (https://issues.rudder.io/issues/25285[#25285])

==== Web - Maintenance

* Fixed: when we have compliance right, the rule page shows a weird message
    (https://issues.rudder.io/issues/24863[#24863])
* Fixed: Don't update plugin password if nothing was given
    (https://issues.rudder.io/issues/25227[#25227])

==== CI

* Fixed: The policies Dockerfile does not fail when the rudder agent fails to install
    (https://issues.rudder.io/issues/25213[#25213])

==== System techniques

* Fixed: Allow non canonfied json in autoconditions
    (https://issues.rudder.io/issues/25298[#25298])
* Fixed: Local inventories are piling up in /var/rudder/inventories
    (https://issues.rudder.io/issues/25289[#25289])

==== Agent

* Fixed: rudder agent factory-reset should reenable service
    (https://issues.rudder.io/issues/25187[#25187])

==== Generic methods

* Fixed: Broken jinja2 templating on Ubuntu 24.04
    (https://issues.rudder.io/issues/25324[#25324])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.2.0.alpha1 (2024-09-09)

=== Changes


==== Packaging

* Remove unsupported distro from rudder-package
    (https://issues.rudder.io/issues/25130[#25130])
* Remove AIX plugin on upgrade
    (https://issues.rudder.io/issues/25133[#25133])
* Update CFEngine to 3.21.5
    (https://issues.rudder.io/issues/25058[#25058])
* Upgrade dependencies for 8.2
    (https://issues.rudder.io/issues/24765[#24765])
* Remove rudder-pkg Python implementation
    (https://issues.rudder.io/issues/24965[#24965])

==== Documentation

* Prepare documentation for repository key change
    (https://issues.rudder.io/issues/24077[#24077])
* Update api doc tooling
    (https://issues.rudder.io/issues/25103[#25103])

==== Agent

* Create a system-updates module in Rust
    (https://issues.rudder.io/issues/24977[#24977])

==== Web - Nodes & inventories

* API to find usage of a node property in Directives
    (https://issues.rudder.io/issues/24634[#24634])
* API to find usage of a node property in Directives
    (https://issues.rudder.io/issues/24634[#24634])

==== Web - UI & UX

* Add parameter to change maximum limit on a quicksearch
    (https://issues.rudder.io/issues/25116[#25116])
* Add parameter to change maximum limit on a quicksearch
    (https://issues.rudder.io/issues/25116[#25116])
* Display the list of users in table form
    (https://issues.rudder.io/issues/24881[#24881])

==== rudderc

* Add error control on Windows techniques
    (https://issues.rudder.io/issues/25152[#25152])
* Add description and documentation fields to methods and blocks
    (https://issues.rudder.io/issues/24962[#24962])
* Allow Boost Software License in Rust crates
    (https://issues.rudder.io/issues/24895[#24895])
* Update to Rust 1.78
    (https://issues.rudder.io/issues/24830[#24830])
* Update Rust dependencies
    (https://issues.rudder.io/issues/24764[#24764])

==== System integration

* Make apache configuration easier to automatically split
    (https://issues.rudder.io/issues/25143[#25143])

==== Miscellaneous

* Some services are not available to build plugins
    (https://issues.rudder.io/issues/25125[#25125])

==== Web - Config management

* Add pre generation hook
    (https://issues.rudder.io/issues/24944[#24944])

==== Web - Compliance & node report

* Add a compliance-by-feature logic and save compliance in base
    (https://issues.rudder.io/issues/24876[#24876])
* Add a compliance-by-feature logic and save compliance in base
    (https://issues.rudder.io/issues/24876[#24876])

==== Architecture - Code maintenance

* Refactoring Elm code related to datatables
    (https://issues.rudder.io/issues/24769[#24769])
* Remove unused tables about compliance and eventlogs
    (https://issues.rudder.io/issues/24964[#24964])

==== Security

* Allow using a different password hash algorithm for each local user
    (https://issues.rudder.io/issues/24729[#24729])
* Implement the custom header CSRF mitigation for XHR requests
    (https://issues.rudder.io/issues/24897[#24897])

==== Architecture - Dependencies

*  Update Scala dependencies
    (https://issues.rudder.io/issues/24768[#24768])

==== System techniques

* Remove AIX support in system techniques
    (https://issues.rudder.io/issues/25131[#25131])

=== Bug fixes

==== Packaging

* Fixed: Remove AIX specific code in agent
    (https://issues.rudder.io/issues/25129[#25129])
* Fixed: Remove the outdated migration scripts from the packaging
    (https://issues.rudder.io/issues/25000[#25000])
* Fixed: copy of doc should ignore version
    (https://issues.rudder.io/issues/24890[#24890])
* Fixed: Remove outdated CFEngine patches
    (https://issues.rudder.io/issues/24773[#24773])
* Fixed: relayd man page build is broken
    (https://issues.rudder.io/issues/24984[#24984])

==== Documentation

* Fixed: Broken doc build
    (https://issues.rudder.io/issues/24151[#24151])

==== API

* Fixed: Missing header XMLHttpRequest for quicksearch call in find property usage
    (https://issues.rudder.io/issues/25184[#25184])
* Fixed: Missing header XMLHttpRequest for quicksearch call in find property usage
    (https://issues.rudder.io/issues/25184[#25184])

==== Web - Nodes & inventories

* Fixed: When agent version is missing in inventory, we get a security token error
    (https://issues.rudder.io/issues/25164[#25164])
* Fixed: XML Entity injection in inventory parsing
    (https://issues.rudder.io/issues/25157[#25157])

==== Web - UI & UX

* Fixed: Small improvements of Targets selection interface
    (https://issues.rudder.io/issues/25176[#25176])
* Fixed: Small improvements of Targets selection interface
    (https://issues.rudder.io/issues/25176[#25176])
* Fixed: User management should display tenants, last and previous session
    (https://issues.rudder.io/issues/24865[#24865])

==== Web - Maintenance

* Fixed: The webapp does not build on jdk22
    (https://issues.rudder.io/issues/25168[#25168])
* Fixed: API tests could fail because yaml files execute concurrently
    (https://issues.rudder.io/issues/24992[#24992])
* Fixed: Move user-management plugin to rudder
    (https://issues.rudder.io/issues/24799[#24799])

==== rudderc

* Fixed: Rudderc fails to render "plain" variables on Windows
    (https://issues.rudder.io/issues/25148[#25148])

==== Security

* Fixed: Generate template variables for Windows policies in directives sequence
    (https://issues.rudder.io/issues/25111[#25111])
* Fixed:  Use Content-Security-Policy strict headers in utilities pages
    (https://issues.rudder.io/issues/25032[#25032])
* Fixed: Generate runtime evaluated variables in windows policies as templates instead of Powershell expansion
    (https://issues.rudder.io/issues/23973[#23973])

==== Architecture - Test

* Fixed: TraitTestApiFromYamlFiles must allow to customize liftRules
    (https://issues.rudder.io/issues/25017[#25017])

==== Architecture - Code maintenance

* Fixed: On a fresh install of Rudder 8.2 nightly, bootcheck error for table deletion
    (https://issues.rudder.io/issues/25016[#25016])

==== Architecture - Dependencies

* Fixed: Update gulp related js dependencies
    (https://issues.rudder.io/issues/24722[#24722])

=== Release notes

This is a bug fix release in the 8.2 series and therefore all installations of 8.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


Rudder 8.2 is currently the developement version of Rudder.
You can test it using development builds, but not use it in production.

This page provides a summary of changes for each version. Previous beta
and rc versions are listed below for convenience.


*Main new features in Rudder 8.2:*

*Installing, upgrading and testing*

* Install docs:
** Debian/Ubuntu: https://docs.rudder.io/reference/8.2/installation/server/debian.html
** RHEL/CentOS: https://docs.rudder.io/reference/8.2/installation/server/rhel.html
** SLES: https://docs.rudder.io/reference/8.2/installation/server/sles.html
* Upgrade docs: https://docs.rudder.io/reference/8.2/installation/upgrade.html
* Download links: https://www.rudder-project.org/site/get-rudder/downloads/

We also recommend using the https://github.com/Normation/rudder-vagrant[Rudder
Vagrant] config if you want
a quick and easy way to get an installation for testing.

*Operating systems supported*

This version provides packages for these operating systems:

* Rudder server and Rudder relay: *Debian 8-9, RHEL/CentOS 7 (64 bits),
SLES 12-15, Ubuntu 16.04 LTS-18.04 LTS*
* Rudder agent: all of the above plus *RHEL/CentOS 6, Ubuntu 14.04 LTS*
* Rudder agent (binary packages available from
(http://www.normation.com[Normation]): *Debian 5-7, RHEL/CentOS 5,
SLES 11, Ubuntu 10.04 LTS-12.04 LTS-13.04-15.10, Windows Server 2008R2-2016, AIX
5-6-7, Slackware 14*

== Rudder 8.2.0~alpha1

=== Changes

=== Release notes

