= Change logs for Rudder 9.0

==  Rudder 9.0.1 (2025-11-19)

=== Changes


==== Packaging

* Update openssl
    (https://issues.rudder.io/issues/27809[#27809])

==== Web - Nodes & inventories

* Add the possibility to get all inventory where lastInventoryDate is after a given datetime
    (https://issues.rudder.io/issues/27737[#27737])

==== Module - augeas

* update help flag for rudder-module-augeas
    (https://issues.rudder.io/issues/27812[#27812])
* add documentation for rudder-module-augeas
    (https://issues.rudder.io/issues/27799[#27799])
* add documentation and bugfix for rudder-module-augeas
    (https://issues.rudder.io/issues/27747[#27747])

==== Web - Maintenance

* Use ESM modules in rudder-web
    (https://issues.rudder.io/issues/27124[#27124])

==== Documentation

* Update api doc tooling
    (https://issues.rudder.io/issues/27803[#27803])
* Add arch doc about remote run
    (https://issues.rudder.io/issues/27796[#27796])

==== Miscellaneous

* Update onboarding documentations
    (https://issues.rudder.io/issues/27720[#27720])

==== rudderc

* Adapt the Windows technique generation to support ID based resulting conditions
    (https://issues.rudder.io/issues/27766[#27766])

=== Bug fixes

==== Packaging

* Fixed: Remove leftover init script
    (https://issues.rudder.io/issues/27755[#27755])
* Fixed: Incorrect data passed to the apache template in the postinst relay script
    (https://issues.rudder.io/issues/27861[#27861])

==== Documentation

* Fixed: Typo in the JSON path example of the documentation
    (https://issues.rudder.io/issues/27870[#27870])
* Fixed: Mention rudder-api-client in upgrade notes
    (https://issues.rudder.io/issues/27828[#27828])
* Fixed: Add known var/readonly issue to the doc
    (https://issues.rudder.io/issues/27788[#27788])
* Fixed: Campaings hooks readme.adoc starts with wrong comment (node-post-acceptance)
    (https://issues.rudder.io/issues/27775[#27775])

==== Web - UI & UX

* Fixed: Node properties cannot be exported in 9.0 since 27580 
    (https://issues.rudder.io/issues/27865[#27865])
* Fixed: Rollback buttons in change logs are out of reach
    (https://issues.rudder.io/issues/27836[#27836])
* Fixed: Node properties diff in change logs show whole diff of all properties
    (https://issues.rudder.io/issues/27819[#27819])

==== Web - Compliance & node report

* Fixed: The 1000 reports of the technical log is not enough with a benchmark
    (https://issues.rudder.io/issues/27782[#27782])

==== Module - augeas

* Fixed: report file not deleted while running in audit mode
    (https://issues.rudder.io/issues/27857[#27857])
* Fixed: Return error when no file associated with path in rudder-module-augeas
    (https://issues.rudder.io/issues/27805[#27805])
* Fixed: Fix warning in augeas module
    (https://issues.rudder.io/issues/27801[#27801])

==== System techniques

* Fixed: Don't use datastate for apache config templating
    (https://issues.rudder.io/issues/27845[#27845])
* Fixed: Disable webdav check in CA mode
    (https://issues.rudder.io/issues/27821[#27821])

==== Server components

* Fixed: Fix definition of system utilities paths for Manjaro Linux
    (https://issues.rudder.io/issues/27795[#27795])

==== Architecture - Code maintenance

* Fixed: Endpoint name are not unique cause /info API endpoint to be inexhaustive
    (https://issues.rudder.io/issues/27731[#27731])

==== Generic methods

* Fixed: The audit/enforce mode status is not passed to the augeas module
    (https://issues.rudder.io/issues/27667[#27667])

==== CI

* Fixed: Update docker requiring the Rudder agent to Debian 12 or 13
    (https://issues.rudder.io/issues/27780[#27780])

==== Web - Nodes & inventories

* Fixed: Nodes properties cannot be exported to CSV
    (https://issues.rudder.io/issues/27580[#27580])

==== Agent

* Fixed: Missing flag file touch on HTTP policy update
    (https://issues.rudder.io/issues/27818[#27818])
* Fixed: System update node hooks are still in /var
    (https://issues.rudder.io/issues/27777[#27777])
* Fixed: rudder agent info doesn't detect masked service
    (https://issues.rudder.io/issues/27743[#27743])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 9.0.0 (2025-10-21)

=== Changes


==== Documentation

* Add upgrade notes
    (https://issues.rudder.io/issues/27754[#27754])
* Update openapi doc to v22 in 9.0
    (https://issues.rudder.io/issues/27753[#27753])

=== Bug fixes

==== Documentation

* Fixed: Remove the 8.1 & 8.2 documentation
    (https://issues.rudder.io/issues/27746[#27746])
* Fixed:  Adapt doc for 9.0
    (https://issues.rudder.io/issues/27738[#27738])
* Fixed: API versions 21 is missing in documentation
    (https://issues.rudder.io/issues/27748[#27748])

==== Module - system-updates

* Fixed: Only the first service detected by needrestart is restarted after system update campaign
    (https://issues.rudder.io/issues/27732[#27732])

==== Web - UI & UX

* Fixed: The Settings -> Licence page should be name License
    (https://issues.rudder.io/issues/27191[#27191])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 9.0.0.rc2 (2025-10-15)

=== Changes


=== Bug fixes

==== API

* Fixed: systemUpdate/targets requieres a POST to get the list of nodes
    (https://issues.rudder.io/issues/27715[#27715])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 9.0.0.rc1 (2025-10-13)

=== Changes


==== Miscellaneous

* Update onboarding documentations
    (https://issues.rudder.io/issues/27604[#27604])
* Update onboarding documentations
    (https://issues.rudder.io/issues/27604[#27604])

==== Generic methods

* add metadata to the GM of the modules
    (https://issues.rudder.io/issues/27663[#27663])

==== CI

* Pin the typos-cli version
    (https://issues.rudder.io/issues/27684[#27684])

=== Bug fixes

==== Web - Technique editor

* Fixed: Rudder 9.0 Beta 2 : Error message when deleting technique in editor
    (https://issues.rudder.io/issues/27644[#27644])
* Fixed: Frozen method in the technique editor after reset of a draft
    (https://issues.rudder.io/issues/27564[#27564])

==== Module - augeas

* Fixed: fix supported_targets in augeas module metadata
    (https://issues.rudder.io/issues/27725[#27725])

==== Module - commands

* Fixed: fix warnings in commands module tests
    (https://issues.rudder.io/issues/27717[#27717])
* Fixed: Error with command_execution_results but everything looks ok
    (https://issues.rudder.io/issues/27683[#27683])

==== Web - UI & UX

* Fixed: "Close" button in API account modals uses the wrong CSS class
    (https://issues.rudder.io/issues/27713[#27713])
* Fixed: Notifications hides the button
    (https://issues.rudder.io/issues/27612[#27612])
* Fixed: Drag-and-drop icon appears when hovering a method over a block
    (https://issues.rudder.io/issues/27625[#27625])

==== Generic methods

* Fixed: Test the file_from_template_options method
    (https://issues.rudder.io/issues/27639[#27639])

==== Miscellaneous

* Fixed: Post-hooks for campaigns should be executed even even if pre-hooks are in failure
    (https://issues.rudder.io/issues/27574[#27574])

==== Web - Config management

* Fixed: The migrate button in directive pages is always displayed and often useless and ugly
    (https://issues.rudder.io/issues/24486[#24486])
* Fixed: Random error after node-to-relay is applied and other dynamic group and node accepted by API problems
    (https://issues.rudder.io/issues/27264[#27264])

==== Web - Nodes & inventories

* Fixed: Multiple JS error on properties page
    (https://issues.rudder.io/issues/27596[#27596])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 9.0.0.beta2 (2025-10-07)

=== Changes


==== Packaging

* Package the command module
    (https://issues.rudder.io/issues/27545[#27545])

==== Module - commands

* add uid/gid lookup by name for the commands module
    (https://issues.rudder.io/issues/27651[#27651])
* The command module should avoid using custom parsing methods for lists
    (https://issues.rudder.io/issues/27598[#27598])
* The command module should avoid using custom parsing methods for lists
    (https://issues.rudder.io/issues/27598[#27598])

==== Module - common

* Better logging for custom promise type protocol when a CFEngine request is malformed
    (https://issues.rudder.io/issues/27568[#27568])

==== API

* Return categoryId in JSON groups API
    (https://issues.rudder.io/issues/27531[#27531])

==== Architecture - Dependencies

* Ignore adler advisory in 8.2
    (https://issues.rudder.io/issues/27539[#27539])

=== Bug fixes

==== Packaging

* Fixed: openssl build broken on RHEL7
    (https://issues.rudder.io/issues/27664[#27664])
* Fixed: Missing flags for required CFEngine dependencies
    (https://issues.rudder.io/issues/27647[#27647])
* Fixed: Allow caching single files
    (https://issues.rudder.io/issues/27571[#27571])
* Fixed: Missing slash in cache path
    (https://issues.rudder.io/issues/27569[#27569])
* Fixed: Only cache the module binaries
    (https://issues.rudder.io/issues/27565[#27565])

==== Agent

* Fixed: Unable to install RHEL agent
    (https://issues.rudder.io/issues/27590[#27590])
* Fixed: APT agents are built without apt support in system-updates
    (https://issues.rudder.io/issues/27649[#27649])
* Fixed: Error trying to compile rudder-agent 8.3.4~git202508191033 on armhf Debian 13 trixie (libapt)
    (https://issues.rudder.io/issues/27459[#27459])
* Fixed: Agent stops when creating modules symlink
    (https://issues.rudder.io/issues/27526[#27526])

==== Security

* Fixed: Update curl & openssl
    (https://issues.rudder.io/issues/27558[#27558])
* Fixed: We need latest cargo deny to check licenses
    (https://issues.rudder.io/issues/27620[#27620])
* Fixed: XSS vulnerability in ammonia dep
    (https://issues.rudder.io/issues/27615[#27615])

==== Inventory

* Fixed: Incorrect script name in the Rudder inventory task
    (https://issues.rudder.io/issues/27534[#27534])

==== Documentation

* Fixed: Remove doc about automatically defined reporting section
    (https://issues.rudder.io/issues/27635[#27635])
* Fixed: Remove metion to AIX from the menu
    (https://issues.rudder.io/issues/27535[#27535])
* Fixed: System info API changed format in v21 and needs new documentation
    (https://issues.rudder.io/issues/26637[#26637])

==== Web - Campaigns

* Fixed: Inconsistency in campaigneventstate between init and DB migration
    (https://issues.rudder.io/issues/27674[#27674])
* Fixed: Campaign hook readme is incorrect
    (https://issues.rudder.io/issues/27544[#27544])

==== Generic methods

* Fixed: Document the file_from_template_options method
    (https://issues.rudder.io/issues/27646[#27646])
* Fixed: Test the command_execution_options generic method
    (https://issues.rudder.io/issues/27585[#27585])
* Fixed: [Regression] Rudder 9.0 Beta 2 : sysctl generic method causes apparent repair loops
    (https://issues.rudder.io/issues/27627[#27627])
* Fixed: Incorrect serialization of the parameters passed by the command_execution_options method to its underlying module
    (https://issues.rudder.io/issues/27550[#27550])

==== Techniques

* Fixed: Password setting from standard user technique fails after upgrade to Rudder 9.0 Beta 2
    (https://issues.rudder.io/issues/27622[#27622])

==== Module - templates

* Fixed: The file_from_template_options method should accept inline JSON in its data field
    (https://issues.rudder.io/issues/27636[#27636])

==== Architecture - Code maintenance

* Fixed: Scala compilation should happen in maven compile phase
    (https://issues.rudder.io/issues/27638[#27638])

==== Web - UI & UX

* Fixed: Copy button on first login page for creating user not working anymore
    (https://issues.rudder.io/issues/27588[#27588])
* Fixed: In technique editor the number of techniqes is under "techniques" big title
    (https://issues.rudder.io/issues/27595[#27595])
* Fixed: Nodes table has CSP error with column containing JSON property
    (https://issues.rudder.io/issues/27577[#27577])
* Fixed: Nodes server list can no longer be exported to CSV
    (https://issues.rudder.io/issues/27578[#27578])
* Fixed: Plugins error callouts width are same as title width
    (https://issues.rudder.io/issues/27561[#27561])
* Fixed: Compliance - No data available
    (https://issues.rudder.io/issues/27623[#27623])

==== Module - system-updates

* Fixed: Document how the services to restart and reboot state are computed
    (https://issues.rudder.io/issues/27553[#27553])

==== rudderc

* Fixed: Allow empty string in JSON fields
    (https://issues.rudder.io/issues/27548[#27548])

==== API

* Fixed: Make group tree API not include system by default
    (https://issues.rudder.io/issues/27498[#27498])
* Fixed: Missleading format for parameter category in API
    (https://issues.rudder.io/issues/27384[#27384])

==== System techniques

* Fixed: Missing report in http only mode
    (https://issues.rudder.io/issues/27563[#27563])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Pierre-Yves Taczynski

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 9.0.0.beta1 (2025-09-09)

=== Changes


==== Packaging

* Add apache conf template to the package
    (https://issues.rudder.io/issues/27517[#27517])
* Prepare Debian 13 packaging
    (https://issues.rudder.io/issues/27430[#27430])

==== Documentation

* Document server certificate change in 9.0
    (https://issues.rudder.io/issues/27390[#27390])
* User API update documentation is incorrect
    (https://issues.rudder.io/issues/27521[#27521])

==== System techniques

* Allow configuring the certificates
    (https://issues.rudder.io/issues/27451[#27451])

==== Architecture - Internal libs

* Move & update AuthorizationType into rudder-core
    (https://issues.rudder.io/issues/22595[#22595])
* Move & update AuthorizationType into rudder-core
    (https://issues.rudder.io/issues/22595[#22595])

==== Architecture - Code maintenance

* Using Cons for big lists can blow the compiler stack and prevent scala project compilation entirely
    (https://issues.rudder.io/issues/27412[#27412])
* Add a generic json codec for enumeratum
    (https://issues.rudder.io/issues/27364[#27364])

==== Agent

* Adding command module
    (https://issues.rudder.io/issues/27218[#27218])

==== Relay server or API

* Finish Rust dependency update
    (https://issues.rudder.io/issues/27404[#27404])

==== Security

* We need to resolve directory real path in our path trasversal check
    (https://issues.rudder.io/issues/27402[#27402])

==== rudderc

* Remove unused promises from rudderc generated techniques
    (https://issues.rudder.io/issues/27400[#27400])

==== Web - Campaigns

* Add campaign hooks in the campaign workflow engine
    (https://issues.rudder.io/issues/26883[#26883])

==== Web - UI & UX

* Make doughnut graphs accessible and manipulable
    (https://issues.rudder.io/issues/27391[#27391])
* Move the graph creation functions from homepage.js to another js file.
    (https://issues.rudder.io/issues/27329[#27329])

==== System integration

* Allow per-hook-kind logger
    (https://issues.rudder.io/issues/27365[#27365])

==== Architecture - Evolution

* Add an ID for node details tab content container
    (https://issues.rudder.io/issues/27358[#27358])

=== Bug fixes

==== Agent

* Fixed: Add a stricter permission control to the inventory hooks executed by the inventory on Windows nodes
    (https://issues.rudder.io/issues/27476[#27476])
* Fixed: Fix the rudder_info! macro to make it usable in audit mode
    (https://issues.rudder.io/issues/27450[#27450])

==== System integration

* Fixed: Upload large file in technique resources or file download returns error
    (https://issues.rudder.io/issues/27413[#27413])

==== Packaging

* Fixed: Missing rudder-sources when building rudderc
    (https://issues.rudder.io/issues/27441[#27441])
* Fixed: Missing rudder-sources when building rudderc
    (https://issues.rudder.io/issues/27441[#27441])
* Fixed: Add a compatibility flag for apt lib
    (https://issues.rudder.io/issues/27436[#27436])
* Fixed: perl-Digest-MD5 is missing from dependencies in RHEL6
    (https://issues.rudder.io/issues/25491[#25491])

==== Documentation

* Fixed: correct prerequisites for Rudder install
    (https://issues.rudder.io/issues/27395[#27395])
* Fixed: Add RHEL 10 in supported OS list
    (https://issues.rudder.io/issues/27362[#27362])

==== Web - UI & UX

* Fixed: Hosts table contains local ipv6 address
    (https://issues.rudder.io/issues/27112[#27112])
* Fixed: When the JSON property is invalid in global properties, the error is nasty
    (https://issues.rudder.io/issues/26718[#26718])
* Fixed: Cannot delete a technique from technique tree with grayed screen
    (https://issues.rudder.io/issues/27387[#27387])
* Fixed: There is no explanation as to why Save button is disabled
    (https://issues.rudder.io/issues/27386[#27386])
* Fixed: Event logs restore button creates as many confirmation blocks as clicks
    (https://issues.rudder.io/issues/25361[#25361])
* Fixed: When a technique is enabled, the directive page button to disabled it is way too exposed
    (https://issues.rudder.io/issues/27239[#27239])

==== Security

* Fixed: Vulnerability in tracing
    (https://issues.rudder.io/issues/27519[#27519])
* Fixed:  Ignore CVEs for icu4j
    (https://issues.rudder.io/issues/27437[#27437])
* Fixed: Hashed password is logged at debug level for all non OAuth2 users 
    (https://issues.rudder.io/issues/26767[#26767])

==== Web - Compliance & node report

* Fixed: Ignored nodes should be excluded from compliance and score processing
    (https://issues.rudder.io/issues/27446[#27446])

==== Generic methods

* Fixed: File_from_template_options fails to render a file when using a custom data as source
    (https://issues.rudder.io/issues/27515[#27515])
* Fixed: When the component value of a method is too long, the reporting can be missing
    (https://issues.rudder.io/issues/27167[#27167])

==== Web - Technique editor

* Fixed: No manual when a filter for methods in the technique editor right panel
    (https://issues.rudder.io/issues/26813[#26813])

==== CI

* Fixed: fix broken agent installation on CI
    (https://issues.rudder.io/issues/27469[#27469])
* Fixed: Missing curl dependency in the methods docker test image
    (https://issues.rudder.io/issues/27453[#27453])

==== Module - templates

* Fixed: Fix audit bug for the template module
    (https://issues.rudder.io/issues/27448[#27448])
* Fixed: Fixing rudder_module_type.yml for the template module
    (https://issues.rudder.io/issues/27381[#27381])

==== Miscellaneous

* Fixed: Dashboard will not display charts when switching between bechmarks
    (https://issues.rudder.io/issues/27370[#27370])

==== rudderc

* Fixed: Constraint doesn't allow to change variable
    (https://issues.rudder.io/issues/27363[#27363])

==== API

* Fixed: Nodes API payload for agentKey has the wrong JSON format
    (https://issues.rudder.io/issues/27369[#27369])

==== Module - system-updates

* Fixed: Security updates not applied on Debian 12, but campaign ends without error
    (https://issues.rudder.io/issues/26855[#26855])
* Fixed: Log the list of restarted services
    (https://issues.rudder.io/issues/27367[#27367])

==== Web - Maintenance

* Fixed: Users cleanup configuration is still too strict for disabling/deleting
    (https://issues.rudder.io/issues/27379[#27379])

==== Plugin manager cli

* Fixed: Quiet option still show spinner in rudder package
    (https://issues.rudder.io/issues/27371[#27371])

==== System techniques

* Fixed: Archive tarball contains wrong directories
    (https://issues.rudder.io/issues/27368[#27368])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Matthieu Baechler

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 9.0.0.alpha1 (2025-07-24)

=== Changes


==== Packaging

* Add a dependency on argon2 on server
    (https://issues.rudder.io/issues/27304[#27304])
* Build the template and inventory modules into the agent
    (https://issues.rudder.io/issues/27206[#27206])
* Cleanup perl build
    (https://issues.rudder.io/issues/27176[#27176])
* Update C dependencies
    (https://issues.rudder.io/issues/27093[#27093])
* Use new hardening options for C compiler
    (https://issues.rudder.io/issues/27060[#27060])
* Remove embedded perl support in rudder 9.0
    (https://issues.rudder.io/issues/26797[#26797])
* Remove letsencrypt root x1 from rudder packages
    (https://issues.rudder.io/issues/26796[#26796])
* Update rudder packages to 9.0 supported OS
    (https://issues.rudder.io/issues/26793[#26793])
* Remove the rudder-api-client package
    (https://issues.rudder.io/issues/26726[#26726])

==== Documentation

* Add link to techblog in docs
    (https://issues.rudder.io/issues/26943[#26943])
* Update the api doc toolchain
    (https://issues.rudder.io/issues/27118[#27118])

==== Miscellaneous

* Rework property hierarchy
    (https://issues.rudder.io/issues/27113[#27113])
* Migrate methods to logger v4
    (https://issues.rudder.io/issues/26732[#26732])
* Adding tests to the CI for the template module
    (https://issues.rudder.io/issues/26505[#26505])

==== Web - UI & UX

* Export pending nodes tables into CSV
    (https://issues.rudder.io/issues/27272[#27272])
* Improve drag'n drop ergonomics in the techniques editor
    (https://issues.rudder.io/issues/26921[#26921])
* Improve drag'n drop ergonomics in the techniques editor
    (https://issues.rudder.io/issues/26921[#26921])
* Improve drag'n drop ergonomics in the techniques editor
    (https://issues.rudder.io/issues/26921[#26921])

==== Architecture - Code maintenance

* Enforce UTC timezone for datetime
    (https://issues.rudder.io/issues/27084[#27084])
* Enable fatal warning and disable variable initialization check
    (https://issues.rudder.io/issues/27147[#27147])
* Scala3 - reorganize imports, clean unused values
    (https://issues.rudder.io/issues/27012[#27012])
* Deprecated method in chimney
    (https://issues.rudder.io/issues/27014[#27014])
* Port remaining lift-json into zio-json
    (https://issues.rudder.io/issues/26866[#26866])
* Compatibility fix for scala 3 in Rudder 9.0
    (https://issues.rudder.io/issues/26887[#26887])
* Clean-up insertion in ruddersysevents
    (https://issues.rudder.io/issues/26865[#26865])

==== Web - Config management

* Add new settings to handle certificate trust
    (https://issues.rudder.io/issues/26942[#26942])
* Export change logs table into CSV
    (https://issues.rudder.io/issues/27096[#27096])

==== Web - Technique editor

* Remove deprecated Windows versions from the technique editor
    (https://issues.rudder.io/issues/27198[#27198])

==== Architecture - Dependencies

* Update front-end dependencies
    (https://issues.rudder.io/issues/27103[#27103])
* Updating Rust version and dependencies
    (https://issues.rudder.io/issues/27168[#27168])
* Migration from Box to ZIO : Refactor XmlUnserialisation 
    (https://issues.rudder.io/issues/26861[#26861])
* Migration from Box to ZIO : Refactoring of classes ChangeRequest and ModificationValidationPopup
    (https://issues.rudder.io/issues/26853[#26853])

==== API

*  Add and Remove/deprecate API for Rudder 9.0 - version 22
    (https://issues.rudder.io/issues/27173[#27173])

==== Security

* Drop support for legacy password hash algorithms
    (https://issues.rudder.io/issues/27128[#27128])
* Add argon2id support for local hash
    (https://issues.rudder.io/issues/26996[#26996])
* Enable CSP on all pages and add tag to exclude a page 
    (https://issues.rudder.io/issues/26934[#26934])

==== Generic methods

* Remove the old methods test framework in 9.0
    (https://issues.rudder.io/issues/27038[#27038])
* Remove the old methods test framework in 9.0
    (https://issues.rudder.io/issues/27038[#27038])
* Migrate user methods to logger v4
    (https://issues.rudder.io/issues/26746[#26746])

==== Web - Compliance & node report

* Export technical logs table into CSV
    (https://issues.rudder.io/issues/27047[#27047])

==== Web - Nodes & inventories

* Export node inventories tables into CSV
    (https://issues.rudder.io/issues/27031[#27031])

==== Architecture - Evolution

* Switch to Scala 3
    (https://issues.rudder.io/issues/27034[#27034])

==== Agent

* Updating Rust dependencies and compiler version
    (https://issues.rudder.io/issues/27066[#27066])
* Updating rust-mustache dependency
    (https://issues.rudder.io/issues/26848[#26848])
* Adding Ansible compatible filters for minijinja engine
    (https://issues.rudder.io/issues/26614[#26614])
* Adding support for calling Jinja2 from python in template module
    (https://issues.rudder.io/issues/26567[#26567])
* Adding a parameter to hide diffs in the report of the template module
    (https://issues.rudder.io/issues/26527[#26527])
* Adding diff to report in template module
    (https://issues.rudder.io/issues/26517[#26517])
* Adding diff to report in template module
    (https://issues.rudder.io/issues/26517[#26517])
* Adding diff to report in template module
    (https://issues.rudder.io/issues/26517[#26517])
* Adding diff to report in template module
    (https://issues.rudder.io/issues/26517[#26517])

==== Module - templates

* Adding documentation for the template module
    (https://issues.rudder.io/issues/27009[#27009])
* Adding audit flag to the CLI
    (https://issues.rudder.io/issues/26971[#26971])
* Adding a Windows runner from GitHub Actions to the template module
    (https://issues.rudder.io/issues/26930[#26930])

==== System techniques

* Cleanup update promises
    (https://issues.rudder.io/issues/27177[#27177])
* remove usage of agent_capability_http_reporting
    (https://issues.rudder.io/issues/27070[#27070])
* Migrate the server system techniques to rudder_logger_v4
    (https://issues.rudder.io/issues/26932[#26932])

==== Server components

* cleanup rudder server create-user
    (https://issues.rudder.io/issues/27303[#27303])
* Add support to download policies via https archives
    (https://issues.rudder.io/issues/27137[#27137])

=== Bug fixes

==== Packaging

* Fixed: Add LD_LIBRARY_PATH to augeas module build
    (https://issues.rudder.io/issues/27097[#27097])
* Fixed: Agent package builds leak rpath
    (https://issues.rudder.io/issues/27059[#27059])
* Fixed: CFengine patch for proper identification of ArchLinux and Manjaro Linux nodes
    (https://issues.rudder.io/issues/26915[#26915])
* Fixed: Broken nettle dep on Debian
    (https://issues.rudder.io/issues/26176[#26176])
* Fixed: raugeas does not build on arm
    (https://issues.rudder.io/issues/26227[#26227])

==== Miscellaneous

* Fixed: Remove two useless “chown root” that prevents building the agent without being root
    (https://issues.rudder.io/issues/26895[#26895])
* Fixed: the logo doesn't display well anymore
    (https://issues.rudder.io/issues/27316[#27316])
* Fixed: Creating global parameter with change-validation enabled leads to 404
    (https://issues.rudder.io/issues/27145[#27145])

==== rudderc

* Fixed: rudderc built-in methods should come from the rudder repo
    (https://issues.rudder.io/issues/27325[#27325])
* Fixed: The Rudderc static binary still includes the outdated ncf library rather than the 8.3+ one
    (https://issues.rudder.io/issues/27308[#27308])

==== Architecture - Code maintenance

* Fixed: NodeInfo instead of CoreNodeFact causing compilation error
    (https://issues.rudder.io/issues/27319[#27319])
* Fixed: Synchronize scalafmt with plugins need
    (https://issues.rudder.io/issues/27265[#27265])
* Fixed: Add .scala.semanticdb in gitignore
    (https://issues.rudder.io/issues/27157[#27157])
* Fixed: Scala3: port RestDataExtractorTest to ZIO
    (https://issues.rudder.io/issues/27016[#27016])

==== Security

* Fixed: Cannot remove all rights from a user who has a single role, from the User management GUI
    (https://issues.rudder.io/issues/27211[#27211])
* Fixed: Update jgit to last version against XXE
    (https://issues.rudder.io/issues/27006[#27006])
* Fixed: Advisories in Rust deps
    (https://issues.rudder.io/issues/26872[#26872])

==== Web - Compliance & node report

* Fixed: the hover on compliance shows HTML
    (https://issues.rudder.io/issues/25584[#25584])

==== Web - UI & UX

* Fixed: Export in CSV concatenate IPs without spaces or delimiters
    (https://issues.rudder.io/issues/27273[#27273])
* Fixed: Missing enable / disable action button for group
    (https://issues.rudder.io/issues/27127[#27127])

==== Architecture - Dependencies

* Fixed: We must specify magnolia version, else it conflicts on difflicious
    (https://issues.rudder.io/issues/27269[#27269])

==== Module - templates

* Fixed: Adding linux generic method for the template module
    (https://issues.rudder.io/issues/27230[#27230])
* Fixed: Improving the clarity of error messages in the template module.
    (https://issues.rudder.io/issues/27094[#27094])
* Fixed: Assigning permissions to GitHub Actions
    (https://issues.rudder.io/issues/26998[#26998])

==== CI

* Fixed: Add the x86_64-pc-windows-gnu cross compilation target to the rust toolchain
    (https://issues.rudder.io/issues/27204[#27204])
* Fixed: Allow LGPL license 2.1 dependencies
    (https://issues.rudder.io/issues/26870[#26870])
* Fixed: Use 8.3 package in 9.0 tests for now
    (https://issues.rudder.io/issues/26588[#26588])

==== Module - augeas

* Fixed: Fix warnings in augeas module
    (https://issues.rudder.io/issues/27122[#27122])

==== Web - Maintenance

* Fixed: Missing webapp dependency
    (https://issues.rudder.io/issues/27098[#27098])

==== Generic methods

* Fixed: Port the permissions_user_acl_absent and permissions_user_acl_present methods to logger v4
    (https://issues.rudder.io/issues/27044[#27044])
* Fixed: Port more generic methods to logger v4
    (https://issues.rudder.io/issues/26859[#26859])
* Fixed: Port to log v4 and test more legacy methods
    (https://issues.rudder.io/issues/26736[#26736])

==== Agent

* Fixed: fixing windows compatibility for the template module
    (https://issues.rudder.io/issues/26914[#26914])
* Fixed: Change default template engine to Minijinja
    (https://issues.rudder.io/issues/26884[#26884])
* Fixed: Agent template module does not compile on Windows.
    (https://issues.rudder.io/issues/26513[#26513])
* Fixed: rudder-client fails to send inventory
    (https://issues.rudder.io/issues/27294[#27294])

==== Techniques

* Fixed: Missing report on built-in directive when removing users en Windows
    (https://issues.rudder.io/issues/27301[#27301])
* Fixed: Migrate the manageKeyValueFile builtin technique to logger V4
    (https://issues.rudder.io/issues/27109[#27109])

==== System techniques

* Fixed: Fix reporting issues on server system techniques
    (https://issues.rudder.io/issues/27117[#27117])

==== Server components

* Fixed: rudder server create-user doesn't work with argon2
    (https://issues.rudder.io/issues/27293[#27293])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

