= Change logs for Rudder 9.0

==  Rudder 9.0.0.alpha1 (2025-07-24)

=== Changes


==== Packaging

* Add a dependency on argon2 on server
    (https://issues.rudder.io/issues/27304[#27304])
* Build the template and inventory modules into the agent
    (https://issues.rudder.io/issues/27206[#27206])
* Cleanup perl build
    (https://issues.rudder.io/issues/27176[#27176])
* Update C dependencies
    (https://issues.rudder.io/issues/27093[#27093])
* Use new hardening options for C compiler
    (https://issues.rudder.io/issues/27060[#27060])
* Remove embedded perl support in rudder 9.0
    (https://issues.rudder.io/issues/26797[#26797])
* Remove letsencrypt root x1 from rudder packages
    (https://issues.rudder.io/issues/26796[#26796])
* Update rudder packages to 9.0 supported OS
    (https://issues.rudder.io/issues/26793[#26793])
* Remove the rudder-api-client package
    (https://issues.rudder.io/issues/26726[#26726])

==== Documentation

* Add link to techblog in docs
    (https://issues.rudder.io/issues/26943[#26943])
* Update the api doc toolchain
    (https://issues.rudder.io/issues/27118[#27118])

==== Miscellaneous

* Rework property hierarchy
    (https://issues.rudder.io/issues/27113[#27113])
* Migrate methods to logger v4
    (https://issues.rudder.io/issues/26732[#26732])
* Adding tests to the CI for the template module
    (https://issues.rudder.io/issues/26505[#26505])

==== Web - UI & UX

* Export pending nodes tables into CSV
    (https://issues.rudder.io/issues/27272[#27272])
* Improve drag'n drop ergonomics in the techniques editor
    (https://issues.rudder.io/issues/26921[#26921])
* Improve drag'n drop ergonomics in the techniques editor
    (https://issues.rudder.io/issues/26921[#26921])
* Improve drag'n drop ergonomics in the techniques editor
    (https://issues.rudder.io/issues/26921[#26921])

==== Architecture - Code maintenance

* Enforce UTC timezone for datetime
    (https://issues.rudder.io/issues/27084[#27084])
* Enable fatal warning and disable variable initialization check
    (https://issues.rudder.io/issues/27147[#27147])
* Scala3 - reorganize imports, clean unused values
    (https://issues.rudder.io/issues/27012[#27012])
* Deprecated method in chimney
    (https://issues.rudder.io/issues/27014[#27014])
* Port remaining lift-json into zio-json
    (https://issues.rudder.io/issues/26866[#26866])
* Compatibility fixe for scala 3 in Rudder 9.0
    (https://issues.rudder.io/issues/26887[#26887])
* Clean-up insertion in ruddersysevents
    (https://issues.rudder.io/issues/26865[#26865])

==== Web - Config management

* Add new settings to handle certificate trust
    (https://issues.rudder.io/issues/26942[#26942])
* Export change logs table into CSV
    (https://issues.rudder.io/issues/27096[#27096])

==== Web - Technique editor

* Remove deprecated Windows versions from the technique editor
    (https://issues.rudder.io/issues/27198[#27198])

==== Architecture - Dependencies

* Update front-end dependencies
    (https://issues.rudder.io/issues/27103[#27103])
* Updating Rust version and dependencies
    (https://issues.rudder.io/issues/27168[#27168])
* Migration from Box to ZIO : Refactor XmlUnserialisation 
    (https://issues.rudder.io/issues/26861[#26861])
* Migration from Box to ZIO : Refactoring of classes ChangeRequest and ModificationValidationPopup
    (https://issues.rudder.io/issues/26853[#26853])

==== API

*  Add and Remove/deprecate API for Rudder 9.0 - version 22
    (https://issues.rudder.io/issues/27173[#27173])

==== Security

* Drop support for legacy password hash algorithms
    (https://issues.rudder.io/issues/27128[#27128])
* Add argon2id support for local hash
    (https://issues.rudder.io/issues/26996[#26996])
* Enable CSP on all pages and add tag to exclude a page 
    (https://issues.rudder.io/issues/26934[#26934])

==== Generic methods

* Remove the old methods test framework in 9.0
    (https://issues.rudder.io/issues/27038[#27038])
* Remove the old methods test framework in 9.0
    (https://issues.rudder.io/issues/27038[#27038])
* Migrate user methods to logger v4
    (https://issues.rudder.io/issues/26746[#26746])

==== Web - Compliance & node report

* Export technical logs table into CSV
    (https://issues.rudder.io/issues/27047[#27047])

==== Web - Nodes & inventories

* Export node inventories tables into CSV
    (https://issues.rudder.io/issues/27031[#27031])

==== Architecture - Evolution

* Switch to Scala 3
    (https://issues.rudder.io/issues/27034[#27034])

==== Agent

* Updating Rust dependencies and compiler version
    (https://issues.rudder.io/issues/27066[#27066])
* Updating rust-mustache dependency
    (https://issues.rudder.io/issues/26848[#26848])
* Adding Ansible compatible filters for minijinja engine
    (https://issues.rudder.io/issues/26614[#26614])
* Adding support for calling Jinja2 from python in template module
    (https://issues.rudder.io/issues/26567[#26567])
* Adding a parameter to hide diffs in the report of the template module
    (https://issues.rudder.io/issues/26527[#26527])
* Adding diff to report in template module
    (https://issues.rudder.io/issues/26517[#26517])
* Adding diff to report in template module
    (https://issues.rudder.io/issues/26517[#26517])
* Adding diff to report in template module
    (https://issues.rudder.io/issues/26517[#26517])
* Adding diff to report in template module
    (https://issues.rudder.io/issues/26517[#26517])

==== Module - templates

* Adding documentation for the template module
    (https://issues.rudder.io/issues/27009[#27009])
* Adding audit flag to the CLI
    (https://issues.rudder.io/issues/26971[#26971])
* Adding a Windows runner from GitHub Actions to the template module
    (https://issues.rudder.io/issues/26930[#26930])

==== System techniques

* Cleanup update promises
    (https://issues.rudder.io/issues/27177[#27177])
* remove usage of agent_capability_http_reporting
    (https://issues.rudder.io/issues/27070[#27070])
* Migrate the server system techniques to rudder_logger_v4
    (https://issues.rudder.io/issues/26932[#26932])

==== Server components

* cleanup rudder server create-user
    (https://issues.rudder.io/issues/27303[#27303])
* Add support to download policies via https archives
    (https://issues.rudder.io/issues/27137[#27137])

=== Bug fixes

==== Packaging

* Fixed: Add LD_LIBRARY_PATH to augeas module build
    (https://issues.rudder.io/issues/27097[#27097])
* Fixed: Agent package builds leak rpath
    (https://issues.rudder.io/issues/27059[#27059])
* Fixed: CFengine patch for proper identification of ArchLinux and Manjaro Linux nodes
    (https://issues.rudder.io/issues/26915[#26915])
* Fixed: Broken nettle dep on Debian
    (https://issues.rudder.io/issues/26176[#26176])
* Fixed: raugeas does not build on arm
    (https://issues.rudder.io/issues/26227[#26227])

==== Miscellaneous

* Fixed: Remove two useless “chown root” that prevents building the agent without being root
    (https://issues.rudder.io/issues/26895[#26895])
* Fixed: the logo doesn't display well anymore
    (https://issues.rudder.io/issues/27316[#27316])
* Fixed: Creating global parameter with change-validation enabled leads to 404
    (https://issues.rudder.io/issues/27145[#27145])

==== rudderc

* Fixed: rudderc built-in methods should come from the rudder repo
    (https://issues.rudder.io/issues/27325[#27325])
* Fixed: The Rudderc static binary still includes the outdated ncf library rather than the 8.3+ one
    (https://issues.rudder.io/issues/27308[#27308])

==== Architecture - Code maintenance

* Fixed: NodeInfo instead of CoreNodeFact causing compilation error
    (https://issues.rudder.io/issues/27319[#27319])
* Fixed: Synchronize scalafmt with plugins need
    (https://issues.rudder.io/issues/27265[#27265])
* Fixed: Add .scala.semanticdb in gitignore
    (https://issues.rudder.io/issues/27157[#27157])
* Fixed: Scala3: port RestDataExtractorTest to ZIO
    (https://issues.rudder.io/issues/27016[#27016])

==== Security

* Fixed: Cannot remove all rights from a user who has a single role, from the User management GUI
    (https://issues.rudder.io/issues/27211[#27211])
* Fixed: Update jgit to last version against XXE
    (https://issues.rudder.io/issues/27006[#27006])
* Fixed: Advisories in Rust deps
    (https://issues.rudder.io/issues/26872[#26872])

==== Web - Compliance & node report

* Fixed: the hover on compliance shows HTML
    (https://issues.rudder.io/issues/25584[#25584])

==== Web - UI & UX

* Fixed: Export in CSV concatenate IPs without spaces or delimiters
    (https://issues.rudder.io/issues/27273[#27273])
* Fixed: Missing enable / disable action button for group
    (https://issues.rudder.io/issues/27127[#27127])

==== Architecture - Dependencies

* Fixed: We must specify magnolia version, else it conflicts on difflicious
    (https://issues.rudder.io/issues/27269[#27269])

==== Module - templates

* Fixed: Adding linux generic method for the template module
    (https://issues.rudder.io/issues/27230[#27230])
* Fixed: Improving the clarity of error messages in the template module.
    (https://issues.rudder.io/issues/27094[#27094])
* Fixed: Assigning permissions to GitHub Actions
    (https://issues.rudder.io/issues/26998[#26998])

==== CI

* Fixed: Add the x86_64-pc-windows-gnu cross compilation target to the rust toolchain
    (https://issues.rudder.io/issues/27204[#27204])
* Fixed: Allow LGPL license 2.1 dependencies
    (https://issues.rudder.io/issues/26870[#26870])
* Fixed: Use 8.3 package in 9.0 tests for now
    (https://issues.rudder.io/issues/26588[#26588])

==== Module - augeas

* Fixed: Fix warnings in augeas module
    (https://issues.rudder.io/issues/27122[#27122])

==== Web - Maintenance

* Fixed: Missing webapp dependency
    (https://issues.rudder.io/issues/27098[#27098])

==== Generic methods

* Fixed: Port the permissions_user_acl_absent and permissions_user_acl_present methods to logger v4
    (https://issues.rudder.io/issues/27044[#27044])
* Fixed: Port more generic methods to logger v4
    (https://issues.rudder.io/issues/26859[#26859])
* Fixed: Port to log v4 and test more legacy methods
    (https://issues.rudder.io/issues/26736[#26736])

==== Agent

* Fixed: fixing windows compatibility for the template module
    (https://issues.rudder.io/issues/26914[#26914])
* Fixed: Change default template engine to Minijinja
    (https://issues.rudder.io/issues/26884[#26884])
* Fixed: Agent template module does not compile on Windows.
    (https://issues.rudder.io/issues/26513[#26513])
* Fixed: rudder-client fails to send inventory
    (https://issues.rudder.io/issues/27294[#27294])

==== Techniques

* Fixed: Missing report on built-in directive when removing users en Windows
    (https://issues.rudder.io/issues/27301[#27301])
* Fixed: Migrate the manageKeyValueFile builtin technique to logger V4
    (https://issues.rudder.io/issues/27109[#27109])

==== System techniques

* Fixed: Fix reporting issues on server system techniques
    (https://issues.rudder.io/issues/27117[#27117])

==== Server components

* Fixed: rudder server create-user doesn't work with argon2
    (https://issues.rudder.io/issues/27293[#27293])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

