Changelogs for Rudder plugin api-authorizations 4.3.* versions
--------------------------------------------------------------

 Plugin api-authorizations - api-authorizations-4.3-1.2 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Bug fixes
^^^^^^^^^

Miscellaneous
+++++++++++++

* Fixed: ACL API does not write the correct ACL "*" element
(https://issues.rudder.io/issues/13082[#13082])
* Fixed: Incorrect verification of plugin status for API authz
(https://issues.rudder.io/issues/13079[#13079])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin api-authorizations - api-authorizations-4.3-1.1 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Bug fixes
^^^^^^^^^

Miscellaneous
+++++++++++++

* Fixed: License incorrectly interpreted in several plugins
(https://issues.rudder.io/issues/13054[#13054])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin api-authorizations - api-authorizations-4.3-1.0 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Miscellaneous
+++++++++++++

* Documentation for API authorizations plugin
(https://issues.rudder.io/issues/13009[#13009])
* UI enhancement for API ACL selection
(https://issues.rudder.io/issues/12843[#12843])
* Add an interface to manage User Api account token
(https://issues.rudder.io/issues/11948[#11948])
* Interface to manage ACL and user token for API authorization
(https://issues.rudder.io/issues/12203[#12203])
* Plugin for API authorization ACL
(https://issues.rudder.io/issues/12112[#12112])

Packaging
+++++++++

* Remove plugin-common from rudder-plugins
(https://issues.rudder.io/issues/12910[#12910])

Bug fixes
^^^^^^^^^

Packaging
+++++++++

* Fixed: Multiple plugin build errors in 4.3
(https://issues.rudder.io/issues/12835[#12835])

Miscellaneous
+++++++++++++

* Fixed: API Authz plugin is not updated to last version of build system
(https://issues.rudder.io/issues/12797[#12797])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
