= Change logs for datasources plugin 4.3

== datasources-4.3-1.4 (2018-11-28)

=== Changes

==== Miscellaneous

* Move plugins docs to rudder-plugins
(https://issues.rudder.io/issues/13002[#13002])

==== Packaging

* Remove plugin-common from rudder-plugins
(https://issues.rudder.io/issues/12910[#12910])

=== Bug fixes

==== Miscellaneous

* Fixed: Datasource plugin does not declare its APIs
(https://issues.rudder.io/issues/12918[#12918])
* Fixed: Datasources postinst SQL does not use Rudder connection
parameters (https://issues.rudder.io/issues/12792[#12792])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== datasources-4.3-1.3 (2018-11-28)

=== Changes

==== Packaging

* Change plugins version to 4.3
(https://issues.rudder.io/issues/12075[#12075])

==== Miscellaneous

* Update Datasources plugin to Rudder v4.3 API
(https://issues.rudder.io/issues/11926[#11926])

=== Bug fixes

==== Packaging

* Fixed: Plugins need a release before 4.3.3 API change
(https://issues.rudder.io/issues/12860[#12860])
* Fixed: Multiple plugin build errors in 4.3
(https://issues.rudder.io/issues/12835[#12835])

==== Miscellaneous

* Fixed: Bad internal API URL in datasources for Rudder 4.3
(https://issues.rudder.io/issues/12416[#12416])
* Fixed: Datasource compilation error with API provider trait
(https://issues.rudder.io/issues/12255[#12255])
* Fixed: datasources plugin is missing LICENSE file
(https://issues.rudder.io/issues/12170[#12170])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.3 series and therefore all
installations of 4.3.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
