= Changelogs for Rudder plugin change-validation 9.2.\* versions

== change-validation-9.2.0.beta1-2.4 (2026-08-31)

=== Changes


==== Miscellaneous

* Log when a user is validating or deploying his own change request
    (https://issues.rudder.io/issues/28576[#28576])

=== Bug fixes

==== Miscellaneous

* Fixed: Validation button are present when you can't self-validate
    (https://issues.rudder.io/issues/29375[#29375])
* Fixed: webapp non-root: fix change-validation postinst
    (https://issues.rudder.io/issues/29467[#29467])

=== Release notes

This is a bug fix release in the 9.2 series and therefore all installations of 9.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-9.2.0.alpha1-2.4 (2026-07-21)

=== Changes


==== Miscellaneous

* Bump rudder-elm-library version to 0.2.5
    (https://issues.rudder.io/issues/29261[#29261])

=== Bug fixes

==== Miscellaneous

* Fixed: self-validation parameter is ignored
    (https://issues.rudder.io/issues/29240[#29240])
* Fixed: webapp non-root: fix broken postinst
    (https://issues.rudder.io/issues/29214[#29214])
* Fixed: webapp non-root: fix postinst in rudder-plugins
    (https://issues.rudder.io/issues/29156[#29156])

=== Release notes

This is a bug fix release in the 9.2 series and therefore all installations of 9.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

