= Changelogs for Rudder plugin dsc 9.2.\* versions

== dsc-9.2.0.beta1-2.12 (2026-08-31)

=== Changes


==== CLI

* rudder agent check should handle agentd
    (https://issues.rudder.io/issues/29622[#29622])

==== Packaging

* Customize the UI installer background to use the Rudder logo
    (https://issues.rudder.io/issues/29639[#29639])
* Deploy the tmp/backups folder using at install time
    (https://issues.rudder.io/issues/29629[#29629])
* Make the agent postinst handle the agentd service startup
    (https://issues.rudder.io/issues/29581[#29581])

==== ci

* Keep the minimal time possible the artefacts used in CI tests
    (https://issues.rudder.io/issues/29588[#29588])

==== System techniques

* Add rudder agentd configuration handling in dsc common system technique
    (https://issues.rudder.io/issues/29353[#29353])

==== Generic methods

* Make the File-Template-Options generic method use the Rudder Module Runner if available
    (https://issues.rudder.io/issues/29429[#29429])

=== Bug fixes

==== Rudder web app

* Fixed: 91-compress-dsc-policies policy hook fails to set the correct permissions to the Windows nodes zip policies
    (https://issues.rudder.io/issues/29608[#29608])

==== Miscellaneous

* Fixed: Add set -e to shell scripts in rudder-plugins-private
    (https://issues.rudder.io/issues/29570[#29570])
* Fixed: webapp non-root: fix dsc 91-compress-dsc-policies hook
    (https://issues.rudder.io/issues/29538[#29538])
* Fixed: fix broken dsc postinst
    (https://issues.rudder.io/issues/29403[#29403])

==== Generic methods

* Fixed: Missing report message when using the File-From-Template-Options generic method
    (https://issues.rudder.io/issues/29616[#29616])
* Fixed: “Registry Entry Present” generic method doesn't work properly for multistring type
    (https://issues.rudder.io/issues/28766[#28766])
* Fixed: Port #29187 to Windows
    (https://issues.rudder.io/issues/29393[#29393])
* Fixed: “Registry Entry Present” generic method doesn't work properly for multistring type
    (https://issues.rudder.io/issues/28766[#28766])
* Fixed: “Registry Entry Present” generic method doesn't work properly for multistring type
    (https://issues.rudder.io/issues/28766[#28766])
* Fixed: “Registry Entry Present” generic method doesn't work properly for multistring type
    (https://issues.rudder.io/issues/28766[#28766])
* Fixed: “Registry Entry Present” generic method doesn't work properly for multistring type
    (https://issues.rudder.io/issues/28766[#28766])
* Fixed: “Registry Entry Present” generic method doesn't work properly for multistring type
    (https://issues.rudder.io/issues/28766[#28766])
* Fixed: “Registry Entry Present” generic method doesn't work properly for multistring type
    (https://issues.rudder.io/issues/28766[#28766])

==== Misc

* Fixed: Cleanup more plugin files from the repository
    (https://issues.rudder.io/issues/29610[#29610])

==== Agent library

* Fixed: Fix windows inventery start time with agentd
    (https://issues.rudder.io/issues/29572[#29572])

==== Packaging

* Fixed: Move the agent event log maintenance to the MSI
    (https://issues.rudder.io/issues/29560[#29560])
* Fixed: Add the Rudder application event log to the MSI installer
    (https://issues.rudder.io/issues/29542[#29542])
* Fixed: Missing 'Rudder\inventories' folder after install
    (https://issues.rudder.io/issues/29511[#29511])

=== Release notes

This is a bug fix release in the 9.2 series and therefore all installations of 9.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-9.2.0.alpha1-2.12 (2026-07-20)

=== Changes


==== Agent library

* Add a Rudder module runner to the .NET library
    (https://issues.rudder.io/issues/29057[#29057])
* Force the minimal .NET requirement to net standard 2.0
    (https://issues.rudder.io/issues/28999[#28999])

==== ci

* Update the dev/build dependencies
    (https://issues.rudder.io/issues/29116[#29116])
* Add some CI packaging tests
    (https://issues.rudder.io/issues/28966[#28966])

==== Packaging

* Add agentd service to windows agent package
    (https://issues.rudder.io/issues/29047[#29047])
* Port the wix build to MSBuild
    (https://issues.rudder.io/issues/28821[#28821])
* Migrate the MSI installer from Wix v3 to Wix v6
    (https://issues.rudder.io/issues/28694[#28694])

=== Bug fixes

==== Packaging

* Fixed: Broken postinst in dsc
    (https://issues.rudder.io/issues/29281[#29281])
* Fixed: Port 29219 to the merge powershell script
    (https://issues.rudder.io/issues/29259[#29259])
* Fixed: Use uconv instead of sed to remove UTF-8 BOM from powershell scripts at build time 
    (https://issues.rudder.io/issues/29219[#29219])
* Fixed: Upmerge broke docker build
    (https://issues.rudder.io/issues/29038[#29038])

==== Miscellaneous

* Fixed: webapp non-root: fix postinst in rudder-plugins-private
    (https://issues.rudder.io/issues/29158[#29158])

==== System techniques

* Fixed: Fix the initial policies
    (https://issues.rudder.io/issues/29271[#29271])

==== Generic methods

* Fixed: Make Rudder-PowershellExecution timeout configurable
    (https://issues.rudder.io/issues/29176[#29176])
* Fixed: Fix the call to the module protocol Library
    (https://issues.rudder.io/issues/29168[#29168])

==== ci

* Fixed: Keep the generated msi path consistent with earlier versions in the build
    (https://issues.rudder.io/issues/28909[#28909])

=== Release notes

This is a bug fix release in the 9.2 series and therefore all installations of 9.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

