= Change logs for Rudder 7.2

== Rudder 7.2.1 (2022-10-12)

=== Changes


==== Documentation

* Document the changes done to the windows agent in the 7.2 release
    (https://issues.rudder.io/issues/21890[#21890])

==== System techniques

* Remove system update technique from Rudder
    (https://issues.rudder.io/issues/21910[#21910])
* Use dist-upgrade for system-update
    (https://issues.rudder.io/issues/21906[#21906])

==== CI

* Remove system-update technique tests
    (https://issues.rudder.io/issues/21920[#21920])

=== Bug fixes

==== Security

* Fixed: CVE in rudder-jetty - 7.2
    (https://issues.rudder.io/issues/21887[#21887])
* Fixed: CVE in Jetty 9.4.32 Rudder 6.2
    (https://issues.rudder.io/issues/21888[#21888])
* Fixed: CVE in nuprocess 2.03 and below
    (https://issues.rudder.io/issues/21893[#21893])

==== Documentation

* Fixed: Format of target group is wrong in API doc
    (https://issues.rudder.io/issues/21935[#21935])

==== Web - UI & UX

* Fixed: User technique should be on top in directive tree
    (https://issues.rudder.io/issues/21917[#21917])
* Fixed: Unable to sort on property in list of nodes tab
    (https://issues.rudder.io/issues/21503[#21503])
* Fixed: Chart show the tooltips only when clicking
    (https://issues.rudder.io/issues/21911[#21911])

==== Miscellaneous

* Fixed: Quick search does not return node name when looking for properties but node id instead
    (https://issues.rudder.io/issues/21901[#21901])
* Fixed: System techniques should not be displayed in directive tree
    (https://issues.rudder.io/issues/21892[#21892])

==== CI

* Fixed: Broken Java 17 tests on 7.2+
    (https://issues.rudder.io/issues/21900[#21900])

==== Web - Config management

* Fixed: Broken technique indentation with jvm >= 12
    (https://issues.rudder.io/issues/21899[#21899])
* Fixed: Links in {directive|rule|group|technique} "tree" can not be open in a new tab
    (https://issues.rudder.io/issues/21373[#21373])

==== Agent

* Fixed: Epoch is displayed in agent version in webapp
    (https://issues.rudder.io/issues/21411[#21411])

==== Architecture - Dependencies

* Fixed: Update scala-lib version due to CVE2022-36944
    (https://issues.rudder.io/issues/21869[#21869])

==== System techniques

* Fixed: Missing report from the system update technique
    (https://issues.rudder.io/issues/21919[#21919])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Alexis TARUSSIO

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 7.2.0 (2022-09-28)

=== Changes


==== Agent

* Add in the agent a feature to express that it support not sending syslog message
    (https://issues.rudder.io/issues/21771[#21771])
* Allow users to specify node hostname (FQDN)
    (https://issues.rudder.io/issues/8022[#8022])

==== Web - Campaigns

* Campaign events api should be sortable
    (https://issues.rudder.io/issues/21849[#21849])

==== CI

* Update dependency check for 7.2
    (https://issues.rudder.io/issues/21830[#21830])

==== Miscellaneous

* Add link to the documentation in the Hooks page
    (https://issues.rudder.io/issues/21791[#21791])

==== System integration

* add an option to select where to log in syslog
    (https://issues.rudder.io/issues/21778[#21778])

==== Generic methods

* Add an audit command generic method
    (https://issues.rudder.io/issues/21763[#21763])
* Precise the documentation of the condition_from_variable_match method
    (https://issues.rudder.io/issues/21744[#21744])
* Improve the command_execution documentation for windows
    (https://issues.rudder.io/issues/21734[#21734])
* Add documentation for package_present update cache
    (https://issues.rudder.io/issues/21412[#21412])

=== Bug fixes

==== Agent

* Fixed: When cf-serverd starts it can kill an unrelated process
    (https://issues.rudder.io/issues/21100[#21100])
* Fixed: Curl build for windows agents must support schannel backend
    (https://issues.rudder.io/issues/21760[#21760])
* Fixed: Broken report parsing when the key value contains line breaks
    (https://issues.rudder.io/issues/21736[#21736])
* Fixed: rudder agent check may not restart cf-execd if an agent is frozen
    (https://issues.rudder.io/issues/21774[#21774])

==== Documentation

* Fixed: Missing ubuntu 22.04 support in documentation
    (https://issues.rudder.io/issues/21721[#21721])
* Fixed: Wrong method for reload technique in API doc
    (https://issues.rudder.io/issues/21762[#21762])

==== Web - Campaigns

* Fixed: One shot schedule condition is invalid
    (https://issues.rudder.io/issues/21865[#21865])
* Fixed: Campaign json should be versionned
    (https://issues.rudder.io/issues/21811[#21811])
* Fixed: Switch campaign schedule from a duration to a end time
    (https://issues.rudder.io/issues/21792[#21792])
* Fixed: Allow to delete a campaign
    (https://issues.rudder.io/issues/21775[#21775])
* Fixed: Reschedule correctly campaign events when a campaign changes
    (https://issues.rudder.io/issues/21766[#21766])
* Fixed: Error on system update campaign technique on SLES 12
    (https://issues.rudder.io/issues/21867[#21867])

==== Web - UI & UX

* Fixed: colors of mixed mode doesn't match enforce and audit
    (https://issues.rudder.io/issues/21837[#21837])
* Fixed: Impossible to move groups
    (https://issues.rudder.io/issues/21755[#21755])
* Fixed: Added a warning icon in a rule details if no target has been selected 
    (https://issues.rudder.io/issues/21789[#21789])
* Fixed: Input Text disapear in technic editor when entering a space with Grammarly/LanguageTool extension
    (https://issues.rudder.io/issues/21172[#21172])
* Fixed: Add css code to generate datatable loading animation
    (https://issues.rudder.io/issues/21711[#21711])

==== Security

* Fixed: Remove Rudder version from login form
    (https://issues.rudder.io/issues/21816[#21816])

==== API

* Fixed: API version was not updated to API 15 for addition of node updates
    (https://issues.rudder.io/issues/21793[#21793])

==== Web - Config management

* Fixed: on a fresh 7.1 install, the number of group displayed for "Global configuration of all nodes" is invalid
    (https://issues.rudder.io/issues/21730[#21730])
* Fixed: No link to directives in a rule if the rule is not applied to some nodes
    (https://issues.rudder.io/issues/21371[#21371])
* Fixed: Archive import does regenerate policies
    (https://issues.rudder.io/issues/21707[#21707])

==== Miscellaneous

* Fixed: Switch to jsonb for campaign event state
    (https://issues.rudder.io/issues/21783[#21783])

==== Web - Technique editor

* Fixed: Cannot save a technique after removing a block
    (https://issues.rudder.io/issues/21768[#21768])
* Fixed: Report if condition and Environement_variable_present by default cause missing report
    (https://issues.rudder.io/issues/21752[#21752])
* Fixed: Methods markdown documentation in the technique editor are not properly rendered
    (https://issues.rudder.io/issues/21368[#21368])

==== System integration

* Fixed: Wrong type for state column for campaign events in migration script
    (https://issues.rudder.io/issues/21767[#21767])

==== Architecture - Internal libs

* Fixed: Syntax errors in scala files
    (https://issues.rudder.io/issues/21748[#21748])

==== Packaging

* Fixed: Cleanup cron job for relay not removed on upgrade ot 7.2
    (https://issues.rudder.io/issues/21714[#21714])

==== Techniques

* Fixed: Incorrect parsing of epoch in installed rpm
    (https://issues.rudder.io/issues/21872[#21872])

==== Relay server or API

* Fixed: Bad parsing of systemUpdate N/A report by relayd
    (https://issues.rudder.io/issues/21846[#21846])

==== Plugins integration

* Fixed: Bad parsing of date for system update python script
    (https://issues.rudder.io/issues/21844[#21844])

==== System techniques

* Fixed: relayd error in logs in 7.2
    (https://issues.rudder.io/issues/21777[#21777])

==== Generic methods

* Fixed: Improve the windows documentation for condition_from_command
    (https://issues.rudder.io/issues/21737[#21737])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Janos Mattyasovszky

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== Rudder 7.2.0.rc1 (2022-09-06)

=== Changes

==== Packaging

* reinstate rudder-webapp package
    (https://issues.rudder.io/issues/21645[#21645])
* Update Rust to 1.62.1
    (https://issues.rudder.io/issues/21440[#21440])

==== Agent

* Add a disable syslog option to cfengine
    (https://issues.rudder.io/issues/20449[#20449])

==== Documentation

* User documentation of archive import/export
    (https://issues.rudder.io/issues/21675[#21675])
* Document SLES15SP2 requirement
    (https://issues.rudder.io/issues/21676[#21676])
* Improve user management docs
    (https://issues.rudder.io/issues/21582[#21582])
* Mention that AIX is compatible with everything noted as "Linux"
    (https://issues.rudder.io/issues/21604[#21604])

==== Web - Campaigns

* Add reason field to disabled field in campains and campain events
    (https://issues.rudder.io/issues/21698[#21698])

==== Plugins integration

* rudder package install can install plugins with short name but cannot remove them
    (https://issues.rudder.io/issues/21318[#21318])

==== Miscellaneous

* New parameter to campaign event request
    (https://issues.rudder.io/issues/21618[#21618])

==== Security

* Skip CVE-2022-31197 in checks
    (https://issues.rudder.io/issues/21602[#21602])

==== Architecture - Internal libs

* Make campaign test work
    (https://issues.rudder.io/issues/21539[#21539])
* Port policy writting test to rudder 7.1
    (https://issues.rudder.io/issues/21477[#21477])

==== Techniques

* Update techniques conditions for rhel9
    (https://issues.rudder.io/issues/21588[#21588])

==== System techniques

* Cleanup system-update files
    (https://issues.rudder.io/issues/21414[#21414])

==== Generic methods

* package method leads to report error when package with non-zero epoch is updated
    (https://issues.rudder.io/issues/19033[#19033])

=== Bug fixes

==== System integration

* Fixed: Postresql not found during migration to 7.2 => missing reports
    (https://issues.rudder.io/issues/21705[#21705])
* Fixed: Postresql not found during migration to 7.2 => missing reports
    (https://issues.rudder.io/issues/21705[#21705])
* Fixed: Correct BOM file in ps1.st used in test
    (https://issues.rudder.io/issues/21498[#21498])

==== Packaging

* Fixed: Missing dependency on libpq for relay on centos9
    (https://issues.rudder.io/issues/21674[#21674])
* Fixed: Uprading relay to 7.2 fails on ubuntu 22
    (https://issues.rudder.io/issues/21640[#21640])
* Fixed: Postinst message on AIX about hostname rudder not found
    (https://issues.rudder.io/issues/21626[#21626])
* Fixed: error when installing Rudder 7.2 on ubuntu22
    (https://issues.rudder.io/issues/21422[#21422])
* Fixed: rudder-relayd fails to uninstall properly
    (https://issues.rudder.io/issues/21581[#21581])
* Fixed: upgrading to 7.2 on centos 8 fails
    (https://issues.rudder.io/issues/21561[#21561])
* Fixed: Missing dependency on gpg breaks "rudder package" command fails on minimal installs
    (https://issues.rudder.io/issues/21061[#21061])
* Fixed: Error when installing Rudder server 7.2 on debian 11
    (https://issues.rudder.io/issues/21487[#21487])

==== Server components

* Fixed: Apache conf files are not overwritten after update
    (https://issues.rudder.io/issues/21583[#21583])

==== Agent

* Fixed: Inventory hostname differ between Windows and Linux
    (https://issues.rudder.io/issues/21356[#21356])
* Fixed: rudder package command fails on amazon linux
    (https://issues.rudder.io/issues/21654[#21654])
* Fixed: Properly display report_json reports in agent output
    (https://issues.rudder.io/issues/21622[#21622])
* Fixed: Deprecation warning with package methods on Ubuntu 22.04 LTS
    (https://issues.rudder.io/issues/21206[#21206])

==== Documentation

* Fixed: Installation documentation for Server has a section about sles12 but we only support sles15 as of 7.0
    (https://issues.rudder.io/issues/21420[#21420])
* Fixed: Add operation docs for webapp
    (https://issues.rudder.io/issues/21578[#21578])
* Fixed: Document 7.2 changes
    (https://issues.rudder.io/issues/21575[#21575])
* Fixed: Finish updating the docs for 7.2
    (https://issues.rudder.io/issues/21548[#21548])
* Fixed: Node create api doc for properties is incorrect
    (https://issues.rudder.io/issues/21553[#21553])
* Fixed: improve contributing doc to state how to generate inventories
    (https://issues.rudder.io/issues/21476[#21476])

==== Web - Config management

* Fixed: missing list of inpacted rules when creating a directive and applying it to a rule
    (https://issues.rudder.io/issues/21671[#21671])
* Fixed: Group permission of policies is not correctly set anymore in 7.2
    (https://issues.rudder.io/issues/21695[#21695])
* Fixed: generated policies are invalid when using a generic method that doesn't exist on linux
    (https://issues.rudder.io/issues/21686[#21686])
* Fixed: Impossible to log in when login in rudder-users.xml contains uppercase chars and login are case-insensitive
    (https://issues.rudder.io/issues/21532[#21532])
* Fixed: Extra spacing when adding several lines with File-Content generic method
    (https://issues.rudder.io/issues/21611[#21611])
* Fixed: Create a migration script for campaign
    (https://issues.rudder.io/issues/21571[#21571])
* Fixed: Concurrent delete of policy backup directory can lead to useless error
    (https://issues.rudder.io/issues/21482[#21482])
* Fixed: rudder don't understand the new reports generated for system update
    (https://issues.rudder.io/issues/21435[#21435])

==== API

* Fixed: API documentation on how to query node is invalid
    (https://issues.rudder.io/issues/21690[#21690])
* Fixed: Broken archive example in API doc
    (https://issues.rudder.io/issues/21664[#21664])
* Fixed: Missing import API documentation
    (https://issues.rudder.io/issues/21531[#21531])

==== Web - UI & UX

* Fixed: rollback button in even log can be clicked several time in a row and error are stacked in other screens
    (https://issues.rudder.io/issues/21429[#21429])
* Fixed: Node certificate expiration date does not follow the same format than the others dates in the UI
    (https://issues.rudder.io/issues/21367[#21367])
* Fixed: Graph caption is ugly for overall compliance in dashboard
    (https://issues.rudder.io/issues/21652[#21652])
* Fixed: Delete group category popup and directive creation popup are not closing
    (https://issues.rudder.io/issues/21666[#21666])
* Fixed: dashboards widget are not correctly aligned
    (https://issues.rudder.io/issues/21416[#21416])
* Fixed: Broken display of nodes list footer
    (https://issues.rudder.io/issues/21256[#21256])
* Fixed: Empty dashboard text does not look good
    (https://issues.rudder.io/issues/21634[#21634])
* Fixed: Wrong button color in techniques tree
    (https://issues.rudder.io/issues/21529[#21529])
* Fixed: Most buttons with the new Rudder color briefly show their old color when clicked
    (https://issues.rudder.io/issues/21258[#21258])
* Fixed: when validating change in directive, a popup appear, but the background is only half grayed out
    (https://issues.rudder.io/issues/18575[#18575])
* Fixed: when validating change in directive, a popup appear, but the background is only half grayed out
    (https://issues.rudder.io/issues/18575[#18575])
* Fixed: Orange color of hovered links
    (https://issues.rudder.io/issues/21528[#21528])
* Fixed: once we setup the Rudder server, we have an option to go to the getting started... which doesn't work
    (https://issues.rudder.io/issues/21488[#21488])
* Fixed: Filter in URL doest work on tab list of nodes
    (https://issues.rudder.io/issues/21558[#21558])
* Fixed: Make the css code for the group selection interface globally accessible.
    (https://issues.rudder.io/issues/21480[#21480])
* Fixed: Refresh Button in Rules menu under Directives Tab is not working
    (https://issues.rudder.io/issues/21264[#21264])

==== Web - Campaigns

* Fixed: Add a name parameter to campaign event
    (https://issues.rudder.io/issues/21662[#21662])
* Fixed: Initialization of campaign blocks rudder
    (https://issues.rudder.io/issues/21523[#21523])
* Fixed: Campaign scheduler seems to not look for existing campaign at boot
    (https://issues.rudder.io/issues/21418[#21418])

==== Web - Nodes & inventories

* Fixed: Rudder agent version is not detected for windows on pending nodes in 7.2
    (https://issues.rudder.io/issues/21667[#21667])
* Fixed: when we receive a lot of inventories at once, not all are processed
    (https://issues.rudder.io/issues/21653[#21653])
* Fixed: Cannot edit/detele an empty group category
    (https://issues.rudder.io/issues/21599[#21599])
* Fixed: 502 - Proxy Error when triggering Rudder agent
    (https://issues.rudder.io/issues/21170[#21170])
* Fixed: error when processing inventories in 7.2
    (https://issues.rudder.io/issues/21423[#21423])

==== Miscellaneous

* Fixed: Shared files cleanup does not work
    (https://issues.rudder.io/issues/21641[#21641])
* Fixed: Campaign events are not put in queue again after a new handler service was added, hence they are not treated after boot
    (https://issues.rudder.io/issues/21621[#21621])
* Fixed: Schedule campaign event when saving a new campaign
    (https://issues.rudder.io/issues/21470[#21470])
* Fixed: Improve handling of certificates not matching the key
    (https://issues.rudder.io/issues/21616[#21616])

==== Web - Compliance & node report

* Fixed: no compliance details on dashboard on 7.2
    (https://issues.rudder.io/issues/21432[#21432])

==== Web - Technique editor

* Fixed: When we change the status of a technique parameter from required to may be empty, it returns to required after saving
    (https://issues.rudder.io/issues/21560[#21560])
* Fixed: result condition are not correct in the technique editor when using properties or variables
    (https://issues.rudder.io/issues/21515[#21515])
* Fixed: Cannot delete technique in the technique editor if it contains a space in its name
    (https://issues.rudder.io/issues/21491[#21491])
* Fixed: Adapt webapp policy generation to 7.2 technique syntax
    (https://issues.rudder.io/issues/21502[#21502])
* Fixed: technique from technique editor not commited in git
    (https://issues.rudder.io/issues/21430[#21430])

==== Relay server or API

* Fixed: Potential segfault in chrono
    (https://issues.rudder.io/issues/21555[#21555])
* Fixed: Unsoundness in "owning_ref"
    (https://issues.rudder.io/issues/21538[#21538])

==== Architecture - Internal libs

* Fixed: Some tests not run because of bad class name
    (https://issues.rudder.io/issues/21534[#21534])
* Fixed: Path.of is not available in java8/rudder 7.1
    (https://issues.rudder.io/issues/21524[#21524])

==== CI

* Fixed: Fix qa-test for 7.2
    (https://issues.rudder.io/issues/21522[#21522])

==== Performance and scalability

* Fixed: Improve group node computation
    (https://issues.rudder.io/issues/20758[#20758])
* Fixed: API to fetch nodes + software times out on large instance
    (https://issues.rudder.io/issues/21241[#21241])

==== Security

* Fixed: Update bouncycastle for 7.2
    (https://issues.rudder.io/issues/21492[#21492])
* Fixed: URL with "%3B" (ie ';') leads to a stacktrace
    (https://issues.rudder.io/issues/21463[#21463])
* Fixed: JSESSIONID cookie should have a SameSite policy
    (https://issues.rudder.io/issues/21445[#21445])
* Fixed: Add HSTS config (commented for now)
    (https://issues.rudder.io/issues/21438[#21438])

==== Techniques

* Fixed: extra & at the end of systemUpdate technique
    (https://issues.rudder.io/issues/21703[#21703])
* Fixed: Fix the reporting and logging of the snmp technique on windows
    (https://issues.rudder.io/issues/21684[#21684])
* Fixed: Migrate the snmp windows technique to the 7.2 syntax
    (https://issues.rudder.io/issues/21673[#21673])
* Fixed: Migrate the motdConfiguration windows technique to the 7.2 syntax
    (https://issues.rudder.io/issues/21657[#21657])
* Fixed:  Migrate the fileTemplate windows technique to the 7.2 syntax
    (https://issues.rudder.io/issues/21655[#21655])
* Fixed: Migrate the copyFileFromSharedFolder windows technique to the 7.2 syntax
    (https://issues.rudder.io/issues/21651[#21651])
* Fixed: Port userManagement dsc technique to the new format
    (https://issues.rudder.io/issues/21609[#21609])
* Fixed: cron configuration restarts cron every 5 minutes on ubuntu22
    (https://issues.rudder.io/issues/21600[#21600])
* Fixed: error in system update technique on ubuntu 22.04
    (https://issues.rudder.io/issues/21434[#21434])
* Fixed: system-update technique output bogus "python" which breaks reporting
    (https://issues.rudder.io/issues/21436[#21436])

==== System techniques

* Fixed: Make system update campaign technique system
    (https://issues.rudder.io/issues/21701[#21701])
* Fixed: Permissions are not preserved in shared-files on the relays
    (https://issues.rudder.io/issues/21617[#21617])
* Fixed: Wrong name use for campaign in report (should not canonify)
    (https://issues.rudder.io/issues/21619[#21619])
* Fixed: Broken reload command in apache logrotate configuration
    (https://issues.rudder.io/issues/21612[#21612])

==== Generic methods

* Fixed: Broken jinja2 templating on ubuntu 22.04
    (https://issues.rudder.io/issues/21606[#21606])
* Fixed: rudder agent run man git-stash
    (https://issues.rudder.io/issues/21525[#21525])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.


== Rudder 7.2.0.beta1 (2022-07-18)

=== Changes


==== Packaging

* Add rhel9 support to packages
    (https://issues.rudder.io/issues/21357[#21357])
* Update C dependencies
    (https://issues.rudder.io/issues/21141[#21141])
* Make Java 11 the minimal required version
    (https://issues.rudder.io/issues/21109[#21109])
* Create a new rudder-server package
    (https://issues.rudder.io/issues/21084[#21084])
* Update to Rust 1.61.0 and update dependencies
    (https://issues.rudder.io/issues/21139[#21139])
* Minify the javascript produced by elm
    (https://issues.rudder.io/issues/21133[#21133])
* Cleanup methods (ncf) repository
    (https://issues.rudder.io/issues/21266[#21266])

==== Performance and scalability

* Add an ldap index on nodeId to improve performance
    (https://issues.rudder.io/issues/21246[#21246])
* Add an ldap index on softwareId to improve software queries performance
    (https://issues.rudder.io/issues/21244[#21244])

==== Documentation

* Prepare doc for 7.2
    (https://issues.rudder.io/issues/21407[#21407])
* Add docs about F# dev environment
    (https://issues.rudder.io/issues/21259[#21259])

==== Web - Config management

* Add logic to handle campaign within Rudder
    (https://issues.rudder.io/issues/21383[#21383])

==== API

* Add an API endpoint to export rules, directives, techniques, groups and their dependencies in an archive
    (https://issues.rudder.io/issues/21247[#21247])
* Moving create node plugin into Rudder
    (https://issues.rudder.io/issues/21117[#21117])

==== Plugins integration

* Allow "rudder package" command install multiple plugins at once
    (https://issues.rudder.io/issues/21316[#21316])

==== Web - UI & UX

*  Rename "classic" and "DSC" agents to "Linux" et "Windows"
    (https://issues.rudder.io/issues/21238[#21238])
* Update the css template for the integration of the system update campaigns plugin
    (https://issues.rudder.io/issues/21348[#21348])
* Provide a page to list the different hooks of a Rudder server
    (https://issues.rudder.io/issues/21083[#21083])
* Allow plugins to have multiple menu entries
    (https://issues.rudder.io/issues/21319[#21319])
* Upgrade Bootstrap to 3.4.1
    (https://issues.rudder.io/issues/21221[#21221])
* Harmonise the color scheme used in Rudder
    (https://issues.rudder.io/issues/21099[#21099])
* Update Javascript dependencies 
    (https://issues.rudder.io/issues/21149[#21149])
* Update the dashboard design with the new graphic charter
    (https://issues.rudder.io/issues/21072[#21072])

==== System integration

* Allow overriding rudder-web.properties parameters with files in rudder-web.properties.d
    (https://issues.rudder.io/issues/21293[#21293])

==== Web - Nodes & inventories

* Change default behavior from moving node inventories to archive branch to erasing them
    (https://issues.rudder.io/issues/21330[#21330])
* root inventory is missing and need to be resent after install
    (https://issues.rudder.io/issues/19920[#19920])

==== Relay server or API

* Allow passing options to postgresql connection URL
    (https://issues.rudder.io/issues/21201[#21201])
* Cleanup relayd tests
    (https://issues.rudder.io/issues/21155[#21155])
* Move shared-files purge from crond to a task in relayd
    (https://issues.rudder.io/issues/21047[#21047])

==== Architecture - Dependencies

* Update scala dependencies
    (https://issues.rudder.io/issues/21102[#21102])

==== Web - Compliance & node report

* Use a unique id to identify reports
    (https://issues.rudder.io/issues/20747[#20747])

==== System techniques

* Add a technique for campaign-based system-update
    (https://issues.rudder.io/issues/21297[#21297])

=== Bug fixes

==== Security

* Fixed: Update embedded openssl to 1.1.1q
    (https://issues.rudder.io/issues/21360[#21360])
* Fixed: Update spring and logback version because of new CVE
    (https://issues.rudder.io/issues/21022[#21022])

==== Packaging

* Fixed: Java does not default to 11 even if it is installed
    (https://issues.rudder.io/issues/21301[#21301])
* Fixed: Disable dwz as it fails on some rudder-relayd binaries on Debian 10
    (https://issues.rudder.io/issues/21275[#21275])
* Fixed: Upgrade to Jetty 10
    (https://issues.rudder.io/issues/21137[#21137])

==== Documentation

* Fixed: Prepare 7.1 doc
    (https://issues.rudder.io/issues/20794[#20794])
* Fixed: Some reponses are missing in technique api doc
    (https://issues.rudder.io/issues/21304[#21304])
* Fixed: Fix typos in techniques API doc
    (https://issues.rudder.io/issues/21290[#21290])

==== Web - Config management

* Fixed: Links to rules inside a directive webpage redirect to the general rule webpage
    (https://issues.rudder.io/issues/21372[#21372])
* Fixed: Reports on method using iterator are wrong in the cli output
    (https://issues.rudder.io/issues/20603[#20603])

==== CI

* Fixed: Ignore rudder-lang repos in script checks
    (https://issues.rudder.io/issues/21364[#21364])

==== Miscellaneous

* Fixed: Remove unused variable newCall in JRTechniqueElem
    (https://issues.rudder.io/issues/21355[#21355])

==== Web - Compliance & node report

* Fixed: In HTTPS mode, we may have errors in logs about duplicate messages that are totally legit
    (https://issues.rudder.io/issues/21352[#21352])

==== Server components

* Fixed: Missing comment in configuration.properties.sample
    (https://issues.rudder.io/issues/21350[#21350])

==== Web - UI & UX

* Fixed: Impossible to put a Rule in a subcategory
    (https://issues.rudder.io/issues/21175[#21175])
* Fixed: Cancel button not showed within disable rule menu 
    (https://issues.rudder.io/issues/21171[#21171])

==== Architecture - Refactoring

* Fixed: Tests fail due to policy mode definition in MockServices
    (https://issues.rudder.io/issues/21336[#21336])

==== Web - Technique editor

* Fixed: we can add carriage return in the condition in technique editor
    (https://issues.rudder.io/issues/21126[#21126])

==== Web - Nodes & inventories

* Fixed: Using '{' in node property lead to error
    (https://issues.rudder.io/issues/21322[#21322])

==== rudderc

* Fixed: Improve rudderc testing system
    (https://issues.rudder.io/issues/21048[#21048])

=== Release notes

This is a bug fix release in the 7.2 series and therefore all installations of 7.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

= Change logs for Rudder 7.2
