= Changelogs for Rudder plugin api-authorizations 7.2.2-2.1.\* versions

== solaris-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== aix-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== zabbix-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== vault-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== scale-out-relay-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== openscap-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== glpi-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== centreon-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== api-authorizations-7.2.2-2.1 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.2-2.1 series and therefore all installations of 7.2.2-2.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

