= Change logs for Rudder 3.1

Rudder 3.1 has reached End of Life the 22th December 2017. This version
is codenamed ``Frigate''.

This page provides a summary of changes for each version. Previous beta
and rc versions are listed below for convenience.

*Main new features in Rudder 3.1:*

* Global improvement on security 
** Inventory system is now signed
** We provide a basic SELinux policy
** Choose between UDP and TCP to send reports
* A more complete API
** Rule categories
** Group categories
** Query on Nodes
** Compliance
** Global API informations
* Allow to sort rules and directive execution on nodes (since 3.1.1)
* Display compliance of each Node in Nodes list
* Add filter boxes on Directive/Group tree in Rule details
* Add a summary of applied Directives in Rule details
* Add a useful 404 page
* Little improvements on Node details display
* New commands to rudder agent cli
* Replace all init scripts by a new generic one
* SLES 12 Support
* Agent based on CFEngine 3.6.5

*Installing, upgrading and testing*

Documentation:

* Install:
https://www.rudder-project.org/doc-3.1/_install_rudder_server.html
* Upgrade: https://www.rudder-project.org/doc-3.1/_upgrade.html

The Download Links are available here:
https://www.rudder-project.org/site/get-rudder/downloads/.

We also recommend using the
https://github.com/Normation/rudder-vagrant[Rudder Vagrant] config if
you want a quick and easy way to get an installation for testing.

*IMPORTANT:* The inventories are now sent over HTTPS by default, you
need to open the HTTPS (443) port between your nodes and your Rudder
servers!

*Operating systems supported*

This version provides packages for these operating systems:

* Rudder server: *Debian 7, Debian 8, RHEL/CentOS 6, RHEL/CentOS 7, SLES
11, Ubuntu 12.04, Ubuntu 14.04*
* Rudder agent: all of the above plus *Debian 5, Debian 6, RHEL/CentOS
3, RHEL/CentOS 5, Fedora 18, SLES 10, SLES 12 Ubuntu 10.04, Ubuntu
12.10*
* Rudder agent (non-free): *Windows Server 2008-2012*, *AIX 5-6-7*

== Rudder 3.1.25 (2017-12-15)

=== Changes

==== Packaging

* Upgrade openssl to 1.0.2m
(https://www.rudder-project.org/redmine/issues/11734[#11734])
* Change rudder-techniques ncf depdency to a correct version
(https://www.rudder-project.org/redmine/issues/11692[#11692])

=== Bug fixes

==== Initial promises & sys tech

* Fixed: Unexpected report for Send inventories to CMDB after #11257
(https://www.rudder-project.org/redmine/issues/11648[#11648])

==== System integration

* Fixed: rudder-init fails to report memory errors from jetty start
(https://www.rudder-project.org/redmine/issues/8165[#8165])
* Fixed: When we have a /var full, Rudder LDAP or Postgres can be
corrupted (https://www.rudder-project.org/redmine/issues/11125[#11125])
* Fixed: Fusioninventory task Deploy is missing a dependency to
File-Copy-Recursive
(https://www.rudder-project.org/redmine/issues/11701[#11701])
* Fixed: Duration of logrotate for /var/log/rudder/ is too long making
/var/log too big
(https://www.rudder-project.org/redmine/issues/10912[#10912])

==== Web - Maintenance

* Fixed: Null pointer exception when restoring group archive.
(https://www.rudder-project.org/redmine/issues/11805[#11805])

==== Documentation

* Fixed: Archive REST section outdated for download ZIP archive
(https://www.rudder-project.org/redmine/issues/11650[#11650])
* Fixed: fetch git branch before checkout when building rudder-doc
(https://www.rudder-project.org/redmine/issues/11697[#11697])
* Fixed: Use new ncf branches in rudder-doc
(https://www.rudder-project.org/redmine/issues/11693[#11693])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky

This is a bug fix release in the 3.1 series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.24 (2017-10-30)

=== Changes

==== Initial promises & sys tech

* Do not send inventory if a forwarder/uploader daemon exists
(https://www.rudder-project.org/redmine/issues/11257[#11257])

==== Techniques

* UserManagement technique does not allow to change the gid of an
existing user
(https://www.rudder-project.org/redmine/issues/11596[#11596])

=== Bug fixes

==== Web - Nodes & inventories

* Fixed: Groups are not reloaded after restoring from archive
(https://www.rudder-project.org/redmine/issues/11244[#11244])

==== Web - Config management

* Fixed: Parameter name requires at least 3 characters
(https://www.rudder-project.org/redmine/issues/11588[#11588])
* Fixed: There is no way to remove a Directive based on a Technique that
no longer exists
(https://www.rudder-project.org/redmine/issues/5203[#5203])

==== Documentation

* Fixed: Manually restoring permissions for NCF after archive import is
broken (https://www.rudder-project.org/redmine/issues/11414[#11414])
* Fixed: Dead link in doc
(https://www.rudder-project.org/redmine/issues/11579[#11579])
* Fixed: Missing documentation on Directive ordering
(https://www.rudder-project.org/redmine/issues/11289[#11289])

==== Agent

* Fixed: Xen domU detection issues with pvops kernels.
(https://www.rudder-project.org/redmine/issues/10787[#10787])
* Fixed: Inventory uploaded multiple times after reinit
(https://www.rudder-project.org/redmine/issues/11580[#11580])

==== Packaging

* Fixed: rudder-techniques requires a recent ncf version
(https://www.rudder-project.org/redmine/issues/11411[#11411])
* Fixed: PORT in /etc/default/rudder-slapd is ignored
(https://www.rudder-project.org/redmine/issues/11331[#11331])

==== API

* Fixed: Archives API list returns date with wrong format
(https://www.rudder-project.org/redmine/issues/11408[#11408])

==== Techniques

* Fixed: generic_variable_definition inserts spaces in multi lined
values (https://www.rudder-project.org/redmine/issues/11613[#11613])
* Fixed: group management technique doesn’t ensure optional user is in
group (https://www.rudder-project.org/redmine/issues/8739[#8739])
* Fixed: Incomplete description of the behaviour of technique
copyGitFile, that may result in broken permissions of whole folder
(https://www.rudder-project.org/redmine/issues/11422[#11422])
* Fixed: File content (key/value format) technique allows white space
before separator but not after it
(https://www.rudder-project.org/redmine/issues/11087[#11087])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky
* Florian Heigl
* Hamlyn Mootoo

This is a bug fix release in the 3.1 series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.23 (2017-09-07)

=== Changes

==== Agent

* Upgrade openssl to 1.0.2l
(https://www.rudder-project.org/redmine/issues/11279[#11279])

=== Bug fixes

==== Packaging

* Fixed: Remove rudder.8.gz from rudder-packages preventing build of man
pages (https://www.rudder-project.org/redmine/issues/11258[#11258])
* Fixed: Configuration of database password fails after install
(https://www.rudder-project.org/redmine/issues/11253[#11253])

==== Agent

* Fixed: When in changes only mode, with no heartbeat, `rudder agent
run' outputs `error: Rudder agent was interrupted during execution by a
fatal error.'
(https://www.rudder-project.org/redmine/issues/9807[#9807])

==== Miscellaneous

* Fixed: ``compliance'' user role is broken
(https://www.rudder-project.org/redmine/issues/11185[#11185])

==== Web - Compliance & node report

* Fixed: ``no report'' explanation is not correct in node details
(https://www.rudder-project.org/redmine/issues/11270[#11270])

==== Techniques

* Fixed: sudo management isn’t update-safe
(https://www.rudder-project.org/redmine/issues/9347[#9347])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Florian Heigl

This is a bug fix release in the 3.1 ESR series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.22 (2017-08-14)

=== Changes

==== Documentation

* Compliance logfile parsing regex
(https://www.rudder-project.org/redmine/issues/11107[#11107])
* Warn on risk of updating file format
(https://www.rudder-project.org/redmine/issues/11155[#11155])

=== Bug fixes

==== Web - UI & UX

* Fixed: Wrong XML identation in event log
(https://www.rudder-project.org/redmine/issues/10951[#10951])

==== Documentation

* Fixed: Put warnings (about dependencies for example) before
install/upgrade instructions
(https://www.rudder-project.org/redmine/issues/11162[#11162])

==== Web - Config management

* Fixed: Typo in generation error
(https://www.rudder-project.org/redmine/issues/11232[#11232])
* Fixed: Typo in unauthorized acces message
(https://www.rudder-project.org/redmine/issues/11182[#11182])
* Fixed: Cannot add a directive with a " in its name in Rule
(https://www.rudder-project.org/redmine/issues/10754[#10754])
* Fixed: Rudder can’t start anymore because does not find
configuration-repository techniques category in git
(https://www.rudder-project.org/redmine/issues/11055[#11055])

==== Initial promises & sys tech

* Fixed: Check permissions on /var/rudder files, particularly
modified-files
(https://www.rudder-project.org/redmine/issues/11110[#11110])

==== Security

* Fixed: JSESSION cookie should be ``secure''
(https://www.rudder-project.org/redmine/issues/11159[#11159])

==== Techniques

* Fixed: Aix group technique
(https://www.rudder-project.org/redmine/issues/11235[#11235])
* Fixed: Directive: Services Management doesn’t support AIX
(https://www.rudder-project.org/redmine/issues/8752[#8752])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky
* David Svejda

This is a bug fix release in the 3.1 ESR series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.21 (2017-06-21)

=== Changes

==== Packaging

* Log check-rudder-agent cron job output
(https://www.rudder-project.org/redmine/issues/8438[#8438])

==== Architecture - Internal libs

* Match non exaustive on workflow step: log on error
(https://www.rudder-project.org/redmine/issues/10938[#10938])

==== Documentation

* Update FAQ links in the doc
(https://www.rudder-project.org/redmine/issues/10760[#10760])

==== Agent

* Create a rudder agent command to format old logs
(https://www.rudder-project.org/redmine/issues/10708[#10708])

=== Bug fixes

==== Web - UI & UX

* Fixed: Broken display on directive screen on 3.1.20
(https://www.rudder-project.org/redmine/issues/10923[#10923])
* Fixed: Node search input field are tiny and a nightmare to use
(https://www.rudder-project.org/redmine/issues/10659[#10659])
* Fixed: Directives tree overflows the page
(https://www.rudder-project.org/redmine/issues/10735[#10735])

==== Agent

* Fixed: check-rudder-agent doesn’t purge the lmdb file when run via
cron (https://www.rudder-project.org/redmine/issues/10771[#10771])

==== Techniques

* Fixed: The rpmPackageInstallation technique tries to install package-*
instead of package when no version is specified
(https://www.rudder-project.org/redmine/issues/9283[#9283])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Florian Heigl
* Janos Mattyasovszky

This is a bug fix release in the 3.1 ESR series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.20 (2017-05-22)

=== Changes

==== Documentation

* Add an example of using a condition in the Technique creation tutorial
(https://www.rudder-project.org/redmine/issues/10694[#10694])
* Add Technique editor documentation
(https://www.rudder-project.org/redmine/issues/10685[#10685])
* Extend node property documentation for templates
(https://www.rudder-project.org/redmine/issues/10614[#10614])

=== Bug fixes

==== Web - UI & UX

* Fixed: Fix details in Technique editor doc
(https://www.rudder-project.org/redmine/issues/10699[#10699])
* Fixed: On some resolution, top bar is on two line and we can’t see the
whole directive tree
(https://www.rudder-project.org/redmine/issues/10552[#10552])
* Fixed: Mono Font text in directive form are not correctly displayed in
Chrome (https://www.rudder-project.org/redmine/issues/9780[#9780])
* Fixed: Selects in Archives page are not wide enough
(https://www.rudder-project.org/redmine/issues/10615[#10615])

==== Web - Config management

* Fixed: Tooltips don’t disapear on safari
(https://www.rudder-project.org/redmine/issues/6145[#6145])
* Fixed: Clearly report on template attribute with a `.' in them
(https://www.rudder-project.org/redmine/issues/10742[#10742])

==== Performance and scalability

* Fixed: Unecessary call to inventory code to check its version during
policy validation
(https://www.rudder-project.org/redmine/issues/10641[#10641])

==== Documentation

* Fixed: Document correctly memory usage
(https://www.rudder-project.org/redmine/issues/10744[#10744])
* Fixed: Missing information in Technique editor doc
(https://www.rudder-project.org/redmine/issues/10710[#10710])
* Fixed: Supported Windows platforms are Windows Server 2008 and after
(https://www.rudder-project.org/redmine/issues/10656[#10656])
* Fixed: Doc: ``Regenerate now'' button has been renamed ``Update
policies'' (https://www.rudder-project.org/redmine/issues/10633[#10633])
* Fixed: Backup restoration requires disabling the agent
(https://www.rudder-project.org/redmine/issues/10639[#10639])
* Fixed: Rudder installation docs are misleading as to running
rudder-init
(https://www.rudder-project.org/redmine/issues/10624[#10624])
* Fixed: Node property documentation has error
(https://www.rudder-project.org/redmine/issues/10613[#10613])

==== Miscellaneous

* Fixed: If cf-serverd is not up, hook 50-reload-policy-file-server is
in error and breaks policy generation
(https://www.rudder-project.org/redmine/issues/10493[#10493])
* Fixed: escaping $\{SSH_ORIGINAL_COMMAND} in GUI -
sshKeyDistribution/3.0
(https://www.rudder-project.org/redmine/issues/10715[#10715])

==== Web - Compliance & node report

* Fixed: In reports list, if the directive contains < >, then the part
in < > doesn’t appear in the reports
(https://www.rudder-project.org/redmine/issues/5718[#5718])
* Fixed: When no reports has been received from a node for new policy,
message contains unexpanded variable
(https://www.rudder-project.org/redmine/issues/10636[#10636])

==== Packaging

* Fixed: Installation fails due to broken nss/nss-softokn detection on
CentOS6 (https://www.rudder-project.org/redmine/issues/10734[#10734])
* Fixed: Man pages provided in rudder-agent package are out-of-date
(https://www.rudder-project.org/redmine/issues/10432[#10432])
* Fixed: rudder-init doesn’t use fully qualified path for executing
cf-agent (https://www.rudder-project.org/redmine/issues/10607[#10607])

==== System integration

* Fixed: Script rudder-init cannot reinit ldap database
(https://www.rudder-project.org/redmine/issues/10608[#10608])
* Fixed: java.lang.InternalError when calling the internal API on Redhat
because of invalid version of nss
(https://www.rudder-project.org/redmine/issues/9905[#9905])
* Fixed: Infinite ``rudder is loading'' page if rudder-init didn’t run
(https://www.rudder-project.org/redmine/issues/10567[#10567])
* Fixed: If an error happen during boostrap, the webapp starts but is in
a zombie state and the error page is not displayed
(https://www.rudder-project.org/redmine/issues/1974[#1974])
* Fixed: rudder server debug fails on SLES 11
(https://www.rudder-project.org/redmine/issues/7892[#7892])

==== Agent

* Fixed: If component value starts with # , report is not outputed by
rudder agent output
(https://www.rudder-project.org/redmine/issues/10601[#10601])

==== Web - Maintenance

* Fixed: Adding an authorized network when ``common-root'' directive is
missing seems to work, but actually fails
(https://www.rudder-project.org/redmine/issues/8017[#8017])
* Fixed: There is small display glitch in change request display
(https://www.rudder-project.org/redmine/issues/6257[#6257])

==== Server components

* Fixed: Inventory endpoint accepts inventory even if ldap or postgresql
connectivity failed
(https://www.rudder-project.org/redmine/issues/10485[#10485])

==== Techniques

* Fixed: Unclear field description in MOTD technique
(https://www.rudder-project.org/redmine/issues/10655[#10655])
* Fixed: Technique files contains UTF-8 chars (especially spaces)
(https://www.rudder-project.org/redmine/issues/7622[#7622])
* Fixed: ``Variable (String)'' Directive in the Directive library does
not use textarea
(https://www.rudder-project.org/redmine/issues/10585[#10585])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Jean Cardona
* Christophe Crier
* Florian Heigl
* Janos Mattyasovszky
* Ferenc Ulrich
* Kiran V
* Rémi Verchère

This is a bug fix release in the 3.1 `esr' series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.19 (2017-04-19)

=== Changes

==== Packaging

* Upgrade OpenSSL to 1.0.2k
(https://www.rudder-project.org/redmine/issues/10246[#10246])

=== Bug fixes

==== API

* Fixed: Wrong error message on directive API
(https://www.rudder-project.org/redmine/issues/10554[#10554])
* Fixed: Log an error when Rest API fails
(https://www.rudder-project.org/redmine/issues/10295[#10295])
* Fixed: Fix behavior of directive API and make api more consistent
(https://www.rudder-project.org/redmine/issues/10225[#10225])

==== Web - UI & UX

* Fixed: Different icons for magnifier in pending nodes page
(https://www.rudder-project.org/redmine/issues/10524[#10524])
* Fixed: A magnifier icon appears in the filter fild after displaying
directives that would be applied in pending nodes page
(https://www.rudder-project.org/redmine/issues/10525[#10525])
* Fixed: ``Reset to default'' action in ``Change Audit Logs'' doesn’t
reset to install version
(https://www.rudder-project.org/redmine/issues/9391[#9391])
* Fixed: A running Policy generation is not displayed on the Status
dropdown (https://www.rudder-project.org/redmine/issues/10451[#10451])
* Fixed: GUI breaks completely with IE 11
(https://www.rudder-project.org/redmine/issues/10452[#10452])
* Fixed: padding-down instead of padding-bottom in rudder.css
(https://www.rudder-project.org/redmine/issues/10465[#10465])
* Fixed: Display issue on ``Accept new Nodes'' page
(https://www.rudder-project.org/redmine/issues/9165[#9165])
* Fixed: Dropdown lists in directive forms are not wide enough and hide
the contents of options
(https://www.rudder-project.org/redmine/issues/10361[#10361])
* Fixed: Cannot use slashes in quick search
(https://www.rudder-project.org/redmine/issues/10407[#10407])
* Fixed: Checkboxes in Administration menu are not locked for users with
missing permissions
(https://www.rudder-project.org/redmine/issues/9328[#9328])
* Fixed: Compliance display when hoverving over the compliance bar is
too precise (https://www.rudder-project.org/redmine/issues/9323[#9323])
* Fixed: When trying to create a new API account that has the same name
as an existing acocunt, nothing happen
(https://www.rudder-project.org/redmine/issues/10250[#10250])

==== Web - Nodes & inventories

* Fixed: Regex search on node properties is broken: returns all nodes
with a property when no using invalid value
(https://www.rudder-project.org/redmine/issues/10570[#10570])
* Fixed: Rudder fails to accept inventories with user account different
only in their case
(https://www.rudder-project.org/redmine/issues/10545[#10545])

==== Web - Maintenance

* Fixed: There is no error logged when an error occurs when updating
information of Node in Node cache
(https://www.rudder-project.org/redmine/issues/10290[#10290])

==== Web - Config management

* Fixed: Missing ``user techniques'' in the technique editor when
exporting / importing archive
(https://www.rudder-project.org/redmine/issues/9448[#9448])
* Fixed: Policy validation fails
(https://www.rudder-project.org/redmine/issues/10446[#10446])

==== Agent

* Fixed: Policy loading is slow due to innefficient variable
manipulation
(https://www.rudder-project.org/redmine/issues/10576[#10576])
* Fixed: On upgrade from 3.1 to 4.1, policy could not be generated any
more (https://www.rudder-project.org/redmine/issues/10559[#10559])

==== Packaging

* Fixed: Don’t display warning about configuring policy server on root
server (https://www.rudder-project.org/redmine/issues/8976[#8976])

==== Initial promises & sys tech

* Fixed: Transient update error on ncf/local
(https://www.rudder-project.org/redmine/issues/10028[#10028])
* Fixed: Propagate promises error when no nodes behind a relay
(https://www.rudder-project.org/redmine/issues/7671[#7671])

==== System integration

* Fixed: Error in migration (ldap backup not found because ending by
.gz) (https://www.rudder-project.org/redmine/issues/10521[#10521])
* Fixed: Log contains debug info ``**** got string:
\{''start``:''2017-03-09 00:00:00``,''end``,''2017-03-11 00:00:00``}''
(https://www.rudder-project.org/redmine/issues/10553[#10553])
* Fixed: Log for failed login attempt is not (correctly) reported
(https://www.rudder-project.org/redmine/issues/10259[#10259])
* Fixed: After running rudder-init, no connectivity to postgresql
(https://www.rudder-project.org/redmine/issues/10486[#10486])
* Fixed: Clean-up and add build information in META-INF
(https://www.rudder-project.org/redmine/issues/10253[#10253])

==== Performance and scalability

* Fixed: Enable gzip compression on text resources
(https://www.rudder-project.org/redmine/issues/10365[#10365])

==== Techniques

* Fixed: ``Download files from the shared folder'' behaving badly?
(https://www.rudder-project.org/redmine/issues/10312[#10312])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Ilan Costa
* Florian Heigl
* Janos Mattyasovszky
* Hamlyn Mootoo
* Dmitry Svyatogorov

This is a bug fix release in the 3.1 `esr' series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.18 (2017-02-20)

=== Changes

==== Web - Nodes & inventories

* API endpoint to get information about queue status of uploaded
inventories (https://www.rudder-project.org/redmine/issues/9976[#9976])

==== Web - UI & UX

* Add an option to not display rule status/recent changes in directives
screen (https://www.rudder-project.org/redmine/issues/10157[#10157])
* Node breakdown - show actual numbers
(https://www.rudder-project.org/redmine/issues/7422[#7422])

==== Documentation

* Add link to the new FAQ in the manual
(https://www.rudder-project.org/redmine/issues/10181[#10181])
* Add qa-test for line breaks
(https://www.rudder-project.org/redmine/issues/9893[#9893])

=== Bug fixes

==== Web - UI & UX

* Fixed: Included ``time ended'' in Status dropdown
(https://www.rudder-project.org/redmine/issues/10133[#10133])
* Fixed: Shared files input does not appear on in directives form
(https://www.rudder-project.org/redmine/issues/9804[#9804])
* Fixed: Change request link is too small
(https://www.rudder-project.org/redmine/issues/6142[#6142])

==== Web - Config management

* Fixed: Deadlock with simultaneous generation and new reports
(https://www.rudder-project.org/redmine/issues/10168[#10168])
* Fixed: Incomplete logging in expected reports computation
(https://www.rudder-project.org/redmine/issues/10143[#10143])

==== Performance and scalability

* Fixed: Compliance on all reports is always computed, even when not
necessary (https://www.rudder-project.org/redmine/issues/9869[#9869])

==== Architecture - Internal libs

* Fixed: Test create directories in /tmp that are not cleaned nor unique
(https://www.rudder-project.org/redmine/issues/10029[#10029])

==== Documentation

* Fixed: Broken link in CFEngine doc
(https://www.rudder-project.org/redmine/issues/10151[#10151])
* Fixed: expected reports, component keys
(https://www.rudder-project.org/redmine/issues/8633[#8633])
* Fixed: Missing ``default ='' word in node properties expansion
documention (https://www.rudder-project.org/redmine/issues/9800[#9800])

==== Miscellaneous

* Fixed: Typo in root of policy libray tree name
(https://www.rudder-project.org/redmine/issues/9884[#9884])

==== Web - Compliance & node report

* Fixed: If node is sending unexpected report, we get an invalid text
(https://www.rudder-project.org/redmine/issues/9930[#9930])
* Fixed: When we receive reports from node with old reports, caches are
not used for compliance computation
(https://www.rudder-project.org/redmine/issues/9835[#9835])

==== Packaging

* Fixed: rudder-techniques depends on perl(XML::TreePP)
(https://www.rudder-project.org/redmine/issues/9845[#9845])
* Fixed: Missing selinux-policy-devel in rudder-server-relay
dependencies
(https://www.rudder-project.org/redmine/issues/10090[#10090])
* Fixed: Do not build SELinux policy on old OSes
(https://www.rudder-project.org/redmine/issues/10089[#10089])
* Fixed: SELinux target directory does not exist
(https://www.rudder-project.org/redmine/issues/10056[#10056])
* Fixed: Add SELinux config to relay package
(https://www.rudder-project.org/redmine/issues/9913[#9913])
* Fixed: ncf-api-virtualenv build depends on selinux
(https://www.rudder-project.org/redmine/issues/9851[#9851])

==== Initial promises & sys tech

* Fixed: Error parsing inventory
(https://www.rudder-project.org/redmine/issues/9841[#9841])

==== Web - Nodes & inventories

* Fixed: Inventories with fields containing only spaces/tabs/… may fail
to be parsed due to invalid sanitization of entry
(https://www.rudder-project.org/redmine/issues/10220[#10220])
* Fixed: FileNotFoundException when looking for deleted history file
(https://www.rudder-project.org/redmine/issues/10115[#10115])

==== Agent

* Fixed: Logs from 4.1 agent are not sent to the server
(https://www.rudder-project.org/redmine/issues/9776[#9776])

==== Architecture - Dependencies

* Fixed: warning: Class javax.annotation.Nonnull not found - continuing
with a stub.
(https://www.rudder-project.org/redmine/issues/10146[#10146])
* Fixed: Use correct repository definition in pom.xml
(https://www.rudder-project.org/redmine/issues/10120[#10120])

==== Web - Maintenance

* Fixed: If the Rudder Web Interface is interrupted during the second
step of reports archiving, then it won’t never succeed in archiving
again (https://www.rudder-project.org/redmine/issues/10171[#10171])

==== Server components

* Fixed: Rudder’s LDAP server configuration does not allow to query the
monitor DB (https://www.rudder-project.org/redmine/issues/9818[#9818])

==== Techniques

* Fixed: The service management technique does not disable boot services
(https://www.rudder-project.org/redmine/issues/9872[#9872])
* Fixed: copyGitFile reports an error when destination is a symbolic
link (https://www.rudder-project.org/redmine/issues/9500[#9500])
* Fixed: Job is not run for Technique JobScheduler in Rudder
(https://www.rudder-project.org/redmine/issues/9822[#9822])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky

This is a bug fix release in the 3.1 `esr' series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.17 (2016-12-12)

=== Changes

==== Web - Nodes & inventories

* On agent, check inventory before sending it to Rudder server
(https://issues.rudder.io/issues/8127[#8127])

==== System integration

* Rudder error pages should not change transport
(https://issues.rudder.io/issues/9637[#9637])

==== Architecture - Internal libs

* Add basic infrastructure to test REST API
(https://issues.rudder.io/issues/9201[#9201])

==== Documentation

* Move techniques reference doc to the manual
(https://issues.rudder.io/issues/9586[#9586])
* Make rudder-doc gitignore more complete
(https://issues.rudder.io/issues/9570[#9570])
* Build final doc for releases in rc status
(https://issues.rudder.io/issues/9564[#9564])
* Use $releasever in upgrade section for RHEL
(https://issues.rudder.io/issues/9439[#9439])
* Update documentation to have version independant repo
(https://issues.rudder.io/issues/9422[#9422])
* Use release info to get ncf version to use in doc
(https://issues.rudder.io/issues/9393[#9393])

=== Bug fixes

==== Web - Config management

* Fixed: Node properties update doesn’t invalidate node configuration
hash (https://issues.rudder.io/issues/9402[#9402])

==== Web - UI & UX

* Fixed: Degraded style of text areas in directive forms
(https://issues.rudder.io/issues/9703[#9703])
* Fixed: Missing top of eventLog datetime picker on small screen
(https://issues.rudder.io/issues/9267[#9267])
* Fixed: If an event logs contains long lines it is not displayed
properly (https://issues.rudder.io/issues/5963[#5963])

==== Web - Nodes & inventories

* Fixed: No server inventory in web interface if /etc/hosts is not
correctly configured
(https://issues.rudder.io/issues/9744[#9744])

Agent

* Fixed: Improve error messages in ``rudder agent update''
(https://issues.rudder.io/issues/9726[#9726])
* Fixed: Fusioninventory is not tracked by check-rudder-health
(https://issues.rudder.io/issues/9622[#9622])
* Fixed: Typo in rudder agent run failure message
(https://issues.rudder.io/issues/9618[#9618])
* Fixed: Virtual machine detected as physical
(https://issues.rudder.io/issues/9496[#9496])
* Fixed: Some QEMU systems are wrongly detected as physical system
(https://issues.rudder.io/issues/9335[#9335])

Techniques

* Fixed: Allow to only install a specific version in apt and rpm
techniques. (https://issues.rudder.io/issues/9761[#9761])
* Fixed: Wrong warn log report in ssh techniques on sles >= 11
(https://issues.rudder.io/issues/9317[#9317])

=== API

* Fixed: API allows to create duplicate UUIDs at group creation
(https://issues.rudder.io/issues/9742[#9742])
* Fixed: Creating an empty group with no search criteria messes up GUI
(https://issues.rudder.io/issues/9741[#9741])
* Fixed: Setting nodeProperty over API does fail on bad key order
(https://issues.rudder.io/issues/9326[#9326])
* Fixed: Rudder API timeouts when passing wrong parameters
(https://issues.rudder.io/issues/7134[#7134])

=== Documentation

* Fixed: Bad plugin installation info on doc
(https://issues.rudder.io/issues/9721[#9721])
* Fixed: Bad file indicated in Java memory config chapter
(https://issues.rudder.io/issues/9628[#9628])
* Fixed: Manual is broken because of some new syntax in ncf doc
(https://issues.rudder.io/issues/9621[#9621])
* Fixed: Wiki documentation broken URL
(https://issues.rudder.io/issues/9608[#9608])
* Fixed: Mention port 80 in manual
(https://issues.rudder.io/issues/9567[#9567])
* Fixed: API Documentation: Delete node shows example of accept node
(https://issues.rudder.io/issues/9368[#9368])
* Fixed: Cleanup node properties documentation
(https://issues.rudder.io/issues/9253[#9253])
* Fixed: Rudder API doc is invalid for getting the list of pending nodes
(https://issues.rudder.io/issues/7973[#7973])

==== Packaging

* Fixed: On Ubuntu 16.04, openjdk 9 is installed by default, and not
recognized as a compatible version
(https://issues.rudder.io/issues/9613[#9613])
* Fixed: fusion agent fail to build on ubuntu 16
(https://issues.rudder.io/issues/9556[#9556])

==== Initial promises & sys tech

* Fixed: Script that validate inventory is not correctly called on
Windows (https://issues.rudder.io/issues/9764[#9764])
* Fixed: Error on inventory of policy servers: Error when parsing an
entry, that agent will be ignored. <- could not parse policy server id
(tag POLICY_SERVER_UUID) from specific inventory
(https://issues.rudder.io/issues/9327[#9327])
* Fixed: Explain in the reports of system techniques that we do not need
to manage the cron service on AIX
(https://issues.rudder.io/issues/9235[#9235])
* Fixed: Multiple errors ``The postgresql process was not running and
has been restarted''
(https://issues.rudder.io/issues/9182[#9182])

==== System integration

* Fixed: rudder-upgrade should use the database name from the webapp
configuration (https://issues.rudder.io/issues/9749[#9749])
* Fixed: Add a warning comment for password change in
rudder-web.properties
(https://issues.rudder.io/issues/9685[#9685])
* Fixed: Compressing the ldap backup hangs if would require to overwrite
it (https://issues.rudder.io/issues/9630[#9630])
* Fixed: Firefox stalls after TLS handshake on self signed certificate
(https://issues.rudder.io/issues/9566[#9566])
* Fixed: The API alive check may hang forever
(https://issues.rudder.io/issues/9561[#9561])
* Fixed: Missing logger information for quicksearch in logback.xml
(https://issues.rudder.io/issues/9406[#9406])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre Anriot
* Alexander Brunhirl
* Florian Heigl
* Janos Mattyasovszky
* Dmitry Svyatogorov

This is a bug fix release in the 3.1 `esr' series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.16 (2016-10-12)

=== Changes

==== Agent

* Send inventory signature before inventory
(https://issues.rudder.io/issues/9196[#9196])

=== Bug fixes

==== Web - UI & UX

* Fixed: Technique ``Enforce a file content'' breaks carriage returns
(https://issues.rudder.io/issues/9243[#9243])

==== Web - Nodes & inventories

* Fixed: Virtual machine detection does not recognize HyperV machines
(https://issues.rudder.io/issues/9262[#9262])

==== Web - Config management

* Fixed: Rule & directive order is not taken into account for nodeConfig
cache invalidation
(https://issues.rudder.io/issues/9320[#9320])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre Anriot

This is a bug fix release in the 3.1 `esr' series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.15 (2016-10-05)

=== Changes

==== Web - Config management

* Allow the use of node properties info in Directive parameters
(https://issues.rudder.io/issues/9057[#9057])
* Allow to look for past reports and event logs using a date selector,
so they are not limited last 1000 entries
(https://issues.rudder.io/issues/8886[#8886])

==== Web - UI & UX

* Make the quicksearch bar in menu able to also search rule, group,
directive, etc
(https://issues.rudder.io/issues/8563[#8563])
* Allow to use JS script in text/textarea
(https://issues.rudder.io/issues/9090[#9090])

==== API

* Add item names in compliance API
(https://issues.rudder.io/issues/9083[#9083])

==== Documentation

* Document separate database configuration in Rudder
(https://issues.rudder.io/issues/8908[#8908])

==== Architecture - Internal libs

* Add a qa-test to techniques repo
(https://issues.rudder.io/issues/8975[#8975])

==== Agent

* Use rudder commands directly inside other rudder commands
(https://issues.rudder.io/issues/8925[#8925])

=== Bug fixes

==== Web - Compliance & node report

* Fixed: When there is missing and received reports, we don’t see the
received one (https://issues.rudder.io/issues/9141[#9141])

==== Web - Config management

* Fixed: JS scripting engine is broken with IBM JDK 7 (and 8)
(https://issues.rudder.io/issues/8936[#8936])
* Fixed: `ip' fields in techniques/directives does not support ipv6
(https://issues.rudder.io/issues/8628[#8628])
* Fixed: If a technique ncf has a $, generation fails
(https://issues.rudder.io/issues/9184[#9184])

==== API

* Fixed: Rudder Directive Rest API does not parse json parameters
correctly (https://issues.rudder.io/issues/8957[#8957])

==== Web - UI & UX

* Fixed: Webapp: sorting by recent changes doesn’t work
(https://issues.rudder.io/issues/8867[#8867])
* Fixed: Typo in error message when ldap is empty
(https://issues.rudder.io/issues/8899[#8899])
* Fixed: Script evaluation is not limited to password fields anymore
(https://issues.rudder.io/issues/9190[#9190])
* Fixed: Typo in doc for new scripts evaluation and node properties
(https://issues.rudder.io/issues/9180[#9180])

==== Builder - UI/UX

* Fixed: Uneeded scrollbar when using ncf builder in an iframe
(https://issues.rudder.io/issues/9164[#9164])
* Fixed: Cannot save new generic method with some contraints
(https://issues.rudder.io/issues/8981[#8981])
* Fixed: We need to save twice after cloning a technique
(https://issues.rudder.io/issues/8896[#8896])

==== Web - Nodes & inventories

* Fixed: AIX inventory tries to report on cpuid.arc
(https://issues.rudder.io/issues/9145[#9145])
* Fixed: Inventory ``toInt'' error when parsing report with
VIRTUALMEMORY = 2297795780
(https://issues.rudder.io/issues/9077[#9077])
* Fixed: Some KVM virtual machines considered as physical nodes
(https://issues.rudder.io/issues/9049[#9049])
* Fixed: Inventory is not parsed if OPERATINGSYSTEM/NAME is missing
(https://issues.rudder.io/issues/8993[#8993])
* Fixed: Virtual machines considered as physical nodes
(https://issues.rudder.io/issues/8953[#8953])

==== Techniques

* Fixed: Techniques use $ for paths of ressources files (ex:
properties), which prevent their validation by the Web Interface during
policies generation
(https://issues.rudder.io/issues/9113[#9113])
* Fixed: Typo in `Package version match' in ``Package management for
RHEL / CentOS / SuSE / RPM systems'' technique
(https://issues.rudder.io/issues/8954[#8954])
* Fixed: crontab frequency does not support reserved string @reboot
(https://issues.rudder.io/issues/8825[#8825])
* Fixed: Zypper repo management ``Delete all other repositories than
those managed by Rudder'' is broken
(https://issues.rudder.io/issues/8824[#8824])

==== ncf - Policies

* Fixed: Do not save backups for expected reports files
(https://issues.rudder.io/issues/9139[#9139])
* Fixed: Package check installed does not produce reports
(https://issues.rudder.io/issues/9132[#9132])
* Fixed: Check/Verify package generic methods are actually installing
packages (https://issues.rudder.io/issues/8972[#8972])
* Fixed: missing rudder_expected_reports.csv.res when starting the agent
for the first time after an update
(https://issues.rudder.io/issues/8871[#8871])
* Fixed: file_ensure_lines_present_in_ini_section.cf test fails with
CFEngine 3.9 (https://issues.rudder.io/issues/8638[#8638])
* Fixed: Missing reporting in ``Service ensure running with service
path'' when the service is not running
(https://issues.rudder.io/issues/8270[#8270])
* The test framework should be able to use list-compatible-input to only
test compatible generic methods
(https://issues.rudder.io/issues/8657[#8657])

==== Agent

* Fixed: rudder agent version doesn’t work on old rpm versions
(https://issues.rudder.io/issues/9142[#9142])
* Fixed: rudder agent fails on aix
(https://issues.rudder.io/issues/9138[#9138])
* Fixed: Kept classes are not defined when editing fields in a file in
warn only mode
(https://issues.rudder.io/issues/9082[#9082])
* Fixed: Forbid agent reinit on the root server
(https://issues.rudder.io/issues/9076[#9076])
* Fixed: Agent sometimes fail to apply package actions because of global
lock (https://issues.rudder.io/issues/8926[#8926])
* Fixed: The agent fails writing fields in lines longer than 4k
(https://issues.rudder.io/issues/8794[#8794])
* Fixed: JSON output in cf-promises is limited to 2048 chars for strings
(https://issues.rudder.io/issues/8260[#8260])
* Fixed: cfengine stops processing a promise on symlinks
(https://issues.rudder.io/issues/7060[#7060])
* Fixed: Rudder agent ignores virtual network interfaces
(https://issues.rudder.io/issues/6124[#6124])
* Fixed: The PowerShell list-compatible-inputs version should be
executed with Bypass ExecutionPolicy
(https://issues.rudder.io/issues/9193[#9193])
* Fixed: Rudder bash completion does not handle correctly commands
containing dashes
(https://issues.rudder.io/issues/9174[#9174])

==== Documentation

* Fixed: Wrong display of Rudder versions in the doc
(https://issues.rudder.io/issues/8937[#8937])
* Fixed: Code blocks in the doc overflow the page width
(https://issues.rudder.io/issues/8917[#8917])
* Fixed: Improve documentation on directive API on update and creation
(https://issues.rudder.io/issues/8913[#8913])
* Fixed: The search bar sometimes hides the page title in webhelp doc
(https://issues.rudder.io/issues/8897[#8897])
* Fixed: Normalize prompt/command display in the doc
(https://issues.rudder.io/issues/8849[#8849])
* Fixed: Give more precise requirements for JVM to manage AIX sha256/512
passwords (https://issues.rudder.io/issues/8804[#8804])

==== ncf - Documentation

* Small improvement for ncf website
(https://issues.rudder.io/issues/9068[#9068])
* Remove TODO file from ncf repo
(https://issues.rudder.io/issues/9014[#9014])
* Drop CFEngine 3.5 support
(https://issues.rudder.io/issues/8946[#8946])

==== Packaging

* Fixed: Embedded openssl command doesn’t work on aix
(https://issues.rudder.io/issues/9143[#9143])
* Fixed: Builds are failing with ``stack overflow error'' in typer
(https://issues.rudder.io/issues/9123[#9123])
* Fixed: rudder-server-relay Makefile misses WGET def
(https://issues.rudder.io/issues/9023[#9023])
* Fixed: [rudder-packages] invalid spec files for SLES12 SP1
(https://issues.rudder.io/issues/9001[#9001])
* Fixed: Update 3.0->3.1 on SLES commits and rebuilds vanilla system
techniques (https://issues.rudder.io/issues/8980[#8980])
* Fixed: Fail while building perl modules on Ubuntu 16.04 for Rudder
3.1/3.2 (https://issues.rudder.io/issues/8979[#8979])
* Fixed: The file rsyslog.d/rudder.conf might not be embedded in
rudder-reports (db on a separate server)
(https://issues.rudder.io/issues/8876[#8876])
* Fixed: We need a run with the initial promises before being able to
update the promises
(https://issues.rudder.io/issues/8850[#8850])

==== Initial promises & sys tech

* Fixed: ncf compatibility cache not updated after Rudder upgrade
(https://issues.rudder.io/issues/9156[#9156])
* Fixed: Typo in common technique reports
(https://issues.rudder.io/issues/9035[#9035])
* Fixed: missing rudder_expected_reports.csv.res when starting the agent
for the first time after an update - technique changes
(https://issues.rudder.io/issues/8909[#8909])
* Fixed: outputs folder is cleaned at each run
(https://issues.rudder.io/issues/8750[#8750])
* Fixed: Don’t report error when the copy of the license file for
CFEngine Enterprise fails
(https://issues.rudder.io/issues/8521[#8521])

==== Builder - API

* Fixed: rudderification breaks when a parameter contains `&'
(https://issues.rudder.io/issues/9096[#9096])
* Fixed: When the conditions contain spaces, they are kept and the
generated file is invalid
(https://issues.rudder.io/issues/8763[#8763])
* Fixed: The Category list is cut on small screen
(https://issues.rudder.io/issues/8762[#8762])

==== System integration

* Fixed: JS Script, Node Properties expansion and Quicksearch should be
disabled on migration
(https://issues.rudder.io/issues/9157[#9157])
* Fixed: The ``rudder'' init script tries to stop slapd before jetty
(https://issues.rudder.io/issues/9091[#9091])

==== Architecture - Internal libs

* Fixed: Control.bestEffort duplicate the last failure
(https://issues.rudder.io/issues/9118[#9118])
* Fixed: wget doesn’t always work
(https://issues.rudder.io/issues/8991[#8991])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre Anriot
* Florian Heigl
* Jérémy Hocdé
* Janos Mattyasovszky

This is a bug fix release in the 3.1 `esr' series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.14 (2016-10-05)

Rudder 3.1.14 was not published because we found
https://issues.rudder.io/projects/rudder/issues?utf8=%E2%9C%93&set_filter=1&f%5B%5D=status_id&op%5Bstatus_id%5D=%3D&v%5Bstatus_id%5D%5B%5D=11&f%5B%5D=fixed_version_id&op%5Bfixed_version_id%5D=%3D&v%5Bfixed_version_id%5D%5B%5D=311&f%5B%5D=&c%5B%5D=project&c%5B%5D=tracker&c%5B%5D=parent&c%5B%5D=status&c%5B%5D=priority&c%5B%5D=subject&c%5B%5D=author&c%5B%5D=assigned_to&c%5B%5D=category&c%5B%5D=fixed_version&group_by=[several
bugs] after build.

== Rudder 3.1.13 (2016-08-30)

=== Changes

==== System integration

* Update JGit to version > 4.0 to support pre-commit hook on
configuration repository
(https://issues.rudder.io/issues/8889[#8889])
* Allow to customize reports database name and user to ease a separate
database (https://issues.rudder.io/issues/8873[#8873])

==== Web - Technique editor

* Add `Windows Server 2012 R2' as OS condition
(https://issues.rudder.io/issues/8071[#8071])

==== Documentation

* Generate a custom index page for the manual
(https://issues.rudder.io/issues/8488[#8488])

==== Techniques

* Download technique-files from Rudder website
(https://issues.rudder.io/issues/8853[#8853])

==== Packaging

* Use dmidecode instead of pmtools on OpenSuSE 11
(https://issues.rudder.io/issues/8821[#8821])

=== Bug fixes

==== Web - Config management

* Fixed: Unable to save/edit a directive via rudder web ui when
technique use an optionnal SELECT field
(https://issues.rudder.io/issues/8874[#8874])
* Fixed: Typo in cf-clerk logs
(https://issues.rudder.io/issues/8823[#8823])
* Fixed: When there is an error in a directive form, the target rule is
unchecked (https://issues.rudder.io/issues/8696[#8696])
* Fixed: Node properties are not being synchronized on the node itself
until promises are created/modified
(https://issues.rudder.io/issues/8840[#8840])
* Fixed: Inconsistent hashing algorithms used in passwords generated in
the script engine
(https://issues.rudder.io/issues/8801[#8801])

==== Web - UI & UX

* Fixed: The new password field hides the Save Directive button
(https://issues.rudder.io/issues/8800[#8800])
* Fixed: Typos in the node’s compliance explanation text
(https://issues.rudder.io/issues/8787[#8787])
* Fixed: Cannot see rule details when you have read_only role
(https://issues.rudder.io/issues/8878[#8878])
* Fixed: When no editing rights are given to Groups, you drag an drop
them between categories
(https://issues.rudder.io/issues/8863[#8863])
* Fixed: ``Update techniques now'' button on the techniques screen is
too small (https://issues.rudder.io/issues/8616[#8616])

==== Web - Technique editor

* Fixed: Cannot access Technique Editor with role technique_all
(https://issues.rudder.io/issues/8492[#8492])
* Fixed: New method calls are considered valid, although they are empty
which leads to error when validated via API
(https://issues.rudder.io/issues/8829[#8829])
* Fixed: Warn when the string length reaches the maximum value supported
by the agent (https://issues.rudder.io/issues/8261[#8261])
* Fixed: ncf still loads mp.autofocus module that was deleted!
(https://issues.rudder.io/issues/8793[#8793])

==== API

* Fixed: Two different API methods return the same action name
``listDirectives''
(https://issues.rudder.io/issues/8688[#8688])

==== Agent

* Fixed: rudder agent run tells to give -i for errors, even if you did
give -i (https://issues.rudder.io/issues/8861[#8861])
* Fixed: Failing CFEngine unit test on recent OSes
(https://issues.rudder.io/issues/8860[#8860])

==== Documentation

* Fixed: Document migration from manually installed relays
(https://issues.rudder.io/issues/6226[#6226])
* Fixed: Safe setup of the Rudder repo in the manual
(https://issues.rudder.io/issues/8864[#8864])

==== Techniques

* Fixed: Broken syntax in fstabConfiguration 4.0
(https://issues.rudder.io/issues/8870[#8870])
* Fixed: Misleading comment in rudder cron
(https://issues.rudder.io/issues/8816[#8816])
* Fixed: ncf template methods do not empty file before editing it
(https://issues.rudder.io/issues/8843[#8843])

==== Initial promises & sys tech

* Fixed: Typo in system techniques reports
(https://issues.rudder.io/issues/8841[#8841])

==== Packaging

* Fixed: Do not depend on pam-devel on AIX
(https://issues.rudder.io/issues/8893[#8893])
* Fixed: Missing BuildRequires for rudder-agent : pam-devel
(https://issues.rudder.io/issues/8822[#8822])

==== Architecture - Internal libs

* Fixed: Some Javascript engine fails when accessing system values
(https://issues.rudder.io/issues/8857[#8857])
* Fixed: JS engine tests broken due to security exeception when using
jdk 1.8 (https://issues.rudder.io/issues/8856[#8856])

==== Architecture - Refactoring

* Fixed: Compilation warning about unsound assumption could lead to hard
to understand errors
(https://issues.rudder.io/issues/8797[#8797])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre Anriot
* Florian Heigl
* Kevin Kok
* Avit Sidis

This is a bug fix release in the 3.1 `esr' series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.12 (2016-07-29)

=== Changes

==== Web - UI & UX

* Improve experience of password field in Directives
(https://issues.rudder.io/issues/8753[#8753])
* Technical logs are sorted by date, oldest date first
(https://issues.rudder.io/issues/8728[#8728])

==== Web - Config management

* Allows generation-time javascript eval in directive parameters
(https://issues.rudder.io/issues/8629[#8629], see
(http://www.rudder-project.org/doc-3.1/_javascript_evaluation_in_directives.html[documentation]
for details)
* Allow Node properties to be used in directives and ncf techniques
(https://issues.rudder.io/issues/6733[#6733], see
(http://www.rudder-project.org/doc-3.1/_node_properties.html[documentation]
for details)

==== Agent

* Create a `rudder agent run –force' option
(https://issues.rudder.io/issues/8729[#8729])
* Support CFEngine enterprise agents on `rudder server debug'
(https://issues.rudder.io/issues/8555[#8555])
* `rudder agent inventory' should not run the techniques
(https://issues.rudder.io/issues/8757[#8757])

==== Architecture - Dependencies

* Update Rudder 3.1 to Scala 2.11 / liftweb 2.6
(https://issues.rudder.io/issues/8655[#8655])
* Utility to get all objects from a sealed trait
(https://issues.rudder.io/issues/8614[#8614])

==== Initial promises & sys tech

* Disable inventories using a file
(https://issues.rudder.io/issues/8741[#8741])

==== Techniques

* Create a technique that manages key/values in a file
(https://issues.rudder.io/issues/8631[#8631])

==== API

* Add an technique API endpoint to display directives based on a
technique (https://issues.rudder.io/issues/8534[#8534])
* API: add an option to just run a ``pre-check'' on directive
modifications to change technique version
(https://issues.rudder.io/issues/7961[#7961])

==== Documentation

* Use release-info to generate the manual header at creation
(https://issues.rudder.io/issues/8450[#8450])
* Add documentation on new techniques and check directive API
(https://issues.rudder.io/issues/8639[#8639])

==== Packaging

* Update openssl to openssl-1.0.2h
(https://issues.rudder.io/issues/8329[#8329])

=== Bug fixes

==== Web - UI & UX

* Fixed: The API token creation popup is not centered
(https://issues.rudder.io/issues/8592[#8592])
* Fixed: Recent changes graph can overflow the page width
(https://issues.rudder.io/issues/8437[#8437])
* Fixed: Missing an information line in rule details to explain that the
graph is clickable
(https://issues.rudder.io/issues/8432[#8432])
* Fixed: When the compliance is very small the status bar twice as big
(https://issues.rudder.io/issues/7658[#7658])

==== Web - Nodes & inventories

* Fixed: Inventory messes up Last logged in user date when last user was
a reboot (https://issues.rudder.io/issues/8239[#8239])

==== Web - Config management

* Fixed: Correct error message when SHA512 algorithm is not available
(https://issues.rudder.io/issues/8770[#8770])
* Fixed: UserManagement need to have hashed password for both Linux and
AIX (https://issues.rudder.io/issues/8593[#8593])

==== Web - Compliance & node report

* Fixed: Refresh button on recent changes graph on Rule details does not
refresh data (https://issues.rudder.io/issues/8630[#8630])
* Fixed: When updating runs, hooks should really be async
(https://issues.rudder.io/issues/8424[#8424])
* Fixed: When a node send reports with an unknow configID, no expected
reports are showned
(https://issues.rudder.io/issues/8409[#8409])

==== Agent

* Fixed: `rudder agent run' should allow multiple -D
(https://issues.rudder.io/issues/8758[#8758])
* Fixed: Having a report-separator in the report message causes the
report not show up in ``rudder agent run'' output
(https://issues.rudder.io/issues/8635[#8635])

==== Server components

* Fixed: Upgrade from 2.11 to 3.1 on sles does not preserve the
rudder-jetty java parameters
(https://issues.rudder.io/issues/8172[#8172])

==== Initial promises & sys tech

* Fixed: Use the list-compatible-input equivalent on Windows system
(https://issues.rudder.io/issues/8553[#8553])
* Fixed: Update promises on Windows complains about setting ownership to
``root'' (https://issues.rudder.io/issues/8532[#8532])
* Fixed: fusionAgent.cf for ARM
(https://issues.rudder.io/issues/7203[#7203])

==== Techniques

* Fixed: Add a technique check to make sure &endif& are followed by an
empty line (https://issues.rudder.io/issues/8646[#8646])
* Fixed: Add a test for checkGenericFileContent 7.0
(https://issues.rudder.io/issues/8673[#8673])
* Fixed: technique-files cannot find with a pattern on the whole
technique name
(https://issues.rudder.io/issues/8736[#8736])
* Fixed: lines after &endif& in techniques
(https://issues.rudder.io/issues/8647[#8647])
* Fixed: technique-metadata-sample.xml has invalid content
(https://issues.rudder.io/issues/8615[#8615])
* Fixed: UserManagement 6.0 fails to add user if the user’s default
group already exists
(https://issues.rudder.io/issues/8599[#8599])
* Fixed: Reporting for usermanagement in case of Policy to apply to this
account ``check only'' is missing the Password component report
(https://issues.rudder.io/issues/8585[#8585])
* Fixed: userManagement technique doesn’t do anything on Windows on
version 5 and 6
(https://issues.rudder.io/issues/8566[#8566])
* Fixed: checkGenericFile missing report when given non absolute path
(https://issues.rudder.io/issues/8405[#8405])
* Fixed: Broken technique tests
(https://issues.rudder.io/issues/8786[#8786])
* Fixed: Check-techniques.sh checks for cfengine_community class in
comments (https://issues.rudder.io/issues/8751[#8751])
* Fixed: Fix metadata syntax of generic enforce file content test
(https://issues.rudder.io/issues/8738[#8738])
* Fixed: Technique userManagement, home directory is not taken into
account (https://issues.rudder.io/issues/8466[#8466])

==== API

* Fixed: Inconsistent directive API parameters at creation
(https://issues.rudder.io/issues/8687[#8687])
* Fixed: NoSuchElementException when querying change request API
(https://issues.rudder.io/issues/8686[#8686])
* Fixed: The select parameter in the nodes API is not correctly
documented (https://issues.rudder.io/issues/7131[#7131])

==== Documentation

* Fixed: Add a test for dead links on the doc
(https://issues.rudder.io/issues/8548[#8548])
* Fixed: Documentation makefile fails to update git repos (git pull
before changing branch)
(https://issues.rudder.io/issues/8788[#8788])
* Fixed: Display link errors in doc build
(https://issues.rudder.io/issues/8727[#8727])
* Fixed: SLES Documentation has bad package name
(https://issues.rudder.io/issues/8624[#8624])
* Fixed: Left menu is sometimes broken when there is an anchor in the
link (https://issues.rudder.io/issues/8569[#8569])
* Fixed: Fix doc after ncf lib changes (same as #8522)
(https://issues.rudder.io/issues/8524[#8524])
* Fixed: Broken formatting of man command sections in the doc
(https://issues.rudder.io/issues/8732[#8732])
* Fixed: Broken link in the doc
(https://issues.rudder.io/issues/8726[#8726])
* Fixed: Correct example to use a query when listing accepted nodes via
API (https://issues.rudder.io/issues/8594[#8594])

==== Packaging

* Fixed: Do not package technique tests
(https://issues.rudder.io/issues/8679[#8679])
* Fixed: There is a non standard test in os detection
(https://issues.rudder.io/issues/8760[#8760])
* Fixed: Packages should remove their temporary files
(https://issues.rudder.io/issues/8744[#8744])
* Fixed: Update openssl to 1.0.1t on 2.11 branch
(https://issues.rudder.io/issues/8658[#8658])
* Fixed: rudder-apache-common.conf is not updated on upgrade with RPM
packages (https://issues.rudder.io/issues/8641[#8641])
* Fixed: Do not only build-depend on virtual packages
(https://issues.rudder.io/issues/8565[#8565])
* Fixed: The event count during the last day in rudder-metrics-reporting
can be very slow
(https://issues.rudder.io/issues/8583[#8583])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky
* Florian Heigl
* Francois Bayart

This is a bug fix release in the 3.1 `esr' series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.11 (2016-06-08)

=== Changes

==== Documentation

* Add tests for doc syntax
(https://issues.rudder.io/issues/8443[#8443])

=== Bug fixes

==== Web - Compliance & node report

* Fixed: Parallel traversal of new promises directories causes some
nodes promises to not be updated
(https://issues.rudder.io/issues/8427[#8427])
* Fixed: Not possible to switch details for time period on rule recent
changes on Chromium
(https://issues.rudder.io/issues/8408[#8408])
* Fixed: When a node send reports with a wrong config_id it is never
marked as unresponsive
(https://issues.rudder.io/issues/8118[#8118])

==== Web - Nodes & inventories

* Fixed: Change in group may be overwritten by dynamic group update
(https://issues.rudder.io/issues/8453[#8453])

==== Web - Config management

* Fixed: Many WARN messages after upgrade about JSON deserialisation
error (https://issues.rudder.io/issues/8288[#8288])

==== Techniques

* Fixed: Invalidation of previous package state and of package status
cache does not work on rpmPackageInstallation 5.0 5.1 6.0 6.1 7.0
(https://issues.rudder.io/issues/8421[#8421])
* Fixed: rpmPackageInstallation 7.0 uses the wrong version number for
it’s data file
(https://issues.rudder.io/issues/8419[#8419])
* Fixed: Missing reports in file and zypper techniques due to a syntax
error in reporting
(https://issues.rudder.io/issues/8403[#8403])

==== Initial promises & sys tech

* Fixed: On Centos6.6, rsyslog is always restarted
(https://issues.rudder.io/issues/8451[#8451])
* Fixed: failsafe sometimes produce rudder reports
(https://issues.rudder.io/issues/8422[#8422])
* Fixed: Reference to &TRACKINGKEY& in initial promises
(https://issues.rudder.io/issues/8415[#8415])
* Fixed: Remove unused variable in cf-serverd
(https://issues.rudder.io/issues/8392[#8392])
* Fixed: The component ``Check Technique library reloading file'' is
sometime a log and sometime a result
(https://issues.rudder.io/issues/8380[#8380])
* Fixed: Launching twice in a row a disabled agent make the agent runs
(https://issues.rudder.io/issues/7100[#7100])
* Fixed: The uuid in the promises and the uuid in
/opt/rudder/etc/uuid.hive may be out of sync, and chaos and sadness
follows (https://issues.rudder.io/issues/7091[#7091])
* Fixed: If using Rudder Server 3.1 and a node with agent 3.2, protocol
used is TLS (https://issues.rudder.io/issues/8458[#8458])

==== Documentation

* Fixed: Unclear message in the upgrade doc
(https://issues.rudder.io/issues/8440[#8440])
* Fixed: The SLES upgrade section has a broken title syntax
(https://issues.rudder.io/issues/8439[#8439])

==== Packaging

* Fixed: stty does not handle no-tty input
(https://issues.rudder.io/issues/8426[#8426])
* Fixed: When updating a Rudder install, changes_executionTimeStamp_idx
index is not created
(https://issues.rudder.io/issues/8423[#8423])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky
* Daniel Stan

This is a bug fix release in the 3.1 `esr' series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.10 (2016-06-01, Not announced)

That version was not announced due to several bugs:
https://issues.rudder.io/issues/8423[#8423],
https://issues.rudder.io/issues/8427[#8427],
https://issues.rudder.io/issues/8430[#8430]

=== Changes

==== Web - Nodes & inventories

* Make page node details/search node less confusing
(https://issues.rudder.io/issues/7642[#7642])

==== Web - UI & UX

* Augment default number of lines displayed in tables and add more
options (https://issues.rudder.io/issues/8107[#8107])

==== Initial promises & sys tech

* Add support to cfengine bootstrap in server
(https://issues.rudder.io/issues/7902[#7902])

==== Documentation

* Create an installation section in the documentation
(https://issues.rudder.io/issues/8233[#8233])
* Homogenize OS names in the doc
(https://issues.rudder.io/issues/8224[#8224])
* How to: Ensure a line is present in a file (and only one time!)
(https://issues.rudder.io/issues/8169[#8169])
* Integrate ncf generic methods reference into the doc
(https://issues.rudder.io/issues/7844[#7844])
* Add ``Troubleshooting'' section
(https://issues.rudder.io/issues/7711[#7711])
* Move man pages into the reference section
(https://issues.rudder.io/issues/8332[#8332])
* Move Relay doc to the install section
(https://issues.rudder.io/issues/7889[#7889])
* Document easier way to reload techniques after upgrade
(https://issues.rudder.io/issues/8291[#8291])

=== Bug fixes

==== Web - UI & UX

* Fixed: Typo in directive migration message ``an other''
(https://issues.rudder.io/issues/8289[#8289])
* Fixed: Broken links in the ``Support Desk'' box of the home page
(https://issues.rudder.io/issues/8110[#8110])
* Fixed: Some messages in the Settings page end with a comma
(https://issues.rudder.io/issues/8044[#8044])
* Fixed: Show seconds in Execution date at Technical Logs of Node
Details (https://issues.rudder.io/issues/7981[#7981])
* Fixed: Prevent red color usage in inventory graphs
(https://issues.rudder.io/issues/8262[#8262])
* Fixed: Change audit message is not checked in the ``Clone Directive''
popup (https://issues.rudder.io/issues/8213[#8213])
* Fixed: Priority field in Directive form does not show it has a tooltip
and has wrong description
(https://issues.rudder.io/issues/8201[#8201])
* Fixed: Fix display issues on IE11
(https://issues.rudder.io/issues/8136[#8136])
* Fixed: Add a left margin to the Rudder search box
(https://issues.rudder.io/issues/7825[#7825])

==== Web - Compliance & node report

* Fixed: ``All the last execution reports for this server are ok''
displayed when no report received
(https://issues.rudder.io/issues/8400[#8400])
* Fixed: Misleading message on node compliance detail when run’s
configID is unknown
(https://issues.rudder.io/issues/8399[#8399])
* Fixed: ``repaired'' are counted as ``required attention'' on node
compliance details
(https://issues.rudder.io/issues/8396[#8396])
* Fixed: Compliance is not correctly computed if we receive run agent
right after generation
(https://issues.rudder.io/issues/8051[#8051])
* Fixed: OOM in Rudder when there are too many repaired reports
(https://issues.rudder.io/issues/7735[#7735])

==== Web - Config management

* Fixed: Node configuration cache is invalidated too often
(https://issues.rudder.io/issues/8246[#8246])
* Fixed: Directive detail don’t show the OS compatibility version
(https://issues.rudder.io/issues/7042[#7042])

==== API

* Fixed: Better document Node Api: include detail always returns
``default'' (https://issues.rudder.io/issues/8192[#8192])
* Fixed: API call to get the list of node is REALLY slow with latest
version (https://issues.rudder.io/issues/7972[#7972])

==== Agent

* Fixed: rudder agent update doesn’t always update policy
(https://issues.rudder.io/issues/8346[#8346])
* Fixed: ``rudder agent enable -s'' doesn’t return an error code if it
can’t start the agent
(https://issues.rudder.io/issues/8317[#8317])
* Fixed: rudder server reload- don’t work due to missing exec perms
(https://issues.rudder.io/issues/8290[#8290])

==== Techniques

* Fixed: permissions technique tries to set a group even when we do not
ask for it (https://issues.rudder.io/issues/8198[#8198])
* Fixed: It is not possible to use quotes in generic variable definition
values (https://issues.rudder.io/issues/8188[#8188])
* Fixed: Clear package caches when repairing a package repository
(https://issues.rudder.io/issues/8121[#8121])
* Fixed: The start at boot does not work in the openssh technique on
systemd OSes (https://issues.rudder.io/issues/8108[#8108])
* Fixed: Double reporting for group creation
(https://issues.rudder.io/issues/8100[#8100])
* Fixed: Avoid waiting on lock when calling yum
(https://issues.rudder.io/issues/6487[#6487])
* Fixed: applications/aptPackageManagerSettings/3.1 missing from list of
maintained techniques
(https://issues.rudder.io/issues/8395[#8395])
* Fixed: Document usage of line replacement in Enforce a file content
technique (https://issues.rudder.io/issues/8162[#8162])

==== System integration

* Fixed: Rudder jetty init script broken on CentOS 7
(https://issues.rudder.io/issues/8369[#8369])
* Fixed: rudder-slapd may break on upgrade when restarting on openVZ
(https://issues.rudder.io/issues/8210[#8210])
* Fixed: check-rudder-agent complains about not existing
policy-server.dat backup file
(https://issues.rudder.io/issues/8202[#8202])
* Fixed: ACL Posix on Git repos
(https://issues.rudder.io/issues/8065[#8065])
* Fixed: Disable ldap logging on non existing indexes
(https://issues.rudder.io/issues/7667[#7667])
* Fixed: Messages can be dropped on the node, resulting in Unknown
reports on the Web Interface
(https://issues.rudder.io/issues/6421[#6421])
* Fixed: promises can become invalid if copies fail rendering the agent
unusable (https://issues.rudder.io/issues/5650[#5650])
* Fixed: rudder-jetty initialisation should not support Java 6
(https://issues.rudder.io/issues/7348[#7348])
* Fixed: rudder init script fails with ``/etc/init.d/rudder: line 109:
printf \033[1;32m—8<—\033[0;39m\n: command not found''
(https://issues.rudder.io/issues/8296[#8296])
* Fixed: rudder init script reports wrong status if run as non-root
(https://issues.rudder.io/issues/8295[#8295])

==== Server components

* Fixed: Apache config does not get cleaned up after removal of
rudder-webapp (https://issues.rudder.io/issues/8232[#8232])
* Fixed: rudder-apache gets added multiple times to apache config
(https://issues.rudder.io/issues/8231[#8231])

==== Packaging

* Fixed: Spurious message ``grep: /etc/sysconfig/apache2: No such file
or directory'' in RPM install for rudder-webapp
(https://issues.rudder.io/issues/8371[#8371])
* Fixed: ncf package asks about replacing dist config file during
upgrade (https://issues.rudder.io/issues/8286[#8286])
* Fixed: When we install rudder-agent after having removing it, the uuid
is not restored on RPM-based systems
(https://issues.rudder.io/issues/6468[#6468])
* Fixed: Makefile missing in rudder-server-relay package
(https://issues.rudder.io/issues/8370[#8370])
* Fixed: Several systemd warnings in install on RHEL/CentOS 7
(https://issues.rudder.io/issues/7530[#7530])

==== Initial promises & sys tech

* Fixed: Can’t stat file `/opt/rudder/bin/cf-hub' on `localhost' in
files.copy_from promise
(https://issues.rudder.io/issues/8397[#8397])
* Fixed: check-techniques script doesn’t properly exit non-zero on
errors (https://issues.rudder.io/issues/8386[#8386])
* Fixed: Error in cf-serverd for allowing remote access to cf-agent
binary (https://issues.rudder.io/issues/8374[#8374])
* Fixed: logrotate promise for CFEngine Enterprise agents
(https://issues.rudder.io/issues/8340[#8340])
* Fixed: Invalid path for rudder_ncf in Windows
(https://issues.rudder.io/issues/8338[#8338])
* Fixed: Duplicate lines in body classes success in update.cf in initial
promises (https://issues.rudder.io/issues/8309[#8309])
* Fixed: Use variables for path to cf-agent in system Techniques to work
on Windows (https://issues.rudder.io/issues/8307[#8307])
* Fixed: Disable Repeated message reduction or reports may be lost on
the relay (https://issues.rudder.io/issues/8264[#8264])
* Fixed: Error message about setgid on ncf.conf
(https://issues.rudder.io/issues/8181[#8181])
* Fixed: Missing reporting in ``check postgresql process'' on rudder-db
role (https://issues.rudder.io/issues/8178[#8178])
* Fixed: Crontab promise with the Windows agent
(https://issues.rudder.io/issues/8161[#8161])
* Fixed: Rudder agent connect at each runs to its policy server to get
its server uuid
(https://issues.rudder.io/issues/7638[#7638])
* Fixed: Extra carriage return in policy_server.dat inventory failure
(https://issues.rudder.io/issues/7328[#7328])
* Fixed: In case of error in logrotate check, there is no report
(https://issues.rudder.io/issues/8382[#8382])
* Fixed: Error on windows: agent tries to check if /usr/bin/env supports
the -0 option (https://issues.rudder.io/issues/8336[#8336])
* Fixed: Using Rudder server 3.x + rudder agent 2.11.x, a node doesn’t
properly detect its change of relay server
(https://issues.rudder.io/issues/8045[#8045])
* Fixed: cf-promises can hang for about 30 seconds looking up default
server name ``rudder''
(https://issues.rudder.io/issues/7621[#7621])

==== Architecture - Internal libs

* Fixed: Examples in ldap-inventory are not real life examples
(https://issues.rudder.io/issues/8236[#8236])

==== Documentation

* Fixed: Documentation wrongly states default report TTL is 30 days
(https://issues.rudder.io/issues/8297[#8297])
* Fixed: Documentation no longer clearly tells user to upgrade
Techniques (https://issues.rudder.io/issues/8294[#8294])
* Fixed: Invalid documentation on how to use rudder global parameters in
Technique editor
(https://issues.rudder.io/issues/8278[#8278])
* Fixed: Make clearer what the goal of Scala-ldap is in readme
(https://issues.rudder.io/issues/8275[#8275])
* Fixed: rudder doc can be misleading on the repo to use for Centos/RHEL
(https://issues.rudder.io/issues/7976[#7976])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre Anriot
* Jean Cardona
* Janos Mattyasovszky
* David Svejda

This is a bug fix release in the 3.1 `esr' series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.9 (2016-04-18)

=== Changes

==== Web - Nodes & inventories

* Exit sending inventory to rudder-webapp if the queue is full
(https://issues.rudder.io/issues/7291[#7291])

==== Agent

* Add -c to general options of rudder command
(https://issues.rudder.io/issues/8139[#8139])
* Add calls to local API in rudder server commands - backport to 3.1
(https://issues.rudder.io/issues/7952[#7952])

==== Documentation

* Explain the SLES 12 case in the zypper segfault section
(https://issues.rudder.io/issues/8097[#8097])

=== Bug fixes

==== Web - UI & UX

* Fixed: API account table broken when empty
(https://issues.rudder.io/issues/8144[#8144])
* Fixed: Double arrow in Pending Nodes list
(https://issues.rudder.io/issues/8078[#8078])

==== Web - Maintenance

* Fixed: web interface login: able to log in with valid ldap account but
no matching rudder-users.xml entry
(https://issues.rudder.io/issues/8085[#8085])

==== Techniques

* Fixed: Missing reporting in UserManagement 6.0 when creating a user
(https://issues.rudder.io/issues/8079[#8079])

==== Performance and scalability

* Fixed: Java OOM during Java’s log migration
(https://issues.rudder.io/issues/7524[#7524])

==== Windows agent

* Fixed: On Windows, a file c:\Program is created
(https://issues.rudder.io/issues/8149[#8149])
* Fixed: Environement variable fail to load on windows
(https://issues.rudder.io/issues/8146[#8146])

==== Packaging

* Fixed: Error in rudder-server-relay post install script on debian
(https://issues.rudder.io/issues/8117[#8117])

==== Server components

* Fixed: node-to-relay fails to reload policy when proxy is set
(https://issues.rudder.io/issues/8054[#8054])
* Fixed: Compress ldif backups
(https://issues.rudder.io/issues/6714[#6714])][#7900]])

==== Initial promises & sys tech

* Fixed: Do not backup modified promise files and encrypt ncf/local
transfer (https://issues.rudder.io/issues/8159[#8159])

==== Architecture - Internal libs

* Fixed: java.util.regex.PatternSyntaxException: Unexpected internal
error near index 1 on windows
(https://issues.rudder.io/issues/7935[#7935])

==== Architecture - Refactoring

* Remove trailing space in code file that make merge conflicts
(https://issues.rudder.io/issues/8126[#8126])
* Fixed: Typo in tests
(https://issues.rudder.io/issues/8116[#8116])
* Fixed: Bad logs for event log migration since #8085
(https://issues.rudder.io/issues/8124[#8124])

==== Documentation

* Fixed: API documentation for compliance needs JSON prettified
(https://issues.rudder.io/issues/7900[#7900])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Florian Heigl
* Janos Mattyasovszky

This is a bug fix release in the 3.1 `esr' series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.8 (2016-03-24)

=== Changes

==== Packaging

* Put a makefile inside each directory of rudder-packages
(https://issues.rudder.io/issues/7718[#7718])

==== Web - Nodes & inventories

* The Motherboard UUID doesn’t appear on the inventory on a Node
(https://issues.rudder.io/issues/3749[#3749])

==== Documentation

* Mark 3.1 as ESR in the doc header
(https://issues.rudder.io/issues/8059[#8059])
* Import doc from foswiki about parametrized variable in the doc
(https://issues.rudder.io/issues/7836[#7836])
* Reorganize the introduction
(https://issues.rudder.io/issues/7818[#7818])

==== Techniques

* Add an option for MOTD Technique to display MOTD before login
(https://issues.rudder.io/issues/7983[#7983])
* New Technique to import a GPG Key into RPM
(https://issues.rudder.io/issues/6756[#6756])

=== Bug fixes

==== API

* Fixed: Changing Directive version via API does not set default values,
and return wrong parameters
(https://issues.rudder.io/issues/7979[#7979])

==== Web - UI & UX

* Fixed: Typo in webapp message when policy generation failed
(https://issues.rudder.io/issues/8094[#8094])
* Fixed: Tooltip on Rule categories may display after selecting Rule
(https://issues.rudder.io/issues/8086[#8086])
* Fixed: Typo in webapp warn message ``sendind''
(https://issues.rudder.io/issues/7990[#7990])
* Fixed: Legend for node breakdown is not readable
(https://issues.rudder.io/issues/7969[#7969])
* Fixed: Sorting is broken in tables after sorting by compliance
(https://issues.rudder.io/issues/7653[#7653])
* Fixed: Typo in webapp logs
(https://issues.rudder.io/issues/8041[#8041])

==== Web - Nodes & inventories

* Fixed: Missing error message in node acceptation when there is a
problem with getting authorized networks
(https://issues.rudder.io/issues/8016[#8016])
* Fixed: Debian Jessie, on VMWare, are wrongly considered as
``Physical'' machine
(https://issues.rudder.io/issues/7204[#7204])
* Fixed: Rudder doesn’t store and display the IPV6 of the nodes
(https://issues.rudder.io/issues/7136[#7136])
* Fixed: Order of button on ``accept nodes in rudder'' is the exact
opposite of the rest of the webapp
(https://issues.rudder.io/issues/6722[#6722])
* Fixed: Allow to make a group with only 32bits or 64bits nodes
(https://issues.rudder.io/issues/2543[#2543])
* Fixed: When several agents are installed, hostname is doubled on that
node inventories
(https://issues.rudder.io/issues/7880[#7880])

==== Documentation

* Fixed: Broken link in the manual
(https://issues.rudder.io/issues/7817[#7817])
* Fixed: Document that when we reduce the run interval of nodes, ``no
data'' may be wrongly reported
(https://issues.rudder.io/issues/6231[#6231])

==== Packaging

* Fixed: rudder-upgrade takes too long
(https://issues.rudder.io/issues/7987[#7987])
* Fixed: Backup and restore policy_server.dat like we do with uuid.hive
file (https://issues.rudder.io/issues/7901[#7901])
* Fixed: Rudder agent tries sending an inventory during update
(https://issues.rudder.io/issues/7881[#7881])
* Fixed: rudder-upgrade does not make some check on remote sql in case
of distributed setup
(https://issues.rudder.io/issues/7849[#7849])
* Fixed: Rudder init script kill all agent on Open VZ (or similar
system) (https://issues.rudder.io/issues/4499[#4499])
* Fixed: Default vhost is not disabled on rudder-relay
(https://issues.rudder.io/issues/7846[#7846])

==== Initial promises & sys tech

* Fixed: gzip can stop rudder agent when compressing log files
(https://issues.rudder.io/issues/7985[#7985])
* Fixed: System technique cannot compress inventories
(https://issues.rudder.io/issues/7930[#7930])
* Fixed: Unexpected reports on ``Check jetty process'' component of
system techniques
(https://issues.rudder.io/issues/7821[#7821])
* Fixed: Rudder inventory don’t produce error report
(https://issues.rudder.io/issues/7785[#7785])
* Fixed: date of report may be invalid on windows
(https://issues.rudder.io/issues/7741[#7741])
* Fixed: Reporting in server-components missing when restarting some
services (ie jetty)
(https://issues.rudder.io/issues/7813[#7813])

==== System integration

* Fixed: rudder-init broken on SLES
(https://issues.rudder.io/issues/7991[#7991])
* Fixed: Missing usefull logger in logger file
(https://issues.rudder.io/issues/7910[#7910])
* Fixed: Errors with apache on ubuntu 12.04
(https://issues.rudder.io/issues/6763[#6763])

==== Server components

* Fixed: Rudder password are not properly protected
(https://issues.rudder.io/issues/8096[#8096])
* Fixed: Allow disable of git-autocommit of system policy on Update
(https://issues.rudder.io/issues/7222[#7222])
* Fixed: Node not included in dynamic group due to openldap bug with
modrdn not showing node children
(https://issues.rudder.io/issues/6780[#6780])

==== Techniques

* Fixed: When we manage twice a same package in rpm package management,
we don’t get the second report
(https://issues.rudder.io/issues/8034[#8034])
* Fixed: Incomplete reporting in service management
(https://issues.rudder.io/issues/8032[#8032])
* Fixed: Script check-techniques.sh fails on first error
(https://issues.rudder.io/issues/8012[#8012])
* Fixed: The script check-techniques.sh checks old techniques when the
parent directory contains a version number
(https://issues.rudder.io/issues/8010[#8010])
* Fixed: Fix invalid metadata.xml statement in clockSettings 3.1
(https://issues.rudder.io/issues/8009[#8009])
* Fixed: Wrong reporting in servicesManagement 3.0
(https://issues.rudder.io/issues/7975[#7975])
* Fixed: ``Download a file from shared folder'' technique doesn’t have
an explicit default value for ``Compare method'' (was mtime, now digest)
(https://issues.rudder.io/issues/7962[#7962])
* Fixed: Missing Timezones from clockConfiguration
(https://issues.rudder.io/issues/7489[#7489])
* Fixed: Missing ``don’t change'' password hash type in userManagement
(https://issues.rudder.io/issues/6493[#6493])
* Fixed: Support for more Debian / Ubuntu repository components
(https://issues.rudder.io/issues/8073[#8073])
* Fixed: Technique jobScheduler v2.0 doesn’t schedule
(https://issues.rudder.io/issues/8068[#8068])

==== Performance and scalability

* Fixed: Queries on expected reports are really slow with more than 2000
nodes (https://issues.rudder.io/issues/8057[#8057])

==== Agent

* Fixed: Put rudder agent output before the awk call
(https://issues.rudder.io/issues/7942[#7942])
* Fixed: The display of truncated lines in rudder agent output
(sometimes?) adds two spaces after | instead of one
(https://issues.rudder.io/issues/7941[#7941])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre Anriot
* Dennis Cabooter
* Janos Mattyasovszky

This is a bug fix release in the 3.1 `esr' series and therefore all
installations of 3.1.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

== Rudder 3.1.6 (2016-01-22)

=== Changes

==== Web - UI & UX

* Add last promise generation date in generation policy menu entry
(https://issues.rudder.io/issues/7661[#7661])
* Clicking on recent changes graph should show detail graph in rule
details (https://issues.rudder.io/issues/7640[#7640])
* Add an option to disable display changes graphes if they are slow
(https://issues.rudder.io/issues/7618[#7618])

==== Agent

* rudder-agent should trigger a new inventory after upgrade
(https://issues.rudder.io/issues/7620[#7620])
* rudder agent run should explain when agent is disabled.
(https://issues.rudder.io/issues/7792[#7792])
* Warn when the agent run was interrupted
(https://issues.rudder.io/issues/7790[#7790])
* Make the output of rudder agent readable by a human
(https://issues.rudder.io/issues/7698[#7698])

==== Techniques

* Add test for rudder-techniques to ensure removed deprecated techniques
don’t come back in an erroneous merge
(https://issues.rudder.io/issues/7504[#7504])

==== Documentation

* Document the zypper segfault when installing Rudder packages locally
(https://issues.rudder.io/issues/7652[#7652])
* Document AIX support in Rudder manual
(https://issues.rudder.io/issues/7650[#7650])
* Document nofiles dependency for syslog/tcp on master and relays
(https://issues.rudder.io/issues/7220[#7220])

==== Architecture - Refactoring

* Remove deprecated package rudder-policy-templates
(https://issues.rudder.io/issues/7723[#7723])
* Make NodeInfo more dependant on Node
(https://issues.rudder.io/issues/7634[#7634])
* Change AGPL to GPL in rudder-plugin-external-node-information
(https://issues.rudder.io/issues/7576[#7576])

=== Bug fixes

==== Web - Config management

* Fixed: Promise generation never finishes if jetty is restarted
mid-generation
(https://issues.rudder.io/issues/7814[#7814])
* Fixed: Too long directive name breaks directive serialization
(https://issues.rudder.io/issues/7766[#7766])
* Fixed: Error on promise generation after accepting a node
(https://issues.rudder.io/issues/7689[#7689])

==== Web - UI & UX

* Fixed: Filter keeps applied between Rules Tables within Directives
page (https://issues.rudder.io/issues/7754[#7754])
* Fixed: Typo in AGENT RUN SCHEDULE description
(https://issues.rudder.io/issues/7749[#7749])
* Fixed: Blue colour in ``Nodes by overall compliance'' chart is
confusingly the same as ``No report'' blue
(https://issues.rudder.io/issues/7757[#7757])
* Fixed: The directive tree filter should not be reset when we click on
a directive (https://issues.rudder.io/issues/7656[#7656])
* Fixed: Remove one pixel `border' in Rudder menu
(https://issues.rudder.io/issues/7641[#7641])
* Fixed: No auto scroll since rudder 3.0
(https://issues.rudder.io/issues/7617[#7617])
* Fixed: Open external links of the webapp in another tab
(https://issues.rudder.io/issues/6628[#6628])
* Fixed: Compliance bar in nodes list should trigger node display
(https://issues.rudder.io/issues/7639[#7639])

==== Web - Compliance & node report

* Fixed: When several directives value have a CFEngine var, we get
``unexpected'' due to bad regex matching
(https://issues.rudder.io/issues/7758[#7758])
* Fixed: Compliance take into account expired run
(https://issues.rudder.io/issues/7743[#7743])
* Fixed: Not accepted node reports trigger compliance processing
(https://issues.rudder.io/issues/7625[#7625])

==== Web - Nodes & inventories

* Fixed: Only one system group is displayed in node details
(https://issues.rudder.io/issues/7061[#7061])

==== Web - Maintenance

* Fixed: Jetty cache files in /tmp directory are removed by the OS
tmpwatch cron job, preventing access to the application
(https://issues.rudder.io/issues/4473[#4473])

==== Agent

* Fixed: rudder-agent does not stop on network error during file copy,
which can lead to file deletions when purging is enabled
(https://issues.rudder.io/issues/7629[#7629])
* Fixed: rudder CLI commands should print their expected options with -h
/ –help (https://issues.rudder.io/issues/7742[#7742])
* Fixed: Add a ``quiet'' option to rudder agent run to only display
errors (https://issues.rudder.io/issues/7608[#7608])

==== Techniques

* Fixed: Invalid reporting on windows for clockconfiguration if Hardware
Clock is not set
(https://issues.rudder.io/issues/7739[#7739])
* Fixed: Technique copyGitFile can send success AND error reports on
post-hook execution and lead to unexpected reports
(https://issues.rudder.io/issues/7624[#7624])
* Fixed: Unexpected reports using ``rpmPackageInstallation'' technique
(https://issues.rudder.io/issues/7623[#7623])
* Fixed: Technique ``Name resolution'': Regexp to check value of
Nameserver does not allow the use of variable
(https://issues.rudder.io/issues/3741[#3741])
* Fixed: Package management for RHEL / CentOS / SuSE / RPM systems: The
number of reports about ZMD is uncorrect
(https://issues.rudder.io/issues/3478[#3478])
* Fixed: syslog-ng’s loghost regex does not match with set line
(https://issues.rudder.io/issues/7635[#7635])
* Fixed: The ``Ignore file or directory if it does not exist'' parameter
in filesPermission is ignored
(https://issues.rudder.io/issues/7607[#7607])

==== Documentation

* Fixed: Fix use links containing emphasized keywords in manual
(https://issues.rudder.io/issues/7812[#7812])
* Fixed: The size of one image is not correctly recognized in the doc
(https://issues.rudder.io/issues/7713[#7713])
* Fixed: Some titles broken in the documentation
(https://issues.rudder.io/issues/7551[#7551])
* Fixed: Wrong anchors in Rudder API doc
(https://issues.rudder.io/issues/6694[#6694])
* Fixed: Document the use of port 5310 for rudder server debug
(https://issues.rudder.io/issues/7712[#7712])
* Fixed: Update documentation to use rudder-server-relay package instead
of manual configuration
(https://issues.rudder.io/issues/7266[#7266])

==== System integration

* Fixed: Firefox stalls after TLS handshake on self signed certificate
with a missing contact email
(https://issues.rudder.io/issues/7800[#7800])

==== Packaging

* Fixed: Test for non-applying patches on rudder-jetty and
rudder-agent-thin is broken
(https://issues.rudder.io/issues/7803[#7803])
* Fixed: Backport fixes for openldap memory leak in our package
(https://issues.rudder.io/issues/7801[#7801])
* Fixed: rudder-upgrade edits the wrong ncf.conf file causing transitory
invalid promises during upgrades
(https://issues.rudder.io/issues/7794[#7794])
* Fixed: rudder-init overwrite its logs
(https://issues.rudder.io/issues/7776[#7776])
* Fixed: rudder-server-relay rpm package should require rudder-agent
(https://issues.rudder.io/issues/7593[#7593])
* Fixed: rudder-agent not set to start on boot on RHEL 5 and older
(https://issues.rudder.io/issues/7737[#7737])

==== Initial promises & sys tech

* Fixed: initial promises don’t create
/var/rudder/configuration-repository/ncf/ncf.conf
(https://issues.rudder.io/issues/7810[#7810])
* Fixed: inventory sent file timestamp not updated in normal run (system
techniques) (https://issues.rudder.io/issues/7782[#7782])
* Fixed: Fix permissions of the rudder tools in the repo
(https://issues.rudder.io/issues/7697[#7697])
* Fixed: check-rsyslog-version is missing on the nodes
(https://issues.rudder.io/issues/7680[#7680])
* Fixed: Non quiet curl calls on root and relay servers
(https://issues.rudder.io/issues/7678[#7678])
* Fixed: Permissions of rudder tools are not preserved on relays
(https://issues.rudder.io/issues/7644[#7644])
* Fixed: Unexpected reports on ``Log system for reports'' component of
system techniques
(https://issues.rudder.io/issues/7619[#7619])
* Fixed: Rudder agent simulates an aptitude full-upgrade during each run
(https://issues.rudder.io/issues/7141[#7141])
* Fixed: Error in environment-variables.cf on Centos 5
(https://issues.rudder.io/issues/7761[#7761])
* Fixed: Missing reporting for jetty and slapd on relay
(https://issues.rudder.io/issues/7645[#7645])

==== Architecture - Refactoring

* Fixed: Change AGPL to GPL in rudder-plugin-itop
(https://issues.rudder.io/issues/7577[#7577])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Enrico Bigaignon
* Florian Heigl
* Janos Mattyasovszky
* Alex Tkachenko

This is a bug fix release in the 3.1 series and therefore all
installations of 3.1 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``esr'' release is still 2.11.*. When we release a new version
of Rudder, it needs to be thoroughly tested, and we consider the release
enterprise-ready for deployment only after it has been proven to run in
production reliably for several months.

== Rudder 3.1.5 (2015-12-10)

=== Changes

==== Documentation

* Add compliance API documentation
(https://issues.rudder.io/issues/7367[#7367])

==== Agent

* Backport rudder agent commands from 3.2 to 3.1
(https://issues.rudder.io/issues/7552[#7552])

==== Packaging

* Update OpenSSL version to latest release
(https://issues.rudder.io/issues/7368[#7368])

=== Bug fixes

==== API

* Fixed: API Parameters create ``overridable'' boolean check doesn’t
work (https://issues.rudder.io/issues/6695[#6695])
* Fixed: Node compliance API is not working
(https://issues.rudder.io/issues/7331[#7331])

==== Web - Config management

* Fixed: Read technique access does not give access to techniques
(https://issues.rudder.io/issues/7514[#7514])
* Fixed: Promises are not regenerated during upgrade
(https://issues.rudder.io/issues/7557[#7557])
* Fixed: Make possible to delete ANY active technique
(https://issues.rudder.io/issues/7536[#7536])
* Fixed: duplicate key value error on Rudder
(https://issues.rudder.io/issues/7316[#7316])
* Fixed: Changing rule/directive name does not start a promise
generation (https://issues.rudder.io/issues/7474[#7474])

==== Web - Nodes & inventories

* Fixed: Tag FULL_NAME missing from SLES12 inventory
(https://issues.rudder.io/issues/7559[#7559])
* Fixed: Inventory  content differs from hostname –fqdn and may lead to
unauthorised nodes
(https://issues.rudder.io/issues/7031[#7031])
* Fixed: Test inventories are out of date since the addition of tag
RUDDER(https://issues.rudder.io/issues/7325[#7325])
* Fixed: Accepting two nodes seems to only accept one
(https://issues.rudder.io/issues/7024[#7024])

==== Web - Technique editor

* Fixed: Impossible to create Technique with technique editor on Centos
(https://issues.rudder.io/issues/7386[#7386])

==== Web - UI & UX

* Fixed: Clone rule window too small
(https://issues.rudder.io/issues/7397[#7397])
* Fixed: Links to Node in event logs still contains an extra rudder
(https://issues.rudder.io/issues/7323[#7323])
* Fixed: Policy server url in node details is broken
(https://issues.rudder.io/issues/7462[#7462])
* Fixed: Compliance detail and compliance summary use different colours
(https://issues.rudder.io/issues/7416[#7416])
* Fixed: Dashboard incorrectly says ``0 node'' (should be nodes, in
plural) (https://issues.rudder.io/issues/7406[#7406])
* Fixed: Improve Rule compliance details loading
(https://issues.rudder.io/issues/7383[#7383])
* Fixed: Remove log from javascript console
(https://issues.rudder.io/issues/7382[#7382])
* Fixed: Rudder error page refers to wrong log file
(https://issues.rudder.io/issues/7484[#7484])

==== Server components

* Fixed: promises are not regenerated when a node is transformed into a
relay (https://issues.rudder.io/issues/7301[#7301])
* Fixed: slapd core dumps on 1TB RAM
(https://issues.rudder.io/issues/7295[#7295])

==== Agent

* Fixed: rudder-agent repository on GitHub does not have a license
(https://issues.rudder.io/issues/7394[#7394])
* Fixed: If using proxmox, process management fails due to bad options
used on vzps (https://issues.rudder.io/issues/7423[#7423])
* Fixed: check-rudder-agent silently fails if namespaces are not
supported (https://issues.rudder.io/issues/7335[#7335])
* Fixed: `rudder agent reset' doesn’t cause ncf and tools to be updated
(https://issues.rudder.io/issues/7481[#7481])
* Fixed: Agent processes parts of the environment (multiline bash
variables) (https://issues.rudder.io/issues/7094[#7094])
* Fixed: rudder agent info should show version number
(https://issues.rudder.io/issues/7482[#7482])

==== Performance and scalability

* Fixed: Major performance hit in promise generation for unused
inventories fetch
(https://issues.rudder.io/issues/7541[#7541])
* Fixed: Improve graph perf by upgrade javascript libraries
(https://issues.rudder.io/issues/7512[#7512])

==== Documentation

* Fixed: Add a section about ncf-builder and its integration wihin
Rudder (https://issues.rudder.io/issues/6305[#6305])
* Fixed: Doc build is broken because of missing Makefile dependencies
(https://issues.rudder.io/issues/7339[#7339])
* Fixed: rudder-doc 3.1 publishes 3.0 man pages
(https://issues.rudder.io/issues/7332[#7332])

==== Techniques

* Fixed: Technique ``Clock settings'' uses Europe/Paris as China’s
timezone (technique version 3.0)
(https://issues.rudder.io/issues/7501[#7501])
* Fixed: OpenSSH server configuration does not reload configurations
(https://issues.rudder.io/issues/7479[#7479])
* Fixed: Create a new version of download file from the shared folder
that would allow to set the suid and gid to multiple file
(https://issues.rudder.io/issues/7379[#7379])

==== Initial promises & sys tech

* Fixed: Use whole path to binaries in cron from check-rudder-agent on
AIX (https://issues.rudder.io/issues/7525[#7525])
* Fixed: Use of nonexistant class cfengine_community makes failsafe.cf
not copy CFEngine binaries to /var/rudder
(https://issues.rudder.io/issues/7499[#7499])
* Fixed: ``Update'' component of common technique sometimes return
unexpected status and has incomplete reporting
(https://issues.rudder.io/issues/6648[#6648])
* Fixed: Syslog fails to restart due bad line in syslog-ng.conf
(https://issues.rudder.io/issues/7389[#7389])
* Fixed: Initial promises and techniques set group to ``root'' rather
than 0, breaking non-Linux OSes
(https://issues.rudder.io/issues/7476[#7476])
* Fixed: New version of ncf_conf.cache may not be properly updated on
nodes after an upgrade
(https://issues.rudder.io/issues/7452[#7452])
* Fixed: internal security check always assume that the node is a
community one (https://issues.rudder.io/issues/7430[#7430])
* Fixed: Agent cannot replace file per folder when copying promises, and
it may lock agent with invalid promises
(https://issues.rudder.io/issues/7190[#7190])
* Fixed: svcadm does not exist - so syslog is never restarted on Solaris
(https://issues.rudder.io/issues/7464[#7464])
* Fixed: Unexpected reports on ``cron daemon'' component of system
techniques (https://issues.rudder.io/issues/7176[#7176])
* Fixed: Agent update Rudder WebDAV user and password at every run
(https://issues.rudder.io/issues/7485[#7485])
* Fixed: ncf copy is always repaired on server due to an non-convergent
hash function (https://issues.rudder.io/issues/7473[#7473])
* Fixed: Invalid inventory files only partially moved/renamed to the
fail folder (https://issues.rudder.io/issues/7004[#7004])

==== System integration

* Fixed: The rudder-agent cron on AIX uses if then, which makes some
security test fails
(https://issues.rudder.io/issues/7508[#7508])
* Fixed: JVM 8.0: warning about ``Ignoring option PermSize=128m; support
was removed in 8.0''
(https://issues.rudder.io/issues/7345[#7345])
* Fixed: rudder-agent and rudder-slapd init scripts may fail to stop
services if killall is missing or misbehaving
(https://issues.rudder.io/issues/7515[#7515])
* Fixed: /etc/init.d/rudder-jetty fails to stop jetty if it’s PID file
is missing (https://issues.rudder.io/issues/7469[#7469])
* Fixed: cf-execd is running twice after a reboot or after running
rudder-agent twice
(https://issues.rudder.io/issues/7420[#7420])
* Fixed: Initial git commit during package installation is too verbose
(https://issues.rudder.io/issues/7419[#7419])
* Fixed: Rudder OpenLDAP Authentication sans ipv4 localhost
(https://issues.rudder.io/issues/4922[#4922])
* Fixed: Missing debuging information for explain_compliance
(https://issues.rudder.io/issues/7353[#7353])
* Fixed: rudder-upgrade recommends to use deprecated rudder-server-root
init script (https://issues.rudder.io/issues/7449[#7449])
* Fixed: Selinux policy prevent running cf-agent when using technique
editor (https://issues.rudder.io/issues/7393[#7393])
* Fixed: The initial installation of rudder-jetty outputs an error on
rudder %pre scriptlet
(https://issues.rudder.io/issues/7387[#7387])

==== Packaging

* Fixed: Some patches silently fail to apply
(https://issues.rudder.io/issues/7556[#7556])
* Fixed: Modify the copy of ncf.conf instead of the original
(https://issues.rudder.io/issues/7445[#7445])
* Fixed: After a fresh install on Centos, the Rudder server web
interface does not work
(https://issues.rudder.io/issues/7395[#7395])
* Fixed: mvn –quiet is too quiet
(https://issues.rudder.io/issues/7371[#7371])
* Fixed: make wget quiet during build
(https://issues.rudder.io/issues/7370[#7370])
* Fixed: Make maven quiet during build
(https://issues.rudder.io/issues/7317[#7317])
* Fixed: rudder-inventory-ldap and rudder-jetty don’t stop their
services on uninstall and rudder-slapd can fail to restart on upgrade
(https://issues.rudder.io/issues/7516[#7516])
* Fixed: rudder-upgrade fails when *re*installing Rudder
(https://issues.rudder.io/issues/7510[#7510])
* Fixed: Script never terminate when they run rudder-jetty init script
(https://issues.rudder.io/issues/7492[#7492])
* Fixed: The package leave a temporary directory mehind
(https://issues.rudder.io/issues/7391[#7391])
* Fixed: All reports are missing (totally orange) for a node due to
multiple cf-execd processes
(https://issues.rudder.io/issues/7338[#7338])
* Fixed: Error when installing rudder : /opt/rudder/bin/rudder-upgrade:
line 573: /opt/rudder/bin/rpmvercmp: No such file or directory
(https://issues.rudder.io/issues/7470[#7470])

==== Techniques - Tests

* Fixed: rudder-techniques test script ``technique-files'' doesn’t list
promises.cf and failsafe.cf in initial-promises
(https://issues.rudder.io/issues/7496[#7496])
* Fixed: rudder-techniques test script ``technique-files'' lists files
in .git (https://issues.rudder.io/issues/7495[#7495])

==== Architecture - Refactoring

* Fixed: Correct a warning in rudder compilation
(https://issues.rudder.io/issues/7356[#7356])
* Fixed: We are using AGPL in place of GPL
(https://issues.rudder.io/issues/7546[#7546])
* Fixed: Inventory query test are not passing anymore in Rudder 3.0
(https://issues.rudder.io/issues/7357[#7357])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Layne Breitkreutz
* Dennis Cabooter
* Steeve Chailloux
* David Durieux
* Fabrice Flore-Thébault
* Greg fr
* Florian Heigl
* LibrA LinuX
* Maxime Longuet
* Olivier Mauras
* Janos Mattyasovszky

This is a bug fix release in the 3.1 series and therefore all
installations of 3.1 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``esr'' release is still 2.11.*. When we release a new version
of Rudder, it needs to be thoroughly tested, and we consider the release
enterprise-ready for deployment only after it has been proven to run in
production reliably for several months.

== Rudder 3.1.4 (2015-10-27)

=== Changes

==== Agent

* Add info about last time inventory and policy updated to rudder agent
info (https://issues.rudder.io/issues/7282[#7282])

==== System & initial promises

 * Touch local file on inventory upload
https://issues.rudder.io/issues/7206[#7206])

=== Bug fixes

==== Web - Config management

* Fixed: Change request list page, link to Rules are invalids (extra
rudder) (https://issues.rudder.io/issues/7244[#7244])

==== Web - Nodes & inventories

* Fixed: Link from node/directive list to node detail is broken on
Firefox/chrome
(https://issues.rudder.io/issues/7286[#7286])

==== Packaging

* Fixed: Maven never uses internal mirror
(https://issues.rudder.io/issues/7300[#7300])
* Fixed: Temporary files are not cleaned up after build
(https://issues.rudder.io/issues/7293[#7293])

==== System integration

* Fixed: zypper –version outputs on stderr
(https://issues.rudder.io/issues/7289[#7289])

==== Performance and scalability

* Fixed: RuleTargetTest.scala takes >40s where it should take 2s
(https://issues.rudder.io/issues/7303[#7303])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Florian Heigl
* Janos Mattyasovszky

This is a bug fix release in the 3.1 series and therefore all
installations of 3.1 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``esr'' release is still 2.11.*. When we release a new version
of Rudder, it needs to be thoroughly tested, and we consider the release
enterprise-ready for deployment only after it has been proven to run in
production reliably for several months.

== Rudder 3.1.3 (2015-10-20)

==== Web - Nodes & inventories

* Fixed: No service pack is reported when lsb_release is installed on
SLES (https://issues.rudder.io/issues/7205[#7205])

==== Techniques

* Fixed: Ssh key distribution cannot distibute several keys on one user
(https://issues.rudder.io/issues/7254[#7254])

==== Agent

* Fixed: Agent should be enabled after reinit
(https://issues.rudder.io/issues/7201[#7201])
* Fixed: Show fqdn in rudder agent info
(https://issues.rudder.io/issues/7269[#7269])

==== Initial promises & sys tech

* Fixed: Network list for apache 2.4 is invalidly generated
(https://issues.rudder.io/issues/7268[#7268])
* Fixed: The daily cf-execd and cf-serverd restart should use SRC on AIX
(https://issues.rudder.io/issues/7274[#7274])
* Fixed: System technique’s curl should follow redirects
(https://issues.rudder.io/issues/7211[#7211])

==== System integration

* Fixed: check-rudder-agent faisl on an error while checking processes
(https://issues.rudder.io/issues/7243[#7243])

==== Packaging

* Fixed: Rudder agent doesn’t build with hardening flags
(https://issues.rudder.io/issues/7257[#7257])
* Fixed: Patch not applied on fusion inventory
(https://issues.rudder.io/issues/7241[#7241])

==== Server components

* Fixed: Root server’s apache config does not honor < 2.4 for webdav
(https://issues.rudder.io/issues/7267[#7267])

==== Performance and scalability

* Fixed: Writting promises should be parallelized
(https://issues.rudder.io/issues/7265[#7265])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Florian Heigl
* Maxime Longuet
* Janos Mattyasovszky

This is a bug fix release in the 3.1 series and therefore all
installations of 3.1 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``esr'' release is still 2.11.*. When we release a new version
of Rudder, it needs to be thoroughly tested, and we consider the release
enterprise-ready for deployment only after it has been proven to run in
production reliably for several months.

== Rudder 3.1.2 (2015-09-24)

=== Changes

==== Techniques

* Fixed: Add an option to ignore non existent file in the file
permission technique
(https://issues.rudder.io/issues/7228[#7228])

==== Documentation

* Split the html documentation to improve readability and navigability
(https://issues.rudder.io/issues/6604[#6604])
* Improve rudder server requirements formatting
(https://issues.rudder.io/issues/7081[#7081])
* Improve the readability of the server installation section of the
manual (https://issues.rudder.io/issues/6603[#6603])
* Fixed: Document clearly technique upgrades
(https://issues.rudder.io/issues/7077[#7077])

=== Bug fixes

==== Web - Config management

* Fixed: When a directive from an unique technique is in several rules,
it’s order may be lost
(https://issues.rudder.io/issues/7128[#7128])
* Fixed: Order of directive in a rule is only for ncf or standard lib
(https://issues.rudder.io/issues/7127[#7127])
* Fixed: Rules are not serialized correctly anymore
(https://issues.rudder.io/issues/7108[#7108])

==== Initial promises & sys tech

* Fixed: The rudder server tries to send ``uuid.hive'' as an inventory
(https://issues.rudder.io/issues/6987[#6987])
* Fixed: System technique distributePolicy is not system and has two
system var section
(https://issues.rudder.io/issues/7138[#7138])
* Fixed: Promise copy is not convergent: if the copy is interupted, it
will never recover
(https://issues.rudder.io/issues/7086[#7086])
* Fixed: If the agent schedule is not every 5 minutes, inventory may not
be sent anymore
(https://issues.rudder.io/issues/6718[#6718])
* Fixed: Environnement variables cannot be used on windows
(https://issues.rudder.io/issues/7150[#7150])
* Fixed: send-clean.sh always wait for expiration time for signed
inventories (https://issues.rudder.io/issues/7212[#7212])

==== Agent

* Fixed: ldap error with rudder-keys
(https://issues.rudder.io/issues/7197[#7197])
* Fixed: Wrong roles display in rudder agent info
(https://issues.rudder.io/issues/7143[#7143])

==== System integration

* Fixed: Error starting apache on SLES11 relay
(https://issues.rudder.io/issues/7097[#7097])

==== Web - Compliance & node report

* Fixed: Agent schedule is not historised, so we can’t know what was the
agent run interval in the past
(https://issues.rudder.io/issues/7154[#7154])

==== Web - Technique editor

* Fixed: Read only role is not correctly interpreted in technique
editor. (https://issues.rudder.io/issues/7199[#7199])

==== Techniques

* Fixed: motd technique wrongly reports that it is incompatible with
windows (https://issues.rudder.io/issues/7153[#7153])

==== Documentation

* Fixed: Documentation for Rudder 3.1 doesn’t properly state the port to
open between client and server
(https://issues.rudder.io/issues/7122[#7122])

==== Packaging

* Fixed: issues with process management on physical hosting LXC
containers (https://issues.rudder.io/issues/7189[#7189])
* Fixed: Migrations to 3.1 may fail due to a wrong Jetty configuration
migration on RPM based systems
(https://issues.rudder.io/issues/7166[#7166])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Libra Linux

This is a bug fix release in the 3.1 series and therefore all
installations of 3.1 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.11.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 3.1.1 (2015-08-19)

=== Changes

==== Web - Config management

* Allow user to choose order of Directive application in a Rule
(https://issues.rudder.io/issues/2881[#2881])

=== Bug fixes

==== Web - Config management

* Fixed: System object (techniques, directives, rules, groups) must be
always enabled
(https://issues.rudder.io/issues/7064[#7064])
* Fixed: Editing a rule category remove it from Git - rule categories
disapear! (Ranärok ensues)
(https://issues.rudder.io/issues/6840[#6840])
* Fixed: Clear cache doesn’t regenerate expected reports
(https://issues.rudder.io/issues/7080[#7080])

==== Web - Compliance & node report

* Fixed: Reporting cannot be used when there is several component with
the same value and several messages
(https://issues.rudder.io/issues/7037[#7037])

==== Web - Maintenance

* Fixed: When accessing event logs page, it stays empty until jetty is
restarted (https://issues.rudder.io/issues/6939[#6939])

==== Web - Nodes & inventories

* Fixed: If domain name is not set in resolv.conf, the inventory
generated is invalid
(https://issues.rudder.io/issues/7001[#7001])
* Fixed: Xen list parsed badly by FusionInventory, causing VCPU to be
counted badly (https://issues.rudder.io/issues/6754[#6754])
* Fixed: FusionInventory doesn’t provide the Rudder extension on other
platform than Linux
(https://issues.rudder.io/issues/6747[#6747])

==== Agent

* Fixed: If we ask to install a package in a version at least equal to
another, we get no report if the version installed is > than the one
requested (https://issues.rudder.io/issues/6996[#6996])
* Fixed: Migration from 2.10.x to 2.11.x on Debian may disable the agent
(https://issues.rudder.io/issues/7099[#7099] )

==== Techniques

* Fixed: aptPackageManagerSetting technique doesn’t work on Ubuntu
(https://issues.rudder.io/issues/6999[#6999])
* Fixed: Reporting on openssh server configuration technique is not
correct for port edition
(https://issues.rudder.io/issues/6942[#6942])
* Fixed: ntp Technique does not report when repairing
(https://issues.rudder.io/issues/6941[#6941])

==== Initial promises & sys tech

* Fixed: Do not sign inventory on windows
(https://issues.rudder.io/issues/7011[#7011])
* Fixed: Bad regexp in the cron for Rudder nova
(https://issues.rudder.io/issues/7014[#7014])
* Fixed: A report is missing on system techniques when cron needs to be
restartd (https://issues.rudder.io/issues/6660[#6660])
* Fixed: On Windows, Rudder specific inventories is not be added to
inventory with most version of CFEngine Enterprise
(https://issues.rudder.io/issues/7057[#7057])
* Fixed: When promises could have been updated, we still have the error
messages saying we couldn’t update promises
(https://issues.rudder.io/issues/7038[#7038])
* Fixed: When the nxlog configuration is changed on windows, service is
not restarted (https://issues.rudder.io/issues/7012[#7012])
* Fixed: System techniques on systemd based system do not handle boot
script correctly
(https://issues.rudder.io/issues/6988[#6988])
* Fixed: After updagre to 3.1.1, nodes reports error ``could not
retrieve UUID of the policy server''
(https://issues.rudder.io/issues/7109[#7109])

==== Performance and scalability

* Fixed: Copy ncf only if it is updated
(https://issues.rudder.io/issues/7020[#7020])

==== Packaging

* Fixed: Some code is duplicated in debian postinst
(https://issues.rudder.io/issues/7073[#7073])
* Fixed: Wrong permission on /var/lib/ncf-api-env
(https://issues.rudder.io/issues/7095[#7095])

==== System integration

* Fixed: Rsyslog problem on Ubuntu 14.04 fresh install
(https://issues.rudder.io/issues/6127[#6127])
* Fixed: With SELinux enabled, httpd cannot execute ncf scripts
(https://issues.rudder.io/issues/7053[#7053])
* Fixed: Add httpd log context to /var/log/rudder/apache2
(https://issues.rudder.io/issues/7041[#7041])
* Fixed: When SELinux is enabled, the ncf-api-venv home is owned by root
(https://issues.rudder.io/issues/7021[#7021])
* Fixed: Could not upload inventory when SELinux is enabled
(https://issues.rudder.io/issues/7019[#7019])
* Fixed: Error starting apache on SLES11 relay
(https://issues.rudder.io/issues/7097[#7097])

==== Architecture - Refactoring

* Fixed: Remove scala compiler warning about comparing values of type
Null (https://issues.rudder.io/issues/7072[#7072])

==== Architecture - Internal libs

* Fixed: A test is not compiling on branch 2.11 since #6729 was merged
(https://issues.rudder.io/issues/7056[#7056])
* Fixed: Exception thrown when debug_timer is set on Rule pages
(https://issues.rudder.io/issues/7071[#7071])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Remi Debay
* Janos Mattyasovszky
* Christophe Nowicki

This is a bug fix release in the 3.1 series and therefore all
installations of 3.1 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.11.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 3.1.0 (2015-07-09)

=== Changes

==== Web - Compliance & node report

* Display node compliances in Nodes lists
(https://issues.rudder.io/issues/6781[#6781])

==== Agent

* Add rudder agent check in rudder cli
(https://issues.rudder.io/issues/6359[#6359])

==== Web - UI & UX

* Rudder 3.1 logo
(https://issues.rudder.io/issues/6927[#6927])

==== Documentation

* Update documentation for 3.1 release
(https://issues.rudder.io/issues/6908[#6908])

==== Packaging

* Add a caching system to rudder build system
(https://issues.rudder.io/issues/6713[#6713])
* Remove migration process from old version to 3.1
(https://issues.rudder.io/issues/6911[#6911])

=== Bug fixes

==== Web - UI & UX

* Fixed: More coherent informations on dashboard
(https://issues.rudder.io/issues/6777[#6777])
* Fixed: Broken down stats by agent version is completely out of it
(https://issues.rudder.io/issues/6491[#6491])

==== Web - Config management

* Fixed: After a partial promise generation, some nodes being a relay
may have their promises stored in a non reachable location
(https://issues.rudder.io/issues/6729[#6729])

==== Web - Nodes & inventories

* Fixed: Broken inventory - missing `FQDN'
(https://issues.rudder.io/issues/6782[#6782])
* Fixed: Heartbeat bad interval time calcul on node
(https://issues.rudder.io/issues/6746[#6746])

==== Agent

* Fixed: Cf-agent writes incorrect files when the server answers too
slowly during recursive copy
(https://issues.rudder.io/issues/6915[#6915])

==== Initial promises & sys tech

* Fixed: Error in signInventories with nodes <3.1 and a 3.1 server
(https://issues.rudder.io/issues/6856[#6856])
* Fixed: System techniques tries to add old services at boot
(https://issues.rudder.io/issues/6833[#6833])
* Fixed: Use HTTP for inventory handling on AIX to prevent minicurl
errors (https://issues.rudder.io/issues/6831[#6831])
* Fixed: Unsigned inventories are not processed
(https://issues.rudder.io/issues/6748[#6748])
* Fixed: Rudder relay rsyslog configuration still have AllowedSender
directives (https://issues.rudder.io/issues/6907[#6907])
* Fixed: Ubuntu trusty does not have an /etc/motd by default
(https://issues.rudder.io/issues/6904[#6904])
* Fixed: We can’t use cf-runagent because port is not taken into account
in the body runagent control
(https://issues.rudder.io/issues/6916[#6916])
* Fixed: Nodes using syslogd coninue to report to their old server when
changing their policy server
(https://issues.rudder.io/issues/6845[#6845])
* Fixed: Editing non-existent /etc/rsyslog.d/pgsql.conf in initial
promises (https://issues.rudder.io/issues/6784[#6784])

==== Web - Maintenance

* Fixed: Syslog protocol not correctly set, using always UDP
(https://issues.rudder.io/issues/6905[#6905])

==== System integration

* Fixed: Bad handling of pid file on OpenVZ
(https://issues.rudder.io/issues/6928[#6928])
* Fixed: Rudder-jetty init script fails to get openjdk version
(https://issues.rudder.io/issues/6765[#6765])
* Fixed: Sometimes, promises get corrupted to the point they can’t be
automatically repaired on a node
(https://issues.rudder.io/issues/6768[#6768])

==== Server components

* Fixed: Relay configuration always use TCP to send reports
(https://issues.rudder.io/issues/6906[#6906])
* Fixed: Relay configuration should be defined on https
(https://issues.rudder.io/issues/6836[#6836])
* Fixed: Rudder-ldap and rudder-jetty settings should be user
configurable in /etc/default
(https://issues.rudder.io/issues/6773[#6773])
* Fixed: Update OpenLDAP to 2.4.41
(https://issues.rudder.io/issues/6931[#6931])

==== Techniques

* Fixed: No reporting in dnsConfiguration 3.0
(https://issues.rudder.io/issues/6775[#6775])
* Fixed: Openssh technique is missing reports
(https://issues.rudder.io/issues/6611[#6611])
* Fixed: Unexpected status for fileAlterationMonitoring
(https://issues.rudder.io/issues/6771[#6771])

==== Documentation

* Fixed: Wrong hierachy in archives section of the manual
(https://issues.rudder.io/issues/6909[#6909])
* Fixed: Broken asciidoc list formatting
(https://issues.rudder.io/issues/6778[#6778])
* Fixed: Outdated download link in the manual
(https://issues.rudder.io/issues/6764[#6764])
* Fixed: Broken link and misplaced page in documentation
(https://issues.rudder.io/issues/6757[#6757])

==== Packaging

* Fixed: AIX installations output errors due to ``cp -a'' usage
(https://issues.rudder.io/issues/6830[#6830])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Dennis Cabooter
* Olivier Mauras

This version of Rudder is a final release. We have tested it thoroughly
and believe it to be free of any major bugs.

== Rudder 3.1.0~rc1 (2015-06-18)

=== Changes

==== API

* Add info about API
(https://issues.rudder.io/issues/6715[#6715])
* Retrieve compliance from the API
(https://issues.rudder.io/issues/6137[#6137])

==== Web - Config management

* Display/manage Directives in Rule details like Groups
(https://issues.rudder.io/issues/6755[#6755])
* Add directive search box in Rule parameters panel
(https://issues.rudder.io/issues/3851[#3851])

==== Agent

* Upgrade CFEngine to 3.6.5
(https://issues.rudder.io/issues/6705[#6705])
* Add an option to run cf-agent with -v to rudder agent run
(https://issues.rudder.io/issues/6731[#6731])
* Man pages for the rudder command
(https://issues.rudder.io/issues/6659[#6659])

==== System integration

* Let the user choose between udp and tcp for syslog messages
(https://issues.rudder.io/issues/5622[#5622])

=== Bug fixes

==== Web - Compliance & node report

* Fixed: Compliance in dashboard and rule page are not consistant
(https://issues.rudder.io/issues/6663[#6663])
* Fixed: The Global compliance is buggy when there is no data
(https://issues.rudder.io/issues/6633[#6633])
* Fixed: Blue for no report in bar charts doesn’t make sense
(https://issues.rudder.io/issues/6489[#6489])

==== Web - UI & UX

* Fixed: No rules displayed in firefox
(https://issues.rudder.io/issues/6490[#6490])

==== Web - Nodes & inventories

* Fixed: Search results grayed out
(https://issues.rudder.io/issues/6277[#6277])
* Fixed: Hostname in inventory may sometimes be wrongfully in lowercase
(https://issues.rudder.io/issues/6711[#6711])

==== Web - Technique editor

* Fixed: Cannot save technique with ncf builder - error during the API
call to the technique librairy reload
(https://issues.rudder.io/issues/6724[#6724])

==== System integration

* Fixed: rudder-server-root init script is not compatible with systemd
(https://issues.rudder.io/issues/6760[#6760])
* Fixed: RHEL7 does not initialise postgresql db
(https://issues.rudder.io/issues/6702[#6702])
* Fixed: ncf init fails in webapp postinst
(https://issues.rudder.io/issues/6698[#6698])
* Fixed: rudder-reports does not find correct postgresql service when
using systemctl
(https://issues.rudder.io/issues/6699[#6699])
* Fixed: Startup links for rudder-server-root on Ubuntu are not correct
- before 3.1 (https://issues.rudder.io/issues/6263[#6263])
* Fixed: Error about ldconfig during rudder-agent installation on AIX
(https://issues.rudder.io/issues/6703[#6703])

==== Server components

* Fixed: rudder-reports has not sufficient dependency to postgresql’s
version (https://issues.rudder.io/issues/6662[#6662])
* Fixed: When a node is promoted to relay, the old rsyslog conf is never
replaced (https://issues.rudder.io/issues/6721[#6721])

==== Documentation

* Fixed: Add Debian 8 support in the specs for Rudder nodes
(https://issues.rudder.io/issues/6704[#6704])
* Fixed: HashcodeCaching.scala typo error WRNING => WARNING
(https://issues.rudder.io/issues/6734[#6734])

==== Techniques

* Fixed: Promises.st can’t load ncf on windows
(https://issues.rudder.io/issues/6700[#6700])

==== Initial promises & sys tech

* Fixed: Create a rudder variable containing all IP of agents
(https://issues.rudder.io/issues/6481[#6481])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Dennis Cabooter
* Florian Heigl
* Janos Mattyasovszky
* Olivier Mauras

This software is in beta status and contains several new features but we
have tested it and believe it to be free of any critical bugs. The use
on production systems is not encouraged at this time and is at your own
risk. However, we do encourage testing, and welcome all and any
feedback!

== Rudder 3.1.0~beta1 (2015-06-08)

=== Changes

==== System integration

* Improve Rudder security in 3.1: Inventory signature and security,
SELinux compliance
(https://issues.rudder.io/issues/6589[#6589])
* Package rudder-agent SLES12
(https://issues.rudder.io/issues/6547[#6547])
* Generic rudder init script
(https://issues.rudder.io/issues/6513[#6513])

==== API

* Add an API to manage Group categories
(https://issues.rudder.io/issues/6512[#6512])
* Add an API to manage Rule categories
(https://issues.rudder.io/issues/6511[#6511])
* Add an API to query Nodes
(https://issues.rudder.io/issues/6470[#6470])

==== Agent

* Add a rudder remote run command
(https://issues.rudder.io/issues/6543[#6543])
* Add rudder-agent general informations command
(https://issues.rudder.io/issues/6432[#6432])

==== Web - UI & UX

* Have a pretty 404 Page, explaining what is wrong
(https://issues.rudder.io/issues/6401[#6401])

==== Documentation

* Prepare doc for 3.1 branch
(https://issues.rudder.io/issues/6647[#6647])

==== Architecture - Dependencies

* Update pom version to 3.1.0~alpha1 on master
(https://issues.rudder.io/issues/6064[#6064])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky

This software is in beta status and contains several new features but we
have tested it and believe it to be free of any critical bugs. The use
on production systems is not encouraged at this time and is at your own
risk. However, we do encourage testing, and welcome all and any
feedback!
