= Changelogs for Rudder plugin auth-backends 8.1.\* versions

== auth-backends-8.1.0.rc1-2.7 (2024-04-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.1.0.beta2-2.7 (2024-03-22)

=== Changes


==== Packaging

* Add description field to plugin metadata
    (https://issues.rudder.io/issues/24477[#24477])

=== Bug fixes

==== Miscellaneous

* Fixed: Update JWT lib for CVE-2023-52428
    (https://issues.rudder.io/issues/24469[#24469])
* Fixed: Fix UI issues caused by bootstrap update in user-management and auth-backends plugin
    (https://issues.rudder.io/issues/24434[#24434])
* Fixed: Documentation for OIDC properties is not up to date
    (https://issues.rudder.io/issues/24384[#24384])
* Fixed: Autoprovisioned users don't have access to any nodes
    (https://issues.rudder.io/issues/24394[#24394])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.1.0.beta1-2.7 (2024-03-04)

=== Changes


==== UI - UX

* Integrate Sass with front-end development tools
    (https://issues.rudder.io/issues/24050[#24050])

=== Bug fixes

==== Miscellaneous

* Fixed: No API right with OIDC provided roles
    (https://issues.rudder.io/issues/24202[#24202])
* Fixed: When the Oauth2 role provisioning attribute is incorrect, the error is misleading
    (https://issues.rudder.io/issues/24042[#24042])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.1.0.alpha1-2.7 (2024-01-19)

=== Changes


==== Plugins management

* license plugin checks are not building since node facts changes
    (https://issues.rudder.io/issues/24029[#24029])

=== Bug fixes

==== UI - UX

* Fixed: Fix UI problems following the Bootstrap 5 upgrade
    (https://issues.rudder.io/issues/23928[#23928])

==== Miscellaneous

* Fixed: One note section is not rendered in auth-backend plugin
    (https://issues.rudder.io/issues/23919[#23919])
* Fixed: Remove Password authentication for OAuth2
    (https://issues.rudder.io/issues/23768[#23768])
* Fixed: Update rudder-plugins dependencies
    (https://issues.rudder.io/issues/23762[#23762])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

