= Changelogs for Rudder plugin branding 8.1.\* versions

== branding-8.1.0-2.2 (2024-04-11)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-8.1.0.rc1-2.2 (2024-04-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-8.1.0.beta2-2.2 (2024-03-22)

=== Changes


==== Packaging

* Add description field to plugin metadata
    (https://issues.rudder.io/issues/24477[#24477])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-8.1.0.beta1-2.2 (2024-03-04)

=== Changes


==== UI - UX

* Integrate Sass with front-end development tools
    (https://issues.rudder.io/issues/24050[#24050])

=== Bug fixes

==== Miscellaneous

* Fixed: Fix UI issues caused by bootstrap update in branding plugin
    (https://issues.rudder.io/issues/24225[#24225])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-8.1.0.alpha1-2.2 (2024-01-19)

=== Changes


==== Plugins management

* license plugin checks are not building since node facts changes
    (https://issues.rudder.io/issues/24029[#24029])

=== Bug fixes

==== UI - UX

* Fixed: Fix UI problems following the Bootstrap 5 upgrade
    (https://issues.rudder.io/issues/23928[#23928])

==== Miscellaneous

* Fixed: Error in test (typo)
    (https://issues.rudder.io/issues/23858[#23858])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

