= Changelogs for Rudder plugin change-validation 8.1.\* versions

== change-validation-8.1.10-2.4 (2024-12-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.9-2.4 (2024-11-28)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.8-2.4 (2024-11-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.7-2.4 (2024-10-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.6-2.4 (2024-08-01)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Missing values for VariableSpec in test
    (https://issues.rudder.io/issues/25160[#25160])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.5-2.4 (2024-07-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.4-2.4 (2024-06-20)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.3-2.4 (2024-06-02)

=== Changes


==== Packaging

* Add basic elm-review config - plugins
    (https://issues.rudder.io/issues/24880[#24880])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.2-2.4 (2024-04-30)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.1-2.4 (2024-04-25)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Already defined json encoders break plugin build
    (https://issues.rudder.io/issues/24790[#24790])
* Fixed: Change validation group settings has broken UI
    (https://issues.rudder.io/issues/24685[#24685])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.1-2.4 (2024-04-25)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Change validation group settings has broken UI
    (https://issues.rudder.io/issues/24685[#24685])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.0-2.4 (2024-04-12)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: /var/rudder/plugin-resources/change-validation is not created anymore on plugin startup
    (https://issues.rudder.io/issues/24714[#24714])

=== Release notes

This is a bug fix release in the 8.1.0-2.4 series and therefore all installations of 8.1.0-2.4.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.0-2.3 (2024-04-11)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.0.rc1-2.3 (2024-04-08)

=== Changes


=== Bug fixes

==== Refactoring

* Fixed: Several compilation error following change in rudder-core
    (https://issues.rudder.io/issues/24623[#24623])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.0.beta2-2.3 (2024-03-22)

=== Changes


==== Packaging

* Add description field to plugin metadata
    (https://issues.rudder.io/issues/24477[#24477])

=== Bug fixes

==== Miscellaneous

* Fixed: Remove duplicated files
    (https://issues.rudder.io/issues/24545[#24545])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.0.beta1-2.3 (2024-03-04)

=== Changes


==== Miscellaneous

* We need an option to force validation of change requests
    (https://issues.rudder.io/issues/24206[#24206])

==== UI - UX

* Integrate Sass with front-end development tools
    (https://issues.rudder.io/issues/24050[#24050])

=== Bug fixes

==== Miscellaneous

* Fixed: change validation plugin documentation refers to Rudder 5.0
    (https://issues.rudder.io/issues/24293[#24293])
* Fixed: Fix typo in HTML of the setting to validate all changes
    (https://issues.rudder.io/issues/24249[#24249])
* Fixed: Fix typo in HTML of the setting to validate all changes
    (https://issues.rudder.io/issues/24249[#24249])
* Fixed: Fix UI issues caused by bootstrap update in change-validation plugin
    (https://issues.rudder.io/issues/24213[#24213])
* Fixed: Group repository in tests should get by ids
    (https://issues.rudder.io/issues/24185[#24185])
* Fixed: When self deployment is disabled, you can still deploy your changes.
    (https://issues.rudder.io/issues/24143[#24143])
* Fixed: Pending deployment action are completely messed up
    (https://issues.rudder.io/issues/24111[#24111])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.1.0.alpha1-2.3 (2024-01-19)

=== Changes


==== Plugins management

* license plugin checks are not building since node facts changes
    (https://issues.rudder.io/issues/24029[#24029])

==== Refactoring

* List change requests with additional filters
    (https://issues.rudder.io/issues/23907[#23907])

=== Bug fixes

==== UI - UX

* Fixed: Fix UI problems following the Bootstrap 5 upgrade
    (https://issues.rudder.io/issues/23928[#23928])

==== Miscellaneous

* Fixed: Update rudder-plugins dependencies
    (https://issues.rudder.io/issues/23762[#23762])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

