= Changelogs for Rudder plugin consul 8.1.\* versions

== consul-8.1.9-2.1 (2024-11-28)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.8-2.1 (2024-11-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.7-2.1 (2024-10-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.6-2.1 (2024-08-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.5-2.1 (2024-07-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.4-2.1 (2024-06-20)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.3-2.1 (2024-06-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.2-2.1 (2024-04-30)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.1-2.1 (2024-04-25)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.1-2.1 (2024-04-25)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.0-2.1 (2024-04-11)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.0.rc1-2.1 (2024-04-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.0.beta2-2.1 (2024-03-22)

=== Changes


==== Packaging

* Add description field to plugin metadata
    (https://issues.rudder.io/issues/24477[#24477])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.0.beta1-2.1 (2024-03-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== consul-8.1.0.alpha1-2.1 (2024-01-19)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

