= Changelogs for Rudder plugin datasources 8.1.\* versions

== datasources-8.1.0.rc1-2.4 (2024-04-08)

=== Changes


=== Bug fixes

==== Refactoring

* Fixed: Several compilation error following change in rudder-core
    (https://issues.rudder.io/issues/24623[#24623])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.1.0.beta2-2.4 (2024-03-22)

=== Changes


==== Packaging

* Add description field to plugin metadata
    (https://issues.rudder.io/issues/24477[#24477])

=== Bug fixes

==== Packaging

* Fixed: Remove duplicated files from some plugins
    (https://issues.rudder.io/issues/24368[#24368])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.1.0.beta1-2.4 (2024-03-04)

=== Changes


==== UI - UX

* Integrate Sass with front-end development tools
    (https://issues.rudder.io/issues/24050[#24050])

=== Bug fixes

==== Miscellaneous

* Fixed: Fix UI issues caused by bootstrap update in datasources plugin
    (https://issues.rudder.io/issues/24221[#24221])
* Fixed: Missing write check on delete button
    (https://issues.rudder.io/issues/24161[#24161])
* Fixed: The UI is barely functional
    (https://issues.rudder.io/issues/24154[#24154])
* Fixed: Merge conflict error
    (https://issues.rudder.io/issues/24108[#24108])

==== Plugins management

* Fixed: gulp-sass missing for datasources
    (https://issues.rudder.io/issues/24163[#24163])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.1.0.alpha1-2.4 (2024-01-19)

=== Changes


==== Plugins management

* license plugin checks are not building since node facts changes
    (https://issues.rudder.io/issues/24029[#24029])

=== Bug fixes

==== UI - UX

* Fixed: Fix UI problems following the Bootstrap 5 upgrade
    (https://issues.rudder.io/issues/23928[#23928])

==== Miscellaneous

* Fixed: Rename the "Add data source" button to "Create" in 8.0
    (https://issues.rudder.io/issues/23900[#23900])
* Fixed: Rename the "Add data source" button to "Create"
    (https://issues.rudder.io/issues/23875[#23875])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

