= Changelogs for Rudder plugin dsc 8.1.\* versions

== dsc-8.1.0-2.5 (2024-04-11)

=== Changes


==== Agent library

* Split the F# library source file in several files
    (https://issues.rudder.io/issues/24700[#24700])

=== Bug fixes

==== System techniques

* Fixed: Agents are not trying to send old accumulated reports anymore
    (https://issues.rudder.io/issues/24650[#24650])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.1.0.rc1-2.5 (2024-04-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.1.0.beta2-2.5 (2024-03-22)

=== Changes


=== Bug fixes

==== Security

* Fixed: Change the security Jenkinsfile to use read-only containers
    (https://issues.rudder.io/issues/24426[#24426])

==== Inventory

* Fixed: Hostname differs from webapp and rudder agent info on Windows
    (https://issues.rudder.io/issues/24360[#24360])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.1.0.beta1-2.5 (2024-03-04)

=== Changes


==== ci

* Try to change the CI dockers to read-only
    (https://issues.rudder.io/issues/24212[#24212])

=== Bug fixes

==== Agent library

* Fixed: Add policy update by default in agent run command
    (https://issues.rudder.io/issues/24103[#24103])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.1.0.alpha1-2.5 (2024-01-19)

=== Changes


==== Miscellaneous

* Adapt license check for private plugins with nodefacts changes
    (https://issues.rudder.io/issues/24030[#24030])

==== System techniques

* Compute the start time of the agent scheduled task from the policies
    (https://issues.rudder.io/issues/24012[#24012])

==== Agent library

* Update dotnet dependencies
    (https://issues.rudder.io/issues/23832[#23832])

=== Bug fixes

==== Agent library

* Fixed: Load the mustache dll at run startup instead of reloading it in each method call
    (https://issues.rudder.io/issues/24001[#24001])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

