= Changelogs for Rudder plugin multi-tenants 8.1.\* versions

== multi-tenants-8.1.9-1.1 (2024-11-28)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Tenants administration UI text should not be specific to Rudder version
    (https://issues.rudder.io/issues/25914[#25914])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.1.8-1.1 (2024-11-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.1.7-1.1 (2024-10-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.1.6-1.1 (2024-08-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.1.5-1.1 (2024-07-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.1.4-1.1 (2024-06-20)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.1.2-1.0 (2024-04-30)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.1.1-1.0 (2024-04-25)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Cannot set API account access to tenants with invalid ids 
    (https://issues.rudder.io/issues/24663[#24663])
* Fixed: title of multi tenant popup is wrong on creation
    (https://issues.rudder.io/issues/24718[#24718])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.1.1-1.0 (2024-04-25)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Cannot set API account access to tenants with invalid ids 
    (https://issues.rudder.io/issues/24663[#24663])
* Fixed: title of multi tenant popup is wrong on creation
    (https://issues.rudder.io/issues/24718[#24718])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.1.0-1.0 (2024-04-11)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.1.0.rc1-1.0 (2024-04-08)

=== Changes


==== Miscellaneous

* Improve UI to manage tenants
    (https://issues.rudder.io/issues/24599[#24599])
* UI to manage tenants
    (https://issues.rudder.io/issues/24588[#24588])

=== Bug fixes

==== Documentation

* Fixed: Tenants documentation has format issue and broken link
    (https://issues.rudder.io/issues/24667[#24667])

==== Miscellaneous

* Fixed: Set tenant API returns null when node didn't change tenant 
    (https://issues.rudder.io/issues/24640[#24640])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

