= Changelogs for Rudder plugin node-external-reports 8.1.\* versions

== node-external-reports-8.1.10-2.1 (2024-12-05)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.9-2.1 (2024-11-28)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.8-2.1 (2024-11-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.7-2.1 (2024-10-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.6-2.1 (2024-08-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.5-2.1 (2024-07-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.4-2.1 (2024-06-20)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.3-2.1 (2024-06-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.2-2.1 (2024-04-30)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.1-2.1 (2024-04-25)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: External reports tab is not aligned in nodes page and content is always displayed
    (https://issues.rudder.io/issues/24630[#24630])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.1-2.1 (2024-04-25)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: External reports tab is not aligned in nodes page and content is always displayed
    (https://issues.rudder.io/issues/24630[#24630])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.0-2.1 (2024-04-11)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.0.rc1-2.1 (2024-04-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.0.beta2-2.1 (2024-03-22)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Remove duplicated files from some plugins
    (https://issues.rudder.io/issues/24368[#24368])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.0.beta1-2.1 (2024-03-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== node-external-reports-8.1.0.alpha1-2.1 (2024-01-19)

=== Changes


==== Plugins management

* license plugin checks are not building since node facts changes
    (https://issues.rudder.io/issues/24029[#24029])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

