= Changelogs for Rudder plugin scale-out-relay 8.1.\* versions

== scale-out-relay-8.1.4-2.1 (2024-06-20)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== scale-out-relay-8.1.3-2.1 (2024-06-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== scale-out-relay-8.1.2-2.1 (2024-04-30)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== scale-out-relay-8.1.1-2.1 (2024-04-25)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== scale-out-relay-8.1.1-2.1 (2024-04-25)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== scale-out-relay-8.1.0-2.1 (2024-04-11)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== scale-out-relay-8.1.0.rc1-2.1 (2024-04-08)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Promote a node to relay command failed with parsing message error
    (https://issues.rudder.io/issues/24417[#24417])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== scale-out-relay-8.1.0.beta2-2.1 (2024-03-22)

=== Changes


==== Packaging

* Add description field to plugin metadata
    (https://issues.rudder.io/issues/24477[#24477])

=== Bug fixes

==== Packaging

* Fixed: Remove duplicated files from some plugins
    (https://issues.rudder.io/issues/24368[#24368])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== scale-out-relay-8.1.0.beta1-2.1 (2024-03-04)

=== Changes


==== UI - UX

* Integrate Sass with front-end development tools
    (https://issues.rudder.io/issues/24050[#24050])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== scale-out-relay-8.1.0.alpha1-2.1 (2024-01-19)

=== Changes


==== Plugins management

* license plugin checks are not building since node facts changes
    (https://issues.rudder.io/issues/24029[#24029])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

