= Changelogs for Rudder plugin secret-management 8.1.\* versions

== secret-management-8.1.4-1.1 (2024-06-20)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-8.1.3-1.1 (2024-06-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-8.1.2-1.1 (2024-04-30)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-8.1.1-1.1 (2024-04-25)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-8.1.1-1.1 (2024-04-25)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-8.1.0-1.1 (2024-04-11)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-8.1.0.rc1-1.1 (2024-04-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-8.1.0.beta2-1.1 (2024-03-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Secret management enables extended user authorizations like user-management
    (https://issues.rudder.io/issues/24399[#24399])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-8.1.0.beta1-1.1 (2024-03-04)

=== Changes


==== Miscellaneous

* Compile css files with Sass
    (https://issues.rudder.io/issues/24092[#24092])

=== Bug fixes

==== Packaging

* Fixed: Private plugins with jar files contain duplicated files
    (https://issues.rudder.io/issues/24246[#24246])

==== Miscellaneous

* Fixed: Fix UI issues caused by bootstrap update in secrets management plugin
    (https://issues.rudder.io/issues/24239[#24239])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-8.1.0.alpha1-1.1 (2024-01-19)

=== Changes


==== Miscellaneous

* Adapt license check for private plugins with nodefacts changes
    (https://issues.rudder.io/issues/24030[#24030])

=== Bug fixes

==== Miscellaneous

* Fixed: Rename the "Create Secret" button in "Create"
    (https://issues.rudder.io/issues/23880[#23880])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

