= Changelogs for Rudder plugin system-updates 8.1.\* versions

== system-updates-8.1.11-1.17 (2025-01-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.10-1.16 (2024-12-05)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.9-1.16 (2024-11-28)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Timezone information should be more visible in system-updates UI
    (https://issues.rudder.io/issues/25899[#25899])
* Fixed: System update current server time take locale timezone instead of UTC
    (https://issues.rudder.io/issues/25689[#25689])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.8-1.16 (2024-11-08)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Windows campaigns do not automatically trigger an inventory when done
    (https://issues.rudder.io/issues/25828[#25828])
* Fixed: Windows campaigns may fail to report their execution if a reboot needed
    (https://issues.rudder.io/issues/25818[#25818])
* Fixed: Missing icon for windows 2022 in system update page
    (https://issues.rudder.io/issues/25690[#25690])
* Fixed: Refresh button in node campaign results does not have a utility
    (https://issues.rudder.io/issues/25697[#25697])
* Fixed: Indicate campaign time as UTC
    (https://issues.rudder.io/issues/25570[#25570])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.7-1.16 (2024-10-01)

=== Changes


==== Miscellaneous

* Add a parameter to customize reboot behavior
    (https://issues.rudder.io/issues/25341[#25341])

=== Bug fixes

==== Miscellaneous

* Fixed: Removing date filter in campaign event list is impossible
    (https://issues.rudder.io/issues/24056[#24056])
* Fixed: System update tab on a node doesn't bring you to the node details
    (https://issues.rudder.io/issues/25446[#25446])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.6-1.16 (2024-08-01)

=== Changes


==== Miscellaneous

* Document the Windows system update hooks
    (https://issues.rudder.io/issues/25255[#25255])
* Add a delete button for events (only done or skipped events)
    (https://issues.rudder.io/issues/25077[#25077])

=== Bug fixes

==== Miscellaneous

* Fixed: Typo in the windows technique prevents the installation of updates
    (https://issues.rudder.io/issues/25254[#25254])
* Fixed: When a patch campaign starts, the first run reports missing status
    (https://issues.rudder.io/issues/25062[#25062])
* Fixed: Windows “System update” Fails
    (https://issues.rudder.io/issues/25084[#25084])
* Fixed: Add hooks support for windows
    (https://issues.rudder.io/issues/25051[#25051])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.5-1.16 (2024-07-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.4-1.15 (2024-06-20)

=== Changes


==== Miscellaneous

* Add extra informations on each Windows update when installed
    (https://issues.rudder.io/issues/24947[#24947])
* Handle new informations of package state 
    (https://issues.rudder.io/issues/25004[#25004])
* Improve understanding of filters by type
    (https://issues.rudder.io/issues/24909[#24909])

=== Bug fixes

==== Miscellaneous

* Fixed: Stack trace: Comparison method violates its general contract in SystemUpdateApi
    (https://issues.rudder.io/issues/25009[#25009])
* Fixed: System updates icons are misaligned for new result tab 
    (https://issues.rudder.io/issues/24654[#24654])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.3-1.15 (2024-06-02)

=== Changes


==== Miscellaneous

* Support daily campaigns in system update plugin
    (https://issues.rudder.io/issues/24702[#24702])
* User Rudder 8.1 CoreNodeFact in place of cache
    (https://issues.rudder.io/issues/24860[#24860])

=== Bug fixes

==== Miscellaneous

* Fixed: Incorrect template source and outpath for Windows
    (https://issues.rudder.io/issues/24950[#24950])
* Fixed: Fix inconsistencies in Linux system updates
    (https://issues.rudder.io/issues/24931[#24931])
* Fixed: Refresh button in campaign history and events does nothing
    (https://issues.rudder.io/issues/24902[#24902])
* Fixed: Nodes loading cause major browser slowdown 
    (https://issues.rudder.io/issues/23642[#23642])
* Fixed: when schedule is too short on windows, the computed start effective date is null, and so we have a nasty error
    (https://issues.rudder.io/issues/23298[#23298])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.2-1.15 (2024-04-30)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.1-1.15 (2024-04-25)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: There is no differences between a "Software update" and a "System update" campaigns creation process
    (https://issues.rudder.io/issues/24482[#24482])
* Fixed: System update plugin metadata are not available to rudder web app
    (https://issues.rudder.io/issues/24415[#24415])
* Fixed:  System updates summary has misaligned updates badges 
    (https://issues.rudder.io/issues/24697[#24697])
* Fixed: Windows download count is always multiplied by two
    (https://issues.rudder.io/issues/24716[#24716])

==== Web - UI & UX

* Fixed: Node page loads with CVE browser error depending on installed plugins
    (https://issues.rudder.io/issues/24578[#24578])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.1-1.15 (2024-04-25)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: There is no differences between a "Software update" and a "System update" campaigns creation process
    (https://issues.rudder.io/issues/24482[#24482])
* Fixed: System update plugin metadata are not available to rudder web app
    (https://issues.rudder.io/issues/24415[#24415])
* Fixed:  System updates summary has misaligned updates badges 
    (https://issues.rudder.io/issues/24697[#24697])
* Fixed: Windows download count is always multiplied by two
    (https://issues.rudder.io/issues/24716[#24716])

==== Web - UI & UX

* Fixed: Node page loads with CVE browser error depending on installed plugins
    (https://issues.rudder.io/issues/24578[#24578])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.0-1.15 (2024-04-11)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.0.rc1-1.15 (2024-04-08)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: System updates summary doesn't look good
    (https://issues.rudder.io/issues/24457[#24457])
* Fixed: System updates packages table has UI issues
    (https://issues.rudder.io/issues/24580[#24580])
* Fixed: up to date page is barely visible since update of bootstrap / css changes
    (https://issues.rudder.io/issues/24553[#24553])
* Fixed: Resize external link in system update tabe
    (https://issues.rudder.io/issues/24572[#24572])
* Fixed: we should no automatically upgrade the rudder server with patch campaign
    (https://issues.rudder.io/issues/24149[#24149])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.0.beta2-1.15 (2024-03-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Missing external link logo on system updates tab
    (https://issues.rudder.io/issues/24552[#24552])
* Fixed: Missing system update tab since css has changed 
    (https://issues.rudder.io/issues/24339[#24339])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.0.beta1-1.15 (2024-03-04)

=== Changes


==== Miscellaneous

* Add system update node details tab
    (https://issues.rudder.io/issues/24162[#24162])
* Compile css files with Sass
    (https://issues.rudder.io/issues/24092[#24092])

=== Bug fixes

==== Miscellaneous

* Fixed: When a patch campaign is running, the node list shows a warning sign
    (https://issues.rudder.io/issues/23906[#23906])
* Fixed: Fix UI issues caused by bootstrap update in system updates plugin
    (https://issues.rudder.io/issues/24240[#24240])
* Fixed: Windows system-updates skip every available updates
    (https://issues.rudder.io/issues/24237[#24237])
* Fixed: Remove duplicate css rules and update css output destination
    (https://issues.rudder.io/issues/24156[#24156])
* Fixed: All system-update files are duplicated in the embedded files.txz
    (https://issues.rudder.io/issues/24128[#24128])
* Fixed: system update plugin is broken because system-updates/system-update-schema.sql is not included
    (https://issues.rudder.io/issues/24113[#24113])

==== Web - UI & UX

* Fixed: We should not be able to access page Update campaigns with role inventory
    (https://issues.rudder.io/issues/24116[#24116])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.0.alpha1-1.13 (2024-01-19)

=== Changes


==== Miscellaneous

* Adapt license check for private plugins with nodefacts changes
    (https://issues.rudder.io/issues/24030[#24030])

=== Bug fixes

==== Miscellaneous

* Fixed: Fix UI problems in System updates plugin following the Bootstrap 5 upgrade
    (https://issues.rudder.io/issues/24002[#24002])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

