= Changelogs for Rudder plugin system-updates 8.1.\* versions

== system-updates-8.1.0.beta2-1.15 (2024-03-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Missing external link logo on system updates tab
    (https://issues.rudder.io/issues/24552[#24552])
* Fixed: Missing system update tab since css has changed 
    (https://issues.rudder.io/issues/24339[#24339])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.0.beta1-1.15 (2024-03-04)

=== Changes


==== Miscellaneous

* Add system update node details tab
    (https://issues.rudder.io/issues/24162[#24162])
* Compile css files with Sass
    (https://issues.rudder.io/issues/24092[#24092])

=== Bug fixes

==== Miscellaneous

* Fixed: When a patch campaign is running, the node list shows a warning sign
    (https://issues.rudder.io/issues/23906[#23906])
* Fixed: Fix UI issues caused by bootstrap update in system updates plugin
    (https://issues.rudder.io/issues/24240[#24240])
* Fixed: Windows system-updates skip every available updates
    (https://issues.rudder.io/issues/24237[#24237])
* Fixed: Remove duplicate css rules and update css output destination
    (https://issues.rudder.io/issues/24156[#24156])
* Fixed: All system-update files are duplicated in the embedded files.txz
    (https://issues.rudder.io/issues/24128[#24128])
* Fixed: system update plugin is broken because system-updates/system-update-schema.sql is not included
    (https://issues.rudder.io/issues/24113[#24113])

==== Web - UI & UX

* Fixed: We should not be able to access page Update campaigns with role inventory
    (https://issues.rudder.io/issues/24116[#24116])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.1.0.alpha1-1.13 (2024-01-19)

=== Changes


==== Miscellaneous

* Adapt license check for private plugins with nodefacts changes
    (https://issues.rudder.io/issues/24030[#24030])

=== Bug fixes

==== Miscellaneous

* Fixed: Fix UI problems in System updates plugin following the Bootstrap 5 upgrade
    (https://issues.rudder.io/issues/24002[#24002])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

