= Changelogs for Rudder plugin user-management 8.1.\* versions

== user-management-8.1.9-2.2 (2024-11-28)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.8-2.2 (2024-11-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.7-2.2 (2024-10-01)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: A user should not be able to delete themselves in user management
    (https://issues.rudder.io/issues/25464[#25464])
* Fixed: A users should not be able to disable themselve in user management
    (https://issues.rudder.io/issues/25454[#25454])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.6-2.2 (2024-08-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.5-2.2 (2024-07-01)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.4-2.2 (2024-06-20)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.3-2.2 (2024-06-02)

=== Changes


==== Packaging

* Add basic elm-review config - plugins
    (https://issues.rudder.io/issues/24880[#24880])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.2-2.2 (2024-04-30)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.1-2.2 (2024-04-25)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Change in rudder user details break plugin compilation
    (https://issues.rudder.io/issues/24791[#24791])
* Fixed: Editing user roles overrides tenants in rudder-users.xml file 
    (https://issues.rudder.io/issues/24690[#24690])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.1-2.2 (2024-04-25)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Editing user roles overrides tenants in rudder-users.xml file 
    (https://issues.rudder.io/issues/24690[#24690])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.0-2.2 (2024-04-11)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.0.rc1-2.2 (2024-04-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.0.beta2-2.2 (2024-03-22)

=== Changes


==== Packaging

* Add description field to plugin metadata
    (https://issues.rudder.io/issues/24477[#24477])

=== Bug fixes

==== Miscellaneous

* Fixed: Missleading placeholder for empty field value
    (https://issues.rudder.io/issues/24461[#24461])
* Fixed: Fix user-management build failure when requiring schema.sql file
    (https://issues.rudder.io/issues/24438[#24438])
* Fixed: Fix UI issues caused by bootstrap update in user-management and auth-backends plugin
    (https://issues.rudder.io/issues/24434[#24434])
* Fixed: Correct user-management build
    (https://issues.rudder.io/issues/24410[#24410])

==== Packaging

* Fixed: Remove duplicated files from some plugins
    (https://issues.rudder.io/issues/24368[#24368])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.0.beta1-2.2 (2024-03-04)

=== Changes


==== Miscellaneous

* Migrate user-management API to zio-json
    (https://issues.rudder.io/issues/24114[#24114])

==== UI - UX

* Integrate Sass with front-end development tools
    (https://issues.rudder.io/issues/24050[#24050])

=== Bug fixes

==== Miscellaneous

* Fixed: Users cards are not evenly aligned and some blank space 
    (https://issues.rudder.io/issues/24187[#24187])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.0.alpha1-2.2 (2024-01-19)

=== Changes


==== Plugins management

* license plugin checks are not building since node facts changes
    (https://issues.rudder.io/issues/24029[#24029])

=== Bug fixes

==== UI - UX

* Fixed: Fix UI problems following the Bootstrap 5 upgrade
    (https://issues.rudder.io/issues/23928[#23928])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

