= Changelogs for Rudder plugin user-management 8.1.\* versions

== user-management-8.1.0.beta1-2.2 (2024-03-04)

=== Changes


==== Miscellaneous

* Migrate user-management API to zio-json
    (https://issues.rudder.io/issues/24114[#24114])

==== UI - UX

* Integrate Sass with front-end development tools
    (https://issues.rudder.io/issues/24050[#24050])

=== Bug fixes

==== Miscellaneous

* Fixed: Users cards are not evenly aligned and some blank space 
    (https://issues.rudder.io/issues/24187[#24187])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-8.1.0.alpha1-2.2 (2024-01-19)

=== Changes


==== Plugins management

* license plugin checks are not building since node facts changes
    (https://issues.rudder.io/issues/24029[#24029])

=== Bug fixes

==== UI - UX

* Fixed: Fix UI problems following the Bootstrap 5 upgrade
    (https://issues.rudder.io/issues/23928[#23928])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

