= Change logs for Rudder 5.1

Rudder 5.1 is currently a development version of Rudder.

This page provides a summary of changes for each version. Previous beta
and rc versions are listed below for convenience.

*Warning*: The following features are now provided as plugins and no
more available as part of default Rudder installation starting from 5.0:

* LDAP-based authentication
* Relay servers
* Changes validation workflow (change requests)

If you were using them, upgrade will disable them and you will have to
install the plugin. Read the http://rudder.io/plugins[plugins page on
our website] for more information.

The initial RUDDER model consisting of a single software block which
includes all features, thus imposing a greater and greater complexity on
all of our users, has reached its limits. We have now reached a
sufficient understanding of the domain, its challenges, and the way
RUDDER is used, to make us realize that this all-in-one model is not, or
is no longer, the best suited.

*Installing, upgrading and testing*

* Install docs:
** https://docs.rudder.io/reference/5.1/installation/server/debian.html[Debian/Ubuntu]
** https://docs.rudder.io/reference/5.1/installation/server/rhel.html[RHEL/centOS]
** https://docs.rudder.io/reference/5.1/installation/server/sles.html[SLES]
* https://docs.rudder.io/reference/5.1/installation/upgrade.html[Upgrade docs]
* https://docs.rudder.io/reference/5.1/installation/versions.html#_versions[Download links]

We also recommend using the
https://github.com/Normation/rudder-vagrant[Rudder Vagrant] config if
you want a quick and easy way to get an installation for testing.

*Supported operating systems*

This version provides packages for these operating systems:

* Rudder server and Rudder relay: *Debian 9-10, RHEL/CentOS 7-8 (64 bits),
SLES 12-15, Ubuntu 16.04 LTS-18.04 LTS*
* Rudder agent: all of the above plus *Debian 8, RHEL/CentOS 6, Ubuntu 14.04 LTS*
* Rudder agent (binary packages available with a https://www.rudder.io/en/pricing/subscription/[subscription]) : *Debian 5-7, RHEL/CentOS 3-5,
SLES 10-11, Ubuntu 10.04 LTS-12.04 LTS-13.04-15.10, Windows Server 2008R2-2016, AIX
5-6-7, Slackware 14*

Read more about supported operating systems 
https://docs.rudder.io/reference/5.1/installation/operating_systems.html[in the documentation].

