= Changelogs for Rudder plugin datasources 7.2.1-2.2.\* versions

== user-management-7.2.1-2.2 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.2 series and therefore all installations of 7.2.1-2.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== notify-7.2.1-2.2 (2022-12-06)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.2.1-2.2 series and therefore all installations of 7.2.1-2.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-7.2.1-2.2 (2022-12-06)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Display an error when user try to save without rights
    (https://issues.rudder.io/issues/21504[#21504])
* Fixed: Error when trying to set default value without quotes for 404 error
    (https://issues.rudder.io/issues/21926[#21926])

=== Release notes

This is a bug fix release in the 7.2.1-2.2 series and therefore all installations of 7.2.1-2.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

