# tasks for installing Rudder Server

- include_tasks: sles.yml
  when: ansible_os_family == "Suse"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

