= Changelogs for Rudder plugin auth-backends 7.0.\* versions

== auth-backends-7.0.2-2.3 (2022-05-15)

=== Changes


==== Packaging

* Plugins package scripts should always exit on error
    (https://issues.rudder.io/issues/21008[#21008])

=== Bug fixes

==== Miscellaneous

* Fixed: Backport 21021 because same NPE happens in 6.2
    (https://issues.rudder.io/issues/21076[#21076])
* Fixed: Oauth login error are not logged
    (https://issues.rudder.io/issues/21024[#21024])
* Fixed: documentation dones't tell which provider to user of oauth2
    (https://issues.rudder.io/issues/21015[#21015])
* Fixed: Login form is not update in 7.0
    (https://issues.rudder.io/issues/21017[#21017])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.0.2-2.2 (2022-05-15)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Incorrect error of missing oauth config when the backend is disabled 
    (https://issues.rudder.io/issues/20997[#20997])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.0.2-2.1 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.0.2-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.0.1-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.0.0-2.0 (2022-05-15)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Document ldaps needs certificate added in jvm keystore
    (https://issues.rudder.io/issues/20613[#20613])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.0.0.rc3-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.0.0.rc2-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.0.0.rc1-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.0.0.beta3-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.0.0.beta2-2.0 (2022-05-15)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Auth backends does not compile in 7.0.0~beta2 
    (https://issues.rudder.io/issues/20044[#20044])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-7.0.0.beta1-2.0 (2022-05-15)

=== Changes


==== Packaging

* Use elm-0.19.1 in plugins
    (https://issues.rudder.io/issues/19696[#19696])
* Adapt rudder plugins makefile so that we make release based on new versioning scheme
    (https://issues.rudder.io/issues/18558[#18558])

=== Bug fixes

==== Miscellaneous

* Fixed: Missing dataContainer in endpoint definition
    (https://issues.rudder.io/issues/19693[#19693])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

