= Changelogs for Rudder plugin change-validation 7.0.\* versions

== change-validation-7.0.2-2.0 (2022-05-15)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Counterpart of 20734: update import for RudderUserDetails
    (https://issues.rudder.io/issues/20735[#20735])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.0.1-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.0.0-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.0.0.rc3-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.0.0.rc2-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.0.0.rc1-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.0.0.beta3-2.0 (2022-05-15)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Bad use of toString in place of serialize in change-validation
    (https://issues.rudder.io/issues/19909[#19909])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.0.0.beta2-2.0 (2022-05-15)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: adapt plugin to changes in #3783 to show directive change based on deleted technique
    (https://issues.rudder.io/issues/20087[#20087])

==== Plugins management

* Fixed: error at start of change validation plugin, datasource & create-node-api in 7.0
    (https://issues.rudder.io/issues/20040[#20040])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-7.0.0.beta1-2.0 (2022-05-15)

=== Changes


==== Packaging

* Use elm-0.19.1 in plugins
    (https://issues.rudder.io/issues/19696[#19696])
* Adapt rudder plugins makefile so that we make release based on new versionning scheme
    (https://issues.rudder.io/issues/18558[#18558])

=== Bug fixes

==== Miscellaneous

* Fixed: Change-validation not building anymore in 7.0
    (https://issues.rudder.io/issues/19701[#19701])
* Fixed: Missing dataContainer in endpoint definition
    (https://issues.rudder.io/issues/19693[#19693])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

