= Changelogs for Rudder plugin create-node-api 7.0.\* versions

== create-node-api-7.0.0.beta2-2.0 (2022-05-15)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: URL in example is invalid
    (https://issues.rudder.io/issues/20055[#20055])

==== Plugins management

* Fixed: error at start of change validation plugin, datasource & create-node-api in 7.0
    (https://issues.rudder.io/issues/20040[#20040])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== create-node-api-7.0.0.beta1-2.0 (2022-05-15)

=== Changes


==== Packaging

* Adapt rudder plugins makefile so that we make release based on new versionning scheme
    (https://issues.rudder.io/issues/18558[#18558])

=== Bug fixes

==== Miscellaneous

* Fixed: Make plugin create node API build with Rudder 7.0
    (https://issues.rudder.io/issues/19644[#19644])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

