= Changelogs for Rudder plugin cve 7.0.\* versions

== cve-7.0.0.rc1-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.0.beta3-2.0 (2022-05-15)

=== Changes


=== Bug fixes

==== Documentation

* Fixed: CVE plugin documentation misses the main title in menu
    (https://issues.rudder.io/issues/20250[#20250])

==== Miscellaneous

* Fixed: Fix typos in cve plugin
    (https://issues.rudder.io/issues/20169[#20169])
* Fixed: Add a fail-fast check when cve API is unreachable
    (https://issues.rudder.io/issues/20129[#20129])
* Fixed: CVE plugin setting documentation is not up to date
    (https://issues.rudder.io/issues/19891[#19891])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.0.beta2-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.0.beta1-2.0 (2022-05-15)

=== Changes


==== Packaging

* Use elm-0.19.1 in plugins-private
    (https://issues.rudder.io/issues/19699[#19699])

=== Bug fixes

==== Miscellaneous

* Fixed: CVE not building anymore in 7.0
    (https://issues.rudder.io/issues/19709[#19709])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

