= Changelogs for Rudder plugin cve 7.0.\* versions

== cve-7.0.2-2.2 (2022-05-15)

=== Changes


==== Miscellaneous

* Migrate to zio-json for better performance
    (https://issues.rudder.io/issues/20771[#20771])

=== Bug fixes

==== Miscellaneous

* Fixed: Optimize Request made by cve plugin
    (https://issues.rudder.io/issues/21050[#21050])
* Fixed: Nodes without vulnerabilities keep old scan result (with vulnerabilities) after check
    (https://issues.rudder.io/issues/21056[#21056])
* Fixed: Display as much data about a CVE in the cve table instead of an ugly line "We don't have data"
    (https://issues.rudder.io/issues/21057[#21057])
* Fixed: Sorting icon display is broken in the CVE table
    (https://issues.rudder.io/issues/21044[#21044])
* Fixed: Proxy url is not sanitized in plugin
    (https://issues.rudder.io/issues/20938[#20938])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.2-2.1 (2022-05-15)

=== Changes


==== Miscellaneous

* Migrate to zio-json for better performance
    (https://issues.rudder.io/issues/20771[#20771])

=== Bug fixes

==== Miscellaneous

* Fixed: Fix compilation issues and remove id from api calls
    (https://issues.rudder.io/issues/20890[#20890])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.1-2.1 (2022-05-15)

=== Changes


==== Miscellaneous

* Migrate to zio-json for better performance
    (https://issues.rudder.io/issues/20771[#20771])
* Put CVE plugin in a dedicated menu
    (https://issues.rudder.io/issues/20745[#20745])

=== Bug fixes

==== Miscellaneous

* Fixed: tests broken with because of new method in NodeInfoService
    (https://issues.rudder.io/issues/20809[#20809])
* Fixed: Incorrect name for API id "getCVEChecks"
    (https://issues.rudder.io/issues/20768[#20768])
* Fixed: Fix jawn cve
    (https://issues.rudder.io/issues/20728[#20728])
* Fixed: Update circe dependendy in cve plugin so that we fix CVE-2022-21653
    (https://issues.rudder.io/issues/20637[#20637])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.1-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.0-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.0.rc3-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.0.rc2-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.0.rc1-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.0.beta3-2.0 (2022-05-15)

=== Changes


=== Bug fixes

==== Documentation

* Fixed: CVE plugin documentation misses the main title in menu
    (https://issues.rudder.io/issues/20250[#20250])

==== Miscellaneous

* Fixed: Fix typos in cve plugin
    (https://issues.rudder.io/issues/20169[#20169])
* Fixed: Add a fail-fast check when cve API is unreachable
    (https://issues.rudder.io/issues/20129[#20129])
* Fixed: CVE plugin setting documentation is not up to date
    (https://issues.rudder.io/issues/19891[#19891])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.0.beta2-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-7.0.0.beta1-2.0 (2022-05-15)

=== Changes


==== Packaging

* Use elm-0.19.1 in plugins-private
    (https://issues.rudder.io/issues/19699[#19699])

=== Bug fixes

==== Miscellaneous

* Fixed: CVE not building anymore in 7.0
    (https://issues.rudder.io/issues/19709[#19709])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

