= Changelogs for Rudder plugin dsc 7.0.\* versions

== dsc-7.0.2-2.0 (2022-06-02)

=== Changes


==== Generic methods

* Add logs to the file_from_shared_folder method
    (https://issues.rudder.io/issues/20889[#20889])
* Result conditions should be visible in the logs
    (https://issues.rudder.io/issues/20829[#20829])

==== Techniques

* Add an option to take a local installer as source in the Windows Software technique
    (https://issues.rudder.io/issues/20893[#20893])

==== System techniques

* Agent scheduled tasks should be able to run as a specific user
    (https://issues.rudder.io/issues/20746[#20746])

==== Packaging

* Add more logs to the installer
    (https://issues.rudder.io/issues/20707[#20707])

=== Bug fixes

==== Generic methods

* Fixed: Re-use the report parameter of GM to handle the "disable reporting" from the technique editor
    (https://issues.rudder.io/issues/20959[#20959])
* Fixed: ncf methods changed signature in 7.0 in Rudder, but not in dsc, so we generate techniques with invalid parameters
    (https://issues.rudder.io/issues/20924[#20924])
* Fixed: Add loglevel parameter to each GM
    (https://issues.rudder.io/issues/20900[#20900])
* Fixed:  DSC methods generate incorrect result conditions when using a custom component name 
    (https://issues.rudder.io/issues/20830[#20830])

==== Miscellaneous

* Fixed: Use report instead of loglevel
    (https://issues.rudder.io/issues/20956[#20956])
* Fixed: Unecessary curl options are passed to the File-From-Http-Server method
    (https://issues.rudder.io/issues/20799[#20799])

==== Techniques

* Fixed: File download Rudder server technique don't work with Rudder 7.0
    (https://issues.rudder.io/issues/20906[#20906])
* Fixed: windows update technique fails to list updates
    (https://issues.rudder.io/issues/20783[#20783])
* Fixed: cumulative update fail to download
    (https://issues.rudder.io/issues/20648[#20648])

==== Misc

* Fixed: Broken tests in 7.0+
    (https://issues.rudder.io/issues/20920[#20920])

==== System techniques

* Fixed: Fix some typos from previous merge
    (https://issues.rudder.io/issues/20895[#20895])
* Fixed: unexpected reports on system technique in 6.2
    (https://issues.rudder.io/issues/20822[#20822])

==== Packaging

* Fixed: Embedded curl does not use the windows system CA store
    (https://issues.rudder.io/issues/20818[#20818])
* Fixed: Sometimes the installer does not correctly write policy-server.conf
    (https://issues.rudder.io/issues/20821[#20821])

==== Inventory

* Fixed: Add a possibility to ignore some specific env variable before the inventory run
    (https://issues.rudder.io/issues/20765[#20765])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.1-2.0 (2022-06-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0-2.0 (2022-06-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.rc3-2.0 (2022-06-02)

=== Changes


==== Techniques

*  Create an update windows technique
    (https://issues.rudder.io/issues/20438[#20438])

==== Generic methods

* Add a simple lib to handle persistent conditions
    (https://issues.rudder.io/issues/20363[#20363])

=== Bug fixes

==== Packaging

* Fixed: missing dependency on zip in metadata
    (https://issues.rudder.io/issues/20270[#20270])

==== Generic methods

* Fixed: package windows method fails to set the auto upgrade option
    (https://issues.rudder.io/issues/20433[#20433])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.rc2-2.0 (2022-06-02)

=== Changes


==== ci

* Add linter for the techniques files
    (https://issues.rudder.io/issues/20358[#20358])
* Dockerify the qa tests
    (https://issues.rudder.io/issues/20357[#20357])

=== Bug fixes

==== Packaging

* Fixed: Unexpected exceptions in the agent output
    (https://issues.rudder.io/issues/20347[#20347])
* Fixed: Postinst should not dump non-error error messages
    (https://issues.rudder.io/issues/20345[#20345])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.rc1-2.0 (2022-06-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.beta3-2.0 (2022-06-02)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Dsc-common techniques are not package correctly
    (https://issues.rudder.io/issues/20079[#20079])

==== CLI

* Fixed: Reports are not alligned when displayed
    (https://issues.rudder.io/issues/20213[#20213])

==== Generic methods

* Fixed: Unformatted log messages in _check_compliance function
    (https://issues.rudder.io/issues/20206[#20206])
* Fixed: Agent does not accept empty class expressions
    (https://issues.rudder.io/issues/20205[#20205])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.beta2-2.0 (2022-06-02)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Dsc-common techniques are not package correctly
    (https://issues.rudder.io/issues/20079[#20079])
* Fixed: Missing dependencies in the agent
    (https://issues.rudder.io/issues/20084[#20084])

==== Generic methods

* Fixed: Dsc apply does not respect the 7.0 resource_state naming
    (https://issues.rudder.io/issues/20131[#20131])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.beta1-2.0 (2022-06-02)

=== Changes


==== Packaging

* Move dsc plugin into plugins repository
    (https://issues.rudder.io/issues/19922[#19922])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

