= Changelogs for Rudder plugin dsc 7.0.\* versions

== dsc-7.0.0.beta2-2.0 (2022-06-02)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Dsc-common techniques are not package correctly
    (https://issues.rudder.io/issues/20079[#20079])
* Fixed: Missing dependencies in the agent
    (https://issues.rudder.io/issues/20084[#20084])

==== Generic methods

* Fixed: Dsc apply does not respect the 7.0 resource_state naming
    (https://issues.rudder.io/issues/20131[#20131])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.beta1-2.0 (2022-06-02)

=== Changes


==== Packaging

* Move dsc plugin into plugins repository
    (https://issues.rudder.io/issues/19922[#19922])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

