= Changelogs for Rudder plugin dsc 7.0.\* versions

== dsc-7.0.1-2.0 (2022-06-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0-2.0 (2022-06-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.rc3-2.0 (2022-06-02)

=== Changes


==== Techniques

*  Create an update windows technique
    (https://issues.rudder.io/issues/20438[#20438])

==== Generic methods

* Add a simple lib to handle persistent conditions
    (https://issues.rudder.io/issues/20363[#20363])

=== Bug fixes

==== Packaging

* Fixed: missing dependency on zip in metadata
    (https://issues.rudder.io/issues/20270[#20270])

==== Generic methods

* Fixed: package windows method fails to set the auto upgrade option
    (https://issues.rudder.io/issues/20433[#20433])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.rc2-2.0 (2022-06-02)

=== Changes


==== ci

* Add linter for the techniques files
    (https://issues.rudder.io/issues/20358[#20358])
* Dockerify the qa tests
    (https://issues.rudder.io/issues/20357[#20357])

=== Bug fixes

==== Packaging

* Fixed: Unexpected exceptions in the agent output
    (https://issues.rudder.io/issues/20347[#20347])
* Fixed: Postinst should not dump non-error error messages
    (https://issues.rudder.io/issues/20345[#20345])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.rc1-2.0 (2022-06-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.beta3-2.0 (2022-06-02)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Dsc-common techniques are not package correctly
    (https://issues.rudder.io/issues/20079[#20079])

==== CLI

* Fixed: Reports are not alligned when displayed
    (https://issues.rudder.io/issues/20213[#20213])

==== Generic methods

* Fixed: Unformatted log messages in _check_compliance function
    (https://issues.rudder.io/issues/20206[#20206])
* Fixed: Agent does not accept empty class expressions
    (https://issues.rudder.io/issues/20205[#20205])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.beta2-2.0 (2022-06-02)

=== Changes


=== Bug fixes

==== Packaging

* Fixed: Dsc-common techniques are not package correctly
    (https://issues.rudder.io/issues/20079[#20079])
* Fixed: Missing dependencies in the agent
    (https://issues.rudder.io/issues/20084[#20084])

==== Generic methods

* Fixed: Dsc apply does not respect the 7.0 resource_state naming
    (https://issues.rudder.io/issues/20131[#20131])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-7.0.0.beta1-2.0 (2022-06-02)

=== Changes


==== Packaging

* Move dsc plugin into plugins repository
    (https://issues.rudder.io/issues/19922[#19922])

=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

