= Changelogs for Rudder plugin reporting 7.0.\* versions

== reporting-7.0.0.rc1-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-7.0.0.beta3-2.0 (2022-05-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-7.0.0.beta2-2.0 (2022-05-15)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Plugin does not compile in 7.0.0~beta2
    (https://issues.rudder.io/issues/20050[#20050])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== reporting-7.0.0.beta1-2.0 (2022-05-15)

=== Changes


==== Packaging

* Use elm-0.19.1 in plugins-private
    (https://issues.rudder.io/issues/19699[#19699])
* Add CI checks to plugins-private
    (https://issues.rudder.io/issues/19434[#19434])

=== Bug fixes

==== Miscellaneous

* Fixed: Reporting plugin not building anymore in 7.0
    (https://issues.rudder.io/issues/19711[#19711])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

