= Changelogs for Rudder plugin secret-management 7.0.\* versions

== secret-management-7.0.0.beta3-1.0 (2022-06-03)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Remove postinst script to let the plugin handle the init
    (https://issues.rudder.io/issues/20138[#20138])
* Fixed: Postinst script is not moving the init file of secrets
    (https://issues.rudder.io/issues/20089[#20089])
* Fixed: Modify documentation to the new engine format
    (https://issues.rudder.io/issues/19945[#19945])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.0.0.beta2-1.0 (2022-06-03)

=== Changes


==== Miscellaneous

* Secret management feature
    (https://issues.rudder.io/issues/19592[#19592])

=== Bug fixes

==== Miscellaneous

* Fixed: Explain in the docs that the value will likely appear in the reports for now
    (https://issues.rudder.io/issues/20147[#20147])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

