= Changelogs for Rudder plugin secret-management 7.0.\* versions

== secret-management-7.0.3-1.0 (2022-06-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.0.2-1.0 (2022-06-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.0.1-1.0 (2022-06-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.0.0-1.0 (2022-06-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.0.0.rc3-1.0 (2022-06-03)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Restrict permissions on directory and secret file
    (https://issues.rudder.io/issues/20461[#20461])
* Fixed: When upgrading plugin secret-management, all secrets are lost
    (https://issues.rudder.io/issues/20458[#20458])
* Fixed: Make it clear that secret are not usable in technique editor
    (https://issues.rudder.io/issues/20411[#20411])
* Fixed: Secret management does not work
    (https://issues.rudder.io/issues/20400[#20400])

==== Documentation

* Fixed: Fix typos in plugins
    (https://issues.rudder.io/issues/20371[#20371])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.0.0.rc2-1.0 (2022-06-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.0.0.rc1-1.0 (2022-06-03)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Add tests for API service
    (https://issues.rudder.io/issues/20217[#20217])
* Fixed: The secrets page should be in the "Configuration Management" part of the menu
    (https://issues.rudder.io/issues/20180[#20180])
* Fixed: Only display description once in the secrets page
    (https://issues.rudder.io/issues/20176[#20176])
* Fixed: The page information should explain how to use secrets
    (https://issues.rudder.io/issues/20177[#20177])
* Fixed: Secret names should have the same constraints as property name
    (https://issues.rudder.io/issues/20178[#20178])
* Fixed: When editing a variable the current descritpion should be kept
    (https://issues.rudder.io/issues/20175[#20175])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.0.0.beta3-1.0 (2022-06-03)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Remove postinst script to let the plugin handle the init
    (https://issues.rudder.io/issues/20138[#20138])
* Fixed: Postinst script is not moving the init file of secrets
    (https://issues.rudder.io/issues/20089[#20089])
* Fixed: Modify documentation to the new engine format
    (https://issues.rudder.io/issues/19945[#19945])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== secret-management-7.0.0.beta2-1.0 (2022-06-03)

=== Changes


==== Miscellaneous

* Secret management feature
    (https://issues.rudder.io/issues/19592[#19592])

=== Bug fixes

==== Miscellaneous

* Fixed: Explain in the docs that the value will likely appear in the reports for now
    (https://issues.rudder.io/issues/20147[#20147])

=== Release notes

This is a bug fix release in the 7.0 series and therefore all installations of 7.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

