= Changelogs for Rudder plugin auth-backends 9.0.\* versions

== auth-backends-9.0.0.beta1-2.7 (2025-09-09)

=== Changes


=== Bug fixes

==== Documentation

* Fixed: How to configure a proxy for SSO feaure
    (https://issues.rudder.io/issues/27320[#27320])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-9.0.0.alpha1-2.7 (2025-07-24)

=== Changes


==== Plugins management

* Update plugins parent pom to use scala 3
    (https://issues.rudder.io/issues/27032[#27032])

=== Bug fixes

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

