= Changelogs for Rudder plugin benchmark-cis-debian-12 9.0.\* versions

== benchmark-cis-debian-12-9.0.0-0.10 (2025-10-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: CIS - Debian 12 - Adapt Section 1
    (https://issues.rudder.io/issues/27415[#27415])
* Fixed: CIS - Debian 12 - Adapt Section 5
    (https://issues.rudder.io/issues/27419[#27419])
* Fixed: CIS - Debian 12 - Adapt Section 6
    (https://issues.rudder.io/issues/27420[#27420])
* Fixed: There are some "null" in the bench descriptions
    (https://issues.rudder.io/issues/27583[#27583])
* Fixed: CIS Debian 11 : “5.4.2.2 - Ensure root is the only GID 0 account” audit results incorrect
    (https://issues.rudder.io/issues/27499[#27499])
* Fixed: CIS Debian 11 : “5.4.1.4 Ensure strong password hashing algorithm is configured” Parameter list value selector incorrect
    (https://issues.rudder.io/issues/27516[#27516])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-debian-12-9.0.0.beta1-0.10 (2025-09-09)

=== Changes


==== Miscellaneous

* Benchmark CIS Debian 12 v1.1.0
    (https://issues.rudder.io/issues/27482[#27482])

=== Bug fixes

==== Miscellaneous

* Fixed: Create structure for Debian 12 benchmark
    (https://issues.rudder.io/issues/27414[#27414])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

