= Changelogs for Rudder plugin benchmark-cis-rhel-9 9.0.\* versions

== benchmark-cis-rhel-9-9.0.4-0.10 (2026-02-16)

=== Changes


==== Miscellaneous

* Refactor control point file key value and service restart
    (https://issues.rudder.io/issues/28016[#28016])

=== Bug fixes

==== Miscellaneous

* Fixed: CIS : rudder_syctl_file is not defined for the benchmark
    (https://issues.rudder.io/issues/28192[#28192])
* Fixed: Debian 12 : path for resource calling is not correct
    (https://issues.rudder.io/issues/28193[#28193])
* Fixed: Uninstall on benchmarks failed due to permission denied on prerm script
    (https://issues.rudder.io/issues/28045[#28045])
* Fixed: Remove CIS mention in category.xml and control.yml
    (https://issues.rudder.io/issues/28146[#28146])
* Fixed: Update rudderc dependency in 9.0
    (https://issues.rudder.io/issues/28121[#28121])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-9-9.0.3-0.10 (2025-12-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: There are still some mention to CIS in the benchmarks
    (https://issues.rudder.io/issues/28043[#28043])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-9-9.0.2-0.10 (2025-12-10)

=== Changes


==== Miscellaneous

* Refactor all bash script call
    (https://issues.rudder.io/issues/27994[#27994])
* Add lib for augeas methods and implement it in all benchmarks
    (https://issues.rudder.io/issues/27761[#27761])
* Add new CIS fields and display them in right part (sharing space with documentation)
    (https://issues.rudder.io/issues/27868[#27868])

=== Bug fixes

==== Miscellaneous

* Fixed: CIS RHEL 9 Section 2.1.21 produces an error if Postfix is not installed
    (https://issues.rudder.io/issues/27832[#27832])
* Fixed: Changes on whitespace semantic breaks benchmarks
    (https://issues.rudder.io/issues/27936[#27936])
* Fixed: CIS RHEL 9 Section 4.3.3 Wrong test
    (https://issues.rudder.io/issues/27896[#27896])
* Fixed: CIS RHEL 9 Section 1.4.1 : Section shows wrong subtitle
    (https://issues.rudder.io/issues/27830[#27830])
* Fixed: CIS RHEL 9 Section 5.3.3.2.6 : 1st test is reversed
    (https://issues.rudder.io/issues/27854[#27854])
* Fixed: Postint should create  /var/rudder/plugins/security-benchmarks/install otherwise rsync may fails
    (https://issues.rudder.io/issues/27794[#27794])
* Fixed: Rename the benchmarks RHEL 8, Debian 11, Debian 12 and Ubuntu 22 to remove CIS
    (https://issues.rudder.io/issues/27806[#27806])
* Fixed: CIS RHEL 9 Section 5.3.3.2.6 : Incorrect numbering
    (https://issues.rudder.io/issues/27853[#27853])
* Fixed: CIS RHEL 9 Section 6.1.3 : Incorrect path harcoded in our test, may vary on actual target systems
    (https://issues.rudder.io/issues/27847[#27847])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-9-9.0.1-0.10 (2025-11-19)

=== Changes


==== Miscellaneous

* Allow fields to have no policy mode (only disabled) and display Manual and Unimplemented tags
    (https://issues.rudder.io/issues/27714[#27714])

=== Bug fixes

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-9-9.0.0-0.10 (2025-10-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-9-9.0.0.rc1-0.10 (2025-10-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-9-9.0.0.beta2-0.10 (2025-10-07)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Make RHEL8, RHEL9 and Debian11 plugin available
    (https://issues.rudder.io/issues/27629[#27629])
* Fixed: RHEL 9 - Section 6.2.2.2 checks only /etc/systemd/journald.conf
    (https://issues.rudder.io/issues/27512[#27512])
* Fixed: RHEL 9 - Section 4.3.3 and 4.3.4 are compliant even if nftable is not present
    (https://issues.rudder.io/issues/27509[#27509])
* Fixed: There are some "null" in the bench descriptions
    (https://issues.rudder.io/issues/27583[#27583])
* Fixed: RHEL 9 - Section 6.2.4.1, 7.1.11 and 7.1.12 , 7.2.8 and 7.2.9 are not implemented, but we don't document why
    (https://issues.rudder.io/issues/27513[#27513])
* Fixed: RHEL 9 - Section 1.8.10 reports an error even if gdm is not there
    (https://issues.rudder.io/issues/27507[#27507])
* Fixed: RHEL 9 - selinux check missing
    (https://issues.rudder.io/issues/27505[#27505])
* Fixed: CIS Debian 11 : “5.4.2.2 - Ensure root is the only GID 0 account” audit results incorrect
    (https://issues.rudder.io/issues/27499[#27499])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-9-9.0.0.beta1-0.10 (2025-09-09)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: RHEL 9 - 5.4.1.6 - test command is invalid
    (https://issues.rudder.io/issues/27510[#27510])
* Fixed: RHEL 9 - Section 3.1.2 - wrong path for resources_dir
    (https://issues.rudder.io/issues/27508[#27508])
* Fixed: CIS RHEL 9 : missing tree on control points v2
    (https://issues.rudder.io/issues/27493[#27493])
* Fixed: CIS RHEL 9 : Fix tree on Sections
    (https://issues.rudder.io/issues/27485[#27485])
* Fixed: CIS : Fix titles, description and documentation on RHEL 9
    (https://issues.rudder.io/issues/27483[#27483])
* Fixed: CIS : Fix titles, description and documentation on RHEL 9
    (https://issues.rudder.io/issues/27483[#27483])
* Fixed: CIS - Debian 11 - Implement Section 4
    (https://issues.rudder.io/issues/27408[#27408])
* Fixed: CIS RHEL 8 Section 1.1.1.1 compliant code is reversed
    (https://issues.rudder.io/issues/27357[#27357])
* Fixed: multiple missing bash for calling ressources script
    (https://issues.rudder.io/issues/27355[#27355])
* Fixed: RHEL 8 - Section 4.2 : missing const.dollar & fixes
    (https://issues.rudder.io/issues/27340[#27340])
* Fixed: RHEL 8 - Section 2.2 : inversion of key / value & fixes
    (https://issues.rudder.io/issues/27342[#27342])
* Fixed: Script 6_2_4_UIDs_consistency.sh, 6_2_5_GIDs_consistency.sh, 6_2_6_username_consistency.sh, 6_2_7_groupname_consistency.sh exit 0 even when it should node
    (https://issues.rudder.io/issues/27350[#27350])
* Fixed: RHEL 8 - Section 6.2 - Local group & group settings
    (https://issues.rudder.io/issues/27225[#27225])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

