= Changelogs for Rudder plugin benchmark-cis-debian-12 9.0.\* versions

== benchmark-cis-debian-12-9.0.3-0.10 (2025-12-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: There are still some mention to CIS in the benchmarks
    (https://issues.rudder.io/issues/28043[#28043])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-debian-12-9.0.2-0.10 (2025-12-10)

=== Changes


==== Miscellaneous

* Refactor all bash script call
    (https://issues.rudder.io/issues/27994[#27994])
* Add lib for augeas methods and implement it in all benchmarks
    (https://issues.rudder.io/issues/27761[#27761])
* Refactoring level 2 controls point in kcllib
    (https://issues.rudder.io/issues/27764[#27764])
* Add new CIS fields and display them in right part (sharing space with documentation)
    (https://issues.rudder.io/issues/27868[#27868])

=== Bug fixes

==== Miscellaneous

* Fixed: Changes on whitespace semantic breaks benchmarks
    (https://issues.rudder.io/issues/27936[#27936])
* Fixed: CIS RHEL 9 Section 5.3.3.2.6 : 1st test is reversed
    (https://issues.rudder.io/issues/27854[#27854])
* Fixed: Postint should create  /var/rudder/plugins/security-benchmarks/install otherwise rsync may fails
    (https://issues.rudder.io/issues/27794[#27794])
* Fixed: Rename the benchmarks RHEL 8, Debian 11, Debian 12 and Ubuntu 22 to remove CIS
    (https://issues.rudder.io/issues/27806[#27806])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-debian-12-9.0.1-0.10 (2025-11-19)

=== Changes


==== Miscellaneous

* Allow fields to have no policy mode (only disabled) and display Manual and Unimplemented tags
    (https://issues.rudder.io/issues/27714[#27714])

=== Bug fixes

==== Miscellaneous

* Fixed: CIS - Debian 12 - Adapt Section 4
    (https://issues.rudder.io/issues/27418[#27418])
* Fixed: CIS - Debian 12 - Adapt Section 2
    (https://issues.rudder.io/issues/27416[#27416])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-debian-12-9.0.0-0.10 (2025-10-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: CIS - Debian 12 - Adapt Section 1
    (https://issues.rudder.io/issues/27415[#27415])
* Fixed: CIS - Debian 12 - Adapt Section 5
    (https://issues.rudder.io/issues/27419[#27419])
* Fixed: CIS - Debian 12 - Adapt Section 6
    (https://issues.rudder.io/issues/27420[#27420])
* Fixed: There are some "null" in the bench descriptions
    (https://issues.rudder.io/issues/27583[#27583])
* Fixed: CIS Debian 11 : “5.4.2.2 - Ensure root is the only GID 0 account” audit results incorrect
    (https://issues.rudder.io/issues/27499[#27499])
* Fixed: CIS Debian 11 : “5.4.1.4 Ensure strong password hashing algorithm is configured” Parameter list value selector incorrect
    (https://issues.rudder.io/issues/27516[#27516])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-debian-12-9.0.0.beta1-0.10 (2025-09-09)

=== Changes


==== Miscellaneous

* Benchmark CIS Debian 12 v1.1.0
    (https://issues.rudder.io/issues/27482[#27482])

=== Bug fixes

==== Miscellaneous

* Fixed: Create structure for Debian 12 benchmark
    (https://issues.rudder.io/issues/27414[#27414])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

