= Changelogs for Rudder plugin benchmark-cis-rhel-9 9.0.\* versions

== benchmark-cis-rhel-9-9.0.0-0.10 (2025-10-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-9-9.0.0.rc1-0.10 (2025-10-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-9-9.0.0.beta2-0.10 (2025-10-07)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Make RHEL8, RHEL9 and Debian11 plugin available
    (https://issues.rudder.io/issues/27629[#27629])
* Fixed: RHEL 9 - Section 6.2.2.2 checks only /etc/systemd/journald.conf
    (https://issues.rudder.io/issues/27512[#27512])
* Fixed: RHEL 9 - Section 4.3.3 and 4.3.4 are compliant even if nftable is not present
    (https://issues.rudder.io/issues/27509[#27509])
* Fixed: There are some "null" in the bench descriptions
    (https://issues.rudder.io/issues/27583[#27583])
* Fixed: RHEL 9 - Section 6.2.4.1, 7.1.11 and 7.1.12 , 7.2.8 and 7.2.9 are not implemented, but we don't document why
    (https://issues.rudder.io/issues/27513[#27513])
* Fixed: RHEL 9 - Section 1.8.10 reports an error even if gdm is not there
    (https://issues.rudder.io/issues/27507[#27507])
* Fixed: RHEL 9 - selinux check missing
    (https://issues.rudder.io/issues/27505[#27505])
* Fixed: CIS Debian 11 : “5.4.2.2 - Ensure root is the only GID 0 account” audit results incorrect
    (https://issues.rudder.io/issues/27499[#27499])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-9-9.0.0.beta1-0.10 (2025-09-09)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: RHEL 9 - 5.4.1.6 - test command is invalid
    (https://issues.rudder.io/issues/27510[#27510])
* Fixed: RHEL 9 - Section 3.1.2 - wrong path for resources_dir
    (https://issues.rudder.io/issues/27508[#27508])
* Fixed: CIS RHEL 9 : missing tree on control points v2
    (https://issues.rudder.io/issues/27493[#27493])
* Fixed: CIS RHEL 9 : Fix tree on Sections
    (https://issues.rudder.io/issues/27485[#27485])
* Fixed: CIS : Fix titles, description and documentation on RHEL 9
    (https://issues.rudder.io/issues/27483[#27483])
* Fixed: CIS : Fix titles, description and documentation on RHEL 9
    (https://issues.rudder.io/issues/27483[#27483])
* Fixed: CIS - Debian 11 - Implement Section 4
    (https://issues.rudder.io/issues/27408[#27408])
* Fixed: CIS RHEL 8 Section 1.1.1.1 compliant code is reversed
    (https://issues.rudder.io/issues/27357[#27357])
* Fixed: multiple missing bash for calling ressources script
    (https://issues.rudder.io/issues/27355[#27355])
* Fixed: RHEL 8 - Section 4.2 : missing const.dollar & fixes
    (https://issues.rudder.io/issues/27340[#27340])
* Fixed: RHEL 8 - Section 2.2 : inversion of key / value & fixes
    (https://issues.rudder.io/issues/27342[#27342])
* Fixed: Script 6_2_4_UIDs_consistency.sh, 6_2_5_GIDs_consistency.sh, 6_2_6_username_consistency.sh, 6_2_7_groupname_consistency.sh exit 0 even when it should node
    (https://issues.rudder.io/issues/27350[#27350])
* Fixed: RHEL 8 - Section 6.2 - Local group & group settings
    (https://issues.rudder.io/issues/27225[#27225])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

