= Changelogs for Rudder plugin change-validation 9.0.\* versions

== change-validation-9.0.0-2.4 (2025-10-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-9.0.0.rc2-2.4 (2025-10-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-9.0.0.rc1-2.4 (2025-10-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-9.0.0.beta2-2.4 (2025-10-07)

=== Changes


==== Miscellaneous

* Change request details history is not updated when updating via API
    (https://issues.rudder.io/issues/27043[#27043])

=== Bug fixes

==== Miscellaneous

* Fixed: Technique editor tree panel is broken when plugin is installed
    (https://issues.rudder.io/issues/27589[#27589])
* Fixed: Change request counts are loading even if the plugin is disabled
    (https://issues.rudder.io/issues/27581[#27581])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-9.0.0.beta1-2.4 (2025-09-09)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Change validation acceptation and decline endpoints fail with permission issues
    (https://issues.rudder.io/issues/27085[#27085])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-9.0.0.alpha1-2.4 (2025-07-24)

=== Changes


==== Plugins management

* Update plugins parent pom to use scala 3
    (https://issues.rudder.io/issues/27032[#27032])

==== Miscellaneous

* Add the 'Validate All' check box to the WorkflowUsers Elm app
    (https://issues.rudder.io/issues/26946[#26946])
* Rewrite WorkflowInformation navigation bar in Elm
    (https://issues.rudder.io/issues/26788[#26788])
* Refactoring : use ZIO instead of Box in change-validation snippets
    (https://issues.rudder.io/issues/26775[#26775])
* Add a new internal endpoint in order to replace WorkflowInformation
    (https://issues.rudder.io/issues/26760[#26760])
* Refactoring of ValidationNeeded class : replace type Box with IOResult
    (https://issues.rudder.io/issues/26698[#26698])

==== Refactoring

* WoChangeRequestJdbcRepository#updateChangeRequest executes several transactions
    (https://issues.rudder.io/issues/26770[#26770])

=== Bug fixes

==== Miscellaneous

* Fixed: Change request page is not updated directly after using the form to edit the title/description 
    (https://issues.rudder.io/issues/27289[#27289])
* Fixed: ChangeRequestJdbcRepository ignores error when change request unserialization fails
    (https://issues.rudder.io/issues/26953[#26953])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

