= Changelogs for Rudder plugin cve 9.0.\* versions

== cve-9.0.0.beta2-2.12 (2025-10-07)

=== Changes


==== Miscellaneous

* CVE: Update CVE details | 'Start update' button shows an error
    (https://issues.rudder.io/issues/27491[#27491])
* CVE: Update CVE details | 'Start update' button shows an error
    (https://issues.rudder.io/issues/27491[#27491])

=== Bug fixes

==== UI - UX

* Fixed: Nodes tabs in plugins are causing CSP errors  
    (https://issues.rudder.io/issues/27576[#27576])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-9.0.0.beta1-2.12 (2025-09-09)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Spaces at the end of the line proxy_url break the parsing of proxy url/port
    (https://issues.rudder.io/issues/27488[#27488])
* Fixed: Inventory is emptied when a node is updated for cve groups (added or removed property)
    (https://issues.rudder.io/issues/27475[#27475])
* Fixed: Inventory is emptied when a node is updated for cve groups (added or removed property)
    (https://issues.rudder.io/issues/27475[#27475])
* Fixed: Vuls need sources packages as separated data for all packages now.
    (https://issues.rudder.io/issues/27460[#27460])
* Fixed: Vuls need sources packages as separated data for all packages now.
    (https://issues.rudder.io/issues/27460[#27460])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-9.0.0.alpha1-2.10 (2025-07-24)

=== Changes


==== Miscellaneous

* Add filter for groups in cve vulnerabilities page
    (https://issues.rudder.io/issues/27209[#27209])

=== Bug fixes

==== Miscellaneous

* Fixed:  CVE last check API upmerge of tests make build fail in 9.0
    (https://issues.rudder.io/issues/27313[#27313])
* Fixed: CVE plugin not compiling in 9.0
    (https://issues.rudder.io/issues/26982[#26982])

==== Architecture - Code maintenance

* Fixed: CVE last check API tests are failing
    (https://issues.rudder.io/issues/27297[#27297])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

