= Changelogs for Rudder plugin security-benchmarks 9.0.\* versions

== security-benchmarks-9.0.0-1.2 (2025-10-24)

=== Changes


==== Miscellaneous

* Remove beta tag
    (https://issues.rudder.io/issues/27768[#27768])
* Allow fields to have no policy mode (only disabled) and display Manual and Unimplemented tags
    (https://issues.rudder.io/issues/27714[#27714])
* Make the parameter list display more compact
    (https://issues.rudder.io/issues/27736[#27736])

=== Bug fixes

==== Miscellaneous

* Fixed: The arrows in security benchmarks Score details don't point down when the menu is extended
    (https://issues.rudder.io/issues/27735[#27735])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-9.0.0-1.1 (2025-10-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-9.0.0.rc1-1.1 (2025-10-13)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: After overloading one time, can't apply via global parameter anymore
    (https://issues.rudder.io/issues/27579[#27579])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-9.0.0.beta2-1.1 (2025-10-07)

=== Changes


==== Miscellaneous

* Bootstrap security benchmark documentation
    (https://issues.rudder.io/issues/27593[#27593])
* User should not be able to select system groups as targets
    (https://issues.rudder.io/issues/27349[#27349])

=== Bug fixes

==== Miscellaneous

* Fixed: "No data available" at some level of benchmark for items, not for node
    (https://issues.rudder.io/issues/27656[#27656])
* Fixed: fix typo in readme
    (https://issues.rudder.io/issues/27637[#27637])
* Fixed: Balance score computation on a more optimistic basis
    (https://issues.rudder.io/issues/27582[#27582])
* Fixed: There are some "null" in the bench descriptions
    (https://issues.rudder.io/issues/27583[#27583])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-9.0.0.beta1-1.1 (2025-09-09)

=== Changes


==== Miscellaneous

* No Answer nodes should be ignored in benchmark score, missing reports message improvement
    (https://issues.rudder.io/issues/27495[#27495])
* Add a validation when changing checks to enforce 
    (https://issues.rudder.io/issues/27262[#27262])
* Enforce a precise kcl version
    (https://issues.rudder.io/issues/27377[#27377])
* Add links between the dashboard and the score details tab
    (https://issues.rudder.io/issues/27378[#27378])
* Add filters to score details
    (https://issues.rudder.io/issues/27351[#27351])
* Add a confirmation step before deleting a benchmark
    (https://issues.rudder.io/issues/27361[#27361])
* Improve display of sub items in node score details
    (https://issues.rudder.io/issues/27332[#27332])
* Improve benchmark dashboard
    (https://issues.rudder.io/issues/27312[#27312])

=== Bug fixes

==== Miscellaneous

* Fixed: Score computation rules need adjustments
    (https://issues.rudder.io/issues/27403[#27403])
* Fixed: Order of control points in nodes reporting is not correct
    (https://issues.rudder.io/issues/27288[#27288])
* Fixed: Multiplication of rudder_auto_conditions
    (https://issues.rudder.io/issues/27334[#27334])
* Fixed: Scores shown missing reports for reports that are no longer expected
    (https://issues.rudder.io/issues/27280[#27280])
* Fixed: When selecting Targets, the filter search does not filter anything
    (https://issues.rudder.io/issues/26471[#26471])
* Fixed: Score computation takes disabled sections into account
    (https://issues.rudder.io/issues/27380[#27380])
* Fixed: Create documentation on how the benchmark are created/built/tested
    (https://issues.rudder.io/issues/27376[#27376])
* Fixed: Setting section to enforce change checks that only have audit/disable as existing states
    (https://issues.rudder.io/issues/27347[#27347])
* Fixed: multiple missing bash for calling ressources script
    (https://issues.rudder.io/issues/27355[#27355])
* Fixed: Use new charting.js file instead of homepage.js
    (https://issues.rudder.io/issues/27330[#27330])
* Fixed: Chart is not updated when new score is fetched from the API
    (https://issues.rudder.io/issues/27335[#27335])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-9.0.0.alpha1-1.1 (2025-07-24)

=== Changes


==== Miscellaneous

* Turn the Summary tab into a dashboard view
    (https://issues.rudder.io/issues/27257[#27257])

=== Bug fixes

==== Miscellaneous

* Fixed: metadata.json generated is incomplete
    (https://issues.rudder.io/issues/27291[#27291])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

