= Changelogs for Rudder plugin system-updates 9.0.\* versions

== system-updates-9.0.0-1.18 (2025-10-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Formatting of python code fails with blue
    (https://issues.rudder.io/issues/27718[#27718])
* Fixed: Generation error on migration hook due to duplicated bundle name
    (https://issues.rudder.io/issues/27655[#27655])
* Fixed: Change bandit version in requirements.txt to fix tests
    (https://issues.rudder.io/issues/27496[#27496])
* Fixed: Incorrect relative path of Json file in the Software Update campaign type
    (https://issues.rudder.io/issues/27465[#27465])

==== UI - UX

* Fixed: Nodes tabs in plugins are causing CSP errors  
    (https://issues.rudder.io/issues/27576[#27576])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-9.0.0-1.17 (2025-10-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-9.0.0.rc2-1.18 (2025-10-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-9.0.0.rc1-1.18 (2025-10-13)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Formatting of python code fails with blue
    (https://issues.rudder.io/issues/27718[#27718])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-9.0.0.beta2-1.18 (2025-10-07)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Generation error on migration hook due to duplicated bundle name
    (https://issues.rudder.io/issues/27655[#27655])

==== UI - UX

* Fixed: Nodes tabs in plugins are causing CSP errors  
    (https://issues.rudder.io/issues/27576[#27576])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-9.0.0.beta1-1.18 (2025-09-09)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Change bandit version in requirements.txt to fix tests
    (https://issues.rudder.io/issues/27496[#27496])
* Fixed: Incorrect relative path of Json file in the Software Update campaign type
    (https://issues.rudder.io/issues/27465[#27465])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-9.0.0.alpha1-1.17 (2025-07-24)

=== Changes


==== Miscellaneous

* Move system update hooks out of /var
    (https://issues.rudder.io/issues/27116[#27116])

=== Bug fixes

==== Miscellaneous

* Fixed: System updates plugin not compiling in 9.0
    (https://issues.rudder.io/issues/27003[#27003])

=== Release notes

This is a bug fix release in the 9.0 series and therefore all installations of 9.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

