= Changelogs for Rudder plugin change-validation 6.1.\* versions

== change-validation-6.1-1.10 (2021-06-07)

=== Changes


==== Packaging

* Use https repos in maven config
    (https://issues.rudder.io/issues/19165[#19165])

=== Bug fixes

==== Miscellaneous

* Fixed: Illegal address when no replyTo configured
    (https://issues.rudder.io/issues/19352[#19352])
* Fixed: Email notification should be disabled when no host server is configured
    (https://issues.rudder.io/issues/19147[#19147])
* Fixed: Parsing error when the port is undefined in change-validation.conf
    (https://issues.rudder.io/issues/19148[#19148])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-6.1-1.9 (2020-11-12)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Cannot remove a validated user
    (https://issues.rudder.io/issues/18518[#18518])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-6.1-1.8 (2020-09-15)

=== Changes

==== Miscellaneous

* Notify change validation request by email
    (https://issues.rudder.io/issues/17205[#17205])

=== Bug fixes

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-6.1-1.7 (2020-07-20)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Optimize elm plugins
    (https://issues.rudder.io/issues/17886[#17886])
* Fixed: Add screenshots for validated users
    (https://issues.rudder.io/issues/17866[#17866])
* Fixed: Trying to add a group property with change request plugin enabled lead to a blank property (plugin side)
    (https://issues.rudder.io/issues/17819[#17819])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-6.1-1.6 (2020-06-18)

=== Changes

=== Bug fixes

==== Refactoring

* Fixed: Adapt plugin to 6.1 rc releases, especially properties Hocon format
    (https://issues.rudder.io/issues/17587[#17587])

==== Miscellaneous

* Fixed: Fix non compiling plugins after changes on Rudder
    (https://issues.rudder.io/issues/17448[#17448])
* Fixed: Adapt change validation plugin to changes made with properties (group / global)
    (https://issues.rudder.io/issues/17269[#17269])

==== Documentation

* Fixed: Make images displayable in plugin doc on github
    (https://issues.rudder.io/issues/16989[#16989])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

