= Changelogs for Rudder plugin datasources 6.1.\* versions

== datasources-6.1-1.9 (2020-07-20)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Ignored node should be ignored for datasource
    (https://issues.rudder.io/issues/17826[#17826])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-6.1-1.8 (2020-06-17)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Datasource retrieve string in place of json
    (https://issues.rudder.io/issues/17640[#17640])
* Fixed: Fix non compiling plugins after changes on Rudder
    (https://issues.rudder.io/issues/17448[#17448])
* Fixed: Adapt datasource plugin to 6.1
    (https://issues.rudder.io/issues/17278[#17278])

==== Refactoring

* Fixed: Adapt plugin to 6.1 rc releases, especially properties Hocon format
    (https://issues.rudder.io/issues/17587[#17587])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

