= Changelogs for Rudder plugin dsc 6.1.\* versions

== dsc-6.1-1.19 (2020-06-18)

=== Changes

=== Bug fixes

==== ncf

* Fixed: HTTP reports are empty when the locale is not set to en-us
    (https://issues.rudder.io/issues/17730[#17730])
* Fixed: Add the possibility to report arbitrary info level logs in the agent
    (https://issues.rudder.io/issues/17170[#17170])
* Fixed: Add HTTPS report mode support to the agent
    (https://issues.rudder.io/issues/17074[#17074])

==== CLI

* Fixed: New agents are always in error before their first run
    (https://issues.rudder.io/issues/17676[#17676])

==== System techniques

* Fixed: Agent 6.0 tries to send reports using https with a 6.1 server
    (https://issues.rudder.io/issues/17432[#17432])
* Fixed: Add a system technique to send leftover reports
    (https://issues.rudder.io/issues/17167[#17167])

==== Rudder web app

* Fixed: Fix non compiling plugin after changes on Rudder
    (https://issues.rudder.io/issues/17473[#17473])

==== Techniques

* Fixed: Techniques in DSC plugins didn't have their RudderUniqueId updated
    (https://issues.rudder.io/issues/17470[#17470])

==== System integration

* Fixed: DSC nodes policies are not generated with the correct permissions
    (https://issues.rudder.io/issues/17417[#17417])
* Fixed: Global const variables are not defined on the windows agent
    (https://issues.rudder.io/issues/17370[#17370])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

