= Changelogs for Rudder plugin dsc 6.1.\* versions

== dsc-6.1-1.21 (2021-01-27)

=== Changes

==== CLI

* Add a rudder agent reset command to the DSC agent
    (https://issues.rudder.io/issues/17923[#17923])

=== Bug fixes

==== Packaging

* Fixed: Plugin is downloading rudder-plugin main-build.conf from master and not from the 6.1 branch displaying wrong version in the UI
    (https://issues.rudder.io/issues/18809[#18809])
* Fixed: Unattended upgrade can not configure correctly the policy server conf
    (https://issues.rudder.io/issues/18560[#18560])

==== ncf

* Fixed: Rudder agent throws exceptions when you try to redefine a class
    (https://issues.rudder.io/issues/18751[#18751])

==== Techniques

* Fixed: Improve the windows install software technique documentation
    (https://issues.rudder.io/issues/18749[#18749])

==== CLI

* Fixed: All powershell script files should be in UTF8 with BOM
    (https://issues.rudder.io/issues/18469[#18469])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-6.1-1.20 (2020-09-09)

=== Changes

=== Bug fixes

==== ncf

* Fixed: handle default values and add sha 512 to file from shared folder generic method
    (https://issues.rudder.io/issues/18179[#18179])
* Fixed: Make the "rudder agent test" command able to call for a specific test
    (https://issues.rudder.io/issues/18148[#18148])
* Fixed: Add a package management GM for windows
    (https://issues.rudder.io/issues/17142[#17142])

==== Packaging

* Fixed: Fresh install only modifies Systel env variables and not the current process one
    (https://issues.rudder.io/issues/18146[#18146])

==== CLI

* Fixed: When an inventory is send, the agent also send an end execution report which should be sent
    (https://issues.rudder.io/issues/18031[#18031])
* Fixed: Add health command to the agent
    (https://issues.rudder.io/issues/17915[#17915])

==== Miscellaneous

* Fixed: Parameters value in the technique editor are changed if they contain a "_" char
    (https://issues.rudder.io/issues/18022[#18022])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-6.1-1.19 (2020-06-18)

=== Changes

=== Bug fixes

==== ncf

* Fixed: HTTP reports are empty when the locale is not set to en-us
    (https://issues.rudder.io/issues/17730[#17730])
* Fixed: Add the possibility to report arbitrary info level logs in the agent
    (https://issues.rudder.io/issues/17170[#17170])
* Fixed: Add HTTPS report mode support to the agent
    (https://issues.rudder.io/issues/17074[#17074])

==== CLI

* Fixed: New agents are always in error before their first run
    (https://issues.rudder.io/issues/17676[#17676])

==== System techniques

* Fixed: Agent 6.0 tries to send reports using https with a 6.1 server
    (https://issues.rudder.io/issues/17432[#17432])
* Fixed: Add a system technique to send leftover reports
    (https://issues.rudder.io/issues/17167[#17167])

==== Rudder web app

* Fixed: Fix non compiling plugin after changes on Rudder
    (https://issues.rudder.io/issues/17473[#17473])

==== Techniques

* Fixed: Techniques in DSC plugins didn't have their RudderUniqueId updated
    (https://issues.rudder.io/issues/17470[#17470])

==== System integration

* Fixed: DSC nodes policies are not generated with the correct permissions
    (https://issues.rudder.io/issues/17417[#17417])
* Fixed: Global const variables are not defined on the windows agent
    (https://issues.rudder.io/issues/17370[#17370])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

