= Changelogs for Rudder plugin scale-out-relay 6.1.\* versions

== scale-out-relay-6.1-1.4 (2020-06-17)

=== Changes

==== Miscellaneous

* Promote a node to relay
    (https://issues.rudder.io/issues/16743[#16743])
* Promote a node to relay
    (https://issues.rudder.io/issues/16743[#16743])
* Promote a node to relay
    (https://issues.rudder.io/issues/16743[#16743])

=== Bug fixes

==== Miscellaneous

* Fixed: Trigger promises generation when promoting a node to relay
    (https://issues.rudder.io/issues/17570[#17570])
* Fixed: Broken line breaks in postinst output
    (https://issues.rudder.io/issues/17548[#17548])
* Fixed: Adapt Scale out relay plugin to 6.1
    (https://issues.rudder.io/issues/17279[#17279])
* Fixed: On high load after a reboot, generation fails because scale-out-relay not OK
    (https://issues.rudder.io/issues/17160[#17160])
* Fixed: Add documentation on version/reporting mode compatibility for the relays
    (https://issues.rudder.io/issues/16747[#16747])

=== Release notes

This is a bug fix release in the 6.1 series and therefore all installations of 6.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

