- hosts: RudderServer
  tasks:

# tasks for installing Rudder Server 

    - name: Adding Rudder Repo Key
      rpm_key:
        key: "https://repository.rudder.io/rpm/rudder_rpm_key.pub"
        state: present
      become: true

    - name: Adding Rudder Repo
      zypper_repository:
        description: "Rudder 6.1"
        name: "Rudder_6.1"
        repo: "http://repository.rudder.io/rpm/6.1/SLES_15"
        disable_gpg_check: false
        auto_import_keys: yes
        state: present
      become: true

    - name: Installing Rudder Root Server
      zypper:
        name: rudder-server-root
        state: present
      become: true
      register: result
      until: result is successful

    - name: Installing Rudder Agent
      zypper:
        name: rudder-agent
        state: present
      become: true
      register: result
      until: result is successful

