#!/usr/bin/env python
# coding: utf8

"""
Pull-request quality tool.

You need a configuration file, if you don't have one, the tool will create one for you at first run.

Usage:
        quality-assistant -h|--help
        quality-assistant merge all
        quality-assistant merge <repo>
        quality-assistant autolabel all
        quality-assistant autolabel <repo>
"""

from __future__ import print_function

import os
from common import *
from github import *

import docopt # apt-get install python-docopt || pip install docopt
from pprint import pprint


def clean_repo(repo):
  redirect = ""
  if Config.LOGLEVEL == "error":
    redirect = " >/dev/null"
  # check master directory
  directory = Config.WORKING_DIRECTORY
  if not os.path.isdir(directory):
    logfail("Master directory doesn't exist, exiting")
    exit(1)
  # check working directory
  directory = directory + "/" + repo
  if not os.path.isdir(directory):
    os.chdir(Config.WORKING_DIRECTORY)
    shell("rudder-dev clone "+repo+redirect, "Cloning ncf in a temporary directory")
  # cleanup working directory
  os.chdir(directory)
  shell("git reset --hard"+redirect, "Cleanup working directory")


def repo_merge(repo):
  redirect = ""
  if Config.LOGLEVEL == "info" or Config.LOGLEVEL == "error":
    redirect = " > /dev/null 2>/dev/null"
  api_url = "https://api.github.com/repos/Normation/{repo}/issues?labels="+Config.PR_VALIDATED_LABEL
  url = api_url.format(repo=repo)
  data = github_call(url)
  for pr_info in data:
    labels = [l['name'] for l in pr_info['labels']]
    if Config.BOT_CANNOT_MERGE_LABEL in labels:
      continue
    clean_repo(repo)
    pr = PR(pr_info['html_url'])
    command = "rudder-dev merge " + pr_info['html_url'] + " --automatic"
    (code, output) = shell(command + " --test" + redirect, "Trying to merge PR " + pr_info['html_url'], fail_exit=False)
    if code != 0:
      # PR must be manually merged
      comment="""This PR is not mergeable to upper versions.
Since it is "Ready for merge" you must merge it by yourself using the following command:
`rudder-dev merge """ + pr_info['html_url'] + """`
-- Your faithful QA"""
      pr.comment(comment)
      pr.label(Config.BOT_CANNOT_MERGE_LABEL)
    else:
      # PR can be automatically merged
      pr=PR(pr_info['html_url'])
      shell(command + redirect, "Automatically merging PR " + pr_info['html_url'])


def repo_merge_all():
  for repo in Config.REPOSITORIES:
    repo_merge(repo)


def manage_label(repo, name, color):
  get_url = "https://api.github.com/repos/Normation/{repo}/labels/{name}".format(repo=repo, name=name)
  label = github_call(get_url, fail_ok=True)
  if label is None:
    # no such label, create it
    create_url = "https://api.github.com/repos/Normation/{repo}/labels".format(repo=repo)
    data = '{"name": "' + name + '", "color": "' + color + '" }'
    print("- Creating label: " + name)
    github_call(create_url, post_data=data)
  else:
    # check label color
    if label['color'] != color:
      data = '{"name": "' + name + '", "color": "' + color + '" }'
      print("- Updating color of label: " + name)
      github_call(get_url, patch_data=data)

def autolabel(repo):
  manage_label(repo, Config.BOT_CANNOT_MERGE_LABEL, Config.BOT_CANNOT_MERGE_COLOR)
  manage_label(repo, Config.PR_VALIDATED_LABEL, Config.PR_VALIDATED_COLOR)

def autolabel_all():
  for repo in Config.REPOSITORIES:
    print("Repo: " + repo)
    autolabel(repo)


if __name__ == "__main__":
  arguments = docopt.docopt(__doc__)
  section = "quality-assistant"
  read_configuration(section)
  # qa specific configuration
  Config.WORKING_DIRECTORY = get_config("working_directory", "No 'working_directory' entry in " + Config.CONFIG_FILE, section)
  Config.LOGLEVEL = get_config("loglevel", "No 'loglevel' entry in " + Config.CONFIG_FILE, section) # verbose, info, error

  if arguments['merge'] and arguments['all']:
    repositories = get_config("repos", "No 'repositories' list in " + Config.CONFIG_FILE, section)
    Config.REPOSITORIES = re.split(r'[ ,]+', repositories)
    repo_merge_all()
  elif arguments['merge']:
    repo_merge(arguments['<repo>'])
  elif arguments['autolabel'] and arguments['all']:
    repositories = get_config("repos", "No 'repositories' list in " + Config.CONFIG_FILE, section)
    Config.REPOSITORIES = re.split(r'[ ,]+', repositories)
    autolabel_all()
  elif arguments['autolabel']:
    autolabel(arguments['<repo>'])

