= Change logs for Rudder 8.1

==  Rudder 8.1.12 (2025-02-26)

=== Changes


==== Agent

* We should not be able to install package on wrong OS
    (https://issues.rudder.io/issues/26090[#26090])

==== CI

* Publish step for CI runs the tests when they already have previously run
    (https://issues.rudder.io/issues/26411[#26411])
* Make rudder jenkins task work with ns-remap
    (https://issues.rudder.io/issues/26370[#26370])
* Make rudder-techniques jenkins task work with ns-remap
    (https://issues.rudder.io/issues/26368[#26368])
* Add docker based tests in rudder-agent
    (https://issues.rudder.io/issues/26379[#26379])

==== Architecture - Code maintenance

* Some more changes needed for scala 3 migrations
    (https://issues.rudder.io/issues/26328[#26328])

==== Web - UI & UX

* Pop up validation for restoring archive
    (https://issues.rudder.io/issues/26265[#26265])

==== Web - Config management

* Allow to enable/disable technique from the directive tree screen
    (https://issues.rudder.io/issues/26161[#26161])

=== Bug fixes

==== Packaging

* Fixed: Fix typos in ruddder-packages
    (https://issues.rudder.io/issues/26409[#26409])
* Fixed: Builds fail to cleanup
    (https://issues.rudder.io/issues/26308[#26308])
* Fixed: Agent fails to build on old systems
    (https://issues.rudder.io/issues/26306[#26306])
* Fixed: rudder server package writes in different log files ...
    (https://issues.rudder.io/issues/26137[#26137])

==== Documentation

* Fixed: Fixup rudder-doc test task
    (https://issues.rudder.io/issues/26369[#26369])
* Fixed: Troubleshooting ESET software modifying certificates by replacing issuers
    (https://issues.rudder.io/issues/26234[#26234])

==== Plugin manager cli

* Fixed: rudder-pkg reports a success when installing a plugin even if the postinst plugin script was in error
    (https://issues.rudder.io/issues/26428[#26428])

==== CI

* Fixed: Cache is not shared anymode
    (https://issues.rudder.io/issues/26414[#26414])
* Fixed: Add a NVD API key to the Jenkins-security jobs
    (https://issues.rudder.io/issues/26385[#26385])

==== Architecture - Test

* Fixed: Roles parsing for custom plugin role may fail in tests
    (https://issues.rudder.io/issues/26342[#26342])

==== Web - Campaigns

* Fixed: Get campaign is creating an empty file when campaign does not exist
    (https://issues.rudder.io/issues/26337[#26337])

==== Agent

* Fixed: The relayd reports parser can break on multiline fields in logs
    (https://issues.rudder.io/issues/26290[#26290])

==== Web - UI & UX

* Fixed: The "Save" button disappears from the group webpage if the group name is too long
    (https://issues.rudder.io/issues/26261[#26261])
* Fixed: Directive will not be displayed when clicking on a technique then on directive in tree
    (https://issues.rudder.io/issues/26206[#26206])
* Fixed: Persistent tooltips on rules page
    (https://issues.rudder.io/issues/25586[#25586])

==== Security

* Fixed: Update the openssl crate
    (https://issues.rudder.io/issues/26305[#26305])

==== Architecture - Code maintenance

* Fixed: Error at rudder start after an upgrade
    (https://issues.rudder.io/issues/26200[#26200])

==== System techniques

* Fixed: Fix some typos in system techniques
    (https://issues.rudder.io/issues/26407[#26407])

==== Techniques

* Fixed: Reporting on user management technique is broken when multiple users are defined in a directive
    (https://issues.rudder.io/issues/26255[#26255])

==== Generic methods

* Fixed: Fix the abort_default acceptance test
    (https://issues.rudder.io/issues/26372[#26372])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.11 (2025-01-13)

=== Changes


==== Generic methods

* Allow passing env vars to package managers
    (https://issues.rudder.io/issues/25908[#25908])

=== Bug fixes

==== Packaging

* Fixed: Installation of RHEL 9 flavors (alma, oraclelinux) fails with postgresql.service: Failed with result 'exit-code'
    (https://issues.rudder.io/issues/26034[#26034])

==== Agent

* Fixed: FQDN on Windows node can take localhost as value
    (https://issues.rudder.io/issues/25706[#25706])

==== Documentation

* Fixed: Documentation point to the wrong repository for AL1 and 2
    (https://issues.rudder.io/issues/26041[#26041])

==== Web - UI & UX

* Fixed: Change Rudder current-year to 2025
    (https://issues.rudder.io/issues/26134[#26134])
* Fixed: Trying to save a group with empty criteria removes all entries
    (https://issues.rudder.io/issues/26075[#26075])
* Fixed: Discordance on node compliance between two tabs
    (https://issues.rudder.io/issues/25617[#25617])
* Fixed: Properties tab : Non-rearrangement of the pop-ups
    (https://issues.rudder.io/issues/25824[#25824])
* Fixed: Acceptation error with new node on hostname duplication is not hightlitghed
    (https://issues.rudder.io/issues/25973[#25973])
* Fixed: Quicksearch filters do not work
    (https://issues.rudder.io/issues/25297[#25297])

==== Web - Compliance & node report

* Fixed: NPE in archive generation
    (https://issues.rudder.io/issues/26088[#26088])
* Fixed: Score breakdown has inconsistent numbers
    (https://issues.rudder.io/issues/25948[#25948])

==== Architecture - Code maintenance

* Fixed: Spotless check fails on RudderConfig unmerged imports
    (https://issues.rudder.io/issues/26107[#26107])
* Fixed: scoreService and scoreServiceManager are not initialized where they should
    (https://issues.rudder.io/issues/25842[#25842])

==== Security

* Fixed: Vulnerability in idna
    (https://issues.rudder.io/issues/26085[#26085])
* Fixed: API token created for a OIDC user should not be usable - allow feature disabling
    (https://issues.rudder.io/issues/25669[#25669])
* Fixed: Path traversal in shared files API for technique resources
    (https://issues.rudder.io/issues/26000[#26000])
* Fixed: /var/rudder/tmp is world-readable
    (https://issues.rudder.io/issues/25989[#25989])

==== API

* Fixed: Group query select attribute has different name in create and update payload
    (https://issues.rudder.io/issues/26064[#26064])

==== Web - Config management

* Fixed: The directive page is much slower with Rudder 8.1 than in 7.3
    (https://issues.rudder.io/issues/26002[#26002])

==== Web - Maintenance

* Fixed: Non admin users in file get disabled even if last login parameter does not exceed the scheduled date
    (https://issues.rudder.io/issues/26056[#26056])
* Fixed: search on event log must also search on event type
    (https://issues.rudder.io/issues/25705[#25705])

==== Server components

* Fixed: rudder-package fails to parse old plugin version numbers, breaking the upgrade
    (https://issues.rudder.io/issues/25156[#25156])

==== Techniques

* Fixed: Techniques file should not be executable
    (https://issues.rudder.io/issues/26027[#26027])

==== Generic methods

* Fixed: Multi directive instance of a technique with jinja templating method fail
    (https://issues.rudder.io/issues/26152[#26152])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Sylvain BALLARD

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.10 (2024-12-03)

=== Changes


==== Documentation

* Add a dedicated Readme for rudder-package
    (https://issues.rudder.io/issues/25917[#25917])

=== Bug fixes

==== Web - Nodes & inventories

* Fixed: Sometimes, software are deleted
    (https://issues.rudder.io/issues/25986[#25986])
* Fixed: tooltip broken for groups description
    (https://issues.rudder.io/issues/25815[#25815])
* Fixed: Link to node is missing for modified nodes
    (https://issues.rudder.io/issues/25974[#25974])

==== rudderc

* Fixed: rudderc fails to compile string with vars and regex
    (https://issues.rudder.io/issues/25959[#25959])

==== Plugin manager cli

* Fixed: Allow installing the licenses with rudder-package
    (https://issues.rudder.io/issues/25971[#25971])

==== Agent

* Fixed: First run after node acceptance does not send reports
    (https://issues.rudder.io/issues/25912[#25912])

==== Generic methods

* Fixed: Add a new type constraint to the variable_dict generic method
    (https://issues.rudder.io/issues/25924[#25924])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.9 (2024-11-28)

=== Changes


==== Packaging

* Update openssl and curl
    (https://issues.rudder.io/issues/25932[#25932])

==== Documentation

* Remove deprecated examples from rudder-by-example
    (https://issues.rudder.io/issues/25909[#25909])

==== Web - UI & UX

* Add padding to trees to prevent the last element from being hidden when a link is hovered
    (https://issues.rudder.io/issues/25923[#25923])

==== rudderc

* Allow validating JSON parameters in methods
    (https://issues.rudder.io/issues/25871[#25871])

==== Architecture - Code maintenance

* Better log for bad node key
    (https://issues.rudder.io/issues/25870[#25870])

=== Bug fixes

==== Documentation

* Fixed: Documentation should advice to trigger agent run after promote a node to relay
    (https://issues.rudder.io/issues/25967[#25967])
* Fixed: Update example to keep up to date rudder-agent package
    (https://issues.rudder.io/issues/25905[#25905])
* Fixed: Remove references to syslog in the docs
    (https://issues.rudder.io/issues/25865[#25865])
* Fixed: Backup/Restore/Migrate documentation are missing essential bits
    (https://issues.rudder.io/issues/25676[#25676])
* Fixed: Documented repository  Rudder public key url is incorrect
    (https://issues.rudder.io/issues/25845[#25845])

==== Web - Nodes & inventories

* Fixed: Error when accepting 2 or more nodes
    (https://issues.rudder.io/issues/25892[#25892])

==== Architecture - Dependencies

* Fixed: Remove security check on a js dev dependency
    (https://issues.rudder.io/issues/25937[#25937])

==== Web - UI & UX

* Fixed: The setup initial page should not be displayed if rudder-pkg.conf has been modified
    (https://issues.rudder.io/issues/25847[#25847])

==== Web - Config management

* Fixed: Locale issue: date picker should be in yyyy/MM/dd in group criteria
    (https://issues.rudder.io/issues/25727[#25727])
* Fixed: After restart, nodes that were set back to default policy mode return to their previous overridden mode
    (https://issues.rudder.io/issues/25866[#25866])

==== Web - Compliance & node report

* Fixed: a node with no rules applied has a score of F
    (https://issues.rudder.io/issues/25813[#25813])

==== Plugin manager cli

* Fixed: Use secrecy to store the password
    (https://issues.rudder.io/issues/25873[#25873])

==== Techniques

* Fixed: File content from remote template technique should allow selecting a file from shared folder
    (https://issues.rudder.io/issues/25851[#25851])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.8 (2024-11-08)

=== Changes


==== Documentation

* Publish the audit report in the docs
    (https://issues.rudder.io/issues/25803[#25803])
* Document how to install plugins on Amazon 2023
    (https://issues.rudder.io/issues/25678[#25678])

==== Agent

* Add a new CLI tool to converts raw Rudder reports to Json
    (https://issues.rudder.io/issues/25757[#25757])

==== Generic methods

*  Add Windows support to the generic method file_report_content_tail
    (https://issues.rudder.io/issues/25588[#25588])

=== Bug fixes

==== Packaging

* Fixed: Start jetty script in debug mode
    (https://issues.rudder.io/issues/25735[#25735])
* Fixed: rudder package log error when trying to update licence on a relay
    (https://issues.rudder.io/issues/25821[#25821])
* Fixed: Update Rust for typos check
    (https://issues.rudder.io/issues/25790[#25790])

==== Documentation

* Fixed: Missing documentation on rudder.users.cleanup.account.disableAfterLastLogin
    (https://issues.rudder.io/issues/25623[#25623])
* Fixed: Change of template.png in docs.rudder.io
    (https://issues.rudder.io/issues/25646[#25646])
* Fixed: OpenAPI documentation is invalid with duplicate /nodes/pending endpoints
    (https://issues.rudder.io/issues/25709[#25709])

==== Web - UI & UX

* Fixed: Sometimes too long properties values move out actions buttons from window
    (https://issues.rudder.io/issues/25762[#25762])
* Fixed: Tooltips in nodes compliance are not displayed
    (https://issues.rudder.io/issues/25663[#25663])
* Fixed: Node search query doesn't find any Windows node
    (https://issues.rudder.io/issues/25638[#25638])

==== rudderc

* Fixed: Override audit/enforce mode does not work with iterator
    (https://issues.rudder.io/issues/25770[#25770])
* Fixed: Broken parsing of node inventory variable
    (https://issues.rudder.io/issues/25771[#25771])

==== Web - Nodes & inventories

* Fixed: On new groups, adding a prop leads to "No query defined for group" error
    (https://issues.rudder.io/issues/25820[#25820])
* Fixed: Lost manufacturer & serial for BIOS  between 7.3 and 8.0
    (https://issues.rudder.io/issues/25589[#25589])
* Fixed: SQL error in the logs when deleting a node
    (https://issues.rudder.io/issues/25633[#25633])
* Fixed: Add support for Tuxedo OS
    (https://issues.rudder.io/issues/25519[#25519])

==== Web - Compliance & node report

* Fixed: ReportsExecution doesn't have timezone on all fields
    (https://issues.rudder.io/issues/25713[#25713])

==== Web - Config management

* Fixed: Search on RAM fails in node groups
    (https://issues.rudder.io/issues/25701[#25701])
* Fixed: When removing files from a technique, it might get disabled unexpectedly
    (https://issues.rudder.io/issues/23959[#23959])
* Fixed: switching policy mode on a node from "Enforce" to anything else produce event log about properties
    (https://issues.rudder.io/issues/25667[#25667])

==== Web - Maintenance

* Fixed: OIDC users are marked as deleted after a new user is provisioned
    (https://issues.rudder.io/issues/25681[#25681])
* Fixed: Technical and event logs get log from browser timezone instead of server timezone
    (https://issues.rudder.io/issues/25720[#25720])

==== Server components

* Fixed: Default settings for new nodes are not applied on a accepted node
    (https://issues.rudder.io/issues/25652[#25652])

==== Relay server or API

* Fixed: Stacktrace in relayd on invalid run time file name
    (https://issues.rudder.io/issues/25754[#25754])
* Fixed: Add 127.0.0.1 as ServerAlias for multi-vhost  server configuration
    (https://issues.rudder.io/issues/25675[#25675])

==== Architecture - Code maintenance

* Fixed: Avoid Content-Security-Policy-Report-Only headers in dev mode
    (https://issues.rudder.io/issues/25715[#25715])
* Fixed: Add tests for the case where there is conflicts in group properties
    (https://issues.rudder.io/issues/25419[#25419])
* Fixed: Chunk appending when resolving node ids from union target can be optimized
    (https://issues.rudder.io/issues/25635[#25635])

==== API

* Fixed: Related rules return an authorization error in UI for non-admin users
    (https://issues.rudder.io/issues/25645[#25645])

==== System techniques

* Fixed: rudder-cf-serverd is not restarted properly after a change in authorized network on a relay
    (https://issues.rudder.io/issues/25639[#25639])

==== Agent

* Fixed: rudder agent factory-reset -f doesn't do anything
    (https://issues.rudder.io/issues/25607[#25607])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.7 (2024-10-01)

=== Changes


==== Documentation

* Undocument global parameters
    (https://issues.rudder.io/issues/25261[#25261])

==== Architecture - evolution

* Normalize authentication logs
    (https://issues.rudder.io/issues/25478[#25478])

=== Bug fixes

==== Inventory

* Fixed: Inventory fails because rudder-agent has no version in inventory
    (https://issues.rudder.io/issues/25496[#25496])

==== Agent

* Fixed: Backport scheduling fixes for cf-execd
    (https://issues.rudder.io/issues/25505[#25505])

==== Packaging

* Fixed: Add the new completion file to RPM package
    (https://issues.rudder.io/issues/25309[#25309])
* Fixed: rudder-package completion build breaks
    (https://issues.rudder.io/issues/25308[#25308])

==== Server components

* Fixed: rudder-cf-serverd was stopped on the server, and nothing restarted it
    (https://issues.rudder.io/issues/25252[#25252])

==== Documentation

* Fixed: User password change no longer needs restart in doc
    (https://issues.rudder.io/issues/25444[#25444])
* Fixed: API documentation for user-management is missing some endpoints
    (https://issues.rudder.io/issues/25459[#25459])
* Fixed: API documentation examples are not valid bash scripts
    (https://issues.rudder.io/issues/25302[#25302])
* Fixed: API documentation for user management has no user info and providers fields
    (https://issues.rudder.io/issues/25291[#25291])
* Fixed: API documentation for pending nodes is missing an endpoint and fields
    (https://issues.rudder.io/issues/25285[#25285])

==== Plugin manager cli

* Fixed: Detect local install tentative in rudder package
    (https://issues.rudder.io/issues/25538[#25538])
* Fixed: Rudder-pkg tests fail since distutils package has been removed in python 3.12
    (https://issues.rudder.io/issues/25417[#25417])
* Fixed: Plugin Postinst script are not run during upgrades
    (https://issues.rudder.io/issues/25282[#25282])
* Fixed: Make plugin install log less verbose
    (https://issues.rudder.io/issues/25275[#25275])

==== Web - UI & UX

* Fixed: When accepting a node with a duplicate hostname, there's no error displayed
    (https://issues.rudder.io/issues/25453[#25453])
* Fixed: Typo in agent schedule selector
    (https://issues.rudder.io/issues/25500[#25500])
* Fixed: Event log table default period of two hours is too short
    (https://issues.rudder.io/issues/25499[#25499])
* Fixed: User identity does not show up in bar when user has last login
    (https://issues.rudder.io/issues/25409[#25409])
* Fixed: Score badge background image should not be repeated
    (https://issues.rudder.io/issues/25391[#25391])
* Fixed: Incorrect display of compliance in newly created rules
    (https://issues.rudder.io/issues/25371[#25371])
* Fixed: Event logs details look broken in 8.1
    (https://issues.rudder.io/issues/25071[#25071])
* Fixed: Nodes table sorting is not obvious and we need to guess the sort column and direction
    (https://issues.rudder.io/issues/25136[#25136])
* Fixed: Only remaining user managed by file cannot be deleted
    (https://issues.rudder.io/issues/25300[#25300])
* Fixed: Message « This node has no properties » on group
    (https://issues.rudder.io/issues/25171[#25171])
* Fixed: tooltips in the rules page persist when switching content
    (https://issues.rudder.io/issues/21668[#21668])
* Fixed: Dashboard information are not updated when deleting a node
    (https://issues.rudder.io/issues/25095[#25095])

==== Security

* Fixed: Unknown API tokens get logged in plain
    (https://issues.rudder.io/issues/25555[#25555])
* Fixed: Ignore RUSTSEC-2024-0365 as we are not vulnerable
    (https://issues.rudder.io/issues/25456[#25456])
* Fixed: User password and permission change should invalidate sessions
    (https://issues.rudder.io/issues/25407[#25407])
* Fixed: Invalidated user sessions need to have an endcause and user should be notified
    (https://issues.rudder.io/issues/25443[#25443])
* Fixed: Authentication happens twice with same session id
    (https://issues.rudder.io/issues/25123[#25123])
* Fixed: Disabled and deleted user can still use Rudder until session expires
    (https://issues.rudder.io/issues/25307[#25307])

==== Architecture - Code maintenance

* Fixed: NuProcessHandler.onStart NPE log message
    (https://issues.rudder.io/issues/25306[#25306])
* Fixed: Add log for error in JSON campaigns on FS
    (https://issues.rudder.io/issues/25388[#25388])
* Fixed: Scheduled processes could stop on error in ZIO
    (https://issues.rudder.io/issues/25365[#25365])

==== Web - Nodes & inventories

* Fixed: API don't include acceptedSince information
    (https://issues.rudder.io/issues/25476[#25476])
* Fixed: Windows KB don't show up in the inventory anymore
    (https://issues.rudder.io/issues/25351[#25351])

==== Web - Config management

* Fixed: Hooks are not executed anymore from their directory
    (https://issues.rudder.io/issues/25498[#25498])

==== Web - Compliance & node report

* Fixed: Technical logs are not loaded when visiting the tab - rudder 8.1
    (https://issues.rudder.io/issues/24332[#24332])

==== Web - Maintenance

* Fixed: Users cleanup configuration is too strict on disabled users
    (https://issues.rudder.io/issues/25479[#25479])
* Fixed: when we have compliance right, the rule page shows a weird message
    (https://issues.rudder.io/issues/24863[#24863])

==== API

* Fixed: The severity ERROR for Node with ID ‘xxx’ was not found in Rudder’ is too strict
    (https://issues.rudder.io/issues/25438[#25438])
* Fixed: Deleting CVE group is possible even if it is a system group
    (https://issues.rudder.io/issues/25348[#25348])
* Fixed: Archive API for import/export doesn't know about technique
    (https://issues.rudder.io/issues/24789[#24789])

==== Miscellaneous

* Fixed: Group position on dashboard statistics  make no sens
    (https://issues.rudder.io/issues/25448[#25448])

==== rudderc

* Fixed: Static rudderc builds are failing due to missing tracing import
    (https://issues.rudder.io/issues/25439[#25439])
* Fixed: rudderc is generating 0 bytes resources when output directory is the same as the input
    (https://issues.rudder.io/issues/25238[#25238])

==== Web - Technique editor

* Fixed: Resources upload over 8 MB show error in log and not in UI
    (https://issues.rudder.io/issues/25155[#25155])

==== Web - Campaigns

* Fixed: no reports in campaign page even if the node sent the data
    (https://issues.rudder.io/issues/25350[#25350])

==== System integration

* Fixed: One user is created each case change even if case sensitivity if false
    (https://issues.rudder.io/issues/24955[#24955])

==== Architecture - Test

* Fixed: Database tests have non temporary DDL that prevents running them twice
    (https://issues.rudder.io/issues/25303[#25303])

==== System techniques

* Fixed: Local inventories are piling up in /var/rudder/inventories
    (https://issues.rudder.io/issues/25289[#25289])

==== Generic methods

* Fixed: Broken jinja2 templating on Ubuntu 24.04
    (https://issues.rudder.io/issues/25324[#25324])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.6 (2024-08-01)

=== Changes


==== Documentation

* Remove 7.3 and 8.0 from doc index
    (https://issues.rudder.io/issues/25150[#25150])

==== Web - Config management

* Add VARIABLE_NAME to technique so that we can use valid parameter name in techniques
    (https://issues.rudder.io/issues/25091[#25091])

==== Web - Technique editor

* Windows DSC logo on method are not aligned
    (https://issues.rudder.io/issues/24587[#24587])

==== Generic methods

* Enable dsc support for some methods
    (https://issues.rudder.io/issues/25153[#25153])

=== Bug fixes

==== Agent

* Fixed: Could not open database txn cf_state.lmdb: Invalid argument
    (https://issues.rudder.io/issues/22442[#22442])
* Fixed: Fusion inventory fails to report software with exotic names
    (https://issues.rudder.io/issues/24321[#24321])
* Fixed: rudder agent factory-reset should reenable service
    (https://issues.rudder.io/issues/25187[#25187])

==== API

* Fixed: Unauthorized access to API should not be logged as error
    (https://issues.rudder.io/issues/25246[#25246])

==== Web - Maintenance

* Fixed: Don't update plugin password if nothing was given
    (https://issues.rudder.io/issues/25227[#25227])
* Fixed: The webapp does not build on jdk22
    (https://issues.rudder.io/issues/25168[#25168])

==== CI

* Fixed: The policies Dockerfile does not fail when the rudder agent fails to install
    (https://issues.rudder.io/issues/25213[#25213])

==== Server components

* Fixed: Node inventory hooks are are not working properly
    (https://issues.rudder.io/issues/25161[#25161])

==== Security

* Fixed: RUSTSEC-2024-0357  vulnerability in openssl lib
    (https://issues.rudder.io/issues/25189[#25189])

==== Web - Nodes & inventories

* Fixed: When agent version is missing in inventory, we get a security token error
    (https://issues.rudder.io/issues/25164[#25164])
* Fixed: XML Entity injection in inventory parsing
    (https://issues.rudder.io/issues/25157[#25157])

==== Web - UI & UX

* Fixed: Create property from inherited one
    (https://issues.rudder.io/issues/25109[#25109])
* Fixed: Some results of quicksearch cannot be opened
    (https://issues.rudder.io/issues/25046[#25046])
* Fixed: Second digit of minutes for agent scheduled not displayed
    (https://issues.rudder.io/issues/25078[#25078])
* Fixed: Generation error logs are unreadable in the interface
    (https://issues.rudder.io/issues/25042[#25042])

==== Web - Config management

* Fixed: No documentation on built-in techniques
    (https://issues.rudder.io/issues/25054[#25054])

==== Miscellaneous

* Fixed: Error 500 when we visit for the first time the campaign page
    (https://issues.rudder.io/issues/25053[#25053])

==== Techniques

* Fixed: sudoers technique in audit mode has unexpected reports
    (https://issues.rudder.io/issues/25093[#25093])
* Fixed: Missing reports with firewall technique
    (https://issues.rudder.io/issues/25090[#25090])

==== Generic methods

* Fixed: No report with method Rudder inventory trigger
    (https://issues.rudder.io/issues/25059[#25059])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Alexander Brunhirl

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.5 (2024-07-01)

=== Changes


==== Documentation

* Add rocky to list of supported architecture
    (https://issues.rudder.io/issues/25070[#25070])

=== Bug fixes

==== Documentation

* Fixed: Remove supported os for Ubuntu 24.04 for server and relay in 8.0
    (https://issues.rudder.io/issues/25074[#25074])
* Fixed: Include Ubuntu 24.04 in the list of supported OS
    (https://issues.rudder.io/issues/25036[#25036])
* Fixed: Only run the agent locally after install
    (https://issues.rudder.io/issues/25049[#25049])

==== Web - UI & UX

* Fixed: Directive detail has compliance bar JS error
    (https://issues.rudder.io/issues/25081[#25081])

==== Security

* Fixed: Escape ids to avoid XSS in rules and directives page
    (https://issues.rudder.io/issues/25050[#25050])

==== Plugin manager cli

* Fixed: When a plugin fails to download, the installation is considered successful
    (https://issues.rudder.io/issues/25048[#25048])

==== Web - Nodes & inventories

* Fixed: Processes are not displayed anymore in 8.1
    (https://issues.rudder.io/issues/25044[#25044])
* Fixed: Node delete has a todoQC
    (https://issues.rudder.io/issues/25045[#25045])

==== Performance and scalability

* Fixed: Rudder 8.1 slows down over time
    (https://issues.rudder.io/issues/24652[#24652])

==== Miscellaneous

* Fixed: Quick search bar selection/results box displays over input field, making input field unusable
    (https://issues.rudder.io/issues/25010[#25010])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.4 (2024-06-20)

=== Changes


==== Documentation

* Specify which repo to use in compatible os page
    (https://issues.rudder.io/issues/24901[#24901])

==== Architecture - Code maintenance

* pylint test failing on rudder package
    (https://issues.rudder.io/issues/24982[#24982])

==== Plugin manager cli

* Improve tracing loggers
    (https://issues.rudder.io/issues/24610[#24610])

==== Architecture - Internal libs

* Add hotswap agent conf file to gitignore to prevent surprises in production site
    (https://issues.rudder.io/issues/24961[#24961])

==== Generic methods

* Missing a generic method "command_execution_as_user'
    (https://issues.rudder.io/issues/22904[#22904])

=== Bug fixes

==== Packaging

* Fixed: Detection of remote database url in postinstallation script is not correct
    (https://issues.rudder.io/issues/24969[#24969])
* Fixed: rudder server debug fails on almalinux 8
    (https://issues.rudder.io/issues/21941[#21941])

==== Web - Nodes & inventories

* Fixed: Process are not saved anymore in 8.1
    (https://issues.rudder.io/issues/25035[#25035])
* Fixed: When node compliance right is missing, we don't want a red error pop-up
    (https://issues.rudder.io/issues/25008[#25008])
* Fixed: User with node_all permission can't modify node policy mode
    (https://issues.rudder.io/issues/25003[#25003])
* Fixed: Search for machine type (virtual, physical) does not work
    (https://issues.rudder.io/issues/24971[#24971])

==== Architecture - Code maintenance

* Fixed: Typo in NoopGetNodesbySoftwareName prevent merge
    (https://issues.rudder.io/issues/25018[#25018])

==== Web - Config management

* Fixed: Property inheritance of type array doesn't work
    (https://issues.rudder.io/issues/24988[#24988])

==== Security

* Fixed: Ignore braces DoS in 7.3
    (https://issues.rudder.io/issues/24995[#24995])

==== Web - UI & UX

* Fixed: Nodes page has console error from the tree script
    (https://issues.rudder.io/issues/24784[#24784])
* Fixed: We should rework the targets rules page when we create a directive
    (https://issues.rudder.io/issues/24472[#24472])
* Fixed: Error message when getting campaign through API
    (https://issues.rudder.io/issues/24959[#24959])

==== Miscellaneous

* Fixed: bugfixes in the list of updates appears in white
    (https://issues.rudder.io/issues/24983[#24983])

==== Documentation

* Fixed: API v19 documentation is missing in 8.1
    (https://issues.rudder.io/issues/24899[#24899])

==== rudderc

* Fixed: stacktraces from rudderc
    (https://issues.rudder.io/issues/24967[#24967])

==== Generic methods

* Fixed: Time lib still uses md5 for scheduling
    (https://issues.rudder.io/issues/24990[#24990])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Maxime Mérian

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.3 (2024-06-02)

=== Changes


==== Packaging

* Add cache debug info to understand why some arch don't use cache
    (https://issues.rudder.io/issues/24923[#24923])

==== Web - UI & UX

* Replace compliance chart with Score chart and and new details score charts
    (https://issues.rudder.io/issues/24829[#24829])
* Add basic elm-review config
    (https://issues.rudder.io/issues/24762[#24762])

==== Web - Campaigns

* Add daily schedule for campaign
    (https://issues.rudder.io/issues/24701[#24701])

==== Architecture - Dependencies

* Update elm dependencies
    (https://issues.rudder.io/issues/24857[#24857])

==== Web - Maintenance

* Clean missing score at start up
    (https://issues.rudder.io/issues/24840[#24840])

==== Web - Technique editor

* When we clone a technique with resource, the clone does not really have the resource
    (https://issues.rudder.io/issues/24280[#24280])

==== Plugin manager cli

* Add an option to inhibit webapp restart
    (https://issues.rudder.io/issues/24745[#24745])

==== Architecture - Code maintenance

* More change to prepare scala 3 migration
    (https://issues.rudder.io/issues/24813[#24813])
* More change to prepare scala 3 migration
    (https://issues.rudder.io/issues/24813[#24813])

=== Bug fixes

==== Packaging

* Fixed: cross compiled packages cache may interfere with other ones
    (https://issues.rudder.io/issues/24932[#24932])
* Fixed: Don't restart webapp on plugin upgrade
    (https://issues.rudder.io/issues/24838[#24838])
* Fixed: On postgresql 15, in some cases, user rudder cannot create or update the tables
    (https://issues.rudder.io/issues/24831[#24831])
* Fixed: Windows agent used to test windows policies was deleted
    (https://issues.rudder.io/issues/24956[#24956])

==== System integration

* Fixed: JVM memory check is too fragile
    (https://issues.rudder.io/issues/24820[#24820])

==== API

* Fixed: Query in get pending node API doesn't match anything
    (https://issues.rudder.io/issues/24937[#24937])
* Fixed: Compliance score are still kept for deleted nodes
    (https://issues.rudder.io/issues/24940[#24940])
* Fixed: Never return a password for plugin settings
    (https://issues.rudder.io/issues/24828[#24828])

==== Architecture - Code maintenance

* Fixed: exclude all old rudder package files from python tests
    (https://issues.rudder.io/issues/24954[#24954])
* Fixed: Fix upmerge of 24856 in 8.1
    (https://issues.rudder.io/issues/24864[#24864])

==== Web - UI & UX

* Fixed: No-report progress bars are the wrong width
    (https://issues.rudder.io/issues/24949[#24949])
* Fixed: The Directive button in pending nodes table has an old appearance
    (https://issues.rudder.io/issues/24948[#24948])
* Fixed: Properties tab in groups has no content after a save
    (https://issues.rudder.io/issues/24942[#24942])
* Fixed: Refresh on nodes tables leads to datatable and console error
    (https://issues.rudder.io/issues/24925[#24925])
* Fixed: Clicking on technique in technique tree doesn't do anything
    (https://issues.rudder.io/issues/24439[#24439])
* Fixed: We can add the same score details column many times in nodes tables
    (https://issues.rudder.io/issues/24627[#24627])
* Fixed: When we save an API Token, the UI is grayed out
    (https://issues.rudder.io/issues/24834[#24834])
* Fixed: Technique markdown documentation are no longer rendered in the directive page
    (https://issues.rudder.io/issues/24808[#24808])
* Fixed: Score details columns in node tables cannot be saved
    (https://issues.rudder.io/issues/24629[#24629])
* Fixed: Group table should display more elements
    (https://issues.rudder.io/issues/24807[#24807])
* Fixed: Empty space in global compliance bar
    (https://issues.rudder.io/issues/24788[#24788])

==== Web - Compliance & node report

* Fixed: Error when going to group page
    (https://issues.rudder.io/issues/24945[#24945])
* Fixed: Unexpected results when using compliance filters
    (https://issues.rudder.io/issues/24501[#24501])
* Fixed: Skipped directive does not show in node compliance tree
    (https://issues.rudder.io/issues/24097[#24097])

==== Web - Technique editor

* Fixed: Technique tags can be arbitrary objects
    (https://issues.rudder.io/issues/24888[#24888])

==== Web - Nodes & inventories

* Fixed: Node with inventories with bad certificate still get into Rudder
    (https://issues.rudder.io/issues/24815[#24815])
* Fixed: Node acceptation or refusal is not logged in event logs in 8.0
    (https://issues.rudder.io/issues/24869[#24869])

==== Miscellaneous

* Fixed: Option to force validation of change requests cannot be set via API
    (https://issues.rudder.io/issues/24845[#24845])

==== Web - Config management

* Fixed: Cannot open a directive if we search in the directive tree with the filter
    (https://issues.rudder.io/issues/24854[#24854])

==== Security

* Fixed: Creating elements with custom IDs can lead to inconsistent behavior
    (https://issues.rudder.io/issues/24856[#24856])
* Fixed: We cannot login with a user login containing uppercase letter if the option case-sensitivity is set to false
    (https://issues.rudder.io/issues/24839[#24839])

==== Performance and scalability

* Fixed: Software updates need to be special cased for performance in nodefact
    (https://issues.rudder.io/issues/24844[#24844])

==== Plugins integration

* Fixed: When there are more nodes than supported by licenses, no logs in webapp states it
    (https://issues.rudder.io/issues/24817[#24817])

==== Techniques

* Fixed: directory templateFolder should not be present when using directive File content
    (https://issues.rudder.io/issues/23974[#23974])

==== Documentation

* Fixed: Add example of how to get exact version to use with package methods
    (https://issues.rudder.io/issues/24736[#24736])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.2 (2024-04-30)

=== Changes


=== Bug fixes

==== Relay server or API

* Fixed: relayd stop runlog processing on invalid run info
    (https://issues.rudder.io/issues/24792[#24792])

==== API

* Fixed: Read-only user no longer has access to groups
    (https://issues.rudder.io/issues/24785[#24785])

==== Plugin manager cli

* Fixed: Add remove as uninstall alias
    (https://issues.rudder.io/issues/24782[#24782])

==== Agent

* Fixed: Switch back to old report file name in 8.1
    (https://issues.rudder.io/issues/24793[#24793])

==== Generic methods

* Fixed: Fix remaining warnings in apt_get module with python 3.12
    (https://issues.rudder.io/issues/24806[#24806])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.1 (2024-04-25)

=== Changes


==== Web - Compliance & node report

* Document stopping process before Postgres restore maintenance to avoid primary key constrain get corrupted
    (https://issues.rudder.io/issues/9752[#9752])

==== Documentation

* Update doc content for 8.1 release
    (https://issues.rudder.io/issues/24720[#24720])

==== Web - Config management

* Have a reset-keys button on the node screen
    (https://issues.rudder.io/issues/12791[#12791])

==== Web - UI & UX

* Nodes table should not be displayed in every tab of group details
    (https://issues.rudder.io/issues/24550[#24550])

==== System techniques

* Make inventory verbose when run in inform mode
    (https://issues.rudder.io/issues/24709[#24709])

==== Agent

* Import new gpg key in agent check
    (https://issues.rudder.io/issues/24216[#24216])

=== Bug fixes

==== Agent

* Fixed: Fusion inventory fails to report software with exotic names
    (https://issues.rudder.io/issues/24321[#24321])

==== Documentation

* Fixed: Add warning for properties not case sensitive on Windows
    (https://issues.rudder.io/issues/24234[#24234])

==== Performance and scalability

* Fixed: Directive details displaying leads to firing duplicated rest queries
    (https://issues.rudder.io/issues/24775[#24775])
* Fixed: Tree group is slow to load up because it contains the list of nodes in the tree
    (https://issues.rudder.io/issues/24723[#24723])
* Fixed: Dynamic groups are slow to compute in Rudder 8.1
    (https://issues.rudder.io/issues/24713[#24713])
* Fixed: ExpiredCompliance events are pilling up
    (https://issues.rudder.io/issues/24712[#24712])

==== Security

* Fixed: Groups node ids list in API is still exhaustive even with restricted tenant access
    (https://issues.rudder.io/issues/24708[#24708])
* Fixed: Disabled provisioned users can still login and use Rudder
    (https://issues.rudder.io/issues/24691[#24691])

==== Web - Compliance & node report

* Fixed: Broken compliance score for E
    (https://issues.rudder.io/issues/24767[#24767])
* Fixed: Directives applied twice don't show in rule details (they should be skipped)
    (https://issues.rudder.io/issues/22525[#22525])
* Fixed: Remove System compliance from Score
    (https://issues.rudder.io/issues/24734[#24734])

==== Web - Nodes & inventories

* Fixed: Accepting one selected pending node pops up a windows that accepts them all
    (https://issues.rudder.io/issues/24756[#24756])
* Fixed: Node properties override hovers are not well rendered
    (https://issues.rudder.io/issues/24497[#24497])
* Fixed: There is no easy way to copy a property/inventory variable name to clipboard
    (https://issues.rudder.io/issues/24498[#24498])
* Fixed: OS type / name are not always compared lower case
    (https://issues.rudder.io/issues/24703[#24703])
* Fixed: API authorization error: secure/api/compliance/nodes/{id}/system
    (https://issues.rudder.io/issues/24671[#24671])
* Fixed: Number of nodes in rule badge is not correct with tenants
    (https://issues.rudder.io/issues/24665[#24665])

==== Miscellaneous

* Fixed: Unable to log in - Server error
    (https://issues.rudder.io/issues/24757[#24757])
* Fixed: Badge style is not coherent in the whole UI
    (https://issues.rudder.io/issues/24742[#24742])
* Fixed: Empty description of technique parameter is not allowed
    (https://issues.rudder.io/issues/24698[#24698])

==== Plugin manager cli

* Fixed: Restart webapp even if some plugin installation failed
    (https://issues.rudder.io/issues/24750[#24750])
* Fixed: The webapp is not restarted when upgrading a plugin
    (https://issues.rudder.io/issues/24738[#24738])

==== Web - UI & UX

* Fixed: Score explanation should not move score element when text is too long
    (https://issues.rudder.io/issues/24744[#24744])
* Fixed: Group property table is cropped
    (https://issues.rudder.io/issues/24748[#24748])
* Fixed: Close icon does not close the modal for creating an API account
    (https://issues.rudder.io/issues/24741[#24741])
* Fixed: Score details element should always appear in the same order
    (https://issues.rudder.io/issues/24603[#24603])
* Fixed: The font weight of labels is too low
    (https://issues.rudder.io/issues/24717[#24717])
* Fixed: The ul and ol lists have the same markdown rendering
    (https://issues.rudder.io/issues/24605[#24605])
* Fixed: Node rudder information section is clipped and needs scroll
    (https://issues.rudder.io/issues/24611[#24611])
* Fixed: Group close button does not appear for readonly user
    (https://issues.rudder.io/issues/24682[#24682])
* Fixed: Beautify node properties tooltips label badge
    (https://issues.rudder.io/issues/24688[#24688])
* Fixed: Broken policy mode badge in rule header
    (https://issues.rudder.io/issues/24643[#24643])

==== Web - Maintenance

* Fixed: Webapp can fail to start with null sessionid error
    (https://issues.rudder.io/issues/24017[#24017])

==== Architecture - Code maintenance

* Fixed: MockLdapServer needs to be a class instantiated for each test
    (https://issues.rudder.io/issues/24719[#24719])

==== Web - Config management

* Fixed: Missing icon in the rule creation page
    (https://issues.rudder.io/issues/24487[#24487])
* Fixed: File picker is broken in 8.0
    (https://issues.rudder.io/issues/24679[#24679])

==== Web - Technique editor

* Fixed: Dropown condition on OS in method is not overlapping the next method
    (https://issues.rudder.io/issues/24543[#24543])

==== Techniques

* Fixed: The services technique is not compatible with Windows
    (https://issues.rudder.io/issues/24763[#24763])

==== Generic methods

* Fixed: Warning in yum module with python 3.12
    (https://issues.rudder.io/issues/24731[#24731])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Nicolas Ecarnot

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.0 (2024-04-11)

=== Changes


==== Documentation

* Prepare doc for 8.1 release
    (https://issues.rudder.io/issues/24705[#24705])

=== Bug fixes

==== Documentation

* Fixed: Typo in ncf 8.0
    (https://issues.rudder.io/issues/24693[#24693])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.0.rc1 (2024-04-08)

=== Changes


==== rudderc

* Reformat the rudderc technique Json schema to match the one published in the schemastore repository
    (https://issues.rudder.io/issues/24655[#24655])

==== Web - UI & UX

* Plugin information is too empty when there is no plugin
    (https://issues.rudder.io/issues/24352[#24352])
* Make a clear separation between the modification message and change audit log
    (https://issues.rudder.io/issues/24575[#24575])

==== Documentation

* Update the security policy
    (https://issues.rudder.io/issues/24608[#24608])

==== Plugin manager cli

* Improve the rudder package errors when using commands without any inputs
    (https://issues.rudder.io/issues/24601[#24601])

==== Architecture - Code maintenance

* Remove unused node function used by scale out relay plugin
    (https://issues.rudder.io/issues/24593[#24593])

==== Relay server or API

* relayd fail on reports containing non utf-8 characters
    (https://issues.rudder.io/issues/24565[#24565])
* Rename reports files for consistency with inventory
    (https://issues.rudder.io/issues/24604[#24604])

==== Techniques

* Package manager options also work on yum
    (https://issues.rudder.io/issues/24571[#24571])

=== Bug fixes

==== Performance and scalability

* Fixed: Rudder 8.1 doesn't start on large instance
    (https://issues.rudder.io/issues/24649[#24649])

==== Packaging

* Fixed: Add an inconditionnal restart of the slapd service in server postinst
    (https://issues.rudder.io/issues/24662[#24662])
* Fixed: Adapt rudder-agent packaging for Ubuntu 24.04
    (https://issues.rudder.io/issues/24569[#24569])
* Fixed: Disabled plugins are enabled when upgrading to 8.1
    (https://issues.rudder.io/issues/24568[#24568])

==== Security

* Fixed: Techniques should not be writable by apache in SELinux
    (https://issues.rudder.io/issues/24618[#24618])
* Fixed: Ignore RUSTSEC-2024-0332
    (https://issues.rudder.io/issues/24678[#24678])
* Fixed: Score API are not accessible to readonly user
    (https://issues.rudder.io/issues/24638[#24638])
* Fixed: Update dependencies to manage CVE-2024-1597  CVE-2024-22257 and CVE-2024-22243
    (https://issues.rudder.io/issues/24607[#24607])
* Fixed: Upgrade postgresql since CVE-2024-1597 and ignore other JS CVEs
    (https://issues.rudder.io/issues/24606[#24606])

==== Web - Nodes & inventories

* Fixed: When sending inventory with no software update anymore, inventory stored is not updated and keeps previous updates
    (https://issues.rudder.io/issues/24675[#24675])
* Fixed: Missing tenant information in API result for node details
    (https://issues.rudder.io/issues/24639[#24639])
* Fixed: Wrong error message when no result are found when using a compliance filter
    (https://issues.rudder.io/issues/24499[#24499])
* Fixed: Technical logs are not loaded when visiting the tab
    (https://issues.rudder.io/issues/24502[#24502])
* Fixed: when we search for a group in the search engine, the group page we arrive on is messed
    (https://issues.rudder.io/issues/24466[#24466])

==== Web - Config management

* Fixed: Typo "dynmaci" in logs
    (https://issues.rudder.io/issues/24669[#24669])
* Fixed: Group page UI is missing several key things
    (https://issues.rudder.io/issues/24489[#24489])

==== Plugin manager cli

* Fixed: Don't hardcode systemctl path
    (https://issues.rudder.io/issues/24676[#24676])
* Fixed: Improve apt/rpm package dependency detection
    (https://issues.rudder.io/issues/24677[#24677])
* Fixed: rudder package does not log in /var/log/rudder/rudder-pkg/rudder-pkg.log anymore
    (https://issues.rudder.io/issues/24484[#24484])
* Fixed: rudder-pkg don't inform that credential are not set up
    (https://issues.rudder.io/issues/24401[#24401])

==== Web - UI & UX

* Fixed: Typos in node state description
    (https://issues.rudder.io/issues/24668[#24668])
* Fixed: Only ignored status is displayed in Node page
    (https://issues.rudder.io/issues/24647[#24647])
* Fixed: Event log fold indicator has a weird color
    (https://issues.rudder.io/issues/24614[#24614])
* Fixed: Elm properties app is loaded multiple times
    (https://issues.rudder.io/issues/24416[#24416])
* Fixed: Status point next the node hostname doesn't provide much info
    (https://issues.rudder.io/issues/24361[#24361])
* Fixed: Button for archiving/deleting reports is not visible
    (https://issues.rudder.io/issues/24408[#24408])
* Fixed: system updates score details is empty when the node is up-to-date
    (https://issues.rudder.io/issues/24421[#24421])
* Fixed: Directive errors section is not consistent and always redirects to first tab
    (https://issues.rudder.io/issues/24590[#24590])
* Fixed: Number of software updates available is redundant
    (https://issues.rudder.io/issues/24602[#24602])
* Fixed: Typo in compliance score tooltip
    (https://issues.rudder.io/issues/24598[#24598])
* Fixed: When the group tab section is too large it cannot be scrolled
    (https://issues.rudder.io/issues/24547[#24547])
* Fixed: Tooltip on compliance in rule page is not rendered
    (https://issues.rudder.io/issues/24436[#24436])
* Fixed: JS error when opening directive form more than once
    (https://issues.rudder.io/issues/24563[#24563])
* Fixed: Add margin right to system updates badge
    (https://issues.rudder.io/issues/24557[#24557])
* Fixed: when sorting by targeted compliance, the No data available should always be last
    (https://issues.rudder.io/issues/24567[#24567])
* Fixed: Update js dependencies
    (https://issues.rudder.io/issues/24566[#24566])
* Fixed: cannot get to the bottom on Nodes/Settings pages
    (https://issues.rudder.io/issues/24251[#24251])
* Fixed: "Usage survey" setting select button is way too large
    (https://issues.rudder.io/issues/24510[#24510])
* Fixed: Resizing node tab in group page should stop at header
    (https://issues.rudder.io/issues/24549[#24549])

==== Miscellaneous

* Fixed: Enabling directive modal has margin between table and change log
    (https://issues.rudder.io/issues/24613[#24613])
* Fixed: Improvements on score: F score, rework tooltip, improve messages
    (https://issues.rudder.io/issues/24637[#24637])
* Fixed: Tags displayed in directive form are broken
    (https://issues.rudder.io/issues/24548[#24548])
* Fixed: API authorization menu bellow username is barely usable
    (https://issues.rudder.io/issues/24433[#24433])

==== System integration

* Fixed: SELinux error for downloading files
    (https://issues.rudder.io/issues/24589[#24589])

==== Web - Maintenance

* Fixed: Missing event for Relay Demote preventing demotion
    (https://issues.rudder.io/issues/24596[#24596])

==== Relay server or API

* Fixed: Teach relayd about a new report file name
    (https://issues.rudder.io/issues/24564[#24564])

==== Web - Technique editor

* Fixed: We can't save a technique with an enum value empty while required option is unchecked
    (https://issues.rudder.io/issues/24594[#24594])
* Fixed: Compilation output tab icon in technique is not aligned
    (https://issues.rudder.io/issues/24586[#24586])
* Fixed: We should not able to save a technique with no method inside
    (https://issues.rudder.io/issues/24579[#24579])
* Fixed: Persistent tooltip on info icon in methods
    (https://issues.rudder.io/issues/24419[#24419])
* Fixed: Delete modal in technique editor is offset
    (https://issues.rudder.io/issues/24453[#24453])

==== rudderc

* Fixed: Allow technique id starting with a number
    (https://issues.rudder.io/issues/24592[#24592])

==== Techniques

* Fixed: We should not be able to save a technique with empty enum parameters
    (https://issues.rudder.io/issues/24583[#24583])

==== API

* Fixed: API export of groups doesn't export the categories as dependencies
    (https://issues.rudder.io/issues/24295[#24295])
* Fixed: Update API doc version to 19
    (https://issues.rudder.io/issues/24581[#24581])

==== Documentation

* Fixed: Rudder-package cli help for install command should document file
    (https://issues.rudder.io/issues/24576[#24576])
* Fixed: Fix typo in file replace lines
    (https://issues.rudder.io/issues/24609[#24609])

==== System techniques

* Fixed: Add a unique component to inventory and inventory signature file name
    (https://issues.rudder.io/issues/24560[#24560])

==== Agent

* Fixed: Add a warning in "rudder agent info" when cf-execd is stopped
    (https://issues.rudder.io/issues/24620[#24620])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.0.beta2 (2024-03-22)

=== Changes


==== Documentation

* Document autoconditions
    (https://issues.rudder.io/issues/24535[#24535])

==== Architecture - Code maintenance

* Use enumeratum in place of sealarate for scala3 migration
    (https://issues.rudder.io/issues/24554[#24554])
*  Scala 3 syntax - branch 7.3 - core
    (https://issues.rudder.io/issues/24532[#24532])

==== Web - UI & UX

* Have list of available score available and define a display name
    (https://issues.rudder.io/issues/24527[#24527])
* Updating bootstrap columns css classes
    (https://issues.rudder.io/issues/24414[#24414])
* Improve technique parameter UI
    (https://issues.rudder.io/issues/24467[#24467])

==== CI

* Add PoC SBOM tooling
    (https://issues.rudder.io/issues/23356[#23356])

==== rudderc

* Add outcome conditions in rudderc docs
    (https://issues.rudder.io/issues/24302[#24302])

==== Plugin manager cli

* Improve rudder-package CLI doc
    (https://issues.rudder.io/issues/24389[#24389])
* Add the ability to specify the version to install
    (https://issues.rudder.io/issues/24373[#24373])

==== Generic methods

* Migrate the condition_from_command method to logger_v4
    (https://issues.rudder.io/issues/24377[#24377])
* Migrate inventory trigger method to logger_v4
    (https://issues.rudder.io/issues/24378[#24378])

=== Bug fixes

==== Packaging

* Fixed: Move plugins postupgrade after webapp restart
    (https://issues.rudder.io/issues/24449[#24449])

==== Agent

* Fixed: Typo in rudder-sign openssl 3 signing regex
    (https://issues.rudder.io/issues/24359[#24359])
* Fixed: rudder-sign fails on some machines with openssl 3
    (https://issues.rudder.io/issues/24320[#24320])

==== Documentation

* Fixed: Documentation on Windows installation misses the dependency on dsc plugin on the rudder server
    (https://issues.rudder.io/issues/24229[#24229])

==== Web - Config management

* Fixed: JS error when clicking on a technique with several version in directive screen
    (https://issues.rudder.io/issues/23400[#23400])
* Fixed: Overriding properties should have the same type as overridden
    (https://issues.rudder.io/issues/24236[#24236])
* Fixed: Rudder should finish to migrate all techniques when booting instead of stopping on first error
    (https://issues.rudder.io/issues/24515[#24515])

==== Web - UI & UX

* Fixed: Group parameters tab is always displayed
    (https://issues.rudder.io/issues/24546[#24546])
* Fixed: Display of group compliance in group information should be on the right
    (https://issues.rudder.io/issues/24381[#24381])
* Fixed: Score details are missing in nodes table
    (https://issues.rudder.io/issues/24355[#24355])
* Fixed: Nodes tables height is too small
    (https://issues.rudder.io/issues/24528[#24528])
* Fixed: Beautify global properties creation
    (https://issues.rudder.io/issues/24471[#24471])
* Fixed: Directive application preview  in pending nodes is broken
    (https://issues.rudder.io/issues/24324[#24324])
* Fixed: Nodes table can take almost all the height of the group page
    (https://issues.rudder.io/issues/24429[#24429])
* Fixed: The "condition" border appears on all methods in the tech. editor.
    (https://issues.rudder.io/issues/24519[#24519])
* Fixed: Tabs are missing their score
    (https://issues.rudder.io/issues/24447[#24447])
* Fixed: Node tabs have onclick event handlers assigned on unrendered elements
    (https://issues.rudder.io/issues/24405[#24405])
* Fixed: Directives button to set parameters on new directive does nothing
    (https://issues.rudder.io/issues/24428[#24428])
* Fixed: Missing space between badge score and number
    (https://issues.rudder.io/issues/24420[#24420])
* Fixed: Broken group creation UI
    (https://issues.rudder.io/issues/24335[#24335])
* Fixed: There is a search box in the node acceptation pop-up
    (https://issues.rudder.io/issues/24388[#24388])
* Fixed: Show logs button in node compliance tab does nothing
    (https://issues.rudder.io/issues/24383[#24383])
* Fixed: Dashboard container does not fit the height of the screen
    (https://issues.rudder.io/issues/24196[#24196])
* Fixed: Use bootstrap variables to define the default text size and font
    (https://issues.rudder.io/issues/24317[#24317])
* Fixed: Use bootstrap variables to define the default text size and font
    (https://issues.rudder.io/issues/24317[#24317])
* Fixed: Odd spacing with filters elements in node search page
    (https://issues.rudder.io/issues/24348[#24348])
* Fixed: Enforce policy mode in block method has a different display than audit
    (https://issues.rudder.io/issues/24382[#24382])
* Fixed: Update Rudder CSS to support bug fixes in plugins interface
    (https://issues.rudder.io/issues/24233[#24233])
* Fixed: The display of the description field is broken
    (https://issues.rudder.io/issues/24174[#24174])
* Fixed: Tooltips on system-updates in score-details is not standard
    (https://issues.rudder.io/issues/24316[#24316])
* Fixed: The height of node tabs is higher than the height of their container
    (https://issues.rudder.io/issues/24369[#24369])
* Fixed: Margin is too small on Global compliance details module in dashboard
    (https://issues.rudder.io/issues/24283[#24283])
* Fixed: Missing header separator in node search page
    (https://issues.rudder.io/issues/24347[#24347])
* Fixed: Popovers don't work anymore
    (https://issues.rudder.io/issues/24345[#24345])
* Fixed: Some dropdowns display are broken
    (https://issues.rudder.io/issues/24323[#24323])
* Fixed: Odd rendering on tooltips in search node page
    (https://issues.rudder.io/issues/24349[#24349])
* Fixed: Tooltips persisted on refresh button on the table in search node page
    (https://issues.rudder.io/issues/24351[#24351])
* Fixed: Description in API account is outside of the header
    (https://issues.rudder.io/issues/24354[#24354])
* Fixed: Warning icon on log out should be on healthcheck heart logo
    (https://issues.rudder.io/issues/24346[#24346])
* Fixed: Checkbox for selecting all nodes for acceptance doesn't work
    (https://issues.rudder.io/issues/24311[#24311])
* Fixed: Filter button on group page doesn't do anything
    (https://issues.rudder.io/issues/24336[#24336])
* Fixed: Modal titles are unreadable
    (https://issues.rudder.io/issues/24322[#24322])
* Fixed: Wrong lalel on tab in compliance group
    (https://issues.rudder.io/issues/24313[#24313])
* Fixed: Display of node compliance info message is broken
    (https://issues.rudder.io/issues/24310[#24310])
* Fixed: Errors in event log for deleted techniques
    (https://issues.rudder.io/issues/24277[#24277])
* Fixed: When the documentation of a technique is very long, the user has to scroll a long way before creating a directive from this technique
    (https://issues.rudder.io/issues/23881[#23881])

==== rudderc

* Fixed: rudderc test should dump the report file path or workdir when a check step fails
    (https://issues.rudder.io/issues/24523[#24523])
* Fixed: Broken detection of incorrect parameter names
    (https://issues.rudder.io/issues/24371[#24371])

==== Security

* Fixed: npm dep security checks are ignored
    (https://issues.rudder.io/issues/24522[#24522])
* Fixed: Ignore angularjs DoS in 7.3
    (https://issues.rudder.io/issues/24517[#24517])

==== API

* Fixed: Async tests are failing for node certificates
    (https://issues.rudder.io/issues/24520[#24520])
* Fixed: Display compliance for system groups
    (https://issues.rudder.io/issues/24363[#24363])
* Fixed: API popup for copying token does not appear
    (https://issues.rudder.io/issues/24391[#24391])
* Fixed: Merge user-management feature branch to 7.3
    (https://issues.rudder.io/issues/24342[#24342])

==== Miscellaneous

* Fixed: It is hard to differentiate between real values and placeholders in inputs
    (https://issues.rudder.io/issues/24463[#24463])
* Fixed: Cannot translate campaign on boot, leading to skipped events
    (https://issues.rudder.io/issues/24441[#24441])
* Fixed: Existing deleted user managed by file cannot be reactivated
    (https://issues.rudder.io/issues/24318[#24318])

==== Relay server or API

* Fixed: Vulnerability in mio
    (https://issues.rudder.io/issues/24516[#24516])

==== Plugin manager cli

* Fixed: Add a quiet argument to rudder-package
    (https://issues.rudder.io/issues/24490[#24490])
* Fixed: Broken pipe when piping rudder-package output
    (https://issues.rudder.io/issues/24432[#24432])
* Fixed: Don't fail on malformed index entries
    (https://issues.rudder.io/issues/24372[#24372])

==== System integration

* Fixed: Missing primary key statement for user sessions table creation when migrating
    (https://issues.rudder.io/issues/24456[#24456])
* Fixed: Rename policy_mode to policy_mode_override
    (https://issues.rudder.io/issues/24380[#24380])

==== Web - Compliance & node report

* Fixed: Group compliance stays empty
    (https://issues.rudder.io/issues/24366[#24366])

==== Architecture - Internal libs

* Fixed: windows Node in tests has invalid  certificate, failing test in plugin windows
    (https://issues.rudder.io/issues/24289[#24289])

==== Web - Technique editor

* Fixed: The technique editor enforces optional parameter presence
    (https://issues.rudder.io/issues/24350[#24350])
* Fixed: sysctl value generic method is not reporting
    (https://issues.rudder.io/issues/20853[#20853])

==== System techniques

* Fixed: Broken techniques qa-test
    (https://issues.rudder.io/issues/24448[#24448])
* Fixed: Extend autoconditions to allow string values
    (https://issues.rudder.io/issues/24412[#24412])

==== Generic methods

* Fixed: Regex in file replace line must not match the string used as replacement
    (https://issues.rudder.io/issues/24537[#24537])
* Fixed: Missing constraint for enforce parameter in method File content
    (https://issues.rudder.io/issues/24458[#24458])
* Fixed: The yum module should install local package with yum
    (https://issues.rudder.io/issues/24367[#24367])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.0.beta1 (2024-03-04)

=== Changes


==== Packaging

* Import new gpg key in rpm postinst
    (https://issues.rudder.io/issues/24070[#24070])

==== Agent

* We should log an error when a hook timeouts
    (https://issues.rudder.io/issues/23936[#23936])

==== Documentation

* Adapt doc for 8.1
    (https://issues.rudder.io/issues/24033[#24033])

==== API

* Add alternative api doc build with RapiDoc
    (https://issues.rudder.io/issues/24286[#24286])
* Add manufacturer field in create node API
    (https://issues.rudder.io/issues/24091[#24091])

==== Plugin manager cli

* Rudder-package should log the package scripts outputs and errors
    (https://issues.rudder.io/issues/24238[#24238])

==== Web - Compliance & node report

* Initialize score on webapp start up
    (https://issues.rudder.io/issues/24178[#24178])

==== Architecture - Code maintenance

* Prepare migration to Scala 3 - Version 8.1 part 1
    (https://issues.rudder.io/issues/24175[#24175])
* Prepare migration to Scala 3 - Version 7.3 part 1
    (https://issues.rudder.io/issues/24171[#24171])

==== Web - Technique editor

* Add a select type for technique parameter
    (https://issues.rudder.io/issues/24099[#24099])

==== Architecture - Internal libs

* Add score enum for score in database
    (https://issues.rudder.io/issues/24147[#24147])

==== Web - UI & UX

* Editing big properties in elm-based properties interface is very inconvenient
    (https://issues.rudder.io/issues/23487[#23487])
* Improve display of audit/enforce mode in technique editor
    (https://issues.rudder.io/issues/24080[#24080])
* Display the list of pending change requests related to the selected rule
    (https://issues.rudder.io/issues/21931[#21931])

=== Bug fixes

==== Packaging

* Fixed: Rudder upgrade may fail on postgres script
    (https://issues.rudder.io/issues/24232[#24232])
* Fixed: add apr-util-db as a dependency for al2023
    (https://issues.rudder.io/issues/24061[#24061])
* Fixed: RHEL9 policies have an incompatible sh shebang
    (https://issues.rudder.io/issues/24057[#24057])

==== Documentation

* Fixed: Import/Export archive feature is no more in beta
    (https://issues.rudder.io/issues/24290[#24290])
* Fixed: layout of https://docs.rudder.io/reference/8.0/administration/server.html#_importing_configuration is broken
    (https://issues.rudder.io/issues/24190[#24190])
* Fixed: Broken doc build
    (https://issues.rudder.io/issues/24136[#24136])
* Fixed: case-sensitivity parameter of rudder-user.xml is not documented
    (https://issues.rudder.io/issues/24024[#24024])

==== rudderc

* Fixed: Add integration tests to rudderc
    (https://issues.rudder.io/issues/24291[#24291])
* Fixed: rudderc canonifies already canonified condition expression resulting in loss of logic operators such as ) and |
    (https://issues.rudder.io/issues/24226[#24226])
* Fixed: Missing method constraints in rudderc
    (https://issues.rudder.io/issues/24100[#24100])

==== CI

* Fixed: Adapt Jenkinsfile after warning-ng plugin upgrade
    (https://issues.rudder.io/issues/24301[#24301])

==== API

* Fixed: Empty role in users file is logged as warning
    (https://issues.rudder.io/issues/24285[#24285])
* Fixed: Bad description for serialNumber attribute of machine
    (https://issues.rudder.io/issues/24141[#24141])
* Fixed: For delete API for node, add a message for node already deleted
    (https://issues.rudder.io/issues/24129[#24129])
* Fixed: If REST url ends with .com, then the .com is removed from path segments
    (https://issues.rudder.io/issues/24036[#24036])

==== Web - Technique editor

* Fixed: An errors occurs within technique editor resource manager when we create a folder that has the same name than another parent folder
    (https://issues.rudder.io/issues/24276[#24276])
* Fixed: when we have conditions on blocks, the condition text is not correctly positioned when the block is opened
    (https://issues.rudder.io/issues/24150[#24150])
* Fixed: Technique import doesn't refresh the list of method in technique editor
    (https://issues.rudder.io/issues/24123[#24123])
* Fixed: Action dropdown list in technique editor goes under parameters
    (https://issues.rudder.io/issues/24122[#24122])
* Fixed: 404 not found in technique editor resource manager Ajax query
    (https://issues.rudder.io/issues/24084[#24084])
* Fixed: Technique editor method filters are not aligned correctly
    (https://issues.rudder.io/issues/23885[#23885])

==== Web - UI & UX

* Fixed: Some tabs do no longer call Elm ports on click
    (https://issues.rudder.io/issues/24287[#24287])
* Fixed: The chevron down icon for "Status" is barely visible
    (https://issues.rudder.io/issues/24197[#24197])
* Fixed: Directive parameters UI details changed since bootstrap 5
    (https://issues.rudder.io/issues/24176[#24176])
* Fixed: Hooks page looks broken since bootstrap 5 update
    (https://issues.rudder.io/issues/24204[#24204])
* Fixed: Add space in the login form between inputs
    (https://issues.rudder.io/issues/24194[#24194])
* Fixed: The active tab indicator no longer works
    (https://issues.rudder.io/issues/24170[#24170])
* Fixed: Active buttons no longer have shadow
    (https://issues.rudder.io/issues/24172[#24172])
* Fixed: Jstree links are broken
    (https://issues.rudder.io/issues/24152[#24152])
* Fixed: System updates badges css in compliance score is not applied
    (https://issues.rudder.io/issues/24155[#24155])
* Fixed: Add score on top of tabs
    (https://issues.rudder.io/issues/24096[#24096])
* Fixed: Links and buttons don't have the right colour since the bootstrap update
    (https://issues.rudder.io/issues/24124[#24124])
* Fixed: Unknown rule targets UI is missing icon and border
    (https://issues.rudder.io/issues/24102[#24102])
* Fixed: Group compliance view does not give global and targeted compliance definitions
    (https://issues.rudder.io/issues/24040[#24040])
* Fixed: System updates badges in compliance score have no css
    (https://issues.rudder.io/issues/24104[#24104])
* Fixed: Fix small ui error in the rules information tab
    (https://issues.rudder.io/issues/24079[#24079])
* Fixed: Add margin-bottom to form group
    (https://issues.rudder.io/issues/24048[#24048])
* Fixed: Fix default font size and menu toggle
    (https://issues.rudder.io/issues/24041[#24041])
* Fixed: Fix the Settings page and its components following the bootstrap 5 update
    (https://issues.rudder.io/issues/24035[#24035])

==== Miscellaneous

* Fixed: Incorrect error message about change request creation failure when it is not needed
    (https://issues.rudder.io/issues/24278[#24278])

==== Plugin manager cli

* Fixed: rudder-pkg stops at first install error on the upgrade-all command
    (https://issues.rudder.io/issues/24201[#24201])
* Fixed: Pylint test fails with an exception
    (https://issues.rudder.io/issues/24205[#24205])
* Fixed: rudder package unpacks scripts.txz in the wrong place
    (https://issues.rudder.io/issues/24131[#24131])
* Fixed: Broken parsing of 8.1 plugin index
    (https://issues.rudder.io/issues/24107[#24107])
* Fixed: Allow running rudder-package with a malformed index
    (https://issues.rudder.io/issues/24072[#24072])
* Fixed: script.txz is not scripts.txz
    (https://issues.rudder.io/issues/24060[#24060])
* Fixed: script.txz is not scripts.txz
    (https://issues.rudder.io/issues/24060[#24060])

==== Architecture - Code maintenance

* Fixed: Make spotless only check source of current project
    (https://issues.rudder.io/issues/24177[#24177])
* Fixed: Missing policy generation status
    (https://issues.rudder.io/issues/24117[#24117])
* Fixed: Backport test correction for allowed networks
    (https://issues.rudder.io/issues/24093[#24093])

==== Web - Compliance & node report

* Fixed: Add missing score
    (https://issues.rudder.io/issues/24158[#24158])
* Fixed: lost audit/enforce on the node compliance page
    (https://issues.rudder.io/issues/23930[#23930])

==== Web - Config management

* Fixed: We must not generate policies for nodes without a well formed certificate
    (https://issues.rudder.io/issues/24112[#24112])
* Fixed: when we import an archive and rules contains non existent targets, the targets can't be removed from the rules
    (https://issues.rudder.io/issues/24007[#24007])

==== Web - Maintenance

* Fixed: Archiving allows to read inconsistent active technique category ids
    (https://issues.rudder.io/issues/24011[#24011])

==== Security

* Fixed: CSP headers are duplicated and missing report-uri
    (https://issues.rudder.io/issues/24101[#24101])
* Fixed: Implementing CSP headers without duplicating Lift scripts
    (https://issues.rudder.io/issues/24062[#24062])
* Fixed: Vulnerability in shlex Rust lib
    (https://issues.rudder.io/issues/24069[#24069])
* Fixed: Ignore cve on ext-js (unused dependency)
    (https://issues.rudder.io/issues/24071[#24071])
* Fixed: DoS vuln in h2 lib in relayd
    (https://issues.rudder.io/issues/24068[#24068])

==== System integration

* Fixed: Score table migration
    (https://issues.rudder.io/issues/24090[#24090])

==== Performance and scalability

* Fixed: Compliance has unoptimized usage of map view and policy mode computation
    (https://issues.rudder.io/issues/24047[#24047])

==== Architecture - Internal libs

* Fixed: Wrong agent type for dsc node in tests
    (https://issues.rudder.io/issues/24051[#24051])

==== Techniques

* Fixed: File content directive add 4 spaces at the beginning of the line
    (https://issues.rudder.io/issues/24022[#24022])

==== Agent

* Fixed: rudder agent modified misses some files
    (https://issues.rudder.io/issues/24133[#24133])
* Fixed: Prompt warning and ask confirmation for factory reset
    (https://issues.rudder.io/issues/23978[#23978])

==== Generic methods

* Fixed: Deprecate "Package check installed"
    (https://issues.rudder.io/issues/24120[#24120])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.0.alpha1 (2024-01-19)

=== Changes


==== Packaging

* Make the rudder-agent package depends of python
    (https://issues.rudder.io/issues/23931[#23931])
* Update packaging scripts for rudder-package
    (https://issues.rudder.io/issues/23795[#23795])
* Add rudder-package to the relay package
    (https://issues.rudder.io/issues/23629[#23629])

==== Web - Compliance & node report

* Display group compliance
    (https://issues.rudder.io/issues/23926[#23926])
* Display group compliance
    (https://issues.rudder.io/issues/23926[#23926])

==== Architecture - Code maintenance

* Remove early return to prepare to Scala3 migration in box sequence/traverse
    (https://issues.rudder.io/issues/23948[#23948])
* Group all node related access into one NodeFactRepository
    (https://issues.rudder.io/issues/23727[#23727])
* Upgrading Bootstrap to version 5
    (https://issues.rudder.io/issues/23593[#23593])
* Integrate Sass with front-end development tools
    (https://issues.rudder.io/issues/23548[#23548])

==== System integration

* Add users table to better track user and sessions
    (https://issues.rudder.io/issues/23440[#23440])

==== rudderc

* Update the rudderc technique json schema to match the minimal SchemaStore expectation
    (https://issues.rudder.io/issues/23966[#23966])
* Improve rudder-package error messages
    (https://issues.rudder.io/issues/23842[#23842])
* Make rudderc able to compile techniques using a per method policy mode override
    (https://issues.rudder.io/issues/23799[#23799])
* Make sources compatible with Windows
    (https://issues.rudder.io/issues/23573[#23573])

==== Web - UI & UX

* Rudder Score for Nodes
    (https://issues.rudder.io/issues/23929[#23929])
* Reorganise the node summary tab
    (https://issues.rudder.io/issues/23854[#23854])
* Common style for Rust CLI output
    (https://issues.rudder.io/issues/23865[#23865])
* Reorganize the header of the node page
    (https://issues.rudder.io/issues/23826[#23826])

==== Server components

* Make the (now) various Rust CLIs more consistent
    (https://issues.rudder.io/issues/23852[#23852])
* Add version parsing to rudder-package
    (https://issues.rudder.io/issues/23687[#23687])

==== API

* Update API doc tooling
    (https://issues.rudder.io/issues/23860[#23860])

==== Plugin manager cli

* Update rudder-package cli for better UX
    (https://issues.rudder.io/issues/23838[#23838])
* Implement missing commands
    (https://issues.rudder.io/issues/23780[#23780])
* Document the rpkg format
    (https://issues.rudder.io/issues/23793[#23793])
* Add enable/disable commands to rudder-package
    (https://issues.rudder.io/issues/23791[#23791])
* Make rudder-package able to download plugin licenses
    (https://issues.rudder.io/issues/23782[#23782])
* Make rudder-package able to uninstall packages
    (https://issues.rudder.io/issues/23773[#23773])
* Add signature validation for plugins
    (https://issues.rudder.io/issues/23776[#23776])
* Make rudder-package able to install plugins from the repository
    (https://issues.rudder.io/issues/23772[#23772])
* Stop rudder-package if not run as root
    (https://issues.rudder.io/issues/23771[#23771])
* Restart the webapp after plugin installation
    (https://issues.rudder.io/issues/23769[#23769])
* Make an install subcommand for the new rudder-package
    (https://issues.rudder.io/issues/23767[#23767])
* Make rudder-package able to track installed files
    (https://issues.rudder.io/issues/23759[#23759])
* Add dependency support to rudder-package
    (https://issues.rudder.io/issues/23739[#23739])
* rudder-package should stroingly type any plugin version
    (https://issues.rudder.io/issues/23695[#23695])
* Add a downloader for files from plugin repository
    (https://issues.rudder.io/issues/23690[#23690])
* Add configuration file path to the cli args
    (https://issues.rudder.io/issues/23632[#23632])
* Add logging basics
    (https://issues.rudder.io/issues/23630[#23630])
* Add configuration file parser to rudder-package
    (https://issues.rudder.io/issues/23627[#23627])
* Implement CI config for rudder-package
    (https://issues.rudder.io/issues/23625[#23625])

==== Architecture - Dependencies

* Update js dependencies
    (https://issues.rudder.io/issues/23825[#23825])
* Update Scala dependencies
    (https://issues.rudder.io/issues/23758[#23758])
* Update to chimney 0.8.2
    (https://issues.rudder.io/issues/23737[#23737])

==== Agent

* PoC for a minimal inventory engine
    (https://issues.rudder.io/issues/23033[#23033])

=== Bug fixes

==== Packaging

* Fixed: Embed openssl cli on 7.3
    (https://issues.rudder.io/issues/24019[#24019])
* Fixed: Abort server build if rudder.war is less than 1Mb
    (https://issues.rudder.io/issues/23958[#23958])
* Fixed: Update C dependencies
    (https://issues.rudder.io/issues/23794[#23794])
* Fixed: Simplify systemd service config
    (https://issues.rudder.io/issues/23712[#23712])
* Fixed: Exclude target dirs in qa-test
    (https://issues.rudder.io/issues/23980[#23980])
* Fixed: rudder-packages does not build the right Rust project
    (https://issues.rudder.io/issues/23904[#23904])
* Fixed: Update Rust dependencies
    (https://issues.rudder.io/issues/23803[#23803])

==== Documentation

* Fixed: Update note for rudder-package
    (https://issues.rudder.io/issues/23960[#23960])
* Fixed: Fixed ref in documentation for centralized page
    (https://issues.rudder.io/issues/23917[#23917])

==== Web - UI & UX

* Fixed: Group compliance tab is loaded only with a double-click
    (https://issues.rudder.io/issues/24034[#24034])
* Fixed: Replace glyphicon icons with font-awesome
    (https://issues.rudder.io/issues/24031[#24031])
* Fixed: Add policy mode info in group compliance details
    (https://issues.rudder.io/issues/24028[#24028])
* Fixed: In quicksearch, query error are not displayed which leads to infinite loading result
    (https://issues.rudder.io/issues/23402[#23402])
* Fixed: New campaigns button does not conform to our graphic charter
    (https://issues.rudder.io/issues/23938[#23938])
* Fixed: The API accounts creation and editing popup no longer appears
    (https://issues.rudder.io/issues/23943[#23943])
* Fixed: A new group display no nodes while all linux are selected
    (https://issues.rudder.io/issues/22170[#22170])
* Fixed: The health check page has an unnecessary "Show check list" button in 8.0
    (https://issues.rudder.io/issues/23916[#23916])
* Fixed: The health check page has an unnecessary "Show check list" button
    (https://issues.rudder.io/issues/23891[#23891])
* Fixed: The "Category" field in the technique editor is displayed as a mandatory field even if it is an unmutable one
    (https://issues.rudder.io/issues/23883[#23883])
* Fixed: Remove the "Edit techniques" button from the directives webpage
    (https://issues.rudder.io/issues/23877[#23877])
* Fixed: Rename the "Create global property" button in "Create"
    (https://issues.rudder.io/issues/23878[#23878])

==== Security

* Fixed: Generate runtime evaluated variables in windows policies as templates instead of Powershell expansion
    (https://issues.rudder.io/issues/23973[#23973])
* Fixed: Vulnerability in zerocopy crate
    (https://issues.rudder.io/issues/24010[#24010])
* Fixed: Ignore CVE-2023-51074 (no impact, score too high)
    (https://issues.rudder.io/issues/24005[#24005])
* Fixed: Unimportant CVE on logback and icu4j
    (https://issues.rudder.io/issues/23983[#23983])
* Fixed: Unaffected CVE on jgit and logback
    (https://issues.rudder.io/issues/23982[#23982])

==== Performance and scalability

* Fixed: Healthcheck on file descriptor should be max 64000
    (https://issues.rudder.io/issues/24006[#24006])

==== Plugin manager cli

* Fixed: rudder package fails to install local rpkg
    (https://issues.rudder.io/issues/23965[#23965])
* Fixed: rudder-package fails to compile in release mode
    (https://issues.rudder.io/issues/23949[#23949])
* Fixed: Make check-connection an option of the update command
    (https://issues.rudder.io/issues/23834[#23834])
* Fixed: Use quick_xml for xml edition
    (https://issues.rudder.io/issues/23781[#23781])

==== Web - Config management

* Fixed: Static group which depends on dynamic subgroup must be forbidden
    (https://issues.rudder.io/issues/18952[#18952])
* Fixed: Rudder agent scheduled runs are not triggered at regular interval
    (https://issues.rudder.io/issues/23956[#23956])

==== Server components

* Fixed: Waning log spam when disabled rudder_compute_changes setting
    (https://issues.rudder.io/issues/23969[#23969])

==== Web - Nodes & inventories

* Fixed: Missing icon for windows 2022
    (https://issues.rudder.io/issues/23972[#23972])
* Fixed: We can accept a node with an existing hostname even if node_accept_duplicated_hostname is false
    (https://issues.rudder.io/issues/22197[#22197])

==== rudderc

* Fixed: Improve rudderc error message when a parameter is missing from a method call
    (https://issues.rudder.io/issues/23953[#23953])
* Fixed: Improve rudderc test error message when no library is passed in the parameters
    (https://issues.rudder.io/issues/23941[#23941])
* Fixed: rudderc code is not properly formatted due to a failed resolution of merge
    (https://issues.rudder.io/issues/23940[#23940])
* Fixed: Parameters are not properly interpreted in method call conditions
    (https://issues.rudder.io/issues/23925[#23925])
* Fixed: tests output should be displayed even if not valid utf-8
    (https://issues.rudder.io/issues/23788[#23788])
* Fixed: rudderc export should use category from technique if existing
    (https://issues.rudder.io/issues/23787[#23787])
* Fixed: Add GPG signature verification to rudder-package
    (https://issues.rudder.io/issues/23711[#23711])

==== Architecture - Code maintenance

* Fixed: Lift Async system is not able to find spring SecurityContextHolder
    (https://issues.rudder.io/issues/23920[#23920])
* Fixed: Inventory accept test sometimes fails on callback check
    (https://issues.rudder.io/issues/23786[#23786])
* Fixed: Update to zio-json 0.6.2
    (https://issues.rudder.io/issues/23409[#23409])

==== Architecture - Internal libs

* Fixed: Plugin license implementation is not coherent with interface
    (https://issues.rudder.io/issues/23932[#23932])

==== Miscellaneous

* Fixed: Change request on special:all_nodes_without_role lead to error
    (https://issues.rudder.io/issues/23446[#23446])

==== Techniques

* Fixed: FileTemplate technique fails with an error on the Directory-Create method call
    (https://issues.rudder.io/issues/23954[#23954])

==== Agent

* Fixed: Rudder agent still contains some syslog reporting handling code
    (https://issues.rudder.io/issues/23946[#23946])
* Fixed: when a node has capitals in its hostname agent history doesn't show manual runs
    (https://issues.rudder.io/issues/23740[#23740])

==== Generic methods

* Fixed: Replace md5 by sha256 in time_lib
    (https://issues.rudder.io/issues/23070[#23070])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Alexis TARUSSIO

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

