= Change logs for Rudder 8.1

==  Rudder 8.1.2 (2024-04-30)

=== Changes


=== Bug fixes

==== Relay server or API

* Fixed: relayd stop runlog processing on invalid run info
    (https://issues.rudder.io/issues/24792[#24792])

==== API

* Fixed: Read-only user no longer has access to groups
    (https://issues.rudder.io/issues/24785[#24785])

==== Plugin manager cli

* Fixed: Add remove as uninstall alias
    (https://issues.rudder.io/issues/24782[#24782])

==== Agent

* Fixed: Switch back to old report file name in 8.1
    (https://issues.rudder.io/issues/24793[#24793])

==== Generic methods

* Fixed: Fix remaining warnings in apt_get module with python 3.12
    (https://issues.rudder.io/issues/24806[#24806])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.1 (2024-04-25)

=== Changes


==== Web - Compliance & node report

* Document stopping process before Postgres restore maintenance to avoid primary key constrain get corrupted
    (https://issues.rudder.io/issues/9752[#9752])

==== Documentation

* Update doc content for 8.1 release
    (https://issues.rudder.io/issues/24720[#24720])

==== Web - Config management

* Have a reset-keys button on the node screen
    (https://issues.rudder.io/issues/12791[#12791])

==== Web - UI & UX

* Nodes table should not be displayed in every tab of group details
    (https://issues.rudder.io/issues/24550[#24550])

==== System techniques

* Make inventory verbose when run in inform mode
    (https://issues.rudder.io/issues/24709[#24709])

==== Agent

* Import new gpg key in agent check
    (https://issues.rudder.io/issues/24216[#24216])

=== Bug fixes

==== Agent

* Fixed: Fusion inventory fails to report software with exotic names
    (https://issues.rudder.io/issues/24321[#24321])

==== Documentation

* Fixed: Add warning for properties not case sensitive on Windows
    (https://issues.rudder.io/issues/24234[#24234])

==== Performance and scalability

* Fixed: Directive details displaying leads to firing duplicated rest queries
    (https://issues.rudder.io/issues/24775[#24775])
* Fixed: Tree group is slow to load up because it contains the list of nodes in the tree
    (https://issues.rudder.io/issues/24723[#24723])
* Fixed: Dynamic groups are slow to compute in Rudder 8.1
    (https://issues.rudder.io/issues/24713[#24713])
* Fixed: ExpiredCompliance events are pilling up
    (https://issues.rudder.io/issues/24712[#24712])

==== Security

* Fixed: Groups node ids list in API is still exhaustive even with restricted tenant access
    (https://issues.rudder.io/issues/24708[#24708])
* Fixed: Disabled provisioned users can still login and use Rudder
    (https://issues.rudder.io/issues/24691[#24691])

==== Web - Compliance & node report

* Fixed: Broken compliance score for E
    (https://issues.rudder.io/issues/24767[#24767])
* Fixed: Directives applied twice don't show in rule details (they should be skipped)
    (https://issues.rudder.io/issues/22525[#22525])
* Fixed: Remove System compliance from Score
    (https://issues.rudder.io/issues/24734[#24734])

==== Web - Nodes & inventories

* Fixed: Accepting one selected pending node pops up a windows that accepts them all
    (https://issues.rudder.io/issues/24756[#24756])
* Fixed: Node properties override hovers are not well rendered
    (https://issues.rudder.io/issues/24497[#24497])
* Fixed: There is no easy way to copy a property/inventory variable name to clipboard
    (https://issues.rudder.io/issues/24498[#24498])
* Fixed: OS type / name are not always compared lower case
    (https://issues.rudder.io/issues/24703[#24703])
* Fixed: API authorization error: secure/api/compliance/nodes/{id}/system
    (https://issues.rudder.io/issues/24671[#24671])
* Fixed: Number of nodes in rule badge is not correct with tenants
    (https://issues.rudder.io/issues/24665[#24665])

==== Miscellaneous

* Fixed: Unable to log in - Server error
    (https://issues.rudder.io/issues/24757[#24757])
* Fixed: Badge style is not coherent in the whole UI 
    (https://issues.rudder.io/issues/24742[#24742])
* Fixed: Empty description of technique parameter is not allowed
    (https://issues.rudder.io/issues/24698[#24698])

==== Plugin manager cli

* Fixed: Restart webapp even if some plugin installation failed
    (https://issues.rudder.io/issues/24750[#24750])
* Fixed: The webapp is not restarted when upgrading a plugin
    (https://issues.rudder.io/issues/24738[#24738])

==== Web - UI & UX

* Fixed: Score explanation should not move score element when text is too long
    (https://issues.rudder.io/issues/24744[#24744])
* Fixed: Group property table is cropped
    (https://issues.rudder.io/issues/24748[#24748])
* Fixed: Close icon does not close the modal for creating an API account
    (https://issues.rudder.io/issues/24741[#24741])
* Fixed: Score details element should always appear in the same order
    (https://issues.rudder.io/issues/24603[#24603])
* Fixed: The font weight of labels is too low
    (https://issues.rudder.io/issues/24717[#24717])
* Fixed: The ul and ol lists have the same markdown rendering
    (https://issues.rudder.io/issues/24605[#24605])
* Fixed: Node rudder information section is clipped and needs scroll 
    (https://issues.rudder.io/issues/24611[#24611])
* Fixed: Group close button does not appear for readonly user
    (https://issues.rudder.io/issues/24682[#24682])
* Fixed: Beautify node properties tooltips label badge
    (https://issues.rudder.io/issues/24688[#24688])
* Fixed: Broken policy mode badge in rule header
    (https://issues.rudder.io/issues/24643[#24643])

==== Web - Maintenance

* Fixed: Webapp can fail to start with null sessionid error 
    (https://issues.rudder.io/issues/24017[#24017])

==== Architecture - Code maintenance

* Fixed: MockLdapServer needs to be a class instantiated for each test
    (https://issues.rudder.io/issues/24719[#24719])

==== Web - Config management

* Fixed: Missing icon in the rule creation page
    (https://issues.rudder.io/issues/24487[#24487])
* Fixed: File picker is broken in 8.0
    (https://issues.rudder.io/issues/24679[#24679])

==== Web - Technique editor

* Fixed: Dropown condition on OS in method is not overlapping the next method
    (https://issues.rudder.io/issues/24543[#24543])

==== Techniques

* Fixed: The services technique is not compatible with Windows
    (https://issues.rudder.io/issues/24763[#24763])

==== Generic methods

* Fixed: Warning in yum module with python 3.12
    (https://issues.rudder.io/issues/24731[#24731])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Nicolas Ecarnot

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.0 (2024-04-11)

=== Changes


==== Documentation

* Prepare doc for 8.1 release
    (https://issues.rudder.io/issues/24705[#24705])

=== Bug fixes

==== Documentation

* Fixed: Typo in ncf 8.0
    (https://issues.rudder.io/issues/24693[#24693])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.0.rc1 (2024-04-08)

=== Changes


==== rudderc

* Reformat the rudderc technique Json schema to match the one published in the schemastore repository
    (https://issues.rudder.io/issues/24655[#24655])

==== Web - UI & UX

* Plugin information is too empty when there is no plugin
    (https://issues.rudder.io/issues/24352[#24352])
* Make a clear separation between the modification message and change audit log
    (https://issues.rudder.io/issues/24575[#24575])

==== Documentation

* Update the security policy
    (https://issues.rudder.io/issues/24608[#24608])

==== Plugin manager cli

* Improve the rudder package errors when using commands without any inputs
    (https://issues.rudder.io/issues/24601[#24601])

==== Architecture - Code maintenance

* Remove unused node function used by scale out relay plugin
    (https://issues.rudder.io/issues/24593[#24593])

==== Relay server or API

* relayd fail on reports containing non utf-8 characters
    (https://issues.rudder.io/issues/24565[#24565])
* Rename reports files for consistency with inventory
    (https://issues.rudder.io/issues/24604[#24604])

==== Techniques

* Package manager options also work on yum
    (https://issues.rudder.io/issues/24571[#24571])

=== Bug fixes

==== Performance and scalability

* Fixed: Rudder 8.1 doesn't start on large instance
    (https://issues.rudder.io/issues/24649[#24649])

==== Packaging

* Fixed: Add an inconditionnal restart of the slapd service in server postinst
    (https://issues.rudder.io/issues/24662[#24662])
* Fixed: Adapt rudder-agent packaging for Ubuntu 24.04
    (https://issues.rudder.io/issues/24569[#24569])
* Fixed: Disabled plugins are enabled when upgrading to 8.1
    (https://issues.rudder.io/issues/24568[#24568])

==== Security

* Fixed: Techniques should not be writable by apache in SELinux
    (https://issues.rudder.io/issues/24618[#24618])
* Fixed: Ignore RUSTSEC-2024-0332 
    (https://issues.rudder.io/issues/24678[#24678])
* Fixed: Score API are not accessible to readonly user
    (https://issues.rudder.io/issues/24638[#24638])
* Fixed: Update dependencies to manage CVE-2024-1597  CVE-2024-22257 and CVE-2024-22243
    (https://issues.rudder.io/issues/24607[#24607])
* Fixed: Upgrade postgresql since CVE-2024-1597 and ignore other JS CVEs
    (https://issues.rudder.io/issues/24606[#24606])

==== Web - Nodes & inventories

* Fixed: When sending inventory with no software update anymore, inventory stored is not updated and keeps previous updates
    (https://issues.rudder.io/issues/24675[#24675])
* Fixed: Missing tenant information in API result for node details
    (https://issues.rudder.io/issues/24639[#24639])
* Fixed: Wrong error message when no result are found when using a compliance filter
    (https://issues.rudder.io/issues/24499[#24499])
* Fixed: Technical logs are not loaded when visiting the tab
    (https://issues.rudder.io/issues/24502[#24502])
* Fixed: when we search for a group in the search engine, the group page we arrive on is messed
    (https://issues.rudder.io/issues/24466[#24466])

==== Web - Config management

* Fixed: Typo "dynmaci" in logs
    (https://issues.rudder.io/issues/24669[#24669])
* Fixed: Group page UI is missing several key things
    (https://issues.rudder.io/issues/24489[#24489])

==== Plugin manager cli

* Fixed: Don't hardcode systemctl path
    (https://issues.rudder.io/issues/24676[#24676])
* Fixed: Improve apt/rpm package dependency detection
    (https://issues.rudder.io/issues/24677[#24677])
* Fixed: rudder package does not log in /var/log/rudder/rudder-pkg/rudder-pkg.log anymore
    (https://issues.rudder.io/issues/24484[#24484])
* Fixed: rudder-pkg don't inform that credential are not set up
    (https://issues.rudder.io/issues/24401[#24401])

==== Web - UI & UX

* Fixed: Typos in node state description
    (https://issues.rudder.io/issues/24668[#24668])
* Fixed: Only ignored status is displayed in Node page
    (https://issues.rudder.io/issues/24647[#24647])
* Fixed: Event log fold indicator has a weird color
    (https://issues.rudder.io/issues/24614[#24614])
* Fixed: Elm properties app is loaded multiple times
    (https://issues.rudder.io/issues/24416[#24416])
* Fixed: Status point next the node hostname doesn't provide much info
    (https://issues.rudder.io/issues/24361[#24361])
* Fixed: Button for archiving/deleting reports is not visible
    (https://issues.rudder.io/issues/24408[#24408])
* Fixed: system updates score details is empty when the node is up-to-date
    (https://issues.rudder.io/issues/24421[#24421])
* Fixed: Directive errors section is not consistent and always redirects to first tab
    (https://issues.rudder.io/issues/24590[#24590])
* Fixed: Number of software updates available is redundant
    (https://issues.rudder.io/issues/24602[#24602])
* Fixed: Typo in compliance score tooltip
    (https://issues.rudder.io/issues/24598[#24598])
* Fixed: When the group tab section is too large it cannot be scrolled
    (https://issues.rudder.io/issues/24547[#24547])
* Fixed: Tooltip on compliance in rule page is not rendered
    (https://issues.rudder.io/issues/24436[#24436])
* Fixed: JS error when opening directive form more than once 
    (https://issues.rudder.io/issues/24563[#24563])
* Fixed: Add margin right to system updates badge
    (https://issues.rudder.io/issues/24557[#24557])
* Fixed: when sorting by targeted compliance, the No data available should always be last
    (https://issues.rudder.io/issues/24567[#24567])
* Fixed: Update js dependencies
    (https://issues.rudder.io/issues/24566[#24566])
* Fixed: cannot get to the bottom on Nodes/Settings pages
    (https://issues.rudder.io/issues/24251[#24251])
* Fixed: "Usage survey" setting select button is way too large
    (https://issues.rudder.io/issues/24510[#24510])
* Fixed: Resizing node tab in group page should stop at header
    (https://issues.rudder.io/issues/24549[#24549])

==== Miscellaneous

* Fixed: Enabling directive modal has margin between table and change log
    (https://issues.rudder.io/issues/24613[#24613])
* Fixed: Improvements on score: F score, rework tooltip, improve messages
    (https://issues.rudder.io/issues/24637[#24637])
* Fixed: Tags displayed in directive form are broken 
    (https://issues.rudder.io/issues/24548[#24548])
* Fixed: API authorization menu bellow username is barely usable
    (https://issues.rudder.io/issues/24433[#24433])

==== System integration

* Fixed: SELinux error for downloading files
    (https://issues.rudder.io/issues/24589[#24589])

==== Web - Maintenance

* Fixed: Missing event for Relay Demote preventing demotion
    (https://issues.rudder.io/issues/24596[#24596])

==== Relay server or API

* Fixed: Teach relayd about a new report file name
    (https://issues.rudder.io/issues/24564[#24564])

==== Web - Technique editor

* Fixed: We can't save a technique with an enum value empty while required option is unchecked
    (https://issues.rudder.io/issues/24594[#24594])
* Fixed: Compilation output tab icon in technique is not aligned
    (https://issues.rudder.io/issues/24586[#24586])
* Fixed: We shoud not able to save a technique with no method inside
    (https://issues.rudder.io/issues/24579[#24579])
* Fixed: Persistant tooltip on info icon in methods
    (https://issues.rudder.io/issues/24419[#24419])
* Fixed: Delete modal in technique editor is offset
    (https://issues.rudder.io/issues/24453[#24453])

==== rudderc

* Fixed: Allow technique id starting with a number
    (https://issues.rudder.io/issues/24592[#24592])

==== Techniques

* Fixed: We should not be able to save a technique with empty enum parameters 
    (https://issues.rudder.io/issues/24583[#24583])

==== API

* Fixed: API export of groups doesn't export the categories as dependencies
    (https://issues.rudder.io/issues/24295[#24295])
* Fixed: Update API doc version to 19
    (https://issues.rudder.io/issues/24581[#24581])

==== Documentation

* Fixed: Rudder-package cli help for install command should document file
    (https://issues.rudder.io/issues/24576[#24576])
* Fixed: Fix typo in file replace lines
    (https://issues.rudder.io/issues/24609[#24609])

==== System techniques

* Fixed: Add a unique component to inventory and inventory signature file name
    (https://issues.rudder.io/issues/24560[#24560])

==== Agent

* Fixed: Add a warning in "rudder agent info" when cf-execd is stopped
    (https://issues.rudder.io/issues/24620[#24620])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.0.beta2 (2024-03-22)

=== Changes


==== Documentation

* Document autoconditions
    (https://issues.rudder.io/issues/24535[#24535])

==== Architecture - Code maintenance

* Use enumeratum in place of sealarate for scala3 migration
    (https://issues.rudder.io/issues/24554[#24554])
*  Scala 3 syntax - branch 7.3 - core
    (https://issues.rudder.io/issues/24532[#24532])

==== Web - UI & UX

* Have list of available score available and define a display name
    (https://issues.rudder.io/issues/24527[#24527])
* Updating bootstrap columns css classes
    (https://issues.rudder.io/issues/24414[#24414])
* Improve technique parameter UI
    (https://issues.rudder.io/issues/24467[#24467])

==== CI

* Add PoC SBOM tooling
    (https://issues.rudder.io/issues/23356[#23356])

==== rudderc

* Add outcome conditions in rudderc docs
    (https://issues.rudder.io/issues/24302[#24302])

==== Plugin manager cli

* Improve rudder-package CLI doc
    (https://issues.rudder.io/issues/24389[#24389])
* Add the ability to specify the version to install
    (https://issues.rudder.io/issues/24373[#24373])

==== Generic methods

* Migrate the condition_from_command methode to logger_v4
    (https://issues.rudder.io/issues/24377[#24377])
* Migrate inventory trigger method to logger_v4
    (https://issues.rudder.io/issues/24378[#24378])

=== Bug fixes

==== Packaging

* Fixed: Move plugins postupgrade after webapp restart
    (https://issues.rudder.io/issues/24449[#24449])

==== Agent

* Fixed: Typo in rudder-sign openssl 3 signing regex
    (https://issues.rudder.io/issues/24359[#24359])
* Fixed: rudder-sign fails on some machines with openssl 3
    (https://issues.rudder.io/issues/24320[#24320])

==== Documentation

* Fixed: Documentation on Windows installation misses the dependency on dsc plugin on the rudder server
    (https://issues.rudder.io/issues/24229[#24229])

==== Web - Config management

* Fixed: JS error when clicking on a technique with several version in directive screen
    (https://issues.rudder.io/issues/23400[#23400])
* Fixed: Overriding properties should have the same type as overridden
    (https://issues.rudder.io/issues/24236[#24236])
* Fixed: Rudder should finish to migrate all techniques when booting instead of stopping on first error
    (https://issues.rudder.io/issues/24515[#24515])

==== Web - UI & UX

* Fixed: Group parameters tab is always displayed
    (https://issues.rudder.io/issues/24546[#24546])
* Fixed: Display of group compliance in group information should be on the right
    (https://issues.rudder.io/issues/24381[#24381])
* Fixed: Score details are missing in nodes table
    (https://issues.rudder.io/issues/24355[#24355])
* Fixed: Nodes tables height is too small
    (https://issues.rudder.io/issues/24528[#24528])
* Fixed: Beautify global properties creation
    (https://issues.rudder.io/issues/24471[#24471])
* Fixed: Directive applicaton preview  in pending nodes is broken
    (https://issues.rudder.io/issues/24324[#24324])
* Fixed: Nodes table can take almost all the height of the group page 
    (https://issues.rudder.io/issues/24429[#24429])
* Fixed: The "condition" border appears on all methods in the tech. editor.
    (https://issues.rudder.io/issues/24519[#24519])
* Fixed: Tabs are missing their score
    (https://issues.rudder.io/issues/24447[#24447])
* Fixed: Node tabs have onclick event handlers assigned on unrendered elements
    (https://issues.rudder.io/issues/24405[#24405])
* Fixed: Directives button to set parameters on new directive does nothing 
    (https://issues.rudder.io/issues/24428[#24428])
* Fixed: Missing space between badge score and number
    (https://issues.rudder.io/issues/24420[#24420])
* Fixed: Broken group creation UI
    (https://issues.rudder.io/issues/24335[#24335])
* Fixed: There is a search box in the node acceptation pop-up
    (https://issues.rudder.io/issues/24388[#24388])
* Fixed: Show logs button in node compliance tab does nothing
    (https://issues.rudder.io/issues/24383[#24383])
* Fixed: Dashboard container does not fit the height of the screen
    (https://issues.rudder.io/issues/24196[#24196])
* Fixed: Use bootstrap variables to define the default text size and font
    (https://issues.rudder.io/issues/24317[#24317])
* Fixed: Use bootstrap variables to define the default text size and font
    (https://issues.rudder.io/issues/24317[#24317])
* Fixed: Odd spacing with filters elements in node search page
    (https://issues.rudder.io/issues/24348[#24348])
* Fixed: Enforce policy mode in block method has a different display than audit  
    (https://issues.rudder.io/issues/24382[#24382])
* Fixed: Update Rudder CSS to support bug fixes in plugins interface
    (https://issues.rudder.io/issues/24233[#24233])
* Fixed: The display of the description field is broken
    (https://issues.rudder.io/issues/24174[#24174])
* Fixed: Tooltips on system-updates in score-details is not standard
    (https://issues.rudder.io/issues/24316[#24316])
* Fixed: The height of node tabs is higher than the height of their container
    (https://issues.rudder.io/issues/24369[#24369])
* Fixed: Margin is too small on Global compliance details module in dashboard
    (https://issues.rudder.io/issues/24283[#24283])
* Fixed: Missing header separator in node search page
    (https://issues.rudder.io/issues/24347[#24347])
* Fixed: Popovers don't work anymore
    (https://issues.rudder.io/issues/24345[#24345])
* Fixed: Some dropdowns display are broken
    (https://issues.rudder.io/issues/24323[#24323])
* Fixed: Odd rendering on tooltips in search node page 
    (https://issues.rudder.io/issues/24349[#24349])
* Fixed: Tooltips persisted on refresh button on the table in search node page
    (https://issues.rudder.io/issues/24351[#24351])
* Fixed: Description in API account is outside of the header
    (https://issues.rudder.io/issues/24354[#24354])
* Fixed: Warning icon on log out should be on healthcheck heart logo
    (https://issues.rudder.io/issues/24346[#24346])
* Fixed: Checkbox for selecting all nodes for acceptance doesn't work
    (https://issues.rudder.io/issues/24311[#24311])
* Fixed: Filter button on group page doesn't do anything
    (https://issues.rudder.io/issues/24336[#24336])
* Fixed: Modal titles are unreadable
    (https://issues.rudder.io/issues/24322[#24322])
* Fixed: Wrong lalel on tab in compliance group
    (https://issues.rudder.io/issues/24313[#24313])
* Fixed: Display of node compliance info message is broken
    (https://issues.rudder.io/issues/24310[#24310])
* Fixed: Errors in event log for deleted techniques
    (https://issues.rudder.io/issues/24277[#24277])
* Fixed: When the documentation of a technique is very long, the user has to scroll a long way before creating a directive from this technique
    (https://issues.rudder.io/issues/23881[#23881])

==== rudderc

* Fixed: rudderc test should dump the report file path or workdir when a check step fails
    (https://issues.rudder.io/issues/24523[#24523])
* Fixed: Broken detection of incorrect parameter names
    (https://issues.rudder.io/issues/24371[#24371])

==== Security

* Fixed: npm dep security checks are ignored
    (https://issues.rudder.io/issues/24522[#24522])
* Fixed: Ignore angularjs DoS in 7.3
    (https://issues.rudder.io/issues/24517[#24517])

==== API

* Fixed: Async tests are failing for node certificates
    (https://issues.rudder.io/issues/24520[#24520])
* Fixed: Display compliance for system groups
    (https://issues.rudder.io/issues/24363[#24363])
* Fixed: API popup for copying token does not appear
    (https://issues.rudder.io/issues/24391[#24391])
* Fixed: Merge user-management feature branch to 7.3
    (https://issues.rudder.io/issues/24342[#24342])

==== Miscellaneous

* Fixed: It is hard to differentiate between real values and placeholders in inputs
    (https://issues.rudder.io/issues/24463[#24463])
* Fixed: Cannot translate campaign on boot, leading to skipped events
    (https://issues.rudder.io/issues/24441[#24441])
* Fixed: Existing deleted user managed by file cannot be reactivated 
    (https://issues.rudder.io/issues/24318[#24318])

==== Relay server or API

* Fixed: Vulnerability in mio
    (https://issues.rudder.io/issues/24516[#24516])

==== Plugin manager cli

* Fixed: Add a quiet argument to rudder-package
    (https://issues.rudder.io/issues/24490[#24490])
* Fixed: Broken pipe when piping rudder-package output
    (https://issues.rudder.io/issues/24432[#24432])
* Fixed: Don't fail on malformed index entries
    (https://issues.rudder.io/issues/24372[#24372])

==== System integration

* Fixed: Missing primary key statement for user sessions table creation when migrating
    (https://issues.rudder.io/issues/24456[#24456])
* Fixed: Rename policy_mode to policy_mode_override
    (https://issues.rudder.io/issues/24380[#24380])

==== Web - Compliance & node report

* Fixed: Group compliance stays empty
    (https://issues.rudder.io/issues/24366[#24366])

==== Architecture - Internal libs

* Fixed: windows Node in tests has invalid  certificate, failing test in plugin windows
    (https://issues.rudder.io/issues/24289[#24289])

==== Web - Technique editor

* Fixed: The technique editor enforces optional parameter presence
    (https://issues.rudder.io/issues/24350[#24350])
* Fixed: sysctl value generic method is not reporting
    (https://issues.rudder.io/issues/20853[#20853])

==== System techniques

* Fixed: Broken techniques qa-test
    (https://issues.rudder.io/issues/24448[#24448])
* Fixed: Extend autoconditions to allow string values
    (https://issues.rudder.io/issues/24412[#24412])

==== Generic methods

* Fixed: Regex in file replace line must not match the string used as replacement
    (https://issues.rudder.io/issues/24537[#24537])
* Fixed: Missing constraint for enforce parameter in method File content
    (https://issues.rudder.io/issues/24458[#24458])
* Fixed: The yum module should install local package with yum
    (https://issues.rudder.io/issues/24367[#24367])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.0.beta1 (2024-03-04)

=== Changes


==== Packaging

* Import new gpg key in rpm postinst
    (https://issues.rudder.io/issues/24070[#24070])

==== Agent

* We should log an error when a hook timeouts
    (https://issues.rudder.io/issues/23936[#23936])

==== Documentation

* Adapt doc for 8.1
    (https://issues.rudder.io/issues/24033[#24033])

==== API

* Add alternative api doc build with RapiDoc
    (https://issues.rudder.io/issues/24286[#24286])
* Add manufacturer field in create node API
    (https://issues.rudder.io/issues/24091[#24091])

==== Plugin manager cli

* Rudder-package should log the package scripts outputs and errors
    (https://issues.rudder.io/issues/24238[#24238])

==== Web - Compliance & node report

* Initialize score on webapp start up
    (https://issues.rudder.io/issues/24178[#24178])

==== Architecture - Code maintenance

* Prepare migration to Scala 3 - Version 8.1 part 1
    (https://issues.rudder.io/issues/24175[#24175])
* Prepare migration to Scala 3 - Version 7.3 part 1
    (https://issues.rudder.io/issues/24171[#24171])

==== Web - Technique editor

* Add a select type for technique parameter
    (https://issues.rudder.io/issues/24099[#24099])

==== Architecture - Internal libs

* Add score enum for score in database
    (https://issues.rudder.io/issues/24147[#24147])

==== Web - UI & UX

* Editing big properties in elm-based properties interface is very inconvenient
    (https://issues.rudder.io/issues/23487[#23487])
* Improve display of audit/enforce mode in technique editor
    (https://issues.rudder.io/issues/24080[#24080])
* Display the list of pending change requests related to the selected rule
    (https://issues.rudder.io/issues/21931[#21931])

=== Bug fixes

==== Packaging

* Fixed: Rudder upgrade may fail on postgres script
    (https://issues.rudder.io/issues/24232[#24232])
* Fixed: add apr-util-db as a dependency for al2023
    (https://issues.rudder.io/issues/24061[#24061])
* Fixed: RHEL9 policies have an incompatible sh shebang
    (https://issues.rudder.io/issues/24057[#24057])

==== Documentation

* Fixed: Import/Export archive feature is no more in beta
    (https://issues.rudder.io/issues/24290[#24290])
* Fixed: layout of https://docs.rudder.io/reference/8.0/administration/server.html#_importing_configuration is broken
    (https://issues.rudder.io/issues/24190[#24190])
* Fixed: Broken doc build
    (https://issues.rudder.io/issues/24136[#24136])
* Fixed: case-sensitivity parameter of rudder-user.xml is not documented
    (https://issues.rudder.io/issues/24024[#24024])

==== rudderc

* Fixed: Add integration tests to rudderc
    (https://issues.rudder.io/issues/24291[#24291])
* Fixed: rudderc canonifies already canonified condition expression resulting in loss of logic operators such as ) and |
    (https://issues.rudder.io/issues/24226[#24226])
* Fixed: Missing method constraints in rudderc
    (https://issues.rudder.io/issues/24100[#24100])

==== CI

* Fixed: Adapt Jenkinsfile after warning-ng plugin upgrade
    (https://issues.rudder.io/issues/24301[#24301])

==== API

* Fixed: Empty role in users file is logged as warning
    (https://issues.rudder.io/issues/24285[#24285])
* Fixed: Bad description for serialNumber attribute of machine
    (https://issues.rudder.io/issues/24141[#24141])
* Fixed: For delete API for node, add a message for node already deleted
    (https://issues.rudder.io/issues/24129[#24129])
* Fixed: If REST url ends with .com, then the .com is removed from path segments
    (https://issues.rudder.io/issues/24036[#24036])

==== Web - Technique editor

* Fixed: An errors occurs within technique editor resource manager when we create a folder that has the same name than another parent folder
    (https://issues.rudder.io/issues/24276[#24276])
* Fixed: when we have conditions on blocks, the condition text is not correctly positionned when the block is opened
    (https://issues.rudder.io/issues/24150[#24150])
* Fixed: Technique import doesn't refresh the list of method in technique editor
    (https://issues.rudder.io/issues/24123[#24123])
* Fixed: Action dropdown list in technique editor goes under parameters
    (https://issues.rudder.io/issues/24122[#24122])
* Fixed: 404 not found in technique editor resource manager Ajax query
    (https://issues.rudder.io/issues/24084[#24084])
* Fixed: Technique editor method filters are not aligned correctly
    (https://issues.rudder.io/issues/23885[#23885])

==== Web - UI & UX

* Fixed: Some tabs do no longer call Elm ports on click
    (https://issues.rudder.io/issues/24287[#24287])
* Fixed: The chevron down icon for "Status" is barely visible
    (https://issues.rudder.io/issues/24197[#24197])
* Fixed: Directive parameters UI details changed since bootstrap 5
    (https://issues.rudder.io/issues/24176[#24176])
* Fixed: Hooks page looks broken since bootstrap 5 update
    (https://issues.rudder.io/issues/24204[#24204])
* Fixed: Add space in the login form between inputs
    (https://issues.rudder.io/issues/24194[#24194])
* Fixed: The active tab indicator no longer works
    (https://issues.rudder.io/issues/24170[#24170])
* Fixed: Active buttons no longer have shadow
    (https://issues.rudder.io/issues/24172[#24172])
* Fixed: Jstree links are broken
    (https://issues.rudder.io/issues/24152[#24152])
* Fixed: System updates badges css in compliance score is not applied
    (https://issues.rudder.io/issues/24155[#24155])
* Fixed: Add score on top of tabs
    (https://issues.rudder.io/issues/24096[#24096])
* Fixed: Links and buttons don't have the right colour since the bootstrap update
    (https://issues.rudder.io/issues/24124[#24124])
* Fixed: Unknown rule targets UI is missing icon and border
    (https://issues.rudder.io/issues/24102[#24102])
* Fixed: Group compliance view does not give global and targeted compliance definitions
    (https://issues.rudder.io/issues/24040[#24040])
* Fixed: System updates badges in compliance score have no css
    (https://issues.rudder.io/issues/24104[#24104])
* Fixed: Fix small ui error in the rules information tab
    (https://issues.rudder.io/issues/24079[#24079])
* Fixed: Add margin-bottom to form group
    (https://issues.rudder.io/issues/24048[#24048])
* Fixed: Fix default font size and menu toggle
    (https://issues.rudder.io/issues/24041[#24041])
* Fixed: Fix the Settings page and its components following the bootstrap 5 update
    (https://issues.rudder.io/issues/24035[#24035])

==== Miscellaneous

* Fixed: Incorrect error message about change request creation failure when it is not needed
    (https://issues.rudder.io/issues/24278[#24278])

==== Plugin manager cli

* Fixed: rudder-pkg stops at first install error on the upgrade-all command
    (https://issues.rudder.io/issues/24201[#24201])
* Fixed: Pylint test fails with an exception
    (https://issues.rudder.io/issues/24205[#24205])
* Fixed: rudder package unpacks scripts.txz in the wrong place
    (https://issues.rudder.io/issues/24131[#24131])
* Fixed: Broken parsing of 8.1 plugin index
    (https://issues.rudder.io/issues/24107[#24107])
* Fixed: Allow running rudder-package with a malformed index
    (https://issues.rudder.io/issues/24072[#24072])
* Fixed: script.txz is not scripts.txz
    (https://issues.rudder.io/issues/24060[#24060])
* Fixed: script.txz is not scripts.txz
    (https://issues.rudder.io/issues/24060[#24060])

==== Architecture - Code maintenance

* Fixed: Make spotless only check source of current project
    (https://issues.rudder.io/issues/24177[#24177])
* Fixed: Missing policy generation status
    (https://issues.rudder.io/issues/24117[#24117])
* Fixed: Backport test correction for allowed networks
    (https://issues.rudder.io/issues/24093[#24093])

==== Web - Compliance & node report

* Fixed: Add missing score
    (https://issues.rudder.io/issues/24158[#24158])
* Fixed: lost audit/enforce on the node compliance page
    (https://issues.rudder.io/issues/23930[#23930])

==== Web - Config management

* Fixed: We must not generate policies for nodes without a well formed certificate
    (https://issues.rudder.io/issues/24112[#24112])
* Fixed: when we import an archive and rules contains non existant targets, the targets can't be removed from the rules
    (https://issues.rudder.io/issues/24007[#24007])

==== Web - Maintenance

* Fixed: Archiving allows to read inconsistent active technique category ids 
    (https://issues.rudder.io/issues/24011[#24011])

==== Security

* Fixed: CSP headers are duplicated and missing report-uri
    (https://issues.rudder.io/issues/24101[#24101])
* Fixed: Implementing CSP headers without duplicating Lift scripts
    (https://issues.rudder.io/issues/24062[#24062])
* Fixed: Vulnerability in shlex Rust lib
    (https://issues.rudder.io/issues/24069[#24069])
* Fixed: Ignore cve on ext-js (unused dependency)
    (https://issues.rudder.io/issues/24071[#24071])
* Fixed: DoS vuln in h2 lib in relayd
    (https://issues.rudder.io/issues/24068[#24068])

==== System integration

* Fixed: Score table migration
    (https://issues.rudder.io/issues/24090[#24090])

==== Performance and scalability

* Fixed: Compliance has unoptimized usage of map view and policy mode computation  
    (https://issues.rudder.io/issues/24047[#24047])

==== Architecture - Internal libs

* Fixed: Wrong agent type for dsc node in tests
    (https://issues.rudder.io/issues/24051[#24051])

==== Techniques

* Fixed: File content directive add 4 spaces at the beginning of the line 
    (https://issues.rudder.io/issues/24022[#24022])

==== Agent

* Fixed: rudder agent modified misses some files
    (https://issues.rudder.io/issues/24133[#24133])
* Fixed: Prompt warning and ask confirmation for factory reset
    (https://issues.rudder.io/issues/23978[#23978])

==== Generic methods

* Fixed: Deprecate "Package check installed"
    (https://issues.rudder.io/issues/24120[#24120])

=== Release notes

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

==  Rudder 8.1.0.alpha1 (2024-01-19)

=== Changes


==== Packaging

* Make the rudder-agent package depends of python
    (https://issues.rudder.io/issues/23931[#23931])
* Update packaging scripts for rudder-package
    (https://issues.rudder.io/issues/23795[#23795])
* Add rudder-package to the relay package
    (https://issues.rudder.io/issues/23629[#23629])

==== Web - Compliance & node report

* Display group compliance
    (https://issues.rudder.io/issues/23926[#23926])
* Display group compliance
    (https://issues.rudder.io/issues/23926[#23926])

==== Architecture - Code maintenance

* Remove early return to prepare to Scala3 migration in box sequence/traverse
    (https://issues.rudder.io/issues/23948[#23948])
* Group all node related access into one NodeFactRepository
    (https://issues.rudder.io/issues/23727[#23727])
* Upgrading Bootstrap to version 5
    (https://issues.rudder.io/issues/23593[#23593])
* Integrate Sass with front-end development tools
    (https://issues.rudder.io/issues/23548[#23548])

==== System integration

* Add users table to better track user and sessions
    (https://issues.rudder.io/issues/23440[#23440])

==== rudderc

* Update the rudderc technique json schema to match the minimal SchemaStore expectation
    (https://issues.rudder.io/issues/23966[#23966])
* Improve rudder-package error messages
    (https://issues.rudder.io/issues/23842[#23842])
* Make rudderc able to compile techniques using a per method policy mode override
    (https://issues.rudder.io/issues/23799[#23799])
* Make sources compatible with Windows
    (https://issues.rudder.io/issues/23573[#23573])

==== Web - UI & UX

* Rudder Score for Nodes
    (https://issues.rudder.io/issues/23929[#23929])
* Reorganise the node summary tab
    (https://issues.rudder.io/issues/23854[#23854])
* Common style for Rust CLI output
    (https://issues.rudder.io/issues/23865[#23865])
* Reorganize the header of the node page
    (https://issues.rudder.io/issues/23826[#23826])

==== Server components

* Make the (now) various Rust CLIs more consistent
    (https://issues.rudder.io/issues/23852[#23852])
* Add version parsing to rudder-package
    (https://issues.rudder.io/issues/23687[#23687])

==== API

* Update API doc tooling
    (https://issues.rudder.io/issues/23860[#23860])

==== Plugin manager cli

* Update rudder-package cli for better UX
    (https://issues.rudder.io/issues/23838[#23838])
* Implement missing commands
    (https://issues.rudder.io/issues/23780[#23780])
* Document the rpkg format
    (https://issues.rudder.io/issues/23793[#23793])
* Add enable/disable commands to rudder-package
    (https://issues.rudder.io/issues/23791[#23791])
* Make rudder-package able to download plugin licenses
    (https://issues.rudder.io/issues/23782[#23782])
* Make rudder-package able to uninstall packages
    (https://issues.rudder.io/issues/23773[#23773])
* Add signature validation for plugins
    (https://issues.rudder.io/issues/23776[#23776])
* Make rudder-package able to install plugins from the repository
    (https://issues.rudder.io/issues/23772[#23772])
* Stop rudder-package if not run as root
    (https://issues.rudder.io/issues/23771[#23771])
* Restart the webapp after plugin installation
    (https://issues.rudder.io/issues/23769[#23769])
* Make an install subcommand for the new rudder-package
    (https://issues.rudder.io/issues/23767[#23767])
* Make rudder-package able to track installed files
    (https://issues.rudder.io/issues/23759[#23759])
* Add dependency support to rudder-package
    (https://issues.rudder.io/issues/23739[#23739])
* rudder-package should stroingly type any plugin version
    (https://issues.rudder.io/issues/23695[#23695])
* Add a downloader for files from plugin repository
    (https://issues.rudder.io/issues/23690[#23690])
* Add configuration file path to the cli args
    (https://issues.rudder.io/issues/23632[#23632])
* Add logging basics
    (https://issues.rudder.io/issues/23630[#23630])
* Add configuration file parser to rudder-package
    (https://issues.rudder.io/issues/23627[#23627])
* Implement CI config for rudder-package
    (https://issues.rudder.io/issues/23625[#23625])

==== Architecture - Dependencies

* Update js dependencies
    (https://issues.rudder.io/issues/23825[#23825])
* Update Scala dependencies
    (https://issues.rudder.io/issues/23758[#23758])
* Update to chimney 0.8.2
    (https://issues.rudder.io/issues/23737[#23737])

==== Agent

* PoC for a minimal inventory engine
    (https://issues.rudder.io/issues/23033[#23033])

=== Bug fixes

==== Packaging

* Fixed: Embed openssl cli on 7.3
    (https://issues.rudder.io/issues/24019[#24019])
* Fixed: Abort server build if rudder.war is less than 1Mb
    (https://issues.rudder.io/issues/23958[#23958])
* Fixed: Update C dependencies
    (https://issues.rudder.io/issues/23794[#23794])
* Fixed: Simplify systemd service config
    (https://issues.rudder.io/issues/23712[#23712])
* Fixed: Exclude target dirs in qa-test
    (https://issues.rudder.io/issues/23980[#23980])
* Fixed: rudder-packages does not build the right Rust project
    (https://issues.rudder.io/issues/23904[#23904])
* Fixed: Update Rust dependencies
    (https://issues.rudder.io/issues/23803[#23803])

==== Documentation

* Fixed: Update note for rudder-package
    (https://issues.rudder.io/issues/23960[#23960])
* Fixed: Fixed ref in documentation for centralized page
    (https://issues.rudder.io/issues/23917[#23917])

==== Web - UI & UX

* Fixed: Group compliance tab is loaded only with a double-click
    (https://issues.rudder.io/issues/24034[#24034])
* Fixed: Replace glyphicon icons with font-awesome
    (https://issues.rudder.io/issues/24031[#24031])
* Fixed: Add policy mode info in group compliance details
    (https://issues.rudder.io/issues/24028[#24028])
* Fixed: In quicksearch, query error are not displayed which leads to infinite loading result
    (https://issues.rudder.io/issues/23402[#23402])
* Fixed: New campaigns button does not conform to our graphic charter
    (https://issues.rudder.io/issues/23938[#23938])
* Fixed: The API accounts creation and editing popup no longer appears
    (https://issues.rudder.io/issues/23943[#23943])
* Fixed: A new group display no nodes while all linux are selected
    (https://issues.rudder.io/issues/22170[#22170])
* Fixed: The health check page has an unnecessary "Show check list" button in 8.0
    (https://issues.rudder.io/issues/23916[#23916])
* Fixed: The health check page has an unnecessary "Show check list" button
    (https://issues.rudder.io/issues/23891[#23891])
* Fixed: The "Category" field in the technique editor is displayed as a mandatory field even if it is an unmutable one
    (https://issues.rudder.io/issues/23883[#23883])
* Fixed: Remove the "Edit techniques" button from the directives webpage
    (https://issues.rudder.io/issues/23877[#23877])
* Fixed: Rename the "Create global property" button in "Create"
    (https://issues.rudder.io/issues/23878[#23878])

==== Security

* Fixed: Generate runtime evaluated variables in windows policies as templates instead of Powershell expansion
    (https://issues.rudder.io/issues/23973[#23973])
* Fixed: Vulnerability in zerocopy crate
    (https://issues.rudder.io/issues/24010[#24010])
* Fixed: Ignore CVE-2023-51074 (no impact, score too high)
    (https://issues.rudder.io/issues/24005[#24005])
* Fixed: Unimportant CVE on logback and icu4j
    (https://issues.rudder.io/issues/23983[#23983])
* Fixed: Unaffected CVE on jgit and logback
    (https://issues.rudder.io/issues/23982[#23982])

==== Performance and scalability

* Fixed: Healthcheck on file descriptor should be max 64000
    (https://issues.rudder.io/issues/24006[#24006])

==== Plugin manager cli

* Fixed: rudder package fails to install local rpkg
    (https://issues.rudder.io/issues/23965[#23965])
* Fixed: rudder-package fails to compile in release mode
    (https://issues.rudder.io/issues/23949[#23949])
* Fixed: Make check-connection an option of the update command
    (https://issues.rudder.io/issues/23834[#23834])
* Fixed: Use quick_xml for xml edition
    (https://issues.rudder.io/issues/23781[#23781])

==== Web - Config management

* Fixed: Static group which depends on dynamic subgroup must be forbiden
    (https://issues.rudder.io/issues/18952[#18952])
* Fixed: Rudder agent scheduled runs are not triggered at regular interval
    (https://issues.rudder.io/issues/23956[#23956])

==== Server components

* Fixed: Waning log spam when disabled rudder_compute_changes setting
    (https://issues.rudder.io/issues/23969[#23969])

==== Web - Nodes & inventories

* Fixed: Missing icon for windows 2022
    (https://issues.rudder.io/issues/23972[#23972])
* Fixed: We can accept a node with an existing hostname even if node_accept_duplicated_hostname is false
    (https://issues.rudder.io/issues/22197[#22197])

==== rudderc

* Fixed: Improve rudderc error message when a parameter is missing from a method call
    (https://issues.rudder.io/issues/23953[#23953])
* Fixed: Improve rudderc test error message when no library is passed in the parameters
    (https://issues.rudder.io/issues/23941[#23941])
* Fixed: rudderc code is not properly formatted due to a failed resolution of merge
    (https://issues.rudder.io/issues/23940[#23940])
* Fixed: Parameters are not properly intepreted in method call conditions
    (https://issues.rudder.io/issues/23925[#23925])
* Fixed: tests output should be displayed even if not valid utf-8
    (https://issues.rudder.io/issues/23788[#23788])
* Fixed: rudderc export should use category from technique if existing
    (https://issues.rudder.io/issues/23787[#23787])
* Fixed: Add GPG signature verification to rudder-package
    (https://issues.rudder.io/issues/23711[#23711])

==== Architecture - Code maintenance

* Fixed: Lift Async system is not able to find spring SecurityContextHolder
    (https://issues.rudder.io/issues/23920[#23920])
* Fixed: Inventory accept test sometimes fails on callback check
    (https://issues.rudder.io/issues/23786[#23786])
* Fixed: Update to zio-json 0.6.2
    (https://issues.rudder.io/issues/23409[#23409])

==== Architecture - Internal libs

* Fixed: Plugin license implementation is not coherent with interface
    (https://issues.rudder.io/issues/23932[#23932])

==== Miscellaneous

* Fixed: Change request on special:all_nodes_without_role lead to error
    (https://issues.rudder.io/issues/23446[#23446])

==== Techniques

* Fixed: FileTemplate technique fails with an error on the Directory-Create method call
    (https://issues.rudder.io/issues/23954[#23954])

==== Agent

* Fixed: Rudder agent still contains some syslog reporting handling code
    (https://issues.rudder.io/issues/23946[#23946])
* Fixed: when a node has capitals in its hostname agent history doesn't show manual runs
    (https://issues.rudder.io/issues/23740[#23740])

==== Generic methods

* Fixed: Replace md5 by sha256 in time_lib
    (https://issues.rudder.io/issues/23070[#23070])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Alexis TARUSSIO

This is a bug fix release in the 8.1 series and therefore all installations of 8.1.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

