= Changelogs for Rudder plugin auth-backends 6.2.\* versions

== auth-backends-6.2-1.12 (2022-10-12)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Jackson-databind used in oauth has CVE
    (https://issues.rudder.io/issues/21927[#21927])
* Fixed: Remaingin OAUTH secret in log in trace level
    (https://issues.rudder.io/issues/21896[#21896])
* Fixed: Bad warning about missing config for oauth when oauth backend is not used
    (https://issues.rudder.io/issues/21228[#21228])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-6.2-1.10 (2022-05-09)

=== Changes


==== Packaging

* Plugins package scripts should always exit on error
    (https://issues.rudder.io/issues/21008[#21008])

=== Bug fixes

==== Miscellaneous

* Fixed: Oauth login error are not logged
    (https://issues.rudder.io/issues/21024[#21024])
* Fixed: documentation dones't tell which provider to user of oauth2
    (https://issues.rudder.io/issues/21015[#21015])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-6.2-1.7 (2020-12-10)

=== Changes

==== Packaging

* Make plugins display names more consistent
    (https://issues.rudder.io/issues/18599[#18599])

=== Bug fixes

==== Miscellaneous

* Fixed: Missing doc about restart jetty after change in config
    (https://issues.rudder.io/issues/18402[#18402])
* Fixed: Stacktrace when radius connection timeout
    (https://issues.rudder.io/issues/18230[#18230])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

