= Changelogs for Rudder plugin change-validation 6.2.\* versions

== change-validation-6.2-1.11 (2021-02-09)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Error when parsing change-validation.conf file
    (https://issues.rudder.io/issues/18875[#18875])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-6.2-1.10 (2020-12-10)

=== Changes

==== Packaging

* Make plugins display names more consistent
    (https://issues.rudder.io/issues/18599[#18599])

=== Bug fixes

==== Refactoring

* Fixed: Fix plugins build according to 6.2 changes
    (https://issues.rudder.io/issues/18630[#18630])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

