= Changelogs for Rudder plugin cve 6.2.\* versions

== cve-6.2-1.8 (2021-06-23)

=== Changes


==== Packaging

* Add CI checks to plugins-private
    (https://issues.rudder.io/issues/19434[#19434])

=== Bug fixes

==== Miscellaneous

* Fixed: Non fixed CVE may not be linked to Nodes, leading to numerous empty CVE found
    (https://issues.rudder.io/issues/19417[#19417])
* Fixed: Scheduled task are not ran anymore
    (https://issues.rudder.io/issues/19402[#19402])
* Fixed: Add a filter to show only active CVE/Vulnerable Nodes when look for Node/CVE details
    (https://issues.rudder.io/issues/19376[#19376])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-6.2-1.7 (2021-06-01)

=== Changes


==== Miscellaneous

* Add an option to download recent/modified archives instead of full years
    (https://issues.rudder.io/issues/19314[#19314])

=== Bug fixes

==== Miscellaneous

* Fixed: If an error occurs during cve check of a node, previous result is lost 
    (https://issues.rudder.io/issues/19318[#19318])
* Fixed: Improve doc to state that we need at least 4Gb of RAM
    (https://issues.rudder.io/issues/18985[#18985])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-6.2-1.6 (2021-05-19)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Filter vulnerable package list so that only vulnerable packages appears
    (https://issues.rudder.io/issues/19234[#19234])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-6.2-1.5 (2021-05-19)

=== Changes


==== Packaging

* Use https repos in maven config
    (https://issues.rudder.io/issues/19165[#19165])

=== Bug fixes

==== Miscellaneous

* Fixed: Assigner field in CVE details maybe empty 
    (https://issues.rudder.io/issues/19204[#19204])
* Fixed: Broken images in doc
    (https://issues.rudder.io/issues/19084[#19084])
* Fixed: Add documentation
    (https://issues.rudder.io/issues/18971[#18971])
* Fixed: Document list ot compatible OSes
    (https://issues.rudder.io/issues/18933[#18933])
* Fixed: Typo in logs
    (https://issues.rudder.io/issues/18908[#18908])
* Fixed: Add note about memory usgae and how to fix problems
    (https://issues.rudder.io/issues/18907[#18907])
* Fixed: Show view by nodes by default
    (https://issues.rudder.io/issues/18890[#18890])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-6.2-1.4 (2020-12-10)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Build for 6.2 branch
    (https://issues.rudder.io/issues/18663[#18663])
* Fixed: Improve texts in the plugin
    (https://issues.rudder.io/issues/18589[#18589])
* Fixed: Support debian packages sources and display check error messages
    (https://issues.rudder.io/issues/18587[#18587])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

