= Changelogs for Rudder plugin datasources 6.2.\* versions

== datasources-6.2-1.12 (2021-09-03)

=== Changes


==== Documentation

* Add typos check in the repository
    (https://issues.rudder.io/issues/19419[#19419])

==== Packaging

* Use https repos in maven config
    (https://issues.rudder.io/issues/19165[#19165])

=== Bug fixes

==== Miscellaneous

* Fixed: Quote are removed when subpath is used leading to parsing error
    (https://issues.rudder.io/issues/19863[#19863])
* Fixed: Datasource reload APIs have no effect
    (https://issues.rudder.io/issues/19864[#19864])
* Fixed: Fix typos in datasources plugin
    (https://issues.rudder.io/issues/19859[#19859])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-6.2-1.11 (2020-12-10)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Datasources test in error
    (https://issues.rudder.io/issues/18643[#18643])
* Fixed: Add tests regarding arrays
    (https://issues.rudder.io/issues/18288[#18288])

==== Refactoring

* Fixed: Fix plugins build according to 6.2 changes
    (https://issues.rudder.io/issues/18630[#18630])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

