= Changelogs for Rudder plugin dsc 6.2.\* versions

== dsc-6.2-1.24 (2021-06-24)

=== Changes


==== ci

* Add typos check to CI config
    (https://issues.rudder.io/issues/19341[#19341])

=== Bug fixes

==== ncf

* Fixed: Some methods do not generate the correct conditions
    (https://issues.rudder.io/issues/19465[#19465])

==== Rudder web app

* Fixed: missing property with name 'plugin-title-description' with DSC plugin (build 6.2-1.23)
    (https://issues.rudder.io/issues/19409[#19409])

==== Miscellaneous

* Fixed: Remove unused global variables
    (https://issues.rudder.io/issues/19303[#19303])

==== ci

* Fixed: The linter does not verify the default rules anymore
    (https://issues.rudder.io/issues/19286[#19286])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-6.2-1.23 (2021-05-21)

=== Changes


==== ci

* Add pester tests to qa-tests
    (https://issues.rudder.io/issues/19224[#19224])

==== Packaging

* Split the agent build from the plugin build
    (https://issues.rudder.io/issues/18769[#18769])

=== Bug fixes

==== ci

* Fixed: Add a custom PSSA rule to look for any usage of undefined variables in the code base
    (https://issues.rudder.io/issues/19267[#19267])

==== Miscellaneous

* Fixed: typo in dot-sourcing mandatory files in rudder.ps1
    (https://issues.rudder.io/issues/19241[#19241])

==== ncf

* Fixed: Powershell files style must be enforced
    (https://issues.rudder.io/issues/19208[#19208])
* Fixed: Add tests for classes.ps1 functions
    (https://issues.rudder.io/issues/19201[#19201])
* Fixed: Fix Changes-only report mode
    (https://issues.rudder.io/issues/19134[#19134])
* Fixed: Add more verbose logs when writing reports
    (https://issues.rudder.io/issues/19133[#19133])

==== Packaging

* Fixed: Exclude tests files from the build
    (https://issues.rudder.io/issues/19210[#19210])

==== Security

* Fixed: Installer should force the Rudder folder ACLs to only give access to the local admins profile
    (https://issues.rudder.io/issues/19183[#19183])

==== CLI

* Fixed: Incorrect path after installing the agent
    (https://issues.rudder.io/issues/19169[#19169])

==== System techniques

* Fixed: System technique prerun-check uses the incorrect PATH source to do some comparison
    (https://issues.rudder.io/issues/18967[#18967])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-6.2-1.22 (2021-01-27)

=== Changes

==== Packaging

* Add a linter conf file to check powershell files
    (https://issues.rudder.io/issues/18802[#18802])

=== Bug fixes

==== System integration

* Fixed: 6.1 agents are not able to run properly on a 6.2 server
    (https://issues.rudder.io/issues/18812[#18812])

==== Packaging

* Fixed: Plugin is downloading rudder-plugin main-build.conf from master and not from the 6.1 branch displaying wrong version in the UI
    (https://issues.rudder.io/issues/18809[#18809])

==== CLI

* Fixed: Typo in update script
    (https://issues.rudder.io/issues/18793[#18793])
* Fixed: Agent update should not throw exceptions when the update fails to create a backup folder
    (https://issues.rudder.io/issues/18753[#18753])
* Fixed: Typo in update script
    (https://issues.rudder.io/issues/18752[#18752])

==== System techniques

* Fixed: System techniques should manage the presence of rudder in the path and psmodulepath
    (https://issues.rudder.io/issues/18754[#18754])

==== ncf

* Fixed: Rudder agent throws exceptions when you try to redefine a class
    (https://issues.rudder.io/issues/18751[#18751])

==== Techniques

* Fixed: Improve the windows install software technique documentation
    (https://issues.rudder.io/issues/18749[#18749])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-6.2-1.21 (2020-12-10)

=== Changes

==== CLI

* Add a rudder agent reset command to the DSC agent
    (https://issues.rudder.io/issues/17923[#17923])

=== Bug fixes

==== ncf

* Fixed: Dsc_from_configuration does not report compilation errors and do not correctly retry the compiilation phase when needed
    (https://issues.rudder.io/issues/18727[#18727])
* Fixed: DSC_compile method does not properly apply the compiled configuration
    (https://issues.rudder.io/issues/18520[#18520])
* Fixed: DSC methods should catch the errors throwed by the DSC jobs
    (https://issues.rudder.io/issues/18398[#18398])
* Fixed: Add DSC_apply GM tests
    (https://issues.rudder.io/issues/18322[#18322])
* Fixed: rename dscea functions in the DSC related GM
    (https://issues.rudder.io/issues/18320[#18320])
* Fixed: DSC GM tests are referencing a renamed lib file
    (https://issues.rudder.io/issues/18315[#18315])
* Fixed: The agent should be able to generate report from a given DSC configuration
    (https://issues.rudder.io/issues/17844[#17844])

==== CLI

* Fixed: Add update log events to the agent
    (https://issues.rudder.io/issues/18716[#18716])
* Fixed: All powershell script files should be in UTF8 with BOM
    (https://issues.rudder.io/issues/18469[#18469])
* Fixed: Rudder cli should not be updated by the agent update but only by the agent upgrade
    (https://issues.rudder.io/issues/18426[#18426])

==== Packaging

* Fixed: error when updating policies
    (https://issues.rudder.io/issues/18559[#18559])
* Fixed: Unattended upgrade can not configure correctly the policy server conf
    (https://issues.rudder.io/issues/18560[#18560])
* Fixed: Update Rudder branch version for 6.2 builds
    (https://issues.rudder.io/issues/18415[#18415])

==== Miscellaneous

* Fixed: Adapt webapp for 6.2
    (https://issues.rudder.io/issues/18665[#18665])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

