= Changelogs for Rudder plugin openscap 6.2.\* versions

== openscap-6.2-1.3 (2021-09-30)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: stack trace when openscap plugin loads
    (https://issues.rudder.io/issues/19958[#19958])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== openscap-6.2-1.2 (2021-09-03)

=== Changes


==== Documentation

* Add typos check in the repository
    (https://issues.rudder.io/issues/19419[#19419])

==== Packaging

* Use https repos in maven config
    (https://issues.rudder.io/issues/19165[#19165])

=== Bug fixes

==== Documentation

* Fixed: Document OpenSCAP on Ubuntu/Debian
    (https://issues.rudder.io/issues/19446[#19446])

==== Miscellaneous

* Fixed: Vulnerabilities in openscap plugin
    (https://issues.rudder.io/issues/19252[#19252])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== openscap-6.2-1.1 (2020-12-10)

=== Changes

==== Packaging

* Make plugins display names more consistent
    (https://issues.rudder.io/issues/18599[#18599])

=== Bug fixes

==== Refactoring

* Fixed: Fix plugins build according to 6.2 changes
    (https://issues.rudder.io/issues/18630[#18630])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

