= Changelogs for Rudder plugin scale-out-relay 6.2.\* versions

== scale-out-relay-6.2-1.6 (2021-09-03)

=== Changes


==== Documentation

* Add typos check in the repository
    (https://issues.rudder.io/issues/19419[#19419])

==== Packaging

* Use https repos in maven config
    (https://issues.rudder.io/issues/19165[#19165])

=== Bug fixes

==== Miscellaneous

* Fixed: Command rudder server node-to-relay may fail with curl error
    (https://issues.rudder.io/issues/18968[#18968])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== scale-out-relay-6.2-1.5 (2020-12-10)

=== Changes

=== Bug fixes

==== Miscellaneous

* Fixed: Add screenshots for validated users
    (https://issues.rudder.io/issues/17866[#17866])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

