= Changelogs for Rudder plugin user-management 6.2.\* versions

== user-management-6.2-1.9 (2022-02-08)

=== Changes


==== Documentation

* Add typos check in the repository
    (https://issues.rudder.io/issues/19419[#19419])

==== Packaging

* Use https repos in maven config
    (https://issues.rudder.io/issues/19165[#19165])

=== Bug fixes

==== Miscellaneous

* Fixed: The password should not be required for LDAP users
    (https://issues.rudder.io/issues/18565[#18565])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== user-management-6.2-1.8 (2020-12-10)

=== Changes

==== Packaging

* Make plugins display names more consistent
    (https://issues.rudder.io/issues/18599[#18599])

=== Bug fixes

==== Refactoring

* Fixed: Fix plugins build according to 6.2 changes
    (https://issues.rudder.io/issues/18630[#18630])

==== Miscellaneous

* Fixed: Add a note indicating that usermanagement is not subject to worflow validation
    (https://issues.rudder.io/issues/17869[#17869])
* Fixed: Optimize elm plugins
    (https://issues.rudder.io/issues/17886[#17886])

=== Release notes

This is a bug fix release in the 6.2 series and therefore all installations of 6.2.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

