= Changelogs for Rudder plugin auth-backends 8.3.\* versions

== auth-backends-8.3.0.beta1-2.7 (2025-03-07)

=== Changes


==== Architecture - evolution

* Impact of 24872 (API rights) on public plugins
    (https://issues.rudder.io/issues/26397[#26397])

==== Miscellaneous

* Add OAuth2 JWT Bearer token with client_credentials flow for Rudder API authentication
    (https://issues.rudder.io/issues/26168[#26168])

=== Bug fixes

==== Miscellaneous

* Fixed:  Add OAuth2 Opaque Accesss Bearer token with client_credentials flow for Rudder API authentication
    (https://issues.rudder.io/issues/26291[#26291])

==== UI - UX

* Fixed: Some plugins don't use the correct notification system
    (https://issues.rudder.io/issues/26279[#26279])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.3.0.alpha1-2.7 (2025-01-23)

=== Changes


==== UI - UX

* Change main menu (public plugins)
    (https://issues.rudder.io/issues/26095[#26095])

=== Bug fixes

==== Miscellaneous

* Fixed: When we use LDAP authentication backend, the error is confusing if the user doesn't exist in Rudder
    (https://issues.rudder.io/issues/26063[#26063])
* Fixed: Update scala plugin dependencies
    (https://issues.rudder.io/issues/25769[#25769])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

