= Changelogs for Rudder plugin benchmark-cis-rhel-9 8.3.\* versions

== benchmark-cis-rhel-9-8.3.2-0.10 (2025-06-04)

=== Changes


==== Miscellaneous

* Manual items report a generic message and should include the item number
    (https://issues.rudder.io/issues/26929[#26929])
* Security Benchmarks - RHEL 9 Section 5.4
    (https://issues.rudder.io/issues/26882[#26882])

=== Bug fixes

==== Miscellaneous

* Fixed: Add the intermediate genrated YAML to the repository
    (https://issues.rudder.io/issues/27030[#27030])
* Fixed:  We should check that nftables package is present in section 4.3 RHEL9
    (https://issues.rudder.io/issues/26988[#26988])
* Fixed: We should check that Firewalld package is present in section 4.2 RHEL9
    (https://issues.rudder.io/issues/26987[#26987])
* Fixed: We should check if Postfix MTA is installed before checking his config file on RHEL9 section 2.1.21
    (https://issues.rudder.io/issues/26986[#26986])
* Fixed: Replace file_check_exists method by package_present in audit mode
    (https://issues.rudder.io/issues/26984[#26984])
* Fixed: Missing section 6.2.3.4 for RHEL9
    (https://issues.rudder.io/issues/26968[#26968])
* Fixed: grep command in section 6.2.3.7 is not working
    (https://issues.rudder.io/issues/26977[#26977])
* Fixed: Typo item number 6.2.1.4
    (https://issues.rudder.io/issues/26967[#26967])
* Fixed: Invalid check for ClientAliveInterval (5.1.9) in RHEL 9 security benchmark
    (https://issues.rudder.io/issues/26928[#26928])
* Fixed: Security Benchmarks - RHEL 9 : Fixes on multiple control points
    (https://issues.rudder.io/issues/26913[#26913])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-9-8.3.1-0.10 (2025-05-07)

=== Changes


==== Miscellaneous

* Security Benchmarks - RHEL 8 Section 2
    (https://issues.rudder.io/issues/26780[#26780])
* Security Benchmarks - RHEL 9 Section 3.1 Fixes
    (https://issues.rudder.io/issues/26786[#26786])
* Security Benchmarks - RHEL 8 Setup and Section 1
    (https://issues.rudder.io/issues/26763[#26763])
* Security Benchmarks - RHEL 9 fixes
    (https://issues.rudder.io/issues/26781[#26781])

=== Bug fixes

==== Miscellaneous

* Fixed: RHEL 9 - Missing controls of section_init.k
    (https://issues.rudder.io/issues/26877[#26877])
* Fixed: RHEL 9 - Missing parameters on Sections 1.3 & 5.1
    (https://issues.rudder.io/issues/26851[#26851])
* Fixed: RHEL 9 - Missing parameters on Sections 5.2 & 6.3.2
    (https://issues.rudder.io/issues/26868[#26868])
* Fixed: RHEL9 - Missing parameters in many sections
    (https://issues.rudder.io/issues/26805[#26805])
* Fixed: Missing parameters in the cis benchmarks
    (https://issues.rudder.io/issues/26837[#26837])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-9-8.3.0-0.10 (2025-04-23)

=== Changes


==== Miscellaneous

*  Security Benchmarks - RHEL 9 Section 7
    (https://issues.rudder.io/issues/26761[#26761])
* Security Benchmarks - RHEL 9 Section 6
    (https://issues.rudder.io/issues/26759[#26759])
* Security Benchmarks - RHEL 9 Section 5
    (https://issues.rudder.io/issues/26751[#26751])
* Security Benchmarks - Rhel 9 Section 1.2 to 1.4
    (https://issues.rudder.io/issues/26705[#26705])
* Security Benchmarks - RHEL 9 Section 3
    (https://issues.rudder.io/issues/26738[#26738])
* Security Benchmarks - RHEL 9 Section 4
    (https://issues.rudder.io/issues/26750[#26750])
* Security Benchmarks - Rhel 9 Section 1.6 to 1.8
    (https://issues.rudder.io/issues/26709[#26709])
* Security Benchmarks - RHEL 9 Section 2
    (https://issues.rudder.io/issues/26735[#26735])
* Security Benchmarks - Rhel 9 Section 1.1 and 1.5
    (https://issues.rudder.io/issues/26663[#26663])

=== Bug fixes

==== Miscellaneous

* Fixed: Do not index the CIS benchmark publicly
    (https://issues.rudder.io/issues/26716[#26716])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

