= Changelogs for Rudder plugin benchmark-cis-rhel-8 8.3.\* versions

== benchmark-cis-rhel-8-8.3.2-0.10 (2025-06-04)

=== Changes


==== Miscellaneous

* Manual items report a generic message and should include the item number
    (https://issues.rudder.io/issues/26929[#26929])

=== Bug fixes

==== Miscellaneous

* Fixed: Add the intermediate generated YAML to the repository
    (https://issues.rudder.io/issues/27030[#27030])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== benchmark-cis-rhel-8-8.3.1-0.10 (2025-05-07)

=== Changes


==== Miscellaneous

* Security Benchmarks - RHEL 8 Section 2
    (https://issues.rudder.io/issues/26780[#26780])
* Security Benchmarks - RHEL 8 Section 3
    (https://issues.rudder.io/issues/26783[#26783])
* Security Benchmarks - RHEL 8 Setup and Section 1
    (https://issues.rudder.io/issues/26763[#26763])

=== Bug fixes

==== Miscellaneous

* Fixed: Missing parameters in the cis benchmarks
    (https://issues.rudder.io/issues/26837[#26837])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

