= Changelogs for Rudder plugin benchmark-cis-rhel-9 8.3.\* versions

== benchmark-cis-rhel-9-8.3.0-0.10 (2025-04-23)

=== Changes


==== Miscellaneous

*  Security Benchmarks - RHEL 9 Section 7
    (https://issues.rudder.io/issues/26761[#26761])
* Security Benchmarks - RHEL 9 Section 6
    (https://issues.rudder.io/issues/26759[#26759])
* Security Benchmarks - RHEL 9 Section 5
    (https://issues.rudder.io/issues/26751[#26751])
* Security Benchmarks - Rhel 9 Section 1.2 to 1.4
    (https://issues.rudder.io/issues/26705[#26705])
* Security Benchmarks - RHEL 9 Section 3
    (https://issues.rudder.io/issues/26738[#26738])
* Security Benchmarks - RHEL 9 Section 4
    (https://issues.rudder.io/issues/26750[#26750])
* Security Benchmarks - Rhel 9 Section 1.6 to 1.8
    (https://issues.rudder.io/issues/26709[#26709])
* Security Benchmarks - RHEL 9 Section 2
    (https://issues.rudder.io/issues/26735[#26735])
* Security Benchmarks - Rhel 9 Section 1.1 and 1.5
    (https://issues.rudder.io/issues/26663[#26663])

=== Bug fixes

==== Miscellaneous

* Fixed: Do not index the CIS benchmark publicly
    (https://issues.rudder.io/issues/26716[#26716])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

