= Changelogs for Rudder plugin branding 8.3.\* versions

== branding-8.3.2-2.2 (2025-06-05)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-8.3.1-2.2 (2025-05-07)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-8.3.0-2.2 (2025-04-23)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-8.3.0.rc1-2.2 (2025-04-10)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Branding plugin display is broken
    (https://issues.rudder.io/issues/26511[#26511])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-8.3.0.beta1-2.2 (2025-03-07)

=== Changes


==== Architecture - evolution

* Impact of 24872 (API rights) on public plugins
    (https://issues.rudder.io/issues/26397[#26397])

=== Bug fixes

==== UI - UX

* Fixed: Some plugins don't use the correct notification system
    (https://issues.rudder.io/issues/26279[#26279])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== branding-8.3.0.alpha1-2.2 (2025-01-23)

=== Changes


==== UI - UX

* Change main menu (public plugins)
    (https://issues.rudder.io/issues/26095[#26095])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

