= Changelogs for Rudder plugin change-validation 8.3.\* versions

== change-validation-8.3.0.rc1-2.4 (2025-04-10)

=== Changes


==== Miscellaneous

* The ValidationNeeded class doesn't have a test class
    (https://issues.rudder.io/issues/26686[#26686])

=== Bug fixes

==== Miscellaneous

* Fixed: Change validation links are all broken
    (https://issues.rudder.io/issues/26647[#26647])
* Fixed: Navbar menu is broken
    (https://issues.rudder.io/issues/26583[#26583])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.3.0.alpha1-2.4 (2025-01-23)

=== Changes


==== UI - UX

* Change main menu (public plugins)
    (https://issues.rudder.io/issues/26095[#26095])

=== Bug fixes

==== Miscellaneous

* Fixed: Impact of JsDataLine in change validation
    (https://issues.rudder.io/issues/26094[#26094])
* Fixed: Update scala plugin dependencies
    (https://issues.rudder.io/issues/25769[#25769])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

