= Changelogs for Rudder plugin cve 8.3.\* versions

== cve-8.3.2-2.10 (2025-06-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.3.1-2.10 (2025-05-07)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: (non impacting) CVE-2025-27820 in httpcomponents 
    (https://issues.rudder.io/issues/26819[#26819])
* Fixed: Filter on blacklisted CVE doesn't work
    (https://issues.rudder.io/issues/26754[#26754])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.3.0-2.10 (2025-04-23)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.3.0.rc1-2.10 (2025-04-10)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Blacklisted CVE may show up again when displaying a node
    (https://issues.rudder.io/issues/26667[#26667])
* Fixed: Node with blacklisted CVEs still keep count and score 
    (https://issues.rudder.io/issues/26635[#26635])
* Fixed: Wrong log line in cve blacklist bootstrap check
    (https://issues.rudder.io/issues/26551[#26551])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.3.0.beta1-2.10 (2025-03-07)

=== Changes


==== Miscellaneous

* Finalize CVE blacklist 
    (https://issues.rudder.io/issues/26347[#26347])

=== Bug fixes

==== Refactoring

* Fixed: Impact of Scala 3 - 26459 - private plugins
    (https://issues.rudder.io/issues/26461[#26461])

==== Packaging

* Fixed: Add a new requires_license field in the metadata in rudder-plugins-private
    (https://issues.rudder.io/issues/26360[#26360])

==== Miscellaneous

* Fixed: Display CVE campaign link only when system update campaign plugin is present
    (https://issues.rudder.io/issues/26314[#26314])
* Fixed: Impact of #26200: update bootstrap check in CVE
    (https://issues.rudder.io/issues/26277[#26277])
* Fixed: CVE check result keep score from old check result instead of new one.
    (https://issues.rudder.io/issues/25953[#25953])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.3.0.alpha1-2.10 (2025-01-23)

=== Changes


==== Miscellaneous

* Add a CVE blacklist
    (https://issues.rudder.io/issues/26142[#26142])
* Remediate CVE with a software update campaign
    (https://issues.rudder.io/issues/26121[#26121])

==== UI - UX

* Change main menu (private plugins)
    (https://issues.rudder.io/issues/26096[#26096])

=== Bug fixes

==== Refactoring

* Fixed: Reporting and CVE don't compile in master
    (https://issues.rudder.io/issues/26097[#26097])

==== Miscellaneous

* Fixed: Update CVE maven dependency
    (https://issues.rudder.io/issues/25897[#25897])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

