= Changelogs for Rudder plugin datasources 8.3.\* versions

== datasources-8.3.3-2.4 (2025-07-17)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Datasources edition has action buttons even for read-only user
    (https://issues.rudder.io/issues/27000[#27000])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.3.2-2.4 (2025-06-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.3.1-2.4 (2025-05-07)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Datasources link from plugin information page is broken
    (https://issues.rudder.io/issues/26764[#26764])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.3.0-2.4 (2025-04-23)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.3.0.rc1-2.4 (2025-04-10)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.3.0.beta1-2.4 (2025-03-07)

=== Changes


==== Architecture - evolution

* Impact of 24872 (API rights) on public plugins
    (https://issues.rudder.io/issues/26397[#26397])

=== Bug fixes

==== Refactoring

* Fixed: Impact of Scala 3 - 26459 - public plugins
    (https://issues.rudder.io/issues/26460[#26460])

==== Miscellaneous

* Fixed: Datasources HTTP tests are failing in 8.2
    (https://issues.rudder.io/issues/26309[#26309])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.3.0.alpha1-2.4 (2025-01-23)

=== Changes


==== UI - UX

* Change main menu (public plugins)
    (https://issues.rudder.io/issues/26095[#26095])

=== Bug fixes

==== Miscellaneous

* Fixed: in datasources, ids are not normalized, thus creating problems at deletion
    (https://issues.rudder.io/issues/26172[#26172])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

