= Changelogs for Rudder plugin dsc 8.3.\* versions

== dsc-8.3.4-2.10 (2025-09-15)

=== Changes


==== Miscellaneous

* Add a validation when changing checks to enforce 
    (https://issues.rudder.io/issues/27262[#27262])

=== Bug fixes

==== Packaging

* Fixed: Backport 27164 to 8.2
    (https://issues.rudder.io/issues/27439[#27439])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.3.2-2.9 (2025-06-04)

=== Changes


=== Bug fixes

==== System integration

* Fixed: Cannot use bash command substitution when we have the DSC plugin 
    (https://issues.rudder.io/issues/26803[#26803])

==== CLI

* Fixed: Policy server file hostname read from the policy-server.conf file should be trimmed
    (https://issues.rudder.io/issues/25561[#25561])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.3.1-2.9 (2025-05-07)

=== Changes


==== Packaging

* Add agent version file
    (https://issues.rudder.io/issues/26838[#26838])

=== Bug fixes

==== Generic methods

* Fixed: Revert the variable control when using mustache templating
    (https://issues.rudder.io/issues/26846[#26846])
* Fixed: Translate the user in local group generic method documentation to YAML
    (https://issues.rudder.io/issues/26840[#26840])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.3.0-2.9 (2025-04-23)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.3.0.rc1-2.9 (2025-04-10)

=== Changes


=== Bug fixes

==== CLI

* Fixed: Windows server 2016 define the windows_2016 condition instead of windows_server_2016
    (https://issues.rudder.io/issues/26662[#26662])
* Fixed: Remove rudderCli unapproved verbs warning
    (https://issues.rudder.io/issues/26550[#26550])
* Fixed: Unnecessary cleanup done when updating the policies
    (https://issues.rudder.io/issues/26506[#26506])

==== System techniques

* Fixed: Scheduled rudder agent run can be skipped by the task scheduler
    (https://issues.rudder.io/issues/26591[#26591])

==== Generic methods

* Fixed:  Fix the Service-Disabled method on Windows
    (https://issues.rudder.io/issues/26522[#26522])
* Fixed: The file_key_value_present_option method fails to edit files
    (https://issues.rudder.io/issues/26528[#26528])

==== Agent library

* Fixed: Re-canonify the expression before evualting them
    (https://issues.rudder.io/issues/26537[#26537])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.3.0.beta1-2.9 (2025-03-07)

=== Changes


==== Misc

* Documentation for DSC plugin should exist
    (https://issues.rudder.io/issues/26484[#26484])

==== CLI

* Improve the agent Powershell modules loading time
    (https://issues.rudder.io/issues/26440[#26440])

==== Generic methods

* Add a method to put a domain user into a local group
    (https://issues.rudder.io/issues/26420[#26420])
* Deprecate the dsc_* generic methods
    (https://issues.rudder.io/issues/26272[#26272])

==== Techniques

* Add an option Command to run after changes on this package
    (https://issues.rudder.io/issues/26118[#26118])

==== Agent library

* Upgrade the Library.Tests dependencies
    (https://issues.rudder.io/issues/26193[#26193])

=== Bug fixes

==== Packaging

* Fixed: There are still some dev files embedded in the policies
    (https://issues.rudder.io/issues/26382[#26382])
* Fixed: Add a new requires_license field in the metadata in rudder-plugins-private
    (https://issues.rudder.io/issues/26360[#26360])
* Fixed: Some build files are shipped in the plugins
    (https://issues.rudder.io/issues/26310[#26310])
* Fixed: Agent fails to compile on new builders
    (https://issues.rudder.io/issues/26419[#26419])
* Fixed: Missing UTF8 bom on the ncf.ps1 generated file
    (https://issues.rudder.io/issues/26383[#26383])
* Fixed: Initial policy are missing a value for REPORTING_PROTOCOL
    (https://issues.rudder.io/issues/26170[#26170])

==== Agent library

* Fixed: agent inventory error due to white space in path for inventory log file
    (https://issues.rudder.io/issues/26450[#26450])

==== CLI

* Fixed: Allow the extraction of zip archive to override existing files
    (https://issues.rudder.io/issues/26400[#26400])
* Fixed: On old Windows, rudder agent update can fail as the New-Item cmdlet uses do not force the file type
    (https://issues.rudder.io/issues/26287[#26287])

==== Techniques

* Fixed: Typo in the windowsSoftware technique metadata in version 2.3
    (https://issues.rudder.io/issues/26395[#26395])
* Fixed: the registry path to the rudder agent in technique windows software in rudder 7.3 is not valid anymore
    (https://issues.rudder.io/issues/22694[#22694])
* Fixed:  Windows software directive skip download check on audit mode
    (https://issues.rudder.io/issues/26299[#26299])

==== Miscellaneous

* Fixed: Rudder agent update always update the policies, even if they did not change
    (https://issues.rudder.io/issues/26281[#26281])

==== Generic methods

* Fixed: conditions from variable are not usable in other methods on windows
    (https://issues.rudder.io/issues/26245[#26245])
* Fixed: condition_from_variable* generic method do not work anymore in 8.2
    (https://issues.rudder.io/issues/26171[#26171])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.3.0.alpha1-2.9 (2025-01-23)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

