= Changelogs for Rudder plugin multi-tenants 8.3.\* versions

== multi-tenants-8.3.2-1.1 (2025-06-04)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.3.1-1.1 (2025-05-07)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.3.0-1.1 (2025-04-23)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.3.0.rc1-1.1 (2025-04-10)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Broken link to API management page
    (https://issues.rudder.io/issues/26566[#26566])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.3.0.beta1-1.1 (2025-03-07)

=== Changes


==== Architecture - evolution

* Impact of #24872 (API rights) on private plugins
    (https://issues.rudder.io/issues/26398[#26398])

=== Bug fixes

==== Packaging

* Fixed: Add a new requires_license field in the metadata in rudder-plugins-private
    (https://issues.rudder.io/issues/26360[#26360])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== multi-tenants-8.3.0.alpha1-1.1 (2025-01-23)

=== Changes


==== UI - UX

* Change main menu (private plugins)
    (https://issues.rudder.io/issues/26096[#26096])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

