= Changelogs for Rudder plugin openscap 8.3.\* versions

== openscap-8.3.1-2.2 (2025-05-07)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== openscap-8.3.0-2.2 (2025-04-23)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== openscap-8.3.0.rc1-2.2 (2025-04-10)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Openscap plugin postinst fails when the plugin is upgraded or re-installed
    (https://issues.rudder.io/issues/26670[#26670])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== openscap-8.3.0.alpha1-2.2 (2025-01-23)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Update scala plugin dependencies
    (https://issues.rudder.io/issues/25769[#25769])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

