= Changelogs for Rudder plugin security-benchmarks 8.3.\* versions

== security-benchmarks-8.3.5-1.2 (2025-10-24)

=== Changes


==== Miscellaneous

* Allow fields to have no policy mode (only disabled) and display Manual and Unimplemented tags
    (https://issues.rudder.io/issues/27714[#27714])
* Make the parameter list display more compact
    (https://issues.rudder.io/issues/27736[#27736])

=== Bug fixes

==== Miscellaneous

* Fixed: After overloading one time, can't apply via global parameter anymore
    (https://issues.rudder.io/issues/27579[#27579])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.3.5-1.1 (2025-10-02)

=== Changes


==== Miscellaneous

* Bootstrap security benchmark documentation
    (https://issues.rudder.io/issues/27593[#27593])

=== Bug fixes

==== Miscellaneous

* Fixed: "No data available" at some level of benchmark for items, not for node
    (https://issues.rudder.io/issues/27656[#27656])
* Fixed: fix typo in readme
    (https://issues.rudder.io/issues/27637[#27637])
* Fixed: Balance score computation on a more optimistic basis
    (https://issues.rudder.io/issues/27582[#27582])
* Fixed: There are some "null" in the bench descriptions
    (https://issues.rudder.io/issues/27583[#27583])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.3.4-1.1 (2025-09-15)

=== Changes


==== Miscellaneous

* User should not be able to select system groups as targets
    (https://issues.rudder.io/issues/27349[#27349])
* No Answer nodes should be ignored in benchmark score, missing reports message improvement
    (https://issues.rudder.io/issues/27495[#27495])
* Add a validation when changing checks to enforce 
    (https://issues.rudder.io/issues/27262[#27262])
* Enforce a precise kcl version
    (https://issues.rudder.io/issues/27377[#27377])
* Add links between the dashboard and the score details tab
    (https://issues.rudder.io/issues/27378[#27378])
* Add filters to score details
    (https://issues.rudder.io/issues/27351[#27351])
* Add a confirmation step before deleting a benchmark
    (https://issues.rudder.io/issues/27361[#27361])
* Improve display of sub items in node score details
    (https://issues.rudder.io/issues/27332[#27332])
* Improve benchmark dashboard
    (https://issues.rudder.io/issues/27312[#27312])
* Turn the Summary tab into a dashboard view
    (https://issues.rudder.io/issues/27257[#27257])

=== Bug fixes

==== Miscellaneous

* Fixed: Score computation rules need adjustments
    (https://issues.rudder.io/issues/27403[#27403])
* Fixed: Order of control points in nodes reporting is not correct
    (https://issues.rudder.io/issues/27288[#27288])
* Fixed: Multiplication of rudder_auto_conditions
    (https://issues.rudder.io/issues/27334[#27334])
* Fixed: Scores shown missing reports for reports that are no longer expected
    (https://issues.rudder.io/issues/27280[#27280])
* Fixed: When selecting Targets, the filter search does not filter anything
    (https://issues.rudder.io/issues/26471[#26471])
* Fixed: Score computation takes disabled sections into account
    (https://issues.rudder.io/issues/27380[#27380])
* Fixed: Create documentation on how the benchmark are created/built/tested
    (https://issues.rudder.io/issues/27376[#27376])
* Fixed: Setting section to enforce change checks that only have audit/disable as existing states
    (https://issues.rudder.io/issues/27347[#27347])
* Fixed: multiple missing bash for calling ressources script
    (https://issues.rudder.io/issues/27355[#27355])
* Fixed: Chart is not updated when new score is fetched from the API
    (https://issues.rudder.io/issues/27335[#27335])
* Fixed: metadata.json generated is incomplete
    (https://issues.rudder.io/issues/27291[#27291])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.3.2-1.1 (2025-06-04)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Add the intermediate generated YAML to the repository
    (https://issues.rudder.io/issues/27030[#27030])
* Fixed: Small score icon when text is wrapping
    (https://issues.rudder.io/issues/26960[#26960])
* Fixed: Cannot configure the benchmark because of long description of items 
    (https://issues.rudder.io/issues/26741[#26741])
* Fixed: Duplicate files in benchmark build
    (https://issues.rudder.io/issues/26807[#26807])
* Fixed: Do not load directly technique category XML
    (https://issues.rudder.io/issues/26937[#26937])
* Fixed: Support security benchmark parameter constraints
    (https://issues.rudder.io/issues/26893[#26893])
* Fixed: Benchmark should not contain model, only use an id as reference
    (https://issues.rudder.io/issues/26822[#26822])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.3.1-1.1 (2025-05-07)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Display tags and limit mode to support policy mode
    (https://issues.rudder.io/issues/26769[#26769])
* Fixed: Missing report in enforce on item 2.1.1 on debian like systems
    (https://issues.rudder.io/issues/26829[#26829])
* Fixed: Compilation errors after #26712
    (https://issues.rudder.io/issues/26820[#26820])
* Fixed: Missing /var/rudder/plugins/security-benchmarks/install folder after install
    (https://issues.rudder.io/issues/26816[#26816])
* Fixed: Cannot save a benchmark (rhel9)
    (https://issues.rudder.io/issues/26742[#26742])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.3.0-1.1 (2025-04-23)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed:  Make the benchmark-cis-dummy plugin use the new security-benchmark API
    (https://issues.rudder.io/issues/26696[#26696])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.3.0.rc1-1.1 (2025-04-10)

=== Changes


==== Miscellaneous

* Security Benchmarks - Rhel 9 Section 1.1 and 1.5
    (https://issues.rudder.io/issues/26663[#26663])
* Add a benchmark model management api to install/remove models
    (https://issues.rudder.io/issues/26645[#26645])
* Adding descriptions to sections and control points
    (https://issues.rudder.io/issues/26454[#26454])

=== Bug fixes

==== Miscellaneous

* Fixed: Score of benchmark seems to never expire
    (https://issues.rudder.io/issues/26453[#26453])
* Fixed: Add sub plugins to distribute benchmarks
    (https://issues.rudder.io/issues/26529[#26529])
* Fixed: Make rsc01 coherent between branches
    (https://issues.rudder.io/issues/26509[#26509])
* Fixed: Fix some typos
    (https://issues.rudder.io/issues/26467[#26467])

==== UI - UX

* Fixed: Patch and security benchmark menu order
    (https://issues.rudder.io/issues/26534[#26534])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.3.0.beta1-1.1 (2025-03-07)

=== Changes


==== Miscellaneous

* Add description to the CIS benchmark items
    (https://issues.rudder.io/issues/26197[#26197])

=== Bug fixes

==== Miscellaneous

* Fixed: Score is not updated when a new score is added
    (https://issues.rudder.io/issues/26393[#26393])
* Fixed: Documentation is always shown and we can't hide it
    (https://issues.rudder.io/issues/26280[#26280])
* Fixed: When we create a new benchmark, the existing rudder_auto_conditions are purged
    (https://issues.rudder.io/issues/26329[#26329])
* Fixed: Missing reporting on applied method
    (https://issues.rudder.io/issues/26073[#26073])
* Fixed: Improve reporting to include more cases
    (https://issues.rudder.io/issues/26295[#26295])
* Fixed: Url are not correctly set in plugin since menu rewriting in 8.3
    (https://issues.rudder.io/issues/26294[#26294])
* Fixed: Resolve the rudderc dependency in the Makefile
    (https://issues.rudder.io/issues/26293[#26293])
* Fixed: Set the policy_types of the CIS benchmark in the KCL configuration
    (https://issues.rudder.io/issues/26276[#26276])
* Fixed: Missing policy type for rsc01
    (https://issues.rudder.io/issues/26274[#26274])

==== Packaging

* Fixed: Add a new requires_license field in the metadata in rudder-plugins-private
    (https://issues.rudder.io/issues/26360[#26360])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.3.0.alpha1-1.0 (2025-01-23)

=== Changes


==== Miscellaneous

* Port the CIS ubuntu20 benchmark to security benchmark
    (https://issues.rudder.io/issues/26053[#26053])

==== UI - UX

* Change main menu (private plugins)
    (https://issues.rudder.io/issues/26096[#26096])

=== Bug fixes

==== Miscellaneous

* Fixed: Improve benchmark documentation display and accessibility
    (https://issues.rudder.io/issues/26038[#26038])
* Fixed: Improve and correct reporting display of benchmarks
    (https://issues.rudder.io/issues/25732[#25732])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

