= Changelogs for Rudder plugin security-benchmarks 8.3.\* versions

== security-benchmarks-8.3.0.beta1-1.1 (2025-03-07)

=== Changes


==== Miscellaneous

* Add description to the CIS benchmark items
    (https://issues.rudder.io/issues/26197[#26197])

=== Bug fixes

==== Miscellaneous

* Fixed: Score is not updated when a new score is added
    (https://issues.rudder.io/issues/26393[#26393])
* Fixed: Documentation is always shown and we can't hide it
    (https://issues.rudder.io/issues/26280[#26280])
* Fixed: When we create a new benchmark, the existing rudder_auto_conditions are purged
    (https://issues.rudder.io/issues/26329[#26329])
* Fixed: Missing reporting on applied method
    (https://issues.rudder.io/issues/26073[#26073])
* Fixed: Improve reporting to include more cases
    (https://issues.rudder.io/issues/26295[#26295])
* Fixed: Url are not correctly set in plugin since menu rewriting in 8.3
    (https://issues.rudder.io/issues/26294[#26294])
* Fixed: Resolve the rudderc dependency in the Makefile
    (https://issues.rudder.io/issues/26293[#26293])
* Fixed: Set the policy_types of the CIS benchmark in the KCL configuration
    (https://issues.rudder.io/issues/26276[#26276])
* Fixed: Missing policy type for rsc01
    (https://issues.rudder.io/issues/26274[#26274])

==== Packaging

* Fixed: Add a new requires_license field in the metadata in rudder-plugins-private
    (https://issues.rudder.io/issues/26360[#26360])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== security-benchmarks-8.3.0.alpha1-1.0 (2025-01-23)

=== Changes


==== Miscellaneous

* Port the CIS ubuntu20 benchmark to security benchmark
    (https://issues.rudder.io/issues/26053[#26053])

==== UI - UX

* Change main menu (private plugins)
    (https://issues.rudder.io/issues/26096[#26096])

=== Bug fixes

==== Miscellaneous

* Fixed: Improve benchmark documentation display and accessibility
    (https://issues.rudder.io/issues/26038[#26038])
* Fixed: Improve and correct reporting display of benchmarks
    (https://issues.rudder.io/issues/25732[#25732])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

