= Changelogs for Rudder plugin system-updates 8.3.\* versions

== system-updates-8.3.3-1.18 (2025-08-20)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Incorrect relative path of Json file in the Software Update campaign type
    (https://issues.rudder.io/issues/27465[#27465])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.3.2-1.17 (2025-06-04)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: System update don't raise an error when all is failing
    (https://issues.rudder.io/issues/26923[#26923])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.3.1-1.17 (2025-05-07)

=== Changes


==== Miscellaneous

* Add filters to campaign events
    (https://issues.rudder.io/issues/26798[#26798])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.3.0-1.17 (2025-04-23)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: System update python module should fails when workdir does not exists
    (https://issues.rudder.io/issues/26740[#26740])
* Fixed: No scrollbar in patch campaign command output
    (https://issues.rudder.io/issues/26689[#26689])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.3.0.rc1-1.17 (2025-04-10)

=== Changes


=== Bug fixes

==== Module - system-updates

* Fixed: Missing timezone setup for one shot campaigns
    (https://issues.rudder.io/issues/26443[#26443])

==== Miscellaneous

* Fixed: cannot set the architecture in a software update campaign
    (https://issues.rudder.io/issues/26610[#26610])
* Fixed: Annoying line returns in the form to create update campaign
    (https://issues.rudder.io/issues/26490[#26490])

==== UI - UX

* Fixed: Patch and security benchmark menu order
    (https://issues.rudder.io/issues/26534[#26534])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.3.0.beta1-1.17 (2025-03-07)

=== Changes


=== Bug fixes

==== Refactoring

* Fixed: Impact of Scala 3 - 26459 - private plugins
    (https://issues.rudder.io/issues/26461[#26461])

==== Packaging

* Fixed: Add a new requires_license field in the metadata in rudder-plugins-private
    (https://issues.rudder.io/issues/26360[#26360])

==== Miscellaneous

* Fixed: impossible to disable a campaign in update campaigns menu
    (https://issues.rudder.io/issues/26208[#26208])
* Fixed: Campaign on SUSE family nodes fail due to unknown flag name on zypper command
    (https://issues.rudder.io/issues/26198[#26198])

==== Module - system-updates

* Fixed: System update campaign targeting Rudder server causes “Missing report” from server
    (https://issues.rudder.io/issues/26189[#26189])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.3.0.alpha1-1.17 (2025-01-23)

=== Changes


==== UI - UX

* Change main menu (private plugins)
    (https://issues.rudder.io/issues/26096[#26096])

==== Miscellaneous

* Remediate CVE with a software update campaign
    (https://issues.rudder.io/issues/26121[#26121])
* Update elm dependencies
    (https://issues.rudder.io/issues/26050[#26050])

=== Bug fixes

==== Miscellaneous

* Fixed: Campaign event should be exportable to CSV
    (https://issues.rudder.io/issues/26113[#26113])
* Fixed: Software update campaign generate invalid cfengine
    (https://issues.rudder.io/issues/25597[#25597])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

