= Changelogs for Rudder plugin system-updates 8.3.\* versions

== system-updates-8.3.0.beta1-1.17 (2025-03-07)

=== Changes


=== Bug fixes

==== Refactoring

* Fixed: Impact of Scala 3 - 26459 - private plugins
    (https://issues.rudder.io/issues/26461[#26461])

==== Packaging

* Fixed: Add a new requires_license field in the metadata in rudder-plugins-private
    (https://issues.rudder.io/issues/26360[#26360])

==== Miscellaneous

* Fixed: impossible to disable a campaign in update campaigns menu
    (https://issues.rudder.io/issues/26208[#26208])
* Fixed: Campaign on SUSE family nodes fail due to unknown flag name on zypper command
    (https://issues.rudder.io/issues/26198[#26198])

==== Module - system-updates

* Fixed: System update campaign targeting Rudder server causes “Missing report” from server
    (https://issues.rudder.io/issues/26189[#26189])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.3.0.alpha1-1.17 (2025-01-23)

=== Changes


==== UI - UX

* Change main menu (private plugins)
    (https://issues.rudder.io/issues/26096[#26096])

==== Miscellaneous

* Remediate CVE with a software update campaign
    (https://issues.rudder.io/issues/26121[#26121])
* Update elm dependencies
    (https://issues.rudder.io/issues/26050[#26050])

=== Bug fixes

==== Miscellaneous

* Fixed: Campaign event should be exportable to CSV
    (https://issues.rudder.io/issues/26113[#26113])
* Fixed: Software update campaign generate invalid cfengine
    (https://issues.rudder.io/issues/25597[#25597])

=== Release notes

This is a bug fix release in the 8.3 series and therefore all installations of 8.3.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

