Changelogs for Rudder plugin datasources 4.2.* versions
-------------------------------------------------------

 Plugin datasources - datasources-4.2-1.2 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Packaging
+++++++++

* Separate scala plugin makefiles from generic plugin makefiles
(https://issues.rudder.io/issues/11758[#11758])

Bug fixes
^^^^^^^^^

Miscellaneous
+++++++++++++

* Fixed: Exception and stacktrace with datasources plugin
(https://issues.rudder.io/issues/12412[#12412])
* Fixed: "" in build.conf description leads to unreacoverable exception
during boot (https://issues.rudder.io/issues/12275[#12275])
* Fixed: datasources plugin is missing LICENSE file
(https://issues.rudder.io/issues/12170[#12170])

Packaging
+++++++++

* Fixed: Use pom-template.xml + makefile to avoid variables in artifact
version in pom.xml (https://issues.rudder.io/issues/12257[#12257])
* Fixed: Normalize plugin build structure
(https://issues.rudder.io/issues/12171[#12171])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin datasources - datasources-4.2-1.1 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Miscellaneous
+++++++++++++

* Update datasource to license framework 1.1.0
(https://issues.rudder.io/issues/11666[#11666])

Bug fixes
^^^^^^^^^

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
