Changelogs for Rudder plugin dsc 4.2.* versions
-----------------------------------------------

 Plugin dsc - dsc-4.2-1.10 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Bug fixes
^^^^^^^^^

Miscellaneous
+++++++++++++

* Fixed: The GM file_download does not create missing folders in path
(https://issues.rudder.io/issues/12900[#12900])
* Fixed: The GM file_download does not create missing folders in path
(https://issues.rudder.io/issues/12900[#12900])
* Fixed: Windows Component present/absent are not working from the
technique editor (https://issues.rudder.io/issues/12753[#12753])

ncf
+++

* Fixed: Missing folder for the KB_present GM
(https://issues.rudder.io/issues/12899[#12899])
* Fixed: Because of wrong encoding for nxlog config file, nxlog fails to
start (https://issues.rudder.io/issues/12972[#12972])
* Fixed: Files enforce content does not UTF8
(https://issues.rudder.io/issues/12935[#12935])
* Fixed: File_copy_from_local_source does not create the path when it is
not already defined (https://issues.rudder.io/issues/12833[#12833])
* Fixed: Variable_Dict GM fails when executed on an already existing
variable (https://issues.rudder.io/issues/12826[#12826])
* Fixed: Variable_String GM fails when executed on an already existing
variable (https://issues.rudder.io/issues/12818[#12818])

Packaging
+++++++++

* Fixed: zip must be a binary dependency for the package
(https://issues.rudder.io/issues/12794[#12794])
* Fixed: Postinst script is always ending with errors because openssl
can not find its conf file
(https://issues.rudder.io/issues/12776[#12776])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-1.9 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Miscellaneous
+++++++++++++

* Add a windows hotfix present GM
(https://issues.rudder.io/issues/12727[#12727])
* Add a condition_from_variable GM
(https://issues.rudder.io/issues/12575[#12575])
* Add a condition_from_variable GM
(https://issues.rudder.io/issues/12575[#12575])

ncf
+++

* Add a windows hotfix absent GM
(https://issues.rudder.io/issues/12726[#12726])

Bug fixes
^^^^^^^^^

System integration
++++++++++++++++++

* Fixed: DSC agent may stay in no answer because of nxlog
(https://issues.rudder.io/issues/11376[#11376])

Miscellaneous
+++++++++++++

* Fixed: condition_from_variable_match is generating wrong classes
(https://issues.rudder.io/issues/12746[#12746])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-1.8 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Bug fixes
^^^^^^^^^

Packaging
+++++++++

* Fixed: Release version 1.8 of windows agent/plugin
(https://issues.rudder.io/issues/12612[#12612])

Miscellaneous
+++++++++++++

* Fixed: Changing windows logger need some service restart
(https://issues.rudder.io/issues/12523[#12523])
* Fixed: registry_entry_present does not work properly in audit mode and
with wrong inputs (https://issues.rudder.io/issues/12551[#12551])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-1.7 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Miscellaneous
+++++++++++++

* Add optional verbose logs on dsc agent
(https://issues.rudder.io/issues/12403[#12403])
* Add a technique to manage installed softwares on the windows agent
(https://issues.rudder.io/issues/12494[#12494])
* Add a variable_string_from_command GM
(https://issues.rudder.io/issues/12492[#12492])
* Add a dedicated rudder application event log
(https://issues.rudder.io/issues/12413[#12413])

Bug fixes
^^^^^^^^^

Miscellaneous
+++++++++++++

* Fixed: nxlog was not well started
(https://issues.rudder.io/issues/12401[#12401])
* Fixed: Command execution GM is not reporting properly
(https://issues.rudder.io/issues/12484[#12484])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-1.6 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Rudder web app
++++++++++++++

* Release version 1.6 of plugin compatible with Rudder 4.2.5
(https://issues.rudder.io/issues/12456[#12456])

Bug fixes
^^^^^^^^^

Rudder web app
++++++++++++++

* Fixed: Upgrade Windows Agent to implement parameter escape API
(https://issues.rudder.io/issues/12405[#12405])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-1.5 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Bug fixes
^^^^^^^^^

Packaging
+++++++++

* Fixed: When we upgrade dsc plugin, techniques are not reloaded
automatically (https://issues.rudder.io/issues/12327[#12327])

System techniques
+++++++++++++++++

* Fixed: Broken policy generation
(https://issues.rudder.io/issues/12315[#12315])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-1.4 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Bug fixes
^^^^^^^^^

System techniques
+++++++++++++++++

* Fixed: Windows Agent ``last seen'' never
(https://issues.rudder.io/issues/12160[#12160])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* pierrick prost

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-1.3 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

System integration
++++++++++++++++++

* NXlog configuration cannot be modified
(https://issues.rudder.io/issues/12088[#12088])

Bug fixes
^^^^^^^^^

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-1.2 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Miscellaneous
+++++++++++++

* Use rudder to dsify techniques instead of ncf
(https://issues.rudder.io/issues/11817[#11817])

Bug fixes
^^^^^^^^^

ncf
+++

* Fixed: Implement condition_from_command in dsc
(https://issues.rudder.io/issues/11815[#11815])
* Fixed: windows component present installs a component in audit mode
(https://issues.rudder.io/issues/11767[#11767])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-1.1 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Packaging
+++++++++

* Release version 1.1. of dsc plugin/agent
(https://issues.rudder.io/issues/11659[#11659])

Bug fixes
^^^^^^^^^

Rudder web app
++++++++++++++

* Fixed: Bootstrap creation of DSC groups is not done
(https://issues.rudder.io/issues/11657[#11657])
* Fixed: DSC system group must be created in plugin
(https://issues.rudder.io/issues/11590[#11590])

System techniques
+++++++++++++++++

* Fixed: ``System variables definition parameters'' component name is
too long (https://issues.rudder.io/issues/11441[#11441])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-1.0 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Packaging
+++++++++

* Release v1.0 of windows agent and plugin.
(https://issues.rudder.io/issues/11446[#11446])

Rudder web app
++++++++++++++

* Add license to dsc plugin
(https://issues.rudder.io/issues/11413[#11413])

System techniques
+++++++++++++++++

* Add support for node properties and Rudder parameters to the DSC agent
(https://issues.rudder.io/issues/11404[#11404])

Miscellaneous
+++++++++++++

* add a File_Download generic method
(https://issues.rudder.io/issues/11343[#11343])
* Adding type field in windows registry present GM
(https://issues.rudder.io/issues/11352[#11352])
* make a dsc version of registry edition technique
(https://issues.rudder.io/issues/11354[#11354])
* make a dsc version of registry edition technique
(https://issues.rudder.io/issues/11354[#11354])
* Add a File_from_template_mustache generic method
(https://issues.rudder.io/issues/11242[#11242])
* Add a variable_string generic_method in dsc
(https://issues.rudder.io/issues/11256[#11256])
* Add a variable_dict_from_file generic method
(https://issues.rudder.io/issues/11269[#11269])

CLI
+++

* Add some colors to agent output
(https://issues.rudder.io/issues/10926[#10926])

Bug fixes
^^^^^^^^^

Packaging
+++++++++

* Fixed: Bad path for demo license file
(https://issues.rudder.io/issues/11440[#11440])
* Fixed: Error at generation after reinstalling rudder windows plugin
(https://issues.rudder.io/issues/11387[#11387])
* Fixed: Fix dsc policy generation tests
(https://issues.rudder.io/issues/11400[#11400])
* Fixed: always update agent schedule when reinstalling agent
(https://issues.rudder.io/issues/11368[#11368])

Rudder web app
++++++++++++++

* Fixed: Missing private repositories
(https://issues.rudder.io/issues/11436[#11436])
* Fixed: Tests are broken after #11406
(https://issues.rudder.io/issues/11419[#11419])

System techniques
+++++++++++++++++

* Fixed: .st files are distributed to the nodes
(https://issues.rudder.io/issues/11425[#11425])
* Fixed: Error when running agent right after install
(https://issues.rudder.io/issues/11292[#11292])

ncf
+++

* Fixed: Change report message of dsc generic methods (part 1)
(https://issues.rudder.io/issues/11369[#11369])
* Fixed: Wrong reporting on generic method File from shared folder
(https://issues.rudder.io/issues/11357[#11357])
* Fixed: componentKey error in Variable-String
(https://issues.rudder.io/issues/11349[#11349])

Miscellaneous
+++++++++++++

* Fixed: Json file of variables
(https://issues.rudder.io/issues/11379[#11379])
* Fixed: file template from mustache template fails when destination is
an empty file (https://issues.rudder.io/issues/11374[#11374])
* Fixed: Agent installer waiting for entries
(https://issues.rudder.io/issues/11373[#11373])
* Fixed: file_copy_from_local patch
(https://issues.rudder.io/issues/11366[#11366])
* Fixed: Missing new standard features in variable string/merge GM
(https://issues.rudder.io/issues/11364[#11364])
* Fixed: missing some state in the agent
(https://issues.rudder.io/issues/11360[#11360])
* Fixed: Techniques are not updated correctly to work on dsc at plugin
install/update (https://issues.rudder.io/issues/11345[#11345])
* Fixed: file_from_shared_folder GM does not handle _
(https://issues.rudder.io/issues/11333[#11333])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-0.4 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Miscellaneous
+++++++++++++

* Add a variable_dict_merge generic method
(https://issues.rudder.io/issues/11271[#11271])
* Add a Windows_Component_absent GM
(https://issues.rudder.io/issues/11321[#11321])
* Add a Windows_Component_present GM
(https://issues.rudder.io/issues/11319[#11319])
* Add a Service-started-at-boot in dsc
(https://issues.rudder.io/issues/11312[#11312])
* Add a Service-stopped-at-boot in dsc
(https://issues.rudder.io/issues/11315[#11315])
* Add a Service-Restart GM in dsc
(https://issues.rudder.io/issues/11311[#11311])
* Add a variable_dict generic method
(https://issues.rudder.io/issues/11267[#11267])
* Add a variable_from_file generic method
(https://issues.rudder.io/issues/11265[#11265])
* rename rudder variables
(https://issues.rudder.io/issues/11247[#11247])
* Add a File_copy_from_local_source generic method
(https://issues.rudder.io/issues/11236[#11236])
* user_present/absent reports
(https://issues.rudder.io/issues/11200[#11200])
* Add a generic method command_execution
(https://issues.rudder.io/issues/11170[#11170])

ncf
+++

* Change reporting message format in ncf agent
(https://issues.rudder.io/issues/11276[#11276])
* Add a parameter to generic methods to configure reporting key if
needed (https://issues.rudder.io/issues/11273[#11273])
* Add generic method to manage registry keys
(https://issues.rudder.io/issues/11240[#11240])
* Add a generic method to download from shared folder
(https://issues.rudder.io/issues/11165[#11165])
* Reporting is mixed with action in generic method, so we can’t call a
generic method from another generic method
(https://issues.rudder.io/issues/11103[#11103])

Bug fixes
^^^^^^^^^

Miscellaneous
+++++++++++++

* Fixed: user_password debug prompt
(https://issues.rudder.io/issues/11337[#11337])
* Fixed: Missing .cf files
(https://issues.rudder.io/issues/11325[#11325])
* Fixed: fix file_from_server method
(https://issues.rudder.io/issues/11302[#11302])
* Fixed: fix file_from_server method
(https://issues.rudder.io/issues/11302[#11302])
* Fixed: user_present audit mode
(https://issues.rudder.io/issues/11202[#11202])

ncf
+++

* Fixed: Policy generation fails due to duplicate bundle
(https://issues.rudder.io/issues/11332[#11332])
* Fixed: Remove code from ncf placeholder methods
(https://issues.rudder.io/issues/11294[#11294])
* Fixed: Unexpected reporting due to mismatch between component name in
generic method .ps1 and @name in equivalent for .cf
(https://issues.rudder.io/issues/11293[#11293])
* Fixed: Generic method wrong function name
(https://issues.rudder.io/issues/11196[#11196])
* Fixed: user_present method
(https://issues.rudder.io/issues/11189[#11189])

Packaging
+++++++++

* Fixed: Error when installing plugin rpk
(https://issues.rudder.io/issues/11298[#11298])
* Fixed: Wrong permissions in dsc techniques
(https://issues.rudder.io/issues/11184[#11184])
* Fixed: zip may be missing from system (ie on my Ubuntu 16)
(https://issues.rudder.io/issues/11115[#11115])

Rudder web app
++++++++++++++

* Fixed: Remove json generation done for all agent type
(https://issues.rudder.io/issues/11227[#11227])
* Fixed: DSC plugin def is the one of DataSource plugin
(https://issues.rudder.io/issues/11175[#11175])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-0.3 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

ncf
+++

* Add extra generic methods for DSC
(https://issues.rudder.io/issues/11104[#11104])

Packaging
+++++++++

* windows agent certificate should contain the uuid instead of the
hostname (https://issues.rudder.io/issues/11032[#11032])

Bug fixes
^^^^^^^^^

Miscellaneous
+++++++++++++

* Fixed: Missing end run report from agent
(https://issues.rudder.io/issues/11026[#11026])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.

 Plugin dsc - dsc-4.2-0.2 (2018-11-28)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Changes
^^^^^^^

Miscellaneous
+++++++++++++

* Make 4.2-0.2 plugin release
(https://issues.rudder.io/issues/11108[#11108])
* Creata a task to run automatically inventory at night
(https://issues.rudder.io/issues/10918[#10918])
* Normalize call to Techniques
(https://issues.rudder.io/issues/10869[#10869])
* Improve reporting (https://issues.rudder.io/issues/10806[#10806])
* Create a generic method to edit file based on a template
(https://issues.rudder.io/issues/10822[#10822])
* Configure nxlog to send reports to the rudder server
(https://issues.rudder.io/issues/10802[#10802])
* Add time classes (https://issues.rudder.io/issues/10804[#10804])
* Generate inventory - first iteration
(https://issues.rudder.io/issues/10800[#10800])
* Add classes management (https://issues.rudder.io/issues/10789[#10789])
* Add reporting to eventlog in agent
(https://issues.rudder.io/issues/10794[#10794])
* Automatically load all generic method and technique files
(https://issues.rudder.io/issues/10790[#10790])
* Add second generic method on User, factor logging code, and detect
error/repaired status (https://issues.rudder.io/issues/10784[#10784])
* First iteration on generic method/technique/loading
(https://issues.rudder.io/issues/10777[#10777])

ncf
+++

* Add directory_create and file_create generic methods
(https://issues.rudder.io/issues/10892[#10892])
* Initial policies should contain no techniques
(https://issues.rudder.io/issues/10966[#10966])
* Normalize generic method format
(https://issues.rudder.io/issues/10831[#10831])

Rudder web app
++++++++++++++

* Move in code from Rudder into the plugin
(https://issues.rudder.io/issues/11073[#11073])

System techniques
+++++++++++++++++

* Change start and end reports for plugin
(https://issues.rudder.io/issues/11036[#11036])
* Load system variables from a json file
(https://issues.rudder.io/issues/10886[#10886])

Packaging
+++++++++

* Add a hook to create dsc version on a technique
(https://issues.rudder.io/issues/11019[#11019])
* Call inventory during postinstall
(https://issues.rudder.io/issues/10921[#10921])
* Support only 64 bits windows
(https://issues.rudder.io/issues/10950[#10950])
* Agent certificate must be a CA to be self signed and able to
authenticate on apache (https://issues.rudder.io/issues/10944[#10944])
* Create a rudder plugin for server-side windows support
(https://issues.rudder.io/issues/10935[#10935])
* Change names in fusion and package accordingly to naming convention
(https://issues.rudder.io/issues/10932[#10932])
* Finish agent command line
(https://issues.rudder.io/issues/10930[#10930])
* Rework windows installer to make debugging easier
(https://issues.rudder.io/issues/10924[#10924])
* Create a rudder executable and make it available in the PATH
(https://issues.rudder.io/issues/10896[#10896])
* Policy server should be in etc
(https://issues.rudder.io/issues/10878[#10878])
* create uuid in lowercase
(https://issues.rudder.io/issues/10882[#10882])
* Create a self signed certificate instead of a public key
(https://issues.rudder.io/issues/10841[#10841])
* Add Rudder-agent sofware information on Windows to have it inventory
(https://issues.rudder.io/issues/10830[#10830])
* First iteration on windows agent packaging
(https://issues.rudder.io/issues/10736[#10736])

CLI
+++

* Update policy using client authentication
(https://issues.rudder.io/issues/10957[#10957])
* Add an help command for CLI
(https://issues.rudder.io/issues/10874[#10874])
* add an update command (https://issues.rudder.io/issues/10888[#10888])
* Add execution time computation to the CLI
(https://issues.rudder.io/issues/10873[#10873])
* Add rudder agent enable/disable
(https://issues.rudder.io/issues/10872[#10872])

System integration
++++++++++++++++++

* Scheduling / execution engine
(https://issues.rudder.io/issues/10740[#10740])
* Change Rudder.pm file in fusion-invneoty to look for windows-dsc agent
(https://issues.rudder.io/issues/10756[#10756])

Bug fixes
^^^^^^^^^

ncf
+++

* Fixed: file_enforce_content is not working
(https://issues.rudder.io/issues/11133[#11133])
* Fixed: When we install dsc plugin, existing techniques generated with
technique editor are not updated
(https://issues.rudder.io/issues/11132[#11132])
* Fixed: File from template does not work when the destination does not
exist (https://issues.rudder.io/issues/10867[#10867])
* Fixed: Allow defining a class that is already defined
(https://issues.rudder.io/issues/10866[#10866])

Packaging
+++++++++

* Fixed: Add cfengine methods for service_status and user_status so they
can be used in technique editor
(https://issues.rudder.io/issues/11091[#11091])
* Fixed: We are distributing rudder.json, rudder-directives.ps1 and
rudder-system-directives.ps1 from initial policies
(https://issues.rudder.io/issues/11090[#11090])
* Fixed: DSC ps1 file is not added in the technique repository after
generation (https://issues.rudder.io/issues/11065[#11065])
* Fixed: Use the version from makefile everywhere
(https://issues.rudder.io/issues/11056[#11056])
* Fixed: Broken UUID generation
(https://issues.rudder.io/issues/10893[#10893])
* Fixed: A new cert is created during every install
(https://issues.rudder.io/issues/10884[#10884])
* Fixed: Wrong installation destination for Rudder
(https://issues.rudder.io/issues/10853[#10853])
* Fixed: Installer cannot install rudder agent dsc
(https://issues.rudder.io/issues/10844[#10844])
* Fixed: Create agent key and parse it in inventory
(https://issues.rudder.io/issues/10817[#10817])

Rudder web app
++++++++++++++

* Fixed: error in dscify hook when creating technique
(https://issues.rudder.io/issues/11092[#11092])

System techniques
+++++++++++++++++

* Fixed: invalid reporting from system technique
(https://issues.rudder.io/issues/11070[#11070])
* Fixed: Load user technique ``.ps1''
(https://issues.rudder.io/issues/11078[#11078])
* Fixed: Missing rudder.ps1 in plugin
(https://issues.rudder.io/issues/11000[#11000])
* Fixed: Missing template for rudder-directives /
rudder-system-directives (https://issues.rudder.io/issues/10968[#10968])
* Fixed: Broken syntax in agent
(https://issues.rudder.io/issues/10851[#10851])

Miscellaneous
+++++++++++++

* Fixed: missing closing ) in dsc agent to read build-info.json
(https://issues.rudder.io/issues/11069[#11069])
* Fixed: policies are not correctly compressed
(https://issues.rudder.io/issues/11068[#11068])
* Fixed: Missing end run report from agent
(https://issues.rudder.io/issues/11026[#11026])
* Fixed: Wrong permission for /var/rudder/configuration-repository/dsc
(https://issues.rudder.io/issues/11022[#11022])
* Fixed: Generated promises are invalid
(https://issues.rudder.io/issues/11024[#11024])
* Fixed: No reports from dsc node
(https://issues.rudder.io/issues/11017[#11017])
* Fixed: Typo in 91-compress-dsc-policies
(https://issues.rudder.io/issues/11008[#11008])
* Fixed: Replace ReportIdentifier by ReportId in initial promises
(https://issues.rudder.io/issues/10954[#10954])
* Fixed: Missing default json properties file
(https://issues.rudder.io/issues/10902[#10902])
* Fixed: Add an inventory command
(https://issues.rudder.io/issues/10815[#10815])
* Fixed: Missing node name in inventory file name
(https://issues.rudder.io/issues/10865[#10865])
* Fixed: no eventlog source created after install
(https://issues.rudder.io/issues/10863[#10863])
* Fixed: Agent log are not inserted in database
(https://issues.rudder.io/issues/10828[#10828])
* Fixed: nodeuuid is not correctly fetched by policies
(https://issues.rudder.io/issues/10827[#10827])
* Fixed: Correctly detect when log config file need to be changed
(https://issues.rudder.io/issues/10821[#10821])
* Fixed: missing variables definition in agent
(https://issues.rudder.io/issues/10813[#10813])
* Fixed: Reset culture in rudder agent
(https://issues.rudder.io/issues/10814[#10814])
* Fixed: Add pretty display for execution and reports
(https://issues.rudder.io/issues/10803[#10803])

System integration
++++++++++++++++++

* Fixed: Scheduled tasks don’t work (and missing update task)
(https://issues.rudder.io/issues/11003[#11003])
* Fixed: Hook that zips policy don’t take agent resource
(https://issues.rudder.io/issues/11011[#11011])
* Fixed: Generated policy are zipped with ``rules.new'' directory
(https://issues.rudder.io/issues/10970[#10970])
* Fixed: Agent type must be ``dsc'' in hook and metadata.xml
(https://issues.rudder.io/issues/10965[#10965])

CLI
+++

* Fixed: Agent cli is too verbose during post-install
(https://issues.rudder.io/issues/10945[#10945])
* Fixed: rudder.bat conflicts with rudder cmdlet
(https://issues.rudder.io/issues/10940[#10940])
* Fixed: Agent inventory fails
(https://issues.rudder.io/issues/10941[#10941])
* Fixed: Abort on error in agent code
(https://issues.rudder.io/issues/10887[#10887])
* Fixed: Fix some display issues in the agent
(https://issues.rudder.io/issues/10883[#10883])
* Fixed: Different fields in report cli outputs are not aligned
(https://issues.rudder.io/issues/10875[#10875])

Release notes
^^^^^^^^^^^^^

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

This is a bug fix release in the 4.2 series and therefore all
installations of 4.2.x should be upgraded when possible. When we release
a new version of Rudder it has been thoroughly tested, and we consider
the release enterprise-ready for deployment.
