= Changelogs for Rudder plugin auth-backends 8.0.\* versions

== auth-backends-8.0.0.beta1-2.7 (2023-09-07)

=== Changes


==== Miscellaneous

* Add example log trace for LDAP connection errors
    (https://issues.rudder.io/issues/23321[#23321])
* Add how-to enable debug log for ldap authentication
    (https://issues.rudder.io/issues/23154[#23154])
* Remove radius support in Rudder 8.0
    (https://issues.rudder.io/issues/23047[#23047])

==== UI - UX

* Use consistent fonts in Rudder interface - plugins
    (https://issues.rudder.io/issues/23270[#23270])

=== Bug fixes

==== Miscellaneous

* Fixed: not allowed to access errors because rudder plugins are missing AuthorizationApiMapping 
    (https://issues.rudder.io/issues/23348[#23348])
* Fixed: Add the role-retrieving OIDC feature to OAuth2
    (https://issues.rudder.io/issues/23112[#23112])

==== Plugins management

* Fixed: Update scala dependencies 
    (https://issues.rudder.io/issues/23371[#23371])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.0.alpha1-2.6 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Update plugin dependencies for 8.0
    (https://issues.rudder.io/issues/22806[#22806])
* Fixed: Update elm dependencies
    (https://issues.rudder.io/issues/22883[#22883])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

