= Changelogs for Rudder plugin auth-backends 8.0.\* versions

== auth-backends-8.0.10-2.7 (2024-07-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.9-2.7 (2024-06-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.8-2.7 (2024-04-25)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.7-2.7 (2024-04-02)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Update JWT lib for CVE-2023-52428
    (https://issues.rudder.io/issues/24469[#24469])
* Fixed: Documentation for OIDC properties is not up to date
    (https://issues.rudder.io/issues/24384[#24384])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.6-2.7 (2024-02-29)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: No API right with OIDC provided roles
    (https://issues.rudder.io/issues/24202[#24202])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.5-2.7 (2024-02-02)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: When the Oauth2 role provisioning attribute is incorrect, the error is misleading
    (https://issues.rudder.io/issues/24042[#24042])
* Fixed: Remove warning about missing ()
    (https://issues.rudder.io/issues/23986[#23986])
* Fixed: One note section is not rendered in auth-backend plugin
    (https://issues.rudder.io/issues/23919[#23919])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.4-2.7 (2023-12-14)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.3-2.7 (2023-11-09)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.2-2.7 (2023-11-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.1-2.7 (2023-10-30)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.0-2.7 (2023-10-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.0.rc2-2.7 (2023-10-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.0.rc1-2.7 (2023-10-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.0.beta3-2.7 (2023-10-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.0.beta2-2.7 (2023-09-15)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Bad doc for known authentication backends
    (https://issues.rudder.io/issues/23419[#23419])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.0.beta1-2.7 (2023-09-07)

=== Changes


==== Miscellaneous

* Add example log trace for LDAP connection errors
    (https://issues.rudder.io/issues/23321[#23321])
* Add how-to enable debug log for ldap authentication
    (https://issues.rudder.io/issues/23154[#23154])
* Remove radius support in Rudder 8.0
    (https://issues.rudder.io/issues/23047[#23047])

==== UI - UX

* Use consistent fonts in Rudder interface - plugins
    (https://issues.rudder.io/issues/23270[#23270])

=== Bug fixes

==== Miscellaneous

* Fixed: not allowed to access errors because rudder plugins are missing AuthorizationApiMapping 
    (https://issues.rudder.io/issues/23348[#23348])
* Fixed: Add the role-retrieving OIDC feature to OAuth2
    (https://issues.rudder.io/issues/23112[#23112])

==== Plugins management

* Fixed: Update scala dependencies 
    (https://issues.rudder.io/issues/23371[#23371])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== auth-backends-8.0.0.alpha1-2.6 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Update plugin dependencies for 8.0
    (https://issues.rudder.io/issues/22806[#22806])
* Fixed: Update elm dependencies
    (https://issues.rudder.io/issues/22883[#22883])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

