= Changelogs for Rudder plugin change-validation 8.0.\* versions

== change-validation-8.0.2-2.3 (2023-11-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.0.1-2.3 (2023-10-30)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: If tables are missing, the error notification toast disappears almost instantly
    (https://issues.rudder.io/issues/17809[#17809])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.0.0-2.3 (2023-10-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.0.0.rc1-2.3 (2023-10-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.0.0.rc2-2.3 (2023-10-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.0.0.rc1-2.3 (2023-10-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.0.0.beta3-2.3 (2023-10-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.0.0.beta2-2.3 (2023-09-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.0.0.beta1-2.3 (2023-09-07)

=== Changes


==== UI - UX

* Use consistent fonts in Rudder interface - plugins
    (https://issues.rudder.io/issues/23270[#23270])

=== Bug fixes

==== Miscellaneous

* Fixed: not allowed to access errors because rudder plugins are missing AuthorizationApiMapping 
    (https://issues.rudder.io/issues/23348[#23348])
* Fixed: Can't deploy, “Configuration state of the object modified by this change request has changed” looping
    (https://issues.rudder.io/issues/22993[#22993])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.0.0.beta1-2.3 (2023-09-07)

=== Changes


==== UI - UX

* Use consistent fonts in Rudder interface - plugins
    (https://issues.rudder.io/issues/23270[#23270])

=== Bug fixes

==== Miscellaneous

* Fixed: not allowed to access errors because rudder plugins are missing AuthorizationApiMapping 
    (https://issues.rudder.io/issues/23348[#23348])
* Fixed: Can't deploy, “Configuration state of the object modified by this change request has changed” looping
    (https://issues.rudder.io/issues/22993[#22993])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== change-validation-8.0.0.alpha1-2.2 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Update plugin dependencies for 8.0
    (https://issues.rudder.io/issues/22806[#22806])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

