= Changelogs for Rudder plugin cve 8.0.\* versions

== cve-8.0.6-2.10 (2024-02-29)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Fix small UI & logs problems
    (https://issues.rudder.io/issues/24118[#24118])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.0.5-2.10 (2024-02-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.0.4-2.9 (2023-12-14)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Make log about skipping windows clearer
    (https://issues.rudder.io/issues/23702[#23702])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.0.3-2.9 (2023-11-09)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Hide psql notice message in upgrade output
    (https://issues.rudder.io/issues/23714[#23714])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.0.2-2.9 (2023-11-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.0.1-2.9 (2023-10-30)

=== Changes


==== Miscellaneous

* Add link to distrib security trackers, add nvd link
    (https://issues.rudder.io/issues/23672[#23672])

=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.0.0-2.9 (2023-10-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.0.0.rc2-2.9 (2023-10-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.0.0.rc1-2.9 (2023-10-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.0.0.beta3-2.9 (2023-10-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.0.0.beta2-2.9 (2023-09-15)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Display that our scores are base scores from NVD
    (https://issues.rudder.io/issues/21212[#21212])

=== Release notes

Special thanks go out to the following individuals who invested time, patience, testing, patches or bug reports to make this version of Rudder better:

* Florent NEYRON

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.0.0.beta1-2.9 (2023-09-07)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Add rights to system update plugin
    (https://issues.rudder.io/issues/23097[#23097])
* Fixed: Unknown CVE with a score of 0 and 0 packages impacted
    (https://issues.rudder.io/issues/22878[#22878])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== cve-8.0.0.alpha1-2.9 (2023-07-22)

=== Changes


==== Miscellaneous

* Adapt cve plugin to changes in 22976
    (https://issues.rudder.io/issues/23063[#23063])

=== Bug fixes

==== Miscellaneous

* Fixed: Update elm dependencies
    (https://issues.rudder.io/issues/22884[#22884])
* Fixed: Update plugin dependencies for 8.0
    (https://issues.rudder.io/issues/22808[#22808])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

