= Changelogs for Rudder plugin datasources 8.0.\* versions

== datasources-8.0.9-2.4 (2024-06-03)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.8-2.4 (2024-04-25)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.7-2.4 (2024-04-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.6-2.4 (2024-02-29)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Missing write check on delete button
    (https://issues.rudder.io/issues/24161[#24161])
* Fixed: The UI is barely functional
    (https://issues.rudder.io/issues/24154[#24154])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.5-2.4 (2024-02-02)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Merge conflict error
    (https://issues.rudder.io/issues/24108[#24108])
* Fixed: Rename the "Add data source" button to "Create" in 8.0
    (https://issues.rudder.io/issues/23900[#23900])
* Fixed: Rename the "Add data source" button to "Create"
    (https://issues.rudder.io/issues/23875[#23875])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.4-2.4 (2023-12-14)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.3-2.4 (2023-11-09)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.2-2.4 (2023-11-08)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: When a datasource is deleted, its properties should be deleted
    (https://issues.rudder.io/issues/23563[#23563])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.1-2.4 (2023-10-30)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.0-2.4 (2023-10-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.0.rc2-2.4 (2023-10-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.0.rc1-2.4 (2023-10-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.0.beta3-2.4 (2023-10-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.0.beta2-2.4 (2023-09-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.0.beta1-2.4 (2023-09-07)

=== Changes


==== Miscellaneous

* Port datasources UI to elm
    (https://issues.rudder.io/issues/23310[#23310])
* Port datasources UI to elm
    (https://issues.rudder.io/issues/23310[#23310])

=== Bug fixes

==== Miscellaneous

* Fixed: not allowed to access errors because rudder plugins are missing AuthorizationApiMapping 
    (https://issues.rudder.io/issues/23348[#23348])
* Fixed: Schedule not displayed correctly in logs
    (https://issues.rudder.io/issues/23141[#23141])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== datasources-8.0.0.alpha1-2.3 (2023-07-22)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Compilation error following change in newNodeManager
    (https://issues.rudder.io/issues/23061[#23061])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

