= Changelogs for Rudder plugin dsc 8.0.\* versions

== dsc-8.0.0.rc1-2.4 (2023-10-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.0.0.beta3-2.4 (2023-10-02)

=== Changes


=== Bug fixes

==== Generic methods

* Fixed: Technique parameters are not callable using their complete name
    (https://issues.rudder.io/issues/23489[#23489])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.0.0.beta2-2.4 (2023-09-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.0.0.beta1-2.4 (2023-09-07)

=== Changes


==== Agent library

* Upgrade Library test dependencies
    (https://issues.rudder.io/issues/23368[#23368])

==== CLI

* Upgrade NTFSSecurity lib to 4.2.6
    (https://issues.rudder.io/issues/23367[#23367])

==== Techniques

* Remove the windowsUpdate technique as it is now replaced by the system-update plugin
    (https://issues.rudder.io/issues/23067[#23067])

=== Bug fixes

==== CLI

* Fixed: error with directive that contains a ' in its name
    (https://issues.rudder.io/issues/22380[#22380])
* Fixed: Older powershell fails to parse some Json files
    (https://issues.rudder.io/issues/23384[#23384])
* Fixed: Rudder agent ignores malformed policy files and does not throw any meaningful error
    (https://issues.rudder.io/issues/23340[#23340])
* Fixed: RudderVariables module throw warning logs when some registry entries are not yet defined
    (https://issues.rudder.io/issues/23115[#23115])
* Fixed: 7.3 rudder agent version displays the agent version in its old format
    (https://issues.rudder.io/issues/23114[#23114])

==== Generic methods

* Fixed: Rudder-Report-NA returns an unwanted boolean
    (https://issues.rudder.io/issues/23344[#23344])
* Fixed: File_from_share_folder fails with unexpected error since upgrade in 7.3.4
    (https://issues.rudder.io/issues/23126[#23126])
* Fixed: file from shared forlder fails badly if the file doesn't exist on the shared folder
    (https://issues.rudder.io/issues/21685[#21685])

==== Packaging

* Fixed: If the installer is run multiple times consecutively, the FusionInventory patches are removed from the system
    (https://issues.rudder.io/issues/23232[#23232])
* Fixed: Windows agent is built with corrupted version number when built from the CI with a timestamp close to a minute end
    (https://issues.rudder.io/issues/23124[#23124])
* Fixed: Windows agent installation from GUI fails
    (https://issues.rudder.io/issues/23019[#23019])

==== Agent library

* Fixed: The false condition should not be definable in a context rudderc expect "false" to always evaluate to a false boolean
    (https://issues.rudder.io/issues/23162[#23162])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== dsc-8.0.0.alpha1-2.4 (2023-07-22)

=== Changes


==== Packaging

* Update fusion to 2.6
    (https://issues.rudder.io/issues/22792[#22792])
* Update dotnet dependencies
    (https://issues.rudder.io/issues/22841[#22841])

=== Bug fixes

==== Packaging

* Fixed: Update the makefile hardcoded version to 8.0
    (https://issues.rudder.io/issues/22990[#22990])

==== Agent library

* Fixed: Missing Update-Log function from rudderCLi module
    (https://issues.rudder.io/issues/22247[#22247])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

