= Changelogs for Rudder plugin glpi 8.0.\* versions

== glpi-8.0.0.beta3-2.1 (2023-10-02)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== glpi-8.0.0.beta2-2.1 (2023-09-15)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== glpi-8.0.0.beta1-2.1 (2023-09-07)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: The cron never runs
    (https://issues.rudder.io/issues/22781[#22781])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== glpi-8.0.0.alpha1-2.1 (2023-07-22)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

