= Changelogs for Rudder plugin system-updates 8.0.\* versions

== system-updates-8.0.2-1.12 (2023-11-08)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.0.1-1.12 (2023-10-30)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Patch campaigns are broken with python error
    (https://issues.rudder.io/issues/23636[#23636])
* Fixed: Once we save a system campaign, the display still shows that we can save it
    (https://issues.rudder.io/issues/23295[#23295])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.0.0-1.12 (2023-10-18)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.0.0.rc2-1.12 (2023-10-13)

=== Changes


=== Bug fixes

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.0.0.rc1-1.12 (2023-10-08)

=== Changes


=== Bug fixes

==== Miscellaneous

* Fixed: Add a log line in patch output for a node for a node so we know if it rebooted or not
    (https://issues.rudder.io/issues/23408[#23408])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.0.0.beta3-1.12 (2023-10-02)

=== Changes


==== Miscellaneous

* Improve system update hooks
    (https://issues.rudder.io/issues/23465[#23465])

=== Bug fixes

==== Miscellaneous

* Fixed: Display of datepicker is broken 
    (https://issues.rudder.io/issues/23455[#23455])
* Fixed: System update report is not parseable
    (https://issues.rudder.io/issues/23445[#23445])
* Fixed: Wrong directory for hooks in docs
    (https://issues.rudder.io/issues/23448[#23448])
* Fixed: Missing documentation about what rights plugin has
    (https://issues.rudder.io/issues/23428[#23428])

==== Web - Campaigns

* Fixed: Update campaign schedule display bug
    (https://issues.rudder.io/issues/23453[#23453])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.0.0.beta2-1.12 (2023-09-15)

=== Changes


==== Miscellaneous

* Document update hooks
    (https://issues.rudder.io/issues/23411[#23411])

=== Bug fixes

==== Miscellaneous

* Fixed: After getting timezone, we refresh all data from plugin, making it reload in continuous when selecting a campaign
    (https://issues.rudder.io/issues/23433[#23433])
* Fixed: Font used for Add Software seems non standard
    (https://issues.rudder.io/issues/22705[#22705])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.0.0.beta1-1.12 (2023-09-07)

=== Changes


==== Miscellaneous

* Add pre/post upgrade hooks on Linux
    (https://issues.rudder.io/issues/23337[#23337])
* Update the documentation of the plugin
    (https://issues.rudder.io/issues/23323[#23323])

=== Bug fixes

==== Miscellaneous

* Fixed: Add rights to system update plugin
    (https://issues.rudder.io/issues/23097[#23097])
* Fixed: Improve field placeholder for micro-patching campaigns
    (https://issues.rudder.io/issues/23327[#23327])
* Fixed: Error 500 when we select an end hour at or before the start date of the campaign
    (https://issues.rudder.io/issues/23222[#23222])
* Fixed: Show campaign and event id in UI
    (https://issues.rudder.io/issues/23304[#23304])
* Fixed: when we create a campaign, the server time displayed is the time when the page was loaded, not when we clicked on new campaign
    (https://issues.rudder.io/issues/23296[#23296])
* Fixed: issue on logging in verbose mode
    (https://issues.rudder.io/issues/23297[#23297])
* Fixed: number of nodes in the list of applicable patch is not valid
    (https://issues.rudder.io/issues/23052[#23052])
* Fixed: update campaign fail by asking question
    (https://issues.rudder.io/issues/23024[#23024])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.0.0.alpha1-1.12 (2023-07-22)

=== Changes


==== Miscellaneous

* Adapt cve plugin to changes in 22976
    (https://issues.rudder.io/issues/23063[#23063])
* Add the windows support for Micro-Patching
    (https://issues.rudder.io/issues/23007[#23007])

=== Bug fixes

==== Miscellaneous

* Fixed: Update elm dependencies
    (https://issues.rudder.io/issues/22884[#22884])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

