= Changelogs for Rudder plugin system-updates 8.0.\* versions

== system-updates-8.0.0.beta1-1.12 (2023-09-07)

=== Changes


==== Miscellaneous

* Add pre/post upgrade hooks on Linux
    (https://issues.rudder.io/issues/23337[#23337])
* Update the documentation of the plugin
    (https://issues.rudder.io/issues/23323[#23323])

=== Bug fixes

==== Miscellaneous

* Fixed: Add rights to system update plugin
    (https://issues.rudder.io/issues/23097[#23097])
* Fixed: Improve field placeholder for micro-patching campaigns
    (https://issues.rudder.io/issues/23327[#23327])
* Fixed: Error 500 when we select an end hour at or before the start date of the campaign
    (https://issues.rudder.io/issues/23222[#23222])
* Fixed: Show campaign and event id in UI
    (https://issues.rudder.io/issues/23304[#23304])
* Fixed: when we create a campaign, the server time displayed is the time when the page was loaded, not when we clicked on new campaign
    (https://issues.rudder.io/issues/23296[#23296])
* Fixed: issue on logging in verbose mode
    (https://issues.rudder.io/issues/23297[#23297])
* Fixed: number of nodes in the list of applicable patch is not valid
    (https://issues.rudder.io/issues/23052[#23052])
* Fixed: update campaign fail by asking question
    (https://issues.rudder.io/issues/23024[#23024])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

== system-updates-8.0.0.alpha1-1.12 (2023-07-22)

=== Changes


==== Miscellaneous

* Adapt cve plugin to changes in 22976
    (https://issues.rudder.io/issues/23063[#23063])
* Add the windows support for Micro-Patching
    (https://issues.rudder.io/issues/23007[#23007])

=== Bug fixes

==== Miscellaneous

* Fixed: Update elm dependencies
    (https://issues.rudder.io/issues/22884[#22884])

=== Release notes

This is a bug fix release in the 8.0 series and therefore all installations of 8.0.x should be upgraded when possible. When we release a new version of Rudder it has been thoroughly tested, and we consider the release enterprise-ready for deployment.

