= Change logs for Rudder 3.0

Rudder 3.0 has reached End of Life the 10th June 2016. This version is
codenamed ``Galleon''.

This page provides a summary of changes for each version. Previous beta
and rc versions are listed below for convenience.

*Main new features in Rudder 3.0:*

* Global redesign of Rudder web interface (menu, directive/group page
organization)
* More precise Rule reporting ( progress bar with different states, a
`per Node' view …)
* Add a dashboard on Home page
* Add a command line interface for Rudder-agent
* Add RHEL/ Centos 7 Support
* Support for systemd services system
* Add a `changes-only' compliance mode, with lower bandwidth usage
* Aggent run interval can be defined by nodes, overriding global param
* Add a Relay server package
* Possibility to add custom attributes to Nodes
* Environment variables can used as parameters in Directives and
Techniques
* ncf Technique will now be added automatically
* Add possibility to deprecated Techniques
* Accept or not to send anonymous metrics to help Rudder development

*Installing, upgrading and testing*

Documentation:

* Install:
https://www.rudder-project.org/doc-3.0/_install_rudder_server.html
* Upgrade: https://www.rudder-project.org/doc-3.0/_upgrade_rudder.html

The Download Links are available here:
https://www.rudder-project.org/site/get-rudder/downloads/.

We also recommend using the
https://github.com/Normation/rudder-vagrant[Rudder Vagrant] config if
you want a quick and easy way to get an installation for testing.

*Operating systems supported*

This version provides packages for these operating systems:

* Rudder server: *Debian 7, Debian 8, RHEL/CentOS 6, RHEL/CentOS 7, SLES
11, Ubuntu 12.04, Ubuntu 14.04*
* Rudder agent: all of the above plus *Debian 5, Debian 6, RHEL/CentOS
3, RHEL/CentOS 5, Fedora 18, SLES 10, Ubuntu 10.04, Ubuntu 12.10*
* Rudder agent (non-free): *Windows Server 2008-2012* , *AIX 5-6-7*

== Rudder 3.0.17 (2016-06-08)

=== Changes

==== Documentation

* Add tests for doc syntax
(https://issues.rudder.io/issues/8443[#8443])

=== Bug fixes

==== Web - Compliance & node report

* Fixed: Parallel traversal of new promises directories causes some
nodes promises to not be updated
(https://issues.rudder.io/issues/8427[#8427])
* Fixed: Not possible to switch details for time period on rule recent
changes on Chromium
(https://issues.rudder.io/issues/8408[#8408])

==== Web - Nodes & inventories

* Fixed: Change in group may be overwritten by dynamic group update
(https://issues.rudder.io/issues/8453[#8453])

==== Web - Config management

* Fixed: Many WARN messages after upgrade about JSON deserialisation
error (https://issues.rudder.io/issues/8288[#8288])

==== Techniques

* Fixed: Invalidation of previous package state and of package status
cache does not work on rpmPackageInstallation 5.0 5.1 6.0 6.1 7.0
(https://issues.rudder.io/issues/8421[#8421])
* Fixed: rpmPackageInstallation 7.0 uses the wrong version number for
it’s data file
(https://issues.rudder.io/issues/8419[#8419])
* Fixed: Missing reports in file and zypper techniques due to a syntax
error in reporting
(https://issues.rudder.io/issues/8403[#8403])

==== Initial promises & sys tech

* Fixed: On Centos6.6, rsyslog is always restarted
(https://issues.rudder.io/issues/8451[#8451])
* Fixed: failsafe sometimes produce rudder reports
(https://issues.rudder.io/issues/8422[#8422])
* Fixed: Reference to &TRACKINGKEY& in initial promises
(https://issues.rudder.io/issues/8415[#8415])
* Fixed: Remove unused variable in cf-serverd
(https://issues.rudder.io/issues/8392[#8392])
* Fixed: The component ``Check Technique library reloading file'' is
sometime a log and sometime a result
(https://issues.rudder.io/issues/8380[#8380])
* Fixed: Launching twice in a row a disabled agent make the agent runs
(https://issues.rudder.io/issues/7100[#7100])
* Fixed: The uuid in the promises and the uuid in
/opt/rudder/etc/uuid.hive may be out of sync, and chaos and sadness
follows (https://issues.rudder.io/issues/7091[#7091])

==== Documentation

* Fixed: Unclear message in the upgrade doc
(https://issues.rudder.io/issues/8440[#8440])
* Fixed: The SLES upgrade section has a broken title syntax
(https://issues.rudder.io/issues/8439[#8439])

==== Packaging

* Fixed: stty does not handle no-tty input
(https://issues.rudder.io/issues/8426[#8426])
* Fixed: When updating a Rudder install, changes_executionTimeStamp_idx
index is not created
(https://issues.rudder.io/issues/8423[#8423])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky
* Daniel Stan

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. The current
``esr'' release is now 3.1.* and there we advice to upgrade to the
latest 3.1.* version. When we release a new version of Rudder, it needs
to be thoroughly tested, and we consider the release enterprise-ready
for deployment only after it has been proven to run in production
reliably for several months.

== Rudder 3.0.16 (2016-06-01, Not announced)

That version was not announced due to several bugs:
https://issues.rudder.io/issues/8423[#8423],
https://issues.rudder.io/issues/8427[#8427],
https://issues.rudder.io/issues/8430[#8430]

=== Changes

==== Web - Nodes & inventories

* Make page node details/search node less confusing
(https://issues.rudder.io/issues/7642[#7642])

==== Web - UI & UX

* Augment default number of lines displayed in tables and add more
options (https://issues.rudder.io/issues/8107[#8107])

==== Documentation

* Create an installation section in the documentation
(https://issues.rudder.io/issues/8233[#8233])
* Homogenize OS names in the doc
(https://issues.rudder.io/issues/8224[#8224])
* How to: Ensure a line is present in a file (and only one time!)
(https://issues.rudder.io/issues/8169[#8169])
* Integrate ncf generic methods reference into the doc
(https://issues.rudder.io/issues/7844[#7844])
* Add ``Troubleshooting'' section
(https://issues.rudder.io/issues/7711[#7711])
* Move man pages into the reference section
(https://issues.rudder.io/issues/8332[#8332])
* Move Relay doc to the install section
(https://issues.rudder.io/issues/7889[#7889])

=== Bug fixes

==== Web - UI & UX

* Fixed: Typo in directive migration message ``an other''
(https://issues.rudder.io/issues/8289[#8289])
* Fixed: Broken links in the ``Support Desk'' box of the home page
(https://issues.rudder.io/issues/8110[#8110])
* Fixed: Some messages in the Settings page end with a comma
(https://issues.rudder.io/issues/8044[#8044])
* Fixed: Show seconds in Execution date at Technical Logs of Node
Details (https://issues.rudder.io/issues/7981[#7981])
* Fixed: Prevent red color usage in inventory graphs
(https://issues.rudder.io/issues/8262[#8262])
* Fixed: Change audit message is not checked in the ``Clone Directive''
popup (https://issues.rudder.io/issues/8213[#8213])
* Fixed: Priority field in Directive form does not show it has a tooltip
and has wrong description
(https://issues.rudder.io/issues/8201[#8201])
* Fixed: Fix display issues on IE11
(https://issues.rudder.io/issues/8136[#8136])
* Fixed: Add a left margin to the Rudder search box
(https://issues.rudder.io/issues/7825[#7825])

==== Web - Compliance & node report

* Fixed: ``All the last execution reports for this server are ok''
displayed when no report received
(https://issues.rudder.io/issues/8400[#8400])
* Fixed: Misleading message on node compliance detail when run’s
configID is unknown
(https://issues.rudder.io/issues/8399[#8399])
* Fixed: ``repaired'' are counted as ``required attention'' on node
compliance details
(https://issues.rudder.io/issues/8396[#8396])
* Fixed: Compliance is not correctly computed if we receive run agent
right after generation
(https://issues.rudder.io/issues/8051[#8051])
* Fixed: OOM in Rudder when there are too many repaired reports
(https://issues.rudder.io/issues/7735[#7735])

==== Web - Config management

* Fixed: Node configuration cache is invalidated too often
(https://issues.rudder.io/issues/8246[#8246])
* Fixed: Directive detail don’t show the OS compatibility version
(https://issues.rudder.io/issues/7042[#7042])

==== API

* Fixed: Better document Node Api: include detail always returns
``default'' (https://issues.rudder.io/issues/8192[#8192])

==== Agent

* Fixed: rudder agent update doesn’t always update policy
(https://issues.rudder.io/issues/8346[#8346])
* Fixed: ``rudder agent enable -s'' doesn’t return an error code if it
can’t start the agent
(https://issues.rudder.io/issues/8317[#8317])

==== Techniques

* Fixed: permissions technique tries to set a group even when we do not
ask for it (https://issues.rudder.io/issues/8198[#8198])
* Fixed: It is not possible to use quotes in generic variable definition
values (https://issues.rudder.io/issues/8188[#8188])
* Fixed: Clear package caches when repairing a package repository
(https://issues.rudder.io/issues/8121[#8121])
* Fixed: The start at boot does not work in the openssh technique on
systemd OSes (https://issues.rudder.io/issues/8108[#8108])
* Fixed: Double reporting for group creation
(https://issues.rudder.io/issues/8100[#8100])
* Fixed: Avoid waiting on lock when calling yum
(https://issues.rudder.io/issues/6487[#6487])
* Fixed: applications/aptPackageManagerSettings/3.1 missing from list of
maintained techniques
(https://issues.rudder.io/issues/8395[#8395])
* Fixed: Document usage of line replacement in Enforce a file content
technique (https://issues.rudder.io/issues/8162[#8162])

==== System integration

* Fixed: Rudder jetty init script broken on CentOS 7
(https://issues.rudder.io/issues/8369[#8369])
* Fixed: rudder-slapd may break on upgrade when restarting on openVZ
(https://issues.rudder.io/issues/8210[#8210])
* Fixed: check-rudder-agent complains about not existing
policy-server.dat backup file
(https://issues.rudder.io/issues/8202[#8202])
* Fixed: ACL Posix on Git repos
(https://issues.rudder.io/issues/8065[#8065])
* Fixed: Disable ldap logging on non existing indexes
(https://issues.rudder.io/issues/7667[#7667])
* Fixed: Messages can be dropped on the node, resulting in Unknown
reports on the Web Interface
(https://issues.rudder.io/issues/6421[#6421])
* Fixed: promises can become invalid if copies fail rendering the agent
unusable (https://issues.rudder.io/issues/5650[#5650])
* Fixed: rudder-jetty initialisation should not support Java 6
(https://issues.rudder.io/issues/7348[#7348])

==== Server components

* Fixed: Apache config does not get cleaned up after removal of
rudder-webapp (https://issues.rudder.io/issues/8232[#8232])
* Fixed: rudder-apache gets added multiple times to apache config
(https://issues.rudder.io/issues/8231[#8231])

==== Packaging

* Fixed: Spurious message ``grep: /etc/sysconfig/apache2: No such file
or directory'' in RPM install for rudder-webapp
(https://issues.rudder.io/issues/8371[#8371])
* Fixed: ncf package asks about replacing dist config file during
upgrade (https://issues.rudder.io/issues/8286[#8286])
* Fixed: When we install rudder-agent after having removing it, the uuid
is not restored on RPM-based systems
(https://issues.rudder.io/issues/6468[#6468])
* Fixed: Makefile missing in rudder-server-relay package
(https://issues.rudder.io/issues/8370[#8370])

==== Initial promises & sys tech

* Fixed: Can’t stat file `/opt/rudder/bin/cf-hub' on `localhost' in
files.copy_from promise
(https://issues.rudder.io/issues/8397[#8397])
* Fixed: check-techniques script doesn’t properly exit non-zero on
errors (https://issues.rudder.io/issues/8386[#8386])
* Fixed: Error in cf-serverd for allowing remote access to cf-agent
binary (https://issues.rudder.io/issues/8374[#8374])
* Fixed: logrotate promise for CFEngine Enterprise agents
(https://issues.rudder.io/issues/8340[#8340])
* Fixed: Invalid path for rudder_ncf in Windows
(https://issues.rudder.io/issues/8338[#8338])
* Fixed: Duplicate lines in body classes success in update.cf in initial
promises (https://issues.rudder.io/issues/8309[#8309])
* Fixed: Use variables for path to cf-agent in system Techniques to work
on Windows (https://issues.rudder.io/issues/8307[#8307])
* Fixed: Disable Repeated message reduction or reports may be lost on
the relay (https://issues.rudder.io/issues/8264[#8264])
* Fixed: Error message about setgid on ncf.conf
(https://issues.rudder.io/issues/8181[#8181])
* Fixed: Missing reporting in ``check postgresql process'' on rudder-db
role (https://issues.rudder.io/issues/8178[#8178])
* Fixed: Crontab promise with the Windows agent
(https://issues.rudder.io/issues/8161[#8161])
* Fixed: Rudder agent connect at each runs to its policy server to get
its server uuid
(https://issues.rudder.io/issues/7638[#7638])
* Fixed: Extra carriage return in policy_server.dat inventory failure
(https://issues.rudder.io/issues/7328[#7328])
* Fixed: In case of error in logrotate check, there is no report
(https://issues.rudder.io/issues/8382[#8382])
* Fixed: Error on windows: agent tries to check if /usr/bin/env supports
the -0 option (https://issues.rudder.io/issues/8336[#8336])
* Fixed: Using Rudder server 3.x + rudder agent 2.11.x, a node doesn’t
properly detect its change of relay server
(https://issues.rudder.io/issues/8045[#8045])

==== Architecture - Internal libs

* Fixed: Examples in ldap-inventory are not real life examples
(https://issues.rudder.io/issues/8236[#8236])

==== Documentation

* Fixed: Documentation wrongly states default report TTL is 30 days
(https://issues.rudder.io/issues/8297[#8297])
* Fixed: Documentation no longer clearly tells user to upgrade
Techniques (https://issues.rudder.io/issues/8294[#8294])
* Fixed: Invalid documentation on how to use rudder global parameters in
Technique editor
(https://issues.rudder.io/issues/8278[#8278])
* Fixed: Make clearer what the goal of Scala-ldap is in readme
(https://issues.rudder.io/issues/8275[#8275])
* Fixed: rudder doc can be misleading on the repo to use for Centos/RHEL
(https://issues.rudder.io/issues/7976[#7976])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre Anriot
* Jean Cardona
* Janos Mattyasovszky
* David Svejda

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. The current
``esr'' release is now 3.1.* and there we advice to upgrade to the
latest 3.1.* version. When we release a new version of Rudder, it needs
to be thoroughly tested, and we consider the release enterprise-ready
for deployment only after it has been proven to run in production
reliably for several months.

== Rudder 3.0.15 (2016-04-18)

=== Changes

==== Web - Nodes & inventories

* Exit sending inventory to rudder-webapp if the queue is full
(https://issues.rudder.io/issues/7291[#7291])

=== Bug fixes

==== Web - UI & UX

* Fixed: API account table broken when empty
(https://issues.rudder.io/issues/8144[#8144])
* Fixed: Double arrow in Pending Nodes list
(https://issues.rudder.io/issues/8078[#8078])

==== Web - Maintenance

* Fixed: web interface login: able to log in with valid ldap account but
no matching rudder-users.xml entry
(https://issues.rudder.io/issues/8085[#8085])

==== Techniques

* Fixed: Missing reporting in UserManagement 6.0 when creating a user
(https://issues.rudder.io/issues/8079[#8079])

==== Performance and scalability

* Fixed: Java OOM during Java’s log migration
(https://issues.rudder.io/issues/7524[#7524])

==== Windows agent

* Fixed: On Windows, a file c:\Program is created
(https://issues.rudder.io/issues/8149[#8149])
* Fixed: Environement variable fail to load on windows
(https://issues.rudder.io/issues/8146[#8146])

==== Packaging

* Fixed: Error in rudder-server-relay post install script on debian
(https://issues.rudder.io/issues/8117[#8117])

==== Server components

* Fixed: node-to-relay fails to reload policy when proxy is set
(https://issues.rudder.io/issues/8054[#8054])
* Fixed: Compress ldif backups
(https://issues.rudder.io/issues/6714[#6714])][#7900]])

==== Initial promises & sys tech

* Fixed: Do not backup modified promise files and encrypt ncf/local
transfer (https://issues.rudder.io/issues/8159[#8159])

==== Architecture - Internal libs

* Fixed: java.util.regex.PatternSyntaxException: Unexpected internal
error near index 1 on windows
(https://issues.rudder.io/issues/7935[#7935])

==== Architecture - Refactoring

* Remove trailing space in code file that make merge conflicts
(https://issues.rudder.io/issues/8126[#8126])
* Fixed: Typo in tests
(https://issues.rudder.io/issues/8116[#8116])
* Fixed: Bad logs for event log migration since #8085
(https://issues.rudder.io/issues/8124[#8124])

==== Documentation

* Fixed: API documentation for compliance needs JSON prettified
(https://issues.rudder.io/issues/7900[#7900])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Florian Heigl
* Janos Mattyasovszky

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. The current
``esr'' release is now 3.1.* and there we advice to upgrade to the
latest 3.1.* version. When we release a new version of Rudder, it needs
to be thoroughly tested, and we consider the release enterprise-ready
for deployment only after it has been proven to run in production
reliably for several months.

== Rudder 3.0.14 (2016-03-24)

=== Changes

==== Packaging

* Put a makefile inside each directory of rudder-packages
(https://issues.rudder.io/issues/7718[#7718])

==== Web - Nodes & inventories

* The Motherboard UUID doesn’t appear on the inventory on a Node
(https://issues.rudder.io/issues/3749[#3749])

==== Documentation

* Mark 3.1 as ESR in the doc header
(https://issues.rudder.io/issues/8059[#8059])
* Import doc from foswiki about parametrized variable in the doc
(https://issues.rudder.io/issues/7836[#7836])
* Reorganize the introduction
(https://issues.rudder.io/issues/7818[#7818])

==== Techniques

* Add an option for MOTD Technique to display MOTD before login
(https://issues.rudder.io/issues/7983[#7983])
* New Technique to import a GPG Key into RPM
(https://issues.rudder.io/issues/6756[#6756])

=== Bug fixes

==== API

* Fixed: Changing Directive version via API does not set default values,
and return wrong parameters
(https://issues.rudder.io/issues/7979[#7979])

==== Web - UI & UX

* Fixed: Typo in webapp message when policy generation failed
(https://issues.rudder.io/issues/8094[#8094])
* Fixed: Tooltip on Rule categories may display after selecting Rule
(https://issues.rudder.io/issues/8086[#8086])
* Fixed: Typo in webapp warn message ``sendind''
(https://issues.rudder.io/issues/7990[#7990])
* Fixed: Legend for node breakdown is not readable
(https://issues.rudder.io/issues/7969[#7969])
* Fixed: Sorting is broken in tables after sorting by compliance
(https://issues.rudder.io/issues/7653[#7653])

==== Web - Nodes & inventories

* Fixed: Missing error message in node acceptation when there is a
problem with getting authorized networks
(https://issues.rudder.io/issues/8016[#8016])
* Fixed: Debian Jessie, on VMWare, are wrongly considered as
``Physical'' machine
(https://issues.rudder.io/issues/7204[#7204])
* Fixed: Rudder doesn’t store and display the IPV6 of the nodes
(https://issues.rudder.io/issues/7136[#7136])
* Fixed: Order of button on ``accept nodes in rudder'' is the exact
opposite of the rest of the webapp
(https://issues.rudder.io/issues/6722[#6722])
* Fixed: Allow to make a group with only 32bits or 64bits nodes
(https://issues.rudder.io/issues/2543[#2543])

==== Documentation

* Fixed: Broken link in the manual
(https://issues.rudder.io/issues/7817[#7817])
* Fixed: Document that when we reduce the run interval of nodes, ``no
data'' may be wrongly reported
(https://issues.rudder.io/issues/6231[#6231])

==== Packaging

* Fixed: rudder-upgrade takes too long
(https://issues.rudder.io/issues/7987[#7987])
* Fixed: Backup and restore policy_server.dat like we do with uuid.hive
file (https://issues.rudder.io/issues/7901[#7901])
* Fixed: Rudder agent tries sending an inventory during update
(https://issues.rudder.io/issues/7881[#7881])
* Fixed: rudder-upgrade does not make some check on remote sql in case
of distributed setup
(https://issues.rudder.io/issues/7849[#7849])
* Fixed: Rudder init script kill all agent on Open VZ (or similar
system) (https://issues.rudder.io/issues/4499[#4499])
* Fixed: Default vhost is not disabled on rudder-relay
(https://issues.rudder.io/issues/7846[#7846])

==== Initial promises & sys tech

* Fixed: gzip can stop rudder agent when compressing log files
(https://issues.rudder.io/issues/7985[#7985])
* Fixed: System technique cannot compress inventories
(https://issues.rudder.io/issues/7930[#7930])
* Fixed: Unexpected reports on ``Check jetty process'' component of
system techniques
(https://issues.rudder.io/issues/7821[#7821])
* Fixed: Rudder inventory don’t produce error report
(https://issues.rudder.io/issues/7785[#7785])
* Fixed: date of report may be invalid on windows
(https://issues.rudder.io/issues/7741[#7741])
* Fixed: Reporting in server-components missing when restarting some
services (ie jetty)
(https://issues.rudder.io/issues/7813[#7813])

==== System integration

* Fixed: rudder-init broken on SLES
(https://issues.rudder.io/issues/7991[#7991])
* Fixed: Missing usefull logger in logger file
(https://issues.rudder.io/issues/7910[#7910])
* Fixed: Errors with apache on ubuntu 12.04
(https://issues.rudder.io/issues/6763[#6763])

==== Server components

* Fixed: Rudder password are not properly protected
(https://issues.rudder.io/issues/8096[#8096])
* Fixed: Allow disable of git-autocommit of system policy on Update
(https://issues.rudder.io/issues/7222[#7222])
* Fixed: Node not included in dynamic group due to openldap bug with
modrdn not showing node children
(https://issues.rudder.io/issues/6780[#6780])

==== Techniques

* Fixed: When we manage twice a same package in rpm package management,
we don’t get the second report
(https://issues.rudder.io/issues/8034[#8034])
* Fixed: Incomplete reporting in service management
(https://issues.rudder.io/issues/8032[#8032])
* Fixed: Script check-techniques.sh fails on first error
(https://issues.rudder.io/issues/8012[#8012])
* Fixed: The script check-techniques.sh checks old techniques when the
parent directory contains a version number
(https://issues.rudder.io/issues/8010[#8010])
* Fixed: Fix invalid metadata.xml statement in clockSettings 3.1
(https://issues.rudder.io/issues/8009[#8009])
* Fixed: Wrong reporting in servicesManagement 3.0
(https://issues.rudder.io/issues/7975[#7975])
* Fixed: ``Download a file from shared folder'' technique doesn’t have
an explicit default value for ``Compare method'' (was mtime, now digest)
(https://issues.rudder.io/issues/7962[#7962])
* Fixed: Missing Timezones from clockConfiguration
(https://issues.rudder.io/issues/7489[#7489])
* Fixed: Missing ``don’t change'' password hash type in userManagement
(https://issues.rudder.io/issues/6493[#6493])
* Fixed: Support for more Debian / Ubuntu repository components
(https://issues.rudder.io/issues/8073[#8073])
* Fixed: Technique jobScheduler v2.0 doesn’t schedule
(https://issues.rudder.io/issues/8068[#8068])

==== Performance and scalability

* Fixed: Queries on expected reports are really slow with more than 2000
nodes (https://issues.rudder.io/issues/8057[#8057])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre Anriot
* Dennis Cabooter
* Janos Mattyasovszky

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. The current
``esr'' release is now 3.1.* and there we advice to upgrade to the
latest 3.1.* version. When we release a new version of Rudder, it needs
to be thoroughly tested, and we consider the release enterprise-ready
for deployment only after it has been proven to run in production
reliably for several months.

== Rudder 3.0.13 (2016-01-21)

=== Changes

==== Web - UI & UX

* Add last promise generation date in generation policy menu entry
(https://issues.rudder.io/issues/7661[#7661])
* Clicking on recent changes graph should show detail graph in rule
details (https://issues.rudder.io/issues/7640[#7640])
* Add an option to disable display changes graphes if they are slow
(https://issues.rudder.io/issues/7618[#7618])

==== Agent

* rudder-agent should trigger a new inventory after upgrade
(https://issues.rudder.io/issues/7620[#7620])

==== Techniques

* Add test for rudder-techniques to ensure removed deprecated techniques
don’t come back in an erroneous merge
(https://issues.rudder.io/issues/7504[#7504])

==== Documentation

* Document the zypper segfault when installing Rudder packages locally
(https://issues.rudder.io/issues/7652[#7652])
* Document AIX support in Rudder manual
(https://issues.rudder.io/issues/7650[#7650])
* Document nofiles dependency for syslog/tcp on master and relays
(https://issues.rudder.io/issues/7220[#7220])

==== Architecture - Refactoring

* Remove deprecated package rudder-policy-templates
(https://issues.rudder.io/issues/7723[#7723])
* Make NodeInfo more dependant on Node
(https://issues.rudder.io/issues/7634[#7634])
* Change AGPL to GPL in rudder-plugin-external-node-information
(https://issues.rudder.io/issues/7576[#7576])

=== Bug fixes

==== Web - Config management

* Fixed: Promise generation never finishes if jetty is restarted
mid-generation
(https://issues.rudder.io/issues/7814[#7814])
* Fixed: Too long directive name breaks directive serialization
(https://issues.rudder.io/issues/7766[#7766])
* Fixed: Error on promise generation after accepting a node
(https://issues.rudder.io/issues/7689[#7689])

==== Web - UI & UX

* Fixed: Filter keeps applied between Rules Tables within Directives
page (https://issues.rudder.io/issues/7754[#7754])
* Fixed: Typo in AGENT RUN SCHEDULE description
(https://issues.rudder.io/issues/7749[#7749])
* Fixed: Blue colour in ``Nodes by overall compliance'' chart is
confusingly the same as ``No report'' blue
(https://issues.rudder.io/issues/7757[#7757])
* Fixed: The directive tree filter should not be reset when we click on
a directive (https://issues.rudder.io/issues/7656[#7656])
* Fixed: Remove one pixel `border' in Rudder menu
(https://issues.rudder.io/issues/7641[#7641])
* Fixed: No auto scroll since rudder 3.0
(https://issues.rudder.io/issues/7617[#7617])
* Fixed: Open external links of the webapp in another tab
(https://issues.rudder.io/issues/6628[#6628])

==== Web - Compliance & node report

* Fixed: When several directives value have a CFEngine var, we get
``unexpected'' due to bad regex matching
(https://issues.rudder.io/issues/7758[#7758])
* Fixed: Compliance take into account expired run
(https://issues.rudder.io/issues/7743[#7743])
* Fixed: Not accepted node reports trigger compliance processing
(https://issues.rudder.io/issues/7625[#7625])

==== Web - Nodes & inventories

* Fixed: Only one system group is displayed in node details
(https://issues.rudder.io/issues/7061[#7061])

==== Web - Maintenance

* Fixed: Jetty cache files in /tmp directory are removed by the OS
tmpwatch cron job, preventing access to the application
(https://issues.rudder.io/issues/4473[#4473])

==== Agent

* Fixed: rudder-agent does not stop on network error during file copy,
which can lead to file deletions when purging is enabled
(https://issues.rudder.io/issues/7629[#7629])
* Fixed: rudder CLI commands should print their expected options with -h
/ –help (https://issues.rudder.io/issues/7742[#7742])
* Fixed: Add a ``quiet'' option to rudder agent run to only display
errors (https://issues.rudder.io/issues/7608[#7608])

==== Techniques

* Fixed: Invalid reporting on windows for clockconfiguration if Hardware
Clock is not set
(https://issues.rudder.io/issues/7739[#7739])
* Fixed: Technique copyGitFile can send success AND error reports on
post-hook execution and lead to unexpected reports
(https://issues.rudder.io/issues/7624[#7624])
* Fixed: Unexpected reports using ``rpmPackageInstallation'' technique
(https://issues.rudder.io/issues/7623[#7623])
* Fixed: Technique ``Name resolution'': Regexp to check value of
Nameserver does not allow the use of variable
(https://issues.rudder.io/issues/3741[#3741])
* Fixed: Package management for RHEL / CentOS / SuSE / RPM systems: The
number of reports about ZMD is uncorrect
(https://issues.rudder.io/issues/3478[#3478])
* Fixed: syslog-ng’s loghost regex does not match with set line
(https://issues.rudder.io/issues/7635[#7635])
* Fixed: The ``Ignore file or directory if it does not exist'' parameter
in filesPermission is ignored
(https://issues.rudder.io/issues/7607[#7607])

==== Documentation

* Fixed: Fix use links containing emphasized keywords in manual
(https://issues.rudder.io/issues/7812[#7812])
* Fixed: The size of one image is not correctly recognized in the doc
(https://issues.rudder.io/issues/7713[#7713])
* Fixed: Some titles broken in the documentation
(https://issues.rudder.io/issues/7551[#7551])
* Fixed: Wrong anchors in Rudder API doc
(https://issues.rudder.io/issues/6694[#6694])
* Fixed: Document the use of port 5310 for rudder server debug
(https://issues.rudder.io/issues/7712[#7712])
* Fixed: Update documentation to use rudder-server-relay package instead
of manual configuration
(https://issues.rudder.io/issues/7266[#7266])

==== System integration

* Fixed: Firefox stalls after TLS handshake on self signed certificate
with a missing contact email
(https://issues.rudder.io/issues/7800[#7800])

==== Packaging

* Fixed: Test for non-applying patches on rudder-jetty and
rudder-agent-thin is broken
(https://issues.rudder.io/issues/7803[#7803])
* Fixed: Backport fixes for openldap memory leak in our package
(https://issues.rudder.io/issues/7801[#7801])
* Fixed: rudder-upgrade edits the wrong ncf.conf file causing transitory
invalid promises during upgrades
(https://issues.rudder.io/issues/7794[#7794])
* Fixed: rudder-init overwrite its logs
(https://issues.rudder.io/issues/7776[#7776])
* Fixed: rudder-server-relay rpm package should require rudder-agent
(https://issues.rudder.io/issues/7593[#7593])

==== Initial promises & sys tech

* Fixed: initial promises don’t create
/var/rudder/configuration-repository/ncf/ncf.conf
(https://issues.rudder.io/issues/7810[#7810])
* Fixed: inventory sent file timestamp not updated in normal run (system
techniques) (https://issues.rudder.io/issues/7782[#7782])
* Fixed: Fix permissions of the rudder tools in the repo
(https://issues.rudder.io/issues/7697[#7697])
* Fixed: check-rsyslog-version is missing on the nodes
(https://issues.rudder.io/issues/7680[#7680])
* Fixed: Non quiet curl calls on root and relay servers
(https://issues.rudder.io/issues/7678[#7678])
* Fixed: Permissions of rudder tools are not preserved on relays
(https://issues.rudder.io/issues/7644[#7644])
* Fixed: Unexpected reports on ``Log system for reports'' component of
system techniques
(https://issues.rudder.io/issues/7619[#7619])
* Fixed: Rudder agent simulates an aptitude full-upgrade during each run
(https://issues.rudder.io/issues/7141[#7141])
* Fixed: Error in environment-variables.cf on Centos 5
(https://issues.rudder.io/issues/7761[#7761])

==== Architecture - Refactoring

* Fixed: Change AGPL to GPL in rudder-plugin-itop
(https://issues.rudder.io/issues/7577[#7577])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Florian Heigl
* Janos Mattyasovszky
* Alex Tkachenko

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``esr'' release is still 2.11.*. When we release a new version
of Rudder, it needs to be thoroughly tested, and we consider the release
enterprise-ready for deployment only after it has been proven to run in
production reliably for several months.

== Rudder 3.0.12 (2015-12-10)

=== Changes

==== Packaging

* Update OpenSSL version to latest release
(https://issues.rudder.io/issues/7368[#7368])

=== Bug fixes

==== API

* Fixed: API Parameters create ``overridable'' boolean check doesn’t
work (https://issues.rudder.io/issues/6695[#6695])

==== Web - Config management

* Fixed: Read technique access does not give access to techniques
(https://issues.rudder.io/issues/7514[#7514])
* Fixed: Promises are not regenerated during upgrade
(https://issues.rudder.io/issues/7557[#7557])
* Fixed: Make possible to delete ANY active technique
(https://issues.rudder.io/issues/7536[#7536])
* Fixed: duplicate key value error on Rudder
(https://issues.rudder.io/issues/7316[#7316])

==== Web - Nodes & inventories

* Fixed: Tag FULL_NAME missing from SLES12 inventory
(https://issues.rudder.io/issues/7559[#7559])
* Fixed: Inventory  content differs from hostname –fqdn and may lead to
unauthorised nodes
(https://issues.rudder.io/issues/7031[#7031])
* Fixed: Test inventories are out of date since the addition of +
(https://issues.rudder.io/issues/7325[#7325])
* Fixed: Accepting two nodes seems to only accept one
(https://issues.rudder.io/issues/7024[#7024])

==== Web - UI & UX

* Fixed: Clone rule window too small
(https://issues.rudder.io/issues/7397[#7397])
* Fixed: Links to Node in event logs still contains an extra rudder
(https://issues.rudder.io/issues/7323[#7323])
* Fixed: Policy server url in node details is broken
(https://issues.rudder.io/issues/7462[#7462])
* Fixed: Compliance detail and compliance summary use different colours
(https://issues.rudder.io/issues/7416[#7416])
* Fixed: Dashboard incorrectly says ``0 node'' (should be nodes, in
plural) (https://issues.rudder.io/issues/7406[#7406])
* Fixed: Improve Rule compliance details loading
(https://issues.rudder.io/issues/7383[#7383])

==== Server components

* Fixed: promises are not regenerated when a node is transformed into a
relay (https://issues.rudder.io/issues/7301[#7301])
* Fixed: slapd core dumps on 1TB RAM
(https://issues.rudder.io/issues/7295[#7295])

==== Agent

* Fixed: rudder-agent repository on GitHub does not have a license
(https://issues.rudder.io/issues/7394[#7394])
* Fixed: If using proxmox, process management fails due to bad options
used on vzps (https://issues.rudder.io/issues/7423[#7423])
* Fixed: check-rudder-agent silently fails if namespaces are not
supported (https://issues.rudder.io/issues/7335[#7335])
* Fixed: `rudder agent reset' doesn’t cause ncf and tools to be updated
(https://issues.rudder.io/issues/7481[#7481])
* Fixed: Agent processes parts of the environment (multiline bash
variables) (https://issues.rudder.io/issues/7094[#7094])

==== Performance and scalability

* Fixed: Major performance hit in promise generation for unused
inventories fetch
(https://issues.rudder.io/issues/7541[#7541])
* Fixed: Improve graph perf by upgrade javascript libraries
(https://issues.rudder.io/issues/7512[#7512])

==== Documentation

* Fixed: Add a section about ncf-builder and its integration wihin
Rudder (https://issues.rudder.io/issues/6305[#6305])
* Fixed: Doc build is broken because of missing Makefile dependencies
(https://issues.rudder.io/issues/7339[#7339])

==== Techniques

* Fixed: Technique ``Clock settings'' uses Europe/Paris as China’s
timezone (technique version 3.0)
(https://issues.rudder.io/issues/7501[#7501])
* Fixed: OpenSSH server configuration does not reload configurations
(https://issues.rudder.io/issues/7479[#7479])
* Fixed: Create a new version of download file from the shared folder
that would allow to set the suid and gid to multiple file
(https://issues.rudder.io/issues/7379[#7379])

==== Initial promises & sys tech

* Fixed: Use whole path to binaries in cron from check-rudder-agent on
AIX (https://issues.rudder.io/issues/7525[#7525])
* Fixed: Use of nonexistant class cfengine_community makes failsafe.cf
not copy CFEngine binaries to /var/rudder
(https://issues.rudder.io/issues/7499[#7499])
* Fixed: ``Update'' component of common technique sometimes return
unexpected status and has incomplete reporting
(https://issues.rudder.io/issues/6648[#6648])
* Fixed: Syslog fails to restart due bad line in syslog-ng.conf
(https://issues.rudder.io/issues/7389[#7389])
* Fixed: Initial promises and techniques set group to ``root'' rather
than 0, breaking non-Linux OSes
(https://issues.rudder.io/issues/7476[#7476])
* Fixed: New version of ncf_conf.cache may not be properly updated on
nodes after an upgrade
(https://issues.rudder.io/issues/7452[#7452])
* Fixed: internal security check always assume that the node is a
community one (https://issues.rudder.io/issues/7430[#7430])
* Fixed: Agent cannot replace file per folder when copying promises, and
it may lock agent with invalid promises
(https://issues.rudder.io/issues/7190[#7190])
* Fixed: svcadm does not exist - so syslog is never restarted on Solaris
(https://issues.rudder.io/issues/7464[#7464])
* Fixed: Unexpected reports on ``cron daemon'' component of system
techniques (https://issues.rudder.io/issues/7176[#7176])

==== System integration

* Fixed: The rudder-agent cron on AIX uses if then, which makes some
security test fails
(https://issues.rudder.io/issues/7508[#7508])
* Fixed: JVM 8.0: warning about ``Ignoring option PermSize=128m; support
was removed in 8.0''
(https://issues.rudder.io/issues/7345[#7345])
* Fixed: rudder-agent and rudder-slapd init scripts may fail to stop
services if killall is missing or misbehaving
(https://issues.rudder.io/issues/7515[#7515])
* Fixed: /etc/init.d/rudder-jetty fails to stop jetty if it’s PID file
is missing (https://issues.rudder.io/issues/7469[#7469])
* Fixed: cf-execd is running twice after a reboot or after running
rudder-agent twice
(https://issues.rudder.io/issues/7420[#7420])
* Fixed: Initial git commit during package installation is too verbose
(https://issues.rudder.io/issues/7419[#7419])
* Fixed: Rudder OpenLDAP Authentication sans ipv4 localhost
(https://issues.rudder.io/issues/4922[#4922])
* Fixed: Missing debuging information for explain_compliance
(https://issues.rudder.io/issues/7353[#7353])

==== Packaging

* Fixed: Some patches silently fail to apply
(https://issues.rudder.io/issues/7556[#7556])
* Fixed: Modify the copy of ncf.conf instead of the original
(https://issues.rudder.io/issues/7445[#7445])
* Fixed: After a fresh install on Centos, the Rudder server web
interface does not work
(https://issues.rudder.io/issues/7395[#7395])
* Fixed: mvn –quiet is too quiet
(https://issues.rudder.io/issues/7371[#7371])
* Fixed: make wget quiet during build
(https://issues.rudder.io/issues/7370[#7370])
* Fixed: Make maven quiet during build
(https://issues.rudder.io/issues/7317[#7317])
* Fixed: rudder-inventory-ldap and rudder-jetty don’t stop their
services on uninstall and rudder-slapd can fail to restart on upgrade
(https://issues.rudder.io/issues/7516[#7516])
* Fixed: rudder-upgrade fails when *re*installing Rudder
(https://issues.rudder.io/issues/7510[#7510])
* Fixed: Script never terminate when they run rudder-jetty init script
(https://issues.rudder.io/issues/7492[#7492])
* Fixed: The package leave a temporary directory mehind
(https://issues.rudder.io/issues/7391[#7391])
* Fixed: All reports are missing (totally orange) for a node due to
multiple cf-execd processes
(https://issues.rudder.io/issues/7338[#7338])
* Fixed: Error when installing rudder : /opt/rudder/bin/rudder-upgrade:
line 573: /opt/rudder/bin/rpmvercmp: No such file or directory
(https://issues.rudder.io/issues/7470[#7470])

==== Techniques - Tests

* Fixed: rudder-techniques test script ``technique-files'' doesn’t list
promises.cf and failsafe.cf in initial-promises
(https://issues.rudder.io/issues/7496[#7496])
* Fixed: rudder-techniques test script ``technique-files'' lists files
in .git (https://issues.rudder.io/issues/7495[#7495])

==== Architecture - Refactoring

* Fixed: Correct a warning in rudder compilation
(https://issues.rudder.io/issues/7356[#7356])
* Fixed: We are using AGPL in place of GPL
(https://issues.rudder.io/issues/7546[#7546])
* Fixed: Inventory query test are not passing anymore in Rudder 3.0
(https://issues.rudder.io/issues/7357[#7357])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Layne Breitkreutz
* Dennis Cabooter
* Steeve Chailloux
* David Durieux
* Fabrice Flore-Thébault
* Greg fr
* Florian Heigl
* Olivier Mauras
* Janos Mattyasovszky

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``esr'' release is still 2.11.*. When we release a new version
of Rudder, it needs to be thoroughly tested, and we consider the release
enterprise-ready for deployment only after it has been proven to run in
production reliably for several months.

== Rudder 3.0.11 (2015-10-27)

=== Changes

==== System & initial promises

 * Touch local file on inventory upload
https://issues.rudder.io/issues/7206[#7206])

=== Bug fixes

==== Web - Config management

* Fixed: Change request list page, link to Rules are invalids (extra
rudder) (https://issues.rudder.io/issues/7244[#7244])

==== Web - Nodes & inventories

* Fixed: Link from node/directive list to node detail is broken on
Firefox/chrome
(https://issues.rudder.io/issues/7286[#7286])

==== Packaging

* Fixed: Maven never uses internal mirror
(https://issues.rudder.io/issues/7300[#7300])
* Fixed: Temporary files are not cleaned up after build
(https://issues.rudder.io/issues/7293[#7293])

==== System integration

* Fixed: zypper –version outputs on stderr
(https://issues.rudder.io/issues/7289[#7289])

==== Performance and scalability

* Fixed: RuleTargetTest.scala takes >40s where it should take 2s
(https://issues.rudder.io/issues/7303[#7303])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Florian Heigl
* Janos Mattyasovszky

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``esr'' release is still 2.11.*. When we release a new version
of Rudder, it needs to be thoroughly tested, and we consider the release
enterprise-ready for deployment only after it has been proven to run in
production reliably for several months.

== Rudder 3.0.10 (2015-10-20)

==== Web - Nodes & inventories

* Fixed: No service pack is reported when lsb_release is installed on
SLES (https://issues.rudder.io/issues/7205[#7205])

==== Techniques

* Fixed: Ssh key distribution cannot distibute several keys on one user
(https://issues.rudder.io/issues/7254[#7254])

==== Agent

* Fixed: Agent should be enabled after reinit
(https://issues.rudder.io/issues/7201[#7201])

==== Initial promises & sys tech

* Fixed: Network list for apache 2.4 is invalidly generated
(https://issues.rudder.io/issues/7268[#7268])
* Fixed: The daily cf-execd and cf-serverd restart should use SRC on AIX
(https://issues.rudder.io/issues/7274[#7274])
* Fixed: System technique’s curl should follow redirects
(https://issues.rudder.io/issues/7211[#7211])

==== System integration

* Fixed: check-rudder-agent faisl on an error while checking processes
(https://issues.rudder.io/issues/7243[#7243])

==== Packaging

* Fixed: Rudder agent doesn’t build with hardening flags
(https://issues.rudder.io/issues/7257[#7257])
* Fixed: Patch not applied on fusion inventory
(https://issues.rudder.io/issues/7241[#7241])

==== Server components

* Fixed: Root server’s apache config does not honor < 2.4 for webdav
(https://issues.rudder.io/issues/7267[#7267])

==== Performance and scalability

* Fixed: Writing promises should be parallelized
(https://issues.rudder.io/issues/7265[#7265])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Florian Heigl
* Janos Mattyasovszky

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``esr'' release is still 2.11.*. When we release a new version
of Rudder, it needs to be thoroughly tested, and we consider the release
enterprise-ready for deployment only after it has been proven to run in
production reliably for several months.

== Rudder 3.0.9 (2015-09-24)

=== Changes

==== Techniques

* Fixed: Add an option to ignore non existent file in the file
permission technique
(https://issues.rudder.io/issues/7228[#7228])

==== Documentation

* Split the html documentation to improve readability and navigability
(https://issues.rudder.io/issues/6604[#6604])
* Improve rudder server requirements formatting
(https://issues.rudder.io/issues/7081[#7081])
* Improve the readability of the server installation section of the
manual (https://issues.rudder.io/issues/6603[#6603])
* Fixed: Document clearly technique upgrades
(https://issues.rudder.io/issues/7077[#7077])

=== Bug fixes

==== Initial promises & sys tech

* Fixed: The rudder server tries to send ``uuid.hive'' as an inventory
(https://issues.rudder.io/issues/6987[#6987])
* Fixed: System technique distributePolicy is not system and has two
system var section
(https://issues.rudder.io/issues/7138[#7138])
* Fixed: Promise copy is not convergent: if the copy is interupted, it
will never recover
(https://issues.rudder.io/issues/7086[#7086])
* Fixed: If the agent schedule is not every 5 minutes, inventory may not
be sent anymore
(https://issues.rudder.io/issues/6718[#6718])
* Fixed: Environnement variables cannot be used on windows
(https://issues.rudder.io/issues/7150[#7150])

==== System integration

* Fixed: Error starting apache on SLES11 relay
(https://issues.rudder.io/issues/7097[#7097])

==== Web - Config management

* Fixed: Rules are not serialized correctly anymore
(https://issues.rudder.io/issues/7108[#7108])

==== Web - Compliance & node report

* Fixed: Agent schedule is not historised, so we can’t know what was the
agent run interval in the past
(https://issues.rudder.io/issues/7154[#7154])

==== Web - Technique editor

* Fixed: Read only role is not correctly interpreted in technique
editor. (https://issues.rudder.io/issues/7199[#7199])

==== Techniques

* Fixed: motd technique wrongly reports that it is incompatible with
windows (https://issues.rudder.io/issues/7153[#7153])

==== Packaging

* Fixed: issues with process management on physical hosting LXC
containers (https://issues.rudder.io/issues/7189[#7189])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Libra Linux

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.11.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 3.0.8 (2015-08-19)

=== Bug fixes

==== Web - Config management

* Fixed: System object (techniques, directives, rules, groups) must be
always enabled
(https://issues.rudder.io/issues/7064[#7064])
* Fixed: Editing a rule category remove it from Git - rule categories
disapear! (Ranärok ensues)
(https://issues.rudder.io/issues/6840[#6840])
* Fixed: Clear cache doesn’t regenerate expected reports
(https://issues.rudder.io/issues/7080[#7080])

==== Web - Compliance & node report

* Fixed: Reporting cannot be used when there is several component with
the same value and several messages
(https://issues.rudder.io/issues/7037[#7037])

==== Web - Maintenance

* Fixed: When accessing event logs page, it stays empty until jetty is
restarted (https://issues.rudder.io/issues/6939[#6939])

==== Web - Nodes & inventories

* Fixed: If domain name is not set in resolv.conf, the inventory
generated is invalid
(https://issues.rudder.io/issues/7001[#7001])
* Fixed: Xen list parsed badly by FusionInventory, causing VCPU to be
counted badly (https://issues.rudder.io/issues/6754[#6754])
* Fixed: FusionInventory doesn’t provide the Rudder extension on other
platform than Linux
(https://issues.rudder.io/issues/6747[#6747])

==== Agent

* Fixed: If we ask to install a package in a version at least equal to
another, we get no report if the version installed is > than the one
requested (https://issues.rudder.io/issues/6996[#6996])
* Fixed: Migration from 2.10.x to 2.11.x on Debian may disable the agent
(https://issues.rudder.io/issues/7099[#7099] )

==== Techniques

* Fixed: aptPackageManagerSetting technique doesn’t work on Ubuntu
(https://issues.rudder.io/issues/6999[#6999])
* Fixed: Reporting on openssh server configuration technique is not
correct for port edition
(https://issues.rudder.io/issues/6942[#6942])
* Fixed: ntp Technique does not report when repairing
(https://issues.rudder.io/issues/6941[#6941])

==== Initial promises & sys tech

* Fixed: Bad regexp in the cron for Rudder nova
(https://issues.rudder.io/issues/7014[#7014])
* Fixed: A report is missing on system techniques when cron needs to be
restartd (https://issues.rudder.io/issues/6660[#6660])
* Fixed: On Windows, Rudder specific inventories is not be added to
inventory with most version of CFEngine Enterprise
(https://issues.rudder.io/issues/7057[#7057])
* Fixed: When promises could have been updated, we still have the error
messages saying we couldn’t update promises
(https://issues.rudder.io/issues/7038[#7038])
* Fixed: When the nxlog configuration is changed on windows, service is
not restarted (https://issues.rudder.io/issues/7012[#7012])
* Fixed: System techniques on systemd based system do not handle boot
script correctly
(https://issues.rudder.io/issues/6988[#6988])

==== Packaging

* Fixed: Some code is duplicated in debian postinst
(https://issues.rudder.io/issues/7073[#7073])

==== System integration

* Fixed: Rsyslog problem on Ubuntu 14.04 fresh install
(https://issues.rudder.io/issues/6127[#6127])

==== Architecture - Refactoring

* Fixed: Remove scala compiler warning about comparing values of type
Null (https://issues.rudder.io/issues/7072[#7072])

==== Architecture - Internal libs

* Fixed: A test is not compiling on branch 2.11 since #6729 was merged
(https://issues.rudder.io/issues/7056[#7056])
* Fixed: Exception thrown when debug_timer is set on Rule pages
(https://issues.rudder.io/issues/7071[#7071])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Remi Debay
* Janos Mattyasovszky
* Christophe Nowicki

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.11.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 3.0.7 (2015-07-09)

=== Changes

==== Packaging

* Add a caching system to rudder build system
(https://issues.rudder.io/issues/6713[#6713])

=== Bug fixes

==== Web - UI & UX

* Fixed: More coherent informations on dashboard
(https://issues.rudder.io/issues/6777[#6777])
* Fixed: Broken down stats by agent version is completely out of it
(https://issues.rudder.io/issues/6491[#6491])

==== Web - Config management

* Fixed: After a partial promise generation, some nodes being a relay
may have their promises stored in a non reachable location
(https://issues.rudder.io/issues/6729[#6729])

==== Web - Nodes & inventories

* Fixed: Heartbeat bad interval time calcul on node
(https://issues.rudder.io/issues/6746[#6746])

==== Agent

* Fixed: Cf-agent writes incorrect files when the server answers too
slowly during recursive copy
(https://issues.rudder.io/issues/6915[#6915])

==== Initial promises & sys tech

* Fixed: Rudder relay rsyslog configuration still have AllowedSender
directives (https://issues.rudder.io/issues/6907[#6907])
* Fixed: Ubuntu trusty does not have an /etc/motd by default
(https://issues.rudder.io/issues/6904[#6904])
* Fixed: We can’t use cf-runagent because port is not taken into account
in the body runagent control
(https://issues.rudder.io/issues/6916[#6916])
* Fixed: Nodes using syslogd coninue to report to their old server when
changing their policy server
(https://issues.rudder.io/issues/6845[#6845])
* Fixed: Editing non-existent /etc/rsyslog.d/pgsql.conf in initial
promises (https://issues.rudder.io/issues/6784[#6784])

==== System integration

* Fixed: Bad handling of pid file on OpenVZ
(https://issues.rudder.io/issues/6928[#6928])
* Fixed: Rudder-jetty init script fails to get openjdk version
(https://issues.rudder.io/issues/6765[#6765])
* Fixed: Sometimes, promises get corrupted to the point they can’t be
automatically repaired on a node
(https://issues.rudder.io/issues/6768[#6768])

==== Server components

* Fixed: Update OpenLDAP to 2.4.41
(https://issues.rudder.io/issues/6931[#6931])

==== Techniques

* Fixed: No reporting in dnsConfiguration 3.0
(https://issues.rudder.io/issues/6775[#6775])
* Fixed: Openssh technique is missing reports
(https://issues.rudder.io/issues/6611[#6611])
* Fixed: Unexpected status for fileAlterationMonitoring
(https://issues.rudder.io/issues/6771[#6771])

==== Documentation

* Fixed: Wrong hierachy in archives section of the manual
(https://issues.rudder.io/issues/6909[#6909])
* Fixed: Broken asciidoc list formatting
(https://issues.rudder.io/issues/6778[#6778])
* Fixed: Outdated download link in the manual
(https://issues.rudder.io/issues/6764[#6764])
* Fixed: Broken link and misplaced page in documentation
(https://issues.rudder.io/issues/6757[#6757])

==== Packaging

* Fixed: AIX installations output errors due to ``cp -a'' usage
(https://issues.rudder.io/issues/6830[#6830])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Dennis Cabooter
* Olivier Mauras

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. The current
``esr'' release is still 2.11.*. When we release a new version of
Rudder, it needs to be thoroughly tested, and we consider the release
enterprise-ready for deployment only after it has been proven to run in
production reliably for several months.

== Rudder 3.0.6 (2015-06-18)

=== Changes

==== Agent

* Add an option to run cf-agent with -v to rudder agent run
(https://issues.rudder.io/issues/6731[#6731])
* Man pages for the rudder command
(https://issues.rudder.io/issues/6659[#6659])

=== Bug fixes

==== Web - Config management

* Fixed: When we accept a new node, we have two promises generation
instead of one
(https://issues.rudder.io/issues/6575[#6575])
* Fixed: When we regenerate promises via `Update' button, all promises
are regenerated even if not needed
(https://issues.rudder.io/issues/6518[#6518])

==== Web - Compliance & node report

* Fixed: Compliance in dashboard and rule page are not consistant
(https://issues.rudder.io/issues/6663[#6663])
* Fixed: The Global compliance is buggy when there is no data
(https://issues.rudder.io/issues/6633[#6633])
* Fixed: Blue for no report in bar charts doesn’t make sense
(https://issues.rudder.io/issues/6489[#6489])
* Fixed: Compliance in dashboard and rule page are not consistant
(https://issues.rudder.io/issues/6663[#6663])
* Fixed: When we add a node in a rule, we lose all compliance info on
this rule applied on it, and we change promises of all the nodes of the
rule (https://issues.rudder.io/issues/6519[#6519])
* Fixed: No reporting on agents on ncf directives on SLES
(https://issues.rudder.io/issues/6673[#6673])

==== Web - UI & UX

* Fixed: No rules displayed in firefox
(https://issues.rudder.io/issues/6490[#6490])
* Fixed: Bad RegEx in Groups causes Server to not respond
(https://issues.rudder.io/issues/6680[#6680])

==== Web - Nodes & inventories

* Fixed: Error 500 when sending multiple files to inventory endpoint
(https://issues.rudder.io/issues/6508[#6508])
* Fixed: Search results grayed out
(https://issues.rudder.io/issues/6277[#6277])

==== Web - Technique editor

* Fixed: Cannot save technique with ncf builder - error during the API
call to the technique librairy reload
(https://issues.rudder.io/issues/6724[#6724])
* Fixed: ncf post-hooks fails when there is nothing to commit
(https://issues.rudder.io/issues/6617[#6617])

==== API

* Fixed: In group API, attribute and comparator names are case sensitive
(https://issues.rudder.io/issues/6577[#6577])

==== System integration

* Fixed: rudder-server-root init script is not compatible with systemd
(https://issues.rudder.io/issues/6760[#6760])
* Fixed: RHEL7 does not initialise postgresql db
(https://issues.rudder.io/issues/6702[#6702])
* Fixed: ncf init fails in webapp postinst
(https://issues.rudder.io/issues/6698[#6698])
* Fixed: rudder-reports does not find correct postgresql service when
using systemctl
(https://issues.rudder.io/issues/6699[#6699])
* Fixed: Startup links for rudder-server-root on Ubuntu are not correct
- before 3.1 (https://issues.rudder.io/issues/6263[#6263])
* Fixed: Error about ldconfig during rudder-agent installation on AIX
(https://issues.rudder.io/issues/6703[#6703])

==== Server components

* Fixed: Webdav allow connection from any network, not only allowed
network (https://issues.rudder.io/issues/6540[#6540])
* Fixed: Messages forwarded from AIX agent are not dropped on
relay/server root after being consumed
(https://issues.rudder.io/issues/6522[#6522])
* Fixed: Log rotation on distributed install is not functionnal
[[https://issues.rudder.io/issues/6521][#6521
* Fixed: Syslog accept reports from non-accepted nodes
(https://issues.rudder.io/issues/6428[#6428])
* Fixed: rudder-reports has not sufficient dependency to postgresql’s
version (https://issues.rudder.io/issues/6662[#6662])
* Fixed: When a node is promoted to relay, the old rsyslog conf is never
replaced (https://issues.rudder.io/issues/6721[#6721])

==== Performance and scalability

* Fixed: Do not check dns when checking promises
(https://issues.rudder.io/issues/6616[#6616])

==== Techniques

* Fixed: Typo in Technique ``zypper settings''
(https://issues.rudder.io/issues/6677[#6677])
* Fixed: Zypper is called without –non-interactive when filling
available updates cache
(https://issues.rudder.io/issues/6588[#6588])
* Fixed: Technique ``Clock settings'' uses Europe/Paris as China’s
timezone (https://issues.rudder.io/issues/6450[#6450])
* Fixed: MaxSessions parameter is supported on RedHat 6.3 (at least),
but Technique SSHConfiguration prevent from configuring it on this
system (https://issues.rudder.io/issues/6527[#6527])
* Fixed: Promises.st can’t load ncf on windows
(https://issues.rudder.io/issues/6700[#6700])

==== Initial promises & sys tech

* Fixed: Create a rudder variable containing all IP of agents
(https://issues.rudder.io/issues/6481[#6481])]])

==== Agent

* Fixed: cfengine context is not updated properly when doing multiple
indivudual package actions
(https://issues.rudder.io/issues/6587[#6587])

==== Packaging

* Fixed: The detect_os.sh script is not valid
(https://issues.rudder.io/issues/6486[#6486])

==== Documentation

* Fixed: Add Debian 8 support in the specs for Rudder nodes
(https://issues.rudder.io/issues/6704[#6704])
* Fixed: HashcodeCaching.scala typo error WRNING => WARNING
(https://issues.rudder.io/issues/6734[#6734])
* Fixed: Restore procedures has service name mistyped
(https://issues.rudder.io/issues/6664[#6664])
* Fixed: Old Normation logo in the manual
(https://issues.rudder.io/issues/6643[#6643])
* Fixed: Broken link in the demo section of rudder README
(https://issues.rudder.io/issues/6610[#6610])
* Fixed: Bibliography links are out of date
(https://issues.rudder.io/issues/6609[#6609])
* Fixed: Broken links in the manual
(https://issues.rudder.io/issues/6607[#6607])
* Fixed: Check spelling and grammar of the manual
(https://issues.rudder.io/issues/6599[#6599])
* Fixed: Remove references to the Big Red Button in the manual
(https://issues.rudder.io/issues/6596[#6596])
* Fixed: Fix asciidoc list formatting
(https://issues.rudder.io/issues/6595[#6595])
* Fixed: Rudder Documentation typo
(https://issues.rudder.io/issues/6559[#6559])
* Fixed: Update command on centos is missing ``ncf-api-virtualenv''
package (https://issues.rudder.io/issues/6503[#6503])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Dennis Cabooter
* Florian Heigl
* Janos Mattyasovszky
* Olivier Mauras

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. The current
``esr'' release is still 2.11.*.

== Rudder 3.0.5 (2015-06-02)

Not released due to a major bug
https://issues.rudder.io/issues/6507[#6507]

== Rudder 3.0.4 (2015-04-13)

=== Changes

=== Bug fixes

==== Web - Compliance & node report

* Fixed: Promises are generated when a directive is created
(https://issues.rudder.io/issues/6452[#6452])

==== Web - Nodes & inventories

* Fixed: Missing error message when trying to accept a node with an
already existing hostname
(https://issues.rudder.io/issues/6451[#6451])

==== API

* Fixed: Node API cannot get pending and refused node details
(https://issues.rudder.io/issues/6482[#6482])

==== Web - Maintenance

* Fixed: Plugin name are not displayed
(https://issues.rudder.io/issues/6484[#6484])

==== Techniques

* Fixed: Document usage of line replacement in Enforce a file content
technique (https://issues.rudder.io/issues/5979[#5979])
* Fixed: MOTD directive has 2 different technique versions
(https://issues.rudder.io/issues/6272[#6272])

==== Server components

* Fixed: networks.conf missing on relay servers
(https://issues.rudder.io/issues/6454[#6454])

==== Agent

* Fixed: Agent may not work after a reinit
(https://issues.rudder.io/issues/6441[#6441])

==== Initial promises & sys tech

* Fixed: No reports for Propagate promises component on relay
(https://issues.rudder.io/issues/6404[#6404])

==== System integration

* Fixed: rudder-agent is stuck, waiting for user input during log
compression (https://issues.rudder.io/issues/6439[#6439])
* Fixed: rudder-jetty init script may fail on success
(https://issues.rudder.io/issues/5653[#5653])

==== Documentation

* Fixed: Improve documentation of archives management
(https://issues.rudder.io/issues/6485[#6485])
* Fixed: Badly explain minimum requierement for Rudder in documentation
(https://issues.rudder.io/issues/6453[#6453])
* Fixed: Outdated chapter: Disable automatic regeneration of promises
(https://issues.rudder.io/issues/6312[#6312])

==== Packaging

* Fixed: Remove python dependency for rudder-agent
(https://issues.rudder.io/issues/6424[#6424])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Florian Heigl
* Peter Keresztes
* Lionel Le Folgoc

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 3.0.3 (2015-03-24)

=== Changes

=== Bug fixes

==== Web - Technique editor

* Fixed: Command execution generic method does not send compliance
report because rudder_expected_reports.csv is empty
(https://issues.rudder.io/issues/6419[#6419])

==== Techniques

* Fixed: Enforce file content Technique doesn’t properly migrate lines
from outside the zone to the zone
(https://issues.rudder.io/issues/6389[#6389])

==== Agent

* Fixed: Using parsestringarrayidx on AIX leads to agent hanging up or
promises validation errors (only on 2.11)
(https://issues.rudder.io/issues/6396[#6396])

==== System integration

* Fixed: Rudder login page doesn’t appear just after the webapp has been
started (https://issues.rudder.io/issues/6402[#6402])
* Fixed: File /var/log/rudder/\{compliance/non-compliant-reports.log,
core/rudder-webapp.log} are not correctly rotated
(https://issues.rudder.io/issues/6381[#6381])

==== Packaging

* Fixed: AIX rudder-agent SPECfile fails to build due to a macro
expansion error
(https://issues.rudder.io/issues/6380[#6380])
* Fixed: The Ubuntu 14.04 default apache vhosts are not removed properly
and ncf-api-virtualenv is not put at the right place
(https://issues.rudder.io/issues/6392[#6392])

==== Architecture - Dependencies

* Fixed: Upgrade Liftweb to v2.5.2 (security issue)
(https://issues.rudder.io/issues/6426[#6426])

=== Release notes

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 3.0.2 (2015-03-09)

=== Changes

==== System integration

* Rudder-update need to check for the PostgreSQL version
(https://issues.rudder.io/issues/6289[#6289])

=== Bug fixes

==== Webapp - Display, home page

* Fixed: rule and group category ID are not displayed
(https://issues.rudder.io/issues/6323[#6323])
* Fixed: Display UUIDs in rudder web interface in lowercase so they can
be used directly.
(https://issues.rudder.io/issues/6297[#6297])

==== Webapp - Config management

* Fixed: ``+'' and ``-'' buttons to add a group to a Rule redirects to
the group edition page instead of adding the group to the Rule
(https://issues.rudder.io/issues/6276[#6276])

==== Webapp - Node management

* Fixed: List of impacted rules when accepting nodes or modifing
directives is not accurate
(https://issues.rudder.io/issues/5764[#5764])
* Fixed: Cannot remove node properties when setting value to ""
(https://issues.rudder.io/issues/6282[#6282])

==== API

* Fixed: Wrong default category set when creating a Rule
(https://issues.rudder.io/issues/6314[#6314])

==== Techniques

* Fixed: it’s not possible to define variables with " in them in generic
variable definition
(https://issues.rudder.io/issues/6279[#6279])
* Fixed: Wrong reporting in Technique Enforce a file content if the file
is not present
(https://issues.rudder.io/issues/6237[#6237])
* Fixed: OpenSSH server technique tries to configure MaxSession on AIX
5.3, but this parameter is invalid on this OS
(https://issues.rudder.io/issues/6374[#6374])
* Fixed: The fileManagement Technique does not report on AIX
(https://issues.rudder.io/issues/6362[#6362])

==== Documentation

* Fixed: SuSE upgrade procedure is missing a ncf upgrade, and the
documentation references no-more-present init scripts
(https://issues.rudder.io/issues/6288[#6288])
* Fixed: documentation states that `Workflow' needs to be set in the
config file, but now in rudder web interface
(https://issues.rudder.io/issues/6283[#6283])
* Fixed: Documentation to upgrade Rudder Server on Debian/Ubuntu is
incomplete (https://issues.rudder.io/issues/6109[#6109])
* Fixed: The migration to 2.11 procedure is misleading
(https://issues.rudder.io/issues/5794[#5794])

==== System integration

* Fixed: The rudder-agent package should remove the inittab entry and
subsystem on AIX, and should not run ldconfig
(https://issues.rudder.io/issues/6364[#6364])
* Fixed: SLES 11 SP1 requires an older version of Python virtualenv
(https://issues.rudder.io/issues/6365[#6365])
* Fixed: ncf-api-virtualenv fails to build due to and outdated version
of virtualenv (https://issues.rudder.io/issues/6347[#6347])
* Fixed: Rudder agent fails to build on Ubuntu 10.04 due to a buggy
dh_shlibdeps (https://issues.rudder.io/issues/6337[#6337])
* Fixed: Remove SASL support from rudder-inventory-ldap
(https://issues.rudder.io/issues/6229[#6229])
* Fixed: Upgrade rudder-agent can’t find/install man pages
(https://issues.rudder.io/issues/6016[#6016])

==== ncf-builder integration

* Fixed: rudderify ncf-hook does not work on first run
(https://issues.rudder.io/issues/6249[#6249])

==== Packaging

* Fixed: When I want to upgrade Rudder to latest version, ncf is NOT
updated on SLES11
(https://issues.rudder.io/issues/6286[#6286])
* Fixed: Unable to install Rudder agent if there is no rsync nor
libpcre3 installed on the system on Debian
(https://issues.rudder.io/issues/6239[#6239])

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Jean Cardona
* Florian Heigl
* Maxime Longuet

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 3.0.1 (2015-02-23)

=== Changes

=== Bug fixes

==== Techniques

* Fixed: Fatal error in rpmPackageInstallation v7.0, cannot generate
policies (https://issues.rudder.io/issues/6273[#6273])

==== Documentation

* Fixed: Adapt Rudder documentation for 3.0 release
(https://issues.rudder.io/issues/6241[#6241])
* Fixed: Add missing `properties' in rudder-api doc
(https://issues.rudder.io/issues/6280[#6280])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter

This is a bug fix release in the 3.0 series and therefore all
installations of 3.0 should be upgraded when possible. This version is
not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 3.0.0 (2015-02-16)

=== Changes

==== Webapp - Node management

* Have the possibility to bookmark search queries
(https://issues.rudder.io/issues/5774[#5774])

==== Webapp - Display, home page

* Rudder 3.0 logo
(https://issues.rudder.io/issues/6084[#6084])

=== Bug fixes

==== Webapp - Config management

* Fixed: Cannot apply a Directive to all visible Rules
(https://issues.rudder.io/issues/6260[#6260])
* Fixed: First access to rule page leads to ``server can not be
contacted at this time''
(https://issues.rudder.io/issues/6255[#6255])
* Fixed: If a run is not completed, compliance computation goes mad
(https://issues.rudder.io/issues/6211[#6211])
* Fixed: Server cannot be contacted at this time when deleting a
Directive (https://issues.rudder.io/issues/6198[#6198])
* Fixed: Refreshing rules grid make them all disappear
(https://issues.rudder.io/issues/6190[#6190])
* Fixed: In rule details->compliance, reload should reload all graphes
at once (https://issues.rudder.io/issues/6165[#6165])
* Fixed: Sorting Rule tables on ``Compliance'' and ``Recent Changes''
sort by name (https://issues.rudder.io/issues/6162[#6162])
* Fixed: Rule details and Directive not accessible if technique version
is missing (https://issues.rudder.io/issues/6161[#6161])
* Fixed: Tooltip on Directive tree does not appear after refresh/click
on a element (https://issues.rudder.io/issues/6148[#6148])
* Fixed: Button to migrate to last version when a Technique is
deprecated is disabled
(https://issues.rudder.io/issues/6147[#6147])

==== Webapp - Node management

* Fixed: The quick search input does not works on search page
(https://issues.rudder.io/issues/6261[#6261])
* Fixed: When you delete a Node it stays in the Node list
(https://issues.rudder.io/issues/6242[#6242])
* Fixed: JsError when opening a node details
(https://issues.rudder.io/issues/6233[#6233])
* Fixed: IE bug: groups cannot be saved nor deleted
(https://issues.rudder.io/issues/6116[#6116])
* Fixed: Accept new node screen has some minor display issue
(https://issues.rudder.io/issues/6114[#6114])
* Fixed: List of impacted rules when accepting nodes or modifing
directives is not accurate
(https://issues.rudder.io/issues/5764[#5764])

==== Webapp - Administration

* Fixed: Event log table cannot be opened on other pages than first one
(https://issues.rudder.io/issues/6214[#6214])
* Fixed: In eventlogs, the ``Raw Technical Details'' is not underlined,
and so we don’t know that it is clickable
(https://issues.rudder.io/issues/5994[#5994])

==== Webapp - Display, home page

* Fixed: Rudder stores too much or too big cookies, causing white page
with HTTP status: 413: FULL head
(https://issues.rudder.io/issues/6160[#6160])
* Fixed: IE bug: charts not displayed
(https://issues.rudder.io/issues/6115[#6115])
* Fixed: Sometimes, there is glitch in display of homepage charts
(https://issues.rudder.io/issues/6091[#6091])
* Fixed: Node breakdown pie chart on homepage may be of different size
(https://issues.rudder.io/issues/6090[#6090])
* Fixed: Some buttons does not work correctly with IE9
(https://issues.rudder.io/issues/6077[#6077])
* Fixed: Add missing logger when there is an error when dsplaying
compliance (https://issues.rudder.io/issues/6053[#6053])
* Fixed: Save message notification misplaced for global agent run
preference (https://issues.rudder.io/issues/6022[#6022])
* Fixed: Display of legend in the dashboard is not really readable
(https://issues.rudder.io/issues/5996[#5996])
* Fixed: Title bar take twice its size in 1280x1024
(https://issues.rudder.io/issues/5964[#5964])

==== ncf-builder integration

* Fixed: URL for the ncf-builder call is misunderstood by IE9 (bad html5
support) (https://issues.rudder.io/issues/6130[#6130])
* Fixed: rudderify ncf-hook does not work on first run
(https://issues.rudder.io/issues/6249[#6249])

==== Webapp - Reporting

* Fixed: Some heartbeat are skipped in change only mode
(https://issues.rudder.io/issues/6209[#6209])
* Fixed: On policy server, we do override the run interval, and the
expected frequency for reports, but the generated promises don’t
override the heartbeat frequency, causing non answer in the webapp
(https://issues.rudder.io/issues/6206[#6206])
* Fixed: Compliance computation on home page dashboard charts is
incoherent regarding pending nodes
(https://issues.rudder.io/issues/6205[#6205])
* Fixed: If I create a rule, the Rules table is not correctly refreshed,
and I get a neverending ``loading''
(https://issues.rudder.io/issues/6203[#6203])
* Fixed: Cleanup databases
(https://issues.rudder.io/issues/6156[#6156],
(https://issues.rudder.io/issues/6050[#6050])
* Fixed: Pending state is not managed as user could expect in changes
only mode (https://issues.rudder.io/issues/6021[#6021])

==== Techniques

* Fixed: Wrong reporting in Technique Enforce a file content if the file
is not present
(https://issues.rudder.io/issues/6238[#6238])
* Fixed: Reporting errors in fstab Technique v4.0
(https://issues.rudder.io/issues/6218[#6218])
* Fixed: Reporting errors in sudoParameters Technique v3.0
(https://issues.rudder.io/issues/6217[#6217])
* Fixed: Wrong reporting in Technique Enforce a file content if the file
is not present
(https://issues.rudder.io/issues/6237[#6237])

==== Techniques - System & initial promises

* Fixed: When we install rudder-agent package, it tries to send
automatically the node inventory to machine ``rudder''
(https://issues.rudder.io/issues/6113[#6113])
* Fixed: Reports on service checks are not correct
(https://issues.rudder.io/issues/6057[#6057])
* Fixed: rudder agent on sles server logs a lot of errors about service
checking (https://issues.rudder.io/issues/6056[#6056])
* Fixed: On a freshly installed node, rsyslog is dropping messages
(https://issues.rudder.io/issues/5991[#5991])

==== Documentation

* Fixed: Documentation to upgrade Rudder Server on Debian/Ubuntu is
incomplete (https://issues.rudder.io/issues/6109[#6109])

==== System integration

* Fixed: Bad logs at info level
(https://issues.rudder.io/issues/6228[#6228])
* Fixed: rudder-metrics-reporting tries to use a ca file that is a
directory (https://issues.rudder.io/issues/6058[#6058])
* Fixed: Upgrading rudder-inventory-ldap between two major OS versions
makes slapd unable to operate because of BerkeleyDB
(https://issues.rudder.io/issues/5741[#5741])

==== Packaging

* Fixed: Error log when installing rudder-inventory ldap on RHEL6
(https://issues.rudder.io/issues/6032[#6032])
* Fixed: Bundled OpenSSL patches in rudder-agent 3.0 are not up to date
(https://issues.rudder.io/issues/6227[#6227])
* Fixed: Add a patch in CFEngine to support FORTIFY_SOURCE
(https://issues.rudder.io/issues/6117[#6117])
* Fixed: CFLAGS/CXXFLAGS definition in rudder-agent SPEC file does not
work on RHEL7 (https://issues.rudder.io/issues/6112[#6112])
* Fixed: Rudder agent build fails on RHEL5 / SLES 10
(https://issues.rudder.io/issues/6095[#6095])
* Fixed: Building rudder-agent fails on Ubuntu 10.04
(https://issues.rudder.io/issues/6093[#6093])
* Fixed: Rudder Debian 8 support patches conflict with rudder-agent-thin
packages (https://issues.rudder.io/issues/6076[#6076])
* Fixed: Remove SASL support from rudder-inventory-ldap
(https://issues.rudder.io/issues/6229[#6229])
* Fixed: Unable to install Rudder agent if there is no rsync nor
libpcre3 installed on the system on Debian
(https://issues.rudder.io/issues/6239[#6239])

==== Performance and scalability

* Fixed: Add a cache for compliance by node
(https://issues.rudder.io/issues/6194[#6194])
* Fixed: Add a cache for recent changes
(https://issues.rudder.io/issues/6184[#6184])
* Fixed: Compliance is computed several time to display Rule grid
(https://issues.rudder.io/issues/6135[#6135])
* Fixed: Performance issue for Accept new nodes > history of acceptation
(https://issues.rudder.io/issues/6078[#6078])
* Fixed: Improve rule page loading by having asynchronous complianced
loading (https://issues.rudder.io/issues/6073[#6073])
* Fixed: Performance of retrieving last node run reports time impact
both compliance and list of node screen
(https://issues.rudder.io/issues/6063[#6063])
* Fixed: Graphs in home page take ages to display
(https://issues.rudder.io/issues/6059[#6059])
* Fixed: Charts in homepage must be lazy loaded
(https://issues.rudder.io/issues/6052[#6052])
* Fixed: Performance issue for node list
(https://issues.rudder.io/issues/5452[#5452])

==== Architecture - Dependencies

* Fixed: Missing war plugin ° attach source for rudder plugin
(https://issues.rudder.io/issues/6072[#6072])

==== Architecture - Refactoring

* Fixed: Remove dead code
(https://issues.rudder.io/issues/6062[#6062],
(https://issues.rudder.io/issues/6060[#6060])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Lionel Le Folgoc
* Maxime Longuet

This version of Rudder is a final release. We have tested it thoroughly
and believe it to be free of any major bugs. However, this branch is not
marked ``stable'', since it still has to be proven reliable on
production systems over a period of several months. The current
``stable'' release is 2.10.*.

== Rudder 3.0.0~rc1 (2014-12-31)

=== Changes

=== Bug fixes

==== Webapp - Config management

* Fixed: Cannot open reporting details for directive in both table at
the same time (https://issues.rudder.io/issues/6036[#6036])
* Fixed: Status of Rule is displayed as ``N/A''
(https://issues.rudder.io/issues/5888[#5888])

==== Webapp - Reporting

* Fixed: If the end reports message contains special characters, like
carriage returns, the reporting fails
(https://issues.rudder.io/issues/6047[#6047])
* Fixed: If i update or create a rule, all nodes that are in the target
of this rule get the ``pending'' state
(https://issues.rudder.io/issues/6040[#6040])
* Fixed: The expected reports of other rules are not correctly updated
when we create a new rule
(https://issues.rudder.io/issues/6039[#6039])
* Fixed: Wrong reporting after execution of migration script to change
the way reports are used from the database
(https://issues.rudder.io/issues/6038[#6038])

==== Webapp - Administration

* Fixed: Do not display send metrics popup directly after `ask later'
was clicked (https://issues.rudder.io/issues/6045[#6045])

==== Webapp - Display, home page

* Fixed: Header menu css is not displayed in IE9
(https://issues.rudder.io/issues/6049[#6049])
* Fixed: No popup displayed in IE9
(https://issues.rudder.io/issues/6048[#6048])
* Fixed: The interface is unsusable under some versions of firefox
(https://issues.rudder.io/issues/5962[#5962])

==== System integration

* Fixed: Missing installation of migration script for database
(https://issues.rudder.io/issues/6044[#6044])
* Fixed: The Debian 8 patch to use the system LMDB instance is outdated
(https://issues.rudder.io/issues/6033[#6033])

=== Release notes

This software is in ``release candidate'' status and contains multiple
bug fixes since the first release candidate (2.8.0~rc1). If no major
bugs are found, a ``final'' release of 2.8.0 will be released next week.

== Rudder 3.0.0~beta2 (2014-12-19)

=== Changes

==== ncf-builder integration

* Integrate ncf-builder in an iframe within the main Rudder interface
(https://issues.rudder.io/issues/5917[#5917])

==== Webapp - Config management

* Add always visible save button for Rules
(https://issues.rudder.io/issues/4331[#4331])

==== Webapp - Administration

* Display a popup when `metrics' property is not set
(https://issues.rudder.io/issues/6003[#6003])
* Make event log table asynchronous
(https://issues.rudder.io/issues/5960[#5960])
* Make change request table asynchronous
(https://issues.rudder.io/issues/5957[#5957])

==== Utilities

* New rudder utility command: agent version
(https://issues.rudder.io/issues/5908[#5908])

==== System integration

* Update to CFEngine 3.6.3 final
(https://issues.rudder.io/issues/5939[#5939])
* Ease rudder-agent installation by setting default values
(https://issues.rudder.io/issues/4900[#4900])

==== Performance and scalability

* Don’t generate promises when there are no change that change the
generated promises
(https://issues.rudder.io/issues/6012[#6012])

==== Architecture - Refactoring

* Delete no more used test files in rudder-core
(https://issues.rudder.io/issues/5990[#5990])

=== Bug fixes

==== API

* Fixed: With the API, it is possible to set a Group with no criteria
(https://issues.rudder.io/issues/3767[#3767])

==== Techniques - Sys & init promis

* Fixed: Rudder crons sends too much mails
(https://issues.rudder.io/issues/5922[#5922])
* Fixed: Rudder agent refuses to update promises when its hostname is
uppercase (https://issues.rudder.io/issues/5772[#5772])
* Fixed: Policy Server UUID in /var/rudder/tmp
(https://issues.rudder.io/issues/2443[#2443])
* Fixed: Inventory file name never change
(https://issues.rudder.io/issues/725[#725])

==== Logging

* Fixed: Eventlogs to track node modification are missing
(https://issues.rudder.io/issues/5986[#5986])
* Fixed: Eventlogs for global frequency modification are missing
(https://issues.rudder.io/issues/5985[#5985])
* Fixed: Eventlogs to track global hearbeat change is missing
(https://issues.rudder.io/issues/5837[#5837])

==== Webapp - Config management

* Fixed: Change request are not migrated to fileformat 6
(https://issues.rudder.io/issues/6001[#6001])
* Fixed: Recent changes graphe is too wide the first time rule details
is opened (https://issues.rudder.io/issues/5904[#5904])
* Fixed: Directive stays selected in Directives tree even after other
item has been selected and displayed
(https://issues.rudder.io/issues/5887[#5887])
* Fixed: A warning should be displayed when migrating directive
(https://issues.rudder.io/issues/5708[#5708])
* Fixed: The directive form error handling is broken
(https://issues.rudder.io/issues/5560[#5560])

==== Vagrant integration

* Fixed: Improve rudder-vagrant README
(https://issues.rudder.io/issues/5131[#5131])

==== Documentation

* Fixed: The screenshots in 3.0 documentation are not up to date anymore
(https://issues.rudder.io/issues/5927[#5927])

==== Miscellaneous

* Fixed: Typo in node API documentation titles
(https://issues.rudder.io/issues/5953[#5953])
* Fixed: The available api versions are not listed
(https://issues.rudder.io/issues/5737[#5737])
* Fixed: Add missing include parameter for node API
(https://issues.rudder.io/issues/5502[#5502])
* Fixed: Demo data is deprecated
(https://issues.rudder.io/issues/5202[#5202])
* Fixed: Add missing examples on Node and Parameters
(https://issues.rudder.io/issues/4082[#4082])

==== Webapp - Administration

* Fixed: Frequency displayed for agent run schedule is missing leading
0s (ex: 4:0 instead of 04:00)
(https://issues.rudder.io/issues/5789[#5789])
* Fixed: It is not possible to add API account in Rudder 3.0
(https://issues.rudder.io/issues/5784[#5784])

==== Webapp - Display, home page

* Fixed: Typo in ``Sucess'' in new reporting
(https://issues.rudder.io/issues/5886[#5886])

==== Techniques

* Fixed: Missing ; in rpmPackageInstallation V7.0
(https://issues.rudder.io/issues/5932[#5932])
* Fixed: filesPermissions recursion applied although not configured
(https://issues.rudder.io/issues/5747[#5747])
* Fixed: Add missing changelogs for motd and ssh techniques
(https://issues.rudder.io/issues/5433[#5433])
* Fixed: The `Hosts settings' Technique should validate the IP address
(https://issues.rudder.io/issues/1925[#1925])

==== System integration

* Fixed: Tests on rudder-techniques are (wrongly) failing on
rudder_stdlib_core.st
(https://issues.rudder.io/issues/5999[#5999])
* Fixed: Synchronize rudder-agent-thin patches with rudder-agent
(https://issues.rudder.io/issues/5941[#5941])
* Fixed: URL in rudder-metrics-reporting points to a redirect
(https://issues.rudder.io/issues/5906[#5906])
* Fixed: rudder-metrics-reporting is relying on local CA bundles to
validate https
(https://issues.rudder.io/issues/5903[#5903])

==== Architecture - Dependencies

* Fixed: Update build pluing to support Java 7
(https://issues.rudder.io/issues/6010[#6010])

==== Webapp - Config management

* Fixed: The command to reload the server after promises generation
fails when killall is not available
(https://issues.rudder.io/issues/5825[#5825])

==== Webapp - Reporting

* Fixed: If a node had a date in the future, but returned to current
time, the reporting will always be invalid (until it catches up with the
future date) (https://issues.rudder.io/issues/6005[#6005])
* Fixed: Javascript alert when trying to see the reports details
(https://issues.rudder.io/issues/5993[#5993])

==== Webapp - Node management

* Fixed: Null pointer exception when displaying the inventory of a
pending node (https://issues.rudder.io/issues/5933[#5933])
* Fixed: In the query based search in multi-server excluding policy
server only exclude the web server
(https://issues.rudder.io/issues/5648[#5648])
* Fixed: Search Nodes: Search button grayed-out after search
(https://issues.rudder.io/issues/4643[#4643])

==== Architecture - Refactoring

* Fixed: SQL definition file uses varchar, but it should use only text
(https://issues.rudder.io/issues/6026[#6026])

=== Release notes

This software is in beta status and contains several new features but we
have tested it and believe it to be free of any critical bugs. The use
on production systems is not encouraged at this time and is at your own
risk. However, we do encourage testing, and welcome all and any
feedback!

== Rudder 3.0.0~beta1 (2014-12-01)

=== Changes

==== Webapp - Display, home page

* Global redesign of Rudder web interface
(https://issues.rudder.io/issues/5537[#5537])
* Replace Rudder `home page' by an informative dashboard
(https://issues.rudder.io/issues/1212[#1212])

==== Webapp - Config management

* Add a `changes only' compliance mode, only reporting changes on
systems (https://issues.rudder.io/issues/5293[#5293])
* Do not display reporting on overriden `unique' Directives
(https://issues.rudder.io/issues/5899[#5899])

==== Rudder agent CLI

* Add a command line interface for Rudder agent
(https://issues.rudder.io/issues/5690[#5690])

==== Webapp - Node management

* Customize Nodes by adding attribute on them
(https://issues.rudder.io/issues/5506[#5506])
* Add a filter on group tree
(https://issues.rudder.io/issues/5833[#5833])

==== Techniques

* Rewrite techniques so they all use ncf report methods
(https://issues.rudder.io/issues/5305[#5305])
* Make environment variables accessible as parameter in all Techniques
(https://issues.rudder.io/issues/5449[#5449])
* Add a ``deprecated'' attribute and notice for Technique version
(https://issues.rudder.io/issues/5610[#5610])
* Adapt Techniques so they use available init system on each Node
(https://issues.rudder.io/issues/3828[#3828])

==== Packaging

* Update to CFEngine 3.6.3 rc
(https://issues.rudder.io/issues/5858[#5858])
* RHEL/CentOS 7 packages
(https://issues.rudder.io/issues/5469[#5469])
* Relay server package
(https://issues.rudder.io/issues/1858[#1858])

==== System integration

* Cleanup send_clean.sh in Rudder agent tools
(https://issues.rudder.io/issues/5691[#5691])
* Replace complex cron one-liner with one script call
(https://issues.rudder.io/issues/4711[#4711])

==== Inventory (webapp, Fusion)

* Report ``Docker'' machine type in inventory
(https://issues.rudder.io/issues/5897[#5897])

==== ncf-builder integration

* Enhance detection of ncf based techniques in Rudder
(https://issues.rudder.io/issues/5895[#5895])
* Auto add/remove ncf Technique to Rudder techniques
(https://issues.rudder.io/issues/5670[#5670])

==== Webapp - CFEngine integration

* Optionnal variables should not be nulled (if they are not system
variables) (https://issues.rudder.io/issues/3014[#3014])

==== Logging

* Add a logger to trace webapp bootstrap actions
(https://issues.rudder.io/issues/5894[#5894])

==== Documentation

* Update rudder documentation version to 3.0
(https://issues.rudder.io/issues/5896[#5896])

==== Performance and scalability

* Remove default webapp from rudder-jetty
(https://issues.rudder.io/issues/5898[#5898])
* Send anonymous metrics
(https://issues.rudder.io/issues/5809[#5809])

==== Architecture - Refactoring

* Normalize our SQL definition file
(https://issues.rudder.io/issues/5893[#5893])
* Clean up all sources to use a double-space indentation convention
(https://issues.rudder.io/issues/5362[#5362])

==== Architecture - Dependencies

* Drop support for Java 6
(https://issues.rudder.io/issues/5664[#5664])
* Update dependencies and version to 3.0.0
(https://issues.rudder.io/issues/5249[#5249])

=== Bug fixes

==== Packaging

* Fixed: Various packaging fixes
(https://issues.rudder.io/issues/5849[#5849])

==== System integration

* Fixed: Upgrading rudder-inventory-ldap between two major OS versions
makes slapd unable to operate because of BerkeleyDB
(https://issues.rudder.io/issues/5575[#5575])
* Fixed: Syslog configuration on agent can conflict with loghosts
(https://issues.rudder.io/issues/5773[#5773])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Andrew Cranson
* Florian Heigl
* Lionel le Folgoc

This software is in beta status and contains several new features but we
have tested it and believe it to be free of any critical bugs. The use
on production systems is not encouraged at this time and is at your own
risk. However, we do encourage testing, and welcome all and any
feedback!
