= Change logs for Rudder 2.11

Rudder 2.11 has reached End of Life the 10th September 2016. This
version is codenamed ``**Perahu**''.

This page provides a summary of changes for each version. Previous beta
and rc versions are listed below for convenience.

*Main new features in Rudder 2.11:*

* Add a ``quick search'' box for nodes at the top right of the web
interface
* Data in Rudder web interface table can now be refreshed and are now
treated asynchronously as JSON
* Allow splitting Rudder server into independent role-based entities
* ncf-builder, a web interface to edit your techniques based on ncf
(http://www.ncf.io/)
* Upgrade rudder-agent versions: CFEngine 3.6, Fusion Inventory 2.3.6
* Compress inventories before sending to the server using gzip
* Add links to Directives in the Rule page
* Add logs of package install actions for debug
* Make writing reports in all.log configurable from Rudder
administration page
* Make promise generation faster: Optimization on variable lookup
* Default account has changed, now use ``admin'' with password ``admin''
to connect

*Installing, upgrading and testing*

Documentation:

* Install:
https://www.rudder-project.org/doc-2.11/_install_rudder_server.html
* Upgrade: https://www.rudder-project.org/doc-2.11/_upgrade_rudder.html

The Download Links are available here:
https://www.rudder-project.org/site/get-rudder/downloads/.

We also recommend using the
https://github.com/Normation/rudder-vagrant[Rudder Vagrant] config if
you want a quick and easy way to get an installation for testing.

*Operating systems supported*

This version provides packages for these operating systems:

* Rudder server: *Debian 7, RHEL/CentOS 6, SLES 11, Ubuntu 12.04, Ubuntu
14.04*
* Rudder agent: all of the above plus *Debian 5, Debian 6, RHEL/CentOS
3, RHEL/CentOS 5, Fedora 18, SLES 10, Ubuntu 10.04, Ubuntu 12.10*
* Rudder agent (non-free): *Windows Server 2008-2012* , *AIX 5-6-7*

== Rudder 2.11.24 (2016-08-30)

=== Changes

==== Web - Technique editor

* Add `Windows Server 2012 R2' as OS condition
(https://issues.rudder.io/issues/8071[#8071])

==== Documentation

* Generate a custom index page for the manual
(https://issues.rudder.io/issues/8488[#8488])

==== Techniques

* Download technique-files from Rudder website
(https://issues.rudder.io/issues/8853[#8853])

=== Bug fixes

==== Web - Config management

* Fixed: Unable to save/edit a directive via rudder web ui when
technique use an optional SELECT field
(https://issues.rudder.io/issues/8874[#8874])
* Fixed: Typo in cf-clerk logs
(https://issues.rudder.io/issues/8823[#8823])
* Fixed: When there is an error in a directive form, the target rule is
unchecked (https://issues.rudder.io/issues/8696[#8696])

==== Web - UI & UX

* Fixed: Cannot see rule details when you have read_only role
(https://issues.rudder.io/issues/8878[#8878])
* Fixed: When no editing rights are given to Groups, you drag an drop
them between categories
(https://issues.rudder.io/issues/8863[#8863])
* Fixed: ``Update techniques now'' button on the techniques screen is
too small (https://issues.rudder.io/issues/8616[#8616])

==== Web - Technique editor

* Fixed: New method calls are considered valid, although they are empty
which leads to error when validated via API
(https://issues.rudder.io/issues/8829[#8829])
* Fixed: Warn when the string length reaches the maximum value supported
by the agent (https://issues.rudder.io/issues/8261[#8261])
* Fixed: ncf still loads mp.autofocus module that was deleted!
(https://issues.rudder.io/issues/8793[#8793])

==== Documentation

* Fixed: Safe setup of the Rudder repo in the manual
(https://issues.rudder.io/issues/8864[#8864])

==== Techniques

* Fixed: ncf template methods do not empty file before editing it
(https://issues.rudder.io/issues/8843[#8843])

==== Initial promises & sys tech

* Fixed: Typo in system techniques reports
(https://issues.rudder.io/issues/8841[#8841])

==== Packaging

* Fixed: Do not depend on pam-devel on AIX
(https://issues.rudder.io/issues/8893[#8893])
* Fixed: Missing BuildRequires for rudder-agent : pam-devel
(https://issues.rudder.io/issues/8822[#8822])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre Anriot
* Avit Sidis

This is a bug fix release in the 2.11 `old-esr' series and therefore all
installations of 2.11.x should be upgraded when possible. The current
``esr'' release is now 3.1.* and there we advice to upgrade to the
latest 3.1.* version. When we release a new version of Rudder it has
been thoroughly tested, and we consider the release enterprise-ready for
deployment.

== Rudder 2.11.23 (2016-07-29)

=== Changes

==== Documentation

* Use release-info to generate the manual header at creation
(https://issues.rudder.io/issues/8450[#8450])

=== Bug fixes

==== Web - UI & UX

* Fixed: The API token creation popup is not centered
(https://issues.rudder.io/issues/8592[#8592])

==== Web - Nodes & inventories

* Fixed: Inventory messes up Last logged in user date when last user was
a reboot (https://issues.rudder.io/issues/8239[#8239])

==== Agent

* Fixed: command_execution_result with undefined code does not define
any classes on 2.11
(https://issues.rudder.io/issues/8723[#8723])

==== Initial promises & sys tech

* Fixed: Use the list-compatible-input equivalent on Windows system
(https://issues.rudder.io/issues/8553[#8553])
* Fixed: Update promises on Windows complains about setting ownership to
``root'' (https://issues.rudder.io/issues/8532[#8532])

==== Techniques

* Fixed: technique-files cannot find with a pattern on the whole
technique name
(https://issues.rudder.io/issues/8736[#8736])
* Fixed: lines after &endif& in techniques
(https://issues.rudder.io/issues/8647[#8647])
* Fixed: technique-metadata-sample.xml has invalid content
(https://issues.rudder.io/issues/8615[#8615])
* Fixed: UserManagement 6.0 fails to add user if the user’s default
group already exists
(https://issues.rudder.io/issues/8599[#8599])
* Fixed: Reporting for usermanagement in case of Policy to apply to this
account ``check only'' is missing the Password component report
(https://issues.rudder.io/issues/8585[#8585])
* Fixed: userManagement technique doesn’t do anything on Windows on
version 5 and 6
(https://issues.rudder.io/issues/8566[#8566])
* Fixed: checkGenericFile missing report when given non absolute path
(https://issues.rudder.io/issues/8405[#8405])
* Fixed: Add a technique check to make sure &endif& are followed by an
empty line (https://issues.rudder.io/issues/8646[#8646])

==== API

* Fixed: Inconsistent directive API parameters at creation
(https://issues.rudder.io/issues/8687[#8687])
* Fixed: NoSuchElementException when querying change request API
(https://issues.rudder.io/issues/8686[#8686])

==== Documentation

* Fixed: Documentation makefile fails to update git repos (git pull
before changing branch)
(https://issues.rudder.io/issues/8788[#8788])
* Fixed: Display link errors in doc build
(https://issues.rudder.io/issues/8727[#8727])
* Fixed: SLES Documentation has bad package name
(https://issues.rudder.io/issues/8624[#8624])
* Fixed: Left menu is sometimes broken when there is an anchor in the
link (https://issues.rudder.io/issues/8569[#8569])
* Fixed: Fix doc after ncf lib changes (same as #8522)
(https://issues.rudder.io/issues/8524[#8524])
* Fixed: Add a test for dead links on the doc
(https://issues.rudder.io/issues/8548[#8548])

==== Packaging

* Fixed: There is a non standard test in os detection
(https://issues.rudder.io/issues/8760[#8760])
* Fixed: Packages should remove their temporary files
(https://issues.rudder.io/issues/8744[#8744])
* Fixed: Update openssl to 1.0.1t on 2.11 branch
(https://issues.rudder.io/issues/8658[#8658])
* Fixed: rudder-apache-common.conf is not updated on upgrade with RPM
packages (https://issues.rudder.io/issues/8641[#8641])
* Fixed: Do not only build-depend on virtual packages
(https://issues.rudder.io/issues/8565[#8565])
* Fixed: Do not package technique tests
(https://issues.rudder.io/issues/8679[#8679])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky
* Florian Heigl

This is a bug fix release in the 2.11 `old-esr' series and therefore all
installations of 2.11.x should be upgraded when possible. The current
``esr'' release is now 3.1.* and there we advice to upgrade to the
latest 3.1.* version. When we release a new version of Rudder it has
been thoroughly tested, and we consider the release enterprise-ready for
deployment.

== Rudder 2.11.22 (2016-06-08)

=== Changes

==== Documentation

* Add tests for doc syntax
(https://issues.rudder.io/issues/8443[#8443])

=== Bug fixes

==== Web - Compliance & node report

* Fixed: Parallel traversal of new promises directories causes some
nodes promises to not be updated
(https://issues.rudder.io/issues/8427[#8427])

==== Web - Nodes & inventories

* Fixed: Change in group may be overwritten by dynamic group update
(https://issues.rudder.io/issues/8453[#8453])

==== Web - Config management

* Fixed: Many WARN messages after upgrade about JSON deserialisation
error (https://issues.rudder.io/issues/8288[#8288])

==== Techniques

* Fixed: Invalidation of previous package state and of package status
cache does not work on rpmPackageInstallation 5.0 5.1 6.0 6.1 7.0
(https://issues.rudder.io/issues/8421[#8421])
* Fixed: rpmPackageInstallation 7.0 uses the wrong version number for
it’s data file
(https://issues.rudder.io/issues/8419[#8419])
* Fixed: Missing reports in file and zypper techniques due to a syntax
error in reporting
(https://issues.rudder.io/issues/8403[#8403])

==== Initial promises & sys tech

* Fixed: On Centos6.6, rsyslog is always restarted
(https://issues.rudder.io/issues/8451[#8451])
* Fixed: failsafe sometimes produce rudder reports
(https://issues.rudder.io/issues/8422[#8422])
* Fixed: Reference to &TRACKINGKEY& in initial promises
(https://issues.rudder.io/issues/8415[#8415])
* Fixed: Remove unused variable in cf-serverd
(https://issues.rudder.io/issues/8392[#8392])
* Fixed: The component ``Check Technique library reloading file'' is
sometime a log and sometime a result
(https://issues.rudder.io/issues/8380[#8380])
* Fixed: Launching twice in a row a disabled agent make the agent runs
(https://issues.rudder.io/issues/7100[#7100])
* Fixed: The uuid in the promises and the uuid in
/opt/rudder/etc/uuid.hive may be out of sync, and chaos and sadness
follows (https://issues.rudder.io/issues/7091[#7091])

==== Documentation

* Fixed: Unclear message in the upgrade doc
(https://issues.rudder.io/issues/8440[#8440])

==== Packaging

* Fixed: stty does not handle no-tty input
(https://issues.rudder.io/issues/8426[#8426])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky
* Daniel Stan

This is a bug fix release in the 2.11 `old-esr' series and therefore all
installations of 2.11.x should be upgraded when possible. The current
``esr'' release is now 3.1.* and there we advice to upgrade to the
latest 3.1.* version. When we release a new version of Rudder it has
been thoroughly tested, and we consider the release enterprise-ready for
deployment.

== Rudder 2.11.21 (2016-06-01, Not announced)

That version was not released due to several bugs:
https://issues.rudder.io/issues/8423[#8423],
https://issues.rudder.io/issues/8427[#8427],
https://issues.rudder.io/issues/8430[#8430]

=== Changes

==== Web - Nodes & inventories

* Make page node details/search node less confusing
(https://issues.rudder.io/issues/7642[#7642])

==== Documentation

* Create an installation section in the documentation
(https://issues.rudder.io/issues/8233[#8233])
* Homogenize OS names in the doc
(https://issues.rudder.io/issues/8224[#8224])
* How to: Ensure a line is present in a file (and only one time!)
(https://issues.rudder.io/issues/8169[#8169])
* Integrate ncf generic methods reference into the doc
(https://issues.rudder.io/issues/7844[#7844])
* Add ``Troubleshooting'' section
(https://issues.rudder.io/issues/7711[#7711])

=== Bug fixes

==== Web - UI & UX

* Fixed: Typo in directive migration message ``an other''
(https://issues.rudder.io/issues/8289[#8289])
* Fixed: Broken links in the ``Support Desk'' box of the home page
(https://issues.rudder.io/issues/8110[#8110])
* Fixed: Some messages in the Settings page end with a comma
(https://issues.rudder.io/issues/8044[#8044])
* Fixed: Show seconds in Execution date at Technical Logs of Node
Details (https://issues.rudder.io/issues/7981[#7981])

==== Web - Config management

* Fixed: Node configuration cache is invalidated too often
(https://issues.rudder.io/issues/8246[#8246])

==== Techniques

* Fixed: permissions technique tries to set a group even when we do not
ask for it (https://issues.rudder.io/issues/8198[#8198])
* Fixed: It is not possible to use quotes in generic variable definition
values (https://issues.rudder.io/issues/8188[#8188])
* Fixed: Clear package caches when repairing a package repository
(https://issues.rudder.io/issues/8121[#8121])
* Fixed: The start at boot does not work in the openssh technique on
systemd OSes (https://issues.rudder.io/issues/8108[#8108])
* Fixed: Double reporting for group creation
(https://issues.rudder.io/issues/8100[#8100])
* Fixed: Avoid waiting on lock when calling yum
(https://issues.rudder.io/issues/6487[#6487])

==== System integration

* Fixed: Rudder jetty init script broken on CentOS 7
(https://issues.rudder.io/issues/8369[#8369])
* Fixed: rudder-slapd may break on upgrade when restarting on openVZ
(https://issues.rudder.io/issues/8210[#8210])
* Fixed: check-rudder-agent complains about not existing
policy-server.dat backup file
(https://issues.rudder.io/issues/8202[#8202])
* Fixed: ACL Posix on Git repos
(https://issues.rudder.io/issues/8065[#8065])
* Fixed: Disable ldap logging on non existing indexes
(https://issues.rudder.io/issues/7667[#7667])
* Fixed: Messages can be dropped on the node, resulting in Unknown
reports on the Web Interface
(https://issues.rudder.io/issues/6421[#6421])
* Fixed: promises can become invalid if copies fail rendering the agent
unusable (https://issues.rudder.io/issues/5650[#5650])

==== Server components

* Fixed: Apache config does not get cleaned up after removal of
rudder-webapp (https://issues.rudder.io/issues/8232[#8232])
* Fixed: rudder-apache gets added multiple times to apache config
(https://issues.rudder.io/issues/8231[#8231])

==== Packaging

* Fixed: Spurious message ``grep: /etc/sysconfig/apache2: No such file
or directory'' in RPM install for rudder-webapp
(https://issues.rudder.io/issues/8371[#8371])
* Fixed: ncf package asks about replacing dist config file during
upgrade (https://issues.rudder.io/issues/8286[#8286])
* Fixed: When we install rudder-agent after having removing it, the uuid
is not restored on RPM-based systems
(https://issues.rudder.io/issues/6468[#6468])

==== Initial promises & sys tech

* Fixed: Can’t stat file `/opt/rudder/bin/cf-hub' on `localhost' in
files.copy_from promise
(https://issues.rudder.io/issues/8397[#8397])
* Fixed: check-techniques script doesn’t properly exit non-zero on
errors (https://issues.rudder.io/issues/8386[#8386])
* Fixed: Error in cf-serverd for allowing remote access to cf-agent
binary (https://issues.rudder.io/issues/8374[#8374])
* Fixed: logrotate promise for CFEngine Enterprise agents
(https://issues.rudder.io/issues/8340[#8340])
* Fixed: Invalid path for rudder_ncf in Windows
(https://issues.rudder.io/issues/8338[#8338])
* Fixed: Duplicate lines in body classes success in update.cf in initial
promises (https://issues.rudder.io/issues/8309[#8309])
* Fixed: Use variables for path to cf-agent in system Techniques to work
on Windows (https://issues.rudder.io/issues/8307[#8307])
* Fixed: Disable Repeated message reduction or reports may be lost on
the relay (https://issues.rudder.io/issues/8264[#8264])
* Fixed: Error message about setgid on ncf.conf
(https://issues.rudder.io/issues/8181[#8181])
* Fixed: Missing reporting in ``check postgresql process'' on rudder-db
role (https://issues.rudder.io/issues/8178[#8178])
* Fixed: Crontab promise with the Windows agent
(https://issues.rudder.io/issues/8161[#8161])
* Fixed: Rudder agent connect at each runs to its policy server to get
its server uuid
(https://issues.rudder.io/issues/7638[#7638])
* Fixed: Extra carriage return in policy_server.dat inventory failure
(https://issues.rudder.io/issues/7328[#7328])

==== Architecture - Internal libs

* Fixed: Examples in ldap-inventory are not real life examples
(https://issues.rudder.io/issues/8236[#8236])

==== Documentation

* Fixed: Documentation wrongly states default report TTL is 30 days
(https://issues.rudder.io/issues/8297[#8297])
* Fixed: Documentation no longer clearly tells user to upgrade
Techniques (https://issues.rudder.io/issues/8294[#8294])
* Fixed: Invalid documentation on how to use rudder global parameters in
Technique editor
(https://issues.rudder.io/issues/8278[#8278])
* Fixed: Make clearer what the goal of Scala-ldap is in readme
(https://issues.rudder.io/issues/8275[#8275])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alexandre Anriot
* Jean Cardona
* Janos Mattyasovszky
* David Svejda

This is a bug fix release in the 2.11 `old-esr' series and therefore all
installations of 2.11.x should be upgraded when possible. The current
``esr'' release is now 3.1.* and there we advice to upgrade to the
latest 3.1.* version. When we release a new version of Rudder it has
been thoroughly tested, and we consider the release enterprise-ready for
deployment.

== Rudder 2.11.20 (2016-04-18)

=== Changes

==== Web - Nodes & inventories

* Exit sending inventory to rudder-webapp if the queue is full
(https://issues.rudder.io/issues/7291[#7291])

=== Bug fixes

==== Web - Maintenance

* Fixed: web interface login: able to log in with valid ldap account but
no matching rudder-users.xml entry
(https://issues.rudder.io/issues/8085[#8085])

==== Techniques

* Fixed: Missing reporting in UserManagement 6.0 when creating a user
(https://issues.rudder.io/issues/8079[#8079])

==== Performance and scalability

* Fixed: Java OOM during Java’s log migration
(https://issues.rudder.io/issues/7524[#7524])

==== Windows agent

* Fixed: On Windows, a file c:\Program is created
(https://issues.rudder.io/issues/8149[#8149])

==== Server components

* Fixed: node-to-relay fails to reload policy when proxy is set
(https://issues.rudder.io/issues/8054[#8054])
* Fixed: Compress ldif backups
(https://issues.rudder.io/issues/6714[#6714])][#7900]])

==== Initial promises & sys tech

* Fixed: Do not backup modified promise files and encrypt ncf/local
transfer (https://issues.rudder.io/issues/8159[#8159])

==== Architecture - Refactoring

* Fixed: Bad logs for event log migration since #8085
(https://issues.rudder.io/issues/8124[#8124])
* Remove trailing space in code file that make merge conflicts
(https://issues.rudder.io/issues/8126[#8126])

==== Architecture - Internal libs

* Fixed: java.util.regex.PatternSyntaxException: Unexpected internal
error near index 1 on windows
(https://issues.rudder.io/issues/7935[#7935])

==== Documentation

* Fixed: API documentation for compliance needs JSON prettified
(https://issues.rudder.io/issues/7900[#7900])

==== Web - Nodes & inventories

* The Motherboard UUID doesn’t appear on the inventory on a Node
(https://issues.rudder.io/issues/3749[#3749])

==== Documentation

* Mark 3.1 as ESR in the doc header
(https://issues.rudder.io/issues/8059[#8059])
* Import doc from foswiki about parametrized variable in the doc
(https://issues.rudder.io/issues/7836[#7836])
* Reorganize the introduction
(https://issues.rudder.io/issues/7818[#7818])

==== Techniques

* Add an option for MOTD Technique to display MOTD before login
(https://issues.rudder.io/issues/7983[#7983])
* New Technique to import a GPG Key into RPM
(https://issues.rudder.io/issues/6756[#6756])

=== Bug fixes

==== API

* Fixed: Changing Directive version via API does not set default values,
and return wrong parameters
(https://issues.rudder.io/issues/7979[#7979])

==== Web - UI & UX

* Fixed: Typo in webapp message when policy generation failed
(https://issues.rudder.io/issues/8094[#8094])
* Fixed: Tooltip on Rule categories may display after selecting Rule
(https://issues.rudder.io/issues/8086[#8086])

==== Web - Nodes & inventories

* Fixed: Missing error message in node acceptation when there is a
problem with getting authorized networks
(https://issues.rudder.io/issues/8016[#8016])
* Fixed: Debian Jessie, on VMWare, are wrongly considered as
``Physical'' machine
(https://issues.rudder.io/issues/7204[#7204])
* Fixed: Rudder doesn’t store and display the IPV6 of the nodes
(https://issues.rudder.io/issues/7136[#7136])
* Fixed: Order of button on ``accept nodes in rudder'' is the exact
opposite of the rest of the webapp
(https://issues.rudder.io/issues/6722[#6722])
* Fixed: Allow to make a group with only 32bits or 64bits nodes
(https://issues.rudder.io/issues/2543[#2543])

==== Documentation

* Fixed: Broken link in the manual
(https://issues.rudder.io/issues/7817[#7817])
* Fixed: Document that when we reduce the run interval of nodes, ``no
data'' may be wrongly reported
(https://issues.rudder.io/issues/6231[#6231])

==== Packaging

* Fixed: rudder-upgrade takes too long
(https://issues.rudder.io/issues/7987[#7987])
* Fixed: Backup and restore policy_server.dat like we do with uuid.hive
file (https://issues.rudder.io/issues/7901[#7901])
* Fixed: Rudder agent tries sending an inventory during update
(https://issues.rudder.io/issues/7881[#7881])
* Fixed: rudder-upgrade does not make some check on remote sql in case
of distributed setup
(https://issues.rudder.io/issues/7849[#7849])
* Fixed: Rudder init script kill all agent on Open VZ (or similar
system) (https://issues.rudder.io/issues/4499[#4499])

==== Initial promises & sys tech

* Fixed: gzip can stop rudder agent when compressing log files
(https://issues.rudder.io/issues/7985[#7985])
* Fixed: System technique cannot compress inventories
(https://issues.rudder.io/issues/7930[#7930])
* Fixed: Unexpected reports on ``Check jetty process'' component of
system techniques
(https://issues.rudder.io/issues/7821[#7821])
* Fixed: Rudder inventory don’t produce error report
(https://issues.rudder.io/issues/7785[#7785])
* Fixed: date of report may be invalid on windows
(https://issues.rudder.io/issues/7741[#7741])

==== System integration

* Fixed: rudder-init broken on SLES
(https://issues.rudder.io/issues/7991[#7991])
* Fixed: Missing useful logger in logger file
(https://issues.rudder.io/issues/7910[#7910])
* Fixed: Errors with apache on ubuntu 12.04
(https://issues.rudder.io/issues/6763[#6763])

==== Server components

* Fixed: Rudder password are not properly protected
(https://issues.rudder.io/issues/8096[#8096])
* Fixed: Allow disable of git-autocommit of system policy on Update
(https://issues.rudder.io/issues/7222[#7222])
* Fixed: Node not included in dynamic group due to openldap bug with
modrdn not showing node children
(https://issues.rudder.io/issues/6780[#6780])

==== Techniques

* Fixed: When we manage twice a same package in rpm package management,
we don’t get the second report
(https://issues.rudder.io/issues/8034[#8034])
* Fixed: Incomplete reporting in service management
(https://issues.rudder.io/issues/8032[#8032])
* Fixed: Script check-techniques.sh fails on first error
(https://issues.rudder.io/issues/8012[#8012])
* Fixed: The script check-techniques.sh checks old techniques when the
parent directory contains a version number
(https://issues.rudder.io/issues/8010[#8010])
* Fixed: Fix invalid metadata.xml statement in clockSettings 3.1
(https://issues.rudder.io/issues/8009[#8009])
* Fixed: Wrong reporting in servicesManagement 3.0
(https://issues.rudder.io/issues/7975[#7975])
* Fixed: ``Download a file from shared folder'' technique doesn’t have
an explicit default value for ``Compare method'' (was mtime, now digest)
(https://issues.rudder.io/issues/7962[#7962])
* Fixed: Missing Timezones from clockConfiguration
(https://issues.rudder.io/issues/7489[#7489])
* Fixed: Missing ``don’t change'' password hash type in userManagement
(https://issues.rudder.io/issues/6493[#6493])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Janos Mattyasovszky

This is a bug fix release in the 2.11 `old-esr' series and therefore all
installations of 2.11.x should be upgraded when possible. The current
``esr'' release is now 3.1.* and there we advice to upgrade to the
latest 3.1.* version. When we release a new version of Rudder it has
been thoroughly tested, and we consider the release enterprise-ready for
deployment.

== Rudder 2.11.18 (2016-01-21)

=== Changes

==== Agent

* rudder-agent should trigger a new inventory after upgrade
(https://issues.rudder.io/issues/7620[#7620])

==== Techniques

* Add test for rudder-techniques to ensure removed deprecated techniques
don’t come back in an erroneous merge
(https://issues.rudder.io/issues/7504[#7504])

==== Documentation

* Document the zypper segfault when installing Rudder packages locally
(https://issues.rudder.io/issues/7652[#7652])
* Document AIX support in Rudder manual
(https://issues.rudder.io/issues/7650[#7650])
* Document nofiles dependency for syslog/tcp on master and relays
(https://issues.rudder.io/issues/7220[#7220])

==== Architecture - Refactoring

* Remove deprecated package rudder-policy-templates
(https://issues.rudder.io/issues/7723[#7723])
* Make NodeInfo more dependant on Node
(https://issues.rudder.io/issues/7634[#7634])
* Change AGPL to GPL in rudder-plugin-external-node-information
(https://issues.rudder.io/issues/7576[#7576])

=== Bug fixes

==== Web - Config management

* Fixed: Promise generation never finishes if jetty is restarted
mid-generation
(https://issues.rudder.io/issues/7814[#7814])
* Fixed: Too long directive name breaks directive serialization
(https://issues.rudder.io/issues/7766[#7766])

==== Web - UI & UX

* Fixed: Filter keeps applied between Rules Tables within Directives
page (https://issues.rudder.io/issues/7754[#7754])
* Fixed: Typo in AGENT RUN SCHEDULE description
(https://issues.rudder.io/issues/7749[#7749])

==== Web - Nodes & inventories

* Fixed: Only one system group is displayed in node details
(https://issues.rudder.io/issues/7061[#7061])

==== Web - Maintenance

* Fixed: Jetty cache files in /tmp directory are removed by the OS
tmpwatch cron job, preventing access to the application
(https://issues.rudder.io/issues/4473[#4473])

==== Agent

* Fixed: rudder-agent does not stop on network error during file copy,
which can lead to file deletions when purging is enabled
(https://issues.rudder.io/issues/7629[#7629])

==== Documentation

* Fixed: Fix use links containing emphasized keywords in manual
(https://issues.rudder.io/issues/7812[#7812])
* Fixed: The size of one image is not correctly recognized in the doc
(https://issues.rudder.io/issues/7713[#7713])
* Fixed: Some titles broken in the documentation
(https://issues.rudder.io/issues/7551[#7551])
* Fixed: Wrong anchors in Rudder API doc
(https://issues.rudder.io/issues/6694[#6694])

==== System integration

* Fixed: Firefox stalls after TLS handshake on self signed certificate
with a missing contact email
(https://issues.rudder.io/issues/7800[#7800])

==== Packaging

* Fixed: Test for non-applying patches on rudder-jetty and
rudder-agent-thin is broken
(https://issues.rudder.io/issues/7803[#7803])
* Fixed: Backport fixes for openldap memory leak in our package
(https://issues.rudder.io/issues/7801[#7801])
* Fixed: rudder-upgrade edits the wrong ncf.conf file causing transitory
invalid promises during upgrades
(https://issues.rudder.io/issues/7794[#7794])
* Fixed: rudder-init overwrite its logs
(https://issues.rudder.io/issues/7776[#7776])

==== Initial promises & sys tech

* Fixed: initial promises don’t create
/var/rudder/configuration-repository/ncf/ncf.conf
(https://issues.rudder.io/issues/7810[#7810])
* Fixed: inventory sent file timestamp not updated in normal run (system
techniques) (https://issues.rudder.io/issues/7782[#7782])
* Fixed: Fix permissions of the rudder tools in the repo
(https://issues.rudder.io/issues/7697[#7697])
* Fixed: check-rsyslog-version is missing on the nodes
(https://issues.rudder.io/issues/7680[#7680])
* Fixed: Non quiet curl calls on root and relay servers
(https://issues.rudder.io/issues/7678[#7678])
* Fixed: Permissions of rudder tools are not preserved on relays
(https://issues.rudder.io/issues/7644[#7644])
* Fixed: Unexpected reports on ``Log system for reports'' component of
system techniques
(https://issues.rudder.io/issues/7619[#7619])
* Fixed: Rudder agent simulates an aptitude full-upgrade during each run
(https://issues.rudder.io/issues/7141[#7141])

==== Techniques

* Fixed: Invalid reporting on windows for clockconfiguration if Hardware
Clock is not set
(https://issues.rudder.io/issues/7739[#7739])
* Fixed: Technique copyGitFile can send success AND error reports on
post-hook execution and lead to unexpected reports
(https://issues.rudder.io/issues/7624[#7624])
* Fixed: Unexpected reports using ``rpmPackageInstallation'' technique
(https://issues.rudder.io/issues/7623[#7623])
* Fixed: Technique ``Name resolution'': Regexp to check value of
Nameserver does not allow the use of variable
(https://issues.rudder.io/issues/3741[#3741])
* Fixed: Package management for RHEL / CentOS / SuSE / RPM systems: The
number of reports about ZMD is incorrect
(https://issues.rudder.io/issues/3478[#3478])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Florian Heigl
* Alex Tkachenko

This is a bug fix release in the 2.11 `esr' series and therefore all
installations of 2.11.x should be upgraded when possible. When we
release a new version of Rudder it has been thoroughly tested, and we
consider the release enterprise-ready for deployment.

== Rudder 2.11.17 (2015-12-10)

=== Changes

==== Packaging

* Update OpenSSL version to latest release
(https://issues.rudder.io/issues/7368[#7368])

=== Bug fixes

==== API

* Fixed: API Parameters create ``overridable'' boolean check doesn’t
work (https://issues.rudder.io/issues/6695[#6695])

==== Web - Config management

* Fixed: Read technique access does not give access to techniques
(https://issues.rudder.io/issues/7514[#7514])
* Fixed: Promises are not regenerated during upgrade
(https://issues.rudder.io/issues/7557[#7557])
* Fixed: Make possible to delete ANY active technique
(https://issues.rudder.io/issues/7536[#7536])

==== Web - Nodes & inventories

* Fixed: Tag FULL_NAME missing from SLES12 inventory
(https://issues.rudder.io/issues/7559[#7559])
* Fixed: Inventory  content differs from hostname –fqdn and may lead to
unauthorised nodes
(https://issues.rudder.io/issues/7031[#7031])

==== Web - UI & UX

* Fixed: Clone rule window too small
(https://issues.rudder.io/issues/7397[#7397])

==== Server components

* Fixed: promises are not regenerated when a node is transformed into a
relay (https://issues.rudder.io/issues/7301[#7301])
* Fixed: slapd core dumps on 1TB RAM
(https://issues.rudder.io/issues/7295[#7295])

==== Agent

* Fixed: rudder-agent repository on GitHub does not have a license
(https://issues.rudder.io/issues/7394[#7394])
* Fixed: If using proxmox, process management fails due to bad options
used on vzps (https://issues.rudder.io/issues/7423[#7423])
* Fixed: check-rudder-agent silently fails if namespaces are not
supported (https://issues.rudder.io/issues/7335[#7335])

==== Documentation

* Fixed: Add a section about ncf-builder and its integration wihin
Rudder (https://issues.rudder.io/issues/6305[#6305])

==== Techniques

* Fixed: Technique ``Clock settings'' uses Europe/Paris as China’s
timezone (technique version 3.0)
(https://issues.rudder.io/issues/7501[#7501])
* Fixed: OpenSSH server configuration does not reload configurations
(https://issues.rudder.io/issues/7479[#7479])
* Fixed: Create a new version of download file from the shared folder
that would allow to set the suid and gid to multiple file
(https://issues.rudder.io/issues/7379[#7379])

==== Initial promises & sys tech

* Fixed: Use whole path to binaries in cron from check-rudder-agent on
AIX (https://issues.rudder.io/issues/7525[#7525])
* Fixed: Use of nonexistent class cfengine_community makes failsafe.cf
not copy CFEngine binaries to /var/rudder
(https://issues.rudder.io/issues/7499[#7499])
* Fixed: ``Update'' component of common technique sometimes return
unexpected status and has incomplete reporting
(https://issues.rudder.io/issues/6648[#6648])
* Fixed: Syslog fails to restart due bad line in syslog-ng.conf
(https://issues.rudder.io/issues/7389[#7389])
* Fixed: Initial promises and techniques set group to ``root'' rather
than 0, breaking non-Linux OSes
(https://issues.rudder.io/issues/7476[#7476])
* Fixed: New version of ncf_conf.cache may not be properly updated on
nodes after an upgrade
(https://issues.rudder.io/issues/7452[#7452])
* Fixed: internal security check always assume that the node is a
community one (https://issues.rudder.io/issues/7430[#7430])
* Fixed: Agent cannot replace file per folder when copying promises, and
it may lock agent with invalid promises
(https://issues.rudder.io/issues/7190[#7190])

==== System integration

* Fixed: The rudder-agent cron on AIX uses if then, which makes some
security test fails
(https://issues.rudder.io/issues/7508[#7508])
* Fixed: JVM 8.0: warning about ``Ignoring option PermSize=128m; support
was removed in 8.0''
(https://issues.rudder.io/issues/7345[#7345])
* Fixed: rudder-agent and rudder-slapd init scripts may fail to stop
services if killall is missing or misbehaving
(https://issues.rudder.io/issues/7515[#7515])
* Fixed: /etc/init.d/rudder-jetty fails to stop jetty if it’s PID file
is missing (https://issues.rudder.io/issues/7469[#7469])
* Fixed: cf-execd is running twice after a reboot or after running
rudder-agent twice
(https://issues.rudder.io/issues/7420[#7420])
* Fixed: Initial git commit during package installation is too verbose
(https://issues.rudder.io/issues/7419[#7419])
* Fixed: Rudder OpenLDAP Authentication sans ipv4 localhost
(https://issues.rudder.io/issues/4922[#4922])

==== Packaging

* Fixed: Some patches silently fail to apply
(https://issues.rudder.io/issues/7556[#7556])
* Fixed: Modify the copy of ncf.conf instead of the original
(https://issues.rudder.io/issues/7445[#7445])
* Fixed: After a fresh install on Centos, the Rudder server web
interface does not work
(https://issues.rudder.io/issues/7395[#7395])
* Fixed: mvn –quiet is too quiet
(https://issues.rudder.io/issues/7371[#7371])
* Fixed: make wget quiet during build
(https://issues.rudder.io/issues/7370[#7370])
* Fixed: Make maven quiet during build
(https://issues.rudder.io/issues/7317[#7317])
* Fixed: rudder-inventory-ldap and rudder-jetty don’t stop their
services on uninstall and rudder-slapd can fail to restart on upgrade
(https://issues.rudder.io/issues/7516[#7516])
* Fixed: rudder-upgrade fails when *re*installing Rudder
(https://issues.rudder.io/issues/7510[#7510])
* Fixed: Script never terminate when they run rudder-jetty init script
(https://issues.rudder.io/issues/7492[#7492])
* Fixed: The package leave a temporary directory mehind
(https://issues.rudder.io/issues/7391[#7391])
* Fixed: All reports are missing (totally orange) for a node due to
multiple cf-execd processes
(https://issues.rudder.io/issues/7338[#7338])

==== Techniques - Tests

* Fixed: rudder-techniques test script ``technique-files'' doesn’t list
promises.cf and failsafe.cf in initial-promises
(https://issues.rudder.io/issues/7496[#7496])
* Fixed: rudder-techniques test script ``technique-files'' lists files
in .git (https://issues.rudder.io/issues/7495[#7495])

==== Architecture - Refactoring

* Fixed: Correct a warning in rudder compilation
(https://issues.rudder.io/issues/7356[#7356])
* Fixed: We are using AGPL in place of GPL
(https://issues.rudder.io/issues/7546[#7546])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Layne Breitkreutz
* Dennis Cabooter
* Steeve Chailloux
* David Durieux
* Fabrice Flore-Thébault
* Janos Mattyasovszky

This is a bug fix release in the 2.11 `esr' series and therefore all
installations of 2.11.x should be upgraded when possible. When we
release a new version of Rudder it has been thoroughly tested, and we
consider the release enterprise-ready for deployment.

== Rudder 2.11.16 (2015-10-27)

=== Changes

==== System & initial promises

 * Touch local file on inventory upload
https://issues.rudder.io/issues/7206[#7206])

=== Bug fixes

==== Web - Nodes & inventories

* Fixed: Link from node/directive list to node detail is broken on
Firefox (https://issues.rudder.io/issues/7286[#7286])

==== Packaging

* Fixed: Maven never uses internal mirror
(https://issues.rudder.io/issues/7300[#7300])
* Fixed: Temporary files are not cleaned up after build
(https://issues.rudder.io/issues/7293[#7293])

==== System integration

* Fixed: zypper –version outputs on stderr
(https://issues.rudder.io/issues/7289[#7289])

==== Performance and scalability

* Fixed: RuleTargetTest.scala takes >40s where it should take 2s
(https://issues.rudder.io/issues/7303[#7303])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky

This is a bug fix release in the 2.11 `esr' series and therefore all
installations of 2.11.x should be upgraded when possible. When we
release a new version of Rudder it has been thoroughly tested, and we
consider the release enterprise-ready for deployment.

== Rudder 2.11.15 (2015-10-20)

=== Changes

=== Bug fixes

==== Web - Nodes & inventories

* Fixed: No service pack is reported when lsb_release is installed on
SLES (https://issues.rudder.io/issues/7205[#7205])

==== Techniques

* Fixed: Ssh key distribution cannot distribute several keys on one user
(https://issues.rudder.io/issues/7254[#7254])

==== Initial promises & sys tech

* Fixed: Network list for apache 2.4 is invalidly generated
(https://issues.rudder.io/issues/7268[#7268])
* Fixed: The daily cf-execd and cf-serverd restart should use SRC on AIX
(https://issues.rudder.io/issues/7274[#7274])
* Fixed: System technique’s curl should follow redirects
(https://issues.rudder.io/issues/7211[#7211])

==== System integration

* Fixed: check-rudder-agent faisl on an error while checking processes
(https://issues.rudder.io/issues/7243[#7243])

==== Packaging

* Fixed: Rudder agent doesn’t build with hardening flags
(https://issues.rudder.io/issues/7257[#7257])
* Fixed: Patch not applied on fusion inventory
(https://issues.rudder.io/issues/7241[#7241])

==== Server components

* Fixed: Root server’s apache config does not honor < 2.4 for webdav
(https://issues.rudder.io/issues/7267[#7267])

==== Performance and scalability

* Fixed: Writing promises should be parallelized
(https://issues.rudder.io/issues/7265[#7265])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Florian Heigl
* Janos Mattyasovszky

This is a bug fix release in the 2.11 `esr' series and therefore all
installations of 2.11.x should be upgraded when possible. When we
release a new version of Rudder it has been thoroughly tested, and we
consider the release enterprise-ready for deployment.

== Rudder 2.11.14 (2015-09-24)

=== Changes

==== Documentation

* Split the html documentation to improve readability and navigability
(https://issues.rudder.io/issues/6604[#6604])
* Improve rudder server requirements formatting
(https://issues.rudder.io/issues/7081[#7081])
* Improve the readability of the server installation section of the
manual (https://issues.rudder.io/issues/6603[#6603])
* Fixed: Document clearly technique upgrades
(https://issues.rudder.io/issues/7077[#7077])

=== Bug fixes

==== Initial promises & sys tech

* Fixed: The rudder server tries to send ``uuid.hive'' as an inventory
(https://issues.rudder.io/issues/6987[#6987])
* Fixed: System technique distributePolicy is not system and has two
system var section
(https://issues.rudder.io/issues/7138[#7138])
* Fixed: Promise copy is not convergent: if the copy is interrupted, it
will never recover
(https://issues.rudder.io/issues/7086[#7086])
* Fixed: If the agent schedule is not every 5 minutes, inventory may not
be sent anymore
(https://issues.rudder.io/issues/6718[#6718])

==== Web - Config management

* Fixed: Rules are not serialized correctly anymore
(https://issues.rudder.io/issues/7108[#7108])

==== Web - Compliance & node report

* Fixed: Agent schedule is not historised, so we can’t know what was the
agent run interval in the past
(https://issues.rudder.io/issues/7154[#7154])

==== Web - Technique editor

* Fixed: Read only role is not correctly interpreted in technique
editor. (https://issues.rudder.io/issues/7199[#7199])

==== Techniques

* Fixed: motd technique wrongly reports that it is incompatible with
windows (https://issues.rudder.io/issues/7153[#7153])

==== Packaging

* Fixed: issues with process management on physical hosting LXC
containers (https://issues.rudder.io/issues/7189[#7189])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Libra Linux

This is a bug fix release in the 2.11 `esr' series and therefore all
installations of 2.11.x should be upgraded when possible. When we
release a new version of Rudder it has been thoroughly tested, and we
consider the release enterprise-ready for deployment.

== Rudder 2.11.13 (2015-08-19)

=== Bug fixes

==== Web - Config management

* Fixed: System object (techniques, directives, rules, groups) must be
always enabled
(https://issues.rudder.io/issues/7064[#7064])
* Fixed: Editing a rule category remove it from Git - rule categories
disappear! (Ranärok ensues)
(https://issues.rudder.io/issues/6840[#6840])
* Fixed: Clear cache doesn’t regenerate expected reports
(https://issues.rudder.io/issues/7080[#7080])

==== Web - Compliance & node report

* Fixed: Reporting cannot be used when there is several component with
the same value and several messages
(https://issues.rudder.io/issues/7037[#7037])

==== Web - Nodes & inventories

* Fixed: If domain name is not set in resolv.conf, the inventory
generated is invalid
(https://issues.rudder.io/issues/7001[#7001])
* Fixed: Xen list parsed badly by FusionInventory, causing VCPU to be
counted badly (https://issues.rudder.io/issues/6754[#6754])
* Fixed: FusionInventory doesn’t provide the Rudder extension on other
platform than Linux
(https://issues.rudder.io/issues/6747[#6747])

==== Agent

* Fixed: If we ask to install a package in a version at least equal to
another, we get no report if the version installed is > than the one
requested (https://issues.rudder.io/issues/6996[#6996])
* Fixed: Migration from 2.10.x to 2.11.x on Debian may disable the agent
(https://issues.rudder.io/issues/7099[#7099] )

==== Techniques

* Fixed: aptPackageManagerSetting technique doesn’t work on Ubuntu
(https://issues.rudder.io/issues/6999[#6999])
* Fixed: Reporting on openssh server configuration technique is not
correct for port edition
(https://issues.rudder.io/issues/6942[#6942])

==== Initial promises & sys tech

* Fixed: Bad regexp in the cron for Rudder nova
(https://issues.rudder.io/issues/7014[#7014])
* Fixed: A report is missing on system techniques when cron needs to be
restartd (https://issues.rudder.io/issues/6660[#6660])
* Fixed: On Windows, Rudder specific inventories is not be added to
inventory with most version of CFEngine Enterprise
(https://issues.rudder.io/issues/7057[#7057])
* Fixed: When promises could have been updated, we still have the error
messages saying we couldn’t update promises
(https://issues.rudder.io/issues/7038[#7038])
* Fixed: When the nxlog configuration is changed on windows, service is
not restarted (https://issues.rudder.io/issues/7012[#7012])

==== Packaging

* Fixed: Some code is duplicated in debian postinst
(https://issues.rudder.io/issues/7073[#7073])

==== System integration

* Fixed: Rsyslog problem on Ubuntu 14.04 fresh install
(https://issues.rudder.io/issues/6127[#6127])

==== Architecture - Refactoring

* Fixed: Remove scala compiler warning about comparing values of type
Null (https://issues.rudder.io/issues/7072[#7072])

==== Architecture - Internal libs

* Fixed: A test is not compiling on branch 2.11 since #6729 was merged
(https://issues.rudder.io/issues/7056[#7056])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Janos Mattyasovszky

This is a bug fix release in the 2.11 `esr' series and therefore all
installations of 2.11.x should be upgraded when possible. When we
release a new version of Rudder it has been thoroughly tested, and we
consider the release enterprise-ready for deployment.

== Rudder 2.11.12 (2015-07-09)

=== Changes

==== Packaging

* Add a caching system to rudder build system
(https://issues.rudder.io/issues/6713[#6713])

=== Bug fixes

==== Web - UI & UX

* Fixed: No rules displayed in firefox
(https://issues.rudder.io/issues/6490[#6490])

==== Web - Config management

* Fixed: After a partial promise generation, some nodes being a relay
may have their promises stored in a non reachable location
(https://issues.rudder.io/issues/6729[#6729])

==== Web - Technique editor

* Fixed: Cannot save technique with ncf builder - error during the API
call to the technique library reload
(https://issues.rudder.io/issues/6724[#6724])

==== Web - Nodes & inventories

* Fixed: ldap.attr.networkInterfaceDhcpServer in search node component
(https://issues.rudder.io/issues/6785[#6785])

==== System integration

* Fixed: Ncf init fails in webapp postinst
(https://issues.rudder.io/issues/6698[#6698])
* Fixed: Startup links for rudder-server-root on Ubuntu are not correct
- before 3.1 (https://issues.rudder.io/issues/6263[#6263])
* Fixed: Sometimes, promises get corrupted to the point they can’t be
automatically repaired on a node
(https://issues.rudder.io/issues/6768[#6768])

==== Initial promises & sys tech

* Fixed: We can’t use cf-runagent because port is not taken into account
in the body runagent control
(https://issues.rudder.io/issues/6916[#6916])
* Fixed: Promises.st can’t load ncf on windows
(https://issues.rudder.io/issues/6700[#6700])
* Fixed: Nodes using syslogd continue to report to their old server when
changing their policy server
(https://issues.rudder.io/issues/6845[#6845])
* Fixed: Editing non-existent /etc/rsyslog.d/pgsql.conf in initial
promises (https://issues.rudder.io/issues/6784[#6784])

==== Techniques

* Fixed: Unexpected status for fileAlterationMonitoring
(https://issues.rudder.io/issues/6771[#6771])

==== Server components

* Fixed: When a node is promoted to relay, the old rsyslog conf is never
replaced (https://issues.rudder.io/issues/6721[#6721])

==== Agent

* Fixed: Cf-agent writes incorrect files when the server answers too
slowly during recursive copy
(https://issues.rudder.io/issues/6915[#6915])
* Fixed: Error about ldconfig during rudder-agent installation on AIX
(https://issues.rudder.io/issues/6703[#6703])

==== Documentation

* Fixed: Wrong hierarchy in archives section of the manual
(https://issues.rudder.io/issues/6909[#6909])
* Fixed: Broken asciidoc list formatting
(https://issues.rudder.io/issues/6778[#6778])
* Fixed: Outdated download link in the manual
(https://issues.rudder.io/issues/6764[#6764])
* Fixed: Broken link and misplaced page in documentation
(https://issues.rudder.io/issues/6757[#6757])
* Fixed: HashcodeCaching.scala typo error WRNING => WARNING
(https://issues.rudder.io/issues/6734[#6734])

==== Packaging

* Fixed: AIX installations output errors due to ``cp -a'' usage
(https://issues.rudder.io/issues/6830[#6830])
* Fixed: Rudder-reports does not find correct postgresql service when
using systemctl
(https://issues.rudder.io/issues/6699[#6699])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* François Bayart
* Dennis Cabooter
* Olivier Mauras

This is a bug fix release in the 2.11 `esr' series and therefore all
installations of 2.11.x should be upgraded when possible. When we
release a new version of Rudder it has been thoroughly tested, and we
consider the release enterprise-ready for deployment.

== Rudder 2.11.11 (2015-06-02)

=== Changes

==== Agent

* Allow rudder server to remotely run the agent
(https://issues.rudder.io/issues/6553[#6553])

=== Bug fixes

==== Web - Config management

* Fixed: When we accept a new node, we have two promises generation
instead of one
(https://issues.rudder.io/issues/6575[#6575])
* Fixed: When we regenerate promises via `Update' button, all promises
are regenerated even if not needed
(https://issues.rudder.io/issues/6518[#6518])

==== Web - Compliance & node report

* Fixed: When we add a node in a rule, we lose all compliance info on
this rule applied on it, and we change promises of all the nodes of the
rule (https://issues.rudder.io/issues/6519[#6519])
* Fixed: No reporting on agents on ncf directives on SLES
(https://issues.rudder.io/issues/6673[#6673])

==== Web - UI & UX

* Fixed: Bad RegEx in Groups causes Server to not respond
(https://issues.rudder.io/issues/6680[#6680])

==== Web - Technique editor

* Fixed: ncf post-hooks fails when there is nothing to commit
(https://issues.rudder.io/issues/6617[#6617])

==== API

* Fixed: In group API, attribute and comparator names are case sensitive
(https://issues.rudder.io/issues/6577[#6577])

==== Performance and scalability

* Fixed: Do not check dns when checking promises
(https://issues.rudder.io/issues/6616[#6616])

==== Server components

* Fixed: Webdav allow connection from any network, not only allowed
network (https://issues.rudder.io/issues/6540[#6540])
* Fixed: Messages forwarded from AIX agent are not dropped on
relay/server root after being consumed
(https://issues.rudder.io/issues/6522[#6522])
* Fixed: Log rotation on distributed install is not functional
(https://issues.rudder.io/issues/6521[#6521])

==== Agent

* Fixed: cfengine context is not updated properly when doing multiple
individual package actions
(https://issues.rudder.io/issues/6587[#6587])

==== Techniques

* Fixed: Typo in Technique ``zypper settings''
(https://issues.rudder.io/issues/6677[#6677])
* Fixed: Zypper is called without –non-interactive when filling
available updates cache
(https://issues.rudder.io/issues/6588[#6588])
* Fixed: Technique ``Clock settings'' uses Europe/Paris as China’s
timezone (https://issues.rudder.io/issues/6450[#6450])
* Fixed: MaxSessions parameter is supported on RedHat 6.3 (at least),
but Technique SSHConfiguration prevent from configuring it on this
system (https://issues.rudder.io/issues/6527[#6527])

==== Web - Nodes & inventories

* Fixed: Error 500 when sending multiple files to inventory endpoint
(https://issues.rudder.io/issues/6508[#6508])

==== System integration

* Fixed: The rudder-agent profile configuration may override the system
MANPATH (https://issues.rudder.io/issues/6548[#6548])
* Fixed: Log rotation of reports and slapd is not correctly functional
on redhat, as the server continues to write to the move file
(https://issues.rudder.io/issues/6526[#6526])
* Fixed: rudder-reports package should use the correct PostgreSQL
service (https://issues.rudder.io/issues/6546[#6546])

==== Packaging

* Fixed: The detect_os.sh script is not valid
(https://issues.rudder.io/issues/6486[#6486])

==== Documentation

* Fixed: Restore procedures has service name mistyped
(https://issues.rudder.io/issues/6664[#6664])
* Fixed: Old Normation logo in the manual
(https://issues.rudder.io/issues/6643[#6643])
* Fixed: Broken link in the demo section of rudder README
(https://issues.rudder.io/issues/6610[#6610])
* Fixed: Bibliography links are out of date
(https://issues.rudder.io/issues/6609[#6609])
* Fixed: Broken links in the manual
(https://issues.rudder.io/issues/6607[#6607])
* Fixed: Check spelling and grammar of the manual
(https://issues.rudder.io/issues/6599[#6599])
* Fixed: Remove references to the Big Red Button in the manual
(https://issues.rudder.io/issues/6596[#6596])
* Fixed: Fix asciidoc list formatting
(https://issues.rudder.io/issues/6595[#6595])
* Fixed: Rudder Documentation typo
(https://issues.rudder.io/issues/6559[#6559])
* Fixed: Update command on centos is missing ``ncf-api-virtualenv''
package (https://issues.rudder.io/issues/6503[#6503])

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Janos Mattyasovszky

This is a bug fix release in the 2.11 series and therefore all
installations of 2.11.x should be upgraded when possible. This version
is not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 2.11.10 (2015-04-13)

=== Changes

=== Bug fixes

==== Techniques

* Fixed: Document usage of line replacement in Enforce a file content
technique (https://issues.rudder.io/issues/5979[#5979])

==== Server components

* Fixed: networks.conf missing on relay servers
(https://issues.rudder.io/issues/6454[#6454])

==== Initial promises & sys tech

* Fixed: No reports for Propagate promises component on relay
(https://issues.rudder.io/issues/6404[#6404])

==== System integration

* Fixed: rudder-agent is stuck, waiting for user input during log
compression (https://issues.rudder.io/issues/6439[#6439])
* Fixed: rudder-jetty init script may fail on success
(https://issues.rudder.io/issues/5653[#5653])

==== Documentation

* Fixed: Improve documentation of archives management
(https://issues.rudder.io/issues/6485[#6485])
* Fixed: Badly explain minimum requirement for Rudder in documentation
(https://issues.rudder.io/issues/6453[#6453])
* Fixed: Outdated chapter: Disable automatic regeneration of promises
(https://issues.rudder.io/issues/6312[#6312])

==== Packaging

* Fixed: Remove python dependency for rudder-agent
(https://issues.rudder.io/issues/6424[#6424])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Florian Heigl
* Peter Keresztes
* Lionel Le Folgoc

This is a bug fix release in the 2.11 series and therefore all
installations of 2.11.x should be upgraded when possible. This version
is not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 2.11.9 (2015-03-24)

=== Changes

=== Bug fixes

==== Techniques

* Fixed: Enforce file content Technique doesn’t properly migrate lines
from outside the zone to the zone
(https://issues.rudder.io/issues/6389[#6389])

==== Agent

* Fixed: Using parsestringarrayidx on AIX leads to agent hanging up or
promises validation errors (only on 2.11)
(https://issues.rudder.io/issues/6396[#6396])

==== System integration

* Fixed: Rudder login page doesn’t appear just after the webapp has been
started (https://issues.rudder.io/issues/6402[#6402])
* Fixed: File /var/log/rudder/\{compliance/non-compliant-reports.log,
core/rudder-webapp.log} are not correctly rotated
(https://issues.rudder.io/issues/6381[#6381])

==== Packaging

* Fixed: AIX rudder-agent SPECfile fails to build due to a macro
expansion error
(https://issues.rudder.io/issues/6380[#6380])
* Fixed: The Ubuntu 14.04 default apache vhosts are not removed properly
and ncf-api-virtualenv is not put at the right place
(https://issues.rudder.io/issues/6392[#6392])

==== Architecture - Dependencies

* Fixed: Upgrade Liftweb to v2.5.2 (security issue)
(https://issues.rudder.io/issues/6426[#6426])

=== Release notes

This is a bug fix release in the 2.11 series and therefore all
installations of 2.11.x should be upgraded when possible. This version
is not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 2.11.8 (2015-03-09)

=== Bug fixes

==== Webapp - Display, home page

* Fixed: rule and group category ID are not displayed
(https://issues.rudder.io/issues/6323[#6323])
* Fixed: Display UUIDs in rudder web interface in lowercase so they can
be used directly.
(https://issues.rudder.io/issues/6297[#6297])

==== Webapp - Config management

* Fixed: ``+'' and ``-'' buttons to add a group to a Rule redirects to
the group edition page instead of adding the group to the Rule
(https://issues.rudder.io/issues/6276[#6276])

==== Webapp - Node management

* Fixed: List of impacted rules when accepting nodes or modifying
directives is not accurate
(https://issues.rudder.io/issues/5764[#5764])

==== API

* Fixed: Wrong default category set when creating a Rule
(https://issues.rudder.io/issues/6314[#6314])

==== Techniques

* Fixed: it’s not possible to define variables with " in them in generic
variable definition
(https://issues.rudder.io/issues/6279[#6279])
* Fixed: Wrong reporting in Technique Enforce a file content if the file
is not present
(https://issues.rudder.io/issues/6237[#6237])
* Fixed: OpenSSH server technique tries to configure MaxSession on AIX
5.3, but this parameter is invalid on this OS
(https://issues.rudder.io/issues/6374[#6374])
* Fixed: The fileManagement Technique does not report on AIX
(https://issues.rudder.io/issues/6362[#6362])

==== Documentation

* Fixed: SuSE upgrade procedure is missing a ncf upgrade, and the
documentation references no-more-present init scripts
(https://issues.rudder.io/issues/6288[#6288])
* Fixed: documentation states that `Workflow' needs to be set in the
config file, but now in rudder web interface
(https://issues.rudder.io/issues/6283[#6283])
* Fixed: Documentation to upgrade Rudder Server on Debian/Ubuntu is
incomplete (https://issues.rudder.io/issues/6109[#6109])
* Fixed: The migration to 2.11 procedure is misleading
(https://issues.rudder.io/issues/5794[#5794])

==== System integration

* Fixed: The rudder-agent package should remove the inittab entry and
subsystem on AIX, and should not run ldconfig
(https://issues.rudder.io/issues/6364[#6364])
* Fixed: SLES 11 SP1 requires an older version of Python virtualenv
(https://issues.rudder.io/issues/6365[#6365])
* Fixed: ncf-api-virtualenv fails to build due to and outdated version
of virtualenv (https://issues.rudder.io/issues/6347[#6347])
* Fixed: Rudder agent fails to build on Ubuntu 10.04 due to a buggy
dh_shlibdeps (https://issues.rudder.io/issues/6337[#6337])
* Fixed: Remove SASL support from rudder-inventory-ldap
(https://issues.rudder.io/issues/6229[#6229])
* Fixed: Upgrade rudder-agent can’t find/install man pages
(https://issues.rudder.io/issues/6016[#6016])

==== ncf-builder integration

* Fixed: rudderify ncf-hook does not work on first run
(https://issues.rudder.io/issues/6249[#6249])

==== Packaging

* Fixed: When I want to upgrade Rudder to latest version, ncf is NOT
updated on SLES11
(https://issues.rudder.io/issues/6286[#6286])
* Fixed: Unable to install Rudder agent if there is no rsync nor
libpcre3 installed on the system on Debian
(https://issues.rudder.io/issues/6239[#6239])

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Jean Cardona
* Florian Heigl
* Maxime Longuet

This is a bug fix release in the 2.11 series and therefore all
installations of 2.11.x should be upgraded when possible. This version
is not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 2.11.7 (2015-02-06)

=== Changes

==== Tools

* Server side debug for a single agent
(https://issues.rudder.io/issues/6180[#6180])

==== Techniques

* Add post hook commands and working update for rpm package installation
(https://issues.rudder.io/issues/3857[#3857])

=== Bug fixes

==== Webapp - Display, home page

* Fixed: Rudder stores too much or too big cookies, causing white page
with HTTP status: 413: FULL head
(https://issues.rudder.io/issues/6157[#6157]))

==== Webapp - Config management

* Fixed: Missing edit link for group in Rule page
(https://issues.rudder.io/issues/6061[#6061])

==== Webapp - Node management

* Fixed: Cannot display software information on accept new Nodes
(https://issues.rudder.io/issues/6155[#6155])
* Fixed: When adding a line of search criteria, the category and field
from the line above should be the same on the new line
(https://issues.rudder.io/issues/5905[#5905])
* Fixed: Wrong error message when accepted an already accepted node
(https://issues.rudder.io/issues/4895[#4895])
* Fixed: Can not move node groups with the form
(https://issues.rudder.io/issues/4571[#4571])

==== Webapp - Administration

* Fixed: ``Server cannot be contacted at this time'' when trying to get
Event Log details
(https://issues.rudder.io/issues/6172[#6172])
* Fixed: Cleanup expected reports
(https://issues.rudder.io/issues/6150[#6150])
* Fixed: Missing login eventlog
(https://issues.rudder.io/issues/6008[#6008])
* Fixed: Deletion of a Rule will lead to a stacktrace into the diff of
the related Change Request
(https://issues.rudder.io/issues/5374[#5374])
* Fixed: It is overly slow to show the list of Pending Review or Pending
Deployment even if the number is 0
(https://issues.rudder.io/issues/4359[#4359])
* Fixed: Jetty should compress the files rotated
(/var/log/rudder/webapp/*.log)
(https://issues.rudder.io/issues/3916[#3916])

==== API

* Fixed: Creating a directive via the api, makes it disabled by default
(https://issues.rudder.io/issues/6200[#6200])
* Fixed: cannot use ``enabled'' json parameter in Directive API
(https://issues.rudder.io/issues/6176[#6176])
* Fixed: Technique version cannot be specified with Directive API
(https://issues.rudder.io/issues/6174[#6174])
==== * Fixed: In API/rules include/exclude is ordered for target parameter
(https://issues.rudder.io/issues/5982[#5982])/redmine/issues/5389][#5389]])

==== Webapp - Reporting

* Fixed: When two techniques generated with ncf-builder use the same
generic method with same parameters, reporting cannot dinstinguish them,
and reports ``Unknown''
(https://issues.rudder.io/issues/5389[#5389])
* Fixed: Error in the Web Interface when trying to access inventory
report, on the node page
(https://issues.rudder.io/issues/5592[#5592])

==== Performance and scalability

* Fixed: Performance of RuleCategory repository requests are bad
(https://issues.rudder.io/issues/6133[#6133])
* Fixed: The way software inventories are saved is totally inefficient
(https://issues.rudder.io/issues/6075[#6075])
* Fixed: Error in the reports archiving process cause log explosion
(https://issues.rudder.io/issues/6007[#6007])
* Fixed: LDAP configuration is not optimized for Rudder use case
(https://issues.rudder.io/issues/5965[#5965])

==== Techniques

* Fixed: wrong group set by SSH key distribution
(https://issues.rudder.io/issues/6031[#6031])
* Fixed: Error output on Time settings at first run
(https://issues.rudder.io/issues/6000[#6000])
* Fixed: sshKeyDistribution creates 0 byte authorized_keys file
(https://issues.rudder.io/issues/5930[#5930])

==== Techniques - System & initial promises

* Fixed: Root server splaytime is always ``5'' - should be ``0''
(https://issues.rudder.io/issues/6164[#6164])
* Fixed: syntax error in promises.st
(https://issues.rudder.io/issues/6131[#6131])
* Fixed: rudder-agent installation may hang infinitely on Centos minimal
install due to curl installation
(https://issues.rudder.io/issues/6035[#6035])
* Fixed: Tests on rudder-techniques are broken due to $()
(https://issues.rudder.io/issues/5987[#5987])
* Fixed: Support uppercase hostname when updating promises
(https://issues.rudder.io/issues/6037[#6037])
* Fixed: Cannot manage more than 4993 nodes, due to CFEngine limitation
(https://issues.rudder.io/issues/5621[#5621])

==== System integration

* Fixed: rudder-agent-thin: missing /var/rudder/share/man
(https://issues.rudder.io/issues/6092[#6092])
* Fixed: Upgrading rudder-inventory-ldap between two major OS versions
makes slapd unable to operate because of BerkeleyDB
(https://issues.rudder.io/issues/5741[#5741])
* Fixed: If killall is not installed, cf-serverd can not reloaded during
promise generation
(https://issues.rudder.io/issues/6202[#6202])
* Fixed: The rudder-upgrade script should never use /sbin/service
(https://issues.rudder.io/issues/6188[#6188])
* Fixed: We should not clean DB_CONFIG and slapd.conf in
rudder-inventory-ldap package source Makefile
(https://issues.rudder.io/issues/6185[#6185])
* Fixed: Building rudder-agent fails on Ubuntu 10.04, due to failing
patch (https://issues.rudder.io/issues/6134[#6134])
* Fixed: Rudder agent compilation fails to build on AIX
(https://issues.rudder.io/issues/6132[#6132])
* Fixed: Warning after policy generation, /bin/pidof does not exists
(https://issues.rudder.io/issues/6051[#6051])

==== ncf-builder integration

* Fixed: ncf API hooks fails because it uses bashism but declares using
shell (https://issues.rudder.io/issues/6168[#6168])
* Fixed: URL for the ncf-builder call is misunderstood by IE9 (bad html5
support) - Rudder 2.11
(https://issues.rudder.io/issues/6129[#6129])
* Fixed: ncf API hooks don’t always fail on errors
(https://issues.rudder.io/issues/5866[#5866])

==== Packaging

* Fixed: When migrating from 2.10 to 2.11, if BDB need to be upgraded,
all changes made by rudder-upgrade are reverted
(https://issues.rudder.io/issues/6199[#6199])
* Fixed: Upgrading Rudder from 2.10 to 2.11 nightly fails to properly
set roles and configures psql password
(https://issues.rudder.io/issues/6196[#6196])
* Fixed: Agent regenerates the list of package available to install
several time per run, causing massive performance hit
(https://issues.rudder.io/issues/6119[#6119])
* Fixed: Error log when installing rudder-inventory ldap on RHEL6
(https://issues.rudder.io/issues/6032[#6032])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Alex Bruni
* Dennis Cabooter
* Florian Heigl
* Lionel Le Folgoc
* Olivier Mauras

This is a bug fix release in the 2.11 series and therefore all
installations of 2.11.x should be upgraded when possible. This version
is not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

Rudder 2.11.6 => Not released, major bug in debian installation
== (https://issues.rudder.io/issues/6232[#6232])

== Rudder 2.11.5 (2014-12-16)

=== Changes

==== Techniques

* Add an option to allow purge of local directory content in ``Copy file
from shared folder'' Technique
(https://issues.rudder.io/issues/5754[#5754])

=== Bug fixes

==== Webapp - Configuration management

* Fixed: System rule are modified when trying to delete a directive
(https://issues.rudder.io/issues/5923[#5923])
* Fixed: It should not be possible to delete system directives
(https://issues.rudder.io/issues/5875[#5875])
* Fixed: Correctly display technique removed from source library
(https://issues.rudder.io/issues/5808[#5808])
* Fixed: Description of default Rule ``Global configuration for all
nodes'' is missing a space
(https://issues.rudder.io/issues/5788[#5788])
* Fixed: On directive tree, tooltips does not appear anymore after
directive update
(https://issues.rudder.io/issues/4223[#4223])
* Fixed: Compliance percents are not sorted correctly
(https://issues.rudder.io/issues/5714[#5714])
* Fixed: Remove edit link for system directive/rules
(https://issues.rudder.io/issues/5916[#5916])

==== Webapp - Node management

* Fixed: We can’t search for ``Name ='' for an environment variable name
in node (https://issues.rudder.io/issues/5644[#5644])
* Fixed: When creating a Group or a Rule, the category should be set to
the currently selected category
(https://issues.rudder.io/issues/4367[#4367])
* Fixed: When cloning a group, the group Tree doesn’t refresh
(https://issues.rudder.io/issues/3796[#3796])

==== Webapp - CFEngine integration

* Fixed: Splaytime duration must be STRICTLY inferior to the agent
period to avoid random run frequency
(https://issues.rudder.io/issues/5806[#5806])
* Fixed: License of CFengine Enterprise is not mandatory on Enterprise,
and should not be enforced by the web interface
(https://issues.rudder.io/issues/5761[#5761])
* Fixed: Generating policies failed with ``key not found: LICENSESPAID''
(https://issues.rudder.io/issues/5961[#5961])

==== Webapp - Display, home page

* Fixed: Missing files on the load page
(https://issues.rudder.io/issues/5867[#5867])
* Fixed: Calendar used in admisnistration page is in japanese
(https://issues.rudder.io/issues/5971[#5971])

==== API

* Fixed: Error message when trying to delete a system directive is
horrible (https://issues.rudder.io/issues/5915[#5915])
* Fixed: You cannot pass `include' / `exclude' targets as json for Rule
API (https://issues.rudder.io/issues/5786[#5786])
* Fixed: Using json to create directive is not working with API
(https://issues.rudder.io/issues/5778[#5778])
* Fixed: Group category cannot be read from json parameters
(https://issues.rudder.io/issues/5123[#5123])

==== Logging

* Fixed: Rudder agents crons send far too many mails
(https://issues.rudder.io/issues/5190[#5190])

==== Documentation

* Fixed: Rudder readme is totally out of date and irrelevant
(https://issues.rudder.io/issues/5926[#5926])
* Fixed: User manual doesn’t explain how to use Parameters
(https://issues.rudder.io/issues/5729[#5729])
* Fixed: Upgrade procedure in reference manual don’t upgrade ncf
(https://issues.rudder.io/issues/5285[#5285])
* Fixed: The relay server docs don’t mention what do on nodes
(https://issues.rudder.io/issues/4365[#4365])
* Fixed: Database maintenance chapter doesn’t mention automatic
archiving (https://issues.rudder.io/issues/3960[#3960])
* Fixed: We should remove the questions we do not ask anymore during
rudder-init from the documentation
(https://issues.rudder.io/issues/5779[#5779])

==== Techniques

* Fixed: Build are failing because the normal ordering is not respected
in technique motdConfiguration v3.1
(https://issues.rudder.io/issues/5959[#5959]
* Fixed: [motdConfiguration] REGEX constraint outside of CONSTRAINT
block (https://issues.rudder.io/issues/5440[#5440])

==== System integration

* Fixed: Require latest version of ncf including fixes for reporting
(https://issues.rudder.io/issues/5880[#5880])
* Fixed: dpkg configure error prevents installing rudder-agent due to
cf-serverd error
(https://issues.rudder.io/issues/5785[#5785])
* Fixed: Use nxlog instead of Centreon E2S, as it has less dependencies,
and installs on every windows
(https://issues.rudder.io/issues/5762[#5762])
* Fixed: Call ncf configuration bundle from Rudder, to ensure
configuration used is correct
(https://issues.rudder.io/issues/5597[#5597])
* Fixed: We can configure the Configuration Repository folder in the
config file of the Web Interface , but the system Techniques are
enforcing the location /var/rudder/configuration-repository
(https://issues.rudder.io/issues/5347[#5347])
* Fixed: Missing cfengine man pages
(https://issues.rudder.io/issues/4903[#4903])
* Fixed: Rudder-init can fail on CentOS when the host has no domain name
(https://issues.rudder.io/issues/5812[#5812])
* Fixed: Rudder virtualhosts are missing a 2.4 compatible proxy
definition (https://issues.rudder.io/issues/5783[#5783])
* Fixed: rudder-init end summary has typos
(https://issues.rudder.io/issues/5780[#5780])

==== Techniques - System & initial promises

* Fixed: System techniques can only setup log settings *once* on
syslog-ng (https://issues.rudder.io/issues/5799[#5799])
* Fixed: Initial promises are calling undefined body u_bootstart
(https://issues.rudder.io/issues/5997[#5997])
* Fixed: Enforce the content of the local ncf configuration file from
techniques (https://issues.rudder.io/issues/5937[#5937])

==== Windows agent

* Fixed: Motd technique only work on Unixes, not on windows
(https://issues.rudder.io/issues/5890[#5890])
* Fixed: Process checking for cf-agent on windows suicide itself
(https://issues.rudder.io/issues/5619[#5619])
* Fixed: Promises on Windows try to download perl
(https://issues.rudder.io/issues/5948[#5948])
* Fixed: Services management technique doesn’t work on Windows
(https://issues.rudder.io/issues/5938[#5938])

==== AIX agent

* Fixed: Technique SSHConfiguration don’t reports properly on Aix for
component ``SSH start at boot'' if it is already correctly defined
(https://issues.rudder.io/issues/5902[#5902])
* Fixed: Technique SSHConfiguration don’t reports properly on Aix for
component ``SSH start at boot''
(https://issues.rudder.io/issues/5860[#5860])
* Fixed: Technique SSHConfiguration v4.0 fails on AIX - and stops agent
execution (https://issues.rudder.io/issues/5836[#5836])
* Fixed: Messages sent from an AIX machine via a relay are not forwarded
correctly (https://issues.rudder.io/issues/5775[#5775])

==== Performance and scalability

* Fixed: Ldap query to get all software by nodes take ages
(https://issues.rudder.io/issues/5803[#5803])

==== Packaging

* Fixed: Debian-like OSes fail to build a bundled OpenSSL when running
inside pbuilder
(https://issues.rudder.io/issues/5818[#5818])
* Fixed: Building OpenSSL on AIX requires triggering slibclean before
installing (https://issues.rudder.io/issues/5815[#5815])
* Fixed: The OpenSSL patches on old Debian rudder-agent packages try to
use a SPEC file macro
(https://issues.rudder.io/issues/5814[#5814])
* Fixed: The rudder-agent SPEC file does not handle bundled Openssl or
not conditions properly
(https://issues.rudder.io/issues/5811[#5811])
* Fixed: We should not build Fusion with SSL support as we do not use it
and it breaks Bundled OpenSSL builds
(https://issues.rudder.io/issues/5776[#5776])

==== Miscellaneous

* Fixed: Null pointer exception on agentTypes class
(https://issues.rudder.io/issues/5816[#5816])
* Fixed: The definition of the current version of XML format is
duplicated (https://issues.rudder.io/issues/3352[#3352])

==== Vagrant boxes

* Fixed: Add a link to rudder-vagrant redmine in Readme
(https://issues.rudder.io/issues/5228[#5228])
* Fixed: For without do in node_centos6.sh
(https://issues.rudder.io/issues/5134[#5134])
* Fixed: /etc/hosts gets messed up by sed commands
(https://issues.rudder.io/issues/4142[#4142])
* Add a test to check boxes source url
(https://issues.rudder.io/issues/5130[#5130])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Florian Heigl
* Lionel Le Folgoc
* Olivier Mauras

This is a bug fix release in the 2.11 series and therefore all
installations of 2.11.x should be upgraded when possible. This version
is not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 2.11.4 (2014-11-18)

=== Changes

==== Webapp - Config management

* Permit the nodes access rules to be reloaded automatically after each
promises generation
(https://issues.rudder.io/issues/5571[#5571])

==== Packaging

* Include our own OpenSSL for non maintained oses in rudder-agent
package (https://issues.rudder.io/issues/5147[#5147])

==== System integration

* Make Rudder Apache 2.4 compliant
(https://issues.rudder.io/issues/5183[#5183])

=== Bug fixes

==== Webapp - Config management

* Fixed: Number of entries displayed in Rule table is not saved
(https://issues.rudder.io/issues/5615[#5615])
* Fixed: No tooltip displayed when you add a new section in a Directive
(https://issues.rudder.io/issues/5706[#5706])
* Fixed: No groups directory in /var/rudder/configuration-repository
(https://issues.rudder.io/issues/5509[#5509])
* Fixed: Rule categories list is not sorted
(https://issues.rudder.io/issues/5471[#5471])

==== Webapp - Display, home page

* Fixed: Popups buttons may not be accessible after window is resized
(https://issues.rudder.io/issues/5492[#5492])
* Fixed: White page with HTTP status: 413: FULL head
(https://issues.rudder.io/issues/4378[#4378])

==== Webapp - Node management

* Fixed: Policies are not regenerated when accepting a node
(https://issues.rudder.io/issues/5756[#5756])
* Fixed: Add number of entries selector on Nodes table
(https://issues.rudder.io/issues/5388[#5388])
* Fixed: Node details is missing plugin extension points
(https://issues.rudder.io/issues/5767[#5767])

==== Techniques

* Fixed: Technique `rpmPackageInstallation' v6.0 stores a file in the
wrong directory
(https://issues.rudder.io/issues/5697[#5697])
* Fixed: Permissions may be applied recursively even if not asked to by
``filesPermissions'' Technique
(https://issues.rudder.io/issues/5632[#5632])
* Rudder is unable to compare two package version correctly
(https://issues.rudder.io/issues/5587[#5587])
* Fixed: It’s not possible to update package to latest version
(https://issues.rudder.io/issues/5609[#5609])
* Fixed: Packages are not updated correctly on redhat based systems
(https://issues.rudder.io/issues/5608[#5608])
* Fixed: Zypper Management Technique doesn’t behave correctly, and
should be split in two separated techniques
(https://issues.rudder.io/issues/5662[#5662])
* Fixed: Multiline header is added at each run on managed files
(https://issues.rudder.io/issues/4650[#4650])
* Fixed: Zypper technique says skipping but returns UNKNOWN.
(https://issues.rudder.io/issues/5493[#5493])
* Fixed: Generic variables definition forbid `&' character usage
(https://issues.rudder.io/issues/5605[#5605])
* Update all techniques to respect normal ordering
(https://issues.rudder.io/issues/5306[#5306])
* Fixed: Acceptance tests are failing on some techniques
(https://issues.rudder.io/issues/5752[#5752])
* Fixed: On 2.11 rudder-agent, ``Repair'' status is always defined, even
if nothing is modified
(https://issues.rudder.io/issues/5327[#5327])
* Fixed: NTP technique has no option to not set hw clock
(https://issues.rudder.io/issues/5671[#5671])
* Fixed: ``sshKeyDistribution'' Technique keeps adding the same keys for
ever (https://issues.rudder.io/issues/5561[#5561])
* Fixed: Evaluation of promises is not correctly done in CFEngine 3.6.0
- 3.6.2, preventing some promises evaluation
(https://issues.rudder.io/issues/5660[#5660])

==== Techniques - System & initial promises

* Fixed: Check on age of promises in failsafe doesn’t take into account
specific schedule, nor lmdb database, and should probably be remove
(https://issues.rudder.io/issues/5582[#5582])

==== Relay Servers

* Fixed: Relay servers keeps sending inventories of their managed nodes
at every run (https://issues.rudder.io/issues/5462[#5462])
* Fixed: When a node changes its policy server, the groups
hasPolicyServer are never updated, and so the promises never make their
way to them (https://issues.rudder.io/issues/5322[#5322])

==== System integration

* Fixed: ``fatal CFEngine error: in built-in FnCall irange-arg: Integer
is out of range'' when using irange on non-linux plateform
(https://issues.rudder.io/issues/5719[#5719])
* Fixed: Compliance to 0 with ``no reports'' but Technical reports
correctly arriving + log about integer out of range for executionStatus
(https://issues.rudder.io/issues/5569[#5569])
* Fixed: Post modification hooks of ncf are group writable, and it makes
grsec complains
(https://issues.rudder.io/issues/5566[#5566])

==== Documentation

* Fixed: Technique upgrade documentation is not correct
(https://issues.rudder.io/issues/5611[#5611])
* Fixed: Update screenshots to be Rudder 2.11 compliant
(https://issues.rudder.io/issues/5350[#5350])

==== Inventory (webapp, Fusion)

* Fixed: Non-unique machine UUID mess up collected inventory
(https://issues.rudder.io/issues/4490[#4490])
* Fixed: Having multiple agents on a node breaks the values of the node
policy server and node administrator user
(https://issues.rudder.io/issues/5583[#5583])

==== Webapp - CFEngine integration

* Fixed: Use of variable starting with `rudder' in cfengine variable is
forbidden (https://issues.rudder.io/issues/5743[#5743])
* Fixed: Two techniques with the same ID leads to strange error about
git tree ids (https://issues.rudder.io/issues/5614[#5614])

==== Packaging

* Fixed: We should trigger slibclean on AIX during rudder-agent upgrades
(https://issues.rudder.io/issues/5733[#5733])
* Fixed: A Rudder upgrade that leads to a different BDB version usage in
slapd fails (https://issues.rudder.io/issues/5705[#5705])
* Fixed: We do not depend on apache2 utilities (and need it to use
htpasswd) (https://issues.rudder.io/issues/5599[#5599])

==== Performance and scalability

* Fixed: Webapp checking that CFEngine variables used in Directive are
correct takes too much time at startup
(https://issues.rudder.io/issues/5358[#5358])

==== Miscellaneous

* Fixed: cf-clerk does not compile with Java 8
(https://issues.rudder.io/issues/5657[#5657])

==== Windows integration

* Fixed: list-compatible-inputs doesn’t work on windows
(https://issues.rudder.io/issues/5616[#5616])
* Fixed: executor daemon command needs to be different on windows for it
to work (https://issues.rudder.io/issues/5594[#5594])
* Fixed: System technique make cfengine enterprise copy binairies from
/opt/rudder, killing itself
(https://issues.rudder.io/issues/5590[#5590])
* Fixed: Handling of inventory fails on Windows
(https://issues.rudder.io/issues/5588[#5588])
* Fixed: The repository for modified files is not activated on Windows
(https://issues.rudder.io/issues/5581[#5581])
* Fixed: Ports used for file copy between Client and Server is not
correct on Windows, preventing copy on Windows
(https://issues.rudder.io/issues/5431[#5431])
* Fixed: remove use of proxy in curl on Windows, as it is an invalid
option (https://issues.rudder.io/issues/5429[#5429])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Dennis Cabooter
* Matthieu Ca.
* Florian Heigl
* Lionel le Folgoc
* Olivier Mauras
* Alex Tkachenko

This is a bug fix release in the 2.11 series and therefore all
installations of 2.11.x should be upgraded when possible. This version
is not yet marked ``stable'', since it has not yet proven itself to be
reliable on production systems over a period of several months. The
current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 2.11.3 (2014-09-24)

=== Changes

==== Agent

* Let vzps act as ps if no CTID is specified
(https://issues.rudder.io/issues/5478[#5478])

==== Documentation

* Installation procedure for distributed rudder server
(https://issues.rudder.io/issues/5178[#5178])

=== Bug fixes

==== Techniques - System & initial

* Fixed: Tools folder are empty!
(https://issues.rudder.io/issues/5564[#5564])
* Fixed: Cache generated by list-compatible-inputs is cleared by the ncf
copy, resulting in perpertual repaired state
(https://issues.rudder.io/issues/5513[#5513])
* Fixed: The script list-compatible-inputs, copied from ncf, cannot be
copied as the path is invalid
(https://issues.rudder.io/issues/5512[#5512])
* Fixed: System techniques on Windows try to schedule a cron task
(https://issues.rudder.io/issues/5441[#5441])
* Fixed: command to run fusion-inventory on windows fails due to parsing
error in command line
(https://issues.rudder.io/issues/5430[#5430])
* Fixed: Rewrite initial promises to use normal ordering on 2.11
(https://issues.rudder.io/issues/5499[#5499])
* Fixed: The Rudder logrotate configuration uses the wrong argument to
reload rsyslog on Debian Wheezy
(https://issues.rudder.io/issues/5486[#5486])

==== Techniques - Other

* Fixed: Weird behaviours of partitionMonitoring technique on ZFS on
2.11 (https://issues.rudder.io/issues/5468[#5468])
* Fixed: clock management technique always report repair on Windows
(https://issues.rudder.io/issues/5341[#5341])
* Fixed: User Management Techniques don’t reports properly on Windows
(https://issues.rudder.io/issues/5340[#5340])
* Fixed: Rewrite techniques to use normal ordering on 2.11
(https://issues.rudder.io/issues/5508[#5508])
* Fixed: rudder-agent start shows an alert
(https://issues.rudder.io/issues/5146[#5146])
* Fixed: implement openvz support for rudder 2.11
(https://issues.rudder.io/issues/5477[#5477])
* Fixed: oracle server Linux are not recognized anymore by inventory
(https://issues.rudder.io/issues/5476[#5476])
* Fixed: implement openvz support for rudder 2.11
(https://issues.rudder.io/issues/5467[#5467])
* Fixed: FusionInventory version check not handling version number
correctly (https://issues.rudder.io/issues/5419[#5419])
* Fixed: The Rudder logrotate configuration is not in sync between
regular and initial promises
(https://issues.rudder.io/issues/5544[#5544])
* Fixed: use list-compatible-inputs from ncf, not from tools
(https://issues.rudder.io/issues/5527[#5527])
* Fixed: Call list-compatible-inputs with /bin/sh
(https://issues.rudder.io/issues/5519[#5519])
* Fixed: The ``Download a file'' Technique contains a syntax error
(https://issues.rudder.io/issues/5457[#5457])
* Fixed: SSH Configuration Technique does not make timestamped version
of all the version of the ssh config file, like other techniques
(https://issues.rudder.io/issues/5344[#5344])
* Fixed: Add a placeholder for new technique on old versions
(https://issues.rudder.io/issues/5463[#5463])

==== Inventory

* Fixed: Inventories generated on Windows are not accepted by the
endpoint (https://issues.rudder.io/issues/5191[#5191])
* Fixed: FusionInventory: Doesn’t display (most) disk sizes
(https://issues.rudder.io/issues/4197[#4197])

==== Webapp - Config management

* Fixed: Correct HTML: badly closed tag
(https://issues.rudder.io/issues/5540[#5540])

==== Webapp - Node management

* Fixed: LDAP error when defining group criteria
(https://issues.rudder.io/issues/5504[#5504])
* Fixed: The Rule compliance explanations in Rudder’s web UI are not
clear (https://issues.rudder.io/issues/5413[#5413])
* Fixed: We cannot edit only section of the file with enforce file
content (https://issues.rudder.io/issues/5301[#5301])

==== API

* Fixed: Get system serial number output from inventory though API
(https://issues.rudder.io/issues/5528[#5528])
* Fixed: Accepting Nodes via API does not trigger policy update
(https://issues.rudder.io/issues/5511[#5511])

==== System integration

* Fixed: upgrade on 2.11 does not end correctly
(https://issues.rudder.io/issues/5495[#5495])
* Fixed: Failing upgrade 2.10 > 2.11 due to rudder-webapp being upgraded
before rudder-inventory-ldap
(https://issues.rudder.io/issues/5387[#5387])
* Fixed: error in rudder-upgrade are not clear on service check
(https://issues.rudder.io/issues/5500[#5500])
* Fixed: Tools directory is not always correctly updated on nodes
(https://issues.rudder.io/issues/5459[#5459])

==== Packaging

* Fixed: Make the rudder-upgrade script more verbose in case of failures
(https://issues.rudder.io/issues/5464[#5464])
* Fixed: The strict dependency on ncf in rudder-techniques need to be
updated (https://issues.rudder.io/issues/5545[#5545])
* Fixed: remove list-compatible-inputs from tools
(https://issues.rudder.io/issues/5532[#5532])
* Fixed: rudder-techniques should require a specific version of ncf
(https://issues.rudder.io/issues/5522[#5522])
* Fixed: Upgrade rudder-agent can fail if cf-serverd/cf-execd fails to
stop gracefully
(https://issues.rudder.io/issues/4387[#4387])

==== Logging

* Fixed: Do not write into cf3.[hostname].runlog files used for debug or
CFEngine Enterprise edition
(https://issues.rudder.io/issues/5488[#5488])

==== Documentation

* Fixed: Do not use contrib and non-free
(https://issues.rudder.io/issues/5181[#5181])
* Fixed: 2.11+ doc should refer to rudder-init instead of rudder-init.sh
(https://issues.rudder.io/issues/5447[#5447])

=== Release notes

This is a bug fix release in the 2.11 series.

It fixes important issues like: * Bloating rudder-agent log files *
Inventory disk detection * OpenVZ container process detection support

All installations of 2.11.x should be upgraded when possible. This
version is not yet marked ``stable'', since it has not yet proven itself
to be reliable on production systems over a period of several months.
The current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

=== Known issues

The update script to switch to BigInt database storage for Rudder
reports (when having a lot of nodes registered reporting) is incomplete.
To switch correctly to BigInt, please use the workaround given in this
ticket: https://issues.rudder.io/issues/5569

== Rudder 2.11.2 (2014-08-13)

=== Bug fixes

==== Techniques

* Fixed: We can’t set the SUID/SGID in technique Manage file and folders
(https://issues.rudder.io/issues/5325[#5325])
* Fixed: fstab Tehcnique empties all options with Rudder 2.11
(https://issues.rudder.io/issues/5328[#5328])
* Fixed: In checkGenericFileContent v5.0, no answer in post modification
hook (https://issues.rudder.io/issues/5318[#5318])
* Fixed: In checkGenericFileContent v5.0, reporting on post modification
hook can be unknown
(https://issues.rudder.io/issues/5312[#5312])
* Fixed: User Management 3.0 reports No Answer for the password
component if the password is not set
(https://issues.rudder.io/issues/5239[#5239])
* Fixed: CheckGenericFileContent does not send reports for post
modification hook when we enforce the content of the file only at
creatio (https://issues.rudder.io/issues/5208[#5208])
* Fixed: Incorrect use of commands without their full path in Sudo
Parameter technique
(https://issues.rudder.io/issues/5187[#5187])
* Fixed: The find call used to get all the files to include in the
CFEngine run is not usable on AIX
(https://issues.rudder.io/issues/5292[#5292])
* Fixed: Inventory are not correctly generated on Windows
(https://issues.rudder.io/issues/5342[#5342])
* Fixed: Agent run may fail on nodes because some promises have not be
correctly updated
(https://issues.rudder.io/issues/5231[#5231])
* Fixed: Process management technique uses invalid syntax on CFEngine
3.5+ (https://issues.rudder.io/issues/5315[#5315])

==== Web application

* Fixed: Changes in directives are not taken into account if we only
change the case of characters
(https://issues.rudder.io/issues/5317[#5317])
* Fixed: The table reportsexecution, storing the agent execution on
every node, is never emptied, and so can get very big
(https://issues.rudder.io/issues/5326[#5326])
* Fixed: When using several times a generic_method on same file with
class_prefix based on filename, reports will be in ``Unknown'' and ``No
answer'' status
(https://issues.rudder.io/issues/5330[#5330])
* Fixed: Popup content can be displayed outside of popup if content grow
after intiialisation
(https://issues.rudder.io/issues/5314[#5314])

==== Performance and scalability

* Fixed: Group page is really slow when a lot of groups are defined
(https://issues.rudder.io/issues/5277[#5277])
* Fixed: Promise generation is slowed down because expected_reports.csv
file is written multiple times per node
(https://issues.rudder.io/issues/5240[#5240])

==== Packaging

* Fixed: After migration to 2.11, no reports are saved since no roles
are defined on root server
(https://issues.rudder.io/issues/5273[#5273])
* Fixed: On RHEL system, ncf-builder hangs on a page with only ncf
header with ``Unable to connect to WSGI daemon process
`ncf_api_flask_app'[…]'' in /var/log/rudder/apache2/error.log
(https://issues.rudder.io/issues/5355[#5355])
* Fixed: ncf replace all files in /usr/share/ncf without exception which
is non compatible with Rudder
(https://issues.rudder.io/issues/5274[#5274])
* Fixed: rudder-init still waits for 5 arguments, but only needs two
(https://issues.rudder.io/issues/5289[#5289])
* Fixed: The rudder-plugin script uses a wrong definition to enable
plugins (https://issues.rudder.io/issues/5323[#5323])
* Fixed: On AIX, when the crontab is edited to add check_rudder_agent,
the service cron is not reloaded
(https://issues.rudder.io/issues/5310[#5310])
* Fixed: The check-rudder-agent script tries to use the stat command on
AIX (https://issues.rudder.io/issues/5198[#5198])
* Fixed: A whitespace added in debian/control of rudder-agent prevent it
to be built on Debian-like OSes
(https://issues.rudder.io/issues/5380[#5380])
* Fixed: Missing dependency on net-tools for rudder-agent and
rudder-thin (https://issues.rudder.io/issues/5199[#5199])

==== System integration

* Fixed: Apache documentroot for SLES seems misconfigured
(https://issues.rudder.io/issues/5370[#5370])
* Fixed: Authorized network sometimes have invalid values after
rudder-init if you add more than one network
(https://issues.rudder.io/issues/5103[#5103])

==== CFEngine

* Fixed: Using the edit_template file attribute in CFEngine sometimes
creates zero length files in 3.6
(https://issues.rudder.io/issues/5379[#5379])
* Fixed: rudder-agent 2.11. ignore duplicate lines in data files causing
rpmPackageInstallation technique to ignore some configurations
(https://issues.rudder.io/issues/5386[#5386])

==== Documentation

* Fixed: Update screenshots to be Rudder 2.6 compliant
(https://issues.rudder.io/issues/5348[#5348])
* Fixed: Incomplete command to force inventory
(https://issues.rudder.io/issues/5205[#5205])
* Fixed: The documentation says there is no Rudder server packages for
RHEL 6 (https://issues.rudder.io/issues/5204[#5204])

=== Release notes

This is a bug fix release in the 2.11 series.

It fixes two important issues: * The migration from a non-2.11 version
to Rudder 2.11 leads to an incorrect syslog configuration, impairing the
compliance display and rule status * ncf builder did not function
properly on RHEL systems due to a permission issue

All installations of 2.11.x should be upgraded when possible. This
version is not yet marked ``stable'', since it has not yet proven itself
to be reliable on production systems over a period of several months.
The current ``stable'' release is still 2.10.*. When we release a new
version of Rudder, it needs to be thoroughly tested, and we consider the
release enterprise-ready for deployment only after it has been proven to
run in production reliably for several months.

== Rudder 2.11.1 (2014-07-21)

=== Changes

=== Bug fixes

==== Performance and scalability

* Fixed: Rule page is really slow when a lot of rules are defined
(https://issues.rudder.io/issues/5279[#5279])
* Fixed: Group page is really slow when a lot of groups are defined
(https://issues.rudder.io/issues/5277[#5277])

=== Release notes

This is a bug fix release in the 2.11 series. All installations of
2.11.x should be upgraded when possible. This version is not yet marked
``stable'', since it has not yet proven itself to be reliable on
production systems over a period of several months. The current
``stable'' release is still 2.10.*.

When we release a new version of Rudder it has been thoroughly tested,
and we consider the release enterprise-ready for deployment. To be
declared ``stable'' we prefer to wait until a version has been available
and running in production for several months.

== Rudder 2.11.0 (2014-07-17)

=== Changes

==== Webapp - Node management

* Add a system group to target all nodes that are not a Rudder server
component (https://issues.rudder.io/issues/5267[#5267])

==== Webapp - Display, home page

* Add Rudder 2.11 logo: Peruha
(https://issues.rudder.io/issues/5263[#5263])

=== Bug fixes

==== Webapp - Reporting

* Fixed: In compliance popup, report status displayed for each node is
not correct (https://issues.rudder.io/issues/5241[#5241])

==== Webapp - Node management

* Fixed: Cannot make group based on server role since the attribute
``Server role'' is missing from search tool
(https://issues.rudder.io/issues/5265[#5265])

==== Techniques - Sys & init promise

* Fixed: Agent run may fail on nodes because some promises have not be
correctly updated
(https://issues.rudder.io/issues/5231[#5231])

=== Release notes

This version of Rudder is a final release. We have tested it thoroughly
and believe it to be free of any major bugs. However, this branch is not
marked ``stable'', since it still has to be proven reliable on
production systems over a period of several months. The current
``stable'' release is 2.10.*.

== Rudder 2.11.0~rc2 (2014-07-09)

=== Changes

=== Bug fixes

==== Webapp - CFEngine integration

* Fixed: CFEngine is unable to run automatically on Rudder Server
2.11.0.rc1 since its generated promises have group writable permissions
(https://issues.rudder.io/issues/5238[#5238])

==== System integration

* Fixed: Reports cannot be stored in local postgresql on a server Rudder
in stand alone configuration
(https://issues.rudder.io/issues/5237[#5237])

==== Packaging

* Fixed: An error occurs during upgrade because variable OPT_RUDDER is
missing in rudder-upgrade-database script
(https://issues.rudder.io/issues/5235[#5235])
* Fixed: After upgrade to 2.11 on rpm systems, web interface isn’t
started by jetty as rudder.xml file is deleted during upgrade
(https://issues.rudder.io/issues/5223[#5223])

==== Techniques

* Fixed: Nodes which are not part of distributed architecture displays
an error log on agent execution about missing
`/opt/rudder/etc/server-roles.d/' directory
(https://issues.rudder.io/issues/5200[#5200])

==== Performance and scalability

* Fixed: Promise generation is slowed down because expected_reports.csv
file is written multiple times per node
(https://issues.rudder.io/issues/5240[#5240])

=== Release notes

This software is in ``release candidate'' status and contains multiple
bug fixes since last release candidate (2.11.0~rc1)

If no major bugs are found, a ``final'' release of 2.11.0 will be
released next week.

== Rudder 2.11.0~rc1 (2014-07-07)

=== Changes

==== Webapp - Config management

* Add links to ncf-builder in Directive and Technique page
(https://issues.rudder.io/issues/5230[#5230])

=== Bug fixes

==== Techniques - Sys & init promise

* Fixed: System Techniques does not use role rudder-relay-top
(https://issues.rudder.io/issues/5189[#5189])

==== Techniques

* Fixed: CheckGenericFileContent does not send reports for post
modification hook when we enforce the content of the file only at
creation (https://issues.rudder.io/issues/5208[#5208])
* Fixed: Incorrect use of commands without their full path in Sudo
Parameter technique
(https://issues.rudder.io/issues/5187[#5187])

==== System integration

* Fixed: Remove unnecessary question about policy server fqdn in
rudder-init script
(https://issues.rudder.io/issues/5206[#5206])
* Fixed: Rename properties (rudder-front, rudder-webapp) in
rudder-webapp configuration file
(https://issues.rudder.io/issues/5185[#5185])
* Fixed: uuid.hive gets overwritten on the root server if rudder-agent
is installed after rudder-webapp
(https://issues.rudder.io/issues/5089[#5089])
* Fixed: Authorized networks sometimes have invalid values after
rudder-init if you add more than one network
(https://issues.rudder.io/issues/5103[#5103])

==== Inventory (webapp, Fusion)

* Fixed: If the inventory of Rudder server is not received by
rudder-webapp, Rudder server has no role then rsyslogd configuration is
broken (https://issues.rudder.io/issues/5233[#5233])

==== ncf-builder

* Fixed: ncf-api does not run as root and cannot use command to
read/write promises
(https://issues.rudder.io/issues/5172[#5172])
* Fixed: The ncf api hooks should not log unneeded things and need
cleanup (https://issues.rudder.io/issues/5221[#5221])
* Fixed: ncf post hooks, use http to reload techniques instead of https
(https://issues.rudder.io/issues/5210[#5210])
* Fixed: ncf techniques category.xml is not committed by ncf-builder post
hook on first technique creation.
(https://issues.rudder.io/issues/5197[#5197])

==== Documentation

* Fixed: Incomplete command to force inventory
(https://issues.rudder.io/issues/5205[#5205])
* Fixed: The documentation says there is no Rudder server packages for
RHEL 6 (https://issues.rudder.io/issues/5204[#5204])

==== Packaging

* Fixed: check-rudder-agent tries to use the stat command on AIX
(https://issues.rudder.io/issues/5198[#5198])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Lionel Le Folgoc

This software is in ``release candidate'' status and contains multiple
bug fixes since last beta (2.11.0~beta2) .

If no major bugs are found, a ``final'' release of 2.11.0 will be
released next week.

== Rudder 2.11.0~beta2 (2014-06-30)

=== Changes

==== Agent

* Update to CFEngine 3.6.0 release
(https://issues.rudder.io/issues/5077[#5077])

==== Techniques

* Integrate ncf-builder in Rudder
(https://issues.rudder.io/issues/2114[#2114])

==== System integration

* Add rudder-plugin script to manage Rudder plugins
(https://issues.rudder.io/issues/4989[#4989])

==== Techniques

* Only copy ``tools'' that are required for each platform
(https://issues.rudder.io/issues/5108[#5108])

==== Techniques - Sys & init promise

* Deprecate Debian 5 support as a Rudder server
(https://issues.rudder.io/issues/5104[#5104])

=== Bug fixes

==== Packaging

* Fixed: Use of a wrong conditional to detect if we are building on sles
in several package specfile
(https://issues.rudder.io/issues/5174[#5174])
* Fixed: rudder-server-root package description is incorrect
(https://issues.rudder.io/issues/5159[#5159])
* Fixed: rudder-agent package fails to backup rudder-server-roles.conf
to /var/archives during installation
(https://issues.rudder.io/issues/5124[#5124])
* Fixed: Remove an unneeded patch in rudder-jetty
(https://issues.rudder.io/issues/5102[#5102])
* Fixed: Add missing dependencies: which
(https://issues.rudder.io/issues/5066[#5066]), bc
(https://issues.rudder.io/issues/5064[#5064]), postgresql
(https://issues.rudder.io/issues/5076[#5076])

==== Techniques - Sys & init promise

* Fixed: A typo in component-check.cf prevent agent starting on initial
promises (https://issues.rudder.io/issues/5143[#5143])
* Fixed: In split architecture, the initial promises don’t send
inventories to the proper endpoint
(https://issues.rudder.io/issues/5120[#5120])
* Fixed: Promises generated generated for server roles are not correct
and are missing from initial promises
(https://issues.rudder.io/issues/5117[#5117])
* Fixed: Authorized networks in split environment, does not allow
inventory sending
(https://issues.rudder.io/issues/5087[#5087])

==== System integration

* Fixed: The 2.11 rudder-webapp package is missing a link on rudder-init
(rudder-init.sh)
(https://issues.rudder.io/issues/5145[#5145])
* Fixed: rudder-init does not run all required bundles to set up a
policy server (in particular rsyslog config is not correct)
(https://issues.rudder.io/issues/5098[#5098])
* Fixed: Typo in a sed command in rudder-init
(https://issues.rudder.io/issues/5067[#5067])

==== Webapp - Node management

* Fixed: Rudder role is not displayed in the web interface if a node is
a server component but neither relay nor root server
(https://issues.rudder.io/issues/5092[#5092])
* Fixed: Typo in server roles display, parenthesis at the end
(https://issues.rudder.io/issues/5073[#5073])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Cédric Jardin
* Lionel Le Folgoc
* Daniel Stan

We have found a bug in the distributed architecture
(https://issues.rudder.io/issues/5189), if you want to use
it you will have to run the following procedure on your `rudder-web'
server

....
cd /var/rudder/configuration-repository/techniques
wget https://github.com/Normation/rudder-techniques/pull/435.patch 
patch -p2 < 435.patch
git commit -am "Fix bug #5189"
touch /opt/rudder/etc/force_technique_reload
service rudder-jetty restart
....

This software is in beta status and contains several new features but we
have tested it and believe it to be free of any critical bugs. The use
on production systems is not encouraged at this time and is at your own
risk. However, we do encourage testing, and welcome all and any
feedback!

== Rudder 2.11.0~beta1 (2014-06-16)

=== Changes

==== Webapp - Display, home page

* Add a ``quick search'' box for nodes at the top right of the web
interface (https://issues.rudder.io/issues/5052[#5052])
* Data in Rudder web interface table can now be refreshed
(https://issues.rudder.io/issues/4793[#4793])
* Data in Rudder web interface table is transferred asynchronously in a
more lightweight format (JSON)
(https://issues.rudder.io/issues/4770[#4770])
* Add links to Directives in the Rule page
(https://issues.rudder.io/issues/4718[#4718])

==== Agent

* Upgrade to CFEngine 3.6 in rudder-agent
(https://issues.rudder.io/issues/4798[#4798])
* Upgrade FusionInventory to version 2.3.6 on rudder-agent (all
platforms) (https://issues.rudder.io/issues/4767[#4767])
* Compress inventories before sending to the server using gzip
(https://issues.rudder.io/issues/4790[#4790])
* User should be able to use https for agent / server exchange
(inventories) (https://issues.rudder.io/issues/4746[#4746])
* Adapt ``/bin/date'' command to use options available on all OSes in
system promises
(https://issues.rudder.io/issues/4967[#4967])

==== Inventory (webapp, Fusion)

* Display and use System Manufacturer/Model from nodes inventory in
Rudder (https://issues.rudder.io/issues/4501[#4501])
* Make run-inventory able to run using a system instance of fusion
inventory if no Rudder instance is available
(https://issues.rudder.io/issues/4926[#4926])

==== System integration

* Allow splitting Rudder into independent role-based entities
(https://issues.rudder.io/issues/4928[#4928],
(https://issues.rudder.io/issues/4628[#4628],
(https://issues.rudder.io/issues/4654[#4654],
(https://issues.rudder.io/issues/4993[#4993])
* Add logs of package install actions for debug
(https://issues.rudder.io/issues/5018[#5018])
* Remove /opt/rudder/jetty7/javadoc files
(https://issues.rudder.io/issues/4870[#4870])

==== Webapp - Administration

* Rudder standard installation should only include an admin user by
default (https://issues.rudder.io/issues/4902[#4902])
* Make writing reports in all.log configurable from Rudder
administration page
(https://issues.rudder.io/issues/4810[#4810])

==== Performance and scalability

* Optimize promise generation algorithm: Rudder variables lookup
(https://issues.rudder.io/issues/4778[#4778])

==== Architecture - Dependencies

* Update Specs2 version
(https://issues.rudder.io/issues/4854[#4854])

=== Release notes

Special thanks go out to the following individuals who invested time,
patience, testing, patches or bug reports to make this version of Rudder
better:

* Cédric Cabessa
* Christope Nowicki

This software is in beta status and contains several new features but we
have tested it and believe it to be free of any critical bugs. The use
on production systems is not encouraged at this time and is at your own
risk. However, we do encourage testing, and welcome all and any
feedback!
